# Benchmarking Results from Classification and Regression

#### Set Up

In [1]:
import pandas as pd
import numpy as np
import site
import os

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from contextlib import nullcontext

import random

from unicodedata import bidirectional

### Utility Classes and Functions

In [3]:
def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

# Datasets
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.T[idx]

def make_cumulative_targets(y_int, K):
    y = y_int.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def decode_ordinal(probs, thr=0.5):
    return (probs >= thr).sum(axis=1)

# Models
class OrdinalHeadCORN(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.fc = nn.Linear(in_dim, K-1)

    def forward(self, h):
        return self.fc(h)


class OrdinalHeadCORAL(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.w = nn.Linear(in_dim, 1, bias=False)
        self._beta = nn.Parameter(torch.zeros(K-1))
        self.softplus = nn.Softplus()

    def forward(self, h):
        base = self.w(h)
        deltas = self.softplus(self._beta)
        b = torch.cumsum(deltas, dim=0)
        return base - b



class RNNHead(nn.Module):
    # Shared head:
    #   - RNN stack (LSTM/GRU, uni/bi)
    #   - BatchNorm + Dense(32, ReLU) + Dropout
    #   - Output layer (1 unit): linear (regression) or logits (classification)
    def __init__(self, input_size, rnn_type='LSTM', bidirectional=False, problem_type='classification',
                 n_classes=6, ordinal_head='coral', hidden1=128, hidden2=64, num_layers=1,
                 inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
        super().__init__()
        self.problem_type = problem_type
        self.bidirectional = bidirectional
        self.rnn_type = rnn_type.upper()
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.num_layers = int(num_layers)
        self.hidden1 = int(hidden1)
        self.hidden2 = int(hidden2)

        if self.num_layers not in (1, 2):
            raise ValueError("num_layers must be 1 or 2")

        rnn_cls = {'LSTM': nn.LSTM, 'GRU': nn.GRU}[('GRU' if 'GRU' in self.rnn_type else 'LSTM')]

        self.rnn1 = rnn_cls(
            input_size=input_size, hidden_size=self.hidden1, num_layers=1,
            batch_first=True, dropout=0.0, bidirectional=bidirectional
        )

        self.inter_rnn_drop = nn.Dropout(float(inter_rnn_drop))

        self.rnn2 = None
        if self.num_layers == 2:
            self.rnn2 = rnn_cls(
                input_size=self.hidden1*(2 if bidirectional else 1), hidden_size=self.hidden2, num_layers=1,
                batch_first=True, dropout=0.0, bidirectional=bidirectional
            )
            feat_dim = self.hidden2*(2 if bidirectional else 1)
        else:
            feat_dim = self.hidden1*(2 if bidirectional else 1)

        if use_layernorm:
            self.bn = nn.LayerNorm(feat_dim)
        else:
            self.bn = nn.BatchNorm1d(feat_dim)
        self.fc = nn.Linear(feat_dim, 32)
        self.drop = nn.Dropout(float(dropout))
        if self.problem_type == 'multiclass':
            head = self.ordinal_head.lower() if isinstance(self.ordinal_head, str) else 'coral'
            if head == 'corn':
                self.out = OrdinalHeadCORN(32, self.n_classes)
            else:
                self.out = OrdinalHeadCORAL(32, self.n_classes)
        else:
            self.out = nn.Linear(32, 1)

    def forward(self, x):
        # x: [B, T, F]
        out, _ = self.rnn1(x)
        if self.num_layers == 2:
            out = self.inter_rnn_drop(out)   # inter-layer dropout (sequence-wise)
            out, _ = self.rnn2(out)
        # take last timestep: [B, T, H] -> [B, H]
        out = out[:, -1, :]
        out = self.bn(out)
        out = F.relu(self.fc(out))
        out = self.drop(out)
        out = self.out(out)  # shape [B,1]
        return out  # regression: raw; classification: logits


def build_model(input_shape, model_type='LSTM', problem_type='regression', n_classes=6, ordinal_head='coral',
                hidden1=128, hidden2=64, num_layers=2, inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
    seq_len, n_features = input_shape
    model_type = model_type.upper()
    kwargs = dict(
        problem_type=problem_type,
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        hidden1=hidden1,
        hidden2=hidden2,
        num_layers=num_layers,
        inter_rnn_drop=inter_rnn_drop,
        dropout=dropout,
        use_layernorm=use_layernorm,
    )
    if model_type == 'LSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=False, **kwargs)
    elif model_type == 'BILSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=True, **kwargs)
    elif model_type == 'GRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=False, **kwargs)
    elif model_type == 'BIGRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=True, **kwargs)
    else:
        raise ValueError("Model type must be one of: ['LSTM','BiLSTM','GRU','BiGRU']")

# Early Stopping (PyTorch)
class EarlyStopper:
    def __init__(self, patience=15, min_delta=0.0, restore_best=True):
        self.patience = patience
        self.min_delta = min_delta
        self.restore_best = restore_best
        self.best_loss = float('inf')
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        improved = (self.best_loss - val_loss) > self.min_delta
        if improved:
            self.best_loss = val_loss
            self.counter = 0
            if self.restore_best:
                # Deep copy state dict
                self.best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            self.counter += 1
        return self.counter >= self.patience

    def restore(self, model):
        if self.restore_best and self.best_state is not None:
            model.load_state_dict(self.best_state)

In [4]:
def edge_labels_from_edges(edges, decimals=1):
    labels = []
    C = len(edges) - 1
    for i in range(C):
        lo, hi = edges[i], edges[i+1]
        if i == 0:
            labels.append(f"≤ {hi*100:.{decimals}f}%")
        elif i == C - 1:
            labels.append(f"> {lo*100:.{decimals}f}%")
        else:
            labels.append(f"({lo*100:.{decimals}f}%,{hi*100:.{decimals}f}%]")
    return labels

def pct_return(series, h):
    return series.shift(-h) / series - 1.0

def safe_quantile_edges(x, n_classes=6):
    qs = np.linspace(0, 1, n_classes + 1)
    edges = np.quantile(x, qs)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = np.nextafter(edges[i-1], np.inf)
    return edges

def bucketize_with_edges(x, edges):
    inner = edges[1:-1]
    return np.digitize(x, inner, right=True).astype(int)

@torch.no_grad()
def collect_logits(model, loader, device):
    model.eval()
    chunks = []
    for xb, _ in loader:
        xb = xb.to(device)
        chunks.append(model(xb).detach().cpu())
    return torch.cat(chunks, dim=0)

def find_taus_per_threshold(Z_val, y_val_idx, grid=np.linspace(0, 1, 100)):
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.numpy()
    P_val = 1.0 / (1.0 + np.exp(-Z_val))
    P_rep = monotone_repair_numpy(P_val)
    K_1 = P_rep.shape[1]
    best_taus = np.full(K_1, 0.5, dtype=np.float32)
    for k in range(K_1):
        best_f1, best_tau = -1.0, 0.5
        for tau in grid:
            y_hat = decode_ordinal_with_taus(P_rep, taus_override={k: tau})
            f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
            if f1 > best_f1:
                best_f1, best_tau = f1, tau
        best_taus[k] = best_tau
    return best_taus

def monotone_repair_numpy(P):
    P = np.asarray(P).copy()
    for k in range(P.shape[1] - 2, -1, -1):
        P[:, k] = np.maximum(P[:, k], P[:, k+1])
    return P

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def ordinal_to_class_probs(P_rep):
    N, K_1 = P_rep.shape
    K = K_1 + 1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:, 0] = 1.0 - P_rep[:, 0]
    for c in range(1, K - 1):
        Pc[:, c] = np.clip(P_rep[:, c-1] - P_rep[:, c], 0.0, 1.0)
    Pc[:, K - 1] = P_rep[:, K_1 - 1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)


def best_threshold_from_val(y_true, y_scores, metric='f1', grid=None):
    """
    Sweep probability thresholds on validation scores to maximize a metric.
    metric can be 'f1', 'mcc', 'accuracy', or a callable(y_true,y_pred)->float.
    Returns (best_threshold, best_metric_value).
    """
    y_true = np.asarray(y_true).astype(int)
    y_scores = np.asarray(y_scores).astype(float)
    if grid is None:
        grid = np.linspace(0.05, 0.95, 181)
    metric_fn = None
    if callable(metric):
        metric_fn = metric
    else:
        name = str(metric).lower()
        if name == 'f1':
            metric_fn = lambda yt, yp: f1_score(yt, yp, zero_division=0)
        elif name == 'mcc':
            metric_fn = lambda yt, yp: matthews_corrcoef(yt, yp)
        elif name in ('acc', 'accuracy'):
            metric_fn = lambda yt, yp: (yt == yp).mean()
        else:
            raise ValueError(f"Unsupported metric '{metric}'")
    best_thr = 0.5
    best_val = -np.inf
    for thr in grid:
        preds = (y_scores >= thr).astype(int)
        val = metric_fn(y_true, preds)
        if val > best_val + 1e-12 or (abs(val - best_val) <= 1e-12 and thr < best_thr):
            best_val = float(val)
            best_thr = float(thr)
    return best_thr, best_val

## Stock Prediction Pipeline

In [5]:
class StockPredictionPipeline:
    def __init__(self, df, feature_columns, model_type='LSTM', sequence_length=24, problem_type='regression', horizon_steps=1, n_classes=6, ordinal_head='coral', fixed_bucket_edges=None,
                 hidden1=256, hidden2=64, num_layers=1, inter_rnn_drop=0.0, dropout=0.4,
                 batch_size=32, learning_rate=7e-3, weight_decay=2e-3, lr_patience=7, lr_factor=0.5,
                 early_stopping_patience=20, max_epochs=20, use_layernorm=False, huber_delta=1.0, early_stopping_min_delta=0.0):
        self.df = df.copy()
        self.feature_columns = feature_columns
        self.model_type = model_type
        self.sequence_length = sequence_length
        self.problem_type = problem_type
        self.horizon_steps = horizon_steps
        self.results = []
        self.loss_curves = []
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.hidden1 = hidden1
        self.hidden2 = hidden2
        self.num_layers = num_layers
        self.inter_rnn_drop = inter_rnn_drop
        self.dropout = dropout
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.lr_patience = lr_patience
        self.lr_factor = lr_factor
        self.early_stopping_patience = early_stopping_patience
        self.max_epochs = max_epochs
        self.use_layernorm = use_layernorm
        self.huber_delta = huber_delta
        self.early_stopping_min_delta = early_stopping_min_delta
        self.fixed_bucket_edges = None
        if fixed_bucket_edges is not None:
            edges = np.asarray(fixed_bucket_edges, dtype=float)
            if edges.ndim != 1:
                raise ValueError("fixed_bucket_edges must be a 1D sequence of monotonically increasing numbers")
            if edges.size < 2:
                raise ValueError("fixed_bucket_edges must contain at least two values")
            if np.any(np.diff(edges) <= 0):
                raise ValueError("fixed_bucket_edges must be strictly increasing")
            self.n_classes = int(edges.size - 1)
            self.fixed_bucket_edges = edges

        # Validate
        self._validate_inputs()

        # Device & precision
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.mixed_precision = torch.cuda.is_available()

        print(f"Pipeline initialized for a '{self.problem_type}' problem "
              f"with horizon {self.horizon_steps} steps. Device: {self.device}")

    def _validate_inputs(self):
        missing_cols = [col for col in self.feature_columns if col not in self.df.columns]
        if missing_cols:
            raise ValueError(f"Missing feature columns: {missing_cols}")

        if 'close' not in self.df.columns and 'close_price' not in self.df.columns:
            raise ValueError("No 'close' or 'close_price' column found in data")

        valid_models = ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']
        if self.model_type not in valid_models:
            raise ValueError(f"Model type must be one of: {valid_models}")

        if self.problem_type not in ['regression', 'classification', 'multiclass']:
            raise ValueError("Problem type must be 'regression', 'classification', or 'multiclass'")

    def create_target_variable(self, company_data):
        company_data = company_data.copy()
        price_col = 'close' if 'close' in company_data.columns else 'close_price'
        if 'date' in company_data.columns:
            company_data = company_data.sort_values('date')
            
        h = self.horizon_steps

        company_data['target_regression'] = (
            np.log(company_data[price_col].shift(-h)) - np.log(company_data[price_col])
        )
        company_data['target_direction'] = (company_data['target_regression'] > 0).astype(int)
        company_data['ret_h'] = pct_return(company_data[price_col], h)
        if self.problem_type == 'multiclass':
            company_data = company_data.dropna(subset=['ret_h'])
        else:
            company_data = company_data.dropna()
        return company_data

    def create_sequences(self, features, *targets):
        X = []
        y_sequences = [[] for _ in targets]
        for i in range(self.sequence_length, len(features)):
            X.append(features[i-self.sequence_length:i])
            for j, target in enumerate(targets):
                y_sequences[j].append(target[i])
        return (np.array(X),) + tuple(np.array(y) for y in y_sequences)

    def _train_one_epoch(self, model, loader, optimizer, loss_fn, scaler):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)

            optimizer.zero_grad(set_to_none=True)

            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                loss = loss_fn(logits, yb)

            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * xb.size(0)

        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch(self, model, loader, loss_fn):
        model.eval()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * xb.size(0)
        return total_loss / len(loader.dataset)

    def _train_one_epoch_multiclass(self, model, loader, optimizer, scaler, *, pos_weight=None):
        model.train()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            optimizer.zero_grad(set_to_none=True)
            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                bces = []
                for k in range(logits.shape[1]):
                    w = None if pos_weight is None else pos_weight[k]
                    bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                    bces.append(bce_k)
                loss = torch.stack(bces).mean()
            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch_multiclass(self, model, loader, pos_weight=None):
        model.eval()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            logits = model(xb)
            bces = []
            for k in range(logits.shape[1]):
                w = None if pos_weight is None else pos_weight[k]
                bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                bces.append(bce_k)
            loss = torch.stack(bces).mean()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _predict(self, model, loader):
        model.eval()
        outs = []
        for xb, _ in loader:
            xb = xb.to(self.device)
            logits = model(xb).squeeze(1).detach().cpu().numpy()
            outs.append(logits)
        return np.concatenate(outs, axis=0)

    def build_model(self, input_shape):
        model = build_model(
            input_shape,
            model_type=self.model_type,
            problem_type=self.problem_type,
            n_classes=self.n_classes,
            ordinal_head=self.ordinal_head,
            hidden1=self.hidden1,
            hidden2=self.hidden2,
            num_layers=self.num_layers,
            inter_rnn_drop=self.inter_rnn_drop,
            dropout=self.dropout,
            use_layernorm=self.use_layernorm
        )
        return model.to(self.device)

    def process_company(self, company_name, company_data, sector):
        print(f"\nProcessing {company_name} ({sector})...")
        try:
            company_data = self.create_target_variable(company_data)

            # Min samples requirement (same heuristic)
            min_samples = self.sequence_length + 75 + self.horizon_steps
            if len(company_data) < min_samples:
                print(f"Insufficient data for {company_name} ({len(company_data)} < {min_samples}). Skipping...")
                return None

            if company_data[self.feature_columns].isnull().any().any():
                print(f"Missing values in features for {company_name}. Skipping...")
                return None

            features = company_data[self.feature_columns].values
            target_reg = company_data['target_regression'].values
            target_dir = company_data['target_direction'].values

            # Create sequences
            X_raw, y_reg, y_dir = self.create_sequences(features, target_reg, target_dir)

            # TimeSeriesSplit
            n_splits = min(5, len(X_raw) // 50)
            if n_splits < 3:
                print(f"Insufficient data for proper time series validation for {company_name}. Skipping...")
                return None

            tscv = TimeSeriesSplit(n_splits=n_splits)
            splits = list(tscv.split(X_raw))
            train_idx, test_idx = splits[-1]

            # Train/Val split (last 20% of train for val)
            val_size = int(0.2 * len(train_idx))
            if val_size == 0:
                print(f'Insufficient data for validation split for {company_name}. Skipping...')
                return None
            final_train_idx = train_idx[:-val_size]
            val_idx = train_idx[-val_size:]
            
            if self.horizon_steps > 1:
                print("Adjusting for multi-step horizon...")
                gap = self.horizon_steps
                if len(final_train_idx) > gap:
                    final_train_idx = final_train_idx[:-gap]  # drop last h labels from train
                if len(val_idx) > gap:
                    val_idx = val_idx[gap:]  # drop last h labels from val
            if len(final_train_idx) == 0 or len(val_idx) == 0:
                print(f'Insufficient data after horizon adjustment for {company_name}. Skipping...')
                return None

            X_train_raw, X_val_raw, X_test_raw = X_raw[final_train_idx], X_raw[val_idx], X_raw[test_idx]
            
            F = X_raw.shape[-1]
            feat_scaler = StandardScaler()
            X_train = feat_scaler.fit_transform(X_train_raw.reshape(-1, F)).reshape(X_train_raw.shape)
            X_val   = feat_scaler.transform(X_val_raw.reshape(-1, F)).reshape(X_val_raw.shape)
            X_test  = feat_scaler.transform(X_test_raw.reshape(-1, F)).reshape(X_test_raw.shape)

            if self.problem_type == 'multiclass':
                if 'ret_h' not in company_data.columns:
                    raise RuntimeError("Expected 'ret_h' for ordinal targets but it was missing.")
                ret_full = company_data['ret_h'].values
                ret_seq_full = ret_full[self.sequence_length:]

                ret_train = ret_seq_full[final_train_idx]
                ret_val = ret_seq_full[val_idx]
                ret_test = ret_seq_full[test_idx]

                if self.fixed_bucket_edges is not None:
                    edges = self.fixed_bucket_edges
                    if int(edges.shape[0] - 1) != self.n_classes:
                        raise ValueError("fixed_bucket_edges length must match n_classes+1")
                else:
                    edges = safe_quantile_edges(ret_train, n_classes=self.n_classes)
                edges = np.asarray(edges, dtype=float)
                K = int(edges.shape[0] - 1)
                label_names = edge_labels_from_edges(edges, decimals=1)

                y_bucket = bucketize_with_edges(ret_seq_full, edges).astype(np.int64)
                y_train = y_bucket[final_train_idx]
                y_val = y_bucket[val_idx]
                y_test = y_bucket[test_idx]

                T_train = make_cumulative_targets(y_train.astype(np.int64), K)
                T_val = make_cumulative_targets(y_val.astype(np.int64), K)
                T_test = make_cumulative_targets(y_test.astype(np.int64), K)

                train_ds = OrdinalSequenceDataset(X_train, T_train)
                val_ds = OrdinalSequenceDataset(X_val, T_val)
                test_ds = OrdinalSequenceDataset(X_test, T_test)

                train_loader = DataLoader(train_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                val_loader = DataLoader(val_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                test_loader = DataLoader(test_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)

                model = self.build_model((self.sequence_length, len(self.feature_columns)))

                pos_rate = T_train.mean(axis=0)
                pos_weight = (1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)
                pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float32).to(self.device)

                optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
                scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
                early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
                scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

                max_epochs = self.max_epochs
                best_val = float('inf')
                epochs_trained = 0
                company_loss_rows = []

                for epoch in range(1, max_epochs + 1):
                    train_loss = self._train_one_epoch_multiclass(model, train_loader, optimizer, scaler, pos_weight=pos_weight_tensor)
                    val_loss = self._eval_one_epoch_multiclass(model, val_loader, pos_weight=pos_weight_tensor)
                    scheduler.step(val_loss)
                    stop = early_stopper.step(val_loss, model)
                    epochs_trained = epoch

                    row = {
                        'company': company_name,
                        'sector': sector,
                        'model_type': self.model_type,
                        'problem_type': self.problem_type,
                        'sequence_length': self.sequence_length,
                        'horizon_steps': self.horizon_steps,
                        'epoch': epoch,
                        'train_loss': float(train_loss),
                        'val_loss': float(val_loss),
                        'train_samples': len(X_train),
                        'val_samples': len(X_val),
                        'test_samples': len(X_test),
                    }

                    company_loss_rows.append(row)
                    self.loss_curves.append(row)

                    if epoch % 10 == 0 or stop:
                        print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                    if stop:
                        break

                early_stopper.restore(model)

                Z_val = collect_logits(model, val_loader, self.device)
                taus = find_taus_per_threshold(Z_val, y_val.astype(np.int64))
                P_cum_val = torch.sigmoid(Z_val).cpu().numpy()
                P_rep_val = monotone_repair_numpy(P_cum_val)
                P_class_val = ordinal_to_class_probs(P_rep_val)
                mid_cut = (K // 2)
                y_val_dir = (y_val >= mid_cut).astype(int)
                prob_val_up = P_class_val[:, mid_cut:].sum(axis=1)
                dir_thr, dir_thr_score = best_threshold_from_val(y_val_dir, prob_val_up, metric='mcc')

                Z_test = collect_logits(model, test_loader, self.device)
                P_cum = torch.sigmoid(Z_test).cpu().numpy()
                P_rep = monotone_repair_numpy(P_cum)
                P_class = ordinal_to_class_probs(P_rep)

                y_pred_labels = decode_ordinal_with_taus(P_rep, taus=taus)
                y_true_labels = y_test

                labels = list(range(K))
                cm_counts = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
                cm_norm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels, normalize='true')

                micro_acc = (y_true_labels == y_pred_labels).mean()
                macro_f1 = f1_score(y_true_labels, y_pred_labels, average='macro', zero_division=0)

                ret_seq_train = ret_seq_full[final_train_idx].astype(np.float32)
                mu_c = np.array([
                    ret_seq_train[y_train == c].mean() if np.any(y_train == c) else 0.0
                    for c in range(K)
                ], dtype=np.float32)

                expected_ret = (P_class * mu_c[None, :]).sum(axis=1)
                expected_ret_mean = float(expected_ret.mean())

                prob_test_up = P_class[:, mid_cut:].sum(axis=1)
                y_true_dir = (y_true_labels >= mid_cut).astype(int)
                y_pred_dir = (prob_test_up >= dir_thr).astype(int)
                precision = precision_score(y_true_dir, y_pred_dir, zero_division=0)
                recall = recall_score(y_true_dir, y_pred_dir, zero_division=0)
                f1 = f1_score(y_true_dir, y_pred_dir, zero_division=0)
                mcc = matthews_corrcoef(y_true_dir, y_pred_dir)
                directional_accuracy = (y_true_dir == y_pred_dir).mean()

                result = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'horizon_steps': self.horizon_steps,
                    'macro_f1': macro_f1,
                    'micro_accuracy': micro_acc,
                    'expected_return_mean': expected_ret_mean,
                    'mse': np.nan,
                    'mae': np.nan,
                    'r2': np.nan,
                    'mcc': mcc,
                    'f1': f1,
                    'precision': precision,
                    'recall': recall,
                    'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                    'n_samples': int(X_raw.shape[0]),
                    'train_samples': int(X_train.shape[0]),
                    'val_samples': int(X_val.shape[0]),
                    'test_samples': int(X_test.shape[0]),
                    'epochs_trained': epochs_trained
                }
                result['confusion_matrix'] = cm_counts.tolist()
                result['confusion_matrix_normalized'] = cm_norm.tolist()
                result['bucket_edges'] = edges.tolist()
                result['bucket_labels'] = label_names
                result['taus'] = taus.astype(float).tolist()
                result['direction_threshold'] = dir_thr
                result['direction_threshold_metric'] = dir_thr_score

                print(f"  Multiclass -> Micro Acc: {micro_acc:.4f}, Macro F1: {macro_f1:.4f}, Expected Return: {expected_ret_mean:.6f}")
                print(f"  Directional threshold -> τ={dir_thr:.3f} (val F1={dir_thr_score:.4f})")

                del model
                torch.cuda.empty_cache()
                return result

            if self.problem_type == 'regression':
                y_train, y_val, y_test = y_reg[final_train_idx], y_reg[val_idx], y_reg[test_idx]
                target_scaler = StandardScaler()
                y_train_scaled = target_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()
                y_val_scaled   = target_scaler.transform(y_val.reshape(-1, 1)).flatten()
                train_target, val_target = y_train_scaled, y_val_scaled
            else:
                y_train, y_val, y_test = y_dir[final_train_idx], y_dir[val_idx], y_dir[test_idx]
                train_target, val_target = y_train, y_val
                target_scaler = None

            # class balance note
            if self.problem_type == 'classification':
                class_ratio = np.mean(y_train)
                if class_ratio < 0.1 or class_ratio > 0.9:
                    print(f"Severe class imbalance for {company_name} ({class_ratio:.3f}). Consider using class weights.")

            # datasets & loaders
            train_ds = SequenceDataset(X_train, train_target)
            val_ds   = SequenceDataset(X_val,   val_target)
            test_ds  = SequenceDataset(X_test,  y_test)

            train_bs = min(self.batch_size, len(train_ds))
            if train_bs < 2:
                print(f'Insufficient training samples for {company_name} (train size={len(train_ds)}). Skipping...')
                return None
            if len(train_ds) % train_bs == 1 and train_bs > 2:
                train_bs -= 1  # avoid batch size 1 for BatchNorm
            val_bs = min(self.batch_size, len(val_ds))
            test_bs = min(self.batch_size, len(test_ds))

            train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=False,  drop_last=False, num_workers=0)
            val_loader   = DataLoader(val_ds,   batch_size=val_bs,   shuffle=False, drop_last=False, num_workers=0)
            test_loader  = DataLoader(test_ds,  batch_size=test_bs,  shuffle=False, drop_last=False, num_workers=0)

            # build model
            model = self.build_model((self.sequence_length, len(self.feature_columns)))

            # loss functions
            if self.problem_type == 'regression':
                loss_fn = nn.HuberLoss(delta=self.huber_delta)
            else:
                # use BCEWithLogitsLoss for numerical stability (logits input)
                loss_fn = nn.BCEWithLogitsLoss()

            # optimizer & scheduler
            optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
            scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
            early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
            scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

            # training loop
            max_epochs = self.max_epochs
            best_val = float('inf')
            epochs_trained = 0
            company_loss_rows = []  

            for epoch in range(1, max_epochs + 1):
                train_loss = self._train_one_epoch(model, train_loader, optimizer, loss_fn, scaler)
                val_loss = self._eval_one_epoch(model, val_loader, loss_fn)
                scheduler.step(val_loss)
                stop = early_stopper.step(val_loss, model)
                epochs_trained = epoch

                
                row = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'sequence_length': self.sequence_length,
                    'horizon_steps': self.horizon_steps,
                    'epoch': epoch,
                    'train_loss': float(train_loss),
                    'val_loss': float(val_loss),
                    'train_samples': len(X_train),
                    'val_samples': len(X_val),
                    'test_samples': len(X_test),
                }
                
                company_loss_rows.append(row)
                self.loss_curves.append(row)

                if epoch % 10 == 0 or stop:
                    print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                if stop:
                    break

            # restore best model weights (like Keras restore_best_weights=True)
            early_stopper.restore(model)

            # summarize train/val loss for overfitting checks
            best_train_loss = np.nan
            best_val_loss = np.nan
            final_train_loss = np.nan
            final_val_loss = np.nan
            if company_loss_rows:
                best_val_loss = min(r['val_loss'] for r in company_loss_rows)
                best_train_loss = min(r['train_loss'] for r in company_loss_rows)
                final_train_loss = company_loss_rows[-1]['train_loss']
                final_val_loss = company_loss_rows[-1]['val_loss']

            # predictions
            y_pred_raw = self._predict(model, test_loader)  # raw/regression or logits

            if self.problem_type == 'regression':
                y_pred_unscaled = target_scaler.inverse_transform(y_pred_raw.reshape(-1,1)).flatten() if target_scaler is not None else y_pred_raw
                mse = mean_squared_error(y_test, y_pred_unscaled)
                mae = mean_absolute_error(y_test, y_pred_unscaled)
                r2  = r2_score(y_test, y_pred_unscaled)

                # directional metrics (derived)
                y_test_dir = (y_reg[test_idx] > 0).astype(int)
                y_pred_dir = (y_pred_unscaled > 0).astype(int)
            else:
                # logits -> probs via sigmoid -> learn best threshold on VAL
                val_logits = self._predict(model, val_loader)
                val_probs = 1.0 / (1.0 + np.exp(-val_logits))
                best_thr, best_thr_score = best_threshold_from_val(y_val, val_probs, metric='mcc')
                val_pred_dir = (val_probs >= best_thr).astype(int)
                val_precision = precision_score(y_val, val_pred_dir, zero_division=0)
                val_recall = recall_score(y_val, val_pred_dir, zero_division=0)
                val_f1 = f1_score(y_val, val_pred_dir, zero_division=0)
                val_mcc = matthews_corrcoef(y_val, val_pred_dir)
                val_directional_accuracy = (y_val == val_pred_dir).mean()
                probs = 1.0 / (1.0 + np.exp(-y_pred_raw))
                y_pred_dir = (probs >= best_thr).astype(int)
                y_test_dir = y_test
                mse = mae = r2 = np.nan

            precision = precision_score(y_test_dir, y_pred_dir, zero_division=0)
            recall    = recall_score(y_test_dir, y_pred_dir, zero_division=0)
            f1        = f1_score(y_test_dir, y_pred_dir, zero_division=0)
            mcc       = matthews_corrcoef(y_test_dir, y_pred_dir)
            directional_accuracy = np.mean(y_test_dir == y_pred_dir)

            result = {
                'company': company_name,
                'sector': sector,
                'model_type': self.model_type,
                'problem_type': self.problem_type,
                'horizon_steps': self.horizon_steps,
                'mse': mse,
                'mae': mae,
                'r2': r2,
                'mcc': mcc,
                'f1': f1,
                'precision': precision,
                'recall': recall,
                'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                'n_samples': int(X_raw.shape[0]),
                'train_samples': int(X_train.shape[0]),
                'val_samples': int(X_val.shape[0]),
                'test_samples': int(X_test.shape[0]),
                'epochs_trained': epochs_trained
            }
            if self.problem_type == 'classification':
                result['best_threshold'] = best_thr
                result['best_threshold_metric'] = best_thr_score

            if self.problem_type == 'regression':
                print(f"  Regression -> MSE: {mse:.6f}, MAE: {mae:.6f}, R²: {r2:.4f}")
            elif self.problem_type == 'classification':
                print(f"  Classification -> best τ={best_thr:.3f} (val F1={best_thr_score:.4f})")
            print(f"  Directional -> Accuracy: {directional_accuracy:.4f}, MCC: {mcc:.4f}, F1: {f1:.4f}")

            # explicit cleanup (PyTorch handles this, but keeps parity with Enrique2025)
            del model
            torch.cuda.empty_cache()

            return result

        except Exception as e:
            print(f"Error processing {company_name}: {str(e)}")
            torch.cuda.empty_cache()
            return None

    def run_pipeline(self):
        company_col = None
        for col_name in ['ticker', 'company', 'symbol']:
            if col_name in self.df.columns:
                company_col = col_name
                break
        if company_col is None:
            company_col = self.df.columns[0]
            print(f"Warning: Using '{company_col}' as company identifier column")

        companies = self.df[company_col].unique()
        print(f"Processing {len(companies)} companies with {self.model_type} model...")
        print(f"Problem type: {self.problem_type}")
        print(f"Sequence length: {self.sequence_length}")
        print(f"Features: {self.feature_columns}")

        successful_companies = 0
        for i, company in enumerate(companies, 1):
            print(f"\n[{i}/{len(companies)}] Processing {company}...")
            company_data = self.df[self.df[company_col] == company].copy()
            sector = company_data['sector'].iloc[0] if 'sector' in company_data.columns else 'Unknown'
            result = self.process_company(company, company_data, sector)
            if result:
                self.results.append(result)
                successful_companies += 1

        print(f"\n{'='*80}")
        print(f"Pipeline completed: {successful_companies}/{len(companies)} companies processed successfully")
        print(f"{'='*80}")

        if self.results:
            self.results_df = pd.DataFrame(self.results)
            return self.results_df
        else:
            print("No companies were processed successfully!")
            return pd.DataFrame()


    def analyze_results(self):
        if not hasattr(self, 'results_df') or self.results_df.empty:
            print("No results to analyze!")
            return None

        df = self.results_df
        analysis = {}

        print("" + "="*80)
        print("STOCK PREDICTION PIPELINE RESULTS")
        print("="*80)
        print(f"Model: {self.model_type} | Problem: {self.problem_type}")
        print(f"Companies analyzed: {len(df)}")
        print(f"Average samples per company: {df['n_samples'].mean():.0f}")

        print("" + "="*50)
        print("OVERALL PERFORMANCE")
        print("="*50)
        if self.problem_type == 'regression':
            print(f"Mean Squared Error:     {df['mse'].mean():.6f} (±{df['mse'].std():.6f})")
            print(f"Mean Absolute Error:    {df['mae'].mean():.6f} (±{df['mae'].std():.6f})")
            print(f"R² Score:              {df['r2'].mean():.4f} (±{df['r2'].std():.4f})")
        if self.problem_type == 'multiclass' and 'micro_accuracy' in df.columns:
            print(f"Micro Accuracy:         {df['micro_accuracy'].mean():.4f} (±{df['micro_accuracy'].std():.4f})")
            print(f"Macro F1 Score:         {df['macro_f1'].mean():.4f} (±{df['macro_f1'].std():.4f})")
            if 'expected_return_mean' in df.columns:
                print(f"Expected Return:        {df['expected_return_mean'].mean():.6f} (±{df['expected_return_mean'].std():.4f})")

        print(f"Directional Accuracy:   {df['directional_accuracy'].mean():.4f} (±{df['directional_accuracy'].std():.4f})")
        print(f"Matthews Correlation:   {df['mcc'].mean():.4f} (±{df['mcc'].std():.4f})")
        print(f"F1 Score:              {df['f1'].mean():.4f} (±{df['f1'].std():.4f})")
        print(f"Precision:             {df['precision'].mean():.4f} (±{df['precision'].std():.4f})")
        print(f"Recall:                {df['recall'].mean():.4f} (±{df['recall'].std():.4f})")

        if self.problem_type == 'multiclass' and 'expected_return_mean' in df.columns:
            print("" + "="*50)
            print("TOP 10 BY EXPECTED RETURN (mean)")
            print("="*50)
            top_er = df.nlargest(10, 'expected_return_mean')
            for _, row in top_er.iterrows():
                print(f"{row['company']:<20} | {row['sector']:<15} | E[r]_mean: {row['expected_return_mean']:.4e} | Macro-F1: {row['macro_f1']:.3f}")

        if 'sector' in df.columns and df['sector'].nunique() > 1:
            print("" + "="*50)
            print("PERFORMANCE BY SECTOR")
            print("="*50)
            sector_stats = df.groupby('sector').agg({
                'directional_accuracy': ['mean', 'std', 'count'],
                'mcc': ['mean', 'std'],
                'r2': 'mean' if self.problem_type == 'regression' else lambda x: np.nan,
                'mae': 'mean' if self.problem_type == 'regression' else lambda x: np.nan
            }).round(4)
            sector_stats.columns = ['_'.join(col).strip() if col[1] else col[0] for col in sector_stats.columns]
            sector_stats = sector_stats.sort_values('directional_accuracy_mean', ascending=False)
            for sector, row in sector_stats.iterrows():
                print(f"{sector:<20} | Acc: {row['directional_accuracy_mean']:.3f}±{row['directional_accuracy_std']:.3f} | "
                      f"MCC: {row['mcc_mean']:.3f} | Companies: {int(row['directional_accuracy_count'])}")

        print("" + "="*50)
        print("TOP 10 PERFORMERS (by Directional Accuracy)")
        print("="*50)
        top_performers = df.nlargest(10, 'directional_accuracy')
        for _, row in top_performers.iterrows():
            print(f"{row['company']:<20} | {row['sector']:<15} | "
                  f"Acc: {row['directional_accuracy']:.3f} | MCC: {row['mcc']:.3f}")

        return analysis

    def save_results(self, results, output_dir='results/benchmarking'):
        if results is not None and not results.empty:
            model_name = self.model_type

            if self.problem_type == 'regression':
                out_dir = os.path.join(output_dir, 'regression')
            elif self.problem_type == 'classification':
                out_dir = os.path.join(output_dir, 'classification')
            else:
                out_dir = os.path.join(output_dir, 'multiclass')

            os.makedirs(out_dir, exist_ok=True)

            output_path = os.path.join(out_dir, f"{model_name}.csv")

            results.to_csv(output_path, index=False)
            print(f"Results saved to {output_path}")
        else:
            print("No results to save.")
            
    def get_loss_curves_df(self):
        if not self.loss_curves:
            print("No loss curves logged yet.")
            return pd.DataFrame()
        return pd.DataFrame(self.loss_curves)

    def save_loss_curves(self, out_path='results/benchmarking/'):
        df = self.get_loss_curves_df()
        if df.empty:
            print("No loss curves to save.")
            return
        if self.problem_type == 'regression':
            out_path = os.path.join(out_path, 'regression', f"{self.model_type}_loss_curves.csv")
        elif self.problem_type == 'classification':
            out_path = os.path.join(out_path, 'classification', f"{self.model_type}_loss_curves.csv")
        else:
            out_path = os.path.join(out_path, 'multiclass', f"{self.model_type}_loss_curves.csv")
            
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        
        df.to_csv(out_path, index=False)
        print(f"Loss curves saved to {out_path}")

    def get_feature_importance_analysis(self):
        print("Feature importance analysis not implemented yet.")
        print("Consider implementing SHAP values or permutation importance for better insights.")
        return None

## Data Preparation

In [6]:
master_df = pd.read_parquet('../data/dataset/ta_nlp_sector.parquet')

In [7]:
master_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [8]:
master_df

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1464.800169,NaN,NaN
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1481.232189,NaN,0.006548
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.755774,NaN,NaN,NaN,1502.627054,NaN,0.006476
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.562466,NaN,NaN,NaN,1506.971629,NaN,0.008604
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,22.507443,NaN,NaN,NaN,1503.735325,NaN,0.012007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108587,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.01430,58.978638,3101.328695,-0.007883,0.005228
108588,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.94445,59.026797,3102.507723,-0.016661,0.002030
108589,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.86875,59.097896,3128.753695,-0.017629,0.004873
108590,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.83190,59.138363,3141.201722,-0.008376,0.006185
108591,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.80760,59.188831,3136.813139,-0.001766,0.007085

In [9]:
columns_to_check = [
                    'sentiment',
                    
                    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                    'emotion_surprize_pct', 
                    
                    'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                    
                    'stance_label', 'stance_score', 
                    
                    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                    'finbert_neutral', 
                    
                    'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                    'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                    'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                    
                    'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                    'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                    'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                    'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
                ]

print(f"Initial master_df shape: {master_df.shape}")

master_df = master_df.dropna(subset=columns_to_check)

print(f"After dropping NaNs in selected columns, master_df shape: {master_df.shape}")

master_df.reset_index(drop=True, inplace=True)

display(master_df)

Initial master_df shape: (108592, 80)
After dropping NaNs in selected columns, master_df shape: (104476, 80)

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,69.613815,119292600.0,AAPL,80.708033,84.949698,...,-0.913108,-0.181794,-0.731314,27.619972,63.948320,61.465736,58.983152,1484.350654,-0.003089,0.006800
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,68.153778,197477700.0,AAPL,79.843501,84.219244,...,-0.926239,-0.155940,-0.770299,32.479352,63.646173,61.261193,58.876213,1484.574993,0.002003,0.019838
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,68.420891,316723400.0,AAPL,79.157248,83.564697,...,-0.892113,-0.097452,-0.794662,37.450172,63.236926,61.078872,58.920817,1497.780485,0.010276,0.010265
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,73.354591,205829400.0,AAPL,79.412836,83.361280,...,-0.733193,0.049174,-0.782368,51.350390,63.001827,61.010079,59.018330,1506.128807,0.024682,0.018850
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,72.729614,160688500.0,AAPL,79.523169,83.121926,...,-0.579416,0.162361,-0.741778,53.267164,62.959435,60.996029,59.032623,1508.629302,0.025531,0.007554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104471,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.014300,58.978638,3101.328695,-0.007883,0.005228
104472,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.944450,59.026797,3102.507723,-0.016661,0.002030
104473,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.868750,59.097896,3128.753695,-0.017629,0.004873
104474,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.831900,59.138363,3141.201722,-0.008376,0.006185
104475,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.807600,59.188831,3136.813139,-0.001766,0.007085

In [10]:
print(master_df.columns)

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [ ]:
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    # 'roll_ret_1d', 'roll_ret_5d', 
    # 'roll_ret_20d',
    
    'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
    'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
    'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv',
]

new_indicator_columns = [
    # 'sentiment',
                    
    # 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    # 'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    # 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    # 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    # 'emotion_surprize_pct', 
    
    # 'positive_emotion', 'negative_emotion','uncertainty_emotion', 
    # 'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
    
    # 'stance_label', 'stance_score', 
    
    # 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    # 'finbert_neutral', 
    
    # 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
    # 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
    # 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
    
    # 'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
    # 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
    # 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
    # 'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
]

# feature_columns.extend(new_indicator_columns)



sequence_length=12



all_pipelines = {}
all_results_dfs = {}
all_analyses = {}
fixed_bucket_edges = np.array([-0.08, -0.03, -0.01, 0.0, 0.01, 0.03, 0.08], dtype=float)
n_classes = len(fixed_bucket_edges) - 1
ordinal_head = 'corn'

In [12]:
print(master_df.shape)
master_df = master_df.dropna(subset=feature_columns).sort_values(['ticker','date'])
print(master_df.shape)

(104476, 80)
(104220, 80)

## Pipeline Execution

In [13]:
# print(f"\n{'='*25}\n  RUNNING PIPELINE FOR: GRU\n{'='*25}\n")

# pipeline_GRU = StockPredictionPipeline(
#     df=master_df,
#     feature_columns=feature_columns,
#     model_type='GRU',
#     sequence_length=sequence_length,
#     problem_type='classification',
#     horizon_steps=1,
#     n_classes=n_classes,
#     ordinal_head=ordinal_head,
#     fixed_bucket_edges=fixed_bucket_edges
# )

# results_GRU = pipeline_GRU.run_pipeline()

# loss_df = pipeline_GRU.get_loss_curves_df()

# pipeline_GRU.save_loss_curves('results/benchmarking/')

# if results_GRU is not None and not results_GRU.empty:
#     analysis_GRU = pipeline_GRU.analyze_results()
#     pipeline_GRU.save_results(results_GRU, output_dir='results/benchmarking/')
#     all_pipelines["GRU"] = pipeline_GRU
#     all_results_dfs["GRU"] = results_GRU
#     all_analyses["GRU"] = analysis_GRU

#     print("\nDisplaying first 5 rows of GRU results:")
#     display(results_GRU.head())
# else:
#     print(f"\n[FAILED] Pipeline for GRU did not produce any results.")

# del pipeline_GRU

In [ ]:
sentinemt_columns = [
    'sentiment',
]

emotion_columns = [
    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    'emotion_surprize_pct',
]

unified_emotion_columns = [
    'positive_emotion', 'negative_emotion','uncertainty_emotion',
    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct',
]

stance_columns = [
    'stance_label', 'stance_score',
]

finbert_columns = [
    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    'finbert_neutral',
]

sector_columns = ['sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                  'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                  'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                  
                  'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                  'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                  'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                  'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

In [ ]:
try:
    import optuna
except ImportError:
    import sys
    !{sys.executable} -m pip install optuna
    import optuna
    
from pathlib import Path
from datetime import datetime
    
# Define feature sets to test
feature_sets = {
    'base': feature_columns,
    # 'sentinment' : feature_columns + sentinemt_columns,
    # 'emotion' : feature_columns + emotion_columns,
    # 'unified_emotion': feature_columns + unified_emotion_columns,
    # 'finbert': feature_columns + finbert_columns,
    # 'all_nlp': feature_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
    'sector': feature_columns + sector_columns,
    'sector_sentiment': feature_columns + sector_columns + sentinemt_columns,
    'sector_emotion': feature_columns + sector_columns + emotion_columns,
    'sector_unified_emotion': feature_columns + sector_columns + unified_emotion_columns,
    'sector_finbert': feature_columns + sector_columns + finbert_columns,
    'sector_all_nlp': feature_columns + sector_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
}

def objective(trial):
    params = {
        'problem_type': 'classification',  # or 'classification'
        'feature_set': trial.suggest_categorical('feature_set', list(feature_sets.keys())),
        'model_type': trial.suggest_categorical('model_type', ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']),
        'sequence_length': trial.suggest_int('sequence_length', 6, 36, step=6),
        'horizon_steps': trial.suggest_categorical('horizon_steps', [1]),
        'hidden1': trial.suggest_categorical('hidden1', [64, 128, 256]),
        'hidden2': trial.suggest_categorical('hidden2', [32, 64, 128]),
        'num_layers': trial.suggest_categorical('num_layers', [1, 2]),
        'inter_rnn_drop': trial.suggest_float('inter_rnn_drop', 0.0, 0.4, step=0.1),
        'dropout': trial.suggest_float('dropout', 0.0, 0.8, step=0.1),
        'batch_size': trial.suggest_categorical('batch_size', [16, 32, 64]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-6, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 1e-7, 1e-3, log=True),
        'lr_patience': trial.suggest_categorical('lr_patience', [5, 7, 10]),
        'lr_factor': trial.suggest_categorical('lr_factor', [0.4, 0.8]),
        'early_stopping_patience': trial.suggest_categorical('early_stopping_patience', [10, 15, 20]),
        'max_epochs': trial.suggest_categorical('max_epochs', [20, 30, 50]),
        'huber_delta': trial.suggest_float('huber_delta', 0.1, 2.0),
        'early_stopping_min_delta': trial.suggest_float('early_stopping_min_delta', 0.0, 0.01),
    }

    selected_features = feature_sets[params['feature_set']]
    missing_cols = [c for c in selected_features if c not in master_df.columns]
    if missing_cols:
        print(f"Missing columns for feature_set={params['feature_set']}: {missing_cols}")
        return -1.0

    pipeline = StockPredictionPipeline(
        df=master_df,
        feature_columns=selected_features,
        model_type=params['model_type'],
        sequence_length=params['sequence_length'],
        problem_type=params['problem_type'],
        horizon_steps=params['horizon_steps'],
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        fixed_bucket_edges=fixed_bucket_edges,
        hidden1=params['hidden1'],
        hidden2=params['hidden2'],
        num_layers=params['num_layers'],
        inter_rnn_drop=params['inter_rnn_drop'],
        dropout=params['dropout'],
        batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        weight_decay=params['weight_decay'],
        lr_patience=params['lr_patience'],
        lr_factor=params['lr_factor'],
        early_stopping_patience=params['early_stopping_patience'],
        max_epochs=params['max_epochs'],
        huber_delta=params['huber_delta'],
        early_stopping_min_delta=params['early_stopping_min_delta']
    )

    results_df = pipeline.run_pipeline()
    del pipeline
    torch.cuda.empty_cache()

    if results_df is None or results_df.empty:
        print('[DEBUG] results_df empty or None')
        return -1.0

    print('[DEBUG] results_df shape:', results_df.shape)
    print('[DEBUG] results_df columns:', results_df.columns.tolist())

    # Aggregate validation metrics
    val_f1 = results_df['val_f1'].mean() if 'val_f1' in results_df.columns else np.nan
    if not np.isfinite(val_f1) and 'best_threshold_metric' in results_df.columns:
        val_f1 = results_df['best_threshold_metric'].mean()
    val_mcc = results_df['val_mcc'].mean() if 'val_mcc' in results_df.columns else np.nan
    print('[DEBUG] val_mcc:', val_mcc)
    val_precision = results_df['val_precision'].mean() if 'val_precision' in results_df.columns else np.nan
    val_recall = results_df['val_recall'].mean() if 'val_recall' in results_df.columns else np.nan
    val_dir_acc = results_df['val_directional_accuracy'].mean() if 'val_directional_accuracy' in results_df.columns else np.nan

    trial.set_user_attr('val_f1', float(val_f1))
    trial.set_user_attr('val_mcc', float(val_mcc))
    trial.set_user_attr('val_precision', float(val_precision))
    trial.set_user_attr('val_recall', float(val_recall))
    trial.set_user_attr('val_directional_accuracy', float(val_dir_acc))

    # Primary metric: mean val MCC (classification) or mean MAE (regression)
    if params['problem_type'] == 'classification':
        score = val_mcc
        if not np.isfinite(score):
            return -1.0
        return float(score)
    else:
        # minimize MAE -> maximize negative MAE
        if 'mae' not in results_df.columns:
            return -1.0
        mae = results_df['mae'].mean()
        if not np.isfinite(mae):
            return -1.0
        return float(-mae)


N_TRIALS = 250

# Run study
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=N_TRIALS, timeout=60*60*8)  # 8 hours max
# Collect results
optuna_results = study.trials_dataframe()
# include user attrs
user_attrs = pd.DataFrame([t.user_attrs for t in study.trials])
optuna_results = pd.concat([optuna_results, user_attrs], axis=1)
optuna_results = optuna_results.sort_values('value', ascending=False)
optuna_results

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
out_path = f'../results/benchmarking/classification/optuna_tuning_sector_1H.csv'
Path('../results/benchmarking/classification').mkdir(parents=True, exist_ok=True)
optuna_results.to_csv(out_path, index=False)
print(f'Saved Optuna results to {out_path}')

[I 2026-02-19 22:49:26,771] A new study created in memory with name: no-name-31f1a120-d8a7-4ffb-8e3b-1219a9ade199

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71666 | val 0.67913
  Epoch 020 - train 0.73953 | val 0.66892
  Epoch 025 - train 0.70842 | val 0.66843
  Classification -> best τ=0.430 (val F1=0.1938)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71014 | val 0.70209
  Epoch 011 - train 0.70413 | val 0.70387
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72194 | val 0.72517
  Epoch 011 - train 0.73569 | val 0.72996
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.73029 | val 0.70955
  Epoch 011 - train 0.75850 | val 0.71081
  Classification -> best τ=0.425 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.73899 | val 0.69283
  Epoch 011 - train 0.73957 | val 0.69543
  Classification -> best τ=0.525 (val F1=0.2567)
  Directional -> Accuracy: 0.5800, MCC: 0.1574, F1: 0.6038

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.75232 | val 0.70042
  Epoch 011 - train 0.74611 | val 0.70297
  Classification -> best τ=0.520 (val F1=0.0427)
  Directional -> Accuracy: 0.5870, MCC: 0.1774, F1: 0.4242

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72189 | val 0.83908
  Epoch 011 - train 0.77114 | val 0.84754
  Classification -> best τ=0.520 (val F1=0.1195)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.74257 | val 0.65677
  Epoch 020 - train 0.75666 | val 0.62602
  Epoch 030 - train 0.71315 | val 0.61089
  Epoch 040 - train 0.74373 | val 0.60779
  Epoch 041 - train 0.71421 | val 0.60781
  Classification -> best τ=0.450 (val F1=0.3974)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71953 | val 0.70339
  Epoch 011 - train 0.71427 | val 0.70598
  Classification -> best τ=0.525 (val F1=0.3431)
  Directional -> Accuracy: 0.6250, MCC: 0.2186, F1: 0.4375

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.73593 | val 0.79134
  Epoch 011 - train 0.75423 | val 0.80253
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72666 | val 0.69973
  Epoch 011 - train 0.71548 | val 0.70463
  Classification -> best τ=0.455 (val F1=0.0263)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72773 | val 0.68910
  Epoch 011 - train 0.72254 | val 0.69072
  Classification -> best τ=0.500 (val F1=0.1576)
  Directional -> Accuracy: 0.5263, MCC: 0.0600, F1: 0.6582

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.76695 | val 0.75683
  Epoch 011 - train 0.75818 | val 0.76403
  Classification -> best τ=0.450 (val F1=0.3131)
  Directional -> Accuracy: 0.4524, MCC: -0.0912, F1: 0.4390

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68615 | val 0.67202
  Epoch 020 - train 0.70682 | val 0.66207
  Epoch 024 - train 0.68793 | val 0.66131
  Classification -> best τ=0.500 (val F1=0.1774)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.3913

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.73013 | val 0.75690
  Epoch 011 - train 0.75008 | val 0.76672
  Classification -> best τ=0.440 (val F1=0.1344)
  Directional -> Accuracy: 0.4706, MCC: 0.0338, F1: 0.6087

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.75261 | val 0.68615
  Epoch 018 - train 0.71811 | val 0.68652
  Classification -> best τ=0.430 (val F1=0.1823)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68884 | val 0.73391
  Epoch 011 - train 0.71029 | val 0.73907
  Classification -> best τ=0.560 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70700 | val 0.70942
  Epoch 011 - train 0.71904 | val 0.71029
  Classification -> best τ=0.490 (val F1=0.1786)
  Directional -> Accuracy: 0.6400, MCC: 0.2058, F1: 0.7611

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69714 | val 0.70510
  Epoch 011 - train 0.71736 | val 0.70812
  Classification -> best τ=0.520 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.72914 | val 0.72335
  Epoch 011 - train 0.73378 | val 0.73250
  Classification -> best τ=0.410 (val F1=0.1895)
  Directional -> Accuracy: 0.5811, MCC: 0.1954, F1: 0.5507

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72293 | val 0.70543
  Epoch 011 - train 0.72263 | val 0.70690
  Classification -> best τ=0.480 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70571 | val 0.72493
  Epoch 011 - train 0.75456 | val 0.72941
  Classification -> best τ=0.495 (val F1=0.1590)
  Directional -> Accuracy: 0.5231, MCC: 0.0435, F1: 0.5974

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.74630 | val 0.68391
  Epoch 020 - train 0.69672 | val 0.68145
  Classification -> best τ=0.520 (val F1=0.2644)
  Directional -> Accuracy: 0.4912, MCC: -0.1880, F1: 0.6506

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70667 | val 0.69375
  Epoch 011 - train 0.70814 | val 0.69521
  Classification -> best τ=0.490 (val F1=0.1855)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72569 | val 0.68825
  Epoch 020 - train 0.72147 | val 0.68385
  Epoch 029 - train 0.70898 | val 0.68230
  Classification -> best τ=0.540 (val F1=0.2364)
  Directional -> Accuracy: 0.5455, MCC: 0.0319, F1: 0.6835

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72098 | val 0.69770
  Epoch 011 - train 0.72388 | val 0.69824
  Classification -> best τ=0.515 (val F1=0.0331)
  Directional -> Accuracy: 0.3778, MCC: -0.2440, F1: 0.3333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.74082 | val 0.73612
  Epoch 011 - train 0.74192 | val 0.74153
  Classification -> best τ=0.450 (val F1=0.0323)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70446 | val 0.66340
  Epoch 020 - train 0.69233 | val 0.65399
  Epoch 025 - train 0.70911 | val 0.65349
  Classification -> best τ=0.375 (val F1=0.3408)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73477 | val 0.69409
  Epoch 011 - train 0.73858 | val 0.69469
  Classification -> best τ=0.555 (val F1=0.0252)
  Directional -> Accuracy: 0.4000, MCC: -0.1919, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70267 | val 0.68521
  Epoch 011 - train 0.72112 | val 0.68496
  Classification -> best τ=0.475 (val F1=0.2114)
  Directional -> Accuracy: 0.4762, MCC: -0.0374, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65837 | val 0.68189
  Epoch 020 - train 0.70286 | val 0.66849
  Epoch 030 - train 0.71933 | val 0.67061
  Classification -> best τ=0.485 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72667 | val 0.74163
  Epoch 011 - train 0.72441 | val 0.74535
  Classification -> best τ=0.560 (val F1=0.1112)
  Directional -> Accuracy: 0.5510, MCC: 0.1535, F1: 0.7027

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.72542 | val 0.72962
  Epoch 011 - train 0.72383 | val 0.73038
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71709 | val 0.69698
  Epoch 011 - train 0.69511 | val 0.69808
  Classification -> best τ=0.490 (val F1=0.1539)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.72188 | val 0.69211
  Epoch 011 - train 0.70698 | val 0.69270
  Classification -> best τ=0.495 (val F1=0.1203)
  Directional -> Accuracy: 0.6061, MCC: 0.2059, F1: 0.7451

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69585 | val 0.70071
  Epoch 011 - train 0.67794 | val 0.70186
  Classification -> best τ=0.500 (val F1=0.1822)
  Directional -> Accuracy: 0.5714, MCC: 0.1685, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70327 | val 0.73281
  Epoch 011 - train 0.74028 | val 0.73787
  Classification -> best τ=0.540 (val F1=0.1997)
  Directional -> Accuracy: 0.5714, MCC: 0.1807, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.76010 | val 0.68699
  Epoch 011 - train 0.71679 | val 0.68842
  Classification -> best τ=0.455 (val F1=0.0475)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.73525 | val 0.70630
  Epoch 011 - train 0.75577 | val 0.70695
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72064 | val 0.67507
  Epoch 018 - train 0.72447 | val 0.67318
  Classification -> best τ=0.455 (val F1=0.2611)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.80271 | val 0.71347
  Epoch 011 - train 0.76151 | val 0.71683
  Classification -> best τ=0.510 (val F1=0.2712)
  Directional -> Accuracy: 0.5111, MCC: 0.0629, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.76061 | val 0.69284
  Epoch 011 - train 0.76138 | val 0.69339
  Classification -> best τ=0.500 (val F1=0.4423)
  Directional -> Accuracy: 0.5238, MCC: 0.0849, F1: 0.5000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70307 | val 0.68945
  Epoch 011 - train 0.69876 | val 0.69029
  Classification -> best τ=0.520 (val F1=0.2689)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72925 | val 0.68328
  Epoch 018 - train 0.75233 | val 0.69297
  Classification -> best τ=0.580 (val F1=0.1817)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.75172 | val 0.69922
  Epoch 011 - train 0.70932 | val 0.69949
  Classification -> best τ=0.515 (val F1=0.2137)
  Directional -> Accuracy: 0.4821, MCC: -0.0766, F1: 0.2162

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.73272 | val 0.68484
  Epoch 020 - train 0.69626 | val 0.67403
  Epoch 026 - train 0.71612 | val 0.67328
  Classification -> best τ=0.540 (val F1=0.1824)
  Directional -> Accuracy: 0.5283, MCC: 0.0631, F1: 0.6575

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69685 | val 0.68869
  Epoch 011 - train 0.72487 | val 0.68946
  Classification -> best τ=0.465 (val F1=0.1683)
  Directional -> Accuracy: 0.5091, MCC: 0.1839, F1: 0.1290

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-19 22:49:57,288] Trial 0 finished with value: 0.16710078737865075 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 6.306270608672354e-06, 'weight_decay': 4.391752816073103e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5828924347246178, 'early_stopping_min_delta': 0.005071097173518639}. Best is trial 0 with value: 0.16710078737865075.

  Epoch 010 - train 0.75541 | val 0.73608
  Epoch 011 - train 0.73554 | val 0.74208
  Classification -> best τ=0.520 (val F1=0.1072)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.16710078737865075
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68544 | val 0.70125
  Epoch 013 - train 0.68634 | val 0.70967
  Classification -> best τ=0.475 (val F1=0.1738)
  Directional -> Accuracy: 0.5000, MCC: 0.1637, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64685 | val 0.72780
  Epoch 013 - train 0.67337 | val 0.69123
  Classification -> best τ=0.535 (val F1=0.2346)
  Directional -> Accuracy: 0.5745, MCC: 0.1049, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69771 | val 0.70250
  Epoch 011 - train 0.69281 | val 0.70538
  Classification -> best τ=0.535 (val F1=0.2266)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5200

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69350 | val 0.76698
  Epoch 011 - train 0.65765 | val 0.77098
  Classification -> best τ=0.470 (val F1=0.1917)
  Directional -> Accuracy: 0.5000, MCC: 0.0692, F1: 0.2963

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70850 | val 0.67855
  Epoch 020 - train 0.65340 | val 0.65985
  Classification -> best τ=0.440 (val F1=0.3920)
  Directional -> Accuracy: 0.7692, MCC: 0.5346, F1: 0.7931

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64770 | val 0.73967
  Epoch 011 - train 0.66408 | val 0.76740
  Classification -> best τ=0.445 (val F1=0.1502)
  Directional -> Accuracy: 0.4898, MCC: -0.1414, F1: 0.6575

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68763 | val 0.71239
  Epoch 011 - train 0.68756 | val 0.71046
  Classification -> best τ=0.505 (val F1=0.2411)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71175 | val 0.84664
  Epoch 011 - train 0.69273 | val 0.87350
  Classification -> best τ=0.425 (val F1=0.2229)
  Directional -> Accuracy: 0.4667, MCC: -0.0782, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69596 | val 0.72673
  Epoch 013 - train 0.66504 | val 0.75447
  Classification -> best τ=0.520 (val F1=0.4382)
  Directional -> Accuracy: 0.5952, MCC: 0.0683, F1: 0.3200

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68322 | val 0.84826
  Epoch 011 - train 0.65304 | val 0.85653
  Classification -> best τ=0.425 (val F1=0.3204)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68384 | val 0.92497
  Epoch 011 - train 0.67999 | val 0.92934
  Classification -> best τ=0.460 (val F1=0.1147)
  Directional -> Accuracy: 0.3529, MCC: -0.2938, F1: 0.4407

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68988 | val 0.72585
  Epoch 011 - train 0.67668 | val 0.72022
  Classification -> best τ=0.480 (val F1=0.2202)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65845 | val 0.91901
  Epoch 011 - train 0.67900 | val 0.91312
  Classification -> best τ=0.450 (val F1=0.3087)
  Directional -> Accuracy: 0.5455, MCC: 0.0624, F1: 0.4118

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68001 | val 0.62231
  Epoch 019 - train 0.67226 | val 0.64113
  Classification -> best τ=0.350 (val F1=0.4018)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67335 | val 0.75939
  Epoch 011 - train 0.69853 | val 0.77275
  Classification -> best τ=0.550 (val F1=0.1000)
  Directional -> Accuracy: 0.5660, MCC: 0.1295, F1: 0.3030

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67392 | val 0.67856
  Epoch 014 - train 0.67940 | val 0.67611
  Classification -> best τ=0.610 (val F1=0.3164)
  Directional -> Accuracy: 0.5493, MCC: 0.0941, F1: 0.5789

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67386 | val 1.00819
  Epoch 011 - train 0.67391 | val 1.01099
  Classification -> best τ=0.540 (val F1=0.0940)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68879 | val 0.79811
  Epoch 011 - train 0.69496 | val 0.80350
  Classification -> best τ=0.485 (val F1=0.0924)
  Directional -> Accuracy: 0.5844, MCC: 0.0948, F1: 0.6800

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68661 | val 0.68765
  Epoch 020 - train 0.68200 | val 0.67496
  Classification -> best τ=0.535 (val F1=0.3170)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68245 | val 0.68726
  Epoch 016 - train 0.65339 | val 0.68367
  Classification -> best τ=0.385 (val F1=0.2563)
  Directional -> Accuracy: 0.6447, MCC: 0.3004, F1: 0.6400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69543 | val 0.69563
  Epoch 011 - train 0.67638 | val 0.69519
  Classification -> best τ=0.515 (val F1=0.0944)
  Directional -> Accuracy: 0.5510, MCC: 0.2661, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66772 | val 0.77748
  Epoch 011 - train 0.69249 | val 0.78182
  Classification -> best τ=0.525 (val F1=0.2709)
  Directional -> Accuracy: 0.4478, MCC: -0.1041, F1: 0.3729

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66867 | val 0.71140
  Epoch 013 - train 0.68457 | val 0.71143
  Classification -> best τ=0.525 (val F1=0.3058)
  Directional -> Accuracy: 0.5424, MCC: -0.0072, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66748 | val 0.92189
  Epoch 011 - train 0.67719 | val 0.91746
  Classification -> best τ=0.490 (val F1=0.0523)
  Directional -> Accuracy: 0.5522, MCC: 0.1375, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69097 | val 0.65494
  Epoch 020 - train 0.67576 | val 0.64400
  Classification -> best τ=0.485 (val F1=0.4455)
  Directional -> Accuracy: 0.5439, MCC: 0.1587, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68966 | val 0.69632
  Epoch 011 - train 0.67427 | val 0.69795
  Classification -> best τ=0.520 (val F1=0.3533)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66647 | val 0.74412
  Epoch 011 - train 0.67555 | val 0.74577
  Classification -> best τ=0.495 (val F1=0.1041)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69020 | val 0.68853
  Epoch 020 - train 0.66414 | val 0.69299
  Classification -> best τ=0.360 (val F1=0.2369)
  Directional -> Accuracy: 0.5690, MCC: 0.1996, F1: 0.4898

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66064 | val 0.69579
  Epoch 011 - train 0.65793 | val 0.69542
  Classification -> best τ=0.540 (val F1=0.2673)
  Directional -> Accuracy: 0.5116, MCC: 0.0864, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71769 | val 0.72949
  Epoch 011 - train 0.71823 | val 0.73330
  Classification -> best τ=0.480 (val F1=0.3024)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71324 | val 0.69818
  Epoch 014 - train 0.69948 | val 0.71265
  Classification -> best τ=0.480 (val F1=0.3125)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66448 | val 0.69296
  Epoch 019 - train 0.68287 | val 0.69774
  Classification -> best τ=0.520 (val F1=0.1781)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69127 | val 0.67301
  Epoch 020 - train 0.67411 | val 0.69162
  Classification -> best τ=0.485 (val F1=0.3679)
  Directional -> Accuracy: 0.5270, MCC: 0.0949, F1: 0.4928

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67539 | val 0.68912
  Epoch 018 - train 0.70019 | val 0.70107
  Classification -> best τ=0.530 (val F1=0.3125)
  Directional -> Accuracy: 0.4872, MCC: -0.0130, F1: 0.6000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66575 | val 0.87859
  Epoch 011 - train 0.65778 | val 0.88960
  Classification -> best τ=0.520 (val F1=0.2922)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66598 | val 0.68725
  Epoch 012 - train 0.65234 | val 0.69139
  Classification -> best τ=0.415 (val F1=0.3930)
  Directional -> Accuracy: 0.5147, MCC: 0.1130, F1: 0.4211

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66259 | val 0.69366
  Epoch 011 - train 0.67328 | val 0.69475
  Classification -> best τ=0.450 (val F1=0.2640)
  Directional -> Accuracy: 0.4091, MCC: -0.1890, F1: 0.4800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64623 | val 0.73729
  Epoch 013 - train 0.66652 | val 0.74737
  Classification -> best τ=0.485 (val F1=0.0745)
  Directional -> Accuracy: 0.4828, MCC: -0.1136, F1: 0.1667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66552 | val 0.94236
  Epoch 011 - train 0.68107 | val 0.95246
  Classification -> best τ=0.525 (val F1=0.2181)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70351 | val 0.71572
  Epoch 011 - train 0.69939 | val 0.71676
  Classification -> best τ=0.510 (val F1=0.1556)
  Directional -> Accuracy: 0.3250, MCC: -0.1981, F1: 0.4490

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66999 | val 0.69977
  Epoch 015 - train 0.66503 | val 0.70786
  Classification -> best τ=0.470 (val F1=0.2548)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66006 | val 0.73990
  Epoch 011 - train 0.67096 | val 0.74268
  Classification -> best τ=0.515 (val F1=0.0365)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6275

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69279 | val 0.81371
  Epoch 011 - train 0.72044 | val 0.82381
  Classification -> best τ=0.455 (val F1=0.1733)
  Directional -> Accuracy: 0.4583, MCC: -0.0845, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67812 | val 0.72013
  Epoch 011 - train 0.67828 | val 0.72455
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65868 | val 1.08469
  Epoch 011 - train 0.68787 | val 1.11174
  Classification -> best τ=0.490 (val F1=0.0325)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69861 | val 0.95854
  Epoch 011 - train 0.69552 | val 0.95452
  Classification -> best τ=0.495 (val F1=0.2302)
  Directional -> Accuracy: 0.5965, MCC: 0.2771, F1: 0.4889

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68531 | val 0.76232
  Epoch 011 - train 0.67047 | val 0.76671
  Classification -> best τ=0.485 (val F1=0.1699)
  Directional -> Accuracy: 0.5000, MCC: -0.0157, F1: 0.3556

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68337 | val 0.91977
  Epoch 011 - train 0.67043 | val 0.92980
  Classification -> best τ=0.540 (val F1=0.0750)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69039 | val 0.79377
  Epoch 011 - train 0.67215 | val 0.80993
  Classification -> best τ=0.430 (val F1=0.1888)
  Directional -> Accuracy: 0.4561, MCC: -0.0874, F1: 0.3404

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70371 | val 0.68017

[I 2026-02-19 22:50:46,137] Trial 1 finished with value: 0.2248100499162296 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0001794136009907318, 'weight_decay': 2.1163383488215383e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.9502191820775947, 'early_stopping_min_delta': 0.0036093059886136603}. Best is trial 1 with value: 0.2248100499162296.

  Epoch 017 - train 0.68017 | val 0.69883
  Classification -> best τ=0.510 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2248100499162296
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53461 | val 2.21591
  Epoch 016 - train 0.45736 | val 3.72568
  Classification -> best τ=0.520 (val F1=0.2015)
  Directional -> Accuracy: 0.5844, MCC: 0.1468, F1: 0.4667

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50983 | val 1.42338
  Epoch 016 - train 0.41097 | val 2.03171
  Classification -> best τ=0.485 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53262 | val 0.83217
  Epoch 020 - train 0.37163 | val 1.58442
  Classification -> best τ=0.655 (val F1=0.3724)
  Directional -> Accuracy: 0.5532, MCC: 0.1979, F1: 0.3636

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56978 | val 2.04112
  Epoch 016 - train 0.50642 | val 1.49700
  Classification -> best τ=0.510 (val F1=0.0966)
  Directional -> Accuracy: 0.4800, MCC: -0.0170, F1: 0.4348

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48773 | val 1.60447
  Epoch 017 - train 0.38148 | val 3.05058
  Classification -> best τ=0.475 (val F1=0.4427)
  Directional -> Accuracy: 0.7843, MCC: 0.5681, F1: 0.8070

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40763 | val 2.44437
  Epoch 016 - train 0.35484 | val 3.27102
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54266 | val 1.04753
  Epoch 016 - train 0.46462 | val 1.45454
  Classification -> best τ=0.410 (val F1=0.2100)
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51813 | val 1.80713
  Epoch 016 - train 0.45232 | val 3.14550
  Classification -> best τ=0.470 (val F1=0.1752)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52737 | val 0.92229
  Epoch 016 - train 0.47782 | val 0.93119
  Classification -> best τ=0.530 (val F1=0.1872)
  Directional -> Accuracy: 0.3469, MCC: -0.3010, F1: 0.4667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51079 | val 0.79855
  Epoch 016 - train 0.44324 | val 0.83239
  Classification -> best τ=0.475 (val F1=0.2012)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.48715 | val 2.75774
  Epoch 016 - train 0.41612 | val 2.88987
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49510 | val 2.59677
  Epoch 016 - train 0.43172 | val 3.16767
  Classification -> best τ=0.450 (val F1=0.1393)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47535 | val 3.05054
  Epoch 016 - train 0.41467 | val 4.17405
  Classification -> best τ=0.490 (val F1=0.2444)
  Directional -> Accuracy: 0.5814, MCC: 0.1223, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56241 | val 0.72627
  Epoch 017 - train 0.47794 | val 0.79535
  Classification -> best τ=0.505 (val F1=0.3180)
  Directional -> Accuracy: 0.5574, MCC: 0.1172, F1: 0.6301

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50353 | val 0.75267
  Epoch 016 - train 0.40091 | val 0.81291
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51037 | val 1.47061
  Epoch 016 - train 0.44234 | val 1.60751
  Classification -> best τ=0.385 (val F1=0.2605)
  Directional -> Accuracy: 0.5714, MCC: 0.1288, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54026 | val 2.33289
  Epoch 016 - train 0.47791 | val 2.61930
  Classification -> best τ=0.570 (val F1=0.0788)
  Directional -> Accuracy: 0.4407, MCC: 0.2080, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50799 | val 1.28011
  Epoch 016 - train 0.42873 | val 1.84540
  Classification -> best τ=0.495 (val F1=0.1054)
  Directional -> Accuracy: 0.4342, MCC: -0.0755, F1: 0.4110

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53630 | val 2.01523
  Epoch 016 - train 0.46877 | val 2.72306
  Classification -> best τ=0.540 (val F1=0.2249)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47898 | val 0.70778
  Epoch 020 - train 0.37210 | val 1.14329
  Classification -> best τ=0.800 (val F1=0.2935)
  Directional -> Accuracy: 0.4933, MCC: 0.1859, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50572 | val 1.48372
  Epoch 016 - train 0.40537 | val 2.56337
  Classification -> best τ=0.480 (val F1=0.1339)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53854 | val 1.78919
  Epoch 016 - train 0.46315 | val 1.68212
  Classification -> best τ=0.515 (val F1=0.2543)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53477 | val 1.46264
  Epoch 016 - train 0.46152 | val 1.83823
  Classification -> best τ=0.515 (val F1=0.2379)
  Directional -> Accuracy: 0.6207, MCC: 0.2085, F1: 0.6944

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51687 | val 1.33990
  Epoch 016 - train 0.44423 | val 2.57546
  Classification -> best τ=0.530 (val F1=0.1318)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49265 | val 0.75387
  Epoch 018 - train 0.42270 | val 0.93197
  Classification -> best τ=0.550 (val F1=0.3656)
  Directional -> Accuracy: 0.4821, MCC: 0.0587, F1: 0.2564

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50353 | val 1.12680
  Epoch 016 - train 0.40749 | val 1.31503
  Classification -> best τ=0.475 (val F1=0.1925)
  Directional -> Accuracy: 0.5870, MCC: 0.1236, F1: 0.1739

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55496 | val 1.51139
  Epoch 016 - train 0.47945 | val 1.86331
  Classification -> best τ=0.475 (val F1=0.1818)
  Directional -> Accuracy: 0.5349, MCC: 0.0295, F1: 0.6154

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54092 | val 0.86975
  Epoch 016 - train 0.45806 | val 1.25544
  Classification -> best τ=0.490 (val F1=0.0860)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55804 | val 0.80611
  Epoch 016 - train 0.50566 | val 1.02454
  Classification -> best τ=0.505 (val F1=0.2774)
  Directional -> Accuracy: 0.5122, MCC: -0.0026, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50754 | val 1.52199
  Epoch 016 - train 0.41962 | val 1.95349
  Classification -> best τ=0.490 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0051, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55948 | val 0.95106
  Epoch 018 - train 0.42151 | val 1.27619
  Classification -> best τ=0.630 (val F1=0.1161)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50410 | val 1.34476
  Epoch 016 - train 0.41191 | val 1.73186
  Classification -> best τ=0.450 (val F1=0.1955)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49320 | val 0.95705
  Epoch 018 - train 0.37879 | val 1.12308
  Classification -> best τ=0.180 (val F1=0.3602)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54733 | val 1.38987
  Epoch 016 - train 0.44048 | val 2.85672
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50634 | val 0.93119
  Epoch 016 - train 0.41227 | val 1.00732
  Classification -> best τ=0.520 (val F1=0.1925)
  Directional -> Accuracy: 0.4545, MCC: -0.0788, F1: 0.5556

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49205 | val 0.72352
  Epoch 017 - train 0.40747 | val 0.87803
  Classification -> best τ=0.460 (val F1=0.3495)
  Directional -> Accuracy: 0.5821, MCC: 0.1241, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50602 | val 0.92759
  Epoch 016 - train 0.42475 | val 1.39421
  Classification -> best τ=0.550 (val F1=0.3099)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48462 | val 0.71278
  Epoch 017 - train 0.38846 | val 0.82552
  Classification -> best τ=0.465 (val F1=0.1590)
  Directional -> Accuracy: 0.5439, MCC: 0.1605, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48330 | val 1.21652
  Epoch 016 - train 0.33927 | val 1.02281
  Classification -> best τ=0.470 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52825 | val 0.84420
  Epoch 020 - train 0.40927 | val 1.21822
  Classification -> best τ=0.355 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51771 | val 1.42866
  Epoch 016 - train 0.43809 | val 2.35314
  Classification -> best τ=0.500 (val F1=0.0134)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50089 | val 2.16616
  Epoch 016 - train 0.42584 | val 2.54988
  Classification -> best τ=0.460 (val F1=0.3051)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50198 | val 1.59443
  Epoch 016 - train 0.38761 | val 2.32137
  Classification -> best τ=0.495 (val F1=0.2030)
  Directional -> Accuracy: 0.4468, MCC: -0.2154, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48841 | val 1.37570
  Epoch 016 - train 0.39431 | val 1.91669
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51649 | val 1.48759
  Epoch 016 - train 0.40098 | val 2.36494
  Classification -> best τ=0.485 (val F1=0.0945)
  Directional -> Accuracy: 0.3673, MCC: -0.1468, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54219 | val 1.80215
  Epoch 018 - train 0.47821 | val 2.83542
  Classification -> best τ=0.525 (val F1=0.2077)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49928 | val 1.32023
  Epoch 016 - train 0.40618 | val 1.57532
  Classification -> best τ=0.575 (val F1=0.4545)
  Directional -> Accuracy: 0.5439, MCC: 0.1810, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51400 | val 1.77556
  Epoch 016 - train 0.43136 | val 2.18252
  Classification -> best τ=0.505 (val F1=0.1869)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50823 | val 0.86051
  Epoch 019 - train 0.35703 | val 1.56849
  Classification -> best τ=0.555 (val F1=0.2222)
  Directional -> Accuracy: 0.4643, MCC: -0.1397, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56149 | val 1.97897

[I 2026-02-19 22:51:29,070] Trial 2 finished with value: 0.19948462598707756 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.001218552725359788, 'weight_decay': 4.6928167502231854e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.10706214191010274, 'early_stopping_min_delta': 0.008250598912477418}. Best is trial 1 with value: 0.2248100499162296.

  Epoch 016 - train 0.46357 | val 3.34439
  Classification -> best τ=0.545 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19948462598707756
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68682 | val 0.71492
  Epoch 011 - train 0.68240 | val 0.71485
  Classification -> best τ=0.545 (val F1=0.1713)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66667 | val 0.70043
  Epoch 011 - train 0.66982 | val 0.70019
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70842 | val 0.70086
  Epoch 011 - train 0.71497 | val 0.70127
  Classification -> best τ=0.470 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69137 | val 0.72946
  Epoch 011 - train 0.69613 | val 0.73892
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71043 | val 0.68220
  Epoch 020 - train 0.68392 | val 0.67448
  Epoch 030 - train 0.65954 | val 0.66549
  Epoch 040 - train 0.65980 | val 0.65793
  Epoch 050 - train 0.64395 | val 0.65440
  Classification -> best τ=0.570 (val F1=0.3946)
  Directional -> Accuracy: 0.4800, MCC: -0.0355, F1: 0.4583

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68040 | val 0.69043
  Epoch 020 - train 0.66590 | val 0.71007
  Classification -> best τ=0.525 (val F1=0.1093)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.1538

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69229 | val 0.70310
  Epoch 011 - train 0.69330 | val 0.70699
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68584 | val 0.71096
  Epoch 011 - train 0.68162 | val 0.71103
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68484 | val 0.68742
  Epoch 011 - train 0.68359 | val 0.68719
  Classification -> best τ=0.480 (val F1=0.1402)
  Directional -> Accuracy: 0.3125, MCC: -0.3563, F1: 0.3774

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69628 | val 0.69432
  Epoch 011 - train 0.69108 | val 0.69684
  Classification -> best τ=0.540 (val F1=0.0690)
  Directional -> Accuracy: 0.4493, MCC: -0.1004, F1: 0.4062

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66991 | val 0.69788
  Epoch 020 - train 0.68110 | val 0.70162
  Classification -> best τ=0.520 (val F1=0.0698)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68071 | val 0.69386
  Epoch 018 - train 0.67418 | val 0.69858
  Classification -> best τ=0.475 (val F1=0.2373)
  Directional -> Accuracy: 0.5965, MCC: 0.1923, F1: 0.6230

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69855 | val 0.72196
  Epoch 011 - train 0.70000 | val 0.72411
  Classification -> best τ=0.465 (val F1=0.1132)
  Directional -> Accuracy: 0.4762, MCC: -0.0478, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70550 | val 0.66719
  Epoch 020 - train 0.69203 | val 0.65986
  Epoch 030 - train 0.68739 | val 0.65541
  Epoch 040 - train 0.68534 | val 0.65294
  Epoch 050 - train 0.67469 | val 0.65203
  Classification -> best τ=0.450 (val F1=0.3145)
  Directional -> Accuracy: 0.5500, MCC: 0.1075, F1: 0.4490

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68422 | val 0.69560
  Epoch 011 - train 0.68800 | val 0.69561
  Classification -> best τ=0.525 (val F1=0.3000)
  Directional -> Accuracy: 0.5686, MCC: 0.1560, F1: 0.0833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68421 | val 0.70221
  Epoch 011 - train 0.68408 | val 0.70568
  Classification -> best τ=0.490 (val F1=0.2341)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72228 | val 0.69610
  Epoch 011 - train 0.71654 | val 0.69706
  Classification -> best τ=0.455 (val F1=0.2135)
  Directional -> Accuracy: 0.4138, MCC: -0.2681, F1: 0.5405

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68275 | val 0.69237
  Epoch 011 - train 0.68098 | val 0.69258
  Classification -> best τ=0.525 (val F1=0.0262)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70194 | val 0.71519
  Epoch 011 - train 0.70519 | val 0.72127
  Classification -> best τ=0.500 (val F1=0.0066)
  Directional -> Accuracy: 0.4219, MCC: -0.0760, F1: 0.2449

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67807 | val 0.70417
  Epoch 011 - train 0.68193 | val 0.70702
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68093 | val 0.68883
  Epoch 011 - train 0.68949 | val 0.68884
  Classification -> best τ=0.520 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69852 | val 0.69713
  Epoch 011 - train 0.69605 | val 0.69978
  Classification -> best τ=0.460 (val F1=0.0382)
  Directional -> Accuracy: 0.4615, MCC: -0.1809, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67584 | val 0.68409
  Epoch 020 - train 0.67703 | val 0.69017
  Epoch 021 - train 0.66728 | val 0.69096
  Classification -> best τ=0.605 (val F1=0.3113)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69784 | val 0.69710
  Epoch 011 - train 0.69142 | val 0.70116
  Classification -> best τ=0.470 (val F1=0.0193)
  Directional -> Accuracy: 0.5231, MCC: 0.0377, F1: 0.4561

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68726 | val 0.68308
  Epoch 020 - train 0.67593 | val 0.65746
  Epoch 030 - train 0.66399 | val 0.64989
  Epoch 040 - train 0.65689 | val 0.64600
  Epoch 050 - train 0.65495 | val 0.64438
  Classification -> best τ=0.500 (val F1=0.4607)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70046 | val 0.69401
  Epoch 011 - train 0.70052 | val 0.69415
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70599 | val 0.69845
  Epoch 011 - train 0.70144 | val 0.69956
  Classification -> best τ=0.490 (val F1=0.2107)
  Directional -> Accuracy: 0.4286, MCC: -0.2041, F1: 0.5385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68505 | val 0.67677
  Epoch 020 - train 0.66457 | val 0.66506
  Epoch 027 - train 0.67006 | val 0.66471
  Classification -> best τ=0.440 (val F1=0.3414)
  Directional -> Accuracy: 0.5893, MCC: 0.2939, F1: 0.4651

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70095 | val 0.70914
  Epoch 011 - train 0.70479 | val 0.70962
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66935 | val 0.71102
  Epoch 011 - train 0.66787 | val 0.71170
  Classification -> best τ=0.555 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68298 | val 0.71572
  Epoch 011 - train 0.69525 | val 0.71650
  Classification -> best τ=0.465 (val F1=0.2328)
  Directional -> Accuracy: 0.5476, MCC: 0.0605, F1: 0.6415

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70412 | val 0.69904
  Epoch 011 - train 0.70479 | val 0.70026
  Classification -> best τ=0.505 (val F1=0.0331)
  Directional -> Accuracy: 0.5510, MCC: 0.1422, F1: 0.4500

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67889 | val 0.69412
  Epoch 011 - train 0.67998 | val 0.69428
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67323 | val 0.70738
  Epoch 011 - train 0.68118 | val 0.70948
  Classification -> best τ=0.525 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67450 | val 0.70188
  Epoch 011 - train 0.66954 | val 0.70228
  Classification -> best τ=0.500 (val F1=0.0388)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70695 | val 0.69828
  Epoch 011 - train 0.69039 | val 0.69930
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67842 | val 0.68308
  Epoch 020 - train 0.66395 | val 0.68289
  Epoch 022 - train 0.65531 | val 0.68421
  Classification -> best τ=0.495 (val F1=0.2382)
  Directional -> Accuracy: 0.3929, MCC: -0.2148, F1: 0.3704

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69982 | val 0.68845
  Epoch 020 - train 0.68632 | val 0.67854
  Epoch 030 - train 0.67696 | val 0.66858
  Epoch 040 - train 0.67168 | val 0.66856
  Classification -> best τ=0.435 (val F1=0.3050)
  Directional -> Accuracy: 0.4130, MCC: -0.0324, F1: 0.2286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69081 | val 0.69188
  Epoch 011 - train 0.69011 | val 0.69186
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69007 | val 0.68650
  Epoch 020 - train 0.68327 | val 0.66756
  Epoch 030 - train 0.66968 | val 0.66632
  Classification -> best τ=0.470 (val F1=0.4347)
  Directional -> Accuracy: 0.4730, MCC: -0.1202, F1: 0.6422

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70670 | val 0.68837
  Epoch 011 - train 0.69062 | val 0.68814
  Classification -> best τ=0.485 (val F1=0.0255)
  Directional -> Accuracy: 0.5111, MCC: 0.0285, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69658 | val 0.67958
  Epoch 011 - train 0.67917 | val 0.67940
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67698 | val 0.71903
  Epoch 011 - train 0.67694 | val 0.71955
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68105 | val 0.71025
  Epoch 011 - train 0.69190 | val 0.71540
  Classification -> best τ=0.525 (val F1=0.1154)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68464 | val 0.68944
  Epoch 019 - train 0.67304 | val 0.69196
  Classification -> best τ=0.500 (val F1=0.3318)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69763 | val 0.68680
  Epoch 011 - train 0.69151 | val 0.68778
  Classification -> best τ=0.520 (val F1=0.2305)
  Directional -> Accuracy: 0.4906, MCC: -0.0585, F1: 0.6400

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69538 | val 0.73091
  Epoch 011 - train 0.70422 | val 0.73475
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-19 22:52:39,170] Trial 3 finished with value: 0.14391981399529918 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 1.9588124974239497e-05, 'weight_decay': 9.19833564161072e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9113043325825042, 'early_stopping_min_delta': 0.0020845162340513957}. Best is trial 1 with value: 0.2248100499162296.

  Epoch 010 - train 0.67319 | val 0.71603
  Epoch 011 - train 0.68662 | val 0.72560
  Classification -> best τ=0.470 (val F1=0.1083)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14391981399529918
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69585 | val 0.66626
  Epoch 020 - train 0.68656 | val 0.66251
  Epoch 030 - train 0.67883 | val 0.66315
  Epoch 039 - train 0.67611 | val 0.66428
  Classification -> best τ=0.485 (val F1=0.3072)
  Directional -> Accuracy: 0.4231, MCC: -0.1631, F1: 0.3662

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68688 | val 0.79958
  Epoch 020 - train 0.68361 | val 0.79292
  Epoch 021 - train 0.68346 | val 0.79256
  Classification -> best τ=0.520 (val F1=0.1563)
  Directional -> Accuracy: 0.4894, MCC: 0.0489, F1: 0.3333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70905 | val 0.70162
  Epoch 020 - train 0.70615 | val 0.70135
  Epoch 023 - train 0.70583 | val 0.70134
  Classification -> best τ=0.535 (val F1=0.3061)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68816 | val 0.70705
  Epoch 020 - train 0.68567 | val 0.70660
  Epoch 021 - train 0.68556 | val 0.70660
  Classification -> best τ=0.500 (val F1=0.0154)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69605 | val 0.84608
  Epoch 020 - train 0.69118 | val 0.84267
  Epoch 021 - train 0.69096 | val 0.84251
  Classification -> best τ=0.515 (val F1=0.1455)
  Directional -> Accuracy: 0.3077, MCC: -0.4304, F1: 0.4194

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70070 | val 0.90709
  Epoch 020 - train 0.69742 | val 0.92125
  Epoch 021 - train 0.69727 | val 0.92175
  Classification -> best τ=0.530 (val F1=0.3429)
  Directional -> Accuracy: 0.4694, MCC: -0.1473, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69780 | val 0.70596
  Epoch 020 - train 0.69618 | val 0.70591
  Epoch 021 - train 0.69612 | val 0.70591
  Classification -> best τ=0.475 (val F1=0.3078)
  Directional -> Accuracy: 0.4857, MCC: -0.0117, F1: 0.4545

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67906 | val 1.09807
  Epoch 020 - train 0.67788 | val 1.12246
  Epoch 021 - train 0.67783 | val 1.12291
  Classification -> best τ=0.535 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69153 | val 0.74781
  Epoch 020 - train 0.68955 | val 0.74165
  Epoch 021 - train 0.68946 | val 0.74135
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69531 | val 0.71076
  Epoch 020 - train 0.69243 | val 0.70822
  Epoch 021 - train 0.69229 | val 0.70814
  Classification -> best τ=0.485 (val F1=0.0850)
  Directional -> Accuracy: 0.4225, MCC: -0.0914, F1: 0.5591

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69971 | val 0.66011
  Epoch 020 - train 0.69370 | val 0.66240
  Epoch 025 - train 0.69235 | val 0.66302
  Classification -> best τ=0.365 (val F1=0.2540)
  Directional -> Accuracy: 0.5098, MCC: 0.0048, F1: 0.4186

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68467 | val 0.69619
  Epoch 020 - train 0.68253 | val 0.69613
  Epoch 021 - train 0.68241 | val 0.69613
  Classification -> best τ=0.530 (val F1=0.0540)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69414 | val 0.65852
  Epoch 020 - train 0.68342 | val 0.65917
  Epoch 023 - train 0.68197 | val 0.65940
  Classification -> best τ=0.600 (val F1=0.2841)
  Directional -> Accuracy: 0.4773, MCC: -0.0788, F1: 0.3429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70095 | val 0.95096
  Epoch 020 - train 0.69892 | val 0.94423
  Epoch 021 - train 0.69883 | val 0.94392
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69204 | val 0.75747
  Epoch 020 - train 0.68938 | val 0.77334
  Epoch 021 - train 0.68926 | val 0.77413
  Classification -> best τ=0.570 (val F1=0.2879)
  Directional -> Accuracy: 0.5849, MCC: 0.1766, F1: 0.3529

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68834 | val 0.74917
  Epoch 020 - train 0.68573 | val 0.74802
  Epoch 021 - train 0.68561 | val 0.74797
  Classification -> best τ=0.490 (val F1=0.2103)
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70196 | val 0.76644
  Epoch 020 - train 0.69911 | val 0.75931
  Epoch 021 - train 0.69900 | val 0.75901
  Classification -> best τ=0.495 (val F1=0.2112)
  Directional -> Accuracy: 0.3667, MCC: -0.1889, F1: 0.2963

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69882 | val 1.25131
  Epoch 020 - train 0.69624 | val 1.27043
  Epoch 021 - train 0.69612 | val 1.27134
  Classification -> best τ=0.395 (val F1=0.1674)
  Directional -> Accuracy: 0.5455, MCC: 0.1468, F1: 0.5455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68321 | val 0.72805
  Epoch 020 - train 0.67969 | val 0.72892
  Epoch 021 - train 0.67953 | val 0.72896
  Classification -> best τ=0.540 (val F1=0.1374)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70804 | val 0.93028
  Epoch 020 - train 0.70287 | val 0.91311
  Epoch 021 - train 0.70265 | val 0.91232
  Classification -> best τ=0.560 (val F1=0.1217)
  Directional -> Accuracy: 0.4868, MCC: -0.0542, F1: 0.5714

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69447 | val 0.70334
  Epoch 020 - train 0.69061 | val 0.70211
  Epoch 021 - train 0.69049 | val 0.70207
  Classification -> best τ=0.500 (val F1=0.1422)
  Directional -> Accuracy: 0.4694, MCC: 0.1428, F1: 0.3500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70507 | val 0.68455
  Epoch 020 - train 0.69780 | val 0.68532
  Epoch 021 - train 0.69728 | val 0.68544
  Classification -> best τ=0.480 (val F1=0.2096)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70903 | val 0.77257
  Epoch 020 - train 0.70614 | val 0.76180
  Epoch 021 - train 0.70601 | val 0.76129
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68462 | val 0.70713
  Epoch 020 - train 0.68216 | val 0.70428
  Epoch 021 - train 0.68205 | val 0.70421
  Classification -> best τ=0.525 (val F1=0.1890)
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69068 | val 0.68997
  Epoch 020 - train 0.68179 | val 0.67768
  Epoch 030 - train 0.67403 | val 0.67004
  Epoch 040 - train 0.66727 | val 0.66601
  Epoch 044 - train 0.66477 | val 0.66519
  Classification -> best τ=0.485 (val F1=0.4639)
  Directional -> Accuracy: 0.5439, MCC: 0.0420, F1: 0.6389

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68273 | val 0.70191
  Epoch 020 - train 0.68089 | val 0.69992
  Epoch 021 - train 0.68071 | val 0.70005
  Classification -> best τ=0.475 (val F1=0.0049)
  Directional -> Accuracy: 0.6458, MCC: 0.2577, F1: 0.5405

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72493 | val 0.67509
  Epoch 020 - train 0.71695 | val 0.67386
  Epoch 029 - train 0.71258 | val 0.68009
  Classification -> best τ=0.550 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0212, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69400 | val 0.70838
  Epoch 020 - train 0.69226 | val 0.70712
  Epoch 021 - train 0.69218 | val 0.70706
  Classification -> best τ=0.500 (val F1=0.1462)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68860 | val 0.68903
  Epoch 020 - train 0.68508 | val 0.68989
  Epoch 021 - train 0.68488 | val 0.68982
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68189 | val 0.73263
  Epoch 020 - train 0.68073 | val 0.73531
  Epoch 021 - train 0.68068 | val 0.73534
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68862 | val 0.68507
  Epoch 020 - train 0.68567 | val 0.68582
  Epoch 026 - train 0.68488 | val 0.68609
  Classification -> best τ=0.435 (val F1=0.2390)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68683 | val 0.64669
  Epoch 020 - train 0.68121 | val 0.64360
  Epoch 030 - train 0.67572 | val 0.64132
  Epoch 035 - train 0.67304 | val 0.64062
  Classification -> best τ=0.450 (val F1=0.5124)
  Directional -> Accuracy: 0.5294, MCC: 0.0119, F1: 0.6842

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69087 | val 0.68657
  Epoch 020 - train 0.68866 | val 0.68382
  Epoch 022 - train 0.68849 | val 0.68358
  Classification -> best τ=0.415 (val F1=0.3096)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69818 | val 0.78468
  Epoch 020 - train 0.69645 | val 0.84320
  Epoch 021 - train 0.69637 | val 0.84309
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70936 | val 0.71430
  Epoch 020 - train 0.70497 | val 0.70973
  Epoch 023 - train 0.70456 | val 0.70927
  Classification -> best τ=0.495 (val F1=0.2373)
  Directional -> Accuracy: 0.6222, MCC: 0.3339, F1: 0.3200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68455 | val 0.65529
  Epoch 020 - train 0.67963 | val 0.65646
  Epoch 023 - train 0.67896 | val 0.65670
  Classification -> best τ=0.435 (val F1=0.4381)
  Directional -> Accuracy: 0.5147, MCC: 0.0769, F1: 0.4762

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71106 | val 0.72142
  Epoch 020 - train 0.70946 | val 0.72026
  Epoch 021 - train 0.70939 | val 0.72018
  Classification -> best τ=0.455 (val F1=0.1765)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67847 | val 0.72789
  Epoch 020 - train 0.67622 | val 0.72449
  Epoch 021 - train 0.67612 | val 0.72433
  Classification -> best τ=0.525 (val F1=0.0037)
  Directional -> Accuracy: 0.5172, MCC: -0.0403, F1: 0.1250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71529 | val 0.80848
  Epoch 020 - train 0.71012 | val 0.78346
  Epoch 021 - train 0.70992 | val 0.78236
  Classification -> best τ=0.445 (val F1=0.0907)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68268 | val 0.64920
  Epoch 020 - train 0.67788 | val 0.64485
  Epoch 030 - train 0.67341 | val 0.64298
  Epoch 032 - train 0.67254 | val 0.64265
  Classification -> best τ=0.435 (val F1=0.4526)
  Directional -> Accuracy: 0.5250, MCC: 0.0682, F1: 0.4571

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68259 | val 0.69097
  Epoch 020 - train 0.67765 | val 0.68748
  Epoch 021 - train 0.67718 | val 0.68781
  Classification -> best τ=0.505 (val F1=0.0707)
  Directional -> Accuracy: 0.5128, MCC: 0.0600, F1: 0.4242

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68676 | val 0.75898
  Epoch 020 - train 0.68412 | val 0.76287
  Epoch 021 - train 0.68402 | val 0.76306
  Classification -> best τ=0.475 (val F1=0.2444)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69106 | val 0.75036
  Epoch 020 - train 0.68887 | val 0.74865
  Epoch 021 - train 0.68877 | val 0.74844
  Classification -> best τ=0.485 (val F1=0.0272)
  Directional -> Accuracy: 0.5417, MCC: 0.2085, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65903 | val 0.76318
  Epoch 020 - train 0.65734 | val 0.77552
  Epoch 021 - train 0.65726 | val 0.77562
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69066 | val 0.80418
  Epoch 020 - train 0.68850 | val 0.81455
  Epoch 021 - train 0.68840 | val 0.81494
  Classification -> best τ=0.460 (val F1=0.2037)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69600 | val 0.73648
  Epoch 020 - train 0.69422 | val 0.73435
  Epoch 021 - train 0.69414 | val 0.73425
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70190 | val 0.67524
  Epoch 020 - train 0.69249 | val 0.66477
  Epoch 030 - train 0.68542 | val 0.65793
  Epoch 040 - train 0.67926 | val 0.65453
  Epoch 050 - train 0.67387 | val 0.65264
  Classification -> best τ=0.385 (val F1=0.2908)
  Directional -> Accuracy: 0.5000, MCC: -0.0273, F1: 0.2564


[I 2026-02-19 22:55:44,276] Trial 4 finished with value: 0.1763685190423992 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 1.7397795774992232e-06, 'weight_decay': 4.621985998409232e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.7853452657106332, 'early_stopping_min_delta': 0.009055082548223061}. Best is trial 1 with value: 0.2248100499162296.

  Classification -> best τ=0.570 (val F1=0.2132)
  Directional -> Accuracy: 0.5484, MCC: 0.0928, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1763685190423992
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68394 | val 0.73145
  Epoch 016 - train 0.68893 | val 0.76955
  Classification -> best τ=0.550 (val F1=0.0276)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66220 | val 0.69471
  Epoch 016 - train 0.66129 | val 0.69360
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68776 | val 0.69325
  Epoch 016 - train 0.69434 | val 0.69373
  Classification -> best τ=0.490 (val F1=0.0548)
  Directional -> Accuracy: 0.5333, MCC: 0.0782, F1: 0.5116

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68357 | val 0.75500
  Epoch 016 - train 0.69181 | val 0.95043
  Classification -> best τ=0.485 (val F1=0.2293)
  Directional -> Accuracy: 0.5479, MCC: 0.0785, F1: 0.6207

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68421 | val 0.68916
  Epoch 020 - train 0.65061 | val 0.65540
  Classification -> best τ=0.490 (val F1=0.5201)
  Directional -> Accuracy: 0.5306, MCC: 0.0578, F1: 0.6102

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69214 | val 0.68924
  Epoch 020 - train 0.69286 | val 0.68535
  Classification -> best τ=0.545 (val F1=0.2737)
  Directional -> Accuracy: 0.5556, MCC: 0.1160, F1: 0.5833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69028 | val 0.69630
  Epoch 020 - train 0.69400 | val 0.68700
  Classification -> best τ=0.580 (val F1=0.2212)
  Directional -> Accuracy: 0.5224, MCC: -0.0443, F1: 0.3043

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68011 | val 0.72750
  Epoch 016 - train 0.67287 | val 0.73169
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69334 | val 0.69548
  Epoch 016 - train 0.68560 | val 0.71091
  Classification -> best τ=0.495 (val F1=0.1030)
  Directional -> Accuracy: 0.6383, MCC: 0.2652, F1: 0.5854

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67881 | val 0.69880
  Epoch 016 - train 0.66861 | val 0.70371
  Classification -> best τ=0.485 (val F1=0.3260)
  Directional -> Accuracy: 0.5147, MCC: 0.1652, F1: 0.6118

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70166 | val 0.72197
  Epoch 016 - train 0.69573 | val 0.73276
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68093 | val 0.69618
  Epoch 016 - train 0.67955 | val 0.71297
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67577 | val 0.70578
  Epoch 016 - train 0.65398 | val 0.73782
  Classification -> best τ=0.480 (val F1=0.1505)
  Directional -> Accuracy: 0.6327, MCC: 0.3114, F1: 0.7000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67977 | val 0.69671
  Epoch 016 - train 0.68559 | val 0.70350
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66892 | val 0.69210
  Epoch 016 - train 0.67360 | val 0.70597
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66577 | val 0.69030
  Epoch 016 - train 0.67299 | val 0.71617
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68522 | val 0.70053
  Epoch 016 - train 0.67389 | val 0.75317
  Classification -> best τ=0.475 (val F1=0.0806)
  Directional -> Accuracy: 0.3158, MCC: -0.3142, F1: 0.2642

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67628 | val 0.68871
  Epoch 016 - train 0.68216 | val 0.70641
  Classification -> best τ=0.510 (val F1=0.1808)
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66900 | val 0.69237
  Epoch 020 - train 0.66518 | val 0.69630
  Classification -> best τ=0.540 (val F1=0.2288)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67355 | val 0.67985
  Epoch 020 - train 0.66109 | val 0.66552
  Classification -> best τ=0.465 (val F1=0.2811)
  Directional -> Accuracy: 0.5342, MCC: 0.2305, F1: 0.2917

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69685 | val 0.69958
  Epoch 016 - train 0.68098 | val 0.70151
  Classification -> best τ=0.465 (val F1=0.1461)
  Directional -> Accuracy: 0.6739, MCC: 0.2924, F1: 0.7826

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68665 | val 0.69904
  Epoch 016 - train 0.67803 | val 0.71696
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67499 | val 0.67823
  Epoch 020 - train 0.65015 | val 0.71522
  Classification -> best τ=0.580 (val F1=0.3404)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68533 | val 0.69286
  Epoch 016 - train 0.68072 | val 0.71319
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67852 | val 0.68664
  Epoch 020 - train 0.67309 | val 0.64320
  Classification -> best τ=0.505 (val F1=0.4477)
  Directional -> Accuracy: 0.4259, MCC: -0.1628, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68424 | val 0.69262
  Epoch 016 - train 0.68474 | val 0.69104
  Classification -> best τ=0.495 (val F1=0.0223)
  Directional -> Accuracy: 0.3953, MCC: -0.1334, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69333 | val 0.69473
  Epoch 016 - train 0.68683 | val 0.69422
  Classification -> best τ=0.490 (val F1=0.1278)
  Directional -> Accuracy: 0.4490, MCC: -0.1000, F1: 0.4906

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68313 | val 0.68544
  Epoch 020 - train 0.66471 | val 0.66694
  Classification -> best τ=0.485 (val F1=0.2728)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70718 | val 0.69250
  Epoch 016 - train 0.68460 | val 0.69207
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69381 | val 0.69862
  Epoch 016 - train 0.69981 | val 0.70239
  Classification -> best τ=0.505 (val F1=0.1425)
  Directional -> Accuracy: 0.4390, MCC: -0.1214, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69783 | val 0.70698
  Epoch 016 - train 0.68157 | val 0.70396
  Classification -> best τ=0.475 (val F1=0.1029)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68415 | val 0.68446
  Epoch 020 - train 0.66453 | val 0.68403
  Classification -> best τ=0.475 (val F1=0.2513)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66707 | val 0.67938
  Epoch 020 - train 0.65407 | val 0.66308
  Classification -> best τ=0.355 (val F1=0.3325)
  Directional -> Accuracy: 0.5070, MCC: 0.0727, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69555 | val 0.71560
  Epoch 016 - train 0.67234 | val 0.71969
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65447 | val 0.68605
  Epoch 020 - train 0.66145 | val 0.72278
  Classification -> best τ=0.450 (val F1=0.3218)
  Directional -> Accuracy: 0.5692, MCC: 0.1000, F1: 0.6500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67724 | val 0.69033
  Epoch 020 - train 0.64616 | val 0.68648
  Classification -> best τ=0.475 (val F1=0.2582)
  Directional -> Accuracy: 0.6250, MCC: 0.2467, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67514 | val 0.69061
  Epoch 020 - train 0.65474 | val 0.69233
  Classification -> best τ=0.490 (val F1=0.1732)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.6494

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66924 | val 0.70314
  Epoch 016 - train 0.67933 | val 0.71719
  Classification -> best τ=0.510 (val F1=0.0943)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68044 | val 0.69690
  Epoch 020 - train 0.67050 | val 0.68924
  Classification -> best τ=0.535 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: -0.0791, F1: 0.4746

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67870 | val 0.69334
  Epoch 016 - train 0.67875 | val 0.69451
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65833 | val 0.69579
  Epoch 016 - train 0.66442 | val 0.69454
  Classification -> best τ=0.515 (val F1=0.0355)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69453 | val 0.70703
  Epoch 016 - train 0.66094 | val 0.70507
  Classification -> best τ=0.535 (val F1=0.0976)
  Directional -> Accuracy: 0.5610, MCC: -0.0111, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66189 | val 0.68096
  Epoch 016 - train 0.66170 | val 0.68494
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69071 | val 0.69812
  Epoch 016 - train 0.69102 | val 0.73827
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69180 | val 0.70275
  Epoch 016 - train 0.67095 | val 0.71738
  Classification -> best τ=0.525 (val F1=0.1115)
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68175 | val 0.69527
  Epoch 020 - train 0.67840 | val 0.67988
  Classification -> best τ=0.595 (val F1=0.2376)
  Directional -> Accuracy: 0.5769, MCC: 0.1543, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68655 | val 0.68175
  Epoch 016 - train 0.67117 | val 0.69623
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68762 | val 0.69532

[I 2026-02-19 22:57:36,085] Trial 5 finished with value: 0.1444448952811215 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 7.802085001572465e-05, 'weight_decay': 0.00017211690304919065, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.0434102815707695, 'early_stopping_min_delta': 0.003696140344004649}. Best is trial 1 with value: 0.2248100499162296.

  Epoch 020 - train 0.67616 | val 0.69275
  Classification -> best τ=0.590 (val F1=0.3074)
  Directional -> Accuracy: 0.5763, MCC: 0.1441, F1: 0.4681

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1444448952811215
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71625 | val 0.67736
  Epoch 020 - train 0.70816 | val 0.67225
  Classification -> best τ=0.515 (val F1=0.2627)
  Directional -> Accuracy: 0.5526, MCC: 0.0676, F1: 0.3929

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.73221 | val 0.68643
  Epoch 020 - train 0.73439 | val 0.68126
  Classification -> best τ=0.460 (val F1=0.0842)
  Directional -> Accuracy: 0.5333, MCC: -0.1844, F1: 0.6957

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69665 | val 0.68033
  Epoch 020 - train 0.69704 | val 0.67428
  Classification -> best τ=0.460 (val F1=0.4078)
  Directional -> Accuracy: 0.5000, MCC: -0.0547, F1: 0.6462

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.75934 | val 0.88349
  Epoch 016 - train 0.74065 | val 0.91956
  Classification -> best τ=0.385 (val F1=0.1394)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.74073 | val 0.69336
  Epoch 016 - train 0.69886 | val 0.69169
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67865 | val 0.68895
  Epoch 016 - train 0.69059 | val 0.68958
  Classification -> best τ=0.500 (val F1=0.3059)
  Directional -> Accuracy: 0.6087, MCC: 0.2496, F1: 0.4000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73056 | val 0.68903
  Epoch 016 - train 0.73596 | val 0.68951
  Classification -> best τ=0.500 (val F1=0.2212)
  Directional -> Accuracy: 0.5588, MCC: -0.1135, F1: 0.0625

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67506 | val 0.75136
  Epoch 016 - train 0.69688 | val 0.76475
  Classification -> best τ=0.550 (val F1=0.2657)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71613 | val 0.68977
  Epoch 016 - train 0.72404 | val 0.69006
  Classification -> best τ=0.495 (val F1=0.0548)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.72763 | val 0.70927
  Epoch 016 - train 0.72708 | val 0.71043
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72036 | val 0.68360
  Epoch 016 - train 0.69857 | val 0.68429
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70165 | val 0.68836
  Epoch 016 - train 0.72351 | val 0.69289
  Classification -> best τ=0.575 (val F1=0.1685)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.73693 | val 0.66714
  Epoch 020 - train 0.70284 | val 0.67267
  Classification -> best τ=0.550 (val F1=0.1733)
  Directional -> Accuracy: 0.4286, MCC: -0.1435, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72588 | val 0.72276
  Epoch 020 - train 0.73658 | val 0.71326
  Classification -> best τ=0.590 (val F1=0.3387)
  Directional -> Accuracy: 0.5833, MCC: 0.1675, F1: 0.6032

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.74356 | val 0.76429
  Epoch 016 - train 0.74739 | val 0.78991
  Classification -> best τ=0.485 (val F1=0.0778)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.72915 | val 0.70217
  Epoch 016 - train 0.72354 | val 0.70801
  Classification -> best τ=0.515 (val F1=0.2972)
  Directional -> Accuracy: 0.5507, MCC: 0.0735, F1: 0.6593

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.74463 | val 0.70399
  Epoch 016 - train 0.69657 | val 0.70539
  Classification -> best τ=0.455 (val F1=0.0046)
  Directional -> Accuracy: 0.6207, MCC: 0.1944, F1: 0.6944

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72154 | val 0.69814
  Epoch 016 - train 0.72161 | val 0.70007
  Classification -> best τ=0.515 (val F1=0.0487)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71712 | val 0.70220
  Epoch 016 - train 0.72499 | val 0.70681
  Classification -> best τ=0.540 (val F1=0.2711)
  Directional -> Accuracy: 0.4688, MCC: 0.0381, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.74589 | val 0.73103
  Epoch 016 - train 0.74296 | val 0.73530
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72248 | val 0.70860
  Epoch 016 - train 0.69095 | val 0.72165
  Classification -> best τ=0.470 (val F1=0.0853)
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.5385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70425 | val 0.69910
  Epoch 016 - train 0.73931 | val 0.70318
  Classification -> best τ=0.495 (val F1=0.0863)
  Directional -> Accuracy: 0.4462, MCC: -0.1341, F1: 0.5610

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.72316 | val 0.69375
  Epoch 016 - train 0.69118 | val 0.68775
  Classification -> best τ=0.525 (val F1=0.1268)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71187 | val 0.70973
  Epoch 016 - train 0.73202 | val 0.70754
  Classification -> best τ=0.555 (val F1=0.1565)
  Directional -> Accuracy: 0.5538, MCC: 0.0974, F1: 0.4082

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72423 | val 0.67423
  Epoch 020 - train 0.70853 | val 0.66878
  Classification -> best τ=0.480 (val F1=0.2735)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72675 | val 0.68734
  Epoch 016 - train 0.72584 | val 0.68542
  Classification -> best τ=0.515 (val F1=0.2756)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.74619 | val 0.68708
  Epoch 020 - train 0.76226 | val 0.68139
  Classification -> best τ=0.510 (val F1=0.1803)
  Directional -> Accuracy: 0.6190, MCC: 0.1964, F1: 0.7333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.75674 | val 0.71938
  Epoch 016 - train 0.72412 | val 0.72330
  Classification -> best τ=0.535 (val F1=0.0804)
  Directional -> Accuracy: 0.4643, MCC: -0.0167, F1: 0.3182

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74755 | val 0.69316
  Epoch 020 - train 0.76437 | val 0.68325
  Classification -> best τ=0.515 (val F1=0.4719)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72898 | val 0.67318
  Epoch 020 - train 0.70755 | val 0.66556
  Classification -> best τ=0.520 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0830, F1: 0.3448

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71936 | val 0.71771
  Epoch 016 - train 0.71120 | val 0.72123
  Classification -> best τ=0.470 (val F1=0.1124)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71606 | val 0.69068
  Epoch 016 - train 0.71544 | val 0.69284
  Classification -> best τ=0.490 (val F1=0.1913)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.74826 | val 0.75196
  Epoch 016 - train 0.76724 | val 0.75951
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70093 | val 0.74098
  Epoch 016 - train 0.68653 | val 0.75386
  Classification -> best τ=0.555 (val F1=0.1027)
  Directional -> Accuracy: 0.4186, MCC: -0.1736, F1: 0.5283

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.74491 | val 0.71012
  Epoch 016 - train 0.74836 | val 0.71201
  Classification -> best τ=0.550 (val F1=0.1279)
  Directional -> Accuracy: 0.3788, MCC: -0.1915, F1: 0.1961

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.76248 | val 0.70435
  Epoch 016 - train 0.71424 | val 0.71684
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.72447 | val 0.71055
  Epoch 016 - train 0.72536 | val 0.72263
  Classification -> best τ=0.510 (val F1=0.1238)
  Directional -> Accuracy: 0.5000, MCC: -0.0157, F1: 0.4167

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72534 | val 0.71158
  Epoch 016 - train 0.75250 | val 0.71877
  Classification -> best τ=0.525 (val F1=0.1490)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69149 | val 0.69038
  Epoch 016 - train 0.69438 | val 0.69553
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72385 | val 0.69835
  Epoch 016 - train 0.70553 | val 0.69935
  Classification -> best τ=0.505 (val F1=0.0080)
  Directional -> Accuracy: 0.4459, MCC: -0.1145, F1: 0.5684

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.75225 | val 0.69663
  Epoch 016 - train 0.73449 | val 0.71614
  Classification -> best τ=0.415 (val F1=0.4000)
  Directional -> Accuracy: 0.5111, MCC: 0.0832, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70622 | val 0.70939
  Epoch 020 - train 0.70164 | val 0.70412
  Classification -> best τ=0.550 (val F1=0.4001)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4651

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71045 | val 0.67915
  Epoch 020 - train 0.73211 | val 0.67322
  Classification -> best τ=0.495 (val F1=0.4542)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.73353 | val 0.74605
  Epoch 016 - train 0.73054 | val 0.79809
  Classification -> best τ=0.465 (val F1=0.3200)
  Directional -> Accuracy: 0.6545, MCC: 0.3012, F1: 0.6885

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.72047 | val 0.68517
  Epoch 016 - train 0.69170 | val 0.69200
  Classification -> best τ=0.480 (val F1=0.2227)
  Directional -> Accuracy: 0.4821, MCC: -0.0309, F1: 0.5085

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71557 | val 0.72440
  Epoch 016 - train 0.75690 | val 0.72920
  Classification -> best τ=0.465 (val F1=0.0957)
  Directional -> Accuracy: 0.5660, MCC: 0.1310, F1: 0.6102

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68477 | val 0.75008
  Epoch 016 - train 0.71184 | val 0.78976
  Classification -> best τ=0.495 (val F1=0.0404)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71678 | val 0.68643

[I 2026-02-19 22:58:23,224] Trial 6 finished with value: 0.1716163477495376 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 2.3370550013193036e-06, 'weight_decay': 4.630670133287439e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6437743935175892, 'early_stopping_min_delta': 0.005916123792926962}. Best is trial 1 with value: 0.2248100499162296.

  Epoch 020 - train 0.72205 | val 0.68473
  Classification -> best τ=0.495 (val F1=0.2810)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1716163477495376
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59916 | val 0.87676
  Epoch 018 - train 0.54102 | val 1.15128
  Classification -> best τ=0.620 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55073 | val 0.71458
  Epoch 019 - train 0.52593 | val 0.77094
  Classification -> best τ=0.460 (val F1=0.1123)
  Directional -> Accuracy: 0.5652, MCC: 0.0604, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61520 | val 0.73705
  Epoch 016 - train 0.57562 | val 0.82464
  Classification -> best τ=0.545 (val F1=0.2365)
  Directional -> Accuracy: 0.5532, MCC: 0.1751, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61814 | val 1.97091
  Epoch 016 - train 0.58636 | val 1.87701
  Classification -> best τ=0.355 (val F1=0.1283)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52075 | val 0.81945
  Epoch 019 - train 0.47235 | val 0.98420
  Classification -> best τ=0.450 (val F1=0.4041)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55994 | val 0.73388
  Epoch 016 - train 0.49139 | val 0.85642
  Classification -> best τ=0.470 (val F1=0.0526)
  Directional -> Accuracy: 0.5319, MCC: 0.0764, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61215 | val 0.84489
  Epoch 016 - train 0.55978 | val 0.86487
  Classification -> best τ=0.560 (val F1=0.1109)
  Directional -> Accuracy: 0.5652, MCC: 0.0575, F1: 0.3750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57201 | val 0.93454
  Epoch 016 - train 0.52607 | val 1.62371
  Classification -> best τ=0.515 (val F1=0.1502)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58124 | val 0.77512
  Epoch 016 - train 0.52996 | val 0.90085
  Classification -> best τ=0.545 (val F1=0.2881)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55527 | val 0.83387
  Epoch 016 - train 0.52842 | val 0.77551
  Classification -> best τ=0.470 (val F1=0.1717)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56865 | val 1.79687
  Epoch 016 - train 0.51680 | val 2.66562
  Classification -> best τ=0.570 (val F1=0.1147)
  Directional -> Accuracy: 0.4400, MCC: -0.0963, F1: 0.5172

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55418 | val 1.69582
  Epoch 016 - train 0.50056 | val 2.21154
  Classification -> best τ=0.430 (val F1=0.1421)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55769 | val 1.07951
  Epoch 016 - train 0.51972 | val 1.28706
  Classification -> best τ=0.490 (val F1=0.1711)
  Directional -> Accuracy: 0.6047, MCC: 0.1753, F1: 0.4138

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62113 | val 0.65915
  Epoch 020 - train 0.53329 | val 0.65571
  Epoch 030 - train 0.47810 | val 0.64905
  Epoch 037 - train 0.46807 | val 0.66450
  Classification -> best τ=0.395 (val F1=0.3358)
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57151 | val 0.88708
  Epoch 016 - train 0.49591 | val 1.07699
  Classification -> best τ=0.535 (val F1=0.0339)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56787 | val 0.87046
  Epoch 018 - train 0.53756 | val 0.89443
  Classification -> best τ=0.505 (val F1=0.2951)
  Directional -> Accuracy: 0.5429, MCC: 0.0885, F1: 0.5556

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58738 | val 1.92176
  Epoch 016 - train 0.57156 | val 2.15729
  Classification -> best τ=0.550 (val F1=0.1857)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58755 | val 1.63371
  Epoch 016 - train 0.55962 | val 2.18348
  Classification -> best τ=0.480 (val F1=0.1217)
  Directional -> Accuracy: 0.6053, MCC: 0.0354, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57625 | val 1.23092
  Epoch 016 - train 0.53190 | val 1.26548
  Classification -> best τ=0.500 (val F1=0.1356)
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58550 | val 0.66741
  Epoch 020 - train 0.52159 | val 0.68632
  Epoch 024 - train 0.46231 | val 0.69169
  Classification -> best τ=0.380 (val F1=0.2609)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56359 | val 1.21029
  Epoch 016 - train 0.50507 | val 0.95062
  Classification -> best τ=0.535 (val F1=0.0788)
  Directional -> Accuracy: 0.4375, MCC: -0.0348, F1: 0.4000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60109 | val 1.24580
  Epoch 016 - train 0.56237 | val 1.34036
  Classification -> best τ=0.530 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61184 | val 0.80173
  Epoch 018 - train 0.55575 | val 0.99471
  Classification -> best τ=0.560 (val F1=0.2554)
  Directional -> Accuracy: 0.5000, MCC: 0.1462, F1: 0.2927

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61295 | val 0.81868
  Epoch 016 - train 0.56822 | val 0.84478
  Classification -> best τ=0.465 (val F1=0.1318)
  Directional -> Accuracy: 0.5303, MCC: 0.0859, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57627 | val 0.66693
  Epoch 019 - train 0.52083 | val 0.71499
  Classification -> best τ=0.520 (val F1=0.4149)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50611 | val 0.72454
  Epoch 016 - train 0.51936 | val 0.77622
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60562 | val 0.74853
  Epoch 020 - train 0.56386 | val 0.70937
  Epoch 030 - train 0.45823 | val 0.73644
  Epoch 034 - train 0.44678 | val 0.76594
  Classification -> best τ=0.435 (val F1=0.2603)
  Directional -> Accuracy: 0.5814, MCC: 0.0789, F1: 0.7000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57908 | val 1.09594
  Epoch 016 - train 0.55921 | val 1.38225
  Classification -> best τ=0.480 (val F1=0.1099)
  Directional -> Accuracy: 0.5789, MCC: 0.1250, F1: 0.6571

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60431 | val 0.70168
  Epoch 016 - train 0.54439 | val 0.81973
  Classification -> best τ=0.455 (val F1=0.1141)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57067 | val 0.97560
  Epoch 016 - train 0.53850 | val 1.35934
  Classification -> best τ=0.525 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59808 | val 0.88207
  Epoch 016 - train 0.58213 | val 1.23798
  Classification -> best τ=0.530 (val F1=0.0497)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57590 | val 0.92378
  Epoch 016 - train 0.54010 | val 1.06467
  Classification -> best τ=0.485 (val F1=0.1329)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56581 | val 0.66877
  Epoch 019 - train 0.50413 | val 1.18689
  Classification -> best τ=0.240 (val F1=0.3602)
  Directional -> Accuracy: 0.5753, MCC: 0.1536, F1: 0.5974

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.57108 | val 0.74724
  Epoch 016 - train 0.51863 | val 0.97403
  Classification -> best τ=0.510 (val F1=0.2357)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6545

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57095 | val 1.12824
  Epoch 016 - train 0.51523 | val 1.26666
  Classification -> best τ=0.590 (val F1=0.2503)
  Directional -> Accuracy: 0.5682, MCC: 0.1412, F1: 0.5778

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54814 | val 0.80802
  Epoch 016 - train 0.52597 | val 0.84135
  Classification -> best τ=0.455 (val F1=0.3767)
  Directional -> Accuracy: 0.5373, MCC: 0.2245, F1: 0.3673

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54052 | val 0.73139
  Epoch 016 - train 0.50464 | val 1.06337
  Classification -> best τ=0.495 (val F1=0.3300)
  Directional -> Accuracy: 0.5116, MCC: 0.0318, F1: 0.4324

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56182 | val 1.21848
  Epoch 016 - train 0.51476 | val 1.58649
  Classification -> best τ=0.435 (val F1=0.1590)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52107 | val 1.34778
  Epoch 016 - train 0.46762 | val 1.68955
  Classification -> best τ=0.500 (val F1=0.3014)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55732 | val 0.62415
  Epoch 020 - train 0.52298 | val 0.66793
  Epoch 026 - train 0.49672 | val 0.68455
  Classification -> best τ=0.340 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58290 | val 0.77661
  Epoch 016 - train 0.55872 | val 0.99474
  Classification -> best τ=0.550 (val F1=0.0200)
  Directional -> Accuracy: 0.5000, MCC: 0.1560, F1: 0.0952

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57446 | val 1.06489
  Epoch 017 - train 0.49867 | val 1.70431
  Classification -> best τ=0.390 (val F1=0.2725)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60326 | val 0.71633
  Epoch 016 - train 0.57230 | val 0.77637
  Classification -> best τ=0.470 (val F1=0.0171)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56140 | val 0.78798
  Epoch 016 - train 0.51027 | val 0.99897
  Classification -> best τ=0.535 (val F1=0.2433)
  Directional -> Accuracy: 0.4091, MCC: -0.1283, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58005 | val 0.73835
  Epoch 016 - train 0.55218 | val 0.91478
  Classification -> best τ=0.515 (val F1=0.3162)
  Directional -> Accuracy: 0.4082, MCC: -0.2589, F1: 0.2162

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59431 | val 1.64863
  Epoch 016 - train 0.55886 | val 1.51512
  Classification -> best τ=0.480 (val F1=0.0027)
  Directional -> Accuracy: 0.4464, MCC: -0.1474, F1: 0.5507

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56696 | val 1.34794
  Epoch 016 - train 0.52774 | val 1.63653
  Classification -> best τ=0.485 (val F1=0.4000)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56109 | val 1.61240
  Epoch 016 - train 0.56068 | val 1.73801
  Classification -> best τ=0.525 (val F1=0.2078)
  Directional -> Accuracy: 0.5185, MCC: 0.0155, F1: 0.6486

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58262 | val 1.44097
  Epoch 016 - train 0.54703 | val 1.39273
  Classification -> best τ=0.545 (val F1=0.1145)
  Directional -> Accuracy: 0.4821, MCC: -0.0069, F1: 0.0645

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59993 | val 1.31827

[I 2026-02-19 22:59:49,943] Trial 7 finished with value: 0.19808678615576628 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.0008373202516591288, 'weight_decay': 6.844126812131721e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.3813922184891096, 'early_stopping_min_delta': 0.006650627988751882}. Best is trial 1 with value: 0.2248100499162296.

  Epoch 016 - train 0.53786 | val 1.71348
  Classification -> best τ=0.495 (val F1=0.0819)
  Directional -> Accuracy: 0.4098, MCC: -0.1771, F1: 0.4194

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19808678615576628
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61182 | val 0.72494
  Epoch 016 - train 0.58328 | val 0.85647
  Classification -> best τ=0.680 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0149, F1: 0.0541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56991 | val 0.69525
  Epoch 011 - train 0.56407 | val 0.70458
  Classification -> best τ=0.455 (val F1=0.0805)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62990 | val 0.72239
  Epoch 015 - train 0.60512 | val 0.80320
  Classification -> best τ=0.510 (val F1=0.2616)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60571 | val 2.27513
  Epoch 011 - train 0.60219 | val 2.35552
  Classification -> best τ=0.490 (val F1=0.1413)
  Directional -> Accuracy: 0.5067, MCC: 0.1052, F1: 0.3019

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57338 | val 0.62780
  Epoch 019 - train 0.51845 | val 0.74492
  Classification -> best τ=0.425 (val F1=0.4458)
  Directional -> Accuracy: 0.5686, MCC: 0.2143, F1: 0.7105

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57491 | val 0.76074
  Epoch 011 - train 0.56802 | val 0.80671
  Classification -> best τ=0.485 (val F1=0.0619)
  Directional -> Accuracy: 0.5319, MCC: 0.0745, F1: 0.5926

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61255 | val 0.81649
  Epoch 011 - train 0.60678 | val 0.83578
  Classification -> best τ=0.535 (val F1=0.0809)
  Directional -> Accuracy: 0.5072, MCC: 0.0835, F1: 0.5405

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57952 | val 0.77949
  Epoch 011 - train 0.57312 | val 0.80153
  Classification -> best τ=0.525 (val F1=0.1266)
  Directional -> Accuracy: 0.5682, MCC: -0.0066, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60738 | val 0.68994
  Epoch 011 - train 0.60247 | val 0.69151
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57718 | val 0.77353
  Epoch 011 - train 0.57151 | val 0.77559
  Classification -> best τ=0.505 (val F1=0.2241)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59276 | val 0.90337
  Epoch 011 - train 0.58765 | val 0.98517
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57773 | val 1.24398
  Epoch 011 - train 0.57227 | val 1.37198
  Classification -> best τ=0.460 (val F1=0.1026)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56914 | val 0.95511
  Epoch 011 - train 0.56428 | val 1.03739
  Classification -> best τ=0.485 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61328 | val 0.65837
  Epoch 017 - train 0.57772 | val 0.74145
  Classification -> best τ=0.420 (val F1=0.3358)
  Directional -> Accuracy: 0.5574, MCC: 0.1142, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59765 | val 0.79948
  Epoch 011 - train 0.59187 | val 0.84649
  Classification -> best τ=0.485 (val F1=0.0952)
  Directional -> Accuracy: 0.5769, MCC: 0.2160, F1: 0.1538

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57536 | val 0.82042
  Epoch 013 - train 0.55699 | val 0.86414
  Classification -> best τ=0.430 (val F1=0.2605)
  Directional -> Accuracy: 0.5714, MCC: 0.1869, F1: 0.7170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60910 | val 1.64156
  Epoch 011 - train 0.60522 | val 1.77901
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60489 | val 1.74441
  Epoch 011 - train 0.60048 | val 1.86205
  Classification -> best τ=0.500 (val F1=0.1231)
  Directional -> Accuracy: 0.5395, MCC: 0.1643, F1: 0.5070

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58954 | val 0.82144
  Epoch 011 - train 0.58323 | val 0.84786
  Classification -> best τ=0.565 (val F1=0.2249)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58648 | val 0.75772
  Epoch 013 - train 0.56798 | val 0.75412
  Classification -> best τ=0.500 (val F1=0.2366)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59773 | val 0.80286
  Epoch 011 - train 0.59080 | val 0.86356
  Classification -> best τ=0.540 (val F1=0.0754)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61326 | val 0.82803
  Epoch 011 - train 0.60850 | val 0.85508
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62567 | val 0.70293
  Epoch 011 - train 0.62110 | val 0.70631
  Classification -> best τ=0.535 (val F1=0.1280)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59251 | val 1.14181
  Epoch 011 - train 0.58631 | val 1.19798
  Classification -> best τ=0.475 (val F1=0.2666)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60707 | val 0.65807
  Epoch 019 - train 0.55942 | val 0.68173
  Classification -> best τ=0.520 (val F1=0.4436)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57793 | val 0.70374
  Epoch 011 - train 0.57216 | val 0.70730
  Classification -> best τ=0.495 (val F1=0.2294)
  Directional -> Accuracy: 0.4565, MCC: 0.0541, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61402 | val 0.79439
  Epoch 011 - train 0.60968 | val 0.83399
  Classification -> best τ=0.520 (val F1=0.0680)
  Directional -> Accuracy: 0.4651, MCC: -0.1265, F1: 0.5660

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59504 | val 0.74140
  Epoch 015 - train 0.56450 | val 0.86878
  Classification -> best τ=0.475 (val F1=0.2224)
  Directional -> Accuracy: 0.5439, MCC: 0.0657, F1: 0.6061

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59500 | val 0.69579
  Epoch 011 - train 0.58874 | val 0.69942
  Classification -> best τ=0.505 (val F1=0.0801)
  Directional -> Accuracy: 0.4390, MCC: -0.1114, F1: 0.4103

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59185 | val 0.74858
  Epoch 011 - train 0.58727 | val 0.78004
  Classification -> best τ=0.485 (val F1=0.1869)
  Directional -> Accuracy: 0.5116, MCC: 0.0074, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61887 | val 0.70736
  Epoch 011 - train 0.61482 | val 0.72121
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56828 | val 0.75142
  Epoch 014 - train 0.54783 | val 0.84736
  Classification -> best τ=0.585 (val F1=0.2320)
  Directional -> Accuracy: 0.4400, MCC: -0.0898, F1: 0.2222

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60721 | val 0.64236
  Epoch 017 - train 0.56428 | val 0.80354
  Classification -> best τ=0.475 (val F1=0.3773)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59461 | val 0.71047
  Epoch 011 - train 0.58977 | val 0.71853
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60105 | val 0.86160
  Epoch 011 - train 0.59647 | val 0.91039
  Classification -> best τ=0.550 (val F1=0.0212)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56177 | val 0.76774
  Epoch 011 - train 0.55547 | val 0.77421
  Classification -> best τ=0.480 (val F1=0.3166)
  Directional -> Accuracy: 0.5224, MCC: 0.2288, F1: 0.3043

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59796 | val 0.68272
  Epoch 017 - train 0.55228 | val 0.73425
  Classification -> best τ=0.490 (val F1=0.3264)
  Directional -> Accuracy: 0.6047, MCC: 0.2270, F1: 0.5405

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57993 | val 1.27472
  Epoch 013 - train 0.56536 | val 1.49915
  Classification -> best τ=0.440 (val F1=0.1803)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56075 | val 0.99930
  Epoch 011 - train 0.55468 | val 1.11131
  Classification -> best τ=0.470 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59665 | val 0.68360
  Epoch 020 - train 0.53771 | val 0.64985
  Epoch 030 - train 0.49426 | val 0.64496
  Epoch 036 - train 0.47280 | val 0.65361
  Classification -> best τ=0.325 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59661 | val 0.72912
  Epoch 011 - train 0.59152 | val 0.73777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59049 | val 0.86484
  Epoch 014 - train 0.56874 | val 0.98075
  Classification -> best τ=0.490 (val F1=0.3140)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59806 | val 0.68883
  Epoch 017 - train 0.56372 | val 0.88180
  Classification -> best τ=0.460 (val F1=0.3855)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58429 | val 0.71061
  Epoch 011 - train 0.57823 | val 0.71968
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60770 | val 0.73214
  Epoch 011 - train 0.60261 | val 0.73956
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61057 | val 1.18417
  Epoch 011 - train 0.60652 | val 1.31209
  Classification -> best τ=0.540 (val F1=0.0533)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58622 | val 0.96485
  Epoch 011 - train 0.58132 | val 1.02819
  Classification -> best τ=0.550 (val F1=0.2962)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59699 | val 1.32275
  Epoch 011 - train 0.59237 | val 1.50150
  Classification -> best τ=0.490 (val F1=0.2357)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59509 | val 1.05472
  Epoch 011 - train 0.58963 | val 1.13573
  Classification -> best τ=0.495 (val F1=0.0366)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61171 | val 1.01179
  Epoch 011 - train 0.60738 | val 1.12415

[I 2026-02-19 23:01:39,307] Trial 8 finished with value: 0.17494596620486025 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.00012868586650999762, 'weight_decay': 7.358505744661562e-07, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.8822594883731023, 'early_stopping_min_delta': 0.005422931442830053}. Best is trial 1 with value: 0.2248100499162296.

  Classification -> best τ=0.450 (val F1=0.2617)
  Directional -> Accuracy: 0.5246, MCC: 0.0130, F1: 0.1212

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.17494596620486025
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66579 | val 0.71329
  Epoch 011 - train 0.66459 | val 0.71092
  Classification -> best τ=0.520 (val F1=0.1810)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64258 | val 0.67824
  Epoch 020 - train 0.61891 | val 0.70427
  Classification -> best τ=0.490 (val F1=0.2389)
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67408 | val 0.70828
  Epoch 011 - train 0.67316 | val 0.70675
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66073 | val 0.78692
  Epoch 011 - train 0.65950 | val 0.79714
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65039 | val 0.68277
  Epoch 017 - train 0.63308 | val 0.70084
  Classification -> best τ=0.400 (val F1=0.4427)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65578 | val 0.72060
  Epoch 011 - train 0.65280 | val 0.73702
  Classification -> best τ=0.475 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: -0.0237, F1: 0.4545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65927 | val 0.69508
  Epoch 011 - train 0.65716 | val 0.69649
  Classification -> best τ=0.535 (val F1=0.1239)
  Directional -> Accuracy: 0.6232, MCC: 0.2091, F1: 0.1333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64995 | val 0.75875
  Epoch 011 - train 0.64887 | val 0.76374
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68684 | val 0.71472
  Epoch 011 - train 0.68527 | val 0.71859
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66004 | val 0.73874
  Epoch 011 - train 0.65847 | val 0.74056
  Classification -> best τ=0.455 (val F1=0.0828)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67078 | val 0.68659
  Epoch 011 - train 0.66964 | val 0.68747
  Classification -> best τ=0.460 (val F1=0.2041)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66678 | val 0.88116
  Epoch 011 - train 0.66528 | val 0.89519
  Classification -> best τ=0.445 (val F1=0.1982)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64781 | val 0.67009
  Epoch 011 - train 0.64461 | val 0.67081
  Classification -> best τ=0.560 (val F1=0.0538)
  Directional -> Accuracy: 0.4651, MCC: -0.0570, F1: 0.4651

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66462 | val 0.67219
  Epoch 020 - train 0.64277 | val 0.65357
  Epoch 030 - train 0.62537 | val 0.64024
  Classification -> best τ=0.405 (val F1=0.1743)
  Directional -> Accuracy: 0.5738, MCC: 0.1512, F1: 0.6389

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66986 | val 0.90872
  Epoch 011 - train 0.66880 | val 0.94537
  Classification -> best τ=0.505 (val F1=0.2952)
  Directional -> Accuracy: 0.5000, MCC: -0.0120, F1: 0.4348

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65344 | val 0.67056
  Epoch 015 - train 0.63954 | val 0.67867
  Classification -> best τ=0.570 (val F1=0.2427)
  Directional -> Accuracy: 0.5857, MCC: 0.2052, F1: 0.5397

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66132 | val 0.86685
  Epoch 011 - train 0.66024 | val 0.88360
  Classification -> best τ=0.480 (val F1=0.2673)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66142 | val 0.75803
  Epoch 011 - train 0.66042 | val 0.76205
  Classification -> best τ=0.505 (val F1=0.0930)
  Directional -> Accuracy: 0.6184, MCC: 0.1430, F1: 0.7603

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64283 | val 0.68880
  Epoch 014 - train 0.63495 | val 0.69577
  Classification -> best τ=0.520 (val F1=0.2249)
  Directional -> Accuracy: 0.4615, MCC: 0.1262, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64958 | val 0.69610
  Epoch 011 - train 0.64683 | val 0.69842
  Classification -> best τ=0.470 (val F1=0.2047)
  Directional -> Accuracy: 0.4133, MCC: -0.1968, F1: 0.4884

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68621 | val 0.80812
  Epoch 011 - train 0.68456 | val 0.82700
  Classification -> best τ=0.455 (val F1=0.1685)
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66070 | val 0.73436
  Epoch 011 - train 0.65955 | val 0.73810
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67170 | val 0.69661
  Epoch 016 - train 0.66185 | val 0.71214
  Classification -> best τ=0.435 (val F1=0.1956)
  Directional -> Accuracy: 0.5690, MCC: 0.0711, F1: 0.6835

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65301 | val 0.80515
  Epoch 011 - train 0.65209 | val 0.81150
  Classification -> best τ=0.490 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0018, F1: 0.4923

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66375 | val 0.66783
  Epoch 020 - train 0.64301 | val 0.64959
  Epoch 030 - train 0.62577 | val 0.63998
  Classification -> best τ=0.525 (val F1=0.4795)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64819 | val 0.70764
  Epoch 011 - train 0.64662 | val 0.71309
  Classification -> best τ=0.495 (val F1=0.2774)
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.2308

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66684 | val 0.69164
  Epoch 011 - train 0.66581 | val 0.69246
  Classification -> best τ=0.525 (val F1=0.0364)
  Directional -> Accuracy: 0.5116, MCC: -0.0276, F1: 0.6038

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66498 | val 0.66125
  Epoch 020 - train 0.64038 | val 0.66120
  Epoch 022 - train 0.63773 | val 0.66179
  Classification -> best τ=0.540 (val F1=0.3287)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65637 | val 0.69133
  Epoch 011 - train 0.65399 | val 0.69152
  Classification -> best τ=0.530 (val F1=0.0452)
  Directional -> Accuracy: 0.4390, MCC: -0.1322, F1: 0.4889

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65530 | val 0.72081
  Epoch 011 - train 0.65372 | val 0.72657
  Classification -> best τ=0.535 (val F1=0.1869)
  Directional -> Accuracy: 0.5814, MCC: 0.2261, F1: 0.3077

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66749 | val 0.77841
  Epoch 011 - train 0.66650 | val 0.79223
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65208 | val 0.70344
  Epoch 011 - train 0.64882 | val 0.70695
  Classification -> best τ=0.515 (val F1=0.1191)
  Directional -> Accuracy: 0.4800, MCC: -0.1191, F1: 0.6176

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65487 | val 0.65952
  Epoch 020 - train 0.62990 | val 0.64590
  Epoch 030 - train 0.60963 | val 0.64079
  Classification -> best τ=0.250 (val F1=0.3809)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68560 | val 0.70690
  Epoch 011 - train 0.68433 | val 0.71009
  Classification -> best τ=0.450 (val F1=0.1826)
  Directional -> Accuracy: 0.5789, MCC: 0.2928, F1: 0.7037

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69122 | val 0.77257
  Epoch 011 - train 0.68992 | val 0.78150
  Classification -> best τ=0.555 (val F1=0.1376)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63876 | val 0.70316
  Epoch 016 - train 0.62635 | val 0.71437
  Classification -> best τ=0.380 (val F1=0.3767)
  Directional -> Accuracy: 0.5224, MCC: 0.1091, F1: 0.4483

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65787 | val 0.67596
  Epoch 020 - train 0.63018 | val 0.67663
  Classification -> best τ=0.465 (val F1=0.4001)
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64124 | val 0.68658
  Epoch 016 - train 0.63075 | val 0.69770
  Classification -> best τ=0.435 (val F1=0.1983)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67010 | val 0.71887
  Epoch 011 - train 0.66886 | val 0.72418
  Classification -> best τ=0.525 (val F1=0.0118)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67048 | val 0.69788
  Epoch 020 - train 0.64555 | val 0.66607
  Epoch 030 - train 0.62654 | val 0.64835
  Classification -> best τ=0.425 (val F1=0.3286)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66432 | val 0.69644
  Epoch 011 - train 0.66308 | val 0.69758
  Classification -> best τ=0.510 (val F1=0.3030)
  Directional -> Accuracy: 0.4737, MCC: -0.0315, F1: 0.3333

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64900 | val 0.71939
  Epoch 011 - train 0.64792 | val 0.72043
  Classification -> best τ=0.510 (val F1=0.1849)
  Directional -> Accuracy: 0.5467, MCC: 0.1305, F1: 0.6531

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67208 | val 0.69855
  Epoch 011 - train 0.67092 | val 0.70089
  Classification -> best τ=0.470 (val F1=0.0031)
  Directional -> Accuracy: 0.5106, MCC: 0.1443, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65661 | val 0.69438
  Epoch 011 - train 0.65463 | val 0.69732
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66818 | val 0.76005
  Epoch 011 - train 0.66707 | val 0.76987
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67257 | val 0.84102
  Epoch 011 - train 0.67172 | val 0.85683
  Classification -> best τ=0.540 (val F1=0.2111)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66302 | val 0.76667
  Epoch 011 - train 0.66194 | val 0.77490
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66812 | val 0.69201
  Epoch 015 - train 0.65750 | val 0.70427
  Classification -> best τ=0.530 (val F1=0.0674)
  Directional -> Accuracy: 0.5741, MCC: 0.2113, F1: 0.4103

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65847 | val 0.72604
  Epoch 011 - train 0.65733 | val 0.72933
  Classification -> best τ=0.535 (val F1=0.1076)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66963 | val 0.69588

[I 2026-02-19 23:02:19,682] Trial 9 finished with value: 0.16979096513507477 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 6.306306743531305e-05, 'weight_decay': 1.5475330381119138e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.3048622964862997, 'early_stopping_min_delta': 0.00613210176232726}. Best is trial 1 with value: 0.2248100499162296.

  Epoch 017 - train 0.65839 | val 0.72499
  Classification -> best τ=0.555 (val F1=0.3074)
  Directional -> Accuracy: 0.4754, MCC: -0.0946, F1: 0.2381

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.16979096513507477
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65406 | val 0.72111
  Epoch 020 - train 0.62103 | val 0.74116
  Epoch 027 - train 0.62995 | val 0.72899
  Classification -> best τ=0.575 (val F1=0.2346)
  Directional -> Accuracy: 0.6203, MCC: 0.2301, F1: 0.3478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63729 | val 0.74106
  Epoch 020 - train 0.63031 | val 0.69014
  Epoch 030 - train 0.56520 | val 0.69323
  Classification -> best τ=0.490 (val F1=0.1654)
  Directional -> Accuracy: 0.5833, MCC: 0.1240, F1: 0.6774

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69135 | val 0.67365
  Epoch 020 - train 0.66065 | val 0.67850
  Epoch 030 - train 0.63992 | val 0.66705
  Classification -> best τ=0.595 (val F1=0.3077)
  Directional -> Accuracy: 0.5102, MCC: 0.0835, F1: 0.2941

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67706 | val 0.69991
  Epoch 020 - train 0.65805 | val 0.69176
  Epoch 030 - train 0.65646 | val 0.69110
  Classification -> best τ=0.510 (val F1=0.1595)
  Directional -> Accuracy: 0.4805, MCC: -0.0476, F1: 0.5238

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66242 | val 0.66295
  Epoch 020 - train 0.67012 | val 0.64146
  Epoch 030 - train 0.52826 | val 0.77090
  Classification -> best τ=0.505 (val F1=0.4508)
  Directional -> Accuracy: 0.5849, MCC: 0.1640, F1: 0.6207

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67008 | val 0.70696
  Epoch 020 - train 0.62390 | val 0.71944
  Epoch 021 - train 0.64259 | val 0.71754
  Classification -> best τ=0.505 (val F1=0.0310)
  Directional -> Accuracy: 0.5366, MCC: 0.0649, F1: 0.4865

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69949 | val 0.69786
  Epoch 020 - train 0.67469 | val 0.70034
  Epoch 030 - train 0.65558 | val 0.68224
  Classification -> best τ=0.440 (val F1=0.3057)
  Directional -> Accuracy: 0.4507, MCC: -0.0265, F1: 0.5063

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62338 | val 0.84711
  Epoch 020 - train 0.57254 | val 1.05461
  Epoch 030 - train 0.55412 | val 1.36858
  Classification -> best τ=0.685 (val F1=0.1936)
  Directional -> Accuracy: 0.4681, MCC: -0.0282, F1: 0.4681

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63522 | val 0.70866
  Epoch 020 - train 0.60293 | val 0.83349
  Epoch 030 - train 0.53577 | val 0.71714
  Classification -> best τ=0.380 (val F1=0.3603)
  Directional -> Accuracy: 0.5581, MCC: 0.1042, F1: 0.4865

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66986 | val 0.74447
  Epoch 020 - train 0.65338 | val 0.73424
  Epoch 030 - train 0.60044 | val 0.70393
  Classification -> best τ=0.475 (val F1=0.2082)
  Directional -> Accuracy: 0.5278, MCC: 0.0680, F1: 0.5143

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66169 | val 0.76488
  Epoch 020 - train 0.65737 | val 0.91249
  Epoch 030 - train 0.62256 | val 0.83872
  Classification -> best τ=0.435 (val F1=0.0356)
  Directional -> Accuracy: 0.4423, MCC: -0.0906, F1: 0.5915

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66608 | val 0.70541
  Epoch 020 - train 0.67778 | val 0.69512
  Epoch 030 - train 0.66289 | val 0.68735
  Classification -> best τ=0.585 (val F1=0.2417)
  Directional -> Accuracy: 0.5500, MCC: 0.1809, F1: 0.2286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61174 | val 0.71879
  Epoch 020 - train 0.61548 | val 0.69512
  Epoch 030 - train 0.61337 | val 0.72302
  Classification -> best τ=0.475 (val F1=0.1689)
  Directional -> Accuracy: 0.4889, MCC: 0.0223, F1: 0.5965

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67394 | val 0.67788
  Epoch 020 - train 0.68521 | val 0.70350
  Epoch 030 - train 0.64731 | val 0.63516
  Classification -> best τ=0.410 (val F1=0.3727)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64857 | val 0.81467
  Epoch 020 - train 0.59680 | val 0.82215
  Epoch 024 - train 0.61444 | val 1.03303
  Classification -> best τ=0.470 (val F1=0.2291)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68625 | val 0.73658
  Epoch 020 - train 0.62532 | val 0.97403
  Epoch 024 - train 0.59169 | val 0.80246
  Classification -> best τ=0.435 (val F1=0.3448)
  Directional -> Accuracy: 0.6667, MCC: 0.3842, F1: 0.7600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65246 | val 0.88049
  Epoch 020 - train 0.61885 | val 0.93248
  Epoch 021 - train 0.60071 | val 0.92211
  Classification -> best τ=0.690 (val F1=0.0979)
  Directional -> Accuracy: 0.4098, MCC: 0.1040, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68801 | val 0.76490
  Epoch 020 - train 0.66820 | val 0.80715
  Epoch 021 - train 0.65866 | val 0.81813
  Classification -> best τ=0.440 (val F1=0.1200)
  Directional -> Accuracy: 0.4359, MCC: -0.1778, F1: 0.5319

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66941 | val 0.66183
  Epoch 020 - train 0.64322 | val 0.68171
  Epoch 027 - train 0.60721 | val 0.69304
  Classification -> best τ=0.390 (val F1=0.3194)
  Directional -> Accuracy: 0.5224, MCC: 0.0684, F1: 0.5294

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67374 | val 0.66891
  Epoch 020 - train 0.62479 | val 0.75004
  Epoch 026 - train 0.56717 | val 0.80714
  Classification -> best τ=0.425 (val F1=0.3464)
  Directional -> Accuracy: 0.4675, MCC: 0.1047, F1: 0.0465

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66664 | val 0.69057
  Epoch 020 - train 0.63648 | val 0.76586
  Epoch 021 - train 0.60755 | val 0.76980
  Classification -> best τ=0.485 (val F1=0.2726)
  Directional -> Accuracy: 0.5600, MCC: 0.0852, F1: 0.6333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69449 | val 0.71620
  Epoch 020 - train 0.68966 | val 0.72752
  Epoch 022 - train 0.69011 | val 0.72154
  Classification -> best τ=0.495 (val F1=0.2798)
  Directional -> Accuracy: 0.4559, MCC: -0.0883, F1: 0.4638

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67811 | val 0.69851
  Epoch 020 - train 0.64744 | val 0.72551
  Epoch 023 - train 0.64312 | val 0.71940
  Classification -> best τ=0.495 (val F1=0.2335)
  Directional -> Accuracy: 0.4833, MCC: 0.0117, F1: 0.4561

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65698 | val 0.69572
  Epoch 020 - train 0.63612 | val 0.73632
  Epoch 030 - train 0.54304 | val 0.80593
  Classification -> best τ=0.565 (val F1=0.1296)
  Directional -> Accuracy: 0.5147, MCC: 0.0277, F1: 0.4923

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67536 | val 0.76004
  Epoch 020 - train 0.60241 | val 0.75103
  Epoch 021 - train 0.61697 | val 0.75327
  Classification -> best τ=0.495 (val F1=0.3859)
  Directional -> Accuracy: 0.5345, MCC: 0.0218, F1: 0.6400

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61466 | val 0.80749
  Epoch 020 - train 0.55672 | val 0.76052
  Epoch 023 - train 0.50818 | val 0.86592
  Classification -> best τ=0.515 (val F1=0.3056)
  Directional -> Accuracy: 0.4694, MCC: 0.1786, F1: 0.6176

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65095 | val 0.69530
  Epoch 020 - train 0.58239 | val 0.69648
  Epoch 023 - train 0.58664 | val 0.70365
  Classification -> best τ=0.535 (val F1=0.1175)
  Directional -> Accuracy: 0.4889, MCC: 0.1424, F1: 0.3429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65768 | val 0.76004
  Epoch 020 - train 0.60352 | val 1.07118
  Epoch 027 - train 0.55263 | val 1.48010
  Classification -> best τ=0.405 (val F1=0.4214)
  Directional -> Accuracy: 0.5254, MCC: 0.2201, F1: 0.3000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62036 | val 0.67053
  Epoch 020 - train 0.61154 | val 0.67634
  Epoch 030 - train 0.53654 | val 0.80319
  Classification -> best τ=0.580 (val F1=0.3458)
  Directional -> Accuracy: 0.5000, MCC: 0.0263, F1: 0.3529

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66055 | val 0.80405
  Epoch 020 - train 0.62094 | val 0.90110
  Epoch 021 - train 0.60035 | val 0.89461
  Classification -> best τ=0.510 (val F1=0.0119)
  Directional -> Accuracy: 0.5217, MCC: 0.0510, F1: 0.6207

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67938 | val 0.74149
  Epoch 020 - train 0.64053 | val 0.73259
  Epoch 025 - train 0.58554 | val 0.76251
  Classification -> best τ=0.675 (val F1=0.2186)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68461 | val 0.70133
  Epoch 020 - train 0.63447 | val 0.69533
  Epoch 028 - train 0.58012 | val 0.72894
  Classification -> best τ=0.365 (val F1=0.2935)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66688 | val 0.64973
  Epoch 020 - train 0.67020 | val 0.69840
  Epoch 030 - train 0.62247 | val 0.66021
  Classification -> best τ=0.425 (val F1=0.3259)
  Directional -> Accuracy: 0.5467, MCC: 0.1701, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62325 | val 0.82930
  Epoch 020 - train 0.56627 | val 0.89931
  Epoch 023 - train 0.58002 | val 0.84761
  Classification -> best τ=0.550 (val F1=0.3477)
  Directional -> Accuracy: 0.5366, MCC: 0.0805, F1: 0.5778

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63780 | val 0.91118
  Epoch 020 - train 0.58502 | val 0.91771
  Epoch 021 - train 0.59572 | val 0.91777
  Classification -> best τ=0.500 (val F1=0.2421)
  Directional -> Accuracy: 0.5217, MCC: 0.1798, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66620 | val 0.78302
  Epoch 020 - train 0.61822 | val 0.80331
  Epoch 021 - train 0.60703 | val 0.81530
  Classification -> best τ=0.345 (val F1=0.2460)
  Directional -> Accuracy: 0.5507, MCC: 0.2601, F1: 0.4151

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64160 | val 0.80769
  Epoch 020 - train 0.57640 | val 0.74137
  Epoch 021 - train 0.56308 | val 0.73775
  Classification -> best τ=0.470 (val F1=0.1839)
  Directional -> Accuracy: 0.4667, MCC: -0.0644, F1: 0.2941

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60644 | val 0.75187
  Epoch 020 - train 0.57957 | val 0.91514
  Epoch 021 - train 0.57453 | val 0.97404
  Classification -> best τ=0.560 (val F1=0.2083)
  Directional -> Accuracy: 0.4915, MCC: -0.0232, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65749 | val 0.73551
  Epoch 020 - train 0.59832 | val 0.73030
  Epoch 028 - train 0.50646 | val 0.90535
  Classification -> best τ=0.340 (val F1=0.3278)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65663 | val 0.78766
  Epoch 020 - train 0.63786 | val 0.72604
  Epoch 023 - train 0.58802 | val 0.80173
  Classification -> best τ=0.510 (val F1=0.1551)
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62886 | val 0.70626
  Epoch 020 - train 0.55208 | val 0.79139
  Epoch 026 - train 0.49870 | val 0.84135
  Classification -> best τ=0.360 (val F1=0.3194)
  Directional -> Accuracy: 0.5122, MCC: 0.0055, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65561 | val 0.96227
  Epoch 020 - train 0.62196 | val 1.23604
  Epoch 024 - train 0.58062 | val 1.51292
  Classification -> best τ=0.510 (val F1=0.1913)
  Directional -> Accuracy: 0.5325, MCC: 0.1654, F1: 0.6842

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66023 | val 0.78265
  Epoch 020 - train 0.63035 | val 0.91123
  Epoch 021 - train 0.63874 | val 0.91389
  Classification -> best τ=0.495 (val F1=0.2962)
  Directional -> Accuracy: 0.5306, MCC: 0.0581, F1: 0.4651

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63209 | val 1.15021
  Epoch 020 - train 0.53684 | val 1.39315
  Epoch 021 - train 0.51457 | val 1.43192
  Classification -> best τ=0.560 (val F1=0.2717)
  Directional -> Accuracy: 0.5957, MCC: 0.1412, F1: 0.6885

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65481 | val 1.00439
  Epoch 020 - train 0.52418 | val 1.07700
  Epoch 021 - train 0.54346 | val 1.07187
  Classification -> best τ=0.435 (val F1=0.0052)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67821 | val 0.67608
  Epoch 020 - train 0.65281 | val 0.67692
  Epoch 030 - train 0.61866 | val 0.68764
  Classification -> best τ=0.565 (val F1=0.2743)
  Directional -> Accuracy: 0.6552, MCC: 0.3350, F1: 0.6429

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66840 | val 1.07205
  Epoch 020 - train 0.63541 | val 1.67686
  Epoch 021 - train 0.62936 | val 1.75964
  Classification -> best τ=0.475 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68307 | val 0.81576
  Epoch 020 - train 0.63535 | val 0.80838
  Epoch 029 - train 0.60897 | val 0.86879
  Classification -> best τ=0.625 (val F1=0.0606)
  Directional -> Accuracy: 0.5893, MCC: 0.1641, F1: 0.6667

[87/88] Processing WMT...


[I 2026-02-19 23:03:18,669] Trial 10 finished with value: 0.2377398798538199 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0073261872277707255, 'weight_decay': 0.0009236142514992792, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.9424556873340237, 'early_stopping_min_delta': 0.00022204186941322075}. Best is trial 10 with value: 0.2377398798538199.

  Epoch 025 - train 0.64454 | val 0.68570
  Classification -> best τ=0.405 (val F1=0.2626)
  Directional -> Accuracy: 0.4762, MCC: -0.0086, F1: 0.6374

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2377398798538199
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66307 | val 0.67877
  Epoch 020 - train 0.65539 | val 0.75269
  Epoch 026 - train 0.62890 | val 0.82674
  Classification -> best τ=0.580 (val F1=0.2346)
  Directional -> Accuracy: 0.5949, MCC: 0.1540, F1: 0.4074

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63127 | val 0.68826
  Epoch 020 - train 0.62155 | val 0.72379
  Epoch 029 - train 0.61203 | val 0.72646
  Classification -> best τ=0.490 (val F1=0.1899)
  Directional -> Accuracy: 0.5833, MCC: 0.1240, F1: 0.6774

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69118 | val 0.67759
  Epoch 020 - train 0.67422 | val 0.63778
  Epoch 030 - train 0.66012 | val 0.64716
  Classification -> best τ=0.480 (val F1=0.4291)
  Directional -> Accuracy: 0.6122, MCC: 0.2698, F1: 0.5366

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68990 | val 0.69989
  Epoch 020 - train 0.65885 | val 0.73253
  Epoch 026 - train 0.65228 | val 0.75869
  Classification -> best τ=0.520 (val F1=0.0122)
  Directional -> Accuracy: 0.5714, MCC: 0.1232, F1: 0.6374

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64986 | val 0.70425
  Epoch 020 - train 0.59363 | val 0.83660
  Epoch 023 - train 0.56112 | val 0.78950
  Classification -> best τ=0.415 (val F1=0.4564)
  Directional -> Accuracy: 0.6604, MCC: 0.3281, F1: 0.6538

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66940 | val 0.69206
  Epoch 020 - train 0.64437 | val 0.73696
  Epoch 030 - train 0.61760 | val 0.73562
  Classification -> best τ=0.475 (val F1=0.2460)
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.6333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69043 | val 0.69515
  Epoch 020 - train 0.68510 | val 0.68128
  Epoch 030 - train 0.67071 | val 0.69168
  Classification -> best τ=0.535 (val F1=0.3474)
  Directional -> Accuracy: 0.5493, MCC: 0.0574, F1: 0.4286

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63740 | val 1.25309
  Epoch 020 - train 0.50638 | val 1.56977
  Epoch 021 - train 0.51394 | val 1.70138
  Classification -> best τ=0.595 (val F1=0.1217)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67343 | val 1.10730
  Epoch 020 - train 0.60189 | val 1.49130
  Epoch 022 - train 0.60353 | val 1.51222
  Classification -> best τ=0.490 (val F1=0.1627)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69301 | val 0.71440
  Epoch 020 - train 0.68090 | val 0.73421
  Epoch 030 - train 0.68371 | val 0.70141
  Classification -> best τ=0.540 (val F1=0.3145)
  Directional -> Accuracy: 0.5139, MCC: 0.0607, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67713 | val 0.74344
  Epoch 020 - train 0.63317 | val 0.77145
  Epoch 021 - train 0.62277 | val 0.84683
  Classification -> best τ=0.480 (val F1=0.1325)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67474 | val 0.71134
  Epoch 020 - train 0.65624 | val 0.72547
  Epoch 022 - train 0.65360 | val 0.73313
  Classification -> best τ=0.580 (val F1=0.2417)
  Directional -> Accuracy: 0.5833, MCC: 0.2596, F1: 0.3243

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65429 | val 0.70479
  Epoch 020 - train 0.58743 | val 0.69469
  Epoch 022 - train 0.53894 | val 0.72412
  Classification -> best τ=0.510 (val F1=0.2641)
  Directional -> Accuracy: 0.4667, MCC: -0.0209, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68277 | val 0.79799
  Epoch 020 - train 0.63061 | val 1.65785
  Epoch 022 - train 0.65441 | val 1.69757
  Classification -> best τ=0.490 (val F1=0.2236)
  Directional -> Accuracy: 0.5079, MCC: 0.0284, F1: 0.6076

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68030 | val 0.67737
  Epoch 020 - train 0.61567 | val 0.76316
  Epoch 029 - train 0.58705 | val 0.70025
  Classification -> best τ=0.535 (val F1=0.3689)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.1429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67078 | val 0.69198
  Epoch 020 - train 0.57583 | val 0.74768
  Epoch 023 - train 0.54930 | val 0.79789
  Classification -> best τ=0.430 (val F1=0.3704)
  Directional -> Accuracy: 0.6667, MCC: 0.3654, F1: 0.7551

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65805 | val 0.96534
  Epoch 020 - train 0.63122 | val 1.21676
  Epoch 021 - train 0.62916 | val 1.20708
  Classification -> best τ=0.565 (val F1=0.0476)
  Directional -> Accuracy: 0.6230, MCC: 0.1263, F1: 0.7527

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68253 | val 0.69388
  Epoch 020 - train 0.67389 | val 0.70995
  Epoch 023 - train 0.65346 | val 0.71763
  Classification -> best τ=0.595 (val F1=0.1083)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69943 | val 0.66483
  Epoch 020 - train 0.65958 | val 0.66576
  Epoch 030 - train 0.67633 | val 0.72164
  Classification -> best τ=0.355 (val F1=0.3402)
  Directional -> Accuracy: 0.5522, MCC: 0.1187, F1: 0.5714

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67268 | val 0.67775
  Epoch 020 - train 0.62798 | val 0.72534
  Epoch 025 - train 0.60334 | val 0.75291
  Classification -> best τ=0.485 (val F1=0.2946)
  Directional -> Accuracy: 0.5065, MCC: 0.1399, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67523 | val 0.77024
  Epoch 020 - train 0.63421 | val 0.92103
  Epoch 023 - train 0.62104 | val 0.92304
  Classification -> best τ=0.595 (val F1=0.2614)
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68557 | val 0.73913
  Epoch 020 - train 0.66851 | val 0.74555
  Epoch 023 - train 0.65795 | val 0.74749
  Classification -> best τ=0.505 (val F1=0.1870)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2917

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69609 | val 0.73175
  Epoch 020 - train 0.65937 | val 0.79163
  Epoch 022 - train 0.63147 | val 0.79648
  Classification -> best τ=0.420 (val F1=0.3224)
  Directional -> Accuracy: 0.5667, MCC: 0.0479, F1: 0.6829

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66950 | val 0.72031
  Epoch 020 - train 0.59442 | val 0.84267
  Epoch 026 - train 0.59483 | val 0.73614
  Classification -> best τ=0.415 (val F1=0.1459)
  Directional -> Accuracy: 0.5294, MCC: 0.0800, F1: 0.6098

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65182 | val 0.71521
  Epoch 020 - train 0.63879 | val 0.74562
  Epoch 021 - train 0.60083 | val 0.74117
  Classification -> best τ=0.560 (val F1=0.4101)
  Directional -> Accuracy: 0.6034, MCC: 0.2080, F1: 0.6230

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60930 | val 0.72495
  Epoch 020 - train 0.54388 | val 1.08180
  Epoch 022 - train 0.52207 | val 1.17945
  Classification -> best τ=0.515 (val F1=0.2124)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64709 | val 0.71596
  Epoch 020 - train 0.60664 | val 0.69640
  Epoch 021 - train 0.60027 | val 0.69687
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66791 | val 0.79188
  Epoch 020 - train 0.59855 | val 1.16404
  Epoch 021 - train 0.60812 | val 1.14589
  Classification -> best τ=0.425 (val F1=0.2240)
  Directional -> Accuracy: 0.4237, MCC: -0.2174, F1: 0.5405

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60364 | val 0.66841
  Epoch 020 - train 0.57775 | val 0.65401
  Epoch 030 - train 0.54731 | val 0.69031
  Classification -> best τ=0.635 (val F1=0.4264)
  Directional -> Accuracy: 0.5227, MCC: 0.0498, F1: 0.5116

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65676 | val 0.76045
  Epoch 020 - train 0.59809 | val 0.88957
  Epoch 023 - train 0.58551 | val 0.90286
  Classification -> best τ=0.570 (val F1=0.1071)
  Directional -> Accuracy: 0.5217, MCC: 0.0442, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66942 | val 0.65282
  Epoch 020 - train 0.62719 | val 0.66330
  Epoch 025 - train 0.63091 | val 0.65558
  Classification -> best τ=0.545 (val F1=0.3248)
  Directional -> Accuracy: 0.5000, MCC: -0.1954, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66833 | val 0.67041
  Epoch 020 - train 0.63013 | val 0.68599
  Epoch 030 - train 0.58796 | val 0.71930
  Classification -> best τ=0.455 (val F1=0.3087)
  Directional -> Accuracy: 0.5192, MCC: 0.0139, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65782 | val 0.66737
  Epoch 020 - train 0.62515 | val 0.66065
  Epoch 028 - train 0.62549 | val 0.74539
  Classification -> best τ=0.705 (val F1=0.3159)
  Directional -> Accuracy: 0.4667, MCC: 0.1467, F1: 0.0909

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63370 | val 0.69757
  Epoch 020 - train 0.65289 | val 0.70249
  Epoch 021 - train 0.63850 | val 0.69951
  Classification -> best τ=0.515 (val F1=0.0374)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69748 | val 0.78294
  Epoch 020 - train 0.62697 | val 0.80720
  Epoch 027 - train 0.56315 | val 0.85333
  Classification -> best τ=0.695 (val F1=0.1818)
  Directional -> Accuracy: 0.6087, MCC: 0.2025, F1: 0.5263

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67400 | val 0.68376
  Epoch 020 - train 0.63909 | val 0.70466
  Epoch 022 - train 0.62830 | val 0.72730
  Classification -> best τ=0.520 (val F1=0.3099)
  Directional -> Accuracy: 0.4203, MCC: -0.1335, F1: 0.4118

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65349 | val 0.96882
  Epoch 020 - train 0.56916 | val 0.96933
  Epoch 022 - train 0.55592 | val 1.05967
  Classification -> best τ=0.425 (val F1=0.1839)
  Directional -> Accuracy: 0.6222, MCC: 0.2882, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61902 | val 0.80571
  Epoch 020 - train 0.56809 | val 0.80274
  Epoch 021 - train 0.57687 | val 0.79156
  Classification -> best τ=0.415 (val F1=0.1667)
  Directional -> Accuracy: 0.5085, MCC: 0.0269, F1: 0.5397

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68405 | val 0.70404
  Epoch 020 - train 0.61842 | val 0.72203
  Epoch 023 - train 0.58386 | val 0.71255
  Classification -> best τ=0.470 (val F1=0.3754)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66287 | val 0.67256
  Epoch 020 - train 0.64491 | val 0.73111
  Epoch 029 - train 0.54132 | val 0.79886
  Classification -> best τ=0.410 (val F1=0.4380)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.4444

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61398 | val 0.76820
  Epoch 020 - train 0.57910 | val 0.76021
  Epoch 022 - train 0.55108 | val 0.79509
  Classification -> best τ=0.475 (val F1=0.4857)
  Directional -> Accuracy: 0.6098, MCC: 0.2220, F1: 0.6000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69503 | val 0.72644
  Epoch 020 - train 0.63379 | val 0.72393
  Epoch 030 - train 0.59575 | val 0.98311
  Classification -> best τ=0.550 (val F1=0.2261)
  Directional -> Accuracy: 0.5195, MCC: 0.0442, F1: 0.4478

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64757 | val 0.88888
  Epoch 020 - train 0.65271 | val 0.84251
  Epoch 022 - train 0.62830 | val 0.83530
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58050 | val 2.01007
  Epoch 020 - train 0.50658 | val 2.11897
  Epoch 023 - train 0.50469 | val 2.50018
  Classification -> best τ=0.635 (val F1=0.3162)
  Directional -> Accuracy: 0.5319, MCC: 0.0952, F1: 0.5217

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63245 | val 0.93638
  Epoch 020 - train 0.58965 | val 0.90666
  Epoch 030 - train 0.49244 | val 1.05071
  Classification -> best τ=0.510 (val F1=0.2193)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68687 | val 0.68575
  Epoch 020 - train 0.70147 | val 0.67200
  Epoch 030 - train 0.68700 | val 0.67570
  Classification -> best τ=0.585 (val F1=0.2688)
  Directional -> Accuracy: 0.5000, MCC: 0.2105, F1: 0.1714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67786 | val 1.13588
  Epoch 020 - train 0.63320 | val 1.33162
  Epoch 022 - train 0.61968 | val 1.26290
  Classification -> best τ=0.655 (val F1=0.3875)
  Directional -> Accuracy: 0.4407, MCC: -0.1215, F1: 0.4000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67124 | val 0.74220
  Epoch 020 - train 0.64188 | val 0.87420
  Epoch 030 - train 0.59122 | val 0.93552
  Classification -> best τ=0.405 (val F1=0.0081)
  Directional -> Accuracy: 0.5536, MCC: 0.1448, F1: 0.7059

[87/88] Processing WMT...


[I 2026-02-19 23:04:14,326] Trial 11 finished with value: 0.24355534062071807 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.009778648566792857, 'weight_decay': 0.0009612278080122574, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.9826986293046538, 'early_stopping_min_delta': 0.000294878230968102}. Best is trial 11 with value: 0.24355534062071807.

  Epoch 028 - train 0.63133 | val 0.71267
  Classification -> best τ=0.430 (val F1=0.2983)
  Directional -> Accuracy: 0.5397, MCC: 0.1182, F1: 0.6234

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24355534062071807
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65088 | val 0.83284
  Epoch 020 - train 0.60350 | val 0.85676
  Epoch 024 - train 0.60812 | val 0.88074
  Classification -> best τ=0.805 (val F1=0.1903)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64922 | val 0.69178
  Epoch 020 - train 0.62092 | val 0.69124
  Epoch 028 - train 0.58309 | val 0.69138
  Classification -> best τ=0.480 (val F1=0.1654)
  Directional -> Accuracy: 0.6042, MCC: 0.1782, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68810 | val 0.70855
  Epoch 020 - train 0.67030 | val 0.74383
  Epoch 022 - train 0.67853 | val 0.72133
  Classification -> best τ=0.465 (val F1=0.2742)
  Directional -> Accuracy: 0.5102, MCC: 0.0835, F1: 0.2941

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67713 | val 0.69611
  Epoch 020 - train 0.65668 | val 0.69744
  Epoch 026 - train 0.65344 | val 0.71180
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64665 | val 0.68700
  Epoch 020 - train 0.57865 | val 0.75444
  Epoch 028 - train 0.54631 | val 0.80448
  Classification -> best τ=0.500 (val F1=0.4836)
  Directional -> Accuracy: 0.6604, MCC: 0.3281, F1: 0.6538

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68952 | val 0.69558
  Epoch 020 - train 0.66971 | val 0.70720
  Epoch 024 - train 0.63057 | val 0.70820
  Classification -> best τ=0.475 (val F1=0.1718)
  Directional -> Accuracy: 0.5366, MCC: 0.1077, F1: 0.5957

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69454 | val 0.68773
  Epoch 020 - train 0.66735 | val 0.67958
  Epoch 030 - train 0.64135 | val 0.74092
  Classification -> best τ=0.440 (val F1=0.3354)
  Directional -> Accuracy: 0.4789, MCC: 0.0634, F1: 0.5542

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58774 | val 0.75498
  Epoch 020 - train 0.58213 | val 0.89615
  Epoch 021 - train 0.54828 | val 0.92367
  Classification -> best τ=0.475 (val F1=0.2191)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67018 | val 0.79661
  Epoch 020 - train 0.60051 | val 1.12521
  Epoch 025 - train 0.55684 | val 1.11667
  Classification -> best τ=0.465 (val F1=0.3603)
  Directional -> Accuracy: 0.6047, MCC: 0.1332, F1: 0.4138

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66244 | val 0.68589
  Epoch 020 - train 0.63848 | val 0.73275
  Epoch 030 - train 0.58753 | val 0.70101
  Classification -> best τ=0.480 (val F1=0.1873)
  Directional -> Accuracy: 0.4444, MCC: -0.0449, F1: 0.5349

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67070 | val 0.73106
  Epoch 020 - train 0.64408 | val 0.70260
  Epoch 025 - train 0.61300 | val 0.72340
  Classification -> best τ=0.485 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69677 | val 0.69376
  Epoch 020 - train 0.66606 | val 0.70134
  Epoch 030 - train 0.65417 | val 0.72362
  Classification -> best τ=0.585 (val F1=0.2345)
  Directional -> Accuracy: 0.6667, MCC: 0.3769, F1: 0.7297

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58510 | val 0.75710
  Epoch 020 - train 0.54647 | val 0.77197
  Epoch 021 - train 0.54221 | val 0.76850
  Classification -> best τ=0.390 (val F1=0.1455)
  Directional -> Accuracy: 0.4444, MCC: -0.0945, F1: 0.5902

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67370 | val 0.65879
  Epoch 020 - train 0.66607 | val 0.76343
  Epoch 022 - train 0.66612 | val 0.76318
  Classification -> best τ=0.455 (val F1=0.3883)
  Directional -> Accuracy: 0.5714, MCC: 0.1431, F1: 0.5714

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64706 | val 0.76091
  Epoch 020 - train 0.64971 | val 0.67258
  Epoch 030 - train 0.56795 | val 0.60845
  Classification -> best τ=0.485 (val F1=0.4699)
  Directional -> Accuracy: 0.4630, MCC: -0.0694, F1: 0.4912

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65490 | val 0.73747
  Epoch 020 - train 0.60003 | val 0.88921
  Epoch 023 - train 0.56407 | val 0.90930
  Classification -> best τ=0.640 (val F1=0.3514)
  Directional -> Accuracy: 0.4444, MCC: -0.1290, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65715 | val 1.03277
  Epoch 020 - train 0.61370 | val 1.19069
  Epoch 021 - train 0.61674 | val 1.20742
  Classification -> best τ=0.495 (val F1=0.2012)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66373 | val 0.70000
  Epoch 020 - train 0.66526 | val 0.81286
  Epoch 026 - train 0.64619 | val 0.80170
  Classification -> best τ=0.480 (val F1=0.1759)
  Directional -> Accuracy: 0.4872, MCC: -0.0827, F1: 0.5833

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65488 | val 0.70164
  Epoch 020 - train 0.66075 | val 0.68157
  Epoch 022 - train 0.61473 | val 0.67854
  Classification -> best τ=0.485 (val F1=0.3105)
  Directional -> Accuracy: 0.5075, MCC: 0.1378, F1: 0.3774

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62852 | val 0.72707
  Epoch 020 - train 0.58904 | val 0.80426
  Epoch 024 - train 0.57501 | val 0.78338
  Classification -> best τ=0.440 (val F1=0.3390)
  Directional -> Accuracy: 0.5844, MCC: 0.1945, F1: 0.5556

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65512 | val 0.67908
  Epoch 020 - train 0.62074 | val 1.17458
  Epoch 025 - train 0.58187 | val 1.18136
  Classification -> best τ=0.470 (val F1=0.3327)
  Directional -> Accuracy: 0.6000, MCC: -0.0243, F1: 0.7436

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69006 | val 0.69073
  Epoch 020 - train 0.68297 | val 0.73512
  Epoch 030 - train 0.64662 | val 0.74395
  Classification -> best τ=0.560 (val F1=0.2369)
  Directional -> Accuracy: 0.4412, MCC: -0.1231, F1: 0.3448

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65876 | val 0.69544
  Epoch 020 - train 0.64534 | val 0.77554
  Epoch 030 - train 0.61329 | val 0.80015
  Classification -> best τ=0.575 (val F1=0.2550)
  Directional -> Accuracy: 0.4167, MCC: -0.0663, F1: 0.1860

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63967 | val 0.71444
  Epoch 020 - train 0.57849 | val 0.77765
  Epoch 023 - train 0.58763 | val 0.85057
  Classification -> best τ=0.475 (val F1=0.1296)
  Directional -> Accuracy: 0.5441, MCC: 0.0908, F1: 0.3111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67024 | val 0.68949
  Epoch 020 - train 0.63668 | val 0.78042
  Epoch 021 - train 0.62316 | val 0.80225
  Classification -> best τ=0.555 (val F1=0.4818)
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58087 | val 0.80648
  Epoch 020 - train 0.52631 | val 0.73787
  Epoch 023 - train 0.49999 | val 0.84434
  Classification -> best τ=0.505 (val F1=0.3056)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67428 | val 0.72531
  Epoch 020 - train 0.60051 | val 0.73209
  Epoch 030 - train 0.56666 | val 0.70349
  Classification -> best τ=0.550 (val F1=0.1410)
  Directional -> Accuracy: 0.5778, MCC: 0.2037, F1: 0.5778

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66217 | val 0.80062
  Epoch 020 - train 0.62842 | val 1.03166
  Epoch 021 - train 0.61402 | val 1.03704
  Classification -> best τ=0.415 (val F1=0.2240)
  Directional -> Accuracy: 0.5424, MCC: -0.0089, F1: 0.6824

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63209 | val 0.70751
  Epoch 020 - train 0.54284 | val 0.70552
  Epoch 028 - train 0.48982 | val 0.86143
  Classification -> best τ=0.545 (val F1=0.2365)
  Directional -> Accuracy: 0.5909, MCC: 0.2313, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66391 | val 0.73772
  Epoch 020 - train 0.63153 | val 0.72908
  Epoch 022 - train 0.59247 | val 0.73091
  Classification -> best τ=0.550 (val F1=0.1712)
  Directional -> Accuracy: 0.5435, MCC: 0.0877, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64746 | val 0.63943
  Epoch 020 - train 0.63623 | val 0.65348
  Epoch 030 - train 0.52422 | val 0.70871
  Classification -> best τ=0.800 (val F1=0.2909)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65633 | val 0.69955
  Epoch 020 - train 0.60113 | val 0.71585
  Epoch 030 - train 0.55253 | val 0.80768
  Classification -> best τ=0.535 (val F1=0.3855)
  Directional -> Accuracy: 0.3654, MCC: -0.2956, F1: 0.4590

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65687 | val 0.67390
  Epoch 020 - train 0.64934 | val 0.71353
  Epoch 023 - train 0.60170 | val 0.70423
  Classification -> best τ=0.405 (val F1=0.3302)
  Directional -> Accuracy: 0.5467, MCC: 0.1288, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66907 | val 0.70994
  Epoch 020 - train 0.64738 | val 0.88763
  Epoch 022 - train 0.60110 | val 0.84190
  Classification -> best τ=0.570 (val F1=0.3427)
  Directional -> Accuracy: 0.5366, MCC: 0.2210, F1: 0.6780

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63365 | val 0.80333
  Epoch 020 - train 0.61624 | val 0.80602
  Epoch 021 - train 0.60376 | val 0.80007
  Classification -> best τ=0.600 (val F1=0.3367)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66059 | val 0.71133
  Epoch 020 - train 0.63960 | val 0.75830
  Epoch 026 - train 0.60490 | val 0.71813
  Classification -> best τ=0.385 (val F1=0.2525)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.7339

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59684 | val 0.99441
  Epoch 020 - train 0.58392 | val 1.04765
  Epoch 021 - train 0.57960 | val 1.02532
  Classification -> best τ=0.445 (val F1=0.2351)
  Directional -> Accuracy: 0.6000, MCC: 0.1996, F1: 0.6087

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60127 | val 0.78608
  Epoch 020 - train 0.57442 | val 0.95801
  Epoch 021 - train 0.55926 | val 0.99387
  Classification -> best τ=0.515 (val F1=0.1105)
  Directional -> Accuracy: 0.4915, MCC: -0.0196, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65095 | val 0.83617
  Epoch 020 - train 0.58255 | val 1.03894
  Epoch 021 - train 0.54337 | val 1.05463
  Classification -> best τ=0.495 (val F1=0.3260)
  Directional -> Accuracy: 0.5714, MCC: 0.0127, F1: 0.6957

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65101 | val 0.68000
  Epoch 020 - train 0.57101 | val 0.72045
  Epoch 026 - train 0.54825 | val 0.71759
  Classification -> best τ=0.420 (val F1=0.3246)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64700 | val 0.68487
  Epoch 020 - train 0.62345 | val 0.78053
  Epoch 030 - train 0.55097 | val 0.89162
  Classification -> best τ=0.455 (val F1=0.3568)
  Directional -> Accuracy: 0.5122, MCC: 0.0290, F1: 0.4737

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65333 | val 0.75170
  Epoch 020 - train 0.58228 | val 0.97241
  Epoch 021 - train 0.59828 | val 0.94886
  Classification -> best τ=0.485 (val F1=0.0369)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63961 | val 0.81113
  Epoch 020 - train 0.62632 | val 0.84507
  Epoch 021 - train 0.60780 | val 0.86088
  Classification -> best τ=0.595 (val F1=0.2433)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62621 | val 1.66226
  Epoch 020 - train 0.52933 | val 2.13904
  Epoch 021 - train 0.51835 | val 2.25598
  Classification -> best τ=0.540 (val F1=0.2282)
  Directional -> Accuracy: 0.5957, MCC: 0.1905, F1: 0.6275

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64455 | val 1.14086
  Epoch 020 - train 0.55900 | val 1.18631
  Epoch 021 - train 0.53543 | val 1.15639
  Classification -> best τ=0.675 (val F1=0.1425)
  Directional -> Accuracy: 0.6429, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69629 | val 0.70177
  Epoch 020 - train 0.67250 | val 0.70307
  Epoch 030 - train 0.63128 | val 0.66227
  Classification -> best τ=0.550 (val F1=0.2392)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65853 | val 1.29397
  Epoch 020 - train 0.62701 | val 1.27416
  Epoch 021 - train 0.62705 | val 1.29388
  Classification -> best τ=0.675 (val F1=0.2494)
  Directional -> Accuracy: 0.5254, MCC: 0.0702, F1: 0.6216

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65514 | val 0.75995
  Epoch 020 - train 0.62962 | val 0.83418
  Epoch 021 - train 0.63303 | val 0.85972
  Classification -> best τ=0.465 (val F1=0.1211)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...


[I 2026-02-19 23:05:09,650] Trial 12 finished with value: 0.25712235217334833 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.006201788355624423, 'weight_decay': 0.0007808874133903417, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.6183655195208124, 'early_stopping_min_delta': 0.00013778608125491982}. Best is trial 12 with value: 0.25712235217334833.

  Epoch 030 - train 0.62028 | val 0.74134
  Classification -> best τ=0.475 (val F1=0.3276)
  Directional -> Accuracy: 0.4921, MCC: 0.0448, F1: 0.6364

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25712235217334833
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65714 | val 0.67820
  Epoch 020 - train 0.63522 | val 0.79445
  Epoch 026 - train 0.61067 | val 0.80321
  Classification -> best τ=0.830 (val F1=0.2346)
  Directional -> Accuracy: 0.5949, MCC: 0.1703, F1: 0.2381

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66260 | val 0.72641
  Epoch 020 - train 0.60976 | val 0.70054
  Epoch 028 - train 0.56658 | val 0.71631
  Classification -> best τ=0.550 (val F1=0.1654)
  Directional -> Accuracy: 0.5625, MCC: 0.0727, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67425 | val 0.71502
  Epoch 020 - train 0.67625 | val 0.71314
  Epoch 030 - train 0.64189 | val 0.73393
  Classification -> best τ=0.380 (val F1=0.3195)
  Directional -> Accuracy: 0.4898, MCC: -0.0704, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66290 | val 0.69560
  Epoch 020 - train 0.65028 | val 0.69409
  Epoch 021 - train 0.65235 | val 0.69288
  Classification -> best τ=0.480 (val F1=0.1704)
  Directional -> Accuracy: 0.4675, MCC: -0.1155, F1: 0.5773

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67588 | val 0.69614
  Epoch 020 - train 0.61831 | val 0.70077
  Epoch 030 - train 0.54838 | val 1.01242
  Classification -> best τ=0.695 (val F1=0.3686)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64384 | val 0.71276
  Epoch 020 - train 0.60960 | val 0.71293
  Epoch 022 - train 0.62938 | val 0.71664
  Classification -> best τ=0.530 (val F1=0.1350)
  Directional -> Accuracy: 0.5122, MCC: 0.0050, F1: 0.4118

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68122 | val 0.75379
  Epoch 020 - train 0.67767 | val 0.78398
  Epoch 027 - train 0.66358 | val 0.88674
  Classification -> best τ=0.450 (val F1=0.2226)
  Directional -> Accuracy: 0.5915, MCC: 0.1593, F1: 0.5085

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60868 | val 1.45297
  Epoch 020 - train 0.52999 | val 0.92767
  Epoch 025 - train 0.51356 | val 1.43311
  Classification -> best τ=0.585 (val F1=0.2921)
  Directional -> Accuracy: 0.5106, MCC: -0.1424, F1: 0.1481

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63127 | val 0.93395
  Epoch 020 - train 0.58095 | val 1.47562
  Epoch 021 - train 0.55791 | val 1.55933
  Classification -> best τ=0.465 (val F1=0.1217)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68316 | val 0.72942
  Epoch 020 - train 0.63941 | val 0.70048
  Epoch 028 - train 0.60494 | val 0.69110
  Classification -> best τ=0.530 (val F1=0.1973)
  Directional -> Accuracy: 0.5417, MCC: 0.0841, F1: 0.5075

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67918 | val 0.70297
  Epoch 020 - train 0.62261 | val 0.70794
  Epoch 030 - train 0.58959 | val 0.69435
  Classification -> best τ=0.485 (val F1=0.1495)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69835 | val 0.69906
  Epoch 020 - train 0.66869 | val 0.68697
  Epoch 029 - train 0.64900 | val 0.68555
  Classification -> best τ=0.545 (val F1=0.2188)
  Directional -> Accuracy: 0.6000, MCC: 0.3333, F1: 0.7143

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60182 | val 0.67217
  Epoch 020 - train 0.57101 | val 0.68486
  Epoch 030 - train 0.50882 | val 0.67153
  Classification -> best τ=0.525 (val F1=0.4364)
  Directional -> Accuracy: 0.5556, MCC: 0.1786, F1: 0.6429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69758 | val 0.66146
  Epoch 020 - train 0.68249 | val 0.62385
  Epoch 030 - train 0.63785 | val 0.61159
  Classification -> best τ=0.435 (val F1=0.4300)
  Directional -> Accuracy: 0.5079, MCC: 0.0196, F1: 0.5507

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66092 | val 0.84140
  Epoch 020 - train 0.63172 | val 0.74782
  Epoch 027 - train 0.60614 | val 0.84071
  Classification -> best τ=0.450 (val F1=0.3786)
  Directional -> Accuracy: 0.4444, MCC: -0.1310, F1: 0.5946

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67242 | val 0.72222
  Epoch 020 - train 0.60014 | val 0.84373
  Epoch 021 - train 0.58222 | val 0.91683
  Classification -> best τ=0.570 (val F1=0.3512)
  Directional -> Accuracy: 0.5556, MCC: 0.1009, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65704 | val 0.89732
  Epoch 020 - train 0.60646 | val 0.98500
  Epoch 021 - train 0.60067 | val 0.95748
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68720 | val 0.70499
  Epoch 020 - train 0.66434 | val 0.70530
  Epoch 023 - train 0.66882 | val 0.71990
  Classification -> best τ=0.590 (val F1=0.1541)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66871 | val 0.70090
  Epoch 020 - train 0.65504 | val 0.67016
  Epoch 030 - train 0.64837 | val 0.66658
  Classification -> best τ=0.375 (val F1=0.3682)
  Directional -> Accuracy: 0.4776, MCC: 0.0801, F1: 0.3137

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66962 | val 0.70619
  Epoch 020 - train 0.64714 | val 0.74164
  Epoch 030 - train 0.58180 | val 0.78517
  Classification -> best τ=0.450 (val F1=0.2913)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67763 | val 0.81649
  Epoch 020 - train 0.61698 | val 0.78584
  Epoch 022 - train 0.63340 | val 0.77995
  Classification -> best τ=0.575 (val F1=0.3626)
  Directional -> Accuracy: 0.5000, MCC: -0.1854, F1: 0.6479

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67793 | val 0.85331
  Epoch 020 - train 0.68283 | val 0.82340
  Epoch 021 - train 0.68450 | val 0.82657
  Classification -> best τ=0.535 (val F1=0.1997)
  Directional -> Accuracy: 0.5147, MCC: 0.0484, F1: 0.1951

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67875 | val 0.70698
  Epoch 020 - train 0.62873 | val 0.77125
  Epoch 022 - train 0.61884 | val 0.79001
  Classification -> best τ=0.500 (val F1=0.3129)
  Directional -> Accuracy: 0.5667, MCC: 0.0364, F1: 0.6905

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64305 | val 0.71934
  Epoch 020 - train 0.60817 | val 0.72374
  Epoch 025 - train 0.58458 | val 0.73171
  Classification -> best τ=0.500 (val F1=0.1296)
  Directional -> Accuracy: 0.5294, MCC: 0.0580, F1: 0.5152

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68553 | val 0.76257
  Epoch 020 - train 0.61109 | val 0.81539
  Epoch 030 - train 0.51363 | val 1.07872
  Classification -> best τ=0.660 (val F1=0.3797)
  Directional -> Accuracy: 0.4310, MCC: -0.1469, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60123 | val 0.76687
  Epoch 020 - train 0.46686 | val 1.16027
  Epoch 030 - train 0.46775 | val 1.46497
  Classification -> best τ=0.425 (val F1=0.3056)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65783 | val 0.70891
  Epoch 020 - train 0.59250 | val 0.69483
  Epoch 021 - train 0.59485 | val 0.69335
  Classification -> best τ=0.545 (val F1=0.1048)
  Directional -> Accuracy: 0.4444, MCC: 0.0237, F1: 0.2857

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68988 | val 0.73398
  Epoch 020 - train 0.62372 | val 1.01779
  Epoch 021 - train 0.63780 | val 1.03516
  Classification -> best τ=0.390 (val F1=0.1957)
  Directional -> Accuracy: 0.5085, MCC: -0.0917, F1: 0.6506

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66316 | val 0.68893
  Epoch 020 - train 0.56429 | val 0.71127
  Epoch 030 - train 0.51914 | val 0.68097
  Classification -> best τ=0.670 (val F1=0.3458)
  Directional -> Accuracy: 0.5227, MCC: 0.0743, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65169 | val 0.76934
  Epoch 020 - train 0.54723 | val 0.78445
  Epoch 021 - train 0.58862 | val 0.79420
  Classification -> best τ=0.505 (val F1=0.1342)
  Directional -> Accuracy: 0.5217, MCC: 0.0464, F1: 0.5926

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64890 | val 0.63245
  Epoch 020 - train 0.61370 | val 0.70097
  Epoch 030 - train 0.54525 | val 0.64912
  Classification -> best τ=0.710 (val F1=0.2562)
  Directional -> Accuracy: 0.4130, MCC: -0.1818, F1: 0.0690

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66725 | val 0.66952
  Epoch 020 - train 0.64920 | val 0.84725
  Epoch 030 - train 0.59851 | val 0.76368
  Classification -> best τ=0.470 (val F1=0.2935)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66079 | val 0.67918
  Epoch 020 - train 0.65648 | val 0.65991
  Epoch 030 - train 0.62335 | val 0.67421
  Classification -> best τ=0.395 (val F1=0.3302)
  Directional -> Accuracy: 0.5333, MCC: 0.1340, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65388 | val 0.77424
  Epoch 020 - train 0.60508 | val 0.86091
  Epoch 021 - train 0.63082 | val 0.86032
  Classification -> best τ=0.635 (val F1=0.1748)
  Directional -> Accuracy: 0.4390, MCC: -0.1229, F1: 0.5306

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64624 | val 0.87858
  Epoch 020 - train 0.56984 | val 0.91121
  Epoch 021 - train 0.60743 | val 0.91824
  Classification -> best τ=0.495 (val F1=0.2254)
  Directional -> Accuracy: 0.5217, MCC: 0.1453, F1: 0.6333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65739 | val 0.69840
  Epoch 020 - train 0.62601 | val 0.84746
  Epoch 024 - train 0.58590 | val 0.84578
  Classification -> best τ=0.435 (val F1=0.4144)
  Directional -> Accuracy: 0.5942, MCC: 0.1264, F1: 0.6957

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66877 | val 0.71591
  Epoch 020 - train 0.60604 | val 0.70004
  Epoch 021 - train 0.55286 | val 0.70452
  Classification -> best τ=0.495 (val F1=0.2891)
  Directional -> Accuracy: 0.6222, MCC: 0.2436, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64957 | val 0.86585
  Epoch 020 - train 0.58522 | val 0.82808
  Epoch 022 - train 0.58280 | val 0.90019
  Classification -> best τ=0.525 (val F1=0.1768)
  Directional -> Accuracy: 0.4576, MCC: -0.0733, F1: 0.5152

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69096 | val 0.70933
  Epoch 020 - train 0.61664 | val 0.74729
  Epoch 022 - train 0.62439 | val 0.85049
  Classification -> best τ=0.390 (val F1=0.2035)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67775 | val 0.65066
  Epoch 020 - train 0.64679 | val 0.65844
  Epoch 030 - train 0.59884 | val 0.71766
  Classification -> best τ=0.145 (val F1=0.4047)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64214 | val 0.80246
  Epoch 020 - train 0.57081 | val 0.99170
  Epoch 023 - train 0.53684 | val 0.96292
  Classification -> best τ=0.415 (val F1=0.3055)
  Directional -> Accuracy: 0.5366, MCC: 0.1005, F1: 0.6780

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65188 | val 0.83710
  Epoch 020 - train 0.63806 | val 0.82421
  Epoch 022 - train 0.59462 | val 0.83951
  Classification -> best τ=0.595 (val F1=0.1654)
  Directional -> Accuracy: 0.4805, MCC: -0.1162, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67015 | val 1.10903
  Epoch 020 - train 0.65439 | val 1.38118
  Epoch 021 - train 0.64740 | val 1.38990
  Classification -> best τ=0.625 (val F1=0.2400)
  Directional -> Accuracy: 0.4694, MCC: -0.2021, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59925 | val 1.64134
  Epoch 020 - train 0.52309 | val 2.73141
  Epoch 021 - train 0.54733 | val 2.66727
  Classification -> best τ=0.620 (val F1=0.2477)
  Directional -> Accuracy: 0.4255, MCC: -0.0318, F1: 0.0690

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58954 | val 0.79846
  Epoch 020 - train 0.51905 | val 0.95121
  Epoch 021 - train 0.50303 | val 0.97339
  Classification -> best τ=0.645 (val F1=0.1425)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68480 | val 0.66911
  Epoch 020 - train 0.66136 | val 0.66863
  Epoch 030 - train 0.65248 | val 0.65918
  Classification -> best τ=0.520 (val F1=0.2688)
  Directional -> Accuracy: 0.7069, MCC: 0.4345, F1: 0.7018

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65849 | val 1.12099
  Epoch 020 - train 0.61860 | val 1.30868
  Epoch 021 - train 0.61660 | val 1.32050
  Classification -> best τ=0.360 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67680 | val 0.78863
  Epoch 020 - train 0.63636 | val 0.79838
  Epoch 025 - train 0.60355 | val 0.80185
  Classification -> best τ=0.415 (val F1=0.0136)
  Directional -> Accuracy: 0.6071, MCC: 0.2026, F1: 0.6765

[87/88] Processing WMT...


[I 2026-02-19 23:06:06,120] Trial 13 finished with value: 0.24543008221959217 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.009950782939500958, 'weight_decay': 0.0007145481853965206, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.5662225054412384, 'early_stopping_min_delta': 0.0008906312558986675}. Best is trial 12 with value: 0.25712235217334833.

  Epoch 030 - train 0.69597 | val 0.68776
  Classification -> best τ=0.430 (val F1=0.1920)
  Directional -> Accuracy: 0.4762, MCC: -0.0935, F1: 0.2326

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24543008221959217
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67331 | val 1.12831
  Epoch 020 - train 0.61239 | val 1.21013
  Epoch 022 - train 0.63307 | val 1.21013
  Classification -> best τ=0.745 (val F1=0.2018)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65810 | val 0.74015
  Epoch 020 - train 0.61623 | val 0.78113
  Epoch 021 - train 0.61990 | val 0.78243
  Classification -> best τ=0.425 (val F1=0.1386)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69184 | val 0.69315
  Epoch 020 - train 0.63177 | val 0.69464
  Epoch 030 - train 0.61172 | val 0.71095
  Classification -> best τ=0.570 (val F1=0.3592)
  Directional -> Accuracy: 0.5227, MCC: 0.0498, F1: 0.5116

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67701 | val 0.76245
  Epoch 020 - train 0.65175 | val 0.80836
  Epoch 030 - train 0.64310 | val 0.85660
  Classification -> best τ=0.430 (val F1=0.2712)
  Directional -> Accuracy: 0.5556, MCC: 0.0743, F1: 0.6800

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62149 | val 0.70634
  Epoch 020 - train 0.54503 | val 0.70341
  Epoch 025 - train 0.53233 | val 0.78407
  Classification -> best τ=0.460 (val F1=0.4638)
  Directional -> Accuracy: 0.5833, MCC: 0.1871, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64391 | val 0.72383
  Epoch 020 - train 0.59668 | val 0.76538
  Epoch 023 - train 0.61345 | val 0.78214
  Classification -> best τ=0.465 (val F1=0.2392)
  Directional -> Accuracy: 0.4318, MCC: -0.1376, F1: 0.3902

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67817 | val 0.69738
  Epoch 020 - train 0.67574 | val 0.71738
  Epoch 023 - train 0.65093 | val 0.72141
  Classification -> best τ=0.430 (val F1=0.3052)
  Directional -> Accuracy: 0.4848, MCC: 0.1510, F1: 0.5952

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64651 | val 1.90084
  Epoch 020 - train 0.57741 | val 1.84087
  Epoch 021 - train 0.59707 | val 1.82915
  Classification -> best τ=0.600 (val F1=0.1448)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62114 | val 0.95340
  Epoch 020 - train 0.61397 | val 0.98837
  Epoch 021 - train 0.59843 | val 0.99950
  Classification -> best τ=0.520 (val F1=0.2351)
  Directional -> Accuracy: 0.3913, MCC: -0.1757, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62686 | val 0.69546
  Epoch 020 - train 0.58056 | val 0.68816
  Epoch 030 - train 0.54887 | val 0.68574
  Classification -> best τ=0.540 (val F1=0.2413)
  Directional -> Accuracy: 0.4776, MCC: -0.1464, F1: 0.2222

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66014 | val 0.70933
  Epoch 020 - train 0.58393 | val 0.75922
  Epoch 029 - train 0.54498 | val 0.74049
  Classification -> best τ=0.565 (val F1=0.2960)
  Directional -> Accuracy: 0.5106, MCC: -0.1895, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67043 | val 0.74239
  Epoch 020 - train 0.65353 | val 0.79038
  Epoch 021 - train 0.64461 | val 0.79879
  Classification -> best τ=0.475 (val F1=0.1260)
  Directional -> Accuracy: 0.6727, MCC: 0.3418, F1: 0.7000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58736 | val 1.09630
  Epoch 020 - train 0.55337 | val 1.55801
  Epoch 021 - train 0.54511 | val 1.57223
  Classification -> best τ=0.420 (val F1=0.1718)
  Directional -> Accuracy: 0.4583, MCC: -0.0969, F1: 0.6176

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68959 | val 0.75372
  Epoch 020 - train 0.67432 | val 0.76729
  Epoch 024 - train 0.67578 | val 0.81820
  Classification -> best τ=0.405 (val F1=0.3229)
  Directional -> Accuracy: 0.6207, MCC: 0.2529, F1: 0.6944

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63639 | val 0.78507
  Epoch 020 - train 0.60747 | val 0.84443
  Epoch 021 - train 0.60346 | val 0.86284
  Classification -> best τ=0.575 (val F1=0.2630)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64041 | val 0.79562
  Epoch 020 - train 0.58852 | val 0.92766
  Epoch 024 - train 0.56038 | val 0.97014
  Classification -> best τ=0.280 (val F1=0.3164)
  Directional -> Accuracy: 0.5821, MCC: 0.1921, F1: 0.7143

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64928 | val 1.07168
  Epoch 020 - train 0.63842 | val 1.07140
  Epoch 021 - train 0.62581 | val 1.06625
  Classification -> best τ=0.635 (val F1=0.1368)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66751 | val 0.98429
  Epoch 020 - train 0.66025 | val 0.90380
  Epoch 022 - train 0.63940 | val 0.95009
  Classification -> best τ=0.455 (val F1=0.2160)
  Directional -> Accuracy: 0.4658, MCC: -0.0081, F1: 0.4179

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63198 | val 0.74952
  Epoch 020 - train 0.58812 | val 0.88431
  Epoch 021 - train 0.59406 | val 0.89664
  Classification -> best τ=0.470 (val F1=0.2336)
  Directional -> Accuracy: 0.5161, MCC: 0.1949, F1: 0.3478

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63842 | val 0.71299
  Epoch 020 - train 0.58278 | val 0.71110
  Epoch 023 - train 0.57959 | val 0.74197
  Classification -> best τ=0.410 (val F1=0.2582)
  Directional -> Accuracy: 0.5556, MCC: 0.1803, F1: 0.4667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63898 | val 0.77894
  Epoch 020 - train 0.61617 | val 0.80837
  Epoch 021 - train 0.60665 | val 0.80282
  Classification -> best τ=0.455 (val F1=0.2193)
  Directional -> Accuracy: 0.4444, MCC: -0.1273, F1: 0.5098

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67595 | val 0.93761
  Epoch 020 - train 0.65254 | val 1.08299
  Epoch 021 - train 0.66235 | val 1.12741
  Classification -> best τ=0.460 (val F1=0.1168)
  Directional -> Accuracy: 0.5873, MCC: 0.1741, F1: 0.5517

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64596 | val 0.81014
  Epoch 020 - train 0.62765 | val 0.85890
  Epoch 021 - train 0.62978 | val 0.87282
  Classification -> best τ=0.555 (val F1=0.1729)
  Directional -> Accuracy: 0.5636, MCC: 0.0711, F1: 0.6571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64439 | val 0.70697
  Epoch 020 - train 0.62176 | val 0.72887
  Epoch 021 - train 0.61574 | val 0.73802
  Classification -> best τ=0.470 (val F1=0.0201)
  Directional -> Accuracy: 0.5714, MCC: 0.1589, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65220 | val 0.69006
  Epoch 020 - train 0.57189 | val 0.73856
  Epoch 029 - train 0.53592 | val 0.85421
  Classification -> best τ=0.595 (val F1=0.4393)
  Directional -> Accuracy: 0.5472, MCC: 0.1852, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66011 | val 0.74182
  Epoch 020 - train 0.61661 | val 0.77697
  Epoch 021 - train 0.61308 | val 0.77608
  Classification -> best τ=0.565 (val F1=0.1364)
  Directional -> Accuracy: 0.3571, MCC: -0.3443, F1: 0.1818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66056 | val 1.16972
  Epoch 020 - train 0.62624 | val 0.84433
  Epoch 024 - train 0.61148 | val 0.89335
  Classification -> best τ=0.490 (val F1=0.2779)
  Directional -> Accuracy: 0.5208, MCC: 0.0639, F1: 0.5306

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67561 | val 0.75111
  Epoch 020 - train 0.59147 | val 0.75743
  Epoch 021 - train 0.60567 | val 0.76462
  Classification -> best τ=0.425 (val F1=0.2649)
  Directional -> Accuracy: 0.5370, MCC: 0.2101, F1: 0.2857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67818 | val 1.11983
  Epoch 020 - train 0.63251 | val 1.44421
  Epoch 021 - train 0.63026 | val 1.41349
  Classification -> best τ=0.495 (val F1=0.2000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64374 | val 0.70411
  Epoch 020 - train 0.64610 | val 0.85308
  Epoch 024 - train 0.63784 | val 0.86865
  Classification -> best τ=0.655 (val F1=0.0249)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65545 | val 0.65928
  Epoch 020 - train 0.61203 | val 0.65478
  Epoch 030 - train 0.57194 | val 0.70289
  Classification -> best τ=0.430 (val F1=0.3780)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65486 | val 0.75352
  Epoch 020 - train 0.58632 | val 0.80593
  Epoch 024 - train 0.59070 | val 0.81280
  Classification -> best τ=0.390 (val F1=0.3430)
  Directional -> Accuracy: 0.4857, MCC: 0.0268, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63016 | val 0.85086
  Epoch 020 - train 0.62316 | val 0.78434
  Epoch 021 - train 0.61867 | val 0.79168
  Classification -> best τ=0.535 (val F1=0.0737)
  Directional -> Accuracy: 0.5306, MCC: 0.1820, F1: 0.6567

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62425 | val 0.81792
  Epoch 020 - train 0.59677 | val 1.05839
  Epoch 021 - train 0.58669 | val 1.06096
  Classification -> best τ=0.380 (val F1=0.3921)
  Directional -> Accuracy: 0.5469, MCC: 0.1068, F1: 0.5538

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60221 | val 0.89003
  Epoch 020 - train 0.54538 | val 0.95210
  Epoch 022 - train 0.56773 | val 0.97914
  Classification -> best τ=0.450 (val F1=0.4105)
  Directional -> Accuracy: 0.5714, MCC: 0.1464, F1: 0.4615

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62083 | val 0.91269
  Epoch 020 - train 0.57900 | val 0.97377
  Epoch 021 - train 0.59107 | val 0.96592
  Classification -> best τ=0.635 (val F1=0.2280)
  Directional -> Accuracy: 0.4815, MCC: -0.0317, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63129 | val 0.87798
  Epoch 020 - train 0.57091 | val 1.30087
  Epoch 022 - train 0.56726 | val 1.30434
  Classification -> best τ=0.430 (val F1=0.2841)
  Directional -> Accuracy: 0.4091, MCC: -0.0377, F1: 0.2353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66243 | val 0.81137
  Epoch 020 - train 0.59974 | val 0.86012
  Epoch 026 - train 0.58196 | val 0.84884
  Classification -> best τ=0.485 (val F1=0.3953)
  Directional -> Accuracy: 0.6889, MCC: 0.2132, F1: 0.1250

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63117 | val 1.11247
  Epoch 020 - train 0.58290 | val 1.29848
  Epoch 021 - train 0.59424 | val 1.28593
  Classification -> best τ=0.430 (val F1=0.1755)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63128 | val 0.69703
  Epoch 020 - train 0.60139 | val 0.71264
  Epoch 021 - train 0.58889 | val 0.71512
  Classification -> best τ=0.465 (val F1=0.1860)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64204 | val 0.69435
  Epoch 020 - train 0.58062 | val 0.76866
  Epoch 030 - train 0.56327 | val 0.75467
  Classification -> best τ=0.400 (val F1=0.3380)
  Directional -> Accuracy: 0.6154, MCC: 0.1479, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59357 | val 1.01671
  Epoch 020 - train 0.55197 | val 1.11413
  Epoch 021 - train 0.57377 | val 1.11841
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64695 | val 0.67050
  Epoch 020 - train 0.61898 | val 0.68421
  Epoch 030 - train 0.61192 | val 0.70851
  Classification -> best τ=0.535 (val F1=0.3024)
  Directional -> Accuracy: 0.5660, MCC: 0.1524, F1: 0.7160

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62368 | val 1.32050
  Epoch 020 - train 0.58351 | val 1.70392
  Epoch 021 - train 0.58718 | val 1.76453
  Classification -> best τ=0.465 (val F1=0.1754)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64620 | val 0.74024
  Epoch 020 - train 0.65143 | val 0.78966
  Epoch 030 - train 0.59293 | val 0.78963
  Classification -> best τ=0.590 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.2072, F1: 0.6765

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64121 | val 0.98432
  Epoch 020 - train 0.61032 | val 1.04261
  Epoch 021 - train 0.59320 | val 1.04200
  Classification -> best τ=0.580 (val F1=0.2457)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67511 | val 0.68541
  Epoch 020 - train 0.62368 | val 0.66884

[I 2026-02-19 23:09:05,388] Trial 14 finished with value: 0.2419475480410302 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.0020566269898568365, 'weight_decay': 4.172382666047869e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.5030433295337673, 'early_stopping_min_delta': 0.0016629368379722865}. Best is trial 12 with value: 0.25712235217334833.

  Epoch 030 - train 0.57184 | val 0.71829
  Classification -> best τ=0.470 (val F1=0.3547)
  Directional -> Accuracy: 0.5345, MCC: 0.1353, F1: 0.6301

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2419475480410302
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63513 | val 0.93176
  Epoch 020 - train 0.62912 | val 0.90391
  Epoch 023 - train 0.60528 | val 0.83854
  Classification -> best τ=0.640 (val F1=0.1903)
  Directional -> Accuracy: 0.6076, MCC: 0.2253, F1: 0.2439

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64536 | val 0.73670
  Epoch 020 - train 0.63482 | val 0.70818
  Epoch 025 - train 0.60330 | val 0.71941
  Classification -> best τ=0.605 (val F1=0.1654)
  Directional -> Accuracy: 0.6250, MCC: 0.2208, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68386 | val 0.68430
  Epoch 020 - train 0.67619 | val 0.69132
  Epoch 028 - train 0.68013 | val 0.68082
  Classification -> best τ=0.410 (val F1=0.4001)
  Directional -> Accuracy: 0.4898, MCC: -0.1018, F1: 0.6377

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69434 | val 0.69335
  Epoch 020 - train 0.65742 | val 0.69419
  Epoch 030 - train 0.64189 | val 0.69522
  Classification -> best τ=0.495 (val F1=0.1976)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65609 | val 0.75176
  Epoch 020 - train 0.63941 | val 0.71398
  Epoch 022 - train 0.64748 | val 0.69601
  Classification -> best τ=0.435 (val F1=0.3911)
  Directional -> Accuracy: 0.6226, MCC: 0.2678, F1: 0.5833

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65503 | val 0.69586
  Epoch 020 - train 0.65684 | val 0.69964
  Epoch 021 - train 0.61710 | val 0.70068
  Classification -> best τ=0.535 (val F1=0.1711)
  Directional -> Accuracy: 0.5122, MCC: -0.0108, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68950 | val 0.69300
  Epoch 020 - train 0.68551 | val 0.69305
  Epoch 030 - train 0.65074 | val 0.68532
  Classification -> best τ=0.455 (val F1=0.2849)
  Directional -> Accuracy: 0.4507, MCC: 0.0582, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61200 | val 1.04312
  Epoch 020 - train 0.62880 | val 1.10611
  Epoch 021 - train 0.58686 | val 1.06553
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67777 | val 0.67939
  Epoch 020 - train 0.57817 | val 0.89210
  Epoch 028 - train 0.56098 | val 0.89846
  Classification -> best τ=0.515 (val F1=0.2522)
  Directional -> Accuracy: 0.6279, MCC: 0.1800, F1: 0.4286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65485 | val 0.71305
  Epoch 020 - train 0.62762 | val 0.70815
  Epoch 030 - train 0.59638 | val 0.70067
  Classification -> best τ=0.520 (val F1=0.1971)
  Directional -> Accuracy: 0.5278, MCC: 0.0850, F1: 0.5405

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67315 | val 0.69409
  Epoch 020 - train 0.65739 | val 0.69708
  Epoch 022 - train 0.63779 | val 0.69799
  Classification -> best τ=0.470 (val F1=0.1646)
  Directional -> Accuracy: 0.4423, MCC: -0.0872, F1: 0.5538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67195 | val 0.69231
  Epoch 020 - train 0.65590 | val 0.69411
  Epoch 030 - train 0.66109 | val 0.67363
  Classification -> best τ=0.590 (val F1=0.2562)
  Directional -> Accuracy: 0.6000, MCC: 0.2500, F1: 0.4286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61859 | val 0.73499
  Epoch 020 - train 0.58069 | val 0.75448
  Epoch 021 - train 0.58333 | val 0.74946
  Classification -> best τ=0.515 (val F1=0.1868)
  Directional -> Accuracy: 0.4667, MCC: -0.0714, F1: 0.4286

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67263 | val 0.60177
  Epoch 020 - train 0.67270 | val 0.60851
  Epoch 026 - train 0.62782 | val 0.61553
  Classification -> best τ=0.285 (val F1=0.4518)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65317 | val 0.78426
  Epoch 020 - train 0.62170 | val 1.14870
  Epoch 021 - train 0.59371 | val 1.16315
  Classification -> best τ=0.515 (val F1=0.1154)
  Directional -> Accuracy: 0.5926, MCC: 0.1819, F1: 0.5217

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63879 | val 0.74280
  Epoch 020 - train 0.58228 | val 0.75711
  Epoch 021 - train 0.58417 | val 0.76009
  Classification -> best τ=0.595 (val F1=0.3484)
  Directional -> Accuracy: 0.5694, MCC: 0.1774, F1: 0.5079

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64175 | val 0.90549
  Epoch 020 - train 0.62423 | val 1.11586
  Epoch 021 - train 0.63123 | val 1.11504
  Classification -> best τ=0.680 (val F1=0.0979)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68392 | val 0.70852
  Epoch 020 - train 0.67154 | val 0.70842
  Epoch 021 - train 0.66383 | val 0.71045
  Classification -> best τ=0.510 (val F1=0.1900)
  Directional -> Accuracy: 0.4872, MCC: 0.0947, F1: 0.3939

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67866 | val 0.67613
  Epoch 020 - train 0.62377 | val 0.66566
  Epoch 030 - train 0.59306 | val 0.71803
  Classification -> best τ=0.260 (val F1=0.2656)
  Directional -> Accuracy: 0.5224, MCC: 0.0083, F1: 0.6000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65039 | val 0.69800
  Epoch 020 - train 0.59657 | val 0.75094
  Epoch 024 - train 0.58852 | val 0.72171
  Classification -> best τ=0.530 (val F1=0.2935)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67517 | val 0.77506
  Epoch 020 - train 0.63457 | val 0.69726
  Epoch 030 - train 0.61673 | val 0.69774
  Classification -> best τ=0.355 (val F1=0.3327)
  Directional -> Accuracy: 0.6200, MCC: 0.0729, F1: 0.7532

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68773 | val 0.71920
  Epoch 020 - train 0.68164 | val 0.72100
  Epoch 021 - train 0.68284 | val 0.71193
  Classification -> best τ=0.520 (val F1=0.0716)
  Directional -> Accuracy: 0.4706, MCC: -0.1250, F1: 0.0526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67114 | val 0.77359
  Epoch 020 - train 0.64626 | val 0.79525
  Epoch 021 - train 0.63999 | val 0.79332
  Classification -> best τ=0.475 (val F1=0.2476)
  Directional -> Accuracy: 0.6167, MCC: 0.1657, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60513 | val 0.73853
  Epoch 020 - train 0.56631 | val 0.86407
  Epoch 022 - train 0.58110 | val 0.87270
  Classification -> best τ=0.435 (val F1=0.1459)
  Directional -> Accuracy: 0.5294, MCC: 0.0800, F1: 0.6098

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64770 | val 0.65381
  Epoch 020 - train 0.62334 | val 0.69818
  Epoch 029 - train 0.57339 | val 0.85248
  Classification -> best τ=0.465 (val F1=0.3482)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63061 | val 0.68491
  Epoch 020 - train 0.57658 | val 0.69958
  Epoch 024 - train 0.56686 | val 0.69444
  Classification -> best τ=0.525 (val F1=0.2124)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64302 | val 0.69750
  Epoch 020 - train 0.60774 | val 0.69779
  Epoch 023 - train 0.58775 | val 0.69477
  Classification -> best τ=0.515 (val F1=0.0299)
  Directional -> Accuracy: 0.5556, MCC: -0.0956, F1: 0.7059

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68075 | val 0.74856
  Epoch 020 - train 0.60142 | val 0.80707
  Epoch 022 - train 0.60499 | val 0.83670
  Classification -> best τ=0.375 (val F1=0.2312)
  Directional -> Accuracy: 0.5763, MCC: 0.2343, F1: 0.4898

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63716 | val 0.68426
  Epoch 020 - train 0.59294 | val 0.66849
  Epoch 030 - train 0.54946 | val 0.70721
  Classification -> best τ=0.645 (val F1=0.3458)
  Directional -> Accuracy: 0.5227, MCC: 0.0743, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66114 | val 0.71865
  Epoch 020 - train 0.63203 | val 0.73205
  Epoch 021 - train 0.62233 | val 0.73259
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68184 | val 0.65606
  Epoch 020 - train 0.63376 | val 0.71542
  Epoch 029 - train 0.64921 | val 0.73108
  Classification -> best τ=0.625 (val F1=0.0432)
  Directional -> Accuracy: 0.5652, MCC: 0.0981, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64296 | val 0.65811
  Epoch 020 - train 0.62996 | val 0.70274
  Epoch 030 - train 0.53709 | val 1.09729
  Classification -> best τ=0.510 (val F1=0.3389)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65932 | val 0.64010
  Epoch 020 - train 0.62751 | val 0.69470
  Epoch 030 - train 0.57121 | val 0.81571
  Classification -> best τ=0.240 (val F1=0.3305)
  Directional -> Accuracy: 0.5467, MCC: 0.0455, F1: 0.6458

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60561 | val 0.71643
  Epoch 020 - train 0.61867 | val 0.79148
  Epoch 025 - train 0.58190 | val 0.77165
  Classification -> best τ=0.590 (val F1=0.3380)
  Directional -> Accuracy: 0.5610, MCC: 0.1407, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61439 | val 0.96005
  Epoch 020 - train 0.62992 | val 0.91531
  Epoch 021 - train 0.59934 | val 0.92601
  Classification -> best τ=0.435 (val F1=0.2421)
  Directional -> Accuracy: 0.5435, MCC: 0.1195, F1: 0.5882

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66569 | val 0.72170
  Epoch 020 - train 0.61934 | val 0.75061
  Epoch 021 - train 0.64792 | val 0.75317
  Classification -> best τ=0.510 (val F1=0.2383)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.0488

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63174 | val 0.72047
  Epoch 020 - train 0.60103 | val 0.73595
  Epoch 022 - train 0.62718 | val 0.73193
  Classification -> best τ=0.410 (val F1=0.2478)
  Directional -> Accuracy: 0.6222, MCC: 0.2436, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61977 | val 0.80816
  Epoch 020 - train 0.61617 | val 0.90381
  Epoch 021 - train 0.57332 | val 0.90052
  Classification -> best τ=0.510 (val F1=0.2473)
  Directional -> Accuracy: 0.4576, MCC: -0.0733, F1: 0.5152

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65617 | val 0.76892
  Epoch 020 - train 0.62470 | val 0.93462
  Epoch 021 - train 0.62557 | val 0.94783
  Classification -> best τ=0.500 (val F1=0.3515)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64423 | val 0.69578
  Epoch 020 - train 0.62792 | val 0.69765
  Epoch 030 - train 0.52600 | val 0.68730
  Classification -> best τ=0.425 (val F1=0.3708)
  Directional -> Accuracy: 0.3571, MCC: -0.0520, F1: 0.4706

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64659 | val 0.69934
  Epoch 020 - train 0.63207 | val 0.70716
  Epoch 025 - train 0.58732 | val 0.70135
  Classification -> best τ=0.515 (val F1=0.2467)
  Directional -> Accuracy: 0.5366, MCC: 0.0805, F1: 0.4865

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66363 | val 0.75773
  Epoch 020 - train 0.63052 | val 0.77973
  Epoch 021 - train 0.63761 | val 0.78980
  Classification -> best τ=0.465 (val F1=0.2654)
  Directional -> Accuracy: 0.4805, MCC: -0.0368, F1: 0.3939

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64191 | val 0.71820
  Epoch 020 - train 0.66991 | val 0.83538
  Epoch 021 - train 0.67105 | val 0.83301
  Classification -> best τ=0.470 (val F1=0.3879)
  Directional -> Accuracy: 0.4898, MCC: -0.0103, F1: 0.6032

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63057 | val 0.95383
  Epoch 020 - train 0.60558 | val 1.37796
  Epoch 021 - train 0.60026 | val 1.37747
  Classification -> best τ=0.535 (val F1=0.3651)
  Directional -> Accuracy: 0.4681, MCC: -0.0040, F1: 0.3902

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58526 | val 0.98291
  Epoch 020 - train 0.56012 | val 0.69644
  Epoch 030 - train 0.53796 | val 0.75449
  Classification -> best τ=0.670 (val F1=0.3545)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67533 | val 0.69706
  Epoch 020 - train 0.66238 | val 0.70511
  Epoch 030 - train 0.64564 | val 0.70236
  Classification -> best τ=0.535 (val F1=0.2794)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63123 | val 1.06086
  Epoch 020 - train 0.58688 | val 1.43446
  Epoch 021 - train 0.60522 | val 1.42167
  Classification -> best τ=0.725 (val F1=0.3610)
  Directional -> Accuracy: 0.5593, MCC: 0.1499, F1: 0.6486

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66750 | val 0.85300
  Epoch 020 - train 0.63714 | val 0.90277
  Epoch 021 - train 0.62717 | val 0.90435
  Classification -> best τ=0.405 (val F1=0.0926)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...


[I 2026-02-19 23:10:01,231] Trial 15 finished with value: 0.24096820676173053 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.003234904657851654, 'weight_decay': 0.00029429268378170474, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.6616872958902003, 'early_stopping_min_delta': 0.0018293618029110786}. Best is trial 12 with value: 0.25712235217334833.

  Epoch 027 - train 0.61345 | val 0.78928
  Classification -> best τ=0.455 (val F1=0.2101)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24096820676173053
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64436 | val 0.86707
  Epoch 020 - train 0.63587 | val 0.92635
  Epoch 021 - train 0.63942 | val 0.93950
  Classification -> best τ=0.545 (val F1=0.1961)
  Directional -> Accuracy: 0.5000, MCC: 0.0303, F1: 0.5412

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66145 | val 0.70285
  Epoch 020 - train 0.64809 | val 0.70203
  Epoch 021 - train 0.66297 | val 0.70228
  Classification -> best τ=0.480 (val F1=0.0810)
  Directional -> Accuracy: 0.4468, MCC: -0.1004, F1: 0.4583

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69753 | val 0.68003
  Epoch 020 - train 0.67663 | val 0.66381
  Epoch 026 - train 0.67242 | val 0.66611
  Classification -> best τ=0.595 (val F1=0.4080)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66896 | val 0.90684
  Epoch 020 - train 0.65279 | val 0.92852
  Epoch 021 - train 0.65904 | val 0.92380
  Classification -> best τ=0.455 (val F1=0.0653)
  Directional -> Accuracy: 0.4737, MCC: -0.0592, F1: 0.5122

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63978 | val 0.73880
  Epoch 020 - train 0.64245 | val 0.80456
  Epoch 022 - train 0.63892 | val 0.79596
  Classification -> best τ=0.545 (val F1=0.3445)
  Directional -> Accuracy: 0.6538, MCC: 0.3155, F1: 0.6538

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62137 | val 1.24248
  Epoch 020 - train 0.62034 | val 1.28019
  Epoch 021 - train 0.60463 | val 1.28376
  Classification -> best τ=0.495 (val F1=0.2511)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68120 | val 0.80416
  Epoch 020 - train 0.66118 | val 0.89181
  Epoch 021 - train 0.65573 | val 0.88449
  Classification -> best τ=0.475 (val F1=0.0730)
  Directional -> Accuracy: 0.6000, MCC: 0.1111, F1: 0.3636

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65567 | val 1.27833
  Epoch 020 - train 0.63466 | val 1.33483
  Epoch 021 - train 0.65740 | val 1.33631
  Classification -> best τ=0.475 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65223 | val 0.74455
  Epoch 020 - train 0.63824 | val 0.80146
  Epoch 021 - train 0.65083 | val 0.79817
  Classification -> best τ=0.515 (val F1=0.3154)
  Directional -> Accuracy: 0.4286, MCC: -0.1356, F1: 0.3684

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67091 | val 1.11463
  Epoch 020 - train 0.64511 | val 1.25383
  Epoch 021 - train 0.63076 | val 1.27638
  Classification -> best τ=0.385 (val F1=0.2573)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65725 | val 0.72420
  Epoch 020 - train 0.64351 | val 0.69512
  Epoch 021 - train 0.65287 | val 0.69413
  Classification -> best τ=0.465 (val F1=0.1926)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68505 | val 0.69713
  Epoch 020 - train 0.67680 | val 0.70762
  Epoch 026 - train 0.66802 | val 0.70517
  Classification -> best τ=0.485 (val F1=0.3019)
  Directional -> Accuracy: 0.5932, MCC: 0.1973, F1: 0.5385

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63063 | val 0.89075
  Epoch 020 - train 0.64488 | val 0.80866
  Epoch 021 - train 0.60805 | val 0.81388
  Classification -> best τ=0.430 (val F1=0.2023)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68599 | val 0.62272
  Epoch 020 - train 0.66931 | val 0.66402
  Epoch 028 - train 0.66141 | val 0.66626
  Classification -> best τ=0.490 (val F1=0.3848)
  Directional -> Accuracy: 0.5323, MCC: 0.0674, F1: 0.5915

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65881 | val 0.99033
  Epoch 020 - train 0.63584 | val 0.98199
  Epoch 021 - train 0.62805 | val 0.97408
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65577 | val 0.76839
  Epoch 020 - train 0.64714 | val 0.75581
  Epoch 021 - train 0.63532 | val 0.75872
  Classification -> best τ=0.365 (val F1=0.2527)
  Directional -> Accuracy: 0.5634, MCC: 0.1145, F1: 0.6931

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64810 | val 0.82772
  Epoch 020 - train 0.66067 | val 0.91730
  Epoch 021 - train 0.66156 | val 0.91597
  Classification -> best τ=0.635 (val F1=0.2042)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67573 | val 0.82060
  Epoch 020 - train 0.67162 | val 0.85921
  Epoch 021 - train 0.67066 | val 0.85484
  Classification -> best τ=0.445 (val F1=0.1263)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66563 | val 0.71645
  Epoch 020 - train 0.65288 | val 0.74731
  Epoch 021 - train 0.65916 | val 0.74546
  Classification -> best τ=0.520 (val F1=0.3542)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65463 | val 0.76890
  Epoch 020 - train 0.62819 | val 0.84119
  Epoch 026 - train 0.61409 | val 0.87565
  Classification -> best τ=0.420 (val F1=0.2886)
  Directional -> Accuracy: 0.5526, MCC: 0.1489, F1: 0.4688

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67946 | val 0.73712
  Epoch 020 - train 0.67207 | val 0.75256
  Epoch 021 - train 0.67166 | val 0.75412
  Classification -> best τ=0.495 (val F1=0.1940)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68596 | val 0.87853
  Epoch 020 - train 0.67749 | val 0.89573
  Epoch 021 - train 0.67752 | val 0.90455
  Classification -> best τ=0.530 (val F1=0.1489)
  Directional -> Accuracy: 0.5224, MCC: 0.0438, F1: 0.6279

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66141 | val 1.04557
  Epoch 020 - train 0.64558 | val 1.11662
  Epoch 021 - train 0.64961 | val 1.12456
  Classification -> best τ=0.575 (val F1=0.2095)
  Directional -> Accuracy: 0.5424, MCC: 0.1228, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65057 | val 0.82843
  Epoch 020 - train 0.65693 | val 0.81928
  Epoch 021 - train 0.64431 | val 0.82066
  Classification -> best τ=0.385 (val F1=0.1994)
  Directional -> Accuracy: 0.5522, MCC: 0.1249, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66403 | val 0.70110
  Epoch 020 - train 0.62045 | val 0.75876
  Epoch 026 - train 0.64073 | val 0.75465
  Classification -> best τ=0.555 (val F1=0.4032)
  Directional -> Accuracy: 0.5263, MCC: 0.0255, F1: 0.5970

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65126 | val 0.71368
  Epoch 020 - train 0.65335 | val 0.72489
  Epoch 021 - train 0.64847 | val 0.72492
  Classification -> best τ=0.540 (val F1=0.0834)
  Directional -> Accuracy: 0.4167, MCC: -0.1555, F1: 0.3913

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67088 | val 1.00822
  Epoch 020 - train 0.66419 | val 1.13431
  Epoch 021 - train 0.66674 | val 1.12886
  Classification -> best τ=0.490 (val F1=0.0435)
  Directional -> Accuracy: 0.5909, MCC: 0.1263, F1: 0.6786

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67940 | val 0.70218
  Epoch 020 - train 0.64707 | val 0.73590
  Epoch 029 - train 0.63802 | val 0.74181
  Classification -> best τ=0.305 (val F1=0.2369)
  Directional -> Accuracy: 0.5517, MCC: 0.1434, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64165 | val 0.68317
  Epoch 020 - train 0.65741 | val 0.68284
  Epoch 024 - train 0.63312 | val 0.68352
  Classification -> best τ=0.555 (val F1=0.2829)
  Directional -> Accuracy: 0.4651, MCC: -0.0486, F1: 0.3784

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68133 | val 0.73392
  Epoch 020 - train 0.67139 | val 0.73757
  Epoch 021 - train 0.66728 | val 0.73582
  Classification -> best τ=0.490 (val F1=0.2174)
  Directional -> Accuracy: 0.4444, MCC: -0.1089, F1: 0.3902

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69096 | val 0.72208
  Epoch 020 - train 0.68530 | val 0.73960
  Epoch 021 - train 0.67903 | val 0.73885
  Classification -> best τ=0.565 (val F1=0.1985)
  Directional -> Accuracy: 0.4889, MCC: 0.0066, F1: 0.3784

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67378 | val 0.70167
  Epoch 020 - train 0.64157 | val 0.71238
  Epoch 021 - train 0.64542 | val 0.71333
  Classification -> best τ=0.490 (val F1=0.0449)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66682 | val 0.65149
  Epoch 020 - train 0.63178 | val 0.69475
  Epoch 030 - train 0.62431 | val 0.71448
  Classification -> best τ=0.300 (val F1=0.3259)
  Directional -> Accuracy: 0.5946, MCC: 0.1627, F1: 0.6591

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66082 | val 0.70968
  Epoch 020 - train 0.60786 | val 0.72833
  Epoch 021 - train 0.61968 | val 0.72850
  Classification -> best τ=0.470 (val F1=0.4045)
  Directional -> Accuracy: 0.4872, MCC: -0.0171, F1: 0.5652

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63799 | val 0.90601
  Epoch 020 - train 0.64286 | val 0.89837
  Epoch 021 - train 0.62210 | val 0.89813
  Classification -> best τ=0.440 (val F1=0.1357)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66017 | val 0.76505
  Epoch 020 - train 0.63566 | val 0.80968
  Epoch 022 - train 0.63417 | val 0.80516
  Classification -> best τ=0.305 (val F1=0.2417)
  Directional -> Accuracy: 0.5294, MCC: 0.2173, F1: 0.3600

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65582 | val 0.76294
  Epoch 020 - train 0.67785 | val 0.79713
  Epoch 021 - train 0.66407 | val 0.80122
  Classification -> best τ=0.500 (val F1=0.1993)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65769 | val 0.75657
  Epoch 020 - train 0.63606 | val 0.78790
  Epoch 021 - train 0.64693 | val 0.79879
  Classification -> best τ=0.510 (val F1=0.2413)
  Directional -> Accuracy: 0.4655, MCC: -0.0823, F1: 0.3922

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65104 | val 1.44570
  Epoch 020 - train 0.63140 | val 1.54338
  Epoch 021 - train 0.62785 | val 1.54056
  Classification -> best τ=0.580 (val F1=0.1368)
  Directional -> Accuracy: 0.5833, MCC: -0.0778, F1: 0.7297

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65816 | val 0.74000
  Epoch 020 - train 0.68668 | val 0.74487
  Epoch 021 - train 0.66058 | val 0.74424
  Classification -> best τ=0.510 (val F1=0.3769)
  Directional -> Accuracy: 0.5500, MCC: -0.0605, F1: 0.2500

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61709 | val 0.85010
  Epoch 020 - train 0.63083 | val 0.89632
  Epoch 021 - train 0.63810 | val 0.90017
  Classification -> best τ=0.480 (val F1=0.2548)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64792 | val 1.02190
  Epoch 020 - train 0.64516 | val 1.15797
  Epoch 021 - train 0.62984 | val 1.16830
  Classification -> best τ=0.510 (val F1=0.2296)
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67136 | val 0.80389
  Epoch 020 - train 0.66805 | val 0.81292
  Epoch 021 - train 0.64763 | val 0.81043
  Classification -> best τ=0.480 (val F1=0.0181)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61765 | val 0.85328
  Epoch 020 - train 0.63557 | val 0.91610
  Epoch 021 - train 0.63544 | val 0.91700
  Classification -> best τ=0.505 (val F1=0.2000)
  Directional -> Accuracy: 0.6222, MCC: 0.2331, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62944 | val 1.17936
  Epoch 020 - train 0.65554 | val 1.31309
  Epoch 021 - train 0.61321 | val 1.30832
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68093 | val 0.91671
  Epoch 020 - train 0.66539 | val 0.92803
  Epoch 021 - train 0.67651 | val 0.94652
  Classification -> best τ=0.435 (val F1=0.0646)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64386 | val 1.21747
  Epoch 020 - train 0.61939 | val 1.38100
  Epoch 021 - train 0.62800 | val 1.37260
  Classification -> best τ=0.545 (val F1=0.3886)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65157 | val 0.85988
  Epoch 020 - train 0.66588 | val 0.90905
  Epoch 021 - train 0.65464 | val 0.90283
  Classification -> best τ=0.495 (val F1=0.2537)
  Directional -> Accuracy: 0.5636, MCC: 0.1605, F1: 0.4783

[87/88] Processing WMT...


[I 2026-02-19 23:12:03,456] Trial 16 finished with value: 0.21206368799862055 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0005327554114328593, 'weight_decay': 5.7036269561102395e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3070254848550202, 'early_stopping_min_delta': 0.0032168325871208426}. Best is trial 12 with value: 0.25712235217334833.

  Epoch 024 - train 0.66609 | val 0.70073
  Classification -> best τ=0.455 (val F1=0.1655)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21206368799862055
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65781 | val 0.67543
  Epoch 020 - train 0.62063 | val 0.73492
  Epoch 027 - train 0.59291 | val 0.77522
  Classification -> best τ=0.635 (val F1=0.2727)
  Directional -> Accuracy: 0.6329, MCC: 0.2445, F1: 0.4528

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64610 | val 0.69947
  Epoch 020 - train 0.58089 | val 0.69572
  Epoch 022 - train 0.55867 | val 0.69605
  Classification -> best τ=0.480 (val F1=0.1654)
  Directional -> Accuracy: 0.5417, MCC: 0.0067, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71672 | val 0.72403
  Epoch 020 - train 0.68234 | val 0.72177
  Epoch 022 - train 0.66351 | val 0.72320
  Classification -> best τ=0.440 (val F1=0.3077)
  Directional -> Accuracy: 0.5306, MCC: 0.1293, F1: 0.3429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68596 | val 0.69408
  Epoch 020 - train 0.65366 | val 0.69861
  Epoch 029 - train 0.64256 | val 0.72543
  Classification -> best τ=0.530 (val F1=0.2475)
  Directional -> Accuracy: 0.4935, MCC: -0.0394, F1: 0.5714

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65181 | val 0.62615
  Epoch 020 - train 0.58475 | val 0.65766
  Epoch 030 - train 0.55837 | val 0.74547
  Classification -> best τ=0.550 (val F1=0.4508)
  Directional -> Accuracy: 0.6604, MCC: 0.3457, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58796 | val 0.72965
  Epoch 020 - train 0.56291 | val 0.77176
  Epoch 023 - train 0.55522 | val 0.78559
  Classification -> best τ=0.510 (val F1=0.2521)
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.1000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68332 | val 0.69238
  Epoch 020 - train 0.67239 | val 0.71341
  Epoch 030 - train 0.60217 | val 0.75251
  Classification -> best τ=0.405 (val F1=0.2981)
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61278 | val 0.90779
  Epoch 020 - train 0.56401 | val 1.08233
  Epoch 025 - train 0.56824 | val 1.09945
  Classification -> best τ=0.660 (val F1=0.1316)
  Directional -> Accuracy: 0.5106, MCC: -0.0625, F1: 0.3030

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62555 | val 0.87500
  Epoch 020 - train 0.54294 | val 1.18766
  Epoch 026 - train 0.56015 | val 1.01791
  Classification -> best τ=0.360 (val F1=0.3603)
  Directional -> Accuracy: 0.5814, MCC: 0.2288, F1: 0.5909

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66802 | val 0.70330
  Epoch 020 - train 0.61964 | val 0.72982
  Epoch 030 - train 0.57892 | val 0.69744
  Classification -> best τ=0.490 (val F1=0.2406)
  Directional -> Accuracy: 0.4861, MCC: -0.0047, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67455 | val 0.77225
  Epoch 020 - train 0.62544 | val 0.79344
  Epoch 022 - train 0.65017 | val 0.78809
  Classification -> best τ=0.570 (val F1=0.1922)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67196 | val 0.71057
  Epoch 020 - train 0.64402 | val 0.71063
  Epoch 025 - train 0.66057 | val 0.71064
  Classification -> best τ=0.575 (val F1=0.2075)
  Directional -> Accuracy: 0.5833, MCC: 0.2023, F1: 0.4186

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58612 | val 0.69570
  Epoch 020 - train 0.57697 | val 0.70527
  Epoch 030 - train 0.46848 | val 0.71007
  Classification -> best τ=0.370 (val F1=0.2641)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68608 | val 0.73049
  Epoch 020 - train 0.65729 | val 0.80301
  Epoch 024 - train 0.62658 | val 0.80028
  Classification -> best τ=0.435 (val F1=0.3883)
  Directional -> Accuracy: 0.5556, MCC: 0.1216, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65743 | val 0.76028
  Epoch 020 - train 0.58534 | val 0.90439
  Epoch 021 - train 0.58430 | val 0.94476
  Classification -> best τ=0.520 (val F1=0.0413)
  Directional -> Accuracy: 0.5926, MCC: 0.1819, F1: 0.5217

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63864 | val 0.75834
  Epoch 020 - train 0.59392 | val 0.83814
  Epoch 021 - train 0.56887 | val 0.83329
  Classification -> best τ=0.515 (val F1=0.2524)
  Directional -> Accuracy: 0.5556, MCC: 0.0903, F1: 0.6279

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67431 | val 0.82271
  Epoch 020 - train 0.60567 | val 0.94448
  Epoch 021 - train 0.61749 | val 0.93703
  Classification -> best τ=0.660 (val F1=0.2383)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66126 | val 0.76425
  Epoch 020 - train 0.65411 | val 0.87613
  Epoch 024 - train 0.62889 | val 0.86533
  Classification -> best τ=0.450 (val F1=0.1180)
  Directional -> Accuracy: 0.4872, MCC: 0.0402, F1: 0.4595

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65739 | val 0.66707
  Epoch 020 - train 0.63906 | val 0.65323
  Epoch 030 - train 0.59144 | val 0.65423
  Classification -> best τ=0.390 (val F1=0.3342)
  Directional -> Accuracy: 0.4925, MCC: 0.1096, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64590 | val 0.70914
  Epoch 020 - train 0.60147 | val 0.79486
  Epoch 021 - train 0.57427 | val 0.80852
  Classification -> best τ=0.515 (val F1=0.2358)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63766 | val 0.83130
  Epoch 020 - train 0.59352 | val 1.13709
  Epoch 027 - train 0.54734 | val 1.45810
  Classification -> best τ=0.490 (val F1=0.3761)
  Directional -> Accuracy: 0.6200, MCC: 0.1079, F1: 0.7397

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68884 | val 0.70584
  Epoch 020 - train 0.64098 | val 0.71033
  Epoch 027 - train 0.62950 | val 0.75696
  Classification -> best τ=0.520 (val F1=0.2582)
  Directional -> Accuracy: 0.5441, MCC: 0.1690, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66993 | val 0.81032
  Epoch 020 - train 0.61398 | val 0.78360
  Epoch 024 - train 0.61719 | val 0.78151
  Classification -> best τ=0.580 (val F1=0.2816)
  Directional -> Accuracy: 0.5833, MCC: 0.1807, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64464 | val 0.74178
  Epoch 020 - train 0.61030 | val 0.76099
  Epoch 030 - train 0.52987 | val 0.79094
  Classification -> best τ=0.430 (val F1=0.1459)
  Directional -> Accuracy: 0.5000, MCC: 0.0170, F1: 0.5952

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64496 | val 0.66228
  Epoch 020 - train 0.59954 | val 0.76048
  Epoch 022 - train 0.57557 | val 0.78906
  Classification -> best τ=0.440 (val F1=0.3933)
  Directional -> Accuracy: 0.5690, MCC: 0.1859, F1: 0.5098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56577 | val 0.70607
  Epoch 020 - train 0.48285 | val 0.76999
  Epoch 026 - train 0.42588 | val 0.81038
  Classification -> best τ=0.530 (val F1=0.3056)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65866 | val 0.70997
  Epoch 020 - train 0.61377 | val 0.69635
  Epoch 022 - train 0.59809 | val 0.69560
  Classification -> best τ=0.555 (val F1=0.0472)
  Directional -> Accuracy: 0.5111, MCC: 0.0551, F1: 0.5217

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64865 | val 0.82301
  Epoch 020 - train 0.59564 | val 1.01705
  Epoch 021 - train 0.59281 | val 1.02236
  Classification -> best τ=0.500 (val F1=0.1295)
  Directional -> Accuracy: 0.6102, MCC: 0.2283, F1: 0.6230

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58899 | val 0.68124
  Epoch 020 - train 0.52961 | val 0.72195
  Epoch 030 - train 0.40698 | val 0.70186
  Classification -> best τ=0.575 (val F1=0.3730)
  Directional -> Accuracy: 0.5000, MCC: -0.0063, F1: 0.5417

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67998 | val 0.70210
  Epoch 020 - train 0.58509 | val 0.79071
  Epoch 029 - train 0.54949 | val 0.81965
  Classification -> best τ=0.525 (val F1=0.2266)
  Directional -> Accuracy: 0.6087, MCC: 0.2252, F1: 0.6538

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66963 | val 0.67282
  Epoch 020 - train 0.66432 | val 0.67845
  Epoch 021 - train 0.67198 | val 0.67849
  Classification -> best τ=0.635 (val F1=0.2490)
  Directional -> Accuracy: 0.4348, MCC: -0.1001, F1: 0.2778

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62679 | val 0.70418
  Epoch 020 - train 0.53559 | val 0.86785
  Epoch 027 - train 0.42543 | val 1.00249
  Classification -> best τ=0.695 (val F1=0.2798)
  Directional -> Accuracy: 0.5000, MCC: -0.1347, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67463 | val 0.64033
  Epoch 020 - train 0.61755 | val 0.71274
  Epoch 030 - train 0.57485 | val 0.70457
  Classification -> best τ=0.385 (val F1=0.3565)
  Directional -> Accuracy: 0.5467, MCC: 0.1288, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67448 | val 0.76492
  Epoch 020 - train 0.61195 | val 0.76431
  Epoch 022 - train 0.62418 | val 0.76287
  Classification -> best τ=0.565 (val F1=0.1457)
  Directional -> Accuracy: 0.5122, MCC: 0.0655, F1: 0.6429

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63940 | val 1.00560
  Epoch 020 - train 0.59673 | val 1.18487
  Epoch 021 - train 0.59279 | val 1.23540
  Classification -> best τ=0.560 (val F1=0.2703)
  Directional -> Accuracy: 0.4565, MCC: -0.0577, F1: 0.5283

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65198 | val 0.75844
  Epoch 020 - train 0.57266 | val 0.76152
  Epoch 021 - train 0.57963 | val 0.76625
  Classification -> best τ=0.425 (val F1=0.3136)
  Directional -> Accuracy: 0.5797, MCC: 0.1256, F1: 0.6506

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63513 | val 0.69751
  Epoch 020 - train 0.59954 | val 0.69135
  Epoch 029 - train 0.60651 | val 0.71537
  Classification -> best τ=0.455 (val F1=0.2651)
  Directional -> Accuracy: 0.6000, MCC: 0.2310, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64310 | val 0.77191
  Epoch 020 - train 0.58929 | val 0.91185
  Epoch 022 - train 0.58501 | val 0.88700
  Classification -> best τ=0.530 (val F1=0.1768)
  Directional -> Accuracy: 0.4407, MCC: -0.1094, F1: 0.4923

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62667 | val 0.77953
  Epoch 020 - train 0.51141 | val 1.01760
  Epoch 021 - train 0.50704 | val 0.98519
  Classification -> best τ=0.475 (val F1=0.3249)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61295 | val 0.65938
  Epoch 020 - train 0.55078 | val 0.64860
  Epoch 030 - train 0.51138 | val 0.64157
  Classification -> best τ=0.275 (val F1=0.4142)
  Directional -> Accuracy: 0.3571, MCC: 0.1104, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63537 | val 0.69805
  Epoch 020 - train 0.61116 | val 0.71669
  Epoch 021 - train 0.56476 | val 0.71956
  Classification -> best τ=0.510 (val F1=0.3780)
  Directional -> Accuracy: 0.5610, MCC: 0.1504, F1: 0.4375

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65149 | val 0.77557
  Epoch 020 - train 0.61308 | val 1.03485
  Epoch 022 - train 0.57516 | val 1.13206
  Classification -> best τ=0.455 (val F1=0.2749)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63188 | val 0.82734
  Epoch 020 - train 0.64212 | val 0.75630
  Epoch 021 - train 0.63861 | val 0.76594
  Classification -> best τ=0.515 (val F1=0.1451)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62043 | val 1.24935
  Epoch 020 - train 0.57022 | val 1.68772
  Epoch 021 - train 0.52854 | val 1.73711
  Classification -> best τ=0.455 (val F1=0.2191)
  Directional -> Accuracy: 0.5957, MCC: 0.1412, F1: 0.6885

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58341 | val 1.13857
  Epoch 020 - train 0.51720 | val 0.92418
  Epoch 022 - train 0.50435 | val 0.96091
  Classification -> best τ=0.470 (val F1=0.2193)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68896 | val 0.68278
  Epoch 020 - train 0.66199 | val 0.70554
  Epoch 021 - train 0.64534 | val 0.70849
  Classification -> best τ=0.565 (val F1=0.1801)
  Directional -> Accuracy: 0.5862, MCC: 0.1942, F1: 0.5714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63372 | val 1.10458
  Epoch 020 - train 0.57527 | val 1.57790
  Epoch 021 - train 0.58997 | val 1.60154
  Classification -> best τ=0.470 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65264 | val 0.86709
  Epoch 020 - train 0.61597 | val 0.82912
  Epoch 024 - train 0.60046 | val 0.83011
  Classification -> best τ=0.455 (val F1=0.1728)
  Directional -> Accuracy: 0.5714, MCC: 0.1247, F1: 0.6757

[87/88] Processing WMT...


[I 2026-02-19 23:13:44,862] Trial 17 finished with value: 0.2514974664434055 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.00470197788475645, 'weight_decay': 0.0003497370096210727, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.6673538405330603, 'early_stopping_min_delta': 0.0008438793230933896}. Best is trial 12 with value: 0.25712235217334833.

  Epoch 025 - train 0.59011 | val 0.70637
  Classification -> best τ=0.515 (val F1=0.2500)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2514974664434055
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66433 | val 0.72004
  Epoch 020 - train 0.66430 | val 0.73152
  Epoch 021 - train 0.66519 | val 0.73069
  Classification -> best τ=0.500 (val F1=0.0977)
  Directional -> Accuracy: 0.6026, MCC: 0.2089, F1: 0.5867

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67296 | val 0.68775
  Epoch 020 - train 0.63762 | val 0.71813
  Epoch 023 - train 0.63253 | val 0.72111
  Classification -> best τ=0.505 (val F1=0.2346)
  Directional -> Accuracy: 0.5745, MCC: 0.1155, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68639 | val 0.73053
  Epoch 020 - train 0.68074 | val 0.71832
  Epoch 021 - train 0.71520 | val 0.71785
  Classification -> best τ=0.515 (val F1=0.1940)
  Directional -> Accuracy: 0.5833, MCC: 0.2070, F1: 0.5238

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69737 | val 0.79259
  Epoch 020 - train 0.66624 | val 0.79477
  Epoch 021 - train 0.66628 | val 0.80872
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66989 | val 0.63841
  Epoch 020 - train 0.62667 | val 0.65860
  Epoch 028 - train 0.61703 | val 0.66540
  Classification -> best τ=0.455 (val F1=0.3592)
  Directional -> Accuracy: 0.6923, MCC: 0.3805, F1: 0.7419

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64548 | val 0.91104
  Epoch 020 - train 0.62480 | val 0.96997
  Epoch 021 - train 0.64030 | val 0.97499
  Classification -> best τ=0.500 (val F1=0.2012)
  Directional -> Accuracy: 0.5714, MCC: 0.2119, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69304 | val 0.70534
  Epoch 020 - train 0.68996 | val 0.77939
  Epoch 022 - train 0.65238 | val 0.77791
  Classification -> best τ=0.440 (val F1=0.2071)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64809 | val 1.13559
  Epoch 020 - train 0.63976 | val 1.26198
  Epoch 021 - train 0.66620 | val 1.26433
  Classification -> best τ=0.545 (val F1=0.3669)
  Directional -> Accuracy: 0.6667, MCC: 0.3002, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69288 | val 0.75377
  Epoch 020 - train 0.66620 | val 0.82958
  Epoch 023 - train 0.66531 | val 0.82803
  Classification -> best τ=0.520 (val F1=0.3364)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.4500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67235 | val 0.82451
  Epoch 020 - train 0.64451 | val 0.85603
  Epoch 021 - train 0.64865 | val 0.85064
  Classification -> best τ=0.445 (val F1=0.1920)
  Directional -> Accuracy: 0.4507, MCC: 0.1052, F1: 0.6139

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66275 | val 0.91494
  Epoch 020 - train 0.67694 | val 0.93204
  Epoch 021 - train 0.67090 | val 0.94030
  Classification -> best τ=0.550 (val F1=0.0969)
  Directional -> Accuracy: 0.4902, MCC: -0.1004, F1: 0.1333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69600 | val 0.73790
  Epoch 020 - train 0.68582 | val 0.73339
  Epoch 021 - train 0.68781 | val 0.73215
  Classification -> best τ=0.510 (val F1=0.1532)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65911 | val 0.76463
  Epoch 020 - train 0.64420 | val 0.85903
  Epoch 021 - train 0.64637 | val 0.86503
  Classification -> best τ=0.455 (val F1=0.2076)
  Directional -> Accuracy: 0.4318, MCC: -0.1193, F1: 0.4681

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68389 | val 0.64432
  Epoch 020 - train 0.67863 | val 0.68089
  Epoch 029 - train 0.65078 | val 0.68173
  Classification -> best τ=0.365 (val F1=0.2708)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67737 | val 1.18554
  Epoch 020 - train 0.67023 | val 1.17758
  Epoch 021 - train 0.65590 | val 1.18442
  Classification -> best τ=0.685 (val F1=0.1685)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65594 | val 0.77367
  Epoch 020 - train 0.65188 | val 0.72768
  Epoch 022 - train 0.65756 | val 0.73528
  Classification -> best τ=0.360 (val F1=0.2527)
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68000 | val 0.86872
  Epoch 020 - train 0.64506 | val 0.86845
  Epoch 021 - train 0.64875 | val 0.86768
  Classification -> best τ=0.575 (val F1=0.2165)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70481 | val 1.11325
  Epoch 020 - train 0.69019 | val 1.21037
  Epoch 021 - train 0.64625 | val 1.21729
  Classification -> best τ=0.510 (val F1=0.0719)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68589 | val 0.70052
  Epoch 020 - train 0.65470 | val 0.71563
  Epoch 024 - train 0.65878 | val 0.72705
  Classification -> best τ=0.370 (val F1=0.2409)
  Directional -> Accuracy: 0.5606, MCC: 0.1407, F1: 0.5797

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67161 | val 0.68609
  Epoch 020 - train 0.65709 | val 0.66337
  Epoch 030 - train 0.63259 | val 0.67618
  Classification -> best τ=0.450 (val F1=0.3413)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68606 | val 0.68544
  Epoch 020 - train 0.64170 | val 0.67125
  Epoch 030 - train 0.64614 | val 0.67374
  Classification -> best τ=0.460 (val F1=0.3584)
  Directional -> Accuracy: 0.5306, MCC: 0.0691, F1: 0.5818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68345 | val 0.82913
  Epoch 020 - train 0.66112 | val 0.85552
  Epoch 021 - train 0.67064 | val 0.85571
  Classification -> best τ=0.455 (val F1=0.0756)
  Directional -> Accuracy: 0.6567, MCC: 0.3131, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67559 | val 0.75317
  Epoch 020 - train 0.65062 | val 0.81370
  Epoch 023 - train 0.67408 | val 0.82032
  Classification -> best τ=0.520 (val F1=0.2097)
  Directional -> Accuracy: 0.5424, MCC: -0.0072, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66581 | val 0.98515
  Epoch 020 - train 0.63926 | val 0.98349
  Epoch 021 - train 0.64731 | val 0.98023
  Classification -> best τ=0.415 (val F1=0.1283)
  Directional -> Accuracy: 0.5821, MCC: 0.1817, F1: 0.6216

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66040 | val 0.62884
  Epoch 020 - train 0.67451 | val 0.67180
  Epoch 026 - train 0.65034 | val 0.68165
  Classification -> best τ=0.555 (val F1=0.5777)
  Directional -> Accuracy: 0.5614, MCC: 0.2071, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66879 | val 0.80347
  Epoch 020 - train 0.64403 | val 0.78975
  Epoch 021 - train 0.66887 | val 0.78668
  Classification -> best τ=0.490 (val F1=0.0555)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65622 | val 0.75730
  Epoch 020 - train 0.66611 | val 0.76897
  Epoch 021 - train 0.64793 | val 0.75938
  Classification -> best τ=0.520 (val F1=0.1116)
  Directional -> Accuracy: 0.6136, MCC: 0.1390, F1: 0.7385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68152 | val 0.73592
  Epoch 020 - train 0.64674 | val 0.76052
  Epoch 021 - train 0.63953 | val 0.75961
  Classification -> best τ=0.480 (val F1=0.0698)
  Directional -> Accuracy: 0.5345, MCC: -0.1194, F1: 0.6966

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64792 | val 0.67831
  Epoch 020 - train 0.63519 | val 0.68261
  Epoch 030 - train 0.59396 | val 0.67821
  Classification -> best τ=0.455 (val F1=0.3901)
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67356 | val 0.75037
  Epoch 020 - train 0.65866 | val 0.77297
  Epoch 021 - train 0.67494 | val 0.77446
  Classification -> best τ=0.545 (val F1=0.2874)
  Directional -> Accuracy: 0.4889, MCC: -0.0103, F1: 0.2581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67571 | val 0.65492
  Epoch 020 - train 0.64930 | val 0.69924
  Epoch 024 - train 0.64865 | val 0.71189
  Classification -> best τ=0.550 (val F1=0.1581)
  Directional -> Accuracy: 0.6000, MCC: 0.2857, F1: 0.7273

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65718 | val 0.66926
  Epoch 020 - train 0.62997 | val 0.73582
  Epoch 026 - train 0.64579 | val 0.71989
  Classification -> best τ=0.485 (val F1=0.2725)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66447 | val 0.66776
  Epoch 020 - train 0.66189 | val 0.69395
  Epoch 024 - train 0.66246 | val 0.70162
  Classification -> best τ=0.410 (val F1=0.3259)
  Directional -> Accuracy: 0.5541, MCC: 0.1516, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68806 | val 0.69657
  Epoch 020 - train 0.63541 | val 0.70183
  Epoch 021 - train 0.67953 | val 0.70199
  Classification -> best τ=0.480 (val F1=0.1241)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65092 | val 0.94424
  Epoch 020 - train 0.65563 | val 0.94802
  Epoch 021 - train 0.65100 | val 0.94894
  Classification -> best τ=0.545 (val F1=0.0496)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64519 | val 0.71480
  Epoch 020 - train 0.61502 | val 0.71736
  Epoch 021 - train 0.63715 | val 0.71855
  Classification -> best τ=0.435 (val F1=0.4157)
  Directional -> Accuracy: 0.6176, MCC: 0.2184, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65495 | val 0.69292
  Epoch 020 - train 0.65678 | val 0.71588
  Epoch 023 - train 0.63935 | val 0.71814
  Classification -> best τ=0.470 (val F1=0.2202)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4211

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66308 | val 0.75807
  Epoch 020 - train 0.61464 | val 0.76229
  Epoch 021 - train 0.65944 | val 0.76547
  Classification -> best τ=0.550 (val F1=0.2171)
  Directional -> Accuracy: 0.5517, MCC: 0.1419, F1: 0.0714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63990 | val 0.98551
  Epoch 020 - train 0.62286 | val 1.13180
  Epoch 021 - train 0.63866 | val 1.12609
  Classification -> best τ=0.550 (val F1=0.2799)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66322 | val 0.70118
  Epoch 020 - train 0.63940 | val 0.67309
  Epoch 030 - train 0.62747 | val 0.69734
  Classification -> best τ=0.475 (val F1=0.4689)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67527 | val 0.70934
  Epoch 020 - train 0.65430 | val 0.76926
  Epoch 021 - train 0.68030 | val 0.76923
  Classification -> best τ=0.525 (val F1=0.4382)
  Directional -> Accuracy: 0.5385, MCC: 0.0878, F1: 0.5263

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67129 | val 0.76251
  Epoch 020 - train 0.63719 | val 0.81598
  Epoch 022 - train 0.67729 | val 0.80879
  Classification -> best τ=0.500 (val F1=0.2234)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68013 | val 0.71025
  Epoch 020 - train 0.66625 | val 0.70514
  Epoch 021 - train 0.66621 | val 0.70665
  Classification -> best τ=0.475 (val F1=0.2046)
  Directional -> Accuracy: 0.5833, MCC: 0.1768, F1: 0.6429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65152 | val 0.82045
  Epoch 020 - train 0.65281 | val 0.88507
  Epoch 021 - train 0.64441 | val 0.88667
  Classification -> best τ=0.470 (val F1=0.0574)
  Directional -> Accuracy: 0.4444, MCC: -0.0520, F1: 0.2424

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62384 | val 0.96584
  Epoch 020 - train 0.66818 | val 1.03190
  Epoch 021 - train 0.63633 | val 1.03321
  Classification -> best τ=0.455 (val F1=0.0325)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65328 | val 0.92351
  Epoch 020 - train 0.66946 | val 0.92184
  Epoch 021 - train 0.67265 | val 0.92188
  Classification -> best τ=0.425 (val F1=0.0922)
  Directional -> Accuracy: 0.6491, MCC: 0.3225, F1: 0.6296

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66579 | val 1.27854
  Epoch 020 - train 0.64887 | val 1.35119
  Epoch 021 - train 0.66017 | val 1.35913
  Classification -> best τ=0.535 (val F1=0.2743)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68793 | val 1.08866
  Epoch 020 - train 0.66143 | val 1.17694
  Epoch 021 - train 0.65460 | val 1.17863
  Classification -> best τ=0.485 (val F1=0.2387)
  Directional -> Accuracy: 0.4909, MCC: -0.1839, F1: 0.6585

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-19 23:16:12,266] Trial 18 finished with value: 0.21964649901752129 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.00047794002762892876, 'weight_decay': 0.00021313135762401154, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.7484336636806457, 'early_stopping_min_delta': 0.002387099733996538}. Best is trial 12 with value: 0.25712235217334833.

  Classification -> best τ=0.485 (val F1=0.2653)
  Directional -> Accuracy: 0.4032, MCC: -0.2807, F1: 0.0976

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21964649901752129
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66315 | val 0.79491
  Epoch 020 - train 0.60606 | val 1.17050
  Epoch 022 - train 0.61187 | val 1.24825
  Classification -> best τ=0.890 (val F1=0.2346)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64486 | val 1.01824
  Epoch 020 - train 0.59357 | val 0.88237
  Epoch 022 - train 0.58266 | val 0.87695
  Classification -> best τ=0.470 (val F1=0.2928)
  Directional -> Accuracy: 0.6042, MCC: 0.1680, F1: 0.7077

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67554 | val 0.76551
  Epoch 020 - train 0.63342 | val 0.76640
  Epoch 021 - train 0.63976 | val 0.76515
  Classification -> best τ=0.575 (val F1=0.3077)
  Directional -> Accuracy: 0.4694, MCC: -0.0127, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64147 | val 0.72134
  Epoch 020 - train 0.63156 | val 0.91154
  Epoch 030 - train 0.60044 | val 0.67966
  Classification -> best τ=0.490 (val F1=0.3516)
  Directional -> Accuracy: 0.4156, MCC: -0.1547, F1: 0.3836

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63045 | val 1.02520
  Epoch 020 - train 0.58737 | val 1.92448
  Epoch 021 - train 0.59513 | val 1.94464
  Classification -> best τ=0.675 (val F1=0.4274)
  Directional -> Accuracy: 0.4528, MCC: -0.0760, F1: 0.2162

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62374 | val 0.73271
  Epoch 020 - train 0.54466 | val 0.79179
  Epoch 024 - train 0.54299 | val 0.79642
  Classification -> best τ=0.615 (val F1=0.2572)
  Directional -> Accuracy: 0.5366, MCC: 0.0649, F1: 0.4865

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68079 | val 1.05586
  Epoch 020 - train 0.62613 | val 1.51759
  Epoch 022 - train 0.63821 | val 1.46976
  Classification -> best τ=0.445 (val F1=0.2509)
  Directional -> Accuracy: 0.4648, MCC: 0.1494, F1: 0.5957

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53605 | val 1.00514
  Epoch 020 - train 0.57089 | val 1.31819
  Epoch 026 - train 0.48208 | val 1.16268
  Classification -> best τ=0.295 (val F1=0.1936)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65507 | val 0.70999
  Epoch 020 - train 0.61206 | val 0.76706
  Epoch 021 - train 0.61771 | val 0.77835
  Classification -> best τ=0.500 (val F1=0.3015)
  Directional -> Accuracy: 0.5116, MCC: 0.0701, F1: 0.5116

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60476 | val 1.14483
  Epoch 020 - train 0.54001 | val 1.26254
  Epoch 021 - train 0.50865 | val 1.27207
  Classification -> best τ=0.320 (val F1=0.1819)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65763 | val 0.94121
  Epoch 020 - train 0.58798 | val 0.81842
  Epoch 022 - train 0.58902 | val 0.82950
  Classification -> best τ=0.490 (val F1=0.1325)
  Directional -> Accuracy: 0.5192, MCC: -0.1296, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69016 | val 0.70401
  Epoch 020 - train 0.62504 | val 0.79073
  Epoch 023 - train 0.61867 | val 0.82213
  Classification -> best τ=0.530 (val F1=0.2010)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.6216

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59254 | val 0.86961
  Epoch 020 - train 0.54899 | val 0.97955
  Epoch 022 - train 0.51733 | val 1.04939
  Classification -> best τ=0.375 (val F1=0.2548)
  Directional -> Accuracy: 0.4889, MCC: -0.0434, F1: 0.3784

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65003 | val 0.89028
  Epoch 020 - train 0.59950 | val 1.02183
  Epoch 025 - train 0.59429 | val 1.09493
  Classification -> best τ=0.390 (val F1=0.3671)
  Directional -> Accuracy: 0.5397, MCC: 0.1296, F1: 0.6588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64067 | val 1.68816
  Epoch 020 - train 0.58227 | val 2.19248
  Epoch 024 - train 0.55209 | val 2.31819
  Classification -> best τ=0.565 (val F1=0.3365)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63107 | val 1.03408
  Epoch 020 - train 0.57742 | val 1.25961
  Epoch 021 - train 0.57145 | val 1.24834
  Classification -> best τ=0.565 (val F1=0.1458)
  Directional -> Accuracy: 0.5972, MCC: 0.1763, F1: 0.6813

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64560 | val 1.38467
  Epoch 020 - train 0.64346 | val 1.84446
  Epoch 021 - train 0.61301 | val 1.84794
  Classification -> best τ=0.725 (val F1=0.2383)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66624 | val 1.02266
  Epoch 020 - train 0.62861 | val 1.38887
  Epoch 021 - train 0.60380 | val 1.41389
  Classification -> best τ=0.605 (val F1=0.2486)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65240 | val 0.85646
  Epoch 020 - train 0.59485 | val 1.03848
  Epoch 022 - train 0.61868 | val 1.03854
  Classification -> best τ=0.605 (val F1=0.2279)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64041 | val 0.80587
  Epoch 020 - train 0.57809 | val 0.89482
  Epoch 021 - train 0.55517 | val 0.91841
  Classification -> best τ=0.530 (val F1=0.2913)
  Directional -> Accuracy: 0.4805, MCC: 0.0544, F1: 0.2000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61634 | val 0.74704
  Epoch 020 - train 0.58380 | val 0.76656
  Epoch 021 - train 0.57154 | val 0.78602
  Classification -> best τ=0.515 (val F1=0.2191)
  Directional -> Accuracy: 0.5800, MCC: 0.1959, F1: 0.6038

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67774 | val 0.68953
  Epoch 020 - train 0.63717 | val 0.75527
  Epoch 027 - train 0.62525 | val 0.76233
  Classification -> best τ=0.450 (val F1=0.2648)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5143

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64042 | val 0.77152
  Epoch 020 - train 0.62417 | val 0.87619
  Epoch 021 - train 0.58909 | val 0.91520
  Classification -> best τ=0.575 (val F1=0.1346)
  Directional -> Accuracy: 0.4667, MCC: 0.0710, F1: 0.2727

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69484 | val 0.70714
  Epoch 020 - train 0.59731 | val 0.70344
  Epoch 028 - train 0.55269 | val 0.71251
  Classification -> best τ=0.460 (val F1=0.1456)
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61566 | val 0.74937
  Epoch 020 - train 0.59063 | val 0.99228
  Epoch 022 - train 0.53817 | val 1.04100
  Classification -> best τ=0.485 (val F1=0.4032)
  Directional -> Accuracy: 0.5345, MCC: 0.1020, F1: 0.4906

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60280 | val 0.80096
  Epoch 020 - train 0.52981 | val 0.95159
  Epoch 024 - train 0.50470 | val 0.98670
  Classification -> best τ=0.450 (val F1=0.3056)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67994 | val 0.78335
  Epoch 020 - train 0.61889 | val 0.74787
  Epoch 030 - train 0.62193 | val 0.75045
  Classification -> best τ=0.315 (val F1=0.1612)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66725 | val 1.16276
  Epoch 020 - train 0.63477 | val 1.34426
  Epoch 021 - train 0.62035 | val 1.35561
  Classification -> best τ=0.470 (val F1=0.3466)
  Directional -> Accuracy: 0.5085, MCC: 0.2394, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61134 | val 1.98475
  Epoch 020 - train 0.54496 | val 1.58450
  Epoch 023 - train 0.60263 | val 1.73013
  Classification -> best τ=0.495 (val F1=0.2908)
  Directional -> Accuracy: 0.5909, MCC: 0.1839, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63162 | val 0.79217
  Epoch 020 - train 0.52718 | val 0.89666
  Epoch 022 - train 0.57395 | val 0.89180
  Classification -> best τ=0.525 (val F1=0.1836)
  Directional -> Accuracy: 0.5217, MCC: 0.0442, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69887 | val 0.91587
  Epoch 020 - train 0.65802 | val 0.96051
  Epoch 023 - train 0.64150 | val 0.98676
  Classification -> best τ=0.540 (val F1=0.3377)
  Directional -> Accuracy: 0.6304, MCC: 0.2474, F1: 0.7018

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59443 | val 1.22659
  Epoch 020 - train 0.51920 | val 1.56429
  Epoch 022 - train 0.52878 | val 1.58844
  Classification -> best τ=0.430 (val F1=0.2187)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61478 | val 0.71705
  Epoch 020 - train 0.58469 | val 0.82231
  Epoch 021 - train 0.58440 | val 0.83475
  Classification -> best τ=0.455 (val F1=0.3351)
  Directional -> Accuracy: 0.5200, MCC: 0.0991, F1: 0.4375

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68709 | val 0.73075
  Epoch 020 - train 0.61927 | val 0.79977
  Epoch 021 - train 0.58717 | val 0.79124
  Classification -> best τ=0.500 (val F1=0.2774)
  Directional -> Accuracy: 0.5610, MCC: 0.1280, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59260 | val 1.71197
  Epoch 020 - train 0.58248 | val 1.91450
  Epoch 021 - train 0.52689 | val 2.03522
  Classification -> best τ=0.565 (val F1=0.2081)
  Directional -> Accuracy: 0.5000, MCC: 0.0371, F1: 0.5660

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61501 | val 0.72691
  Epoch 020 - train 0.54928 | val 0.70595
  Epoch 021 - train 0.56910 | val 0.70483
  Classification -> best τ=0.415 (val F1=0.2460)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.7339

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63708 | val 1.03834
  Epoch 020 - train 0.58378 | val 0.88967
  Epoch 023 - train 0.55861 | val 0.88642
  Classification -> best τ=0.495 (val F1=0.2651)
  Directional -> Accuracy: 0.6222, MCC: 0.3089, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63990 | val 1.21296
  Epoch 020 - train 0.61778 | val 1.66333
  Epoch 021 - train 0.62286 | val 1.66525
  Classification -> best τ=0.445 (val F1=0.2289)
  Directional -> Accuracy: 0.5593, MCC: 0.1651, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61208 | val 2.09411
  Epoch 020 - train 0.49327 | val 2.19379
  Epoch 021 - train 0.49776 | val 2.24889
  Classification -> best τ=0.745 (val F1=0.1741)
  Directional -> Accuracy: 0.4490, MCC: 0.0530, F1: 0.3077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62193 | val 0.66903
  Epoch 020 - train 0.54918 | val 0.69228
  Epoch 025 - train 0.52760 | val 0.76779
  Classification -> best τ=0.315 (val F1=0.4411)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62801 | val 0.87327
  Epoch 020 - train 0.60691 | val 0.80746
  Epoch 021 - train 0.54128 | val 0.80882
  Classification -> best τ=0.405 (val F1=0.3194)
  Directional -> Accuracy: 0.5122, MCC: 0.0139, F1: 0.6154

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60755 | val 1.50991
  Epoch 020 - train 0.58332 | val 2.18213
  Epoch 021 - train 0.61728 | val 2.06478
  Classification -> best τ=0.460 (val F1=0.2447)
  Directional -> Accuracy: 0.5325, MCC: 0.1201, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68278 | val 0.92968
  Epoch 020 - train 0.60321 | val 0.99792
  Epoch 021 - train 0.63036 | val 0.99856
  Classification -> best τ=0.515 (val F1=0.1282)
  Directional -> Accuracy: 0.5714, MCC: 0.1678, F1: 0.3636

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55276 | val 1.20825
  Epoch 020 - train 0.51892 | val 1.14682
  Epoch 021 - train 0.57655 | val 1.12563
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57559 | val 1.09637
  Epoch 020 - train 0.57346 | val 0.97840
  Epoch 021 - train 0.53693 | val 0.99521
  Classification -> best τ=0.610 (val F1=0.1425)
  Directional -> Accuracy: 0.5476, MCC: -0.0314, F1: 0.2963

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68677 | val 0.69801
  Epoch 020 - train 0.65876 | val 0.75327
  Epoch 029 - train 0.63159 | val 0.79749
  Classification -> best τ=0.645 (val F1=0.2837)
  Directional -> Accuracy: 0.5345, MCC: 0.2275, F1: 0.3077

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61020 | val 1.89814
  Epoch 020 - train 0.59895 | val 2.02815
  Epoch 022 - train 0.56784 | val 2.04853
  Classification -> best τ=0.715 (val F1=0.4281)
  Directional -> Accuracy: 0.5254, MCC: 0.0488, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65583 | val 1.46921
  Epoch 020 - train 0.62091 | val 1.47762
  Epoch 022 - train 0.61678 | val 1.51528
  Classification -> best τ=0.415 (val F1=0.1553)
  Directional -> Accuracy: 0.5357, MCC: 0.0248, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-19 23:18:08,357] Trial 19 finished with value: 0.24994512669496408 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.003453528362733125, 'weight_decay': 0.00040367004283921163, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.1693357665462951, 'early_stopping_min_delta': 0.0009955969495597332}. Best is trial 12 with value: 0.25712235217334833.

  Epoch 024 - train 0.59764 | val 0.74431
  Classification -> best τ=0.550 (val F1=0.2500)
  Directional -> Accuracy: 0.5238, MCC: 0.0086, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24994512669496408
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67223 | val 0.69258
  Epoch 020 - train 0.65903 | val 0.71556
  Epoch 022 - train 0.65804 | val 0.71804
  Classification -> best τ=0.520 (val F1=0.2463)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66224 | val 0.69462
  Epoch 020 - train 0.65472 | val 0.70259
  Epoch 021 - train 0.65970 | val 0.70206
  Classification -> best τ=0.455 (val F1=0.1730)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67306 | val 0.69693
  Epoch 020 - train 0.67594 | val 0.75202
  Epoch 023 - train 0.64648 | val 0.74709
  Classification -> best τ=0.455 (val F1=0.1758)
  Directional -> Accuracy: 0.5208, MCC: 0.0384, F1: 0.5490

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66698 | val 0.76500
  Epoch 020 - train 0.63630 | val 0.75880
  Epoch 026 - train 0.64573 | val 0.71185
  Classification -> best τ=0.445 (val F1=0.2635)
  Directional -> Accuracy: 0.5263, MCC: 0.0389, F1: 0.5814

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63671 | val 0.64846
  Epoch 020 - train 0.62695 | val 0.66642
  Epoch 025 - train 0.60380 | val 0.66700
  Classification -> best τ=0.450 (val F1=0.4225)
  Directional -> Accuracy: 0.7692, MCC: 0.5357, F1: 0.7857

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63379 | val 0.96259
  Epoch 020 - train 0.60772 | val 1.14134
  Epoch 021 - train 0.61077 | val 1.15502
  Classification -> best τ=0.475 (val F1=0.1903)
  Directional -> Accuracy: 0.4694, MCC: -0.0667, F1: 0.1875

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66631 | val 0.77385
  Epoch 020 - train 0.66372 | val 0.77992
  Epoch 021 - train 0.66717 | val 0.78144
  Classification -> best τ=0.495 (val F1=0.2142)
  Directional -> Accuracy: 0.4571, MCC: 0.0278, F1: 0.5366

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66223 | val 1.03536
  Epoch 020 - train 0.63182 | val 1.29656
  Epoch 021 - train 0.64676 | val 1.30531
  Classification -> best τ=0.530 (val F1=0.3669)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.2609

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65550 | val 0.80588
  Epoch 020 - train 0.64257 | val 0.87249
  Epoch 024 - train 0.63327 | val 0.87754
  Classification -> best τ=0.555 (val F1=0.3928)
  Directional -> Accuracy: 0.5238, MCC: -0.0932, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61700 | val 0.89767
  Epoch 020 - train 0.64133 | val 0.87232
  Epoch 021 - train 0.62161 | val 0.86868
  Classification -> best τ=0.405 (val F1=0.2108)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64506 | val 0.95451
  Epoch 020 - train 0.63442 | val 1.02506
  Epoch 021 - train 0.65970 | val 1.03264
  Classification -> best τ=0.545 (val F1=0.2179)
  Directional -> Accuracy: 0.5882, MCC: 0.1673, F1: 0.5116

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68387 | val 0.71663
  Epoch 020 - train 0.66116 | val 0.72589
  Epoch 021 - train 0.66320 | val 0.72773
  Classification -> best τ=0.565 (val F1=0.1663)
  Directional -> Accuracy: 0.5763, MCC: 0.2285, F1: 0.3590

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62673 | val 0.90539
  Epoch 020 - train 0.61053 | val 0.90145
  Epoch 021 - train 0.61323 | val 0.90401
  Classification -> best τ=0.520 (val F1=0.2509)
  Directional -> Accuracy: 0.5227, MCC: -0.0103, F1: 0.2759

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65925 | val 0.62791
  Epoch 020 - train 0.63875 | val 0.63368
  Epoch 030 - train 0.63044 | val 0.64483
  Classification -> best τ=0.305 (val F1=0.3138)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65595 | val 0.89457
  Epoch 020 - train 0.64237 | val 0.92840
  Epoch 021 - train 0.64434 | val 0.92362
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64696 | val 0.73241
  Epoch 020 - train 0.63800 | val 0.75717
  Epoch 022 - train 0.61771 | val 0.75516
  Classification -> best τ=0.395 (val F1=0.2527)
  Directional -> Accuracy: 0.5775, MCC: 0.1850, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65256 | val 1.15102
  Epoch 020 - train 0.66285 | val 1.26906
  Epoch 021 - train 0.64919 | val 1.26648
  Classification -> best τ=0.485 (val F1=0.1356)
  Directional -> Accuracy: 0.5833, MCC: -0.1464, F1: 0.7368

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65983 | val 1.08384
  Epoch 020 - train 0.65930 | val 1.20590
  Epoch 021 - train 0.65606 | val 1.20552
  Classification -> best τ=0.560 (val F1=0.1080)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66316 | val 0.76900
  Epoch 020 - train 0.66236 | val 0.76879
  Epoch 021 - train 0.64509 | val 0.76868
  Classification -> best τ=0.435 (val F1=0.1312)
  Directional -> Accuracy: 0.5455, MCC: 0.2306, F1: 0.4444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65762 | val 0.68825
  Epoch 020 - train 0.63797 | val 0.68592
  Epoch 023 - train 0.62839 | val 0.68685
  Classification -> best τ=0.530 (val F1=0.2332)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65317 | val 0.67994
  Epoch 020 - train 0.64358 | val 0.66510
  Epoch 030 - train 0.58896 | val 0.64861
  Classification -> best τ=0.415 (val F1=0.3513)
  Directional -> Accuracy: 0.3878, MCC: 0.1100, F1: 0.0625

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66346 | val 0.82805
  Epoch 020 - train 0.66552 | val 0.85501
  Epoch 021 - train 0.66342 | val 0.85164
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65162 | val 0.84260
  Epoch 020 - train 0.66282 | val 0.85385
  Epoch 021 - train 0.64463 | val 0.85770
  Classification -> best τ=0.570 (val F1=0.1291)
  Directional -> Accuracy: 0.4407, MCC: -0.0407, F1: 0.2979

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66671 | val 0.78878
  Epoch 020 - train 0.64319 | val 0.72971
  Epoch 021 - train 0.65486 | val 0.72675
  Classification -> best τ=0.400 (val F1=0.2338)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64418 | val 0.64860
  Epoch 020 - train 0.61972 | val 0.67977
  Epoch 025 - train 0.59325 | val 0.68460
  Classification -> best τ=0.510 (val F1=0.5137)
  Directional -> Accuracy: 0.6140, MCC: 0.2794, F1: 0.5769

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65308 | val 0.79162
  Epoch 020 - train 0.65220 | val 0.82306
  Epoch 021 - train 0.62871 | val 0.82090
  Classification -> best τ=0.470 (val F1=0.0555)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66453 | val 0.86645
  Epoch 020 - train 0.63582 | val 0.82360
  Epoch 021 - train 0.63625 | val 0.82424
  Classification -> best τ=0.440 (val F1=0.1267)
  Directional -> Accuracy: 0.5227, MCC: 0.0212, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64484 | val 0.72551
  Epoch 020 - train 0.64115 | val 0.73881
  Epoch 022 - train 0.60675 | val 0.73833
  Classification -> best τ=0.460 (val F1=0.2033)
  Directional -> Accuracy: 0.5345, MCC: 0.1708, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64734 | val 0.71363
  Epoch 020 - train 0.63306 | val 0.68758
  Epoch 030 - train 0.60738 | val 0.66259
  Classification -> best τ=0.570 (val F1=0.3948)
  Directional -> Accuracy: 0.5581, MCC: 0.1217, F1: 0.5581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66682 | val 0.75437
  Epoch 020 - train 0.64875 | val 0.79615
  Epoch 021 - train 0.65720 | val 0.79918
  Classification -> best τ=0.505 (val F1=0.1000)
  Directional -> Accuracy: 0.4889, MCC: -0.0391, F1: 0.5965

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67091 | val 0.77007
  Epoch 020 - train 0.67456 | val 0.75312
  Epoch 021 - train 0.66461 | val 0.75306
  Classification -> best τ=0.475 (val F1=0.2754)
  Directional -> Accuracy: 0.4444, MCC: -0.1612, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64407 | val 0.69921
  Epoch 020 - train 0.62602 | val 0.69397
  Epoch 021 - train 0.62653 | val 0.69509
  Classification -> best τ=0.525 (val F1=0.2335)
  Directional -> Accuracy: 0.5490, MCC: 0.1525, F1: 0.4103

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66113 | val 0.70974
  Epoch 020 - train 0.64508 | val 0.73709
  Epoch 023 - train 0.63895 | val 0.74014
  Classification -> best τ=0.410 (val F1=0.3655)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67093 | val 0.68551
  Epoch 020 - train 0.63089 | val 0.70357
  Epoch 028 - train 0.59684 | val 0.70882
  Classification -> best τ=0.495 (val F1=0.3024)
  Directional -> Accuracy: 0.4872, MCC: -0.0151, F1: 0.5833

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66358 | val 0.82160
  Epoch 020 - train 0.64018 | val 0.87206
  Epoch 021 - train 0.64965 | val 0.87074
  Classification -> best τ=0.500 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62671 | val 0.73210
  Epoch 020 - train 0.61562 | val 0.76789
  Epoch 022 - train 0.60403 | val 0.77089
  Classification -> best τ=0.390 (val F1=0.4021)
  Directional -> Accuracy: 0.5735, MCC: 0.2150, F1: 0.5246

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65990 | val 0.72350
  Epoch 020 - train 0.63241 | val 0.73240
  Epoch 021 - train 0.63137 | val 0.73197
  Classification -> best τ=0.495 (val F1=0.2100)
  Directional -> Accuracy: 0.4318, MCC: -0.1575, F1: 0.2424

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63229 | val 0.75774
  Epoch 020 - train 0.61751 | val 0.77001
  Epoch 021 - train 0.61901 | val 0.77006
  Classification -> best τ=0.445 (val F1=0.1687)
  Directional -> Accuracy: 0.5345, MCC: 0.1226, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63172 | val 1.05309
  Epoch 020 - train 0.63385 | val 1.14333
  Epoch 021 - train 0.62523 | val 1.15119
  Classification -> best τ=0.525 (val F1=0.2799)
  Directional -> Accuracy: 0.5208, MCC: -0.1516, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65461 | val 0.69845
  Epoch 020 - train 0.64555 | val 0.67738
  Epoch 030 - train 0.58954 | val 0.67683
  Classification -> best τ=0.480 (val F1=0.3873)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64621 | val 0.77176
  Epoch 020 - train 0.65991 | val 0.81348
  Epoch 021 - train 0.65638 | val 0.81724
  Classification -> best τ=0.470 (val F1=0.1704)
  Directional -> Accuracy: 0.5641, MCC: 0.1055, F1: 0.6531

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65365 | val 0.73003
  Epoch 020 - train 0.61956 | val 0.82915
  Epoch 024 - train 0.64072 | val 0.83679
  Classification -> best τ=0.410 (val F1=0.2812)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66952 | val 0.72263
  Epoch 020 - train 0.62653 | val 0.75061
  Epoch 023 - train 0.64824 | val 0.75876
  Classification -> best τ=0.470 (val F1=0.2569)
  Directional -> Accuracy: 0.5208, MCC: 0.1459, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65357 | val 0.79058
  Epoch 020 - train 0.62658 | val 0.84306
  Epoch 021 - train 0.60141 | val 0.84530
  Classification -> best τ=0.500 (val F1=0.1474)
  Directional -> Accuracy: 0.4444, MCC: -0.0913, F1: 0.4186

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64534 | val 0.99985
  Epoch 020 - train 0.62289 | val 1.10497
  Epoch 021 - train 0.62955 | val 1.10238
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64569 | val 0.84546
  Epoch 020 - train 0.64835 | val 0.89352
  Epoch 021 - train 0.63741 | val 0.89446
  Classification -> best τ=0.480 (val F1=0.2973)
  Directional -> Accuracy: 0.5965, MCC: 0.1769, F1: 0.7013

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63282 | val 0.99387
  Epoch 020 - train 0.63137 | val 1.11255
  Epoch 021 - train 0.65020 | val 1.11403
  Classification -> best τ=0.535 (val F1=0.2334)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65544 | val 1.06142
  Epoch 020 - train 0.64948 | val 1.18711
  Epoch 021 - train 0.63883 | val 1.17581
  Classification -> best τ=0.445 (val F1=0.1129)
  Directional -> Accuracy: 0.6000, MCC: 0.1976, F1: 0.6207

[87/88] Processing WMT...


[I 2026-02-19 23:20:45,929] Trial 20 finished with value: 0.22835910541566204 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.0003072814049612642, 'weight_decay': 1.0747877623801468e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.49664210891954264, 'early_stopping_min_delta': 0.004139468639660407}. Best is trial 12 with value: 0.25712235217334833.

  Classification -> best τ=0.605 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22835910541566204
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64374 | val 0.68510
  Epoch 020 - train 0.65263 | val 0.89695
  Epoch 022 - train 0.61678 | val 0.89239
  Classification -> best τ=0.715 (val F1=0.2727)
  Directional -> Accuracy: 0.5443, MCC: -0.0091, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64761 | val 0.73910
  Epoch 020 - train 0.59938 | val 0.81739
  Epoch 021 - train 0.60664 | val 0.80869
  Classification -> best τ=0.480 (val F1=0.0727)
  Directional -> Accuracy: 0.5833, MCC: 0.1193, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67875 | val 0.74600
  Epoch 020 - train 0.59610 | val 0.70775
  Epoch 024 - train 0.58756 | val 0.72098
  Classification -> best τ=0.555 (val F1=0.3724)
  Directional -> Accuracy: 0.4490, MCC: -0.0835, F1: 0.1818

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70440 | val 0.69428
  Epoch 020 - train 0.62168 | val 0.86170
  Epoch 028 - train 0.61552 | val 0.79476
  Classification -> best τ=0.460 (val F1=0.3053)
  Directional -> Accuracy: 0.4805, MCC: 0.0054, F1: 0.3548

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63533 | val 1.75213
  Epoch 020 - train 0.57662 | val 3.12054
  Epoch 022 - train 0.56176 | val 3.25129
  Classification -> best τ=0.640 (val F1=0.4557)
  Directional -> Accuracy: 0.6038, MCC: 0.2751, F1: 0.4878

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62398 | val 0.72626
  Epoch 020 - train 0.57083 | val 0.71431
  Epoch 030 - train 0.50272 | val 0.73613
  Classification -> best τ=0.375 (val F1=0.2460)
  Directional -> Accuracy: 0.4878, MCC: 0.1469, F1: 0.6441

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66000 | val 0.98524
  Epoch 020 - train 0.65089 | val 1.09041
  Epoch 021 - train 0.63736 | val 1.15476
  Classification -> best τ=0.385 (val F1=0.3338)
  Directional -> Accuracy: 0.5070, MCC: 0.1493, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64295 | val 1.02366
  Epoch 020 - train 0.51444 | val 1.13144
  Epoch 024 - train 0.49992 | val 1.11708
  Classification -> best τ=0.205 (val F1=0.1217)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64642 | val 0.95950
  Epoch 020 - train 0.57318 | val 0.94073
  Epoch 024 - train 0.56393 | val 0.89254
  Classification -> best τ=0.650 (val F1=0.3466)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57875 | val 1.13002
  Epoch 020 - train 0.53070 | val 1.33540
  Epoch 021 - train 0.53454 | val 1.33100
  Classification -> best τ=0.395 (val F1=0.2764)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70096 | val 0.83426
  Epoch 020 - train 0.60827 | val 0.87306
  Epoch 024 - train 0.62131 | val 0.86025
  Classification -> best τ=0.675 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66941 | val 0.79500
  Epoch 020 - train 0.66499 | val 0.98434
  Epoch 021 - train 0.62641 | val 1.00490
  Classification -> best τ=0.385 (val F1=0.2053)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66148 | val 0.75559
  Epoch 020 - train 0.51971 | val 0.74237
  Epoch 026 - train 0.49843 | val 0.87013
  Classification -> best τ=0.590 (val F1=0.3203)
  Directional -> Accuracy: 0.5556, MCC: 0.0901, F1: 0.2857

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67073 | val 0.82610
  Epoch 020 - train 0.60588 | val 1.20691
  Epoch 024 - train 0.59685 | val 1.31415
  Classification -> best τ=0.640 (val F1=0.3883)
  Directional -> Accuracy: 0.5397, MCC: 0.0809, F1: 0.5538

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66828 | val 1.40428
  Epoch 020 - train 0.57794 | val 1.91778
  Epoch 022 - train 0.58753 | val 1.99764
  Classification -> best τ=0.605 (val F1=0.2693)
  Directional -> Accuracy: 0.6111, MCC: 0.2213, F1: 0.5333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61826 | val 1.30518
  Epoch 020 - train 0.57645 | val 1.30471
  Epoch 021 - train 0.57401 | val 1.30979
  Classification -> best τ=0.450 (val F1=0.2398)
  Directional -> Accuracy: 0.6250, MCC: 0.3278, F1: 0.7429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65788 | val 1.69684
  Epoch 020 - train 0.62746 | val 2.19812
  Epoch 021 - train 0.58795 | val 2.25892
  Classification -> best τ=0.740 (val F1=0.1559)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66457 | val 1.15203
  Epoch 020 - train 0.62753 | val 1.43330
  Epoch 021 - train 0.62371 | val 1.46273
  Classification -> best τ=0.235 (val F1=0.2195)
  Directional -> Accuracy: 0.6026, MCC: 0.1065, F1: 0.7156

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68130 | val 0.69548
  Epoch 020 - train 0.60068 | val 0.96947
  Epoch 025 - train 0.58853 | val 0.99216
  Classification -> best τ=0.185 (val F1=0.2933)
  Directional -> Accuracy: 0.5522, MCC: 0.0222, F1: 0.6667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60759 | val 0.68128
  Epoch 020 - train 0.58938 | val 0.75202
  Epoch 030 - train 0.49941 | val 1.05922
  Classification -> best τ=0.270 (val F1=0.2236)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62309 | val 0.75961
  Epoch 020 - train 0.57699 | val 0.69235
  Epoch 021 - train 0.54013 | val 0.70425
  Classification -> best τ=0.495 (val F1=0.1746)
  Directional -> Accuracy: 0.5800, MCC: 0.1959, F1: 0.6038

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69352 | val 0.83525
  Epoch 020 - train 0.62617 | val 0.78000
  Epoch 028 - train 0.57927 | val 0.77186
  Classification -> best τ=0.595 (val F1=0.2910)
  Directional -> Accuracy: 0.4412, MCC: -0.1257, F1: 0.3214

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67000 | val 1.02904
  Epoch 020 - train 0.62310 | val 0.83429
  Epoch 021 - train 0.62895 | val 0.82601
  Classification -> best τ=0.610 (val F1=0.2372)
  Directional -> Accuracy: 0.5500, MCC: 0.2039, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61644 | val 0.85796
  Epoch 020 - train 0.56328 | val 0.75826
  Epoch 021 - train 0.57557 | val 0.75578
  Classification -> best τ=0.380 (val F1=0.1021)
  Directional -> Accuracy: 0.5588, MCC: 0.1529, F1: 0.6429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62405 | val 0.70298
  Epoch 020 - train 0.58195 | val 0.81177
  Epoch 023 - train 0.56386 | val 0.80948
  Classification -> best τ=0.405 (val F1=0.4766)
  Directional -> Accuracy: 0.5862, MCC: 0.1942, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61807 | val 0.70233
  Epoch 020 - train 0.52726 | val 1.38207
  Epoch 029 - train 0.41190 | val 1.72486
  Classification -> best τ=0.580 (val F1=0.4135)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70523 | val 0.69127
  Epoch 020 - train 0.65312 | val 0.68828
  Epoch 030 - train 0.56897 | val 0.68023
  Classification -> best τ=0.570 (val F1=0.2450)
  Directional -> Accuracy: 0.4667, MCC: 0.2182, F1: 0.2000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63353 | val 1.23765
  Epoch 020 - train 0.59777 | val 1.53236
  Epoch 021 - train 0.60555 | val 1.54894
  Classification -> best τ=0.475 (val F1=0.2356)
  Directional -> Accuracy: 0.5593, MCC: 0.2816, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61453 | val 1.24861
  Epoch 020 - train 0.60020 | val 1.52815
  Epoch 023 - train 0.51370 | val 1.63499
  Classification -> best τ=0.610 (val F1=0.2345)
  Directional -> Accuracy: 0.5000, MCC: 0.0063, F1: 0.4762

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70277 | val 0.89041
  Epoch 020 - train 0.55310 | val 0.89599
  Epoch 021 - train 0.54053 | val 0.88706
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66464 | val 0.68132
  Epoch 020 - train 0.60205 | val 1.04302
  Epoch 027 - train 0.56930 | val 1.06966
  Classification -> best τ=0.530 (val F1=0.2425)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59324 | val 0.76502
  Epoch 020 - train 0.54646 | val 0.90111
  Epoch 022 - train 0.52063 | val 0.86869
  Classification -> best τ=0.655 (val F1=0.2879)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62411 | val 0.72916
  Epoch 020 - train 0.58492 | val 0.89022
  Epoch 029 - train 0.58876 | val 0.93948
  Classification -> best τ=0.860 (val F1=0.3028)
  Directional -> Accuracy: 0.5067, MCC: 0.0950, F1: 0.3729

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73379 | val 0.72881
  Epoch 020 - train 0.57657 | val 0.74317
  Epoch 021 - train 0.56831 | val 0.74599
  Classification -> best τ=0.520 (val F1=0.2774)
  Directional -> Accuracy: 0.5610, MCC: 0.1504, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63776 | val 1.72627
  Epoch 020 - train 0.55247 | val 2.33376
  Epoch 021 - train 0.56973 | val 2.41397
  Classification -> best τ=0.510 (val F1=0.2024)
  Directional -> Accuracy: 0.5435, MCC: 0.0186, F1: 0.0870

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63324 | val 0.75732
  Epoch 020 - train 0.56987 | val 0.77409
  Epoch 021 - train 0.57481 | val 0.77270
  Classification -> best τ=0.410 (val F1=0.3138)
  Directional -> Accuracy: 0.5507, MCC: -0.0034, F1: 0.6804

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63140 | val 1.08278
  Epoch 020 - train 0.56954 | val 1.04027
  Epoch 022 - train 0.58076 | val 1.07221
  Classification -> best τ=0.380 (val F1=0.3382)
  Directional -> Accuracy: 0.6000, MCC: 0.2460, F1: 0.4706

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65819 | val 0.84439
  Epoch 020 - train 0.63468 | val 0.98088
  Epoch 022 - train 0.63298 | val 1.00944
  Classification -> best τ=0.350 (val F1=0.3753)
  Directional -> Accuracy: 0.5593, MCC: 0.1465, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60760 | val 1.47912
  Epoch 020 - train 0.49692 | val 1.69186
  Epoch 021 - train 0.51185 | val 1.70835
  Classification -> best τ=0.510 (val F1=0.2373)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67132 | val 0.65714
  Epoch 020 - train 0.54410 | val 0.72479
  Epoch 026 - train 0.51245 | val 0.75087
  Classification -> best τ=0.380 (val F1=0.4142)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62506 | val 0.92280
  Epoch 020 - train 0.54803 | val 1.01373
  Epoch 021 - train 0.50199 | val 0.96048
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64950 | val 1.51860
  Epoch 020 - train 0.59216 | val 1.53692
  Epoch 022 - train 0.57154 | val 1.57247
  Classification -> best τ=0.330 (val F1=0.2717)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64814 | val 1.15174
  Epoch 020 - train 0.63887 | val 0.98040
  Epoch 021 - train 0.60286 | val 0.98332
  Classification -> best τ=0.540 (val F1=0.3462)
  Directional -> Accuracy: 0.5918, MCC: 0.2129, F1: 0.4118

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62897 | val 1.85587
  Epoch 020 - train 0.55701 | val 2.37187
  Epoch 021 - train 0.48115 | val 2.34140
  Classification -> best τ=0.480 (val F1=0.1754)
  Directional -> Accuracy: 0.6170, MCC: 0.1866, F1: 0.7353

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55118 | val 0.80329
  Epoch 020 - train 0.51088 | val 1.24281
  Epoch 026 - train 0.53057 | val 0.99157
  Classification -> best τ=0.520 (val F1=0.2706)
  Directional -> Accuracy: 0.4286, MCC: 0.2067, F1: 0.5556

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68412 | val 0.68478
  Epoch 020 - train 0.65357 | val 0.70398
  Epoch 030 - train 0.64700 | val 0.72101
  Classification -> best τ=0.555 (val F1=0.2837)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61067 | val 2.03680
  Epoch 020 - train 0.55926 | val 1.87760
  Epoch 021 - train 0.58634 | val 1.82523
  Classification -> best τ=0.795 (val F1=0.3123)
  Directional -> Accuracy: 0.4746, MCC: -0.0811, F1: 0.6353

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64376 | val 1.78679
  Epoch 020 - train 0.62886 | val 1.89649
  Epoch 021 - train 0.62695 | val 1.85012
  Classification -> best τ=0.365 (val F1=0.1078)
  Directional -> Accuracy: 0.5536, MCC: 0.1448, F1: 0.7059

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-19 23:22:52,168] Trial 21 finished with value: 0.25545184115205766 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0032108472940887804, 'weight_decay': 0.0003445600013047142, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.1803337552033424, 'early_stopping_min_delta': 0.0009054523911791363}. Best is trial 12 with value: 0.25712235217334833.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25545184115205766
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67664 | val 0.66636
  Epoch 020 - train 0.67187 | val 0.67456
  Epoch 030 - train 0.63480 | val 0.71388
  Classification -> best τ=0.770 (val F1=0.2727)
  Directional -> Accuracy: 0.5316, MCC: -0.0460, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68786 | val 0.69340
  Epoch 020 - train 0.60268 | val 0.75254
  Epoch 028 - train 0.56063 | val 0.74202
  Classification -> best τ=0.450 (val F1=0.3016)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65264 | val 0.79503
  Epoch 020 - train 0.63771 | val 0.74338
  Epoch 022 - train 0.65323 | val 0.75034
  Classification -> best τ=0.515 (val F1=0.2964)
  Directional -> Accuracy: 0.4694, MCC: -0.0229, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66878 | val 0.71821
  Epoch 020 - train 0.65759 | val 0.70651
  Epoch 030 - train 0.64131 | val 0.70583
  Classification -> best τ=0.425 (val F1=0.2040)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66163 | val 0.81015
  Epoch 020 - train 0.64239 | val 1.61664
  Epoch 028 - train 0.60794 | val 1.60692
  Classification -> best τ=0.675 (val F1=0.3050)
  Directional -> Accuracy: 0.6604, MCC: 0.3584, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65028 | val 0.83790
  Epoch 020 - train 0.61905 | val 0.71348
  Epoch 024 - train 0.62187 | val 0.73960
  Classification -> best τ=0.650 (val F1=0.2521)
  Directional -> Accuracy: 0.5366, MCC: 0.0304, F1: 0.2400

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67922 | val 0.82773
  Epoch 020 - train 0.65561 | val 0.88835
  Epoch 022 - train 0.69034 | val 0.87035
  Classification -> best τ=0.485 (val F1=0.1709)
  Directional -> Accuracy: 0.5070, MCC: -0.0369, F1: 0.3636

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61941 | val 0.71827
  Epoch 020 - train 0.57538 | val 0.79596
  Epoch 030 - train 0.52997 | val 1.00297
  Classification -> best τ=0.170 (val F1=0.3651)
  Directional -> Accuracy: 0.5532, MCC: 0.1126, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.73333 | val 1.08309
  Epoch 020 - train 0.63313 | val 0.76558
  Epoch 030 - train 0.60138 | val 0.82244
  Classification -> best τ=0.625 (val F1=0.3429)
  Directional -> Accuracy: 0.5581, MCC: -0.0199, F1: 0.2400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68479 | val 0.96752
  Epoch 020 - train 0.60286 | val 1.21162
  Epoch 021 - train 0.59421 | val 1.24684
  Classification -> best τ=0.420 (val F1=0.0971)
  Directional -> Accuracy: 0.4028, MCC: -0.1380, F1: 0.5275

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71381 | val 0.69681
  Epoch 020 - train 0.65838 | val 0.75208
  Epoch 029 - train 0.63540 | val 0.73898
  Classification -> best τ=0.435 (val F1=0.2693)
  Directional -> Accuracy: 0.6538, MCC: 0.3077, F1: 0.5263

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69861 | val 0.72329
  Epoch 020 - train 0.67961 | val 0.76107
  Epoch 028 - train 0.66708 | val 0.78802
  Classification -> best τ=0.435 (val F1=0.2053)
  Directional -> Accuracy: 0.4833, MCC: -0.0467, F1: 0.6173

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62364 | val 0.79680
  Epoch 020 - train 0.59677 | val 0.90017
  Epoch 021 - train 0.58680 | val 0.89744
  Classification -> best τ=0.365 (val F1=0.2135)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68134 | val 0.71080
  Epoch 020 - train 0.64853 | val 0.98278
  Epoch 030 - train 0.61266 | val 1.22349
  Classification -> best τ=0.325 (val F1=0.3727)
  Directional -> Accuracy: 0.5397, MCC: 0.1029, F1: 0.6329

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69778 | val 0.81344
  Epoch 020 - train 0.61837 | val 1.04444
  Epoch 023 - train 0.63008 | val 1.02140
  Classification -> best τ=0.510 (val F1=0.3104)
  Directional -> Accuracy: 0.4444, MCC: -0.2035, F1: 0.6154

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65983 | val 0.98853
  Epoch 020 - train 0.60602 | val 1.26611
  Epoch 021 - train 0.60247 | val 1.23894
  Classification -> best τ=0.610 (val F1=0.2807)
  Directional -> Accuracy: 0.5139, MCC: 0.0279, F1: 0.5333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67722 | val 1.20927
  Epoch 020 - train 0.62843 | val 1.44291
  Epoch 021 - train 0.64394 | val 1.46922
  Classification -> best τ=0.780 (val F1=0.1064)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66296 | val 0.79934
  Epoch 020 - train 0.65765 | val 0.84188
  Epoch 021 - train 0.66056 | val 0.84499
  Classification -> best τ=0.630 (val F1=0.1900)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69825 | val 0.74839
  Epoch 020 - train 0.64344 | val 0.72892
  Epoch 024 - train 0.64306 | val 0.75487
  Classification -> best τ=0.500 (val F1=0.2635)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63212 | val 0.71724
  Epoch 020 - train 0.61997 | val 0.74579
  Epoch 022 - train 0.62142 | val 0.75250
  Classification -> best τ=0.530 (val F1=0.2309)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62705 | val 0.79951
  Epoch 020 - train 0.66698 | val 0.81626
  Epoch 021 - train 0.61854 | val 0.81183
  Classification -> best τ=0.515 (val F1=0.2632)
  Directional -> Accuracy: 0.5600, MCC: 0.0470, F1: 0.6562

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70793 | val 0.67698
  Epoch 020 - train 0.65619 | val 0.72314
  Epoch 027 - train 0.64564 | val 0.70112
  Classification -> best τ=0.540 (val F1=0.3554)
  Directional -> Accuracy: 0.4412, MCC: -0.1291, F1: 0.2963

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65634 | val 0.69009
  Epoch 020 - train 0.61828 | val 0.81157
  Epoch 024 - train 0.61468 | val 0.75708
  Classification -> best τ=0.670 (val F1=0.3338)
  Directional -> Accuracy: 0.4667, MCC: 0.1939, F1: 0.1579

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64357 | val 0.72417
  Epoch 020 - train 0.61904 | val 0.74350
  Epoch 021 - train 0.63338 | val 0.73916
  Classification -> best τ=0.585 (val F1=0.1859)
  Directional -> Accuracy: 0.4706, MCC: -0.0617, F1: 0.4375

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68028 | val 0.90246
  Epoch 020 - train 0.59108 | val 0.89735
  Epoch 027 - train 0.59122 | val 0.96166
  Classification -> best τ=0.615 (val F1=0.4937)
  Directional -> Accuracy: 0.5690, MCC: 0.2157, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68849 | val 0.82472
  Epoch 020 - train 0.49212 | val 1.22692
  Epoch 024 - train 0.48601 | val 1.27122
  Classification -> best τ=0.500 (val F1=0.2787)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64559 | val 0.74863
  Epoch 020 - train 0.62673 | val 0.75010
  Epoch 022 - train 0.67545 | val 0.74040
  Classification -> best τ=0.535 (val F1=0.1557)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69851 | val 0.99559
  Epoch 020 - train 0.64113 | val 1.28045
  Epoch 021 - train 0.61097 | val 1.30282
  Classification -> best τ=0.450 (val F1=0.2356)
  Directional -> Accuracy: 0.5424, MCC: 0.2518, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65099 | val 0.94960
  Epoch 020 - train 0.55245 | val 0.99283
  Epoch 024 - train 0.56815 | val 1.08198
  Classification -> best τ=0.585 (val F1=0.3458)
  Directional -> Accuracy: 0.4773, MCC: -0.0379, F1: 0.4390

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64282 | val 0.79286
  Epoch 020 - train 0.62326 | val 0.90802
  Epoch 021 - train 0.60610 | val 0.91196
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71583 | val 0.72535
  Epoch 020 - train 0.67578 | val 0.72583
  Epoch 025 - train 0.70067 | val 0.71372
  Classification -> best τ=0.520 (val F1=0.2885)
  Directional -> Accuracy: 0.6087, MCC: 0.2004, F1: 0.6786

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65083 | val 0.85751
  Epoch 020 - train 0.60592 | val 0.87796
  Epoch 022 - train 0.54928 | val 0.89268
  Classification -> best τ=0.395 (val F1=0.3804)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67419 | val 0.67190
  Epoch 020 - train 0.65452 | val 0.68473
  Epoch 028 - train 0.61144 | val 0.72220
  Classification -> best τ=0.380 (val F1=0.3177)
  Directional -> Accuracy: 0.5333, MCC: 0.1340, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68485 | val 0.70870
  Epoch 020 - train 0.65258 | val 0.71553
  Epoch 022 - train 0.64327 | val 0.71625
  Classification -> best τ=0.560 (val F1=0.2774)
  Directional -> Accuracy: 0.5122, MCC: 0.0176, F1: 0.4118

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67621 | val 1.01478
  Epoch 020 - train 0.62663 | val 1.05069
  Epoch 021 - train 0.60955 | val 1.08013
  Classification -> best τ=0.505 (val F1=0.4019)
  Directional -> Accuracy: 0.6304, MCC: 0.2659, F1: 0.6222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62396 | val 0.74572
  Epoch 020 - train 0.62811 | val 0.76665
  Epoch 021 - train 0.61248 | val 0.75815
  Classification -> best τ=0.390 (val F1=0.3271)
  Directional -> Accuracy: 0.5942, MCC: 0.1207, F1: 0.7021

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67760 | val 0.68895
  Epoch 020 - train 0.61920 | val 0.70503
  Epoch 021 - train 0.60502 | val 0.70741
  Classification -> best τ=0.465 (val F1=0.2478)
  Directional -> Accuracy: 0.6444, MCC: 0.2960, F1: 0.6190

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68803 | val 0.87911
  Epoch 020 - train 0.64445 | val 0.91841
  Epoch 021 - train 0.64630 | val 0.92455
  Classification -> best τ=0.360 (val F1=0.2344)
  Directional -> Accuracy: 0.5254, MCC: 0.0554, F1: 0.5333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68601 | val 1.12613
  Epoch 020 - train 0.55013 | val 1.56215
  Epoch 023 - train 0.55505 | val 1.47078
  Classification -> best τ=0.215 (val F1=0.2052)
  Directional -> Accuracy: 0.4898, MCC: -0.1325, F1: 0.6154

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63240 | val 0.66759
  Epoch 020 - train 0.57414 | val 0.67126
  Epoch 030 - train 0.51597 | val 0.69576
  Classification -> best τ=0.390 (val F1=0.3156)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74903 | val 0.79426
  Epoch 020 - train 0.65082 | val 0.79336
  Epoch 024 - train 0.57349 | val 0.78745
  Classification -> best τ=0.475 (val F1=0.2467)
  Directional -> Accuracy: 0.5610, MCC: 0.1504, F1: 0.4375

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64700 | val 0.95153
  Epoch 020 - train 0.63521 | val 1.43528
  Epoch 022 - train 0.59859 | val 1.41074
  Classification -> best τ=0.310 (val F1=0.1987)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68691 | val 1.45789
  Epoch 020 - train 0.67543 | val 1.41888
  Epoch 021 - train 0.67040 | val 1.41079
  Classification -> best τ=0.565 (val F1=0.2266)
  Directional -> Accuracy: 0.5102, MCC: 0.0500, F1: 0.6364

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65499 | val 1.06259
  Epoch 020 - train 0.53354 | val 1.69685
  Epoch 021 - train 0.58010 | val 1.72544
  Classification -> best τ=0.515 (val F1=0.5477)
  Directional -> Accuracy: 0.4468, MCC: 0.0178, F1: 0.1875

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64160 | val 1.14927
  Epoch 020 - train 0.61714 | val 1.03811
  Epoch 021 - train 0.62823 | val 1.00560
  Classification -> best τ=0.480 (val F1=0.0551)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68860 | val 0.68948
  Epoch 020 - train 0.67408 | val 0.68810
  Epoch 027 - train 0.67379 | val 0.69110
  Classification -> best τ=0.625 (val F1=0.2345)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66314 | val 1.44685
  Epoch 020 - train 0.63227 | val 1.43859
  Epoch 021 - train 0.58970 | val 1.40877
  Classification -> best τ=0.660 (val F1=0.4567)
  Directional -> Accuracy: 0.6102, MCC: 0.2256, F1: 0.6349

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67217 | val 1.40589
  Epoch 020 - train 0.64456 | val 1.67611
  Epoch 021 - train 0.62307 | val 1.69800
  Classification -> best τ=0.505 (val F1=0.1502)
  Directional -> Accuracy: 0.6071, MCC: 0.2339, F1: 0.7179

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68069 | val 1.28507
  Epoch 020 - train 0.64700 | val 1.50224

[I 2026-02-19 23:24:59,552] Trial 22 finished with value: 0.26179994200866186 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.004063751713726025, 'weight_decay': 0.0001495160664103952, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.4397893156467398, 'early_stopping_min_delta': 0.00011152265007515622}. Best is trial 22 with value: 0.26179994200866186.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26179994200866186
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68161 | val 0.91679
  Epoch 020 - train 0.65243 | val 0.90801
  Epoch 021 - train 0.63455 | val 0.92308
  Classification -> best τ=0.700 (val F1=0.2571)
  Directional -> Accuracy: 0.5385, MCC: -0.0127, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61105 | val 0.76745
  Epoch 020 - train 0.68572 | val 0.79102
  Epoch 021 - train 0.63832 | val 0.79195
  Classification -> best τ=0.460 (val F1=0.1941)
  Directional -> Accuracy: 0.5957, MCC: 0.1860, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.75086 | val 0.72362
  Epoch 020 - train 0.69176 | val 0.69362
  Epoch 022 - train 0.68408 | val 0.69333
  Classification -> best τ=0.555 (val F1=0.2733)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68082 | val 1.08276
  Epoch 020 - train 0.66031 | val 1.07888
  Epoch 021 - train 0.66876 | val 1.11067
  Classification -> best τ=0.405 (val F1=0.2485)
  Directional -> Accuracy: 0.5526, MCC: 0.0724, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65516 | val 0.90783
  Epoch 020 - train 0.59426 | val 0.95911
  Epoch 022 - train 0.64048 | val 0.96544
  Classification -> best τ=0.620 (val F1=0.3719)
  Directional -> Accuracy: 0.5577, MCC: 0.2521, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67117 | val 1.33813
  Epoch 020 - train 0.63408 | val 1.39859
  Epoch 021 - train 0.60179 | val 1.41633
  Classification -> best τ=0.570 (val F1=0.2511)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72691 | val 0.80309
  Epoch 020 - train 0.64789 | val 0.83868
  Epoch 022 - train 0.65160 | val 0.86193
  Classification -> best τ=0.620 (val F1=0.2409)
  Directional -> Accuracy: 0.5714, MCC: -0.0754, F1: 0.0625

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61775 | val 1.19526
  Epoch 020 - train 0.63414 | val 1.29592
  Epoch 021 - train 0.64487 | val 1.31825
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68040 | val 0.68078
  Epoch 020 - train 0.60203 | val 0.91933
  Epoch 028 - train 0.59524 | val 0.97397
  Classification -> best τ=0.470 (val F1=0.3553)
  Directional -> Accuracy: 0.7143, MCC: 0.3814, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66603 | val 1.27041
  Epoch 020 - train 0.63923 | val 1.26542
  Epoch 021 - train 0.65582 | val 1.30948
  Classification -> best τ=0.370 (val F1=0.1808)
  Directional -> Accuracy: 0.4507, MCC: 0.0437, F1: 0.6061

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67482 | val 0.79911
  Epoch 020 - train 0.63407 | val 0.72204
  Epoch 021 - train 0.66967 | val 0.72847
  Classification -> best τ=0.540 (val F1=0.1368)
  Directional -> Accuracy: 0.5294, MCC: 0.0913, F1: 0.6000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70678 | val 0.74777
  Epoch 020 - train 0.65286 | val 0.75858
  Epoch 021 - train 0.68207 | val 0.76315
  Classification -> best τ=0.555 (val F1=0.1663)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66554 | val 1.28965
  Epoch 020 - train 0.63286 | val 1.53591
  Epoch 021 - train 0.63179 | val 1.63409
  Classification -> best τ=0.515 (val F1=0.1320)
  Directional -> Accuracy: 0.5000, MCC: -0.0356, F1: 0.3529

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72566 | val 0.64466
  Epoch 020 - train 0.68893 | val 0.66232
  Epoch 026 - train 0.68061 | val 0.65397
  Classification -> best τ=0.390 (val F1=0.3755)
  Directional -> Accuracy: 0.5323, MCC: 0.0877, F1: 0.6506

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66888 | val 1.22044
  Epoch 020 - train 0.64945 | val 0.96885
  Epoch 022 - train 0.64751 | val 0.98810
  Classification -> best τ=0.605 (val F1=0.2530)
  Directional -> Accuracy: 0.6226, MCC: 0.2678, F1: 0.6552

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66085 | val 0.87487
  Epoch 020 - train 0.62021 | val 0.88524
  Epoch 021 - train 0.65470 | val 0.88959
  Classification -> best τ=0.670 (val F1=0.2354)
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67134 | val 1.03664
  Epoch 020 - train 0.68057 | val 0.91355
  Epoch 021 - train 0.66511 | val 0.91837
  Classification -> best τ=0.670 (val F1=0.2165)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65298 | val 1.38232
  Epoch 020 - train 0.68869 | val 1.47004
  Epoch 021 - train 0.64785 | val 1.47902
  Classification -> best τ=0.480 (val F1=0.1233)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67019 | val 0.88614
  Epoch 020 - train 0.65066 | val 0.85659
  Epoch 021 - train 0.66937 | val 0.86131
  Classification -> best τ=0.525 (val F1=0.2865)
  Directional -> Accuracy: 0.4394, MCC: 0.0822, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67444 | val 0.76234
  Epoch 020 - train 0.62157 | val 0.82904
  Epoch 021 - train 0.61092 | val 0.84256
  Classification -> best τ=0.525 (val F1=0.2602)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66733 | val 0.89244
  Epoch 020 - train 0.66193 | val 0.87927
  Epoch 021 - train 0.63962 | val 0.88563
  Classification -> best τ=0.510 (val F1=0.2233)
  Directional -> Accuracy: 0.5102, MCC: 0.0851, F1: 0.5200

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67848 | val 1.04117
  Epoch 020 - train 0.67785 | val 1.03143
  Epoch 021 - train 0.67938 | val 1.03519
  Classification -> best τ=0.490 (val F1=0.1677)
  Directional -> Accuracy: 0.5672, MCC: 0.1376, F1: 0.6329

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69820 | val 1.00790
  Epoch 020 - train 0.63692 | val 1.50955
  Epoch 021 - train 0.67180 | val 1.50549
  Classification -> best τ=0.580 (val F1=0.2097)
  Directional -> Accuracy: 0.5593, MCC: 0.0178, F1: 0.6905

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68890 | val 0.71401
  Epoch 020 - train 0.65954 | val 0.71250
  Epoch 026 - train 0.63689 | val 0.73901
  Classification -> best τ=0.585 (val F1=0.1890)
  Directional -> Accuracy: 0.4179, MCC: -0.2142, F1: 0.2041

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65524 | val 0.85690
  Epoch 020 - train 0.63727 | val 0.89880
  Epoch 022 - train 0.67148 | val 0.90898
  Classification -> best τ=0.565 (val F1=0.4402)
  Directional -> Accuracy: 0.5789, MCC: 0.2579, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68687 | val 1.00851
  Epoch 020 - train 0.65037 | val 0.99866
  Epoch 021 - train 0.67095 | val 1.00025
  Classification -> best τ=0.520 (val F1=0.1588)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71722 | val 1.41320
  Epoch 020 - train 0.69471 | val 1.62325
  Epoch 021 - train 0.68249 | val 1.61026
  Classification -> best τ=0.400 (val F1=0.0300)
  Directional -> Accuracy: 0.5227, MCC: -0.1091, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68692 | val 0.68554
  Epoch 020 - train 0.65224 | val 0.75932
  Epoch 026 - train 0.63743 | val 0.77738
  Classification -> best τ=0.365 (val F1=0.3358)
  Directional -> Accuracy: 0.5345, MCC: 0.2275, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66822 | val 0.68415
  Epoch 020 - train 0.65918 | val 0.67527
  Epoch 029 - train 0.61162 | val 0.67203
  Classification -> best τ=0.605 (val F1=0.3344)
  Directional -> Accuracy: 0.5349, MCC: 0.0786, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65853 | val 0.80444
  Epoch 020 - train 0.72576 | val 0.81196
  Epoch 021 - train 0.67779 | val 0.81030
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72301 | val 0.68742
  Epoch 020 - train 0.69191 | val 0.72543
  Epoch 029 - train 0.67135 | val 0.72947
  Classification -> best τ=0.450 (val F1=0.2390)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68961 | val 0.78434
  Epoch 020 - train 0.64190 | val 0.78216
  Epoch 022 - train 0.62548 | val 0.78546
  Classification -> best τ=0.555 (val F1=0.2325)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70208 | val 1.02270
  Epoch 020 - train 0.67919 | val 1.05795
  Epoch 022 - train 0.65614 | val 1.06496
  Classification -> best τ=0.435 (val F1=0.3259)
  Directional -> Accuracy: 0.5541, MCC: 0.1516, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66399 | val 0.74708
  Epoch 020 - train 0.65803 | val 0.81601
  Epoch 021 - train 0.67219 | val 0.80910
  Classification -> best τ=0.450 (val F1=0.1241)
  Directional -> Accuracy: 0.5385, MCC: 0.1140, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70308 | val 1.29603
  Epoch 020 - train 0.62956 | val 1.54445
  Epoch 021 - train 0.67477 | val 1.53724
  Classification -> best τ=0.590 (val F1=0.2362)
  Directional -> Accuracy: 0.5333, MCC: 0.0782, F1: 0.5532

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67573 | val 0.85357
  Epoch 020 - train 0.65154 | val 0.95553
  Epoch 021 - train 0.65313 | val 0.95718
  Classification -> best τ=0.435 (val F1=0.3342)
  Directional -> Accuracy: 0.6176, MCC: 0.2424, F1: 0.6389

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70126 | val 0.85698
  Epoch 020 - train 0.66132 | val 0.84398
  Epoch 021 - train 0.65288 | val 0.84690
  Classification -> best τ=0.535 (val F1=0.2033)
  Directional -> Accuracy: 0.5455, MCC: 0.1179, F1: 0.3333

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70931 | val 0.87261
  Epoch 020 - train 0.63239 | val 0.90268
  Epoch 022 - train 0.62998 | val 0.89707
  Classification -> best τ=0.430 (val F1=0.1089)
  Directional -> Accuracy: 0.4483, MCC: -0.0992, F1: 0.4483

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67630 | val 1.84077
  Epoch 020 - train 0.57594 | val 2.28813
  Epoch 021 - train 0.62621 | val 2.30255
  Classification -> best τ=0.535 (val F1=0.2835)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70766 | val 0.65714
  Epoch 020 - train 0.57151 | val 0.71007
  Epoch 029 - train 0.58686 | val 0.74241
  Classification -> best τ=0.400 (val F1=0.4689)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64902 | val 0.95344
  Epoch 020 - train 0.59631 | val 1.12066
  Epoch 021 - train 0.59957 | val 1.12860
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66668 | val 1.21918
  Epoch 020 - train 0.62900 | val 1.39283
  Epoch 021 - train 0.62319 | val 1.40660
  Classification -> best τ=0.365 (val F1=0.2439)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66212 | val 0.86695
  Epoch 020 - train 0.64896 | val 0.87281
  Epoch 022 - train 0.65107 | val 0.85704
  Classification -> best τ=0.490 (val F1=0.3119)
  Directional -> Accuracy: 0.5417, MCC: 0.1026, F1: 0.6452

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65273 | val 1.28539
  Epoch 020 - train 0.61267 | val 1.36775
  Epoch 021 - train 0.59795 | val 1.35874
  Classification -> best τ=0.560 (val F1=0.1000)
  Directional -> Accuracy: 0.4444, MCC: -0.0349, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65074 | val 1.56316
  Epoch 020 - train 0.61395 | val 1.42639
  Epoch 021 - train 0.63239 | val 1.46665
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66537 | val 0.84885
  Epoch 020 - train 0.70088 | val 0.87779
  Epoch 021 - train 0.66974 | val 0.88857
  Classification -> best τ=0.495 (val F1=0.2023)
  Directional -> Accuracy: 0.7368, MCC: 0.4851, F1: 0.7368

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67445 | val 1.75199
  Epoch 020 - train 0.59324 | val 1.88987
  Epoch 021 - train 0.60914 | val 1.87279
  Classification -> best τ=0.575 (val F1=0.3778)
  Directional -> Accuracy: 0.4828, MCC: -0.0333, F1: 0.4828

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69132 | val 0.82973
  Epoch 020 - train 0.68084 | val 0.82333
  Epoch 021 - train 0.65513 | val 0.82648
  Classification -> best τ=0.515 (val F1=0.1600)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66451 | val 0.90720
  Epoch 020 - train 0.64300 | val 0.92423
  Epoch 027 - train 0.63528 | val 1.01488

[I 2026-02-19 23:27:56,422] Trial 23 finished with value: 0.22242306095540368 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0014629962593481045, 'weight_decay': 0.00013965680449294372, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.1414794923813862, 'early_stopping_min_delta': 1.915297657868834e-05}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 030 - train 0.63933 | val 0.68108
  Classification -> best τ=0.420 (val F1=0.3115)
  Directional -> Accuracy: 0.5968, MCC: 0.2334, F1: 0.6667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22242306095540368
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65925 | val 0.77295
  Epoch 020 - train 0.63553 | val 0.76200
  Epoch 025 - train 0.61879 | val 0.79799
  Classification -> best τ=0.860 (val F1=0.1903)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66830 | val 0.71700
  Epoch 020 - train 0.67545 | val 0.73440
  Epoch 028 - train 0.62145 | val 0.72649
  Classification -> best τ=0.415 (val F1=0.1899)
  Directional -> Accuracy: 0.6250, MCC: 0.2305, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65825 | val 0.82267
  Epoch 020 - train 0.64638 | val 0.86260
  Epoch 021 - train 0.67908 | val 0.85696
  Classification -> best τ=0.525 (val F1=0.3331)
  Directional -> Accuracy: 0.4898, MCC: -0.0323, F1: 0.5455

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68088 | val 0.69745
  Epoch 020 - train 0.63745 | val 0.70716
  Epoch 030 - train 0.63191 | val 0.69542
  Classification -> best τ=0.440 (val F1=0.1581)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68901 | val 1.27772
  Epoch 020 - train 0.59830 | val 2.27847
  Epoch 021 - train 0.62199 | val 2.28694
  Classification -> best τ=0.660 (val F1=0.4274)
  Directional -> Accuracy: 0.4906, MCC: 0.0464, F1: 0.1818

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59198 | val 0.82074
  Epoch 020 - train 0.59277 | val 0.73350
  Epoch 027 - train 0.53383 | val 0.70847
  Classification -> best τ=0.610 (val F1=0.2032)
  Directional -> Accuracy: 0.4634, MCC: -0.1383, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70230 | val 0.84178
  Epoch 020 - train 0.67625 | val 1.16282
  Epoch 027 - train 0.68470 | val 1.09931
  Classification -> best τ=0.435 (val F1=0.1805)
  Directional -> Accuracy: 0.4507, MCC: 0.0582, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63970 | val 0.68560
  Epoch 020 - train 0.60142 | val 1.15138
  Epoch 030 - train 0.53752 | val 1.24913
  Classification -> best τ=0.285 (val F1=0.3244)
  Directional -> Accuracy: 0.5532, MCC: -0.0045, F1: 0.2759

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67841 | val 0.69516
  Epoch 020 - train 0.60531 | val 0.81290
  Epoch 024 - train 0.57491 | val 0.79666
  Classification -> best τ=0.370 (val F1=0.1928)
  Directional -> Accuracy: 0.4884, MCC: 0.1074, F1: 0.5600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63426 | val 1.16603
  Epoch 020 - train 0.57047 | val 1.12202
  Epoch 021 - train 0.56195 | val 1.12668
  Classification -> best τ=0.360 (val F1=0.1838)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65910 | val 0.93330
  Epoch 020 - train 0.65172 | val 0.77758
  Epoch 025 - train 0.64901 | val 0.83262
  Classification -> best τ=0.450 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67352 | val 0.72848
  Epoch 020 - train 0.64116 | val 0.85163
  Epoch 022 - train 0.66289 | val 0.84244
  Classification -> best τ=0.520 (val F1=0.1919)
  Directional -> Accuracy: 0.4000, MCC: -0.2004, F1: 0.3793

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62017 | val 0.64927
  Epoch 020 - train 0.59676 | val 0.74119
  Epoch 029 - train 0.49881 | val 0.83700
  Classification -> best τ=0.620 (val F1=0.3331)
  Directional -> Accuracy: 0.4444, MCC: -0.1273, F1: 0.3590

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67567 | val 0.92144
  Epoch 020 - train 0.64513 | val 0.93112
  Epoch 022 - train 0.65073 | val 0.94456
  Classification -> best τ=0.740 (val F1=0.4300)
  Directional -> Accuracy: 0.5238, MCC: 0.0449, F1: 0.4231

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68268 | val 0.86790
  Epoch 020 - train 0.61337 | val 1.29307
  Epoch 021 - train 0.61659 | val 1.31999
  Classification -> best τ=0.580 (val F1=0.2292)
  Directional -> Accuracy: 0.4630, MCC: -0.0676, F1: 0.5085

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64762 | val 1.04174
  Epoch 020 - train 0.61443 | val 1.16626
  Epoch 021 - train 0.59445 | val 1.20004
  Classification -> best τ=0.425 (val F1=0.3091)
  Directional -> Accuracy: 0.6250, MCC: 0.2524, F1: 0.7216

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68692 | val 1.42307
  Epoch 020 - train 0.61038 | val 1.75075
  Epoch 021 - train 0.60282 | val 1.72387
  Classification -> best τ=0.635 (val F1=0.1657)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66851 | val 0.80438
  Epoch 020 - train 0.63944 | val 0.84893
  Epoch 021 - train 0.64505 | val 0.83153
  Classification -> best τ=0.650 (val F1=0.1083)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68645 | val 0.69348
  Epoch 020 - train 0.63666 | val 0.73731
  Epoch 026 - train 0.62229 | val 0.89554
  Classification -> best τ=0.305 (val F1=0.2542)
  Directional -> Accuracy: 0.4776, MCC: 0.0801, F1: 0.3137

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66798 | val 0.67791
  Epoch 020 - train 0.61823 | val 0.66404
  Epoch 028 - train 0.57715 | val 0.72618
  Classification -> best τ=0.445 (val F1=0.3190)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59768 | val 0.87684
  Epoch 020 - train 0.56723 | val 0.91994
  Epoch 021 - train 0.58570 | val 0.92562
  Classification -> best τ=0.585 (val F1=0.1129)
  Directional -> Accuracy: 0.5200, MCC: 0.1529, F1: 0.4783

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68850 | val 0.71886
  Epoch 020 - train 0.66142 | val 0.74812
  Epoch 025 - train 0.61072 | val 0.73128
  Classification -> best τ=0.490 (val F1=0.2798)
  Directional -> Accuracy: 0.4118, MCC: -0.1765, F1: 0.4118

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69742 | val 0.79527
  Epoch 020 - train 0.62409 | val 1.06051
  Epoch 021 - train 0.62910 | val 1.12978
  Classification -> best τ=0.535 (val F1=0.2763)
  Directional -> Accuracy: 0.4667, MCC: 0.0710, F1: 0.2727

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68326 | val 0.71551
  Epoch 020 - train 0.60333 | val 0.76879
  Epoch 021 - train 0.63848 | val 0.76465
  Classification -> best τ=0.495 (val F1=0.2041)
  Directional -> Accuracy: 0.4853, MCC: -0.0312, F1: 0.4615

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64124 | val 0.74520
  Epoch 020 - train 0.60531 | val 1.06460
  Epoch 023 - train 0.59435 | val 1.12851
  Classification -> best τ=0.515 (val F1=0.4491)
  Directional -> Accuracy: 0.5690, MCC: 0.1859, F1: 0.5098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74348 | val 0.70407
  Epoch 020 - train 0.57067 | val 1.14384
  Epoch 024 - train 0.55464 | val 1.25885
  Classification -> best τ=0.540 (val F1=0.3862)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71337 | val 0.83168
  Epoch 020 - train 0.69586 | val 0.73135
  Epoch 022 - train 0.65223 | val 0.73454
  Classification -> best τ=0.535 (val F1=0.1273)
  Directional -> Accuracy: 0.4667, MCC: 0.0200, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66779 | val 0.84301
  Epoch 020 - train 0.64772 | val 1.06861
  Epoch 021 - train 0.63960 | val 1.06520
  Classification -> best τ=0.455 (val F1=0.2145)
  Directional -> Accuracy: 0.5085, MCC: 0.1857, F1: 0.2564

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62236 | val 1.25147
  Epoch 020 - train 0.62791 | val 1.19440
  Epoch 022 - train 0.62645 | val 1.19578
  Classification -> best τ=0.475 (val F1=0.2820)
  Directional -> Accuracy: 0.5909, MCC: 0.1923, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64988 | val 0.77627
  Epoch 020 - train 0.64761 | val 0.77378
  Epoch 022 - train 0.65930 | val 0.76963
  Classification -> best τ=0.585 (val F1=0.3031)
  Directional -> Accuracy: 0.5217, MCC: 0.1491, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.74384 | val 0.67864
  Epoch 020 - train 0.68068 | val 0.75388
  Epoch 030 - train 0.69442 | val 0.79710
  Classification -> best τ=0.695 (val F1=0.2562)
  Directional -> Accuracy: 0.3913, MCC: -0.2408, F1: 0.0667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61804 | val 0.80068
  Epoch 020 - train 0.60432 | val 0.89877
  Epoch 021 - train 0.57666 | val 0.89893
  Classification -> best τ=0.460 (val F1=0.2946)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66446 | val 0.65849
  Epoch 020 - train 0.61505 | val 0.86422
  Epoch 030 - train 0.59493 | val 0.98561
  Classification -> best τ=0.375 (val F1=0.3177)
  Directional -> Accuracy: 0.5333, MCC: 0.1340, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.72013 | val 0.70901
  Epoch 020 - train 0.67140 | val 0.70775
  Epoch 023 - train 0.61856 | val 0.70526
  Classification -> best τ=0.600 (val F1=0.2774)
  Directional -> Accuracy: 0.5610, MCC: 0.1482, F1: 0.3077

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65279 | val 1.04961
  Epoch 020 - train 0.57807 | val 1.69624
  Epoch 022 - train 0.60250 | val 1.71233
  Classification -> best τ=0.380 (val F1=0.1954)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67089 | val 0.73421
  Epoch 020 - train 0.62253 | val 0.78426
  Epoch 022 - train 0.63190 | val 0.75694
  Classification -> best τ=0.395 (val F1=0.3348)
  Directional -> Accuracy: 0.5652, MCC: 0.2591, F1: 0.4643

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63263 | val 0.68141
  Epoch 020 - train 0.65541 | val 0.70981
  Epoch 025 - train 0.62520 | val 0.74960
  Classification -> best τ=0.510 (val F1=0.2727)
  Directional -> Accuracy: 0.6444, MCC: 0.4198, F1: 0.4667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63703 | val 0.87068
  Epoch 020 - train 0.61019 | val 0.90622
  Epoch 021 - train 0.62376 | val 0.92598
  Classification -> best τ=0.465 (val F1=0.2118)
  Directional -> Accuracy: 0.4915, MCC: -0.0196, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62338 | val 1.66810
  Epoch 020 - train 0.54180 | val 2.06136
  Epoch 021 - train 0.53987 | val 2.10012
  Classification -> best τ=0.490 (val F1=0.3515)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71708 | val 0.62524
  Epoch 020 - train 0.58075 | val 0.70270
  Epoch 026 - train 0.57806 | val 0.71819
  Classification -> best τ=0.300 (val F1=0.4769)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.75036 | val 0.74162
  Epoch 020 - train 0.62595 | val 0.78472
  Epoch 021 - train 0.53567 | val 0.81048
  Classification -> best τ=0.485 (val F1=0.2254)
  Directional -> Accuracy: 0.5610, MCC: 0.1482, F1: 0.6786

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63399 | val 1.04734
  Epoch 020 - train 0.61504 | val 1.50072
  Epoch 021 - train 0.63268 | val 1.51280
  Classification -> best τ=0.465 (val F1=0.1770)
  Directional -> Accuracy: 0.5325, MCC: 0.1654, F1: 0.6842

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66881 | val 0.76370
  Epoch 020 - train 0.63568 | val 0.92683
  Epoch 021 - train 0.63175 | val 0.92230
  Classification -> best τ=0.545 (val F1=0.2962)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62561 | val 1.15504
  Epoch 020 - train 0.55619 | val 1.60649
  Epoch 021 - train 0.53655 | val 1.62975
  Classification -> best τ=0.430 (val F1=0.2582)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67695 | val 0.78560
  Epoch 020 - train 0.59617 | val 0.78299
  Epoch 021 - train 0.57642 | val 0.79191
  Classification -> best τ=0.655 (val F1=0.1425)
  Directional -> Accuracy: 0.4762, MCC: 0.1470, F1: 0.5417

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70545 | val 0.71280
  Epoch 020 - train 0.68538 | val 0.72241
  Epoch 025 - train 0.66863 | val 0.69509
  Classification -> best τ=0.565 (val F1=0.2563)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63168 | val 1.41912
  Epoch 020 - train 0.62505 | val 1.75572
  Epoch 021 - train 0.62249 | val 1.75490
  Classification -> best τ=0.670 (val F1=0.3591)
  Directional -> Accuracy: 0.5763, MCC: 0.2559, F1: 0.6914

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65858 | val 1.08117
  Epoch 020 - train 0.64721 | val 1.31931
  Epoch 021 - train 0.65323 | val 1.33710
  Classification -> best τ=0.340 (val F1=0.1728)
  Directional -> Accuracy: 0.6250, MCC: 0.2607, F1: 0.7200

[87/88] Processing WMT...


[I 2026-02-19 23:30:02,059] Trial 24 finished with value: 0.2601105774078373 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0042914340117465545, 'weight_decay': 0.0004934155440512424, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.428912871785734, 'early_stopping_min_delta': 0.002548664611682464}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 023 - train 0.62669 | val 0.78228
  Classification -> best τ=0.460 (val F1=0.2500)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.3922

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2601105774078373
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67972 | val 0.85289
  Epoch 020 - train 0.59494 | val 1.38269
  Epoch 027 - train 0.56047 | val 1.70741
  Classification -> best τ=0.590 (val F1=0.2416)
  Directional -> Accuracy: 0.5949, MCC: 0.1956, F1: 0.5789

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61246 | val 1.81338
  Epoch 020 - train 0.54150 | val 1.43918
  Epoch 024 - train 0.54622 | val 1.39981
  Classification -> best τ=0.455 (val F1=0.2219)
  Directional -> Accuracy: 0.6250, MCC: 0.2492, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63806 | val 0.90267
  Epoch 020 - train 0.59624 | val 0.99526
  Epoch 023 - train 0.59963 | val 1.06149
  Classification -> best τ=0.495 (val F1=0.3789)
  Directional -> Accuracy: 0.5306, MCC: 0.1140, F1: 0.3784

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65040 | val 0.66935
  Epoch 020 - train 0.60112 | val 0.82347
  Epoch 030 - train 0.56342 | val 1.02165
  Classification -> best τ=0.665 (val F1=0.3203)
  Directional -> Accuracy: 0.4935, MCC: -0.0649, F1: 0.6061

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58493 | val 1.88715
  Epoch 020 - train 0.54242 | val 2.74085
  Epoch 023 - train 0.52911 | val 3.10772
  Classification -> best τ=0.565 (val F1=0.3376)
  Directional -> Accuracy: 0.5849, MCC: 0.2403, F1: 0.4500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60787 | val 0.73633
  Epoch 020 - train 0.52367 | val 0.68671
  Epoch 030 - train 0.47204 | val 0.78912
  Classification -> best τ=0.630 (val F1=0.2949)
  Directional -> Accuracy: 0.4634, MCC: -0.0304, F1: 0.5926

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65966 | val 0.81190
  Epoch 020 - train 0.63875 | val 0.94328
  Epoch 021 - train 0.61923 | val 0.96087
  Classification -> best τ=0.460 (val F1=0.2795)
  Directional -> Accuracy: 0.5352, MCC: 0.1618, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64701 | val 1.02568
  Epoch 020 - train 0.52381 | val 1.33474
  Epoch 026 - train 0.49917 | val 1.52893
  Classification -> best τ=0.445 (val F1=0.4196)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60003 | val 1.09433
  Epoch 020 - train 0.52096 | val 1.17245
  Epoch 023 - train 0.58363 | val 1.18327
  Classification -> best τ=0.525 (val F1=0.3015)
  Directional -> Accuracy: 0.6047, MCC: 0.2647, F1: 0.6047

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62983 | val 0.84922
  Epoch 020 - train 0.56764 | val 1.35952
  Epoch 021 - train 0.55482 | val 1.40823
  Classification -> best τ=0.500 (val F1=0.2223)
  Directional -> Accuracy: 0.4583, MCC: 0.0884, F1: 0.6061

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61489 | val 0.72577
  Epoch 020 - train 0.58587 | val 0.67498
  Epoch 030 - train 0.56015 | val 0.67849
  Classification -> best τ=0.590 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67062 | val 0.72141
  Epoch 020 - train 0.61717 | val 1.39972
  Epoch 021 - train 0.58242 | val 1.32955
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59171 | val 1.75881
  Epoch 020 - train 0.52272 | val 2.68479
  Epoch 021 - train 0.54658 | val 2.73678
  Classification -> best τ=0.530 (val F1=0.0364)
  Directional -> Accuracy: 0.5556, MCC: 0.0901, F1: 0.2857

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66987 | val 0.60358
  Epoch 020 - train 0.60602 | val 0.67993
  Epoch 024 - train 0.58464 | val 0.72571
  Classification -> best τ=0.525 (val F1=0.3844)
  Directional -> Accuracy: 0.4921, MCC: -0.0100, F1: 0.5789

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62416 | val 2.85719
  Epoch 020 - train 0.57068 | val 2.70741
  Epoch 021 - train 0.54701 | val 2.57488
  Classification -> best τ=0.520 (val F1=0.1997)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63507 | val 1.08839
  Epoch 020 - train 0.55759 | val 1.46233
  Epoch 022 - train 0.57433 | val 1.53233
  Classification -> best τ=0.580 (val F1=0.2909)
  Directional -> Accuracy: 0.5694, MCC: 0.1496, F1: 0.5634

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61124 | val 1.33516
  Epoch 020 - train 0.58946 | val 1.46706
  Epoch 021 - train 0.59154 | val 1.45087
  Classification -> best τ=0.480 (val F1=0.0525)
  Directional -> Accuracy: 0.6230, MCC: 0.1272, F1: 0.7579

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68145 | val 1.11820
  Epoch 020 - train 0.63199 | val 1.08070
  Epoch 021 - train 0.62676 | val 1.06197
  Classification -> best τ=0.460 (val F1=0.0129)
  Directional -> Accuracy: 0.5641, MCC: 0.0155, F1: 0.6852

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63217 | val 0.72009
  Epoch 020 - train 0.61307 | val 0.80943
  Epoch 022 - train 0.61773 | val 0.80824
  Classification -> best τ=0.440 (val F1=0.2357)
  Directional -> Accuracy: 0.5373, MCC: 0.1559, F1: 0.4746

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58937 | val 0.70889
  Epoch 020 - train 0.56344 | val 0.73207
  Epoch 022 - train 0.57156 | val 0.76502
  Classification -> best τ=0.505 (val F1=0.1619)
  Directional -> Accuracy: 0.5195, MCC: 0.0760, F1: 0.4478

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63903 | val 1.00775
  Epoch 020 - train 0.50289 | val 1.96072
  Epoch 022 - train 0.49930 | val 2.01803
  Classification -> best τ=0.495 (val F1=0.2229)
  Directional -> Accuracy: 0.6400, MCC: 0.1492, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68949 | val 0.69698
  Epoch 020 - train 0.62639 | val 0.76166
  Epoch 027 - train 0.60653 | val 0.75495
  Classification -> best τ=0.515 (val F1=0.3651)
  Directional -> Accuracy: 0.4412, MCC: -0.1176, F1: 0.4412

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71779 | val 0.82078
  Epoch 020 - train 0.60250 | val 0.83018
  Epoch 021 - train 0.61759 | val 0.84047
  Classification -> best τ=0.540 (val F1=0.1307)
  Directional -> Accuracy: 0.5333, MCC: 0.1393, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63928 | val 0.82850
  Epoch 020 - train 0.55180 | val 0.86030
  Epoch 021 - train 0.55890 | val 0.90093
  Classification -> best τ=0.465 (val F1=0.1650)
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62614 | val 0.70154
  Epoch 020 - train 0.55337 | val 0.76090
  Epoch 025 - train 0.54995 | val 0.79759
  Classification -> best τ=0.515 (val F1=0.3734)
  Directional -> Accuracy: 0.5862, MCC: 0.1942, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58580 | val 0.90246
  Epoch 020 - train 0.57691 | val 1.44526
  Epoch 027 - train 0.51722 | val 1.88295
  Classification -> best τ=0.395 (val F1=0.3056)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70176 | val 1.36730
  Epoch 020 - train 0.61773 | val 1.73877
  Epoch 021 - train 0.58926 | val 1.76211
  Classification -> best τ=0.510 (val F1=0.1195)
  Directional -> Accuracy: 0.5778, MCC: 0.1633, F1: 0.6122

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63846 | val 1.08626
  Epoch 020 - train 0.59606 | val 1.35783
  Epoch 021 - train 0.60245 | val 1.35596
  Classification -> best τ=0.480 (val F1=0.1985)
  Directional -> Accuracy: 0.5593, MCC: 0.2248, F1: 0.4348

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62769 | val 0.89715
  Epoch 020 - train 0.60174 | val 1.49288
  Epoch 023 - train 0.56424 | val 1.55503
  Classification -> best τ=0.485 (val F1=0.3237)
  Directional -> Accuracy: 0.5909, MCC: 0.1775, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64723 | val 0.79468
  Epoch 020 - train 0.55738 | val 0.97605
  Epoch 026 - train 0.51445 | val 1.00751
  Classification -> best τ=0.540 (val F1=0.3304)
  Directional -> Accuracy: 0.6739, MCC: 0.3482, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67812 | val 0.79690
  Epoch 020 - train 0.67196 | val 0.85709
  Epoch 025 - train 0.60066 | val 0.89812
  Classification -> best τ=0.380 (val F1=0.2265)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66975 | val 0.99773
  Epoch 020 - train 0.55585 | val 1.26428
  Epoch 024 - train 0.55618 | val 1.24881
  Classification -> best τ=0.435 (val F1=0.2741)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64484 | val 0.83841
  Epoch 020 - train 0.57149 | val 1.20163
  Epoch 023 - train 0.55087 | val 1.23089
  Classification -> best τ=0.460 (val F1=0.3135)
  Directional -> Accuracy: 0.5733, MCC: 0.1673, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65427 | val 0.70164
  Epoch 020 - train 0.60757 | val 0.73482
  Epoch 028 - train 0.56722 | val 0.72836
  Classification -> best τ=0.595 (val F1=0.3477)
  Directional -> Accuracy: 0.4634, MCC: -0.0701, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66275 | val 1.14549
  Epoch 020 - train 0.57507 | val 1.30895
  Epoch 021 - train 0.54486 | val 1.30386
  Classification -> best τ=0.495 (val F1=0.2081)
  Directional -> Accuracy: 0.6304, MCC: 0.2756, F1: 0.6383

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66048 | val 0.67882
  Epoch 020 - train 0.56136 | val 0.72223
  Epoch 024 - train 0.57410 | val 0.74620
  Classification -> best τ=0.235 (val F1=0.3933)
  Directional -> Accuracy: 0.6087, MCC: 0.2616, F1: 0.5970

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63400 | val 0.83886
  Epoch 020 - train 0.57612 | val 0.98268
  Epoch 024 - train 0.56632 | val 1.03204
  Classification -> best τ=0.495 (val F1=0.2980)
  Directional -> Accuracy: 0.4889, MCC: -0.0134, F1: 0.3429

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64954 | val 0.71653
  Epoch 020 - train 0.57928 | val 0.69257
  Epoch 021 - train 0.56261 | val 0.69134
  Classification -> best τ=0.480 (val F1=0.1632)
  Directional -> Accuracy: 0.5085, MCC: 0.0161, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62366 | val 3.49566
  Epoch 020 - train 0.54259 | val 3.67448
  Epoch 021 - train 0.59607 | val 3.58230
  Classification -> best τ=0.525 (val F1=0.1539)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61945 | val 0.80093
  Epoch 020 - train 0.52142 | val 1.25125
  Epoch 028 - train 0.53974 | val 1.32074
  Classification -> best τ=0.340 (val F1=0.3420)
  Directional -> Accuracy: 0.4524, MCC: 0.0766, F1: 0.4889

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66357 | val 0.74352
  Epoch 020 - train 0.58161 | val 0.76788
  Epoch 021 - train 0.60163 | val 0.77314
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63193 | val 1.39350
  Epoch 020 - train 0.55084 | val 2.38444
  Epoch 023 - train 0.58248 | val 2.40340
  Classification -> best τ=0.445 (val F1=0.3272)
  Directional -> Accuracy: 0.5325, MCC: 0.1201, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67021 | val 0.88134
  Epoch 020 - train 0.62100 | val 0.88750
  Epoch 021 - train 0.62024 | val 0.88658
  Classification -> best τ=0.520 (val F1=0.1664)
  Directional -> Accuracy: 0.5510, MCC: 0.1013, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56694 | val 1.05651
  Epoch 020 - train 0.52061 | val 1.31778
  Epoch 021 - train 0.58126 | val 1.30504
  Classification -> best τ=0.525 (val F1=0.5477)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65040 | val 1.04680
  Epoch 020 - train 0.59834 | val 0.76737
  Epoch 021 - train 0.62453 | val 0.75698
  Classification -> best τ=0.530 (val F1=0.1425)
  Directional -> Accuracy: 0.5952, MCC: 0.0181, F1: 0.2609

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67046 | val 0.69926
  Epoch 020 - train 0.62342 | val 0.72823
  Epoch 023 - train 0.60445 | val 0.73245
  Classification -> best τ=0.570 (val F1=0.1962)
  Directional -> Accuracy: 0.4655, MCC: 0.1194, F1: 0.0606

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62638 | val 0.90738
  Epoch 020 - train 0.61751 | val 1.10420
  Epoch 021 - train 0.58717 | val 1.12973
  Classification -> best τ=0.525 (val F1=0.4144)
  Directional -> Accuracy: 0.5424, MCC: 0.0833, F1: 0.5091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63752 | val 2.19265
  Epoch 020 - train 0.59469 | val 2.21975
  Epoch 021 - train 0.59334 | val 2.13902
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...


[I 2026-02-19 23:31:15,439] Trial 25 finished with value: 0.24072200819788264 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0019326613004677108, 'weight_decay': 0.0006288626736132063, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.4664388707359526, 'early_stopping_min_delta': 0.0022482520192663082}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 024 - train 0.57781 | val 0.78219
  Classification -> best τ=0.490 (val F1=0.2850)
  Directional -> Accuracy: 0.5397, MCC: 0.0853, F1: 0.5538

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24072200819788264
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68191 | val 1.27281
  Epoch 020 - train 0.62793 | val 1.39558
  Epoch 024 - train 0.62481 | val 2.19376
  Classification -> best τ=0.680 (val F1=0.1997)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66216 | val 0.70044
  Epoch 020 - train 0.60735 | val 0.72577
  Epoch 021 - train 0.57656 | val 0.73933
  Classification -> best τ=0.500 (val F1=0.2905)
  Directional -> Accuracy: 0.5957, MCC: 0.1623, F1: 0.7077

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.74808 | val 0.70953
  Epoch 020 - train 0.65525 | val 1.46550
  Epoch 021 - train 0.62391 | val 1.08287
  Classification -> best τ=0.425 (val F1=0.3972)
  Directional -> Accuracy: 0.5208, MCC: -0.0648, F1: 0.6761

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69261 | val 1.05582
  Epoch 020 - train 0.65297 | val 1.17680
  Epoch 021 - train 0.61756 | val 1.21670
  Classification -> best τ=0.390 (val F1=0.0586)
  Directional -> Accuracy: 0.5526, MCC: 0.0960, F1: 0.5952

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70007 | val 1.12032
  Epoch 020 - train 0.63897 | val 1.30844
  Epoch 025 - train 0.60893 | val 2.32555
  Classification -> best τ=0.580 (val F1=0.4747)
  Directional -> Accuracy: 0.6731, MCC: 0.3821, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63423 | val 2.19739
  Epoch 020 - train 0.49321 | val 2.09751
  Epoch 025 - train 0.53533 | val 1.42041
  Classification -> best τ=0.680 (val F1=0.2494)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67037 | val 0.95143
  Epoch 020 - train 0.61914 | val 1.31699
  Epoch 021 - train 0.61465 | val 1.48383
  Classification -> best τ=0.495 (val F1=0.2161)
  Directional -> Accuracy: 0.4857, MCC: 0.0369, F1: 0.5135

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64084 | val 1.56897
  Epoch 020 - train 0.54944 | val 2.68366
  Epoch 022 - train 0.51894 | val 3.47351
  Classification -> best τ=0.665 (val F1=0.0945)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67777 | val 0.77342
  Epoch 020 - train 0.56097 | val 0.67720
  Epoch 030 - train 0.56274 | val 1.19081
  Classification -> best τ=0.595 (val F1=0.4315)
  Directional -> Accuracy: 0.5714, MCC: 0.0465, F1: 0.3571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67543 | val 1.07359
  Epoch 020 - train 0.58230 | val 2.16178
  Epoch 021 - train 0.57478 | val 1.69765
  Classification -> best τ=0.485 (val F1=0.0850)
  Directional -> Accuracy: 0.4085, MCC: -0.1544, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63822 | val 1.02203
  Epoch 020 - train 0.61793 | val 0.91437
  Epoch 026 - train 0.55737 | val 0.77545
  Classification -> best τ=0.595 (val F1=0.3244)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70363 | val 0.81114
  Epoch 020 - train 0.65101 | val 0.89027
  Epoch 022 - train 0.66537 | val 1.02396
  Classification -> best τ=0.615 (val F1=0.2201)
  Directional -> Accuracy: 0.5254, MCC: 0.0757, F1: 0.3333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56961 | val 1.50887
  Epoch 020 - train 0.59636 | val 1.86365
  Epoch 021 - train 0.53674 | val 2.31318
  Classification -> best τ=0.385 (val F1=0.2477)
  Directional -> Accuracy: 0.4773, MCC: 0.0103, F1: 0.5818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71733 | val 0.60984
  Epoch 020 - train 0.66726 | val 0.72583
  Epoch 030 - train 0.69197 | val 0.77393
  Classification -> best τ=0.190 (val F1=0.3076)
  Directional -> Accuracy: 0.4839, MCC: -0.0752, F1: 0.6444

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65526 | val 1.24505
  Epoch 020 - train 0.61983 | val 1.30077
  Epoch 021 - train 0.57186 | val 1.00620
  Classification -> best τ=0.660 (val F1=0.2193)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62859 | val 0.84640
  Epoch 020 - train 0.56683 | val 1.50507
  Epoch 026 - train 0.51828 | val 2.33307
  Classification -> best τ=0.795 (val F1=0.2819)
  Directional -> Accuracy: 0.5352, MCC: 0.0802, F1: 0.5217

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68921 | val 0.93844
  Epoch 020 - train 0.66921 | val 0.81125
  Epoch 021 - train 0.67230 | val 0.83321
  Classification -> best τ=0.480 (val F1=0.2389)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68070 | val 1.57344
  Epoch 020 - train 0.67317 | val 2.12661
  Epoch 021 - train 0.61379 | val 1.98109
  Classification -> best τ=0.330 (val F1=0.1685)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67709 | val 0.76370
  Epoch 020 - train 0.65809 | val 1.23536
  Epoch 021 - train 0.61989 | val 1.23858
  Classification -> best τ=0.425 (val F1=0.2709)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63170 | val 0.80251
  Epoch 020 - train 0.60887 | val 0.90853
  Epoch 021 - train 0.55742 | val 1.03164
  Classification -> best τ=0.575 (val F1=0.2970)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62425 | val 0.86416
  Epoch 020 - train 0.56942 | val 1.89714
  Epoch 022 - train 0.57269 | val 2.00489
  Classification -> best τ=0.425 (val F1=0.3170)
  Directional -> Accuracy: 0.5714, MCC: 0.2598, F1: 0.5532

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69170 | val 1.04184
  Epoch 020 - train 0.67109 | val 2.14758
  Epoch 021 - train 0.67218 | val 2.38588
  Classification -> best τ=0.575 (val F1=0.1834)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66158 | val 0.91933
  Epoch 020 - train 0.61413 | val 1.59580
  Epoch 021 - train 0.64679 | val 1.67200
  Classification -> best τ=0.675 (val F1=0.2674)
  Directional -> Accuracy: 0.5085, MCC: 0.1248, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68046 | val 0.70932
  Epoch 020 - train 0.61267 | val 0.77937
  Epoch 030 - train 0.59536 | val 0.70673
  Classification -> best τ=0.850 (val F1=0.1890)
  Directional -> Accuracy: 0.5373, MCC: 0.1287, F1: 0.0606

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65968 | val 1.59872
  Epoch 020 - train 0.59367 | val 1.89160
  Epoch 022 - train 0.56438 | val 1.46596
  Classification -> best τ=0.525 (val F1=0.4532)
  Directional -> Accuracy: 0.5614, MCC: 0.2071, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60336 | val 1.17242
  Epoch 020 - train 0.48528 | val 2.14771
  Epoch 021 - train 0.55424 | val 2.17362
  Classification -> best τ=0.500 (val F1=0.1096)
  Directional -> Accuracy: 0.5417, MCC: -0.1762, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67165 | val 0.83639
  Epoch 020 - train 0.65517 | val 0.76797
  Epoch 021 - train 0.60568 | val 0.81767
  Classification -> best τ=0.415 (val F1=0.1161)
  Directional -> Accuracy: 0.5000, MCC: 0.1959, F1: 0.3125

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66877 | val 0.91667
  Epoch 020 - train 0.56617 | val 1.13262
  Epoch 021 - train 0.59139 | val 1.23967
  Classification -> best τ=0.385 (val F1=0.2472)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62169 | val 0.76557
  Epoch 020 - train 0.57722 | val 1.13374
  Epoch 030 - train 0.48131 | val 0.96139
  Classification -> best τ=0.595 (val F1=0.3344)
  Directional -> Accuracy: 0.5116, MCC: 0.0283, F1: 0.5116

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69340 | val 0.87183
  Epoch 020 - train 0.61760 | val 1.26110
  Epoch 022 - train 0.59225 | val 1.55816
  Classification -> best τ=0.525 (val F1=0.0259)
  Directional -> Accuracy: 0.6000, MCC: 0.2145, F1: 0.6786

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69320 | val 0.77107
  Epoch 020 - train 0.62390 | val 1.28885
  Epoch 022 - train 0.60073 | val 1.56875
  Classification -> best τ=0.520 (val F1=0.2132)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63599 | val 0.81580
  Epoch 020 - train 0.56774 | val 1.03352
  Epoch 023 - train 0.52702 | val 1.26514
  Classification -> best τ=0.675 (val F1=0.2889)
  Directional -> Accuracy: 0.5294, MCC: 0.0473, F1: 0.5862

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65927 | val 1.08089
  Epoch 020 - train 0.61497 | val 1.45980
  Epoch 022 - train 0.59076 | val 1.43140
  Classification -> best τ=0.455 (val F1=0.3717)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70992 | val 0.72907
  Epoch 020 - train 0.51754 | val 0.70091
  Epoch 021 - train 0.51117 | val 0.69849
  Classification -> best τ=0.395 (val F1=0.3708)
  Directional -> Accuracy: 0.5128, MCC: 0.1581, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64781 | val 1.25468
  Epoch 020 - train 0.64790 | val 0.85290
  Epoch 021 - train 0.57311 | val 0.75904
  Classification -> best τ=0.625 (val F1=0.1612)
  Directional -> Accuracy: 0.5556, MCC: 0.1195, F1: 0.5652

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63915 | val 1.10777
  Epoch 020 - train 0.56197 | val 1.06416
  Epoch 021 - train 0.53298 | val 1.63311
  Classification -> best τ=0.260 (val F1=0.2967)
  Directional -> Accuracy: 0.5000, MCC: 0.1613, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63535 | val 0.78439
  Epoch 020 - train 0.61017 | val 2.46408
  Epoch 022 - train 0.54982 | val 2.39784
  Classification -> best τ=0.645 (val F1=0.1765)
  Directional -> Accuracy: 0.5455, MCC: 0.1581, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66079 | val 0.74278
  Epoch 020 - train 0.60121 | val 0.74171
  Epoch 026 - train 0.61503 | val 0.93598
  Classification -> best τ=0.445 (val F1=0.2475)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62725 | val 1.84311
  Epoch 020 - train 0.50722 | val 3.55452
  Epoch 021 - train 0.52546 | val 3.80222
  Classification -> best τ=0.385 (val F1=0.2233)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61967 | val 0.76802
  Epoch 020 - train 0.62099 | val 2.07502
  Epoch 022 - train 0.51240 | val 2.19611
  Classification -> best τ=0.495 (val F1=0.3873)
  Directional -> Accuracy: 0.5750, MCC: 0.0504, F1: 0.3704

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67001 | val 1.69747
  Epoch 020 - train 0.55161 | val 1.91615
  Epoch 021 - train 0.53390 | val 2.02236
  Classification -> best τ=0.450 (val F1=0.1762)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63132 | val 1.38410
  Epoch 020 - train 0.60400 | val 2.19731
  Epoch 021 - train 0.59801 | val 2.25276
  Classification -> best τ=0.345 (val F1=0.2774)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67711 | val 0.94776
  Epoch 020 - train 0.54913 | val 1.54522
  Epoch 021 - train 0.60199 | val 1.43354
  Classification -> best τ=0.510 (val F1=0.1054)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4783

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66515 | val 2.03468
  Epoch 020 - train 0.48673 | val 2.97083
  Epoch 021 - train 0.49293 | val 3.72580
  Classification -> best τ=0.660 (val F1=0.4000)
  Directional -> Accuracy: 0.4222, MCC: -0.1685, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67933 | val 1.18148
  Epoch 020 - train 0.49728 | val 1.96027
  Epoch 021 - train 0.58076 | val 1.99147
  Classification -> best τ=0.400 (val F1=0.1486)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69765 | val 0.82199
  Epoch 020 - train 0.62482 | val 0.94374
  Epoch 021 - train 0.60697 | val 1.03482
  Classification -> best τ=0.450 (val F1=0.0224)
  Directional -> Accuracy: 0.5614, MCC: 0.2686, F1: 0.3590

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64096 | val 0.89222
  Epoch 020 - train 0.60800 | val 1.99893
  Epoch 021 - train 0.58727 | val 1.97996
  Classification -> best τ=0.695 (val F1=0.4403)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67416 | val 1.16698
  Epoch 020 - train 0.60252 | val 1.50911
  Epoch 028 - train 0.56177 | val 1.13951
  Classification -> best τ=0.480 (val F1=0.2040)
  Directional -> Accuracy: 0.5273, MCC: 0.0695, F1: 0.4800

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-19 23:34:16,748] Trial 26 finished with value: 0.24630404837521616 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.00509961583629753, 'weight_decay': 0.00012135868508257015, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.7851454369507362, 'early_stopping_min_delta': 0.0032281731440828086}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 024 - train 0.65084 | val 0.75213
  Classification -> best τ=0.515 (val F1=0.2653)
  Directional -> Accuracy: 0.4839, MCC: -0.0736, F1: 0.2000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24630404837521616
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68826 | val 0.66762
  Epoch 020 - train 0.68183 | val 0.67128
  Epoch 024 - train 0.68188 | val 0.67001
  Classification -> best τ=0.480 (val F1=0.2989)
  Directional -> Accuracy: 0.5867, MCC: 0.1540, F1: 0.4918

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68817 | val 0.71126
  Epoch 020 - train 0.70539 | val 0.71192
  Epoch 021 - train 0.70863 | val 0.70928
  Classification -> best τ=0.470 (val F1=0.1264)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68770 | val 0.76822
  Epoch 020 - train 0.69137 | val 0.76910
  Epoch 021 - train 0.69848 | val 0.76795
  Classification -> best τ=0.525 (val F1=0.0891)
  Directional -> Accuracy: 0.5111, MCC: -0.0714, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70916 | val 0.70347
  Epoch 020 - train 0.69700 | val 0.70388
  Epoch 021 - train 0.69121 | val 0.70515
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68516 | val 0.65167
  Epoch 020 - train 0.66092 | val 0.64331
  Epoch 030 - train 0.65694 | val 0.63581
  Classification -> best τ=0.655 (val F1=0.4726)
  Directional -> Accuracy: 0.5510, MCC: 0.1954, F1: 0.2667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69648 | val 0.69347
  Epoch 020 - train 0.69695 | val 0.69497
  Epoch 021 - train 0.70434 | val 0.69682
  Classification -> best τ=0.520 (val F1=0.1443)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68945 | val 0.70063
  Epoch 020 - train 0.70418 | val 0.69704
  Epoch 030 - train 0.70543 | val 0.69623
  Classification -> best τ=0.435 (val F1=0.2476)
  Directional -> Accuracy: 0.3881, MCC: -0.1141, F1: 0.5393

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70905 | val 0.66582
  Epoch 020 - train 0.67615 | val 0.68607
  Epoch 027 - train 0.68508 | val 0.69161
  Classification -> best τ=0.440 (val F1=0.0592)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67840 | val 0.67372
  Epoch 020 - train 0.69821 | val 0.67260
  Epoch 028 - train 0.67817 | val 0.67387
  Classification -> best τ=0.470 (val F1=0.3177)
  Directional -> Accuracy: 0.5745, MCC: 0.2111, F1: 0.6296

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68706 | val 0.70736
  Epoch 020 - train 0.68242 | val 0.70707
  Epoch 021 - train 0.67752 | val 0.70890
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69423 | val 0.73169
  Epoch 020 - train 0.68936 | val 0.74842
  Epoch 021 - train 0.68110 | val 0.74733
  Classification -> best τ=0.485 (val F1=0.2000)
  Directional -> Accuracy: 0.4375, MCC: -0.1056, F1: 0.4906

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69551 | val 0.74080
  Epoch 020 - train 0.69995 | val 0.74422
  Epoch 021 - train 0.70873 | val 0.74182
  Classification -> best τ=0.455 (val F1=0.0965)
  Directional -> Accuracy: 0.5536, MCC: 0.1279, F1: 0.6835

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67247 | val 0.80320
  Epoch 020 - train 0.67615 | val 0.83661
  Epoch 021 - train 0.67145 | val 0.82977
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70052 | val 0.67392
  Epoch 020 - train 0.68400 | val 0.67857
  Epoch 027 - train 0.68273 | val 0.67987
  Classification -> best τ=0.530 (val F1=0.3628)
  Directional -> Accuracy: 0.5593, MCC: 0.1311, F1: 0.4800

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68822 | val 0.74500
  Epoch 020 - train 0.68722 | val 0.76099
  Epoch 021 - train 0.69188 | val 0.76070
  Classification -> best τ=0.485 (val F1=0.1558)
  Directional -> Accuracy: 0.6200, MCC: 0.2094, F1: 0.4571

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68623 | val 0.70275
  Epoch 020 - train 0.67809 | val 0.71539
  Epoch 021 - train 0.67236 | val 0.70985
  Classification -> best τ=0.530 (val F1=0.0932)
  Directional -> Accuracy: 0.4853, MCC: 0.0042, F1: 0.3137

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.73409 | val 0.80544
  Epoch 020 - train 0.72622 | val 0.80748
  Epoch 021 - train 0.72578 | val 0.81126
  Classification -> best τ=0.425 (val F1=0.0614)
  Directional -> Accuracy: 0.5789, MCC: -0.0767, F1: 0.7273

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68622 | val 0.70419
  Epoch 020 - train 0.67697 | val 0.70758
  Epoch 021 - train 0.68581 | val 0.70539
  Classification -> best τ=0.520 (val F1=0.1722)
  Directional -> Accuracy: 0.5270, MCC: 0.0137, F1: 0.6067

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68025 | val 0.71444
  Epoch 020 - train 0.67166 | val 0.71829
  Epoch 021 - train 0.67137 | val 0.71603
  Classification -> best τ=0.510 (val F1=0.2449)
  Directional -> Accuracy: 0.5238, MCC: 0.0063, F1: 0.6053

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68391 | val 0.67317
  Epoch 020 - train 0.66122 | val 0.67157
  Epoch 029 - train 0.67726 | val 0.67608
  Classification -> best τ=0.425 (val F1=0.2734)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68005 | val 0.70693
  Epoch 020 - train 0.68562 | val 0.71225
  Epoch 021 - train 0.68811 | val 0.70652
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69175 | val 0.70052
  Epoch 020 - train 0.69110 | val 0.70794
  Epoch 021 - train 0.69918 | val 0.71175
  Classification -> best τ=0.490 (val F1=0.1173)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69585 | val 0.70933
  Epoch 020 - train 0.70527 | val 0.72181
  Epoch 022 - train 0.68553 | val 0.71405
  Classification -> best τ=0.610 (val F1=0.3131)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69128 | val 0.79391
  Epoch 020 - train 0.68111 | val 0.78917
  Epoch 021 - train 0.68884 | val 0.80215
  Classification -> best τ=0.465 (val F1=0.1932)
  Directional -> Accuracy: 0.5000, MCC: -0.0039, F1: 0.4667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68874 | val 0.66810
  Epoch 020 - train 0.67418 | val 0.65356
  Epoch 030 - train 0.67683 | val 0.64175
  Classification -> best τ=0.550 (val F1=0.4542)
  Directional -> Accuracy: 0.4259, MCC: -0.1628, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70563 | val 0.72148
  Epoch 020 - train 0.68185 | val 0.73078
  Epoch 021 - train 0.69734 | val 0.73159
  Classification -> best τ=0.485 (val F1=0.0223)
  Directional -> Accuracy: 0.4651, MCC: 0.1874, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70202 | val 0.69029
  Epoch 020 - train 0.70154 | val 0.68735
  Epoch 021 - train 0.68428 | val 0.68774
  Classification -> best τ=0.520 (val F1=0.0366)
  Directional -> Accuracy: 0.3878, MCC: -0.1422, F1: 0.2105

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68089 | val 0.66447
  Epoch 020 - train 0.69466 | val 0.65781
  Epoch 030 - train 0.68561 | val 0.65663
  Classification -> best τ=0.430 (val F1=0.3514)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75571 | val 0.75302
  Epoch 020 - train 0.72518 | val 0.77360
  Epoch 021 - train 0.73011 | val 0.77269
  Classification -> best τ=0.440 (val F1=0.1288)
  Directional -> Accuracy: 0.6053, MCC: 0.2620, F1: 0.7368

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67208 | val 0.75760
  Epoch 020 - train 0.67952 | val 0.76887
  Epoch 021 - train 0.67374 | val 0.76982
  Classification -> best τ=0.505 (val F1=0.2706)
  Directional -> Accuracy: 0.5366, MCC: 0.0719, F1: 0.3448

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69301 | val 0.72355
  Epoch 020 - train 0.69815 | val 0.73080
  Epoch 023 - train 0.70772 | val 0.72515
  Classification -> best τ=0.445 (val F1=0.2339)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69140 | val 0.68713
  Epoch 020 - train 0.67865 | val 0.69183
  Epoch 026 - train 0.69328 | val 0.69458
  Classification -> best τ=0.505 (val F1=0.3177)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67273 | val 0.67085
  Epoch 020 - train 0.66840 | val 0.66850
  Epoch 030 - train 0.66217 | val 0.66945
  Classification -> best τ=0.515 (val F1=0.2623)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67785 | val 0.68604
  Epoch 020 - train 0.67935 | val 0.68159
  Epoch 024 - train 0.68008 | val 0.68476
  Classification -> best τ=0.525 (val F1=0.1462)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67132 | val 0.69143
  Epoch 020 - train 0.66722 | val 0.69487
  Epoch 022 - train 0.66607 | val 0.69649
  Classification -> best τ=0.405 (val F1=0.2100)
  Directional -> Accuracy: 0.5692, MCC: 0.0000, F1: 0.7255

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69891 | val 0.68542
  Epoch 020 - train 0.67829 | val 0.68459
  Epoch 027 - train 0.66683 | val 0.68523
  Classification -> best τ=0.520 (val F1=0.2887)
  Directional -> Accuracy: 0.5250, MCC: 0.0409, F1: 0.5778

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66048 | val 0.69833
  Epoch 020 - train 0.66938 | val 0.69951
  Epoch 021 - train 0.66398 | val 0.69926
  Classification -> best τ=0.475 (val F1=0.0803)
  Directional -> Accuracy: 0.4909, MCC: -0.0913, F1: 0.2222

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67733 | val 0.69023
  Epoch 020 - train 0.68629 | val 0.69871
  Epoch 021 - train 0.67125 | val 0.69989
  Classification -> best τ=0.470 (val F1=0.0710)
  Directional -> Accuracy: 0.3778, MCC: -0.1872, F1: 0.3636

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69555 | val 0.67883
  Epoch 020 - train 0.70447 | val 0.67221
  Epoch 030 - train 0.68874 | val 0.67020
  Classification -> best τ=0.665 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70418 | val 0.72610
  Epoch 020 - train 0.69605 | val 0.72919
  Epoch 021 - train 0.67426 | val 0.73400
  Classification -> best τ=0.455 (val F1=0.1776)
  Directional -> Accuracy: 0.5342, MCC: 0.0897, F1: 0.6304

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68151 | val 0.68114
  Epoch 020 - train 0.68270 | val 0.67843
  Epoch 030 - train 0.68201 | val 0.67494
  Classification -> best τ=0.510 (val F1=0.3536)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67079 | val 0.69304
  Epoch 020 - train 0.67472 | val 0.69362
  Epoch 021 - train 0.69748 | val 0.69421
  Classification -> best τ=0.495 (val F1=0.1690)
  Directional -> Accuracy: 0.5366, MCC: 0.0371, F1: 0.6122

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69053 | val 0.80714
  Epoch 020 - train 0.66524 | val 0.83426
  Epoch 021 - train 0.69132 | val 0.83307
  Classification -> best τ=0.530 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71657 | val 0.68753
  Epoch 020 - train 0.70260 | val 0.68752
  Epoch 024 - train 0.69743 | val 0.68715
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66922 | val 0.74535
  Epoch 020 - train 0.69367 | val 0.78324
  Epoch 021 - train 0.68467 | val 0.78193
  Classification -> best τ=0.470 (val F1=0.1949)
  Directional -> Accuracy: 0.4545, MCC: -0.0941, F1: 0.5588

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69530 | val 0.68972
  Epoch 020 - train 0.68527 | val 0.69388
  Epoch 021 - train 0.69460 | val 0.69024
  Classification -> best τ=0.535 (val F1=0.2376)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6176

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67036 | val 0.67488
  Epoch 020 - train 0.68073 | val 0.68284
  Epoch 025 - train 0.68281 | val 0.68647
  Classification -> best τ=0.460 (val F1=0.2383)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69061 | val 0.68125
  Epoch 020 - train 0.68821 | val 0.68906

[I 2026-02-19 23:40:11,731] Trial 27 finished with value: 0.18805265215424227 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 2.1109745167825455e-05, 'weight_decay': 2.0481252051690598e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3967753624928654, 'early_stopping_min_delta': 0.002557816403272701}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 027 - train 0.67408 | val 0.69737
  Classification -> best τ=0.480 (val F1=0.2671)
  Directional -> Accuracy: 0.5424, MCC: 0.0764, F1: 0.1818

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18805265215424227
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67980 | val 0.80549
  Epoch 020 - train 0.66634 | val 0.81051
  Classification -> best τ=0.510 (val F1=0.0961)
  Directional -> Accuracy: 0.5443, MCC: -0.0439, F1: 0.0526

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68427 | val 0.71872
  Epoch 020 - train 0.66743 | val 0.72918
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67417 | val 0.66000
  Epoch 020 - train 0.66646 | val 0.68618
  Classification -> best τ=0.345 (val F1=0.4729)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67572 | val 0.73711
  Epoch 020 - train 0.66875 | val 0.73182
  Classification -> best τ=0.470 (val F1=0.0122)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66650 | val 0.76951
  Epoch 020 - train 0.65198 | val 1.07543
  Classification -> best τ=0.730 (val F1=0.3686)
  Directional -> Accuracy: 0.5849, MCC: 0.2403, F1: 0.4500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65755 | val 0.71459
  Epoch 020 - train 0.63729 | val 0.71513
  Classification -> best τ=0.545 (val F1=0.1419)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68908 | val 0.79682
  Epoch 020 - train 0.68701 | val 0.81004
  Classification -> best τ=0.465 (val F1=0.2582)
  Directional -> Accuracy: 0.5493, MCC: 0.1429, F1: 0.5556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65765 | val 0.65900
  Epoch 020 - train 0.66134 | val 0.77928
  Classification -> best τ=0.375 (val F1=0.0231)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64899 | val 0.80365
  Epoch 020 - train 0.69744 | val 0.81657
  Classification -> best τ=0.515 (val F1=0.1391)
  Directional -> Accuracy: 0.4651, MCC: -0.0271, F1: 0.4651

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64382 | val 1.17355
  Epoch 020 - train 0.64291 | val 1.10133
  Classification -> best τ=0.485 (val F1=0.2273)
  Directional -> Accuracy: 0.4167, MCC: -0.1158, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67804 | val 0.69907
  Epoch 020 - train 0.65935 | val 0.71482
  Classification -> best τ=0.560 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69025 | val 0.70879
  Epoch 020 - train 0.68512 | val 0.69600
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61938 | val 0.85922
  Epoch 020 - train 0.63421 | val 0.94383
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66710 | val 0.58928
  Epoch 020 - train 0.65757 | val 0.61618
  Classification -> best τ=0.410 (val F1=0.3610)
  Directional -> Accuracy: 0.5079, MCC: 0.0261, F1: 0.5974

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69016 | val 0.90463
  Epoch 020 - train 0.68159 | val 0.98841
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65066 | val 0.94565
  Epoch 020 - train 0.65106 | val 0.98936
  Classification -> best τ=0.440 (val F1=0.2453)
  Directional -> Accuracy: 0.5972, MCC: 0.2637, F1: 0.7290

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64972 | val 1.25769
  Epoch 020 - train 0.65628 | val 1.33345
  Classification -> best τ=0.505 (val F1=0.0059)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67490 | val 0.77602
  Epoch 020 - train 0.67533 | val 0.79166
  Classification -> best τ=0.465 (val F1=0.0727)
  Directional -> Accuracy: 0.4744, MCC: 0.1882, F1: 0.2545

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67119 | val 0.70264
  Epoch 020 - train 0.66448 | val 0.71574
  Classification -> best τ=0.490 (val F1=0.2665)
  Directional -> Accuracy: 0.4328, MCC: 0.0371, F1: 0.0952

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63896 | val 0.71520
  Epoch 020 - train 0.64334 | val 0.68824
  Classification -> best τ=0.415 (val F1=0.2935)
  Directional -> Accuracy: 0.5325, MCC: 0.1155, F1: 0.4375

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69162 | val 0.72963
  Epoch 020 - train 0.64502 | val 0.79228
  Classification -> best τ=0.515 (val F1=0.0097)
  Directional -> Accuracy: 0.4400, MCC: -0.1042, F1: 0.4815

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67883 | val 0.69061
  Epoch 020 - train 0.69955 | val 0.69531
  Classification -> best τ=0.495 (val F1=0.2705)
  Directional -> Accuracy: 0.4412, MCC: -0.1179, F1: 0.4242

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65897 | val 0.77073
  Epoch 020 - train 0.64964 | val 0.78490
  Classification -> best τ=0.580 (val F1=0.2372)
  Directional -> Accuracy: 0.4667, MCC: 0.1939, F1: 0.1579

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65559 | val 0.71663
  Epoch 020 - train 0.63463 | val 0.71689
  Classification -> best τ=0.490 (val F1=0.1667)
  Directional -> Accuracy: 0.5294, MCC: 0.0849, F1: 0.6190

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70585 | val 0.65746
  Epoch 020 - train 0.63716 | val 0.62685
  Classification -> best τ=0.485 (val F1=0.4242)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65494 | val 0.69446
  Epoch 020 - train 0.63463 | val 0.69917
  Classification -> best τ=0.630 (val F1=0.2337)
  Directional -> Accuracy: 0.4490, MCC: -0.0282, F1: 0.5424

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70621 | val 0.69653
  Epoch 020 - train 0.65564 | val 0.69298
  Classification -> best τ=0.510 (val F1=0.2883)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7164

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69105 | val 0.71624
  Epoch 020 - train 0.66272 | val 0.73798
  Classification -> best τ=0.485 (val F1=0.1558)
  Directional -> Accuracy: 0.5424, MCC: 0.2190, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65404 | val 0.72430
  Epoch 020 - train 0.62335 | val 0.76323
  Classification -> best τ=0.550 (val F1=0.2345)
  Directional -> Accuracy: 0.5000, MCC: 0.0204, F1: 0.3889

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66565 | val 0.71109
  Epoch 020 - train 0.68590 | val 0.71132
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69247 | val 0.67534
  Epoch 020 - train 0.67110 | val 0.70049
  Classification -> best τ=0.595 (val F1=0.2429)
  Directional -> Accuracy: 0.5870, MCC: 0.1818, F1: 0.7164

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67922 | val 0.71140
  Epoch 020 - train 0.66287 | val 0.72780
  Classification -> best τ=0.425 (val F1=0.2981)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67341 | val 0.68088
  Epoch 020 - train 0.66708 | val 0.68507
  Classification -> best τ=0.405 (val F1=0.3850)
  Directional -> Accuracy: 0.5467, MCC: 0.1288, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68163 | val 0.68856
  Epoch 020 - train 0.67172 | val 0.71314
  Classification -> best τ=0.595 (val F1=0.3477)
  Directional -> Accuracy: 0.5366, MCC: 0.0998, F1: 0.6275

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69735 | val 0.74691
  Epoch 020 - train 0.68441 | val 0.77438
  Classification -> best τ=0.505 (val F1=0.0186)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67297 | val 0.67386
  Epoch 020 - train 0.64807 | val 0.70327
  Classification -> best τ=0.330 (val F1=0.3376)
  Directional -> Accuracy: 0.6087, MCC: 0.2907, F1: 0.5714

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66235 | val 0.68980
  Epoch 020 - train 0.66101 | val 0.70883
  Classification -> best τ=0.590 (val F1=0.1787)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63095 | val 0.85110
  Epoch 020 - train 0.62425 | val 0.84397
  Classification -> best τ=0.485 (val F1=0.0228)
  Directional -> Accuracy: 0.4576, MCC: -0.0688, F1: 0.5897

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69126 | val 1.98469
  Epoch 020 - train 0.69037 | val 1.94397
  Classification -> best τ=0.545 (val F1=0.2052)
  Directional -> Accuracy: 0.5510, MCC: -0.0266, F1: 0.6765

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65079 | val 0.67250
  Epoch 020 - train 0.65718 | val 0.66417
  Classification -> best τ=0.675 (val F1=0.3679)
  Directional -> Accuracy: 0.4048, MCC: 0.0452, F1: 0.4898

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70224 | val 0.73037
  Epoch 020 - train 0.65693 | val 0.79052
  Classification -> best τ=0.505 (val F1=0.0173)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67891 | val 0.85420
  Epoch 020 - train 0.65547 | val 0.97695
  Classification -> best τ=0.500 (val F1=0.2312)
  Directional -> Accuracy: 0.5195, MCC: 0.1162, F1: 0.6783

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68405 | val 0.73221
  Epoch 020 - train 0.63830 | val 0.88223
  Classification -> best τ=0.560 (val F1=0.2400)
  Directional -> Accuracy: 0.5510, MCC: 0.1322, F1: 0.2667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63552 | val 0.79222
  Epoch 020 - train 0.63962 | val 0.84122
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67001 | val 0.93671
  Epoch 020 - train 0.66130 | val 1.00525
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71659 | val 0.67843
  Epoch 020 - train 0.68676 | val 0.68613
  Classification -> best τ=0.720 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67868 | val 1.32558
  Epoch 020 - train 0.66073 | val 1.32652
  Classification -> best τ=0.540 (val F1=0.3789)
  Directional -> Accuracy: 0.5424, MCC: 0.1774, F1: 0.6747

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66698 | val 0.87737
  Epoch 020 - train 0.65361 | val 0.90572
  Classification -> best τ=0.495 (val F1=0.0039)
  Directional -> Accuracy: 0.6429, MCC: 0.2776, F1: 0.6970

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62488 | val 1.80345
  Epoch 020 - train 0.65627 | val 1.62716
  Classification -> best τ=0.470 (val F1=0.1867)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67073 | val 0.75528

[I 2026-02-19 23:41:14,833] Trial 28 finished with value: 0.18278751037095417 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0006244546993799865, 'weight_decay': 0.00044299227099675077, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.9407341023543949, 'early_stopping_min_delta': 0.0014366026644389914}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 020 - train 0.69549 | val 0.82727
  Classification -> best τ=0.495 (val F1=0.2329)
  Directional -> Accuracy: 0.4603, MCC: -0.0853, F1: 0.6222

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18278751037095417
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65828 | val 0.69468
  Epoch 016 - train 0.64877 | val 0.72137
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63999 | val 0.69024
  Epoch 020 - train 0.59418 | val 0.69280
  Epoch 026 - train 0.61869 | val 0.70077
  Classification -> best τ=0.505 (val F1=0.2346)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70786 | val 0.69941
  Epoch 016 - train 0.71239 | val 0.75901
  Classification -> best τ=0.470 (val F1=0.2173)
  Directional -> Accuracy: 0.5208, MCC: -0.0648, F1: 0.6761

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65367 | val 0.75621
  Epoch 016 - train 0.65603 | val 0.83794
  Classification -> best τ=0.445 (val F1=0.0601)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66017 | val 0.65680
  Epoch 020 - train 0.61931 | val 0.75083
  Epoch 026 - train 0.61049 | val 0.75632
  Classification -> best τ=0.590 (val F1=0.3385)
  Directional -> Accuracy: 0.5962, MCC: 0.2906, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64502 | val 0.69140
  Epoch 016 - train 0.63154 | val 0.76139
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70129 | val 0.68194
  Epoch 020 - train 0.68117 | val 0.71988
  Epoch 025 - train 0.69107 | val 0.71553
  Classification -> best τ=0.530 (val F1=0.1832)
  Directional -> Accuracy: 0.4429, MCC: 0.0000, F1: 0.5301

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59578 | val 0.83705
  Epoch 016 - train 0.64470 | val 0.91451
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68594 | val 0.67813
  Epoch 020 - train 0.64545 | val 0.71392
  Epoch 023 - train 0.65386 | val 0.74150
  Classification -> best τ=0.530 (val F1=0.3364)
  Directional -> Accuracy: 0.5952, MCC: 0.2205, F1: 0.5641

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63842 | val 0.72239
  Epoch 016 - train 0.64570 | val 0.70975
  Classification -> best τ=0.475 (val F1=0.2721)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67566 | val 0.71715
  Epoch 016 - train 0.63451 | val 0.76472
  Classification -> best τ=0.520 (val F1=0.1557)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67054 | val 0.71927
  Epoch 016 - train 0.65307 | val 0.83473
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65353 | val 0.70745
  Epoch 016 - train 0.62314 | val 0.83368
  Classification -> best τ=0.515 (val F1=0.1922)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68988 | val 0.70655
  Epoch 020 - train 0.64242 | val 0.76267
  Epoch 021 - train 0.64805 | val 0.78250
  Classification -> best τ=0.515 (val F1=0.3395)
  Directional -> Accuracy: 0.5968, MCC: 0.2070, F1: 0.5098

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64869 | val 0.72959
  Epoch 016 - train 0.65185 | val 0.80607
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61757 | val 0.67354
  Epoch 020 - train 0.65088 | val 0.79445
  Epoch 023 - train 0.63386 | val 0.78591
  Classification -> best τ=0.590 (val F1=0.3276)
  Directional -> Accuracy: 0.5352, MCC: 0.1649, F1: 0.3265

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66100 | val 0.72390
  Epoch 016 - train 0.62980 | val 0.76002
  Classification -> best τ=0.475 (val F1=0.1555)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69144 | val 0.76846
  Epoch 016 - train 0.67449 | val 0.96293
  Classification -> best τ=0.540 (val F1=0.0549)
  Directional -> Accuracy: 0.4675, MCC: 0.0637, F1: 0.3692

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69121 | val 0.72575
  Epoch 016 - train 0.65340 | val 1.04252
  Classification -> best τ=0.455 (val F1=0.1677)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65489 | val 0.67663
  Epoch 020 - train 0.62350 | val 0.69517
  Epoch 023 - train 0.57669 | val 0.69458
  Classification -> best τ=0.515 (val F1=0.2582)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64415 | val 0.69169
  Epoch 016 - train 0.63347 | val 0.72288
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67226 | val 0.73073
  Epoch 016 - train 0.66325 | val 0.73759
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67740 | val 0.68354
  Epoch 020 - train 0.65421 | val 0.77036
  Epoch 023 - train 0.63447 | val 0.76690
  Classification -> best τ=0.525 (val F1=0.2226)
  Directional -> Accuracy: 0.5593, MCC: 0.0603, F1: 0.6579

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67246 | val 0.72352
  Epoch 019 - train 0.64289 | val 0.72998
  Classification -> best τ=0.510 (val F1=0.1075)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65579 | val 0.65720
  Epoch 020 - train 0.63287 | val 0.66420
  Epoch 028 - train 0.63472 | val 0.68121
  Classification -> best τ=0.455 (val F1=0.4030)
  Directional -> Accuracy: 0.5088, MCC: 0.0025, F1: 0.5625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65030 | val 0.70210
  Epoch 016 - train 0.70704 | val 0.71628
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66707 | val 0.71242
  Epoch 020 - train 0.63731 | val 0.77089
  Epoch 029 - train 0.61034 | val 0.78805
  Classification -> best τ=0.480 (val F1=0.2079)
  Directional -> Accuracy: 0.5909, MCC: 0.0403, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65810 | val 0.68648
  Epoch 016 - train 0.63007 | val 0.73047
  Classification -> best τ=0.460 (val F1=0.2369)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69852 | val 0.68852
  Epoch 020 - train 0.61693 | val 0.69201
  Epoch 029 - train 0.64551 | val 0.85206
  Classification -> best τ=0.565 (val F1=0.3077)
  Directional -> Accuracy: 0.5814, MCC: 0.1533, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65704 | val 0.72739
  Epoch 016 - train 0.68736 | val 0.75282
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70019 | val 0.68408
  Epoch 016 - train 0.68454 | val 0.71154
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67708 | val 0.67326
  Epoch 020 - train 0.61795 | val 0.70791
  Epoch 023 - train 0.62133 | val 0.71068
  Classification -> best τ=0.455 (val F1=0.2787)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66756 | val 0.70126
  Epoch 020 - train 0.63989 | val 1.05333
  Epoch 021 - train 0.66008 | val 1.07484
  Classification -> best τ=0.475 (val F1=0.3259)
  Directional -> Accuracy: 0.5946, MCC: 0.1682, F1: 0.6512

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65258 | val 0.70862
  Epoch 016 - train 0.64993 | val 0.72579
  Classification -> best τ=0.485 (val F1=0.2097)
  Directional -> Accuracy: 0.4359, MCC: -0.1282, F1: 0.5217

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65331 | val 0.72380
  Epoch 016 - train 0.65462 | val 0.76860
  Classification -> best τ=0.520 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69590 | val 0.70273
  Epoch 020 - train 0.65693 | val 0.73165
  Epoch 021 - train 0.62359 | val 0.73442
  Classification -> best τ=0.430 (val F1=0.2967)
  Directional -> Accuracy: 0.5147, MCC: 0.2226, F1: 0.2979

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70707 | val 0.68976
  Epoch 020 - train 0.64423 | val 0.68198
  Epoch 030 - train 0.64331 | val 0.68308
  Classification -> best τ=0.540 (val F1=0.3151)
  Directional -> Accuracy: 0.7045, MCC: 0.4201, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64119 | val 0.77118
  Epoch 016 - train 0.62794 | val 0.79043
  Classification -> best τ=0.495 (val F1=0.2171)
  Directional -> Accuracy: 0.5345, MCC: 0.0188, F1: 0.1290

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61659 | val 0.75287
  Epoch 016 - train 0.63823 | val 0.95818
  Classification -> best τ=0.520 (val F1=0.2726)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65097 | val 0.68150
  Epoch 016 - train 0.64357 | val 0.68733
  Classification -> best τ=0.465 (val F1=0.2000)
  Directional -> Accuracy: 0.3750, MCC: 0.0099, F1: 0.5098

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66573 | val 0.69904
  Epoch 016 - train 0.65389 | val 0.72000
  Classification -> best τ=0.455 (val F1=0.1762)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65746 | val 0.67335
  Epoch 020 - train 0.62040 | val 0.78362
  Epoch 023 - train 0.64556 | val 0.83862
  Classification -> best τ=0.400 (val F1=0.3763)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65513 | val 0.70622
  Epoch 016 - train 0.66332 | val 0.70833
  Classification -> best τ=0.540 (val F1=0.1492)
  Directional -> Accuracy: 0.5208, MCC: 0.1459, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69623 | val 0.70935
  Epoch 016 - train 0.60896 | val 0.73276
  Classification -> best τ=0.500 (val F1=0.3686)
  Directional -> Accuracy: 0.5111, MCC: 0.0767, F1: 0.4211

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65645 | val 0.76440
  Epoch 016 - train 0.69732 | val 0.88138
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66151 | val 0.75599
  Epoch 016 - train 0.66393 | val 0.89860
  Classification -> best τ=0.505 (val F1=0.1512)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67284 | val 0.74459
  Epoch 016 - train 0.65189 | val 0.92492
  Classification -> best τ=0.525 (val F1=0.2908)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64317 | val 0.84423
  Epoch 016 - train 0.62696 | val 1.34526
  Classification -> best τ=0.490 (val F1=0.1771)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65461 | val 0.73992
  Epoch 016 - train 0.64042 | val 1.13659
  Classification -> best τ=0.475 (val F1=0.1093)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65344 | val 0.77950

[I 2026-02-19 23:42:06,576] Trial 29 finished with value: 0.1779070474775342 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.001103131677490042, 'weight_decay': 2.352750438502512e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.5483815053457293, 'early_stopping_min_delta': 0.004381791088204945}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 016 - train 0.65803 | val 0.93077
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1779070474775342
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61843 | val 0.88154
  Epoch 011 - train 0.63361 | val 0.88484
  Classification -> best τ=0.570 (val F1=0.1903)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63062 | val 0.86264
  Epoch 012 - train 0.60186 | val 0.87201
  Classification -> best τ=0.560 (val F1=0.1654)
  Directional -> Accuracy: 0.6250, MCC: 0.2208, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63409 | val 0.77413
  Epoch 013 - train 0.63180 | val 0.79554
  Classification -> best τ=0.400 (val F1=0.3215)
  Directional -> Accuracy: 0.5510, MCC: 0.1535, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63411 | val 0.84165
  Epoch 011 - train 0.62744 | val 0.82210
  Classification -> best τ=0.455 (val F1=0.1654)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59942 | val 0.64923
  Epoch 015 - train 0.58418 | val 0.68626
  Classification -> best τ=0.595 (val F1=0.4274)
  Directional -> Accuracy: 0.6226, MCC: 0.3089, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60164 | val 0.89541
  Epoch 011 - train 0.59861 | val 0.90658
  Classification -> best τ=0.510 (val F1=0.1249)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65629 | val 1.07565
  Epoch 011 - train 0.64126 | val 1.08756
  Classification -> best τ=0.475 (val F1=0.2524)
  Directional -> Accuracy: 0.5070, MCC: 0.1305, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61129 | val 0.78844
  Epoch 011 - train 0.59857 | val 0.77933
  Classification -> best τ=0.475 (val F1=0.2582)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62885 | val 0.76053
  Epoch 011 - train 0.63816 | val 0.75817
  Classification -> best τ=0.555 (val F1=0.3015)
  Directional -> Accuracy: 0.5581, MCC: 0.2561, F1: 0.6122

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60252 | val 1.32282
  Epoch 011 - train 0.60584 | val 1.32317
  Classification -> best τ=0.480 (val F1=0.1582)
  Directional -> Accuracy: 0.4583, MCC: 0.0020, F1: 0.5618

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62930 | val 0.93073
  Epoch 011 - train 0.62571 | val 0.89838
  Classification -> best τ=0.480 (val F1=0.1306)
  Directional -> Accuracy: 0.6346, MCC: 0.2673, F1: 0.4865

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64844 | val 0.81196
  Epoch 011 - train 0.66083 | val 0.81291
  Classification -> best τ=0.475 (val F1=0.0711)
  Directional -> Accuracy: 0.6500, MCC: 0.3464, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56702 | val 0.67327
  Epoch 020 - train 0.51248 | val 0.69126
  Epoch 021 - train 0.48789 | val 0.68747
  Classification -> best τ=0.595 (val F1=0.2963)
  Directional -> Accuracy: 0.4444, MCC: -0.1022, F1: 0.4681

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63339 | val 0.70417
  Epoch 013 - train 0.61221 | val 0.73142
  Classification -> best τ=0.620 (val F1=0.3883)
  Directional -> Accuracy: 0.5238, MCC: 0.0602, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63958 | val 2.72538
  Epoch 011 - train 0.65156 | val 2.78500
  Classification -> best τ=0.585 (val F1=0.2527)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59527 | val 1.08797
  Epoch 011 - train 0.59457 | val 1.07408
  Classification -> best τ=0.400 (val F1=0.2453)
  Directional -> Accuracy: 0.5833, MCC: 0.2267, F1: 0.7222

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62650 | val 1.66294
  Epoch 011 - train 0.63027 | val 1.75003
  Classification -> best τ=0.575 (val F1=0.1559)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63825 | val 1.03216
  Epoch 011 - train 0.64300 | val 1.02169
  Classification -> best τ=0.485 (val F1=0.1020)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62739 | val 0.78098
  Epoch 013 - train 0.62439 | val 0.78929
  Classification -> best τ=0.505 (val F1=0.2652)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61293 | val 0.71074
  Epoch 011 - train 0.60329 | val 0.71627
  Classification -> best τ=0.460 (val F1=0.2334)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61639 | val 0.76496
  Epoch 011 - train 0.60558 | val 0.77105
  Classification -> best τ=0.525 (val F1=0.2303)
  Directional -> Accuracy: 0.5400, MCC: -0.0071, F1: 0.6462

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66081 | val 0.71697
  Epoch 011 - train 0.65142 | val 0.72063
  Classification -> best τ=0.520 (val F1=0.1698)
  Directional -> Accuracy: 0.4265, MCC: -0.1476, F1: 0.4507

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63728 | val 0.73724
  Epoch 011 - train 0.62754 | val 0.74338
  Classification -> best τ=0.550 (val F1=0.1044)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61534 | val 0.69901
  Epoch 011 - train 0.61853 | val 0.70179
  Classification -> best τ=0.465 (val F1=0.1641)
  Directional -> Accuracy: 0.5147, MCC: 0.1177, F1: 0.6598

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61521 | val 0.66059
  Epoch 015 - train 0.61209 | val 0.67289
  Classification -> best τ=0.465 (val F1=0.4873)
  Directional -> Accuracy: 0.5690, MCC: 0.2157, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63271 | val 0.69915
  Epoch 011 - train 0.63286 | val 0.70157
  Classification -> best τ=0.495 (val F1=0.0147)
  Directional -> Accuracy: 0.5306, MCC: 0.1978, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62401 | val 0.77943
  Epoch 011 - train 0.62734 | val 0.77376
  Classification -> best τ=0.460 (val F1=0.1455)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.5769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63092 | val 0.90460
  Epoch 013 - train 0.63632 | val 0.96049
  Classification -> best τ=0.415 (val F1=0.2634)
  Directional -> Accuracy: 0.5424, MCC: 0.2518, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59968 | val 0.89623
  Epoch 011 - train 0.59322 | val 0.93762
  Classification -> best τ=0.500 (val F1=0.1465)
  Directional -> Accuracy: 0.6364, MCC: 0.2818, F1: 0.6190

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61951 | val 0.74100
  Epoch 011 - train 0.61406 | val 0.74305
  Classification -> best τ=0.490 (val F1=0.0065)
  Directional -> Accuracy: 0.5217, MCC: 0.0510, F1: 0.6207

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63196 | val 0.71743
  Epoch 015 - train 0.62024 | val 0.71093
  Classification -> best τ=0.480 (val F1=0.2425)
  Directional -> Accuracy: 0.5652, MCC: 0.1114, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59607 | val 0.87593
  Epoch 012 - train 0.59011 | val 0.88673
  Classification -> best τ=0.430 (val F1=0.3025)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62027 | val 0.67066
  Epoch 012 - train 0.61189 | val 0.67706
  Classification -> best τ=0.355 (val F1=0.3523)
  Directional -> Accuracy: 0.5333, MCC: 0.0971, F1: 0.5070

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63798 | val 0.70078
  Epoch 011 - train 0.62566 | val 0.70970
  Classification -> best τ=0.505 (val F1=0.2774)
  Directional -> Accuracy: 0.5122, MCC: 0.0080, F1: 0.1667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62490 | val 1.10669
  Epoch 011 - train 0.63139 | val 1.09148
  Classification -> best τ=0.540 (val F1=0.1114)
  Directional -> Accuracy: 0.5435, MCC: 0.0460, F1: 0.3226

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62014 | val 0.74082
  Epoch 012 - train 0.61134 | val 0.74083
  Classification -> best τ=0.400 (val F1=0.3498)
  Directional -> Accuracy: 0.6522, MCC: 0.3016, F1: 0.6842

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60539 | val 0.78694
  Epoch 014 - train 0.59507 | val 0.85146
  Classification -> best τ=0.440 (val F1=0.2891)
  Directional -> Accuracy: 0.5778, MCC: 0.2222, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62267 | val 0.90076
  Epoch 011 - train 0.61205 | val 0.90383
  Classification -> best τ=0.480 (val F1=0.1097)
  Directional -> Accuracy: 0.5085, MCC: -0.0192, F1: 0.2564

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59917 | val 1.45793
  Epoch 011 - train 0.59921 | val 1.47276
  Classification -> best τ=0.510 (val F1=0.2032)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61466 | val 0.64580
  Epoch 017 - train 0.56018 | val 0.66310
  Classification -> best τ=0.415 (val F1=0.4142)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61930 | val 0.73933
  Epoch 011 - train 0.60741 | val 0.74253
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62710 | val 1.02946
  Epoch 011 - train 0.61743 | val 1.08172
  Classification -> best τ=0.455 (val F1=0.1576)
  Directional -> Accuracy: 0.5325, MCC: 0.1654, F1: 0.6842

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63483 | val 1.09263
  Epoch 011 - train 0.63695 | val 1.12103
  Classification -> best τ=0.555 (val F1=0.0731)
  Directional -> Accuracy: 0.5510, MCC: 0.1264, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59524 | val 1.07250
  Epoch 011 - train 0.59426 | val 1.09346
  Classification -> best τ=0.540 (val F1=0.2191)
  Directional -> Accuracy: 0.6809, MCC: 0.3467, F1: 0.7692

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59065 | val 0.83405
  Epoch 011 - train 0.58955 | val 0.81087
  Classification -> best τ=0.575 (val F1=0.1425)
  Directional -> Accuracy: 0.4048, MCC: 0.0203, F1: 0.5098

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65061 | val 0.72263
  Epoch 013 - train 0.65450 | val 0.71431
  Classification -> best τ=0.655 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60106 | val 1.70577
  Epoch 011 - train 0.62063 | val 1.69968
  Classification -> best τ=0.495 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63411 | val 1.12575
  Epoch 011 - train 0.63372 | val 1.13222
  Classification -> best τ=0.490 (val F1=0.1602)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60196 | val 1.98618
  Epoch 011 - train 0.61288 | val 1.99045
  Classification -> best τ=0.530 (val F1=0.2129)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64096 | val 1.20577
  Epoch 011 - train 0.64669 | val 1.19899

[I 2026-02-19 23:43:12,759] Trial 30 finished with value: 0.21018772534327343 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.000322717749899261, 'weight_decay': 0.00019777471209912254, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5659143355064133, 'early_stopping_min_delta': 0.0029198772636040466}. Best is trial 22 with value: 0.26179994200866186.

  Classification -> best τ=0.560 (val F1=0.2101)
  Directional -> Accuracy: 0.5079, MCC: -0.0199, F1: 0.2439

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21018772534327343
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65013 | val 0.75432
  Epoch 020 - train 0.61495 | val 0.96598
  Epoch 022 - train 0.63268 | val 1.04414
  Classification -> best τ=0.705 (val F1=0.2346)
  Directional -> Accuracy: 0.5316, MCC: -0.0460, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63721 | val 0.97425
  Epoch 020 - train 0.57990 | val 1.10904
  Epoch 021 - train 0.60779 | val 1.09167
  Classification -> best τ=0.500 (val F1=0.2219)
  Directional -> Accuracy: 0.6042, MCC: 0.1732, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65724 | val 0.82469
  Epoch 020 - train 0.63195 | val 0.92461
  Epoch 021 - train 0.64242 | val 0.93530
  Classification -> best τ=0.445 (val F1=0.3215)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64953 | val 0.67603
  Epoch 020 - train 0.60653 | val 0.74344
  Epoch 030 - train 0.61558 | val 0.79029
  Classification -> best τ=0.385 (val F1=0.2371)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66361 | val 0.99839
  Epoch 020 - train 0.60006 | val 1.52334
  Epoch 022 - train 0.59562 | val 1.53978
  Classification -> best τ=0.555 (val F1=0.3686)
  Directional -> Accuracy: 0.6226, MCC: 0.2403, F1: 0.6552

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63584 | val 0.94643
  Epoch 020 - train 0.60085 | val 0.76129
  Epoch 021 - train 0.60341 | val 0.74560
  Classification -> best τ=0.565 (val F1=0.1194)
  Directional -> Accuracy: 0.5854, MCC: 0.1556, F1: 0.4138

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65905 | val 1.00015
  Epoch 020 - train 0.64244 | val 1.14649
  Epoch 021 - train 0.63211 | val 1.17212
  Classification -> best τ=0.455 (val F1=0.2524)
  Directional -> Accuracy: 0.5493, MCC: 0.1698, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66473 | val 0.71058
  Epoch 020 - train 0.50931 | val 0.94545
  Epoch 029 - train 0.47586 | val 1.00278
  Classification -> best τ=0.395 (val F1=0.1886)
  Directional -> Accuracy: 0.5745, MCC: -0.0377, F1: 0.0909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65083 | val 0.88095
  Epoch 020 - train 0.58865 | val 0.83859
  Epoch 021 - train 0.56906 | val 0.83984
  Classification -> best τ=0.565 (val F1=0.3015)
  Directional -> Accuracy: 0.4651, MCC: -0.1076, F1: 0.3429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63718 | val 1.37420
  Epoch 020 - train 0.57205 | val 1.64114
  Epoch 021 - train 0.55214 | val 1.69138
  Classification -> best τ=0.320 (val F1=0.2068)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65014 | val 0.95392
  Epoch 020 - train 0.58667 | val 0.86413
  Epoch 021 - train 0.59117 | val 0.87829
  Classification -> best τ=0.450 (val F1=0.1337)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65624 | val 0.76836
  Epoch 020 - train 0.63704 | val 1.01268
  Epoch 025 - train 0.62658 | val 1.11634
  Classification -> best τ=0.450 (val F1=0.2593)
  Directional -> Accuracy: 0.6833, MCC: 0.3719, F1: 0.6545

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57380 | val 0.81426
  Epoch 020 - train 0.54597 | val 0.80076
  Epoch 021 - train 0.49671 | val 0.78794
  Classification -> best τ=0.500 (val F1=0.1868)
  Directional -> Accuracy: 0.5333, MCC: 0.0144, F1: 0.0870

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68732 | val 0.99850
  Epoch 020 - train 0.61624 | val 1.45209
  Epoch 025 - train 0.58313 | val 1.71582
  Classification -> best τ=0.825 (val F1=0.4152)
  Directional -> Accuracy: 0.5238, MCC: 0.0453, F1: 0.4643

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60869 | val 1.32922
  Epoch 020 - train 0.59318 | val 1.74253
  Epoch 021 - train 0.60539 | val 1.75316
  Classification -> best τ=0.535 (val F1=0.1884)
  Directional -> Accuracy: 0.4815, MCC: -0.1890, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63611 | val 1.05174
  Epoch 020 - train 0.58083 | val 1.09226
  Epoch 021 - train 0.59486 | val 1.12133
  Classification -> best τ=0.535 (val F1=0.4294)
  Directional -> Accuracy: 0.5417, MCC: 0.0555, F1: 0.6292

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64361 | val 1.42257
  Epoch 020 - train 0.60297 | val 1.60219
  Epoch 021 - train 0.65047 | val 1.64862
  Classification -> best τ=0.525 (val F1=0.0861)
  Directional -> Accuracy: 0.6066, MCC: 0.0402, F1: 0.7500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66032 | val 1.06980
  Epoch 020 - train 0.62972 | val 0.99083
  Epoch 021 - train 0.62361 | val 0.99718
  Classification -> best τ=0.570 (val F1=0.1541)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63675 | val 0.74370
  Epoch 020 - train 0.62658 | val 0.87029
  Epoch 027 - train 0.60141 | val 0.95859
  Classification -> best τ=0.430 (val F1=0.2500)
  Directional -> Accuracy: 0.4776, MCC: -0.0083, F1: 0.4615

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67398 | val 0.68252
  Epoch 020 - train 0.57492 | val 0.79932
  Epoch 029 - train 0.51683 | val 0.95180
  Classification -> best τ=0.400 (val F1=0.3619)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57247 | val 0.86281
  Epoch 020 - train 0.59677 | val 1.08563
  Epoch 021 - train 0.57096 | val 1.11018
  Classification -> best τ=0.520 (val F1=0.2191)
  Directional -> Accuracy: 0.5200, MCC: 0.0412, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66287 | val 0.70651
  Epoch 020 - train 0.65277 | val 0.71643
  Epoch 022 - train 0.64371 | val 0.72090
  Classification -> best τ=0.475 (val F1=0.3038)
  Directional -> Accuracy: 0.4559, MCC: -0.0902, F1: 0.5067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61514 | val 0.86839
  Epoch 020 - train 0.61095 | val 1.06470
  Epoch 021 - train 0.64120 | val 1.03977
  Classification -> best τ=0.605 (val F1=0.3117)
  Directional -> Accuracy: 0.5333, MCC: 0.1393, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62401 | val 0.71420
  Epoch 020 - train 0.59884 | val 0.72539
  Epoch 021 - train 0.60567 | val 0.73638
  Classification -> best τ=0.525 (val F1=0.1846)
  Directional -> Accuracy: 0.5441, MCC: 0.1054, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62111 | val 0.78500
  Epoch 020 - train 0.60734 | val 0.85891
  Epoch 022 - train 0.60352 | val 0.84943
  Classification -> best τ=0.590 (val F1=0.4865)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61436 | val 0.79327
  Epoch 020 - train 0.57905 | val 1.44022
  Epoch 021 - train 0.55034 | val 1.43852
  Classification -> best τ=0.540 (val F1=0.2106)
  Directional -> Accuracy: 0.6939, MCC: 0.3889, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64690 | val 0.69066
  Epoch 020 - train 0.63708 | val 0.69672
  Epoch 030 - train 0.60367 | val 0.68898
  Classification -> best τ=0.575 (val F1=0.2857)
  Directional -> Accuracy: 0.5111, MCC: 0.1814, F1: 0.3889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66510 | val 1.13559
  Epoch 020 - train 0.60153 | val 1.43073
  Epoch 021 - train 0.62764 | val 1.46706
  Classification -> best τ=0.460 (val F1=0.0752)
  Directional -> Accuracy: 0.5593, MCC: 0.0000, F1: 0.7174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60759 | val 1.17348
  Epoch 020 - train 0.57422 | val 1.90006
  Epoch 023 - train 0.60434 | val 1.95811
  Classification -> best τ=0.575 (val F1=0.3458)
  Directional -> Accuracy: 0.5455, MCC: 0.0981, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58550 | val 0.79387
  Epoch 020 - train 0.57070 | val 0.85581
  Epoch 021 - train 0.60555 | val 0.85005
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69383 | val 0.76316
  Epoch 020 - train 0.63868 | val 0.90167
  Epoch 028 - train 0.62323 | val 0.95971
  Classification -> best τ=0.665 (val F1=0.2853)
  Directional -> Accuracy: 0.5000, MCC: -0.0279, F1: 0.5818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58509 | val 0.90249
  Epoch 020 - train 0.53971 | val 1.07640
  Epoch 022 - train 0.57257 | val 1.04066
  Classification -> best τ=0.535 (val F1=0.1822)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61649 | val 0.80493
  Epoch 020 - train 0.57573 | val 0.93966
  Epoch 022 - train 0.58126 | val 0.99685
  Classification -> best τ=0.370 (val F1=0.3523)
  Directional -> Accuracy: 0.5200, MCC: 0.0991, F1: 0.4375

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65824 | val 0.75644
  Epoch 020 - train 0.61701 | val 0.77177
  Epoch 021 - train 0.59525 | val 0.77481
  Classification -> best τ=0.460 (val F1=0.1870)
  Directional -> Accuracy: 0.5610, MCC: 0.1407, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63869 | val 1.43304
  Epoch 020 - train 0.59852 | val 1.78578
  Epoch 021 - train 0.63585 | val 1.77625
  Classification -> best τ=0.685 (val F1=0.2326)
  Directional -> Accuracy: 0.6087, MCC: 0.2081, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63174 | val 0.71912
  Epoch 020 - train 0.60008 | val 0.68843
  Epoch 022 - train 0.62198 | val 0.68701
  Classification -> best τ=0.335 (val F1=0.3138)
  Directional -> Accuracy: 0.6377, MCC: 0.2467, F1: 0.6988

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61971 | val 0.93574
  Epoch 020 - train 0.58274 | val 1.01612
  Epoch 022 - train 0.58783 | val 1.03002
  Classification -> best τ=0.425 (val F1=0.2862)
  Directional -> Accuracy: 0.5778, MCC: 0.2222, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61380 | val 1.06099
  Epoch 020 - train 0.60173 | val 1.01428
  Epoch 021 - train 0.62195 | val 1.01176
  Classification -> best τ=0.405 (val F1=0.1730)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58076 | val 1.66794
  Epoch 020 - train 0.55123 | val 2.19640
  Epoch 021 - train 0.52367 | val 2.22221
  Classification -> best τ=0.505 (val F1=0.2032)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61372 | val 0.74810
  Epoch 020 - train 0.53647 | val 0.64632
  Epoch 027 - train 0.51310 | val 0.64205
  Classification -> best τ=0.395 (val F1=0.4647)
  Directional -> Accuracy: 0.4048, MCC: 0.1961, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67418 | val 1.13039
  Epoch 020 - train 0.56008 | val 0.99746
  Epoch 024 - train 0.52788 | val 0.88327
  Classification -> best τ=0.500 (val F1=0.3568)
  Directional -> Accuracy: 0.4878, MCC: -0.0176, F1: 0.4000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66118 | val 1.35607
  Epoch 020 - train 0.57675 | val 1.86024
  Epoch 021 - train 0.61628 | val 1.88345
  Classification -> best τ=0.525 (val F1=0.1913)
  Directional -> Accuracy: 0.5325, MCC: 0.1007, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67252 | val 0.92723
  Epoch 020 - train 0.65493 | val 1.18157
  Epoch 021 - train 0.61593 | val 1.16351
  Classification -> best τ=0.555 (val F1=0.5339)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57227 | val 1.57942
  Epoch 020 - train 0.57097 | val 1.80022
  Epoch 021 - train 0.49155 | val 1.85733
  Classification -> best τ=0.535 (val F1=0.5477)
  Directional -> Accuracy: 0.5319, MCC: 0.2001, F1: 0.3889

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63627 | val 0.79073
  Epoch 020 - train 0.56246 | val 0.78885
  Epoch 029 - train 0.50966 | val 0.94389
  Classification -> best τ=0.430 (val F1=0.3150)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71181 | val 0.74426
  Epoch 020 - train 0.65000 | val 0.79621
  Epoch 021 - train 0.66590 | val 0.79611
  Classification -> best τ=0.465 (val F1=0.2413)
  Directional -> Accuracy: 0.5345, MCC: 0.2769, F1: 0.2703

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62423 | val 1.26971
  Epoch 020 - train 0.59821 | val 1.55188
  Epoch 021 - train 0.59034 | val 1.55062
  Classification -> best τ=0.440 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65802 | val 1.24107
  Epoch 020 - train 0.60019 | val 1.58997
  Epoch 021 - train 0.61306 | val 1.61052
  Classification -> best τ=0.435 (val F1=0.1037)
  Directional -> Accuracy: 0.5893, MCC: 0.1895, F1: 0.7089

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-19 23:45:13,413] Trial 31 finished with value: 0.25783457737947535 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.002719408703481715, 'weight_decay': 0.00046960417753869185, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.2299975810091515, 'early_stopping_min_delta': 0.0007026516995952385}. Best is trial 22 with value: 0.26179994200866186.

  Classification -> best τ=0.470 (val F1=0.1658)
  Directional -> Accuracy: 0.4762, MCC: -0.0935, F1: 0.2326

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25783457737947535
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68065 | val 0.76990
  Epoch 020 - train 0.63862 | val 0.84978
  Epoch 021 - train 0.63104 | val 0.84790
  Classification -> best τ=0.640 (val F1=0.2346)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64640 | val 0.92143
  Epoch 020 - train 0.66931 | val 0.89993
  Epoch 021 - train 0.61844 | val 0.90891
  Classification -> best τ=0.470 (val F1=0.1260)
  Directional -> Accuracy: 0.6250, MCC: 0.2928, F1: 0.7500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.76225 | val 0.75086
  Epoch 020 - train 0.66429 | val 0.78703
  Epoch 025 - train 0.61719 | val 0.78469
  Classification -> best τ=0.310 (val F1=0.3182)
  Directional -> Accuracy: 0.5102, MCC: -0.0036, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67071 | val 0.76290
  Epoch 020 - train 0.64951 | val 0.74549
  Epoch 022 - train 0.67617 | val 0.73881
  Classification -> best τ=0.425 (val F1=0.1201)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64871 | val 1.38687
  Epoch 020 - train 0.62403 | val 2.37104
  Epoch 022 - train 0.61680 | val 2.36872
  Classification -> best τ=0.630 (val F1=0.3984)
  Directional -> Accuracy: 0.4906, MCC: 0.0247, F1: 0.2703

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65348 | val 0.68405
  Epoch 020 - train 0.58733 | val 0.68562
  Epoch 022 - train 0.55462 | val 0.68836
  Classification -> best τ=0.555 (val F1=0.2949)
  Directional -> Accuracy: 0.5610, MCC: 0.1322, F1: 0.5714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68254 | val 0.82738
  Epoch 020 - train 0.66722 | val 0.88018
  Epoch 021 - train 0.66632 | val 0.88967
  Classification -> best τ=0.395 (val F1=0.2582)
  Directional -> Accuracy: 0.4930, MCC: 0.1717, F1: 0.6000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.76731 | val 0.63592
  Epoch 020 - train 0.59399 | val 1.00963
  Epoch 028 - train 0.59828 | val 0.97355
  Classification -> best τ=0.470 (val F1=0.3043)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69917 | val 0.73867
  Epoch 020 - train 0.67153 | val 0.68880
  Epoch 030 - train 0.60931 | val 0.73138
  Classification -> best τ=0.575 (val F1=0.3015)
  Directional -> Accuracy: 0.6512, MCC: 0.2392, F1: 0.4828

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60846 | val 1.26912
  Epoch 020 - train 0.59030 | val 1.27288
  Epoch 021 - train 0.60747 | val 1.21292
  Classification -> best τ=0.360 (val F1=0.2208)
  Directional -> Accuracy: 0.4306, MCC: -0.0423, F1: 0.5773

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65879 | val 1.11909
  Epoch 020 - train 0.63202 | val 0.96755
  Epoch 021 - train 0.63495 | val 0.97546
  Classification -> best τ=0.570 (val F1=0.2037)
  Directional -> Accuracy: 0.6346, MCC: 0.3130, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68225 | val 0.80903
  Epoch 020 - train 0.65602 | val 0.84083
  Epoch 021 - train 0.62894 | val 0.85625
  Classification -> best τ=0.540 (val F1=0.2075)
  Directional -> Accuracy: 0.5333, MCC: 0.1336, F1: 0.1765

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64860 | val 0.74774
  Epoch 020 - train 0.61043 | val 0.77114
  Epoch 021 - train 0.60588 | val 0.76375
  Classification -> best τ=0.520 (val F1=0.1231)
  Directional -> Accuracy: 0.4667, MCC: -0.0598, F1: 0.4783

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67242 | val 0.72652
  Epoch 020 - train 0.67291 | val 0.93004
  Epoch 022 - train 0.64005 | val 0.96710
  Classification -> best τ=0.545 (val F1=0.4287)
  Directional -> Accuracy: 0.5397, MCC: 0.0778, F1: 0.4912

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66019 | val 2.34893
  Epoch 020 - train 0.61892 | val 2.64045
  Epoch 021 - train 0.64307 | val 2.64237
  Classification -> best τ=0.605 (val F1=0.2686)
  Directional -> Accuracy: 0.5556, MCC: 0.1520, F1: 0.2000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63644 | val 0.92654
  Epoch 020 - train 0.61565 | val 1.00967
  Epoch 021 - train 0.59805 | val 1.02350
  Classification -> best τ=0.355 (val F1=0.3173)
  Directional -> Accuracy: 0.5694, MCC: 0.1420, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67175 | val 1.69402
  Epoch 020 - train 0.64425 | val 1.88843
  Epoch 021 - train 0.66223 | val 1.89379
  Classification -> best τ=0.615 (val F1=0.0593)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66916 | val 1.15312
  Epoch 020 - train 0.67124 | val 1.18986
  Epoch 021 - train 0.64072 | val 1.19934
  Classification -> best τ=0.555 (val F1=0.1083)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67711 | val 0.68076
  Epoch 020 - train 0.62456 | val 0.77888
  Epoch 023 - train 0.63469 | val 0.77650
  Classification -> best τ=0.315 (val F1=0.3682)
  Directional -> Accuracy: 0.5224, MCC: -0.0237, F1: 0.6279

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62195 | val 0.70354
  Epoch 020 - train 0.61615 | val 0.72400
  Epoch 030 - train 0.60135 | val 0.71383
  Classification -> best τ=0.390 (val F1=0.3794)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62589 | val 0.76838
  Epoch 020 - train 0.64173 | val 0.88242
  Epoch 021 - train 0.61899 | val 0.87559
  Classification -> best τ=0.485 (val F1=0.1746)
  Directional -> Accuracy: 0.5800, MCC: 0.3047, F1: 0.5333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70034 | val 0.70657
  Epoch 020 - train 0.63713 | val 0.71298
  Epoch 023 - train 0.63240 | val 0.70695
  Classification -> best τ=0.670 (val F1=0.3086)
  Directional -> Accuracy: 0.4412, MCC: -0.1333, F1: 0.2692

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66274 | val 0.69688
  Epoch 020 - train 0.67475 | val 0.73593
  Epoch 021 - train 0.67117 | val 0.73634
  Classification -> best τ=0.545 (val F1=0.3130)
  Directional -> Accuracy: 0.4833, MCC: 0.2259, F1: 0.2051

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66190 | val 0.72730
  Epoch 020 - train 0.63617 | val 0.70899
  Epoch 021 - train 0.63834 | val 0.70850
  Classification -> best τ=0.540 (val F1=0.2044)
  Directional -> Accuracy: 0.4265, MCC: -0.1551, F1: 0.5412

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65609 | val 0.69628
  Epoch 020 - train 0.59863 | val 0.72621
  Epoch 025 - train 0.62202 | val 0.75679
  Classification -> best τ=0.525 (val F1=0.5270)
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66461 | val 0.71022
  Epoch 020 - train 0.58937 | val 1.20962
  Epoch 030 - train 0.56444 | val 0.98393
  Classification -> best τ=0.480 (val F1=0.3575)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72806 | val 0.70551
  Epoch 020 - train 0.64872 | val 0.73752
  Epoch 027 - train 0.64740 | val 0.72317
  Classification -> best τ=0.480 (val F1=0.1774)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65816 | val 0.98354
  Epoch 020 - train 0.62794 | val 1.10923
  Epoch 021 - train 0.65569 | val 1.11154
  Classification -> best τ=0.465 (val F1=0.2775)
  Directional -> Accuracy: 0.6102, MCC: 0.3346, F1: 0.5106

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69155 | val 1.43245
  Epoch 020 - train 0.67897 | val 1.95413
  Epoch 022 - train 0.57584 | val 1.92853
  Classification -> best τ=0.505 (val F1=0.1866)
  Directional -> Accuracy: 0.5682, MCC: 0.1727, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68954 | val 0.72354
  Epoch 020 - train 0.60659 | val 0.75540
  Epoch 021 - train 0.65534 | val 0.75378
  Classification -> best τ=0.505 (val F1=0.1172)
  Directional -> Accuracy: 0.5217, MCC: 0.0548, F1: 0.6333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.78103 | val 0.80073
  Epoch 020 - train 0.66121 | val 0.84333
  Epoch 023 - train 0.69285 | val 0.84426
  Classification -> best τ=0.510 (val F1=0.2227)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62961 | val 0.95084
  Epoch 020 - train 0.59005 | val 1.02728
  Epoch 022 - train 0.59949 | val 0.99640
  Classification -> best τ=0.475 (val F1=0.2540)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68205 | val 0.65748
  Epoch 020 - train 0.65601 | val 0.72355
  Epoch 022 - train 0.62600 | val 0.73953
  Classification -> best τ=0.430 (val F1=0.3259)
  Directional -> Accuracy: 0.5200, MCC: 0.1208, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73993 | val 0.71404
  Epoch 020 - train 0.64073 | val 0.71931
  Epoch 021 - train 0.64425 | val 0.72014
  Classification -> best τ=0.530 (val F1=0.0252)
  Directional -> Accuracy: 0.4634, MCC: -0.0853, F1: 0.3529

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65424 | val 1.31305
  Epoch 020 - train 0.61291 | val 1.40438
  Epoch 021 - train 0.63018 | val 1.40003
  Classification -> best τ=0.690 (val F1=0.2326)
  Directional -> Accuracy: 0.5217, MCC: -0.0022, F1: 0.3125

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67228 | val 0.67989
  Epoch 020 - train 0.63105 | val 0.69786
  Epoch 029 - train 0.62984 | val 0.70140
  Classification -> best τ=0.250 (val F1=0.2891)
  Directional -> Accuracy: 0.6087, MCC: 0.1628, F1: 0.7033

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71076 | val 1.01317
  Epoch 020 - train 0.65558 | val 0.98946
  Epoch 023 - train 0.59430 | val 0.92619
  Classification -> best τ=0.455 (val F1=0.2478)
  Directional -> Accuracy: 0.4667, MCC: -0.0950, F1: 0.0769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70167 | val 1.27216
  Epoch 020 - train 0.65951 | val 1.06388
  Epoch 021 - train 0.65503 | val 1.06419
  Classification -> best τ=0.475 (val F1=0.1713)
  Directional -> Accuracy: 0.5593, MCC: 0.1333, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60956 | val 1.96457
  Epoch 020 - train 0.57352 | val 2.17248
  Epoch 021 - train 0.58594 | val 2.19098
  Classification -> best τ=0.520 (val F1=0.2683)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70658 | val 0.68514
  Epoch 020 - train 0.62953 | val 0.77040
  Epoch 024 - train 0.60825 | val 0.75272
  Classification -> best τ=0.575 (val F1=0.3684)
  Directional -> Accuracy: 0.6667, MCC: 0.2236, F1: 0.4615

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71490 | val 0.69057
  Epoch 020 - train 0.59611 | val 0.62384
  Epoch 030 - train 0.54856 | val 0.62283
  Classification -> best τ=0.470 (val F1=0.5976)
  Directional -> Accuracy: 0.4878, MCC: -0.0195, F1: 0.4324

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64601 | val 1.16163
  Epoch 020 - train 0.64653 | val 1.38222
  Epoch 021 - train 0.63953 | val 1.35832
  Classification -> best τ=0.410 (val F1=0.1807)
  Directional -> Accuracy: 0.5195, MCC: 0.0561, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66329 | val 1.37855
  Epoch 020 - train 0.65821 | val 0.96861
  Epoch 021 - train 0.68422 | val 0.96610
  Classification -> best τ=0.495 (val F1=0.2385)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62647 | val 0.97775
  Epoch 020 - train 0.57185 | val 1.09149
  Epoch 021 - train 0.62389 | val 1.10041
  Classification -> best τ=0.520 (val F1=0.1936)
  Directional -> Accuracy: 0.4255, MCC: -0.0682, F1: 0.2286

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65896 | val 1.20409
  Epoch 020 - train 0.63677 | val 0.95543
  Epoch 021 - train 0.57592 | val 0.92739
  Classification -> best τ=0.570 (val F1=0.0392)
  Directional -> Accuracy: 0.6429, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66342 | val 0.68008
  Epoch 020 - train 0.66721 | val 0.71500
  Epoch 030 - train 0.62457 | val 0.68034
  Classification -> best τ=0.475 (val F1=0.2249)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63700 | val 1.23866
  Epoch 020 - train 0.65643 | val 1.57821
  Epoch 021 - train 0.65234 | val 1.54384
  Classification -> best τ=0.630 (val F1=0.3033)
  Directional -> Accuracy: 0.5763, MCC: 0.2559, F1: 0.6914

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67509 | val 1.51460
  Epoch 020 - train 0.63456 | val 1.56900
  Epoch 021 - train 0.64173 | val 1.56201
  Classification -> best τ=0.425 (val F1=0.1244)
  Directional -> Accuracy: 0.5714, MCC: 0.1406, F1: 0.7000

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-19 23:47:17,919] Trial 32 finished with value: 0.24570746480032024 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.002386203752529449, 'weight_decay': 0.0005714545271265733, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.2753233717977723, 'early_stopping_min_delta': 0.0004869591406871527}. Best is trial 22 with value: 0.26179994200866186.

  Classification -> best τ=0.550 (val F1=0.1586)
  Directional -> Accuracy: 0.6032, MCC: 0.2045, F1: 0.4898

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24570746480032024
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69222 | val 0.83703
  Epoch 020 - train 0.55903 | val 2.09684
  Epoch 024 - train 0.57030 | val 1.97705
  Classification -> best τ=0.640 (val F1=0.2863)
  Directional -> Accuracy: 0.5513, MCC: 0.0349, F1: 0.1860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56244 | val 0.76104
  Epoch 020 - train 0.48550 | val 0.83478
  Epoch 021 - train 0.45041 | val 0.83030
  Classification -> best τ=0.580 (val F1=0.2346)
  Directional -> Accuracy: 0.6170, MCC: 0.2541, F1: 0.6087

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67649 | val 1.02781
  Epoch 020 - train 0.47750 | val 1.73316
  Epoch 026 - train 0.41191 | val 2.28065
  Classification -> best τ=0.375 (val F1=0.3170)
  Directional -> Accuracy: 0.5417, MCC: 0.0174, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63851 | val 0.89482
  Epoch 020 - train 0.59804 | val 1.07258
  Epoch 021 - train 0.58449 | val 0.99315
  Classification -> best τ=0.335 (val F1=0.1898)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57772 | val 1.48015
  Epoch 020 - train 0.39882 | val 2.23614
  Epoch 024 - train 0.37971 | val 2.49749
  Classification -> best τ=0.630 (val F1=0.4574)
  Directional -> Accuracy: 0.6538, MCC: 0.3665, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54547 | val 2.76330
  Epoch 020 - train 0.43648 | val 3.30367
  Epoch 021 - train 0.45190 | val 3.33752
  Classification -> best τ=0.665 (val F1=0.3081)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61273 | val 1.07514
  Epoch 020 - train 0.56883 | val 1.20485
  Epoch 021 - train 0.54647 | val 1.21670
  Classification -> best τ=0.610 (val F1=0.1108)
  Directional -> Accuracy: 0.5571, MCC: 0.0497, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57819 | val 3.05361
  Epoch 020 - train 0.44650 | val 1.80257
  Epoch 021 - train 0.41565 | val 1.86300
  Classification -> best τ=0.605 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60716 | val 1.27462
  Epoch 020 - train 0.50171 | val 1.47048
  Epoch 023 - train 0.45880 | val 1.68587
  Classification -> best τ=0.715 (val F1=0.4523)
  Directional -> Accuracy: 0.6667, MCC: 0.2774, F1: 0.5333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59506 | val 1.65619
  Epoch 020 - train 0.49356 | val 2.27681
  Epoch 021 - train 0.49785 | val 2.34328
  Classification -> best τ=0.430 (val F1=0.1072)
  Directional -> Accuracy: 0.4648, MCC: 0.0443, F1: 0.5957

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64406 | val 0.65445
  Epoch 020 - train 0.51668 | val 0.71242
  Epoch 030 - train 0.33930 | val 0.77251
  Classification -> best τ=0.385 (val F1=0.2451)
  Directional -> Accuracy: 0.4706, MCC: -0.0650, F1: 0.4255

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66379 | val 0.85613
  Epoch 020 - train 0.57899 | val 0.98703
  Epoch 022 - train 0.55238 | val 1.02639
  Classification -> best τ=0.720 (val F1=0.2518)
  Directional -> Accuracy: 0.5254, MCC: 0.1842, F1: 0.1250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50846 | val 2.93571
  Epoch 020 - train 0.41755 | val 4.56048
  Epoch 022 - train 0.40367 | val 4.60668
  Classification -> best τ=0.520 (val F1=0.1793)
  Directional -> Accuracy: 0.5000, MCC: -0.0083, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64275 | val 0.74246
  Epoch 020 - train 0.48725 | val 0.79782
  Epoch 026 - train 0.42194 | val 0.97279
  Classification -> best τ=0.210 (val F1=0.2949)
  Directional -> Accuracy: 0.5161, MCC: 0.1280, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63501 | val 1.05163
  Epoch 020 - train 0.42076 | val 0.91061
  Epoch 026 - train 0.37213 | val 1.01051
  Classification -> best τ=0.605 (val F1=0.2193)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60313 | val 1.19000
  Epoch 020 - train 0.53040 | val 1.65283
  Epoch 021 - train 0.49461 | val 1.68340
  Classification -> best τ=0.795 (val F1=0.1797)
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64609 | val 0.78070
  Epoch 020 - train 0.52004 | val 1.10608
  Epoch 022 - train 0.51685 | val 1.17348
  Classification -> best τ=0.680 (val F1=0.1753)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65406 | val 1.59841
  Epoch 020 - train 0.56195 | val 2.10351
  Epoch 021 - train 0.52861 | val 2.19229
  Classification -> best τ=0.345 (val F1=0.1193)
  Directional -> Accuracy: 0.5844, MCC: -0.0102, F1: 0.7241

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60978 | val 1.01303
  Epoch 020 - train 0.53852 | val 1.21309
  Epoch 021 - train 0.53648 | val 1.17642
  Classification -> best τ=0.515 (val F1=0.2142)
  Directional -> Accuracy: 0.3939, MCC: -0.1594, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56377 | val 0.87637
  Epoch 020 - train 0.46452 | val 1.42871
  Epoch 021 - train 0.46023 | val 1.35057
  Classification -> best τ=0.550 (val F1=0.2661)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62380 | val 0.75797
  Epoch 020 - train 0.49480 | val 1.31460
  Epoch 025 - train 0.43860 | val 1.39868
  Classification -> best τ=0.595 (val F1=0.4014)
  Directional -> Accuracy: 0.4082, MCC: 0.1572, F1: 0.1212

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65085 | val 1.38538
  Epoch 020 - train 0.60469 | val 1.70953
  Epoch 021 - train 0.62610 | val 1.69847
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60477 | val 2.25572
  Epoch 020 - train 0.53163 | val 3.16349
  Epoch 021 - train 0.50157 | val 3.00371
  Classification -> best τ=0.705 (val F1=0.2095)
  Directional -> Accuracy: 0.5763, MCC: 0.1023, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63306 | val 0.69086
  Epoch 020 - train 0.53615 | val 0.69503
  Epoch 027 - train 0.40570 | val 0.70258
  Classification -> best τ=0.560 (val F1=0.1921)
  Directional -> Accuracy: 0.5224, MCC: 0.0483, F1: 0.5294

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56768 | val 1.41984
  Epoch 020 - train 0.43195 | val 1.06075
  Epoch 021 - train 0.46033 | val 1.12061
  Classification -> best τ=0.495 (val F1=0.2626)
  Directional -> Accuracy: 0.5088, MCC: 0.0025, F1: 0.5625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53642 | val 1.65956
  Epoch 020 - train 0.49137 | val 2.80136
  Epoch 021 - train 0.45620 | val 2.79764
  Classification -> best τ=0.570 (val F1=0.2854)
  Directional -> Accuracy: 0.4792, MCC: -0.0352, F1: 0.4444

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62749 | val 1.27119
  Epoch 020 - train 0.53604 | val 1.62530
  Epoch 021 - train 0.55585 | val 1.59182
  Classification -> best τ=0.430 (val F1=0.1663)
  Directional -> Accuracy: 0.5000, MCC: 0.0342, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59566 | val 1.07415
  Epoch 020 - train 0.45086 | val 1.76304
  Epoch 021 - train 0.45045 | val 1.81425
  Classification -> best τ=0.390 (val F1=0.1867)
  Directional -> Accuracy: 0.5517, MCC: 0.1434, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55109 | val 0.98974
  Epoch 020 - train 0.48313 | val 0.77825
  Epoch 021 - train 0.48452 | val 0.78018
  Classification -> best τ=0.550 (val F1=0.3118)
  Directional -> Accuracy: 0.6047, MCC: 0.1983, F1: 0.6792

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59068 | val 1.24389
  Epoch 020 - train 0.44753 | val 1.16305
  Epoch 023 - train 0.43117 | val 1.16968
  Classification -> best τ=0.550 (val F1=0.2712)
  Directional -> Accuracy: 0.4222, MCC: -0.2200, F1: 0.0714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62032 | val 0.88165
  Epoch 020 - train 0.47862 | val 0.98823
  Epoch 021 - train 0.44080 | val 1.10739
  Classification -> best τ=0.450 (val F1=0.2390)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56351 | val 1.24785
  Epoch 020 - train 0.39669 | val 1.89126
  Epoch 021 - train 0.37137 | val 1.88558
  Classification -> best τ=0.500 (val F1=0.1635)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63439 | val 0.76574
  Epoch 020 - train 0.50908 | val 1.09539
  Epoch 022 - train 0.48037 | val 1.11044
  Classification -> best τ=0.370 (val F1=0.2241)
  Directional -> Accuracy: 0.5541, MCC: 0.2008, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51256 | val 1.13409
  Epoch 020 - train 0.40024 | val 0.94692
  Epoch 025 - train 0.44872 | val 1.15387
  Classification -> best τ=0.490 (val F1=0.2326)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53592 | val 1.75875
  Epoch 020 - train 0.43433 | val 2.62428
  Epoch 021 - train 0.42956 | val 2.49009
  Classification -> best τ=0.440 (val F1=0.1410)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54523 | val 1.19332
  Epoch 020 - train 0.44978 | val 1.50566
  Epoch 021 - train 0.44482 | val 1.47279
  Classification -> best τ=0.110 (val F1=0.1966)
  Directional -> Accuracy: 0.4853, MCC: 0.0577, F1: 0.3636

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59116 | val 1.53229
  Epoch 020 - train 0.39739 | val 3.13227
  Epoch 025 - train 0.39451 | val 3.46568
  Classification -> best τ=0.705 (val F1=0.2533)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60351 | val 1.04420
  Epoch 020 - train 0.53203 | val 1.60864
  Epoch 026 - train 0.48701 | val 1.77211
  Classification -> best τ=0.160 (val F1=0.1645)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48856 | val 3.92299
  Epoch 020 - train 0.36250 | val 5.38408
  Epoch 021 - train 0.35045 | val 5.31641
  Classification -> best τ=0.600 (val F1=0.2799)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54662 | val 1.42568
  Epoch 020 - train 0.42356 | val 2.61371
  Epoch 021 - train 0.43627 | val 2.61134
  Classification -> best τ=0.390 (val F1=0.1391)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51875 | val 1.06891
  Epoch 020 - train 0.45352 | val 0.95039
  Epoch 021 - train 0.44812 | val 0.94882
  Classification -> best τ=0.480 (val F1=0.2548)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58856 | val 1.87731
  Epoch 020 - train 0.47623 | val 3.87426
  Epoch 021 - train 0.48409 | val 4.04707
  Classification -> best τ=0.535 (val F1=0.1801)
  Directional -> Accuracy: 0.5263, MCC: 0.1179, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60155 | val 2.97107
  Epoch 020 - train 0.46104 | val 3.64742
  Epoch 024 - train 0.41786 | val 3.99491
  Classification -> best τ=0.410 (val F1=0.2236)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48469 | val 2.42777
  Epoch 020 - train 0.41533 | val 2.95156
  Epoch 021 - train 0.40227 | val 2.86897
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52867 | val 2.31109
  Epoch 020 - train 0.41657 | val 2.56913
  Epoch 021 - train 0.40535 | val 2.53883
  Classification -> best τ=0.500 (val F1=0.1078)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63231 | val 1.08499
  Epoch 020 - train 0.58627 | val 1.16595
  Epoch 021 - train 0.58003 | val 1.15770
  Classification -> best τ=0.525 (val F1=0.0377)
  Directional -> Accuracy: 0.4386, MCC: -0.1248, F1: 0.4667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57282 | val 3.23463
  Epoch 020 - train 0.44475 | val 3.36321
  Epoch 021 - train 0.41708 | val 3.32353
  Classification -> best τ=0.710 (val F1=0.3886)
  Directional -> Accuracy: 0.5172, MCC: 0.0476, F1: 0.5758

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62178 | val 1.18094
  Epoch 020 - train 0.55627 | val 1.55202
  Epoch 021 - train 0.54952 | val 1.54561
  Classification -> best τ=0.405 (val F1=0.2257)
  Directional -> Accuracy: 0.5636, MCC: 0.1555, F1: 0.7000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56386 | val 0.71090

[I 2026-02-19 23:50:30,362] Trial 33 finished with value: 0.22128704775691033 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.005511460419748441, 'weight_decay': 8.17442238076536e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.428595863200168, 'early_stopping_min_delta': 0.0013910741944034338}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 028 - train 0.44580 | val 0.92050
  Classification -> best τ=0.465 (val F1=0.3383)
  Directional -> Accuracy: 0.5806, MCC: 0.1784, F1: 0.6286

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22128704775691033
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67915 | val 0.89997
  Epoch 020 - train 0.65981 | val 0.98284
  Classification -> best τ=0.620 (val F1=0.2136)
  Directional -> Accuracy: 0.5190, MCC: -0.0792, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64839 | val 0.88083
  Epoch 020 - train 0.61807 | val 0.89777
  Classification -> best τ=0.535 (val F1=0.2364)
  Directional -> Accuracy: 0.6042, MCC: 0.1782, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68352 | val 0.74463
  Epoch 020 - train 0.66018 | val 0.76545
  Classification -> best τ=0.610 (val F1=0.2368)
  Directional -> Accuracy: 0.4694, MCC: -0.0183, F1: 0.1333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67566 | val 0.71496
  Epoch 020 - train 0.66584 | val 0.70826
  Classification -> best τ=0.580 (val F1=0.0645)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67199 | val 1.31546
  Epoch 020 - train 0.64869 | val 1.60648
  Classification -> best τ=0.595 (val F1=0.3686)
  Directional -> Accuracy: 0.6604, MCC: 0.3457, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66524 | val 0.71057
  Epoch 020 - train 0.61096 | val 0.70198
  Classification -> best τ=0.545 (val F1=0.2032)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71575 | val 0.81367
  Epoch 020 - train 0.64250 | val 0.98032
  Classification -> best τ=0.435 (val F1=0.1982)
  Directional -> Accuracy: 0.5211, MCC: 0.1958, F1: 0.6047

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64021 | val 0.87839
  Epoch 020 - train 0.58137 | val 0.89573
  Classification -> best τ=0.225 (val F1=0.1581)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68691 | val 0.92224
  Epoch 020 - train 0.63858 | val 0.83605
  Classification -> best τ=0.495 (val F1=0.2973)
  Directional -> Accuracy: 0.6512, MCC: 0.2323, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63354 | val 1.42251
  Epoch 020 - train 0.60121 | val 1.40753
  Classification -> best τ=0.400 (val F1=0.2663)
  Directional -> Accuracy: 0.4583, MCC: 0.0592, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64526 | val 0.79922
  Epoch 020 - train 0.62939 | val 0.83269
  Classification -> best τ=0.560 (val F1=0.1325)
  Directional -> Accuracy: 0.5000, MCC: -0.0120, F1: 0.4348

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69762 | val 0.75971
  Epoch 020 - train 0.63698 | val 0.83998
  Classification -> best τ=0.505 (val F1=0.1116)
  Directional -> Accuracy: 0.6500, MCC: 0.3043, F1: 0.6182

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62681 | val 0.71157
  Epoch 020 - train 0.59952 | val 0.66671
  Classification -> best τ=0.620 (val F1=0.2202)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68362 | val 0.70214
  Epoch 020 - train 0.63489 | val 0.69667
  Classification -> best τ=0.600 (val F1=0.4287)
  Directional -> Accuracy: 0.5397, MCC: 0.0782, F1: 0.4528

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63177 | val 2.57752
  Epoch 020 - train 0.64691 | val 2.54537
  Classification -> best τ=0.515 (val F1=0.1430)
  Directional -> Accuracy: 0.5741, MCC: 0.1459, F1: 0.5490

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64762 | val 0.99543
  Epoch 020 - train 0.59843 | val 1.16470
  Classification -> best τ=0.510 (val F1=0.1896)
  Directional -> Accuracy: 0.5694, MCC: 0.1349, F1: 0.5974

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67347 | val 2.08407
  Epoch 020 - train 0.63966 | val 2.26679
  Classification -> best τ=0.560 (val F1=0.1189)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64480 | val 0.86795
  Epoch 020 - train 0.64191 | val 0.96529
  Classification -> best τ=0.535 (val F1=0.1541)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65040 | val 0.83520
  Epoch 020 - train 0.62341 | val 0.81047
  Classification -> best τ=0.395 (val F1=0.2741)
  Directional -> Accuracy: 0.5672, MCC: 0.0531, F1: 0.6813

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62496 | val 0.78070
  Epoch 020 - train 0.62477 | val 0.80659
  Classification -> best τ=0.335 (val F1=0.2406)
  Directional -> Accuracy: 0.5195, MCC: 0.0760, F1: 0.4478

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64791 | val 0.77945
  Epoch 020 - train 0.62707 | val 0.78538
  Classification -> best τ=0.525 (val F1=0.2065)
  Directional -> Accuracy: 0.5600, MCC: 0.2140, F1: 0.5417

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67817 | val 0.68743
  Epoch 020 - train 0.68629 | val 0.70286
  Classification -> best τ=0.600 (val F1=0.2315)
  Directional -> Accuracy: 0.5147, MCC: 0.0318, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67820 | val 0.79826
  Epoch 020 - train 0.64014 | val 0.87427
  Classification -> best τ=0.685 (val F1=0.3446)
  Directional -> Accuracy: 0.4500, MCC: 0.0331, F1: 0.2326

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66287 | val 0.76355
  Epoch 020 - train 0.63785 | val 0.73980
  Classification -> best τ=0.395 (val F1=0.1459)
  Directional -> Accuracy: 0.5588, MCC: 0.1868, F1: 0.6667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67184 | val 0.65590
  Epoch 020 - train 0.63607 | val 0.69406
  Classification -> best τ=0.625 (val F1=0.4947)
  Directional -> Accuracy: 0.5172, MCC: 0.1180, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63709 | val 0.76142
  Epoch 020 - train 0.62615 | val 0.73745
  Classification -> best τ=0.480 (val F1=0.3330)
  Directional -> Accuracy: 0.4694, MCC: -0.0360, F1: 0.4800

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68027 | val 0.98513
  Epoch 020 - train 0.64548 | val 0.93255
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70019 | val 0.90678
  Epoch 020 - train 0.67602 | val 0.98382
  Classification -> best τ=0.325 (val F1=0.1985)
  Directional -> Accuracy: 0.5424, MCC: 0.1941, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62668 | val 1.24168
  Epoch 020 - train 0.54206 | val 1.48495
  Classification -> best τ=0.480 (val F1=0.2345)
  Directional -> Accuracy: 0.5455, MCC: 0.1113, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67098 | val 0.82230
  Epoch 020 - train 0.60918 | val 0.76395
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67995 | val 0.78386
  Epoch 020 - train 0.66773 | val 0.78749
  Classification -> best τ=0.435 (val F1=0.2059)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60690 | val 0.89823
  Epoch 020 - train 0.58528 | val 1.03807
  Classification -> best τ=0.470 (val F1=0.2384)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66386 | val 0.68005
  Epoch 020 - train 0.63885 | val 0.75530
  Classification -> best τ=0.395 (val F1=0.3290)
  Directional -> Accuracy: 0.5733, MCC: 0.2171, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68582 | val 0.69395
  Epoch 020 - train 0.66147 | val 0.71415
  Classification -> best τ=0.520 (val F1=0.3427)
  Directional -> Accuracy: 0.5366, MCC: 0.2210, F1: 0.6780

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66766 | val 1.01518
  Epoch 020 - train 0.61391 | val 1.05177
  Classification -> best τ=0.575 (val F1=0.2326)
  Directional -> Accuracy: 0.6304, MCC: 0.2930, F1: 0.3704

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65825 | val 0.69487
  Epoch 020 - train 0.62956 | val 0.71085
  Classification -> best τ=0.420 (val F1=0.3271)
  Directional -> Accuracy: 0.5652, MCC: 0.0495, F1: 0.6809

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68405 | val 0.73636
  Epoch 020 - train 0.60595 | val 0.75007
  Classification -> best τ=0.485 (val F1=0.2980)
  Directional -> Accuracy: 0.5556, MCC: 0.1257, F1: 0.4737

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67241 | val 0.94400
  Epoch 020 - train 0.61272 | val 0.98903
  Classification -> best τ=0.465 (val F1=0.1713)
  Directional -> Accuracy: 0.5763, MCC: 0.1448, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59098 | val 2.16810
  Epoch 020 - train 0.60655 | val 2.54397
  Classification -> best τ=0.530 (val F1=0.2373)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64714 | val 0.64077
  Epoch 020 - train 0.60028 | val 0.72973
  Classification -> best τ=0.270 (val F1=0.4142)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67544 | val 0.78070
  Epoch 020 - train 0.55856 | val 0.63225
  Classification -> best τ=0.355 (val F1=0.4801)
  Directional -> Accuracy: 0.4390, MCC: -0.1199, F1: 0.4103

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65821 | val 1.23439
  Epoch 020 - train 0.60380 | val 1.52270
  Classification -> best τ=0.530 (val F1=0.1807)
  Directional -> Accuracy: 0.5325, MCC: 0.0735, F1: 0.6471

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67987 | val 0.82413
  Epoch 020 - train 0.64577 | val 0.83677
  Classification -> best τ=0.580 (val F1=0.2953)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65342 | val 0.92623
  Epoch 020 - train 0.59999 | val 1.07220
  Classification -> best τ=0.500 (val F1=0.4750)
  Directional -> Accuracy: 0.5106, MCC: 0.0312, F1: 0.5306

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62145 | val 0.87404
  Epoch 020 - train 0.61292 | val 0.74703
  Classification -> best τ=0.565 (val F1=0.4219)
  Directional -> Accuracy: 0.3571, MCC: -0.1446, F1: 0.4490

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72214 | val 0.68575
  Epoch 020 - train 0.67007 | val 0.67430
  Classification -> best τ=0.465 (val F1=0.2186)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66914 | val 1.86878
  Epoch 020 - train 0.60445 | val 1.68153
  Classification -> best τ=0.670 (val F1=0.3257)
  Directional -> Accuracy: 0.5763, MCC: 0.1848, F1: 0.6575

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65159 | val 2.01571
  Epoch 020 - train 0.62186 | val 2.18281
  Classification -> best τ=0.515 (val F1=0.1211)
  Directional -> Accuracy: 0.5536, MCC: 0.1049, F1: 0.5763

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63473 | val 2.19684
  Epoch 020 - train 0.66092 | val 2.46903
  Classification -> best τ=0.530 (val F1=0.1743)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68813 | val 1.30771

[I 2026-02-19 23:52:21,513] Trial 34 finished with value: 0.24369365392717068 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.001326468572634198, 'weight_decay': 0.00023986567471518305, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.8114056012995874, 'early_stopping_min_delta': 5.030384057039299e-05}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 020 - train 0.64891 | val 1.21876
  Classification -> best τ=0.575 (val F1=0.2500)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24369365392717068
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67117 | val 0.85000
  Epoch 017 - train 0.53313 | val 1.98462
  Classification -> best τ=0.820 (val F1=0.2463)
  Directional -> Accuracy: 0.5128, MCC: -0.0838, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58036 | val 0.70977
  Epoch 012 - train 0.61369 | val 0.73100
  Classification -> best τ=0.450 (val F1=0.2905)
  Directional -> Accuracy: 0.5957, MCC: 0.1602, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66376 | val 0.72286
  Epoch 013 - train 0.63653 | val 0.76098
  Classification -> best τ=0.660 (val F1=0.2402)
  Directional -> Accuracy: 0.5000, MCC: 0.0601, F1: 0.3333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65096 | val 0.81468
  Epoch 011 - train 0.62961 | val 0.83006
  Classification -> best τ=0.390 (val F1=0.1771)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60169 | val 1.04088
  Epoch 014 - train 0.51839 | val 1.39110
  Classification -> best τ=0.590 (val F1=0.4973)
  Directional -> Accuracy: 0.6731, MCC: 0.4192, F1: 0.6047

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54767 | val 2.14249
  Epoch 011 - train 0.48839 | val 2.31478
  Classification -> best τ=0.625 (val F1=0.3118)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65589 | val 1.04963
  Epoch 011 - train 0.61245 | val 1.02731
  Classification -> best τ=0.365 (val F1=0.1732)
  Directional -> Accuracy: 0.3857, MCC: -0.1474, F1: 0.5567

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62840 | val 2.04608
  Epoch 011 - train 0.62428 | val 2.00945
  Classification -> best τ=0.515 (val F1=0.1890)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62683 | val 0.73099
  Epoch 014 - train 0.55563 | val 0.93780
  Classification -> best τ=0.645 (val F1=0.5735)
  Directional -> Accuracy: 0.5476, MCC: -0.0512, F1: 0.2400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59899 | val 2.79181
  Epoch 011 - train 0.57365 | val 2.66978
  Classification -> best τ=0.355 (val F1=0.2254)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61334 | val 1.12882
  Epoch 015 - train 0.58524 | val 0.99096
  Classification -> best τ=0.695 (val F1=0.2622)
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65281 | val 0.71893
  Epoch 020 - train 0.63932 | val 0.79398
  Epoch 025 - train 0.57115 | val 0.71336
  Classification -> best τ=0.560 (val F1=0.3124)
  Directional -> Accuracy: 0.6780, MCC: 0.3702, F1: 0.7246

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56386 | val 1.61272
  Epoch 011 - train 0.56580 | val 1.88842
  Classification -> best τ=0.365 (val F1=0.2310)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70449 | val 0.65520
  Epoch 015 - train 0.64213 | val 0.75689
  Classification -> best τ=0.225 (val F1=0.3050)
  Directional -> Accuracy: 0.5806, MCC: 0.2548, F1: 0.6977

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60661 | val 1.57355
  Epoch 012 - train 0.57881 | val 1.54362
  Classification -> best τ=0.755 (val F1=0.2712)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62952 | val 1.12096
  Epoch 011 - train 0.60973 | val 1.11380
  Classification -> best τ=0.665 (val F1=0.2266)
  Directional -> Accuracy: 0.5211, MCC: 0.0454, F1: 0.5278

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62910 | val 0.96606
  Epoch 011 - train 0.62745 | val 1.00804
  Classification -> best τ=0.690 (val F1=0.1368)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63266 | val 2.13441
  Epoch 011 - train 0.59765 | val 2.53518
  Classification -> best τ=0.080 (val F1=0.2053)
  Directional -> Accuracy: 0.6104, MCC: 0.1341, F1: 0.7115

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61113 | val 0.94867
  Epoch 011 - train 0.59736 | val 1.08433
  Classification -> best τ=0.515 (val F1=0.2435)
  Directional -> Accuracy: 0.4091, MCC: -0.0327, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57831 | val 1.19846
  Epoch 014 - train 0.51354 | val 1.10027
  Classification -> best τ=0.440 (val F1=0.2594)
  Directional -> Accuracy: 0.3553, MCC: -0.2800, F1: 0.3099

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59384 | val 0.95885
  Epoch 011 - train 0.55149 | val 1.02589
  Classification -> best τ=0.405 (val F1=0.2193)
  Directional -> Accuracy: 0.6327, MCC: 0.0820, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62846 | val 1.75433
  Epoch 011 - train 0.64720 | val 1.88372
  Classification -> best τ=0.635 (val F1=0.1834)
  Directional -> Accuracy: 0.4776, MCC: -0.1249, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63790 | val 1.14452
  Epoch 011 - train 0.60267 | val 1.40520
  Classification -> best τ=0.620 (val F1=0.2743)
  Directional -> Accuracy: 0.5254, MCC: 0.1068, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62194 | val 0.69017
  Epoch 011 - train 0.59414 | val 0.68843
  Classification -> best τ=0.445 (val F1=0.2562)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57362 | val 0.94842
  Epoch 011 - train 0.56184 | val 1.04298
  Classification -> best τ=0.545 (val F1=0.4222)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62280 | val 1.99081
  Epoch 011 - train 0.57752 | val 2.26621
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61530 | val 1.43185
  Epoch 011 - train 0.62496 | val 1.67482
  Classification -> best τ=0.370 (val F1=0.1676)
  Directional -> Accuracy: 0.3409, MCC: -0.2700, F1: 0.1212

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62082 | val 1.00122
  Epoch 011 - train 0.62264 | val 1.02354
  Classification -> best τ=0.445 (val F1=0.2435)
  Directional -> Accuracy: 0.6034, MCC: 0.1802, F1: 0.6933

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57085 | val 0.79524
  Epoch 017 - train 0.48913 | val 1.01251
  Classification -> best τ=0.625 (val F1=0.3344)
  Directional -> Accuracy: 0.4884, MCC: 0.0124, F1: 0.3529

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64744 | val 0.94360
  Epoch 011 - train 0.58097 | val 0.95024
  Classification -> best τ=0.530 (val F1=0.2982)
  Directional -> Accuracy: 0.4667, MCC: -0.0653, F1: 0.4545

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64389 | val 0.86061
  Epoch 011 - train 0.63624 | val 0.89635
  Classification -> best τ=0.510 (val F1=0.1581)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59365 | val 0.91607
  Epoch 012 - train 0.58543 | val 1.08406
  Classification -> best τ=0.535 (val F1=0.2822)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63337 | val 0.91827
  Epoch 013 - train 0.59301 | val 1.23073
  Classification -> best τ=0.735 (val F1=0.2355)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65489 | val 0.87991
  Epoch 011 - train 0.61036 | val 0.87455
  Classification -> best τ=0.520 (val F1=0.2550)
  Directional -> Accuracy: 0.5641, MCC: 0.1326, F1: 0.5854

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61291 | val 1.66019
  Epoch 011 - train 0.56540 | val 1.74223
  Classification -> best τ=0.670 (val F1=0.1774)
  Directional -> Accuracy: 0.5556, MCC: 0.1195, F1: 0.5652

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55403 | val 1.06877
  Epoch 011 - train 0.54839 | val 1.16620
  Classification -> best τ=0.335 (val F1=0.1468)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65568 | val 1.05620
  Epoch 011 - train 0.62533 | val 1.24348
  Classification -> best τ=0.605 (val F1=0.2533)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63223 | val 1.14258
  Epoch 011 - train 0.63399 | val 1.01380
  Classification -> best τ=0.415 (val F1=0.3743)
  Directional -> Accuracy: 0.4828, MCC: -0.0014, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53780 | val 2.62861
  Epoch 011 - train 0.52236 | val 2.89474
  Classification -> best τ=0.795 (val F1=0.2816)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62719 | val 1.08412
  Epoch 013 - train 0.52123 | val 0.97873
  Classification -> best τ=0.460 (val F1=0.5164)
  Directional -> Accuracy: 0.6250, MCC: 0.0759, F1: 0.2857

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57790 | val 1.08813
  Epoch 011 - train 0.62262 | val 1.09807
  Classification -> best τ=0.440 (val F1=0.1762)
  Directional -> Accuracy: 0.5385, MCC: 0.0392, F1: 0.6538

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61142 | val 2.09094
  Epoch 011 - train 0.59149 | val 2.45664
  Classification -> best τ=0.485 (val F1=0.1801)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61155 | val 0.73958
  Epoch 012 - train 0.61062 | val 0.75150
  Classification -> best τ=0.480 (val F1=0.2777)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58024 | val 1.89416
  Epoch 011 - train 0.57848 | val 1.98578
  Classification -> best τ=0.490 (val F1=0.1387)
  Directional -> Accuracy: 0.5778, MCC: 0.1156, F1: 0.6780

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58042 | val 1.54285
  Epoch 011 - train 0.60733 | val 1.44785
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63382 | val 1.60683
  Epoch 011 - train 0.64374 | val 1.63347
  Classification -> best τ=0.405 (val F1=0.1685)
  Directional -> Accuracy: 0.5439, MCC: 0.0168, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61413 | val 1.47171
  Epoch 012 - train 0.56458 | val 1.70452
  Classification -> best τ=0.615 (val F1=0.3627)
  Directional -> Accuracy: 0.4828, MCC: -0.0176, F1: 0.5946

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64704 | val 0.77445
  Epoch 011 - train 0.65665 | val 0.85958
  Classification -> best τ=0.475 (val F1=0.1771)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63255 | val 0.78801
  Epoch 011 - train 0.59030 | val 0.77809
  Classification -> best τ=0.600 (val F1=0.2157)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-19 23:53:03,631] Trial 35 finished with value: 0.24636027870394298 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.006160091605990103, 'weight_decay': 2.1744214192149238e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.3336205845545619, 'early_stopping_min_delta': 0.0012855190898212465}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 010 - train 0.67655 | val 1.37756
  Epoch 011 - train 0.64142 | val 1.46825
  Classification -> best τ=0.425 (val F1=0.1641)
  Directional -> Accuracy: 0.3871, MCC: -0.2250, F1: 0.3871

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24636027870394298
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62928 | val 0.74585
  Epoch 020 - train 0.63017 | val 0.89864
  Epoch 026 - train 0.61556 | val 0.97935
  Classification -> best τ=0.405 (val F1=0.1307)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62239 | val 0.68992
  Epoch 020 - train 0.60904 | val 0.69234
  Epoch 030 - train 0.55939 | val 0.68225
  Classification -> best τ=0.445 (val F1=0.2776)
  Directional -> Accuracy: 0.6087, MCC: 0.1780, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67633 | val 0.69410
  Epoch 020 - train 0.65498 | val 0.72677
  Epoch 030 - train 0.62799 | val 0.66239
  Classification -> best τ=0.475 (val F1=0.3534)
  Directional -> Accuracy: 0.4681, MCC: -0.0600, F1: 0.4681

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67027 | val 0.78290
  Epoch 020 - train 0.65101 | val 0.88680
  Epoch 021 - train 0.65501 | val 0.97579
  Classification -> best τ=0.530 (val F1=0.1134)
  Directional -> Accuracy: 0.5733, MCC: 0.1217, F1: 0.6522

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63901 | val 0.72143
  Epoch 020 - train 0.59749 | val 1.33711
  Epoch 024 - train 0.60058 | val 1.29016
  Classification -> best τ=0.510 (val F1=0.4255)
  Directional -> Accuracy: 0.6078, MCC: 0.2083, F1: 0.6552

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65257 | val 0.69371
  Epoch 020 - train 0.64371 | val 0.69936
  Epoch 023 - train 0.65854 | val 0.71171
  Classification -> best τ=0.505 (val F1=0.1741)
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66402 | val 0.70104
  Epoch 020 - train 0.64559 | val 0.73079
  Epoch 027 - train 0.64328 | val 0.74305
  Classification -> best τ=0.480 (val F1=0.1994)
  Directional -> Accuracy: 0.4638, MCC: 0.0500, F1: 0.5542

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63059 | val 0.72715
  Epoch 020 - train 0.57524 | val 0.73046
  Epoch 021 - train 0.57557 | val 0.77024
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65246 | val 0.71292
  Epoch 020 - train 0.61103 | val 0.89487
  Epoch 021 - train 0.62811 | val 0.92485
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65260 | val 0.69671
  Epoch 020 - train 0.61939 | val 0.70319
  Epoch 021 - train 0.61510 | val 0.70536
  Classification -> best τ=0.525 (val F1=0.2415)
  Directional -> Accuracy: 0.5143, MCC: 0.0414, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65078 | val 0.70105
  Epoch 020 - train 0.64395 | val 0.71153
  Epoch 023 - train 0.64626 | val 0.84517
  Classification -> best τ=0.515 (val F1=0.0891)
  Directional -> Accuracy: 0.6200, MCC: 0.3195, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65028 | val 0.76797
  Epoch 020 - train 0.64159 | val 1.15815
  Epoch 021 - train 0.63308 | val 1.17006
  Classification -> best τ=0.490 (val F1=0.0382)
  Directional -> Accuracy: 0.5862, MCC: 0.1837, F1: 0.6471

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62078 | val 0.74427
  Epoch 020 - train 0.59115 | val 1.41024
  Epoch 021 - train 0.58424 | val 1.42294
  Classification -> best τ=0.530 (val F1=0.1953)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64807 | val 0.65031
  Epoch 020 - train 0.61933 | val 0.68049
  Epoch 030 - train 0.59658 | val 0.65556
  Classification -> best τ=0.600 (val F1=0.3656)
  Directional -> Accuracy: 0.4918, MCC: -0.0030, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66705 | val 0.68134
  Epoch 020 - train 0.60699 | val 0.94217
  Epoch 030 - train 0.54396 | val 1.49741
  Classification -> best τ=0.505 (val F1=0.3205)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64826 | val 0.70663
  Epoch 020 - train 0.61133 | val 0.91222
  Epoch 027 - train 0.59371 | val 0.76336
  Classification -> best τ=0.570 (val F1=0.2179)
  Directional -> Accuracy: 0.5714, MCC: 0.2263, F1: 0.4444

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66548 | val 0.75654
  Epoch 020 - train 0.62994 | val 0.84312
  Epoch 021 - train 0.63395 | val 0.86262
  Classification -> best τ=0.500 (val F1=0.1111)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66937 | val 0.83047
  Epoch 020 - train 0.66010 | val 1.25588
  Epoch 021 - train 0.65561 | val 1.28221
  Classification -> best τ=0.505 (val F1=0.0728)
  Directional -> Accuracy: 0.5658, MCC: 0.1290, F1: 0.6118

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65736 | val 0.71116
  Epoch 020 - train 0.64938 | val 0.72030
  Epoch 030 - train 0.62562 | val 0.75893
  Classification -> best τ=0.405 (val F1=0.3201)
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64131 | val 0.69872
  Epoch 020 - train 0.60682 | val 0.99630
  Epoch 026 - train 0.60503 | val 0.85044
  Classification -> best τ=0.535 (val F1=0.2366)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69108 | val 0.69195
  Epoch 020 - train 0.62330 | val 0.72077
  Epoch 030 - train 0.62327 | val 0.72416
  Classification -> best τ=0.475 (val F1=0.3143)
  Directional -> Accuracy: 0.5833, MCC: 0.1943, F1: 0.6154

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67393 | val 0.69785
  Epoch 020 - train 0.64818 | val 0.73364
  Epoch 023 - train 0.66485 | val 0.69947
  Classification -> best τ=0.460 (val F1=0.1664)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65273 | val 0.68934
  Epoch 020 - train 0.63445 | val 0.76572
  Epoch 027 - train 0.63519 | val 0.89786
  Classification -> best τ=0.545 (val F1=0.2653)
  Directional -> Accuracy: 0.5517, MCC: 0.0425, F1: 0.6579

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66826 | val 0.69312
  Epoch 020 - train 0.65114 | val 0.86142
  Epoch 024 - train 0.66383 | val 0.84969
  Classification -> best τ=0.510 (val F1=0.1427)
  Directional -> Accuracy: 0.5455, MCC: 0.0692, F1: 0.3478

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64874 | val 0.67074
  Epoch 020 - train 0.58209 | val 0.72186
  Epoch 030 - train 0.55528 | val 0.76940
  Classification -> best τ=0.495 (val F1=0.3727)
  Directional -> Accuracy: 0.4464, MCC: -0.0299, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63248 | val 0.70689
  Epoch 020 - train 0.59562 | val 0.90371
  Epoch 021 - train 0.57931 | val 0.94048
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66161 | val 0.69510
  Epoch 020 - train 0.61678 | val 0.70349
  Epoch 030 - train 0.60271 | val 0.68012
  Classification -> best τ=0.575 (val F1=0.1140)
  Directional -> Accuracy: 0.6512, MCC: 0.2804, F1: 0.7619

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66247 | val 0.68220
  Epoch 020 - train 0.63877 | val 0.73739
  Epoch 028 - train 0.62726 | val 0.82969
  Classification -> best τ=0.425 (val F1=0.2946)
  Directional -> Accuracy: 0.5263, MCC: 0.0339, F1: 0.5846

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63149 | val 0.68777
  Epoch 020 - train 0.65590 | val 0.68712
  Epoch 030 - train 0.57965 | val 0.74528
  Classification -> best τ=0.440 (val F1=0.3203)
  Directional -> Accuracy: 0.5854, MCC: 0.1890, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67171 | val 0.77943
  Epoch 020 - train 0.60587 | val 1.92650
  Epoch 021 - train 0.61302 | val 2.33886
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67116 | val 0.72515
  Epoch 020 - train 0.62623 | val 0.86171
  Epoch 021 - train 0.65591 | val 0.81956
  Classification -> best τ=0.485 (val F1=0.2010)
  Directional -> Accuracy: 0.4651, MCC: -0.0385, F1: 0.3030

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64516 | val 0.71850
  Epoch 020 - train 0.62172 | val 0.95591
  Epoch 027 - train 0.58205 | val 1.33986
  Classification -> best τ=0.560 (val F1=0.1624)
  Directional -> Accuracy: 0.4400, MCC: -0.1204, F1: 0.4615

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64365 | val 0.67248
  Epoch 020 - train 0.62042 | val 0.64951
  Epoch 030 - train 0.60161 | val 0.74574
  Classification -> best τ=0.260 (val F1=0.3112)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65362 | val 0.69621
  Epoch 020 - train 0.59524 | val 0.77139
  Epoch 023 - train 0.61312 | val 0.87850
  Classification -> best τ=0.520 (val F1=0.2727)
  Directional -> Accuracy: 0.5789, MCC: 0.2928, F1: 0.7037

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68615 | val 0.71788
  Epoch 020 - train 0.65940 | val 0.69941
  Epoch 030 - train 0.61098 | val 0.70782
  Classification -> best τ=0.470 (val F1=0.3121)
  Directional -> Accuracy: 0.5455, MCC: 0.1988, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63231 | val 0.79221
  Epoch 020 - train 0.60910 | val 0.77528
  Epoch 022 - train 0.62979 | val 0.86923
  Classification -> best τ=0.455 (val F1=0.3521)
  Directional -> Accuracy: 0.5821, MCC: 0.1488, F1: 0.6316

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61072 | val 0.69036
  Epoch 020 - train 0.61098 | val 0.73412
  Epoch 030 - train 0.57387 | val 0.78309
  Classification -> best τ=0.520 (val F1=0.3300)
  Directional -> Accuracy: 0.4884, MCC: -0.0074, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62842 | val 0.68090
  Epoch 020 - train 0.61122 | val 0.74819
  Epoch 027 - train 0.55196 | val 0.99080
  Classification -> best τ=0.455 (val F1=0.2166)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65614 | val 0.71601
  Epoch 020 - train 0.58032 | val 1.04350
  Epoch 021 - train 0.59317 | val 1.05712
  Classification -> best τ=0.470 (val F1=0.1410)
  Directional -> Accuracy: 0.4255, MCC: 0.0391, F1: 0.2286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68799 | val 0.68244
  Epoch 020 - train 0.63768 | val 0.64911
  Epoch 030 - train 0.58578 | val 0.67249
  Classification -> best τ=0.425 (val F1=0.3973)
  Directional -> Accuracy: 0.3673, MCC: -0.0568, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63888 | val 0.75415
  Epoch 020 - train 0.55759 | val 1.02525
  Epoch 021 - train 0.57072 | val 1.07112
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64793 | val 0.79162
  Epoch 020 - train 0.60185 | val 1.34161
  Epoch 025 - train 0.59087 | val 1.18034
  Classification -> best τ=0.460 (val F1=0.2782)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67571 | val 0.68651
  Epoch 020 - train 0.63586 | val 0.69655
  Epoch 030 - train 0.61234 | val 0.68600
  Classification -> best τ=0.475 (val F1=0.3776)
  Directional -> Accuracy: 0.5106, MCC: 0.0168, F1: 0.5660

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59931 | val 0.71698
  Epoch 020 - train 0.57531 | val 0.73814
  Epoch 021 - train 0.57324 | val 0.73667
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62247 | val 0.70757
  Epoch 020 - train 0.60703 | val 0.74507
  Epoch 026 - train 0.62631 | val 0.78059
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67715 | val 0.73820
  Epoch 020 - train 0.66537 | val 0.76814
  Epoch 021 - train 0.67367 | val 0.77630
  Classification -> best τ=0.520 (val F1=0.1846)
  Directional -> Accuracy: 0.4643, MCC: -0.1371, F1: 0.5946

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65294 | val 0.73572
  Epoch 020 - train 0.60421 | val 0.95033
  Epoch 021 - train 0.59839 | val 1.05311
  Classification -> best τ=0.485 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63479 | val 0.90243
  Epoch 020 - train 0.65006 | val 0.93305
  Epoch 021 - train 0.63522 | val 0.92381
  Classification -> best τ=0.505 (val F1=0.2665)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-19 23:54:03,812] Trial 36 finished with value: 0.20421608224305493 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 0.0030971018294163525, 'weight_decay': 0.0005269792888977608, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.767635800111363, 'early_stopping_min_delta': 0.0006563772951714252}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 030 - train 0.59726 | val 0.72576
  Classification -> best τ=0.420 (val F1=0.2794)
  Directional -> Accuracy: 0.6066, MCC: 0.2103, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.20421608224305493
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68227 | val 0.78020
  Epoch 020 - train 0.68213 | val 0.78511
  Classification -> best τ=0.510 (val F1=0.2346)
  Directional -> Accuracy: 0.5256, MCC: -0.0670, F1: 0.0976

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68906 | val 0.86343
  Epoch 020 - train 0.67292 | val 0.86023
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68262 | val 0.67758
  Epoch 020 - train 0.70210 | val 0.67657
  Classification -> best τ=0.585 (val F1=0.3110)
  Directional -> Accuracy: 0.5625, MCC: 0.1843, F1: 0.4615

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68647 | val 0.99507
  Epoch 020 - train 0.71406 | val 1.01557
  Classification -> best τ=0.465 (val F1=0.0777)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69408 | val 0.67055
  Epoch 020 - train 0.68359 | val 0.65900
  Classification -> best τ=0.705 (val F1=0.3139)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.71841 | val 0.75433
  Epoch 020 - train 0.71560 | val 0.76037
  Classification -> best τ=0.525 (val F1=0.1650)
  Directional -> Accuracy: 0.5510, MCC: 0.1000, F1: 0.5926

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69993 | val 0.70570
  Epoch 020 - train 0.69652 | val 0.70620
  Classification -> best τ=0.455 (val F1=0.0329)
  Directional -> Accuracy: 0.4000, MCC: -0.0503, F1: 0.5532

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67983 | val 1.08741
  Epoch 020 - train 0.66854 | val 1.23789
  Classification -> best τ=0.525 (val F1=0.3368)
  Directional -> Accuracy: 0.4667, MCC: -0.0230, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70433 | val 0.75652
  Epoch 020 - train 0.70146 | val 0.75249
  Classification -> best τ=0.440 (val F1=0.1168)
  Directional -> Accuracy: 0.4762, MCC: 0.1308, F1: 0.5600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70323 | val 0.92528
  Epoch 020 - train 0.69590 | val 0.94490
  Classification -> best τ=0.440 (val F1=0.2095)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69970 | val 0.68613
  Epoch 020 - train 0.71018 | val 0.68700
  Classification -> best τ=0.480 (val F1=0.1302)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70064 | val 0.78867
  Epoch 020 - train 0.70029 | val 0.79242
  Classification -> best τ=0.500 (val F1=0.2298)
  Directional -> Accuracy: 0.5254, MCC: 0.0811, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70340 | val 0.67205
  Epoch 020 - train 0.69464 | val 0.67698
  Classification -> best τ=0.545 (val F1=0.2891)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69924 | val 0.71533
  Epoch 020 - train 0.71392 | val 0.71257
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69317 | val 0.72908
  Epoch 020 - train 0.68101 | val 0.73636
  Classification -> best τ=0.525 (val F1=0.1739)
  Directional -> Accuracy: 0.4906, MCC: -0.0693, F1: 0.2286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69690 | val 0.68521
  Epoch 020 - train 0.69379 | val 0.68029
  Classification -> best τ=0.545 (val F1=0.2990)
  Directional -> Accuracy: 0.4648, MCC: -0.0442, F1: 0.3448

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70942 | val 0.83231
  Epoch 020 - train 0.70469 | val 0.83044
  Classification -> best τ=0.480 (val F1=0.2150)
  Directional -> Accuracy: 0.4000, MCC: -0.0990, F1: 0.3077

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70648 | val 0.73297
  Epoch 020 - train 0.70030 | val 0.72233
  Classification -> best τ=0.490 (val F1=0.1571)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70185 | val 0.68918
  Epoch 020 - train 0.68633 | val 0.68059
  Classification -> best τ=0.630 (val F1=0.2750)
  Directional -> Accuracy: 0.4242, MCC: 0.1032, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69050 | val 0.76230
  Epoch 020 - train 0.68584 | val 0.75601
  Classification -> best τ=0.535 (val F1=0.1332)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70752 | val 0.71007
  Epoch 020 - train 0.69839 | val 0.70794
  Classification -> best τ=0.490 (val F1=0.0349)
  Directional -> Accuracy: 0.5714, MCC: -0.1946, F1: 0.7273

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70056 | val 0.74663
  Epoch 020 - train 0.69965 | val 0.75207
  Classification -> best τ=0.540 (val F1=0.2264)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71189 | val 0.68451
  Epoch 020 - train 0.69542 | val 0.67513
  Classification -> best τ=0.445 (val F1=0.3702)
  Directional -> Accuracy: 0.5085, MCC: 0.0524, F1: 0.4912

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70591 | val 0.72976
  Epoch 020 - train 0.69974 | val 0.72423
  Classification -> best τ=0.480 (val F1=0.1628)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69822 | val 0.69959
  Epoch 020 - train 0.69067 | val 0.69324
  Classification -> best τ=0.465 (val F1=0.2073)
  Directional -> Accuracy: 0.4386, MCC: -0.1304, F1: 0.4839

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67776 | val 0.69959
  Epoch 020 - train 0.69785 | val 0.70466
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70431 | val 0.82370
  Epoch 020 - train 0.71813 | val 0.82999
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70040 | val 0.74791
  Epoch 020 - train 0.70195 | val 0.74580
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.72487 | val 0.71677
  Epoch 020 - train 0.73600 | val 0.72381
  Classification -> best τ=0.465 (val F1=0.2141)
  Directional -> Accuracy: 0.4651, MCC: -0.0385, F1: 0.3030

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71710 | val 0.75803
  Epoch 020 - train 0.69696 | val 0.76266
  Classification -> best τ=0.495 (val F1=0.2039)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70670 | val 0.69364
  Epoch 020 - train 0.72471 | val 0.69228
  Classification -> best τ=0.460 (val F1=0.2272)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70004 | val 0.69451
  Epoch 020 - train 0.67640 | val 0.68973
  Classification -> best τ=0.415 (val F1=0.2472)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69329 | val 0.67540
  Epoch 020 - train 0.67839 | val 0.67375
  Classification -> best τ=0.450 (val F1=0.3723)
  Directional -> Accuracy: 0.5811, MCC: 0.1565, F1: 0.6173

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.74165 | val 0.71478
  Epoch 020 - train 0.70642 | val 0.77968
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72748 | val 0.70625
  Epoch 020 - train 0.71836 | val 0.70647
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69348 | val 0.70603
  Epoch 020 - train 0.68069 | val 0.70723
  Classification -> best τ=0.480 (val F1=0.2541)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68641 | val 0.69199
  Epoch 020 - train 0.70035 | val 0.69229
  Classification -> best τ=0.480 (val F1=0.1206)
  Directional -> Accuracy: 0.6136, MCC: 0.2294, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70297 | val 0.75720
  Epoch 020 - train 0.70711 | val 0.75234
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68448 | val 0.80006
  Epoch 020 - train 0.68499 | val 0.81623
  Classification -> best τ=0.510 (val F1=0.1544)
  Directional -> Accuracy: 0.5625, MCC: -0.2000, F1: 0.7200

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69844 | val 0.69367
  Epoch 020 - train 0.69748 | val 0.69544
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70714 | val 0.71318
  Epoch 020 - train 0.71327 | val 0.72815
  Classification -> best τ=0.505 (val F1=0.3194)
  Directional -> Accuracy: 0.4359, MCC: -0.1139, F1: 0.3889

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69505 | val 0.68122
  Epoch 020 - train 0.68110 | val 0.68260
  Classification -> best τ=0.485 (val F1=0.2897)
  Directional -> Accuracy: 0.5395, MCC: 0.0992, F1: 0.6465

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68789 | val 0.71193
  Epoch 020 - train 0.69161 | val 0.70908
  Classification -> best τ=0.520 (val F1=0.0228)
  Directional -> Accuracy: 0.5208, MCC: 0.1459, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70025 | val 0.72808
  Epoch 020 - train 0.67734 | val 0.74105
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71191 | val 0.70494
  Epoch 020 - train 0.71705 | val 0.70773
  Classification -> best τ=0.525 (val F1=0.3780)
  Directional -> Accuracy: 0.4146, MCC: -0.1190, F1: 0.4000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.73277 | val 0.90404
  Epoch 020 - train 0.71436 | val 0.90789
  Classification -> best τ=0.440 (val F1=0.0698)
  Directional -> Accuracy: 0.5088, MCC: 0.1595, F1: 0.2222

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67681 | val 0.73093
  Epoch 020 - train 0.68734 | val 0.73344
  Classification -> best τ=0.540 (val F1=0.2961)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71648 | val 0.70880
  Epoch 020 - train 0.70468 | val 0.70705
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69697 | val 0.71692
  Epoch 020 - train 0.70468 | val 0.71852
  Classification -> best τ=0.500 (val F1=0.1724)
  Directional -> Accuracy: 0.5614, MCC: 0.1915, F1: 0.6914

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70320 | val 0.74044

[I 2026-02-19 23:55:53,157] Trial 37 finished with value: 0.16514250650261847 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 6.245785969294741e-06, 'weight_decay': 0.00011708475961817253, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.0292963116802083, 'early_stopping_min_delta': 0.0019685039266583385}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 020 - train 0.68816 | val 0.74929
  Classification -> best τ=0.485 (val F1=0.2132)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.16514250650261847
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60998 | val 1.15265
  Epoch 016 - train 0.58243 | val 1.35362
  Classification -> best τ=0.520 (val F1=0.2122)
  Directional -> Accuracy: 0.4267, MCC: -0.1140, F1: 0.5567

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60161 | val 0.80694
  Epoch 016 - train 0.57124 | val 0.89476
  Classification -> best τ=0.425 (val F1=0.1994)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64316 | val 0.73647
  Epoch 017 - train 0.59557 | val 0.72771
  Classification -> best τ=0.510 (val F1=0.3563)
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64460 | val 2.27683
  Epoch 016 - train 0.63411 | val 2.40148
  Classification -> best τ=0.500 (val F1=0.1508)
  Directional -> Accuracy: 0.5205, MCC: -0.0095, F1: 0.6535

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56559 | val 1.34255
  Epoch 018 - train 0.50341 | val 1.04113
  Classification -> best τ=0.585 (val F1=0.3860)
  Directional -> Accuracy: 0.5510, MCC: 0.1138, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56781 | val 1.09414
  Epoch 016 - train 0.48215 | val 1.01129
  Classification -> best τ=0.455 (val F1=0.1839)
  Directional -> Accuracy: 0.4889, MCC: -0.0181, F1: 0.5306

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62621 | val 0.84456
  Epoch 016 - train 0.60518 | val 1.03045
  Classification -> best τ=0.455 (val F1=0.2321)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59201 | val 2.19372
  Epoch 016 - train 0.55388 | val 2.77264
  Classification -> best τ=0.515 (val F1=0.0976)
  Directional -> Accuracy: 0.4634, MCC: 0.0293, F1: 0.5926

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62711 | val 0.89018
  Epoch 016 - train 0.58992 | val 0.77087
  Classification -> best τ=0.490 (val F1=0.2139)
  Directional -> Accuracy: 0.3617, MCC: -0.2805, F1: 0.3182

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60443 | val 0.89876
  Epoch 016 - train 0.57680 | val 0.93598
  Classification -> best τ=0.425 (val F1=0.2357)
  Directional -> Accuracy: 0.4412, MCC: 0.0151, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62306 | val 1.03768
  Epoch 016 - train 0.59858 | val 0.97392
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61177 | val 0.84385
  Epoch 016 - train 0.56573 | val 0.86385
  Classification -> best τ=0.500 (val F1=0.1281)
  Directional -> Accuracy: 0.6250, MCC: 0.2966, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55806 | val 3.30928
  Epoch 016 - train 0.52869 | val 4.31026
  Classification -> best τ=0.530 (val F1=0.1184)
  Directional -> Accuracy: 0.4898, MCC: -0.0184, F1: 0.5098

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64080 | val 0.72893
  Epoch 017 - train 0.61018 | val 0.77847
  Classification -> best τ=0.470 (val F1=0.4371)
  Directional -> Accuracy: 0.5932, MCC: 0.2257, F1: 0.6923

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62518 | val 1.23488
  Epoch 016 - train 0.57541 | val 1.41932
  Classification -> best τ=0.550 (val F1=0.0883)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59677 | val 0.94362
  Epoch 016 - train 0.51753 | val 1.36351
  Classification -> best τ=0.455 (val F1=0.2526)
  Directional -> Accuracy: 0.5294, MCC: 0.0245, F1: 0.6596

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62412 | val 1.47685
  Epoch 016 - train 0.59147 | val 1.48151
  Classification -> best τ=0.570 (val F1=0.2000)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64619 | val 0.75121
  Epoch 016 - train 0.59358 | val 0.79765
  Classification -> best τ=0.465 (val F1=0.1745)
  Directional -> Accuracy: 0.5676, MCC: 0.1652, F1: 0.5789

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60943 | val 1.23074
  Epoch 016 - train 0.57413 | val 1.70377
  Classification -> best τ=0.525 (val F1=0.2288)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61112 | val 0.67690
  Epoch 019 - train 0.52773 | val 0.75361
  Classification -> best τ=0.440 (val F1=0.2963)
  Directional -> Accuracy: 0.6712, MCC: 0.3313, F1: 0.7143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62002 | val 1.04058
  Epoch 016 - train 0.55728 | val 0.86863
  Classification -> best τ=0.505 (val F1=0.1288)
  Directional -> Accuracy: 0.5217, MCC: 0.0952, F1: 0.5217

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62805 | val 1.55160
  Epoch 016 - train 0.61574 | val 1.71603
  Classification -> best τ=0.495 (val F1=0.1741)
  Directional -> Accuracy: 0.5781, MCC: 0.1569, F1: 0.5970

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61150 | val 1.17208
  Epoch 017 - train 0.60317 | val 1.23750
  Classification -> best τ=0.625 (val F1=0.3780)
  Directional -> Accuracy: 0.4821, MCC: 0.2060, F1: 0.1714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57959 | val 1.73195
  Epoch 016 - train 0.54505 | val 1.82685
  Classification -> best τ=0.355 (val F1=0.1604)
  Directional -> Accuracy: 0.5469, MCC: 0.1501, F1: 0.6329

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58387 | val 0.82799
  Epoch 019 - train 0.51460 | val 1.03137
  Classification -> best τ=0.650 (val F1=0.4553)
  Directional -> Accuracy: 0.4259, MCC: -0.1628, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57504 | val 0.75117
  Epoch 016 - train 0.54561 | val 0.82368
  Classification -> best τ=0.485 (val F1=0.1355)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60631 | val 0.98779
  Epoch 020 - train 0.56168 | val 1.35198
  Classification -> best τ=0.490 (val F1=0.2626)
  Directional -> Accuracy: 0.5306, MCC: 0.0661, F1: 0.5660

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59967 | val 1.04090
  Epoch 016 - train 0.57580 | val 1.67978
  Classification -> best τ=0.490 (val F1=0.2283)
  Directional -> Accuracy: 0.6000, MCC: 0.1815, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60368 | val 0.69482
  Epoch 020 - train 0.53549 | val 0.69178
  Classification -> best τ=0.405 (val F1=0.3708)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60704 | val 1.64473
  Epoch 016 - train 0.56553 | val 2.00682
  Classification -> best τ=0.550 (val F1=0.1765)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60252 | val 1.08438
  Epoch 016 - train 0.54180 | val 1.30046
  Classification -> best τ=0.490 (val F1=0.0319)
  Directional -> Accuracy: 0.5122, MCC: -0.1252, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59354 | val 0.75086
  Epoch 016 - train 0.56123 | val 0.80256
  Classification -> best τ=0.485 (val F1=0.2597)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60895 | val 1.13395
  Epoch 017 - train 0.58201 | val 1.45376
  Classification -> best τ=0.530 (val F1=0.3810)
  Directional -> Accuracy: 0.5352, MCC: 0.1773, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62777 | val 0.83790
  Epoch 016 - train 0.57282 | val 0.93493
  Classification -> best τ=0.485 (val F1=0.2675)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5581

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57986 | val 1.01020
  Epoch 016 - train 0.56699 | val 1.09619
  Classification -> best τ=0.475 (val F1=0.3828)
  Directional -> Accuracy: 0.5692, MCC: 0.1000, F1: 0.6500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57978 | val 0.71822
  Epoch 019 - train 0.50070 | val 0.75006
  Classification -> best τ=0.415 (val F1=0.2582)
  Directional -> Accuracy: 0.5750, MCC: 0.1417, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57118 | val 0.88619
  Epoch 017 - train 0.52293 | val 0.99807
  Classification -> best τ=0.475 (val F1=0.2140)
  Directional -> Accuracy: 0.4364, MCC: -0.1047, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56188 | val 2.05606
  Epoch 016 - train 0.48477 | val 2.76948
  Classification -> best τ=0.485 (val F1=0.2913)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55437 | val 0.74887
  Epoch 019 - train 0.53233 | val 0.69841
  Classification -> best τ=0.540 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56931 | val 1.39552
  Epoch 016 - train 0.52784 | val 1.83594
  Classification -> best τ=0.420 (val F1=0.2464)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62016 | val 0.87819
  Epoch 016 - train 0.60828 | val 0.77695
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59336 | val 0.78443
  Epoch 016 - train 0.54833 | val 0.82396
  Classification -> best τ=0.475 (val F1=0.1917)
  Directional -> Accuracy: 0.4878, MCC: 0.1187, F1: 0.3226

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57481 | val 0.74504
  Epoch 020 - train 0.51824 | val 0.66742
  Epoch 030 - train 0.43943 | val 0.68960
  Epoch 032 - train 0.42868 | val 0.81285
  Classification -> best τ=0.400 (val F1=0.4625)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64328 | val 1.08421
  Epoch 016 - train 0.60497 | val 1.29007
  Classification -> best τ=0.470 (val F1=0.0616)
  Directional -> Accuracy: 0.6667, MCC: 0.3773, F1: 0.6400

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58862 | val 1.82538
  Epoch 016 - train 0.56348 | val 2.06133
  Classification -> best τ=0.605 (val F1=0.2566)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60048 | val 0.92408
  Epoch 016 - train 0.57664 | val 0.98389
  Classification -> best τ=0.500 (val F1=0.2479)
  Directional -> Accuracy: 0.5962, MCC: 0.1925, F1: 0.6038

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61356 | val 0.73666
  Epoch 016 - train 0.55071 | val 0.83294
  Classification -> best τ=0.485 (val F1=0.1626)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61897 | val 0.74665

[I 2026-02-19 23:57:44,340] Trial 38 finished with value: 0.23065793893018074 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.0009111794260007198, 'weight_decay': 3.8815774086842965e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.5823616123644897, 'early_stopping_min_delta': 0.0026532884370097797}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 020 - train 0.53704 | val 0.92959
  Classification -> best τ=0.540 (val F1=0.2608)
  Directional -> Accuracy: 0.5424, MCC: 0.0688, F1: 0.2703

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23065793893018074
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68920 | val 0.67633
  Epoch 020 - train 0.67016 | val 0.68858
  Epoch 022 - train 0.68555 | val 0.68982
  Classification -> best τ=0.515 (val F1=0.1810)
  Directional -> Accuracy: 0.5696, MCC: 0.2013, F1: 0.6222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71643 | val 0.69114
  Epoch 016 - train 0.67137 | val 0.69182
  Classification -> best τ=0.435 (val F1=0.3018)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69333 | val 0.69022
  Epoch 016 - train 0.69075 | val 0.69586
  Classification -> best τ=0.480 (val F1=0.1943)
  Directional -> Accuracy: 0.5306, MCC: 0.0708, F1: 0.5106

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68971 | val 0.72871
  Epoch 016 - train 0.69551 | val 0.75195
  Classification -> best τ=0.530 (val F1=0.2300)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70516 | val 0.65475
  Epoch 020 - train 0.69016 | val 0.64000
  Epoch 028 - train 0.68107 | val 0.65067
  Classification -> best τ=0.495 (val F1=0.4274)
  Directional -> Accuracy: 0.5660, MCC: 0.1357, F1: 0.5660

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69512 | val 0.70005
  Epoch 016 - train 0.69537 | val 0.74489
  Classification -> best τ=0.535 (val F1=0.1419)
  Directional -> Accuracy: 0.5122, MCC: 0.0263, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69060 | val 0.69209
  Epoch 016 - train 0.70504 | val 0.68776
  Classification -> best τ=0.465 (val F1=0.0884)
  Directional -> Accuracy: 0.5915, MCC: 0.0455, F1: 0.1212

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68570 | val 0.71608
  Epoch 016 - train 0.68369 | val 0.73507
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69952 | val 0.69601
  Epoch 016 - train 0.72479 | val 0.70109
  Classification -> best τ=0.525 (val F1=0.2522)
  Directional -> Accuracy: 0.5581, MCC: 0.0271, F1: 0.3448

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68874 | val 0.74000
  Epoch 016 - train 0.68647 | val 0.73141
  Classification -> best τ=0.490 (val F1=0.0523)
  Directional -> Accuracy: 0.5278, MCC: 0.0370, F1: 0.4516

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68799 | val 0.70194
  Epoch 016 - train 0.68565 | val 0.71477
  Classification -> best τ=0.480 (val F1=0.2633)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.3243

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68101 | val 0.72941
  Epoch 016 - train 0.71483 | val 0.80421
  Classification -> best τ=0.495 (val F1=0.1074)
  Directional -> Accuracy: 0.5167, MCC: 0.0765, F1: 0.1212

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64075 | val 0.69838
  Epoch 016 - train 0.65331 | val 0.70440
  Classification -> best τ=0.525 (val F1=0.0364)
  Directional -> Accuracy: 0.5778, MCC: 0.1411, F1: 0.4571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68615 | val 0.68711
  Epoch 020 - train 0.68852 | val 0.68892
  Epoch 022 - train 0.69382 | val 0.68480
  Classification -> best τ=0.475 (val F1=0.2365)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71630 | val 0.69461
  Epoch 016 - train 0.69351 | val 0.69468
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68119 | val 0.70215
  Epoch 016 - train 0.67475 | val 0.71405
  Classification -> best τ=0.530 (val F1=0.0866)
  Directional -> Accuracy: 0.5417, MCC: 0.0555, F1: 0.6292

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69480 | val 0.78464
  Epoch 016 - train 0.67110 | val 0.94851
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71348 | val 0.74404
  Epoch 016 - train 0.68264 | val 0.83452
  Classification -> best τ=0.505 (val F1=0.1180)
  Directional -> Accuracy: 0.5897, MCC: 0.1729, F1: 0.6364

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66011 | val 0.69059
  Epoch 016 - train 0.67673 | val 0.69361
  Classification -> best τ=0.490 (val F1=0.0398)
  Directional -> Accuracy: 0.5373, MCC: 0.0832, F1: 0.5634

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66917 | val 0.68013
  Epoch 016 - train 0.67085 | val 0.68306
  Classification -> best τ=0.490 (val F1=0.1901)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70813 | val 0.70227
  Epoch 016 - train 0.67591 | val 0.73178
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69487 | val 0.71058
  Epoch 016 - train 0.70587 | val 0.72266
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73404 | val 0.68032
  Epoch 020 - train 0.70801 | val 0.67480
  Epoch 023 - train 0.70750 | val 0.67564
  Classification -> best τ=0.490 (val F1=0.3130)
  Directional -> Accuracy: 0.5333, MCC: 0.1240, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69021 | val 0.70384
  Epoch 016 - train 0.68167 | val 0.69836
  Classification -> best τ=0.460 (val F1=0.0147)
  Directional -> Accuracy: 0.4853, MCC: -0.0456, F1: 0.3396

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68984 | val 0.66737
  Epoch 020 - train 0.70257 | val 0.64271
  Epoch 030 - train 0.67775 | val 0.63366
  Classification -> best τ=0.485 (val F1=0.5041)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68509 | val 0.69031
  Epoch 016 - train 0.66327 | val 0.69542
  Classification -> best τ=0.515 (val F1=0.0673)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70586 | val 0.69723
  Epoch 016 - train 0.67922 | val 0.70473
  Classification -> best τ=0.495 (val F1=0.1612)
  Directional -> Accuracy: 0.5778, MCC: 0.0633, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68212 | val 0.68601
  Epoch 016 - train 0.68549 | val 0.68777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5593, MCC: 0.0000, F1: 0.7174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69823 | val 0.71709
  Epoch 016 - train 0.67886 | val 0.72842
  Classification -> best τ=0.470 (val F1=0.2932)
  Directional -> Accuracy: 0.5000, MCC: 0.0106, F1: 0.4500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71156 | val 0.69396
  Epoch 016 - train 0.72729 | val 0.69512
  Classification -> best τ=0.475 (val F1=0.1877)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5490

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70796 | val 0.70573
  Epoch 016 - train 0.68618 | val 0.70891
  Classification -> best τ=0.490 (val F1=0.1702)
  Directional -> Accuracy: 0.3913, MCC: -0.2062, F1: 0.3636

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68851 | val 0.68073
  Epoch 020 - train 0.68209 | val 0.67595
  Epoch 030 - train 0.69274 | val 0.67107
  Classification -> best τ=0.410 (val F1=0.2981)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68613 | val 0.67953
  Epoch 020 - train 0.70047 | val 0.65485
  Epoch 030 - train 0.69097 | val 0.65132
  Classification -> best τ=0.395 (val F1=0.3202)
  Directional -> Accuracy: 0.5600, MCC: 0.1440, F1: 0.5479

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69780 | val 0.69425
  Epoch 016 - train 0.72970 | val 0.69577
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70227 | val 0.72021
  Epoch 016 - train 0.68665 | val 0.74959
  Classification -> best τ=0.555 (val F1=0.2576)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69430 | val 0.69631
  Epoch 016 - train 0.65094 | val 0.70364
  Classification -> best τ=0.535 (val F1=0.1072)
  Directional -> Accuracy: 0.4638, MCC: 0.0217, F1: 0.3273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.75315 | val 0.69966
  Epoch 016 - train 0.69655 | val 0.69946
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64478 | val 0.70796
  Epoch 016 - train 0.63664 | val 0.73217
  Classification -> best τ=0.530 (val F1=0.1025)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67240 | val 0.69242
  Epoch 016 - train 0.67495 | val 0.74581
  Classification -> best τ=0.480 (val F1=0.1610)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71938 | val 0.68402
  Epoch 020 - train 0.68283 | val 0.65894
  Epoch 030 - train 0.67436 | val 0.66642
  Classification -> best τ=0.445 (val F1=0.3420)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71721 | val 0.68640
  Epoch 016 - train 0.71893 | val 0.68559
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69365 | val 0.67971
  Epoch 020 - train 0.69472 | val 0.68677
  Epoch 023 - train 0.67262 | val 0.68171
  Classification -> best τ=0.550 (val F1=0.2598)
  Directional -> Accuracy: 0.5455, MCC: 0.0920, F1: 0.5333

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70775 | val 0.70219
  Epoch 016 - train 0.71766 | val 0.74473
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68126 | val 0.67465
  Epoch 016 - train 0.66859 | val 0.68482
  Classification -> best τ=0.465 (val F1=0.1826)
  Directional -> Accuracy: 0.5532, MCC: 0.0026, F1: 0.6866

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65930 | val 0.70356
  Epoch 016 - train 0.67712 | val 0.74332
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68112 | val 0.72144
  Epoch 016 - train 0.69929 | val 0.77178
  Classification -> best τ=0.515 (val F1=0.2780)
  Directional -> Accuracy: 0.6379, MCC: 0.3046, F1: 0.7470

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69358 | val 0.71909
  Epoch 016 - train 0.69275 | val 0.76109
  Classification -> best τ=0.505 (val F1=0.1277)
  Directional -> Accuracy: 0.4746, MCC: -0.0482, F1: 0.5634

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68236 | val 0.72146
  Epoch 016 - train 0.70091 | val 0.76788
  Classification -> best τ=0.485 (val F1=0.0131)
  Directional -> Accuracy: 0.5179, MCC: -0.0404, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68640 | val 0.73475
  Epoch 016 - train 0.65700 | val 0.75809
  Classification -> best τ=0.530 (val F1=0.1362)
  Directional -> Accuracy: 0.5000, MCC: -0.0228, F1: 0.6133

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71851 | val 0.72892

[I 2026-02-19 23:58:27,125] Trial 39 finished with value: 0.14592477561124662 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.00019538285740712685, 'weight_decay': 0.0009672082638592013, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.2412053158364034, 'early_stopping_min_delta': 0.009902452020822142}. Best is trial 22 with value: 0.26179994200866186.

  Epoch 016 - train 0.69312 | val 0.77891
  Classification -> best τ=0.555 (val F1=0.0516)
  Directional -> Accuracy: 0.5397, MCC: 0.0728, F1: 0.1714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14592477561124662
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67843 | val 0.74419
  Epoch 011 - train 0.68025 | val 0.74619
  Classification -> best τ=0.515 (val F1=0.0676)
  Directional -> Accuracy: 0.5974, MCC: 0.1830, F1: 0.3404

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66246 | val 0.68284
  Epoch 018 - train 0.63478 | val 0.69551
  Classification -> best τ=0.425 (val F1=0.3015)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69378 | val 0.75054
  Epoch 011 - train 0.69170 | val 0.74880
  Classification -> best τ=0.540 (val F1=0.0909)
  Directional -> Accuracy: 0.5532, MCC: 0.1174, F1: 0.5333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68021 | val 1.21671
  Epoch 011 - train 0.67383 | val 1.21062
  Classification -> best τ=0.400 (val F1=0.1283)
  Directional -> Accuracy: 0.5600, MCC: 0.1059, F1: 0.6118

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66869 | val 0.63467
  Epoch 020 - train 0.64983 | val 0.63035
  Classification -> best τ=0.565 (val F1=0.4711)
  Directional -> Accuracy: 0.7451, MCC: 0.4900, F1: 0.7547

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64963 | val 0.78443
  Epoch 011 - train 0.68342 | val 0.79172
  Classification -> best τ=0.470 (val F1=0.1644)
  Directional -> Accuracy: 0.4468, MCC: -0.1051, F1: 0.5185

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66138 | val 0.70347
  Epoch 011 - train 0.66696 | val 0.70532
  Classification -> best τ=0.485 (val F1=0.1891)
  Directional -> Accuracy: 0.5652, MCC: 0.0984, F1: 0.4643

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71251 | val 0.60765
  Epoch 018 - train 0.68618 | val 0.62285
  Classification -> best τ=0.415 (val F1=0.3295)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70775 | val 0.75605
  Epoch 011 - train 0.69775 | val 0.75734
  Classification -> best τ=0.520 (val F1=0.1978)
  Directional -> Accuracy: 0.5918, MCC: 0.1687, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69188 | val 0.98918
  Epoch 011 - train 0.69577 | val 0.98764
  Classification -> best τ=0.430 (val F1=0.2231)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67430 | val 0.78881
  Epoch 011 - train 0.67860 | val 0.79697
  Classification -> best τ=0.510 (val F1=0.0602)
  Directional -> Accuracy: 0.5600, MCC: 0.1548, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68338 | val 0.79736
  Epoch 011 - train 0.68779 | val 0.80214
  Classification -> best τ=0.495 (val F1=0.1923)
  Directional -> Accuracy: 0.3966, MCC: -0.2100, F1: 0.3396

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67999 | val 0.89019
  Epoch 011 - train 0.65749 | val 0.90441
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69332 | val 0.64752
  Epoch 014 - train 0.67519 | val 0.64892
  Classification -> best τ=0.425 (val F1=0.2272)
  Directional -> Accuracy: 0.5738, MCC: 0.1489, F1: 0.6286

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68419 | val 1.04658
  Epoch 011 - train 0.68939 | val 1.04826
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67583 | val 0.72130
  Epoch 013 - train 0.65729 | val 0.73113
  Classification -> best τ=0.445 (val F1=0.2605)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66910 | val 0.70347
  Epoch 011 - train 0.68596 | val 0.70587
  Classification -> best τ=0.470 (val F1=0.2508)
  Directional -> Accuracy: 0.3898, MCC: -0.0171, F1: 0.1429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67953 | val 0.81884
  Epoch 011 - train 0.68943 | val 0.81792
  Classification -> best τ=0.450 (val F1=0.1236)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66799 | val 0.69697
  Epoch 011 - train 0.68124 | val 0.69757
  Classification -> best τ=0.465 (val F1=0.2237)
  Directional -> Accuracy: 0.5692, MCC: 0.0852, F1: 0.6585

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66541 | val 0.67831
  Epoch 015 - train 0.65687 | val 0.67843
  Classification -> best τ=0.530 (val F1=0.3237)
  Directional -> Accuracy: 0.3467, MCC: -0.2934, F1: 0.2687

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67701 | val 0.69207
  Epoch 011 - train 0.67669 | val 0.69204
  Classification -> best τ=0.505 (val F1=0.0087)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68630 | val 0.71285
  Epoch 011 - train 0.68060 | val 0.71383
  Classification -> best τ=0.525 (val F1=0.2044)
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68683 | val 0.68360
  Epoch 013 - train 0.69031 | val 0.68498
  Classification -> best τ=0.510 (val F1=0.3067)
  Directional -> Accuracy: 0.5690, MCC: 0.0711, F1: 0.6835

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68764 | val 0.98278
  Epoch 011 - train 0.69246 | val 0.99487
  Classification -> best τ=0.445 (val F1=0.2044)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66332 | val 0.68408
  Epoch 020 - train 0.65446 | val 0.67436
  Epoch 030 - train 0.64712 | val 0.67017
  Epoch 031 - train 0.65788 | val 0.67056
  Classification -> best τ=0.550 (val F1=0.4472)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69165 | val 0.79626
  Epoch 011 - train 0.70145 | val 0.81679
  Classification -> best τ=0.485 (val F1=0.1443)
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.2308

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70437 | val 0.87527
  Epoch 011 - train 0.69780 | val 0.87430
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68876 | val 0.73606
  Epoch 011 - train 0.70657 | val 0.73469
  Classification -> best τ=0.525 (val F1=0.1568)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63987 | val 0.69129
  Epoch 011 - train 0.66400 | val 0.69603
  Classification -> best τ=0.495 (val F1=0.3069)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70785 | val 0.70208
  Epoch 011 - train 0.67351 | val 0.70394
  Classification -> best τ=0.470 (val F1=0.2683)
  Directional -> Accuracy: 0.4651, MCC: -0.0893, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.73664 | val 0.78846
  Epoch 011 - train 0.69731 | val 0.79224
  Classification -> best τ=0.495 (val F1=0.2890)
  Directional -> Accuracy: 0.5581, MCC: 0.0933, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69579 | val 0.71926
  Epoch 011 - train 0.68015 | val 0.72049
  Classification -> best τ=0.510 (val F1=0.0684)
  Directional -> Accuracy: 0.4600, MCC: -0.0655, F1: 0.4255

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67785 | val 0.71254
  Epoch 020 - train 0.66816 | val 0.68852
  Epoch 030 - train 0.66045 | val 0.67392
  Epoch 040 - train 0.64028 | val 0.66684
  Epoch 044 - train 0.63585 | val 0.66527
  Classification -> best τ=0.470 (val F1=0.3602)
  Directional -> Accuracy: 0.5342, MCC: 0.1237, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67876 | val 0.68999
  Epoch 011 - train 0.67058 | val 0.68870
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71122 | val 0.76762
  Epoch 011 - train 0.69661 | val 0.76910
  Classification -> best τ=0.515 (val F1=0.1041)
  Directional -> Accuracy: 0.5455, MCC: 0.1668, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68736 | val 0.66901
  Epoch 017 - train 0.65220 | val 0.66828
  Classification -> best τ=0.375 (val F1=0.3444)
  Directional -> Accuracy: 0.4776, MCC: -0.0028, F1: 0.4262

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66631 | val 0.68473
  Epoch 020 - train 0.68189 | val 0.67893
  Epoch 023 - train 0.65530 | val 0.67881
  Classification -> best τ=0.350 (val F1=0.2819)
  Directional -> Accuracy: 0.5814, MCC: 0.1635, F1: 0.6400

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65928 | val 0.77315
  Epoch 013 - train 0.63341 | val 0.78618
  Classification -> best τ=0.415 (val F1=0.2803)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68067 | val 0.67475
  Epoch 019 - train 0.64544 | val 0.67950
  Classification -> best τ=0.340 (val F1=0.2057)
  Directional -> Accuracy: 0.5319, MCC: -0.0118, F1: 0.6333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69824 | val 0.79791
  Epoch 011 - train 0.68945 | val 0.80570
  Classification -> best τ=0.525 (val F1=0.2677)
  Directional -> Accuracy: 0.4286, MCC: 0.0335, F1: 0.5172

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67959 | val 0.70218
  Epoch 011 - train 0.67962 | val 0.70252
  Classification -> best τ=0.460 (val F1=0.2197)
  Directional -> Accuracy: 0.5000, MCC: -0.0245, F1: 0.5957

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67799 | val 0.72097
  Epoch 013 - train 0.68088 | val 0.72461
  Classification -> best τ=0.405 (val F1=0.3450)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71004 | val 0.79056
  Epoch 011 - train 0.70730 | val 0.79504
  Classification -> best τ=0.470 (val F1=0.1463)
  Directional -> Accuracy: 0.4681, MCC: -0.0644, F1: 0.2424

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69919 | val 0.74143
  Epoch 011 - train 0.67390 | val 0.74745
  Classification -> best τ=0.525 (val F1=0.0552)
  Directional -> Accuracy: 0.4545, MCC: 0.1329, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70685 | val 0.87065
  Epoch 011 - train 0.68524 | val 0.87861
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71210 | val 0.98481
  Epoch 011 - train 0.73026 | val 0.98179
  Classification -> best τ=0.445 (val F1=0.0636)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67489 | val 0.76956
  Epoch 011 - train 0.66934 | val 0.77530
  Classification -> best τ=0.520 (val F1=0.0199)
  Directional -> Accuracy: 0.5263, MCC: 0.0301, F1: 0.3415

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69744 | val 0.68964
  Epoch 020 - train 0.68509 | val 0.69603
  Classification -> best τ=0.620 (val F1=0.0935)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67149 | val 0.70848
  Epoch 011 - train 0.67756 | val 0.70766
  Classification -> best τ=0.495 (val F1=0.1168)
  Directional -> Accuracy: 0.5536, MCC: 0.1176, F1: 0.5098

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67740 | val 0.69348
  Epoch 011 - train 0.66515 | val 0.69509

[I 2026-02-20 00:00:07,143] Trial 40 finished with value: 0.186280662128779 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 3.985512870465257e-05, 'weight_decay': 5.5257702193479466e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.8189972280783295, 'early_stopping_min_delta': 0.007420900438807705}. Best is trial 22 with value: 0.26179994200866186.

  Classification -> best τ=0.485 (val F1=0.1790)
  Directional -> Accuracy: 0.5246, MCC: 0.0091, F1: 0.0645

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.186280662128779
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66685 | val 0.78958
  Epoch 020 - train 0.63159 | val 0.97920
  Epoch 023 - train 0.63771 | val 1.07125
  Classification -> best τ=0.755 (val F1=0.2346)
  Directional -> Accuracy: 0.5949, MCC: 0.1868, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62804 | val 0.90073
  Epoch 020 - train 0.61503 | val 0.92348
  Epoch 021 - train 0.61609 | val 0.93370
  Classification -> best τ=0.520 (val F1=0.1193)
  Directional -> Accuracy: 0.6250, MCC: 0.2928, F1: 0.7500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65693 | val 0.83059
  Epoch 020 - train 0.64121 | val 0.78121
  Epoch 022 - train 0.63304 | val 0.77209
  Classification -> best τ=0.620 (val F1=0.3077)
  Directional -> Accuracy: 0.4694, MCC: -0.0183, F1: 0.1333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64103 | val 0.74002
  Epoch 020 - train 0.63352 | val 0.70849
  Epoch 021 - train 0.64783 | val 0.71333
  Classification -> best τ=0.570 (val F1=0.1156)
  Directional -> Accuracy: 0.5584, MCC: 0.1186, F1: 0.5750

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67159 | val 1.39824
  Epoch 020 - train 0.57490 | val 1.57558
  Epoch 023 - train 0.55836 | val 1.72403
  Classification -> best τ=0.735 (val F1=0.4557)
  Directional -> Accuracy: 0.5849, MCC: 0.2403, F1: 0.4500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59813 | val 0.78994
  Epoch 020 - train 0.56555 | val 0.74941
  Epoch 023 - train 0.55718 | val 0.75441
  Classification -> best τ=0.515 (val F1=0.2981)
  Directional -> Accuracy: 0.4878, MCC: -0.0263, F1: 0.4615

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67935 | val 0.85326
  Epoch 020 - train 0.65516 | val 1.12511
  Epoch 021 - train 0.62770 | val 1.13050
  Classification -> best τ=0.425 (val F1=0.3115)
  Directional -> Accuracy: 0.5634, MCC: 0.1787, F1: 0.5753

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60577 | val 0.74568
  Epoch 020 - train 0.57586 | val 0.76524
  Epoch 022 - train 0.62418 | val 0.78972
  Classification -> best τ=0.550 (val F1=0.3043)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62163 | val 0.72497
  Epoch 020 - train 0.59949 | val 0.78193
  Epoch 021 - train 0.60898 | val 0.77578
  Classification -> best τ=0.480 (val F1=0.2958)
  Directional -> Accuracy: 0.5814, MCC: 0.0710, F1: 0.3571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61286 | val 1.54423
  Epoch 020 - train 0.53189 | val 1.71150
  Epoch 021 - train 0.56757 | val 1.76031
  Classification -> best τ=0.315 (val F1=0.2365)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66484 | val 0.66732
  Epoch 020 - train 0.57758 | val 0.68661
  Epoch 030 - train 0.62223 | val 0.68959
  Classification -> best τ=0.430 (val F1=0.1951)
  Directional -> Accuracy: 0.6154, MCC: 0.2694, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69962 | val 0.72332
  Epoch 020 - train 0.62636 | val 0.85505
  Epoch 027 - train 0.62865 | val 0.92284
  Classification -> best τ=0.345 (val F1=0.1439)
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56473 | val 1.19194
  Epoch 020 - train 0.54982 | val 0.80438
  Epoch 021 - train 0.55315 | val 0.85261
  Classification -> best τ=0.425 (val F1=0.2135)
  Directional -> Accuracy: 0.4889, MCC: 0.1410, F1: 0.6462

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64488 | val 0.93552
  Epoch 020 - train 0.62798 | val 1.19804
  Epoch 021 - train 0.63571 | val 1.19932
  Classification -> best τ=0.525 (val F1=0.4287)
  Directional -> Accuracy: 0.5238, MCC: 0.0465, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65789 | val 1.33160
  Epoch 020 - train 0.57954 | val 1.71821
  Epoch 021 - train 0.58733 | val 1.81752
  Classification -> best τ=0.530 (val F1=0.0969)
  Directional -> Accuracy: 0.5556, MCC: 0.1520, F1: 0.2000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60411 | val 1.19646
  Epoch 020 - train 0.58384 | val 1.30923
  Epoch 021 - train 0.59310 | val 1.33858
  Classification -> best τ=0.565 (val F1=0.2114)
  Directional -> Accuracy: 0.5417, MCC: 0.1564, F1: 0.4000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64298 | val 1.70625
  Epoch 020 - train 0.64294 | val 1.81880
  Epoch 021 - train 0.63680 | val 1.79891
  Classification -> best τ=0.645 (val F1=0.1559)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64661 | val 1.02867
  Epoch 020 - train 0.63162 | val 1.12751
  Epoch 021 - train 0.62730 | val 1.13279
  Classification -> best τ=0.525 (val F1=0.2436)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65681 | val 0.80082
  Epoch 020 - train 0.60795 | val 0.89458
  Epoch 023 - train 0.60660 | val 0.93088
  Classification -> best τ=0.435 (val F1=0.2834)
  Directional -> Accuracy: 0.4627, MCC: 0.0488, F1: 0.2800

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62366 | val 0.83349
  Epoch 020 - train 0.59255 | val 0.83276
  Epoch 021 - train 0.57698 | val 0.84273
  Classification -> best τ=0.360 (val F1=0.2137)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61697 | val 0.80183
  Epoch 020 - train 0.61799 | val 0.90692
  Epoch 021 - train 0.57044 | val 0.89802
  Classification -> best τ=0.545 (val F1=0.2065)
  Directional -> Accuracy: 0.5400, MCC: 0.0726, F1: 0.5965

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68947 | val 0.70770
  Epoch 020 - train 0.66563 | val 0.73982
  Epoch 022 - train 0.64263 | val 0.74289
  Classification -> best τ=0.565 (val F1=0.3322)
  Directional -> Accuracy: 0.4265, MCC: -0.1639, F1: 0.2642

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67967 | val 0.77358
  Epoch 020 - train 0.62752 | val 0.89677
  Epoch 021 - train 0.62646 | val 0.90201
  Classification -> best τ=0.565 (val F1=0.3022)
  Directional -> Accuracy: 0.5500, MCC: 0.2039, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62253 | val 0.90405
  Epoch 020 - train 0.58352 | val 0.76176
  Epoch 021 - train 0.60280 | val 0.76859
  Classification -> best τ=0.505 (val F1=0.1459)
  Directional -> Accuracy: 0.5294, MCC: 0.0800, F1: 0.6098

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61876 | val 1.03635
  Epoch 020 - train 0.59749 | val 1.03359
  Epoch 022 - train 0.57086 | val 1.04368
  Classification -> best τ=0.470 (val F1=0.4766)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58711 | val 0.67239
  Epoch 020 - train 0.52749 | val 1.23998
  Epoch 030 - train 0.51914 | val 1.37288
  Classification -> best τ=0.380 (val F1=0.3812)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63260 | val 1.04586
  Epoch 020 - train 0.65820 | val 0.82941
  Epoch 021 - train 0.61891 | val 0.84557
  Classification -> best τ=0.455 (val F1=0.1612)
  Directional -> Accuracy: 0.5333, MCC: 0.0726, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68069 | val 1.15818
  Epoch 020 - train 0.60449 | val 1.34350
  Epoch 022 - train 0.64608 | val 1.35664
  Classification -> best τ=0.410 (val F1=0.3066)
  Directional -> Accuracy: 0.5424, MCC: 0.2518, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60973 | val 1.11340
  Epoch 020 - train 0.57045 | val 1.31475
  Epoch 021 - train 0.55124 | val 1.33797
  Classification -> best τ=0.455 (val F1=0.1465)
  Directional -> Accuracy: 0.5909, MCC: 0.1843, F1: 0.5909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65309 | val 1.01378
  Epoch 020 - train 0.63157 | val 1.07315
  Epoch 021 - train 0.58181 | val 1.07558
  Classification -> best τ=0.495 (val F1=0.0767)
  Directional -> Accuracy: 0.5217, MCC: 0.1491, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67802 | val 0.80422
  Epoch 020 - train 0.66264 | val 0.75987
  Epoch 023 - train 0.62107 | val 0.77267
  Classification -> best τ=0.470 (val F1=0.2645)
  Directional -> Accuracy: 0.5652, MCC: 0.1006, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60877 | val 0.97989
  Epoch 020 - train 0.61688 | val 1.09156
  Epoch 021 - train 0.59521 | val 1.04709
  Classification -> best τ=0.470 (val F1=0.1895)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67632 | val 0.71581
  Epoch 020 - train 0.58972 | val 0.92120
  Epoch 024 - train 0.57538 | val 0.94445
  Classification -> best τ=0.320 (val F1=0.3565)
  Directional -> Accuracy: 0.5333, MCC: 0.0895, F1: 0.5205

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65874 | val 0.70422
  Epoch 020 - train 0.58104 | val 0.74717
  Epoch 027 - train 0.61029 | val 0.75109
  Classification -> best τ=0.510 (val F1=0.4114)
  Directional -> Accuracy: 0.5366, MCC: 0.0998, F1: 0.6275

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64831 | val 1.22086
  Epoch 020 - train 0.57550 | val 1.47136
  Epoch 021 - train 0.60386 | val 1.40339
  Classification -> best τ=0.465 (val F1=0.3201)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64950 | val 0.75733
  Epoch 020 - train 0.60622 | val 0.75507
  Epoch 022 - train 0.58568 | val 0.75400
  Classification -> best τ=0.325 (val F1=0.3271)
  Directional -> Accuracy: 0.5797, MCC: 0.1105, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59397 | val 0.87185
  Epoch 020 - train 0.54878 | val 0.83642
  Epoch 022 - train 0.59229 | val 0.83149
  Classification -> best τ=0.455 (val F1=0.3148)
  Directional -> Accuracy: 0.5778, MCC: 0.2222, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65109 | val 0.86136
  Epoch 020 - train 0.59086 | val 0.81992
  Epoch 021 - train 0.60953 | val 0.83104
  Classification -> best τ=0.510 (val F1=0.2494)
  Directional -> Accuracy: 0.5424, MCC: 0.1069, F1: 0.5970

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59328 | val 2.17372
  Epoch 020 - train 0.57587 | val 2.29540
  Epoch 021 - train 0.54077 | val 2.32799
  Classification -> best τ=0.490 (val F1=0.2032)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62153 | val 0.74027
  Epoch 020 - train 0.56679 | val 0.73808
  Epoch 024 - train 0.54707 | val 0.75237
  Classification -> best τ=0.375 (val F1=0.3420)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62795 | val 0.72172
  Epoch 020 - train 0.52667 | val 0.73852
  Epoch 030 - train 0.54741 | val 0.82163
  Classification -> best τ=0.385 (val F1=0.3194)
  Directional -> Accuracy: 0.5366, MCC: 0.0716, F1: 0.5581

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64505 | val 1.56463
  Epoch 020 - train 0.60346 | val 1.93405
  Epoch 021 - train 0.59012 | val 1.92347
  Classification -> best τ=0.470 (val F1=0.1807)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63785 | val 0.80707
  Epoch 020 - train 0.63138 | val 0.87504
  Epoch 021 - train 0.64697 | val 0.87266
  Classification -> best τ=0.510 (val F1=0.1967)
  Directional -> Accuracy: 0.5102, MCC: 0.0103, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62132 | val 1.30263
  Epoch 020 - train 0.49592 | val 1.52101
  Epoch 021 - train 0.54597 | val 1.56945
  Classification -> best τ=0.465 (val F1=0.0323)
  Directional -> Accuracy: 0.5319, MCC: 0.0550, F1: 0.5769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64613 | val 1.09433
  Epoch 020 - train 0.59447 | val 1.10821
  Epoch 021 - train 0.55864 | val 1.09434
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68997 | val 0.68520
  Epoch 020 - train 0.64211 | val 0.77596
  Epoch 025 - train 0.62307 | val 0.78982
  Classification -> best τ=0.545 (val F1=0.2492)
  Directional -> Accuracy: 0.5517, MCC: 0.2036, F1: 0.4091

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60300 | val 1.25213
  Epoch 020 - train 0.59012 | val 1.34774
  Epoch 022 - train 0.58864 | val 1.37254
  Classification -> best τ=0.760 (val F1=0.4783)
  Directional -> Accuracy: 0.4746, MCC: -0.0488, F1: 0.5079

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61098 | val 1.35956
  Epoch 020 - train 0.60768 | val 1.38843
  Epoch 021 - train 0.60574 | val 1.40283
  Classification -> best τ=0.485 (val F1=0.0321)
  Directional -> Accuracy: 0.5893, MCC: 0.1895, F1: 0.7089

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-20 00:02:09,655] Trial 41 finished with value: 0.2442764838763856 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0021269915562089157, 'weight_decay': 0.0003020960849545118, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.167303020249757, 'early_stopping_min_delta': 0.0011486846879426122}. Best is trial 22 with value: 0.26179994200866186.

  Classification -> best τ=0.480 (val F1=0.2307)
  Directional -> Accuracy: 0.4444, MCC: -0.1500, F1: 0.2553

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2442764838763856
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66816 | val 0.69208
  Epoch 020 - train 0.60307 | val 0.84863
  Epoch 026 - train 0.57350 | val 0.88506
  Classification -> best τ=0.670 (val F1=0.2727)
  Directional -> Accuracy: 0.5823, MCC: 0.1230, F1: 0.3774

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61603 | val 0.75783
  Epoch 020 - train 0.54945 | val 0.81411
  Epoch 022 - train 0.52825 | val 0.81671
  Classification -> best τ=0.445 (val F1=0.1654)
  Directional -> Accuracy: 0.6250, MCC: 0.2305, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65178 | val 0.80072
  Epoch 020 - train 0.58693 | val 0.97917
  Epoch 022 - train 0.60978 | val 1.02661
  Classification -> best τ=0.505 (val F1=0.3307)
  Directional -> Accuracy: 0.4694, MCC: -0.0183, F1: 0.1333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65677 | val 0.67298
  Epoch 020 - train 0.63251 | val 0.68208
  Epoch 029 - train 0.57361 | val 0.68701
  Classification -> best τ=0.450 (val F1=0.3050)
  Directional -> Accuracy: 0.4805, MCC: 0.1491, F1: 0.0909

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63844 | val 1.18533
  Epoch 020 - train 0.51285 | val 2.03219
  Epoch 023 - train 0.52377 | val 2.21354
  Classification -> best τ=0.670 (val F1=0.4836)
  Directional -> Accuracy: 0.6604, MCC: 0.3457, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56534 | val 0.72150
  Epoch 020 - train 0.52576 | val 0.70691
  Epoch 021 - train 0.51887 | val 0.71298
  Classification -> best τ=0.495 (val F1=0.3052)
  Directional -> Accuracy: 0.5366, MCC: 0.1969, F1: 0.6545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65818 | val 1.12418
  Epoch 020 - train 0.60697 | val 1.30926
  Epoch 021 - train 0.60801 | val 1.29133
  Classification -> best τ=0.510 (val F1=0.1930)
  Directional -> Accuracy: 0.5493, MCC: 0.0773, F1: 0.4667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62355 | val 0.64245
  Epoch 020 - train 0.49933 | val 0.96989
  Epoch 024 - train 0.47106 | val 1.11130
  Classification -> best τ=0.480 (val F1=0.3043)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66930 | val 0.87729
  Epoch 020 - train 0.55714 | val 1.10260
  Epoch 023 - train 0.52409 | val 1.03287
  Classification -> best τ=0.595 (val F1=0.4150)
  Directional -> Accuracy: 0.5581, MCC: -0.1786, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57436 | val 1.20565
  Epoch 020 - train 0.54455 | val 1.84483
  Epoch 022 - train 0.49541 | val 1.93118
  Classification -> best τ=0.325 (val F1=0.1092)
  Directional -> Accuracy: 0.5000, MCC: 0.0039, F1: 0.4706

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63772 | val 1.28432
  Epoch 020 - train 0.60983 | val 1.46578
  Epoch 022 - train 0.56817 | val 1.54772
  Classification -> best τ=0.550 (val F1=0.3963)
  Directional -> Accuracy: 0.6154, MCC: 0.2694, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64024 | val 1.00476
  Epoch 020 - train 0.59047 | val 1.43625
  Epoch 021 - train 0.59832 | val 1.46855
  Classification -> best τ=0.490 (val F1=0.1721)
  Directional -> Accuracy: 0.6667, MCC: 0.3459, F1: 0.6154

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55299 | val 0.68147
  Epoch 020 - train 0.46957 | val 1.00460
  Epoch 029 - train 0.46855 | val 1.10869
  Classification -> best τ=0.520 (val F1=0.2802)
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65026 | val 0.89260
  Epoch 020 - train 0.59385 | val 1.37956
  Epoch 023 - train 0.57987 | val 1.53887
  Classification -> best τ=0.550 (val F1=0.4300)
  Directional -> Accuracy: 0.5238, MCC: 0.0474, F1: 0.5161

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61803 | val 1.98879
  Epoch 020 - train 0.51323 | val 2.63986
  Epoch 021 - train 0.54657 | val 2.81548
  Classification -> best τ=0.510 (val F1=0.1154)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63966 | val 0.98480
  Epoch 020 - train 0.57376 | val 1.12509
  Epoch 021 - train 0.55785 | val 1.08941
  Classification -> best τ=0.595 (val F1=0.2218)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3462

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63508 | val 1.67619
  Epoch 020 - train 0.58517 | val 2.03952
  Epoch 021 - train 0.60601 | val 2.06651
  Classification -> best τ=0.675 (val F1=0.1189)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62717 | val 0.85708
  Epoch 020 - train 0.60752 | val 0.91317
  Epoch 021 - train 0.60659 | val 0.93102
  Classification -> best τ=0.680 (val F1=0.1900)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63915 | val 0.70633
  Epoch 020 - train 0.59100 | val 1.01962
  Epoch 026 - train 0.55075 | val 1.08531
  Classification -> best τ=0.245 (val F1=0.3443)
  Directional -> Accuracy: 0.5075, MCC: 0.0430, F1: 0.5075

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58302 | val 0.79545
  Epoch 020 - train 0.53830 | val 0.76891
  Epoch 021 - train 0.51712 | val 0.77954
  Classification -> best τ=0.715 (val F1=0.2564)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60509 | val 0.98318
  Epoch 020 - train 0.55281 | val 1.29515
  Epoch 021 - train 0.51174 | val 1.25378
  Classification -> best τ=0.525 (val F1=0.2303)
  Directional -> Accuracy: 0.6400, MCC: 0.1825, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65390 | val 0.79370
  Epoch 020 - train 0.61800 | val 0.80455
  Epoch 026 - train 0.57529 | val 0.84125
  Classification -> best τ=0.505 (val F1=0.3554)
  Directional -> Accuracy: 0.4706, MCC: -0.0589, F1: 0.4545

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63172 | val 0.83827
  Epoch 020 - train 0.61764 | val 0.91401
  Epoch 021 - train 0.55261 | val 0.96836
  Classification -> best τ=0.770 (val F1=0.2763)
  Directional -> Accuracy: 0.4667, MCC: 0.0710, F1: 0.2727

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63261 | val 0.71566
  Epoch 020 - train 0.53706 | val 0.70092
  Epoch 030 - train 0.50488 | val 0.70370
  Classification -> best τ=0.390 (val F1=0.2357)
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60532 | val 0.92694
  Epoch 020 - train 0.51185 | val 0.87287
  Epoch 023 - train 0.49913 | val 0.89395
  Classification -> best τ=0.610 (val F1=0.4815)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52180 | val 2.57030
  Epoch 020 - train 0.48012 | val 4.15026
  Epoch 023 - train 0.47474 | val 3.93220
  Classification -> best τ=0.660 (val F1=0.2915)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.3429

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65476 | val 0.76294
  Epoch 020 - train 0.60207 | val 0.79541
  Epoch 030 - train 0.59747 | val 0.70385
  Classification -> best τ=0.445 (val F1=0.1612)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61600 | val 1.01790
  Epoch 020 - train 0.57061 | val 1.26574
  Epoch 021 - train 0.56814 | val 1.28190
  Classification -> best τ=0.655 (val F1=0.1531)
  Directional -> Accuracy: 0.4237, MCC: -0.1370, F1: 0.4138

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67820 | val 1.77193
  Epoch 020 - train 0.55429 | val 2.13403
  Epoch 021 - train 0.46544 | val 2.15508
  Classification -> best τ=0.550 (val F1=0.3006)
  Directional -> Accuracy: 0.5227, MCC: 0.0311, F1: 0.6038

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59338 | val 0.82018
  Epoch 020 - train 0.53879 | val 0.92078
  Epoch 021 - train 0.54262 | val 0.93786
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65237 | val 0.80556
  Epoch 020 - train 0.59835 | val 0.91419
  Epoch 021 - train 0.62542 | val 0.92691
  Classification -> best τ=0.500 (val F1=0.0781)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60017 | val 0.93975
  Epoch 020 - train 0.53389 | val 1.18069
  Epoch 021 - train 0.50456 | val 1.18981
  Classification -> best τ=0.450 (val F1=0.2535)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65782 | val 0.72577
  Epoch 020 - train 0.57797 | val 0.82002
  Epoch 021 - train 0.57860 | val 0.84278
  Classification -> best τ=0.355 (val F1=0.3290)
  Directional -> Accuracy: 0.5067, MCC: 0.0652, F1: 0.4308

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60415 | val 0.73814
  Epoch 020 - train 0.54833 | val 0.75956
  Epoch 021 - train 0.49894 | val 0.76376
  Classification -> best τ=0.490 (val F1=0.2774)
  Directional -> Accuracy: 0.5366, MCC: 0.0998, F1: 0.6275

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64055 | val 1.32928
  Epoch 020 - train 0.53985 | val 1.72916
  Epoch 021 - train 0.56541 | val 1.64335
  Classification -> best τ=0.485 (val F1=0.3201)
  Directional -> Accuracy: 0.4783, MCC: 0.0022, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61558 | val 0.72927
  Epoch 020 - train 0.52143 | val 0.77109
  Epoch 028 - train 0.49428 | val 0.79867
  Classification -> best τ=0.150 (val F1=0.2241)
  Directional -> Accuracy: 0.6377, MCC: 0.2412, F1: 0.7059

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56276 | val 0.85130
  Epoch 020 - train 0.44881 | val 0.92365
  Epoch 021 - train 0.43601 | val 0.93780
  Classification -> best τ=0.455 (val F1=0.2260)
  Directional -> Accuracy: 0.4889, MCC: -0.0048, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63694 | val 1.20987
  Epoch 020 - train 0.57208 | val 1.12073
  Epoch 021 - train 0.53936 | val 1.19975
  Classification -> best τ=0.410 (val F1=0.2222)
  Directional -> Accuracy: 0.5424, MCC: 0.0915, F1: 0.5574

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58096 | val 1.78857
  Epoch 020 - train 0.45619 | val 2.13404
  Epoch 021 - train 0.50909 | val 2.24345
  Classification -> best τ=0.545 (val F1=0.1755)
  Directional -> Accuracy: 0.6122, MCC: 0.0861, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63429 | val 0.66196
  Epoch 020 - train 0.54943 | val 0.72782
  Epoch 030 - train 0.40584 | val 0.82376
  Classification -> best τ=0.425 (val F1=0.5709)
  Directional -> Accuracy: 0.4048, MCC: 0.1961, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62860 | val 1.03195
  Epoch 020 - train 0.42579 | val 1.48600
  Epoch 026 - train 0.40490 | val 1.40589
  Classification -> best τ=0.320 (val F1=0.5423)
  Directional -> Accuracy: 0.4634, MCC: -0.0701, F1: 0.4211

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63338 | val 1.38313
  Epoch 020 - train 0.54515 | val 1.88298
  Epoch 021 - train 0.53856 | val 1.93857
  Classification -> best τ=0.395 (val F1=0.2368)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68716 | val 1.00462
  Epoch 020 - train 0.65570 | val 1.38386
  Epoch 021 - train 0.62230 | val 1.40015
  Classification -> best τ=0.480 (val F1=0.1581)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53452 | val 1.78178
  Epoch 020 - train 0.45719 | val 2.25947
  Epoch 021 - train 0.41071 | val 2.32854
  Classification -> best τ=0.560 (val F1=0.5477)
  Directional -> Accuracy: 0.6383, MCC: 0.3459, F1: 0.6047

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59011 | val 0.96338
  Epoch 020 - train 0.46433 | val 1.20258
  Epoch 021 - train 0.47449 | val 1.10294
  Classification -> best τ=0.510 (val F1=0.3545)
  Directional -> Accuracy: 0.6429, MCC: 0.4714, F1: 0.6667

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65809 | val 0.67682
  Epoch 020 - train 0.61150 | val 0.69250
  Epoch 030 - train 0.61564 | val 0.73296
  Classification -> best τ=0.565 (val F1=0.2135)
  Directional -> Accuracy: 0.3966, MCC: -0.1802, F1: 0.2553

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62240 | val 1.77822
  Epoch 020 - train 0.58352 | val 1.79492
  Epoch 022 - train 0.57272 | val 1.78157
  Classification -> best τ=0.710 (val F1=0.3610)
  Directional -> Accuracy: 0.5424, MCC: 0.0865, F1: 0.5574

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60969 | val 1.71019
  Epoch 020 - train 0.56645 | val 1.85164
  Epoch 021 - train 0.56047 | val 1.77735
  Classification -> best τ=0.295 (val F1=0.1438)
  Directional -> Accuracy: 0.5357, MCC: 0.0199, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-20 00:04:15,380] Trial 42 finished with value: 0.268296303084699 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.004199507864796786, 'weight_decay': 0.000436056871943176, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3572459474155814, 'early_stopping_min_delta': 0.0009373669980318961}. Best is trial 42 with value: 0.268296303084699.

  Epoch 024 - train 0.58232 | val 0.78988
  Classification -> best τ=0.425 (val F1=0.1701)
  Directional -> Accuracy: 0.5238, MCC: 0.1037, F1: 0.6341

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.268296303084699
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66190 | val 0.71530
  Epoch 020 - train 0.61071 | val 0.74326
  Epoch 024 - train 0.58370 | val 0.79554
  Classification -> best τ=0.740 (val F1=0.2727)
  Directional -> Accuracy: 0.5190, MCC: -0.0792, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60489 | val 0.83012
  Epoch 020 - train 0.54048 | val 1.01308
  Epoch 021 - train 0.48554 | val 1.00592
  Classification -> best τ=0.405 (val F1=0.1264)
  Directional -> Accuracy: 0.6458, MCC: 0.3016, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64166 | val 0.86446
  Epoch 020 - train 0.59059 | val 1.36083
  Epoch 022 - train 0.56934 | val 1.36177
  Classification -> best τ=0.600 (val F1=0.3529)
  Directional -> Accuracy: 0.4694, MCC: -0.0509, F1: 0.4348

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69191 | val 0.71004
  Epoch 020 - train 0.60810 | val 0.72699
  Epoch 029 - train 0.54503 | val 0.76551
  Classification -> best τ=0.550 (val F1=0.2749)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59906 | val 2.02094
  Epoch 020 - train 0.51820 | val 2.60449
  Epoch 025 - train 0.47647 | val 2.65384
  Classification -> best τ=0.565 (val F1=0.3172)
  Directional -> Accuracy: 0.6415, MCC: 0.3018, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62377 | val 0.83664
  Epoch 020 - train 0.45597 | val 0.77313
  Epoch 023 - train 0.45065 | val 0.71524
  Classification -> best τ=0.505 (val F1=0.3052)
  Directional -> Accuracy: 0.5366, MCC: 0.0304, F1: 0.2400

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66322 | val 0.96676
  Epoch 020 - train 0.57348 | val 1.90290
  Epoch 021 - train 0.57439 | val 1.73988
  Classification -> best τ=0.565 (val F1=0.1805)
  Directional -> Accuracy: 0.5634, MCC: 0.1212, F1: 0.5079

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56449 | val 0.87182
  Epoch 020 - train 0.36720 | val 1.33979
  Epoch 028 - train 0.33846 | val 1.57348
  Classification -> best τ=0.310 (val F1=0.3536)
  Directional -> Accuracy: 0.5745, MCC: -0.1215, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60583 | val 0.95375
  Epoch 020 - train 0.55762 | val 1.27694
  Epoch 023 - train 0.49084 | val 1.19691
  Classification -> best τ=0.470 (val F1=0.3457)
  Directional -> Accuracy: 0.6047, MCC: 0.1996, F1: 0.5405

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59521 | val 0.92935
  Epoch 020 - train 0.48444 | val 1.00813
  Epoch 021 - train 0.51505 | val 1.11708
  Classification -> best τ=0.410 (val F1=0.1478)
  Directional -> Accuracy: 0.5139, MCC: 0.0607, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63539 | val 0.91013
  Epoch 020 - train 0.59174 | val 0.73084
  Epoch 024 - train 0.55326 | val 0.71620
  Classification -> best τ=0.490 (val F1=0.2633)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.0800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66830 | val 0.69974
  Epoch 020 - train 0.62201 | val 0.75297
  Epoch 024 - train 0.62883 | val 0.77594
  Classification -> best τ=0.700 (val F1=0.2075)
  Directional -> Accuracy: 0.5833, MCC: 0.2596, F1: 0.3243

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56497 | val 0.81922
  Epoch 020 - train 0.44438 | val 1.03352
  Epoch 021 - train 0.41773 | val 1.11834
  Classification -> best τ=0.520 (val F1=0.2253)
  Directional -> Accuracy: 0.5556, MCC: 0.0917, F1: 0.4118

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66196 | val 0.81634
  Epoch 020 - train 0.53631 | val 2.00242
  Epoch 023 - train 0.53111 | val 2.18441
  Classification -> best τ=0.435 (val F1=0.3727)
  Directional -> Accuracy: 0.4921, MCC: -0.0108, F1: 0.5676

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60781 | val 1.24446
  Epoch 020 - train 0.53201 | val 1.18385
  Epoch 022 - train 0.50462 | val 1.21265
  Classification -> best τ=0.595 (val F1=0.2833)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62042 | val 0.99240
  Epoch 020 - train 0.54269 | val 1.32029
  Epoch 022 - train 0.50684 | val 1.52678
  Classification -> best τ=0.415 (val F1=0.3372)
  Directional -> Accuracy: 0.5972, MCC: 0.1763, F1: 0.6813

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64103 | val 1.31955
  Epoch 020 - train 0.57975 | val 1.86346
  Epoch 021 - train 0.57636 | val 1.88134
  Classification -> best τ=0.650 (val F1=0.1162)
  Directional -> Accuracy: 0.3607, MCC: -0.2286, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67602 | val 0.80564
  Epoch 020 - train 0.64319 | val 1.00876
  Epoch 024 - train 0.60009 | val 1.08569
  Classification -> best τ=0.875 (val F1=0.1541)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64843 | val 0.90155
  Epoch 020 - train 0.56423 | val 1.35258
  Epoch 021 - train 0.53503 | val 1.37734
  Classification -> best τ=0.455 (val F1=0.3264)
  Directional -> Accuracy: 0.4925, MCC: 0.1905, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64742 | val 0.74511
  Epoch 020 - train 0.49749 | val 0.83228
  Epoch 027 - train 0.43469 | val 0.90149
  Classification -> best τ=0.440 (val F1=0.3404)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63409 | val 0.95308
  Epoch 020 - train 0.53045 | val 1.23645
  Epoch 029 - train 0.42385 | val 1.22349
  Classification -> best τ=0.370 (val F1=0.3761)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69700 | val 0.70026
  Epoch 020 - train 0.62306 | val 0.80387
  Epoch 026 - train 0.56977 | val 0.87477
  Classification -> best τ=0.585 (val F1=0.3873)
  Directional -> Accuracy: 0.4706, MCC: -0.0727, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66116 | val 0.72172
  Epoch 020 - train 0.56857 | val 0.90078
  Epoch 023 - train 0.55016 | val 0.86533
  Classification -> best τ=0.605 (val F1=0.2736)
  Directional -> Accuracy: 0.5333, MCC: 0.1240, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64745 | val 0.71286
  Epoch 020 - train 0.47435 | val 0.74103
  Epoch 026 - train 0.44290 | val 0.73467
  Classification -> best τ=0.450 (val F1=0.2008)
  Directional -> Accuracy: 0.5000, MCC: 0.0170, F1: 0.5952

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62772 | val 1.33633
  Epoch 020 - train 0.50234 | val 1.64221
  Epoch 023 - train 0.42129 | val 1.58366
  Classification -> best τ=0.635 (val F1=0.5493)
  Directional -> Accuracy: 0.5345, MCC: 0.1519, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52435 | val 0.87164
  Epoch 020 - train 0.34188 | val 1.04329
  Epoch 022 - train 0.35400 | val 1.01408
  Classification -> best τ=0.670 (val F1=0.1643)
  Directional -> Accuracy: 0.5510, MCC: 0.1633, F1: 0.5926

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64429 | val 0.71149
  Epoch 020 - train 0.58912 | val 0.70493
  Epoch 030 - train 0.55321 | val 0.75869
  Classification -> best τ=0.490 (val F1=0.1612)
  Directional -> Accuracy: 0.4889, MCC: -0.1814, F1: 0.6349

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61308 | val 1.70197
  Epoch 020 - train 0.54617 | val 2.56800
  Epoch 021 - train 0.52477 | val 2.62264
  Classification -> best τ=0.390 (val F1=0.1126)
  Directional -> Accuracy: 0.5593, MCC: 0.0000, F1: 0.7174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64329 | val 1.17338
  Epoch 020 - train 0.40737 | val 1.53223
  Epoch 022 - train 0.42632 | val 1.59406
  Classification -> best τ=0.615 (val F1=0.2345)
  Directional -> Accuracy: 0.5227, MCC: 0.1439, F1: 0.2222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59243 | val 1.03797
  Epoch 020 - train 0.45098 | val 1.51661
  Epoch 021 - train 0.42938 | val 1.51599
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65856 | val 0.72950
  Epoch 020 - train 0.61945 | val 0.86150
  Epoch 030 - train 0.55490 | val 0.87165
  Classification -> best τ=0.765 (val F1=0.2562)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59899 | val 0.95499
  Epoch 020 - train 0.40688 | val 2.15902
  Epoch 023 - train 0.34709 | val 2.25540
  Classification -> best τ=0.370 (val F1=0.3262)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66139 | val 0.66581
  Epoch 020 - train 0.58563 | val 0.81975
  Epoch 024 - train 0.56529 | val 0.82391
  Classification -> best τ=0.265 (val F1=0.3523)
  Directional -> Accuracy: 0.5333, MCC: 0.0971, F1: 0.5070

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68736 | val 0.69014
  Epoch 020 - train 0.48216 | val 0.87882
  Epoch 025 - train 0.44266 | val 0.91184
  Classification -> best τ=0.575 (val F1=0.1918)
  Directional -> Accuracy: 0.5610, MCC: 0.1504, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61094 | val 1.75229
  Epoch 020 - train 0.46140 | val 2.32559
  Epoch 021 - train 0.46791 | val 2.28771
  Classification -> best τ=0.430 (val F1=0.3636)
  Directional -> Accuracy: 0.5217, MCC: 0.2421, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66068 | val 0.82491
  Epoch 020 - train 0.52360 | val 0.87521
  Epoch 025 - train 0.47848 | val 0.89036
  Classification -> best τ=0.120 (val F1=0.3498)
  Directional -> Accuracy: 0.6087, MCC: 0.1735, F1: 0.6897

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61261 | val 1.01568
  Epoch 020 - train 0.43468 | val 1.29607
  Epoch 021 - train 0.52652 | val 1.31808
  Classification -> best τ=0.390 (val F1=0.2980)
  Directional -> Accuracy: 0.5778, MCC: 0.1771, F1: 0.4865

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63250 | val 0.79561
  Epoch 020 - train 0.53008 | val 0.74724
  Epoch 024 - train 0.51254 | val 0.77377
  Classification -> best τ=0.265 (val F1=0.1558)
  Directional -> Accuracy: 0.4915, MCC: 0.0092, F1: 0.5833

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55348 | val 1.49748
  Epoch 020 - train 0.39648 | val 1.61142
  Epoch 021 - train 0.37776 | val 1.64943
  Classification -> best τ=0.435 (val F1=0.3249)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62859 | val 0.74133
  Epoch 020 - train 0.53105 | val 0.96213
  Epoch 028 - train 0.38171 | val 1.08922
  Classification -> best τ=0.400 (val F1=0.5214)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.53242 | val 0.93492
  Epoch 020 - train 0.38022 | val 0.75873
  Epoch 024 - train 0.27501 | val 0.85830
  Classification -> best τ=0.250 (val F1=0.3194)
  Directional -> Accuracy: 0.5366, MCC: 0.0719, F1: 0.6415

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65346 | val 1.60575
  Epoch 020 - train 0.45779 | val 3.08046
  Epoch 025 - train 0.40166 | val 3.72174
  Classification -> best τ=0.380 (val F1=0.3504)
  Directional -> Accuracy: 0.5714, MCC: 0.1704, F1: 0.6733

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62656 | val 1.35764
  Epoch 020 - train 0.59062 | val 1.84128
  Epoch 021 - train 0.59947 | val 1.92949
  Classification -> best τ=0.595 (val F1=0.2385)
  Directional -> Accuracy: 0.5306, MCC: 0.0599, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50771 | val 2.04848
  Epoch 020 - train 0.32042 | val 3.47613
  Epoch 021 - train 0.42074 | val 3.59083
  Classification -> best τ=0.640 (val F1=0.1316)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50464 | val 1.33441
  Epoch 020 - train 0.39964 | val 2.25266
  Epoch 021 - train 0.40366 | val 2.25276
  Classification -> best τ=0.440 (val F1=0.1765)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68645 | val 0.70227
  Epoch 020 - train 0.66118 | val 1.00693
  Epoch 028 - train 0.61766 | val 1.54383
  Classification -> best τ=0.470 (val F1=0.2780)
  Directional -> Accuracy: 0.7069, MCC: 0.4160, F1: 0.7213

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57022 | val 1.71817
  Epoch 020 - train 0.52697 | val 2.17436
  Epoch 022 - train 0.53689 | val 2.01173
  Classification -> best τ=0.555 (val F1=0.3591)
  Directional -> Accuracy: 0.5254, MCC: 0.0550, F1: 0.5625

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61153 | val 1.68141
  Epoch 020 - train 0.54126 | val 3.01273
  Epoch 022 - train 0.57369 | val 2.98291
  Classification -> best τ=0.270 (val F1=0.1502)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...


[I 2026-02-20 00:06:24,064] Trial 43 finished with value: 0.26727801222210007 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.007399337800455097, 'weight_decay': 0.00017609995852481636, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3485517686933117, 'early_stopping_min_delta': 0.00045198832862771126}. Best is trial 42 with value: 0.268296303084699.

  Epoch 022 - train 0.60843 | val 0.85728
  Classification -> best τ=0.460 (val F1=0.2539)
  Directional -> Accuracy: 0.5873, MCC: 0.1691, F1: 0.4800

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26727801222210007
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66372 | val 0.67424
  Epoch 020 - train 0.61417 | val 0.85282
  Epoch 026 - train 0.59742 | val 0.91743
  Classification -> best τ=0.680 (val F1=0.2727)
  Directional -> Accuracy: 0.5949, MCC: 0.1868, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63221 | val 0.76177
  Epoch 020 - train 0.51178 | val 0.76577
  Epoch 021 - train 0.56236 | val 0.76249
  Classification -> best τ=0.375 (val F1=0.0542)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60977 | val 0.85860
  Epoch 020 - train 0.57022 | val 1.03106
  Epoch 021 - train 0.58117 | val 1.02599
  Classification -> best τ=0.485 (val F1=0.2722)
  Directional -> Accuracy: 0.4898, MCC: 0.0696, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62693 | val 0.91199
  Epoch 020 - train 0.58563 | val 0.90331
  Epoch 021 - train 0.58703 | val 0.89270
  Classification -> best τ=0.575 (val F1=0.2877)
  Directional -> Accuracy: 0.5584, MCC: 0.0881, F1: 0.6458

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63991 | val 1.01630
  Epoch 020 - train 0.51633 | val 2.31056
  Epoch 023 - train 0.52397 | val 2.54716
  Classification -> best τ=0.455 (val F1=0.4804)
  Directional -> Accuracy: 0.6604, MCC: 0.3186, F1: 0.6786

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61111 | val 0.82814
  Epoch 020 - train 0.50345 | val 0.73492
  Epoch 022 - train 0.47704 | val 0.79657
  Classification -> best τ=0.520 (val F1=0.2521)
  Directional -> Accuracy: 0.5610, MCC: 0.1021, F1: 0.2500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65320 | val 1.03038
  Epoch 020 - train 0.59740 | val 1.34713
  Epoch 021 - train 0.58646 | val 1.45887
  Classification -> best τ=0.565 (val F1=0.2085)
  Directional -> Accuracy: 0.5915, MCC: 0.0754, F1: 0.2564

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56371 | val 0.82584
  Epoch 020 - train 0.44181 | val 1.12568
  Epoch 025 - train 0.46540 | val 1.18864
  Classification -> best τ=0.505 (val F1=0.2921)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67142 | val 0.66712
  Epoch 020 - train 0.49387 | val 1.22094
  Epoch 030 - train 0.39469 | val 1.04353
  Classification -> best τ=0.730 (val F1=0.3890)
  Directional -> Accuracy: 0.5814, MCC: -0.1248, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58438 | val 1.20507
  Epoch 020 - train 0.51786 | val 1.70521
  Epoch 022 - train 0.47746 | val 1.60994
  Classification -> best τ=0.545 (val F1=0.1092)
  Directional -> Accuracy: 0.5139, MCC: -0.0032, F1: 0.4068

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69445 | val 0.74054
  Epoch 020 - train 0.53866 | val 0.75602
  Epoch 023 - train 0.50985 | val 0.76645
  Classification -> best τ=0.390 (val F1=0.2250)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68588 | val 0.80036
  Epoch 020 - train 0.60912 | val 0.88741
  Epoch 021 - train 0.58165 | val 0.88860
  Classification -> best τ=0.500 (val F1=0.1452)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.5538

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67392 | val 0.66645
  Epoch 020 - train 0.52288 | val 1.21603
  Epoch 030 - train 0.45216 | val 1.33306
  Classification -> best τ=0.630 (val F1=0.3123)
  Directional -> Accuracy: 0.5333, MCC: 0.0857, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64996 | val 0.73272
  Epoch 020 - train 0.55863 | val 1.28805
  Epoch 026 - train 0.52170 | val 1.54790
  Classification -> best τ=0.565 (val F1=0.3610)
  Directional -> Accuracy: 0.4762, MCC: -0.0453, F1: 0.5217

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60496 | val 2.29404
  Epoch 020 - train 0.52143 | val 3.23410
  Epoch 021 - train 0.51884 | val 3.28050
  Classification -> best τ=0.625 (val F1=0.1254)
  Directional -> Accuracy: 0.5370, MCC: 0.0741, F1: 0.5283

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59422 | val 1.14955
  Epoch 020 - train 0.55682 | val 1.11197
  Epoch 021 - train 0.54148 | val 1.08266
  Classification -> best τ=0.610 (val F1=0.3085)
  Directional -> Accuracy: 0.5417, MCC: 0.0989, F1: 0.5217

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65480 | val 2.38812
  Epoch 020 - train 0.59378 | val 2.46433
  Epoch 021 - train 0.57792 | val 2.50483
  Classification -> best τ=0.760 (val F1=0.1162)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64848 | val 0.86048
  Epoch 020 - train 0.57597 | val 0.89477
  Epoch 022 - train 0.56928 | val 0.88259
  Classification -> best τ=0.830 (val F1=0.1541)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62187 | val 0.89567
  Epoch 020 - train 0.54820 | val 1.12310
  Epoch 021 - train 0.55373 | val 1.13677
  Classification -> best τ=0.480 (val F1=0.1859)
  Directional -> Accuracy: 0.4328, MCC: 0.0103, F1: 0.1364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61301 | val 0.71222
  Epoch 020 - train 0.48762 | val 0.98875
  Epoch 025 - train 0.44993 | val 1.06060
  Classification -> best τ=0.405 (val F1=0.2946)
  Directional -> Accuracy: 0.4416, MCC: -0.1257, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58650 | val 1.59375
  Epoch 020 - train 0.50284 | val 1.22296
  Epoch 021 - train 0.49621 | val 1.24150
  Classification -> best τ=0.490 (val F1=0.1842)
  Directional -> Accuracy: 0.6200, MCC: 0.0505, F1: 0.7595

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65594 | val 0.73301
  Epoch 020 - train 0.60007 | val 0.83260
  Epoch 022 - train 0.63828 | val 0.83608
  Classification -> best τ=0.495 (val F1=0.2648)
  Directional -> Accuracy: 0.4559, MCC: -0.1019, F1: 0.5647

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61318 | val 0.96380
  Epoch 020 - train 0.55855 | val 0.85925
  Epoch 021 - train 0.58146 | val 0.87317
  Classification -> best τ=0.635 (val F1=0.2763)
  Directional -> Accuracy: 0.5333, MCC: 0.1757, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61176 | val 0.73786
  Epoch 020 - train 0.52343 | val 0.71359
  Epoch 021 - train 0.50884 | val 0.72317
  Classification -> best τ=0.545 (val F1=0.1296)
  Directional -> Accuracy: 0.4853, MCC: -0.0331, F1: 0.4444

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62849 | val 1.20214
  Epoch 020 - train 0.48630 | val 1.84931
  Epoch 022 - train 0.50058 | val 1.93877
  Classification -> best τ=0.580 (val F1=0.4792)
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49131 | val 0.86076
  Epoch 020 - train 0.46194 | val 0.87758
  Epoch 021 - train 0.43282 | val 0.88604
  Classification -> best τ=0.480 (val F1=0.2124)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64366 | val 0.81981
  Epoch 020 - train 0.61383 | val 0.92094
  Epoch 021 - train 0.58607 | val 0.92022
  Classification -> best τ=0.520 (val F1=0.1411)
  Directional -> Accuracy: 0.5333, MCC: 0.1327, F1: 0.5116

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63350 | val 1.20480
  Epoch 020 - train 0.57308 | val 2.41594
  Epoch 021 - train 0.55736 | val 2.36527
  Classification -> best τ=0.480 (val F1=0.1830)
  Directional -> Accuracy: 0.6102, MCC: 0.3111, F1: 0.5306

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55881 | val 0.98783
  Epoch 020 - train 0.43869 | val 1.86686
  Epoch 023 - train 0.52535 | val 2.07597
  Classification -> best τ=0.470 (val F1=0.2908)
  Directional -> Accuracy: 0.5455, MCC: 0.0793, F1: 0.6296

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58186 | val 1.02161
  Epoch 020 - train 0.52379 | val 1.11953
  Epoch 021 - train 0.48664 | val 1.09337
  Classification -> best τ=0.565 (val F1=0.2456)
  Directional -> Accuracy: 0.5652, MCC: 0.1644, F1: 0.3750

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68078 | val 0.67594
  Epoch 020 - train 0.55943 | val 0.75927
  Epoch 027 - train 0.55089 | val 0.77402
  Classification -> best τ=0.650 (val F1=0.1115)
  Directional -> Accuracy: 0.4565, MCC: -0.0269, F1: 0.1379

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58114 | val 1.00535
  Epoch 020 - train 0.48827 | val 1.12075
  Epoch 021 - train 0.46301 | val 1.11374
  Classification -> best τ=0.420 (val F1=0.4460)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60485 | val 0.68731
  Epoch 020 - train 0.54517 | val 0.83378
  Epoch 021 - train 0.55389 | val 0.86426
  Classification -> best τ=0.355 (val F1=0.3290)
  Directional -> Accuracy: 0.5200, MCC: 0.0733, F1: 0.4857

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63533 | val 0.72368
  Epoch 020 - train 0.55080 | val 0.76645
  Epoch 022 - train 0.55867 | val 0.76206
  Classification -> best τ=0.455 (val F1=0.3278)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61664 | val 1.52247
  Epoch 020 - train 0.56903 | val 1.92886
  Epoch 021 - train 0.53531 | val 1.90482
  Classification -> best τ=0.390 (val F1=0.2828)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62401 | val 0.65274
  Epoch 020 - train 0.49129 | val 0.73264
  Epoch 025 - train 0.47357 | val 0.73901
  Classification -> best τ=0.280 (val F1=0.3679)
  Directional -> Accuracy: 0.5652, MCC: 0.1903, F1: 0.5312

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55628 | val 0.91146
  Epoch 020 - train 0.51309 | val 0.97953
  Epoch 021 - train 0.53059 | val 0.95385
  Classification -> best τ=0.390 (val F1=0.2190)
  Directional -> Accuracy: 0.6000, MCC: 0.1988, F1: 0.6250

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66676 | val 0.90504
  Epoch 020 - train 0.52926 | val 1.36352
  Epoch 021 - train 0.56135 | val 1.38179
  Classification -> best τ=0.315 (val F1=0.1768)
  Directional -> Accuracy: 0.5085, MCC: 0.0453, F1: 0.5915

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52419 | val 1.79320
  Epoch 020 - train 0.43069 | val 2.38214
  Epoch 021 - train 0.43676 | val 2.39240
  Classification -> best τ=0.610 (val F1=0.1539)
  Directional -> Accuracy: 0.5714, MCC: 0.1237, F1: 0.6316

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60167 | val 0.67634
  Epoch 020 - train 0.46318 | val 0.66775
  Epoch 028 - train 0.35665 | val 0.66710
  Classification -> best τ=0.365 (val F1=0.5666)
  Directional -> Accuracy: 0.3810, MCC: 0.1581, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60480 | val 0.86646
  Epoch 020 - train 0.48523 | val 0.76228
  Epoch 021 - train 0.54536 | val 0.76029
  Classification -> best τ=0.470 (val F1=0.3780)
  Directional -> Accuracy: 0.6098, MCC: 0.2302, F1: 0.6800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59676 | val 1.14327
  Epoch 020 - train 0.48818 | val 1.82407
  Epoch 021 - train 0.51846 | val 1.86548
  Classification -> best τ=0.390 (val F1=0.2465)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63093 | val 1.24357
  Epoch 020 - train 0.60675 | val 1.29256
  Epoch 021 - train 0.55199 | val 1.32687
  Classification -> best τ=0.600 (val F1=0.0292)
  Directional -> Accuracy: 0.5510, MCC: 0.1485, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59416 | val 2.06863
  Epoch 020 - train 0.39517 | val 3.62031
  Epoch 021 - train 0.41680 | val 3.68567
  Classification -> best τ=0.555 (val F1=0.1414)
  Directional -> Accuracy: 0.6170, MCC: 0.2705, F1: 0.6087

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54585 | val 0.69608
  Epoch 020 - train 0.50434 | val 1.24985
  Epoch 025 - train 0.38224 | val 1.23863
  Classification -> best τ=0.715 (val F1=0.5231)
  Directional -> Accuracy: 0.6429, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67265 | val 0.70449
  Epoch 020 - train 0.63347 | val 0.90764
  Epoch 029 - train 0.62187 | val 1.01473
  Classification -> best τ=0.760 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62043 | val 1.12441
  Epoch 020 - train 0.55598 | val 1.71886
  Epoch 021 - train 0.50887 | val 1.67934
  Classification -> best τ=0.690 (val F1=0.3180)
  Directional -> Accuracy: 0.5424, MCC: 0.1225, F1: 0.6494

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65059 | val 1.47903
  Epoch 020 - train 0.58287 | val 1.87917
  Epoch 021 - train 0.56314 | val 1.91026
  Classification -> best τ=0.310 (val F1=0.1124)
  Directional -> Accuracy: 0.5536, MCC: 0.0852, F1: 0.6914

[87/88] Processing WMT...


[I 2026-02-20 00:08:26,171] Trial 44 finished with value: 0.2521124050906405 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.004371073921432498, 'weight_decay': 0.0001689134348473052, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.346290095025834, 'early_stopping_min_delta': 0.001879016171491318}. Best is trial 42 with value: 0.268296303084699.

  Epoch 023 - train 0.56883 | val 0.70205
  Classification -> best τ=0.380 (val F1=0.2626)
  Directional -> Accuracy: 0.5714, MCC: 0.1912, F1: 0.6494

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2521124050906405
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62226 | val 0.86613
  Epoch 020 - train 0.63296 | val 0.79474
  Classification -> best τ=0.500 (val F1=0.2571)
  Directional -> Accuracy: 0.5385, MCC: -0.0127, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60693 | val 0.75539
  Epoch 020 - train 0.48863 | val 0.69292
  Classification -> best τ=0.565 (val F1=0.2905)
  Directional -> Accuracy: 0.5532, MCC: 0.1421, F1: 0.5116

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66461 | val 1.09202
  Epoch 020 - train 0.60160 | val 1.89973
  Classification -> best τ=0.600 (val F1=0.2780)
  Directional -> Accuracy: 0.4167, MCC: -0.2070, F1: 0.5172

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64913 | val 1.25906
  Epoch 020 - train 0.59963 | val 0.78113
  Classification -> best τ=0.465 (val F1=0.0671)
  Directional -> Accuracy: 0.5263, MCC: -0.1067, F1: 0.6897

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50541 | val 2.68132
  Epoch 020 - train 0.45313 | val 2.59552
  Classification -> best τ=0.630 (val F1=0.2889)
  Directional -> Accuracy: 0.5385, MCC: 0.2673, F1: 0.2500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63144 | val 1.60286
  Epoch 020 - train 0.46018 | val 2.18036
  Classification -> best τ=0.600 (val F1=0.3413)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63575 | val 1.72128
  Epoch 020 - train 0.54721 | val 2.17739
  Classification -> best τ=0.480 (val F1=0.1377)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.75716 | val 1.58939
  Epoch 020 - train 0.34547 | val 5.14513
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67015 | val 0.69043
  Epoch 020 - train 0.52953 | val 1.03915
  Classification -> best τ=0.475 (val F1=0.3855)
  Directional -> Accuracy: 0.4524, MCC: 0.1370, F1: 0.5660

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62459 | val 2.33529
  Epoch 020 - train 0.52198 | val 3.19119
  Classification -> best τ=0.385 (val F1=0.1070)
  Directional -> Accuracy: 0.5211, MCC: 0.1350, F1: 0.6047

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61813 | val 0.89989
  Epoch 020 - train 0.64128 | val 1.26618
  Classification -> best τ=0.425 (val F1=0.2915)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69537 | val 0.84939
  Epoch 020 - train 0.61985 | val 1.00365
  Classification -> best τ=0.520 (val F1=0.2333)
  Directional -> Accuracy: 0.6102, MCC: 0.3422, F1: 0.7229

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60482 | val 1.33410
  Epoch 020 - train 0.50916 | val 1.69067
  Classification -> best τ=0.480 (val F1=0.3046)
  Directional -> Accuracy: 0.4545, MCC: -0.0760, F1: 0.4783

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66513 | val 0.67644
  Epoch 020 - train 0.63850 | val 0.63246
  Classification -> best τ=0.415 (val F1=0.2477)
  Directional -> Accuracy: 0.5806, MCC: 0.1644, F1: 0.5357

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63670 | val 0.85927
  Epoch 020 - train 0.61307 | val 0.80397
  Classification -> best τ=0.475 (val F1=0.2096)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64227 | val 1.59537
  Epoch 020 - train 0.46800 | val 1.71118
  Classification -> best τ=0.405 (val F1=0.1065)
  Directional -> Accuracy: 0.5070, MCC: -0.0801, F1: 0.6602

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63858 | val 0.86332
  Epoch 020 - train 0.61200 | val 0.84475
  Classification -> best τ=0.480 (val F1=0.3804)
  Directional -> Accuracy: 0.4667, MCC: 0.0818, F1: 0.3600

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66407 | val 1.68382
  Epoch 020 - train 0.65763 | val 1.60057
  Classification -> best τ=0.740 (val F1=0.1936)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65937 | val 0.74230
  Epoch 020 - train 0.60150 | val 0.75390
  Classification -> best τ=0.375 (val F1=0.2908)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62745 | val 0.90477
  Epoch 020 - train 0.50975 | val 1.29914
  Classification -> best τ=0.715 (val F1=0.2773)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62263 | val 1.34535
  Epoch 020 - train 0.53468 | val 0.91577
  Classification -> best τ=0.495 (val F1=0.2189)
  Directional -> Accuracy: 0.3878, MCC: 0.1100, F1: 0.0625

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67546 | val 0.87135
  Epoch 020 - train 0.62034 | val 1.44656
  Classification -> best τ=0.460 (val F1=0.2070)
  Directional -> Accuracy: 0.5224, MCC: 0.0494, F1: 0.4667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64454 | val 1.60338
  Epoch 020 - train 0.51095 | val 3.11443
  Classification -> best τ=0.845 (val F1=0.2559)
  Directional -> Accuracy: 0.4915, MCC: 0.0924, F1: 0.3478

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65609 | val 0.70226
  Epoch 020 - train 0.55765 | val 1.00445
  Classification -> best τ=0.550 (val F1=0.2715)
  Directional -> Accuracy: 0.4776, MCC: -0.1011, F1: 0.1860

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54893 | val 2.27616
  Epoch 020 - train 0.46851 | val 2.08190
  Classification -> best τ=0.445 (val F1=0.4766)
  Directional -> Accuracy: 0.5789, MCC: 0.2202, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53380 | val 1.70056
  Epoch 020 - train 0.33972 | val 5.53202
  Classification -> best τ=0.330 (val F1=0.1467)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58925 | val 1.23652
  Epoch 020 - train 0.59277 | val 1.10640
  Classification -> best τ=0.510 (val F1=0.3627)
  Directional -> Accuracy: 0.5682, MCC: 0.1145, F1: 0.6275

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57761 | val 0.94257
  Epoch 020 - train 0.50276 | val 1.72012
  Classification -> best τ=0.365 (val F1=0.2156)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60707 | val 0.81453
  Epoch 020 - train 0.45189 | val 0.65327
  Classification -> best τ=0.595 (val F1=0.4501)
  Directional -> Accuracy: 0.4419, MCC: -0.1150, F1: 0.4545

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55535 | val 1.21043
  Epoch 020 - train 0.43361 | val 1.29154
  Classification -> best τ=0.355 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58227 | val 1.94342
  Epoch 020 - train 0.49974 | val 1.64834
  Classification -> best τ=0.690 (val F1=0.1715)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55898 | val 1.00135
  Epoch 020 - train 0.42159 | val 1.71736
  Classification -> best τ=0.605 (val F1=0.1635)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69915 | val 0.68087
  Epoch 020 - train 0.63323 | val 1.12231
  Classification -> best τ=0.415 (val F1=0.3469)
  Directional -> Accuracy: 0.5405, MCC: 0.1770, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.57030 | val 0.96237
  Epoch 020 - train 0.40638 | val 1.22165
  Classification -> best τ=0.420 (val F1=0.2137)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59623 | val 1.66534
  Epoch 020 - train 0.62831 | val 1.68406
  Classification -> best τ=0.270 (val F1=0.1890)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61483 | val 1.49075
  Epoch 020 - train 0.49591 | val 1.50574
  Classification -> best τ=0.130 (val F1=0.2923)
  Directional -> Accuracy: 0.4853, MCC: 0.0054, F1: 0.4615

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53713 | val 2.75603
  Epoch 020 - train 0.45358 | val 4.22847
  Classification -> best τ=0.435 (val F1=0.2533)
  Directional -> Accuracy: 0.6364, MCC: 0.3254, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62350 | val 0.85239
  Epoch 020 - train 0.55247 | val 1.13096
  Classification -> best τ=0.390 (val F1=0.1687)
  Directional -> Accuracy: 0.4828, MCC: -0.0207, F1: 0.5161

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56429 | val 2.86538
  Epoch 020 - train 0.34799 | val 2.38478
  Classification -> best τ=0.475 (val F1=0.2441)
  Directional -> Accuracy: 0.6042, MCC: 0.0689, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56475 | val 1.77490
  Epoch 020 - train 0.40943 | val 1.70329
  Classification -> best τ=0.550 (val F1=0.4689)
  Directional -> Accuracy: 0.4500, MCC: -0.0737, F1: 0.3889

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54623 | val 1.45844
  Epoch 020 - train 0.33531 | val 2.27614
  Classification -> best τ=0.450 (val F1=0.3194)
  Directional -> Accuracy: 0.4615, MCC: -0.1650, F1: 0.6038

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63935 | val 1.60525
  Epoch 020 - train 0.56428 | val 3.03176
  Classification -> best τ=0.200 (val F1=0.2480)
  Directional -> Accuracy: 0.5395, MCC: 0.2027, F1: 0.6847

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53532 | val 1.21197
  Epoch 020 - train 0.30657 | val 2.39024
  Classification -> best τ=0.510 (val F1=0.2626)
  Directional -> Accuracy: 0.5625, MCC: 0.1601, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48239 | val 3.03347
  Epoch 020 - train 0.24021 | val 4.84894
  Classification -> best τ=0.770 (val F1=0.5000)
  Directional -> Accuracy: 0.4667, MCC: -0.0116, F1: 0.3333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58346 | val 1.71078
  Epoch 020 - train 0.34387 | val 2.65016
  Classification -> best τ=0.490 (val F1=0.1489)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69384 | val 0.66818
  Epoch 020 - train 0.64036 | val 0.70334
  Classification -> best τ=0.660 (val F1=0.2178)
  Directional -> Accuracy: 0.4737, MCC: 0.1224, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58909 | val 2.75517
  Epoch 020 - train 0.48962 | val 5.03038
  Classification -> best τ=0.925 (val F1=0.3335)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63087 | val 1.24456
  Epoch 020 - train 0.57206 | val 2.54659
  Classification -> best τ=0.670 (val F1=0.1197)
  Directional -> Accuracy: 0.6000, MCC: 0.1933, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61633 | val 2.16072
  Epoch 020 - train 0.57100 | val 2.52200
  Classification -> best τ=0.320 (val F1=0.2794)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66672 | val 0.73116

[I 2026-02-20 00:11:13,205] Trial 45 finished with value: 0.2544635734534861 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009985662560149787, 'weight_decay': 0.00010178326125038193, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.076465950934686, 'early_stopping_min_delta': 0.0004583220163206987}. Best is trial 42 with value: 0.268296303084699.

  Epoch 020 - train 0.65663 | val 0.68622
  Classification -> best τ=0.440 (val F1=0.2714)
  Directional -> Accuracy: 0.5484, MCC: 0.1216, F1: 0.6216

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2544635734534861
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61710 | val 0.94067
  Epoch 020 - train 0.55513 | val 1.31437
  Epoch 021 - train 0.57115 | val 1.32216
  Classification -> best τ=0.630 (val F1=0.2346)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60611 | val 1.08494
  Epoch 020 - train 0.54532 | val 1.15947
  Epoch 021 - train 0.50493 | val 1.17252
  Classification -> best τ=0.455 (val F1=0.0646)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60890 | val 1.35974
  Epoch 020 - train 0.57790 | val 1.43081
  Epoch 022 - train 0.57535 | val 1.41320
  Classification -> best τ=0.530 (val F1=0.2722)
  Directional -> Accuracy: 0.4694, MCC: -0.0229, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61045 | val 1.49432
  Epoch 020 - train 0.56460 | val 1.79391
  Epoch 021 - train 0.56196 | val 1.80714
  Classification -> best τ=0.475 (val F1=0.0424)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56212 | val 2.03722
  Epoch 020 - train 0.50439 | val 2.11236
  Epoch 022 - train 0.48076 | val 2.15141
  Classification -> best τ=0.585 (val F1=0.3050)
  Directional -> Accuracy: 0.5283, MCC: 0.0441, F1: 0.5902

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52872 | val 0.95140
  Epoch 020 - train 0.47161 | val 1.54856
  Epoch 022 - train 0.49708 | val 1.58120
  Classification -> best τ=0.535 (val F1=0.2622)
  Directional -> Accuracy: 0.4146, MCC: -0.1547, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63692 | val 1.07361
  Epoch 020 - train 0.59254 | val 1.25788
  Epoch 021 - train 0.57139 | val 1.26582
  Classification -> best τ=0.465 (val F1=0.2817)
  Directional -> Accuracy: 0.5352, MCC: 0.1977, F1: 0.6024

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56768 | val 1.17074
  Epoch 020 - train 0.45146 | val 1.28036
  Epoch 026 - train 0.39714 | val 1.35906
  Classification -> best τ=0.330 (val F1=0.2418)
  Directional -> Accuracy: 0.5745, MCC: -0.1215, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60006 | val 0.71351
  Epoch 020 - train 0.54633 | val 0.72771
  Epoch 021 - train 0.54309 | val 0.72101
  Classification -> best τ=0.535 (val F1=0.3015)
  Directional -> Accuracy: 0.4884, MCC: -0.0089, F1: 0.4500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54893 | val 1.79184
  Epoch 020 - train 0.47225 | val 2.76440
  Epoch 021 - train 0.48347 | val 2.72176
  Classification -> best τ=0.335 (val F1=0.2618)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59996 | val 0.74211
  Epoch 020 - train 0.47244 | val 0.86441
  Epoch 030 - train 0.46939 | val 0.79393
  Classification -> best τ=0.720 (val F1=0.3006)
  Directional -> Accuracy: 0.5769, MCC: 0.1670, F1: 0.2143

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63266 | val 1.39724
  Epoch 020 - train 0.55074 | val 1.79788
  Epoch 021 - train 0.57361 | val 1.87746
  Classification -> best τ=0.505 (val F1=0.2485)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50980 | val 0.72927
  Epoch 020 - train 0.46387 | val 0.78710
  Epoch 024 - train 0.44834 | val 0.75237
  Classification -> best τ=0.565 (val F1=0.2388)
  Directional -> Accuracy: 0.5556, MCC: 0.0980, F1: 0.4737

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60959 | val 0.81667
  Epoch 020 - train 0.56366 | val 1.10729
  Epoch 023 - train 0.57620 | val 1.12290
  Classification -> best τ=0.510 (val F1=0.3610)
  Directional -> Accuracy: 0.5397, MCC: 0.0869, F1: 0.5915

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55468 | val 2.23405
  Epoch 020 - train 0.47137 | val 3.04871
  Epoch 022 - train 0.49700 | val 3.03923
  Classification -> best τ=0.570 (val F1=0.2224)
  Directional -> Accuracy: 0.4444, MCC: -0.1131, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55195 | val 0.98485
  Epoch 020 - train 0.52702 | val 1.23207
  Epoch 021 - train 0.51491 | val 1.21050
  Classification -> best τ=0.610 (val F1=0.2578)
  Directional -> Accuracy: 0.5000, MCC: 0.0216, F1: 0.4545

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58217 | val 2.79456
  Epoch 020 - train 0.56170 | val 2.92931
  Epoch 021 - train 0.55986 | val 2.91396
  Classification -> best τ=0.645 (val F1=0.1657)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62974 | val 0.93904
  Epoch 020 - train 0.58147 | val 0.98815
  Epoch 021 - train 0.59682 | val 1.02108
  Classification -> best τ=0.535 (val F1=0.1900)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60804 | val 0.84011
  Epoch 020 - train 0.55227 | val 1.14627
  Epoch 021 - train 0.54326 | val 1.10875
  Classification -> best τ=0.385 (val F1=0.2025)
  Directional -> Accuracy: 0.5224, MCC: 0.0479, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59907 | val 0.73511
  Epoch 020 - train 0.49652 | val 0.76492
  Epoch 023 - train 0.49082 | val 0.76993
  Classification -> best τ=0.205 (val F1=0.2722)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56020 | val 1.12139
  Epoch 020 - train 0.52207 | val 1.69958
  Epoch 021 - train 0.48693 | val 1.70683
  Classification -> best τ=0.535 (val F1=0.2191)
  Directional -> Accuracy: 0.5200, MCC: 0.0215, F1: 0.5862

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62148 | val 0.73706
  Epoch 020 - train 0.56852 | val 0.75070
  Epoch 021 - train 0.58364 | val 0.74715
  Classification -> best τ=0.505 (val F1=0.2739)
  Directional -> Accuracy: 0.4853, MCC: -0.1222, F1: 0.6535

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58789 | val 0.93569
  Epoch 020 - train 0.52667 | val 0.88101
  Epoch 021 - train 0.53804 | val 0.90682
  Classification -> best τ=0.565 (val F1=0.2335)
  Directional -> Accuracy: 0.4500, MCC: 0.0331, F1: 0.2326

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61579 | val 0.68293
  Epoch 020 - train 0.51049 | val 0.70085
  Epoch 026 - train 0.50281 | val 0.71251
  Classification -> best τ=0.525 (val F1=0.1757)
  Directional -> Accuracy: 0.5000, MCC: 0.0653, F1: 0.6531

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60500 | val 0.84889
  Epoch 020 - train 0.48918 | val 0.95115
  Epoch 027 - train 0.46724 | val 0.96366
  Classification -> best τ=0.615 (val F1=0.3797)
  Directional -> Accuracy: 0.5345, MCC: 0.1519, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49873 | val 1.98518
  Epoch 020 - train 0.43288 | val 2.04008
  Epoch 024 - train 0.38252 | val 2.82267
  Classification -> best τ=0.560 (val F1=0.3575)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59798 | val 0.80315
  Epoch 020 - train 0.56480 | val 0.77149
  Epoch 021 - train 0.56252 | val 0.76383
  Classification -> best τ=0.465 (val F1=0.1071)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.5333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61612 | val 1.42438
  Epoch 020 - train 0.56597 | val 1.77136
  Epoch 021 - train 0.55061 | val 1.77581
  Classification -> best τ=0.480 (val F1=0.2942)
  Directional -> Accuracy: 0.5593, MCC: 0.2816, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53567 | val 2.40489
  Epoch 020 - train 0.47685 | val 2.56678
  Epoch 021 - train 0.47597 | val 2.61297
  Classification -> best τ=0.490 (val F1=0.1626)
  Directional -> Accuracy: 0.5000, MCC: 0.0106, F1: 0.4500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55520 | val 0.87404
  Epoch 020 - train 0.49794 | val 0.95735
  Epoch 021 - train 0.50393 | val 0.93884
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59378 | val 0.77387
  Epoch 020 - train 0.60189 | val 0.91461
  Epoch 024 - train 0.54414 | val 0.97251
  Classification -> best τ=0.645 (val F1=0.2110)
  Directional -> Accuracy: 0.6087, MCC: 0.2114, F1: 0.6400

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53653 | val 1.08354
  Epoch 020 - train 0.47599 | val 1.21424
  Epoch 022 - train 0.45929 | val 1.23039
  Classification -> best τ=0.410 (val F1=0.2423)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59932 | val 0.77880
  Epoch 020 - train 0.54165 | val 0.95358
  Epoch 023 - train 0.53438 | val 1.00334
  Classification -> best τ=0.355 (val F1=0.3565)
  Directional -> Accuracy: 0.5067, MCC: 0.0570, F1: 0.4478

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.63689 | val 0.73908
  Epoch 020 - train 0.53288 | val 0.83594
  Epoch 021 - train 0.58882 | val 0.83222
  Classification -> best τ=0.490 (val F1=0.3477)
  Directional -> Accuracy: 0.5610, MCC: 0.1504, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55345 | val 1.35989
  Epoch 020 - train 0.54533 | val 1.50246
  Epoch 021 - train 0.50346 | val 1.46246
  Classification -> best τ=0.560 (val F1=0.2882)
  Directional -> Accuracy: 0.5000, MCC: -0.1280, F1: 0.0800

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57174 | val 0.77246
  Epoch 020 - train 0.51169 | val 0.81178
  Epoch 021 - train 0.51830 | val 0.81664
  Classification -> best τ=0.440 (val F1=0.3136)
  Directional -> Accuracy: 0.5507, MCC: 0.0913, F1: 0.5974

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50037 | val 0.90124
  Epoch 020 - train 0.47005 | val 1.02196
  Epoch 022 - train 0.42079 | val 1.02346
  Classification -> best τ=0.425 (val F1=0.2980)
  Directional -> Accuracy: 0.6222, MCC: 0.2882, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57731 | val 1.47275
  Epoch 020 - train 0.55243 | val 1.73341
  Epoch 021 - train 0.52090 | val 1.76650
  Classification -> best τ=0.455 (val F1=0.2165)
  Directional -> Accuracy: 0.5254, MCC: 0.0554, F1: 0.5333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53775 | val 1.85500
  Epoch 020 - train 0.43292 | val 2.35876
  Epoch 021 - train 0.45519 | val 2.36631
  Classification -> best τ=0.490 (val F1=0.2032)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57073 | val 0.66940
  Epoch 020 - train 0.45532 | val 0.70954
  Epoch 027 - train 0.47288 | val 0.75002
  Classification -> best τ=0.270 (val F1=0.3647)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48212 | val 0.73739
  Epoch 020 - train 0.41025 | val 0.97169
  Epoch 028 - train 0.40174 | val 1.29527
  Classification -> best τ=0.575 (val F1=0.3874)
  Directional -> Accuracy: 0.4634, MCC: -0.0837, F1: 0.1538

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60975 | val 2.45056
  Epoch 020 - train 0.54632 | val 2.94983
  Epoch 021 - train 0.53159 | val 3.01032
  Classification -> best τ=0.445 (val F1=0.1999)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57928 | val 0.99424
  Epoch 020 - train 0.54975 | val 1.41184
  Epoch 021 - train 0.56208 | val 1.44335
  Classification -> best τ=0.560 (val F1=0.1885)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48268 | val 1.72351
  Epoch 020 - train 0.43475 | val 2.51753
  Epoch 021 - train 0.41267 | val 2.51029
  Classification -> best τ=0.550 (val F1=0.5477)
  Directional -> Accuracy: 0.4468, MCC: 0.1269, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57256 | val 0.95578
  Epoch 020 - train 0.49299 | val 0.83228
  Epoch 021 - train 0.44960 | val 0.84904
  Classification -> best τ=0.570 (val F1=0.1425)
  Directional -> Accuracy: 0.5476, MCC: -0.0314, F1: 0.2963

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63824 | val 0.70642
  Epoch 020 - train 0.58353 | val 0.67598
  Epoch 030 - train 0.56666 | val 0.66470
  Classification -> best τ=0.500 (val F1=0.3479)
  Directional -> Accuracy: 0.4483, MCC: -0.0938, F1: 0.4483

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58612 | val 1.51591
  Epoch 020 - train 0.54953 | val 1.54707
  Epoch 021 - train 0.51800 | val 1.55799
  Classification -> best τ=0.675 (val F1=0.4144)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60903 | val 1.26027
  Epoch 020 - train 0.51949 | val 1.21491
  Epoch 021 - train 0.56139 | val 1.23564
  Classification -> best τ=0.430 (val F1=0.2143)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...


[I 2026-02-20 00:13:14,159] Trial 46 finished with value: 0.25316383631144485 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.001720054530763659, 'weight_decay': 0.00019649430431196334, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.465055543516906, 'early_stopping_min_delta': 0.0006132691683232908}. Best is trial 42 with value: 0.268296303084699.

  Epoch 023 - train 0.56224 | val 0.93956
  Classification -> best τ=0.600 (val F1=0.2911)
  Directional -> Accuracy: 0.4444, MCC: -0.1348, F1: 0.3137

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25316383631144485
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65902 | val 0.79823
  Epoch 020 - train 0.65832 | val 0.66164
  Epoch 028 - train 0.61152 | val 0.64384
  Classification -> best τ=0.440 (val F1=0.3107)
  Directional -> Accuracy: 0.5526, MCC: 0.0503, F1: 0.2917

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65946 | val 0.98726
  Epoch 020 - train 0.55681 | val 0.70150
  Epoch 030 - train 0.49433 | val 0.76299
  Classification -> best τ=0.300 (val F1=0.2670)
  Directional -> Accuracy: 0.5556, MCC: 0.0763, F1: 0.6296

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65295 | val 0.65539
  Epoch 020 - train 0.66015 | val 0.65032
  Classification -> best τ=0.420 (val F1=0.3308)
  Directional -> Accuracy: 0.6304, MCC: 0.2822, F1: 0.5854

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67946 | val 1.08971
  Epoch 016 - train 0.64012 | val 1.48580
  Classification -> best τ=0.285 (val F1=0.1394)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58903 | val 0.73478
  Epoch 016 - train 0.56257 | val 0.74677
  Classification -> best τ=0.480 (val F1=0.5155)
  Directional -> Accuracy: 0.7200, MCC: 0.4470, F1: 0.7586

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68446 | val 0.72381
  Epoch 017 - train 0.54734 | val 0.78542
  Classification -> best τ=0.495 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0200, F1: 0.2667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67378 | val 0.71889
  Epoch 020 - train 0.61864 | val 1.02920
  Classification -> best τ=0.410 (val F1=0.2648)
  Directional -> Accuracy: 0.4853, MCC: -0.0177, F1: 0.4444

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70149 | val 0.72547
  Epoch 020 - train 0.58863 | val 0.77859
  Epoch 025 - train 0.51575 | val 1.02753
  Classification -> best τ=0.550 (val F1=0.0668)
  Directional -> Accuracy: 0.4286, MCC: -0.0807, F1: 0.5200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65268 | val 0.87200
  Epoch 016 - train 0.61598 | val 0.87565
  Classification -> best τ=0.585 (val F1=0.2988)
  Directional -> Accuracy: 0.6875, MCC: 0.3687, F1: 0.6512

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63407 | val 0.78435
  Epoch 016 - train 0.58753 | val 0.86994
  Classification -> best τ=0.705 (val F1=0.1607)
  Directional -> Accuracy: 0.4928, MCC: -0.0562, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68026 | val 0.71184
  Epoch 017 - train 0.63122 | val 0.88271
  Classification -> best τ=0.500 (val F1=0.1738)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66367 | val 0.71670
  Epoch 017 - train 0.63057 | val 0.79923
  Classification -> best τ=0.495 (val F1=0.0737)
  Directional -> Accuracy: 0.4912, MCC: -0.1313, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67571 | val 0.73483
  Epoch 017 - train 0.57539 | val 1.14487
  Classification -> best τ=0.430 (val F1=0.3073)
  Directional -> Accuracy: 0.4762, MCC: 0.0663, F1: 0.6207

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72209 | val 0.65606
  Epoch 020 - train 0.69339 | val 0.70287
  Classification -> best τ=0.275 (val F1=0.3455)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66425 | val 0.73311
  Epoch 018 - train 0.63140 | val 0.81720
  Classification -> best τ=0.525 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64865 | val 0.99424
  Epoch 020 - train 0.59675 | val 1.00114
  Classification -> best τ=0.680 (val F1=0.3438)
  Directional -> Accuracy: 0.5652, MCC: 0.1389, F1: 0.5588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65785 | val 1.05698
  Epoch 017 - train 0.65671 | val 1.39513
  Classification -> best τ=0.400 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65401 | val 0.88285
  Epoch 017 - train 0.67614 | val 0.96989
  Classification -> best τ=0.485 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68653 | val 0.69147
  Epoch 020 - train 0.63553 | val 0.76972
  Epoch 026 - train 0.61172 | val 0.75836
  Classification -> best τ=0.305 (val F1=0.3140)
  Directional -> Accuracy: 0.5156, MCC: 0.0853, F1: 0.4746

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61038 | val 1.03218
  Epoch 016 - train 0.55792 | val 1.13605
  Classification -> best τ=0.465 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69288 | val 0.68498
  Epoch 020 - train 0.65985 | val 0.67813
  Epoch 030 - train 0.54057 | val 0.76320
  Classification -> best τ=0.490 (val F1=0.4104)
  Directional -> Accuracy: 0.4043, MCC: -0.1537, F1: 0.4167

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68736 | val 0.71818
  Epoch 020 - train 0.65482 | val 0.83611
  Classification -> best τ=0.610 (val F1=0.1925)
  Directional -> Accuracy: 0.4615, MCC: -0.0919, F1: 0.1860

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67848 | val 0.75164
  Epoch 020 - train 0.66563 | val 0.73560
  Epoch 021 - train 0.64964 | val 0.75765
  Classification -> best τ=0.450 (val F1=0.2236)
  Directional -> Accuracy: 0.4561, MCC: -0.0420, F1: 0.3673

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70213 | val 0.73829
  Epoch 020 - train 0.61203 | val 0.74876
  Epoch 021 - train 0.61598 | val 0.77671
  Classification -> best τ=0.540 (val F1=0.1565)
  Directional -> Accuracy: 0.6000, MCC: 0.2086, F1: 0.6176

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62258 | val 1.21479
  Epoch 017 - train 0.58503 | val 1.64608
  Classification -> best τ=0.440 (val F1=0.4307)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67696 | val 1.56870
  Epoch 016 - train 0.55623 | val 3.03651
  Classification -> best τ=0.430 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68595 | val 0.84653
  Epoch 016 - train 0.67120 | val 0.77241
  Classification -> best τ=0.470 (val F1=0.0323)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60567 | val 1.05156
  Epoch 016 - train 0.62214 | val 1.24849
  Classification -> best τ=0.425 (val F1=0.4916)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64336 | val 0.85787
  Epoch 017 - train 0.65849 | val 0.99982
  Classification -> best τ=0.475 (val F1=0.2414)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64082 | val 1.11152
  Epoch 016 - train 0.63546 | val 1.24497
  Classification -> best τ=0.520 (val F1=0.3656)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66772 | val 0.95375
  Epoch 020 - train 0.65785 | val 1.05248
  Epoch 021 - train 0.64690 | val 1.06431
  Classification -> best τ=0.425 (val F1=0.1124)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64838 | val 0.82483
  Epoch 016 - train 0.47330 | val 1.01366
  Classification -> best τ=0.505 (val F1=0.3789)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66863 | val 0.69955
  Epoch 020 - train 0.64088 | val 0.67695
  Epoch 030 - train 0.56182 | val 0.73708
  Classification -> best τ=0.330 (val F1=0.3366)
  Directional -> Accuracy: 0.5972, MCC: 0.1640, F1: 0.6813

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66483 | val 0.97381
  Epoch 016 - train 0.63913 | val 1.30705
  Classification -> best τ=0.450 (val F1=0.2057)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66700 | val 0.92212
  Epoch 019 - train 0.61266 | val 1.27587
  Classification -> best τ=0.145 (val F1=0.3855)
  Directional -> Accuracy: 0.5909, MCC: 0.1513, F1: 0.6582

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64761 | val 0.70287
  Epoch 020 - train 0.55225 | val 0.80774
  Epoch 021 - train 0.61363 | val 0.84369
  Classification -> best τ=0.425 (val F1=0.2439)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61656 | val 0.79383
  Epoch 016 - train 0.62458 | val 0.80409
  Classification -> best τ=0.325 (val F1=0.2530)
  Directional -> Accuracy: 0.5357, MCC: 0.1040, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61743 | val 0.92453
  Epoch 016 - train 0.54550 | val 0.91372
  Classification -> best τ=0.475 (val F1=0.3218)
  Directional -> Accuracy: 0.6087, MCC: 0.1174, F1: 0.7188

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62575 | val 0.68887
  Epoch 020 - train 0.64216 | val 0.67615
  Epoch 021 - train 0.60552 | val 0.66849
  Classification -> best τ=0.365 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64910 | val 0.88093
  Epoch 020 - train 0.62807 | val 1.06279
  Epoch 021 - train 0.59806 | val 1.09125
  Classification -> best τ=0.520 (val F1=0.3523)
  Directional -> Accuracy: 0.5405, MCC: 0.1172, F1: 0.6383

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64978 | val 0.81327
  Epoch 017 - train 0.63962 | val 0.95577
  Classification -> best τ=0.495 (val F1=0.2586)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61410 | val 1.05403
  Epoch 016 - train 0.55592 | val 1.28765
  Classification -> best τ=0.520 (val F1=0.3015)
  Directional -> Accuracy: 0.5952, MCC: 0.1578, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66299 | val 0.94780
  Epoch 019 - train 0.53019 | val 1.09576
  Classification -> best τ=0.590 (val F1=0.6292)
  Directional -> Accuracy: 0.5417, MCC: 0.3464, F1: 0.6207

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68061 | val 0.85664
  Epoch 017 - train 0.64657 | val 1.16198
  Classification -> best τ=0.555 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63334 | val 2.45235
  Epoch 016 - train 0.61151 | val 2.74638
  Classification -> best τ=0.870 (val F1=0.3846)
  Directional -> Accuracy: 0.4821, MCC: -0.0444, F1: 0.4082

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70373 | val 0.73322
  Epoch 016 - train 0.67721 | val 0.84299
  Classification -> best τ=0.505 (val F1=0.2434)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66198 | val 1.93660
  Epoch 016 - train 0.59711 | val 2.17110
  Classification -> best τ=0.750 (val F1=0.1957)
  Directional -> Accuracy: 0.5455, MCC: 0.0942, F1: 0.5455

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65332 | val 0.72607
  Epoch 020 - train 0.62404 | val 0.78108

[I 2026-02-20 00:16:36,272] Trial 47 finished with value: 0.2781229548444326 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.007869374610163704, 'weight_decay': 6.943986029452591e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.386940397237425, 'early_stopping_min_delta': 0.004954929680556932}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 021 - train 0.61426 | val 0.75606
  Classification -> best τ=0.365 (val F1=0.2337)
  Directional -> Accuracy: 0.5833, MCC: 0.2182, F1: 0.6667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2781229548444326
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61123 | val 0.68037
  Epoch 016 - train 0.61712 | val 0.90171
  Classification -> best τ=0.455 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1542, F1: 0.4364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55898 | val 0.88585
  Epoch 019 - train 0.40779 | val 0.92897
  Classification -> best τ=0.320 (val F1=0.1650)
  Directional -> Accuracy: 0.5556, MCC: 0.1160, F1: 0.5833

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57547 | val 1.02923
  Epoch 017 - train 0.46608 | val 1.05274
  Classification -> best τ=0.560 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62051 | val 1.07513
  Epoch 016 - train 0.55392 | val 1.92565
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47515 | val 0.88471
  Epoch 016 - train 0.38309 | val 1.58241
  Classification -> best τ=0.550 (val F1=0.3751)
  Directional -> Accuracy: 0.5200, MCC: 0.1084, F1: 0.2500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51285 | val 0.95649
  Epoch 017 - train 0.39008 | val 1.11442
  Classification -> best τ=0.585 (val F1=0.2241)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63646 | val 1.28416
  Epoch 017 - train 0.54240 | val 1.30316
  Classification -> best τ=0.780 (val F1=0.1753)
  Directional -> Accuracy: 0.6176, MCC: 0.1505, F1: 0.0714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51548 | val 2.28623
  Epoch 018 - train 0.39454 | val 3.75755
  Classification -> best τ=0.630 (val F1=0.3689)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50643 | val 1.28602
  Epoch 016 - train 0.43297 | val 1.34127
  Classification -> best τ=0.555 (val F1=0.2154)
  Directional -> Accuracy: 0.5833, MCC: 0.1143, F1: 0.3333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58728 | val 0.97919
  Epoch 020 - train 0.44139 | val 1.17784
  Epoch 022 - train 0.39018 | val 1.22035
  Classification -> best τ=0.440 (val F1=0.1708)
  Directional -> Accuracy: 0.4928, MCC: 0.0017, F1: 0.4776

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65813 | val 0.66464
  Epoch 020 - train 0.49071 | val 0.71257
  Epoch 030 - train 0.41726 | val 0.70885
  Classification -> best τ=0.695 (val F1=0.4916)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59468 | val 1.66532
  Epoch 017 - train 0.47591 | val 2.35239
  Classification -> best τ=0.505 (val F1=0.4077)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50675 | val 1.76889
  Epoch 016 - train 0.42202 | val 1.96756
  Classification -> best τ=0.515 (val F1=0.3942)
  Directional -> Accuracy: 0.5476, MCC: 0.1105, F1: 0.5581

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62831 | val 0.64511
  Epoch 020 - train 0.46547 | val 0.68991
  Classification -> best τ=0.325 (val F1=0.3367)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6154

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50460 | val 0.70513
  Epoch 016 - train 0.42565 | val 0.70824
  Classification -> best τ=0.515 (val F1=0.3865)
  Directional -> Accuracy: 0.5490, MCC: 0.1393, F1: 0.5965

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55670 | val 0.93680
  Epoch 017 - train 0.47473 | val 0.80931
  Classification -> best τ=0.540 (val F1=0.2957)
  Directional -> Accuracy: 0.4928, MCC: 0.0807, F1: 0.1860

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58326 | val 2.53279
  Epoch 016 - train 0.53447 | val 3.20450
  Classification -> best τ=0.450 (val F1=0.1179)
  Directional -> Accuracy: 0.5172, MCC: 0.0099, F1: 0.5882

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61175 | val 1.02399
  Epoch 017 - train 0.51302 | val 1.18501
  Classification -> best τ=0.570 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61912 | val 0.88052
  Epoch 020 - train 0.45488 | val 1.77483
  Epoch 021 - train 0.42966 | val 1.95621
  Classification -> best τ=0.835 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52539 | val 0.83126
  Epoch 016 - train 0.44859 | val 0.98862
  Classification -> best τ=0.445 (val F1=0.3715)
  Directional -> Accuracy: 0.4730, MCC: 0.1495, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59174 | val 0.96404
  Epoch 016 - train 0.51995 | val 0.93734
  Classification -> best τ=0.515 (val F1=0.2295)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67122 | val 0.75664
  Epoch 020 - train 0.53918 | val 1.03009
  Classification -> best τ=0.710 (val F1=0.1960)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57687 | val 1.21135
  Epoch 016 - train 0.52167 | val 1.74678
  Classification -> best τ=0.620 (val F1=0.2380)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64585 | val 0.73854
  Epoch 018 - train 0.47647 | val 1.66333
  Classification -> best τ=0.640 (val F1=0.1565)
  Directional -> Accuracy: 0.5538, MCC: 0.1269, F1: 0.6027

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50124 | val 1.91721
  Epoch 016 - train 0.40954 | val 2.08733
  Classification -> best τ=0.465 (val F1=0.3751)
  Directional -> Accuracy: 0.4182, MCC: -0.2155, F1: 0.5294

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48814 | val 2.79849
  Epoch 016 - train 0.42405 | val 3.20898
  Classification -> best τ=0.605 (val F1=0.2097)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62532 | val 0.74272
  Epoch 016 - train 0.54991 | val 0.80636
  Classification -> best τ=0.520 (val F1=0.0534)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53494 | val 2.02808
  Epoch 016 - train 0.49039 | val 2.82162
  Classification -> best τ=0.350 (val F1=0.1151)
  Directional -> Accuracy: 0.5179, MCC: 0.0797, F1: 0.4490

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50883 | val 1.77958
  Epoch 016 - train 0.46187 | val 2.32848
  Classification -> best τ=0.570 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53103 | val 0.82760
  Epoch 017 - train 0.41334 | val 0.97355
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62773 | val 0.91943
  Epoch 017 - train 0.51666 | val 1.31412
  Classification -> best τ=0.550 (val F1=0.2238)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52055 | val 0.99875
  Epoch 016 - train 0.41074 | val 1.30871
  Classification -> best τ=0.555 (val F1=0.2969)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64838 | val 0.66205
  Epoch 019 - train 0.52165 | val 0.93025
  Classification -> best τ=0.320 (val F1=0.4458)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50824 | val 1.16762
  Epoch 016 - train 0.46310 | val 1.05495
  Classification -> best τ=0.530 (val F1=0.3227)
  Directional -> Accuracy: 0.5581, MCC: 0.1307, F1: 0.3448

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54481 | val 0.84924
  Epoch 016 - train 0.41926 | val 1.16462
  Classification -> best τ=0.440 (val F1=0.1745)
  Directional -> Accuracy: 0.6212, MCC: 0.2542, F1: 0.7525

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48322 | val 0.80275
  Epoch 016 - train 0.35972 | val 1.16521
  Classification -> best τ=0.520 (val F1=0.2144)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55572 | val 0.94086
  Epoch 016 - train 0.46413 | val 1.12075
  Classification -> best τ=0.465 (val F1=0.2382)
  Directional -> Accuracy: 0.5179, MCC: 0.0234, F1: 0.4490

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45631 | val 0.90884
  Epoch 016 - train 0.32178 | val 0.98689
  Classification -> best τ=0.395 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50832 | val 0.87221
  Epoch 017 - train 0.43922 | val 0.97229
  Classification -> best τ=0.460 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56054 | val 1.91511
  Epoch 016 - train 0.46413 | val 1.93686
  Classification -> best τ=0.165 (val F1=0.2773)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58540 | val 0.82881
  Epoch 016 - train 0.50657 | val 0.94265
  Classification -> best τ=0.490 (val F1=0.3287)
  Directional -> Accuracy: 0.5778, MCC: 0.1540, F1: 0.6122

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53102 | val 1.20328
  Epoch 016 - train 0.41741 | val 1.87425
  Classification -> best τ=0.585 (val F1=0.3612)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.3030

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51295 | val 0.64724
  Epoch 020 - train 0.33558 | val 0.67545
  Epoch 029 - train 0.18610 | val 0.75114
  Classification -> best τ=0.785 (val F1=0.6539)
  Directional -> Accuracy: 0.4375, MCC: 0.0413, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65640 | val 0.83090
  Epoch 016 - train 0.55841 | val 1.40129
  Classification -> best τ=0.570 (val F1=0.3238)
  Directional -> Accuracy: 0.3818, MCC: -0.2193, F1: 0.2917

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48828 | val 1.77896
  Epoch 016 - train 0.41177 | val 1.91996
  Classification -> best τ=0.805 (val F1=0.3846)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64513 | val 0.81479
  Epoch 016 - train 0.56841 | val 0.89908
  Classification -> best τ=0.535 (val F1=0.1024)
  Directional -> Accuracy: 0.5849, MCC: 0.1691, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51905 | val 3.86302
  Epoch 016 - train 0.44932 | val 5.01908
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55340 | val 1.37972

[I 2026-02-20 00:19:34,412] Trial 48 finished with value: 0.27120461231001075 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.006639295259528863, 'weight_decay': 3.526079197653317e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.3949952698775827, 'early_stopping_min_delta': 0.005302189361200614}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.52010 | val 1.42376
  Classification -> best τ=0.470 (val F1=0.2915)
  Directional -> Accuracy: 0.5667, MCC: 0.1452, F1: 0.6061

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27120461231001075
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52138 | val 1.04329
  Epoch 016 - train 0.41348 | val 1.00198
  Classification -> best τ=0.565 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41222 | val 2.50934
  Epoch 016 - train 0.27729 | val 2.54524
  Classification -> best τ=0.590 (val F1=0.0618)
  Directional -> Accuracy: 0.6222, MCC: 0.1924, F1: 0.7213

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49029 | val 1.03665
  Epoch 016 - train 0.31542 | val 1.23288
  Classification -> best τ=0.490 (val F1=0.0417)
  Directional -> Accuracy: 0.3913, MCC: -0.2423, F1: 0.4815

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.49416 | val 1.40490
  Epoch 016 - train 0.41537 | val 1.43030
  Classification -> best τ=0.375 (val F1=0.1005)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41061 | val 3.19400
  Epoch 016 - train 0.29956 | val 3.44042
  Classification -> best τ=0.560 (val F1=0.4851)
  Directional -> Accuracy: 0.6800, MCC: 0.3759, F1: 0.6522

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49201 | val 1.34207
  Epoch 016 - train 0.30418 | val 2.16835
  Classification -> best τ=0.565 (val F1=0.2303)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.50919 | val 1.50884
  Epoch 016 - train 0.37882 | val 3.52322
  Classification -> best τ=0.295 (val F1=0.2481)
  Directional -> Accuracy: 0.4706, MCC: 0.1116, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32972 | val 1.85714
  Epoch 016 - train 0.18625 | val 2.61546
  Classification -> best τ=0.570 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.0430, F1: 0.3636

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53964 | val 1.99633
  Epoch 016 - train 0.32445 | val 3.20899
  Classification -> best τ=0.585 (val F1=0.1411)
  Directional -> Accuracy: 0.5417, MCC: 0.0295, F1: 0.3529

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48001 | val 2.33069
  Epoch 016 - train 0.33238 | val 3.43869
  Classification -> best τ=0.255 (val F1=0.2849)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45799 | val 0.62546
  Epoch 020 - train 0.25861 | val 1.52800
  Epoch 024 - train 0.13955 | val 2.75955
  Classification -> best τ=0.705 (val F1=0.4196)
  Directional -> Accuracy: 0.6122, MCC: 0.2076, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47393 | val 3.13509
  Epoch 016 - train 0.35114 | val 6.28150
  Classification -> best τ=0.435 (val F1=0.2236)
  Directional -> Accuracy: 0.6491, MCC: 0.3234, F1: 0.7143

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38409 | val 3.61673
  Epoch 016 - train 0.29935 | val 4.30169
  Classification -> best τ=0.435 (val F1=0.2557)
  Directional -> Accuracy: 0.5238, MCC: 0.0389, F1: 0.4737

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58853 | val 1.60727
  Epoch 016 - train 0.43608 | val 2.17966
  Classification -> best τ=0.505 (val F1=0.3833)
  Directional -> Accuracy: 0.5833, MCC: 0.1747, F1: 0.5098

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50248 | val 1.61365
  Epoch 016 - train 0.35365 | val 2.50773
  Classification -> best τ=0.585 (val F1=0.1455)
  Directional -> Accuracy: 0.5294, MCC: 0.0038, F1: 0.2941

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49876 | val 0.88260
  Epoch 016 - train 0.36002 | val 1.70632
  Classification -> best τ=0.590 (val F1=0.1709)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55243 | val 5.30068
  Epoch 016 - train 0.40117 | val 9.50899
  Classification -> best τ=0.630 (val F1=0.2186)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50052 | val 1.76169
  Epoch 016 - train 0.39870 | val 1.36981
  Classification -> best τ=0.190 (val F1=0.1097)
  Directional -> Accuracy: 0.5733, MCC: 0.0817, F1: 0.6667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52000 | val 0.97063
  Epoch 016 - train 0.41511 | val 1.94367
  Classification -> best τ=0.335 (val F1=0.2522)
  Directional -> Accuracy: 0.5000, MCC: 0.0250, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44145 | val 1.10693
  Epoch 016 - train 0.35447 | val 1.08893
  Classification -> best τ=0.565 (val F1=0.3548)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53180 | val 1.87698
  Epoch 016 - train 0.34447 | val 3.16452
  Classification -> best τ=0.535 (val F1=0.1830)
  Directional -> Accuracy: 0.5319, MCC: 0.0708, F1: 0.5769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63465 | val 0.99252
  Epoch 016 - train 0.41323 | val 1.78254
  Classification -> best τ=0.505 (val F1=0.1482)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49202 | val 1.63796
  Epoch 016 - train 0.30483 | val 1.28355
  Classification -> best τ=0.500 (val F1=0.2599)
  Directional -> Accuracy: 0.5263, MCC: 0.0596, F1: 0.5424

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51408 | val 1.54427
  Epoch 016 - train 0.36609 | val 2.90486
  Classification -> best τ=0.585 (val F1=0.2177)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43510 | val 2.58333
  Epoch 016 - train 0.32664 | val 3.92981
  Classification -> best τ=0.525 (val F1=0.2974)
  Directional -> Accuracy: 0.4909, MCC: 0.0659, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.36973 | val 3.53724
  Epoch 016 - train 0.17788 | val 6.09889
  Classification -> best τ=0.605 (val F1=0.3039)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52646 | val 1.11733
  Epoch 016 - train 0.36867 | val 1.16718
  Classification -> best τ=0.480 (val F1=0.0807)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45943 | val 2.22974
  Epoch 016 - train 0.32100 | val 3.12814
  Classification -> best τ=0.385 (val F1=0.1607)
  Directional -> Accuracy: 0.5536, MCC: 0.1446, F1: 0.5098

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41395 | val 3.97431
  Epoch 016 - train 0.28512 | val 5.33055
  Classification -> best τ=0.515 (val F1=0.0601)
  Directional -> Accuracy: 0.6000, MCC: 0.1919, F1: 0.6364

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40480 | val 0.91536
  Epoch 016 - train 0.26002 | val 0.95788
  Classification -> best τ=0.560 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0337, F1: 0.4118

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47653 | val 1.97130
  Epoch 017 - train 0.28090 | val 4.05060
  Classification -> best τ=0.505 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42748 | val 1.21272
  Epoch 016 - train 0.26647 | val 1.60609
  Classification -> best τ=0.465 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52335 | val 2.80782
  Epoch 016 - train 0.42528 | val 2.86207
  Classification -> best τ=0.525 (val F1=0.2466)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41698 | val 1.84362
  Epoch 017 - train 0.21250 | val 2.20814
  Classification -> best τ=0.705 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47907 | val 0.99814
  Epoch 016 - train 0.38666 | val 1.05614
  Classification -> best τ=0.490 (val F1=0.1912)
  Directional -> Accuracy: 0.6212, MCC: 0.3061, F1: 0.5902

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44530 | val 1.28299
  Epoch 016 - train 0.24497 | val 1.39056
  Classification -> best τ=0.430 (val F1=0.0866)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46071 | val 2.93795
  Epoch 016 - train 0.33869 | val 5.85815
  Classification -> best τ=0.255 (val F1=0.2450)
  Directional -> Accuracy: 0.5714, MCC: 0.1623, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46619 | val 0.89334
  Epoch 016 - train 0.25416 | val 1.88186
  Classification -> best τ=0.555 (val F1=0.3089)
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40773 | val 1.02359
  Epoch 017 - train 0.28912 | val 1.03375
  Classification -> best τ=0.460 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51773 | val 2.51814
  Epoch 016 - train 0.38887 | val 3.98909
  Classification -> best τ=0.240 (val F1=0.3533)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42998 | val 1.37362
  Epoch 018 - train 0.28362 | val 2.49242
  Classification -> best τ=0.660 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.1632, F1: 0.6875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42135 | val 1.65088
  Epoch 016 - train 0.18952 | val 1.91988
  Classification -> best τ=0.640 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43678 | val 1.30982
  Epoch 020 - train 0.17855 | val 2.29359
  Classification -> best τ=0.505 (val F1=0.3895)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57468 | val 0.92695
  Epoch 016 - train 0.35990 | val 2.22369
  Classification -> best τ=0.525 (val F1=0.1154)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48014 | val 3.50486
  Epoch 016 - train 0.34105 | val 4.56175
  Classification -> best τ=0.755 (val F1=0.4185)
  Directional -> Accuracy: 0.5357, MCC: 0.0930, F1: 0.6061

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48243 | val 1.02731
  Epoch 016 - train 0.41813 | val 1.75749
  Classification -> best τ=0.475 (val F1=0.1646)
  Directional -> Accuracy: 0.5472, MCC: 0.1483, F1: 0.6842

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41621 | val 5.60915
  Epoch 016 - train 0.28769 | val 4.68488
  Classification -> best τ=0.845 (val F1=0.0462)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50390 | val 2.38889

[I 2026-02-20 00:21:02,671] Trial 49 finished with value: 0.23798564601731398 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.008149819993021218, 'weight_decay': 2.7199324630199975e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.7116240247203884, 'early_stopping_min_delta': 0.005169852673951371}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.29948 | val 1.19090
  Classification -> best τ=0.535 (val F1=0.1489)
  Directional -> Accuracy: 0.4833, MCC: -0.0292, F1: 0.5079

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23798564601731398
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61565 | val 0.66921
  Epoch 017 - train 0.59444 | val 0.74941
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.5132, MCC: -0.1320, F1: 0.0513

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62983 | val 0.67862
  Epoch 018 - train 0.53696 | val 0.85986
  Classification -> best τ=0.425 (val F1=0.1058)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64139 | val 0.74849
  Epoch 019 - train 0.57243 | val 1.09438
  Classification -> best τ=0.505 (val F1=0.3482)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65545 | val 0.92042
  Epoch 016 - train 0.61247 | val 0.80075
  Classification -> best τ=0.450 (val F1=0.2228)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59774 | val 0.63985
  Epoch 020 - train 0.53852 | val 0.88758
  Classification -> best τ=0.530 (val F1=0.4751)
  Directional -> Accuracy: 0.7000, MCC: 0.4003, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60250 | val 0.72431
  Epoch 019 - train 0.52489 | val 0.97982
  Classification -> best τ=0.510 (val F1=0.3222)
  Directional -> Accuracy: 0.6304, MCC: 0.2575, F1: 0.5854

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64250 | val 0.81505
  Epoch 018 - train 0.60885 | val 1.00702
  Classification -> best τ=0.415 (val F1=0.2228)
  Directional -> Accuracy: 0.4412, MCC: 0.1743, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59928 | val 1.05386
  Epoch 020 - train 0.52556 | val 1.52022
  Classification -> best τ=0.450 (val F1=0.1228)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63478 | val 0.78795
  Epoch 019 - train 0.55626 | val 0.94170
  Classification -> best τ=0.620 (val F1=0.2233)
  Directional -> Accuracy: 0.5833, MCC: 0.1193, F1: 0.1667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61337 | val 0.70357
  Epoch 017 - train 0.60236 | val 0.73349
  Classification -> best τ=0.525 (val F1=0.1427)
  Directional -> Accuracy: 0.4783, MCC: -0.0044, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65772 | val 0.71850
  Epoch 016 - train 0.63481 | val 0.74420
  Classification -> best τ=0.460 (val F1=0.2487)
  Directional -> Accuracy: 0.6122, MCC: 0.2178, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64856 | val 0.93138
  Epoch 017 - train 0.60315 | val 1.27786
  Classification -> best τ=0.450 (val F1=0.2536)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55221 | val 1.16307
  Epoch 016 - train 0.53499 | val 1.86785
  Classification -> best τ=0.525 (val F1=0.1308)
  Directional -> Accuracy: 0.6190, MCC: 0.2202, F1: 0.4667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66074 | val 0.69711
  Epoch 020 - train 0.57091 | val 0.76425
  Epoch 021 - train 0.55400 | val 0.77523
  Classification -> best τ=0.405 (val F1=0.3268)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.5333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62478 | val 0.75391
  Epoch 016 - train 0.56809 | val 0.77177
  Classification -> best τ=0.500 (val F1=0.2084)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61146 | val 0.88201
  Epoch 017 - train 0.53325 | val 0.97965
  Classification -> best τ=0.580 (val F1=0.1963)
  Directional -> Accuracy: 0.5652, MCC: 0.1389, F1: 0.5588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63537 | val 0.93701
  Epoch 016 - train 0.60041 | val 1.07070
  Classification -> best τ=0.580 (val F1=0.1510)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67321 | val 0.95697
  Epoch 019 - train 0.62898 | val 1.21423
  Classification -> best τ=0.560 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63812 | val 0.72693
  Epoch 017 - train 0.60737 | val 0.79259
  Classification -> best τ=0.435 (val F1=0.3689)
  Directional -> Accuracy: 0.5469, MCC: 0.0384, F1: 0.6420

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60196 | val 0.74159
  Epoch 017 - train 0.57686 | val 0.71084
  Classification -> best τ=0.575 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62664 | val 0.69434
  Epoch 020 - train 0.57373 | val 0.84492
  Epoch 021 - train 0.54602 | val 0.82136
  Classification -> best τ=0.505 (val F1=0.2247)
  Directional -> Accuracy: 0.5957, MCC: 0.0392, F1: 0.7246

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65327 | val 0.75289
  Epoch 016 - train 0.64124 | val 0.88467
  Classification -> best τ=0.530 (val F1=0.0198)
  Directional -> Accuracy: 0.5231, MCC: 0.0626, F1: 0.3673

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62845 | val 0.81067
  Epoch 016 - train 0.57921 | val 0.88912
  Classification -> best τ=0.625 (val F1=0.3254)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64764 | val 0.69192
  Epoch 017 - train 0.56901 | val 0.68314
  Classification -> best τ=0.565 (val F1=0.1565)
  Directional -> Accuracy: 0.5231, MCC: 0.0428, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57293 | val 1.12277
  Epoch 020 - train 0.48511 | val 1.12453
  Epoch 021 - train 0.49265 | val 1.18563
  Classification -> best τ=0.685 (val F1=0.5116)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59640 | val 0.81932
  Epoch 016 - train 0.51882 | val 1.06694
  Classification -> best τ=0.540 (val F1=0.1310)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64667 | val 0.71398
  Epoch 016 - train 0.61569 | val 0.72602
  Classification -> best τ=0.595 (val F1=0.1353)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63456 | val 0.84104
  Epoch 017 - train 0.57063 | val 1.05109
  Classification -> best τ=0.380 (val F1=0.2371)
  Directional -> Accuracy: 0.5536, MCC: 0.2311, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65195 | val 0.80805
  Epoch 020 - train 0.60831 | val 0.82252
  Epoch 028 - train 0.46476 | val 1.00726
  Classification -> best τ=0.480 (val F1=0.4139)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66227 | val 1.05631
  Epoch 016 - train 0.61398 | val 1.19084
  Classification -> best τ=0.540 (val F1=0.3501)
  Directional -> Accuracy: 0.4524, MCC: -0.1342, F1: 0.2581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64365 | val 0.76136
  Epoch 016 - train 0.62487 | val 1.30867
  Classification -> best τ=0.435 (val F1=0.2042)
  Directional -> Accuracy: 0.5000, MCC: -0.0754, F1: 0.6316

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61776 | val 0.84835
  Epoch 018 - train 0.52845 | val 1.13557
  Classification -> best τ=0.600 (val F1=0.3465)
  Directional -> Accuracy: 0.5714, MCC: 0.1299, F1: 0.6441

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59370 | val 0.72344
  Epoch 020 - train 0.54501 | val 0.88065
  Epoch 022 - train 0.55254 | val 1.15132
  Classification -> best τ=0.350 (val F1=0.3196)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60760 | val 1.09888
  Epoch 016 - train 0.59100 | val 1.32721
  Classification -> best τ=0.435 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62371 | val 1.00638
  Epoch 016 - train 0.58296 | val 1.07695
  Classification -> best τ=0.485 (val F1=0.2809)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59825 | val 0.77944
  Epoch 016 - train 0.54745 | val 0.79279
  Classification -> best τ=0.480 (val F1=0.2658)
  Directional -> Accuracy: 0.6429, MCC: 0.2860, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60994 | val 0.76740
  Epoch 016 - train 0.56415 | val 0.80236
  Classification -> best τ=0.385 (val F1=0.2804)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59670 | val 1.02879
  Epoch 016 - train 0.53332 | val 1.37482
  Classification -> best τ=0.485 (val F1=0.2024)
  Directional -> Accuracy: 0.3696, MCC: -0.1493, F1: 0.1212

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58027 | val 0.64270
  Epoch 020 - train 0.54756 | val 0.69660
  Epoch 027 - train 0.51438 | val 0.68564
  Classification -> best τ=0.300 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60629 | val 0.81295
  Epoch 017 - train 0.53048 | val 1.04412
  Classification -> best τ=0.510 (val F1=0.2782)
  Directional -> Accuracy: 0.5270, MCC: 0.2001, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65094 | val 0.71424
  Epoch 019 - train 0.61567 | val 0.72889
  Classification -> best τ=0.525 (val F1=0.2562)
  Directional -> Accuracy: 0.6222, MCC: 0.2713, F1: 0.7018

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58829 | val 0.68127
  Epoch 020 - train 0.55947 | val 0.67094
  Epoch 027 - train 0.52875 | val 0.68794
  Classification -> best τ=0.440 (val F1=0.5092)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58356 | val 0.75402
  Epoch 020 - train 0.52063 | val 0.78315
  Epoch 027 - train 0.42913 | val 0.95328
  Classification -> best τ=0.570 (val F1=0.4478)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65288 | val 0.69360
  Epoch 016 - train 0.61565 | val 0.69885
  Classification -> best τ=0.565 (val F1=0.0361)
  Directional -> Accuracy: 0.3273, MCC: -0.3864, F1: 0.4308

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59360 | val 1.78499
  Epoch 016 - train 0.54514 | val 2.53514
  Classification -> best τ=0.605 (val F1=0.3111)
  Directional -> Accuracy: 0.5357, MCC: 0.0930, F1: 0.6061

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63722 | val 0.86700
  Epoch 020 - train 0.60998 | val 1.03184
  Epoch 027 - train 0.54746 | val 1.07626
  Classification -> best τ=0.625 (val F1=0.3010)
  Directional -> Accuracy: 0.5660, MCC: 0.1998, F1: 0.6933

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61001 | val 0.92150
  Epoch 017 - train 0.54396 | val 1.04802
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61285 | val 0.90185

[I 2026-02-20 00:22:30,193] Trial 50 finished with value: 0.25814660329265565 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00770827566799562, 'weight_decay': 1.1821551816303728e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.3337087256437696, 'early_stopping_min_delta': 0.006173532985407435}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.58092 | val 0.87064
  Classification -> best τ=0.405 (val F1=0.3213)
  Directional -> Accuracy: 0.4000, MCC: -0.2045, F1: 0.3571

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25814660329265565
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61719 | val 0.90487
  Epoch 020 - train 0.52224 | val 1.34827
  Epoch 021 - train 0.49600 | val 1.33572
  Classification -> best τ=0.805 (val F1=0.2989)
  Directional -> Accuracy: 0.5067, MCC: -0.0536, F1: 0.2449

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58767 | val 0.74406
  Epoch 020 - train 0.46896 | val 0.78569
  Epoch 024 - train 0.44659 | val 0.78062
  Classification -> best τ=0.440 (val F1=0.3444)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57165 | val 1.07025
  Epoch 016 - train 0.47730 | val 1.14684
  Classification -> best τ=0.560 (val F1=0.2641)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62943 | val 2.88650
  Epoch 016 - train 0.59045 | val 3.18310
  Classification -> best τ=0.385 (val F1=0.1749)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48384 | val 0.99388
  Epoch 016 - train 0.45245 | val 1.02094
  Classification -> best τ=0.640 (val F1=0.3748)
  Directional -> Accuracy: 0.5714, MCC: 0.1923, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49787 | val 1.08791
  Epoch 016 - train 0.39463 | val 1.31146
  Classification -> best τ=0.480 (val F1=0.3389)
  Directional -> Accuracy: 0.5556, MCC: 0.1188, F1: 0.3750

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58445 | val 0.97367
  Epoch 016 - train 0.51778 | val 1.18128
  Classification -> best τ=0.450 (val F1=0.2056)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46808 | val 3.13951
  Epoch 016 - train 0.47914 | val 3.79428
  Classification -> best τ=0.545 (val F1=0.3637)
  Directional -> Accuracy: 0.5854, MCC: 0.1751, F1: 0.5641

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56685 | val 0.94284
  Epoch 016 - train 0.48347 | val 1.20385
  Classification -> best τ=0.600 (val F1=0.3148)
  Directional -> Accuracy: 0.5106, MCC: -0.0037, F1: 0.4103

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54941 | val 1.53542
  Epoch 016 - train 0.49424 | val 1.65332
  Classification -> best τ=0.410 (val F1=0.1689)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55897 | val 0.97670
  Epoch 016 - train 0.47110 | val 1.07564
  Classification -> best τ=0.550 (val F1=0.1556)
  Directional -> Accuracy: 0.5833, MCC: 0.1496, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53605 | val 1.40779
  Epoch 016 - train 0.49780 | val 1.53922
  Classification -> best τ=0.380 (val F1=0.2420)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49986 | val 3.29982
  Epoch 016 - train 0.41486 | val 3.54482
  Classification -> best τ=0.405 (val F1=0.2112)
  Directional -> Accuracy: 0.4490, MCC: -0.1138, F1: 0.3415

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61287 | val 0.72642
  Epoch 016 - train 0.55955 | val 0.72494
  Classification -> best τ=0.450 (val F1=0.3346)
  Directional -> Accuracy: 0.5254, MCC: 0.0506, F1: 0.5333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54604 | val 1.41614
  Epoch 016 - train 0.48191 | val 1.53090
  Classification -> best τ=0.615 (val F1=0.2060)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55633 | val 1.29186
  Epoch 016 - train 0.46437 | val 1.53327
  Classification -> best τ=0.490 (val F1=0.3277)
  Directional -> Accuracy: 0.6029, MCC: 0.2404, F1: 0.7158

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58762 | val 1.49468
  Epoch 016 - train 0.50716 | val 1.85055
  Classification -> best τ=0.755 (val F1=0.1826)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56846 | val 1.20385
  Epoch 016 - train 0.51628 | val 1.94497
  Classification -> best τ=0.390 (val F1=0.2228)
  Directional -> Accuracy: 0.5676, MCC: -0.0757, F1: 0.7193

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55762 | val 1.71625
  Epoch 016 - train 0.51499 | val 2.03267
  Classification -> best τ=0.550 (val F1=0.1372)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54615 | val 0.86799
  Epoch 017 - train 0.47884 | val 0.95212
  Classification -> best τ=0.420 (val F1=0.2732)
  Directional -> Accuracy: 0.5342, MCC: 0.0149, F1: 0.6531

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53550 | val 1.47985
  Epoch 016 - train 0.50669 | val 2.15754
  Classification -> best τ=0.395 (val F1=0.2227)
  Directional -> Accuracy: 0.6304, MCC: 0.1660, F1: 0.7385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59425 | val 2.02844
  Epoch 016 - train 0.52687 | val 2.31932
  Classification -> best τ=0.710 (val F1=0.0276)
  Directional -> Accuracy: 0.5469, MCC: 0.1165, F1: 0.3556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55647 | val 2.29159
  Epoch 016 - train 0.48203 | val 2.63477
  Classification -> best τ=0.800 (val F1=0.3062)
  Directional -> Accuracy: 0.5536, MCC: 0.1362, F1: 0.5455

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53888 | val 0.82712
  Epoch 016 - train 0.45957 | val 1.14172
  Classification -> best τ=0.495 (val F1=0.2106)
  Directional -> Accuracy: 0.5156, MCC: 0.1285, F1: 0.6437

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48440 | val 0.91300
  Epoch 016 - train 0.43335 | val 1.23250
  Classification -> best τ=0.595 (val F1=0.5231)
  Directional -> Accuracy: 0.4630, MCC: -0.0263, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51987 | val 0.72029
  Epoch 019 - train 0.38259 | val 1.20863
  Classification -> best τ=0.530 (val F1=0.4805)
  Directional -> Accuracy: 0.4419, MCC: -0.0993, F1: 0.4286

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61386 | val 0.79203
  Epoch 020 - train 0.44918 | val 0.80007
  Epoch 023 - train 0.44431 | val 1.27680
  Classification -> best τ=0.590 (val F1=0.2952)
  Directional -> Accuracy: 0.6531, MCC: 0.2534, F1: 0.7385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52671 | val 1.67879
  Epoch 016 - train 0.47962 | val 2.02898
  Classification -> best τ=0.480 (val F1=0.2203)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54637 | val 0.70576
  Epoch 016 - train 0.51850 | val 0.73979
  Classification -> best τ=0.490 (val F1=0.2496)
  Directional -> Accuracy: 0.5263, MCC: 0.0420, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49854 | val 2.40530
  Epoch 016 - train 0.47394 | val 2.49212
  Classification -> best τ=0.690 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53538 | val 1.60886
  Epoch 016 - train 0.45321 | val 2.01193
  Classification -> best τ=0.465 (val F1=0.2339)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48034 | val 0.81656
  Epoch 016 - train 0.43739 | val 1.04000
  Classification -> best τ=0.650 (val F1=0.2382)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52587 | val 1.33597
  Epoch 016 - train 0.50176 | val 1.66973
  Classification -> best τ=0.420 (val F1=0.2946)
  Directional -> Accuracy: 0.5352, MCC: 0.1773, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49275 | val 0.97127
  Epoch 016 - train 0.42729 | val 1.17861
  Classification -> best τ=0.610 (val F1=0.2820)
  Directional -> Accuracy: 0.5476, MCC: 0.0853, F1: 0.2963

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50454 | val 1.05488
  Epoch 016 - train 0.46654 | val 1.21295
  Classification -> best τ=0.315 (val F1=0.3218)
  Directional -> Accuracy: 0.6154, MCC: 0.2352, F1: 0.6377

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49982 | val 0.77260
  Epoch 017 - train 0.46243 | val 0.92224
  Classification -> best τ=0.500 (val F1=0.2697)
  Directional -> Accuracy: 0.6500, MCC: 0.3394, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55494 | val 0.87040
  Epoch 016 - train 0.47071 | val 0.96119
  Classification -> best τ=0.385 (val F1=0.2494)
  Directional -> Accuracy: 0.4909, MCC: 0.0305, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47572 | val 1.90282
  Epoch 016 - train 0.39197 | val 2.02095
  Classification -> best τ=0.520 (val F1=0.3714)
  Directional -> Accuracy: 0.5778, MCC: -0.1680, F1: 0.7324

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45390 | val 0.70420
  Epoch 017 - train 0.45647 | val 0.79773
  Classification -> best τ=0.560 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54011 | val 2.20502
  Epoch 016 - train 0.48260 | val 2.93428
  Classification -> best τ=0.640 (val F1=0.1237)
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56088 | val 1.28064
  Epoch 017 - train 0.54956 | val 1.54118
  Classification -> best τ=0.525 (val F1=0.3536)
  Directional -> Accuracy: 0.4773, MCC: -0.0563, F1: 0.5965

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47794 | val 1.22685
  Epoch 016 - train 0.37782 | val 1.39065
  Classification -> best τ=0.505 (val F1=0.1309)
  Directional -> Accuracy: 0.4634, MCC: -0.0701, F1: 0.5000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55282 | val 1.84387
  Epoch 020 - train 0.32297 | val 2.45500
  Epoch 024 - train 0.22427 | val 2.86291
  Classification -> best τ=0.770 (val F1=0.3476)
  Directional -> Accuracy: 0.5652, MCC: 0.3236, F1: 0.6154

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64221 | val 1.82118
  Epoch 016 - train 0.58736 | val 2.07583
  Classification -> best τ=0.455 (val F1=0.3200)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54300 | val 3.35920
  Epoch 016 - train 0.48560 | val 3.87930
  Classification -> best τ=0.460 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61772 | val 0.79693
  Epoch 020 - train 0.49220 | val 1.42606
  Epoch 024 - train 0.37821 | val 1.74036
  Classification -> best τ=0.290 (val F1=0.2430)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54514 | val 1.46572
  Epoch 017 - train 0.49912 | val 2.01829
  Classification -> best τ=0.555 (val F1=0.2128)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57413 | val 0.85889

[I 2026-02-20 00:26:02,366] Trial 51 finished with value: 0.26926556185298023 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.004093043333045334, 'weight_decay': 6.82199302657955e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.5125299675419983, 'early_stopping_min_delta': 0.004365467138495861}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 018 - train 0.46805 | val 1.61434
  Classification -> best τ=0.475 (val F1=0.2608)
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26926556185298023
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65852 | val 0.68625
  Epoch 020 - train 0.54321 | val 1.15374
  Epoch 022 - train 0.48126 | val 1.09574
  Classification -> best τ=0.815 (val F1=0.2989)
  Directional -> Accuracy: 0.5200, MCC: -0.0711, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56059 | val 0.80418
  Epoch 017 - train 0.46020 | val 0.79401
  Classification -> best τ=0.430 (val F1=0.1283)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57621 | val 0.79616
  Epoch 016 - train 0.47289 | val 0.96817
  Classification -> best τ=0.595 (val F1=0.3441)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63472 | val 0.88197
  Epoch 016 - train 0.56912 | val 1.44977
  Classification -> best τ=0.400 (val F1=0.0494)
  Directional -> Accuracy: 0.4932, MCC: 0.0363, F1: 0.3019

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49897 | val 1.66690
  Epoch 016 - train 0.40786 | val 2.68151
  Classification -> best τ=0.585 (val F1=0.5487)
  Directional -> Accuracy: 0.6531, MCC: 0.3153, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45733 | val 1.91110
  Epoch 020 - train 0.31669 | val 1.43745
  Epoch 022 - train 0.23118 | val 1.56728
  Classification -> best τ=0.375 (val F1=0.3188)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.6567

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61115 | val 0.98968
  Epoch 018 - train 0.44196 | val 1.56594
  Classification -> best τ=0.515 (val F1=0.2364)
  Directional -> Accuracy: 0.5224, MCC: 0.0667, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43447 | val 1.39638
  Epoch 019 - train 0.33746 | val 3.35037
  Classification -> best τ=0.725 (val F1=0.3612)
  Directional -> Accuracy: 0.4146, MCC: -0.1299, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63177 | val 1.05233
  Epoch 019 - train 0.49239 | val 0.85330
  Classification -> best τ=0.415 (val F1=0.1974)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55389 | val 1.47755
  Epoch 017 - train 0.43740 | val 1.80773
  Classification -> best τ=0.375 (val F1=0.0730)
  Directional -> Accuracy: 0.4559, MCC: 0.1501, F1: 0.6105

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59814 | val 0.89952
  Epoch 017 - train 0.50383 | val 0.99743
  Classification -> best τ=0.545 (val F1=0.3578)
  Directional -> Accuracy: 0.6042, MCC: 0.2807, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57163 | val 1.52604
  Epoch 016 - train 0.46789 | val 1.97870
  Classification -> best τ=0.605 (val F1=0.1792)
  Directional -> Accuracy: 0.6786, MCC: 0.3783, F1: 0.6400

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49542 | val 4.49905
  Epoch 016 - train 0.37890 | val 5.38666
  Classification -> best τ=0.405 (val F1=0.2094)
  Directional -> Accuracy: 0.4694, MCC: -0.0637, F1: 0.4348

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63608 | val 0.65133
  Epoch 020 - train 0.48866 | val 0.74185
  Epoch 022 - train 0.48034 | val 0.78976
  Classification -> best τ=0.220 (val F1=0.2650)
  Directional -> Accuracy: 0.5593, MCC: 0.1486, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59780 | val 1.28787
  Epoch 016 - train 0.50241 | val 1.21549
  Classification -> best τ=0.550 (val F1=0.2157)
  Directional -> Accuracy: 0.4400, MCC: -0.0679, F1: 0.5333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55253 | val 1.33844
  Epoch 016 - train 0.42179 | val 1.58470
  Classification -> best τ=0.605 (val F1=0.0932)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55083 | val 0.94601
  Epoch 016 - train 0.50858 | val 0.84994
  Classification -> best τ=0.545 (val F1=0.1034)
  Directional -> Accuracy: 0.3684, MCC: -0.2583, F1: 0.4194

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61405 | val 1.19106
  Epoch 017 - train 0.51061 | val 1.41979
  Classification -> best τ=0.455 (val F1=0.1722)
  Directional -> Accuracy: 0.5811, MCC: 0.1265, F1: 0.6517

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58793 | val 1.35479
  Epoch 017 - train 0.48998 | val 1.64878
  Classification -> best τ=0.685 (val F1=0.2288)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57548 | val 0.76465
  Epoch 018 - train 0.43830 | val 1.13295
  Classification -> best τ=0.500 (val F1=0.3590)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53183 | val 1.11174
  Epoch 016 - train 0.45082 | val 1.07755
  Classification -> best τ=0.365 (val F1=0.1557)
  Directional -> Accuracy: 0.6087, MCC: 0.1174, F1: 0.7188

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58849 | val 1.23947
  Epoch 016 - train 0.51175 | val 1.75758
  Classification -> best τ=0.735 (val F1=0.0276)
  Directional -> Accuracy: 0.5938, MCC: 0.2085, F1: 0.4800

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54708 | val 2.57474
  Epoch 016 - train 0.49283 | val 2.90878
  Classification -> best τ=0.515 (val F1=0.2640)
  Directional -> Accuracy: 0.6071, MCC: 0.2222, F1: 0.7442

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57958 | val 1.18566
  Epoch 020 - train 0.47180 | val 0.84057
  Epoch 021 - train 0.44845 | val 0.85524
  Classification -> best τ=0.680 (val F1=0.1932)
  Directional -> Accuracy: 0.4844, MCC: 0.0073, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51344 | val 1.08050
  Epoch 017 - train 0.39199 | val 1.40899
  Classification -> best τ=0.505 (val F1=0.4979)
  Directional -> Accuracy: 0.5185, MCC: 0.1008, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47258 | val 1.29122
  Epoch 016 - train 0.39363 | val 1.31379
  Classification -> best τ=0.480 (val F1=0.3118)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61611 | val 0.92825
  Epoch 016 - train 0.52873 | val 0.76490
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53521 | val 1.50075
  Epoch 016 - train 0.47128 | val 2.13840
  Classification -> best τ=0.415 (val F1=0.1757)
  Directional -> Accuracy: 0.5455, MCC: 0.1257, F1: 0.4898

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51301 | val 0.75187
  Epoch 017 - train 0.44992 | val 0.89011
  Classification -> best τ=0.465 (val F1=0.3708)
  Directional -> Accuracy: 0.5526, MCC: 0.0547, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57243 | val 1.69768
  Epoch 016 - train 0.41735 | val 1.77810
  Classification -> best τ=0.645 (val F1=0.2706)
  Directional -> Accuracy: 0.4878, MCC: -0.0321, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47553 | val 1.41246
  Epoch 016 - train 0.43471 | val 1.87284
  Classification -> best τ=0.425 (val F1=0.1992)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50347 | val 0.84468
  Epoch 016 - train 0.36141 | val 1.09903
  Classification -> best τ=0.540 (val F1=0.2949)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55616 | val 1.28314
  Epoch 016 - train 0.49889 | val 1.43291
  Classification -> best τ=0.570 (val F1=0.2254)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61324 | val 1.06322
  Epoch 020 - train 0.39701 | val 1.14713
  Classification -> best τ=0.370 (val F1=0.2386)
  Directional -> Accuracy: 0.4286, MCC: -0.1376, F1: 0.4545

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51057 | val 1.23616
  Epoch 016 - train 0.44232 | val 1.95935
  Classification -> best τ=0.215 (val F1=0.2936)
  Directional -> Accuracy: 0.5692, MCC: 0.1142, F1: 0.6316

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49160 | val 0.86798
  Epoch 017 - train 0.39584 | val 1.00287
  Classification -> best τ=0.515 (val F1=0.1909)
  Directional -> Accuracy: 0.4750, MCC: -0.0115, F1: 0.0870

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52955 | val 1.13131
  Epoch 016 - train 0.45243 | val 1.16758
  Classification -> best τ=0.260 (val F1=0.2544)
  Directional -> Accuracy: 0.5273, MCC: 0.0920, F1: 0.5806

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42403 | val 1.90027
  Epoch 016 - train 0.37361 | val 1.77228
  Classification -> best τ=0.665 (val F1=0.4267)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52866 | val 0.67069
  Epoch 020 - train 0.33488 | val 0.68181
  Epoch 024 - train 0.29050 | val 0.70789
  Classification -> best τ=0.420 (val F1=0.5795)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57564 | val 1.80683
  Epoch 016 - train 0.44545 | val 3.42642
  Classification -> best τ=0.750 (val F1=0.1237)
  Directional -> Accuracy: 0.4932, MCC: -0.0121, F1: 0.5195

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59425 | val 0.99724
  Epoch 017 - train 0.46761 | val 0.98504
  Classification -> best τ=0.505 (val F1=0.2902)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6071

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46081 | val 1.28755
  Epoch 016 - train 0.33660 | val 1.44427
  Classification -> best τ=0.625 (val F1=0.0510)
  Directional -> Accuracy: 0.4146, MCC: -0.0570, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41744 | val 0.92355
  Epoch 016 - train 0.38081 | val 1.89677
  Classification -> best τ=0.455 (val F1=0.2111)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61722 | val 1.47488
  Epoch 016 - train 0.56539 | val 2.26731
  Classification -> best τ=0.500 (val F1=0.1386)
  Directional -> Accuracy: 0.3519, MCC: -0.3182, F1: 0.4262

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53448 | val 2.65151
  Epoch 016 - train 0.44590 | val 3.49223
  Classification -> best τ=0.265 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59690 | val 0.85116
  Epoch 018 - train 0.46950 | val 1.35130
  Classification -> best τ=0.780 (val F1=0.2376)
  Directional -> Accuracy: 0.5962, MCC: 0.1936, F1: 0.5714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54357 | val 0.68240
  Epoch 020 - train 0.32858 | val 0.94162
  Epoch 025 - train 0.30321 | val 0.99980
  Classification -> best τ=0.285 (val F1=0.2649)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58953 | val 0.75692

[I 2026-02-20 00:29:37,061] Trial 52 finished with value: 0.24087518400651356 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.006483390201055891, 'weight_decay': 7.164772846293929e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.5502742816104222, 'early_stopping_min_delta': 0.004643902749238658}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.47157 | val 0.89923
  Classification -> best τ=0.440 (val F1=0.2881)
  Directional -> Accuracy: 0.4915, MCC: -0.0352, F1: 0.3750

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24087518400651356
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61668 | val 0.73523
  Epoch 020 - train 0.51582 | val 1.23124
  Epoch 023 - train 0.48831 | val 1.30540
  Classification -> best τ=0.560 (val F1=0.2571)
  Directional -> Accuracy: 0.5333, MCC: -0.0160, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55193 | val 0.89618
  Epoch 016 - train 0.49677 | val 0.99917
  Classification -> best τ=0.405 (val F1=0.0538)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55182 | val 0.86935
  Epoch 016 - train 0.51151 | val 0.90995
  Classification -> best τ=0.510 (val F1=0.3563)
  Directional -> Accuracy: 0.4444, MCC: -0.0891, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61357 | val 2.41738
  Epoch 016 - train 0.57798 | val 2.81540
  Classification -> best τ=0.420 (val F1=0.1880)
  Directional -> Accuracy: 0.5479, MCC: 0.0810, F1: 0.6118

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48890 | val 0.89468
  Epoch 016 - train 0.43034 | val 1.50269
  Classification -> best τ=0.685 (val F1=0.3426)
  Directional -> Accuracy: 0.5102, MCC: 0.0500, F1: 0.2500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50608 | val 2.07631
  Epoch 020 - train 0.34707 | val 0.90408
  Classification -> best τ=0.640 (val F1=0.3859)
  Directional -> Accuracy: 0.5778, MCC: 0.1590, F1: 0.5957

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55376 | val 1.00683
  Epoch 016 - train 0.53318 | val 1.06304
  Classification -> best τ=0.475 (val F1=0.1931)
  Directional -> Accuracy: 0.5224, MCC: 0.0667, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51325 | val 2.88294
  Epoch 016 - train 0.44690 | val 3.61903
  Classification -> best τ=0.555 (val F1=0.0727)
  Directional -> Accuracy: 0.4146, MCC: -0.1365, F1: 0.4783

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54368 | val 0.81894
  Epoch 018 - train 0.49169 | val 1.25916
  Classification -> best τ=0.525 (val F1=0.3773)
  Directional -> Accuracy: 0.4255, MCC: -0.1097, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54245 | val 1.66517
  Epoch 016 - train 0.49495 | val 2.07397
  Classification -> best τ=0.345 (val F1=0.2279)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58604 | val 1.60129
  Epoch 016 - train 0.53899 | val 1.92193
  Classification -> best τ=0.570 (val F1=0.2182)
  Directional -> Accuracy: 0.4792, MCC: 0.1342, F1: 0.6377

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55352 | val 1.38944
  Epoch 016 - train 0.50373 | val 1.60616
  Classification -> best τ=0.420 (val F1=0.2067)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46864 | val 4.87848
  Epoch 016 - train 0.39051 | val 5.87293
  Classification -> best τ=0.330 (val F1=0.3039)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59332 | val 0.75093
  Epoch 017 - train 0.55187 | val 0.78743
  Classification -> best τ=0.555 (val F1=0.3428)
  Directional -> Accuracy: 0.5763, MCC: 0.1546, F1: 0.5614

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53270 | val 1.11236
  Epoch 016 - train 0.53896 | val 1.41262
  Classification -> best τ=0.595 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56938 | val 1.32201
  Epoch 017 - train 0.46703 | val 1.86793
  Classification -> best τ=0.435 (val F1=0.3279)
  Directional -> Accuracy: 0.6471, MCC: 0.3572, F1: 0.7447

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56501 | val 1.19172
  Epoch 016 - train 0.51616 | val 1.48573
  Classification -> best τ=0.675 (val F1=0.1843)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58875 | val 1.23442
  Epoch 016 - train 0.53499 | val 1.02210
  Classification -> best τ=0.330 (val F1=0.1115)
  Directional -> Accuracy: 0.6081, MCC: 0.1417, F1: 0.7521

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58008 | val 1.43888
  Epoch 016 - train 0.52073 | val 2.25172
  Classification -> best τ=0.450 (val F1=0.0092)
  Directional -> Accuracy: 0.4444, MCC: -0.0832, F1: 0.4444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51147 | val 0.73963
  Epoch 017 - train 0.42833 | val 0.72599
  Classification -> best τ=0.445 (val F1=0.3060)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51701 | val 1.39273
  Epoch 016 - train 0.50302 | val 1.61544
  Classification -> best τ=0.500 (val F1=0.1427)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59279 | val 1.90077
  Epoch 016 - train 0.54838 | val 1.97557
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57551 | val 1.44631
  Epoch 016 - train 0.48455 | val 2.55914
  Classification -> best τ=0.560 (val F1=0.3267)
  Directional -> Accuracy: 0.5893, MCC: 0.1659, F1: 0.6349

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56018 | val 0.85264
  Epoch 018 - train 0.45523 | val 0.97873
  Classification -> best τ=0.375 (val F1=0.1604)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49660 | val 0.97204
  Epoch 017 - train 0.43853 | val 1.26184
  Classification -> best τ=0.550 (val F1=0.4835)
  Directional -> Accuracy: 0.4444, MCC: -0.0991, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48564 | val 1.20395
  Epoch 017 - train 0.42787 | val 1.89469
  Classification -> best τ=0.490 (val F1=0.3118)
  Directional -> Accuracy: 0.4186, MCC: -0.1027, F1: 0.4898

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55392 | val 0.70417
  Epoch 020 - train 0.47289 | val 0.74772
  Epoch 029 - train 0.44618 | val 0.71766
  Classification -> best τ=0.625 (val F1=0.2764)
  Directional -> Accuracy: 0.5306, MCC: 0.0983, F1: 0.5306

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56246 | val 1.60095
  Epoch 016 - train 0.51980 | val 1.99138
  Classification -> best τ=0.455 (val F1=0.2480)
  Directional -> Accuracy: 0.5273, MCC: 0.2557, F1: 0.2353

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54728 | val 1.00299
  Epoch 016 - train 0.51127 | val 1.01837
  Classification -> best τ=0.515 (val F1=0.2496)
  Directional -> Accuracy: 0.4737, MCC: -0.0313, F1: 0.4444

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50414 | val 2.72884
  Epoch 016 - train 0.42966 | val 2.97811
  Classification -> best τ=0.780 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55037 | val 1.28837
  Epoch 016 - train 0.43533 | val 1.34056
  Classification -> best τ=0.480 (val F1=0.1336)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52204 | val 0.82642
  Epoch 016 - train 0.42687 | val 0.83271
  Classification -> best τ=0.395 (val F1=0.2357)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56134 | val 1.32019
  Epoch 016 - train 0.51481 | val 1.67526
  Classification -> best τ=0.625 (val F1=0.3260)
  Directional -> Accuracy: 0.4507, MCC: 0.1052, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50341 | val 0.90053
  Epoch 016 - train 0.46290 | val 1.07088
  Classification -> best τ=0.630 (val F1=0.2712)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51797 | val 1.31975
  Epoch 016 - train 0.47092 | val 1.74122
  Classification -> best τ=0.205 (val F1=0.3317)
  Directional -> Accuracy: 0.6154, MCC: 0.1923, F1: 0.6988

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45355 | val 0.89043
  Epoch 016 - train 0.39223 | val 1.11064
  Classification -> best τ=0.570 (val F1=0.2268)
  Directional -> Accuracy: 0.5250, MCC: 0.1502, F1: 0.2400

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52532 | val 0.80685
  Epoch 016 - train 0.53205 | val 0.81418
  Classification -> best τ=0.350 (val F1=0.2544)
  Directional -> Accuracy: 0.4909, MCC: 0.0219, F1: 0.5625

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46163 | val 2.14921
  Epoch 016 - train 0.41100 | val 2.56288
  Classification -> best τ=0.560 (val F1=0.3188)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51247 | val 0.89916
  Epoch 017 - train 0.47912 | val 0.99030
  Classification -> best τ=0.640 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51191 | val 1.96106
  Epoch 016 - train 0.47677 | val 2.75137
  Classification -> best τ=0.295 (val F1=0.1642)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55788 | val 0.96676
  Epoch 016 - train 0.47359 | val 1.28552
  Classification -> best τ=0.465 (val F1=0.2887)
  Directional -> Accuracy: 0.5227, MCC: 0.0455, F1: 0.5333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48980 | val 1.12923
  Epoch 016 - train 0.39918 | val 1.27227
  Classification -> best τ=0.535 (val F1=0.0707)
  Directional -> Accuracy: 0.5366, MCC: 0.0701, F1: 0.5778

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49027 | val 1.35978
  Epoch 016 - train 0.38534 | val 1.57788
  Classification -> best τ=0.480 (val F1=0.2392)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60527 | val 1.35737
  Epoch 016 - train 0.57786 | val 1.28653
  Classification -> best τ=0.475 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52533 | val 1.39648
  Epoch 016 - train 0.48335 | val 1.70913
  Classification -> best τ=0.680 (val F1=0.3347)
  Directional -> Accuracy: 0.5455, MCC: 0.1273, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62806 | val 0.79492
  Epoch 017 - train 0.48675 | val 0.73818
  Classification -> best τ=0.590 (val F1=0.3022)
  Directional -> Accuracy: 0.4615, MCC: -0.0772, F1: 0.4400

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55280 | val 1.71369
  Epoch 017 - train 0.46525 | val 2.45009
  Classification -> best τ=0.545 (val F1=0.2444)
  Directional -> Accuracy: 0.5926, MCC: 0.2935, F1: 0.7179

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59158 | val 0.83501
  Epoch 020 - train 0.44056 | val 1.02245

[I 2026-02-20 00:33:07,749] Trial 53 finished with value: 0.24833974735115763 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.004154303600829289, 'weight_decay': 3.57651216045329e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.3714956074114748, 'early_stopping_min_delta': 0.0071538579847394415}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 021 - train 0.45568 | val 1.02484
  Classification -> best τ=0.450 (val F1=0.3100)
  Directional -> Accuracy: 0.4237, MCC: -0.1632, F1: 0.5641

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24833974735115763
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57824 | val 0.87059
  Epoch 016 - train 0.50903 | val 0.80282
  Classification -> best τ=0.670 (val F1=0.2895)
  Directional -> Accuracy: 0.5676, MCC: 0.0834, F1: 0.1579

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50821 | val 1.14238
  Epoch 017 - train 0.45069 | val 1.73794
  Classification -> best τ=0.380 (val F1=0.1612)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56009 | val 1.20590
  Epoch 016 - train 0.48359 | val 1.89782
  Classification -> best τ=0.545 (val F1=0.3575)
  Directional -> Accuracy: 0.5909, MCC: 0.2199, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63836 | val 1.71194
  Epoch 017 - train 0.58515 | val 2.67589
  Classification -> best τ=0.430 (val F1=0.2431)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47222 | val 0.89043
  Epoch 017 - train 0.32694 | val 1.11440
  Classification -> best τ=0.540 (val F1=0.4665)
  Directional -> Accuracy: 0.6250, MCC: 0.3539, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43544 | val 1.58230
  Epoch 016 - train 0.33316 | val 2.48168
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55998 | val 0.95578
  Epoch 016 - train 0.45869 | val 1.28857
  Classification -> best τ=0.355 (val F1=0.1818)
  Directional -> Accuracy: 0.4394, MCC: 0.0822, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51616 | val 0.84098
  Epoch 016 - train 0.40388 | val 1.30680
  Classification -> best τ=0.470 (val F1=0.1925)
  Directional -> Accuracy: 0.6154, MCC: 0.1937, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53814 | val 0.94703
  Epoch 018 - train 0.41065 | val 2.00527
  Classification -> best τ=0.555 (val F1=0.3660)
  Directional -> Accuracy: 0.6739, MCC: 0.3982, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53697 | val 0.76087
  Epoch 020 - train 0.42223 | val 0.67269
  Epoch 030 - train 0.29442 | val 0.73138
  Classification -> best τ=0.490 (val F1=0.3804)
  Directional -> Accuracy: 0.4478, MCC: 0.0320, F1: 0.5747

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58329 | val 1.72394
  Epoch 017 - train 0.46252 | val 1.87919
  Classification -> best τ=0.675 (val F1=0.4598)
  Directional -> Accuracy: 0.6170, MCC: 0.2905, F1: 0.2500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55656 | val 1.30328
  Epoch 016 - train 0.46489 | val 1.64747
  Classification -> best τ=0.390 (val F1=0.1386)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47182 | val 1.25346
  Epoch 017 - train 0.41469 | val 0.81888
  Classification -> best τ=0.355 (val F1=0.2919)
  Directional -> Accuracy: 0.4792, MCC: -0.0087, F1: 0.6377

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60677 | val 1.41755
  Epoch 016 - train 0.51121 | val 2.18545
  Classification -> best τ=0.455 (val F1=0.2693)
  Directional -> Accuracy: 0.5172, MCC: 0.0311, F1: 0.5484

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52139 | val 0.78449
  Epoch 016 - train 0.46508 | val 0.99093
  Classification -> best τ=0.450 (val F1=0.3451)
  Directional -> Accuracy: 0.5510, MCC: 0.0782, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54667 | val 0.93363
  Epoch 016 - train 0.43195 | val 1.10407
  Classification -> best τ=0.625 (val F1=0.1584)
  Directional -> Accuracy: 0.4627, MCC: -0.0189, F1: 0.1000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59445 | val 2.19796
  Epoch 016 - train 0.49349 | val 3.69929
  Classification -> best τ=0.445 (val F1=0.0033)
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59491 | val 1.08850
  Epoch 017 - train 0.52430 | val 1.67310
  Classification -> best τ=0.620 (val F1=0.2127)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55630 | val 1.71531
  Epoch 016 - train 0.47425 | val 2.08931
  Classification -> best τ=0.560 (val F1=0.2345)
  Directional -> Accuracy: 0.4516, MCC: 0.0901, F1: 0.1500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58040 | val 0.85370
  Epoch 020 - train 0.33534 | val 1.37512
  Epoch 021 - train 0.34320 | val 1.37843
  Classification -> best τ=0.610 (val F1=0.2750)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55865 | val 0.91242
  Epoch 020 - train 0.36264 | val 1.09534
  Classification -> best τ=0.425 (val F1=0.4125)
  Directional -> Accuracy: 0.4444, MCC: 0.0956, F1: 0.1935

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58776 | val 1.56420
  Epoch 016 - train 0.51320 | val 2.24357
  Classification -> best τ=0.670 (val F1=0.1904)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54588 | val 0.76147
  Epoch 017 - train 0.42024 | val 0.98916
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57042 | val 0.72095
  Epoch 020 - train 0.46546 | val 0.84280
  Epoch 024 - train 0.45356 | val 0.81216
  Classification -> best τ=0.460 (val F1=0.1217)
  Directional -> Accuracy: 0.5397, MCC: 0.1040, F1: 0.6027

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52384 | val 1.33311
  Epoch 016 - train 0.39371 | val 1.76780
  Classification -> best τ=0.565 (val F1=0.4040)
  Directional -> Accuracy: 0.4717, MCC: 0.0076, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51876 | val 1.87567
  Epoch 016 - train 0.39931 | val 2.53093
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54773 | val 1.77546
  Epoch 016 - train 0.46912 | val 1.28034
  Classification -> best τ=0.570 (val F1=0.0903)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56625 | val 0.99916
  Epoch 016 - train 0.42095 | val 1.34946
  Classification -> best τ=0.450 (val F1=0.2128)
  Directional -> Accuracy: 0.4815, MCC: 0.1275, F1: 0.0667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46734 | val 2.62891
  Epoch 016 - train 0.40024 | val 3.50555
  Classification -> best τ=0.690 (val F1=0.4152)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2308

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53665 | val 1.20215
  Epoch 019 - train 0.35097 | val 2.16220
  Classification -> best τ=0.775 (val F1=0.2736)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47617 | val 0.84796
  Epoch 017 - train 0.35900 | val 1.17050
  Classification -> best τ=0.545 (val F1=0.2928)
  Directional -> Accuracy: 0.4255, MCC: -0.2144, F1: 0.0690

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55008 | val 0.80462
  Epoch 016 - train 0.49523 | val 1.04698
  Classification -> best τ=0.570 (val F1=0.2533)
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49523 | val 0.80150
  Epoch 020 - train 0.37621 | val 0.94420
  Epoch 023 - train 0.35364 | val 0.98727
  Classification -> best τ=0.460 (val F1=0.3237)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49040 | val 1.12085
  Epoch 016 - train 0.43072 | val 1.31978
  Classification -> best τ=0.340 (val F1=0.3587)
  Directional -> Accuracy: 0.5781, MCC: 0.1163, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36012 | val 2.64085
  Epoch 016 - train 0.35581 | val 2.75830
  Classification -> best τ=0.645 (val F1=0.2875)
  Directional -> Accuracy: 0.5918, MCC: 0.1936, F1: 0.4737

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53525 | val 1.36087
  Epoch 016 - train 0.41738 | val 2.02871
  Classification -> best τ=0.455 (val F1=0.2225)
  Directional -> Accuracy: 0.4815, MCC: 0.0016, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40843 | val 1.79011
  Epoch 016 - train 0.30824 | val 1.66449
  Classification -> best τ=0.520 (val F1=0.1922)
  Directional -> Accuracy: 0.5000, MCC: -0.0106, F1: 0.5600

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48908 | val 1.84998
  Epoch 016 - train 0.37755 | val 1.58866
  Classification -> best τ=0.395 (val F1=0.4973)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52843 | val 2.75259
  Epoch 016 - train 0.44986 | val 3.38994
  Classification -> best τ=0.060 (val F1=0.2040)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47536 | val 0.73001
  Epoch 020 - train 0.28215 | val 0.80984
  Epoch 028 - train 0.21806 | val 0.97606
  Classification -> best τ=0.310 (val F1=0.2055)
  Directional -> Accuracy: 0.4651, MCC: -0.0660, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46631 | val 0.91793
  Epoch 019 - train 0.25159 | val 1.22150
  Classification -> best τ=0.440 (val F1=0.4063)
  Directional -> Accuracy: 0.5897, MCC: 0.1071, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43114 | val 1.34422
  Epoch 016 - train 0.30657 | val 1.47052
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61403 | val 1.51082
  Epoch 016 - train 0.52078 | val 1.78091
  Classification -> best τ=0.490 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50602 | val 2.22435
  Epoch 016 - train 0.38554 | val 2.61746
  Classification -> best τ=0.720 (val F1=0.3727)
  Directional -> Accuracy: 0.5370, MCC: 0.0741, F1: 0.5283

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54625 | val 1.40034
  Epoch 016 - train 0.48864 | val 2.25498
  Classification -> best τ=0.475 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1387, F1: 0.5769

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53703 | val 3.95693
  Epoch 016 - train 0.46623 | val 5.45366
  Classification -> best τ=0.485 (val F1=0.1243)
  Directional -> Accuracy: 0.5283, MCC: 0.0588, F1: 0.6479

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60617 | val 0.69192

[I 2026-02-20 00:37:13,209] Trial 54 finished with value: 0.24826585372939938 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.00675993684066461, 'weight_decay': 5.599513672331164e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.4843086776233736, 'early_stopping_min_delta': 0.0054592939979189025}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 018 - train 0.44634 | val 0.91151
  Classification -> best τ=0.355 (val F1=0.3062)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24826585372939938
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56643 | val 0.95592
  Epoch 020 - train 0.55005 | val 0.89221
  Classification -> best τ=0.560 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: -0.0841, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56266 | val 0.85439
  Epoch 016 - train 0.49483 | val 1.40469
  Classification -> best τ=0.540 (val F1=0.0492)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59803 | val 0.88575
  Epoch 016 - train 0.54119 | val 0.91818
  Classification -> best τ=0.475 (val F1=0.3251)
  Directional -> Accuracy: 0.3913, MCC: -0.2423, F1: 0.4815

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61890 | val 1.59233
  Epoch 016 - train 0.57628 | val 1.78826
  Classification -> best τ=0.310 (val F1=0.0116)
  Directional -> Accuracy: 0.5135, MCC: 0.0537, F1: 0.4545

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51729 | val 0.79369
  Epoch 017 - train 0.42597 | val 1.29807
  Classification -> best τ=0.645 (val F1=0.4048)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50452 | val 1.12988
  Epoch 016 - train 0.45407 | val 1.06439
  Classification -> best τ=0.530 (val F1=0.2204)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60143 | val 1.22075
  Epoch 016 - train 0.51730 | val 1.67425
  Classification -> best τ=0.430 (val F1=0.2437)
  Directional -> Accuracy: 0.5000, MCC: 0.0871, F1: 0.5405

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50578 | val 2.24559
  Epoch 016 - train 0.50042 | val 2.36379
  Classification -> best τ=0.570 (val F1=0.1795)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55138 | val 1.22713
  Epoch 016 - train 0.48848 | val 1.26828
  Classification -> best τ=0.585 (val F1=0.2443)
  Directional -> Accuracy: 0.6042, MCC: 0.2002, F1: 0.5581

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54015 | val 0.97673
  Epoch 016 - train 0.50135 | val 0.96598
  Classification -> best τ=0.265 (val F1=0.2465)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62245 | val 0.67337
  Epoch 020 - train 0.47784 | val 0.67354
  Epoch 024 - train 0.45954 | val 0.67297
  Classification -> best τ=0.365 (val F1=0.4196)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57391 | val 1.34412
  Epoch 016 - train 0.50614 | val 1.75741
  Classification -> best τ=0.475 (val F1=0.0784)
  Directional -> Accuracy: 0.6667, MCC: 0.3691, F1: 0.7324

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50570 | val 1.46610
  Epoch 016 - train 0.46536 | val 2.29641
  Classification -> best τ=0.335 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60437 | val 0.81390
  Epoch 017 - train 0.56261 | val 0.91573
  Classification -> best τ=0.405 (val F1=0.3320)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58337 | val 1.02030
  Epoch 020 - train 0.45053 | val 0.93248
  Classification -> best τ=0.705 (val F1=0.3498)
  Directional -> Accuracy: 0.4902, MCC: 0.1178, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52938 | val 0.99305
  Epoch 016 - train 0.49598 | val 1.04642
  Classification -> best τ=0.510 (val F1=0.1741)
  Directional -> Accuracy: 0.4783, MCC: -0.0892, F1: 0.5909

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57540 | val 2.53970
  Epoch 016 - train 0.54904 | val 3.08334
  Classification -> best τ=0.695 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55630 | val 1.28923
  Epoch 016 - train 0.54667 | val 1.68679
  Classification -> best τ=0.320 (val F1=0.2253)
  Directional -> Accuracy: 0.4800, MCC: -0.0219, F1: 0.5063

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55379 | val 1.01211
  Epoch 016 - train 0.48700 | val 1.44843
  Classification -> best τ=0.580 (val F1=0.1398)
  Directional -> Accuracy: 0.4844, MCC: 0.1662, F1: 0.2326

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55226 | val 0.94410
  Epoch 016 - train 0.46792 | val 1.13389
  Classification -> best τ=0.610 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58085 | val 0.94594
  Epoch 016 - train 0.51495 | val 1.15493
  Classification -> best τ=0.485 (val F1=0.1723)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61193 | val 0.90391
  Epoch 016 - train 0.55760 | val 0.85394
  Classification -> best τ=0.480 (val F1=0.1650)
  Directional -> Accuracy: 0.4923, MCC: -0.0239, F1: 0.5823

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56217 | val 0.97735
  Epoch 016 - train 0.51216 | val 1.30322
  Classification -> best τ=0.625 (val F1=0.2822)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56632 | val 1.10384
  Epoch 016 - train 0.50954 | val 1.05403
  Classification -> best τ=0.485 (val F1=0.1565)
  Directional -> Accuracy: 0.5538, MCC: 0.1327, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53215 | val 1.61499
  Epoch 016 - train 0.44544 | val 1.75610
  Classification -> best τ=0.525 (val F1=0.4994)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50063 | val 1.80148
  Epoch 016 - train 0.40226 | val 2.03601
  Classification -> best τ=0.605 (val F1=0.4019)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60737 | val 0.83348
  Epoch 016 - train 0.58077 | val 0.80610
  Classification -> best τ=0.485 (val F1=0.0700)
  Directional -> Accuracy: 0.5952, MCC: 0.1578, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50727 | val 1.68920
  Epoch 016 - train 0.49842 | val 1.78137
  Classification -> best τ=0.390 (val F1=0.2665)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53173 | val 1.09031
  Epoch 016 - train 0.48960 | val 1.52152
  Classification -> best τ=0.475 (val F1=0.0989)
  Directional -> Accuracy: 0.6750, MCC: 0.3373, F1: 0.7234

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54916 | val 0.68856
  Epoch 020 - train 0.46060 | val 0.69535
  Epoch 023 - train 0.44501 | val 0.70553
  Classification -> best τ=0.695 (val F1=0.5210)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57497 | val 1.14933
  Epoch 016 - train 0.54195 | val 1.41850
  Classification -> best τ=0.495 (val F1=0.2238)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51850 | val 0.90926
  Epoch 016 - train 0.44986 | val 1.19468
  Classification -> best τ=0.535 (val F1=0.2611)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59767 | val 0.96816
  Epoch 017 - train 0.52138 | val 1.45753
  Classification -> best τ=0.285 (val F1=0.3450)
  Directional -> Accuracy: 0.5139, MCC: 0.0733, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52551 | val 1.17026
  Epoch 016 - train 0.51807 | val 1.25716
  Classification -> best τ=0.605 (val F1=0.1377)
  Directional -> Accuracy: 0.6047, MCC: 0.2219, F1: 0.4848

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54115 | val 1.26228
  Epoch 016 - train 0.49891 | val 1.45625
  Classification -> best τ=0.335 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0485, F1: 0.7143

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49873 | val 1.03250
  Epoch 016 - train 0.44813 | val 1.01475
  Classification -> best τ=0.500 (val F1=0.1857)
  Directional -> Accuracy: 0.5714, MCC: 0.1455, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55381 | val 1.00776
  Epoch 016 - train 0.52105 | val 1.37897
  Classification -> best τ=0.475 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: -0.0051, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46654 | val 1.21124
  Epoch 016 - train 0.39157 | val 1.39484
  Classification -> best τ=0.490 (val F1=0.4012)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51837 | val 0.90198
  Epoch 018 - train 0.49273 | val 0.91176
  Classification -> best τ=0.415 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55699 | val 1.37754
  Epoch 016 - train 0.48333 | val 1.47640
  Classification -> best τ=0.275 (val F1=0.3052)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55657 | val 0.76587
  Epoch 017 - train 0.53872 | val 1.10594
  Classification -> best τ=0.510 (val F1=0.3500)
  Directional -> Accuracy: 0.5111, MCC: 0.0087, F1: 0.6452

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54364 | val 1.28595
  Epoch 016 - train 0.45170 | val 1.46550
  Classification -> best τ=0.650 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53382 | val 0.52976
  Epoch 020 - train 0.31925 | val 1.21241
  Epoch 025 - train 0.31727 | val 1.45151
  Classification -> best τ=0.860 (val F1=0.6058)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63705 | val 0.83420
  Epoch 019 - train 0.53824 | val 1.24032
  Classification -> best τ=0.535 (val F1=0.2036)
  Directional -> Accuracy: 0.4182, MCC: -0.1412, F1: 0.1579

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53213 | val 1.78641
  Epoch 016 - train 0.47397 | val 2.10730
  Classification -> best τ=0.695 (val F1=0.2696)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5263

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60177 | val 1.07109
  Epoch 016 - train 0.53258 | val 1.16472
  Classification -> best τ=0.390 (val F1=0.3392)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53542 | val 2.79335
  Epoch 016 - train 0.48092 | val 3.49706
  Classification -> best τ=0.730 (val F1=0.1399)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53279 | val 0.72997
  Epoch 020 - train 0.47216 | val 0.92843

[I 2026-02-20 00:41:05,562] Trial 55 finished with value: 0.26457623775315725 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0028244493258780855, 'weight_decay': 1.895213549471013e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.6296605908681128, 'early_stopping_min_delta': 0.005751650595023354}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 023 - train 0.45290 | val 0.88644
  Classification -> best τ=0.665 (val F1=0.2623)
  Directional -> Accuracy: 0.5333, MCC: 0.0578, F1: 0.3636

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26457623775315725
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62092 | val 0.72796
  Epoch 016 - train 0.56377 | val 0.75361
  Classification -> best τ=0.475 (val F1=0.1739)
  Directional -> Accuracy: 0.5395, MCC: 0.1654, F1: 0.6237

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54978 | val 1.56492
  Epoch 016 - train 0.50013 | val 1.90444
  Classification -> best τ=0.455 (val F1=0.0900)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61901 | val 1.04682
  Epoch 020 - train 0.48264 | val 1.18799
  Classification -> best τ=0.485 (val F1=0.5292)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62444 | val 1.30565
  Epoch 016 - train 0.56536 | val 1.65922
  Classification -> best τ=0.425 (val F1=0.1005)
  Directional -> Accuracy: 0.5541, MCC: 0.1504, F1: 0.4762

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51735 | val 1.47783
  Epoch 017 - train 0.44615 | val 1.73868
  Classification -> best τ=0.585 (val F1=0.3932)
  Directional -> Accuracy: 0.4600, MCC: -0.0738, F1: 0.1818

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52630 | val 1.03405
  Epoch 016 - train 0.48059 | val 1.34079
  Classification -> best τ=0.485 (val F1=0.0194)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60449 | val 1.19116
  Epoch 016 - train 0.55145 | val 1.10915
  Classification -> best τ=0.490 (val F1=0.2481)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53782 | val 2.28695
  Epoch 016 - train 0.50547 | val 3.86172
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52042 | val 1.22018
  Epoch 016 - train 0.45766 | val 1.45668
  Classification -> best τ=0.495 (val F1=0.2443)
  Directional -> Accuracy: 0.5208, MCC: 0.1422, F1: 0.6102

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55843 | val 0.96407
  Epoch 016 - train 0.51561 | val 1.09304
  Classification -> best τ=0.455 (val F1=0.2144)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63197 | val 0.65476
  Epoch 020 - train 0.46117 | val 1.22354
  Epoch 025 - train 0.46497 | val 1.32780
  Classification -> best τ=0.255 (val F1=0.3436)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56978 | val 0.92840
  Epoch 016 - train 0.51471 | val 1.28030
  Classification -> best τ=0.480 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51975 | val 2.25114
  Epoch 016 - train 0.47475 | val 2.79951
  Classification -> best τ=0.445 (val F1=0.1733)
  Directional -> Accuracy: 0.4762, MCC: 0.0214, F1: 0.5926

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63241 | val 0.77365
  Epoch 018 - train 0.53851 | val 1.11650
  Classification -> best τ=0.360 (val F1=0.3320)
  Directional -> Accuracy: 0.5667, MCC: 0.1961, F1: 0.6829

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53833 | val 1.15483
  Epoch 020 - train 0.47779 | val 0.81095
  Epoch 027 - train 0.42942 | val 0.74923
  Classification -> best τ=0.710 (val F1=0.3498)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58274 | val 0.78723
  Epoch 018 - train 0.51370 | val 0.80479
  Classification -> best τ=0.560 (val F1=0.2430)
  Directional -> Accuracy: 0.5362, MCC: 0.1027, F1: 0.4667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60715 | val 1.90721
  Epoch 016 - train 0.55602 | val 2.43462
  Classification -> best τ=0.505 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60753 | val 1.42798
  Epoch 016 - train 0.55425 | val 1.03262
  Classification -> best τ=0.510 (val F1=0.1429)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58040 | val 0.79199
  Epoch 016 - train 0.51950 | val 0.94862
  Classification -> best τ=0.540 (val F1=0.1809)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54885 | val 0.99573
  Epoch 016 - train 0.50669 | val 1.13694
  Classification -> best τ=0.525 (val F1=0.2329)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56042 | val 0.73169
  Epoch 016 - train 0.49725 | val 0.72522
  Classification -> best τ=0.495 (val F1=0.1569)
  Directional -> Accuracy: 0.5532, MCC: 0.1469, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62969 | val 1.08740
  Epoch 016 - train 0.60798 | val 1.22015
  Classification -> best τ=0.545 (val F1=0.0905)
  Directional -> Accuracy: 0.4462, MCC: -0.1543, F1: 0.1000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61931 | val 0.72495
  Epoch 016 - train 0.54935 | val 0.84281
  Classification -> best τ=0.545 (val F1=0.1576)
  Directional -> Accuracy: 0.5088, MCC: 0.1880, F1: 0.2632

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57614 | val 1.44743
  Epoch 016 - train 0.53819 | val 2.13152
  Classification -> best τ=0.510 (val F1=0.1727)
  Directional -> Accuracy: 0.4923, MCC: 0.0202, F1: 0.6118

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53357 | val 1.38795
  Epoch 018 - train 0.45131 | val 1.97335
  Classification -> best τ=0.630 (val F1=0.4260)
  Directional -> Accuracy: 0.5091, MCC: 0.1077, F1: 0.3077

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51099 | val 1.82597
  Epoch 016 - train 0.46876 | val 1.66010
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62354 | val 0.71129
  Epoch 016 - train 0.57204 | val 0.72867
  Classification -> best τ=0.500 (val F1=0.0786)
  Directional -> Accuracy: 0.5952, MCC: 0.2240, F1: 0.5854

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56559 | val 0.99376
  Epoch 016 - train 0.50294 | val 1.32524
  Classification -> best τ=0.455 (val F1=0.2435)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56119 | val 0.95084
  Epoch 017 - train 0.47557 | val 1.19683
  Classification -> best τ=0.475 (val F1=0.2618)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55668 | val 0.68092
  Epoch 020 - train 0.45577 | val 0.59801
  Epoch 028 - train 0.39005 | val 0.63280
  Classification -> best τ=0.560 (val F1=0.5965)
  Directional -> Accuracy: 0.4524, MCC: -0.0912, F1: 0.4651

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57977 | val 1.19316
  Epoch 016 - train 0.53321 | val 1.44697
  Classification -> best τ=0.520 (val F1=0.0715)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51992 | val 0.96660
  Epoch 018 - train 0.42330 | val 1.24477
  Classification -> best τ=0.520 (val F1=0.3302)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62438 | val 0.91837
  Epoch 019 - train 0.52686 | val 0.90180
  Classification -> best τ=0.520 (val F1=0.3427)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55244 | val 1.57765
  Epoch 016 - train 0.54253 | val 1.81138
  Classification -> best τ=0.495 (val F1=0.3227)
  Directional -> Accuracy: 0.6512, MCC: 0.3067, F1: 0.5946

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54624 | val 0.92469
  Epoch 016 - train 0.49472 | val 0.93853
  Classification -> best τ=0.435 (val F1=0.3068)
  Directional -> Accuracy: 0.6061, MCC: 0.1678, F1: 0.6905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51873 | val 0.92150
  Epoch 018 - train 0.41764 | val 0.95058
  Classification -> best τ=0.485 (val F1=0.2464)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54285 | val 0.81126
  Epoch 016 - train 0.48944 | val 1.10502
  Classification -> best τ=0.460 (val F1=0.2287)
  Directional -> Accuracy: 0.5000, MCC: -0.0157, F1: 0.4167

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47308 | val 1.71377
  Epoch 016 - train 0.38893 | val 1.21142
  Classification -> best τ=0.470 (val F1=0.3105)
  Directional -> Accuracy: 0.5652, MCC: 0.0691, F1: 0.6552

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54594 | val 0.65060
  Epoch 020 - train 0.45692 | val 0.76960
  Epoch 022 - train 0.41610 | val 0.80445
  Classification -> best τ=0.655 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54007 | val 1.20527
  Epoch 016 - train 0.48496 | val 1.13261
  Classification -> best τ=0.475 (val F1=0.2218)
  Directional -> Accuracy: 0.4595, MCC: -0.1712, F1: 0.6296

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58568 | val 1.10016
  Epoch 016 - train 0.53512 | val 1.25043
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52916 | val 1.04928
  Epoch 016 - train 0.45622 | val 1.23417
  Classification -> best τ=0.525 (val F1=0.3015)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50850 | val 1.14801
  Epoch 020 - train 0.39956 | val 0.60430
  Epoch 026 - train 0.34814 | val 0.80513
  Classification -> best τ=0.655 (val F1=0.5689)
  Directional -> Accuracy: 0.5417, MCC: 0.3464, F1: 0.6207

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62594 | val 1.16299
  Epoch 016 - train 0.59726 | val 1.43801
  Classification -> best τ=0.500 (val F1=0.2132)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52875 | val 2.08680
  Epoch 016 - train 0.49286 | val 2.25894
  Classification -> best τ=0.550 (val F1=0.3401)
  Directional -> Accuracy: 0.5536, MCC: 0.2187, F1: 0.6753

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60596 | val 0.95885
  Epoch 016 - train 0.54880 | val 0.69386
  Classification -> best τ=0.500 (val F1=0.2064)
  Directional -> Accuracy: 0.5660, MCC: 0.1593, F1: 0.6761

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53173 | val 1.80553
  Epoch 016 - train 0.48908 | val 2.36150
  Classification -> best τ=0.590 (val F1=0.0716)
  Directional -> Accuracy: 0.5455, MCC: 0.0728, F1: 0.6575

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54552 | val 0.71978

[I 2026-02-20 00:43:15,927] Trial 56 finished with value: 0.2330548026887439 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.002446226559558681, 'weight_decay': 6.7385007425546485e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.6102384050680374, 'early_stopping_min_delta': 0.0058696156380255585}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.54133 | val 0.95264
  Classification -> best τ=0.465 (val F1=0.0879)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2330548026887439
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69139 | val 1.09806
  Epoch 016 - train 0.68302 | val 1.09327
  Classification -> best τ=0.585 (val F1=0.0865)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67456 | val 0.70178
  Epoch 016 - train 0.67519 | val 0.70147
  Classification -> best τ=0.515 (val F1=0.0225)
  Directional -> Accuracy: 0.4667, MCC: -0.3022, F1: 0.6364

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67770 | val 0.68419
  Epoch 016 - train 0.69007 | val 0.68352
  Classification -> best τ=0.515 (val F1=0.3135)
  Directional -> Accuracy: 0.5652, MCC: 0.1374, F1: 0.5455

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69037 | val 0.69628
  Epoch 016 - train 0.69571 | val 0.69211
  Classification -> best τ=0.545 (val F1=0.1079)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69889 | val 0.71233
  Epoch 016 - train 0.69897 | val 0.71081
  Classification -> best τ=0.495 (val F1=0.0164)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70565 | val 0.71150
  Epoch 016 - train 0.69736 | val 0.70768
  Classification -> best τ=0.535 (val F1=0.0171)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71035 | val 0.78859
  Epoch 016 - train 0.69825 | val 0.78585
  Classification -> best τ=0.490 (val F1=0.1753)
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70013 | val 0.71178
  Epoch 016 - train 0.70216 | val 0.71359
  Classification -> best τ=0.490 (val F1=0.0668)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70888 | val 0.68862
  Epoch 016 - train 0.71101 | val 0.68624
  Classification -> best τ=0.475 (val F1=0.0769)
  Directional -> Accuracy: 0.3750, MCC: -0.2250, F1: 0.4231

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68865 | val 0.73690
  Epoch 016 - train 0.68946 | val 0.73999
  Classification -> best τ=0.470 (val F1=0.0906)
  Directional -> Accuracy: 0.4638, MCC: 0.0916, F1: 0.5934

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68763 | val 0.74280
  Epoch 016 - train 0.68992 | val 0.74883
  Classification -> best τ=0.510 (val F1=0.2484)
  Directional -> Accuracy: 0.4898, MCC: -0.0184, F1: 0.4681

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68962 | val 0.68245
  Epoch 016 - train 0.70149 | val 0.68079
  Classification -> best τ=0.510 (val F1=0.1949)
  Directional -> Accuracy: 0.3158, MCC: -0.3684, F1: 0.2909

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69066 | val 0.82706
  Epoch 016 - train 0.70324 | val 0.84153
  Classification -> best τ=0.480 (val F1=0.1733)
  Directional -> Accuracy: 0.4286, MCC: -0.1435, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69600 | val 0.66188
  Epoch 020 - train 0.69796 | val 0.65607
  Epoch 030 - train 0.70476 | val 0.65462
  Classification -> best τ=0.390 (val F1=0.1949)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71559 | val 0.70945
  Epoch 016 - train 0.71871 | val 0.71339
  Classification -> best τ=0.540 (val F1=0.2571)
  Directional -> Accuracy: 0.4510, MCC: -0.1087, F1: 0.3913

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69547 | val 0.66862
  Epoch 018 - train 0.70145 | val 0.67218
  Classification -> best τ=0.365 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69330 | val 0.70673
  Epoch 016 - train 0.68885 | val 0.70929
  Classification -> best τ=0.515 (val F1=0.1842)
  Directional -> Accuracy: 0.5517, MCC: 0.2440, F1: 0.5000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71142 | val 0.72078
  Epoch 016 - train 0.71211 | val 0.72047
  Classification -> best τ=0.455 (val F1=0.0818)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68197 | val 0.69756
  Epoch 016 - train 0.67855 | val 0.69909
  Classification -> best τ=0.485 (val F1=0.1517)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69325 | val 0.68078
  Epoch 020 - train 0.66720 | val 0.67496
  Epoch 027 - train 0.66716 | val 0.67430
  Classification -> best τ=0.435 (val F1=0.2572)
  Directional -> Accuracy: 0.5946, MCC: 0.2107, F1: 0.5833

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69745 | val 0.70252
  Epoch 016 - train 0.68636 | val 0.69666
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70573 | val 0.71512
  Epoch 016 - train 0.70805 | val 0.71424
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68558 | val 0.70547
  Epoch 016 - train 0.69411 | val 0.70557
  Classification -> best τ=0.515 (val F1=0.0911)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68048 | val 0.70220
  Epoch 016 - train 0.68687 | val 0.70076
  Classification -> best τ=0.510 (val F1=0.0876)
  Directional -> Accuracy: 0.5231, MCC: 0.0428, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69963 | val 0.68617
  Epoch 020 - train 0.69715 | val 0.68249
  Epoch 030 - train 0.69822 | val 0.67777
  Classification -> best τ=0.560 (val F1=0.4075)
  Directional -> Accuracy: 0.5455, MCC: 0.0930, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72377 | val 0.71780
  Epoch 016 - train 0.69431 | val 0.71897
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68210 | val 0.76001
  Epoch 016 - train 0.67905 | val 0.76208
  Classification -> best τ=0.490 (val F1=0.1964)
  Directional -> Accuracy: 0.4762, MCC: -0.1452, F1: 0.6071

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68738 | val 0.67346
  Epoch 020 - train 0.68861 | val 0.67151
  Epoch 024 - train 0.69161 | val 0.67154
  Classification -> best τ=0.400 (val F1=0.1997)
  Directional -> Accuracy: 0.5714, MCC: 0.1102, F1: 0.6571

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70613 | val 0.76145
  Epoch 016 - train 0.68573 | val 0.76359
  Classification -> best τ=0.490 (val F1=0.2660)
  Directional -> Accuracy: 0.4250, MCC: -0.1816, F1: 0.5106

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69350 | val 0.78429
  Epoch 016 - train 0.69029 | val 0.78928
  Classification -> best τ=0.550 (val F1=0.1382)
  Directional -> Accuracy: 0.5714, MCC: 0.1357, F1: 0.4375

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69675 | val 0.65742
  Epoch 020 - train 0.71202 | val 0.65848
  Epoch 023 - train 0.69867 | val 0.65941
  Classification -> best τ=0.560 (val F1=0.1707)
  Directional -> Accuracy: 0.5238, MCC: -0.0387, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70673 | val 0.72409
  Epoch 016 - train 0.70345 | val 0.72374
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69913 | val 0.74637
  Epoch 016 - train 0.70021 | val 0.74262
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69823 | val 0.70597
  Epoch 016 - train 0.69711 | val 0.70769
  Classification -> best τ=0.510 (val F1=0.1297)
  Directional -> Accuracy: 0.5581, MCC: 0.1198, F1: 0.5778

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71085 | val 0.69930
  Epoch 020 - train 0.70494 | val 0.68705
  Epoch 030 - train 0.69225 | val 0.68172
  Classification -> best τ=0.520 (val F1=0.3091)
  Directional -> Accuracy: 0.5758, MCC: 0.1159, F1: 0.6500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72312 | val 0.70097
  Epoch 016 - train 0.72438 | val 0.69887
  Classification -> best τ=0.540 (val F1=0.2193)
  Directional -> Accuracy: 0.4048, MCC: -0.1907, F1: 0.4186

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70318 | val 0.70014
  Epoch 018 - train 0.70533 | val 0.69643
  Classification -> best τ=0.450 (val F1=0.1986)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70917 | val 0.72569
  Epoch 016 - train 0.71281 | val 0.73866
  Classification -> best τ=0.520 (val F1=0.2832)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71954 | val 0.71149
  Epoch 016 - train 0.71052 | val 0.70909
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69509 | val 0.71901
  Epoch 016 - train 0.69580 | val 0.72059
  Classification -> best τ=0.490 (val F1=0.1599)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67682 | val 0.76484
  Epoch 016 - train 0.66910 | val 0.77081
  Classification -> best τ=0.520 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: 0.0950, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69248 | val 0.71201
  Epoch 016 - train 0.67801 | val 0.71557
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70135 | val 0.75612
  Epoch 016 - train 0.69786 | val 0.75928
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69574 | val 0.73357
  Epoch 016 - train 0.70467 | val 0.73856
  Classification -> best τ=0.435 (val F1=0.3730)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.71226 | val 0.70588
  Epoch 016 - train 0.70939 | val 0.70285
  Classification -> best τ=0.430 (val F1=0.1211)
  Directional -> Accuracy: 0.4643, MCC: -0.1768, F1: 0.0625

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70124 | val 0.68915
  Epoch 016 - train 0.70568 | val 0.68901
  Classification -> best τ=0.545 (val F1=0.0099)
  Directional -> Accuracy: 0.4528, MCC: -0.1004, F1: 0.2564

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68980 | val 0.68879
  Epoch 016 - train 0.69838 | val 0.69355
  Classification -> best τ=0.435 (val F1=0.0955)
  Directional -> Accuracy: 0.4727, MCC: -0.1093, F1: 0.6027

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70200 | val 0.74875

[I 2026-02-20 00:47:20,653] Trial 57 finished with value: 0.13899498445410194 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 5.535340515742645e-06, 'weight_decay': 1.3949409545863371e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.680381436223289, 'early_stopping_min_delta': 0.006796823131085266}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.69458 | val 0.75013
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13899498445410194
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67458 | val 0.65118
  Epoch 020 - train 0.54661 | val 1.09186
  Epoch 021 - train 0.52848 | val 1.12727
  Classification -> best τ=0.505 (val F1=0.3100)
  Directional -> Accuracy: 0.5200, MCC: -0.0544, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58080 | val 0.97468
  Epoch 020 - train 0.42626 | val 0.68523
  Epoch 022 - train 0.41765 | val 0.76639
  Classification -> best τ=0.405 (val F1=0.1902)
  Directional -> Accuracy: 0.5909, MCC: 0.1132, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60495 | val 0.89505
  Epoch 018 - train 0.48960 | val 0.86272
  Classification -> best τ=0.575 (val F1=0.2582)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65403 | val 1.99346
  Epoch 017 - train 0.58780 | val 1.92757
  Classification -> best τ=0.385 (val F1=0.0453)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50934 | val 2.84985
  Epoch 016 - train 0.47678 | val 4.57073
  Classification -> best τ=0.525 (val F1=0.4726)
  Directional -> Accuracy: 0.6122, MCC: 0.3223, F1: 0.4242

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54563 | val 1.06219
  Epoch 019 - train 0.37242 | val 1.51435
  Classification -> best τ=0.570 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63129 | val 1.43314
  Epoch 020 - train 0.46633 | val 2.48044
  Epoch 021 - train 0.43305 | val 2.54547
  Classification -> best τ=0.560 (val F1=0.2127)
  Directional -> Accuracy: 0.5373, MCC: 0.0208, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55641 | val 0.63794
  Epoch 020 - train 0.36985 | val 1.75617
  Epoch 027 - train 0.25236 | val 2.16291
  Classification -> best τ=0.505 (val F1=0.5222)
  Directional -> Accuracy: 0.5610, MCC: 0.1803, F1: 0.6087

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62420 | val 0.96559
  Epoch 020 - train 0.48159 | val 1.29713
  Epoch 021 - train 0.44784 | val 1.41990
  Classification -> best τ=0.385 (val F1=0.3398)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57993 | val 0.80385
  Epoch 017 - train 0.50023 | val 1.06971
  Classification -> best τ=0.445 (val F1=0.1859)
  Directional -> Accuracy: 0.4118, MCC: -0.1417, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60010 | val 1.16654
  Epoch 016 - train 0.50794 | val 0.79025
  Classification -> best τ=0.480 (val F1=0.2604)
  Directional -> Accuracy: 0.5625, MCC: 0.1221, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59484 | val 1.48662
  Epoch 017 - train 0.46064 | val 1.79059
  Classification -> best τ=0.660 (val F1=0.1899)
  Directional -> Accuracy: 0.6786, MCC: 0.3733, F1: 0.7353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50269 | val 2.33630
  Epoch 016 - train 0.42458 | val 3.84674
  Classification -> best τ=0.460 (val F1=0.2112)
  Directional -> Accuracy: 0.5102, MCC: 0.0042, F1: 0.0769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64433 | val 0.86072
  Epoch 019 - train 0.53677 | val 0.89040
  Classification -> best τ=0.320 (val F1=0.3276)
  Directional -> Accuracy: 0.5763, MCC: 0.1533, F1: 0.6269

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52661 | val 1.78948
  Epoch 016 - train 0.50394 | val 1.18466
  Classification -> best τ=0.630 (val F1=0.2550)
  Directional -> Accuracy: 0.5400, MCC: -0.1266, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59107 | val 1.38173
  Epoch 017 - train 0.49434 | val 1.63444
  Classification -> best τ=0.655 (val F1=0.1638)
  Directional -> Accuracy: 0.4853, MCC: 0.0591, F1: 0.1026

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60898 | val 1.03468
  Epoch 016 - train 0.49043 | val 1.48038
  Classification -> best τ=0.680 (val F1=0.1429)
  Directional -> Accuracy: 0.4211, MCC: 0.0091, F1: 0.2326

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64713 | val 0.78257
  Epoch 016 - train 0.55540 | val 1.15262
  Classification -> best τ=0.625 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58498 | val 0.85549
  Epoch 017 - train 0.51916 | val 0.81038
  Classification -> best τ=0.720 (val F1=0.2288)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60811 | val 0.84321
  Epoch 018 - train 0.42013 | val 0.89573
  Classification -> best τ=0.590 (val F1=0.2159)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55978 | val 1.51539
  Epoch 016 - train 0.46730 | val 2.02599
  Classification -> best τ=0.480 (val F1=0.2041)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64587 | val 2.13186
  Epoch 017 - train 0.58435 | val 1.76720
  Classification -> best τ=0.680 (val F1=0.1678)
  Directional -> Accuracy: 0.5469, MCC: 0.1242, F1: 0.6588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64904 | val 1.46567
  Epoch 016 - train 0.52552 | val 2.31550
  Classification -> best τ=0.710 (val F1=0.2961)
  Directional -> Accuracy: 0.5536, MCC: 0.1491, F1: 0.5283

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58903 | val 1.79789
  Epoch 019 - train 0.46904 | val 1.83660
  Classification -> best τ=0.615 (val F1=0.2130)
  Directional -> Accuracy: 0.5156, MCC: 0.0022, F1: 0.3404

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50345 | val 1.40944
  Epoch 016 - train 0.40884 | val 2.19613
  Classification -> best τ=0.350 (val F1=0.4977)
  Directional -> Accuracy: 0.5370, MCC: 0.1390, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53263 | val 0.93173
  Epoch 016 - train 0.36238 | val 1.24720
  Classification -> best τ=0.535 (val F1=0.3313)
  Directional -> Accuracy: 0.6744, MCC: 0.3158, F1: 0.5625

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58061 | val 0.79948
  Epoch 017 - train 0.45912 | val 0.71565
  Classification -> best τ=0.610 (val F1=0.1824)
  Directional -> Accuracy: 0.5714, MCC: 0.1061, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57283 | val 1.56015
  Epoch 016 - train 0.44885 | val 2.16445
  Classification -> best τ=0.380 (val F1=0.1985)
  Directional -> Accuracy: 0.4909, MCC: 0.1773, F1: 0.1250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57955 | val 0.75413
  Epoch 016 - train 0.40260 | val 1.23609
  Classification -> best τ=0.470 (val F1=0.2955)
  Directional -> Accuracy: 0.6053, MCC: 0.2088, F1: 0.7273

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56124 | val 1.41540
  Epoch 016 - train 0.49079 | val 1.45153
  Classification -> best τ=0.775 (val F1=0.2193)
  Directional -> Accuracy: 0.4634, MCC: -0.1280, F1: 0.1538

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59628 | val 1.41563
  Epoch 020 - train 0.42939 | val 2.08052
  Epoch 022 - train 0.39226 | val 2.20031
  Classification -> best τ=0.660 (val F1=0.2807)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56139 | val 1.01775
  Epoch 016 - train 0.40770 | val 1.08302
  Classification -> best τ=0.330 (val F1=0.2357)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65377 | val 0.89958
  Epoch 019 - train 0.50632 | val 1.18085
  Classification -> best τ=0.270 (val F1=0.2961)
  Directional -> Accuracy: 0.5493, MCC: 0.1600, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57343 | val 0.87936
  Epoch 016 - train 0.47592 | val 1.10824
  Classification -> best τ=0.625 (val F1=0.3520)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6818

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59861 | val 0.98999
  Epoch 020 - train 0.40735 | val 1.15245
  Epoch 021 - train 0.44582 | val 1.07970
  Classification -> best τ=0.445 (val F1=0.3580)
  Directional -> Accuracy: 0.6000, MCC: 0.2183, F1: 0.6061

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53614 | val 0.75957
  Epoch 020 - train 0.30699 | val 1.23362
  Classification -> best τ=0.525 (val F1=0.3290)
  Directional -> Accuracy: 0.6500, MCC: 0.3394, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54273 | val 0.78028
  Epoch 017 - train 0.47116 | val 0.92489
  Classification -> best τ=0.430 (val F1=0.2203)
  Directional -> Accuracy: 0.5091, MCC: 0.0671, F1: 0.5846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50238 | val 1.80983
  Epoch 016 - train 0.38470 | val 1.63460
  Classification -> best τ=0.565 (val F1=0.1602)
  Directional -> Accuracy: 0.4889, MCC: 0.0921, F1: 0.4390

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55347 | val 2.12171
  Epoch 020 - train 0.47040 | val 3.12568
  Epoch 022 - train 0.37561 | val 3.43365
  Classification -> best τ=0.385 (val F1=0.4556)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62673 | val 1.21139
  Epoch 018 - train 0.44121 | val 2.52562
  Classification -> best τ=0.650 (val F1=0.2344)
  Directional -> Accuracy: 0.5342, MCC: 0.0673, F1: 0.5000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60599 | val 0.70735
  Epoch 020 - train 0.45275 | val 0.79489
  Epoch 022 - train 0.42578 | val 0.80935
  Classification -> best τ=0.530 (val F1=0.1473)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43094 | val 1.15739
  Epoch 016 - train 0.30983 | val 1.33983
  Classification -> best τ=0.455 (val F1=0.2548)
  Directional -> Accuracy: 0.6341, MCC: 0.2401, F1: 0.6939

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51559 | val 0.89789
  Epoch 016 - train 0.41672 | val 1.43596
  Classification -> best τ=0.640 (val F1=0.5489)
  Directional -> Accuracy: 0.6304, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64139 | val 0.95419
  Epoch 016 - train 0.58923 | val 1.20758
  Classification -> best τ=0.465 (val F1=0.2710)
  Directional -> Accuracy: 0.5741, MCC: 0.3452, F1: 0.3784

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54918 | val 1.85460
  Epoch 016 - train 0.44911 | val 1.98059
  Classification -> best τ=0.260 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61607 | val 1.11780
  Epoch 016 - train 0.51400 | val 1.97610
  Classification -> best τ=0.415 (val F1=0.2430)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57844 | val 2.06428
  Epoch 016 - train 0.48584 | val 3.15764
  Classification -> best τ=0.455 (val F1=0.1139)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61787 | val 0.90267

[I 2026-02-20 00:52:06,087] Trial 58 finished with value: 0.26176959085592105 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.009846298115031555, 'weight_decay': 1.0973898584907369e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.8764021110605218, 'early_stopping_min_delta': 0.003762530691621948}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 018 - train 0.48807 | val 0.69765
  Classification -> best τ=0.410 (val F1=0.2608)
  Directional -> Accuracy: 0.4576, MCC: -0.0876, F1: 0.4286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26176959085592105
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59797 | val 0.77304
  Epoch 016 - train 0.58572 | val 0.83793
  Classification -> best τ=0.640 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59882 | val 1.34057
  Epoch 016 - train 0.56992 | val 1.21891
  Classification -> best τ=0.530 (val F1=0.0492)
  Directional -> Accuracy: 0.5778, MCC: 0.0842, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65481 | val 0.75206
  Epoch 017 - train 0.62085 | val 0.79250
  Classification -> best τ=0.545 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62050 | val 1.14406
  Epoch 016 - train 0.60621 | val 1.06238
  Classification -> best τ=0.315 (val F1=0.0931)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55805 | val 1.20414
  Epoch 016 - train 0.52830 | val 1.27572
  Classification -> best τ=0.615 (val F1=0.3612)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57899 | val 0.86464
  Epoch 016 - train 0.57463 | val 0.91522
  Classification -> best τ=0.525 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61745 | val 1.20012
  Epoch 016 - train 0.60965 | val 1.15492
  Classification -> best τ=0.405 (val F1=0.2540)
  Directional -> Accuracy: 0.5294, MCC: 0.1704, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57563 | val 1.33916
  Epoch 016 - train 0.52627 | val 1.80014
  Classification -> best τ=0.500 (val F1=0.1657)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57978 | val 1.02075
  Epoch 016 - train 0.60555 | val 1.06277
  Classification -> best τ=0.555 (val F1=0.2443)
  Directional -> Accuracy: 0.6458, MCC: 0.2656, F1: 0.5143

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58154 | val 0.80333
  Epoch 016 - train 0.56659 | val 0.84774
  Classification -> best τ=0.455 (val F1=0.2083)
  Directional -> Accuracy: 0.4928, MCC: 0.0310, F1: 0.5205

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58769 | val 0.66242
  Epoch 020 - train 0.55113 | val 0.68197
  Epoch 026 - train 0.52017 | val 0.70648
  Classification -> best τ=0.380 (val F1=0.3744)
  Directional -> Accuracy: 0.6327, MCC: 0.2484, F1: 0.5500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63359 | val 1.33472
  Epoch 016 - train 0.60456 | val 1.47450
  Classification -> best τ=0.525 (val F1=0.0377)
  Directional -> Accuracy: 0.5614, MCC: 0.1669, F1: 0.6835

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55585 | val 1.82864
  Epoch 016 - train 0.54142 | val 2.19161
  Classification -> best τ=0.420 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64197 | val 0.81932
  Epoch 018 - train 0.60183 | val 0.81981
  Classification -> best τ=0.395 (val F1=0.2692)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58447 | val 1.09599
  Epoch 016 - train 0.56268 | val 1.20318
  Classification -> best τ=0.605 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58935 | val 0.91447
  Epoch 016 - train 0.57513 | val 0.93387
  Classification -> best τ=0.415 (val F1=0.2795)
  Directional -> Accuracy: 0.5797, MCC: 0.1885, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61222 | val 2.92812
  Epoch 016 - train 0.59174 | val 3.15886
  Classification -> best τ=0.665 (val F1=0.1342)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62074 | val 1.15806
  Epoch 016 - train 0.57179 | val 1.18651
  Classification -> best τ=0.485 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62260 | val 1.10733
  Epoch 016 - train 0.59728 | val 1.31200
  Classification -> best τ=0.475 (val F1=0.1517)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59955 | val 0.95499
  Epoch 016 - train 0.58343 | val 1.06395
  Classification -> best τ=0.510 (val F1=0.3439)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61707 | val 1.00101
  Epoch 016 - train 0.58044 | val 1.08244
  Classification -> best τ=0.465 (val F1=0.1723)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65272 | val 0.91596
  Epoch 016 - train 0.61279 | val 0.95732
  Classification -> best τ=0.560 (val F1=0.2381)
  Directional -> Accuracy: 0.5538, MCC: 0.1816, F1: 0.2927

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62575 | val 1.23406
  Epoch 016 - train 0.58260 | val 1.36052
  Classification -> best τ=0.530 (val F1=0.2799)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60591 | val 1.27364
  Epoch 016 - train 0.56334 | val 1.34025
  Classification -> best τ=0.460 (val F1=0.1348)
  Directional -> Accuracy: 0.5385, MCC: 0.0777, F1: 0.5312

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57643 | val 1.18821
  Epoch 017 - train 0.54235 | val 1.39550
  Classification -> best τ=0.610 (val F1=0.5345)
  Directional -> Accuracy: 0.5091, MCC: 0.1077, F1: 0.3077

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57016 | val 1.14222
  Epoch 016 - train 0.56248 | val 1.18567
  Classification -> best τ=0.535 (val F1=0.1890)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63459 | val 1.40647
  Epoch 016 - train 0.59904 | val 1.30490
  Classification -> best τ=0.510 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60248 | val 1.15450
  Epoch 016 - train 0.57344 | val 1.37797
  Classification -> best τ=0.365 (val F1=0.1986)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60498 | val 1.00195
  Epoch 016 - train 0.58173 | val 1.30604
  Classification -> best τ=0.520 (val F1=0.0948)
  Directional -> Accuracy: 0.5000, MCC: 0.0205, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62060 | val 0.67532
  Epoch 020 - train 0.50943 | val 0.65614
  Epoch 030 - train 0.44113 | val 0.57252
  Classification -> best τ=0.555 (val F1=0.5251)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63325 | val 0.95752
  Epoch 016 - train 0.61705 | val 1.00967
  Classification -> best τ=0.470 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58688 | val 0.85323
  Epoch 016 - train 0.55486 | val 0.91127
  Classification -> best τ=0.480 (val F1=0.3136)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62685 | val 0.75139
  Epoch 019 - train 0.58812 | val 1.02068
  Classification -> best τ=0.380 (val F1=0.3076)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61586 | val 1.30019
  Epoch 016 - train 0.57563 | val 1.31923
  Classification -> best τ=0.570 (val F1=0.1818)
  Directional -> Accuracy: 0.5349, MCC: 0.0670, F1: 0.3750

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61338 | val 0.75464
  Epoch 016 - train 0.59843 | val 0.79991
  Classification -> best τ=0.440 (val F1=0.3855)
  Directional -> Accuracy: 0.5606, MCC: 0.0466, F1: 0.6742

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55093 | val 0.72382
  Epoch 018 - train 0.56373 | val 0.75953
  Classification -> best τ=0.485 (val F1=0.2439)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57516 | val 0.99495
  Epoch 017 - train 0.54680 | val 1.06400
  Classification -> best τ=0.415 (val F1=0.1995)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55008 | val 1.50594
  Epoch 016 - train 0.53274 | val 1.73867
  Classification -> best τ=0.615 (val F1=0.2815)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58141 | val 0.65889
  Epoch 020 - train 0.54089 | val 0.71783
  Epoch 021 - train 0.57000 | val 0.71843
  Classification -> best τ=0.680 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58836 | val 1.46728
  Epoch 016 - train 0.56613 | val 1.63895
  Classification -> best τ=0.475 (val F1=0.2447)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59988 | val 0.93817
  Epoch 018 - train 0.57963 | val 0.77875
  Classification -> best τ=0.495 (val F1=0.2874)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58231 | val 0.92378
  Epoch 016 - train 0.57250 | val 1.01022
  Classification -> best τ=0.515 (val F1=0.3015)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57032 | val 0.69923
  Epoch 020 - train 0.53741 | val 0.75131
  Epoch 030 - train 0.50702 | val 0.74390
  Classification -> best τ=0.915 (val F1=0.4092)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61238 | val 1.30937
  Epoch 016 - train 0.63215 | val 1.29901
  Classification -> best τ=0.390 (val F1=0.2212)
  Directional -> Accuracy: 0.5455, MCC: 0.0637, F1: 0.6269

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56172 | val 1.85816
  Epoch 016 - train 0.52238 | val 2.13258
  Classification -> best τ=0.560 (val F1=0.4159)
  Directional -> Accuracy: 0.5357, MCC: 0.1173, F1: 0.6389

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62928 | val 0.87261
  Epoch 016 - train 0.60949 | val 0.84929
  Classification -> best τ=0.500 (val F1=0.1942)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57847 | val 3.10288
  Epoch 016 - train 0.54953 | val 3.28623
  Classification -> best τ=0.590 (val F1=0.1399)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61502 | val 1.37870

[I 2026-02-20 00:55:51,074] Trial 59 finished with value: 0.24400114177770593 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0008878435857270349, 'weight_decay': 3.423543735701391e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.5390913866208782, 'early_stopping_min_delta': 0.0048776314209733026}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.59074 | val 1.62522
  Classification -> best τ=0.550 (val F1=0.2006)
  Directional -> Accuracy: 0.5667, MCC: 0.1503, F1: 0.6176

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24400114177770593
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54853 | val 1.07624
  Epoch 017 - train 0.47524 | val 1.22537
  Classification -> best τ=0.590 (val F1=0.2453)
  Directional -> Accuracy: 0.5195, MCC: -0.0544, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50144 | val 1.46006
  Epoch 016 - train 0.41671 | val 1.46587
  Classification -> best τ=0.490 (val F1=0.0635)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56146 | val 0.65481
  Epoch 020 - train 0.39016 | val 1.09417
  Classification -> best τ=0.540 (val F1=0.4382)
  Directional -> Accuracy: 0.5745, MCC: 0.1988, F1: 0.4737

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57887 | val 2.09283
  Epoch 016 - train 0.55194 | val 2.30562
  Classification -> best τ=0.490 (val F1=0.1283)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44379 | val 2.31504
  Epoch 016 - train 0.38763 | val 3.19209
  Classification -> best τ=0.470 (val F1=0.4836)
  Directional -> Accuracy: 0.7451, MCC: 0.5000, F1: 0.7869

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41275 | val 3.35216
  Epoch 016 - train 0.34618 | val 3.66180
  Classification -> best τ=0.520 (val F1=0.1091)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54793 | val 1.01488
  Epoch 016 - train 0.48827 | val 1.14558
  Classification -> best τ=0.490 (val F1=0.2146)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50063 | val 2.98006
  Epoch 016 - train 0.41820 | val 4.01781
  Classification -> best τ=0.480 (val F1=0.1214)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49518 | val 1.23166
  Epoch 016 - train 0.46365 | val 1.29562
  Classification -> best τ=0.525 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48907 | val 0.90400
  Epoch 016 - train 0.41722 | val 1.15609
  Classification -> best τ=0.490 (val F1=0.0429)
  Directional -> Accuracy: 0.6286, MCC: 0.2843, F1: 0.2353

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50346 | val 2.92633
  Epoch 016 - train 0.47933 | val 3.25763
  Classification -> best τ=0.555 (val F1=0.1750)
  Directional -> Accuracy: 0.5800, MCC: 0.1445, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50231 | val 1.95072
  Epoch 016 - train 0.43021 | val 2.42610
  Classification -> best τ=0.455 (val F1=0.1866)
  Directional -> Accuracy: 0.5517, MCC: 0.2335, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48000 | val 4.67075
  Epoch 016 - train 0.42051 | val 6.06676
  Classification -> best τ=0.405 (val F1=0.1669)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55942 | val 0.84051
  Epoch 018 - train 0.46663 | val 0.86325
  Classification -> best τ=0.415 (val F1=0.2718)
  Directional -> Accuracy: 0.5738, MCC: 0.2007, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50887 | val 0.93151
  Epoch 016 - train 0.44158 | val 1.09944
  Classification -> best τ=0.495 (val F1=0.1706)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49504 | val 1.70109
  Epoch 016 - train 0.44329 | val 1.77869
  Classification -> best τ=0.520 (val F1=0.2143)
  Directional -> Accuracy: 0.5714, MCC: 0.1200, F1: 0.6512

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54708 | val 2.63318
  Epoch 016 - train 0.48903 | val 3.28883
  Classification -> best τ=0.480 (val F1=0.0765)
  Directional -> Accuracy: 0.6441, MCC: 0.1429, F1: 0.7692

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56071 | val 0.97929
  Epoch 016 - train 0.50201 | val 1.17892
  Classification -> best τ=0.525 (val F1=0.1923)
  Directional -> Accuracy: 0.3684, MCC: -0.2036, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50372 | val 1.25880
  Epoch 016 - train 0.47401 | val 1.73416
  Classification -> best τ=0.470 (val F1=0.1372)
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50696 | val 1.12801
  Epoch 018 - train 0.39979 | val 1.14630
  Classification -> best τ=0.585 (val F1=0.2940)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48096 | val 1.53116
  Epoch 016 - train 0.43569 | val 1.97986
  Classification -> best τ=0.535 (val F1=0.1399)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51771 | val 1.18402
  Epoch 016 - train 0.48096 | val 1.21749
  Classification -> best τ=0.530 (val F1=0.2140)
  Directional -> Accuracy: 0.5455, MCC: 0.1718, F1: 0.2105

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51737 | val 1.30511
  Epoch 016 - train 0.47661 | val 1.67043
  Classification -> best τ=0.480 (val F1=0.1371)
  Directional -> Accuracy: 0.5517, MCC: 0.0687, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53330 | val 1.86289
  Epoch 016 - train 0.46708 | val 2.08421
  Classification -> best τ=0.530 (val F1=0.2319)
  Directional -> Accuracy: 0.5152, MCC: 0.0304, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52637 | val 0.75087
  Epoch 018 - train 0.41615 | val 0.99658
  Classification -> best τ=0.470 (val F1=0.3404)
  Directional -> Accuracy: 0.4821, MCC: 0.0587, F1: 0.2564

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41999 | val 1.83264
  Epoch 016 - train 0.38914 | val 2.32146
  Classification -> best τ=0.450 (val F1=0.2774)
  Directional -> Accuracy: 0.4565, MCC: -0.1123, F1: 0.3590

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54576 | val 1.16524
  Epoch 016 - train 0.51181 | val 1.10430
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51864 | val 1.17437
  Epoch 016 - train 0.50303 | val 1.35048
  Classification -> best τ=0.490 (val F1=0.2519)
  Directional -> Accuracy: 0.5263, MCC: 0.0169, F1: 0.6087

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51537 | val 0.75004
  Epoch 020 - train 0.40946 | val 0.89407
  Classification -> best τ=0.670 (val F1=0.3548)
  Directional -> Accuracy: 0.4634, MCC: -0.0166, F1: 0.0833

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50462 | val 2.27174
  Epoch 016 - train 0.44812 | val 2.82254
  Classification -> best τ=0.480 (val F1=0.2112)
  Directional -> Accuracy: 0.5349, MCC: 0.0733, F1: 0.2857

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51660 | val 1.20355
  Epoch 016 - train 0.46157 | val 1.54141
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48920 | val 1.49778
  Epoch 016 - train 0.42659 | val 1.64787
  Classification -> best τ=0.465 (val F1=0.2668)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51765 | val 1.39994
  Epoch 018 - train 0.43427 | val 1.55330
  Classification -> best τ=0.285 (val F1=0.3809)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.48324 | val 1.93675
  Epoch 016 - train 0.44248 | val 3.20615
  Classification -> best τ=0.465 (val F1=0.3254)
  Directional -> Accuracy: 0.5789, MCC: 0.2335, F1: 0.6923

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50895 | val 1.11176
  Epoch 016 - train 0.49442 | val 1.18017
  Classification -> best τ=0.485 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52095 | val 0.89914
  Epoch 018 - train 0.41509 | val 0.96472
  Classification -> best τ=0.450 (val F1=0.3495)
  Directional -> Accuracy: 0.4925, MCC: 0.0073, F1: 0.4848

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49283 | val 1.03361
  Epoch 016 - train 0.42340 | val 1.42142
  Classification -> best τ=0.535 (val F1=0.2986)
  Directional -> Accuracy: 0.6744, MCC: 0.3575, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47815 | val 0.78201
  Epoch 016 - train 0.42359 | val 0.93003
  Classification -> best τ=0.440 (val F1=0.1851)
  Directional -> Accuracy: 0.5088, MCC: 0.0799, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44477 | val 1.99519
  Epoch 016 - train 0.37846 | val 1.57391
  Classification -> best τ=0.505 (val F1=0.1978)
  Directional -> Accuracy: 0.4894, MCC: 0.0465, F1: 0.4783

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47491 | val 0.81893
  Epoch 020 - train 0.40192 | val 1.11505
  Classification -> best τ=0.370 (val F1=0.3533)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41916 | val 2.27829
  Epoch 016 - train 0.38902 | val 3.70981
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50278 | val 2.04664
  Epoch 016 - train 0.45285 | val 2.63609
  Classification -> best τ=0.485 (val F1=0.2135)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44351 | val 1.41234
  Epoch 019 - train 0.36173 | val 1.70162
  Classification -> best τ=0.450 (val F1=0.3471)
  Directional -> Accuracy: 0.4894, MCC: -0.0815, F1: 0.6471

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43449 | val 2.00159
  Epoch 016 - train 0.41426 | val 2.38854
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48838 | val 1.42150
  Epoch 016 - train 0.43252 | val 1.89816
  Classification -> best τ=0.475 (val F1=0.0945)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57710 | val 1.23550
  Epoch 018 - train 0.49309 | val 1.48067
  Classification -> best τ=0.540 (val F1=0.1623)
  Directional -> Accuracy: 0.5714, MCC: 0.2067, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47941 | val 1.18060
  Epoch 017 - train 0.41341 | val 1.39559
  Classification -> best τ=0.540 (val F1=0.3535)
  Directional -> Accuracy: 0.4737, MCC: -0.0882, F1: 0.2857

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52740 | val 1.38388
  Epoch 016 - train 0.46363 | val 1.25348
  Classification -> best τ=0.495 (val F1=0.1712)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46434 | val 1.07889
  Epoch 016 - train 0.41724 | val 1.33919
  Classification -> best τ=0.485 (val F1=0.1091)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55301 | val 2.04579

[I 2026-02-20 00:59:05,239] Trial 60 finished with value: 0.21098893625489482 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.001447978927538023, 'weight_decay': 1.7029882531301198e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.074562729480979, 'early_stopping_min_delta': 0.008176785521782179}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.51378 | val 2.22480
  Classification -> best τ=0.525 (val F1=0.2855)
  Directional -> Accuracy: 0.4918, MCC: -0.0940, F1: 0.1143

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21098893625489482
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59162 | val 0.71714
  Epoch 016 - train 0.56357 | val 0.78245
  Classification -> best τ=0.685 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55884 | val 1.43484
  Epoch 016 - train 0.44178 | val 1.49495
  Classification -> best τ=0.300 (val F1=0.2103)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60340 | val 0.70405
  Epoch 017 - train 0.51172 | val 0.79460
  Classification -> best τ=0.550 (val F1=0.3762)
  Directional -> Accuracy: 0.3696, MCC: -0.3213, F1: 0.0645

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59922 | val 0.82351
  Epoch 017 - train 0.55319 | val 0.78838
  Classification -> best τ=0.510 (val F1=0.0537)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49090 | val 1.52447
  Epoch 016 - train 0.40522 | val 2.46928
  Classification -> best τ=0.600 (val F1=0.3933)
  Directional -> Accuracy: 0.5200, MCC: 0.1084, F1: 0.2500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49888 | val 0.78049
  Epoch 016 - train 0.44736 | val 0.73416
  Classification -> best τ=0.530 (val F1=0.3059)
  Directional -> Accuracy: 0.6522, MCC: 0.3015, F1: 0.6190

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60200 | val 1.05819
  Epoch 016 - train 0.55740 | val 1.38827
  Classification -> best τ=0.405 (val F1=0.2383)
  Directional -> Accuracy: 0.4265, MCC: 0.0751, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53998 | val 2.33531
  Epoch 018 - train 0.39552 | val 3.75785
  Classification -> best τ=0.575 (val F1=0.2168)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58818 | val 1.10126
  Epoch 016 - train 0.47889 | val 1.38305
  Classification -> best τ=0.585 (val F1=0.2443)
  Directional -> Accuracy: 0.5625, MCC: 0.1260, F1: 0.5333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52751 | val 1.38271
  Epoch 016 - train 0.46566 | val 1.58315
  Classification -> best τ=0.405 (val F1=0.2620)
  Directional -> Accuracy: 0.4928, MCC: 0.0527, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66368 | val 0.70286
  Epoch 020 - train 0.46370 | val 0.78091
  Epoch 022 - train 0.42742 | val 0.69821
  Classification -> best τ=0.640 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61353 | val 1.60265
  Epoch 016 - train 0.52116 | val 2.79301
  Classification -> best τ=0.505 (val F1=0.1125)
  Directional -> Accuracy: 0.5789, MCC: 0.1571, F1: 0.6129

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50661 | val 2.14578
  Epoch 016 - train 0.43758 | val 2.60218
  Classification -> best τ=0.270 (val F1=0.1632)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62130 | val 0.86916
  Epoch 016 - train 0.56093 | val 0.80875
  Classification -> best τ=0.455 (val F1=0.3833)
  Directional -> Accuracy: 0.6000, MCC: 0.2000, F1: 0.6000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52772 | val 0.75726
  Epoch 017 - train 0.42534 | val 0.94372
  Classification -> best τ=0.585 (val F1=0.2078)
  Directional -> Accuracy: 0.4314, MCC: -0.1167, F1: 0.4727

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60319 | val 0.94393
  Epoch 019 - train 0.45333 | val 1.12290
  Classification -> best τ=0.865 (val F1=0.1709)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56339 | val 2.49715
  Epoch 016 - train 0.57132 | val 2.67691
  Classification -> best τ=0.470 (val F1=0.0046)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57642 | val 1.05397
  Epoch 016 - train 0.54116 | val 1.18526
  Classification -> best τ=0.555 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59078 | val 0.99234
  Epoch 016 - train 0.50176 | val 1.33637
  Classification -> best τ=0.655 (val F1=0.1809)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55441 | val 0.83998
  Epoch 016 - train 0.50994 | val 0.93833
  Classification -> best τ=0.620 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57613 | val 1.01551
  Epoch 016 - train 0.49686 | val 1.30964
  Classification -> best τ=0.515 (val F1=0.1810)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60358 | val 0.86136
  Epoch 016 - train 0.59143 | val 0.91949
  Classification -> best τ=0.485 (val F1=0.1157)
  Directional -> Accuracy: 0.4308, MCC: -0.1383, F1: 0.4308

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61696 | val 1.17060
  Epoch 016 - train 0.54584 | val 1.51535
  Classification -> best τ=0.515 (val F1=0.2147)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57122 | val 1.42022
  Epoch 016 - train 0.52930 | val 1.56991
  Classification -> best τ=0.535 (val F1=0.2484)
  Directional -> Accuracy: 0.5231, MCC: 0.0844, F1: 0.6173

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50909 | val 1.81178
  Epoch 017 - train 0.43778 | val 2.27162
  Classification -> best τ=0.500 (val F1=0.4903)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45777 | val 2.01022
  Epoch 016 - train 0.36848 | val 2.04040
  Classification -> best τ=0.510 (val F1=0.1099)
  Directional -> Accuracy: 0.5333, MCC: 0.3022, F1: 0.6441

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61391 | val 0.74795
  Epoch 016 - train 0.61001 | val 0.77913
  Classification -> best τ=0.490 (val F1=0.0413)
  Directional -> Accuracy: 0.5714, MCC: 0.2041, F1: 0.5263

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56912 | val 1.49900
  Epoch 016 - train 0.50062 | val 1.89084
  Classification -> best τ=0.305 (val F1=0.2315)
  Directional -> Accuracy: 0.5893, MCC: 0.1723, F1: 0.6230

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53691 | val 1.66663
  Epoch 017 - train 0.47551 | val 1.61148
  Classification -> best τ=0.530 (val F1=0.1457)
  Directional -> Accuracy: 0.6000, MCC: 0.1759, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56645 | val 0.84253
  Epoch 018 - train 0.44243 | val 0.69600
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57593 | val 0.95465
  Epoch 016 - train 0.53599 | val 1.16289
  Classification -> best τ=0.480 (val F1=0.1591)
  Directional -> Accuracy: 0.4048, MCC: -0.2460, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53548 | val 1.16554
  Epoch 016 - train 0.46253 | val 1.30815
  Classification -> best τ=0.520 (val F1=0.2716)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58696 | val 0.77540
  Epoch 017 - train 0.52007 | val 1.27145
  Classification -> best τ=0.385 (val F1=0.3076)
  Directional -> Accuracy: 0.5278, MCC: 0.0828, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54731 | val 1.12440
  Epoch 016 - train 0.49827 | val 1.32059
  Classification -> best τ=0.420 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51924 | val 1.02323
  Epoch 016 - train 0.47609 | val 1.14202
  Classification -> best τ=0.415 (val F1=0.3254)
  Directional -> Accuracy: 0.6212, MCC: 0.2034, F1: 0.6988

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49052 | val 1.04352
  Epoch 016 - train 0.41006 | val 1.14143
  Classification -> best τ=0.445 (val F1=0.1715)
  Directional -> Accuracy: 0.5952, MCC: 0.1850, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53957 | val 0.81336
  Epoch 016 - train 0.46058 | val 0.89756
  Classification -> best τ=0.420 (val F1=0.2755)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48093 | val 1.14288
  Epoch 016 - train 0.38318 | val 1.24353
  Classification -> best τ=0.490 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56539 | val 0.77497
  Epoch 020 - train 0.46313 | val 0.79615
  Epoch 021 - train 0.48492 | val 0.84636
  Classification -> best τ=0.360 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57712 | val 1.43361
  Epoch 016 - train 0.50335 | val 1.45327
  Classification -> best τ=0.295 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55640 | val 0.84876
  Epoch 016 - train 0.55483 | val 0.95794
  Classification -> best τ=0.475 (val F1=0.2125)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51558 | val 1.13349
  Epoch 016 - train 0.47511 | val 1.38931
  Classification -> best τ=0.605 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1273, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48937 | val 0.94528
  Epoch 017 - train 0.41422 | val 1.15674
  Classification -> best τ=0.450 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62726 | val 0.83069
  Epoch 016 - train 0.55824 | val 0.83516
  Classification -> best τ=0.485 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47856 | val 1.63577
  Epoch 016 - train 0.47154 | val 1.64597
  Classification -> best τ=0.675 (val F1=0.3104)
  Directional -> Accuracy: 0.5000, MCC: 0.0153, F1: 0.5758

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60518 | val 1.74473
  Epoch 016 - train 0.53357 | val 1.60814
  Classification -> best τ=0.470 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1825, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52971 | val 3.29910
  Epoch 016 - train 0.47793 | val 3.74807
  Classification -> best τ=0.780 (val F1=0.0684)
  Directional -> Accuracy: 0.4545, MCC: -0.0755, F1: 0.1667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61587 | val 0.85014

[I 2026-02-20 01:01:58,938] Trial 61 finished with value: 0.23451015661900598 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.004076766310971124, 'weight_decay': 8.722988878845112e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.2995757066640725, 'early_stopping_min_delta': 0.005778115556163427}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 018 - train 0.50063 | val 0.96038
  Classification -> best τ=0.535 (val F1=0.1116)
  Directional -> Accuracy: 0.6833, MCC: 0.4127, F1: 0.5581

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23451015661900598
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61885 | val 0.73811
  Epoch 016 - train 0.59253 | val 0.72036
  Classification -> best τ=0.570 (val F1=0.2409)
  Directional -> Accuracy: 0.5000, MCC: -0.0862, F1: 0.2083

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58793 | val 1.48293
  Epoch 016 - train 0.53454 | val 1.57752
  Classification -> best τ=0.420 (val F1=0.1323)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61454 | val 0.84051
  Epoch 020 - train 0.56884 | val 0.85432
  Classification -> best τ=0.320 (val F1=0.2800)
  Directional -> Accuracy: 0.4783, MCC: -0.0948, F1: 0.6129

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65486 | val 1.21080
  Epoch 017 - train 0.60391 | val 1.06735
  Classification -> best τ=0.370 (val F1=0.1895)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53679 | val 0.76542
  Epoch 016 - train 0.45248 | val 1.00797
  Classification -> best τ=0.610 (val F1=0.3612)
  Directional -> Accuracy: 0.4800, MCC: -0.0118, F1: 0.1333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52880 | val 0.89883
  Epoch 016 - train 0.48735 | val 0.82743
  Classification -> best τ=0.540 (val F1=0.1122)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65612 | val 1.15135
  Epoch 016 - train 0.62953 | val 1.06576
  Classification -> best τ=0.420 (val F1=0.2352)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60786 | val 1.45030
  Epoch 016 - train 0.53933 | val 2.40214
  Classification -> best τ=0.545 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62524 | val 1.19635
  Epoch 016 - train 0.60871 | val 1.28711
  Classification -> best τ=0.575 (val F1=0.3962)
  Directional -> Accuracy: 0.6458, MCC: 0.3016, F1: 0.3704

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59245 | val 0.75398
  Epoch 016 - train 0.53717 | val 1.02734
  Classification -> best τ=0.325 (val F1=0.2144)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63831 | val 0.80759
  Epoch 019 - train 0.56279 | val 0.74784
  Classification -> best τ=0.690 (val F1=0.4059)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63861 | val 1.24374
  Epoch 016 - train 0.59451 | val 1.56607
  Classification -> best τ=0.475 (val F1=0.1707)
  Directional -> Accuracy: 0.5263, MCC: 0.0675, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55472 | val 1.22455
  Epoch 016 - train 0.53836 | val 1.24216
  Classification -> best τ=0.340 (val F1=0.2172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67570 | val 0.71101
  Epoch 017 - train 0.59138 | val 0.75119
  Classification -> best τ=0.285 (val F1=0.3282)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56750 | val 0.70679
  Epoch 020 - train 0.51111 | val 0.80693
  Epoch 030 - train 0.46824 | val 0.96451
  Classification -> best τ=0.700 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59005 | val 0.95420
  Epoch 016 - train 0.54361 | val 0.96225
  Classification -> best τ=0.445 (val F1=0.2155)
  Directional -> Accuracy: 0.6087, MCC: 0.3006, F1: 0.7327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61863 | val 1.99280
  Epoch 016 - train 0.60149 | val 2.37949
  Classification -> best τ=0.755 (val F1=0.0732)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62050 | val 0.91940
  Epoch 020 - train 0.55259 | val 1.16445
  Classification -> best τ=0.715 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60953 | val 0.83766
  Epoch 016 - train 0.57600 | val 0.96282
  Classification -> best τ=0.625 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58007 | val 0.90902
  Epoch 016 - train 0.57720 | val 0.80700
  Classification -> best τ=0.510 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62229 | val 0.87108
  Epoch 016 - train 0.58591 | val 1.03123
  Classification -> best τ=0.510 (val F1=0.1340)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63785 | val 0.86101
  Epoch 016 - train 0.64102 | val 0.95962
  Classification -> best τ=0.550 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60821 | val 1.34657
  Epoch 016 - train 0.62272 | val 1.49894
  Classification -> best τ=0.640 (val F1=0.2942)
  Directional -> Accuracy: 0.5088, MCC: 0.1288, F1: 0.3333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59612 | val 1.72608
  Epoch 016 - train 0.57248 | val 1.62861
  Classification -> best τ=0.620 (val F1=0.1565)
  Directional -> Accuracy: 0.5231, MCC: 0.0428, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57076 | val 1.59838
  Epoch 017 - train 0.52451 | val 1.82023
  Classification -> best τ=0.560 (val F1=0.5489)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53203 | val 1.83269
  Epoch 016 - train 0.53924 | val 1.84994
  Classification -> best τ=0.495 (val F1=0.2035)
  Directional -> Accuracy: 0.6222, MCC: 0.2440, F1: 0.5854

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62909 | val 1.51822
  Epoch 016 - train 0.63426 | val 1.30265
  Classification -> best τ=0.480 (val F1=0.1376)
  Directional -> Accuracy: 0.5714, MCC: 0.0807, F1: 0.6786

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58872 | val 1.35004
  Epoch 016 - train 0.55778 | val 1.85330
  Classification -> best τ=0.505 (val F1=0.2755)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57103 | val 1.63693
  Epoch 016 - train 0.52255 | val 1.66126
  Classification -> best τ=0.515 (val F1=0.0948)
  Directional -> Accuracy: 0.5750, MCC: 0.1677, F1: 0.5641

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65078 | val 0.83673
  Epoch 020 - train 0.52260 | val 0.67912
  Epoch 030 - train 0.47179 | val 0.67774
  Classification -> best τ=0.795 (val F1=0.5210)
  Directional -> Accuracy: 0.5476, MCC: 0.0879, F1: 0.4865

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65443 | val 0.82390
  Epoch 020 - train 0.54965 | val 0.96655
  Epoch 021 - train 0.58548 | val 0.92717
  Classification -> best τ=0.780 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57616 | val 0.87067
  Epoch 016 - train 0.56529 | val 0.90102
  Classification -> best τ=0.420 (val F1=0.1737)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62617 | val 0.88462
  Epoch 018 - train 0.60194 | val 1.29909
  Classification -> best τ=0.305 (val F1=0.3366)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61910 | val 1.26956
  Epoch 016 - train 0.57710 | val 1.05078
  Classification -> best τ=0.625 (val F1=0.1818)
  Directional -> Accuracy: 0.5116, MCC: 0.0128, F1: 0.3226

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63952 | val 0.87991
  Epoch 016 - train 0.57051 | val 0.97669
  Classification -> best τ=0.440 (val F1=0.3525)
  Directional -> Accuracy: 0.6364, MCC: 0.3026, F1: 0.6364

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54917 | val 0.77820
  Epoch 016 - train 0.55562 | val 0.81858
  Classification -> best τ=0.440 (val F1=0.2658)
  Directional -> Accuracy: 0.5952, MCC: 0.2035, F1: 0.5641

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57085 | val 0.87559
  Epoch 016 - train 0.53084 | val 0.94002
  Classification -> best τ=0.495 (val F1=0.2026)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52466 | val 1.09187
  Epoch 016 - train 0.46055 | val 1.27247
  Classification -> best τ=0.455 (val F1=0.3105)
  Directional -> Accuracy: 0.5652, MCC: -0.0460, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58485 | val 0.71139
  Epoch 018 - train 0.56719 | val 0.88604
  Classification -> best τ=0.585 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58076 | val 1.38124
  Epoch 016 - train 0.56927 | val 1.45880
  Classification -> best τ=0.590 (val F1=0.1787)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63081 | val 0.73183
  Epoch 016 - train 0.58988 | val 0.75775
  Classification -> best τ=0.515 (val F1=0.4472)
  Directional -> Accuracy: 0.5556, MCC: 0.1093, F1: 0.5833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62555 | val 1.04082
  Epoch 016 - train 0.53291 | val 1.29495
  Classification -> best τ=0.490 (val F1=0.3015)
  Directional -> Accuracy: 0.5952, MCC: 0.1487, F1: 0.6792

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57184 | val 0.57285
  Epoch 020 - train 0.41389 | val 0.87793
  Epoch 027 - train 0.36215 | val 1.07035
  Classification -> best τ=0.890 (val F1=0.4867)
  Directional -> Accuracy: 0.4792, MCC: 0.1516, F1: 0.5614

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65322 | val 0.89026
  Epoch 016 - train 0.60702 | val 1.18783
  Classification -> best τ=0.475 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53620 | val 1.60364
  Epoch 016 - train 0.49650 | val 1.39352
  Classification -> best τ=0.805 (val F1=0.3884)
  Directional -> Accuracy: 0.5179, MCC: 0.0565, F1: 0.5970

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59837 | val 0.94969
  Epoch 016 - train 0.61486 | val 0.95835
  Classification -> best τ=0.425 (val F1=0.1646)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58090 | val 2.43908
  Epoch 016 - train 0.54155 | val 3.07542
  Classification -> best τ=0.780 (val F1=0.1144)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62421 | val 1.12339

[I 2026-02-20 01:04:57,442] Trial 62 finished with value: 0.2551976070928063 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0033445703623568844, 'weight_decay': 5.0688508661835796e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.3875858939932997, 'early_stopping_min_delta': 0.006454987534830161}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 017 - train 0.56684 | val 1.27629
  Classification -> best τ=0.525 (val F1=0.2124)
  Directional -> Accuracy: 0.4667, MCC: -0.0704, F1: 0.4286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2551976070928063
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61855 | val 0.96237
  Epoch 019 - train 0.48691 | val 0.96583
  Classification -> best τ=0.730 (val F1=0.2895)
  Directional -> Accuracy: 0.5405, MCC: -0.0113, F1: 0.1500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52656 | val 1.63683
  Epoch 016 - train 0.50758 | val 2.37776
  Classification -> best τ=0.500 (val F1=0.2850)
  Directional -> Accuracy: 0.6512, MCC: 0.3620, F1: 0.6512

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58636 | val 0.88305
  Epoch 017 - train 0.54523 | val 1.10853
  Classification -> best τ=0.580 (val F1=0.3592)
  Directional -> Accuracy: 0.4545, MCC: -0.1596, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61299 | val 1.91735
  Epoch 016 - train 0.58876 | val 1.49315
  Classification -> best τ=0.440 (val F1=0.1327)
  Directional -> Accuracy: 0.5417, MCC: 0.0411, F1: 0.6598

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50180 | val 0.94328
  Epoch 016 - train 0.42612 | val 1.11153
  Classification -> best τ=0.500 (val F1=0.3348)
  Directional -> Accuracy: 0.6250, MCC: 0.3539, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42587 | val 1.46050
  Epoch 016 - train 0.32843 | val 3.23255
  Classification -> best τ=0.395 (val F1=0.1993)
  Directional -> Accuracy: 0.4091, MCC: -0.1952, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59089 | val 0.94184
  Epoch 016 - train 0.52854 | val 1.24548
  Classification -> best τ=0.580 (val F1=0.1374)
  Directional -> Accuracy: 0.5455, MCC: 0.0271, F1: 0.3750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50748 | val 1.39345
  Epoch 016 - train 0.47711 | val 1.35573
  Classification -> best τ=0.525 (val F1=0.1204)
  Directional -> Accuracy: 0.5897, MCC: 0.1463, F1: 0.4667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48001 | val 1.46649
  Epoch 017 - train 0.43068 | val 1.58771
  Classification -> best τ=0.580 (val F1=0.3614)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55269 | val 0.87562
  Epoch 016 - train 0.48268 | val 0.92534
  Classification -> best τ=0.445 (val F1=0.1982)
  Directional -> Accuracy: 0.4328, MCC: -0.0798, F1: 0.4865

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54342 | val 2.76169
  Epoch 016 - train 0.49996 | val 2.70409
  Classification -> best τ=0.685 (val F1=0.3559)
  Directional -> Accuracy: 0.5532, MCC: 0.0626, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57097 | val 1.92444
  Epoch 016 - train 0.49426 | val 2.22715
  Classification -> best τ=0.380 (val F1=0.1955)
  Directional -> Accuracy: 0.5636, MCC: 0.1155, F1: 0.6571

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61469 | val 0.70141
  Epoch 020 - train 0.34873 | val 0.72776
  Epoch 029 - train 0.30088 | val 0.93691
  Classification -> best τ=0.580 (val F1=0.3732)
  Directional -> Accuracy: 0.5625, MCC: 0.1221, F1: 0.5333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61581 | val 1.13451
  Epoch 016 - train 0.54894 | val 1.82554
  Classification -> best τ=0.380 (val F1=0.3229)
  Directional -> Accuracy: 0.6034, MCC: 0.2776, F1: 0.7160

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52945 | val 0.98970
  Epoch 017 - train 0.45143 | val 1.66395
  Classification -> best τ=0.600 (val F1=0.2630)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54599 | val 0.91234
  Epoch 016 - train 0.49586 | val 1.13494
  Classification -> best τ=0.540 (val F1=0.2735)
  Directional -> Accuracy: 0.6716, MCC: 0.3532, F1: 0.7442

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60853 | val 1.99385
  Epoch 016 - train 0.54114 | val 2.60952
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57692 | val 1.22870
  Epoch 016 - train 0.51206 | val 1.39478
  Classification -> best τ=0.360 (val F1=0.2382)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57884 | val 0.98927
  Epoch 016 - train 0.51467 | val 1.40266
  Classification -> best τ=0.255 (val F1=0.2011)
  Directional -> Accuracy: 0.5161, MCC: 0.1681, F1: 0.3750

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58036 | val 0.74897
  Epoch 018 - train 0.41861 | val 0.90247
  Classification -> best τ=0.490 (val F1=0.2925)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50107 | val 1.34888
  Epoch 016 - train 0.44179 | val 1.40607
  Classification -> best τ=0.530 (val F1=0.1826)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55708 | val 1.16216
  Epoch 016 - train 0.51983 | val 1.27605
  Classification -> best τ=0.515 (val F1=0.2373)
  Directional -> Accuracy: 0.4444, MCC: -0.1443, F1: 0.2222

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59863 | val 1.21109
  Epoch 016 - train 0.51628 | val 1.30496
  Classification -> best τ=0.590 (val F1=0.0542)
  Directional -> Accuracy: 0.5091, MCC: 0.0885, F1: 0.4490

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58962 | val 0.91527
  Epoch 016 - train 0.50290 | val 1.10615
  Classification -> best τ=0.370 (val F1=0.1280)
  Directional -> Accuracy: 0.5397, MCC: 0.1727, F1: 0.6588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52544 | val 1.17754
  Epoch 016 - train 0.45823 | val 1.28135
  Classification -> best τ=0.590 (val F1=0.5093)
  Directional -> Accuracy: 0.5283, MCC: 0.1718, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47405 | val 1.23883
  Epoch 016 - train 0.42582 | val 1.83870
  Classification -> best τ=0.575 (val F1=0.2303)
  Directional -> Accuracy: 0.4286, MCC: -0.1132, F1: 0.4545

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58419 | val 1.27121
  Epoch 016 - train 0.53328 | val 1.05897
  Classification -> best τ=0.505 (val F1=0.0903)
  Directional -> Accuracy: 0.5208, MCC: 0.0493, F1: 0.5490

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59998 | val 1.01985
  Epoch 017 - train 0.50189 | val 0.96620
  Classification -> best τ=0.255 (val F1=0.2932)
  Directional -> Accuracy: 0.5370, MCC: 0.1256, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50879 | val 1.44500
  Epoch 016 - train 0.39799 | val 2.34286
  Classification -> best τ=0.685 (val F1=0.3333)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58406 | val 1.04546
  Epoch 019 - train 0.49222 | val 1.53210
  Classification -> best τ=0.670 (val F1=0.2659)
  Directional -> Accuracy: 0.4500, MCC: -0.0231, F1: 0.0833

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54456 | val 0.85055
  Epoch 018 - train 0.36048 | val 1.23289
  Classification -> best τ=0.200 (val F1=0.3007)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58313 | val 0.80090
  Epoch 016 - train 0.49367 | val 0.84128
  Classification -> best τ=0.475 (val F1=0.2994)
  Directional -> Accuracy: 0.5000, MCC: 0.1003, F1: 0.3137

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55238 | val 1.07318
  Epoch 016 - train 0.44628 | val 0.94134
  Classification -> best τ=0.580 (val F1=0.2901)
  Directional -> Accuracy: 0.5306, MCC: 0.0183, F1: 0.1481

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50770 | val 1.02902
  Epoch 016 - train 0.45392 | val 1.25755
  Classification -> best τ=0.235 (val F1=0.3663)
  Directional -> Accuracy: 0.6562, MCC: 0.3730, F1: 0.6207

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42067 | val 2.41117
  Epoch 016 - train 0.44649 | val 2.51489
  Classification -> best τ=0.585 (val F1=0.2583)
  Directional -> Accuracy: 0.5510, MCC: 0.1552, F1: 0.2143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54183 | val 1.10158
  Epoch 016 - train 0.49913 | val 1.43040
  Classification -> best τ=0.395 (val F1=0.3054)
  Directional -> Accuracy: 0.4815, MCC: 0.0631, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42486 | val 2.00671
  Epoch 016 - train 0.34353 | val 2.31534
  Classification -> best τ=0.390 (val F1=0.1732)
  Directional -> Accuracy: 0.5909, MCC: 0.1000, F1: 0.6897

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49338 | val 1.47127
  Epoch 017 - train 0.43750 | val 2.15210
  Classification -> best τ=0.440 (val F1=0.3458)
  Directional -> Accuracy: 0.3111, MCC: -0.1890, F1: 0.4561

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55920 | val 2.48142
  Epoch 016 - train 0.47620 | val 3.50352
  Classification -> best τ=0.205 (val F1=0.1350)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49236 | val 0.69224
  Epoch 020 - train 0.39433 | val 0.74878
  Epoch 024 - train 0.31327 | val 0.78500
  Classification -> best τ=0.330 (val F1=0.1013)
  Directional -> Accuracy: 0.3721, MCC: -0.2554, F1: 0.3721

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44041 | val 0.72245
  Epoch 019 - train 0.29010 | val 1.08850
  Classification -> best τ=0.520 (val F1=0.2618)
  Directional -> Accuracy: 0.5897, MCC: 0.1365, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46155 | val 1.08744
  Epoch 016 - train 0.31958 | val 1.44771
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58920 | val 1.45244
  Epoch 016 - train 0.51809 | val 1.77582
  Classification -> best τ=0.530 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54062 | val 2.31154
  Epoch 016 - train 0.47616 | val 2.55151
  Classification -> best τ=0.740 (val F1=0.2750)
  Directional -> Accuracy: 0.4815, MCC: -0.0388, F1: 0.3913

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55238 | val 1.24576
  Epoch 016 - train 0.51943 | val 1.47895
  Classification -> best τ=0.500 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1369, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52252 | val 2.71675
  Epoch 016 - train 0.40885 | val 2.84004
  Classification -> best τ=0.535 (val F1=0.0798)
  Directional -> Accuracy: 0.4717, MCC: -0.0800, F1: 0.5882

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62648 | val 1.02787
  Epoch 020 - train 0.46745 | val 1.37029

[I 2026-02-20 01:08:53,353] Trial 63 finished with value: 0.23820664079885923 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.004937860041046939, 'weight_decay': 0.00013885775938803562, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.4599863641265143, 'early_stopping_min_delta': 0.00415924431296497}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 022 - train 0.45591 | val 1.29903
  Classification -> best τ=0.575 (val F1=0.2714)
  Directional -> Accuracy: 0.5172, MCC: -0.0619, F1: 0.0667

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23820664079885923
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63220 | val 0.92046
  Epoch 020 - train 0.50783 | val 0.75875
  Classification -> best τ=0.660 (val F1=0.2571)
  Directional -> Accuracy: 0.5067, MCC: -0.0747, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58017 | val 0.89857
  Epoch 017 - train 0.47960 | val 1.29236
  Classification -> best τ=0.475 (val F1=0.1994)
  Directional -> Accuracy: 0.6136, MCC: 0.1436, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63030 | val 0.79358
  Epoch 016 - train 0.55185 | val 0.93986
  Classification -> best τ=0.585 (val F1=0.2835)
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64085 | val 1.19213
  Epoch 016 - train 0.61111 | val 1.30823
  Classification -> best τ=0.365 (val F1=0.1070)
  Directional -> Accuracy: 0.4247, MCC: -0.2217, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54576 | val 1.27559
  Epoch 016 - train 0.46154 | val 2.02870
  Classification -> best τ=0.610 (val F1=0.4278)
  Directional -> Accuracy: 0.6327, MCC: 0.2965, F1: 0.5500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54023 | val 0.67689
  Epoch 020 - train 0.36183 | val 1.06405
  Epoch 025 - train 0.29599 | val 1.10104
  Classification -> best τ=0.450 (val F1=0.4489)
  Directional -> Accuracy: 0.5111, MCC: 0.0445, F1: 0.6207

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61556 | val 0.72668
  Epoch 017 - train 0.51422 | val 1.10206
  Classification -> best τ=0.535 (val F1=0.1605)
  Directional -> Accuracy: 0.4627, MCC: -0.0673, F1: 0.4194

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58459 | val 2.09482
  Epoch 016 - train 0.50251 | val 2.29047
  Classification -> best τ=0.560 (val F1=0.3637)
  Directional -> Accuracy: 0.5122, MCC: -0.0025, F1: 0.4118

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64205 | val 1.00304
  Epoch 020 - train 0.56371 | val 1.04774
  Epoch 027 - train 0.40147 | val 1.06555
  Classification -> best τ=0.270 (val F1=0.2875)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59470 | val 0.83372
  Epoch 020 - train 0.46121 | val 1.52853
  Classification -> best τ=0.520 (val F1=0.1074)
  Directional -> Accuracy: 0.5441, MCC: 0.0981, F1: 0.5231

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58473 | val 1.21663
  Epoch 016 - train 0.57257 | val 1.43018
  Classification -> best τ=0.540 (val F1=0.3997)
  Directional -> Accuracy: 0.6250, MCC: 0.2365, F1: 0.5263

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59398 | val 1.09158
  Epoch 017 - train 0.48854 | val 1.52944
  Classification -> best τ=0.405 (val F1=0.2108)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52563 | val 2.86019
  Epoch 016 - train 0.46220 | val 2.84032
  Classification -> best τ=0.365 (val F1=0.2112)
  Directional -> Accuracy: 0.4490, MCC: -0.1193, F1: 0.3077

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65832 | val 0.80041
  Epoch 020 - train 0.50748 | val 0.77169
  Classification -> best τ=0.435 (val F1=0.3428)
  Directional -> Accuracy: 0.5593, MCC: 0.1176, F1: 0.5806

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57175 | val 0.99140
  Epoch 016 - train 0.50317 | val 1.51137
  Classification -> best τ=0.715 (val F1=0.1289)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61848 | val 0.88334
  Epoch 017 - train 0.47787 | val 1.55849
  Classification -> best τ=0.420 (val F1=0.2818)
  Directional -> Accuracy: 0.5147, MCC: -0.0141, F1: 0.6452

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59833 | val 1.35471
  Epoch 016 - train 0.56719 | val 1.94842
  Classification -> best τ=0.745 (val F1=0.1325)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62037 | val 1.29906
  Epoch 017 - train 0.54608 | val 2.08865
  Classification -> best τ=0.415 (val F1=0.1411)
  Directional -> Accuracy: 0.5270, MCC: -0.0443, F1: 0.6465

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57500 | val 1.20264
  Epoch 016 - train 0.52057 | val 1.62409
  Classification -> best τ=0.550 (val F1=0.2009)
  Directional -> Accuracy: 0.3968, MCC: -0.1153, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54186 | val 0.84593
  Epoch 016 - train 0.48741 | val 0.90516
  Classification -> best τ=0.555 (val F1=0.2467)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58325 | val 2.26758
  Epoch 016 - train 0.51544 | val 2.46918
  Classification -> best τ=0.480 (val F1=0.2041)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63746 | val 1.31980
  Epoch 016 - train 0.59636 | val 1.14073
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59218 | val 2.55256
  Epoch 016 - train 0.52003 | val 3.12430
  Classification -> best τ=0.710 (val F1=0.2474)
  Directional -> Accuracy: 0.6071, MCC: 0.2165, F1: 0.6333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56985 | val 0.89145
  Epoch 016 - train 0.47538 | val 1.06789
  Classification -> best τ=0.390 (val F1=0.2481)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57355 | val 1.48919
  Epoch 017 - train 0.43720 | val 1.71911
  Classification -> best τ=0.615 (val F1=0.4890)
  Directional -> Accuracy: 0.4630, MCC: -0.0146, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52471 | val 1.33759
  Epoch 016 - train 0.43525 | val 1.39332
  Classification -> best τ=0.470 (val F1=0.2829)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61816 | val 0.79858
  Epoch 017 - train 0.53817 | val 0.68387
  Classification -> best τ=0.585 (val F1=0.2513)
  Directional -> Accuracy: 0.5102, MCC: 0.2799, F1: 0.2941

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58082 | val 1.62792
  Epoch 016 - train 0.49397 | val 2.57610
  Classification -> best τ=0.525 (val F1=0.1186)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56856 | val 0.71790
  Epoch 020 - train 0.48420 | val 0.69878
  Epoch 026 - train 0.38341 | val 0.85205
  Classification -> best τ=0.405 (val F1=0.2955)
  Directional -> Accuracy: 0.5789, MCC: 0.1212, F1: 0.6800

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57289 | val 2.67190
  Epoch 016 - train 0.49709 | val 3.29497
  Classification -> best τ=0.575 (val F1=0.2550)
  Directional -> Accuracy: 0.4878, MCC: -0.0321, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61340 | val 1.19124
  Epoch 016 - train 0.52177 | val 0.98244
  Classification -> best τ=0.600 (val F1=0.1336)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55565 | val 1.02646
  Epoch 016 - train 0.46444 | val 1.41807
  Classification -> best τ=0.430 (val F1=0.1594)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58090 | val 1.37248
  Epoch 017 - train 0.49320 | val 1.72147
  Classification -> best τ=0.875 (val F1=0.2787)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56518 | val 0.96558
  Epoch 016 - train 0.52831 | val 1.59570
  Classification -> best τ=0.635 (val F1=0.3362)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50468 | val 1.05042
  Epoch 016 - train 0.45718 | val 1.52002
  Classification -> best τ=0.185 (val F1=0.2100)
  Directional -> Accuracy: 0.6154, MCC: 0.2664, F1: 0.6032

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53323 | val 0.97228
  Epoch 016 - train 0.48374 | val 1.08872
  Classification -> best τ=0.485 (val F1=0.2582)
  Directional -> Accuracy: 0.5500, MCC: 0.1746, F1: 0.3571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56730 | val 0.86085
  Epoch 016 - train 0.47438 | val 1.06732
  Classification -> best τ=0.410 (val F1=0.2203)
  Directional -> Accuracy: 0.5273, MCC: 0.0828, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50867 | val 1.81712
  Epoch 016 - train 0.39818 | val 2.17420
  Classification -> best τ=0.565 (val F1=0.3145)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51135 | val 1.16291
  Epoch 018 - train 0.43654 | val 1.92405
  Classification -> best τ=0.655 (val F1=0.4242)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56196 | val 2.22069
  Epoch 017 - train 0.44969 | val 3.49346
  Classification -> best τ=0.120 (val F1=0.2021)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58592 | val 0.73839
  Epoch 016 - train 0.57975 | val 0.80001
  Classification -> best τ=0.590 (val F1=0.3536)
  Directional -> Accuracy: 0.5455, MCC: 0.0945, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51588 | val 1.05607
  Epoch 016 - train 0.33389 | val 1.16786
  Classification -> best τ=0.495 (val F1=0.3194)
  Directional -> Accuracy: 0.6098, MCC: 0.1830, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45468 | val 2.01687
  Epoch 019 - train 0.37144 | val 2.26607
  Classification -> best τ=0.490 (val F1=0.1978)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65262 | val 1.56617
  Epoch 016 - train 0.56916 | val 1.93420
  Classification -> best τ=0.410 (val F1=0.1626)
  Directional -> Accuracy: 0.5000, MCC: 0.2169, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59663 | val 1.66214
  Epoch 018 - train 0.48697 | val 1.89827
  Classification -> best τ=0.240 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64053 | val 0.70901
  Epoch 020 - train 0.53704 | val 0.78981
  Epoch 021 - train 0.49522 | val 0.84100
  Classification -> best τ=0.395 (val F1=0.2495)
  Directional -> Accuracy: 0.5192, MCC: 0.1400, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60382 | val 1.22228
  Epoch 016 - train 0.49970 | val 1.88923
  Classification -> best τ=0.330 (val F1=0.2345)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63864 | val 0.70128

[I 2026-02-20 01:12:29,509] Trial 64 finished with value: 0.2478700738956157 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007314837453482228, 'weight_decay': 2.8394642902823737e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.2231529393328504, 'early_stopping_min_delta': 0.0054542234500905935}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 018 - train 0.47465 | val 1.13973
  Classification -> best τ=0.455 (val F1=0.2658)
  Directional -> Accuracy: 0.4576, MCC: -0.1382, F1: 0.6279

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2478700738956157
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60418 | val 0.79622
  Epoch 018 - train 0.56638 | val 0.86630
  Classification -> best τ=0.735 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57911 | val 0.89805
  Epoch 016 - train 0.54301 | val 0.99742
  Classification -> best τ=0.435 (val F1=0.0900)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61691 | val 0.82113
  Epoch 016 - train 0.58577 | val 0.87530
  Classification -> best τ=0.465 (val F1=0.3639)
  Directional -> Accuracy: 0.4565, MCC: -0.0763, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60830 | val 0.98719
  Epoch 016 - train 0.59065 | val 0.92144
  Classification -> best τ=0.380 (val F1=0.0322)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49581 | val 1.35657
  Epoch 016 - train 0.44966 | val 1.46737
  Classification -> best τ=0.580 (val F1=0.3641)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50115 | val 1.11360
  Epoch 016 - train 0.47144 | val 0.88497
  Classification -> best τ=0.605 (val F1=0.3069)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61191 | val 0.95641
  Epoch 016 - train 0.58431 | val 1.14580
  Classification -> best τ=0.500 (val F1=0.1833)
  Directional -> Accuracy: 0.4853, MCC: 0.0959, F1: 0.5570

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53789 | val 2.12510
  Epoch 016 - train 0.50228 | val 2.93726
  Classification -> best τ=0.525 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61579 | val 1.25326
  Epoch 016 - train 0.52342 | val 1.23503
  Classification -> best τ=0.620 (val F1=0.2988)
  Directional -> Accuracy: 0.6458, MCC: 0.2714, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58956 | val 1.42655
  Epoch 016 - train 0.51841 | val 1.30947
  Classification -> best τ=0.255 (val F1=0.2535)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59214 | val 0.73227
  Epoch 020 - train 0.58518 | val 0.80454
  Epoch 029 - train 0.42452 | val 1.10631
  Classification -> best τ=0.270 (val F1=0.4052)
  Directional -> Accuracy: 0.6531, MCC: 0.3350, F1: 0.4138

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62971 | val 2.40148
  Epoch 016 - train 0.52046 | val 3.19107
  Classification -> best τ=0.430 (val F1=0.1771)
  Directional -> Accuracy: 0.5965, MCC: 0.2482, F1: 0.7013

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52582 | val 1.75151
  Epoch 016 - train 0.45874 | val 1.87230
  Classification -> best τ=0.325 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64741 | val 0.74507
  Epoch 016 - train 0.58957 | val 0.86437
  Classification -> best τ=0.425 (val F1=0.3391)
  Directional -> Accuracy: 0.5333, MCC: 0.0692, F1: 0.5882

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51071 | val 0.73807
  Epoch 016 - train 0.50372 | val 0.93557
  Classification -> best τ=0.580 (val F1=0.1925)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55787 | val 0.71946
  Epoch 020 - train 0.47068 | val 0.73326
  Epoch 023 - train 0.49665 | val 0.75744
  Classification -> best τ=0.560 (val F1=0.2250)
  Directional -> Accuracy: 0.5072, MCC: 0.0467, F1: 0.4138

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58147 | val 1.86388
  Epoch 016 - train 0.57027 | val 1.78869
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58934 | val 1.05085
  Epoch 016 - train 0.53715 | val 0.91546
  Classification -> best τ=0.490 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59597 | val 1.25702
  Epoch 016 - train 0.52677 | val 1.23941
  Classification -> best τ=0.560 (val F1=0.1578)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58275 | val 1.08695
  Epoch 020 - train 0.47526 | val 0.88356
  Classification -> best τ=0.500 (val F1=0.3430)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58717 | val 0.88333
  Epoch 016 - train 0.55343 | val 0.97430
  Classification -> best τ=0.545 (val F1=0.2784)
  Directional -> Accuracy: 0.5106, MCC: -0.1609, F1: 0.6567

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64380 | val 1.08922
  Epoch 016 - train 0.59468 | val 1.15129
  Classification -> best τ=0.540 (val F1=0.1999)
  Directional -> Accuracy: 0.4308, MCC: -0.1578, F1: 0.2128

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57609 | val 0.95308
  Epoch 016 - train 0.58552 | val 0.98803
  Classification -> best τ=0.600 (val F1=0.2644)
  Directional -> Accuracy: 0.4561, MCC: -0.0051, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57740 | val 0.81948
  Epoch 016 - train 0.50646 | val 0.91290
  Classification -> best τ=0.460 (val F1=0.0599)
  Directional -> Accuracy: 0.4769, MCC: -0.0220, F1: 0.5952

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53799 | val 1.65544
  Epoch 016 - train 0.49603 | val 1.83806
  Classification -> best τ=0.530 (val F1=0.5644)
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51622 | val 1.63023
  Epoch 016 - train 0.43121 | val 1.82269
  Classification -> best τ=0.590 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58813 | val 0.93156
  Epoch 016 - train 0.55751 | val 0.84656
  Classification -> best τ=0.425 (val F1=0.1803)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56641 | val 1.49138
  Epoch 016 - train 0.48874 | val 1.82824
  Classification -> best τ=0.410 (val F1=0.2300)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57218 | val 1.99214
  Epoch 016 - train 0.47411 | val 2.07122
  Classification -> best τ=0.525 (val F1=0.1918)
  Directional -> Accuracy: 0.4500, MCC: -0.0821, F1: 0.4211

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57520 | val 0.72447
  Epoch 017 - train 0.49338 | val 0.78706
  Classification -> best τ=0.630 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0426, F1: 0.2222

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56604 | val 0.95917
  Epoch 016 - train 0.51020 | val 1.09476
  Classification -> best τ=0.470 (val F1=0.1641)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50224 | val 0.97721
  Epoch 017 - train 0.45573 | val 1.14684
  Classification -> best τ=0.520 (val F1=0.2978)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60781 | val 0.96961
  Epoch 017 - train 0.53087 | val 1.27629
  Classification -> best τ=0.700 (val F1=0.2637)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59327 | val 1.85038
  Epoch 016 - train 0.52671 | val 1.32866
  Classification -> best τ=0.395 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57348 | val 0.84454
  Epoch 019 - train 0.45579 | val 1.00386
  Classification -> best τ=0.275 (val F1=0.3787)
  Directional -> Accuracy: 0.6667, MCC: 0.3327, F1: 0.6944

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53675 | val 1.01127
  Epoch 016 - train 0.46300 | val 1.06969
  Classification -> best τ=0.515 (val F1=0.1822)
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.0870

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54164 | val 1.14075
  Epoch 016 - train 0.48187 | val 1.69712
  Classification -> best τ=0.435 (val F1=0.2755)
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46169 | val 1.56167
  Epoch 016 - train 0.38306 | val 1.70466
  Classification -> best τ=0.450 (val F1=0.3397)
  Directional -> Accuracy: 0.5652, MCC: 0.0094, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54046 | val 0.72334
  Epoch 019 - train 0.47998 | val 0.75558
  Classification -> best τ=0.375 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57540 | val 1.04785
  Epoch 016 - train 0.50217 | val 1.25626
  Classification -> best τ=0.410 (val F1=0.3053)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57820 | val 0.79334
  Epoch 016 - train 0.53538 | val 0.84532
  Classification -> best τ=0.525 (val F1=0.2737)
  Directional -> Accuracy: 0.5333, MCC: 0.0644, F1: 0.6316

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52157 | val 1.08856
  Epoch 016 - train 0.48434 | val 1.28223
  Classification -> best τ=0.600 (val F1=0.3612)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.2069

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48446 | val 1.09346
  Epoch 016 - train 0.45356 | val 1.07527
  Classification -> best τ=0.625 (val F1=0.1371)
  Directional -> Accuracy: 0.5417, MCC: 0.1309, F1: 0.5217

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60343 | val 1.12597
  Epoch 016 - train 0.56492 | val 1.15084
  Classification -> best τ=0.445 (val F1=0.3303)
  Directional -> Accuracy: 0.4000, MCC: -0.3357, F1: 0.5600

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54772 | val 2.16411
  Epoch 016 - train 0.49260 | val 2.19196
  Classification -> best τ=0.765 (val F1=0.3111)
  Directional -> Accuracy: 0.5357, MCC: 0.1073, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61924 | val 0.85167
  Epoch 017 - train 0.57643 | val 0.94507
  Classification -> best τ=0.340 (val F1=0.2309)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51726 | val 2.75687
  Epoch 016 - train 0.47898 | val 2.65303
  Classification -> best τ=0.780 (val F1=0.1254)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61499 | val 0.70313
  Epoch 020 - train 0.47392 | val 0.85225

[I 2026-02-20 01:15:30,934] Trial 65 finished with value: 0.24950365221692805 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0034175474009727905, 'weight_decay': 0.0002496330499166548, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.5131971128786434, 'early_stopping_min_delta': 0.005103200528195599}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 024 - train 0.43915 | val 0.78643
  Classification -> best τ=0.555 (val F1=0.1708)
  Directional -> Accuracy: 0.5833, MCC: 0.2093, F1: 0.3243

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24950365221692805
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61326 | val 0.92776
  Epoch 014 - train 0.60540 | val 0.91172
  Classification -> best τ=0.555 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61805 | val 0.70790
  Epoch 011 - train 0.62112 | val 0.72310
  Classification -> best τ=0.435 (val F1=0.1870)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66144 | val 0.72613
  Epoch 011 - train 0.63219 | val 0.74408
  Classification -> best τ=0.485 (val F1=0.2070)
  Directional -> Accuracy: 0.5957, MCC: 0.2128, F1: 0.5581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63893 | val 0.98463
  Epoch 011 - train 0.64412 | val 0.91894
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58106 | val 0.99287
  Epoch 012 - train 0.57605 | val 1.17427
  Classification -> best τ=0.480 (val F1=0.3612)
  Directional -> Accuracy: 0.5294, MCC: 0.0119, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59001 | val 0.69206
  Epoch 011 - train 0.60242 | val 0.69091
  Classification -> best τ=0.550 (val F1=0.1715)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65341 | val 0.74788
  Epoch 013 - train 0.63700 | val 0.82776
  Classification -> best τ=0.440 (val F1=0.1517)
  Directional -> Accuracy: 0.4203, MCC: 0.0315, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60337 | val 1.02944
  Epoch 011 - train 0.54603 | val 1.06341
  Classification -> best τ=0.530 (val F1=0.1688)
  Directional -> Accuracy: 0.5682, MCC: 0.0365, F1: 0.2963

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61190 | val 0.79551
  Epoch 011 - train 0.62888 | val 0.83927
  Classification -> best τ=0.510 (val F1=0.1978)
  Directional -> Accuracy: 0.5714, MCC: 0.2278, F1: 0.6441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60071 | val 0.69846
  Epoch 016 - train 0.56216 | val 0.68672
  Classification -> best τ=0.445 (val F1=0.2607)
  Directional -> Accuracy: 0.4286, MCC: -0.0849, F1: 0.5122

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63696 | val 0.89091
  Epoch 011 - train 0.63768 | val 0.92081
  Classification -> best τ=0.465 (val F1=0.0344)
  Directional -> Accuracy: 0.5600, MCC: 0.0963, F1: 0.4211

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60201 | val 0.99344
  Epoch 011 - train 0.59606 | val 1.03730
  Classification -> best τ=0.435 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58167 | val 0.85186
  Epoch 011 - train 0.56297 | val 0.95285
  Classification -> best τ=0.475 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63154 | val 0.63968
  Epoch 017 - train 0.61319 | val 0.65265
  Classification -> best τ=0.305 (val F1=0.3336)
  Directional -> Accuracy: 0.5574, MCC: 0.2312, F1: 0.6966

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61473 | val 0.80509
  Epoch 011 - train 0.60004 | val 0.83668
  Classification -> best τ=0.500 (val F1=0.0188)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60379 | val 0.78482
  Epoch 011 - train 0.59712 | val 0.74618
  Classification -> best τ=0.420 (val F1=0.2172)
  Directional -> Accuracy: 0.5857, MCC: 0.1909, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62994 | val 0.90836
  Epoch 011 - train 0.60434 | val 0.89691
  Classification -> best τ=0.615 (val F1=0.0833)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64139 | val 0.84767
  Epoch 011 - train 0.64434 | val 0.84675
  Classification -> best τ=0.465 (val F1=0.1095)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63367 | val 0.69310
  Epoch 014 - train 0.60571 | val 0.85984
  Classification -> best τ=0.395 (val F1=0.3068)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59476 | val 0.73000
  Epoch 012 - train 0.58449 | val 0.79031
  Classification -> best τ=0.555 (val F1=0.2083)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64006 | val 0.71791
  Epoch 011 - train 0.62954 | val 0.73447
  Classification -> best τ=0.485 (val F1=0.2000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62938 | val 0.75516
  Epoch 011 - train 0.63111 | val 0.73743
  Classification -> best τ=0.495 (val F1=0.1086)
  Directional -> Accuracy: 0.5152, MCC: 0.0305, F1: 0.5429

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62818 | val 0.76431
  Epoch 011 - train 0.61313 | val 0.77268
  Classification -> best τ=0.570 (val F1=0.2967)
  Directional -> Accuracy: 0.5000, MCC: 0.2369, F1: 0.2162

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62428 | val 0.79823
  Epoch 011 - train 0.61598 | val 0.84462
  Classification -> best τ=0.500 (val F1=0.1860)
  Directional -> Accuracy: 0.5152, MCC: 0.1086, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61367 | val 0.62470
  Epoch 017 - train 0.54763 | val 0.66614
  Classification -> best τ=0.455 (val F1=0.4472)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58765 | val 0.73581
  Epoch 011 - train 0.58032 | val 0.74427
  Classification -> best τ=0.445 (val F1=0.1925)
  Directional -> Accuracy: 0.5000, MCC: 0.1274, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61958 | val 0.69076
  Epoch 020 - train 0.58742 | val 0.69003
  Epoch 028 - train 0.56359 | val 0.72898
  Classification -> best τ=0.575 (val F1=0.3920)
  Directional -> Accuracy: 0.6047, MCC: 0.1428, F1: 0.7119

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62170 | val 0.88440
  Epoch 014 - train 0.60501 | val 1.04965
  Classification -> best τ=0.420 (val F1=0.1286)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60608 | val 0.70579
  Epoch 011 - train 0.56497 | val 0.72630
  Classification -> best τ=0.485 (val F1=0.2924)
  Directional -> Accuracy: 0.5854, MCC: 0.1890, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61627 | val 1.33947
  Epoch 011 - train 0.59867 | val 1.45414
  Classification -> best τ=0.500 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64179 | val 0.79686
  Epoch 011 - train 0.63998 | val 0.79666
  Classification -> best τ=0.455 (val F1=0.1650)
  Directional -> Accuracy: 0.5349, MCC: 0.0282, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61714 | val 0.90255
  Epoch 011 - train 0.60007 | val 0.92714
  Classification -> best τ=0.460 (val F1=0.1278)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62687 | val 0.69855
  Epoch 014 - train 0.60413 | val 0.71542
  Classification -> best τ=0.370 (val F1=0.3721)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60952 | val 0.77969
  Epoch 011 - train 0.61531 | val 0.81993
  Classification -> best τ=0.510 (val F1=0.4082)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6122

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61593 | val 0.77988
  Epoch 011 - train 0.61736 | val 0.79713
  Classification -> best τ=0.480 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61918 | val 0.84210
  Epoch 011 - train 0.59483 | val 0.90238
  Classification -> best τ=0.450 (val F1=0.3266)
  Directional -> Accuracy: 0.5970, MCC: 0.1698, F1: 0.6582

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61519 | val 0.71819
  Epoch 011 - train 0.61887 | val 0.72750
  Classification -> best τ=0.480 (val F1=0.1902)
  Directional -> Accuracy: 0.6512, MCC: 0.3596, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58235 | val 0.75329
  Epoch 012 - train 0.59358 | val 0.73882
  Classification -> best τ=0.475 (val F1=0.1851)
  Directional -> Accuracy: 0.4561, MCC: -0.0745, F1: 0.5231

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58964 | val 0.89782
  Epoch 012 - train 0.54888 | val 0.91592
  Classification -> best τ=0.500 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60744 | val 0.65707
  Epoch 020 - train 0.57264 | val 0.65012
  Epoch 028 - train 0.58531 | val 0.68390
  Classification -> best τ=0.315 (val F1=0.4708)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58631 | val 0.97489
  Epoch 011 - train 0.59410 | val 1.03826
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60705 | val 0.91811
  Epoch 013 - train 0.59781 | val 1.14426
  Classification -> best τ=0.445 (val F1=0.2831)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62614 | val 0.69145
  Epoch 016 - train 0.58594 | val 0.69143
  Classification -> best τ=0.490 (val F1=0.3222)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58252 | val 0.72349
  Epoch 011 - train 0.59053 | val 0.72663
  Classification -> best τ=0.520 (val F1=0.2749)
  Directional -> Accuracy: 0.4091, MCC: -0.1283, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61844 | val 0.74616
  Epoch 017 - train 0.56033 | val 0.75609
  Classification -> best τ=0.455 (val F1=0.2786)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62256 | val 0.91597
  Epoch 014 - train 0.60023 | val 0.99131
  Classification -> best τ=0.480 (val F1=0.1903)
  Directional -> Accuracy: 0.6964, MCC: 0.3883, F1: 0.7385

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62299 | val 1.09135
  Epoch 011 - train 0.59413 | val 1.21026
  Classification -> best τ=0.510 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63361 | val 1.02546
  Epoch 011 - train 0.64684 | val 1.04512
  Classification -> best τ=0.500 (val F1=0.1508)
  Directional -> Accuracy: 0.6111, MCC: 0.2376, F1: 0.6957

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63956 | val 0.83082
  Epoch 011 - train 0.62304 | val 0.81858
  Classification -> best τ=0.505 (val F1=0.1979)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61829 | val 0.72521

[I 2026-02-20 01:16:39,906] Trial 66 finished with value: 0.2231333259183428 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.0017141997789236422, 'weight_decay': 7.250394509143063e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7698199651213162, 'early_stopping_min_delta': 0.003848413176176106}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 013 - train 0.60301 | val 0.79161
  Classification -> best τ=0.560 (val F1=0.3074)
  Directional -> Accuracy: 0.4754, MCC: -0.1050, F1: 0.2000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2231333259183428
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62302 | val 0.69006
  Epoch 017 - train 0.56240 | val 0.99975
  Classification -> best τ=0.395 (val F1=0.1499)
  Directional -> Accuracy: 0.5733, MCC: 0.1312, F1: 0.5000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57201 | val 1.01221
  Epoch 017 - train 0.49438 | val 1.07326
  Classification -> best τ=0.400 (val F1=0.1030)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59900 | val 0.70512
  Epoch 016 - train 0.54900 | val 0.71059
  Classification -> best τ=0.480 (val F1=0.3055)
  Directional -> Accuracy: 0.4444, MCC: -0.1195, F1: 0.4898

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64245 | val 1.76337
  Epoch 016 - train 0.60767 | val 1.73692
  Classification -> best τ=0.355 (val F1=0.1070)
  Directional -> Accuracy: 0.4795, MCC: -0.0133, F1: 0.3667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55590 | val 1.85162
  Epoch 016 - train 0.48550 | val 1.54277
  Classification -> best τ=0.535 (val F1=0.4264)
  Directional -> Accuracy: 0.6939, MCC: 0.3984, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47028 | val 1.49911
  Epoch 016 - train 0.47554 | val 1.05088
  Classification -> best τ=0.620 (val F1=0.2190)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61504 | val 0.94558
  Epoch 017 - train 0.48884 | val 1.52239
  Classification -> best τ=0.310 (val F1=0.2112)
  Directional -> Accuracy: 0.4478, MCC: 0.1175, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54715 | val 3.83615
  Epoch 016 - train 0.51702 | val 3.88721
  Classification -> best τ=0.680 (val F1=0.1777)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58321 | val 0.87643
  Epoch 017 - train 0.53013 | val 1.03419
  Classification -> best τ=0.510 (val F1=0.2018)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56182 | val 0.78943
  Epoch 016 - train 0.49964 | val 1.18383
  Classification -> best τ=0.365 (val F1=0.1846)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62746 | val 1.18291
  Epoch 016 - train 0.53900 | val 1.38492
  Classification -> best τ=0.595 (val F1=0.2444)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60979 | val 1.23180
  Epoch 016 - train 0.53780 | val 1.65285
  Classification -> best τ=0.355 (val F1=0.1269)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49126 | val 2.07533
  Epoch 016 - train 0.47108 | val 3.15248
  Classification -> best τ=0.255 (val F1=0.2335)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65985 | val 0.79404
  Epoch 020 - train 0.52826 | val 0.76313
  Epoch 022 - train 0.49825 | val 0.79913
  Classification -> best τ=0.255 (val F1=0.3358)
  Directional -> Accuracy: 0.5424, MCC: 0.1057, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60332 | val 1.06955
  Epoch 017 - train 0.51834 | val 1.44435
  Classification -> best τ=0.585 (val F1=0.2043)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54374 | val 0.99082
  Epoch 016 - train 0.49887 | val 1.13284
  Classification -> best τ=0.395 (val F1=0.3005)
  Directional -> Accuracy: 0.5882, MCC: 0.2261, F1: 0.7143

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60772 | val 1.07128
  Epoch 016 - train 0.53962 | val 1.28163
  Classification -> best τ=0.570 (val F1=0.1890)
  Directional -> Accuracy: 0.4386, MCC: 0.1869, F1: 0.1579

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64200 | val 1.08151
  Epoch 016 - train 0.58327 | val 1.55071
  Classification -> best τ=0.385 (val F1=0.2030)
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60009 | val 1.23235
  Epoch 016 - train 0.55797 | val 1.09826
  Classification -> best τ=0.600 (val F1=0.2246)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59304 | val 0.75218
  Epoch 016 - train 0.50433 | val 0.78591
  Classification -> best τ=0.350 (val F1=0.2463)
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55649 | val 0.90099
  Epoch 016 - train 0.52048 | val 0.98141
  Classification -> best τ=0.535 (val F1=0.1427)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62109 | val 1.70389
  Epoch 016 - train 0.56366 | val 1.98995
  Classification -> best τ=0.445 (val F1=0.2149)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5789

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58886 | val 1.67622
  Epoch 016 - train 0.48612 | val 2.31350
  Classification -> best τ=0.715 (val F1=0.3464)
  Directional -> Accuracy: 0.5000, MCC: 0.2402, F1: 0.2222

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54315 | val 1.02916
  Epoch 016 - train 0.50045 | val 1.07297
  Classification -> best τ=0.460 (val F1=0.1994)
  Directional -> Accuracy: 0.5000, MCC: 0.0426, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54722 | val 0.97956
  Epoch 016 - train 0.45177 | val 1.09464
  Classification -> best τ=0.530 (val F1=0.4447)
  Directional -> Accuracy: 0.5556, MCC: 0.1930, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52760 | val 1.13312
  Epoch 016 - train 0.42890 | val 1.25015
  Classification -> best τ=0.520 (val F1=0.1543)
  Directional -> Accuracy: 0.5349, MCC: 0.0295, F1: 0.4118

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58067 | val 1.24982
  Epoch 018 - train 0.49717 | val 2.56411
  Classification -> best τ=0.555 (val F1=0.1915)
  Directional -> Accuracy: 0.5510, MCC: 0.1000, F1: 0.5926

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54491 | val 1.57796
  Epoch 016 - train 0.49022 | val 1.74489
  Classification -> best τ=0.425 (val F1=0.1682)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61669 | val 0.72803
  Epoch 020 - train 0.47491 | val 0.74576
  Epoch 027 - train 0.46278 | val 0.77971
  Classification -> best τ=0.270 (val F1=0.2955)
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55041 | val 3.04636
  Epoch 016 - train 0.51811 | val 3.75612
  Classification -> best τ=0.700 (val F1=0.3922)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57854 | val 0.87282
  Epoch 016 - train 0.45925 | val 1.02978
  Classification -> best τ=0.440 (val F1=0.1992)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50575 | val 0.99134
  Epoch 016 - train 0.41181 | val 1.19663
  Classification -> best τ=0.470 (val F1=0.0118)
  Directional -> Accuracy: 0.4375, MCC: -0.1306, F1: 0.1818

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55817 | val 0.99316
  Epoch 016 - train 0.51434 | val 1.33209
  Classification -> best τ=0.480 (val F1=0.2646)
  Directional -> Accuracy: 0.5211, MCC: 0.1508, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61477 | val 1.01568
  Epoch 016 - train 0.50004 | val 1.30863
  Classification -> best τ=0.700 (val F1=0.3363)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50227 | val 1.18630
  Epoch 016 - train 0.47265 | val 1.46473
  Classification -> best τ=0.220 (val F1=0.3828)
  Directional -> Accuracy: 0.5846, MCC: 0.1425, F1: 0.6494

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50773 | val 0.87275
  Epoch 017 - train 0.41748 | val 1.44218
  Classification -> best τ=0.525 (val F1=0.2085)
  Directional -> Accuracy: 0.5750, MCC: 0.2253, F1: 0.4138

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53885 | val 0.88802
  Epoch 016 - train 0.51556 | val 1.07185
  Classification -> best τ=0.250 (val F1=0.2247)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48909 | val 1.73208
  Epoch 016 - train 0.34830 | val 1.84103
  Classification -> best τ=0.640 (val F1=0.3283)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51635 | val 0.88922
  Epoch 017 - train 0.47046 | val 1.01420
  Classification -> best τ=0.585 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54579 | val 2.60797
  Epoch 016 - train 0.47805 | val 3.53296
  Classification -> best τ=0.730 (val F1=0.1237)
  Directional -> Accuracy: 0.5205, MCC: 0.0442, F1: 0.5570

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59177 | val 0.81335
  Epoch 016 - train 0.54668 | val 0.92757
  Classification -> best τ=0.560 (val F1=0.2902)
  Directional -> Accuracy: 0.5227, MCC: 0.0716, F1: 0.6557

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48345 | val 0.85409
  Epoch 016 - train 0.40065 | val 0.95374
  Classification -> best τ=0.500 (val F1=0.3194)
  Directional -> Accuracy: 0.6341, MCC: 0.2401, F1: 0.6939

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54491 | val 0.99890
  Epoch 016 - train 0.46229 | val 1.17335
  Classification -> best τ=0.430 (val F1=0.2985)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61842 | val 1.00775
  Epoch 016 - train 0.59773 | val 1.20019
  Classification -> best τ=0.525 (val F1=0.1626)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54501 | val 1.67176
  Epoch 016 - train 0.49983 | val 1.98881
  Classification -> best τ=0.505 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62479 | val 0.80715
  Epoch 020 - train 0.49787 | val 0.94132
  Epoch 023 - train 0.49750 | val 0.88716
  Classification -> best τ=0.500 (val F1=0.3082)
  Directional -> Accuracy: 0.5962, MCC: 0.1925, F1: 0.6038

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55948 | val 2.58298
  Epoch 016 - train 0.48242 | val 2.76320
  Classification -> best τ=0.595 (val F1=0.1685)
  Directional -> Accuracy: 0.4815, MCC: -0.0262, F1: 0.3913

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61281 | val 0.73702
  Epoch 020 - train 0.49272 | val 0.98206

[I 2026-02-20 01:20:10,786] Trial 67 finished with value: 0.24197198267333442 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.0055018601681049465, 'weight_decay': 1.695656938731908e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.6335450875703745, 'early_stopping_min_delta': 0.00436145149326171}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 029 - train 0.43949 | val 0.95440
  Classification -> best τ=0.285 (val F1=0.3637)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24197198267333442
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56512 | val 2.12111
  Epoch 016 - train 0.48894 | val 2.04893
  Classification -> best τ=0.495 (val F1=0.2453)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50193 | val 1.42868
  Epoch 016 - train 0.45788 | val 1.52438
  Classification -> best τ=0.445 (val F1=0.1424)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52884 | val 0.85027
  Epoch 019 - train 0.46297 | val 1.13765
  Classification -> best τ=0.550 (val F1=0.3143)
  Directional -> Accuracy: 0.4681, MCC: -0.0135, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56450 | val 2.86809
  Epoch 016 - train 0.54246 | val 2.44400
  Classification -> best τ=0.505 (val F1=0.1498)
  Directional -> Accuracy: 0.4533, MCC: -0.0155, F1: 0.0465

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48203 | val 2.15440
  Epoch 017 - train 0.39235 | val 4.23684
  Classification -> best τ=0.455 (val F1=0.4513)
  Directional -> Accuracy: 0.6863, MCC: 0.3785, F1: 0.7419

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42212 | val 1.82325
  Epoch 016 - train 0.30356 | val 5.83223
  Classification -> best τ=0.610 (val F1=0.2335)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54680 | val 0.79400
  Epoch 016 - train 0.50713 | val 1.47260
  Classification -> best τ=0.450 (val F1=0.1891)
  Directional -> Accuracy: 0.5507, MCC: 0.1554, F1: 0.5634

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49810 | val 2.67506
  Epoch 016 - train 0.39521 | val 4.10774
  Classification -> best τ=0.525 (val F1=0.0226)
  Directional -> Accuracy: 0.5227, MCC: 0.1108, F1: 0.5532

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51649 | val 1.01012
  Epoch 016 - train 0.45640 | val 1.28632
  Classification -> best τ=0.490 (val F1=0.4055)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50757 | val 0.90089
  Epoch 016 - train 0.44608 | val 0.94859
  Classification -> best τ=0.545 (val F1=0.1137)
  Directional -> Accuracy: 0.6143, MCC: 0.2443, F1: 0.1818

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52739 | val 3.42218
  Epoch 016 - train 0.44772 | val 4.19922
  Classification -> best τ=0.560 (val F1=0.0689)
  Directional -> Accuracy: 0.3600, MCC: -0.2987, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54005 | val 2.64259
  Epoch 016 - train 0.47420 | val 3.36738
  Classification -> best τ=0.475 (val F1=0.1026)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49167 | val 3.75312
  Epoch 016 - train 0.40172 | val 5.91008
  Classification -> best τ=0.420 (val F1=0.1839)
  Directional -> Accuracy: 0.4651, MCC: -0.0261, F1: 0.5306

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57454 | val 0.89898
  Epoch 017 - train 0.46249 | val 0.90949
  Classification -> best τ=0.380 (val F1=0.2501)
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52388 | val 0.78737
  Epoch 016 - train 0.45557 | val 0.93024
  Classification -> best τ=0.460 (val F1=0.0952)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53784 | val 1.78088
  Epoch 016 - train 0.49154 | val 1.46274
  Classification -> best τ=0.370 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55153 | val 2.64678
  Epoch 016 - train 0.53970 | val 2.99412
  Classification -> best τ=0.460 (val F1=0.1302)
  Directional -> Accuracy: 0.5932, MCC: -0.1444, F1: 0.7447

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55751 | val 0.81471
  Epoch 016 - train 0.53411 | val 1.18241
  Classification -> best τ=0.550 (val F1=0.1800)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51816 | val 2.15641
  Epoch 016 - train 0.47228 | val 3.16345
  Classification -> best τ=0.590 (val F1=0.1446)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50176 | val 0.94321
  Epoch 020 - train 0.42160 | val 0.96723
  Epoch 021 - train 0.36800 | val 1.65559
  Classification -> best τ=0.630 (val F1=0.2747)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46218 | val 2.77961
  Epoch 016 - train 0.40582 | val 2.54857
  Classification -> best τ=0.470 (val F1=0.1617)
  Directional -> Accuracy: 0.5208, MCC: 0.0759, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56097 | val 1.16806
  Epoch 016 - train 0.47962 | val 1.70483
  Classification -> best τ=0.545 (val F1=0.2617)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2979

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52719 | val 1.72439
  Epoch 016 - train 0.52087 | val 2.29986
  Classification -> best τ=0.525 (val F1=0.1984)
  Directional -> Accuracy: 0.5690, MCC: 0.1345, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52860 | val 1.46136
  Epoch 016 - train 0.50870 | val 1.35113
  Classification -> best τ=0.395 (val F1=0.1878)
  Directional -> Accuracy: 0.5606, MCC: 0.1275, F1: 0.5672

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49273 | val 0.87230
  Epoch 018 - train 0.41649 | val 1.08491
  Classification -> best τ=0.480 (val F1=0.4653)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46746 | val 1.25918
  Epoch 016 - train 0.37908 | val 1.74034
  Classification -> best τ=0.500 (val F1=0.1155)
  Directional -> Accuracy: 0.5870, MCC: 0.1236, F1: 0.1739

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60017 | val 0.85157
  Epoch 016 - train 0.50501 | val 1.13133
  Classification -> best τ=0.495 (val F1=0.1818)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52073 | val 1.23959
  Epoch 016 - train 0.46611 | val 1.68437
  Classification -> best τ=0.455 (val F1=0.1939)
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51823 | val 1.01050
  Epoch 016 - train 0.47597 | val 1.21736
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49300 | val 2.50186
  Epoch 016 - train 0.41448 | val 3.75422
  Classification -> best τ=0.520 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0074, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50663 | val 0.82484
  Epoch 016 - train 0.45425 | val 1.15039
  Classification -> best τ=0.500 (val F1=0.0754)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49136 | val 1.46132
  Epoch 016 - train 0.41118 | val 1.86855
  Classification -> best τ=0.515 (val F1=0.1852)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51163 | val 0.85201
  Epoch 018 - train 0.41870 | val 1.25720
  Classification -> best τ=0.230 (val F1=0.3602)
  Directional -> Accuracy: 0.5616, MCC: 0.1368, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51565 | val 2.22085
  Epoch 016 - train 0.41274 | val 2.34484
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53939 | val 1.05884
  Epoch 016 - train 0.41355 | val 1.28992
  Classification -> best τ=0.495 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51127 | val 0.86861
  Epoch 016 - train 0.42532 | val 0.99499
  Classification -> best τ=0.440 (val F1=0.3431)
  Directional -> Accuracy: 0.5224, MCC: 0.1217, F1: 0.4286

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47038 | val 0.81692
  Epoch 020 - train 0.32540 | val 0.80666
  Classification -> best τ=0.475 (val F1=0.3499)
  Directional -> Accuracy: 0.6744, MCC: 0.3519, F1: 0.7083

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48749 | val 1.49356
  Epoch 016 - train 0.41008 | val 1.80082
  Classification -> best τ=0.360 (val F1=0.1971)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47397 | val 1.71001
  Epoch 016 - train 0.34744 | val 1.73341
  Classification -> best τ=0.555 (val F1=0.2232)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48020 | val 0.79395
  Epoch 020 - train 0.39359 | val 1.00309
  Classification -> best τ=0.420 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.50324 | val 2.03892
  Epoch 016 - train 0.41537 | val 3.63209
  Classification -> best τ=0.510 (val F1=0.1461)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51885 | val 2.26064
  Epoch 016 - train 0.40960 | val 3.38511
  Classification -> best τ=0.430 (val F1=0.3203)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49617 | val 2.41757
  Epoch 016 - train 0.40975 | val 2.97550
  Classification -> best τ=0.515 (val F1=0.4379)
  Directional -> Accuracy: 0.5319, MCC: 0.0653, F1: 0.5217

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47149 | val 2.19184
  Epoch 016 - train 0.35412 | val 3.73775
  Classification -> best τ=0.460 (val F1=0.2100)
  Directional -> Accuracy: 0.5909, MCC: 0.1325, F1: 0.6897

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49318 | val 1.25432
  Epoch 016 - train 0.39159 | val 2.55948
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59541 | val 1.03520
  Epoch 017 - train 0.53719 | val 1.23945
  Classification -> best τ=0.570 (val F1=0.1563)
  Directional -> Accuracy: 0.5714, MCC: 0.1385, F1: 0.6000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52600 | val 1.09967
  Epoch 016 - train 0.44871 | val 1.20423
  Classification -> best τ=0.555 (val F1=0.3444)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54639 | val 1.14334
  Epoch 016 - train 0.48719 | val 1.08952
  Classification -> best τ=0.470 (val F1=0.2444)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48976 | val 0.80071
  Epoch 020 - train 0.36581 | val 1.28341
  Epoch 021 - train 0.33920 | val 1.07298
  Classification -> best τ=0.460 (val F1=0.1667)
  Directional -> Accuracy: 0.4464, MCC: -0.1995, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55701 | val 2.42045

[I 2026-02-20 01:20:55,324] Trial 68 finished with value: 0.21137827914899782 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.002543459143990648, 'weight_decay': 6.0765192149243855e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.4214192094109999, 'early_stopping_min_delta': 0.004634215153160449}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 017 - train 0.47684 | val 2.18175
  Classification -> best τ=0.560 (val F1=0.2639)
  Directional -> Accuracy: 0.4918, MCC: -0.0781, F1: 0.1622

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21137827914899782
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69746 | val 0.70219
  Epoch 016 - train 0.68884 | val 0.70190
  Classification -> best τ=0.490 (val F1=0.0149)
  Directional -> Accuracy: 0.3947, MCC: -0.1845, F1: 0.5106

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68868 | val 0.70167
  Epoch 019 - train 0.69017 | val 0.71714
  Classification -> best τ=0.425 (val F1=0.2029)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69438 | val 0.73397
  Epoch 016 - train 0.69509 | val 0.73848
  Classification -> best τ=0.505 (val F1=0.0705)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71668 | val 0.75061
  Epoch 016 - train 0.70791 | val 0.74103
  Classification -> best τ=0.575 (val F1=0.0992)
  Directional -> Accuracy: 0.4865, MCC: -0.0726, F1: 0.5957

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70010 | val 0.67435
  Epoch 020 - train 0.71058 | val 0.67254
  Classification -> best τ=0.545 (val F1=0.2848)
  Directional -> Accuracy: 0.6400, MCC: 0.2942, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70575 | val 0.70436
  Epoch 016 - train 0.69103 | val 0.70919
  Classification -> best τ=0.550 (val F1=0.1085)
  Directional -> Accuracy: 0.4565, MCC: -0.0851, F1: 0.6032

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70916 | val 0.73847
  Epoch 016 - train 0.71915 | val 0.73710
  Classification -> best τ=0.450 (val F1=0.1718)
  Directional -> Accuracy: 0.6176, MCC: 0.1505, F1: 0.0714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70175 | val 0.71347
  Epoch 016 - train 0.69943 | val 0.71657
  Classification -> best τ=0.490 (val F1=0.0965)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4615

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72723 | val 0.72645
  Epoch 016 - train 0.70407 | val 0.73569
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69346 | val 0.74658
  Epoch 016 - train 0.69651 | val 0.74669
  Classification -> best τ=0.465 (val F1=0.1810)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69094 | val 0.68877
  Epoch 020 - train 0.69570 | val 0.68879
  Epoch 030 - train 0.69137 | val 0.69063
  Epoch 033 - train 0.68958 | val 0.68903
  Classification -> best τ=0.405 (val F1=0.1713)
  Directional -> Accuracy: 0.4490, MCC: -0.1005, F1: 0.4255

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69745 | val 0.69491
  Epoch 016 - train 0.71336 | val 0.69612
  Classification -> best τ=0.490 (val F1=0.1724)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67829 | val 1.09381
  Epoch 016 - train 0.68095 | val 1.14236
  Classification -> best τ=0.425 (val F1=0.2172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69843 | val 0.71230
  Epoch 016 - train 0.68933 | val 0.71530
  Classification -> best τ=0.500 (val F1=0.2623)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70840 | val 0.71575
  Epoch 016 - train 0.71363 | val 0.71703
  Classification -> best τ=0.535 (val F1=0.0903)
  Directional -> Accuracy: 0.5490, MCC: 0.2470, F1: 0.6567

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70418 | val 0.72943
  Epoch 016 - train 0.69797 | val 0.73226
  Classification -> best τ=0.475 (val F1=0.2659)
  Directional -> Accuracy: 0.5942, MCC: 0.2287, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68006 | val 0.74261
  Epoch 016 - train 0.67884 | val 0.74147
  Classification -> best τ=0.565 (val F1=0.1291)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69872 | val 0.72107
  Epoch 016 - train 0.68648 | val 0.72029
  Classification -> best τ=0.495 (val F1=0.1592)
  Directional -> Accuracy: 0.6000, MCC: 0.0705, F1: 0.7321

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70628 | val 0.75015
  Epoch 016 - train 0.70863 | val 0.75064
  Classification -> best τ=0.565 (val F1=0.2648)
  Directional -> Accuracy: 0.4375, MCC: -0.2088, F1: 0.5610

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71952 | val 0.77240
  Epoch 016 - train 0.71259 | val 0.76862
  Classification -> best τ=0.485 (val F1=0.1844)
  Directional -> Accuracy: 0.5135, MCC: 0.0917, F1: 0.4000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68393 | val 0.73865
  Epoch 016 - train 0.68681 | val 0.73775
  Classification -> best τ=0.490 (val F1=0.1455)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69997 | val 0.69133
  Epoch 016 - train 0.71474 | val 0.69191
  Classification -> best τ=0.465 (val F1=0.2371)
  Directional -> Accuracy: 0.4923, MCC: -0.0443, F1: 0.6374

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.72357 | val 0.72899
  Epoch 016 - train 0.71409 | val 0.72966
  Classification -> best τ=0.465 (val F1=0.2010)
  Directional -> Accuracy: 0.4561, MCC: -0.0906, F1: 0.4918

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70872 | val 0.69503
  Epoch 016 - train 0.72119 | val 0.69489
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70266 | val 0.69945
  Epoch 016 - train 0.69631 | val 0.70018
  Classification -> best τ=0.490 (val F1=0.0096)
  Directional -> Accuracy: 0.5455, MCC: 0.0745, F1: 0.6032

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.77555 | val 0.74557
  Epoch 016 - train 0.75790 | val 0.78242
  Classification -> best τ=0.430 (val F1=0.1131)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72596 | val 0.78924
  Epoch 016 - train 0.71624 | val 0.79893
  Classification -> best τ=0.485 (val F1=0.3586)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72847 | val 0.69229
  Epoch 016 - train 0.71106 | val 0.69135
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68729 | val 0.70823
  Epoch 016 - train 0.67957 | val 0.71011
  Classification -> best τ=0.465 (val F1=0.0216)
  Directional -> Accuracy: 0.6250, MCC: 0.2389, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69363 | val 0.69735
  Epoch 020 - train 0.68489 | val 0.69675
  Epoch 026 - train 0.68514 | val 0.69681
  Classification -> best τ=0.575 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70397 | val 0.64596
  Epoch 020 - train 0.71989 | val 0.63874
  Epoch 027 - train 0.70654 | val 0.63895
  Classification -> best τ=0.560 (val F1=0.3561)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70530 | val 0.69625
  Epoch 016 - train 0.70016 | val 0.69651
  Classification -> best τ=0.515 (val F1=0.1679)
  Directional -> Accuracy: 0.5306, MCC: 0.0601, F1: 0.5490

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69911 | val 0.70473
  Epoch 016 - train 0.70453 | val 0.70506
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71800 | val 0.69087
  Epoch 020 - train 0.73246 | val 0.69451
  Epoch 024 - train 0.71022 | val 0.69279
  Classification -> best τ=0.560 (val F1=0.2892)
  Directional -> Accuracy: 0.5116, MCC: 0.0145, F1: 0.3636

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68556 | val 0.69204
  Epoch 016 - train 0.68336 | val 0.69135
  Classification -> best τ=0.515 (val F1=0.2329)
  Directional -> Accuracy: 0.4697, MCC: 0.0731, F1: 0.2553

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73109 | val 0.71850
  Epoch 016 - train 0.72621 | val 0.72256
  Classification -> best τ=0.565 (val F1=0.1822)
  Directional -> Accuracy: 0.4286, MCC: -0.1386, F1: 0.2500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68393 | val 0.70118
  Epoch 019 - train 0.68292 | val 0.70229
  Classification -> best τ=0.465 (val F1=0.2287)
  Directional -> Accuracy: 0.5714, MCC: 0.1309, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68943 | val 0.74175
  Epoch 016 - train 0.71217 | val 0.74562
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.73159 | val 0.67047
  Epoch 016 - train 0.72185 | val 0.67117
  Classification -> best τ=0.440 (val F1=0.2928)
  Directional -> Accuracy: 0.5417, MCC: -0.1826, F1: 0.0833

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70333 | val 0.69876
  Epoch 016 - train 0.71410 | val 0.69939
  Classification -> best τ=0.515 (val F1=0.0910)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71682 | val 0.70876
  Epoch 016 - train 0.70978 | val 0.70949
  Classification -> best τ=0.525 (val F1=0.2169)
  Directional -> Accuracy: 0.4667, MCC: -0.0640, F1: 0.4286

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71346 | val 0.69576
  Epoch 016 - train 0.69302 | val 0.69707
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67819 | val 0.70369
  Epoch 016 - train 0.68710 | val 0.71563
  Classification -> best τ=0.555 (val F1=0.1371)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5172

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69670 | val 0.72820
  Epoch 016 - train 0.71307 | val 0.72647
  Classification -> best τ=0.485 (val F1=0.1407)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69078 | val 0.73117
  Epoch 016 - train 0.70145 | val 0.73118
  Classification -> best τ=0.550 (val F1=0.1970)
  Directional -> Accuracy: 0.5893, MCC: 0.2918, F1: 0.6933

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71334 | val 0.68186
  Epoch 016 - train 0.70979 | val 0.68229
  Classification -> best τ=0.550 (val F1=0.1024)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70565 | val 0.86504
  Epoch 016 - train 0.69323 | val 0.87230
  Classification -> best τ=0.525 (val F1=0.2132)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69145 | val 0.69523

[I 2026-02-20 01:22:47,533] Trial 69 finished with value: 0.1588695079801054 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 2.0831175016097357e-06, 'weight_decay': 0.00015751843986428152, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.8398354779746628, 'early_stopping_min_delta': 0.0034257175858752706}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.70299 | val 0.69849
  Classification -> best τ=0.490 (val F1=0.1941)
  Directional -> Accuracy: 0.5500, MCC: 0.1112, F1: 0.2703

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1588695079801054
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59955 | val 0.73759
  Epoch 011 - train 0.60002 | val 0.75544
  Classification -> best τ=0.530 (val F1=0.2163)
  Directional -> Accuracy: 0.5946, MCC: 0.1652, F1: 0.2857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51886 | val 1.09275
  Epoch 011 - train 0.53352 | val 1.39780
  Classification -> best τ=0.530 (val F1=0.2804)
  Directional -> Accuracy: 0.6279, MCC: 0.1800, F1: 0.7241

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60768 | val 1.04837
  Epoch 014 - train 0.54561 | val 1.86743
  Classification -> best τ=0.695 (val F1=0.3194)
  Directional -> Accuracy: 0.4773, MCC: -0.0099, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67614 | val 0.91042
  Epoch 017 - train 0.58039 | val 2.46514
  Classification -> best τ=0.445 (val F1=0.0271)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43539 | val 2.10605
  Epoch 011 - train 0.39723 | val 2.44789
  Classification -> best τ=0.385 (val F1=0.4266)
  Directional -> Accuracy: 0.7708, MCC: 0.5405, F1: 0.7843

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43889 | val 1.58489
  Epoch 011 - train 0.44166 | val 1.47996
  Classification -> best τ=0.460 (val F1=0.2392)
  Directional -> Accuracy: 0.4773, MCC: -0.0716, F1: 0.1481

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60180 | val 1.07410
  Epoch 012 - train 0.53828 | val 1.64130
  Classification -> best τ=0.615 (val F1=0.1834)
  Directional -> Accuracy: 0.6212, MCC: 0.1824, F1: 0.4444

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50082 | val 0.73737
  Epoch 017 - train 0.39093 | val 1.69718
  Classification -> best τ=0.150 (val F1=0.2928)
  Directional -> Accuracy: 0.4615, MCC: 0.1426, F1: 0.6182

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47364 | val 0.91655
  Epoch 012 - train 0.51192 | val 1.18618
  Classification -> best τ=0.575 (val F1=0.3614)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59556 | val 0.75089
  Epoch 013 - train 0.59796 | val 0.77505
  Classification -> best τ=0.530 (val F1=0.1950)
  Directional -> Accuracy: 0.4925, MCC: 0.0280, F1: 0.5143

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55310 | val 1.81630
  Epoch 011 - train 0.53234 | val 2.13464
  Classification -> best τ=0.665 (val F1=0.2413)
  Directional -> Accuracy: 0.4894, MCC: -0.0237, F1: 0.4545

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58972 | val 1.41404
  Epoch 011 - train 0.55901 | val 1.48317
  Classification -> best τ=0.485 (val F1=0.1908)
  Directional -> Accuracy: 0.6545, MCC: 0.3191, F1: 0.6415

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50642 | val 1.00291
  Epoch 012 - train 0.43533 | val 1.02625
  Classification -> best τ=0.480 (val F1=0.5074)
  Directional -> Accuracy: 0.5000, MCC: 0.0053, F1: 0.5200

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58630 | val 1.06808
  Epoch 011 - train 0.57749 | val 1.10963
  Classification -> best τ=0.505 (val F1=0.3229)
  Directional -> Accuracy: 0.5690, MCC: 0.1344, F1: 0.6377

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61045 | val 1.05167
  Epoch 014 - train 0.57816 | val 1.17389
  Classification -> best τ=0.470 (val F1=0.2670)
  Directional -> Accuracy: 0.4490, MCC: -0.0453, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50957 | val 1.45147
  Epoch 011 - train 0.49275 | val 1.55113
  Classification -> best τ=0.495 (val F1=0.3164)
  Directional -> Accuracy: 0.5970, MCC: 0.2331, F1: 0.7216

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55887 | val 2.17740
  Epoch 011 - train 0.58100 | val 1.83355
  Classification -> best τ=0.690 (val F1=0.1326)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62760 | val 0.73990
  Epoch 014 - train 0.53698 | val 1.24281
  Classification -> best τ=0.430 (val F1=0.1847)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56764 | val 1.42326
  Epoch 011 - train 0.54529 | val 1.36093
  Classification -> best τ=0.595 (val F1=0.2345)
  Directional -> Accuracy: 0.4677, MCC: 0.0966, F1: 0.2326

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55518 | val 0.70883
  Epoch 012 - train 0.51524 | val 0.91378
  Classification -> best τ=0.595 (val F1=0.2982)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56275 | val 0.67755
  Epoch 016 - train 0.46625 | val 0.99854
  Classification -> best τ=0.675 (val F1=0.4775)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58471 | val 1.22265
  Epoch 011 - train 0.57255 | val 1.26770
  Classification -> best τ=0.520 (val F1=0.1500)
  Directional -> Accuracy: 0.4286, MCC: -0.1528, F1: 0.3333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63109 | val 0.93873
  Epoch 014 - train 0.54442 | val 1.18566
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59028 | val 0.73776
  Epoch 020 - train 0.47520 | val 0.76644
  Classification -> best τ=0.335 (val F1=0.2008)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.6207

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54167 | val 0.98005
  Epoch 013 - train 0.42537 | val 1.04956
  Classification -> best τ=0.380 (val F1=0.3975)
  Directional -> Accuracy: 0.5849, MCC: 0.2350, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46775 | val 1.39770
  Epoch 011 - train 0.46129 | val 1.40481
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61561 | val 0.68650
  Epoch 011 - train 0.57439 | val 0.73713
  Classification -> best τ=0.525 (val F1=0.0618)
  Directional -> Accuracy: 0.5417, MCC: 0.1309, F1: 0.5217

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52468 | val 1.04437
  Epoch 011 - train 0.51791 | val 0.93937
  Classification -> best τ=0.505 (val F1=0.3293)
  Directional -> Accuracy: 0.5185, MCC: 0.2252, F1: 0.1875

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44892 | val 2.64983
  Epoch 011 - train 0.49600 | val 3.78867
  Classification -> best τ=0.725 (val F1=0.3333)
  Directional -> Accuracy: 0.5250, MCC: 0.0516, F1: 0.4571

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50798 | val 1.30539
  Epoch 012 - train 0.46524 | val 1.70399
  Classification -> best τ=0.785 (val F1=0.2736)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49168 | val 0.90539
  Epoch 013 - train 0.40659 | val 1.02256
  Classification -> best τ=0.210 (val F1=0.4524)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58944 | val 0.82059
  Epoch 012 - train 0.56733 | val 0.89825
  Classification -> best τ=0.560 (val F1=0.2177)
  Directional -> Accuracy: 0.4429, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60171 | val 0.78343
  Epoch 017 - train 0.38059 | val 0.75431
  Classification -> best τ=0.355 (val F1=0.5222)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49939 | val 1.21240
  Epoch 011 - train 0.52125 | val 1.12579
  Classification -> best τ=0.410 (val F1=0.1852)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48161 | val 3.07535
  Epoch 011 - train 0.42897 | val 3.18350
  Classification -> best τ=0.630 (val F1=0.3837)
  Directional -> Accuracy: 0.5510, MCC: 0.1322, F1: 0.2667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50480 | val 1.50389
  Epoch 011 - train 0.50264 | val 1.60679
  Classification -> best τ=0.385 (val F1=0.2004)
  Directional -> Accuracy: 0.5185, MCC: 0.1372, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39264 | val 2.12672
  Epoch 011 - train 0.39704 | val 2.40424
  Classification -> best τ=0.340 (val F1=0.2146)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49086 | val 1.17984
  Epoch 014 - train 0.43295 | val 1.57017
  Classification -> best τ=0.245 (val F1=0.5899)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52140 | val 2.48084
  Epoch 011 - train 0.54212 | val 2.26968
  Classification -> best τ=0.130 (val F1=0.1961)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46934 | val 0.80997
  Epoch 012 - train 0.42662 | val 0.76037
  Classification -> best τ=0.515 (val F1=0.1981)
  Directional -> Accuracy: 0.5581, MCC: 0.1140, F1: 0.5957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41995 | val 1.03675
  Epoch 017 - train 0.27856 | val 0.76184
  Classification -> best τ=0.295 (val F1=0.3380)
  Directional -> Accuracy: 0.6154, MCC: 0.1479, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41968 | val 1.16592
  Epoch 011 - train 0.41718 | val 1.27926
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61028 | val 1.10302
  Epoch 011 - train 0.57394 | val 1.52321
  Classification -> best τ=0.460 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54950 | val 2.88970
  Epoch 011 - train 0.53935 | val 3.01747
  Classification -> best τ=0.735 (val F1=0.3174)
  Directional -> Accuracy: 0.4815, MCC: -0.0413, F1: 0.3333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59832 | val 1.10095
  Epoch 016 - train 0.50197 | val 1.53127
  Classification -> best τ=0.415 (val F1=0.2777)
  Directional -> Accuracy: 0.5294, MCC: 0.0676, F1: 0.5862

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53021 | val 2.81201
  Epoch 011 - train 0.53148 | val 2.59719
  Classification -> best τ=0.755 (val F1=0.1942)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64477 | val 1.01498

[I 2026-02-20 01:25:34,040] Trial 70 finished with value: 0.2607178835195821 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.007932321635213303, 'weight_decay': 2.76122334888475e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.7335857917407218, 'early_stopping_min_delta': 0.005661216309291334}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 014 - train 0.58070 | val 0.97554
  Classification -> best τ=0.275 (val F1=0.3062)
  Directional -> Accuracy: 0.5000, MCC: 0.1764, F1: 0.6506

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2607178835195821
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66621 | val 0.65221
  Epoch 020 - train 0.55800 | val 0.65512
  Classification -> best τ=0.610 (val F1=0.3366)
  Directional -> Accuracy: 0.5200, MCC: -0.0544, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57039 | val 0.72387
  Epoch 020 - train 0.41172 | val 0.93304
  Epoch 028 - train 0.30808 | val 1.29706
  Classification -> best τ=0.360 (val F1=0.3612)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61755 | val 0.81978
  Epoch 019 - train 0.47990 | val 0.78743
  Classification -> best τ=0.580 (val F1=0.3928)
  Directional -> Accuracy: 0.6667, MCC: 0.3327, F1: 0.6809

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68686 | val 0.91164
  Epoch 020 - train 0.60233 | val 1.83176
  Epoch 022 - train 0.55179 | val 2.07706
  Classification -> best τ=0.425 (val F1=0.1992)
  Directional -> Accuracy: 0.4658, MCC: -0.1157, F1: 0.5806

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52407 | val 2.15998
  Epoch 016 - train 0.38724 | val 3.36702
  Classification -> best τ=0.650 (val F1=0.3933)
  Directional -> Accuracy: 0.4898, MCC: -0.0042, F1: 0.0741

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47035 | val 1.49967
  Epoch 016 - train 0.47317 | val 1.49540
  Classification -> best τ=0.580 (val F1=0.2294)
  Directional -> Accuracy: 0.5778, MCC: 0.2733, F1: 0.2400

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63192 | val 0.91883
  Epoch 016 - train 0.52510 | val 1.35262
  Classification -> best τ=0.595 (val F1=0.1784)
  Directional -> Accuracy: 0.6119, MCC: 0.1287, F1: 0.3158

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50696 | val 1.68634
  Epoch 018 - train 0.39917 | val 1.75924
  Classification -> best τ=0.660 (val F1=0.5164)
  Directional -> Accuracy: 0.4146, MCC: -0.1289, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57694 | val 0.78850
  Epoch 017 - train 0.48672 | val 0.73420
  Classification -> best τ=0.470 (val F1=0.2018)
  Directional -> Accuracy: 0.4681, MCC: -0.0918, F1: 0.3590

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56561 | val 1.75653
  Epoch 016 - train 0.48467 | val 2.18170
  Classification -> best τ=0.415 (val F1=0.1222)
  Directional -> Accuracy: 0.4853, MCC: 0.0872, F1: 0.5882

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57232 | val 1.19893
  Epoch 016 - train 0.52041 | val 0.88572
  Classification -> best τ=0.615 (val F1=0.1883)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61567 | val 0.80896
  Epoch 019 - train 0.44058 | val 1.81032
  Classification -> best τ=0.660 (val F1=0.1792)
  Directional -> Accuracy: 0.7143, MCC: 0.4278, F1: 0.7241

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57548 | val 1.84106
  Epoch 016 - train 0.39596 | val 4.27339
  Classification -> best τ=0.515 (val F1=0.2112)
  Directional -> Accuracy: 0.5306, MCC: 0.0743, F1: 0.2069

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66346 | val 0.65790
  Epoch 016 - train 0.57250 | val 0.77066
  Classification -> best τ=0.460 (val F1=0.3428)
  Directional -> Accuracy: 0.6102, MCC: 0.2423, F1: 0.5306

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59552 | val 1.30823
  Epoch 016 - train 0.51619 | val 1.53923
  Classification -> best τ=0.490 (val F1=0.2550)
  Directional -> Accuracy: 0.5800, MCC: 0.1612, F1: 0.0870

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59577 | val 0.90311
  Epoch 017 - train 0.49041 | val 1.49325
  Classification -> best τ=0.480 (val F1=0.1825)
  Directional -> Accuracy: 0.5441, MCC: 0.0806, F1: 0.5867

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64452 | val 0.83265
  Epoch 018 - train 0.56325 | val 0.82958
  Classification -> best τ=0.500 (val F1=0.0913)
  Directional -> Accuracy: 0.5614, MCC: -0.0224, F1: 0.6914

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65334 | val 0.76176
  Epoch 017 - train 0.58129 | val 0.86007
  Classification -> best τ=0.510 (val F1=0.2701)
  Directional -> Accuracy: 0.5811, MCC: 0.1651, F1: 0.6173

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62547 | val 0.79696
  Epoch 018 - train 0.47072 | val 1.84832
  Classification -> best τ=0.315 (val F1=0.3397)
  Directional -> Accuracy: 0.5556, MCC: 0.1396, F1: 0.5625

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60265 | val 0.98719
  Epoch 016 - train 0.52966 | val 0.95722
  Classification -> best τ=0.270 (val F1=0.1524)
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58749 | val 1.74027
  Epoch 016 - train 0.52237 | val 3.25030
  Classification -> best τ=0.445 (val F1=0.2132)
  Directional -> Accuracy: 0.4348, MCC: 0.1709, F1: 0.1333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61774 | val 2.23192
  Epoch 016 - train 0.56456 | val 3.17333
  Classification -> best τ=0.770 (val F1=0.1476)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56624 | val 2.23904
  Epoch 016 - train 0.46525 | val 2.89238
  Classification -> best τ=0.700 (val F1=0.3495)
  Directional -> Accuracy: 0.5000, MCC: 0.0552, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56010 | val 1.48875
  Epoch 016 - train 0.45171 | val 1.52355
  Classification -> best τ=0.375 (val F1=0.2262)
  Directional -> Accuracy: 0.5312, MCC: 0.1085, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47823 | val 1.56458
  Epoch 016 - train 0.39355 | val 1.74650
  Classification -> best τ=0.525 (val F1=0.4477)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49290 | val 1.39919
  Epoch 016 - train 0.31635 | val 2.62079
  Classification -> best τ=0.475 (val F1=0.3313)
  Directional -> Accuracy: 0.6977, MCC: 0.4132, F1: 0.6829

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59398 | val 1.99220
  Epoch 016 - train 0.51700 | val 2.08609
  Classification -> best τ=0.580 (val F1=0.1463)
  Directional -> Accuracy: 0.5510, MCC: 0.1000, F1: 0.5926

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55075 | val 1.60680
  Epoch 016 - train 0.44555 | val 1.85197
  Classification -> best τ=0.495 (val F1=0.3278)
  Directional -> Accuracy: 0.5818, MCC: 0.2739, F1: 0.4390

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58324 | val 0.68956
  Epoch 020 - train 0.52870 | val 0.90300
  Epoch 026 - train 0.34406 | val 1.50918
  Classification -> best τ=0.410 (val F1=0.2955)
  Directional -> Accuracy: 0.6053, MCC: 0.1858, F1: 0.6809

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58728 | val 5.44481
  Epoch 016 - train 0.50893 | val 6.41153
  Classification -> best τ=0.875 (val F1=0.2193)
  Directional -> Accuracy: 0.4878, MCC: -0.0403, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53846 | val 1.27314
  Epoch 017 - train 0.38186 | val 1.31589
  Classification -> best τ=0.470 (val F1=0.2339)
  Directional -> Accuracy: 0.5366, MCC: -0.0293, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51185 | val 0.82328
  Epoch 020 - train 0.33246 | val 1.32715
  Epoch 023 - train 0.31913 | val 1.40384
  Classification -> best τ=0.665 (val F1=0.3892)
  Directional -> Accuracy: 0.5208, MCC: 0.0087, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59671 | val 0.95708
  Epoch 017 - train 0.50404 | val 1.87183
  Classification -> best τ=0.425 (val F1=0.2510)
  Directional -> Accuracy: 0.5211, MCC: 0.1508, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54713 | val 1.43547
  Epoch 016 - train 0.46310 | val 1.68958
  Classification -> best τ=0.640 (val F1=0.3362)
  Directional -> Accuracy: 0.5476, MCC: 0.0826, F1: 0.3871

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55234 | val 1.15476
  Epoch 020 - train 0.41323 | val 1.18675
  Classification -> best τ=0.130 (val F1=0.2956)
  Directional -> Accuracy: 0.6462, MCC: 0.2641, F1: 0.7416

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51614 | val 0.71007
  Epoch 017 - train 0.42414 | val 0.91193
  Classification -> best τ=0.525 (val F1=0.2520)
  Directional -> Accuracy: 0.6750, MCC: 0.4042, F1: 0.6061

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57396 | val 0.75120
  Epoch 020 - train 0.43993 | val 1.32549
  Classification -> best τ=0.485 (val F1=0.2140)
  Directional -> Accuracy: 0.5273, MCC: 0.0215, F1: 0.3810

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50622 | val 1.33630
  Epoch 016 - train 0.38027 | val 1.47770
  Classification -> best τ=0.645 (val F1=0.3288)
  Directional -> Accuracy: 0.5111, MCC: 0.0061, F1: 0.5769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52816 | val 0.80888
  Epoch 017 - train 0.42794 | val 1.19846
  Classification -> best τ=0.605 (val F1=0.3523)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61859 | val 1.80343
  Epoch 017 - train 0.49487 | val 2.52912
  Classification -> best τ=0.070 (val F1=0.2968)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62526 | val 0.86248
  Epoch 016 - train 0.50127 | val 1.02319
  Classification -> best τ=0.465 (val F1=0.3720)
  Directional -> Accuracy: 0.5682, MCC: 0.1690, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52031 | val 1.31573
  Epoch 018 - train 0.28404 | val 1.64626
  Classification -> best τ=0.345 (val F1=0.3194)
  Directional -> Accuracy: 0.5122, MCC: -0.0627, F1: 0.6296

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53878 | val 1.55445
  Epoch 018 - train 0.35437 | val 1.60774
  Classification -> best τ=0.630 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65122 | val 0.93707
  Epoch 016 - train 0.60390 | val 1.93546
  Classification -> best τ=0.290 (val F1=0.3807)
  Directional -> Accuracy: 0.3704, MCC: -0.2362, F1: 0.2273

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60749 | val 2.18819
  Epoch 020 - train 0.40097 | val 3.19201
  Classification -> best τ=0.715 (val F1=0.4079)
  Directional -> Accuracy: 0.5273, MCC: 0.0531, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66749 | val 0.67319
  Epoch 020 - train 0.57627 | val 0.87013
  Epoch 028 - train 0.44889 | val 1.62482
  Classification -> best τ=0.760 (val F1=0.2376)
  Directional -> Accuracy: 0.5769, MCC: 0.1543, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59079 | val 0.93228
  Epoch 020 - train 0.45275 | val 1.47296
  Epoch 023 - train 0.41339 | val 2.00950
  Classification -> best τ=0.650 (val F1=0.3371)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66836 | val 0.68450
  Epoch 020 - train 0.57537 | val 0.72965

[I 2026-02-20 01:30:19,825] Trial 71 finished with value: 0.2742683181595528 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.009033377839951921, 'weight_decay': 2.770514782118319e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9952878904303168, 'early_stopping_min_delta': 0.0048299067244720675}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 023 - train 0.51242 | val 0.75816
  Classification -> best τ=0.405 (val F1=0.2701)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2742683181595528
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62396 | val 0.88035
  Epoch 020 - train 0.52548 | val 1.12850
  Epoch 023 - train 0.49242 | val 1.16332
  Classification -> best τ=0.500 (val F1=0.2874)
  Directional -> Accuracy: 0.5600, MCC: 0.1244, F1: 0.5479

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61588 | val 0.77691
  Epoch 019 - train 0.43590 | val 1.39381
  Classification -> best τ=0.330 (val F1=0.1902)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61813 | val 0.63762
  Epoch 020 - train 0.47719 | val 0.96914
  Epoch 023 - train 0.45185 | val 1.16168
  Classification -> best τ=0.435 (val F1=0.4951)
  Directional -> Accuracy: 0.4889, MCC: -0.0238, F1: 0.5106

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65883 | val 1.21798
  Epoch 018 - train 0.50357 | val 1.70094
  Classification -> best τ=0.405 (val F1=0.1524)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49775 | val 1.30322
  Epoch 016 - train 0.35344 | val 2.74275
  Classification -> best τ=0.520 (val F1=0.4664)
  Directional -> Accuracy: 0.6122, MCC: 0.2250, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49688 | val 0.79720
  Epoch 020 - train 0.25880 | val 1.62735
  Classification -> best τ=0.465 (val F1=0.2564)
  Directional -> Accuracy: 0.5111, MCC: 0.0391, F1: 0.6071

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64623 | val 0.97765
  Epoch 016 - train 0.53851 | val 1.28797
  Classification -> best τ=0.600 (val F1=0.2426)
  Directional -> Accuracy: 0.5522, MCC: 0.0104, F1: 0.3182

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55257 | val 0.79585
  Epoch 020 - train 0.41895 | val 1.53221
  Epoch 023 - train 0.39446 | val 1.79396
  Classification -> best τ=0.165 (val F1=0.1204)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59465 | val 0.79565
  Epoch 020 - train 0.41216 | val 1.13183
  Classification -> best τ=0.425 (val F1=0.2763)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59884 | val 0.95897
  Epoch 016 - train 0.49586 | val 0.97046
  Classification -> best τ=0.365 (val F1=0.1215)
  Directional -> Accuracy: 0.5147, MCC: 0.1130, F1: 0.5823

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58384 | val 0.86049
  Epoch 016 - train 0.53422 | val 0.90507
  Classification -> best τ=0.600 (val F1=0.2907)
  Directional -> Accuracy: 0.5833, MCC: 0.1555, F1: 0.5238

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53853 | val 1.03114
  Epoch 016 - train 0.51131 | val 1.43564
  Classification -> best τ=0.320 (val F1=0.2067)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51687 | val 5.65348
  Epoch 017 - train 0.38055 | val 7.99148
  Classification -> best τ=0.495 (val F1=0.2788)
  Directional -> Accuracy: 0.4490, MCC: -0.1033, F1: 0.5424

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60993 | val 0.87157
  Epoch 017 - train 0.50753 | val 0.64894
  Classification -> best τ=0.350 (val F1=0.3764)
  Directional -> Accuracy: 0.5254, MCC: 0.0516, F1: 0.6410

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54107 | val 1.37839
  Epoch 016 - train 0.46935 | val 1.90670
  Classification -> best τ=0.710 (val F1=0.0724)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59224 | val 1.25228
  Epoch 016 - train 0.49091 | val 1.41925
  Classification -> best τ=0.440 (val F1=0.3299)
  Directional -> Accuracy: 0.6324, MCC: 0.2722, F1: 0.7126

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62965 | val 1.07670
  Epoch 016 - train 0.55185 | val 1.08328
  Classification -> best τ=0.445 (val F1=0.2894)
  Directional -> Accuracy: 0.3684, MCC: -0.2163, F1: 0.3571

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58184 | val 1.27145
  Epoch 016 - train 0.53922 | val 1.37092
  Classification -> best τ=0.260 (val F1=0.1085)
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55002 | val 1.12228
  Epoch 017 - train 0.47542 | val 1.36289
  Classification -> best τ=0.320 (val F1=0.2503)
  Directional -> Accuracy: 0.5079, MCC: 0.1379, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57830 | val 0.92286
  Epoch 016 - train 0.51659 | val 0.86557
  Classification -> best τ=0.240 (val F1=0.1880)
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55211 | val 1.06224
  Epoch 018 - train 0.48900 | val 1.26566
  Classification -> best τ=0.435 (val F1=0.2689)
  Directional -> Accuracy: 0.4565, MCC: 0.0586, F1: 0.3243

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63464 | val 2.28030
  Epoch 017 - train 0.53806 | val 2.45057
  Classification -> best τ=0.235 (val F1=0.1741)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50974 | val 1.76924
  Epoch 016 - train 0.40878 | val 2.41977
  Classification -> best τ=0.725 (val F1=0.3059)
  Directional -> Accuracy: 0.5179, MCC: 0.1557, F1: 0.3721

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53240 | val 1.36764
  Epoch 017 - train 0.46246 | val 1.86581
  Classification -> best τ=0.435 (val F1=0.1912)
  Directional -> Accuracy: 0.5625, MCC: 0.1088, F1: 0.4167

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50091 | val 1.21470
  Epoch 016 - train 0.37768 | val 1.39200
  Classification -> best τ=0.580 (val F1=0.4889)
  Directional -> Accuracy: 0.5556, MCC: 0.1930, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48140 | val 0.95210
  Epoch 016 - train 0.37093 | val 1.88079
  Classification -> best τ=0.540 (val F1=0.2562)
  Directional -> Accuracy: 0.4651, MCC: -0.0140, F1: 0.5106

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56441 | val 0.70393
  Epoch 016 - train 0.47016 | val 0.69032
  Classification -> best τ=0.535 (val F1=0.2062)
  Directional -> Accuracy: 0.5306, MCC: 0.0983, F1: 0.5306

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53751 | val 2.62300
  Epoch 016 - train 0.44768 | val 2.87544
  Classification -> best τ=0.435 (val F1=0.2203)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50154 | val 1.21960
  Epoch 019 - train 0.40905 | val 1.38366
  Classification -> best τ=0.425 (val F1=0.3708)
  Directional -> Accuracy: 0.5526, MCC: 0.0719, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52520 | val 1.81358
  Epoch 016 - train 0.40210 | val 2.61664
  Classification -> best τ=0.700 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0080, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46682 | val 1.26989
  Epoch 016 - train 0.31908 | val 1.52881
  Classification -> best τ=0.465 (val F1=0.1992)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47856 | val 1.16888
  Epoch 016 - train 0.32926 | val 1.30865
  Classification -> best τ=0.610 (val F1=0.2382)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59096 | val 1.19810
  Epoch 016 - train 0.53490 | val 1.69376
  Classification -> best τ=0.650 (val F1=0.2255)
  Directional -> Accuracy: 0.5493, MCC: 0.1725, F1: 0.4667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56481 | val 1.07243
  Epoch 016 - train 0.45825 | val 1.01490
  Classification -> best τ=0.430 (val F1=0.2765)
  Directional -> Accuracy: 0.5714, MCC: 0.1356, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50980 | val 1.18285
  Epoch 016 - train 0.40886 | val 1.27949
  Classification -> best τ=0.185 (val F1=0.3218)
  Directional -> Accuracy: 0.6000, MCC: 0.2183, F1: 0.6061

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44092 | val 1.33669
  Epoch 016 - train 0.30313 | val 1.58718
  Classification -> best τ=0.495 (val F1=0.2697)
  Directional -> Accuracy: 0.6250, MCC: 0.2950, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53201 | val 0.82948
  Epoch 017 - train 0.41770 | val 1.09910
  Classification -> best τ=0.455 (val F1=0.2494)
  Directional -> Accuracy: 0.4727, MCC: -0.0467, F1: 0.4727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43944 | val 1.06139
  Epoch 016 - train 0.33075 | val 1.04638
  Classification -> best τ=0.525 (val F1=0.2913)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47697 | val 0.97678
  Epoch 016 - train 0.39756 | val 1.13282
  Classification -> best τ=0.515 (val F1=0.4359)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56033 | val 2.34133
  Epoch 017 - train 0.48187 | val 3.94221
  Classification -> best τ=0.065 (val F1=0.2896)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57056 | val 0.91902
  Epoch 016 - train 0.45353 | val 1.17649
  Classification -> best τ=0.500 (val F1=0.3720)
  Directional -> Accuracy: 0.5682, MCC: 0.1575, F1: 0.6545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42447 | val 0.98068
  Epoch 016 - train 0.32701 | val 1.20270
  Classification -> best τ=0.445 (val F1=0.3194)
  Directional -> Accuracy: 0.6585, MCC: 0.2777, F1: 0.7308

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44827 | val 1.42271
  Epoch 016 - train 0.31628 | val 1.75605
  Classification -> best τ=0.445 (val F1=0.2111)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63412 | val 0.86640
  Epoch 016 - train 0.58821 | val 0.75860
  Classification -> best τ=0.515 (val F1=0.1042)
  Directional -> Accuracy: 0.5741, MCC: 0.1908, F1: 0.5306

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58551 | val 1.86216
  Epoch 018 - train 0.44988 | val 2.39060
  Classification -> best τ=0.750 (val F1=0.2946)
  Directional -> Accuracy: 0.5091, MCC: 0.0199, F1: 0.5263

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65173 | val 0.70638
  Epoch 019 - train 0.49052 | val 0.84279
  Classification -> best τ=0.695 (val F1=0.2376)
  Directional -> Accuracy: 0.5769, MCC: 0.1734, F1: 0.6562

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51499 | val 0.90951
  Epoch 017 - train 0.38818 | val 1.03038
  Classification -> best τ=0.600 (val F1=0.2710)
  Directional -> Accuracy: 0.5741, MCC: 0.1657, F1: 0.6849

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57236 | val 0.72263

[I 2026-02-20 01:34:49,027] Trial 72 finished with value: 0.2618940072917085 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.005585712246453475, 'weight_decay': 3.1006891865399193e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9541823114786883, 'early_stopping_min_delta': 0.006138106319362958}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.47179 | val 0.71271
  Classification -> best τ=0.390 (val F1=0.1663)
  Directional -> Accuracy: 0.4746, MCC: -0.0257, F1: 0.5867

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2618940072917085
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60391 | val 0.68555
  Epoch 020 - train 0.50353 | val 0.92235
  Epoch 023 - train 0.46026 | val 0.92089
  Classification -> best τ=0.715 (val F1=0.2989)
  Directional -> Accuracy: 0.5067, MCC: -0.0890, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56837 | val 0.86601
  Epoch 017 - train 0.45577 | val 1.36596
  Classification -> best τ=0.570 (val F1=0.2503)
  Directional -> Accuracy: 0.6136, MCC: 0.1417, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61441 | val 0.98084
  Epoch 016 - train 0.53100 | val 1.11375
  Classification -> best τ=0.635 (val F1=0.2582)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64256 | val 1.41622
  Epoch 016 - train 0.55630 | val 1.63612
  Classification -> best τ=0.345 (val F1=0.1297)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50566 | val 1.47280
  Epoch 016 - train 0.38293 | val 2.47575
  Classification -> best τ=0.500 (val F1=0.4622)
  Directional -> Accuracy: 0.6122, MCC: 0.2732, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49891 | val 1.98997
  Epoch 020 - train 0.34477 | val 1.73078
  Epoch 021 - train 0.32905 | val 2.27902
  Classification -> best τ=0.500 (val F1=0.3241)
  Directional -> Accuracy: 0.4889, MCC: -0.0217, F1: 0.4889

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57417 | val 1.32026
  Epoch 016 - train 0.48782 | val 1.60919
  Classification -> best τ=0.580 (val F1=0.2926)
  Directional -> Accuracy: 0.6119, MCC: 0.1225, F1: 0.2778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54819 | val 1.19554
  Epoch 016 - train 0.46504 | val 2.63695
  Classification -> best τ=0.585 (val F1=0.1741)
  Directional -> Accuracy: 0.5122, MCC: -0.0152, F1: 0.3750

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52909 | val 1.23977
  Epoch 017 - train 0.45878 | val 1.10807
  Classification -> best τ=0.530 (val F1=0.1995)
  Directional -> Accuracy: 0.4681, MCC: 0.1325, F1: 0.6269

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52183 | val 1.49972
  Epoch 016 - train 0.44345 | val 1.74886
  Classification -> best τ=0.495 (val F1=0.0699)
  Directional -> Accuracy: 0.5294, MCC: 0.0295, F1: 0.4286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61292 | val 0.98576
  Epoch 016 - train 0.54500 | val 1.14892
  Classification -> best τ=0.500 (val F1=0.2277)
  Directional -> Accuracy: 0.5833, MCC: 0.1448, F1: 0.4118

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54119 | val 1.33947
  Epoch 016 - train 0.47966 | val 1.51750
  Classification -> best τ=0.340 (val F1=0.2038)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44940 | val 4.59290
  Epoch 016 - train 0.36819 | val 5.53245
  Classification -> best τ=0.305 (val F1=0.2112)
  Directional -> Accuracy: 0.4694, MCC: -0.0661, F1: 0.4091

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65682 | val 0.63694
  Epoch 018 - train 0.54728 | val 0.71914
  Classification -> best τ=0.365 (val F1=0.3346)
  Directional -> Accuracy: 0.6102, MCC: 0.2352, F1: 0.5490

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57071 | val 1.47673
  Epoch 016 - train 0.49640 | val 1.42384
  Classification -> best τ=0.610 (val F1=0.1442)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59499 | val 0.87858
  Epoch 017 - train 0.47625 | val 1.09000
  Classification -> best τ=0.450 (val F1=0.1772)
  Directional -> Accuracy: 0.5294, MCC: 0.0625, F1: 0.5294

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62839 | val 0.74544
  Epoch 020 - train 0.47958 | val 0.99607
  Epoch 026 - train 0.37165 | val 1.14072
  Classification -> best τ=0.395 (val F1=0.3000)
  Directional -> Accuracy: 0.4035, MCC: -0.2382, F1: 0.5000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63756 | val 0.94386
  Epoch 016 - train 0.56627 | val 1.22791
  Classification -> best τ=0.400 (val F1=0.2228)
  Directional -> Accuracy: 0.5946, MCC: 0.1092, F1: 0.7000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57152 | val 1.80962
  Epoch 016 - train 0.49231 | val 2.37706
  Classification -> best τ=0.550 (val F1=0.1883)
  Directional -> Accuracy: 0.3968, MCC: -0.1515, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54176 | val 0.91659
  Epoch 016 - train 0.42984 | val 0.89548
  Classification -> best τ=0.515 (val F1=0.2443)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49574 | val 0.82180
  Epoch 020 - train 0.39854 | val 0.93446
  Epoch 026 - train 0.29511 | val 1.02756
  Classification -> best τ=0.285 (val F1=0.4054)
  Directional -> Accuracy: 0.5217, MCC: 0.1179, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61018 | val 1.55439
  Epoch 016 - train 0.53116 | val 1.80606
  Classification -> best τ=0.410 (val F1=0.1741)
  Directional -> Accuracy: 0.4531, MCC: -0.2218, F1: 0.6237

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54625 | val 2.52773
  Epoch 016 - train 0.41927 | val 2.78336
  Classification -> best τ=0.750 (val F1=0.2474)
  Directional -> Accuracy: 0.5714, MCC: 0.0993, F1: 0.6571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52720 | val 1.17767
  Epoch 016 - train 0.43705 | val 1.11951
  Classification -> best τ=0.290 (val F1=0.2531)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49786 | val 1.63141
  Epoch 016 - train 0.37624 | val 1.84233
  Classification -> best τ=0.580 (val F1=0.4553)
  Directional -> Accuracy: 0.4815, MCC: 0.0266, F1: 0.2222

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48590 | val 2.61186
  Epoch 016 - train 0.40056 | val 2.89020
  Classification -> best τ=0.430 (val F1=0.1809)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56200 | val 0.71478
  Epoch 016 - train 0.50246 | val 0.80559
  Classification -> best τ=0.580 (val F1=0.1343)
  Directional -> Accuracy: 0.5306, MCC: 0.0509, F1: 0.5818

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58393 | val 1.35900
  Epoch 016 - train 0.51709 | val 1.58391
  Classification -> best τ=0.480 (val F1=0.2132)
  Directional -> Accuracy: 0.5818, MCC: 0.2128, F1: 0.7229

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48449 | val 0.79077
  Epoch 016 - train 0.45702 | val 0.80796
  Classification -> best τ=0.560 (val F1=0.2496)
  Directional -> Accuracy: 0.5526, MCC: 0.1241, F1: 0.5405

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49952 | val 2.83669
  Epoch 016 - train 0.35360 | val 4.01657
  Classification -> best τ=0.595 (val F1=0.2193)
  Directional -> Accuracy: 0.4878, MCC: -0.0321, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52571 | val 1.16687
  Epoch 016 - train 0.37092 | val 1.71680
  Classification -> best τ=0.490 (val F1=0.2076)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49496 | val 0.93145
  Epoch 016 - train 0.37064 | val 1.07980
  Classification -> best τ=0.410 (val F1=0.2212)
  Directional -> Accuracy: 0.5833, MCC: 0.1734, F1: 0.5652

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56431 | val 1.01317
  Epoch 016 - train 0.53613 | val 1.44032
  Classification -> best τ=0.515 (val F1=0.2961)
  Directional -> Accuracy: 0.5211, MCC: 0.1508, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56349 | val 0.96689
  Epoch 016 - train 0.44982 | val 1.19890
  Classification -> best τ=0.680 (val F1=0.3363)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56233 | val 0.89416
  Epoch 020 - train 0.36280 | val 1.26288
  Epoch 021 - train 0.33638 | val 1.33599
  Classification -> best τ=0.705 (val F1=0.4198)
  Directional -> Accuracy: 0.4308, MCC: -0.0249, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55590 | val 0.92312
  Epoch 016 - train 0.42713 | val 1.10018
  Classification -> best τ=0.500 (val F1=0.3181)
  Directional -> Accuracy: 0.5750, MCC: 0.2253, F1: 0.4138

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55215 | val 1.17011
  Epoch 019 - train 0.36803 | val 1.51506
  Classification -> best τ=0.420 (val F1=0.2608)
  Directional -> Accuracy: 0.5273, MCC: 0.0828, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41563 | val 1.42596
  Epoch 016 - train 0.31917 | val 1.52426
  Classification -> best τ=0.585 (val F1=0.2608)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55456 | val 1.09385
  Epoch 016 - train 0.46546 | val 1.40934
  Classification -> best τ=0.615 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60453 | val 1.68857
  Epoch 017 - train 0.50002 | val 2.84959
  Classification -> best τ=0.210 (val F1=0.3273)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55062 | val 0.99406
  Epoch 017 - train 0.42803 | val 1.29066
  Classification -> best τ=0.420 (val F1=0.3064)
  Directional -> Accuracy: 0.5909, MCC: 0.2041, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54912 | val 1.33000
  Epoch 016 - train 0.34206 | val 1.83816
  Classification -> best τ=0.500 (val F1=0.2390)
  Directional -> Accuracy: 0.5610, MCC: -0.1331, F1: 0.7188

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46006 | val 1.66407
  Epoch 016 - train 0.34334 | val 1.88572
  Classification -> best τ=0.405 (val F1=0.2111)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62705 | val 1.32966
  Epoch 016 - train 0.57372 | val 1.30039
  Classification -> best τ=0.510 (val F1=0.2649)
  Directional -> Accuracy: 0.3519, MCC: -0.2803, F1: 0.3137

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54832 | val 2.35791
  Epoch 016 - train 0.44903 | val 3.10179
  Classification -> best τ=0.330 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65806 | val 0.68635
  Epoch 020 - train 0.47379 | val 0.76355
  Epoch 025 - train 0.39644 | val 0.85563
  Classification -> best τ=0.560 (val F1=0.2423)
  Directional -> Accuracy: 0.5192, MCC: 0.0444, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58303 | val 1.09364
  Epoch 018 - train 0.30979 | val 0.92833
  Classification -> best τ=0.470 (val F1=0.2570)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.7000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59473 | val 0.76196
  Epoch 020 - train 0.42299 | val 1.19829

[I 2026-02-20 01:39:18,466] Trial 73 finished with value: 0.25739584053841363 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.005454737943491643, 'weight_decay': 1.8204565789990078e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9881033590011532, 'early_stopping_min_delta': 0.0062354047260543026}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 021 - train 0.39010 | val 1.25201
  Classification -> best τ=0.505 (val F1=0.2608)
  Directional -> Accuracy: 0.4576, MCC: -0.0960, F1: 0.3846

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25739584053841363
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64580 | val 0.63029
  Epoch 020 - train 0.53979 | val 0.64954
  Epoch 025 - train 0.50360 | val 0.66037
  Classification -> best τ=0.450 (val F1=0.3714)
  Directional -> Accuracy: 0.5067, MCC: -0.0890, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54167 | val 0.73482
  Epoch 020 - train 0.38199 | val 0.97312
  Epoch 027 - train 0.30536 | val 0.99169
  Classification -> best τ=0.405 (val F1=0.2920)
  Directional -> Accuracy: 0.6364, MCC: 0.2623, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57914 | val 0.95484
  Epoch 016 - train 0.51272 | val 1.24791
  Classification -> best τ=0.575 (val F1=0.3441)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62522 | val 2.95661
  Epoch 016 - train 0.54672 | val 4.40381
  Classification -> best τ=0.375 (val F1=0.1524)
  Directional -> Accuracy: 0.4384, MCC: -0.1192, F1: 0.4384

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49978 | val 4.32309
  Epoch 016 - train 0.37172 | val 4.89075
  Classification -> best τ=0.760 (val F1=0.4473)
  Directional -> Accuracy: 0.5714, MCC: 0.2119, F1: 0.3636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47645 | val 0.76364
  Epoch 020 - train 0.31127 | val 1.32931
  Epoch 024 - train 0.27361 | val 1.09458
  Classification -> best τ=0.395 (val F1=0.3188)
  Directional -> Accuracy: 0.5333, MCC: 0.0764, F1: 0.5882

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66636 | val 0.75572
  Epoch 020 - train 0.50948 | val 1.52606
  Epoch 022 - train 0.47767 | val 1.85636
  Classification -> best τ=0.410 (val F1=0.3259)
  Directional -> Accuracy: 0.5224, MCC: 0.2250, F1: 0.6098

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55511 | val 3.18015
  Epoch 017 - train 0.44028 | val 3.57659
  Classification -> best τ=0.670 (val F1=0.4146)
  Directional -> Accuracy: 0.4390, MCC: -0.0278, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57844 | val 0.98659
  Epoch 016 - train 0.46926 | val 2.31743
  Classification -> best τ=0.610 (val F1=0.2018)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57440 | val 1.13283
  Epoch 016 - train 0.45869 | val 1.94727
  Classification -> best τ=0.480 (val F1=0.1303)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58237 | val 0.78539
  Epoch 020 - train 0.49550 | val 0.99682
  Epoch 029 - train 0.35345 | val 1.70682
  Classification -> best τ=0.335 (val F1=0.1615)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58181 | val 1.23667
  Epoch 016 - train 0.51382 | val 1.74641
  Classification -> best τ=0.485 (val F1=0.2215)
  Directional -> Accuracy: 0.6786, MCC: 0.3633, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52432 | val 1.39744
  Epoch 016 - train 0.34743 | val 2.79890
  Classification -> best τ=0.395 (val F1=0.2223)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61783 | val 0.93162
  Epoch 017 - train 0.47703 | val 1.18389
  Classification -> best τ=0.470 (val F1=0.2763)
  Directional -> Accuracy: 0.5763, MCC: 0.1533, F1: 0.6269

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54881 | val 1.41824
  Epoch 016 - train 0.46976 | val 2.02344
  Classification -> best τ=0.485 (val F1=0.2060)
  Directional -> Accuracy: 0.5000, MCC: -0.0817, F1: 0.2424

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59336 | val 0.91045
  Epoch 017 - train 0.48474 | val 0.81453
  Classification -> best τ=0.335 (val F1=0.4080)
  Directional -> Accuracy: 0.5735, MCC: 0.2279, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61686 | val 0.78124
  Epoch 017 - train 0.51504 | val 0.92547
  Classification -> best τ=0.415 (val F1=0.2739)
  Directional -> Accuracy: 0.4386, MCC: -0.1844, F1: 0.5429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63799 | val 0.75926
  Epoch 016 - train 0.58717 | val 0.98718
  Classification -> best τ=0.410 (val F1=0.1269)
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64740 | val 0.85257
  Epoch 020 - train 0.51292 | val 1.96279
  Epoch 023 - train 0.42013 | val 2.25646
  Classification -> best τ=0.330 (val F1=0.3310)
  Directional -> Accuracy: 0.5556, MCC: 0.0727, F1: 0.6316

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60988 | val 0.80925
  Epoch 017 - train 0.42939 | val 1.37515
  Classification -> best τ=0.405 (val F1=0.3320)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63273 | val 1.09676
  Epoch 020 - train 0.41189 | val 2.54522
  Classification -> best τ=0.465 (val F1=0.3902)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61411 | val 2.47444
  Epoch 016 - train 0.56415 | val 2.94040
  Classification -> best τ=0.445 (val F1=0.2149)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55370 | val 2.10237
  Epoch 016 - train 0.50640 | val 4.07919
  Classification -> best τ=0.540 (val F1=0.2640)
  Directional -> Accuracy: 0.4821, MCC: 0.2060, F1: 0.1714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62385 | val 0.72393
  Epoch 020 - train 0.45012 | val 0.88494
  Epoch 022 - train 0.42730 | val 1.00688
  Classification -> best τ=0.490 (val F1=0.2361)
  Directional -> Accuracy: 0.5000, MCC: 0.0206, F1: 0.5556

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48749 | val 1.55338
  Epoch 017 - train 0.35787 | val 2.11006
  Classification -> best τ=0.540 (val F1=0.4477)
  Directional -> Accuracy: 0.4444, MCC: -0.0991, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38776 | val 1.85763
  Epoch 016 - train 0.30882 | val 3.25519
  Classification -> best τ=0.620 (val F1=0.2381)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57174 | val 0.70872
  Epoch 017 - train 0.42771 | val 0.78788
  Classification -> best τ=0.570 (val F1=0.1824)
  Directional -> Accuracy: 0.5102, MCC: 0.1483, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57166 | val 1.34240
  Epoch 017 - train 0.45561 | val 1.68367
  Classification -> best τ=0.465 (val F1=0.3058)
  Directional -> Accuracy: 0.5273, MCC: 0.2557, F1: 0.2353

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60112 | val 0.72142
  Epoch 020 - train 0.36247 | val 0.70200
  Epoch 027 - train 0.20263 | val 0.80973
  Classification -> best τ=0.400 (val F1=0.2955)
  Directional -> Accuracy: 0.5789, MCC: 0.1186, F1: 0.6923

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52196 | val 4.38841
  Epoch 016 - train 0.40157 | val 4.54267
  Classification -> best τ=0.645 (val F1=0.2193)
  Directional -> Accuracy: 0.5366, MCC: 0.0701, F1: 0.4865

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55079 | val 0.83598
  Epoch 020 - train 0.43713 | val 0.99281
  Epoch 028 - train 0.31505 | val 2.49377
  Classification -> best τ=0.550 (val F1=0.0720)
  Directional -> Accuracy: 0.6829, MCC: 0.4297, F1: 0.6486

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50083 | val 0.85099
  Epoch 016 - train 0.38247 | val 1.13521
  Classification -> best τ=0.570 (val F1=0.2382)
  Directional -> Accuracy: 0.4375, MCC: -0.1180, F1: 0.3415

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57284 | val 0.92673
  Epoch 016 - train 0.49742 | val 1.38425
  Classification -> best τ=0.745 (val F1=0.2622)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55940 | val 0.87427
  Epoch 020 - train 0.33523 | val 1.40863
  Classification -> best τ=0.850 (val F1=0.3363)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56763 | val 0.98102
  Epoch 016 - train 0.43041 | val 1.25635
  Classification -> best τ=0.180 (val F1=0.3828)
  Directional -> Accuracy: 0.5692, MCC: 0.0000, F1: 0.7255

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51978 | val 0.69540
  Epoch 017 - train 0.33395 | val 0.81521
  Classification -> best τ=0.450 (val F1=0.2887)
  Directional -> Accuracy: 0.6750, MCC: 0.3679, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54148 | val 0.87823
  Epoch 017 - train 0.46089 | val 1.09016
  Classification -> best τ=0.435 (val F1=0.2203)
  Directional -> Accuracy: 0.5455, MCC: 0.2064, F1: 0.6479

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48660 | val 1.50632
  Epoch 016 - train 0.34745 | val 2.13373
  Classification -> best τ=0.485 (val F1=0.2951)
  Directional -> Accuracy: 0.5333, MCC: -0.1225, F1: 0.6769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49332 | val 1.10060
  Epoch 016 - train 0.38311 | val 1.73329
  Classification -> best τ=0.520 (val F1=0.3581)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56919 | val 1.00040
  Epoch 017 - train 0.44938 | val 1.29203
  Classification -> best τ=0.320 (val F1=0.2391)
  Directional -> Accuracy: 0.5205, MCC: 0.1171, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54883 | val 1.55235
  Epoch 016 - train 0.45270 | val 1.63372
  Classification -> best τ=0.450 (val F1=0.3064)
  Directional -> Accuracy: 0.5909, MCC: 0.1952, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45255 | val 1.00131
  Epoch 016 - train 0.32290 | val 1.08714
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47672 | val 1.60658
  Epoch 016 - train 0.37575 | val 2.60349
  Classification -> best τ=0.490 (val F1=0.5489)
  Directional -> Accuracy: 0.3913, MCC: 0.1141, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59698 | val 1.15835
  Epoch 016 - train 0.55083 | val 1.99642
  Classification -> best τ=0.385 (val F1=0.2345)
  Directional -> Accuracy: 0.4630, MCC: 0.1229, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55534 | val 1.62879
  Epoch 016 - train 0.47392 | val 2.14892
  Classification -> best τ=0.305 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62314 | val 0.96935
  Epoch 020 - train 0.51201 | val 0.98851
  Epoch 022 - train 0.49821 | val 0.83001
  Classification -> best τ=0.645 (val F1=0.2376)
  Directional -> Accuracy: 0.5192, MCC: 0.0392, F1: 0.4681

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56997 | val 1.32731
  Epoch 016 - train 0.47730 | val 1.82692
  Classification -> best τ=0.355 (val F1=0.2710)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56930 | val 0.70104

[I 2026-02-20 01:44:04,011] Trial 74 finished with value: 0.2748138700190271 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.009765656442226071, 'weight_decay': 3.836889202720403e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9305541828618071, 'early_stopping_min_delta': 0.005251394023433807}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.50102 | val 0.72447
  Classification -> best τ=0.410 (val F1=0.3016)
  Directional -> Accuracy: 0.4576, MCC: -0.0915, F1: 0.4074

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2748138700190271
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65712 | val 0.63701
  Epoch 020 - train 0.54692 | val 0.93856
  Epoch 026 - train 0.48591 | val 0.80845
  Classification -> best τ=0.415 (val F1=0.2989)
  Directional -> Accuracy: 0.5200, MCC: -0.0544, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57503 | val 1.28763
  Epoch 016 - train 0.43748 | val 1.93193
  Classification -> best τ=0.325 (val F1=0.0538)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56323 | val 1.10310
  Epoch 016 - train 0.49185 | val 1.63757
  Classification -> best τ=0.490 (val F1=0.4174)
  Directional -> Accuracy: 0.4667, MCC: -0.0653, F1: 0.4783

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69292 | val 1.13715
  Epoch 019 - train 0.52074 | val 4.09807
  Classification -> best τ=0.350 (val F1=0.1524)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57513 | val 2.14341
  Epoch 016 - train 0.43746 | val 1.98335
  Classification -> best τ=0.730 (val F1=0.4483)
  Directional -> Accuracy: 0.5714, MCC: 0.2119, F1: 0.3636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53816 | val 1.11089
  Epoch 018 - train 0.38473 | val 2.72161
  Classification -> best τ=0.605 (val F1=0.2980)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65578 | val 0.97847
  Epoch 018 - train 0.48092 | val 1.34784
  Classification -> best τ=0.465 (val F1=0.1931)
  Directional -> Accuracy: 0.5672, MCC: 0.1650, F1: 0.5538

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52706 | val 1.71927
  Epoch 019 - train 0.41340 | val 2.52337
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57801 | val 1.10555
  Epoch 017 - train 0.53602 | val 1.07139
  Classification -> best τ=0.545 (val F1=0.2895)
  Directional -> Accuracy: 0.3191, MCC: -0.3571, F1: 0.4286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57982 | val 1.03234
  Epoch 017 - train 0.50597 | val 1.51557
  Classification -> best τ=0.275 (val F1=0.1534)
  Directional -> Accuracy: 0.4118, MCC: -0.1101, F1: 0.5238

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58409 | val 1.57666
  Epoch 016 - train 0.50657 | val 1.07936
  Classification -> best τ=0.375 (val F1=0.1883)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60237 | val 1.07133
  Epoch 017 - train 0.51601 | val 1.65775
  Classification -> best τ=0.710 (val F1=0.2582)
  Directional -> Accuracy: 0.5179, MCC: 0.0565, F1: 0.4000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61220 | val 1.13716
  Epoch 020 - train 0.34683 | val 3.62460
  Classification -> best τ=0.515 (val F1=0.2788)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62868 | val 0.93331
  Epoch 017 - train 0.56922 | val 1.27514
  Classification -> best τ=0.305 (val F1=0.3308)
  Directional -> Accuracy: 0.5593, MCC: 0.1174, F1: 0.5938

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65451 | val 0.68767
  Epoch 020 - train 0.55888 | val 1.18599
  Epoch 025 - train 0.48860 | val 1.30353
  Classification -> best τ=0.620 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60082 | val 0.92298
  Epoch 017 - train 0.50960 | val 0.95103
  Classification -> best τ=0.445 (val F1=0.3277)
  Directional -> Accuracy: 0.5588, MCC: 0.1222, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57387 | val 2.71325
  Epoch 016 - train 0.52045 | val 2.17744
  Classification -> best τ=0.640 (val F1=0.1429)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59822 | val 1.15381
  Epoch 016 - train 0.55330 | val 1.23384
  Classification -> best τ=0.385 (val F1=0.1745)
  Directional -> Accuracy: 0.5811, MCC: 0.0908, F1: 0.6804

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59637 | val 1.11172
  Epoch 016 - train 0.51621 | val 1.12999
  Classification -> best τ=0.600 (val F1=0.2375)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61416 | val 0.97508
  Epoch 016 - train 0.49920 | val 0.92605
  Classification -> best τ=0.570 (val F1=0.3060)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55740 | val 0.82775
  Epoch 020 - train 0.45651 | val 0.83713
  Epoch 023 - train 0.44891 | val 0.71787
  Classification -> best τ=0.295 (val F1=0.3223)
  Directional -> Accuracy: 0.5652, MCC: 0.0309, F1: 0.6774

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63011 | val 1.51586
  Epoch 016 - train 0.54046 | val 2.17648
  Classification -> best τ=0.700 (val F1=0.0674)
  Directional -> Accuracy: 0.5312, MCC: 0.0801, F1: 0.3182

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59172 | val 3.43801
  Epoch 016 - train 0.49444 | val 3.33415
  Classification -> best τ=0.655 (val F1=0.3059)
  Directional -> Accuracy: 0.5714, MCC: 0.1550, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57504 | val 0.87917
  Epoch 018 - train 0.46427 | val 1.48534
  Classification -> best τ=0.280 (val F1=0.1912)
  Directional -> Accuracy: 0.5938, MCC: 0.2130, F1: 0.3158

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51614 | val 1.40461
  Epoch 016 - train 0.37796 | val 1.43117
  Classification -> best τ=0.325 (val F1=0.3764)
  Directional -> Accuracy: 0.4259, MCC: -0.1838, F1: 0.5231

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55112 | val 2.51912
  Epoch 016 - train 0.42257 | val 3.54643
  Classification -> best τ=0.610 (val F1=0.1852)
  Directional -> Accuracy: 0.4884, MCC: 0.0112, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55577 | val 0.75743
  Epoch 018 - train 0.35744 | val 1.11379
  Classification -> best τ=0.530 (val F1=0.0615)
  Directional -> Accuracy: 0.5510, MCC: 0.0852, F1: 0.6071

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61176 | val 0.97758
  Epoch 019 - train 0.42844 | val 2.64775
  Classification -> best τ=0.335 (val F1=0.2859)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.1818

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51036 | val 0.72974
  Epoch 016 - train 0.45375 | val 0.75524
  Classification -> best τ=0.475 (val F1=0.2097)
  Directional -> Accuracy: 0.6316, MCC: 0.2761, F1: 0.7407

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54278 | val 2.60929
  Epoch 016 - train 0.44530 | val 3.67978
  Classification -> best τ=0.625 (val F1=0.2193)
  Directional -> Accuracy: 0.4878, MCC: -0.0216, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56697 | val 1.08854
  Epoch 016 - train 0.41345 | val 2.01544
  Classification -> best τ=0.570 (val F1=0.2339)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51318 | val 0.84823
  Epoch 016 - train 0.45426 | val 0.92814
  Classification -> best τ=0.615 (val F1=0.3892)
  Directional -> Accuracy: 0.3958, MCC: -0.3143, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57551 | val 1.09221
  Epoch 016 - train 0.51651 | val 1.30938
  Classification -> best τ=0.400 (val F1=0.2961)
  Directional -> Accuracy: 0.5775, MCC: 0.1781, F1: 0.5714

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54075 | val 0.95055
  Epoch 016 - train 0.42069 | val 1.51605
  Classification -> best τ=0.370 (val F1=0.3367)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57159 | val 0.90084
  Epoch 017 - train 0.42923 | val 1.32055
  Classification -> best τ=0.110 (val F1=0.3317)
  Directional -> Accuracy: 0.5692, MCC: 0.0000, F1: 0.7255

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49431 | val 0.74545
  Epoch 017 - train 0.32120 | val 1.11647
  Classification -> best τ=0.390 (val F1=0.2582)
  Directional -> Accuracy: 0.7000, MCC: 0.4127, F1: 0.6842

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57014 | val 1.23419
  Epoch 017 - train 0.50839 | val 2.92044
  Classification -> best τ=0.375 (val F1=0.2089)
  Directional -> Accuracy: 0.4364, MCC: -0.1144, F1: 0.4561

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56602 | val 0.70371
  Epoch 020 - train 0.38879 | val 1.20167
  Epoch 025 - train 0.28495 | val 1.61481
  Classification -> best τ=0.515 (val F1=0.3050)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49148 | val 2.05071
  Epoch 016 - train 0.38802 | val 2.12235
  Classification -> best τ=0.635 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61647 | val 0.95687
  Epoch 018 - train 0.53182 | val 1.53489
  Classification -> best τ=0.365 (val F1=0.2963)
  Directional -> Accuracy: 0.5068, MCC: 0.0294, F1: 0.6250

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59151 | val 0.75671
  Epoch 016 - train 0.49599 | val 0.91286
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47622 | val 1.30142
  Epoch 016 - train 0.34506 | val 1.90179
  Classification -> best τ=0.275 (val F1=0.2548)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49091 | val 1.61326
  Epoch 016 - train 0.42481 | val 2.35325
  Classification -> best τ=0.555 (val F1=0.5489)
  Directional -> Accuracy: 0.6304, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64349 | val 1.19346
  Epoch 016 - train 0.61573 | val 2.75415
  Classification -> best τ=0.475 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53692 | val 2.30380
  Epoch 016 - train 0.44858 | val 3.22760
  Classification -> best τ=0.800 (val F1=0.3306)
  Directional -> Accuracy: 0.5455, MCC: 0.1183, F1: 0.6377

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64715 | val 0.67184
  Epoch 020 - train 0.52955 | val 0.91819
  Epoch 025 - train 0.43599 | val 0.99256
  Classification -> best τ=0.590 (val F1=0.2037)
  Directional -> Accuracy: 0.5577, MCC: 0.1332, F1: 0.6462

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57090 | val 2.88665
  Epoch 016 - train 0.48936 | val 3.52582
  Classification -> best τ=0.280 (val F1=0.2011)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61236 | val 1.29630

[I 2026-02-20 01:48:42,759] Trial 75 finished with value: 0.2532587306502678 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.00993226636288596, 'weight_decay': 1.070850679152459e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9381822870721617, 'early_stopping_min_delta': 0.004782013395921217}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.60677 | val 1.32235
  Classification -> best τ=0.450 (val F1=0.2987)
  Directional -> Accuracy: 0.4915, MCC: 0.0012, F1: 0.5588

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2532587306502678
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65352 | val 0.83384
  Epoch 020 - train 0.54539 | val 0.73309
  Epoch 024 - train 0.52566 | val 0.84345
  Classification -> best τ=0.795 (val F1=0.3286)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57380 | val 0.74215
  Epoch 017 - train 0.42634 | val 0.82023
  Classification -> best τ=0.360 (val F1=0.1591)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63642 | val 0.73268
  Epoch 020 - train 0.48008 | val 1.17821
  Classification -> best τ=0.660 (val F1=0.3482)
  Directional -> Accuracy: 0.5000, MCC: 0.0766, F1: 0.1481

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60423 | val 2.60873
  Epoch 016 - train 0.58047 | val 2.87108
  Classification -> best τ=0.450 (val F1=0.0683)
  Directional -> Accuracy: 0.5676, MCC: 0.1194, F1: 0.6279

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54219 | val 0.71158
  Epoch 017 - train 0.38592 | val 0.81535
  Classification -> best τ=0.645 (val F1=0.4602)
  Directional -> Accuracy: 0.5800, MCC: 0.2723, F1: 0.3636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45178 | val 0.72697
  Epoch 016 - train 0.35999 | val 0.94373
  Classification -> best τ=0.585 (val F1=0.1085)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61644 | val 0.95688
  Epoch 017 - train 0.49052 | val 1.65949
  Classification -> best τ=0.425 (val F1=0.2823)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47402 | val 1.91541
  Epoch 016 - train 0.30179 | val 1.45158
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49228 | val 1.87582
  Epoch 016 - train 0.43119 | val 2.50689
  Classification -> best τ=0.615 (val F1=0.3441)
  Directional -> Accuracy: 0.6667, MCC: 0.3130, F1: 0.5294

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54101 | val 0.82655
  Epoch 016 - train 0.42609 | val 1.14303
  Classification -> best τ=0.560 (val F1=0.1607)
  Directional -> Accuracy: 0.5217, MCC: -0.0054, F1: 0.3774

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61525 | val 0.70501
  Epoch 017 - train 0.54333 | val 0.92814
  Classification -> best τ=0.495 (val F1=0.1576)
  Directional -> Accuracy: 0.5510, MCC: 0.1091, F1: 0.5417

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57385 | val 2.65901
  Epoch 019 - train 0.44909 | val 2.30308
  Classification -> best τ=0.470 (val F1=0.2667)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50192 | val 1.18861
  Epoch 020 - train 0.31902 | val 0.90290
  Epoch 022 - train 0.25800 | val 0.89386
  Classification -> best τ=0.585 (val F1=0.3133)
  Directional -> Accuracy: 0.4524, MCC: -0.0677, F1: 0.5106

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68822 | val 0.65839
  Epoch 020 - train 0.57208 | val 0.81942
  Epoch 022 - train 0.50294 | val 0.77704
  Classification -> best τ=0.300 (val F1=0.3838)
  Directional -> Accuracy: 0.5833, MCC: 0.1849, F1: 0.6575

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51580 | val 0.97116
  Epoch 016 - train 0.43205 | val 0.77489
  Classification -> best τ=0.395 (val F1=0.1925)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60220 | val 1.02102
  Epoch 020 - train 0.37194 | val 1.16050
  Classification -> best τ=0.460 (val F1=0.2341)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6737

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59509 | val 1.38499
  Epoch 016 - train 0.49854 | val 1.76436
  Classification -> best τ=0.475 (val F1=0.0980)
  Directional -> Accuracy: 0.6379, MCC: 0.1397, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59299 | val 0.97726
  Epoch 016 - train 0.55037 | val 1.20849
  Classification -> best τ=0.430 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61132 | val 0.73639
  Epoch 017 - train 0.47616 | val 1.41644
  Classification -> best τ=0.525 (val F1=0.2234)
  Directional -> Accuracy: 0.4375, MCC: 0.0398, F1: 0.1000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50903 | val 1.18370
  Epoch 016 - train 0.42196 | val 1.26396
  Classification -> best τ=0.535 (val F1=0.3495)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61780 | val 0.83646
  Epoch 020 - train 0.43508 | val 0.71961
  Epoch 021 - train 0.43486 | val 0.72481
  Classification -> best τ=0.405 (val F1=0.3262)
  Directional -> Accuracy: 0.5532, MCC: -0.0837, F1: 0.6957

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62700 | val 1.19621
  Epoch 016 - train 0.58245 | val 1.50707
  Classification -> best τ=0.465 (val F1=0.2281)
  Directional -> Accuracy: 0.4154, MCC: -0.1687, F1: 0.4062

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54765 | val 0.88395
  Epoch 019 - train 0.26963 | val 1.46686
  Classification -> best τ=0.520 (val F1=0.3304)
  Directional -> Accuracy: 0.4386, MCC: -0.1400, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56753 | val 1.05548
  Epoch 017 - train 0.42172 | val 1.89168
  Classification -> best τ=0.530 (val F1=0.0722)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47619 | val 1.60842
  Epoch 016 - train 0.34148 | val 2.41387
  Classification -> best τ=0.345 (val F1=0.3105)
  Directional -> Accuracy: 0.5818, MCC: 0.1491, F1: 0.6349

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44077 | val 2.91005
  Epoch 016 - train 0.26974 | val 3.47635
  Classification -> best τ=0.650 (val F1=0.3039)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60084 | val 0.73206
  Epoch 016 - train 0.56611 | val 0.84071
  Classification -> best τ=0.595 (val F1=0.1005)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51358 | val 1.62648
  Epoch 016 - train 0.40990 | val 2.35705
  Classification -> best τ=0.385 (val F1=0.1860)
  Directional -> Accuracy: 0.5714, MCC: 0.1502, F1: 0.7209

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50829 | val 1.26352
  Epoch 016 - train 0.35535 | val 1.84352
  Classification -> best τ=0.595 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62211 | val 0.92188
  Epoch 020 - train 0.31826 | val 0.89442
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.5238, MCC: 0.0455, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58362 | val 0.77127
  Epoch 016 - train 0.49052 | val 0.87122
  Classification -> best τ=0.450 (val F1=0.1425)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46727 | val 0.97375
  Epoch 016 - train 0.32879 | val 1.28130
  Classification -> best τ=0.460 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61135 | val 0.95354
  Epoch 016 - train 0.54195 | val 1.15915
  Classification -> best τ=0.640 (val F1=0.2831)
  Directional -> Accuracy: 0.4306, MCC: -0.1327, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53467 | val 0.90392
  Epoch 016 - train 0.39146 | val 1.24949
  Classification -> best τ=0.720 (val F1=0.2151)
  Directional -> Accuracy: 0.4884, MCC: -0.0641, F1: 0.1538

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54420 | val 1.08106
  Epoch 016 - train 0.44387 | val 1.29019
  Classification -> best τ=0.420 (val F1=0.3814)
  Directional -> Accuracy: 0.6364, MCC: 0.2631, F1: 0.6757

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39271 | val 0.98441
  Epoch 016 - train 0.25967 | val 1.18974
  Classification -> best τ=0.480 (val F1=0.2439)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53102 | val 0.78028
  Epoch 017 - train 0.34785 | val 1.20095
  Classification -> best τ=0.345 (val F1=0.1949)
  Directional -> Accuracy: 0.5000, MCC: 0.1192, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46580 | val 1.21602
  Epoch 017 - train 0.25147 | val 1.58057
  Classification -> best τ=0.340 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49576 | val 1.08279
  Epoch 016 - train 0.41607 | val 1.43791
  Classification -> best τ=0.590 (val F1=0.4306)
  Directional -> Accuracy: 0.4167, MCC: 0.0209, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59412 | val 1.23636
  Epoch 020 - train 0.39733 | val 1.10977
  Epoch 028 - train 0.28806 | val 1.29527
  Classification -> best τ=0.320 (val F1=0.3805)
  Directional -> Accuracy: 0.4865, MCC: -0.0211, F1: 0.5366

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54844 | val 0.98408
  Epoch 017 - train 0.36243 | val 1.71148
  Classification -> best τ=0.520 (val F1=0.2874)
  Directional -> Accuracy: 0.5111, MCC: 0.0445, F1: 0.3125

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45680 | val 1.64947
  Epoch 016 - train 0.34730 | val 1.81421
  Classification -> best τ=0.455 (val F1=0.2408)
  Directional -> Accuracy: 0.5000, MCC: -0.2402, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41267 | val 0.83315
  Epoch 016 - train 0.26831 | val 0.94113
  Classification -> best τ=0.660 (val F1=0.2464)
  Directional -> Accuracy: 0.6250, MCC: 0.0976, F1: 0.2500

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62565 | val 0.92987
  Epoch 018 - train 0.50329 | val 1.04260
  Classification -> best τ=0.540 (val F1=0.2132)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48618 | val 1.93246
  Epoch 016 - train 0.38560 | val 1.87392
  Classification -> best τ=0.740 (val F1=0.2143)
  Directional -> Accuracy: 0.5714, MCC: 0.1518, F1: 0.6000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61570 | val 1.02439
  Epoch 016 - train 0.51076 | val 1.78249
  Classification -> best τ=0.545 (val F1=0.1813)
  Directional -> Accuracy: 0.5849, MCC: 0.1704, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45657 | val 4.09172
  Epoch 016 - train 0.36649 | val 3.15609
  Classification -> best τ=0.755 (val F1=0.1957)
  Directional -> Accuracy: 0.5455, MCC: 0.0743, F1: 0.6377

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62470 | val 0.68113

[I 2026-02-20 01:52:36,240] Trial 76 finished with value: 0.2492209978456801 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.006995388168462506, 'weight_decay': 8.945893228584227e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.8827380228243085, 'early_stopping_min_delta': 0.005271614590697042}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 017 - train 0.48996 | val 0.80382
  Classification -> best τ=0.490 (val F1=0.2790)
  Directional -> Accuracy: 0.5333, MCC: 0.0641, F1: 0.2222

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2492209978456801
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66031 | val 0.92390
  Epoch 017 - train 0.61109 | val 1.10353
  Classification -> best τ=0.485 (val F1=0.2578)
  Directional -> Accuracy: 0.5867, MCC: 0.1467, F1: 0.3922

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55452 | val 0.71909
  Epoch 017 - train 0.48943 | val 1.81687
  Classification -> best τ=0.430 (val F1=0.0721)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61300 | val 0.77309
  Epoch 016 - train 0.56327 | val 0.80023
  Classification -> best τ=0.505 (val F1=0.2673)
  Directional -> Accuracy: 0.4889, MCC: 0.0714, F1: 0.1481

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68187 | val 0.69876
  Epoch 020 - train 0.64134 | val 1.49910
  Epoch 021 - train 0.63601 | val 1.47514
  Classification -> best τ=0.440 (val F1=0.1848)
  Directional -> Accuracy: 0.4658, MCC: -0.1012, F1: 0.5618

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53184 | val 1.09195
  Epoch 018 - train 0.38701 | val 1.73888
  Classification -> best τ=0.545 (val F1=0.3842)
  Directional -> Accuracy: 0.5510, MCC: 0.1013, F1: 0.6207

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56174 | val 0.78240
  Epoch 020 - train 0.39308 | val 0.95947
  Classification -> best τ=0.545 (val F1=0.3241)
  Directional -> Accuracy: 0.4889, MCC: -0.0165, F1: 0.5490

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61318 | val 1.08457
  Epoch 017 - train 0.51980 | val 1.11221
  Classification -> best τ=0.505 (val F1=0.1793)
  Directional -> Accuracy: 0.6119, MCC: 0.1355, F1: 0.3500

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53594 | val 1.78537
  Epoch 016 - train 0.46672 | val 1.87531
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55849 | val 1.15987
  Epoch 016 - train 0.52061 | val 1.24690
  Classification -> best τ=0.475 (val F1=0.1017)
  Directional -> Accuracy: 0.3617, MCC: -0.2589, F1: 0.4643

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56041 | val 1.23843
  Epoch 016 - train 0.50420 | val 1.20210
  Classification -> best τ=0.455 (val F1=0.1846)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59639 | val 2.03458
  Epoch 016 - train 0.52937 | val 1.36971
  Classification -> best τ=0.540 (val F1=0.2335)
  Directional -> Accuracy: 0.5000, MCC: -0.0296, F1: 0.3684

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58661 | val 1.33956
  Epoch 016 - train 0.51496 | val 1.81761
  Classification -> best τ=0.485 (val F1=0.1448)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49714 | val 6.12521
  Epoch 016 - train 0.44121 | val 7.37669
  Classification -> best τ=0.450 (val F1=0.2094)
  Directional -> Accuracy: 0.4694, MCC: -0.0691, F1: 0.3810

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64037 | val 0.63551
  Epoch 018 - train 0.60208 | val 0.62410
  Classification -> best τ=0.305 (val F1=0.3098)
  Directional -> Accuracy: 0.5763, MCC: 0.2300, F1: 0.6988

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58768 | val 1.29708
  Epoch 016 - train 0.53298 | val 1.57068
  Classification -> best τ=0.550 (val F1=0.0200)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55100 | val 1.07400
  Epoch 016 - train 0.48790 | val 1.31686
  Classification -> best τ=0.435 (val F1=0.3005)
  Directional -> Accuracy: 0.5588, MCC: 0.1846, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58888 | val 1.31128
  Epoch 016 - train 0.55995 | val 1.32741
  Classification -> best τ=0.550 (val F1=0.0529)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61329 | val 1.31744
  Epoch 016 - train 0.54045 | val 1.95896
  Classification -> best τ=0.450 (val F1=0.2246)
  Directional -> Accuracy: 0.5811, MCC: 0.0418, F1: 0.7103

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58915 | val 1.11073
  Epoch 016 - train 0.52188 | val 1.45714
  Classification -> best τ=0.540 (val F1=0.1853)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57475 | val 0.84297
  Epoch 017 - train 0.48979 | val 0.75107
  Classification -> best τ=0.460 (val F1=0.2443)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57463 | val 1.85374
  Epoch 016 - train 0.56822 | val 1.76262
  Classification -> best τ=0.525 (val F1=0.0912)
  Directional -> Accuracy: 0.5435, MCC: -0.0086, F1: 0.6557

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59299 | val 1.28820
  Epoch 016 - train 0.53381 | val 1.43753
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55645 | val 2.16767
  Epoch 016 - train 0.48093 | val 3.36803
  Classification -> best τ=0.520 (val F1=0.2640)
  Directional -> Accuracy: 0.5714, MCC: 0.0833, F1: 0.6757

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57271 | val 1.12814
  Epoch 020 - train 0.45061 | val 1.32250
  Classification -> best τ=0.420 (val F1=0.2106)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52942 | val 1.38556
  Epoch 017 - train 0.48410 | val 1.58087
  Classification -> best τ=0.500 (val F1=0.4193)
  Directional -> Accuracy: 0.4444, MCC: -0.0878, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50353 | val 1.69824
  Epoch 016 - train 0.47831 | val 1.47025
  Classification -> best τ=0.535 (val F1=0.0602)
  Directional -> Accuracy: 0.5349, MCC: -0.0208, F1: 0.2857

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61161 | val 0.74987
  Epoch 016 - train 0.55228 | val 0.88268
  Classification -> best τ=0.530 (val F1=0.0425)
  Directional -> Accuracy: 0.4286, MCC: -0.0350, F1: 0.2632

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55504 | val 1.16505
  Epoch 016 - train 0.52146 | val 1.44255
  Classification -> best τ=0.465 (val F1=0.1682)
  Directional -> Accuracy: 0.5636, MCC: 0.1491, F1: 0.7143

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57336 | val 0.73347
  Epoch 019 - train 0.49834 | val 0.69390
  Classification -> best τ=0.500 (val F1=0.2496)
  Directional -> Accuracy: 0.3947, MCC: -0.1858, F1: 0.3030

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57140 | val 3.58589
  Epoch 016 - train 0.45748 | val 2.95017
  Classification -> best τ=0.535 (val F1=0.3922)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56580 | val 0.93604
  Epoch 016 - train 0.48091 | val 1.31189
  Classification -> best τ=0.500 (val F1=0.1992)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48935 | val 1.02208
  Epoch 016 - train 0.41590 | val 1.08456
  Classification -> best τ=0.515 (val F1=0.2949)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55971 | val 1.02410
  Epoch 017 - train 0.51763 | val 1.40226
  Classification -> best τ=0.325 (val F1=0.3439)
  Directional -> Accuracy: 0.5070, MCC: 0.0831, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57427 | val 1.06901
  Epoch 016 - train 0.49449 | val 1.11095
  Classification -> best τ=0.530 (val F1=0.3124)
  Directional -> Accuracy: 0.6429, MCC: 0.2919, F1: 0.6512

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54241 | val 1.03155
  Epoch 016 - train 0.46039 | val 1.05641
  Classification -> best τ=0.355 (val F1=0.3828)
  Directional -> Accuracy: 0.6000, MCC: 0.1776, F1: 0.6579

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51115 | val 0.95381
  Epoch 016 - train 0.41091 | val 0.96615
  Classification -> best τ=0.535 (val F1=0.2582)
  Directional -> Accuracy: 0.6000, MCC: 0.1949, F1: 0.6364

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55449 | val 0.96740
  Epoch 016 - train 0.51543 | val 1.13673
  Classification -> best τ=0.485 (val F1=0.2494)
  Directional -> Accuracy: 0.4364, MCC: -0.1093, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44801 | val 2.38954
  Epoch 016 - train 0.42597 | val 2.37971
  Classification -> best τ=0.545 (val F1=0.2030)
  Directional -> Accuracy: 0.6000, MCC: 0.0450, F1: 0.7273

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52524 | val 0.90888
  Epoch 019 - train 0.40642 | val 1.06296
  Classification -> best τ=0.655 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53792 | val 1.91631
  Epoch 016 - train 0.49478 | val 2.54036
  Classification -> best τ=0.380 (val F1=0.2282)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56349 | val 0.77503
  Epoch 016 - train 0.50891 | val 0.84645
  Classification -> best τ=0.495 (val F1=0.2843)
  Directional -> Accuracy: 0.5455, MCC: 0.0925, F1: 0.5833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48935 | val 0.88220
  Epoch 016 - train 0.40230 | val 1.07070
  Classification -> best τ=0.530 (val F1=0.1512)
  Directional -> Accuracy: 0.6098, MCC: 0.1713, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47939 | val 1.33570
  Epoch 016 - train 0.40186 | val 1.30592
  Classification -> best τ=0.500 (val F1=0.1942)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66038 | val 0.97135
  Epoch 016 - train 0.60924 | val 1.06417
  Classification -> best τ=0.470 (val F1=0.1685)
  Directional -> Accuracy: 0.3519, MCC: -0.2907, F1: 0.3636

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56358 | val 2.48151
  Epoch 016 - train 0.51286 | val 2.11846
  Classification -> best τ=0.455 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63680 | val 0.93441
  Epoch 016 - train 0.55843 | val 0.94577
  Classification -> best τ=0.495 (val F1=0.0709)
  Directional -> Accuracy: 0.5385, MCC: 0.1443, F1: 0.6757

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52302 | val 1.18905
  Epoch 016 - train 0.47291 | val 1.13811
  Classification -> best τ=0.575 (val F1=0.2397)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60775 | val 1.03687

[I 2026-02-20 01:57:17,884] Trial 77 finished with value: 0.2171216521709282 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.003573487556202364, 'weight_decay': 3.4729638896257153e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9166282862802329, 'early_stopping_min_delta': 0.004984180907100791}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 017 - train 0.54412 | val 1.21614
  Classification -> best τ=0.510 (val F1=0.3830)
  Directional -> Accuracy: 0.5763, MCC: 0.1651, F1: 0.6032

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2171216521709282
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62562 | val 0.78847
  Epoch 018 - train 0.47032 | val 1.07705
  Classification -> best τ=0.640 (val F1=0.2895)
  Directional -> Accuracy: 0.5405, MCC: 0.1005, F1: 0.5526

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57698 | val 0.84044
  Epoch 017 - train 0.48531 | val 1.64988
  Classification -> best τ=0.455 (val F1=0.2549)
  Directional -> Accuracy: 0.6279, MCC: 0.1520, F1: 0.7576

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56543 | val 1.35836
  Epoch 017 - train 0.47369 | val 1.78145
  Classification -> best τ=0.430 (val F1=0.3458)
  Directional -> Accuracy: 0.5000, MCC: -0.0333, F1: 0.6207

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64321 | val 2.25623
  Epoch 016 - train 0.55463 | val 4.01690
  Classification -> best τ=0.355 (val F1=0.0933)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49170 | val 1.09599
  Epoch 016 - train 0.38796 | val 1.58856
  Classification -> best τ=0.420 (val F1=0.3239)
  Directional -> Accuracy: 0.6875, MCC: 0.4321, F1: 0.7619

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43602 | val 3.12171
  Epoch 016 - train 0.38286 | val 4.13576
  Classification -> best τ=0.485 (val F1=0.2392)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6071

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61354 | val 0.79261
  Epoch 016 - train 0.50756 | val 1.11883
  Classification -> best τ=0.445 (val F1=0.1316)
  Directional -> Accuracy: 0.5303, MCC: 0.1636, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50903 | val 1.23047
  Epoch 016 - train 0.46660 | val 1.50133
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58241 | val 1.53402
  Epoch 017 - train 0.44072 | val 1.98472
  Classification -> best τ=0.545 (val F1=0.3780)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57095 | val 0.73407
  Epoch 020 - train 0.44314 | val 0.78523
  Classification -> best τ=0.410 (val F1=0.1367)
  Directional -> Accuracy: 0.4478, MCC: 0.1486, F1: 0.6022

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58396 | val 2.41943
  Epoch 016 - train 0.44851 | val 3.12533
  Classification -> best τ=0.595 (val F1=0.3005)
  Directional -> Accuracy: 0.6383, MCC: 0.2762, F1: 0.4138

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55966 | val 1.83852
  Epoch 016 - train 0.45575 | val 1.59915
  Classification -> best τ=0.455 (val F1=0.0546)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54916 | val 1.09477
  Epoch 017 - train 0.42061 | val 1.07782
  Classification -> best τ=0.395 (val F1=0.4366)
  Directional -> Accuracy: 0.4583, MCC: -0.0723, F1: 0.5517

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64556 | val 1.26207
  Epoch 016 - train 0.52805 | val 1.56821
  Classification -> best τ=0.465 (val F1=0.3174)
  Directional -> Accuracy: 0.5690, MCC: 0.1386, F1: 0.6575

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57395 | val 0.87789
  Epoch 020 - train 0.53782 | val 0.91593
  Epoch 030 - train 0.32055 | val 0.82925
  Classification -> best τ=0.680 (val F1=0.2630)
  Directional -> Accuracy: 0.4286, MCC: -0.1081, F1: 0.5172

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54834 | val 1.48660
  Epoch 016 - train 0.43482 | val 1.82189
  Classification -> best τ=0.435 (val F1=0.2735)
  Directional -> Accuracy: 0.5970, MCC: 0.2331, F1: 0.7216

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60401 | val 2.15145
  Epoch 016 - train 0.48609 | val 4.05418
  Classification -> best τ=0.340 (val F1=0.1204)
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57784 | val 1.49739
  Epoch 016 - train 0.49191 | val 1.91110
  Classification -> best τ=0.370 (val F1=0.1501)
  Directional -> Accuracy: 0.3836, MCC: -0.2009, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59064 | val 1.79255
  Epoch 016 - train 0.46608 | val 2.10445
  Classification -> best τ=0.295 (val F1=0.1726)
  Directional -> Accuracy: 0.5161, MCC: 0.0598, F1: 0.5161

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54493 | val 0.79779
  Epoch 019 - train 0.44221 | val 0.79338
  Classification -> best τ=0.405 (val F1=0.2548)
  Directional -> Accuracy: 0.5694, MCC: 0.0951, F1: 0.6737

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49231 | val 1.81073
  Epoch 016 - train 0.38293 | val 1.95979
  Classification -> best τ=0.400 (val F1=0.1700)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61675 | val 1.67428
  Epoch 016 - train 0.52187 | val 1.80900
  Classification -> best τ=0.550 (val F1=0.2694)
  Directional -> Accuracy: 0.5397, MCC: 0.0938, F1: 0.2927

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59619 | val 1.04153
  Epoch 016 - train 0.47674 | val 1.13367
  Classification -> best τ=0.605 (val F1=0.1800)
  Directional -> Accuracy: 0.4909, MCC: 0.1784, F1: 0.2632

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55253 | val 0.83073
  Epoch 016 - train 0.49214 | val 0.83006
  Classification -> best τ=0.325 (val F1=0.2252)
  Directional -> Accuracy: 0.4921, MCC: 0.0337, F1: 0.6279

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51504 | val 1.30384
  Epoch 016 - train 0.41749 | val 1.47791
  Classification -> best τ=0.510 (val F1=0.5115)
  Directional -> Accuracy: 0.5472, MCC: 0.2095, F1: 0.3684

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54694 | val 1.53969
  Epoch 016 - train 0.43854 | val 1.97545
  Classification -> best τ=0.505 (val F1=0.2417)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57346 | val 0.86054
  Epoch 016 - train 0.51780 | val 1.62679
  Classification -> best τ=0.485 (val F1=0.1928)
  Directional -> Accuracy: 0.5417, MCC: 0.0436, F1: 0.6207

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61136 | val 1.02706
  Epoch 016 - train 0.48152 | val 1.34780
  Classification -> best τ=0.505 (val F1=0.2410)
  Directional -> Accuracy: 0.4815, MCC: 0.1275, F1: 0.0667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49768 | val 2.17897
  Epoch 016 - train 0.39549 | val 3.13096
  Classification -> best τ=0.610 (val F1=0.4152)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52229 | val 1.26667
  Epoch 016 - train 0.43635 | val 1.57451
  Classification -> best τ=0.535 (val F1=0.1300)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49329 | val 0.85170
  Epoch 017 - train 0.36398 | val 0.92658
  Classification -> best τ=0.415 (val F1=0.3780)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59224 | val 1.12311
  Epoch 016 - train 0.47309 | val 0.97571
  Classification -> best τ=0.440 (val F1=0.2904)
  Directional -> Accuracy: 0.5429, MCC: 0.1852, F1: 0.4074

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50634 | val 1.23090
  Epoch 016 - train 0.42770 | val 0.99077
  Classification -> best τ=0.375 (val F1=0.3015)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51655 | val 0.81499
  Epoch 016 - train 0.46596 | val 1.02741
  Classification -> best τ=0.225 (val F1=0.3397)
  Directional -> Accuracy: 0.5938, MCC: 0.1489, F1: 0.6829

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44224 | val 1.82053
  Epoch 016 - train 0.35757 | val 1.84492
  Classification -> best τ=0.525 (val F1=0.3231)
  Directional -> Accuracy: 0.6531, MCC: 0.3095, F1: 0.6047

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54140 | val 1.40421
  Epoch 016 - train 0.44150 | val 1.79880
  Classification -> best τ=0.520 (val F1=0.2280)
  Directional -> Accuracy: 0.5000, MCC: 0.0263, F1: 0.5574

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43522 | val 3.10142
  Epoch 016 - train 0.32399 | val 2.64086
  Classification -> best τ=0.515 (val F1=0.3153)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55243 | val 1.38716
  Epoch 019 - train 0.37130 | val 1.72917
  Classification -> best τ=0.365 (val F1=0.5899)
  Directional -> Accuracy: 0.3778, MCC: 0.1525, F1: 0.5172

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53500 | val 2.57256
  Epoch 016 - train 0.42135 | val 3.29417
  Classification -> best τ=0.300 (val F1=0.2105)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55850 | val 0.78576
  Epoch 017 - train 0.43546 | val 0.79669
  Classification -> best τ=0.415 (val F1=0.0605)
  Directional -> Accuracy: 0.5349, MCC: 0.0977, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50116 | val 0.65070
  Epoch 020 - train 0.30609 | val 0.99021
  Epoch 030 - train 0.15188 | val 0.92920
  Classification -> best τ=0.650 (val F1=0.5105)
  Directional -> Accuracy: 0.4615, MCC: -0.1236, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48465 | val 1.27599
  Epoch 017 - train 0.40881 | val 1.66642
  Classification -> best τ=0.500 (val F1=0.2390)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59173 | val 1.26608
  Epoch 016 - train 0.53469 | val 2.07690
  Classification -> best τ=0.410 (val F1=0.2336)
  Directional -> Accuracy: 0.5849, MCC: 0.1847, F1: 0.5769

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55677 | val 1.38941
  Epoch 016 - train 0.44819 | val 1.07814
  Classification -> best τ=0.645 (val F1=0.3452)
  Directional -> Accuracy: 0.5185, MCC: 0.0808, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57323 | val 2.03682
  Epoch 016 - train 0.48356 | val 2.46594
  Classification -> best τ=0.470 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1449, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53362 | val 3.72988
  Epoch 016 - train 0.42195 | val 4.75893
  Classification -> best τ=0.675 (val F1=0.1968)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62527 | val 0.68200
  Epoch 020 - train 0.45631 | val 1.38846

[I 2026-02-20 02:02:15,272] Trial 78 finished with value: 0.25978632218700165 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0028040059594261857, 'weight_decay': 1.3879069604754675e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.8297026056561683, 'early_stopping_min_delta': 0.004021969769377759}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 022 - train 0.45834 | val 1.43170
  Classification -> best τ=0.595 (val F1=0.2591)
  Directional -> Accuracy: 0.5172, MCC: 0.0694, F1: 0.5882

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25978632218700165
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62520 | val 0.74826
  Epoch 017 - train 0.56653 | val 0.71480
  Classification -> best τ=0.530 (val F1=0.2627)
  Directional -> Accuracy: 0.5263, MCC: -0.0267, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58656 | val 0.73870
  Epoch 016 - train 0.45488 | val 0.98605
  Classification -> best τ=0.430 (val F1=0.1186)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53235 | val 1.02637
  Epoch 016 - train 0.43013 | val 1.42112
  Classification -> best τ=0.640 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59889 | val 1.05395
  Epoch 017 - train 0.57281 | val 1.48923
  Classification -> best τ=0.425 (val F1=0.1079)
  Directional -> Accuracy: 0.5270, MCC: 0.1566, F1: 0.3137

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53859 | val 0.64246
  Epoch 019 - train 0.35619 | val 0.92198
  Classification -> best τ=0.515 (val F1=0.5155)
  Directional -> Accuracy: 0.7400, MCC: 0.5047, F1: 0.7111

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45689 | val 0.70688
  Epoch 020 - train 0.32863 | val 0.76034
  Classification -> best τ=0.375 (val F1=0.3495)
  Directional -> Accuracy: 0.5217, MCC: 0.0733, F1: 0.6071

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61683 | val 0.97502
  Epoch 017 - train 0.50659 | val 1.18506
  Classification -> best τ=0.340 (val F1=0.2220)
  Directional -> Accuracy: 0.4265, MCC: 0.0751, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51247 | val 0.90490
  Epoch 016 - train 0.37103 | val 1.24156
  Classification -> best τ=0.280 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50101 | val 1.72939
  Epoch 016 - train 0.40713 | val 1.82406
  Classification -> best τ=0.575 (val F1=0.2822)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53314 | val 0.72963
  Epoch 016 - train 0.47459 | val 0.79093
  Classification -> best τ=0.465 (val F1=0.1910)
  Directional -> Accuracy: 0.4928, MCC: 0.0780, F1: 0.5679

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61018 | val 0.83612
  Epoch 019 - train 0.50122 | val 0.69444
  Classification -> best τ=0.480 (val F1=0.3231)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57613 | val 1.58113
  Epoch 017 - train 0.51970 | val 2.86397
  Classification -> best τ=0.435 (val F1=0.2430)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55339 | val 1.06120
  Epoch 020 - train 0.38163 | val 1.82420
  Classification -> best τ=0.495 (val F1=0.3070)
  Directional -> Accuracy: 0.4524, MCC: -0.0391, F1: 0.5818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60803 | val 0.78687
  Epoch 019 - train 0.46304 | val 1.06674
  Classification -> best τ=0.450 (val F1=0.4048)
  Directional -> Accuracy: 0.4833, MCC: -0.0349, F1: 0.5507

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49219 | val 0.70375
  Epoch 017 - train 0.44329 | val 0.83122
  Classification -> best τ=0.500 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61506 | val 0.74783
  Epoch 017 - train 0.52869 | val 0.88345
  Classification -> best τ=0.520 (val F1=0.3383)
  Directional -> Accuracy: 0.6087, MCC: 0.2238, F1: 0.6087

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58631 | val 1.08505
  Epoch 016 - train 0.51598 | val 1.08903
  Classification -> best τ=0.435 (val F1=0.1486)
  Directional -> Accuracy: 0.6207, MCC: 0.1403, F1: 0.7250

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62754 | val 0.77331
  Epoch 017 - train 0.56842 | val 1.13291
  Classification -> best τ=0.510 (val F1=0.1348)
  Directional -> Accuracy: 0.6000, MCC: 0.2069, F1: 0.6341

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59211 | val 0.92928
  Epoch 016 - train 0.51397 | val 1.30804
  Classification -> best τ=0.575 (val F1=0.1578)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53826 | val 0.78578
  Epoch 017 - train 0.43969 | val 0.77249
  Classification -> best τ=0.485 (val F1=0.3219)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57255 | val 0.79893
  Epoch 017 - train 0.47214 | val 0.70725
  Classification -> best τ=0.615 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64125 | val 1.01379
  Epoch 018 - train 0.57090 | val 1.09763
  Classification -> best τ=0.410 (val F1=0.1925)
  Directional -> Accuracy: 0.3692, MCC: -0.2782, F1: 0.4533

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57236 | val 1.09611
  Epoch 016 - train 0.45581 | val 2.02383
  Classification -> best τ=0.530 (val F1=0.1409)
  Directional -> Accuracy: 0.5965, MCC: 0.1500, F1: 0.7089

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61493 | val 0.75035
  Epoch 017 - train 0.53387 | val 0.75045
  Classification -> best τ=0.440 (val F1=0.1717)
  Directional -> Accuracy: 0.5385, MCC: 0.1027, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52189 | val 1.03935
  Epoch 016 - train 0.42126 | val 1.49599
  Classification -> best τ=0.600 (val F1=0.3618)
  Directional -> Accuracy: 0.5818, MCC: 0.2155, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51068 | val 1.64204
  Epoch 016 - train 0.40211 | val 1.93701
  Classification -> best τ=0.530 (val F1=0.2935)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66326 | val 0.82723
  Epoch 017 - train 0.56940 | val 0.93926
  Classification -> best τ=0.510 (val F1=0.1171)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52598 | val 1.17064
  Epoch 016 - train 0.44232 | val 1.48652
  Classification -> best τ=0.505 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52177 | val 1.96574
  Epoch 016 - train 0.40356 | val 3.82545
  Classification -> best τ=0.485 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57762 | val 0.97164
  Epoch 018 - train 0.40830 | val 1.27300
  Classification -> best τ=0.685 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0608, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52658 | val 1.21171
  Epoch 016 - train 0.45007 | val 1.23466
  Classification -> best τ=0.525 (val F1=0.1149)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52814 | val 0.74605
  Epoch 017 - train 0.40291 | val 0.96914
  Classification -> best τ=0.410 (val F1=0.3356)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66127 | val 0.66868
  Epoch 020 - train 0.49159 | val 0.85005
  Classification -> best τ=0.205 (val F1=0.3346)
  Directional -> Accuracy: 0.5972, MCC: 0.1640, F1: 0.6813

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54720 | val 1.32674
  Epoch 017 - train 0.43538 | val 1.82491
  Classification -> best τ=0.340 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.1084, F1: 0.6429

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58627 | val 1.20475
  Epoch 020 - train 0.38824 | val 1.49660
  Classification -> best τ=0.170 (val F1=0.4100)
  Directional -> Accuracy: 0.5758, MCC: 0.1487, F1: 0.6111

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47471 | val 1.82840
  Epoch 019 - train 0.34718 | val 2.79528
  Classification -> best τ=0.390 (val F1=0.2858)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52396 | val 0.89655
  Epoch 016 - train 0.42239 | val 1.56806
  Classification -> best τ=0.445 (val F1=0.2450)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51164 | val 0.68055
  Epoch 016 - train 0.32059 | val 0.87380
  Classification -> best τ=0.440 (val F1=0.4043)
  Directional -> Accuracy: 0.5870, MCC: -0.0314, F1: 0.7324

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46381 | val 0.80324
  Epoch 016 - train 0.39307 | val 1.15350
  Classification -> best τ=0.455 (val F1=0.3378)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56249 | val 0.95460
  Epoch 017 - train 0.44743 | val 1.61028
  Classification -> best τ=0.200 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56138 | val 1.55045
  Epoch 016 - train 0.51662 | val 1.84312
  Classification -> best τ=0.485 (val F1=0.3371)
  Directional -> Accuracy: 0.5556, MCC: 0.1266, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50431 | val 0.95439
  Epoch 016 - train 0.41432 | val 0.99397
  Classification -> best τ=0.585 (val F1=0.5345)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50538 | val 0.52510
  Epoch 020 - train 0.29003 | val 1.03644
  Classification -> best τ=0.645 (val F1=0.5081)
  Directional -> Accuracy: 0.3958, MCC: -0.0176, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61921 | val 0.70089
  Epoch 016 - train 0.55629 | val 0.73410
  Classification -> best τ=0.490 (val F1=0.2212)
  Directional -> Accuracy: 0.3455, MCC: -0.3735, F1: 0.4706

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56443 | val 1.68585
  Epoch 016 - train 0.45595 | val 2.43977
  Classification -> best τ=0.555 (val F1=0.1502)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59240 | val 0.88189
  Epoch 017 - train 0.52509 | val 1.39325
  Classification -> best τ=0.540 (val F1=0.0561)
  Directional -> Accuracy: 0.4340, MCC: -0.1312, F1: 0.4231

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57828 | val 1.61066
  Epoch 016 - train 0.44987 | val 1.77563
  Classification -> best τ=0.605 (val F1=0.0832)
  Directional -> Accuracy: 0.5455, MCC: 0.0743, F1: 0.6377

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59656 | val 0.67318

[I 2026-02-20 02:04:59,812] Trial 79 finished with value: 0.25822297011437306 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.008233277392995272, 'weight_decay': 5.602521425764921e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5911368119568872, 'early_stopping_min_delta': 0.0056086561384523816}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 020 - train 0.52050 | val 0.72445
  Classification -> best τ=0.420 (val F1=0.2534)
  Directional -> Accuracy: 0.4667, MCC: -0.0679, F1: 0.4483

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25822297011437306
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65731 | val 0.70469
  Epoch 016 - train 0.64596 | val 0.77941
  Classification -> best τ=0.495 (val F1=0.2085)
  Directional -> Accuracy: 0.5333, MCC: -0.0286, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65664 | val 0.68807
  Epoch 016 - train 0.64260 | val 0.71134
  Classification -> best τ=0.445 (val F1=0.2079)
  Directional -> Accuracy: 0.6364, MCC: 0.2479, F1: 0.6923

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65728 | val 0.68790
  Epoch 020 - train 0.64120 | val 0.70885
  Epoch 026 - train 0.63330 | val 0.74181
  Classification -> best τ=0.550 (val F1=0.3086)
  Directional -> Accuracy: 0.4444, MCC: -0.1071, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65306 | val 0.88418
  Epoch 016 - train 0.64417 | val 0.91454
  Classification -> best τ=0.450 (val F1=0.1260)
  Directional -> Accuracy: 0.5205, MCC: -0.0039, F1: 0.6465

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65849 | val 0.65176
  Epoch 020 - train 0.63687 | val 0.63191
  Epoch 029 - train 0.62168 | val 0.64019
  Classification -> best τ=0.540 (val F1=0.3454)
  Directional -> Accuracy: 0.5714, MCC: 0.1414, F1: 0.6038

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67333 | val 0.69033
  Epoch 020 - train 0.64099 | val 0.70143
  Epoch 028 - train 0.62448 | val 0.73176
  Classification -> best τ=0.520 (val F1=0.2156)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.6567

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67120 | val 0.69059
  Epoch 016 - train 0.66387 | val 0.69146
  Classification -> best τ=0.455 (val F1=0.1690)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66891 | val 0.71577
  Epoch 016 - train 0.65543 | val 0.75759
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66036 | val 0.68510
  Epoch 016 - train 0.64787 | val 0.71183
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64259 | val 0.70652
  Epoch 016 - train 0.62901 | val 0.70446
  Classification -> best τ=0.435 (val F1=0.1296)
  Directional -> Accuracy: 0.4559, MCC: 0.1501, F1: 0.6105

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66095 | val 0.70258
  Epoch 016 - train 0.65166 | val 0.70701
  Classification -> best τ=0.490 (val F1=0.1556)
  Directional -> Accuracy: 0.4583, MCC: -0.1448, F1: 0.2353

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65870 | val 0.71217
  Epoch 016 - train 0.64206 | val 0.76197
  Classification -> best τ=0.440 (val F1=0.2119)
  Directional -> Accuracy: 0.4821, MCC: -0.0266, F1: 0.4082

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63494 | val 0.76987
  Epoch 016 - train 0.61884 | val 1.02490
  Classification -> best τ=0.495 (val F1=0.2335)
  Directional -> Accuracy: 0.5714, MCC: 0.2119, F1: 0.6769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66357 | val 0.63916
  Epoch 020 - train 0.64553 | val 0.62603
  Epoch 028 - train 0.63339 | val 0.62639
  Classification -> best τ=0.410 (val F1=0.3210)
  Directional -> Accuracy: 0.5254, MCC: 0.0488, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64575 | val 0.71462
  Epoch 016 - train 0.63129 | val 0.75451
  Classification -> best τ=0.490 (val F1=0.1402)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65657 | val 0.71804
  Epoch 016 - train 0.64501 | val 0.75402
  Classification -> best τ=0.530 (val F1=0.0478)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65258 | val 0.88402
  Epoch 016 - train 0.64354 | val 1.18524
  Classification -> best τ=0.515 (val F1=0.0379)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66086 | val 0.73091
  Epoch 016 - train 0.65109 | val 0.78345
  Classification -> best τ=0.500 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65726 | val 0.68947
  Epoch 016 - train 0.64652 | val 0.69378
  Classification -> best τ=0.545 (val F1=0.1300)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64994 | val 0.68634
  Epoch 019 - train 0.63510 | val 0.69464
  Classification -> best τ=0.450 (val F1=0.2443)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65414 | val 0.69057
  Epoch 020 - train 0.63181 | val 0.67959
  Epoch 030 - train 0.61254 | val 0.67654
  Classification -> best τ=0.390 (val F1=0.2249)
  Directional -> Accuracy: 0.6087, MCC: 0.3050, F1: 0.5909

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66167 | val 0.72670
  Epoch 016 - train 0.65252 | val 0.76185
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65663 | val 0.67783
  Epoch 020 - train 0.63820 | val 0.73641
  Epoch 022 - train 0.63584 | val 0.74211
  Classification -> best τ=0.515 (val F1=0.3267)
  Directional -> Accuracy: 0.6250, MCC: 0.2076, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64938 | val 0.79171
  Epoch 016 - train 0.63755 | val 0.85825
  Classification -> best τ=0.480 (val F1=0.1604)
  Directional -> Accuracy: 0.5156, MCC: 0.1098, F1: 0.6353

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66337 | val 0.66114
  Epoch 020 - train 0.64342 | val 0.62479
  Epoch 030 - train 0.62736 | val 0.61459
  Classification -> best τ=0.580 (val F1=0.4973)
  Directional -> Accuracy: 0.4815, MCC: 0.0631, F1: 0.1250

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65896 | val 0.68730
  Epoch 016 - train 0.64610 | val 0.68978
  Classification -> best τ=0.530 (val F1=0.3243)
  Directional -> Accuracy: 0.3721, MCC: -0.2151, F1: 0.5263

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65674 | val 0.69148
  Epoch 016 - train 0.64543 | val 0.70124
  Classification -> best τ=0.555 (val F1=0.0301)
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65538 | val 0.68785
  Epoch 020 - train 0.63791 | val 0.71929
  Epoch 022 - train 0.63538 | val 0.72461
  Classification -> best τ=0.475 (val F1=0.1881)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66592 | val 0.68913
  Epoch 016 - train 0.64765 | val 0.68696
  Classification -> best τ=0.490 (val F1=0.3030)
  Directional -> Accuracy: 0.5263, MCC: -0.0180, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66092 | val 0.71561
  Epoch 016 - train 0.65160 | val 0.74392
  Classification -> best τ=0.530 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66280 | val 0.69969
  Epoch 016 - train 0.64951 | val 0.75012
  Classification -> best τ=0.530 (val F1=0.0720)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65584 | val 0.71943
  Epoch 016 - train 0.63933 | val 0.73060
  Classification -> best τ=0.555 (val F1=0.1229)
  Directional -> Accuracy: 0.4583, MCC: -0.0723, F1: 0.2778

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65211 | val 0.67636
  Epoch 020 - train 0.63249 | val 0.67682
  Epoch 024 - train 0.62638 | val 0.67691
  Classification -> best τ=0.420 (val F1=0.2411)
  Directional -> Accuracy: 0.5211, MCC: 0.1508, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65757 | val 0.71388
  Epoch 016 - train 0.64599 | val 0.76938
  Classification -> best τ=0.505 (val F1=0.1894)
  Directional -> Accuracy: 0.5714, MCC: 0.1445, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67241 | val 0.70731
  Epoch 016 - train 0.65448 | val 0.71211
  Classification -> best τ=0.545 (val F1=0.0657)
  Directional -> Accuracy: 0.5538, MCC: -0.1087, F1: 0.7129

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65028 | val 0.68109
  Epoch 020 - train 0.61760 | val 0.69167
  Epoch 021 - train 0.61525 | val 0.69305
  Classification -> best τ=0.445 (val F1=0.2582)
  Directional -> Accuracy: 0.5500, MCC: 0.0977, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63610 | val 0.69130
  Epoch 019 - train 0.62026 | val 0.74028
  Classification -> best τ=0.455 (val F1=0.2140)
  Directional -> Accuracy: 0.5091, MCC: 0.1617, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65536 | val 0.68734
  Epoch 016 - train 0.63928 | val 0.72346
  Classification -> best τ=0.445 (val F1=0.1120)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66417 | val 0.68327
  Epoch 020 - train 0.63961 | val 0.66759
  Epoch 030 - train 0.62065 | val 0.65571
  Classification -> best τ=0.555 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65487 | val 0.68982
  Epoch 020 - train 0.63076 | val 0.68597
  Epoch 028 - train 0.61569 | val 0.69726
  Classification -> best τ=0.530 (val F1=0.2570)
  Directional -> Accuracy: 0.5342, MCC: 0.1091, F1: 0.6531

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66183 | val 0.68869
  Epoch 016 - train 0.64927 | val 0.69341
  Classification -> best τ=0.495 (val F1=0.2887)
  Directional -> Accuracy: 0.4545, MCC: -0.1179, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65141 | val 0.70307
  Epoch 020 - train 0.62663 | val 0.69290
  Epoch 030 - train 0.60961 | val 0.68658
  Classification -> best τ=0.375 (val F1=0.2548)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65144 | val 0.69626
  Epoch 016 - train 0.63537 | val 0.70051
  Classification -> best τ=0.495 (val F1=0.4469)
  Directional -> Accuracy: 0.6304, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66765 | val 0.84376
  Epoch 016 - train 0.65798 | val 1.08771
  Classification -> best τ=0.485 (val F1=0.1386)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64277 | val 0.79006
  Epoch 016 - train 0.62973 | val 0.89142
  Classification -> best τ=0.540 (val F1=0.3630)
  Directional -> Accuracy: 0.5455, MCC: 0.1394, F1: 0.6575

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66523 | val 0.67641
  Epoch 020 - train 0.64628 | val 0.66046
  Epoch 030 - train 0.62984 | val 0.66884
  Classification -> best τ=0.450 (val F1=0.2430)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66316 | val 0.72459
  Epoch 016 - train 0.64984 | val 0.78350
  Classification -> best τ=0.520 (val F1=0.0370)
  Directional -> Accuracy: 0.4074, MCC: -0.2935, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66679 | val 0.68374
  Epoch 020 - train 0.64755 | val 0.70634

[I 2026-02-20 02:06:35,743] Trial 80 finished with value: 0.2025449951059254 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 9.43885299134675e-05, 'weight_decay': 7.760337381042127e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.6906155027759437, 'early_stopping_min_delta': 0.004505796628149184}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 025 - train 0.64077 | val 0.72561
  Classification -> best τ=0.475 (val F1=0.1931)
  Directional -> Accuracy: 0.5424, MCC: 0.1216, F1: 0.6197

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2025449951059254
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64683 | val 0.67854
  Epoch 020 - train 0.51192 | val 0.69850
  Epoch 023 - train 0.46340 | val 0.67293
  Classification -> best τ=0.560 (val F1=0.3366)
  Directional -> Accuracy: 0.5067, MCC: -0.0890, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62171 | val 0.81471
  Epoch 019 - train 0.41913 | val 0.74740
  Classification -> best τ=0.375 (val F1=0.3000)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62399 | val 0.81359
  Epoch 016 - train 0.50858 | val 0.87771
  Classification -> best τ=0.645 (val F1=0.2414)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62762 | val 3.34980
  Epoch 016 - train 0.56348 | val 2.74373
  Classification -> best τ=0.230 (val F1=0.1290)
  Directional -> Accuracy: 0.5068, MCC: -0.1041, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51022 | val 2.20930
  Epoch 016 - train 0.36132 | val 2.64207
  Classification -> best τ=0.530 (val F1=0.4250)
  Directional -> Accuracy: 0.7143, MCC: 0.4307, F1: 0.7083

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46452 | val 1.79638
  Epoch 020 - train 0.29826 | val 1.57434
  Epoch 021 - train 0.32809 | val 1.59828
  Classification -> best τ=0.705 (val F1=0.3382)
  Directional -> Accuracy: 0.5778, MCC: 0.1692, F1: 0.6275

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61006 | val 0.82678
  Epoch 016 - train 0.53716 | val 1.05991
  Classification -> best τ=0.545 (val F1=0.1869)
  Directional -> Accuracy: 0.6269, MCC: 0.1765, F1: 0.3902

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53067 | val 1.56806
  Epoch 016 - train 0.44573 | val 2.76748
  Classification -> best τ=0.610 (val F1=0.3333)
  Directional -> Accuracy: 0.5854, MCC: 0.1443, F1: 0.4848

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50701 | val 0.94709
  Epoch 016 - train 0.44477 | val 1.01220
  Classification -> best τ=0.505 (val F1=0.4166)
  Directional -> Accuracy: 0.3191, MCC: -0.3571, F1: 0.4286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53547 | val 1.06126
  Epoch 016 - train 0.47795 | val 1.14522
  Classification -> best τ=0.550 (val F1=0.0684)
  Directional -> Accuracy: 0.3971, MCC: -0.1566, F1: 0.4810

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61093 | val 0.93232
  Epoch 016 - train 0.48763 | val 1.08606
  Classification -> best τ=0.610 (val F1=0.2335)
  Directional -> Accuracy: 0.6042, MCC: 0.2807, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54280 | val 1.47786
  Epoch 016 - train 0.46213 | val 1.97087
  Classification -> best τ=0.655 (val F1=0.1792)
  Directional -> Accuracy: 0.6964, MCC: 0.3967, F1: 0.6909

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46592 | val 3.02112
  Epoch 016 - train 0.39001 | val 4.06044
  Classification -> best τ=0.390 (val F1=0.2112)
  Directional -> Accuracy: 0.4490, MCC: -0.1193, F1: 0.3077

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63602 | val 0.71893
  Epoch 020 - train 0.46950 | val 0.99508
  Classification -> best τ=0.730 (val F1=0.3113)
  Directional -> Accuracy: 0.5424, MCC: 0.1510, F1: 0.2703

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55067 | val 1.12005
  Epoch 016 - train 0.43790 | val 1.57220
  Classification -> best τ=0.650 (val F1=0.2060)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54646 | val 0.95648
  Epoch 017 - train 0.41019 | val 1.48528
  Classification -> best τ=0.365 (val F1=0.2818)
  Directional -> Accuracy: 0.6029, MCC: 0.2988, F1: 0.7273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57955 | val 1.18835
  Epoch 016 - train 0.48998 | val 1.47659
  Classification -> best τ=0.325 (val F1=0.1890)
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64292 | val 1.03449
  Epoch 017 - train 0.57734 | val 1.38200
  Classification -> best τ=0.415 (val F1=0.2230)
  Directional -> Accuracy: 0.6351, MCC: 0.1980, F1: 0.7523

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56532 | val 1.38922
  Epoch 016 - train 0.48528 | val 1.54521
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5873, MCC: 0.0000, F1: 0.7400

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53554 | val 0.80025
  Epoch 016 - train 0.45656 | val 1.03743
  Classification -> best τ=0.560 (val F1=0.2506)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55602 | val 1.71876
  Epoch 016 - train 0.43440 | val 1.50385
  Classification -> best τ=0.440 (val F1=0.2227)
  Directional -> Accuracy: 0.6739, MCC: 0.3294, F1: 0.7887

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57775 | val 1.90039
  Epoch 016 - train 0.56789 | val 1.63810
  Classification -> best τ=0.810 (val F1=0.2288)
  Directional -> Accuracy: 0.5156, MCC: 0.1260, F1: 0.0606

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49496 | val 1.75596
  Epoch 016 - train 0.42509 | val 2.40804
  Classification -> best τ=0.610 (val F1=0.2719)
  Directional -> Accuracy: 0.5536, MCC: 0.0366, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50257 | val 1.49488
  Epoch 016 - train 0.44352 | val 1.45214
  Classification -> best τ=0.495 (val F1=0.2350)
  Directional -> Accuracy: 0.5156, MCC: 0.0687, F1: 0.5974

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50774 | val 1.59755
  Epoch 016 - train 0.38383 | val 1.73140
  Classification -> best τ=0.625 (val F1=0.4835)
  Directional -> Accuracy: 0.5556, MCC: 0.1930, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48598 | val 1.64932
  Epoch 016 - train 0.35268 | val 1.97980
  Classification -> best τ=0.500 (val F1=0.0329)
  Directional -> Accuracy: 0.4186, MCC: -0.0364, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58869 | val 0.69144
  Epoch 020 - train 0.45528 | val 1.19863
  Epoch 027 - train 0.38793 | val 1.53512
  Classification -> best τ=0.585 (val F1=0.1426)
  Directional -> Accuracy: 0.5510, MCC: 0.1496, F1: 0.5417

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54216 | val 1.60400
  Epoch 016 - train 0.42739 | val 2.55064
  Classification -> best τ=0.705 (val F1=0.1605)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49421 | val 0.79761
  Epoch 020 - train 0.38732 | val 1.07571
  Epoch 021 - train 0.40286 | val 1.03679
  Classification -> best τ=0.360 (val F1=0.3708)
  Directional -> Accuracy: 0.6053, MCC: 0.2088, F1: 0.7273

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50672 | val 2.95087
  Epoch 016 - train 0.36956 | val 2.41505
  Classification -> best τ=0.640 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50856 | val 1.16212
  Epoch 016 - train 0.41281 | val 1.20103
  Classification -> best τ=0.575 (val F1=0.1437)
  Directional -> Accuracy: 0.4390, MCC: -0.0278, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43403 | val 0.96366
  Epoch 016 - train 0.31853 | val 1.27794
  Classification -> best τ=0.590 (val F1=0.2949)
  Directional -> Accuracy: 0.4792, MCC: -0.0268, F1: 0.3590

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54311 | val 1.13536
  Epoch 016 - train 0.47040 | val 1.72973
  Classification -> best τ=0.750 (val F1=0.2721)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49763 | val 0.80384
  Epoch 016 - train 0.38715 | val 1.05536
  Classification -> best τ=0.625 (val F1=0.3362)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52292 | val 1.16008
  Epoch 016 - train 0.45889 | val 1.43664
  Classification -> best τ=0.150 (val F1=0.2100)
  Directional -> Accuracy: 0.5692, MCC: 0.1142, F1: 0.6316

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52013 | val 0.97954
  Epoch 016 - train 0.41712 | val 0.82532
  Classification -> best τ=0.530 (val F1=0.0636)
  Directional -> Accuracy: 0.6250, MCC: 0.2950, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53736 | val 0.76354
  Epoch 020 - train 0.33747 | val 1.12379
  Classification -> best τ=0.500 (val F1=0.2494)
  Directional -> Accuracy: 0.4909, MCC: 0.0219, F1: 0.5625

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45107 | val 1.08129
  Epoch 016 - train 0.34028 | val 0.97560
  Classification -> best τ=0.585 (val F1=0.2320)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49141 | val 1.24381
  Epoch 016 - train 0.41474 | val 1.31657
  Classification -> best τ=0.640 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56709 | val 1.72741
  Epoch 018 - train 0.43943 | val 3.30069
  Classification -> best τ=0.255 (val F1=0.2206)
  Directional -> Accuracy: 0.5205, MCC: 0.1171, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54506 | val 1.14751
  Epoch 016 - train 0.48676 | val 1.36616
  Classification -> best τ=0.400 (val F1=0.4330)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3529

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41862 | val 1.60687
  Epoch 016 - train 0.31194 | val 1.82648
  Classification -> best τ=0.535 (val F1=0.0707)
  Directional -> Accuracy: 0.5122, MCC: 0.0290, F1: 0.5455

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43699 | val 1.72345
  Epoch 016 - train 0.28132 | val 2.39744
  Classification -> best τ=0.470 (val F1=0.1942)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63161 | val 1.13531
  Epoch 016 - train 0.55994 | val 1.72939
  Classification -> best τ=0.435 (val F1=0.2697)
  Directional -> Accuracy: 0.4074, MCC: -0.1542, F1: 0.3043

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52600 | val 2.42659
  Epoch 016 - train 0.45278 | val 2.84343
  Classification -> best τ=0.305 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64712 | val 0.87243
  Epoch 020 - train 0.52270 | val 1.38417
  Epoch 022 - train 0.47998 | val 1.35455
  Classification -> best τ=0.615 (val F1=0.2619)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6486

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54184 | val 1.84391
  Epoch 017 - train 0.43292 | val 2.03091
  Classification -> best τ=0.300 (val F1=0.2011)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63379 | val 0.74815

[I 2026-02-20 02:11:16,880] Trial 81 finished with value: 0.24393545270887515 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.005103009225983568, 'weight_decay': 2.857076569222609e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9209505908127278, 'early_stopping_min_delta': 0.006878612723175899}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 020 - train 0.43650 | val 0.76482
  Classification -> best τ=0.350 (val F1=0.2518)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24393545270887515
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62576 | val 0.71362
  Epoch 020 - train 0.58445 | val 1.11365
  Classification -> best τ=0.510 (val F1=0.2705)
  Directional -> Accuracy: 0.5467, MCC: 0.0488, F1: 0.3200

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55624 | val 0.79282
  Epoch 020 - train 0.47686 | val 0.73620
  Epoch 022 - train 0.45390 | val 0.70632
  Classification -> best τ=0.370 (val F1=0.1902)
  Directional -> Accuracy: 0.5682, MCC: -0.0066, F1: 0.7077

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61600 | val 1.29263
  Epoch 018 - train 0.43820 | val 1.24625
  Classification -> best τ=0.190 (val F1=0.3086)
  Directional -> Accuracy: 0.4889, MCC: -0.0854, F1: 0.6230

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62082 | val 1.12788
  Epoch 016 - train 0.56821 | val 1.82462
  Classification -> best τ=0.335 (val F1=0.2100)
  Directional -> Accuracy: 0.5068, MCC: -0.1041, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45856 | val 2.84863
  Epoch 016 - train 0.38094 | val 3.49622
  Classification -> best τ=0.595 (val F1=0.4307)
  Directional -> Accuracy: 0.6327, MCC: 0.2671, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48324 | val 0.78079
  Epoch 017 - train 0.32423 | val 1.81213
  Classification -> best τ=0.590 (val F1=0.2294)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.3226

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64847 | val 0.85319
  Epoch 018 - train 0.45936 | val 1.18282
  Classification -> best τ=0.420 (val F1=0.2389)
  Directional -> Accuracy: 0.4179, MCC: -0.0178, F1: 0.5517

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52466 | val 1.59780
  Epoch 017 - train 0.38893 | val 1.92207
  Classification -> best τ=0.665 (val F1=0.1777)
  Directional -> Accuracy: 0.3902, MCC: -0.1842, F1: 0.4898

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54328 | val 1.78410
  Epoch 020 - train 0.39861 | val 1.64050
  Classification -> best τ=0.600 (val F1=0.3433)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53318 | val 0.82966
  Epoch 016 - train 0.47178 | val 1.05230
  Classification -> best τ=0.415 (val F1=0.1838)
  Directional -> Accuracy: 0.5147, MCC: 0.1130, F1: 0.5823

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61660 | val 0.70946
  Epoch 020 - train 0.45700 | val 0.76908
  Epoch 026 - train 0.39322 | val 0.77266
  Classification -> best τ=0.500 (val F1=0.3055)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62010 | val 0.94405
  Epoch 018 - train 0.46905 | val 1.48038
  Classification -> best τ=0.585 (val F1=0.2215)
  Directional -> Accuracy: 0.6786, MCC: 0.3895, F1: 0.6250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47617 | val 3.11022
  Epoch 017 - train 0.38112 | val 3.74728
  Classification -> best τ=0.400 (val F1=0.1639)
  Directional -> Accuracy: 0.5102, MCC: 0.0042, F1: 0.0769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64706 | val 0.76199
  Epoch 020 - train 0.52356 | val 1.28647
  Epoch 021 - train 0.51177 | val 1.21306
  Classification -> best τ=0.255 (val F1=0.3358)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55249 | val 0.98036
  Epoch 016 - train 0.42911 | val 1.33385
  Classification -> best τ=0.500 (val F1=0.0994)
  Directional -> Accuracy: 0.5200, MCC: 0.1041, F1: 0.5862

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60526 | val 1.00342
  Epoch 020 - train 0.39335 | val 2.04897
  Epoch 022 - train 0.31818 | val 2.29213
  Classification -> best τ=0.200 (val F1=0.2818)
  Directional -> Accuracy: 0.6176, MCC: 0.2959, F1: 0.7292

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57652 | val 1.51218
  Epoch 016 - train 0.48184 | val 2.02672
  Classification -> best τ=0.590 (val F1=0.0725)
  Directional -> Accuracy: 0.3860, MCC: -0.1591, F1: 0.3396

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65028 | val 0.80140
  Epoch 018 - train 0.53129 | val 1.21074
  Classification -> best τ=0.660 (val F1=0.2204)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54869 | val 0.83126
  Epoch 016 - train 0.48582 | val 1.29285
  Classification -> best τ=0.540 (val F1=0.2288)
  Directional -> Accuracy: 0.3810, MCC: -0.1784, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58088 | val 0.86005
  Epoch 016 - train 0.49376 | val 1.10146
  Classification -> best τ=0.535 (val F1=0.3060)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50534 | val 1.52273
  Epoch 016 - train 0.47436 | val 1.07699
  Classification -> best τ=0.420 (val F1=0.1461)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63082 | val 2.31812
  Epoch 016 - train 0.58306 | val 2.88877
  Classification -> best τ=0.695 (val F1=0.0276)
  Directional -> Accuracy: 0.5781, MCC: 0.1563, F1: 0.5846

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58494 | val 1.65211
  Epoch 016 - train 0.49013 | val 3.42424
  Classification -> best τ=0.670 (val F1=0.2981)
  Directional -> Accuracy: 0.5179, MCC: 0.0871, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55135 | val 1.34261
  Epoch 016 - train 0.42832 | val 1.56344
  Classification -> best τ=0.590 (val F1=0.1341)
  Directional -> Accuracy: 0.5469, MCC: 0.0852, F1: 0.4912

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47698 | val 1.21535
  Epoch 016 - train 0.36918 | val 1.64218
  Classification -> best τ=0.470 (val F1=0.4977)
  Directional -> Accuracy: 0.5556, MCC: 0.1930, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48448 | val 1.50850
  Epoch 016 - train 0.36946 | val 1.76701
  Classification -> best τ=0.640 (val F1=0.4501)
  Directional -> Accuracy: 0.3953, MCC: -0.2422, F1: 0.2778

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54778 | val 0.69588
  Epoch 020 - train 0.40652 | val 0.89632
  Epoch 024 - train 0.29766 | val 1.21456
  Classification -> best τ=0.640 (val F1=0.2538)
  Directional -> Accuracy: 0.4694, MCC: -0.0053, F1: 0.4348

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56326 | val 1.79471
  Epoch 016 - train 0.44690 | val 2.64976
  Classification -> best τ=0.490 (val F1=0.2257)
  Directional -> Accuracy: 0.5273, MCC: 0.2557, F1: 0.2353

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52454 | val 0.75336
  Epoch 016 - train 0.39703 | val 0.71640
  Classification -> best τ=0.500 (val F1=0.2955)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54482 | val 2.66200
  Epoch 016 - train 0.39350 | val 3.96724
  Classification -> best τ=0.775 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49665 | val 0.85247
  Epoch 016 - train 0.34541 | val 0.84197
  Classification -> best τ=0.620 (val F1=0.1920)
  Directional -> Accuracy: 0.4146, MCC: -0.1245, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51194 | val 0.89628
  Epoch 016 - train 0.41250 | val 1.11883
  Classification -> best τ=0.595 (val F1=0.2949)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59103 | val 1.42161
  Epoch 017 - train 0.50570 | val 1.85403
  Classification -> best τ=0.135 (val F1=0.2961)
  Directional -> Accuracy: 0.5634, MCC: 0.0633, F1: 0.6804

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55544 | val 0.97733
  Epoch 016 - train 0.44064 | val 1.27311
  Classification -> best τ=0.740 (val F1=0.2712)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50035 | val 0.93887
  Epoch 016 - train 0.37520 | val 0.98160
  Classification -> best τ=0.250 (val F1=0.3218)
  Directional -> Accuracy: 0.6154, MCC: 0.1923, F1: 0.6988

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49123 | val 0.88390
  Epoch 017 - train 0.38060 | val 1.07510
  Classification -> best τ=0.385 (val F1=0.2697)
  Directional -> Accuracy: 0.6500, MCC: 0.3394, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50312 | val 1.13654
  Epoch 016 - train 0.45757 | val 1.85845
  Classification -> best τ=0.405 (val F1=0.2436)
  Directional -> Accuracy: 0.5273, MCC: 0.0828, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47563 | val 0.97177
  Epoch 018 - train 0.31370 | val 1.18847
  Classification -> best τ=0.450 (val F1=0.1985)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51556 | val 1.23115
  Epoch 016 - train 0.45839 | val 1.59894
  Classification -> best τ=0.600 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58307 | val 1.64341
  Epoch 018 - train 0.44132 | val 3.21082
  Classification -> best τ=0.260 (val F1=0.1765)
  Directional -> Accuracy: 0.5068, MCC: 0.1162, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54690 | val 0.76572
  Epoch 016 - train 0.45680 | val 1.09965
  Classification -> best τ=0.475 (val F1=0.3536)
  Directional -> Accuracy: 0.5455, MCC: 0.1179, F1: 0.6552

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43538 | val 1.18000
  Epoch 016 - train 0.34188 | val 1.41519
  Classification -> best τ=0.455 (val F1=0.1762)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46766 | val 1.04849
  Epoch 016 - train 0.31938 | val 1.41906
  Classification -> best τ=0.400 (val F1=0.1387)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62190 | val 1.09943
  Epoch 016 - train 0.59125 | val 1.35726
  Classification -> best τ=0.535 (val F1=0.2649)
  Directional -> Accuracy: 0.4815, MCC: 0.1754, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54515 | val 2.51019
  Epoch 016 - train 0.42591 | val 2.23693
  Classification -> best τ=0.325 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62773 | val 0.71887
  Epoch 018 - train 0.50236 | val 0.89399
  Classification -> best τ=0.585 (val F1=0.2744)
  Directional -> Accuracy: 0.5192, MCC: 0.0825, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60471 | val 0.81307
  Epoch 020 - train 0.39485 | val 1.96683
  Epoch 022 - train 0.31994 | val 1.74894
  Classification -> best τ=0.470 (val F1=0.2132)
  Directional -> Accuracy: 0.4815, MCC: -0.0693, F1: 0.6000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53606 | val 0.78975

[I 2026-02-20 02:16:00,747] Trial 82 finished with value: 0.2516374500496987 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.00575784355207072, 'weight_decay': 2.6251579154626598e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.9618733216347866, 'early_stopping_min_delta': 0.006451788384896226}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.44661 | val 0.88326
  Classification -> best τ=0.375 (val F1=0.2518)
  Directional -> Accuracy: 0.4407, MCC: -0.1135, F1: 0.5714

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2516374500496987
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63851 | val 0.68321
  Epoch 020 - train 0.52284 | val 1.19308
  Classification -> best τ=0.475 (val F1=0.2578)
  Directional -> Accuracy: 0.5200, MCC: -0.0321, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56035 | val 0.85922
  Epoch 017 - train 0.47740 | val 0.80014
  Classification -> best τ=0.450 (val F1=0.2818)
  Directional -> Accuracy: 0.5909, MCC: 0.0403, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59898 | val 1.07443
  Epoch 017 - train 0.49698 | val 1.12096
  Classification -> best τ=0.730 (val F1=0.3026)
  Directional -> Accuracy: 0.4444, MCC: -0.1612, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62968 | val 1.83208
  Epoch 016 - train 0.57910 | val 1.81477
  Classification -> best τ=0.385 (val F1=0.1560)
  Directional -> Accuracy: 0.5205, MCC: -0.0550, F1: 0.6789

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48886 | val 1.51636
  Epoch 016 - train 0.40721 | val 1.98925
  Classification -> best τ=0.545 (val F1=0.4080)
  Directional -> Accuracy: 0.6531, MCC: 0.3486, F1: 0.5641

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51283 | val 0.68765
  Epoch 020 - train 0.29584 | val 0.90288
  Classification -> best τ=0.540 (val F1=0.3241)
  Directional -> Accuracy: 0.4889, MCC: -0.0349, F1: 0.3429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60256 | val 0.90945
  Epoch 016 - train 0.49065 | val 1.54446
  Classification -> best τ=0.520 (val F1=0.1789)
  Directional -> Accuracy: 0.5970, MCC: 0.0620, F1: 0.1818

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53117 | val 2.67014
  Epoch 016 - train 0.44806 | val 3.31272
  Classification -> best τ=0.590 (val F1=0.3637)
  Directional -> Accuracy: 0.4146, MCC: -0.1443, F1: 0.4545

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59375 | val 1.29425
  Epoch 017 - train 0.49811 | val 1.74884
  Classification -> best τ=0.510 (val F1=0.1654)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55434 | val 1.25205
  Epoch 016 - train 0.50420 | val 1.15904
  Classification -> best τ=0.515 (val F1=0.0699)
  Directional -> Accuracy: 0.4706, MCC: -0.0295, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56767 | val 1.07275
  Epoch 016 - train 0.51467 | val 1.48648
  Classification -> best τ=0.635 (val F1=0.2896)
  Directional -> Accuracy: 0.6250, MCC: 0.3278, F1: 0.3077

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54635 | val 1.11462
  Epoch 016 - train 0.50233 | val 1.44041
  Classification -> best τ=0.395 (val F1=0.1269)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50007 | val 2.88612
  Epoch 016 - train 0.38787 | val 3.54524
  Classification -> best τ=0.245 (val F1=0.2510)
  Directional -> Accuracy: 0.4898, MCC: -0.0256, F1: 0.4186

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62327 | val 0.76849
  Epoch 016 - train 0.57764 | val 0.74002
  Classification -> best τ=0.530 (val F1=0.3428)
  Directional -> Accuracy: 0.5932, MCC: 0.1930, F1: 0.5556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57267 | val 1.85492
  Epoch 016 - train 0.52355 | val 1.83005
  Classification -> best τ=0.650 (val F1=0.0158)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56527 | val 1.24678
  Epoch 016 - train 0.46436 | val 1.49385
  Classification -> best τ=0.380 (val F1=0.2818)
  Directional -> Accuracy: 0.5000, MCC: -0.0500, F1: 0.6304

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63294 | val 1.21170
  Epoch 016 - train 0.54654 | val 1.35161
  Classification -> best τ=0.695 (val F1=0.0367)
  Directional -> Accuracy: 0.3684, MCC: -0.1508, F1: 0.1818

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62737 | val 1.30866
  Epoch 016 - train 0.55977 | val 1.70399
  Classification -> best τ=0.295 (val F1=0.1483)
  Directional -> Accuracy: 0.5676, MCC: 0.0228, F1: 0.6923

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56831 | val 1.06316
  Epoch 016 - train 0.52189 | val 1.12623
  Classification -> best τ=0.595 (val F1=0.0056)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55248 | val 0.94210
  Epoch 016 - train 0.46488 | val 1.00282
  Classification -> best τ=0.550 (val F1=0.2443)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54680 | val 1.98475
  Epoch 016 - train 0.53380 | val 1.41687
  Classification -> best τ=0.435 (val F1=0.1427)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59469 | val 1.72097
  Epoch 016 - train 0.53508 | val 2.31692
  Classification -> best τ=0.435 (val F1=0.1741)
  Directional -> Accuracy: 0.5469, MCC: 0.1348, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54908 | val 2.19919
  Epoch 016 - train 0.46107 | val 2.40040
  Classification -> best τ=0.635 (val F1=0.2961)
  Directional -> Accuracy: 0.5357, MCC: 0.1884, F1: 0.4091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57165 | val 0.90034
  Epoch 016 - train 0.45725 | val 0.79490
  Classification -> best τ=0.380 (val F1=0.1604)
  Directional -> Accuracy: 0.4688, MCC: -0.0112, F1: 0.6304

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49293 | val 1.28478
  Epoch 017 - train 0.41607 | val 1.46375
  Classification -> best τ=0.670 (val F1=0.5302)
  Directional -> Accuracy: 0.4630, MCC: -0.0146, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50450 | val 2.73044
  Epoch 016 - train 0.40245 | val 3.28301
  Classification -> best τ=0.540 (val F1=0.2829)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61137 | val 0.69811
  Epoch 019 - train 0.48528 | val 0.80538
  Classification -> best τ=0.560 (val F1=0.2045)
  Directional -> Accuracy: 0.6122, MCC: 0.2322, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54177 | val 1.31470
  Epoch 016 - train 0.47130 | val 1.54455
  Classification -> best τ=0.495 (val F1=0.2228)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57203 | val 0.73697
  Epoch 017 - train 0.46641 | val 0.75355
  Classification -> best τ=0.480 (val F1=0.2955)
  Directional -> Accuracy: 0.5789, MCC: 0.1195, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51918 | val 2.38592
  Epoch 016 - train 0.48117 | val 3.10017
  Classification -> best τ=0.625 (val F1=0.3922)
  Directional -> Accuracy: 0.4878, MCC: -0.0868, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50921 | val 0.89540
  Epoch 018 - train 0.34443 | val 1.76796
  Classification -> best τ=0.765 (val F1=0.2807)
  Directional -> Accuracy: 0.4390, MCC: -0.0278, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50161 | val 0.91369
  Epoch 016 - train 0.44960 | val 1.11664
  Classification -> best τ=0.590 (val F1=0.2382)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55920 | val 1.17819
  Epoch 016 - train 0.51785 | val 1.44865
  Classification -> best τ=0.670 (val F1=0.2622)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52586 | val 1.15387
  Epoch 016 - train 0.47509 | val 1.23773
  Classification -> best τ=0.545 (val F1=0.3031)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4878

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51290 | val 1.13433
  Epoch 016 - train 0.44478 | val 1.56336
  Classification -> best τ=0.280 (val F1=0.3317)
  Directional -> Accuracy: 0.6154, MCC: 0.2124, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50930 | val 0.94133
  Epoch 018 - train 0.35972 | val 0.95071
  Classification -> best τ=0.435 (val F1=0.2582)
  Directional -> Accuracy: 0.6250, MCC: 0.3179, F1: 0.5161

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59019 | val 0.85258
  Epoch 016 - train 0.44123 | val 1.08752
  Classification -> best τ=0.290 (val F1=0.2494)
  Directional -> Accuracy: 0.5273, MCC: 0.0598, F1: 0.5185

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46493 | val 1.68154
  Epoch 016 - train 0.39056 | val 1.70193
  Classification -> best τ=0.665 (val F1=0.5407)
  Directional -> Accuracy: 0.5556, MCC: -0.1296, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48911 | val 1.24884
  Epoch 016 - train 0.43333 | val 1.22156
  Classification -> best τ=0.480 (val F1=0.4341)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55841 | val 2.21626
  Epoch 016 - train 0.49025 | val 2.85525
  Classification -> best τ=0.750 (val F1=0.1664)
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57620 | val 1.04690
  Epoch 016 - train 0.55185 | val 1.27023
  Classification -> best τ=0.480 (val F1=0.4152)
  Directional -> Accuracy: 0.5909, MCC: 0.2041, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50091 | val 1.33520
  Epoch 016 - train 0.39405 | val 1.48089
  Classification -> best τ=0.605 (val F1=0.0510)
  Directional -> Accuracy: 0.4146, MCC: -0.0570, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44711 | val 1.91114
  Epoch 016 - train 0.33258 | val 2.02177
  Classification -> best τ=0.435 (val F1=0.0896)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65485 | val 1.12106
  Epoch 016 - train 0.58768 | val 1.52620
  Classification -> best τ=0.590 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54639 | val 2.51884
  Epoch 016 - train 0.48692 | val 3.11516
  Classification -> best τ=0.390 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58985 | val 0.98113
  Epoch 020 - train 0.41345 | val 1.16096
  Classification -> best τ=0.675 (val F1=0.2376)
  Directional -> Accuracy: 0.5962, MCC: 0.1960, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54276 | val 1.58363
  Epoch 017 - train 0.40384 | val 1.43289
  Classification -> best τ=0.710 (val F1=0.2495)
  Directional -> Accuracy: 0.5370, MCC: 0.0644, F1: 0.6269

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64050 | val 0.79411
  Epoch 020 - train 0.49258 | val 0.72235

[I 2026-02-20 02:20:32,347] Trial 83 finished with value: 0.24706637635000941 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.004329384651421221, 'weight_decay': 4.9020497517345135e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.8850022368916746, 'early_stopping_min_delta': 0.006148161064120192}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 026 - train 0.37078 | val 0.75854
  Classification -> best τ=0.395 (val F1=0.3516)
  Directional -> Accuracy: 0.4237, MCC: -0.1499, F1: 0.5405

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24706637635000941
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62581 | val 0.64110
  Epoch 020 - train 0.55696 | val 0.68200
  Epoch 026 - train 0.43153 | val 0.73498
  Classification -> best τ=0.835 (val F1=0.3714)
  Directional -> Accuracy: 0.5200, MCC: -0.0544, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57593 | val 1.25514
  Epoch 016 - train 0.47912 | val 1.26904
  Classification -> best τ=0.440 (val F1=0.1329)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55794 | val 1.20401
  Epoch 017 - train 0.47754 | val 1.40573
  Classification -> best τ=0.545 (val F1=0.3043)
  Directional -> Accuracy: 0.6444, MCC: 0.2971, F1: 0.7241

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64293 | val 1.02156
  Epoch 017 - train 0.57290 | val 1.74015
  Classification -> best τ=0.260 (val F1=0.1716)
  Directional -> Accuracy: 0.4795, MCC: -0.0882, F1: 0.5957

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55104 | val 1.55772
  Epoch 016 - train 0.43813 | val 2.84301
  Classification -> best τ=0.685 (val F1=0.4138)
  Directional -> Accuracy: 0.5102, MCC: 0.0606, F1: 0.2000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45542 | val 1.07115
  Epoch 016 - train 0.32586 | val 1.50418
  Classification -> best τ=0.590 (val F1=0.2737)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62104 | val 1.27552
  Epoch 017 - train 0.46680 | val 2.02533
  Classification -> best τ=0.470 (val F1=0.2452)
  Directional -> Accuracy: 0.5821, MCC: 0.0466, F1: 0.2632

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49345 | val 1.57156
  Epoch 017 - train 0.43849 | val 1.30689
  Classification -> best τ=0.555 (val F1=0.4082)
  Directional -> Accuracy: 0.5122, MCC: 0.0216, F1: 0.4737

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61452 | val 1.27164
  Epoch 017 - train 0.46847 | val 1.30006
  Classification -> best τ=0.500 (val F1=0.2583)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54917 | val 2.04863
  Epoch 016 - train 0.46951 | val 2.87616
  Classification -> best τ=0.575 (val F1=0.1152)
  Directional -> Accuracy: 0.5000, MCC: -0.0044, F1: 0.4516

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60083 | val 1.39330
  Epoch 016 - train 0.51857 | val 1.21738
  Classification -> best τ=0.470 (val F1=0.1883)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63616 | val 1.01301
  Epoch 016 - train 0.51196 | val 1.50709
  Classification -> best τ=0.720 (val F1=0.2215)
  Directional -> Accuracy: 0.6607, MCC: 0.3371, F1: 0.6275

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52523 | val 1.51684
  Epoch 018 - train 0.27523 | val 3.92182
  Classification -> best τ=0.280 (val F1=0.2788)
  Directional -> Accuracy: 0.4082, MCC: -0.2129, F1: 0.5397

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66317 | val 0.63858
  Epoch 020 - train 0.58550 | val 0.70461
  Epoch 028 - train 0.49763 | val 0.69623
  Classification -> best τ=0.310 (val F1=0.4021)
  Directional -> Accuracy: 0.5932, MCC: 0.1979, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54184 | val 0.72381
  Epoch 017 - train 0.46560 | val 1.14618
  Classification -> best τ=0.515 (val F1=0.3061)
  Directional -> Accuracy: 0.6400, MCC: 0.3125, F1: 0.6538

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63386 | val 0.74766
  Epoch 018 - train 0.46298 | val 0.89916
  Classification -> best τ=0.255 (val F1=0.3279)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60642 | val 1.55792
  Epoch 016 - train 0.54679 | val 1.48974
  Classification -> best τ=0.470 (val F1=0.2381)
  Directional -> Accuracy: 0.4737, MCC: -0.2012, F1: 0.6154

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61658 | val 0.90209
  Epoch 016 - train 0.57032 | val 1.64520
  Classification -> best τ=0.445 (val F1=0.2246)
  Directional -> Accuracy: 0.6216, MCC: 0.1792, F1: 0.7143

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61373 | val 0.72822
  Epoch 020 - train 0.53088 | val 1.14208
  Epoch 028 - train 0.42899 | val 1.47442
  Classification -> best τ=0.730 (val F1=0.2288)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61899 | val 0.88242
  Epoch 020 - train 0.48007 | val 0.93114
  Classification -> best τ=0.515 (val F1=0.3060)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54551 | val 1.00136
  Epoch 016 - train 0.40123 | val 0.95879
  Classification -> best τ=0.265 (val F1=0.2227)
  Directional -> Accuracy: 0.6522, MCC: 0.2659, F1: 0.7778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61617 | val 2.25492
  Epoch 016 - train 0.50896 | val 2.52645
  Classification -> best τ=0.860 (val F1=0.0276)
  Directional -> Accuracy: 0.5312, MCC: 0.1072, F1: 0.2105

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61802 | val 1.00975
  Epoch 016 - train 0.50761 | val 0.98617
  Classification -> best τ=0.625 (val F1=0.2611)
  Directional -> Accuracy: 0.4643, MCC: -0.0521, F1: 0.4643

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54793 | val 1.31984
  Epoch 016 - train 0.47673 | val 1.69471
  Classification -> best τ=0.495 (val F1=0.1932)
  Directional -> Accuracy: 0.5312, MCC: 0.0757, F1: 0.5588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48137 | val 1.91491
  Epoch 016 - train 0.39098 | val 2.20312
  Classification -> best τ=0.510 (val F1=0.4079)
  Directional -> Accuracy: 0.4259, MCC: -0.1628, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48713 | val 0.87553
  Epoch 016 - train 0.34813 | val 1.13607
  Classification -> best τ=0.690 (val F1=0.2560)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58387 | val 0.75495
  Epoch 016 - train 0.50075 | val 0.70305
  Classification -> best τ=0.520 (val F1=0.1984)
  Directional -> Accuracy: 0.5510, MCC: 0.0416, F1: 0.6452

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53850 | val 1.09916
  Epoch 016 - train 0.43735 | val 1.51658
  Classification -> best τ=0.535 (val F1=0.1817)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65617 | val 0.70599
  Epoch 019 - train 0.41806 | val 0.82922
  Classification -> best τ=0.475 (val F1=0.3973)
  Directional -> Accuracy: 0.5263, MCC: 0.0644, F1: 0.5263

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49672 | val 2.74279
  Epoch 016 - train 0.38174 | val 3.79102
  Classification -> best τ=0.605 (val F1=0.2193)
  Directional -> Accuracy: 0.4634, MCC: -0.0738, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53737 | val 0.80485
  Epoch 020 - train 0.28223 | val 0.97999
  Classification -> best τ=0.790 (val F1=0.3614)
  Directional -> Accuracy: 0.5122, MCC: 0.1129, F1: 0.3750

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54645 | val 1.02926
  Epoch 016 - train 0.35268 | val 1.38733
  Classification -> best τ=0.495 (val F1=0.2513)
  Directional -> Accuracy: 0.6042, MCC: 0.2425, F1: 0.7077

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58986 | val 0.78397
  Epoch 020 - train 0.50886 | val 1.29084
  Classification -> best τ=0.420 (val F1=0.2999)
  Directional -> Accuracy: 0.5211, MCC: 0.1094, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52974 | val 1.49711
  Epoch 016 - train 0.42614 | val 1.55699
  Classification -> best τ=0.630 (val F1=0.2176)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54164 | val 1.04994
  Epoch 016 - train 0.43769 | val 1.35322
  Classification -> best τ=0.420 (val F1=0.1635)
  Directional -> Accuracy: 0.4769, MCC: 0.0612, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50775 | val 0.87476
  Epoch 017 - train 0.39327 | val 1.55812
  Classification -> best τ=0.370 (val F1=0.3290)
  Directional -> Accuracy: 0.7000, MCC: 0.4035, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57246 | val 1.14405
  Epoch 019 - train 0.37202 | val 1.66384
  Classification -> best τ=0.275 (val F1=0.2608)
  Directional -> Accuracy: 0.4727, MCC: -0.0149, F1: 0.5538

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42856 | val 1.82518
  Epoch 016 - train 0.35400 | val 2.04781
  Classification -> best τ=0.585 (val F1=0.2913)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50008 | val 1.54770
  Epoch 017 - train 0.38981 | val 1.01407
  Classification -> best τ=0.480 (val F1=0.4862)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62400 | val 0.92691
  Epoch 017 - train 0.51238 | val 1.91805
  Classification -> best τ=0.220 (val F1=0.3100)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57421 | val 0.96854
  Epoch 016 - train 0.51938 | val 1.15695
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38702 | val 1.09761
  Epoch 016 - train 0.23667 | val 1.27157
  Classification -> best τ=0.495 (val F1=0.2548)
  Directional -> Accuracy: 0.5122, MCC: -0.2365, F1: 0.6774

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44523 | val 1.27100
  Epoch 016 - train 0.28386 | val 1.54841
  Classification -> best τ=0.490 (val F1=0.5119)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60911 | val 1.12540
  Epoch 016 - train 0.57238 | val 1.31247
  Classification -> best τ=0.425 (val F1=0.2749)
  Directional -> Accuracy: 0.4630, MCC: -0.0434, F1: 0.4082

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56953 | val 2.06404
  Epoch 016 - train 0.46011 | val 3.04221
  Classification -> best τ=0.255 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62924 | val 0.85806
  Epoch 020 - train 0.55079 | val 0.97033
  Epoch 024 - train 0.44826 | val 0.89312
  Classification -> best τ=0.645 (val F1=0.2648)
  Directional -> Accuracy: 0.5962, MCC: 0.1936, F1: 0.6182

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65475 | val 0.73551
  Epoch 018 - train 0.48098 | val 1.05554
  Classification -> best τ=0.440 (val F1=0.1657)
  Directional -> Accuracy: 0.5370, MCC: 0.0644, F1: 0.6269

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61124 | val 0.69668

[I 2026-02-20 02:25:23,324] Trial 84 finished with value: 0.26215943250430557 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.008083915368753152, 'weight_decay': 1.5506663249387919e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.266052457193179, 'early_stopping_min_delta': 0.007933126189254328}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 016 - train 0.54431 | val 0.68679
  Classification -> best τ=0.405 (val F1=0.1124)
  Directional -> Accuracy: 0.4407, MCC: -0.1136, F1: 0.4590

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26215943250430557
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63410 | val 0.94289
  Epoch 020 - train 0.60615 | val 0.87641
  Classification -> best τ=0.710 (val F1=0.3625)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58005 | val 0.90898
  Epoch 016 - train 0.52648 | val 1.14453
  Classification -> best τ=0.550 (val F1=0.1297)
  Directional -> Accuracy: 0.5556, MCC: 0.0636, F1: 0.6429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63659 | val 0.80317
  Epoch 016 - train 0.57596 | val 0.98444
  Classification -> best τ=0.425 (val F1=0.3212)
  Directional -> Accuracy: 0.3913, MCC: -0.2145, F1: 0.3000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64312 | val 1.02395
  Epoch 018 - train 0.58041 | val 1.50430
  Classification -> best τ=0.340 (val F1=0.1971)
  Directional -> Accuracy: 0.5000, MCC: 0.0180, F1: 0.4638

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57170 | val 0.64064
  Epoch 017 - train 0.48887 | val 0.66749
  Classification -> best τ=0.645 (val F1=0.4611)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58547 | val 0.80384
  Epoch 016 - train 0.51986 | val 0.88107
  Classification -> best τ=0.515 (val F1=0.2058)
  Directional -> Accuracy: 0.3913, MCC: -0.2197, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63793 | val 0.96949
  Epoch 016 - train 0.59476 | val 0.95848
  Classification -> best τ=0.345 (val F1=0.2182)
  Directional -> Accuracy: 0.4265, MCC: 0.0751, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54461 | val 0.75154
  Epoch 018 - train 0.51469 | val 0.74338
  Classification -> best τ=0.415 (val F1=0.3632)
  Directional -> Accuracy: 0.4048, MCC: -0.1407, F1: 0.4898

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59498 | val 1.07261
  Epoch 016 - train 0.56128 | val 1.40049
  Classification -> best τ=0.575 (val F1=0.2784)
  Directional -> Accuracy: 0.6667, MCC: 0.3130, F1: 0.5294

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66240 | val 0.71588
  Epoch 019 - train 0.51822 | val 0.88994
  Classification -> best τ=0.470 (val F1=0.2208)
  Directional -> Accuracy: 0.5072, MCC: 0.0265, F1: 0.4848

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65792 | val 0.69026
  Epoch 020 - train 0.60570 | val 0.91750
  Epoch 021 - train 0.54627 | val 0.88229
  Classification -> best τ=0.495 (val F1=0.2534)
  Directional -> Accuracy: 0.5918, MCC: 0.1589, F1: 0.4737

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65060 | val 0.78782
  Epoch 016 - train 0.59824 | val 1.06725
  Classification -> best τ=0.500 (val F1=0.1441)
  Directional -> Accuracy: 0.5965, MCC: 0.1953, F1: 0.6462

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59407 | val 0.81870
  Epoch 018 - train 0.48974 | val 0.82149
  Classification -> best τ=0.215 (val F1=0.2466)
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.6333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68969 | val 0.64005
  Epoch 020 - train 0.56873 | val 0.63966
  Epoch 030 - train 0.52481 | val 0.61413
  Classification -> best τ=0.255 (val F1=0.4530)
  Directional -> Accuracy: 0.5500, MCC: 0.1001, F1: 0.5574

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63222 | val 0.68097
  Epoch 020 - train 0.50263 | val 0.72829
  Epoch 025 - train 0.47153 | val 0.73364
  Classification -> best τ=0.435 (val F1=0.3079)
  Directional -> Accuracy: 0.4902, MCC: 0.1178, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61777 | val 0.87049
  Epoch 018 - train 0.51902 | val 1.13080
  Classification -> best τ=0.565 (val F1=0.3151)
  Directional -> Accuracy: 0.5652, MCC: 0.1389, F1: 0.5588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65855 | val 0.96564
  Epoch 016 - train 0.61198 | val 1.27757
  Classification -> best τ=0.505 (val F1=0.1486)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64688 | val 0.73227
  Epoch 016 - train 0.64538 | val 0.80012
  Classification -> best τ=0.590 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65544 | val 0.71118
  Epoch 018 - train 0.54049 | val 0.70272
  Classification -> best τ=0.690 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55746 | val 0.99414
  Epoch 016 - train 0.53244 | val 0.92505
  Classification -> best τ=0.440 (val F1=0.3219)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67284 | val 0.81950
  Epoch 020 - train 0.59582 | val 1.28179
  Epoch 028 - train 0.54500 | val 1.41039
  Classification -> best τ=0.620 (val F1=0.2941)
  Directional -> Accuracy: 0.3191, MCC: -0.2851, F1: 0.1111

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66895 | val 0.90014
  Epoch 017 - train 0.64010 | val 1.13846
  Classification -> best τ=0.460 (val F1=0.1650)
  Directional -> Accuracy: 0.4923, MCC: -0.0183, F1: 0.5352

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66802 | val 0.79725
  Epoch 017 - train 0.62515 | val 0.96690
  Classification -> best τ=0.545 (val F1=0.3045)
  Directional -> Accuracy: 0.4211, MCC: -0.1021, F1: 0.1951

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63412 | val 1.30604
  Epoch 016 - train 0.58369 | val 1.06635
  Classification -> best τ=0.540 (val F1=0.1393)
  Directional -> Accuracy: 0.5231, MCC: 0.0082, F1: 0.0606

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60758 | val 2.23778
  Epoch 016 - train 0.51967 | val 2.27941
  Classification -> best τ=0.555 (val F1=0.4839)
  Directional -> Accuracy: 0.4727, MCC: 0.0199, F1: 0.2162

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51079 | val 3.57587
  Epoch 016 - train 0.47085 | val 4.01596
  Classification -> best τ=0.620 (val F1=0.2318)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66324 | val 0.89346
  Epoch 016 - train 0.63474 | val 0.80761
  Classification -> best τ=0.500 (val F1=0.1353)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.6316

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60851 | val 1.14293
  Epoch 016 - train 0.49814 | val 1.53239
  Classification -> best τ=0.310 (val F1=0.2665)
  Directional -> Accuracy: 0.6071, MCC: 0.2804, F1: 0.5417

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60948 | val 1.33102
  Epoch 016 - train 0.53634 | val 1.38435
  Classification -> best τ=0.495 (val F1=0.2267)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62271 | val 0.76006
  Epoch 017 - train 0.58293 | val 0.77071
  Classification -> best τ=0.515 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70822 | val 1.19862
  Epoch 016 - train 0.65117 | val 1.12382
  Classification -> best τ=0.430 (val F1=0.2042)
  Directional -> Accuracy: 0.5476, MCC: 0.0677, F1: 0.6275

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57451 | val 0.80794
  Epoch 016 - train 0.44190 | val 1.00689
  Classification -> best τ=0.555 (val F1=0.3574)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66587 | val 0.77166
  Epoch 019 - train 0.63367 | val 0.88988
  Classification -> best τ=0.345 (val F1=0.2836)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58817 | val 1.79956
  Epoch 016 - train 0.48231 | val 2.02912
  Classification -> best τ=0.640 (val F1=0.2804)
  Directional -> Accuracy: 0.5116, MCC: 0.0288, F1: 0.5532

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59931 | val 1.42202
  Epoch 016 - train 0.54643 | val 1.59139
  Classification -> best τ=0.155 (val F1=0.3603)
  Directional -> Accuracy: 0.5455, MCC: 0.1658, F1: 0.4828

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59468 | val 0.70254
  Epoch 019 - train 0.41554 | val 0.89798
  Classification -> best τ=0.495 (val F1=0.3218)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62385 | val 0.67640
  Epoch 020 - train 0.50808 | val 1.01352
  Epoch 025 - train 0.46124 | val 0.98520
  Classification -> best τ=0.405 (val F1=0.2804)
  Directional -> Accuracy: 0.5000, MCC: -0.0051, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53495 | val 0.69225
  Epoch 017 - train 0.43715 | val 0.75656
  Classification -> best τ=0.445 (val F1=0.4524)
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.5769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60780 | val 0.92827
  Epoch 020 - train 0.47546 | val 1.29318
  Epoch 022 - train 0.47679 | val 1.32279
  Classification -> best τ=0.875 (val F1=0.2392)
  Directional -> Accuracy: 0.3958, MCC: -0.1232, F1: 0.4082

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58748 | val 0.94003
  Epoch 016 - train 0.54620 | val 1.27642
  Classification -> best τ=0.460 (val F1=0.2102)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60384 | val 0.81926
  Epoch 016 - train 0.59674 | val 0.79686
  Classification -> best τ=0.465 (val F1=0.1291)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53404 | val 0.98921
  Epoch 016 - train 0.53091 | val 1.13406
  Classification -> best τ=0.685 (val F1=0.3612)
  Directional -> Accuracy: 0.3810, MCC: -0.2582, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59393 | val 0.70378
  Epoch 020 - train 0.40269 | val 0.81535
  Epoch 027 - train 0.23509 | val 0.57563
  Classification -> best τ=0.310 (val F1=0.6080)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68690 | val 0.73240
  Epoch 020 - train 0.64373 | val 0.87443
  Epoch 022 - train 0.62873 | val 0.88651
  Classification -> best τ=0.490 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59571 | val 1.07798
  Epoch 020 - train 0.47537 | val 1.88293
  Epoch 024 - train 0.41944 | val 1.84096
  Classification -> best τ=0.835 (val F1=0.3988)
  Directional -> Accuracy: 0.5714, MCC: 0.1920, F1: 0.6571

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65797 | val 1.21238
  Epoch 018 - train 0.57590 | val 1.51945
  Classification -> best τ=0.485 (val F1=0.1126)
  Directional -> Accuracy: 0.5849, MCC: 0.1729, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62113 | val 2.26845
  Epoch 016 - train 0.56646 | val 3.34660
  Classification -> best τ=0.805 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67533 | val 0.74826

[I 2026-02-20 02:29:22,187] Trial 85 finished with value: 0.2771020396331076 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.007695490032385543, 'weight_decay': 1.5655827008423713e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.266460621000659, 'early_stopping_min_delta': 0.008450694954420645}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 018 - train 0.59671 | val 0.71370
  Classification -> best τ=0.490 (val F1=0.3461)
  Directional -> Accuracy: 0.5667, MCC: 0.1390, F1: 0.3810

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2771020396331076
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65357 | val 1.29150
  Epoch 017 - train 0.64377 | val 0.77818
  Classification -> best τ=0.415 (val F1=0.2176)
  Directional -> Accuracy: 0.5000, MCC: 0.0169, F1: 0.5128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65237 | val 0.72151
  Epoch 016 - train 0.60194 | val 0.70707
  Classification -> best τ=0.465 (val F1=0.2670)
  Directional -> Accuracy: 0.5333, MCC: -0.1089, F1: 0.6866

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66582 | val 0.63973
  Epoch 020 - train 0.58296 | val 0.68806
  Epoch 021 - train 0.55431 | val 0.65765
  Classification -> best τ=0.635 (val F1=0.4593)
  Directional -> Accuracy: 0.6087, MCC: 0.2137, F1: 0.6400

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67542 | val 0.81407
  Epoch 019 - train 0.61135 | val 1.39746
  Classification -> best τ=0.450 (val F1=0.2352)
  Directional -> Accuracy: 0.4595, MCC: -0.0635, F1: 0.4118

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59831 | val 0.80418
  Epoch 017 - train 0.54706 | val 1.14939
  Classification -> best τ=0.500 (val F1=0.4862)
  Directional -> Accuracy: 0.5600, MCC: 0.2316, F1: 0.3125

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60574 | val 0.70982
  Epoch 016 - train 0.54961 | val 0.71300
  Classification -> best τ=0.515 (val F1=0.0358)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68267 | val 0.69060
  Epoch 020 - train 0.62641 | val 0.79476
  Epoch 022 - train 0.62801 | val 0.79993
  Classification -> best τ=0.460 (val F1=0.3353)
  Directional -> Accuracy: 0.4559, MCC: 0.0250, F1: 0.5316

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62355 | val 1.06112
  Epoch 020 - train 0.56860 | val 2.91884
  Epoch 027 - train 0.41285 | val 3.51048
  Classification -> best τ=0.450 (val F1=0.2453)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.4865

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64997 | val 0.85666
  Epoch 020 - train 0.59136 | val 0.73333
  Epoch 026 - train 0.55826 | val 0.75047
  Classification -> best τ=0.435 (val F1=0.3376)
  Directional -> Accuracy: 0.4792, MCC: -0.1422, F1: 0.1935

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62493 | val 1.26944
  Epoch 016 - train 0.61301 | val 1.31130
  Classification -> best τ=0.495 (val F1=0.2216)
  Directional -> Accuracy: 0.5217, MCC: 0.0511, F1: 0.4923

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67468 | val 0.76426
  Epoch 020 - train 0.63428 | val 0.90284
  Epoch 023 - train 0.60184 | val 0.96685
  Classification -> best τ=0.445 (val F1=0.2867)
  Directional -> Accuracy: 0.4694, MCC: 0.0332, F1: 0.6061

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64927 | val 0.93505
  Epoch 018 - train 0.59820 | val 0.72789
  Classification -> best τ=0.675 (val F1=0.2858)
  Directional -> Accuracy: 0.4912, MCC: -0.0150, F1: 0.4528

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56310 | val 0.93524
  Epoch 016 - train 0.52647 | val 0.89608
  Classification -> best τ=0.505 (val F1=0.2636)
  Directional -> Accuracy: 0.5000, MCC: 0.0588, F1: 0.5882

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68448 | val 0.81864
  Epoch 016 - train 0.65587 | val 0.67824
  Classification -> best τ=0.365 (val F1=0.1363)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64581 | val 0.90027
  Epoch 016 - train 0.58780 | val 0.71761
  Classification -> best τ=0.505 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66623 | val 0.65220
  Epoch 020 - train 0.56698 | val 0.76451
  Epoch 024 - train 0.58206 | val 0.83758
  Classification -> best τ=0.765 (val F1=0.3307)
  Directional -> Accuracy: 0.5072, MCC: 0.0874, F1: 0.2917

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65867 | val 0.82638
  Epoch 016 - train 0.62951 | val 0.95151
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63909 | val 0.74568
  Epoch 017 - train 0.62725 | val 1.05825
  Classification -> best τ=0.540 (val F1=0.1243)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64302 | val 0.76719
  Epoch 016 - train 0.61035 | val 0.85817
  Classification -> best τ=0.480 (val F1=0.3140)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66011 | val 0.80259
  Epoch 018 - train 0.55474 | val 1.00601
  Classification -> best τ=0.540 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65011 | val 0.75859
  Epoch 016 - train 0.62801 | val 0.76903
  Classification -> best τ=0.510 (val F1=0.2247)
  Directional -> Accuracy: 0.5532, MCC: -0.0497, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66318 | val 1.86185
  Epoch 016 - train 0.64170 | val 2.73872
  Classification -> best τ=0.575 (val F1=0.1709)
  Directional -> Accuracy: 0.5692, MCC: 0.1431, F1: 0.5333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67096 | val 1.20902
  Epoch 019 - train 0.61567 | val 2.01256
  Classification -> best τ=0.335 (val F1=0.3938)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67069 | val 0.75634
  Epoch 016 - train 0.64526 | val 0.73535
  Classification -> best τ=0.470 (val F1=0.1348)
  Directional -> Accuracy: 0.5231, MCC: 0.0844, F1: 0.6173

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65245 | val 1.10022
  Epoch 016 - train 0.58711 | val 1.36261
  Classification -> best τ=0.470 (val F1=0.3750)
  Directional -> Accuracy: 0.4909, MCC: -0.1617, F1: 0.6500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62261 | val 2.39887
  Epoch 016 - train 0.56423 | val 3.52012
  Classification -> best τ=0.680 (val F1=0.2726)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62622 | val 0.69351
  Epoch 018 - train 0.60564 | val 0.69328
  Classification -> best τ=0.530 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.1481

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68584 | val 0.74132
  Epoch 020 - train 0.59444 | val 0.94561
  Epoch 023 - train 0.57028 | val 0.98710
  Classification -> best τ=0.430 (val F1=0.2999)
  Directional -> Accuracy: 0.5536, MCC: 0.2640, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63088 | val 1.08926
  Epoch 017 - train 0.57968 | val 1.27533
  Classification -> best τ=0.510 (val F1=0.1918)
  Directional -> Accuracy: 0.5250, MCC: 0.0056, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63629 | val 0.80439
  Epoch 016 - train 0.62817 | val 0.87497
  Classification -> best τ=0.565 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70474 | val 0.77549
  Epoch 020 - train 0.61062 | val 1.04009
  Epoch 021 - train 0.62404 | val 1.06343
  Classification -> best τ=0.545 (val F1=0.2844)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57830 | val 0.72977
  Epoch 018 - train 0.53660 | val 0.83579
  Classification -> best τ=0.430 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65811 | val 0.77088
  Epoch 020 - train 0.56577 | val 1.22730
  Epoch 021 - train 0.61090 | val 1.19056
  Classification -> best τ=0.420 (val F1=0.3366)
  Directional -> Accuracy: 0.5694, MCC: 0.1066, F1: 0.6517

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67426 | val 0.90580
  Epoch 016 - train 0.58490 | val 1.40234
  Classification -> best τ=0.500 (val F1=0.2632)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65243 | val 0.78878
  Epoch 017 - train 0.59888 | val 0.87360
  Classification -> best τ=0.270 (val F1=0.4781)
  Directional -> Accuracy: 0.5758, MCC: 0.1236, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63702 | val 0.84200
  Epoch 016 - train 0.56357 | val 0.76327
  Classification -> best τ=0.455 (val F1=0.2439)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63756 | val 0.77395
  Epoch 017 - train 0.54563 | val 1.20649
  Classification -> best τ=0.355 (val F1=0.2110)
  Directional -> Accuracy: 0.4821, MCC: -0.0083, F1: 0.5538

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58417 | val 1.38700
  Epoch 016 - train 0.54506 | val 1.91194
  Classification -> best τ=0.330 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64445 | val 0.69870
  Epoch 020 - train 0.52304 | val 0.67425
  Epoch 024 - train 0.54532 | val 0.69692
  Classification -> best τ=0.395 (val F1=0.4855)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65367 | val 0.72655
  Epoch 016 - train 0.58597 | val 0.83681
  Classification -> best τ=0.560 (val F1=0.4328)
  Directional -> Accuracy: 0.5405, MCC: 0.0782, F1: 0.5000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69290 | val 0.68378
  Epoch 020 - train 0.65356 | val 0.74155
  Epoch 025 - train 0.63983 | val 0.74125
  Classification -> best τ=0.515 (val F1=0.3190)
  Directional -> Accuracy: 0.5111, MCC: 0.0349, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63239 | val 1.01540
  Epoch 016 - train 0.60759 | val 1.10851
  Classification -> best τ=0.600 (val F1=0.4082)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62340 | val 1.39449
  Epoch 016 - train 0.58965 | val 1.84577
  Classification -> best τ=0.660 (val F1=0.1371)
  Directional -> Accuracy: 0.6042, MCC: 0.0457, F1: 0.2400

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68375 | val 1.27265
  Epoch 016 - train 0.66296 | val 1.82919
  Classification -> best τ=0.415 (val F1=0.1997)
  Directional -> Accuracy: 0.4909, MCC: -0.0199, F1: 0.5172

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63603 | val 1.39553
  Epoch 019 - train 0.56060 | val 1.71811
  Classification -> best τ=0.860 (val F1=0.2680)
  Directional -> Accuracy: 0.5714, MCC: 0.1476, F1: 0.5862

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69594 | val 0.71506
  Epoch 018 - train 0.64730 | val 0.71636
  Classification -> best τ=0.580 (val F1=0.0593)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59497 | val 1.45658
  Epoch 016 - train 0.59247 | val 2.22912
  Classification -> best τ=0.760 (val F1=0.1811)
  Directional -> Accuracy: 0.5455, MCC: 0.1437, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67572 | val 0.76886

[I 2026-02-20 02:32:32,108] Trial 86 finished with value: 0.2711103103995798 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.006681674399816155, 'weight_decay': 3.6762477780169207e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.3184992887617657, 'early_stopping_min_delta': 0.00784915720473226}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 019 - train 0.63378 | val 0.69074
  Classification -> best τ=0.465 (val F1=0.2810)
  Directional -> Accuracy: 0.5500, MCC: 0.0955, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2711103103995798
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72929 | val 0.68576
  Epoch 018 - train 0.70388 | val 0.68339
  Classification -> best τ=0.425 (val F1=0.0933)
  Directional -> Accuracy: 0.5000, MCC: 0.1653, F1: 0.6346

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70935 | val 0.71895
  Epoch 016 - train 0.71144 | val 0.72037
  Classification -> best τ=0.500 (val F1=0.0492)
  Directional -> Accuracy: 0.4000, MCC: -0.1419, F1: 0.2703

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.76163 | val 0.72089
  Epoch 016 - train 0.78363 | val 0.72072
  Classification -> best τ=0.465 (val F1=0.1529)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70640 | val 0.68744
  Epoch 016 - train 0.71770 | val 0.69044
  Classification -> best τ=0.540 (val F1=0.1194)
  Directional -> Accuracy: 0.4865, MCC: -0.0031, F1: 0.4242

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70288 | val 0.66215
  Epoch 020 - train 0.69494 | val 0.66017
  Epoch 021 - train 0.70556 | val 0.66105
  Classification -> best τ=0.530 (val F1=0.3984)
  Directional -> Accuracy: 0.5400, MCC: 0.0746, F1: 0.5818

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70154 | val 0.78340
  Epoch 016 - train 0.68493 | val 0.80151
  Classification -> best τ=0.510 (val F1=0.0564)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.1538

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73710 | val 0.73167
  Epoch 016 - train 0.72006 | val 0.72700
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72444 | val 0.82516
  Epoch 016 - train 0.72057 | val 0.83432
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70536 | val 0.73846
  Epoch 016 - train 0.70347 | val 0.73876
  Classification -> best τ=0.515 (val F1=0.1411)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71052 | val 0.69663
  Epoch 016 - train 0.71612 | val 0.69608
  Classification -> best τ=0.460 (val F1=0.1950)
  Directional -> Accuracy: 0.4203, MCC: -0.0279, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69843 | val 0.67191
  Epoch 019 - train 0.69290 | val 0.67382
  Classification -> best τ=0.485 (val F1=0.2670)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71899 | val 0.90155
  Epoch 016 - train 0.72333 | val 0.90410
  Classification -> best τ=0.555 (val F1=0.0571)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69733 | val 0.69006
  Epoch 016 - train 0.71453 | val 0.68929
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70977 | val 0.65155
  Epoch 018 - train 0.69394 | val 0.65295
  Classification -> best τ=0.405 (val F1=0.2344)
  Directional -> Accuracy: 0.5500, MCC: 0.1214, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71118 | val 0.79290
  Epoch 016 - train 0.71499 | val 0.79895
  Classification -> best τ=0.560 (val F1=0.1925)
  Directional -> Accuracy: 0.5294, MCC: 0.1742, F1: 0.6364

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71573 | val 0.78782
  Epoch 016 - train 0.71868 | val 0.78599
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70319 | val 0.74794
  Epoch 016 - train 0.69919 | val 0.74541
  Classification -> best τ=0.455 (val F1=0.3038)
  Directional -> Accuracy: 0.6552, MCC: 0.2025, F1: 0.7674

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72328 | val 0.70384
  Epoch 016 - train 0.71592 | val 0.70380
  Classification -> best τ=0.490 (val F1=0.1769)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72188 | val 0.69770
  Epoch 016 - train 0.70654 | val 0.70052
  Classification -> best τ=0.495 (val F1=0.1809)
  Directional -> Accuracy: 0.4531, MCC: -0.0757, F1: 0.4615

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71390 | val 0.69136
  Epoch 016 - train 0.70819 | val 0.69221
  Classification -> best τ=0.500 (val F1=0.1839)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70726 | val 0.74533
  Epoch 016 - train 0.69570 | val 0.74151
  Classification -> best τ=0.560 (val F1=0.2259)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.73781 | val 0.75851
  Epoch 016 - train 0.74925 | val 0.75634
  Classification -> best τ=0.475 (val F1=0.1482)
  Directional -> Accuracy: 0.4769, MCC: -0.0442, F1: 0.3200

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71785 | val 0.75887
  Epoch 016 - train 0.71133 | val 0.76474
  Classification -> best τ=0.500 (val F1=0.0187)
  Directional -> Accuracy: 0.4561, MCC: -0.1198, F1: 0.5373

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.73478 | val 0.77686
  Epoch 016 - train 0.72146 | val 0.77664
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69626 | val 0.70470
  Epoch 016 - train 0.69999 | val 0.70561
  Classification -> best τ=0.540 (val F1=0.0529)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71439 | val 0.70801
  Epoch 016 - train 0.67207 | val 0.71099
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67912 | val 0.68766
  Epoch 016 - train 0.68328 | val 0.68874
  Classification -> best τ=0.525 (val F1=0.2810)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69778 | val 0.69458
  Epoch 016 - train 0.72352 | val 0.69666
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74146 | val 0.80453
  Epoch 016 - train 0.72784 | val 0.80425
  Classification -> best τ=0.480 (val F1=0.1870)
  Directional -> Accuracy: 0.4750, MCC: 0.0198, F1: 0.2759

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68764 | val 0.70286
  Epoch 016 - train 0.68871 | val 0.70147
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71147 | val 0.75409
  Epoch 016 - train 0.70180 | val 0.75218
  Classification -> best τ=0.470 (val F1=0.2575)
  Directional -> Accuracy: 0.6905, MCC: 0.4175, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70410 | val 0.68623
  Epoch 018 - train 0.71791 | val 0.68375
  Classification -> best τ=0.560 (val F1=0.4339)
  Directional -> Accuracy: 0.4898, MCC: -0.1311, F1: 0.6479

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71886 | val 0.65391
  Epoch 019 - train 0.71418 | val 0.65383
  Classification -> best τ=0.420 (val F1=0.3434)
  Directional -> Accuracy: 0.5833, MCC: 0.1617, F1: 0.6154

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.73430 | val 0.67265
  Epoch 016 - train 0.70983 | val 0.67292
  Classification -> best τ=0.460 (val F1=0.2151)
  Directional -> Accuracy: 0.6047, MCC: 0.2104, F1: 0.5405

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70821 | val 0.68809
  Epoch 016 - train 0.69292 | val 0.68226
  Classification -> best τ=0.510 (val F1=0.2566)
  Directional -> Accuracy: 0.4394, MCC: -0.0374, F1: 0.2745

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73090 | val 0.70964
  Epoch 016 - train 0.72228 | val 0.71074
  Classification -> best τ=0.470 (val F1=0.1715)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70587 | val 0.67824
  Epoch 016 - train 0.72004 | val 0.67875
  Classification -> best τ=0.475 (val F1=0.1913)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68431 | val 0.83386
  Epoch 016 - train 0.69300 | val 0.82967
  Classification -> best τ=0.450 (val F1=0.2474)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70699 | val 0.67204
  Epoch 020 - train 0.72372 | val 0.66788
  Epoch 029 - train 0.69953 | val 0.66954
  Classification -> best τ=0.550 (val F1=0.4306)
  Directional -> Accuracy: 0.6667, MCC: 0.2023, F1: 0.3846

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71092 | val 0.67766
  Epoch 018 - train 0.70895 | val 0.67582
  Classification -> best τ=0.505 (val F1=0.3446)
  Directional -> Accuracy: 0.5135, MCC: 0.1622, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.73410 | val 0.82951
  Epoch 016 - train 0.73419 | val 0.82015
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70010 | val 0.67250
  Epoch 020 - train 0.72043 | val 0.67226
  Epoch 029 - train 0.71498 | val 0.67242
  Classification -> best τ=0.405 (val F1=0.2722)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71947 | val 0.75905
  Epoch 016 - train 0.69500 | val 0.76382
  Classification -> best τ=0.455 (val F1=0.3752)
  Directional -> Accuracy: 0.3542, MCC: -0.2711, F1: 0.3111

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70408 | val 0.83152
  Epoch 016 - train 0.73173 | val 0.83192
  Classification -> best τ=0.470 (val F1=0.0379)
  Directional -> Accuracy: 0.4909, MCC: 0.0402, F1: 0.3333

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70175 | val 0.67467
  Epoch 019 - train 0.70932 | val 0.67233
  Classification -> best τ=0.390 (val F1=0.2187)
  Directional -> Accuracy: 0.5000, MCC: -0.1301, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.73672 | val 0.76494
  Epoch 016 - train 0.72952 | val 0.76890
  Classification -> best τ=0.470 (val F1=0.1341)
  Directional -> Accuracy: 0.4340, MCC: -0.1423, F1: 0.2500

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71855 | val 0.71274
  Epoch 016 - train 0.70762 | val 0.71625
  Classification -> best τ=0.570 (val F1=0.1763)
  Directional -> Accuracy: 0.5273, MCC: 0.1093, F1: 0.3500

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69811 | val 0.67748
  Epoch 020 - train 0.69096 | val 0.67913

[I 2026-02-20 02:35:26,404] Trial 87 finished with value: 0.16669001642444448 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 1.134161805307433e-06, 'weight_decay': 4.009049632460966e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.3332741559551848, 'early_stopping_min_delta': 0.008766913120362213}. Best is trial 47 with value: 0.2781229548444326.

  Epoch 024 - train 0.69714 | val 0.67959
  Classification -> best τ=0.370 (val F1=0.1790)
  Directional -> Accuracy: 0.6000, MCC: 0.2086, F1: 0.6250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.16669001642444448
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64656 | val 0.77766
  Epoch 011 - train 0.63811 | val 1.00916
  Classification -> best τ=0.560 (val F1=0.2082)
  Directional -> Accuracy: 0.5921, MCC: 0.1528, F1: 0.4151

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60925 | val 0.69543
  Epoch 017 - train 0.60692 | val 0.73580
  Classification -> best τ=0.385 (val F1=0.2670)
  Directional -> Accuracy: 0.6222, MCC: 0.1924, F1: 0.7213

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64473 | val 0.67713
  Epoch 019 - train 0.62071 | val 0.81206
  Classification -> best τ=0.525 (val F1=0.3589)
  Directional -> Accuracy: 0.5000, MCC: 0.0038, F1: 0.4889

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65716 | val 1.01474
  Epoch 015 - train 0.63927 | val 0.81628
  Classification -> best τ=0.440 (val F1=0.2377)
  Directional -> Accuracy: 0.6081, MCC: 0.2377, F1: 0.7238

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60451 | val 1.53227
  Epoch 012 - train 0.59126 | val 2.32825
  Classification -> best τ=0.490 (val F1=0.4139)
  Directional -> Accuracy: 0.6800, MCC: 0.3870, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63021 | val 0.74231
  Epoch 013 - train 0.61303 | val 0.82481
  Classification -> best τ=0.580 (val F1=0.1684)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67565 | val 0.74784
  Epoch 011 - train 0.66753 | val 0.73335
  Classification -> best τ=0.600 (val F1=0.3239)
  Directional -> Accuracy: 0.5882, MCC: 0.0378, F1: 0.2222

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60850 | val 0.55961
  Epoch 017 - train 0.54649 | val 0.66756
  Classification -> best τ=0.280 (val F1=0.2075)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66921 | val 0.70414
  Epoch 014 - train 0.64881 | val 0.78311
  Classification -> best τ=0.565 (val F1=0.4748)
  Directional -> Accuracy: 0.6250, MCC: 0.2381, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67043 | val 0.72348
  Epoch 012 - train 0.63423 | val 0.71840
  Classification -> best τ=0.410 (val F1=0.3314)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64442 | val 1.21796
  Epoch 011 - train 0.65445 | val 0.87088
  Classification -> best τ=0.555 (val F1=0.1356)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65436 | val 0.76833
  Epoch 013 - train 0.63891 | val 0.79933
  Classification -> best τ=0.565 (val F1=0.2874)
  Directional -> Accuracy: 0.4737, MCC: -0.0530, F1: 0.4828

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63635 | val 0.73577
  Epoch 020 - train 0.59204 | val 0.73141
  Epoch 030 - train 0.51824 | val 0.75044
  Epoch 031 - train 0.47517 | val 0.77260
  Classification -> best τ=0.490 (val F1=0.3536)
  Directional -> Accuracy: 0.3571, MCC: -0.2706, F1: 0.4255

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69039 | val 0.66001
  Epoch 012 - train 0.67654 | val 0.66705
  Classification -> best τ=0.310 (val F1=0.2662)
  Directional -> Accuracy: 0.4833, MCC: -0.0335, F1: 0.5079

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60459 | val 0.74808
  Epoch 011 - train 0.59961 | val 0.80216
  Classification -> best τ=0.535 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69887 | val 0.64086
  Epoch 019 - train 0.64565 | val 0.71041
  Classification -> best τ=0.545 (val F1=0.3570)
  Directional -> Accuracy: 0.6087, MCC: 0.2150, F1: 0.6301

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67938 | val 0.71716
  Epoch 013 - train 0.65036 | val 0.71970
  Classification -> best τ=0.655 (val F1=0.2651)
  Directional -> Accuracy: 0.3103, MCC: -0.3482, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65830 | val 0.77404
  Epoch 011 - train 0.66018 | val 0.76227
  Classification -> best τ=0.390 (val F1=0.1605)
  Directional -> Accuracy: 0.5467, MCC: 0.0660, F1: 0.6136

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67192 | val 0.78689
  Epoch 011 - train 0.62039 | val 0.70887
  Classification -> best τ=0.590 (val F1=0.1809)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61257 | val 0.85660
  Epoch 011 - train 0.61003 | val 0.95381
  Classification -> best τ=0.430 (val F1=0.2672)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64513 | val 0.76345
  Epoch 011 - train 0.64384 | val 0.79985
  Classification -> best τ=0.570 (val F1=0.3678)
  Directional -> Accuracy: 0.4894, MCC: -0.0373, F1: 0.5556

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68160 | val 1.17638
  Epoch 011 - train 0.66883 | val 1.19287
  Classification -> best τ=0.560 (val F1=0.2546)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67848 | val 0.76196
  Epoch 018 - train 0.60739 | val 1.10549
  Classification -> best τ=0.465 (val F1=0.2750)
  Directional -> Accuracy: 0.4737, MCC: -0.0169, F1: 0.4231

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63072 | val 0.80428
  Epoch 011 - train 0.61958 | val 0.79070
  Classification -> best τ=0.530 (val F1=0.1741)
  Directional -> Accuracy: 0.5692, MCC: 0.1426, F1: 0.5758

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65213 | val 0.83188
  Epoch 013 - train 0.61521 | val 0.95028
  Classification -> best τ=0.485 (val F1=0.3751)
  Directional -> Accuracy: 0.5455, MCC: 0.0533, F1: 0.6479

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65570 | val 1.57856
  Epoch 011 - train 0.61527 | val 1.61833
  Classification -> best τ=0.750 (val F1=0.2318)
  Directional -> Accuracy: 0.5556, MCC: 0.0507, F1: 0.3750

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69005 | val 0.75816
  Epoch 011 - train 0.65763 | val 0.73979
  Classification -> best τ=0.500 (val F1=0.2107)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65397 | val 0.71981
  Epoch 017 - train 0.58231 | val 0.77330
  Classification -> best τ=0.265 (val F1=0.3475)
  Directional -> Accuracy: 0.5179, MCC: 0.1037, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58041 | val 0.98120
  Epoch 012 - train 0.57171 | val 1.07588
  Classification -> best τ=0.500 (val F1=0.4099)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66254 | val 0.68497
  Epoch 011 - train 0.63506 | val 0.73813
  Classification -> best τ=0.515 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.2033, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66609 | val 0.73425
  Epoch 015 - train 0.66020 | val 0.89274
  Classification -> best τ=0.585 (val F1=0.1231)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63827 | val 0.86840
  Epoch 014 - train 0.69011 | val 0.71482
  Classification -> best τ=0.515 (val F1=0.3541)
  Directional -> Accuracy: 0.5102, MCC: -0.1358, F1: 0.6757

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65577 | val 0.65023
  Epoch 020 - train 0.65890 | val 0.80195
  Epoch 024 - train 0.60227 | val 0.75551
  Classification -> best τ=0.440 (val F1=0.3681)
  Directional -> Accuracy: 0.5417, MCC: 0.1155, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68407 | val 1.03796
  Epoch 013 - train 0.66829 | val 0.99355
  Classification -> best τ=0.410 (val F1=0.3575)
  Directional -> Accuracy: 0.6047, MCC: 0.2270, F1: 0.6531

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67063 | val 0.80390
  Epoch 015 - train 0.62226 | val 1.01098
  Classification -> best τ=0.290 (val F1=0.3603)
  Directional -> Accuracy: 0.6061, MCC: 0.1796, F1: 0.6750

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59549 | val 1.03074
  Epoch 015 - train 0.58321 | val 1.54728
  Classification -> best τ=0.455 (val F1=0.2658)
  Directional -> Accuracy: 0.6429, MCC: 0.2860, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57475 | val 1.91733
  Epoch 011 - train 0.54762 | val 1.92427
  Classification -> best τ=0.375 (val F1=0.2614)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62031 | val 1.48338
  Epoch 013 - train 0.53482 | val 2.04091
  Classification -> best τ=0.515 (val F1=0.2268)
  Directional -> Accuracy: 0.3696, MCC: -0.1859, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65408 | val 0.67065
  Epoch 013 - train 0.62613 | val 0.64244
  Classification -> best τ=0.510 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61309 | val 0.67711
  Epoch 020 - train 0.50359 | val 0.71934
  Epoch 022 - train 0.51746 | val 0.72389
  Classification -> best τ=0.385 (val F1=0.3563)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64801 | val 0.69405
  Epoch 014 - train 0.62724 | val 0.71911
  Classification -> best τ=0.480 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: 0.1059, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63109 | val 1.16652
  Epoch 016 - train 0.62744 | val 1.15585
  Classification -> best τ=0.635 (val F1=0.5230)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63624 | val 0.68237
  Epoch 016 - train 0.60106 | val 1.09599
  Classification -> best τ=0.760 (val F1=0.3300)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66422 | val 0.73016
  Epoch 011 - train 0.66453 | val 0.76440
  Classification -> best τ=0.700 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62647 | val 1.56363
  Epoch 015 - train 0.57891 | val 1.63214
  Classification -> best τ=0.640 (val F1=0.2504)
  Directional -> Accuracy: 0.4821, MCC: -0.0226, F1: 0.5672

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67046 | val 0.69061
  Epoch 017 - train 0.66028 | val 0.69465
  Classification -> best τ=0.565 (val F1=0.2743)
  Directional -> Accuracy: 0.5660, MCC: 0.1325, F1: 0.5660

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61947 | val 1.16161
  Epoch 014 - train 0.58214 | val 1.69309
  Classification -> best τ=0.525 (val F1=0.2132)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65843 | val 0.69659

[I 2026-02-20 02:37:55,793] Trial 88 finished with value: 0.2868500347884126 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.00631898474836459, 'weight_decay': 9.074076657517129e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1257758684245502, 'early_stopping_min_delta': 0.009212044854634921}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.64616 | val 0.67950
  Classification -> best τ=0.480 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0167, F1: 0.2927

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2868500347884126
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63576 | val 0.81017
  Epoch 012 - train 0.60909 | val 0.76129
  Classification -> best τ=0.715 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59328 | val 0.81698
  Epoch 011 - train 0.59422 | val 0.77306
  Classification -> best τ=0.600 (val F1=0.2523)
  Directional -> Accuracy: 0.6667, MCC: 0.3050, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67932 | val 0.67937
  Epoch 014 - train 0.62967 | val 0.75325
  Classification -> best τ=0.355 (val F1=0.4500)
  Directional -> Accuracy: 0.5652, MCC: 0.1260, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66766 | val 1.09939
  Epoch 011 - train 0.65321 | val 1.32637
  Classification -> best τ=0.250 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61846 | val 0.71209
  Epoch 020 - train 0.49414 | val 0.90424
  Epoch 021 - train 0.45452 | val 0.87138
  Classification -> best τ=0.565 (val F1=0.4862)
  Directional -> Accuracy: 0.7200, MCC: 0.4484, F1: 0.7083

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59120 | val 0.73996
  Epoch 011 - train 0.58209 | val 0.80139
  Classification -> best τ=0.535 (val F1=0.2899)
  Directional -> Accuracy: 0.5217, MCC: 0.0229, F1: 0.3125

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62999 | val 0.96215
  Epoch 011 - train 0.62618 | val 1.05721
  Classification -> best τ=0.450 (val F1=0.2437)
  Directional -> Accuracy: 0.5294, MCC: 0.1521, F1: 0.5676

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59775 | val 2.29463
  Epoch 011 - train 0.58759 | val 2.58007
  Classification -> best τ=0.525 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61844 | val 1.10163
  Epoch 011 - train 0.61112 | val 1.10667
  Classification -> best τ=0.615 (val F1=0.2764)
  Directional -> Accuracy: 0.6458, MCC: 0.2656, F1: 0.5143

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58895 | val 0.83678
  Epoch 012 - train 0.58518 | val 0.76319
  Classification -> best τ=0.295 (val F1=0.2293)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64215 | val 0.81269
  Epoch 012 - train 0.64864 | val 0.70681
  Classification -> best τ=0.400 (val F1=0.3322)
  Directional -> Accuracy: 0.5510, MCC: 0.0453, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66372 | val 0.83471
  Epoch 011 - train 0.65680 | val 0.82076
  Classification -> best τ=0.495 (val F1=0.1044)
  Directional -> Accuracy: 0.5263, MCC: 0.0770, F1: 0.3415

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56592 | val 1.15971
  Epoch 011 - train 0.56505 | val 1.14542
  Classification -> best τ=0.475 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: -0.1972, F1: 0.1481

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66197 | val 0.68129
  Epoch 012 - train 0.66530 | val 0.67646
  Classification -> best τ=0.345 (val F1=0.3367)
  Directional -> Accuracy: 0.5167, MCC: 0.0765, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61271 | val 0.77549
  Epoch 011 - train 0.59416 | val 0.76853
  Classification -> best τ=0.600 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62534 | val 0.71968
  Epoch 014 - train 0.60464 | val 0.69025
  Classification -> best τ=0.440 (val F1=0.3589)
  Directional -> Accuracy: 0.4928, MCC: -0.0220, F1: 0.5333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60507 | val 1.52424
  Epoch 011 - train 0.62966 | val 1.53219
  Classification -> best τ=0.430 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64590 | val 0.87700
  Epoch 011 - train 0.63465 | val 0.85440
  Classification -> best τ=0.525 (val F1=0.1612)
  Directional -> Accuracy: 0.5600, MCC: 0.1091, F1: 0.6118

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63294 | val 0.75893
  Epoch 011 - train 0.62709 | val 0.72839
  Classification -> best τ=0.495 (val F1=0.3421)
  Directional -> Accuracy: 0.5156, MCC: -0.0861, F1: 0.6517

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59045 | val 0.82472
  Epoch 011 - train 0.57724 | val 0.85185
  Classification -> best τ=0.495 (val F1=0.2329)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64622 | val 0.79106
  Epoch 011 - train 0.61795 | val 0.79538
  Classification -> best τ=0.485 (val F1=0.2037)
  Directional -> Accuracy: 0.4681, MCC: -0.1139, F1: 0.5614

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65905 | val 0.78415
  Epoch 011 - train 0.66358 | val 0.81447
  Classification -> best τ=0.455 (val F1=0.2508)
  Directional -> Accuracy: 0.5077, MCC: 0.0341, F1: 0.2727

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63217 | val 0.85627
  Epoch 011 - train 0.62366 | val 0.87230
  Classification -> best τ=0.525 (val F1=0.0784)
  Directional -> Accuracy: 0.6140, MCC: 0.2258, F1: 0.7381

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61435 | val 0.75573
  Epoch 011 - train 0.61490 | val 0.78246
  Classification -> best τ=0.430 (val F1=0.1348)
  Directional -> Accuracy: 0.5077, MCC: 0.0764, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58685 | val 1.38950
  Epoch 014 - train 0.56443 | val 1.39755
  Classification -> best τ=0.535 (val F1=0.4688)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58314 | val 1.58006
  Epoch 011 - train 0.56212 | val 1.63475
  Classification -> best τ=0.545 (val F1=0.1310)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65346 | val 0.83931
  Epoch 011 - train 0.64227 | val 0.90627
  Classification -> best τ=0.405 (val F1=0.0700)
  Directional -> Accuracy: 0.6429, MCC: 0.2759, F1: 0.7541

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63029 | val 0.92804
  Epoch 011 - train 0.64090 | val 0.97644
  Classification -> best τ=0.385 (val F1=0.1997)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61255 | val 0.72097
  Epoch 011 - train 0.58174 | val 0.73584
  Classification -> best τ=0.590 (val F1=0.1918)
  Directional -> Accuracy: 0.4750, MCC: 0.0060, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61676 | val 0.73370
  Epoch 016 - train 0.54746 | val 0.72308
  Classification -> best τ=0.595 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63233 | val 0.87284
  Epoch 011 - train 0.63581 | val 0.84157
  Classification -> best τ=0.520 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57707 | val 0.82995
  Epoch 011 - train 0.57816 | val 0.80248
  Classification -> best τ=0.410 (val F1=0.2488)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66644 | val 0.71015
  Epoch 013 - train 0.66792 | val 0.68723
  Classification -> best τ=0.405 (val F1=0.3427)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60610 | val 1.11159
  Epoch 011 - train 0.61213 | val 1.13033
  Classification -> best τ=0.510 (val F1=0.2804)
  Directional -> Accuracy: 0.5581, MCC: 0.1229, F1: 0.3871

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61999 | val 1.01831
  Epoch 013 - train 0.64383 | val 0.99037
  Classification -> best τ=0.200 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59314 | val 0.87813
  Epoch 011 - train 0.56680 | val 0.93671
  Classification -> best τ=0.465 (val F1=0.2292)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.4865

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59495 | val 0.89146
  Epoch 011 - train 0.58637 | val 0.96538
  Classification -> best τ=0.470 (val F1=0.2450)
  Directional -> Accuracy: 0.4286, MCC: -0.1281, F1: 0.4839

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57802 | val 0.86865
  Epoch 019 - train 0.40450 | val 1.20334
  Classification -> best τ=0.615 (val F1=0.4012)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62530 | val 0.98788
  Epoch 014 - train 0.58585 | val 1.14338
  Classification -> best τ=0.605 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62314 | val 0.78220
  Epoch 011 - train 0.60346 | val 0.78234
  Classification -> best τ=0.240 (val F1=0.2456)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61788 | val 0.71706
  Epoch 011 - train 0.61166 | val 0.82681
  Classification -> best τ=0.515 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58031 | val 0.97416
  Epoch 011 - train 0.59421 | val 0.96630
  Classification -> best τ=0.595 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.2500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58713 | val 0.84986
  Epoch 020 - train 0.53705 | val 0.77417
  Epoch 026 - train 0.48771 | val 1.15875
  Classification -> best τ=0.860 (val F1=0.4478)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68080 | val 0.78025
  Epoch 016 - train 0.63062 | val 0.82827
  Classification -> best τ=0.575 (val F1=0.2085)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56435 | val 1.42560
  Epoch 011 - train 0.54501 | val 1.44702
  Classification -> best τ=0.610 (val F1=0.3546)
  Directional -> Accuracy: 0.4643, MCC: -0.0791, F1: 0.4000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63418 | val 0.75714
  Epoch 011 - train 0.63295 | val 0.79009
  Classification -> best τ=0.465 (val F1=0.1893)
  Directional -> Accuracy: 0.5660, MCC: 0.1423, F1: 0.6567

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58249 | val 1.89230
  Epoch 011 - train 0.56770 | val 1.89482
  Classification -> best τ=0.615 (val F1=0.2452)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63349 | val 0.75170

[I 2026-02-20 02:40:14,646] Trial 89 finished with value: 0.26012583210859047 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0020573997809671496, 'weight_decay': 6.012918761116692e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.960045783597064, 'early_stopping_min_delta': 0.00977414336750262}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.60981 | val 0.76097
  Classification -> best τ=0.575 (val F1=0.1489)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26012583210859047
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65445 | val 0.71206
  Epoch 018 - train 0.66974 | val 0.86593
  Classification -> best τ=0.705 (val F1=0.3286)
  Directional -> Accuracy: 0.5263, MCC: -0.0371, F1: 0.1818

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62056 | val 0.88243
  Epoch 013 - train 0.58879 | val 0.70992
  Classification -> best τ=0.410 (val F1=0.2769)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65221 | val 0.89669
  Epoch 020 - train 0.59404 | val 0.75441
  Epoch 023 - train 0.57534 | val 0.66454
  Classification -> best τ=0.585 (val F1=0.4142)
  Directional -> Accuracy: 0.5870, MCC: 0.1723, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66424 | val 0.85206
  Epoch 015 - train 0.64522 | val 1.18674
  Classification -> best τ=0.310 (val F1=0.3776)
  Directional -> Accuracy: 0.5405, MCC: 0.0882, F1: 0.5405

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66114 | val 0.63673
  Epoch 020 - train 0.51189 | val 1.09700
  Classification -> best τ=0.600 (val F1=0.3933)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61212 | val 0.76238
  Epoch 011 - train 0.63982 | val 0.77024
  Classification -> best τ=0.560 (val F1=0.2204)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68632 | val 0.68279
  Epoch 011 - train 0.68332 | val 0.69148
  Classification -> best τ=0.525 (val F1=0.3677)
  Directional -> Accuracy: 0.4706, MCC: -0.1355, F1: 0.2800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66246 | val 0.61753
  Epoch 018 - train 0.57390 | val 0.63138
  Classification -> best τ=0.250 (val F1=0.2810)
  Directional -> Accuracy: 0.5238, MCC: 0.2161, F1: 0.6296

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62604 | val 1.08925
  Epoch 011 - train 0.59531 | val 1.07295
  Classification -> best τ=0.630 (val F1=0.1928)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65898 | val 0.75440
  Epoch 011 - train 0.65018 | val 0.71055
  Classification -> best τ=0.410 (val F1=0.1730)
  Directional -> Accuracy: 0.5362, MCC: 0.0758, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65241 | val 1.11029
  Epoch 014 - train 0.64431 | val 0.96030
  Classification -> best τ=0.465 (val F1=0.2101)
  Directional -> Accuracy: 0.4898, MCC: -0.0654, F1: 0.3243

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64606 | val 0.72648
  Epoch 017 - train 0.61473 | val 0.82806
  Classification -> best τ=0.525 (val F1=0.2875)
  Directional -> Accuracy: 0.4561, MCC: -0.1159, F1: 0.5753

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62418 | val 0.66907
  Epoch 020 - train 0.54309 | val 0.78909
  Classification -> best τ=0.695 (val F1=0.2557)
  Directional -> Accuracy: 0.4048, MCC: -0.1795, F1: 0.4186

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66451 | val 0.90330
  Epoch 016 - train 0.66554 | val 0.76783
  Classification -> best τ=0.500 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59669 | val 0.79040
  Epoch 012 - train 0.58329 | val 0.98042
  Classification -> best τ=0.490 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65186 | val 0.69103
  Epoch 011 - train 0.66114 | val 0.66368
  Classification -> best τ=0.530 (val F1=0.2662)
  Directional -> Accuracy: 0.5797, MCC: 0.1688, F1: 0.7071

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68309 | val 1.17040
  Epoch 018 - train 0.61383 | val 0.99469
  Classification -> best τ=0.535 (val F1=0.1394)
  Directional -> Accuracy: 0.6724, MCC: 0.2686, F1: 0.7595

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66907 | val 0.73278
  Epoch 012 - train 0.65656 | val 0.70240
  Classification -> best τ=0.400 (val F1=0.1769)
  Directional -> Accuracy: 0.5867, MCC: -0.0278, F1: 0.7350

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63556 | val 0.67669
  Epoch 011 - train 0.65727 | val 0.71080
  Classification -> best τ=0.485 (val F1=0.3689)
  Directional -> Accuracy: 0.5469, MCC: 0.1664, F1: 0.4912

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58653 | val 0.92153
  Epoch 011 - train 0.59140 | val 0.96814
  Classification -> best τ=0.340 (val F1=0.3145)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68658 | val 0.72422
  Epoch 011 - train 0.65375 | val 0.75498
  Classification -> best τ=0.530 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: -0.1090, F1: 0.2162

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67637 | val 6.33948
  Epoch 011 - train 0.67821 | val 5.62831
  Classification -> best τ=0.455 (val F1=0.1886)
  Directional -> Accuracy: 0.4923, MCC: -0.0118, F1: 0.4211

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63050 | val 0.72300
  Epoch 020 - train 0.59118 | val 0.68114
  Epoch 022 - train 0.56510 | val 0.79642
  Classification -> best τ=0.200 (val F1=0.3269)
  Directional -> Accuracy: 0.5439, MCC: 0.0500, F1: 0.6286

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62617 | val 0.88654
  Epoch 011 - train 0.63767 | val 0.81967
  Classification -> best τ=0.475 (val F1=0.2056)
  Directional -> Accuracy: 0.5846, MCC: 0.1694, F1: 0.4255

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64847 | val 0.64988
  Epoch 014 - train 0.61141 | val 0.70822
  Classification -> best τ=0.445 (val F1=0.4068)
  Directional -> Accuracy: 0.5091, MCC: -0.0219, F1: 0.6087

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68236 | val 1.03678
  Epoch 011 - train 0.63634 | val 1.36848
  Classification -> best τ=0.570 (val F1=0.3006)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64540 | val 0.68702
  Epoch 017 - train 0.60080 | val 0.68999
  Classification -> best τ=0.605 (val F1=0.1005)
  Directional -> Accuracy: 0.5714, MCC: 0.1667, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63003 | val 0.88826
  Epoch 011 - train 0.64078 | val 0.95861
  Classification -> best τ=0.330 (val F1=0.2871)
  Directional -> Accuracy: 0.5536, MCC: 0.0563, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62123 | val 0.78625
  Epoch 014 - train 0.66150 | val 0.74746
  Classification -> best τ=0.475 (val F1=0.1580)
  Directional -> Accuracy: 0.6000, MCC: 0.1755, F1: 0.6800

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67515 | val 0.66166
  Epoch 019 - train 0.57809 | val 0.65589
  Classification -> best τ=0.380 (val F1=0.3985)
  Directional -> Accuracy: 0.5476, MCC: 0.1494, F1: 0.6415

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65121 | val 0.84654
  Epoch 014 - train 0.64288 | val 0.86168
  Classification -> best τ=0.585 (val F1=0.3039)
  Directional -> Accuracy: 0.5714, MCC: 0.2150, F1: 0.4706

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64889 | val 0.66681
  Epoch 017 - train 0.64071 | val 0.76349
  Classification -> best τ=0.305 (val F1=0.2509)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66071 | val 0.70167
  Epoch 013 - train 0.65863 | val 0.96640
  Classification -> best τ=0.350 (val F1=0.4460)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64335 | val 1.02637
  Epoch 011 - train 0.67501 | val 0.95188
  Classification -> best τ=0.475 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65765 | val 0.88239
  Epoch 014 - train 0.65099 | val 1.01605
  Classification -> best τ=0.475 (val F1=0.2739)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62528 | val 1.17653
  Epoch 011 - train 0.61760 | val 1.67046
  Classification -> best τ=0.485 (val F1=0.2858)
  Directional -> Accuracy: 0.5000, MCC: 0.0426, F1: 0.2759

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60144 | val 0.74373
  Epoch 011 - train 0.57821 | val 0.72145
  Classification -> best τ=0.405 (val F1=0.2110)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62577 | val 0.89700
  Epoch 012 - train 0.57642 | val 0.73252
  Classification -> best τ=0.530 (val F1=0.2441)
  Directional -> Accuracy: 0.4783, MCC: 0.0706, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66881 | val 0.80162
  Epoch 015 - train 0.65332 | val 0.65658
  Classification -> best τ=0.285 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67941 | val 1.05199
  Epoch 013 - train 0.62893 | val 1.07090
  Classification -> best τ=0.450 (val F1=0.4182)
  Directional -> Accuracy: 0.5270, MCC: 0.2001, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63521 | val 0.88836
  Epoch 011 - train 0.64346 | val 0.80524
  Classification -> best τ=0.530 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.1089, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58135 | val 1.11166
  Epoch 015 - train 0.53454 | val 1.20217
  Classification -> best τ=0.655 (val F1=0.5601)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65889 | val 0.99681
  Epoch 011 - train 0.65308 | val 0.98614
  Classification -> best τ=0.505 (val F1=0.4542)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68196 | val 1.78682
  Epoch 013 - train 0.66741 | val 1.31370
  Classification -> best τ=0.540 (val F1=0.2833)
  Directional -> Accuracy: 0.3455, MCC: -0.3416, F1: 0.4375

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58185 | val 0.96466
  Epoch 011 - train 0.59064 | val 0.93988
  Classification -> best τ=0.495 (val F1=0.4087)
  Directional -> Accuracy: 0.5357, MCC: 0.1486, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69436 | val 0.78076
  Epoch 012 - train 0.67193 | val 0.70021
  Classification -> best τ=0.455 (val F1=0.2351)
  Directional -> Accuracy: 0.4906, MCC: -0.0484, F1: 0.6301

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61915 | val 1.32976
  Epoch 012 - train 0.57608 | val 1.80146
  Classification -> best τ=0.505 (val F1=0.2859)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65684 | val 0.69762

[I 2026-02-20 02:42:35,216] Trial 90 finished with value: 0.2858274320745487 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.006427550591183396, 'weight_decay': 3.7973555968336376e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1976316064188381, 'early_stopping_min_delta': 0.009415722700378255}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.67237 | val 0.68536
  Classification -> best τ=0.485 (val F1=0.2045)
  Directional -> Accuracy: 0.5000, MCC: 0.0689, F1: 0.6512

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2858274320745487
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66130 | val 0.67567
  Epoch 011 - train 0.65355 | val 0.71809
  Classification -> best τ=0.660 (val F1=0.2510)
  Directional -> Accuracy: 0.5921, MCC: 0.2253, F1: 0.1622

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68303 | val 0.71590
  Epoch 015 - train 0.66241 | val 0.75154
  Classification -> best τ=0.545 (val F1=0.3353)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67490 | val 0.64482
  Epoch 015 - train 0.64504 | val 0.70753
  Classification -> best τ=0.475 (val F1=0.4500)
  Directional -> Accuracy: 0.5652, MCC: 0.1232, F1: 0.6296

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66757 | val 0.68830
  Epoch 015 - train 0.65171 | val 1.18029
  Classification -> best τ=0.595 (val F1=0.1537)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61615 | val 0.82086
  Epoch 016 - train 0.55532 | val 0.70981
  Classification -> best τ=0.455 (val F1=0.4753)
  Directional -> Accuracy: 0.6000, MCC: 0.1968, F1: 0.6296

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60734 | val 0.88881
  Epoch 020 - train 0.54376 | val 0.74514
  Epoch 024 - train 0.54196 | val 0.88708
  Classification -> best τ=0.490 (val F1=0.3222)
  Directional -> Accuracy: 0.5870, MCC: 0.2002, F1: 0.3448

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68549 | val 0.83520
  Epoch 011 - train 0.66814 | val 0.93024
  Classification -> best τ=0.445 (val F1=0.2753)
  Directional -> Accuracy: 0.4559, MCC: 0.0250, F1: 0.5316

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66022 | val 0.55331
  Epoch 019 - train 0.59470 | val 0.65239
  Classification -> best τ=0.240 (val F1=0.1208)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63932 | val 0.97120
  Epoch 012 - train 0.64884 | val 0.84971
  Classification -> best τ=0.410 (val F1=0.2233)
  Directional -> Accuracy: 0.4375, MCC: -0.0380, F1: 0.5846

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67240 | val 0.74198
  Epoch 011 - train 0.65936 | val 0.74975
  Classification -> best τ=0.635 (val F1=0.1607)
  Directional -> Accuracy: 0.5362, MCC: 0.0111, F1: 0.3600

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67175 | val 0.72394
  Epoch 013 - train 0.68221 | val 0.70631
  Classification -> best τ=0.480 (val F1=0.1987)
  Directional -> Accuracy: 0.5102, MCC: 0.0923, F1: 0.6000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65165 | val 0.71433
  Epoch 013 - train 0.66653 | val 0.89583
  Classification -> best τ=0.550 (val F1=0.3119)
  Directional -> Accuracy: 0.4561, MCC: -0.1538, F1: 0.6076

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59997 | val 0.86070
  Epoch 020 - train 0.50903 | val 0.97454
  Epoch 023 - train 0.46911 | val 0.91594
  Classification -> best τ=0.705 (val F1=0.2557)
  Directional -> Accuracy: 0.5238, MCC: 0.0214, F1: 0.4118

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68538 | val 0.70449
  Epoch 017 - train 0.65298 | val 0.66647
  Classification -> best τ=0.465 (val F1=0.2942)
  Directional -> Accuracy: 0.5500, MCC: 0.1014, F1: 0.5846

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69440 | val 0.70950
  Epoch 012 - train 0.67769 | val 0.75792
  Classification -> best τ=0.630 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64612 | val 0.88751
  Epoch 015 - train 0.63548 | val 0.73522
  Classification -> best τ=0.730 (val F1=0.2474)
  Directional -> Accuracy: 0.5217, MCC: 0.2307, F1: 0.1951

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65018 | val 0.71024
  Epoch 014 - train 0.65230 | val 0.74417
  Classification -> best τ=0.555 (val F1=0.2186)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68076 | val 0.70094
  Epoch 014 - train 0.65692 | val 0.69549
  Classification -> best τ=0.635 (val F1=0.2758)
  Directional -> Accuracy: 0.4267, MCC: 0.0000, F1: 0.2182

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65473 | val 0.70082
  Epoch 012 - train 0.62567 | val 0.85296
  Classification -> best τ=0.575 (val F1=0.3622)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61154 | val 0.99460
  Epoch 011 - train 0.61926 | val 0.93168
  Classification -> best τ=0.450 (val F1=0.2312)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62296 | val 0.77822
  Epoch 011 - train 0.64717 | val 0.74357
  Classification -> best τ=0.520 (val F1=0.1864)
  Directional -> Accuracy: 0.5319, MCC: -0.1702, F1: 0.6857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69052 | val 0.74379
  Epoch 011 - train 0.68199 | val 0.73100
  Classification -> best τ=0.425 (val F1=0.2221)
  Directional -> Accuracy: 0.4308, MCC: -0.1377, F1: 0.3934

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67450 | val 0.67994
  Epoch 020 - train 0.63615 | val 0.79983
  Classification -> best τ=0.380 (val F1=0.3720)
  Directional -> Accuracy: 0.5263, MCC: -0.0228, F1: 0.6494

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66691 | val 0.69650
  Epoch 011 - train 0.66410 | val 0.69577
  Classification -> best τ=0.505 (val F1=0.2054)
  Directional -> Accuracy: 0.5231, MCC: 0.0924, F1: 0.6265

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66947 | val 0.67978
  Epoch 020 - train 0.58019 | val 0.65039
  Epoch 030 - train 0.49592 | val 0.76498
  Classification -> best τ=0.370 (val F1=0.4001)
  Directional -> Accuracy: 0.4909, MCC: 0.0141, F1: 0.4167

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60204 | val 1.84981
  Epoch 011 - train 0.61714 | val 2.05917
  Classification -> best τ=0.565 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66929 | val 0.70172
  Epoch 012 - train 0.63610 | val 0.69610
  Classification -> best τ=0.545 (val F1=0.0550)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.4878

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63672 | val 0.72309
  Epoch 014 - train 0.61008 | val 0.85093
  Classification -> best τ=0.355 (val F1=0.2718)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64713 | val 0.70786
  Epoch 011 - train 0.61121 | val 0.71508
  Classification -> best τ=0.525 (val F1=0.1918)
  Directional -> Accuracy: 0.4250, MCC: -0.1182, F1: 0.3030

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65832 | val 0.66656
  Epoch 020 - train 0.57753 | val 0.68719
  Epoch 021 - train 0.57173 | val 0.68296
  Classification -> best τ=0.450 (val F1=0.3689)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66637 | val 0.79147
  Epoch 012 - train 0.66494 | val 0.98703
  Classification -> best τ=0.490 (val F1=0.3036)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64254 | val 0.75338
  Epoch 015 - train 0.60897 | val 0.70670
  Classification -> best τ=0.515 (val F1=0.2969)
  Directional -> Accuracy: 0.5306, MCC: 0.0127, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69564 | val 0.62710
  Epoch 020 - train 0.63411 | val 0.86981
  Classification -> best τ=0.415 (val F1=0.3610)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63816 | val 1.20048
  Epoch 011 - train 0.65717 | val 1.14608
  Classification -> best τ=0.640 (val F1=0.1377)
  Directional -> Accuracy: 0.6047, MCC: 0.2135, F1: 0.6222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65384 | val 0.98144
  Epoch 011 - train 0.62892 | val 1.13274
  Classification -> best τ=0.410 (val F1=0.2071)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67025 | val 0.86733
  Epoch 011 - train 0.69540 | val 0.91187
  Classification -> best τ=0.505 (val F1=0.0967)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65045 | val 0.77412
  Epoch 011 - train 0.64284 | val 0.79690
  Classification -> best τ=0.515 (val F1=0.2305)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61311 | val 0.71810
  Epoch 011 - train 0.61172 | val 0.75804
  Classification -> best τ=0.385 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64599 | val 0.63329
  Epoch 011 - train 0.65452 | val 0.63435
  Classification -> best τ=0.255 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65548 | val 0.67689
  Epoch 015 - train 0.61696 | val 0.68892
  Classification -> best τ=0.500 (val F1=0.3307)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65916 | val 0.69334
  Epoch 011 - train 0.66972 | val 0.69676
  Classification -> best τ=0.510 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.1110, F1: 0.6296

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64208 | val 1.03406
  Epoch 011 - train 0.61792 | val 1.13146
  Classification -> best τ=0.690 (val F1=0.4001)
  Directional -> Accuracy: 0.5476, MCC: 0.1876, F1: 0.4571

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65941 | val 0.94733
  Epoch 012 - train 0.62260 | val 1.12584
  Classification -> best τ=0.580 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68604 | val 0.87052
  Epoch 013 - train 0.65122 | val 0.91081
  Classification -> best τ=0.390 (val F1=0.1884)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63452 | val 0.89038
  Epoch 011 - train 0.62116 | val 1.00226
  Classification -> best τ=0.545 (val F1=0.3536)
  Directional -> Accuracy: 0.5714, MCC: 0.2072, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68887 | val 0.74183
  Epoch 015 - train 0.64691 | val 0.80801
  Classification -> best τ=0.635 (val F1=0.3310)
  Directional -> Accuracy: 0.5094, MCC: 0.0300, F1: 0.3810

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63133 | val 1.70271
  Epoch 012 - train 0.59320 | val 2.09073
  Classification -> best τ=0.805 (val F1=0.2557)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66410 | val 0.69000

[I 2026-02-20 02:45:00,117] Trial 91 finished with value: 0.26389610037458494 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0064454279632534415, 'weight_decay': 2.356467265801885e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2094560509916983, 'early_stopping_min_delta': 0.009269792908120618}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 014 - train 0.66372 | val 0.67721
  Classification -> best τ=0.480 (val F1=0.2691)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26389610037458494
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65665 | val 0.70794
  Epoch 011 - train 0.66740 | val 0.73130
  Classification -> best τ=0.450 (val F1=0.2176)
  Directional -> Accuracy: 0.5526, MCC: 0.1059, F1: 0.5278

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62854 | val 0.93816
  Epoch 018 - train 0.57268 | val 1.01697
  Classification -> best τ=0.425 (val F1=0.2670)
  Directional -> Accuracy: 0.5778, MCC: 0.0492, F1: 0.7164

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66221 | val 0.67816
  Epoch 011 - train 0.63020 | val 0.66520
  Classification -> best τ=0.505 (val F1=0.2800)
  Directional -> Accuracy: 0.5000, MCC: -0.1427, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68467 | val 0.86128
  Epoch 015 - train 0.65218 | val 1.06966
  Classification -> best τ=0.530 (val F1=0.0855)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63998 | val 0.95527
  Epoch 017 - train 0.52137 | val 1.36426
  Classification -> best τ=0.615 (val F1=0.4259)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61232 | val 0.77840
  Epoch 012 - train 0.60589 | val 0.92460
  Classification -> best τ=0.515 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64599 | val 0.86259
  Epoch 012 - train 0.63907 | val 0.81942
  Classification -> best τ=0.535 (val F1=0.2208)
  Directional -> Accuracy: 0.5735, MCC: -0.0165, F1: 0.1714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62667 | val 0.98454
  Epoch 012 - train 0.63991 | val 0.96167
  Classification -> best τ=0.560 (val F1=0.1147)
  Directional -> Accuracy: 0.6190, MCC: 0.1925, F1: 0.3846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60877 | val 0.88070
  Epoch 011 - train 0.59510 | val 1.03421
  Classification -> best τ=0.530 (val F1=0.1402)
  Directional -> Accuracy: 0.2917, MCC: -0.4371, F1: 0.4333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64524 | val 0.71095
  Epoch 019 - train 0.60853 | val 2.24080
  Classification -> best τ=0.535 (val F1=0.2293)
  Directional -> Accuracy: 0.4348, MCC: -0.0912, F1: 0.4658

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64869 | val 0.70895
  Epoch 013 - train 0.66082 | val 0.72695
  Classification -> best τ=0.385 (val F1=0.2798)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66452 | val 0.72030
  Epoch 011 - train 0.66955 | val 0.72525
  Classification -> best τ=0.535 (val F1=0.3401)
  Directional -> Accuracy: 0.4386, MCC: -0.1950, F1: 0.5897

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59812 | val 0.74392
  Epoch 017 - train 0.47871 | val 0.94619
  Classification -> best τ=0.635 (val F1=0.1754)
  Directional -> Accuracy: 0.4048, MCC: -0.2460, F1: 0.5763

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68238 | val 0.66706
  Epoch 019 - train 0.62775 | val 0.69845
  Classification -> best τ=0.385 (val F1=0.1473)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5312

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68302 | val 0.89501
  Epoch 020 - train 0.55883 | val 0.74182
  Epoch 023 - train 0.54853 | val 0.72832
  Classification -> best τ=0.470 (val F1=0.2298)
  Directional -> Accuracy: 0.5098, MCC: -0.1178, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65844 | val 0.67127
  Epoch 017 - train 0.60634 | val 0.75036
  Classification -> best τ=0.765 (val F1=0.2694)
  Directional -> Accuracy: 0.4783, MCC: 0.0022, F1: 0.2800

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65357 | val 0.72503
  Epoch 014 - train 0.64303 | val 1.07743
  Classification -> best τ=0.600 (val F1=0.1842)
  Directional -> Accuracy: 0.4310, MCC: 0.0715, F1: 0.2326

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68569 | val 0.69277
  Epoch 020 - train 0.65883 | val 1.42066
  Classification -> best τ=0.465 (val F1=0.1410)
  Directional -> Accuracy: 0.5733, MCC: -0.0176, F1: 0.7143

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65688 | val 0.70936
  Epoch 015 - train 0.66639 | val 0.73385
  Classification -> best τ=0.425 (val F1=0.3421)
  Directional -> Accuracy: 0.5312, MCC: 0.1954, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62577 | val 0.87069
  Epoch 011 - train 0.61044 | val 0.88038
  Classification -> best τ=0.530 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66680 | val 0.76894
  Epoch 011 - train 0.66482 | val 0.71951
  Classification -> best τ=0.555 (val F1=0.1039)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65362 | val 1.24494
  Epoch 011 - train 0.65944 | val 1.24841
  Classification -> best τ=0.535 (val F1=0.2057)
  Directional -> Accuracy: 0.4923, MCC: -0.0073, F1: 0.2667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64755 | val 0.65664
  Epoch 019 - train 0.60743 | val 0.71394
  Classification -> best τ=0.465 (val F1=0.3032)
  Directional -> Accuracy: 0.4561, MCC: 0.0076, F1: 0.2051

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65899 | val 0.71035
  Epoch 011 - train 0.63110 | val 0.75032
  Classification -> best τ=0.555 (val F1=0.1727)
  Directional -> Accuracy: 0.4769, MCC: -0.0548, F1: 0.4138

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63943 | val 1.05463
  Epoch 014 - train 0.60936 | val 1.27897
  Classification -> best τ=0.600 (val F1=0.5104)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61088 | val 1.92240
  Epoch 011 - train 0.60830 | val 1.96627
  Classification -> best τ=0.720 (val F1=0.2726)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62897 | val 0.70702
  Epoch 011 - train 0.66168 | val 0.89647
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62110 | val 0.69228
  Epoch 016 - train 0.64119 | val 0.72528
  Classification -> best τ=0.540 (val F1=0.3751)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66244 | val 0.73098
  Epoch 015 - train 0.61693 | val 0.82859
  Classification -> best τ=0.550 (val F1=0.1511)
  Directional -> Accuracy: 0.6250, MCC: 0.2347, F1: 0.7170

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63789 | val 0.80394
  Epoch 011 - train 0.61515 | val 0.82324
  Classification -> best τ=0.690 (val F1=0.2814)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63220 | val 1.45488
  Epoch 013 - train 0.62250 | val 2.15960
  Classification -> best τ=0.415 (val F1=0.3034)
  Directional -> Accuracy: 0.5952, MCC: 0.1682, F1: 0.7018

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65161 | val 0.70027
  Epoch 013 - train 0.56960 | val 0.87398
  Classification -> best τ=0.540 (val F1=0.3396)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66778 | val 0.93791
  Epoch 014 - train 0.61439 | val 0.90024
  Classification -> best τ=0.555 (val F1=0.2659)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68144 | val 0.78269
  Epoch 014 - train 0.62114 | val 0.91825
  Classification -> best τ=0.475 (val F1=0.2845)
  Directional -> Accuracy: 0.4651, MCC: -0.2158, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66628 | val 0.84944
  Epoch 013 - train 0.62098 | val 0.92485
  Classification -> best τ=0.475 (val F1=0.2518)
  Directional -> Accuracy: 0.4242, MCC: -0.0723, F1: 0.2400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57005 | val 1.72106
  Epoch 011 - train 0.51959 | val 1.88168
  Classification -> best τ=0.500 (val F1=0.2658)
  Directional -> Accuracy: 0.5714, MCC: 0.1455, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60036 | val 1.15716
  Epoch 011 - train 0.59972 | val 1.11612
  Classification -> best τ=0.515 (val F1=0.1913)
  Directional -> Accuracy: 0.5714, MCC: 0.1316, F1: 0.2941

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58706 | val 1.74840
  Epoch 013 - train 0.49693 | val 1.76920
  Classification -> best τ=0.385 (val F1=0.1362)
  Directional -> Accuracy: 0.4565, MCC: -0.0321, F1: 0.4444

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68153 | val 0.68280
  Epoch 020 - train 0.56034 | val 0.72608
  Classification -> best τ=0.460 (val F1=0.0896)
  Directional -> Accuracy: 0.3125, MCC: -0.2816, F1: 0.4762

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66454 | val 0.77264
  Epoch 017 - train 0.58825 | val 0.68094
  Classification -> best τ=0.525 (val F1=0.3965)
  Directional -> Accuracy: 0.5000, MCC: 0.0230, F1: 0.6186

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68110 | val 0.77338
  Epoch 011 - train 0.63742 | val 0.78212
  Classification -> best τ=0.490 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: 0.0644, F1: 0.6316

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60161 | val 0.78242
  Epoch 011 - train 0.61652 | val 0.80484
  Classification -> best τ=0.660 (val F1=0.5000)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.5714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61809 | val 1.64161
  Epoch 012 - train 0.58317 | val 1.60076
  Classification -> best τ=0.620 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: -0.0976, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65941 | val 1.31793
  Epoch 011 - train 0.65476 | val 1.32014
  Classification -> best τ=0.420 (val F1=0.1571)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67022 | val 0.79642
  Epoch 012 - train 0.61387 | val 1.04881
  Classification -> best τ=0.495 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67673 | val 0.70440
  Epoch 017 - train 0.61925 | val 0.74238
  Classification -> best τ=0.610 (val F1=0.1479)
  Directional -> Accuracy: 0.4906, MCC: -0.0080, F1: 0.2286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62141 | val 1.80755
  Epoch 011 - train 0.62662 | val 1.84133
  Classification -> best τ=0.590 (val F1=0.2625)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68832 | val 0.73915

[I 2026-02-20 02:47:30,077] Trial 92 finished with value: 0.23617903039844124 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.008934604718357463, 'weight_decay': 3.0842264967569065e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1252107572113645, 'early_stopping_min_delta': 0.008741186113283428}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.69390 | val 0.69176
  Classification -> best τ=0.450 (val F1=0.2637)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23617903039844124
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66984 | val 0.72183
  Epoch 013 - train 0.62586 | val 0.70076
  Classification -> best τ=0.440 (val F1=0.2701)
  Directional -> Accuracy: 0.6316, MCC: 0.2479, F1: 0.5625

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58229 | val 0.68247
  Epoch 011 - train 0.62137 | val 0.69189
  Classification -> best τ=0.465 (val F1=0.0492)
  Directional -> Accuracy: 0.6000, MCC: 0.1350, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65766 | val 0.77958
  Epoch 017 - train 0.62429 | val 0.66461
  Classification -> best τ=0.585 (val F1=0.3285)
  Directional -> Accuracy: 0.5217, MCC: 0.1410, F1: 0.2143

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67026 | val 0.92849
  Epoch 014 - train 0.66358 | val 1.30872
  Classification -> best τ=0.380 (val F1=0.1839)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60599 | val 0.85864
  Epoch 014 - train 0.57012 | val 1.68610
  Classification -> best τ=0.590 (val F1=0.4602)
  Directional -> Accuracy: 0.5600, MCC: 0.1534, F1: 0.4500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61941 | val 0.69648
  Epoch 015 - train 0.58137 | val 0.98697
  Classification -> best τ=0.545 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68774 | val 0.71210
  Epoch 012 - train 0.66481 | val 0.73672
  Classification -> best τ=0.440 (val F1=0.2789)
  Directional -> Accuracy: 0.5147, MCC: 0.1280, F1: 0.5600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61270 | val 0.59476
  Epoch 020 - train 0.54628 | val 0.67626
  Epoch 023 - train 0.50589 | val 0.73815
  Classification -> best τ=0.125 (val F1=0.2677)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62641 | val 1.16080
  Epoch 012 - train 0.60773 | val 1.23996
  Classification -> best τ=0.630 (val F1=0.2764)
  Directional -> Accuracy: 0.7292, MCC: 0.4783, F1: 0.5806

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65001 | val 0.71156
  Epoch 020 - train 0.59463 | val 0.90017
  Epoch 022 - train 0.59446 | val 1.02791
  Classification -> best τ=0.545 (val F1=0.2480)
  Directional -> Accuracy: 0.5362, MCC: 0.0573, F1: 0.4667

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67468 | val 0.68234
  Epoch 018 - train 0.65286 | val 0.75854
  Classification -> best τ=0.490 (val F1=0.2397)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68336 | val 0.67920
  Epoch 016 - train 0.65414 | val 0.70090
  Classification -> best τ=0.505 (val F1=0.2794)
  Directional -> Accuracy: 0.4386, MCC: -0.1303, F1: 0.5000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60276 | val 1.12559
  Epoch 011 - train 0.59843 | val 0.99931
  Classification -> best τ=0.375 (val F1=0.2339)
  Directional -> Accuracy: 0.6429, MCC: 0.3631, F1: 0.6939

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68639 | val 0.67751
  Epoch 011 - train 0.68455 | val 0.67128
  Classification -> best τ=0.360 (val F1=0.3642)
  Directional -> Accuracy: 0.5167, MCC: 0.0431, F1: 0.6329

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64011 | val 0.86064
  Epoch 011 - train 0.64151 | val 1.01171
  Classification -> best τ=0.510 (val F1=0.3390)
  Directional -> Accuracy: 0.4510, MCC: -0.0360, F1: 0.5882

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65942 | val 0.78030
  Epoch 011 - train 0.67272 | val 0.74438
  Classification -> best τ=0.595 (val F1=0.1711)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68205 | val 1.98612
  Epoch 011 - train 0.65529 | val 2.07484
  Classification -> best τ=0.765 (val F1=0.1913)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67365 | val 0.77005
  Epoch 011 - train 0.68297 | val 0.78758
  Classification -> best τ=0.445 (val F1=0.1243)
  Directional -> Accuracy: 0.6267, MCC: 0.1605, F1: 0.7544

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67194 | val 0.71032
  Epoch 015 - train 0.62798 | val 0.77908
  Classification -> best τ=0.280 (val F1=0.2522)
  Directional -> Accuracy: 0.5781, MCC: 0.1486, F1: 0.6197

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60507 | val 0.85132
  Epoch 011 - train 0.58685 | val 0.84390
  Classification -> best τ=0.465 (val F1=0.2871)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67508 | val 0.84805
  Epoch 011 - train 0.67333 | val 0.91013
  Classification -> best τ=0.535 (val F1=0.1174)
  Directional -> Accuracy: 0.4681, MCC: -0.0708, F1: 0.5283

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68233 | val 0.80677
  Epoch 013 - train 0.68411 | val 0.78462
  Classification -> best τ=0.605 (val F1=0.1762)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67281 | val 0.66482
  Epoch 020 - train 0.65150 | val 0.69322
  Classification -> best τ=0.545 (val F1=0.4455)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67720 | val 0.68849
  Epoch 011 - train 0.67838 | val 0.68668
  Classification -> best τ=0.430 (val F1=0.1337)
  Directional -> Accuracy: 0.4154, MCC: -0.1635, F1: 0.4571

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67062 | val 0.77208
  Epoch 011 - train 0.66220 | val 0.69854
  Classification -> best τ=0.595 (val F1=0.3889)
  Directional -> Accuracy: 0.4545, MCC: -0.0319, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62129 | val 2.45308
  Epoch 011 - train 0.60035 | val 2.58128
  Classification -> best τ=0.580 (val F1=0.0385)
  Directional -> Accuracy: 0.4889, MCC: 0.1186, F1: 0.5965

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67573 | val 0.68279
  Epoch 012 - train 0.64184 | val 0.68908
  Classification -> best τ=0.520 (val F1=0.1936)
  Directional -> Accuracy: 0.5952, MCC: 0.1487, F1: 0.6792

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66325 | val 0.75777
  Epoch 011 - train 0.63789 | val 0.76333
  Classification -> best τ=0.425 (val F1=0.2149)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62664 | val 0.76424
  Epoch 011 - train 0.63854 | val 0.75005
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66634 | val 0.71072
  Epoch 015 - train 0.63917 | val 0.71224
  Classification -> best τ=0.720 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68663 | val 0.87862
  Epoch 012 - train 0.66283 | val 0.77249
  Classification -> best τ=0.520 (val F1=0.2901)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63065 | val 0.73968
  Epoch 014 - train 0.56430 | val 0.80161
  Classification -> best τ=0.425 (val F1=0.4278)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68672 | val 0.64875
  Epoch 018 - train 0.65888 | val 0.67260
  Classification -> best τ=0.390 (val F1=0.4243)
  Directional -> Accuracy: 0.4306, MCC: -0.0855, F1: 0.0889

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65633 | val 1.01945
  Epoch 011 - train 0.63123 | val 1.03277
  Classification -> best τ=0.585 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67486 | val 0.70894
  Epoch 018 - train 0.61326 | val 0.84603
  Classification -> best τ=0.370 (val F1=0.4292)
  Directional -> Accuracy: 0.5455, MCC: 0.0874, F1: 0.5833

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65530 | val 0.69903
  Epoch 011 - train 0.63277 | val 0.69048
  Classification -> best τ=0.480 (val F1=0.3001)
  Directional -> Accuracy: 0.5476, MCC: 0.1342, F1: 0.4242

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64455 | val 0.74316
  Epoch 011 - train 0.61343 | val 0.74149
  Classification -> best τ=0.500 (val F1=0.2327)
  Directional -> Accuracy: 0.4464, MCC: -0.1100, F1: 0.4151

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60858 | val 0.72000
  Epoch 012 - train 0.57017 | val 0.76061
  Classification -> best τ=0.345 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65219 | val 0.70481
  Epoch 015 - train 0.57717 | val 0.72527
  Classification -> best τ=0.480 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65980 | val 0.69745
  Epoch 013 - train 0.63218 | val 0.69573
  Classification -> best τ=0.420 (val F1=0.4068)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63349 | val 0.97761
  Epoch 011 - train 0.63472 | val 1.36171
  Classification -> best τ=0.530 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64349 | val 0.93178
  Epoch 011 - train 0.62700 | val 0.92112
  Classification -> best τ=0.755 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67282 | val 0.89663
  Epoch 015 - train 0.63144 | val 0.78921
  Classification -> best τ=0.685 (val F1=0.2902)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67712 | val 1.21015
  Epoch 011 - train 0.67460 | val 1.23606
  Classification -> best τ=0.475 (val F1=0.1399)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63182 | val 1.60763
  Epoch 012 - train 0.62027 | val 1.52232
  Classification -> best τ=0.610 (val F1=0.4159)
  Directional -> Accuracy: 0.5536, MCC: 0.1700, F1: 0.6575

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68481 | val 0.72904
  Epoch 014 - train 0.67047 | val 0.71417
  Classification -> best τ=0.545 (val F1=0.2133)
  Directional -> Accuracy: 0.5283, MCC: 0.0662, F1: 0.4444

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60537 | val 1.75201
  Epoch 011 - train 0.59942 | val 1.89009
  Classification -> best τ=0.725 (val F1=0.2132)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67113 | val 0.69789

[I 2026-02-20 02:49:49,853] Trial 93 finished with value: 0.26651802175056116 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.003990970928665918, 'weight_decay': 9.57812161711607e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.121983001739769, 'early_stopping_min_delta': 0.009510012168109878}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.68896 | val 0.69707
  Classification -> best τ=0.390 (val F1=0.2472)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26651802175056116
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66528 | val 0.66738
  Epoch 020 - train 0.61736 | val 1.80293
  Epoch 021 - train 0.68407 | val 0.82889
  Classification -> best τ=0.505 (val F1=0.2851)
  Directional -> Accuracy: 0.5455, MCC: 0.0265, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63596 | val 0.91996
  Epoch 013 - train 0.62468 | val 0.92681
  Classification -> best τ=0.555 (val F1=0.1264)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67155 | val 1.19365
  Epoch 011 - train 0.63725 | val 1.21999
  Classification -> best τ=0.495 (val F1=0.2943)
  Directional -> Accuracy: 0.4043, MCC: -0.2240, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70082 | val 0.71995
  Epoch 012 - train 0.68272 | val 0.73686
  Classification -> best τ=0.485 (val F1=0.0763)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62822 | val 1.30382
  Epoch 011 - train 0.61405 | val 1.69387
  Classification -> best τ=0.525 (val F1=0.4255)
  Directional -> Accuracy: 0.6667, MCC: 0.3550, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64107 | val 0.94981
  Epoch 012 - train 0.63054 | val 0.82332
  Classification -> best τ=0.570 (val F1=0.2582)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67319 | val 0.79280
  Epoch 017 - train 0.63232 | val 0.70771
  Classification -> best τ=0.370 (val F1=0.1592)
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58645 | val 2.71839
  Epoch 011 - train 0.57097 | val 2.80754
  Classification -> best τ=0.585 (val F1=0.1214)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66227 | val 0.84728
  Epoch 011 - train 0.62640 | val 0.97898
  Classification -> best τ=0.475 (val F1=0.2788)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66259 | val 0.85685
  Epoch 011 - train 0.66132 | val 0.84251
  Classification -> best τ=0.550 (val F1=0.1462)
  Directional -> Accuracy: 0.4429, MCC: -0.0123, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68773 | val 0.82880
  Epoch 013 - train 0.66970 | val 0.96402
  Classification -> best τ=0.395 (val F1=0.2063)
  Directional -> Accuracy: 0.4800, MCC: 0.0642, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61506 | val 1.17780
  Epoch 011 - train 0.65033 | val 1.16044
  Classification -> best τ=0.635 (val F1=0.2275)
  Directional -> Accuracy: 0.6724, MCC: 0.3858, F1: 0.5778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60099 | val 1.15985
  Epoch 011 - train 0.59994 | val 1.35568
  Classification -> best τ=0.340 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: -0.0471, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69561 | val 0.72062
  Epoch 020 - train 0.64512 | val 0.62848
  Epoch 025 - train 0.63893 | val 0.63578
  Classification -> best τ=0.420 (val F1=0.2877)
  Directional -> Accuracy: 0.5738, MCC: 0.1467, F1: 0.5938

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64759 | val 0.72307
  Epoch 018 - train 0.59833 | val 0.69457
  Classification -> best τ=0.550 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63592 | val 0.91366
  Epoch 012 - train 0.62201 | val 0.80411
  Classification -> best τ=0.755 (val F1=0.2595)
  Directional -> Accuracy: 0.4714, MCC: -0.0203, F1: 0.3509

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64744 | val 1.53960
  Epoch 013 - train 0.63511 | val 1.66943
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68091 | val 0.68644
  Epoch 016 - train 0.70743 | val 0.70453
  Classification -> best τ=0.605 (val F1=0.2134)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65545 | val 0.76696
  Epoch 012 - train 0.67547 | val 0.86132
  Classification -> best τ=0.685 (val F1=0.1822)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65389 | val 0.82954
  Epoch 014 - train 0.61744 | val 0.90779
  Classification -> best τ=0.475 (val F1=0.2613)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63942 | val 1.50097
  Epoch 011 - train 0.63580 | val 1.33258
  Classification -> best τ=0.530 (val F1=0.0754)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.1212

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68425 | val 0.77310
  Epoch 013 - train 0.66755 | val 0.75716
  Classification -> best τ=0.685 (val F1=0.2209)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66834 | val 0.81033
  Epoch 011 - train 0.66038 | val 0.91595
  Classification -> best τ=0.600 (val F1=0.2575)
  Directional -> Accuracy: 0.5690, MCC: 0.2469, F1: 0.4681

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62419 | val 0.86015
  Epoch 012 - train 0.60056 | val 0.91631
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67359 | val 0.68179
  Epoch 015 - train 0.63962 | val 0.75608
  Classification -> best τ=0.495 (val F1=0.4472)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65143 | val 0.86228
  Epoch 011 - train 0.64694 | val 0.77228
  Classification -> best τ=0.475 (val F1=0.3162)
  Directional -> Accuracy: 0.4130, MCC: -0.2583, F1: 0.1818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63002 | val 0.68950
  Epoch 011 - train 0.65008 | val 0.68626
  Classification -> best τ=0.535 (val F1=0.0593)
  Directional -> Accuracy: 0.3953, MCC: -0.1377, F1: 0.0714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68359 | val 0.75017
  Epoch 014 - train 0.66321 | val 0.82821
  Classification -> best τ=0.455 (val F1=0.2781)
  Directional -> Accuracy: 0.5614, MCC: 0.2858, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66185 | val 0.76689
  Epoch 011 - train 0.65811 | val 0.76788
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63271 | val 3.48445
  Epoch 011 - train 0.63406 | val 3.46975
  Classification -> best τ=0.635 (val F1=0.2683)
  Directional -> Accuracy: 0.5349, MCC: 0.0670, F1: 0.3750

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67295 | val 0.63695
  Epoch 013 - train 0.64930 | val 0.62500
  Classification -> best τ=0.730 (val F1=0.2073)
  Directional -> Accuracy: 0.5116, MCC: 0.2060, F1: 0.1600

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61115 | val 0.76735
  Epoch 011 - train 0.62957 | val 0.78594
  Classification -> best τ=0.430 (val F1=0.2872)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63931 | val 0.80314
  Epoch 016 - train 0.60239 | val 0.88486
  Classification -> best τ=0.315 (val F1=0.2885)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64643 | val 0.76089
  Epoch 011 - train 0.63654 | val 0.75884
  Classification -> best τ=0.480 (val F1=0.3254)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69789 | val 0.72067
  Epoch 019 - train 0.59485 | val 0.76417
  Classification -> best τ=0.470 (val F1=0.2588)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63970 | val 0.79184
  Epoch 011 - train 0.61356 | val 0.80961
  Classification -> best τ=0.425 (val F1=0.2781)
  Directional -> Accuracy: 0.5821, MCC: 0.1241, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61217 | val 0.91929
  Epoch 013 - train 0.61629 | val 1.02490
  Classification -> best τ=0.630 (val F1=0.2652)
  Directional -> Accuracy: 0.4651, MCC: -0.1579, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60963 | val 0.71698
  Epoch 012 - train 0.60902 | val 0.95326
  Classification -> best τ=0.415 (val F1=0.2453)
  Directional -> Accuracy: 0.4737, MCC: -0.0243, F1: 0.5946

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66779 | val 0.76350
  Epoch 014 - train 0.57371 | val 1.08120
  Classification -> best τ=0.325 (val F1=0.3014)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68442 | val 0.64501
  Epoch 013 - train 0.64060 | val 0.94559
  Classification -> best τ=0.360 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63165 | val 0.86239
  Epoch 011 - train 0.63554 | val 0.85790
  Classification -> best τ=0.460 (val F1=0.4808)
  Directional -> Accuracy: 0.4737, MCC: -0.1217, F1: 0.6154

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60534 | val 1.19402
  Epoch 011 - train 0.61754 | val 1.16909
  Classification -> best τ=0.580 (val F1=0.2284)
  Directional -> Accuracy: 0.5467, MCC: 0.0924, F1: 0.5000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62986 | val 0.72768
  Epoch 013 - train 0.62109 | val 0.81329
  Classification -> best τ=0.490 (val F1=0.3062)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60053 | val 0.95796
  Epoch 011 - train 0.57594 | val 0.89194
  Classification -> best τ=0.490 (val F1=0.2100)
  Directional -> Accuracy: 0.6364, MCC: 0.2404, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63749 | val 1.19135
  Epoch 011 - train 0.62341 | val 1.25114
  Classification -> best τ=0.585 (val F1=0.1890)
  Directional -> Accuracy: 0.5714, MCC: -0.0843, F1: 0.0870

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64964 | val 0.80542
  Epoch 011 - train 0.64440 | val 0.79841
  Classification -> best τ=0.630 (val F1=0.2180)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60468 | val 1.43168
  Epoch 012 - train 0.57079 | val 1.62651
  Classification -> best τ=0.625 (val F1=0.2819)
  Directional -> Accuracy: 0.4737, MCC: -0.0145, F1: 0.6250

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68345 | val 0.73627
  Epoch 014 - train 0.64229 | val 0.72292
  Classification -> best τ=0.500 (val F1=0.3324)
  Directional -> Accuracy: 0.5926, MCC: 0.2935, F1: 0.7179

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66449 | val 1.50902
  Epoch 014 - train 0.65323 | val 3.07988
  Classification -> best τ=0.345 (val F1=0.2060)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66587 | val 0.67637
  Epoch 011 - train 0.67058 | val 0.67514

[I 2026-02-20 02:51:40,671] Trial 94 finished with value: 0.23632668920925728 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.004720188635102152, 'weight_decay': 3.432492115775064e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.3015051186529367, 'early_stopping_min_delta': 0.008720748360878635}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.420 (val F1=0.2454)
  Directional -> Accuracy: 0.4918, MCC: 0.0196, F1: 0.6076

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23632668920925728
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66986 | val 0.75496
  Epoch 012 - train 0.66352 | val 0.89252
  Classification -> best τ=0.410 (val F1=0.1396)
  Directional -> Accuracy: 0.4605, MCC: -0.0192, F1: 0.5684

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64409 | val 0.86550
  Epoch 020 - train 0.63384 | val 0.90719
  Epoch 022 - train 0.59056 | val 0.83064
  Classification -> best τ=0.300 (val F1=0.2670)
  Directional -> Accuracy: 0.5556, MCC: 0.0507, F1: 0.6552

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67897 | val 0.66070
  Epoch 019 - train 0.60587 | val 1.16151
  Classification -> best τ=0.565 (val F1=0.4593)
  Directional -> Accuracy: 0.5652, MCC: 0.1260, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66362 | val 1.08589
  Epoch 013 - train 0.66435 | val 1.18255
  Classification -> best τ=0.565 (val F1=0.1908)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62369 | val 0.80078
  Epoch 015 - train 0.60478 | val 1.98375
  Classification -> best τ=0.490 (val F1=0.4851)
  Directional -> Accuracy: 0.6000, MCC: 0.2019, F1: 0.6000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65824 | val 0.70239
  Epoch 020 - train 0.60093 | val 0.75103
  Epoch 021 - train 0.57715 | val 0.75571
  Classification -> best τ=0.500 (val F1=0.3433)
  Directional -> Accuracy: 0.6304, MCC: 0.2611, F1: 0.6222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69066 | val 0.72446
  Epoch 014 - train 0.65884 | val 0.81536
  Classification -> best τ=0.405 (val F1=0.2445)
  Directional -> Accuracy: 0.3971, MCC: -0.1167, F1: 0.4810

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66505 | val 0.64261
  Epoch 014 - train 0.65064 | val 0.63172
  Classification -> best τ=0.375 (val F1=0.2810)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64080 | val 1.38645
  Epoch 011 - train 0.65626 | val 1.21156
  Classification -> best τ=0.560 (val F1=0.2784)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67063 | val 0.70738
  Epoch 013 - train 0.63739 | val 0.75071
  Classification -> best τ=0.585 (val F1=0.1730)
  Directional -> Accuracy: 0.5072, MCC: 0.0670, F1: 0.5405

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66687 | val 0.67505
  Epoch 020 - train 0.59728 | val 0.66556
  Epoch 029 - train 0.59246 | val 0.81010
  Classification -> best τ=0.455 (val F1=0.4037)
  Directional -> Accuracy: 0.6531, MCC: 0.3350, F1: 0.4138

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67619 | val 0.79155
  Epoch 012 - train 0.66726 | val 0.80046
  Classification -> best τ=0.515 (val F1=0.1880)
  Directional -> Accuracy: 0.4912, MCC: -0.0129, F1: 0.4082

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59281 | val 0.72676
  Epoch 012 - train 0.56237 | val 0.82771
  Classification -> best τ=0.420 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68457 | val 0.65759
  Epoch 020 - train 0.67351 | val 1.00594
  Epoch 021 - train 0.67380 | val 1.06129
  Classification -> best τ=0.505 (val F1=0.3864)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.2222

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62617 | val 0.73080
  Epoch 013 - train 0.58866 | val 0.82195
  Classification -> best τ=0.585 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64550 | val 0.84200
  Epoch 011 - train 0.63133 | val 0.86252
  Classification -> best τ=0.785 (val F1=0.3104)
  Directional -> Accuracy: 0.5652, MCC: 0.1829, F1: 0.4643

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67895 | val 0.71366
  Epoch 012 - train 0.64787 | val 0.79971
  Classification -> best τ=0.640 (val F1=0.2651)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68437 | val 0.69671
  Epoch 014 - train 0.67245 | val 0.76869
  Classification -> best τ=0.565 (val F1=0.2500)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66995 | val 0.70221
  Epoch 017 - train 0.61001 | val 0.75292
  Classification -> best τ=0.400 (val F1=0.3933)
  Directional -> Accuracy: 0.5156, MCC: 0.1672, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67429 | val 0.66511
  Epoch 013 - train 0.66009 | val 0.70988
  Classification -> best τ=0.555 (val F1=0.3301)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67300 | val 0.69972
  Epoch 011 - train 0.66104 | val 0.70022
  Classification -> best τ=0.465 (val F1=0.3678)
  Directional -> Accuracy: 0.5745, MCC: 0.0406, F1: 0.6875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66498 | val 0.91624
  Epoch 011 - train 0.65086 | val 0.81974
  Classification -> best τ=0.320 (val F1=0.2371)
  Directional -> Accuracy: 0.4462, MCC: -0.1092, F1: 0.4706

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68311 | val 0.78474
  Epoch 012 - train 0.66516 | val 0.82736
  Classification -> best τ=0.540 (val F1=0.3382)
  Directional -> Accuracy: 0.5263, MCC: 0.0169, F1: 0.6087

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68028 | val 0.73025
  Epoch 011 - train 0.64946 | val 0.74522
  Classification -> best τ=0.440 (val F1=0.1348)
  Directional -> Accuracy: 0.5692, MCC: 0.1509, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66279 | val 0.77773
  Epoch 019 - train 0.57505 | val 0.88266
  Classification -> best τ=0.470 (val F1=0.3918)
  Directional -> Accuracy: 0.6000, MCC: 0.1796, F1: 0.6765

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66879 | val 1.07274
  Epoch 011 - train 0.65316 | val 1.03196
  Classification -> best τ=0.585 (val F1=0.1310)
  Directional -> Accuracy: 0.5333, MCC: 0.0086, F1: 0.3636

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67662 | val 0.75040
  Epoch 011 - train 0.66300 | val 0.75001
  Classification -> best τ=0.440 (val F1=0.1698)
  Directional -> Accuracy: 0.6429, MCC: 0.2501, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69323 | val 0.78800
  Epoch 013 - train 0.64895 | val 0.85326
  Classification -> best τ=0.420 (val F1=0.2724)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64189 | val 1.11422
  Epoch 011 - train 0.62872 | val 1.18366
  Classification -> best τ=0.480 (val F1=0.2618)
  Directional -> Accuracy: 0.5250, MCC: -0.1448, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66687 | val 0.70639
  Epoch 011 - train 0.63185 | val 0.76260
  Classification -> best τ=0.590 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67820 | val 0.77051
  Epoch 015 - train 0.64360 | val 0.77671
  Classification -> best τ=0.545 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70783 | val 0.74280
  Epoch 018 - train 0.63684 | val 0.73903
  Classification -> best τ=0.490 (val F1=0.2812)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68471 | val 0.67924
  Epoch 012 - train 0.68119 | val 0.70879
  Classification -> best τ=0.515 (val F1=0.3380)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67887 | val 0.95675
  Epoch 016 - train 0.63063 | val 1.04000
  Classification -> best τ=0.570 (val F1=0.3385)
  Directional -> Accuracy: 0.5349, MCC: 0.1579, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67085 | val 0.74920
  Epoch 011 - train 0.65026 | val 0.76190
  Classification -> best τ=0.430 (val F1=0.2357)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63990 | val 0.85151
  Epoch 011 - train 0.62903 | val 0.85045
  Classification -> best τ=0.485 (val F1=0.0229)
  Directional -> Accuracy: 0.6667, MCC: 0.3920, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67230 | val 0.80208
  Epoch 011 - train 0.63956 | val 0.70179
  Classification -> best τ=0.480 (val F1=0.2450)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.4828

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66297 | val 0.85257
  Epoch 011 - train 0.64436 | val 0.93545
  Classification -> best τ=0.430 (val F1=0.2321)
  Directional -> Accuracy: 0.4783, MCC: 0.0244, F1: 0.4545

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66282 | val 0.71120
  Epoch 011 - train 0.64609 | val 0.70105
  Classification -> best τ=0.485 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64718 | val 0.87044
  Epoch 012 - train 0.65045 | val 0.74248
  Classification -> best τ=0.580 (val F1=0.3072)
  Directional -> Accuracy: 0.5541, MCC: 0.1199, F1: 0.6024

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68574 | val 0.78965
  Epoch 011 - train 0.66588 | val 0.78770
  Classification -> best τ=0.510 (val F1=0.0271)
  Directional -> Accuracy: 0.5778, MCC: 0.1613, F1: 0.6545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63246 | val 0.98004
  Epoch 012 - train 0.60989 | val 0.92643
  Classification -> best τ=0.660 (val F1=0.4082)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69109 | val 0.78451
  Epoch 012 - train 0.65326 | val 0.77243
  Classification -> best τ=0.555 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68006 | val 0.97478
  Epoch 011 - train 0.66855 | val 0.98992
  Classification -> best τ=0.420 (val F1=0.2212)
  Directional -> Accuracy: 0.4545, MCC: -0.1641, F1: 0.5833

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65221 | val 1.68200
  Epoch 013 - train 0.59626 | val 1.78566
  Classification -> best τ=0.470 (val F1=0.2952)
  Directional -> Accuracy: 0.5357, MCC: 0.0994, F1: 0.6176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68208 | val 0.68474
  Epoch 013 - train 0.66847 | val 0.73777
  Classification -> best τ=0.615 (val F1=0.2351)
  Directional -> Accuracy: 0.4717, MCC: -0.0537, F1: 0.3333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65307 | val 1.14019
  Epoch 013 - train 0.59996 | val 1.17919
  Classification -> best τ=0.745 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67462 | val 0.68530

[I 2026-02-20 02:53:57,772] Trial 95 finished with value: 0.27093338942271633 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.006890697640770194, 'weight_decay': 4.66737260818031e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0351117574203696, 'early_stopping_min_delta': 0.007708935778084358}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.66553 | val 0.68574
  Classification -> best τ=0.500 (val F1=0.0673)
  Directional -> Accuracy: 0.4667, MCC: -0.0733, F1: 0.4074

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27093338942271633
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67887 | val 0.74560
  Epoch 012 - train 0.67476 | val 0.67307
  Classification -> best τ=0.515 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66158 | val 0.74082
  Epoch 019 - train 0.61624 | val 0.81852
  Classification -> best τ=0.360 (val F1=0.3463)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63484 | val 0.67960
  Epoch 013 - train 0.65781 | val 0.70661
  Classification -> best τ=0.530 (val F1=0.4847)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68616 | val 0.81354
  Epoch 014 - train 0.67731 | val 1.20725
  Classification -> best τ=0.420 (val F1=0.1537)
  Directional -> Accuracy: 0.5000, MCC: 0.1127, F1: 0.2128

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64262 | val 1.27563
  Epoch 014 - train 0.57639 | val 1.11251
  Classification -> best τ=0.455 (val F1=0.4342)
  Directional -> Accuracy: 0.5800, MCC: 0.1606, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70603 | val 0.75715
  Epoch 011 - train 0.69807 | val 0.71772
  Classification -> best τ=0.535 (val F1=0.2204)
  Directional -> Accuracy: 0.4348, MCC: -0.1260, F1: 0.4583

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69436 | val 0.69145
  Epoch 014 - train 0.67616 | val 0.72705
  Classification -> best τ=0.440 (val F1=0.3051)
  Directional -> Accuracy: 0.4412, MCC: -0.0032, F1: 0.5250

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65964 | val 0.93775
  Epoch 012 - train 0.67222 | val 0.88794
  Classification -> best τ=0.420 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65503 | val 1.08309
  Epoch 011 - train 0.69381 | val 1.01509
  Classification -> best τ=0.605 (val F1=0.2166)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66594 | val 0.69596
  Epoch 014 - train 0.65092 | val 0.70456
  Classification -> best τ=0.565 (val F1=0.1801)
  Directional -> Accuracy: 0.5072, MCC: 0.1047, F1: 0.5750

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66943 | val 0.66613
  Epoch 014 - train 0.66136 | val 0.66805
  Classification -> best τ=0.420 (val F1=0.2545)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65047 | val 0.80276
  Epoch 014 - train 0.62692 | val 0.84219
  Classification -> best τ=0.590 (val F1=0.1771)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62889 | val 0.75357
  Epoch 013 - train 0.62568 | val 0.68213
  Classification -> best τ=0.475 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69272 | val 0.67444
  Epoch 011 - train 0.70718 | val 0.67557
  Classification -> best τ=0.450 (val F1=0.3706)
  Directional -> Accuracy: 0.5500, MCC: 0.1014, F1: 0.5846

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66422 | val 0.74766
  Epoch 020 - train 0.60181 | val 0.69519
  Epoch 028 - train 0.58716 | val 0.73384
  Classification -> best τ=0.550 (val F1=0.3118)
  Directional -> Accuracy: 0.6078, MCC: 0.2325, F1: 0.6154

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68909 | val 0.68779
  Epoch 014 - train 0.68906 | val 0.69394
  Classification -> best τ=0.700 (val F1=0.2895)
  Directional -> Accuracy: 0.5072, MCC: 0.0674, F1: 0.3462

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.73253 | val 0.81497
  Epoch 012 - train 0.67995 | val 0.80865
  Classification -> best τ=0.605 (val F1=0.2186)
  Directional -> Accuracy: 0.5345, MCC: 0.2498, F1: 0.4490

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69675 | val 0.71892
  Epoch 018 - train 0.64439 | val 0.68840
  Classification -> best τ=0.480 (val F1=0.2921)
  Directional -> Accuracy: 0.5733, MCC: 0.0915, F1: 0.6596

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67747 | val 0.99330
  Epoch 015 - train 0.64529 | val 0.69078
  Classification -> best τ=0.390 (val F1=0.2843)
  Directional -> Accuracy: 0.5312, MCC: -0.0011, F1: 0.6341

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62904 | val 0.87335
  Epoch 013 - train 0.65059 | val 0.77145
  Classification -> best τ=0.540 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67379 | val 0.82185
  Epoch 011 - train 0.67208 | val 0.75765
  Classification -> best τ=0.540 (val F1=0.2309)
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.5385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65783 | val 1.00192
  Epoch 011 - train 0.66529 | val 1.08794
  Classification -> best τ=0.410 (val F1=0.1708)
  Directional -> Accuracy: 0.4000, MCC: -0.1994, F1: 0.3810

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68344 | val 0.69459
  Epoch 011 - train 0.69842 | val 0.67930
  Classification -> best τ=0.510 (val F1=0.3191)
  Directional -> Accuracy: 0.5088, MCC: 0.0801, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65601 | val 0.76200
  Epoch 013 - train 0.64612 | val 0.71439
  Classification -> best τ=0.435 (val F1=0.1348)
  Directional -> Accuracy: 0.4769, MCC: -0.0548, F1: 0.4138

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65690 | val 0.66420
  Epoch 014 - train 0.65583 | val 0.66393
  Classification -> best τ=0.480 (val F1=0.5197)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65679 | val 1.54686
  Epoch 011 - train 0.64722 | val 1.41415
  Classification -> best τ=0.700 (val F1=0.1048)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66460 | val 0.68534
  Epoch 016 - train 0.67205 | val 0.69524
  Classification -> best τ=0.615 (val F1=0.1353)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69398 | val 0.70505
  Epoch 016 - train 0.67526 | val 0.72584
  Classification -> best τ=0.480 (val F1=0.3265)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65312 | val 0.72736
  Epoch 011 - train 0.63892 | val 0.86737
  Classification -> best τ=0.570 (val F1=0.1918)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65336 | val 1.06317
  Epoch 011 - train 0.66503 | val 1.12929
  Classification -> best τ=0.580 (val F1=0.2271)
  Directional -> Accuracy: 0.5000, MCC: -0.0793, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67969 | val 0.67457
  Epoch 017 - train 0.61283 | val 0.86371
  Classification -> best τ=0.590 (val F1=0.2357)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66290 | val 0.68182
  Epoch 015 - train 0.64737 | val 0.81975
  Classification -> best τ=0.455 (val F1=0.3647)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68786 | val 0.61439
  Epoch 020 - train 0.66033 | val 0.71944
  Classification -> best τ=0.455 (val F1=0.4286)
  Directional -> Accuracy: 0.5833, MCC: 0.1890, F1: 0.5714

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67925 | val 0.91441
  Epoch 012 - train 0.66241 | val 1.08660
  Classification -> best τ=0.555 (val F1=0.1539)
  Directional -> Accuracy: 0.5349, MCC: 0.1527, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70544 | val 0.71579
  Epoch 014 - train 0.63762 | val 0.92567
  Classification -> best τ=0.395 (val F1=0.2357)
  Directional -> Accuracy: 0.6515, MCC: 0.2660, F1: 0.7416

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65820 | val 0.74946
  Epoch 011 - train 0.65755 | val 0.75322
  Classification -> best τ=0.450 (val F1=0.1745)
  Directional -> Accuracy: 0.6905, MCC: 0.3792, F1: 0.7234

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64400 | val 0.75858
  Epoch 011 - train 0.61506 | val 0.79867
  Classification -> best τ=0.395 (val F1=0.2114)
  Directional -> Accuracy: 0.5000, MCC: 0.0731, F1: 0.6216

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65828 | val 0.81812
  Epoch 012 - train 0.64403 | val 0.92623
  Classification -> best τ=0.285 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68478 | val 0.67544
  Epoch 012 - train 0.65233 | val 0.80060
  Classification -> best τ=0.425 (val F1=0.3378)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64655 | val 0.72766
  Epoch 019 - train 0.61894 | val 0.68809
  Classification -> best τ=0.410 (val F1=0.4739)
  Directional -> Accuracy: 0.4730, MCC: -0.1202, F1: 0.6422

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65352 | val 0.87094
  Epoch 011 - train 0.64198 | val 0.85016
  Classification -> best τ=0.495 (val F1=0.4332)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62395 | val 0.86658
  Epoch 011 - train 0.60508 | val 0.93423
  Classification -> best τ=0.475 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0807, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65944 | val 0.64165
  Epoch 020 - train 0.65761 | val 0.65397
  Epoch 027 - train 0.61464 | val 0.94292
  Classification -> best τ=0.655 (val F1=0.4478)
  Directional -> Accuracy: 0.6042, MCC: 0.0176, F1: 0.1739

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69417 | val 0.89434
  Epoch 012 - train 0.66847 | val 0.87823
  Classification -> best τ=0.440 (val F1=0.0876)
  Directional -> Accuracy: 0.3455, MCC: -0.3298, F1: 0.4194

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63306 | val 1.05036
  Epoch 011 - train 0.62644 | val 1.04124
  Classification -> best τ=0.695 (val F1=0.2037)
  Directional -> Accuracy: 0.5179, MCC: 0.0246, F1: 0.4000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67965 | val 0.69464
  Epoch 018 - train 0.68936 | val 0.68589
  Classification -> best τ=0.585 (val F1=0.1168)
  Directional -> Accuracy: 0.4906, MCC: -0.0067, F1: 0.1818

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64554 | val 2.48631
  Epoch 011 - train 0.62541 | val 2.41457
  Classification -> best τ=0.595 (val F1=0.2203)
  Directional -> Accuracy: 0.3455, MCC: -0.3271, F1: 0.4194

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68891 | val 0.67637

[I 2026-02-20 02:56:23,029] Trial 96 finished with value: 0.2620858786186796 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.006333850943428662, 'weight_decay': 5.012668556092148e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0003189961995664, 'early_stopping_min_delta': 0.008410892785436322}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.66979 | val 0.68804
  Classification -> best τ=0.395 (val F1=0.1624)
  Directional -> Accuracy: 0.5000, MCC: 0.1259, F1: 0.6591

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2620858786186796
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63920 | val 0.84246
  Epoch 012 - train 0.57787 | val 0.77253
  Classification -> best τ=0.635 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68665 | val 1.11875
  Epoch 014 - train 0.61922 | val 1.35060
  Classification -> best τ=0.355 (val F1=0.3487)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64325 | val 0.68729
  Epoch 018 - train 0.52227 | val 0.99693
  Classification -> best τ=0.620 (val F1=0.3482)
  Directional -> Accuracy: 0.4783, MCC: -0.0200, F1: 0.2500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63988 | val 1.31134
  Epoch 012 - train 0.57866 | val 2.13219
  Classification -> best τ=0.385 (val F1=0.1918)
  Directional -> Accuracy: 0.4324, MCC: -0.1094, F1: 0.1923

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56932 | val 0.72147
  Epoch 011 - train 0.53781 | val 0.85180
  Classification -> best τ=0.545 (val F1=0.4048)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51901 | val 1.47558
  Epoch 019 - train 0.33130 | val 0.73723
  Classification -> best τ=0.730 (val F1=0.2699)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60076 | val 1.12466
  Epoch 018 - train 0.55907 | val 2.07248
  Classification -> best τ=0.385 (val F1=0.2460)
  Directional -> Accuracy: 0.4118, MCC: 0.0280, F1: 0.5652

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66493 | val 1.07584
  Epoch 011 - train 0.64956 | val 0.91001
  Classification -> best τ=0.425 (val F1=0.2168)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55416 | val 1.87247
  Epoch 011 - train 0.53578 | val 1.72081
  Classification -> best τ=0.645 (val F1=0.1435)
  Directional -> Accuracy: 0.7292, MCC: 0.4783, F1: 0.5806

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51476 | val 0.98036
  Epoch 011 - train 0.53240 | val 1.44921
  Classification -> best τ=0.430 (val F1=0.2986)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59484 | val 0.70842
  Epoch 011 - train 0.60482 | val 0.77773
  Classification -> best τ=0.320 (val F1=0.2498)
  Directional -> Accuracy: 0.4694, MCC: -0.0637, F1: 0.4348

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48182 | val 3.33818
  Epoch 011 - train 0.44338 | val 4.63017
  Classification -> best τ=0.435 (val F1=0.3307)
  Directional -> Accuracy: 0.6316, MCC: 0.2635, F1: 0.6316

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54523 | val 1.08566
  Epoch 011 - train 0.50352 | val 0.80386
  Classification -> best τ=0.485 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62999 | val 1.67706
  Epoch 015 - train 0.52976 | val 1.40299
  Classification -> best τ=0.400 (val F1=0.3477)
  Directional -> Accuracy: 0.5667, MCC: 0.1667, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53005 | val 3.73854
  Epoch 016 - train 0.45444 | val 2.60245
  Classification -> best τ=0.620 (val F1=0.2298)
  Directional -> Accuracy: 0.5294, MCC: -0.0061, F1: 0.2500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68333 | val 0.90169
  Epoch 012 - train 0.64444 | val 0.95552
  Classification -> best τ=0.590 (val F1=0.3849)
  Directional -> Accuracy: 0.6087, MCC: 0.2102, F1: 0.6966

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64618 | val 1.91556
  Epoch 012 - train 0.60851 | val 2.79692
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58493 | val 0.96791
  Epoch 012 - train 0.57645 | val 1.31157
  Classification -> best τ=0.745 (val F1=0.2220)
  Directional -> Accuracy: 0.4533, MCC: 0.1938, F1: 0.1633

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59762 | val 0.87647
  Epoch 012 - train 0.56897 | val 0.95196
  Classification -> best τ=0.375 (val F1=0.2428)
  Directional -> Accuracy: 0.4531, MCC: -0.0664, F1: 0.4444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49315 | val 1.99021
  Epoch 011 - train 0.52674 | val 1.58232
  Classification -> best τ=0.690 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62077 | val 0.70252
  Epoch 020 - train 0.44593 | val 0.93509
  Epoch 022 - train 0.38262 | val 1.54310
  Classification -> best τ=0.505 (val F1=0.5079)
  Directional -> Accuracy: 0.5106, MCC: 0.1957, F1: 0.4103

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62331 | val 1.65141
  Epoch 013 - train 0.53653 | val 2.51546
  Classification -> best τ=0.340 (val F1=0.1890)
  Directional -> Accuracy: 0.4308, MCC: -0.1393, F1: 0.4478

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65807 | val 1.39027
  Epoch 014 - train 0.52915 | val 3.04849
  Classification -> best τ=0.270 (val F1=0.3680)
  Directional -> Accuracy: 0.4035, MCC: -0.2012, F1: 0.4516

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61399 | val 0.96273
  Epoch 011 - train 0.57993 | val 0.78424
  Classification -> best τ=0.610 (val F1=0.2451)
  Directional -> Accuracy: 0.5231, MCC: 0.0242, F1: 0.3111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54478 | val 1.59450
  Epoch 012 - train 0.52188 | val 2.99270
  Classification -> best τ=0.555 (val F1=0.3091)
  Directional -> Accuracy: 0.4909, MCC: -0.0133, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58813 | val 2.43298
  Epoch 011 - train 0.52340 | val 2.83413
  Classification -> best τ=0.680 (val F1=0.1868)
  Directional -> Accuracy: 0.4000, MCC: -0.1323, F1: 0.5574

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58638 | val 0.73716
  Epoch 013 - train 0.51888 | val 1.03887
  Classification -> best τ=0.570 (val F1=0.1936)
  Directional -> Accuracy: 0.3571, MCC: -0.3203, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55280 | val 1.22162
  Epoch 011 - train 0.51871 | val 1.34980
  Classification -> best τ=0.275 (val F1=0.2149)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61446 | val 1.09474
  Epoch 012 - train 0.53401 | val 1.17677
  Classification -> best τ=0.415 (val F1=0.2414)
  Directional -> Accuracy: 0.6250, MCC: 0.2447, F1: 0.7273

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58826 | val 0.77539
  Epoch 016 - train 0.41788 | val 1.00395
  Classification -> best τ=0.810 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54927 | val 1.19269
  Epoch 016 - train 0.46481 | val 1.26864
  Classification -> best τ=0.645 (val F1=0.0365)
  Directional -> Accuracy: 0.5238, MCC: 0.0026, F1: 0.6296

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59297 | val 1.02542
  Epoch 015 - train 0.36341 | val 1.13316
  Classification -> best τ=0.390 (val F1=0.3232)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59421 | val 2.21278
  Epoch 013 - train 0.57742 | val 1.44758
  Classification -> best τ=0.775 (val F1=0.2637)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60572 | val 2.10665
  Epoch 011 - train 0.55636 | val 2.54168
  Classification -> best τ=0.725 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61042 | val 1.07347
  Epoch 011 - train 0.57182 | val 1.28615
  Classification -> best τ=0.105 (val F1=0.3855)
  Directional -> Accuracy: 0.6364, MCC: 0.3156, F1: 0.6250

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45253 | val 2.48022
  Epoch 011 - train 0.40653 | val 2.56163
  Classification -> best τ=0.525 (val F1=0.2439)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54837 | val 3.44900
  Epoch 012 - train 0.41713 | val 4.84460
  Classification -> best τ=0.405 (val F1=0.2327)
  Directional -> Accuracy: 0.5357, MCC: 0.0199, F1: 0.1333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41398 | val 1.63789
  Epoch 011 - train 0.42673 | val 1.42426
  Classification -> best τ=0.490 (val F1=0.3690)
  Directional -> Accuracy: 0.5870, MCC: 0.0903, F1: 0.6885

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59347 | val 1.28913
  Epoch 015 - train 0.43728 | val 1.23418
  Classification -> best τ=0.310 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63969 | val 0.76377
  Epoch 011 - train 0.55827 | val 0.71369
  Classification -> best τ=0.340 (val F1=0.3040)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47816 | val 0.89380
  Epoch 011 - train 0.46985 | val 0.95327
  Classification -> best τ=0.550 (val F1=0.2767)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60027 | val 0.88935
  Epoch 016 - train 0.45437 | val 1.77882
  Classification -> best τ=0.640 (val F1=0.5819)
  Directional -> Accuracy: 0.3333, MCC: -0.3746, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69134 | val 1.18170
  Epoch 014 - train 0.45854 | val 1.16381
  Classification -> best τ=0.740 (val F1=0.0203)
  Directional -> Accuracy: 0.5417, MCC: 0.1826, F1: 0.5600

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60043 | val 2.12765
  Epoch 011 - train 0.56931 | val 2.66427
  Classification -> best τ=0.685 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56607 | val 2.85405
  Epoch 012 - train 0.53265 | val 3.45328
  Classification -> best τ=0.830 (val F1=0.3556)
  Directional -> Accuracy: 0.5179, MCC: 0.0357, F1: 0.5091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62622 | val 0.86857
  Epoch 012 - train 0.61941 | val 0.90978
  Classification -> best τ=0.565 (val F1=0.3048)
  Directional -> Accuracy: 0.5094, MCC: 0.0252, F1: 0.4348

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53339 | val 1.87344
  Epoch 012 - train 0.52096 | val 2.35180
  Classification -> best τ=0.730 (val F1=0.1884)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65759 | val 0.69568

[I 2026-02-20 02:58:09,826] Trial 97 finished with value: 0.2739850380399485 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.009778889724285676, 'weight_decay': 2.4866912790740503e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.8633526956645949, 'early_stopping_min_delta': 0.00767733740071545}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 017 - train 0.56713 | val 0.82619
  Classification -> best τ=0.470 (val F1=0.2337)
  Directional -> Accuracy: 0.5833, MCC: 0.1638, F1: 0.5098

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2739850380399485
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65094 | val 0.67827
  Epoch 011 - train 0.63210 | val 0.69496
  Classification -> best τ=0.410 (val F1=0.2510)
  Directional -> Accuracy: 0.4342, MCC: -0.1702, F1: 0.2951

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64248 | val 0.82534
  Epoch 013 - train 0.54486 | val 0.67963
  Classification -> best τ=0.315 (val F1=0.2670)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65891 | val 0.71610
  Epoch 012 - train 0.61123 | val 0.79670
  Classification -> best τ=0.575 (val F1=0.3882)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62136 | val 0.96931
  Epoch 012 - train 0.62567 | val 1.22631
  Classification -> best τ=0.445 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67640 | val 0.61043
  Epoch 020 - train 0.61495 | val 0.83255
  Classification -> best τ=0.480 (val F1=0.5175)
  Directional -> Accuracy: 0.7000, MCC: 0.4120, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60412 | val 0.89133
  Epoch 011 - train 0.68066 | val 0.88348
  Classification -> best τ=0.490 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0496, F1: 0.5417

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64313 | val 0.91911
  Epoch 011 - train 0.65411 | val 0.94625
  Classification -> best τ=0.450 (val F1=0.2013)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60323 | val 0.60264
  Epoch 014 - train 0.51959 | val 0.66818
  Classification -> best τ=0.295 (val F1=0.2810)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57499 | val 0.78879
  Epoch 014 - train 0.55283 | val 1.03397
  Classification -> best τ=0.505 (val F1=0.2326)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63210 | val 0.89680
  Epoch 013 - train 0.60437 | val 0.75146
  Classification -> best τ=0.500 (val F1=0.1200)
  Directional -> Accuracy: 0.5507, MCC: -0.1471, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64879 | val 0.91890
  Epoch 012 - train 0.65991 | val 0.90489
  Classification -> best τ=0.390 (val F1=0.1833)
  Directional -> Accuracy: 0.6327, MCC: 0.2465, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61700 | val 2.06798
  Epoch 012 - train 0.54969 | val 3.48567
  Classification -> best τ=0.510 (val F1=0.3307)
  Directional -> Accuracy: 0.5614, MCC: 0.1764, F1: 0.3590

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63515 | val 0.63860
  Epoch 020 - train 0.43801 | val 4.42743
  Classification -> best τ=0.490 (val F1=0.3721)
  Directional -> Accuracy: 0.5000, MCC: 0.0454, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69575 | val 0.61008
  Epoch 020 - train 0.64123 | val 0.65635
  Epoch 026 - train 0.67009 | val 0.88905
  Classification -> best τ=0.535 (val F1=0.3289)
  Directional -> Accuracy: 0.6000, MCC: 0.2182, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57837 | val 0.73898
  Epoch 011 - train 0.58517 | val 0.81874
  Classification -> best τ=0.450 (val F1=0.1526)
  Directional -> Accuracy: 0.5686, MCC: 0.1560, F1: 0.0833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68662 | val 0.73948
  Epoch 011 - train 0.64971 | val 0.96475
  Classification -> best τ=0.735 (val F1=0.1976)
  Directional -> Accuracy: 0.5072, MCC: 0.0596, F1: 0.3704

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65974 | val 1.31502
  Epoch 012 - train 0.58272 | val 1.81881
  Classification -> best τ=0.490 (val F1=0.3128)
  Directional -> Accuracy: 0.3793, MCC: -0.1805, F1: 0.3571

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64486 | val 0.78357
  Epoch 011 - train 0.60593 | val 0.69327
  Classification -> best τ=0.555 (val F1=0.1773)
  Directional -> Accuracy: 0.4533, MCC: 0.1938, F1: 0.1633

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61765 | val 0.75612
  Epoch 012 - train 0.62197 | val 0.96551
  Classification -> best τ=0.350 (val F1=0.2843)
  Directional -> Accuracy: 0.5625, MCC: 0.1782, F1: 0.5333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64486 | val 0.80098
  Epoch 014 - train 0.60693 | val 0.92931
  Classification -> best τ=0.375 (val F1=0.3045)
  Directional -> Accuracy: 0.4865, MCC: 0.1844, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63508 | val 1.12482
  Epoch 012 - train 0.66736 | val 0.88375
  Classification -> best τ=0.495 (val F1=0.2784)
  Directional -> Accuracy: 0.5745, MCC: -0.1661, F1: 0.7297

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69366 | val 0.81563
  Epoch 012 - train 0.66115 | val 1.10973
  Classification -> best τ=0.685 (val F1=0.1925)
  Directional -> Accuracy: 0.4462, MCC: -0.1180, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70004 | val 0.69631
  Epoch 011 - train 0.69028 | val 0.67695
  Classification -> best τ=0.795 (val F1=0.3144)
  Directional -> Accuracy: 0.5088, MCC: 0.0937, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65704 | val 0.68749
  Epoch 015 - train 0.61011 | val 0.73421
  Classification -> best τ=0.425 (val F1=0.1348)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56353 | val 1.56351
  Epoch 011 - train 0.60122 | val 1.35199
  Classification -> best τ=0.560 (val F1=0.4839)
  Directional -> Accuracy: 0.5091, MCC: 0.0913, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62474 | val 1.01747
  Epoch 011 - train 0.59134 | val 1.06623
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59300 | val 0.75653
  Epoch 013 - train 0.57570 | val 0.79351
  Classification -> best τ=0.500 (val F1=0.2041)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.2000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63785 | val 0.76828
  Epoch 014 - train 0.53729 | val 0.88482
  Classification -> best τ=0.380 (val F1=0.2530)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.81311 | val 1.49498
  Epoch 012 - train 0.56383 | val 1.74258
  Classification -> best τ=0.510 (val F1=0.2774)
  Directional -> Accuracy: 0.4500, MCC: -0.0909, F1: 0.4500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.73516 | val 0.76402
  Epoch 014 - train 0.64981 | val 0.69088
  Classification -> best τ=0.655 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62226 | val 1.35797
  Epoch 011 - train 0.54219 | val 1.28935
  Classification -> best τ=0.730 (val F1=0.1286)
  Directional -> Accuracy: 0.4048, MCC: -0.1758, F1: 0.1379

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65515 | val 0.85213
  Epoch 014 - train 0.55212 | val 0.84268
  Classification -> best τ=0.505 (val F1=0.4120)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70726 | val 0.62579
  Epoch 020 - train 0.62034 | val 0.65050
  Classification -> best τ=0.505 (val F1=0.4460)
  Directional -> Accuracy: 0.5417, MCC: 0.1239, F1: 0.4923

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69901 | val 0.97683
  Epoch 015 - train 0.61510 | val 1.18652
  Classification -> best τ=0.320 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66295 | val 0.80780
  Epoch 015 - train 0.55500 | val 0.86896
  Classification -> best τ=0.365 (val F1=0.3280)
  Directional -> Accuracy: 0.4848, MCC: 0.1062, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53451 | val 0.81060
  Epoch 015 - train 0.50187 | val 2.62211
  Classification -> best τ=0.595 (val F1=0.2618)
  Directional -> Accuracy: 0.6905, MCC: 0.4122, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58870 | val 1.50252
  Epoch 013 - train 0.55817 | val 1.29616
  Classification -> best τ=0.300 (val F1=0.2450)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59249 | val 0.89205
  Epoch 013 - train 0.52468 | val 0.76888
  Classification -> best τ=0.520 (val F1=0.2804)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61691 | val 0.84380
  Epoch 016 - train 0.57450 | val 0.78562
  Classification -> best τ=0.440 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63266 | val 0.66946
  Epoch 020 - train 0.52750 | val 0.85666
  Classification -> best τ=0.145 (val F1=0.4032)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60022 | val 1.02999
  Epoch 012 - train 0.58033 | val 1.60956
  Classification -> best τ=0.435 (val F1=0.4080)
  Directional -> Accuracy: 0.5778, MCC: 0.1549, F1: 0.6275

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65327 | val 0.90459
  Epoch 012 - train 0.61360 | val 1.01893
  Classification -> best τ=0.395 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66693 | val 0.83601
  Epoch 016 - train 0.58389 | val 0.77346
  Classification -> best τ=0.610 (val F1=0.4092)
  Directional -> Accuracy: 0.4167, MCC: 0.0778, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69997 | val 0.72539
  Epoch 017 - train 0.61555 | val 0.68621
  Classification -> best τ=0.475 (val F1=0.1884)
  Directional -> Accuracy: 0.5091, MCC: -0.1773, F1: 0.6747

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68426 | val 1.20355
  Epoch 011 - train 0.64926 | val 1.26755
  Classification -> best τ=0.645 (val F1=0.2143)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63900 | val 0.71112
  Epoch 020 - train 0.60273 | val 0.96482
  Epoch 021 - train 0.54894 | val 1.04330
  Classification -> best τ=0.685 (val F1=0.1668)
  Directional -> Accuracy: 0.5849, MCC: 0.1688, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69274 | val 0.72829
  Epoch 012 - train 0.66731 | val 0.81754
  Classification -> best τ=0.375 (val F1=0.0955)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63388 | val 0.71376

[I 2026-02-20 02:59:21,965] Trial 98 finished with value: 0.26819319461371843 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.009674749108683217, 'weight_decay': 4.309729402073107e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.8129783995155091, 'early_stopping_min_delta': 0.00755044273340593}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.59310 | val 0.71359
  Classification -> best τ=0.390 (val F1=0.2006)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26819319461371843
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68516 | val 0.68177
  Epoch 011 - train 0.67843 | val 0.68188
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69345 | val 0.70269
  Epoch 011 - train 0.68358 | val 0.70410
  Classification -> best τ=0.460 (val F1=0.0551)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68983 | val 0.81795
  Epoch 011 - train 0.69005 | val 0.81495
  Classification -> best τ=0.565 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67595 | val 1.00355
  Epoch 011 - train 0.68118 | val 1.01794
  Classification -> best τ=0.555 (val F1=0.1537)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68358 | val 0.70092
  Epoch 011 - train 0.68486 | val 0.69875
  Classification -> best τ=0.490 (val F1=0.0018)
  Directional -> Accuracy: 0.3200, MCC: -0.4016, F1: 0.4333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67304 | val 0.69956
  Epoch 011 - train 0.67254 | val 0.69922
  Classification -> best τ=0.480 (val F1=0.1537)
  Directional -> Accuracy: 0.3913, MCC: -0.2241, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69367 | val 0.71260
  Epoch 011 - train 0.69612 | val 0.71068
  Classification -> best τ=0.525 (val F1=0.1234)
  Directional -> Accuracy: 0.5735, MCC: 0.0581, F1: 0.3556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69503 | val 0.94698
  Epoch 011 - train 0.67487 | val 0.98305
  Classification -> best τ=0.480 (val F1=0.2657)
  Directional -> Accuracy: 0.6190, MCC: 0.1936, F1: 0.4286

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69273 | val 0.69687
  Epoch 011 - train 0.68054 | val 0.69663
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66811 | val 0.78220
  Epoch 011 - train 0.67690 | val 0.78894
  Classification -> best τ=0.525 (val F1=0.2079)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68127 | val 0.80896
  Epoch 011 - train 0.68048 | val 0.81038
  Classification -> best τ=0.565 (val F1=0.2687)
  Directional -> Accuracy: 0.5510, MCC: 0.0306, F1: 0.1538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68923 | val 0.97369
  Epoch 011 - train 0.70571 | val 0.97431
  Classification -> best τ=0.450 (val F1=0.2428)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67349 | val 0.90056
  Epoch 011 - train 0.67108 | val 0.90652
  Classification -> best τ=0.465 (val F1=0.1733)
  Directional -> Accuracy: 0.5714, MCC: 0.2415, F1: 0.6538

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71088 | val 0.74268
  Epoch 011 - train 0.69648 | val 0.74170
  Classification -> best τ=0.530 (val F1=0.1406)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65909 | val 0.71674
  Epoch 011 - train 0.67569 | val 0.71679
  Classification -> best τ=0.545 (val F1=0.0716)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67950 | val 0.82247
  Epoch 011 - train 0.69435 | val 0.82379
  Classification -> best τ=0.455 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68052 | val 0.91349
  Epoch 011 - train 0.68914 | val 0.91629
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68706 | val 0.86721
  Epoch 011 - train 0.69853 | val 0.87347
  Classification -> best τ=0.490 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68448 | val 0.68758
  Epoch 011 - train 0.69137 | val 0.68753
  Classification -> best τ=0.545 (val F1=0.3357)
  Directional -> Accuracy: 0.5469, MCC: 0.0286, F1: 0.6506

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66733 | val 0.79099
  Epoch 011 - train 0.67028 | val 0.79736
  Classification -> best τ=0.495 (val F1=0.1812)
  Directional -> Accuracy: 0.6216, MCC: 0.2236, F1: 0.6818

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70674 | val 0.85217
  Epoch 011 - train 0.70951 | val 0.85162
  Classification -> best τ=0.480 (val F1=0.0603)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69316 | val 0.67422
  Epoch 013 - train 0.70194 | val 0.67399
  Classification -> best τ=0.540 (val F1=0.3086)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69119 | val 0.68937
  Epoch 013 - train 0.68856 | val 0.69077
  Classification -> best τ=0.570 (val F1=0.2644)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68577 | val 1.78090
  Epoch 011 - train 0.69759 | val 1.77376
  Classification -> best τ=0.600 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: -0.0719, F1: 0.3200

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66657 | val 0.65368
  Epoch 020 - train 0.66667 | val 0.64588
  Epoch 022 - train 0.64644 | val 0.64659
  Classification -> best τ=0.515 (val F1=0.3851)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68380 | val 0.76743
  Epoch 011 - train 0.68229 | val 0.77321
  Classification -> best τ=0.475 (val F1=0.2035)
  Directional -> Accuracy: 0.5111, MCC: 0.2670, F1: 0.6333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69896 | val 0.86939
  Epoch 011 - train 0.68846 | val 0.87249
  Classification -> best τ=0.525 (val F1=0.0574)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.1538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67773 | val 0.72011
  Epoch 011 - train 0.67603 | val 0.71955
  Classification -> best τ=0.480 (val F1=0.1222)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67741 | val 0.69145
  Epoch 016 - train 0.67998 | val 0.69163
  Classification -> best τ=0.430 (val F1=0.3518)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69750 | val 0.69586
  Epoch 011 - train 0.70858 | val 0.69565
  Classification -> best τ=0.480 (val F1=0.2814)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71669 | val 0.67995
  Epoch 013 - train 0.71461 | val 0.67878
  Classification -> best τ=0.460 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68893 | val 0.68676
  Epoch 020 - train 0.66959 | val 0.68405
  Epoch 023 - train 0.65916 | val 0.68432
  Classification -> best τ=0.475 (val F1=0.3502)
  Directional -> Accuracy: 0.5102, MCC: 0.1311, F1: 0.2000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68314 | val 0.72891
  Epoch 011 - train 0.68853 | val 0.72838
  Classification -> best τ=0.555 (val F1=0.3111)
  Directional -> Accuracy: 0.5139, MCC: -0.0205, F1: 0.6154

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69833 | val 0.68550
  Epoch 011 - train 0.70095 | val 0.69058
  Classification -> best τ=0.415 (val F1=0.1309)
  Directional -> Accuracy: 0.3023, MCC: -0.4133, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68574 | val 0.67204
  Epoch 020 - train 0.66041 | val 0.65756
  Epoch 030 - train 0.64964 | val 0.65731
  Classification -> best τ=0.310 (val F1=0.3855)
  Directional -> Accuracy: 0.6061, MCC: 0.1678, F1: 0.6905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67256 | val 0.74534
  Epoch 011 - train 0.69897 | val 0.74681
  Classification -> best τ=0.520 (val F1=0.2618)
  Directional -> Accuracy: 0.5238, MCC: 0.0337, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68844 | val 0.71208
  Epoch 011 - train 0.66494 | val 0.71173
  Classification -> best τ=0.535 (val F1=0.0741)
  Directional -> Accuracy: 0.4464, MCC: -0.1222, F1: 0.3673

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70119 | val 0.77544
  Epoch 011 - train 0.67836 | val 0.77821
  Classification -> best τ=0.495 (val F1=0.2562)
  Directional -> Accuracy: 0.4783, MCC: 0.0706, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66891 | val 0.66083
  Epoch 020 - train 0.66075 | val 0.65108
  Epoch 022 - train 0.65679 | val 0.64981
  Classification -> best τ=0.470 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: -0.0636, F1: 0.5079

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67425 | val 0.68629
  Epoch 014 - train 0.64824 | val 0.69232
  Classification -> best τ=0.650 (val F1=0.2001)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66126 | val 0.70262
  Epoch 011 - train 0.66978 | val 0.70348
  Classification -> best τ=0.470 (val F1=0.4394)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69483 | val 0.66579
  Epoch 018 - train 0.67633 | val 0.66500
  Classification -> best τ=0.445 (val F1=0.4588)
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.6875

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70622 | val 0.65685
  Epoch 017 - train 0.66743 | val 0.66889
  Classification -> best τ=0.545 (val F1=0.3752)
  Directional -> Accuracy: 0.6042, MCC: 0.1843, F1: 0.5128

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68109 | val 0.70218
  Epoch 011 - train 0.69229 | val 0.70297
  Classification -> best τ=0.540 (val F1=0.1053)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68122 | val 0.66347
  Epoch 015 - train 0.68129 | val 0.67054
  Classification -> best τ=0.505 (val F1=0.3432)
  Directional -> Accuracy: 0.4643, MCC: -0.1303, F1: 0.1667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68388 | val 0.70454
  Epoch 013 - train 0.68716 | val 0.70544
  Classification -> best τ=0.550 (val F1=0.1801)
  Directional -> Accuracy: 0.5094, MCC: 0.0585, F1: 0.1875

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69592 | val 0.83094
  Epoch 011 - train 0.67034 | val 0.84264
  Classification -> best τ=0.520 (val F1=0.1738)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68003 | val 0.73856
  Epoch 011 - train 0.68466 | val 0.73823

[I 2026-02-20 03:01:04,871] Trial 99 finished with value: 0.21322763365767206 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 1.5698124451652598e-05, 'weight_decay': 1.7852813117286216e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.740899735620798, 'early_stopping_min_delta': 0.0077468215570015925}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.535 (val F1=0.3195)
  Directional -> Accuracy: 0.5000, MCC: -0.0160, F1: 0.3478

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21322763365767206
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65042 | val 0.71766
  Epoch 012 - train 0.65227 | val 0.67265
  Classification -> best τ=0.470 (val F1=0.2510)
  Directional -> Accuracy: 0.6184, MCC: 0.2149, F1: 0.5085

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63916 | val 0.70391
  Epoch 012 - train 0.64157 | val 0.69053
  Classification -> best τ=0.405 (val F1=0.2204)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66687 | val 0.66505
  Epoch 013 - train 0.65144 | val 0.68639
  Classification -> best τ=0.490 (val F1=0.3135)
  Directional -> Accuracy: 0.6087, MCC: 0.2145, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67286 | val 0.74827
  Epoch 011 - train 0.68117 | val 0.76890
  Classification -> best τ=0.520 (val F1=0.1079)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60378 | val 0.71451
  Epoch 013 - train 0.60496 | val 0.87466
  Classification -> best τ=0.510 (val F1=0.5079)
  Directional -> Accuracy: 0.5000, MCC: 0.1373, F1: 0.0741

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66169 | val 0.78572
  Epoch 011 - train 0.64088 | val 0.75465
  Classification -> best τ=0.435 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66117 | val 0.79174
  Epoch 011 - train 0.67541 | val 0.79631
  Classification -> best τ=0.445 (val F1=0.1963)
  Directional -> Accuracy: 0.4559, MCC: 0.1465, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58648 | val 0.77418
  Epoch 015 - train 0.61705 | val 0.77307
  Classification -> best τ=0.300 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68478 | val 0.73517
  Epoch 013 - train 0.62519 | val 0.89765
  Classification -> best τ=0.510 (val F1=0.3433)
  Directional -> Accuracy: 0.6458, MCC: 0.2817, F1: 0.4138

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60583 | val 0.72679
  Epoch 012 - train 0.62792 | val 0.77150
  Classification -> best τ=0.500 (val F1=0.3633)
  Directional -> Accuracy: 0.4348, MCC: 0.0376, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68380 | val 0.69822
  Epoch 011 - train 0.63906 | val 0.71489
  Classification -> best τ=0.395 (val F1=0.1949)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64913 | val 1.18907
  Epoch 011 - train 0.66382 | val 1.29611
  Classification -> best τ=0.405 (val F1=0.2157)
  Directional -> Accuracy: 0.5263, MCC: 0.0675, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64174 | val 0.97670
  Epoch 012 - train 0.62425 | val 0.92859
  Classification -> best τ=0.455 (val F1=0.2115)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67238 | val 0.66893
  Epoch 015 - train 0.63083 | val 0.71612
  Classification -> best τ=0.395 (val F1=0.3387)
  Directional -> Accuracy: 0.5333, MCC: 0.0673, F1: 0.5625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63050 | val 0.74377
  Epoch 015 - train 0.57260 | val 0.84224
  Classification -> best τ=0.525 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69383 | val 0.66530
  Epoch 018 - train 0.64883 | val 0.79661
  Classification -> best τ=0.425 (val F1=0.2341)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65516 | val 0.91834
  Epoch 014 - train 0.61969 | val 1.15459
  Classification -> best τ=0.495 (val F1=0.0811)
  Directional -> Accuracy: 0.6207, MCC: 0.1135, F1: 0.7381

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66210 | val 1.04288
  Epoch 011 - train 0.64809 | val 1.13425
  Classification -> best τ=0.430 (val F1=0.1311)
  Directional -> Accuracy: 0.4667, MCC: 0.1684, F1: 0.2308

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63254 | val 0.93171
  Epoch 015 - train 0.63181 | val 1.18369
  Classification -> best τ=0.410 (val F1=0.3624)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69424 | val 0.67896
  Epoch 013 - train 0.68121 | val 0.69757
  Classification -> best τ=0.575 (val F1=0.3062)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64461 | val 0.70438
  Epoch 012 - train 0.68067 | val 0.68610
  Classification -> best τ=0.485 (val F1=0.2258)
  Directional -> Accuracy: 0.5532, MCC: 0.1469, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70174 | val 0.76651
  Epoch 012 - train 0.67384 | val 0.87070
  Classification -> best τ=0.540 (val F1=0.2508)
  Directional -> Accuracy: 0.5077, MCC: 0.0103, F1: 0.5897

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66455 | val 0.72813
  Epoch 011 - train 0.66572 | val 0.72461
  Classification -> best τ=0.500 (val F1=0.3294)
  Directional -> Accuracy: 0.5965, MCC: 0.1923, F1: 0.6230

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67337 | val 0.75309
  Epoch 014 - train 0.66259 | val 0.74563
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61378 | val 0.68749
  Epoch 015 - train 0.62579 | val 0.91526
  Classification -> best τ=0.425 (val F1=0.4543)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.73338 | val 0.99191
  Epoch 012 - train 0.63618 | val 0.87567
  Classification -> best τ=0.465 (val F1=0.2035)
  Directional -> Accuracy: 0.5111, MCC: 0.2029, F1: 0.6207

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67515 | val 0.68531
  Epoch 011 - train 0.66847 | val 0.69234
  Classification -> best τ=0.610 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67451 | val 0.72501
  Epoch 014 - train 0.64486 | val 0.83753
  Classification -> best τ=0.340 (val F1=0.1986)
  Directional -> Accuracy: 0.5536, MCC: 0.2640, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.75923 | val 0.68764
  Epoch 011 - train 0.65595 | val 0.70154
  Classification -> best τ=0.500 (val F1=0.1457)
  Directional -> Accuracy: 0.6500, MCC: 0.3685, F1: 0.7586

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67917 | val 0.76052
  Epoch 015 - train 0.64282 | val 0.86663
  Classification -> best τ=0.720 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62075 | val 0.90007
  Epoch 011 - train 0.64580 | val 0.95640
  Classification -> best τ=0.460 (val F1=0.2238)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65195 | val 0.70119
  Epoch 013 - train 0.58167 | val 0.83170
  Classification -> best τ=0.580 (val F1=0.3465)
  Directional -> Accuracy: 0.4898, MCC: -0.1940, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63771 | val 0.65575
  Epoch 015 - train 0.61695 | val 0.71611
  Classification -> best τ=0.455 (val F1=0.3681)
  Directional -> Accuracy: 0.5417, MCC: 0.1239, F1: 0.4923

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66863 | val 0.80261
  Epoch 011 - train 0.68568 | val 0.87080
  Classification -> best τ=0.530 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68285 | val 0.70194
  Epoch 019 - train 0.67151 | val 0.72156
  Classification -> best τ=0.380 (val F1=0.3280)
  Directional -> Accuracy: 0.6061, MCC: 0.2295, F1: 0.6176

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63140 | val 0.70759
  Epoch 011 - train 0.62046 | val 0.71225
  Classification -> best τ=0.490 (val F1=0.1745)
  Directional -> Accuracy: 0.7143, MCC: 0.4273, F1: 0.7273

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63793 | val 0.73728
  Epoch 011 - train 0.57383 | val 0.84502
  Classification -> best τ=0.455 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0103, F1: 0.5172

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60284 | val 0.85540
  Epoch 011 - train 0.55929 | val 0.88092
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62236 | val 0.84647
  Epoch 016 - train 0.58416 | val 0.76746
  Classification -> best τ=0.560 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64249 | val 0.65861
  Epoch 020 - train 0.57843 | val 0.69145
  Epoch 028 - train 0.58657 | val 0.79472
  Classification -> best τ=0.495 (val F1=0.3765)
  Directional -> Accuracy: 0.5135, MCC: 0.0910, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69808 | val 0.70898
  Epoch 016 - train 0.58643 | val 0.79954
  Classification -> best τ=0.460 (val F1=0.4632)
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65989 | val 0.76620
  Epoch 012 - train 0.66462 | val 0.91651
  Classification -> best τ=0.530 (val F1=0.4588)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66209 | val 0.75848
  Epoch 020 - train 0.63304 | val 0.77894
  Epoch 022 - train 0.64207 | val 0.79285
  Classification -> best τ=0.700 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67113 | val 0.67264
  Epoch 012 - train 0.63512 | val 0.67382
  Classification -> best τ=0.560 (val F1=0.1763)
  Directional -> Accuracy: 0.4909, MCC: -0.2193, F1: 0.6585

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63526 | val 1.42206
  Epoch 011 - train 0.61122 | val 1.51213
  Classification -> best τ=0.510 (val F1=0.2696)
  Directional -> Accuracy: 0.5357, MCC: 0.0994, F1: 0.6176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67791 | val 0.74106
  Epoch 017 - train 0.62222 | val 0.82195
  Classification -> best τ=0.445 (val F1=0.2415)
  Directional -> Accuracy: 0.5283, MCC: 0.0562, F1: 0.6377

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65800 | val 0.82959
  Epoch 012 - train 0.63821 | val 0.89604
  Classification -> best τ=0.590 (val F1=0.1605)
  Directional -> Accuracy: 0.4364, MCC: -0.1258, F1: 0.1622

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 03:02:03,002] Trial 100 finished with value: 0.25361755113503115 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.006796987520113939, 'weight_decay': 1.6371661240753718e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9264251856001696, 'early_stopping_min_delta': 0.00895761118662331}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 010 - train 0.65196 | val 0.71484
  Epoch 011 - train 0.63511 | val 0.72186
  Classification -> best τ=0.460 (val F1=0.1722)
  Directional -> Accuracy: 0.4833, MCC: -0.1248, F1: 0.0606

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25361755113503115
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57583 | val 0.97363
  Epoch 011 - train 0.59144 | val 0.96640
  Classification -> best τ=0.375 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0559, F1: 0.4444

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54676 | val 1.10593
  Epoch 011 - train 0.51055 | val 1.00741
  Classification -> best τ=0.520 (val F1=0.1273)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57764 | val 0.80742
  Epoch 012 - train 0.49027 | val 0.83246
  Classification -> best τ=0.315 (val F1=0.3212)
  Directional -> Accuracy: 0.5870, MCC: 0.2143, F1: 0.4865

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57781 | val 2.08484
  Epoch 011 - train 0.55409 | val 3.25522
  Classification -> best τ=0.665 (val F1=0.0803)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52988 | val 2.32364
  Epoch 011 - train 0.49729 | val 2.04132
  Classification -> best τ=0.685 (val F1=0.2964)
  Directional -> Accuracy: 0.5000, MCC: 0.0415, F1: 0.2424

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59588 | val 0.87353
  Epoch 020 - train 0.40163 | val 1.10657
  Epoch 024 - train 0.23322 | val 1.88917
  Classification -> best τ=0.540 (val F1=0.4047)
  Directional -> Accuracy: 0.5870, MCC: 0.2307, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61541 | val 2.17813
  Epoch 012 - train 0.55784 | val 2.62430
  Classification -> best τ=0.555 (val F1=0.2236)
  Directional -> Accuracy: 0.4706, MCC: -0.0663, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55818 | val 3.67958
  Epoch 015 - train 0.35962 | val 2.57492
  Classification -> best τ=0.330 (val F1=0.3855)
  Directional -> Accuracy: 0.5476, MCC: -0.0534, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52232 | val 2.60400
  Epoch 011 - train 0.45369 | val 2.44071
  Classification -> best τ=0.545 (val F1=0.2784)
  Directional -> Accuracy: 0.7083, MCC: 0.4371, F1: 0.5333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57068 | val 0.74989
  Epoch 011 - train 0.52858 | val 0.76218
  Classification -> best τ=0.490 (val F1=0.1858)
  Directional -> Accuracy: 0.4058, MCC: -0.1061, F1: 0.5393

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59556 | val 1.02331
  Epoch 011 - train 0.54798 | val 1.30071
  Classification -> best τ=0.585 (val F1=0.2687)
  Directional -> Accuracy: 0.6327, MCC: 0.2465, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54629 | val 1.99406
  Epoch 012 - train 0.48081 | val 2.35692
  Classification -> best τ=0.800 (val F1=0.3401)
  Directional -> Accuracy: 0.4912, MCC: -0.1313, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48908 | val 1.35336
  Epoch 014 - train 0.42539 | val 0.82089
  Classification -> best τ=0.340 (val F1=0.1658)
  Directional -> Accuracy: 0.4286, MCC: -0.1083, F1: 0.5385

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65063 | val 1.19553
  Epoch 015 - train 0.56950 | val 0.90593
  Classification -> best τ=0.735 (val F1=0.2531)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48031 | val 1.91046
  Epoch 011 - train 0.48708 | val 1.93233
  Classification -> best τ=0.445 (val F1=0.2381)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68490 | val 1.30134
  Epoch 012 - train 0.61021 | val 1.04162
  Classification -> best τ=0.585 (val F1=0.1841)
  Directional -> Accuracy: 0.4928, MCC: -0.0765, F1: 0.6237

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59085 | val 1.85001
  Epoch 011 - train 0.54945 | val 2.18900
  Classification -> best τ=0.745 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54676 | val 2.16493
  Epoch 011 - train 0.51081 | val 2.18195
  Classification -> best τ=0.430 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60734 | val 0.76710
  Epoch 013 - train 0.54951 | val 3.02053
  Classification -> best τ=0.395 (val F1=0.2843)
  Directional -> Accuracy: 0.4844, MCC: -0.0624, F1: 0.5600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49401 | val 1.48542
  Epoch 011 - train 0.51233 | val 2.44606
  Classification -> best τ=0.720 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64854 | val 0.89196
  Epoch 013 - train 0.50242 | val 1.04577
  Classification -> best τ=0.470 (val F1=0.3262)
  Directional -> Accuracy: 0.5745, MCC: 0.0406, F1: 0.6875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60188 | val 1.61441
  Epoch 011 - train 0.61854 | val 1.52966
  Classification -> best τ=0.550 (val F1=0.2766)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54276 | val 1.29883
  Epoch 011 - train 0.54381 | val 1.33557
  Classification -> best τ=0.595 (val F1=0.2236)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58157 | val 0.98462
  Epoch 012 - train 0.59407 | val 0.96662
  Classification -> best τ=0.540 (val F1=0.2055)
  Directional -> Accuracy: 0.5846, MCC: 0.1741, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52618 | val 1.89895
  Epoch 012 - train 0.46765 | val 1.94281
  Classification -> best τ=0.530 (val F1=0.6005)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52921 | val 2.53539
  Epoch 011 - train 0.42814 | val 2.59078
  Classification -> best τ=0.825 (val F1=0.0385)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.4375

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54178 | val 0.73569
  Epoch 012 - train 0.54557 | val 0.91599
  Classification -> best τ=0.515 (val F1=0.0962)
  Directional -> Accuracy: 0.5952, MCC: 0.2240, F1: 0.5854

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52935 | val 1.32604
  Epoch 011 - train 0.52165 | val 1.54110
  Classification -> best τ=0.685 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58412 | val 1.19474
  Epoch 014 - train 0.53837 | val 1.52912
  Classification -> best τ=0.660 (val F1=0.1608)
  Directional -> Accuracy: 0.5750, MCC: 0.1182, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51337 | val 0.77640
  Epoch 011 - train 0.46019 | val 0.74681
  Classification -> best τ=0.465 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55361 | val 0.84607
  Epoch 011 - train 0.51326 | val 0.76696
  Classification -> best τ=0.460 (val F1=0.2042)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52994 | val 1.06612
  Epoch 013 - train 0.47767 | val 1.13611
  Classification -> best τ=0.520 (val F1=0.3461)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65089 | val 0.70157
  Epoch 013 - train 0.54177 | val 0.81875
  Classification -> best τ=0.215 (val F1=0.4318)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61914 | val 1.78765
  Epoch 011 - train 0.60663 | val 2.12446
  Classification -> best τ=0.810 (val F1=0.2603)
  Directional -> Accuracy: 0.4651, MCC: -0.0693, F1: 0.4651

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62882 | val 0.90938
  Epoch 012 - train 0.58430 | val 0.92592
  Classification -> best τ=0.315 (val F1=0.4328)
  Directional -> Accuracy: 0.5606, MCC: 0.1530, F1: 0.5538

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48984 | val 1.13268
  Epoch 015 - train 0.44057 | val 1.85230
  Classification -> best τ=0.400 (val F1=0.2144)
  Directional -> Accuracy: 0.6190, MCC: 0.2340, F1: 0.6522

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52534 | val 1.33223
  Epoch 011 - train 0.56055 | val 1.15248
  Classification -> best τ=0.335 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55742 | val 0.91189
  Epoch 011 - train 0.54598 | val 0.86945
  Classification -> best τ=0.465 (val F1=0.2338)
  Directional -> Accuracy: 0.5000, MCC: 0.0602, F1: 0.4889

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60834 | val 0.83960
  Epoch 017 - train 0.39861 | val 1.44521
  Classification -> best τ=0.330 (val F1=0.5489)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61256 | val 1.15372
  Epoch 020 - train 0.53277 | val 1.22260
  Epoch 025 - train 0.50518 | val 1.40148
  Classification -> best τ=0.710 (val F1=0.4605)
  Directional -> Accuracy: 0.4595, MCC: -0.0783, F1: 0.5652

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47611 | val 0.77394
  Epoch 012 - train 0.42159 | val 0.85958
  Classification -> best τ=0.355 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0069, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52665 | val 1.45666
  Epoch 011 - train 0.51184 | val 1.87048
  Classification -> best τ=0.530 (val F1=0.4001)
  Directional -> Accuracy: 0.4762, MCC: -0.1021, F1: 0.5769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53744 | val 0.88516
  Epoch 016 - train 0.40229 | val 1.08306
  Classification -> best τ=0.500 (val F1=0.5261)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63396 | val 1.00272
  Epoch 011 - train 0.62761 | val 1.02894
  Classification -> best τ=0.495 (val F1=0.0226)
  Directional -> Accuracy: 0.4727, MCC: -0.1695, F1: 0.6234

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52369 | val 3.34541
  Epoch 011 - train 0.47228 | val 3.35836
  Classification -> best τ=0.595 (val F1=0.4642)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59121 | val 0.82728
  Epoch 012 - train 0.50136 | val 1.65258
  Classification -> best τ=0.630 (val F1=0.0537)
  Directional -> Accuracy: 0.5849, MCC: 0.1739, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60610 | val 5.22791
  Epoch 014 - train 0.48984 | val 5.35065
  Classification -> best τ=0.920 (val F1=0.2203)
  Directional -> Accuracy: 0.3818, MCC: -0.2336, F1: 0.2609

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55721 | val 1.01000

[I 2026-02-20 03:03:36,163] Trial 101 finished with value: 0.2710425650175456 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.00838861302382937, 'weight_decay': 2.2065864562978358e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1796149277571437, 'early_stopping_min_delta': 0.009313509617316498}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.58886 | val 0.88349
  Classification -> best τ=0.640 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2710425650175456
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56231 | val 1.82756
  Epoch 011 - train 0.55341 | val 2.59526
  Classification -> best τ=0.480 (val F1=0.2036)
  Directional -> Accuracy: 0.5395, MCC: -0.0465, F1: 0.0541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60615 | val 0.87603
  Epoch 013 - train 0.44981 | val 1.14283
  Classification -> best τ=0.455 (val F1=0.0618)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.6545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54445 | val 0.91711
  Epoch 012 - train 0.50104 | val 1.09279
  Classification -> best τ=0.565 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63056 | val 1.04491
  Epoch 013 - train 0.56440 | val 0.73875
  Classification -> best τ=0.645 (val F1=0.1537)
  Directional -> Accuracy: 0.5270, MCC: 0.2482, F1: 0.2222

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53455 | val 1.37556
  Epoch 012 - train 0.53465 | val 1.18805
  Classification -> best τ=0.715 (val F1=0.3641)
  Directional -> Accuracy: 0.6000, MCC: 0.1961, F1: 0.6429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50643 | val 1.09359
  Epoch 011 - train 0.56464 | val 0.70846
  Classification -> best τ=0.635 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58782 | val 2.31005
  Epoch 012 - train 0.57140 | val 1.93071
  Classification -> best τ=0.305 (val F1=0.2555)
  Directional -> Accuracy: 0.4118, MCC: 0.0991, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65483 | val 0.63073
  Epoch 014 - train 0.33843 | val 1.43611
  Classification -> best τ=0.115 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55741 | val 4.71451
  Epoch 015 - train 0.38756 | val 6.61186
  Classification -> best τ=0.470 (val F1=0.4025)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53727 | val 1.30294
  Epoch 013 - train 0.48384 | val 1.40205
  Classification -> best τ=0.430 (val F1=0.1885)
  Directional -> Accuracy: 0.4928, MCC: 0.0209, F1: 0.5070

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69999 | val 0.69538
  Epoch 020 - train 0.51085 | val 1.52917
  Epoch 021 - train 0.53307 | val 1.74936
  Classification -> best τ=0.465 (val F1=0.3492)
  Directional -> Accuracy: 0.4694, MCC: -0.0474, F1: 0.4800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48318 | val 1.53226
  Epoch 011 - train 0.46535 | val 2.03060
  Classification -> best τ=0.505 (val F1=0.1512)
  Directional -> Accuracy: 0.4737, MCC: -0.1083, F1: 0.6250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44513 | val 1.55451
  Epoch 011 - train 0.45696 | val 2.14003
  Classification -> best τ=0.445 (val F1=0.2438)
  Directional -> Accuracy: 0.5238, MCC: 0.0912, F1: 0.5833

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62344 | val 1.18120
  Epoch 016 - train 0.48646 | val 1.54188
  Classification -> best τ=0.250 (val F1=0.2396)
  Directional -> Accuracy: 0.4833, MCC: -0.0338, F1: 0.4364

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54011 | val 1.98415
  Epoch 011 - train 0.52804 | val 1.77390
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66181 | val 0.93661
  Epoch 018 - train 0.53645 | val 0.95391
  Classification -> best τ=0.200 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55917 | val 1.89578
  Epoch 011 - train 0.52636 | val 2.21919
  Classification -> best τ=0.385 (val F1=0.0032)
  Directional -> Accuracy: 0.5345, MCC: -0.1805, F1: 0.6897

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50911 | val 1.30071
  Epoch 011 - train 0.48057 | val 1.44935
  Classification -> best τ=0.430 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65016 | val 0.86052
  Epoch 012 - train 0.61080 | val 1.32034
  Classification -> best τ=0.325 (val F1=0.2752)
  Directional -> Accuracy: 0.5469, MCC: 0.1389, F1: 0.5246

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53478 | val 1.14573
  Epoch 011 - train 0.47028 | val 1.20114
  Classification -> best τ=0.510 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57253 | val 0.93638
  Epoch 015 - train 0.49679 | val 0.78977
  Classification -> best τ=0.630 (val F1=0.4959)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62467 | val 1.44040
  Epoch 012 - train 0.58277 | val 1.40109
  Classification -> best τ=0.435 (val F1=0.2237)
  Directional -> Accuracy: 0.4308, MCC: -0.1377, F1: 0.3934

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68577 | val 1.38711
  Epoch 014 - train 0.52891 | val 1.70379
  Classification -> best τ=0.835 (val F1=0.3144)
  Directional -> Accuracy: 0.4912, MCC: 0.0739, F1: 0.3256

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59158 | val 1.68812
  Epoch 012 - train 0.54395 | val 1.99912
  Classification -> best τ=0.440 (val F1=0.1599)
  Directional -> Accuracy: 0.4923, MCC: 0.1194, F1: 0.6526

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54062 | val 1.40403
  Epoch 012 - train 0.52758 | val 1.59751
  Classification -> best τ=0.675 (val F1=0.5048)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51381 | val 4.17934
  Epoch 011 - train 0.47901 | val 4.95613
  Classification -> best τ=0.825 (val F1=0.1890)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.1905

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59974 | val 0.75514
  Epoch 015 - train 0.43664 | val 0.83022
  Classification -> best τ=0.575 (val F1=0.0468)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54383 | val 1.52800
  Epoch 011 - train 0.47302 | val 1.64145
  Classification -> best τ=0.420 (val F1=0.2354)
  Directional -> Accuracy: 0.5357, MCC: 0.1376, F1: 0.4348

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52799 | val 0.85527
  Epoch 012 - train 0.51448 | val 0.76532
  Classification -> best τ=0.435 (val F1=0.4099)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55035 | val 0.71289
  Epoch 012 - train 0.46293 | val 0.87837
  Classification -> best τ=0.735 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63739 | val 3.00240
  Epoch 014 - train 0.48668 | val 2.89272
  Classification -> best τ=0.555 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50890 | val 0.86917
  Epoch 011 - train 0.54624 | val 0.98334
  Classification -> best τ=0.525 (val F1=0.3574)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55945 | val 0.99448
  Epoch 011 - train 0.53010 | val 1.25063
  Classification -> best τ=0.315 (val F1=0.2414)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59381 | val 1.57894
  Epoch 011 - train 0.56208 | val 1.48983
  Classification -> best τ=0.480 (val F1=0.3243)
  Directional -> Accuracy: 0.5814, MCC: 0.1612, F1: 0.5500

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55578 | val 1.40629
  Epoch 013 - train 0.44773 | val 1.94315
  Classification -> best τ=0.225 (val F1=0.3787)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43780 | val 0.95857
  Epoch 012 - train 0.45263 | val 1.16730
  Classification -> best τ=0.420 (val F1=0.2658)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58421 | val 1.20630
  Epoch 011 - train 0.52118 | val 2.01111
  Classification -> best τ=0.190 (val F1=0.1718)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53150 | val 0.94336
  Epoch 011 - train 0.53304 | val 0.90090
  Classification -> best τ=0.575 (val F1=0.2441)
  Directional -> Accuracy: 0.5000, MCC: 0.0393, F1: 0.5106

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57568 | val 0.89336
  Epoch 015 - train 0.41645 | val 1.05615
  Classification -> best τ=0.525 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55191 | val 1.42674
  Epoch 013 - train 0.50146 | val 1.38817
  Classification -> best τ=0.435 (val F1=0.3805)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65709 | val 0.74678
  Epoch 014 - train 0.50658 | val 1.26562
  Classification -> best τ=0.460 (val F1=0.1890)
  Directional -> Accuracy: 0.6000, MCC: 0.2703, F1: 0.7097

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50952 | val 1.21856
  Epoch 011 - train 0.44780 | val 1.41335
  Classification -> best τ=0.620 (val F1=0.5601)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.5652

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53204 | val 0.80618
  Epoch 012 - train 0.52208 | val 0.89186
  Classification -> best τ=0.430 (val F1=0.5081)
  Directional -> Accuracy: 0.3958, MCC: -0.1089, F1: 0.4528

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61776 | val 1.26764
  Epoch 011 - train 0.55258 | val 1.48791
  Classification -> best τ=0.490 (val F1=0.1605)
  Directional -> Accuracy: 0.5818, MCC: 0.1372, F1: 0.6761

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45056 | val 2.39203
  Epoch 011 - train 0.48232 | val 3.09354
  Classification -> best τ=0.500 (val F1=0.3809)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66990 | val 1.02724
  Epoch 012 - train 0.62786 | val 1.44414
  Classification -> best τ=0.680 (val F1=0.1668)
  Directional -> Accuracy: 0.5094, MCC: 0.0417, F1: 0.2778

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59803 | val 2.98653
  Epoch 014 - train 0.55521 | val 2.73906
  Classification -> best τ=0.670 (val F1=0.1053)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58725 | val 1.32966

[I 2026-02-20 03:05:06,507] Trial 102 finished with value: 0.2583198511066969 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.007307540113528703, 'weight_decay': 2.3048301920051637e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.8616460858390751, 'early_stopping_min_delta': 0.008377188650114772}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.51843 | val 2.42273
  Classification -> best τ=0.345 (val F1=0.2337)
  Directional -> Accuracy: 0.6167, MCC: 0.3431, F1: 0.7089

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2583198511066969
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59113 | val 1.04880
  Epoch 011 - train 0.56540 | val 1.52504
  Classification -> best τ=0.420 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0192, F1: 0.2857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61750 | val 0.91753
  Epoch 012 - train 0.51655 | val 1.25360
  Classification -> best τ=0.485 (val F1=0.1022)
  Directional -> Accuracy: 0.6000, MCC: 0.1350, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60882 | val 0.77515
  Epoch 012 - train 0.59202 | val 0.75475
  Classification -> best τ=0.355 (val F1=0.3693)
  Directional -> Accuracy: 0.4783, MCC: -0.0826, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56716 | val 2.60938
  Epoch 011 - train 0.54442 | val 4.30861
  Classification -> best τ=0.225 (val F1=0.1115)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50564 | val 1.23508
  Epoch 012 - train 0.43719 | val 1.22403
  Classification -> best τ=0.595 (val F1=0.3933)
  Directional -> Accuracy: 0.7000, MCC: 0.4361, F1: 0.6512

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43031 | val 1.52344
  Epoch 011 - train 0.41469 | val 1.76386
  Classification -> best τ=0.555 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60958 | val 1.29156
  Epoch 013 - train 0.51781 | val 1.35490
  Classification -> best τ=0.180 (val F1=0.2463)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55268 | val 0.69219
  Epoch 019 - train 0.27118 | val 1.03388
  Classification -> best τ=0.280 (val F1=0.2168)
  Directional -> Accuracy: 0.5238, MCC: 0.0849, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57171 | val 1.54915
  Epoch 011 - train 0.51661 | val 1.46953
  Classification -> best τ=0.630 (val F1=0.2443)
  Directional -> Accuracy: 0.6042, MCC: 0.2887, F1: 0.6545

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62580 | val 1.31378
  Epoch 017 - train 0.47260 | val 1.01203
  Classification -> best τ=0.380 (val F1=0.2982)
  Directional -> Accuracy: 0.4638, MCC: -0.0392, F1: 0.4789

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60518 | val 0.68641
  Epoch 013 - train 0.50231 | val 0.70262
  Classification -> best τ=0.595 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59813 | val 0.72748
  Epoch 019 - train 0.36629 | val 1.83115
  Classification -> best τ=0.610 (val F1=0.3429)
  Directional -> Accuracy: 0.6316, MCC: 0.2799, F1: 0.6957

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47023 | val 1.42217
  Epoch 012 - train 0.47271 | val 2.24937
  Classification -> best τ=0.490 (val F1=0.2176)
  Directional -> Accuracy: 0.5000, MCC: -0.0976, F1: 0.1600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64473 | val 0.91211
  Epoch 014 - train 0.58660 | val 1.51446
  Classification -> best τ=0.390 (val F1=0.3387)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56449 | val 1.50684
  Epoch 012 - train 0.52731 | val 1.96448
  Classification -> best τ=0.510 (val F1=0.1499)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58829 | val 0.96876
  Epoch 013 - train 0.50832 | val 1.49242
  Classification -> best τ=0.465 (val F1=0.2155)
  Directional -> Accuracy: 0.4638, MCC: -0.2162, F1: 0.6263

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55862 | val 2.42601
  Epoch 013 - train 0.43994 | val 5.08685
  Classification -> best τ=0.280 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56880 | val 1.10989
  Epoch 011 - train 0.57449 | val 1.49481
  Classification -> best τ=0.380 (val F1=0.1769)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59582 | val 0.76558
  Epoch 012 - train 0.60689 | val 0.88686
  Classification -> best τ=0.350 (val F1=0.2522)
  Directional -> Accuracy: 0.5156, MCC: 0.0416, F1: 0.5373

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46287 | val 1.53951
  Epoch 011 - train 0.47523 | val 1.80490
  Classification -> best τ=0.855 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56223 | val 0.81858
  Epoch 020 - train 0.35989 | val 2.46565
  Epoch 022 - train 0.32931 | val 2.82460
  Classification -> best τ=0.430 (val F1=0.3732)
  Directional -> Accuracy: 0.5106, MCC: 0.1957, F1: 0.4103

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63769 | val 0.76402
  Epoch 011 - train 0.63847 | val 0.81200
  Classification -> best τ=0.435 (val F1=0.2879)
  Directional -> Accuracy: 0.4769, MCC: -0.0540, F1: 0.5526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73275 | val 1.41070
  Epoch 014 - train 0.58872 | val 1.86605
  Classification -> best τ=0.475 (val F1=0.4222)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60736 | val 1.46111
  Epoch 012 - train 0.63651 | val 2.67671
  Classification -> best τ=0.485 (val F1=0.2192)
  Directional -> Accuracy: 0.5385, MCC: 0.1256, F1: 0.6341

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48905 | val 1.96687
  Epoch 011 - train 0.46757 | val 1.97148
  Classification -> best τ=0.465 (val F1=0.3563)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46803 | val 2.75530
  Epoch 011 - train 0.53230 | val 3.15026
  Classification -> best τ=0.685 (val F1=0.3368)
  Directional -> Accuracy: 0.3778, MCC: -0.3181, F1: 0.1765

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51683 | val 0.88851
  Epoch 011 - train 0.50692 | val 0.91728
  Classification -> best τ=0.600 (val F1=0.0534)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61948 | val 0.96154
  Epoch 011 - train 0.60640 | val 1.19376
  Classification -> best τ=0.460 (val F1=0.1235)
  Directional -> Accuracy: 0.4286, MCC: -0.0961, F1: 0.2000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65045 | val 1.03869
  Epoch 012 - train 0.60139 | val 1.07334
  Classification -> best τ=0.505 (val F1=0.2267)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55180 | val 0.83441
  Epoch 018 - train 0.35365 | val 0.86661
  Classification -> best τ=0.315 (val F1=0.3689)
  Directional -> Accuracy: 0.4286, MCC: -0.1589, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53385 | val 1.63176
  Epoch 013 - train 0.43680 | val 1.16192
  Classification -> best τ=0.500 (val F1=0.3419)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61696 | val 0.78934
  Epoch 011 - train 0.58338 | val 0.95564
  Classification -> best τ=0.450 (val F1=0.2488)
  Directional -> Accuracy: 0.4694, MCC: -0.0554, F1: 0.4583

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65830 | val 1.29034
  Epoch 013 - train 0.52251 | val 1.54000
  Classification -> best τ=0.330 (val F1=0.3366)
  Directional -> Accuracy: 0.5694, MCC: 0.0839, F1: 0.7048

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66553 | val 2.32020
  Epoch 016 - train 0.48160 | val 3.21309
  Classification -> best τ=0.645 (val F1=0.1027)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61840 | val 0.85526
  Epoch 011 - train 0.57614 | val 1.04786
  Classification -> best τ=0.705 (val F1=0.2249)
  Directional -> Accuracy: 0.4394, MCC: -0.0636, F1: 0.3509

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40566 | val 2.05929
  Epoch 016 - train 0.25265 | val 2.88797
  Classification -> best τ=0.120 (val F1=0.3068)
  Directional -> Accuracy: 0.6667, MCC: 0.3319, F1: 0.7083

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49833 | val 1.98936
  Epoch 012 - train 0.43130 | val 2.81245
  Classification -> best τ=0.460 (val F1=0.2305)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53244 | val 1.82101
  Epoch 011 - train 0.44410 | val 2.40541
  Classification -> best τ=0.470 (val F1=0.2882)
  Directional -> Accuracy: 0.5652, MCC: 0.0094, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58441 | val 0.72253
  Epoch 015 - train 0.46118 | val 0.73953
  Classification -> best τ=0.470 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59934 | val 0.94736
  Epoch 012 - train 0.54958 | val 0.84329
  Classification -> best τ=0.565 (val F1=0.3584)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54592 | val 1.26944
  Epoch 012 - train 0.49442 | val 1.52786
  Classification -> best τ=0.530 (val F1=0.1890)
  Directional -> Accuracy: 0.5111, MCC: 0.0832, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59443 | val 1.03163
  Epoch 011 - train 0.52711 | val 1.24107
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61760 | val 1.75357
  Epoch 012 - train 0.52688 | val 1.59602
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63908 | val 2.35416
  Epoch 011 - train 0.61791 | val 2.73003
  Classification -> best τ=0.745 (val F1=0.0174)
  Directional -> Accuracy: 0.3273, MCC: -0.3376, F1: 0.2128

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61165 | val 2.64311
  Epoch 017 - train 0.41613 | val 2.92082
  Classification -> best τ=0.845 (val F1=0.2649)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63107 | val 0.91478
  Epoch 013 - train 0.61002 | val 1.02975
  Classification -> best τ=0.530 (val F1=0.2608)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60401 | val 2.81564
  Epoch 012 - train 0.54232 | val 4.41257
  Classification -> best τ=0.865 (val F1=0.1884)
  Directional -> Accuracy: 0.4364, MCC: -0.1152, F1: 0.3111

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56880 | val 1.00253
  Epoch 011 - train 0.55374 | val 0.69552

[I 2026-02-20 03:06:44,160] Trial 103 finished with value: 0.24561283992203967 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.008483405221773158, 'weight_decay': 4.151509922351101e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1811563043827586, 'early_stopping_min_delta': 0.00932320582475193}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.515 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24561283992203967
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61948 | val 2.50724
  Epoch 011 - train 0.59334 | val 4.02408
  Classification -> best τ=0.405 (val F1=0.2627)
  Directional -> Accuracy: 0.5132, MCC: 0.1137, F1: 0.6105

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63014 | val 1.16615
  Epoch 016 - train 0.51626 | val 1.40369
  Classification -> best τ=0.620 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59050 | val 0.72294
  Epoch 020 - train 0.46950 | val 1.54018
  Epoch 023 - train 0.44121 | val 1.34879
  Classification -> best τ=0.370 (val F1=0.3214)
  Directional -> Accuracy: 0.5652, MCC: 0.1348, F1: 0.6774

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60510 | val 2.21858
  Epoch 011 - train 0.57611 | val 1.80731
  Classification -> best τ=0.310 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51763 | val 1.26278
  Epoch 012 - train 0.45285 | val 1.06159
  Classification -> best τ=0.525 (val F1=0.5217)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49772 | val 1.30777
  Epoch 011 - train 0.50297 | val 1.34909
  Classification -> best τ=0.600 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66928 | val 1.39188
  Epoch 013 - train 0.60564 | val 2.12554
  Classification -> best τ=0.320 (val F1=0.1932)
  Directional -> Accuracy: 0.5147, MCC: 0.2521, F1: 0.6118

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54563 | val 3.21875
  Epoch 011 - train 0.54564 | val 3.67845
  Classification -> best τ=0.515 (val F1=0.0807)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59046 | val 2.37624
  Epoch 011 - train 0.57067 | val 2.48160
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60522 | val 1.15486
  Epoch 011 - train 0.61009 | val 1.57541
  Classification -> best τ=0.440 (val F1=0.1801)
  Directional -> Accuracy: 0.4203, MCC: -0.0741, F1: 0.5349

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62122 | val 0.94283
  Epoch 014 - train 0.57375 | val 0.79730
  Classification -> best τ=0.445 (val F1=0.3729)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50815 | val 4.85005
  Epoch 011 - train 0.56691 | val 4.71422
  Classification -> best τ=0.465 (val F1=0.1093)
  Directional -> Accuracy: 0.5614, MCC: 0.1915, F1: 0.6914

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56807 | val 2.21662
  Epoch 013 - train 0.47246 | val 2.22962
  Classification -> best τ=0.295 (val F1=0.2522)
  Directional -> Accuracy: 0.5000, MCC: 0.2032, F1: 0.6441

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63149 | val 0.67031
  Epoch 014 - train 0.54196 | val 0.68283
  Classification -> best τ=0.430 (val F1=0.3145)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56265 | val 1.34297
  Epoch 011 - train 0.54094 | val 1.23525
  Classification -> best τ=0.675 (val F1=0.3516)
  Directional -> Accuracy: 0.4510, MCC: -0.0546, F1: 0.5484

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60266 | val 0.81951
  Epoch 013 - train 0.53780 | val 0.90096
  Classification -> best τ=0.495 (val F1=0.2998)
  Directional -> Accuracy: 0.4783, MCC: -0.0324, F1: 0.4545

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61213 | val 1.74782
  Epoch 011 - train 0.61097 | val 2.00616
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55985 | val 1.52246
  Epoch 011 - train 0.52129 | val 2.03270
  Classification -> best τ=0.530 (val F1=0.2262)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65803 | val 0.77038
  Epoch 015 - train 0.58937 | val 1.07503
  Classification -> best τ=0.535 (val F1=0.2973)
  Directional -> Accuracy: 0.5156, MCC: -0.0082, F1: 0.5974

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63865 | val 0.77747
  Epoch 019 - train 0.50228 | val 1.13794
  Classification -> best τ=0.740 (val F1=0.3008)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66140 | val 0.87545
  Epoch 015 - train 0.58540 | val 0.82954
  Classification -> best τ=0.340 (val F1=0.3678)
  Directional -> Accuracy: 0.5532, MCC: -0.0220, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65156 | val 0.72150
  Epoch 017 - train 0.59462 | val 0.97780
  Classification -> best τ=0.575 (val F1=0.3107)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61108 | val 0.98204
  Epoch 013 - train 0.63939 | val 0.99816
  Classification -> best τ=0.440 (val F1=0.4370)
  Directional -> Accuracy: 0.5614, MCC: 0.1898, F1: 0.4898

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66540 | val 1.66915
  Epoch 011 - train 0.65971 | val 1.65077
  Classification -> best τ=0.395 (val F1=0.2484)
  Directional -> Accuracy: 0.5231, MCC: 0.0924, F1: 0.6265

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64285 | val 1.11359
  Epoch 011 - train 0.57389 | val 1.12166
  Classification -> best τ=0.620 (val F1=0.3446)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51123 | val 2.18687
  Epoch 011 - train 0.50640 | val 2.22376
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67846 | val 0.87826
  Epoch 015 - train 0.58012 | val 0.83211
  Classification -> best τ=0.610 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64610 | val 1.15121
  Epoch 011 - train 0.64828 | val 1.31074
  Classification -> best τ=0.245 (val F1=0.3192)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60489 | val 0.73170
  Epoch 012 - train 0.58150 | val 1.08582
  Classification -> best τ=0.485 (val F1=0.2365)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67124 | val 0.71862
  Epoch 013 - train 0.52905 | val 0.81277
  Classification -> best τ=0.405 (val F1=0.3689)
  Directional -> Accuracy: 0.5476, MCC: 0.1342, F1: 0.6275

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58270 | val 2.54149
  Epoch 011 - train 0.61373 | val 3.25434
  Classification -> best τ=0.390 (val F1=0.2147)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49628 | val 1.32945
  Epoch 011 - train 0.54120 | val 1.18620
  Classification -> best τ=0.550 (val F1=0.2969)
  Directional -> Accuracy: 0.4898, MCC: -0.0268, F1: 0.5283

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64382 | val 0.76989
  Epoch 016 - train 0.57892 | val 0.70733
  Classification -> best τ=0.300 (val F1=0.4023)
  Directional -> Accuracy: 0.5278, MCC: 0.0988, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67347 | val 1.64274
  Epoch 012 - train 0.65496 | val 2.10118
  Classification -> best τ=0.660 (val F1=0.3385)
  Directional -> Accuracy: 0.6279, MCC: 0.2549, F1: 0.6000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58910 | val 0.95482
  Epoch 011 - train 0.55273 | val 1.14576
  Classification -> best τ=0.750 (val F1=0.2249)
  Directional -> Accuracy: 0.3939, MCC: -0.1582, F1: 0.2593

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58094 | val 0.79707
  Epoch 016 - train 0.38964 | val 1.22706
  Classification -> best τ=0.650 (val F1=0.3260)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60448 | val 0.80822
  Epoch 011 - train 0.59199 | val 0.89797
  Classification -> best τ=0.465 (val F1=0.1886)
  Directional -> Accuracy: 0.5179, MCC: -0.0404, F1: 0.1290

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53509 | val 0.97489
  Epoch 011 - train 0.50349 | val 1.01774
  Classification -> best τ=0.440 (val F1=0.3218)
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.5769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66490 | val 1.15802
  Epoch 015 - train 0.49254 | val 1.01279
  Classification -> best τ=0.220 (val F1=0.3970)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62272 | val 1.39493
  Epoch 016 - train 0.49406 | val 1.68978
  Classification -> best τ=0.350 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64882 | val 0.88605
  Epoch 011 - train 0.62678 | val 0.89953
  Classification -> best τ=0.525 (val F1=0.3857)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53948 | val 1.53572
  Epoch 011 - train 0.53454 | val 1.47580
  Classification -> best τ=0.600 (val F1=0.2500)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61017 | val 1.01066
  Epoch 012 - train 0.55895 | val 0.91466
  Classification -> best τ=0.595 (val F1=0.2450)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64755 | val 3.92185
  Epoch 011 - train 0.61166 | val 3.97426
  Classification -> best τ=0.625 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55424 | val 1.08264
  Epoch 013 - train 0.49753 | val 1.53160
  Classification -> best τ=0.525 (val F1=0.3249)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71430 | val 0.67319
  Epoch 014 - train 0.68569 | val 0.69731
  Classification -> best τ=0.440 (val F1=0.3392)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56285 | val 2.88285
  Epoch 011 - train 0.61026 | val 3.17777
  Classification -> best τ=0.880 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65146 | val 0.92371
  Epoch 011 - train 0.63598 | val 0.79742

[I 2026-02-20 03:08:20,655] Trial 104 finished with value: 0.26232575972899075 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.005337875439859026, 'weight_decay': 2.2074197186848684e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.031894694918169, 'early_stopping_min_delta': 0.00964073338755788}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.340 (val F1=0.1489)
  Directional -> Accuracy: 0.4500, MCC: -0.1054, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26232575972899075
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53564 | val 1.80309
  Epoch 011 - train 0.52741 | val 1.99412
  Classification -> best τ=0.870 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47454 | val 1.61988
  Epoch 011 - train 0.46677 | val 2.19530
  Classification -> best τ=0.475 (val F1=0.0732)
  Directional -> Accuracy: 0.6222, MCC: 0.2440, F1: 0.6531

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63900 | val 1.08440
  Epoch 014 - train 0.43224 | val 1.19836
  Classification -> best τ=0.540 (val F1=0.4065)
  Directional -> Accuracy: 0.5652, MCC: 0.2097, F1: 0.3750

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51891 | val 3.27831
  Epoch 011 - train 0.52739 | val 2.91534
  Classification -> best τ=0.235 (val F1=0.2228)
  Directional -> Accuracy: 0.5405, MCC: 0.0283, F1: 0.6792

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51800 | val 0.69936
  Epoch 013 - train 0.52990 | val 0.93558
  Classification -> best τ=0.405 (val F1=0.4851)
  Directional -> Accuracy: 0.7400, MCC: 0.4851, F1: 0.7347

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57640 | val 0.89897
  Epoch 011 - train 0.49269 | val 1.43981
  Classification -> best τ=0.460 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: -0.0496, F1: 0.4286

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59106 | val 1.38669
  Epoch 012 - train 0.55855 | val 1.32266
  Classification -> best τ=0.355 (val F1=0.2101)
  Directional -> Accuracy: 0.3971, MCC: -0.0366, F1: 0.5591

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45278 | val 0.98127
  Epoch 016 - train 0.23067 | val 1.28487
  Classification -> best τ=0.290 (val F1=0.3689)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.4444

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56692 | val 2.77078
  Epoch 012 - train 0.54293 | val 2.30012
  Classification -> best τ=0.630 (val F1=0.3959)
  Directional -> Accuracy: 0.7083, MCC: 0.4021, F1: 0.6111

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48646 | val 1.50761
  Epoch 011 - train 0.49085 | val 2.97788
  Classification -> best τ=0.645 (val F1=0.1352)
  Directional -> Accuracy: 0.4638, MCC: -0.0758, F1: 0.4127

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50465 | val 0.83942
  Epoch 012 - train 0.52674 | val 0.81800
  Classification -> best τ=0.405 (val F1=0.3005)
  Directional -> Accuracy: 0.5102, MCC: 0.1340, F1: 0.6250

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45788 | val 1.66551
  Epoch 011 - train 0.46833 | val 2.32636
  Classification -> best τ=0.390 (val F1=0.2236)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49555 | val 0.87329
  Epoch 019 - train 0.29711 | val 0.97301
  Classification -> best τ=0.545 (val F1=0.2427)
  Directional -> Accuracy: 0.4762, MCC: -0.1062, F1: 0.2667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65627 | val 0.70821
  Epoch 012 - train 0.58170 | val 0.68716
  Classification -> best τ=0.205 (val F1=0.1961)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6591

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48545 | val 2.18989
  Epoch 013 - train 0.41000 | val 2.98053
  Classification -> best τ=0.470 (val F1=0.1960)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62536 | val 0.84930
  Epoch 014 - train 0.48210 | val 0.97448
  Classification -> best τ=0.435 (val F1=0.3094)
  Directional -> Accuracy: 0.5072, MCC: -0.0807, F1: 0.6600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53143 | val 1.68119
  Epoch 011 - train 0.53211 | val 1.68805
  Classification -> best τ=0.515 (val F1=0.0046)
  Directional -> Accuracy: 0.4310, MCC: -0.2428, F1: 0.5600

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50404 | val 0.84459
  Epoch 011 - train 0.49570 | val 0.91136
  Classification -> best τ=0.445 (val F1=0.1348)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61412 | val 0.85764
  Epoch 013 - train 0.52327 | val 1.76022
  Classification -> best τ=0.295 (val F1=0.2166)
  Directional -> Accuracy: 0.5312, MCC: 0.0294, F1: 0.6053

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48600 | val 1.23869
  Epoch 011 - train 0.46290 | val 1.21918
  Classification -> best τ=0.585 (val F1=0.3271)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51743 | val 1.62963
  Epoch 011 - train 0.42116 | val 1.70306
  Classification -> best τ=0.490 (val F1=0.2784)
  Directional -> Accuracy: 0.4681, MCC: 0.2403, F1: 0.2424

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61659 | val 1.87534
  Epoch 015 - train 0.49909 | val 2.29139
  Classification -> best τ=0.195 (val F1=0.1650)
  Directional -> Accuracy: 0.4769, MCC: -0.0464, F1: 0.4848

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64580 | val 0.70242
  Epoch 020 - train 0.46454 | val 0.91013
  Epoch 022 - train 0.39055 | val 1.06930
  Classification -> best τ=0.540 (val F1=0.4532)
  Directional -> Accuracy: 0.5263, MCC: 0.1000, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60127 | val 2.43251
  Epoch 013 - train 0.56979 | val 3.60456
  Classification -> best τ=0.650 (val F1=0.0293)
  Directional -> Accuracy: 0.4769, MCC: -0.1601, F1: 0.0556

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53053 | val 1.63052
  Epoch 011 - train 0.45470 | val 1.84847
  Classification -> best τ=0.700 (val F1=0.4499)
  Directional -> Accuracy: 0.5273, MCC: 0.1023, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42108 | val 3.58081
  Epoch 012 - train 0.36067 | val 4.20652
  Classification -> best τ=0.530 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72443 | val 0.98531
  Epoch 015 - train 0.51581 | val 0.76507
  Classification -> best τ=0.425 (val F1=0.1803)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47393 | val 3.11289
  Epoch 011 - train 0.47131 | val 3.02542
  Classification -> best τ=0.275 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53938 | val 2.19280
  Epoch 013 - train 0.38219 | val 3.45697
  Classification -> best τ=0.535 (val F1=0.1511)
  Directional -> Accuracy: 0.6500, MCC: 0.3015, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55389 | val 1.26375
  Epoch 014 - train 0.30175 | val 1.43133
  Classification -> best τ=0.620 (val F1=0.3501)
  Directional -> Accuracy: 0.4048, MCC: -0.1907, F1: 0.3902

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42021 | val 2.18160
  Epoch 011 - train 0.40107 | val 1.97659
  Classification -> best τ=0.380 (val F1=0.0875)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51782 | val 1.34719
  Epoch 011 - train 0.59519 | val 1.26989
  Classification -> best τ=0.490 (val F1=0.4158)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61611 | val 0.71414
  Epoch 011 - train 0.54933 | val 0.73655
  Classification -> best τ=0.440 (val F1=0.2431)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.46149 | val 4.01859
  Epoch 011 - train 0.43014 | val 4.74376
  Classification -> best τ=0.465 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53977 | val 1.36591
  Epoch 011 - train 0.46232 | val 1.53373
  Classification -> best τ=0.215 (val F1=0.4292)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40951 | val 2.02732
  Epoch 011 - train 0.34916 | val 2.45793
  Classification -> best τ=0.425 (val F1=0.1970)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55310 | val 0.77610
  Epoch 011 - train 0.47551 | val 0.81877
  Classification -> best τ=0.175 (val F1=0.2892)
  Directional -> Accuracy: 0.5357, MCC: 0.2067, F1: 0.6579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41410 | val 1.67978
  Epoch 011 - train 0.45162 | val 2.06247
  Classification -> best τ=0.455 (val F1=0.3105)
  Directional -> Accuracy: 0.6304, MCC: 0.1490, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55498 | val 1.30021
  Epoch 014 - train 0.36581 | val 1.66220
  Classification -> best τ=0.285 (val F1=0.5489)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50053 | val 1.84825
  Epoch 011 - train 0.47912 | val 2.08181
  Classification -> best τ=0.790 (val F1=0.2815)
  Directional -> Accuracy: 0.5270, MCC: 0.1027, F1: 0.6465

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59864 | val 2.71061
  Epoch 013 - train 0.47043 | val 1.68308
  Classification -> best τ=0.700 (val F1=0.1890)
  Directional -> Accuracy: 0.6000, MCC: 0.1996, F1: 0.6400

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53610 | val 1.24796
  Epoch 012 - train 0.50144 | val 1.33291
  Classification -> best τ=0.455 (val F1=0.5000)
  Directional -> Accuracy: 0.4524, MCC: -0.1876, F1: 0.5818

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52597 | val 1.38896
  Epoch 011 - train 0.50765 | val 1.25712
  Classification -> best τ=0.440 (val F1=0.3410)
  Directional -> Accuracy: 0.4167, MCC: -0.0265, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.51194 | val 1.17790
  Epoch 011 - train 0.51614 | val 1.00542
  Classification -> best τ=0.550 (val F1=0.0369)
  Directional -> Accuracy: 0.4000, MCC: -0.3054, F1: 0.5479

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40823 | val 3.34104
  Epoch 011 - train 0.36902 | val 3.42570
  Classification -> best τ=0.150 (val F1=0.3526)
  Directional -> Accuracy: 0.5357, MCC: 0.1073, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69352 | val 0.79680
  Epoch 019 - train 0.39634 | val 1.92481
  Classification -> best τ=0.725 (val F1=0.2155)
  Directional -> Accuracy: 0.5849, MCC: 0.1729, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49455 | val 4.85000
  Epoch 011 - train 0.47510 | val 2.96757
  Classification -> best τ=0.480 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60846 | val 1.03644

[I 2026-02-20 03:09:54,742] Trial 105 finished with value: 0.2625601773079318 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.008481374183058069, 'weight_decay': 1.15036885280788e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.109561764157249, 'early_stopping_min_delta': 0.00998403317336728}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.50287 | val 1.06081
  Classification -> best τ=0.520 (val F1=0.2507)
  Directional -> Accuracy: 0.5667, MCC: 0.1390, F1: 0.3810

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2625601773079318
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64021 | val 0.69073
  Epoch 017 - train 0.49318 | val 0.68080
  Classification -> best τ=0.425 (val F1=0.1635)
  Directional -> Accuracy: 0.5921, MCC: 0.2009, F1: 0.5974

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61377 | val 0.74118
  Epoch 017 - train 0.35348 | val 0.70509
  Classification -> best τ=0.485 (val F1=0.1764)
  Directional -> Accuracy: 0.6667, MCC: 0.3664, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64853 | val 0.82406
  Epoch 016 - train 0.41742 | val 1.42392
  Classification -> best τ=0.580 (val F1=0.2818)
  Directional -> Accuracy: 0.5435, MCC: 0.0807, F1: 0.5882

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56837 | val 3.83515
  Epoch 011 - train 0.52058 | val 3.66212
  Classification -> best τ=0.140 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54857 | val 1.50251
  Epoch 014 - train 0.41511 | val 3.73630
  Classification -> best τ=0.565 (val F1=0.4851)
  Directional -> Accuracy: 0.3400, MCC: -0.3669, F1: 0.4590

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54695 | val 0.85435
  Epoch 017 - train 0.26460 | val 0.81481
  Classification -> best τ=0.690 (val F1=0.2585)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53643 | val 1.32453
  Epoch 011 - train 0.56942 | val 1.22930
  Classification -> best τ=0.705 (val F1=0.3287)
  Directional -> Accuracy: 0.5588, MCC: 0.1671, F1: 0.5588

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54318 | val 0.65872
  Epoch 015 - train 0.24610 | val 0.90454
  Classification -> best τ=0.340 (val F1=0.1795)
  Directional -> Accuracy: 0.5952, MCC: 0.2676, F1: 0.6383

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48266 | val 2.17638
  Epoch 011 - train 0.39761 | val 1.98053
  Classification -> best τ=0.415 (val F1=0.2925)
  Directional -> Accuracy: 0.6042, MCC: 0.1782, F1: 0.4865

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59077 | val 0.88157
  Epoch 012 - train 0.51213 | val 0.79240
  Classification -> best τ=0.425 (val F1=0.2238)
  Directional -> Accuracy: 0.5072, MCC: 0.1376, F1: 0.5952

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60106 | val 0.73242
  Epoch 011 - train 0.53955 | val 0.75555
  Classification -> best τ=0.420 (val F1=0.3729)
  Directional -> Accuracy: 0.6327, MCC: 0.2673, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49253 | val 1.38470
  Epoch 011 - train 0.44019 | val 1.69975
  Classification -> best τ=0.600 (val F1=0.3426)
  Directional -> Accuracy: 0.5263, MCC: 0.0671, F1: 0.4000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53179 | val 0.74801
  Epoch 014 - train 0.39479 | val 0.85982
  Classification -> best τ=0.630 (val F1=0.2205)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62039 | val 0.89073
  Epoch 011 - train 0.58905 | val 0.63250
  Classification -> best τ=0.340 (val F1=0.3387)
  Directional -> Accuracy: 0.5833, MCC: 0.1925, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48356 | val 5.69287
  Epoch 011 - train 0.51057 | val 6.72803
  Classification -> best τ=0.580 (val F1=0.3961)
  Directional -> Accuracy: 0.4314, MCC: -0.1028, F1: 0.5246

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56394 | val 0.84784
  Epoch 012 - train 0.52331 | val 0.97681
  Classification -> best τ=0.365 (val F1=0.3067)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58346 | val 2.74667
  Epoch 013 - train 0.49977 | val 3.36869
  Classification -> best τ=0.405 (val F1=0.1905)
  Directional -> Accuracy: 0.6034, MCC: -0.0221, F1: 0.7473

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56978 | val 1.81437
  Epoch 016 - train 0.41490 | val 1.38085
  Classification -> best τ=0.510 (val F1=0.1809)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62204 | val 1.30936
  Epoch 012 - train 0.61277 | val 2.28806
  Classification -> best τ=0.190 (val F1=0.3893)
  Directional -> Accuracy: 0.5156, MCC: 0.1672, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48464 | val 2.13506
  Epoch 011 - train 0.48752 | val 1.68641
  Classification -> best τ=0.800 (val F1=0.2651)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67895 | val 0.78580
  Epoch 016 - train 0.50281 | val 1.45584
  Classification -> best τ=0.530 (val F1=0.2559)
  Directional -> Accuracy: 0.5106, MCC: -0.1254, F1: 0.6462

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55892 | val 1.75751
  Epoch 011 - train 0.51685 | val 2.55146
  Classification -> best τ=0.165 (val F1=0.2371)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61908 | val 1.15694
  Epoch 015 - train 0.44207 | val 1.62424
  Classification -> best τ=0.670 (val F1=0.4532)
  Directional -> Accuracy: 0.4912, MCC: 0.0919, F1: 0.2927

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54231 | val 5.45353
  Epoch 011 - train 0.56875 | val 1.01468
  Classification -> best τ=0.495 (val F1=0.1122)
  Directional -> Accuracy: 0.4462, MCC: -0.1866, F1: 0.6170

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54640 | val 0.95567
  Epoch 013 - train 0.39963 | val 1.83194
  Classification -> best τ=0.665 (val F1=0.4260)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45259 | val 0.88481
  Epoch 011 - train 0.60081 | val 1.96544
  Classification -> best τ=0.765 (val F1=0.2935)
  Directional -> Accuracy: 0.4889, MCC: 0.1591, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46357 | val 1.39980
  Epoch 012 - train 0.49434 | val 1.42128
  Classification -> best τ=0.720 (val F1=0.1353)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.0741

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61261 | val 0.98322
  Epoch 011 - train 0.52097 | val 1.03700
  Classification -> best τ=0.260 (val F1=0.1949)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49821 | val 1.95160
  Epoch 011 - train 0.42965 | val 2.38107
  Classification -> best τ=0.585 (val F1=0.3518)
  Directional -> Accuracy: 0.5250, MCC: -0.0060, F1: 0.6415

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49814 | val 2.10499
  Epoch 013 - train 0.43291 | val 2.49050
  Classification -> best τ=0.750 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54159 | val 1.07613
  Epoch 014 - train 0.36595 | val 3.19295
  Classification -> best τ=0.465 (val F1=0.2575)
  Directional -> Accuracy: 0.5000, MCC: -0.0588, F1: 0.6182

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60670 | val 1.03654
  Epoch 011 - train 0.60236 | val 1.13098
  Classification -> best τ=0.405 (val F1=0.2509)
  Directional -> Accuracy: 0.5510, MCC: 0.1535, F1: 0.7027

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53272 | val 2.01003
  Epoch 012 - train 0.48738 | val 3.24653
  Classification -> best τ=0.555 (val F1=0.3380)
  Directional -> Accuracy: 0.5972, MCC: 0.2216, F1: 0.5797

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44343 | val 2.73135
  Epoch 011 - train 0.39960 | val 2.97434
  Classification -> best τ=0.470 (val F1=0.0473)
  Directional -> Accuracy: 0.5814, MCC: 0.2592, F1: 0.6897

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52554 | val 0.84585
  Epoch 011 - train 0.49579 | val 0.94475
  Classification -> best τ=0.295 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38132 | val 3.22648
  Epoch 013 - train 0.30980 | val 4.85546
  Classification -> best τ=0.385 (val F1=0.2858)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52365 | val 2.23405
  Epoch 013 - train 0.40963 | val 2.73182
  Classification -> best τ=0.270 (val F1=0.2256)
  Directional -> Accuracy: 0.4286, MCC: -0.1344, F1: 0.4483

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62237 | val 1.17885
  Epoch 013 - train 0.46091 | val 0.98694
  Classification -> best τ=0.285 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42186 | val 0.84239
  Epoch 011 - train 0.44563 | val 0.84881
  Classification -> best τ=0.600 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57316 | val 0.61759
  Epoch 020 - train 0.28880 | val 1.11502
  Classification -> best τ=0.685 (val F1=0.3937)
  Directional -> Accuracy: 0.4730, MCC: -0.0486, F1: 0.5301

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50568 | val 3.77490
  Epoch 012 - train 0.40592 | val 3.37099
  Classification -> best τ=0.570 (val F1=0.3500)
  Directional -> Accuracy: 0.4667, MCC: -0.0667, F1: 0.2500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50015 | val 1.94163
  Epoch 011 - train 0.46407 | val 1.95763
  Classification -> best τ=0.380 (val F1=0.5601)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60303 | val 1.17178
  Epoch 011 - train 0.53905 | val 1.16898
  Classification -> best τ=0.535 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63933 | val 3.86819
  Epoch 014 - train 0.50398 | val 8.06147
  Classification -> best τ=0.285 (val F1=0.3092)
  Directional -> Accuracy: 0.3636, MCC: -0.2667, F1: 0.3636

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49062 | val 2.58690
  Epoch 011 - train 0.48606 | val 3.18319
  Classification -> best τ=0.600 (val F1=0.3570)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65591 | val 0.73678
  Epoch 012 - train 0.51104 | val 0.80625
  Classification -> best τ=0.705 (val F1=0.2743)
  Directional -> Accuracy: 0.5283, MCC: 0.0588, F1: 0.6479

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54392 | val 1.98120
  Epoch 012 - train 0.54149 | val 1.48762
  Classification -> best τ=0.625 (val F1=0.1763)
  Directional -> Accuracy: 0.4909, MCC: -0.0254, F1: 0.5333

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51513 | val 0.95871
  Epoch 011 - train 0.54505 | val 1.08571

[I 2026-02-20 03:11:29,248] Trial 106 finished with value: 0.28126371654733057 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009891899135932051, 'weight_decay': 1.0407310048603105e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.7315797039512424, 'early_stopping_min_delta': 0.008153750289248739}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.555 (val F1=0.1570)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28126371654733057
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57801 | val 1.36222
  Epoch 012 - train 0.57642 | val 1.83577
  Classification -> best τ=0.810 (val F1=0.2453)
  Directional -> Accuracy: 0.5195, MCC: -0.0708, F1: 0.0976

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57934 | val 1.19670
  Epoch 015 - train 0.38499 | val 2.98230
  Classification -> best τ=0.240 (val F1=0.2573)
  Directional -> Accuracy: 0.6087, MCC: 0.1962, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51752 | val 0.92186
  Epoch 018 - train 0.38247 | val 0.77496
  Classification -> best τ=0.730 (val F1=0.4419)
  Directional -> Accuracy: 0.5532, MCC: 0.2861, F1: 0.2759

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58528 | val 1.03300
  Epoch 011 - train 0.54406 | val 1.22621
  Classification -> best τ=0.505 (val F1=0.1346)
  Directional -> Accuracy: 0.5200, MCC: 0.1714, F1: 0.2800

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49854 | val 5.67247
  Epoch 017 - train 0.54736 | val 5.38909
  Classification -> best τ=0.590 (val F1=0.4020)
  Directional -> Accuracy: 0.3922, MCC: -0.2301, F1: 0.4561

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35630 | val 1.60787
  Epoch 011 - train 0.32696 | val 1.73367
  Classification -> best τ=0.380 (val F1=0.1644)
  Directional -> Accuracy: 0.4681, MCC: -0.0926, F1: 0.6269

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63226 | val 0.92875
  Epoch 011 - train 0.64177 | val 0.81854
  Classification -> best τ=0.430 (val F1=0.2130)
  Directional -> Accuracy: 0.5217, MCC: 0.0360, F1: 0.4590

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34564 | val 8.66000
  Epoch 011 - train 0.29978 | val 9.02359
  Classification -> best τ=0.630 (val F1=0.1214)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51794 | val 1.22635
  Epoch 012 - train 0.48610 | val 1.66239
  Classification -> best τ=0.490 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50442 | val 0.88524
  Epoch 012 - train 0.46088 | val 1.29425
  Classification -> best τ=0.405 (val F1=0.3212)
  Directional -> Accuracy: 0.5286, MCC: 0.1909, F1: 0.6207

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58327 | val 2.48566
  Epoch 012 - train 0.41571 | val 1.35351
  Classification -> best τ=0.130 (val F1=0.1336)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49986 | val 3.24177
  Epoch 011 - train 0.45971 | val 4.07629
  Classification -> best τ=0.610 (val F1=0.3196)
  Directional -> Accuracy: 0.6207, MCC: 0.2894, F1: 0.7027

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54594 | val 1.92432
  Epoch 011 - train 0.46834 | val 1.84460
  Classification -> best τ=0.510 (val F1=0.2501)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60285 | val 0.82222
  Epoch 015 - train 0.53880 | val 1.05050
  Classification -> best τ=0.420 (val F1=0.3192)
  Directional -> Accuracy: 0.5410, MCC: 0.0809, F1: 0.5625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57796 | val 0.68799
  Epoch 020 - train 0.46770 | val 0.72428
  Epoch 025 - train 0.28459 | val 0.64431
  Classification -> best τ=0.440 (val F1=0.4670)
  Directional -> Accuracy: 0.4231, MCC: -0.1355, F1: 0.5455

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48187 | val 2.01078
  Epoch 011 - train 0.47155 | val 1.53841
  Classification -> best τ=0.575 (val F1=0.2030)
  Directional -> Accuracy: 0.5143, MCC: 0.0898, F1: 0.3704

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56473 | val 1.08531
  Epoch 013 - train 0.51354 | val 1.22840
  Classification -> best τ=0.095 (val F1=0.3015)
  Directional -> Accuracy: 0.4915, MCC: -0.2155, F1: 0.6429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64798 | val 0.71883
  Epoch 015 - train 0.50620 | val 1.14483
  Classification -> best τ=0.635 (val F1=0.1988)
  Directional -> Accuracy: 0.4079, MCC: 0.0933, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60356 | val 0.71400
  Epoch 012 - train 0.50922 | val 1.04065
  Classification -> best τ=0.630 (val F1=0.3260)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58439 | val 0.74887
  Epoch 016 - train 0.44516 | val 1.02629
  Classification -> best τ=0.600 (val F1=0.2988)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42900 | val 2.44976
  Epoch 011 - train 0.42428 | val 2.77973
  Classification -> best τ=0.600 (val F1=0.2708)
  Directional -> Accuracy: 0.5208, MCC: 0.0759, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51792 | val 3.49049
  Epoch 011 - train 0.48375 | val 4.66436
  Classification -> best τ=0.765 (val F1=0.2304)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56910 | val 3.51934
  Epoch 011 - train 0.53450 | val 4.29067
  Classification -> best τ=0.440 (val F1=0.1371)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57593 | val 1.49302
  Epoch 011 - train 0.51607 | val 2.23890
  Classification -> best τ=0.565 (val F1=0.1878)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51037 | val 1.57335
  Epoch 012 - train 0.44049 | val 1.58194
  Classification -> best τ=0.525 (val F1=0.2700)
  Directional -> Accuracy: 0.4464, MCC: -0.0207, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47005 | val 1.03842
  Epoch 011 - train 0.48729 | val 1.22932
  Classification -> best τ=0.535 (val F1=0.1925)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72825 | val 0.83285
  Epoch 020 - train 0.44245 | val 0.70925
  Epoch 021 - train 0.45688 | val 0.68539
  Classification -> best τ=0.685 (val F1=0.2324)
  Directional -> Accuracy: 0.4651, MCC: -0.0593, F1: 0.4889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61919 | val 0.89055
  Epoch 015 - train 0.46825 | val 1.25254
  Classification -> best τ=0.535 (val F1=0.2854)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66946 | val 0.70537
  Epoch 016 - train 0.46449 | val 1.26194
  Classification -> best τ=0.555 (val F1=0.3158)
  Directional -> Accuracy: 0.4634, MCC: -0.0417, F1: 0.3125

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46472 | val 7.20246
  Epoch 012 - train 0.41288 | val 8.31582
  Classification -> best τ=0.845 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44631 | val 3.18460
  Epoch 011 - train 0.43209 | val 3.20548
  Classification -> best τ=0.405 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53146 | val 2.00019
  Epoch 013 - train 0.34240 | val 2.63947
  Classification -> best τ=0.375 (val F1=0.2735)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49020 | val 0.98046
  Epoch 011 - train 0.46604 | val 0.93751
  Classification -> best τ=0.250 (val F1=0.2877)
  Directional -> Accuracy: 0.5890, MCC: 0.2303, F1: 0.5455

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54188 | val 1.37806
  Epoch 011 - train 0.51557 | val 1.44943
  Classification -> best τ=0.575 (val F1=0.2182)
  Directional -> Accuracy: 0.4737, MCC: -0.0526, F1: 0.4737

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50282 | val 2.41238
  Epoch 011 - train 0.44043 | val 2.62491
  Classification -> best τ=0.820 (val F1=0.1749)
  Directional -> Accuracy: 0.5000, MCC: -0.0263, F1: 0.3125

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61232 | val 1.12896
  Epoch 015 - train 0.44150 | val 1.45953
  Classification -> best τ=0.165 (val F1=0.3767)
  Directional -> Accuracy: 0.5522, MCC: 0.0880, F1: 0.6053

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48869 | val 1.89566
  Epoch 011 - train 0.44001 | val 2.38367
  Classification -> best τ=0.680 (val F1=0.2652)
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51485 | val 2.78145
  Epoch 013 - train 0.45136 | val 5.73177
  Classification -> best τ=0.170 (val F1=0.2644)
  Directional -> Accuracy: 0.5263, MCC: 0.1409, F1: 0.6494

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53409 | val 0.81838
  Epoch 012 - train 0.41735 | val 0.93311
  Classification -> best τ=0.210 (val F1=0.3026)
  Directional -> Accuracy: 0.5745, MCC: 0.0996, F1: 0.6552

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47944 | val 1.13396
  Epoch 013 - train 0.35762 | val 1.03104
  Classification -> best τ=0.220 (val F1=0.3993)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44775 | val 2.97068
  Epoch 011 - train 0.38683 | val 3.37273
  Classification -> best τ=0.630 (val F1=0.2227)
  Directional -> Accuracy: 0.4737, MCC: -0.0181, F1: 0.1667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57178 | val 2.96171
  Epoch 012 - train 0.47000 | val 3.65288
  Classification -> best τ=0.715 (val F1=0.2983)
  Directional -> Accuracy: 0.5467, MCC: 0.1927, F1: 0.6792

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51511 | val 1.55753
  Epoch 014 - train 0.35178 | val 1.39378
  Classification -> best τ=0.580 (val F1=0.2470)
  Directional -> Accuracy: 0.4468, MCC: -0.2154, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49983 | val 1.81902
  Epoch 011 - train 0.42835 | val 2.01079
  Classification -> best τ=0.685 (val F1=0.5294)
  Directional -> Accuracy: 0.5000, MCC: -0.0617, F1: 0.6071

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46652 | val 1.78839
  Epoch 011 - train 0.39992 | val 1.82266
  Classification -> best τ=0.380 (val F1=0.6325)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.52661 | val 1.57989
  Epoch 012 - train 0.49481 | val 2.35151
  Classification -> best τ=0.475 (val F1=0.2958)
  Directional -> Accuracy: 0.5357, MCC: 0.0138, F1: 0.6905

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49318 | val 3.25785
  Epoch 011 - train 0.42639 | val 2.96896
  Classification -> best τ=0.430 (val F1=0.2741)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57389 | val 1.08917
  Epoch 012 - train 0.52432 | val 1.33362
  Classification -> best τ=0.560 (val F1=0.2360)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55152 | val 2.52429
  Epoch 011 - train 0.49454 | val 2.56704
  Classification -> best τ=0.375 (val F1=0.2539)
  Directional -> Accuracy: 0.5357, MCC: 0.0643, F1: 0.6579

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62270 | val 0.71244

[I 2026-02-20 03:12:49,377] Trial 107 finished with value: 0.27785851294379627 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009866980281106384, 'weight_decay': 1.0514107962728877e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5344200965763263, 'early_stopping_min_delta': 0.008109707446214682}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.51771 | val 0.90653
  Classification -> best τ=0.425 (val F1=0.3103)
  Directional -> Accuracy: 0.4918, MCC: -0.0140, F1: 0.4918

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27785851294379627
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64420 | val 1.50302
  Epoch 014 - train 0.53538 | val 2.16955
  Classification -> best τ=0.500 (val F1=0.1946)
  Directional -> Accuracy: 0.5584, MCC: 0.1186, F1: 0.5405

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52464 | val 1.16517
  Epoch 015 - train 0.44522 | val 1.61745
  Classification -> best τ=0.480 (val F1=0.4075)
  Directional -> Accuracy: 0.6739, MCC: 0.3330, F1: 0.7170

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55584 | val 3.51487
  Epoch 014 - train 0.46653 | val 1.94356
  Classification -> best τ=0.715 (val F1=0.4665)
  Directional -> Accuracy: 0.5532, MCC: 0.2311, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67398 | val 1.37888
  Epoch 013 - train 0.60630 | val 1.53192
  Classification -> best τ=0.380 (val F1=0.1723)
  Directional -> Accuracy: 0.5333, MCC: 0.0333, F1: 0.6237

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56778 | val 1.96549
  Epoch 012 - train 0.46973 | val 2.29050
  Classification -> best τ=0.615 (val F1=0.3724)
  Directional -> Accuracy: 0.5882, MCC: 0.2141, F1: 0.5116

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46155 | val 1.15826
  Epoch 013 - train 0.35273 | val 1.30198
  Classification -> best τ=0.470 (val F1=0.1741)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63349 | val 1.79754
  Epoch 013 - train 0.58472 | val 2.57311
  Classification -> best τ=0.625 (val F1=0.1524)
  Directional -> Accuracy: 0.5507, MCC: 0.0192, F1: 0.3404

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52133 | val 3.34076
  Epoch 012 - train 0.42793 | val 3.04733
  Classification -> best τ=0.220 (val F1=0.1752)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51786 | val 2.68271
  Epoch 011 - train 0.48911 | val 3.00384
  Classification -> best τ=0.570 (val F1=0.3331)
  Directional -> Accuracy: 0.5306, MCC: -0.0168, F1: 0.2069

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62502 | val 1.35819
  Epoch 012 - train 0.55723 | val 1.59576
  Classification -> best τ=0.595 (val F1=0.1719)
  Directional -> Accuracy: 0.5571, MCC: 0.0000, F1: 0.1622

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52599 | val 2.55607
  Epoch 011 - train 0.50625 | val 3.59647
  Classification -> best τ=0.565 (val F1=0.3765)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48163 | val 2.76505
  Epoch 011 - train 0.47744 | val 3.37553
  Classification -> best τ=0.065 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53362 | val 0.96502
  Epoch 013 - train 0.48454 | val 1.13291
  Classification -> best τ=0.365 (val F1=0.3808)
  Directional -> Accuracy: 0.5814, MCC: 0.2185, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59166 | val 1.09197
  Epoch 014 - train 0.56642 | val 0.75858
  Classification -> best τ=0.250 (val F1=0.3383)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60663 | val 0.79962
  Epoch 012 - train 0.58538 | val 0.84011
  Classification -> best τ=0.495 (val F1=0.2822)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62542 | val 2.19783
  Epoch 014 - train 0.49005 | val 1.40204
  Classification -> best τ=0.440 (val F1=0.2030)
  Directional -> Accuracy: 0.5857, MCC: 0.1721, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56742 | val 5.80404
  Epoch 011 - train 0.54568 | val 2.11339
  Classification -> best τ=0.630 (val F1=0.1302)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61840 | val 0.82640
  Epoch 011 - train 0.60623 | val 0.72007
  Classification -> best τ=0.470 (val F1=0.1242)
  Directional -> Accuracy: 0.5789, MCC: -0.1328, F1: 0.7333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58637 | val 0.82218
  Epoch 014 - train 0.49038 | val 1.53452
  Classification -> best τ=0.375 (val F1=0.2712)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58914 | val 0.90397
  Epoch 011 - train 0.57024 | val 0.79699
  Classification -> best τ=0.645 (val F1=0.2731)
  Directional -> Accuracy: 0.4933, MCC: 0.1859, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56346 | val 2.82209
  Epoch 014 - train 0.45335 | val 3.91680
  Classification -> best τ=0.160 (val F1=0.3143)
  Directional -> Accuracy: 0.5625, MCC: -0.1233, F1: 0.7123

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57764 | val 1.21628
  Epoch 011 - train 0.57063 | val 1.62293
  Classification -> best τ=0.495 (val F1=0.1664)
  Directional -> Accuracy: 0.5152, MCC: 0.0442, F1: 0.6444

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61749 | val 1.87300
  Epoch 011 - train 0.57382 | val 2.30964
  Classification -> best τ=0.675 (val F1=0.2583)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59651 | val 1.51859
  Epoch 011 - train 0.57723 | val 2.01497
  Classification -> best τ=0.360 (val F1=0.1318)
  Directional -> Accuracy: 0.5606, MCC: 0.1135, F1: 0.5085

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51491 | val 0.81779
  Epoch 011 - train 0.50142 | val 0.71890
  Classification -> best τ=0.570 (val F1=0.3951)
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57576 | val 2.70798
  Epoch 011 - train 0.50760 | val 3.38063
  Classification -> best τ=0.530 (val F1=0.3581)
  Directional -> Accuracy: 0.6087, MCC: 0.1757, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63320 | val 2.65117
  Epoch 016 - train 0.56506 | val 0.68793
  Classification -> best τ=0.525 (val F1=0.1480)
  Directional -> Accuracy: 0.5814, MCC: 0.2040, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59051 | val 1.33461
  Epoch 012 - train 0.49594 | val 1.60020
  Classification -> best τ=0.310 (val F1=0.2781)
  Directional -> Accuracy: 0.5614, MCC: 0.0981, F1: 0.6269

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64367 | val 0.72463
  Epoch 020 - train 0.49893 | val 0.92478
  Epoch 021 - train 0.51276 | val 1.15941
  Classification -> best τ=0.490 (val F1=0.3707)
  Directional -> Accuracy: 0.5610, MCC: 0.1241, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50983 | val 4.76988
  Epoch 011 - train 0.48194 | val 5.83224
  Classification -> best τ=0.660 (val F1=0.1869)
  Directional -> Accuracy: 0.5116, MCC: 0.0074, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49754 | val 2.00481
  Epoch 011 - train 0.44352 | val 2.09579
  Classification -> best τ=0.465 (val F1=0.2533)
  Directional -> Accuracy: 0.5581, MCC: 0.1107, F1: 0.6984

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47772 | val 2.96850
  Epoch 011 - train 0.49591 | val 3.44555
  Classification -> best τ=0.490 (val F1=0.3339)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59281 | val 1.53943
  Epoch 012 - train 0.47982 | val 1.52669
  Classification -> best τ=0.515 (val F1=0.2343)
  Directional -> Accuracy: 0.5616, MCC: 0.2949, F1: 0.3846

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.58385 | val 1.38893
  Epoch 012 - train 0.47937 | val 1.50765
  Classification -> best τ=0.530 (val F1=0.4082)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5778

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53449 | val 1.60778
  Epoch 011 - train 0.49289 | val 1.90170
  Classification -> best τ=0.595 (val F1=0.2914)
  Directional -> Accuracy: 0.6364, MCC: 0.2818, F1: 0.6522

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55026 | val 1.45537
  Epoch 011 - train 0.54377 | val 1.26787
  Classification -> best τ=0.275 (val F1=0.3954)
  Directional -> Accuracy: 0.4925, MCC: 0.1359, F1: 0.2609

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51859 | val 1.16898
  Epoch 016 - train 0.41492 | val 1.94505
  Classification -> best τ=0.595 (val F1=0.2357)
  Directional -> Accuracy: 0.6512, MCC: 0.3596, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53933 | val 1.57418
  Epoch 014 - train 0.46284 | val 2.52136
  Classification -> best τ=0.255 (val F1=0.2453)
  Directional -> Accuracy: 0.5439, MCC: 0.1605, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59508 | val 1.15648
  Epoch 011 - train 0.52596 | val 2.31185
  Classification -> best τ=0.520 (val F1=0.1897)
  Directional -> Accuracy: 0.4681, MCC: -0.0301, F1: 0.4898

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49376 | val 0.95835
  Epoch 013 - train 0.38275 | val 1.22971
  Classification -> best τ=0.415 (val F1=0.3973)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51119 | val 3.25342
  Epoch 012 - train 0.41972 | val 3.01280
  Classification -> best τ=0.460 (val F1=0.0658)
  Directional -> Accuracy: 0.7368, MCC: 0.4893, F1: 0.7826

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58327 | val 1.40655
  Epoch 012 - train 0.53335 | val 1.88558
  Classification -> best τ=0.510 (val F1=0.3729)
  Directional -> Accuracy: 0.5867, MCC: 0.1845, F1: 0.6353

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57382 | val 0.70091
  Epoch 011 - train 0.50397 | val 0.78140
  Classification -> best τ=0.405 (val F1=0.3855)
  Directional -> Accuracy: 0.4468, MCC: -0.1229, F1: 0.1875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55846 | val 1.12736
  Epoch 012 - train 0.50921 | val 2.30097
  Classification -> best τ=0.430 (val F1=0.4416)
  Directional -> Accuracy: 0.5909, MCC: 0.1283, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48583 | val 5.00219
  Epoch 012 - train 0.47590 | val 4.61456
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65632 | val 1.94064
  Epoch 014 - train 0.52680 | val 3.18105
  Classification -> best τ=0.645 (val F1=0.1236)
  Directional -> Accuracy: 0.4464, MCC: -0.1003, F1: 0.4364

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.77689 | val 1.01911
  Epoch 017 - train 0.42098 | val 2.10464
  Classification -> best τ=0.840 (val F1=0.3156)
  Directional -> Accuracy: 0.4211, MCC: -0.2017, F1: 0.2326

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58179 | val 1.00038
  Epoch 012 - train 0.53529 | val 1.24402
  Classification -> best τ=0.550 (val F1=0.2495)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54126 | val 1.74895
  Epoch 011 - train 0.51025 | val 1.92138
  Classification -> best τ=0.770 (val F1=0.2557)
  Directional -> Accuracy: 0.3929, MCC: -0.2114, F1: 0.3462

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65807 | val 0.88570

[I 2026-02-20 03:14:09,275] Trial 108 finished with value: 0.2631074871733627 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0099047074502352, 'weight_decay': 1.292617552575137e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.3371094898905006, 'early_stopping_min_delta': 0.0071815689387170496}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 017 - train 0.50833 | val 2.25827
  Classification -> best τ=0.400 (val F1=0.2066)
  Directional -> Accuracy: 0.5246, MCC: 0.0218, F1: 0.2564

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2631074871733627
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56273 | val 1.24602
  Epoch 011 - train 0.54368 | val 1.36409
  Classification -> best τ=0.450 (val F1=0.1341)
  Directional -> Accuracy: 0.4545, MCC: -0.0265, F1: 0.6038

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58831 | val 0.86648
  Epoch 016 - train 0.36355 | val 1.36055
  Classification -> best τ=0.505 (val F1=0.2573)
  Directional -> Accuracy: 0.6957, MCC: 0.4008, F1: 0.7083

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48390 | val 1.18528
  Epoch 011 - train 0.47061 | val 1.31588
  Classification -> best τ=0.315 (val F1=0.2845)
  Directional -> Accuracy: 0.4681, MCC: -0.2449, F1: 0.6377

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58143 | val 3.58877
  Epoch 011 - train 0.57181 | val 2.49811
  Classification -> best τ=0.625 (val F1=0.1723)
  Directional -> Accuracy: 0.5733, MCC: 0.1277, F1: 0.6364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49792 | val 1.28531
  Epoch 013 - train 0.39232 | val 2.66496
  Classification -> best τ=0.635 (val F1=0.3665)
  Directional -> Accuracy: 0.4706, MCC: -0.1124, F1: 0.5970

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35025 | val 2.26108
  Epoch 011 - train 0.39099 | val 2.04657
  Classification -> best τ=0.385 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52735 | val 1.08634
  Epoch 011 - train 0.48174 | val 1.06590
  Classification -> best τ=0.650 (val F1=0.1239)
  Directional -> Accuracy: 0.5942, MCC: 0.1585, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47616 | val 3.34130
  Epoch 012 - train 0.43906 | val 4.04898
  Classification -> best τ=0.510 (val F1=0.3236)
  Directional -> Accuracy: 0.6591, MCC: 0.2700, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47507 | val 3.47105
  Epoch 012 - train 0.41457 | val 4.07342
  Classification -> best τ=0.595 (val F1=0.3039)
  Directional -> Accuracy: 0.6531, MCC: 0.3350, F1: 0.4138

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51970 | val 1.07175
  Epoch 011 - train 0.46981 | val 1.13333
  Classification -> best τ=0.420 (val F1=0.3388)
  Directional -> Accuracy: 0.5143, MCC: 0.0589, F1: 0.5278

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51983 | val 2.26908
  Epoch 012 - train 0.44914 | val 3.39568
  Classification -> best τ=0.500 (val F1=0.1147)
  Directional -> Accuracy: 0.5200, MCC: -0.0642, F1: 0.0769

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48577 | val 5.34782
  Epoch 011 - train 0.47951 | val 6.06096
  Classification -> best τ=0.260 (val F1=0.1955)
  Directional -> Accuracy: 0.5862, MCC: 0.3071, F1: 0.7073

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50121 | val 2.46659
  Epoch 012 - train 0.40770 | val 2.46383
  Classification -> best τ=0.605 (val F1=0.2444)
  Directional -> Accuracy: 0.5581, MCC: 0.0644, F1: 0.3448

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57358 | val 0.72018
  Epoch 013 - train 0.49944 | val 0.69644
  Classification -> best τ=0.380 (val F1=0.2739)
  Directional -> Accuracy: 0.5738, MCC: 0.1489, F1: 0.6286

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53408 | val 0.80410
  Epoch 011 - train 0.53710 | val 0.86126
  Classification -> best τ=0.670 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50225 | val 1.05191
  Epoch 012 - train 0.48227 | val 3.47276
  Classification -> best τ=0.195 (val F1=0.2927)
  Directional -> Accuracy: 0.5857, MCC: 0.1909, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55628 | val 1.50434
  Epoch 012 - train 0.47307 | val 1.87555
  Classification -> best τ=0.245 (val F1=0.3015)
  Directional -> Accuracy: 0.5424, MCC: -0.1322, F1: 0.6897

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57436 | val 1.07863
  Epoch 011 - train 0.55106 | val 0.91635
  Classification -> best τ=0.780 (val F1=0.2236)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64795 | val 0.80624
  Epoch 016 - train 0.50075 | val 0.79337
  Classification -> best τ=0.660 (val F1=0.2249)
  Directional -> Accuracy: 0.4462, MCC: 0.0531, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51448 | val 1.00099
  Epoch 011 - train 0.49183 | val 1.60793
  Classification -> best τ=0.420 (val F1=0.2952)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58574 | val 1.38822
  Epoch 014 - train 0.37238 | val 1.18698
  Classification -> best τ=0.545 (val F1=0.2261)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61143 | val 2.05096
  Epoch 011 - train 0.57217 | val 1.36374
  Classification -> best τ=0.285 (val F1=0.0705)
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.6739

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57758 | val 0.90107
  Epoch 016 - train 0.48934 | val 1.57207
  Classification -> best τ=0.705 (val F1=0.3538)
  Directional -> Accuracy: 0.5862, MCC: 0.1741, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56030 | val 1.77994
  Epoch 011 - train 0.47052 | val 1.57899
  Classification -> best τ=0.485 (val F1=0.2125)
  Directional -> Accuracy: 0.5152, MCC: 0.0844, F1: 0.6190

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46139 | val 0.90374
  Epoch 012 - train 0.45627 | val 1.29738
  Classification -> best τ=0.545 (val F1=0.4297)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56472 | val 1.60446
  Epoch 011 - train 0.48284 | val 1.22619
  Classification -> best τ=0.305 (val F1=0.2774)
  Directional -> Accuracy: 0.6304, MCC: 0.3557, F1: 0.6792

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62903 | val 0.68295
  Epoch 011 - train 0.62182 | val 0.68537
  Classification -> best τ=0.605 (val F1=0.0866)
  Directional -> Accuracy: 0.5581, MCC: 0.1467, F1: 0.5581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51577 | val 1.45749
  Epoch 013 - train 0.47364 | val 1.55873
  Classification -> best τ=0.445 (val F1=0.2391)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54985 | val 1.23587
  Epoch 011 - train 0.50995 | val 1.28670
  Classification -> best τ=0.585 (val F1=0.3548)
  Directional -> Accuracy: 0.5122, MCC: 0.0416, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50159 | val 2.34649
  Epoch 011 - train 0.46856 | val 2.60462
  Classification -> best τ=0.455 (val F1=0.3296)
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49299 | val 0.72704
  Epoch 012 - train 0.51256 | val 0.74376
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49249 | val 1.24306
  Epoch 011 - train 0.46111 | val 1.58177
  Classification -> best τ=0.240 (val F1=0.3304)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55698 | val 1.35592
  Epoch 014 - train 0.42759 | val 1.44120
  Classification -> best τ=0.310 (val F1=0.2797)
  Directional -> Accuracy: 0.4521, MCC: -0.0485, F1: 0.3548

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52886 | val 1.58395
  Epoch 011 - train 0.60589 | val 2.52281
  Classification -> best τ=0.405 (val F1=0.0976)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65855 | val 0.97525
  Epoch 011 - train 0.64850 | val 1.06090
  Classification -> best τ=0.565 (val F1=0.3464)
  Directional -> Accuracy: 0.5000, MCC: 0.0554, F1: 0.6333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53281 | val 0.93547
  Epoch 012 - train 0.50977 | val 1.02567
  Classification -> best τ=0.370 (val F1=0.3515)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47990 | val 0.92042
  Epoch 011 - train 0.45367 | val 1.10328
  Classification -> best τ=0.510 (val F1=0.1482)
  Directional -> Accuracy: 0.4884, MCC: -0.0641, F1: 0.6333

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44188 | val 2.24235
  Epoch 012 - train 0.39911 | val 1.95652
  Classification -> best τ=0.215 (val F1=0.2453)
  Directional -> Accuracy: 0.4737, MCC: -0.0101, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47821 | val 1.18415
  Epoch 013 - train 0.37227 | val 1.13374
  Classification -> best τ=0.775 (val F1=0.1871)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55283 | val 0.74071
  Epoch 015 - train 0.39659 | val 0.72012
  Classification -> best τ=0.380 (val F1=0.2677)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48045 | val 2.26303
  Epoch 011 - train 0.44177 | val 2.41518
  Classification -> best τ=0.505 (val F1=0.2041)
  Directional -> Accuracy: 0.5000, MCC: -0.0574, F1: 0.6415

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53756 | val 1.91541
  Epoch 012 - train 0.48913 | val 2.20087
  Classification -> best τ=0.325 (val F1=0.2774)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53461 | val 0.77625
  Epoch 014 - train 0.38875 | val 1.23550
  Classification -> best τ=0.395 (val F1=0.4575)
  Directional -> Accuracy: 0.5106, MCC: 0.0081, F1: 0.6462

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50480 | val 1.23990
  Epoch 014 - train 0.39403 | val 1.74389
  Classification -> best τ=0.535 (val F1=0.3985)
  Directional -> Accuracy: 0.6136, MCC: 0.1884, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50254 | val 3.06224
  Epoch 011 - train 0.39638 | val 2.98865
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49962 | val 3.00492
  Epoch 012 - train 0.46988 | val 3.77265
  Classification -> best τ=0.560 (val F1=0.2231)
  Directional -> Accuracy: 0.5179, MCC: 0.2215, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48790 | val 1.57223
  Epoch 011 - train 0.46109 | val 1.60684
  Classification -> best τ=0.510 (val F1=0.2779)
  Directional -> Accuracy: 0.5088, MCC: 0.0590, F1: 0.6111

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59002 | val 1.20777
  Epoch 013 - train 0.48093 | val 1.08654
  Classification -> best τ=0.665 (val F1=0.2024)
  Directional -> Accuracy: 0.4259, MCC: -0.1436, F1: 0.3673

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56132 | val 1.75918
  Epoch 014 - train 0.34687 | val 2.48274
  Classification -> best τ=0.575 (val F1=0.2182)
  Directional -> Accuracy: 0.4107, MCC: -0.2435, F1: 0.0571

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61791 | val 0.79884

[I 2026-02-20 03:15:26,681] Trial 109 finished with value: 0.24808497265017604 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.006016725845659708, 'weight_decay': 1.9335486595867975e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.652292808112496, 'early_stopping_min_delta': 0.008939247765853503}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 018 - train 0.45337 | val 1.66506
  Classification -> best τ=0.350 (val F1=0.3349)
  Directional -> Accuracy: 0.5574, MCC: 0.1213, F1: 0.5714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24808497265017604
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66178 | val 1.08669
  Epoch 016 - train 0.47582 | val 0.75458
  Classification -> best τ=0.660 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0577, F1: 0.3860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53542 | val 1.03039
  Epoch 012 - train 0.41123 | val 1.38532
  Classification -> best τ=0.375 (val F1=0.1870)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56046 | val 0.93078
  Epoch 014 - train 0.46155 | val 0.94131
  Classification -> best τ=0.605 (val F1=0.3731)
  Directional -> Accuracy: 0.5532, MCC: 0.0961, F1: 0.6038

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63958 | val 1.83156
  Epoch 011 - train 0.61176 | val 2.51824
  Classification -> best τ=0.535 (val F1=0.2163)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45960 | val 2.89254
  Epoch 012 - train 0.40855 | val 3.25331
  Classification -> best τ=0.530 (val F1=0.4063)
  Directional -> Accuracy: 0.4118, MCC: -0.2141, F1: 0.5161

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39549 | val 3.80541
  Epoch 011 - train 0.36700 | val 3.32544
  Classification -> best τ=0.615 (val F1=0.3273)
  Directional -> Accuracy: 0.5106, MCC: 0.0081, F1: 0.2069

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61725 | val 0.81488
  Epoch 017 - train 0.46126 | val 1.50630
  Classification -> best τ=0.330 (val F1=0.3177)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48631 | val 6.07330
  Epoch 011 - train 0.45523 | val 6.47858
  Classification -> best τ=0.510 (val F1=0.3016)
  Directional -> Accuracy: 0.5682, MCC: 0.0842, F1: 0.4242

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48308 | val 1.15790
  Epoch 011 - train 0.46041 | val 1.65015
  Classification -> best τ=0.565 (val F1=0.3475)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57796 | val 0.77783
  Epoch 011 - train 0.56887 | val 0.80487
  Classification -> best τ=0.665 (val F1=0.1620)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51855 | val 4.35101
  Epoch 011 - train 0.47878 | val 4.73421
  Classification -> best τ=0.635 (val F1=0.2758)
  Directional -> Accuracy: 0.5000, MCC: 0.0602, F1: 0.6032

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51698 | val 3.92733
  Epoch 012 - train 0.45973 | val 4.94804
  Classification -> best τ=0.335 (val F1=0.2453)
  Directional -> Accuracy: 0.5862, MCC: 0.2381, F1: 0.3684

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56476 | val 2.35799
  Epoch 012 - train 0.49739 | val 2.73506
  Classification -> best τ=0.275 (val F1=0.2004)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61013 | val 0.71837
  Epoch 011 - train 0.54396 | val 0.71975
  Classification -> best τ=0.445 (val F1=0.3024)
  Directional -> Accuracy: 0.5410, MCC: 0.0825, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58494 | val 0.77118
  Epoch 011 - train 0.53157 | val 0.75542
  Classification -> best τ=0.490 (val F1=0.1706)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51725 | val 1.30757
  Epoch 011 - train 0.51101 | val 1.54155
  Classification -> best τ=0.430 (val F1=0.2516)
  Directional -> Accuracy: 0.6143, MCC: 0.2196, F1: 0.7097

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55138 | val 0.86061
  Epoch 019 - train 0.39407 | val 0.96473
  Classification -> best τ=0.355 (val F1=0.3015)
  Directional -> Accuracy: 0.3729, MCC: -0.3536, F1: 0.5067

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55718 | val 2.13825
  Epoch 011 - train 0.52634 | val 2.61050
  Classification -> best τ=0.680 (val F1=0.1923)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54101 | val 2.19674
  Epoch 012 - train 0.46312 | val 2.21351
  Classification -> best τ=0.385 (val F1=0.2193)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58462 | val 0.77001
  Epoch 017 - train 0.43913 | val 0.82577
  Classification -> best τ=0.240 (val F1=0.3018)
  Directional -> Accuracy: 0.4533, MCC: -0.0223, F1: 0.0889

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44288 | val 1.59156
  Epoch 011 - train 0.39820 | val 4.33745
  Classification -> best τ=0.570 (val F1=0.2174)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58459 | val 1.01306
  Epoch 011 - train 0.59048 | val 1.12050
  Classification -> best τ=0.410 (val F1=0.2054)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57709 | val 1.43693
  Epoch 011 - train 0.54166 | val 1.60515
  Classification -> best τ=0.555 (val F1=0.2006)
  Directional -> Accuracy: 0.5517, MCC: 0.0601, F1: 0.6389

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53865 | val 1.31196
  Epoch 011 - train 0.54084 | val 1.18822
  Classification -> best τ=0.330 (val F1=0.2039)
  Directional -> Accuracy: 0.5000, MCC: 0.0705, F1: 0.6292

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57171 | val 0.75693
  Epoch 015 - train 0.49812 | val 1.00086
  Classification -> best τ=0.215 (val F1=0.4082)
  Directional -> Accuracy: 0.5893, MCC: 0.1878, F1: 0.5965

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50459 | val 1.66998
  Epoch 011 - train 0.43072 | val 1.43655
  Classification -> best τ=0.485 (val F1=0.1741)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58029 | val 0.85346
  Epoch 011 - train 0.58882 | val 1.07597
  Classification -> best τ=0.505 (val F1=0.2643)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54232 | val 1.00226
  Epoch 011 - train 0.53777 | val 1.10201
  Classification -> best τ=0.480 (val F1=0.2866)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53354 | val 0.82809
  Epoch 013 - train 0.45278 | val 1.03077
  Classification -> best τ=0.570 (val F1=0.3548)
  Directional -> Accuracy: 0.6341, MCC: 0.2620, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45761 | val 1.95913
  Epoch 011 - train 0.41905 | val 2.44601
  Classification -> best τ=0.645 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53021 | val 1.19523
  Epoch 012 - train 0.46325 | val 1.28727
  Classification -> best τ=0.650 (val F1=0.2432)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52900 | val 1.26514
  Epoch 011 - train 0.49803 | val 1.36764
  Classification -> best τ=0.440 (val F1=0.2659)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50452 | val 1.19320
  Epoch 011 - train 0.47916 | val 1.25177
  Classification -> best τ=0.385 (val F1=0.3785)
  Directional -> Accuracy: 0.5068, MCC: 0.0735, F1: 0.4194

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.50755 | val 2.97922
  Epoch 011 - train 0.49351 | val 2.97820
  Classification -> best τ=0.345 (val F1=0.3974)
  Directional -> Accuracy: 0.5526, MCC: 0.1715, F1: 0.6792

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55048 | val 0.93973
  Epoch 011 - train 0.48810 | val 0.95374
  Classification -> best τ=0.505 (val F1=0.3121)
  Directional -> Accuracy: 0.5227, MCC: 0.1439, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52229 | val 0.72064
  Epoch 011 - train 0.55104 | val 0.87140
  Classification -> best τ=0.390 (val F1=0.4655)
  Directional -> Accuracy: 0.5075, MCC: 0.1674, F1: 0.2979

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48967 | val 1.01729
  Epoch 011 - train 0.48586 | val 1.01305
  Classification -> best τ=0.600 (val F1=0.2304)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44870 | val 1.58547
  Epoch 011 - train 0.42976 | val 1.35512
  Classification -> best τ=0.405 (val F1=0.3241)
  Directional -> Accuracy: 0.5614, MCC: 0.1491, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45098 | val 1.97741
  Epoch 011 - train 0.42757 | val 1.82427
  Classification -> best τ=0.750 (val F1=0.2303)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61928 | val 1.20392
  Epoch 012 - train 0.51320 | val 1.08109
  Classification -> best τ=0.475 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49318 | val 2.34187
  Epoch 011 - train 0.46857 | val 2.31000
  Classification -> best τ=0.475 (val F1=0.1284)
  Directional -> Accuracy: 0.5526, MCC: 0.1192, F1: 0.5143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62097 | val 0.88063
  Epoch 015 - train 0.48835 | val 1.24257
  Classification -> best τ=0.430 (val F1=0.3634)
  Directional -> Accuracy: 0.5200, MCC: 0.1633, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44173 | val 1.06811
  Epoch 011 - train 0.42460 | val 1.08051
  Classification -> best τ=0.510 (val F1=0.2593)
  Directional -> Accuracy: 0.4894, MCC: -0.0385, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48008 | val 2.27983
  Epoch 011 - train 0.41969 | val 2.12183
  Classification -> best τ=0.655 (val F1=0.2749)
  Directional -> Accuracy: 0.4545, MCC: 0.0230, F1: 0.2000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45382 | val 2.62343
  Epoch 011 - train 0.45327 | val 2.80007
  Classification -> best τ=0.470 (val F1=0.2626)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56706 | val 1.07662
  Epoch 011 - train 0.53041 | val 1.36927
  Classification -> best τ=0.440 (val F1=0.2985)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46683 | val 1.42723
  Epoch 011 - train 0.43358 | val 1.43912
  Classification -> best τ=0.665 (val F1=0.3666)
  Directional -> Accuracy: 0.5088, MCC: 0.1231, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60834 | val 0.69111
  Epoch 020 - train 0.44985 | val 1.08421
  Epoch 021 - train 0.45138 | val 0.94710
  Classification -> best τ=0.520 (val F1=0.3065)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52815 | val 0.80841
  Epoch 011 - train 0.51341 | val 0.86161
  Classification -> best τ=0.530 (val F1=0.0278)
  Directional -> Accuracy: 0.4107, MCC: -0.2435, F1: 0.0571

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61753 | val 0.90389

[I 2026-02-20 03:16:46,155] Trial 110 finished with value: 0.2751531788247013 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0034954508712275846, 'weight_decay': 7.915365073226505e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.39221382864820453, 'early_stopping_min_delta': 0.008515860849866833}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.52581 | val 1.00529
  Classification -> best τ=0.505 (val F1=0.2793)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2751531788247013
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54643 | val 1.67746
  Epoch 011 - train 0.55170 | val 1.40636
  Classification -> best τ=0.540 (val F1=0.2553)
  Directional -> Accuracy: 0.4156, MCC: -0.1547, F1: 0.4444

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49929 | val 1.66126
  Epoch 011 - train 0.51018 | val 1.72192
  Classification -> best τ=0.645 (val F1=0.1236)
  Directional -> Accuracy: 0.5217, MCC: -0.0083, F1: 0.6207

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61177 | val 0.76054
  Epoch 020 - train 0.42438 | val 1.00320
  Epoch 022 - train 0.34917 | val 1.36803
  Classification -> best τ=0.550 (val F1=0.4398)
  Directional -> Accuracy: 0.5745, MCC: 0.1988, F1: 0.4737

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57914 | val 1.49571
  Epoch 011 - train 0.55726 | val 2.04200
  Classification -> best τ=0.460 (val F1=0.2422)
  Directional -> Accuracy: 0.5067, MCC: -0.0632, F1: 0.6408

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44533 | val 4.06556
  Epoch 011 - train 0.40521 | val 4.46945
  Classification -> best τ=0.340 (val F1=0.4380)
  Directional -> Accuracy: 0.7647, MCC: 0.5301, F1: 0.7931

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38404 | val 1.68347
  Epoch 011 - train 0.37567 | val 1.70430
  Classification -> best τ=0.475 (val F1=0.1588)
  Directional -> Accuracy: 0.5319, MCC: 0.0644, F1: 0.3125

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60793 | val 0.94588
  Epoch 011 - train 0.57297 | val 1.03335
  Classification -> best τ=0.255 (val F1=0.2607)
  Directional -> Accuracy: 0.4203, MCC: 0.0033, F1: 0.5652

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48154 | val 3.74037
  Epoch 011 - train 0.42980 | val 4.21121
  Classification -> best τ=0.600 (val F1=0.3639)
  Directional -> Accuracy: 0.4545, MCC: -0.0437, F1: 0.4783

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58827 | val 1.09454
  Epoch 013 - train 0.50518 | val 1.39110
  Classification -> best τ=0.370 (val F1=0.2855)
  Directional -> Accuracy: 0.6939, MCC: 0.3869, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52899 | val 0.83676
  Epoch 011 - train 0.45435 | val 0.72037
  Classification -> best τ=0.320 (val F1=0.1816)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51006 | val 3.93137
  Epoch 011 - train 0.48837 | val 3.69523
  Classification -> best τ=0.615 (val F1=0.1896)
  Directional -> Accuracy: 0.6400, MCC: 0.2694, F1: 0.5500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55558 | val 2.72549
  Epoch 012 - train 0.50370 | val 2.89707
  Classification -> best τ=0.500 (val F1=0.2453)
  Directional -> Accuracy: 0.6379, MCC: 0.3223, F1: 0.5116

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54608 | val 1.98149
  Epoch 012 - train 0.46345 | val 2.63112
  Classification -> best τ=0.320 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68341 | val 0.65781
  Epoch 011 - train 0.66523 | val 0.69904
  Classification -> best τ=0.190 (val F1=0.2928)
  Directional -> Accuracy: 0.5246, MCC: 0.0647, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49533 | val 1.26835
  Epoch 011 - train 0.49345 | val 0.96120
  Classification -> best τ=0.665 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59812 | val 0.77653
  Epoch 013 - train 0.55449 | val 0.99695
  Classification -> best τ=0.275 (val F1=0.2039)
  Directional -> Accuracy: 0.5286, MCC: -0.1105, F1: 0.6916

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56218 | val 1.38931
  Epoch 011 - train 0.55033 | val 1.20561
  Classification -> best τ=0.295 (val F1=0.1302)
  Directional -> Accuracy: 0.6271, MCC: 0.0884, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53397 | val 1.78676
  Epoch 012 - train 0.53910 | val 1.42887
  Classification -> best τ=0.455 (val F1=0.1799)
  Directional -> Accuracy: 0.5395, MCC: 0.1804, F1: 0.4928

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55031 | val 1.66580
  Epoch 017 - train 0.45507 | val 1.42717
  Classification -> best τ=0.650 (val F1=0.2249)
  Directional -> Accuracy: 0.4308, MCC: 0.0090, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55040 | val 0.73938
  Epoch 013 - train 0.45726 | val 1.27535
  Classification -> best τ=0.575 (val F1=0.2672)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52526 | val 0.82133
  Epoch 019 - train 0.29151 | val 2.54106
  Classification -> best τ=0.330 (val F1=0.3143)
  Directional -> Accuracy: 0.6042, MCC: 0.0689, F1: 0.7246

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54171 | val 1.46535
  Epoch 011 - train 0.52104 | val 1.73804
  Classification -> best τ=0.335 (val F1=0.1167)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6452

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55215 | val 3.83001
  Epoch 011 - train 0.52919 | val 4.84760
  Classification -> best τ=0.585 (val F1=0.2234)
  Directional -> Accuracy: 0.5517, MCC: 0.0331, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50658 | val 0.85275
  Epoch 011 - train 0.50684 | val 1.16325
  Classification -> best τ=0.340 (val F1=0.2342)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57443 | val 0.76998
  Epoch 011 - train 0.50277 | val 0.81823
  Classification -> best τ=0.480 (val F1=0.3807)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47503 | val 1.32045
  Epoch 011 - train 0.43580 | val 1.53420
  Classification -> best τ=0.445 (val F1=0.1581)
  Directional -> Accuracy: 0.5652, MCC: 0.1641, F1: 0.5833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60188 | val 1.86123
  Epoch 015 - train 0.48563 | val 1.31743
  Classification -> best τ=0.550 (val F1=0.2587)
  Directional -> Accuracy: 0.6279, MCC: 0.2804, F1: 0.6364

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61371 | val 0.89064
  Epoch 015 - train 0.50175 | val 1.43562
  Classification -> best τ=0.440 (val F1=0.2781)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53879 | val 0.73232
  Epoch 013 - train 0.47240 | val 0.82648
  Classification -> best τ=0.490 (val F1=0.5204)
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45564 | val 4.08585
  Epoch 011 - train 0.42983 | val 4.01324
  Classification -> best τ=0.690 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50675 | val 1.30381
  Epoch 011 - train 0.52594 | val 1.43311
  Classification -> best τ=0.440 (val F1=0.0296)
  Directional -> Accuracy: 0.4884, MCC: -0.0604, F1: 0.5926

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47473 | val 2.03226
  Epoch 011 - train 0.47507 | val 1.71644
  Classification -> best τ=0.365 (val F1=0.2369)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57010 | val 0.79757
  Epoch 016 - train 0.39748 | val 1.26469
  Classification -> best τ=0.380 (val F1=0.4012)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49751 | val 2.64419
  Epoch 011 - train 0.46978 | val 2.42815
  Classification -> best τ=0.495 (val F1=0.2041)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56987 | val 0.77447
  Epoch 016 - train 0.47806 | val 1.37246
  Classification -> best τ=0.690 (val F1=0.2400)
  Directional -> Accuracy: 0.5455, MCC: 0.1041, F1: 0.5833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56488 | val 0.71673
  Epoch 012 - train 0.53004 | val 0.86853
  Classification -> best τ=0.245 (val F1=0.3687)
  Directional -> Accuracy: 0.5821, MCC: 0.1560, F1: 0.6216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49083 | val 1.36667
  Epoch 011 - train 0.46085 | val 1.34532
  Classification -> best τ=0.645 (val F1=0.1818)
  Directional -> Accuracy: 0.5814, MCC: 0.2074, F1: 0.4375

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48392 | val 1.50529
  Epoch 012 - train 0.39624 | val 2.21544
  Classification -> best τ=0.360 (val F1=0.2547)
  Directional -> Accuracy: 0.5088, MCC: 0.0516, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47824 | val 2.25289
  Epoch 011 - train 0.42175 | val 1.64210
  Classification -> best τ=0.395 (val F1=0.1162)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51192 | val 0.74337
  Epoch 012 - train 0.45923 | val 0.73866
  Classification -> best τ=0.475 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51268 | val 1.66134
  Epoch 011 - train 0.45809 | val 1.88108
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55627 | val 1.76078
  Epoch 013 - train 0.42924 | val 1.95620
  Classification -> best τ=0.625 (val F1=0.3971)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55667 | val 0.91337
  Epoch 012 - train 0.46895 | val 1.04408
  Classification -> best τ=0.450 (val F1=0.4379)
  Directional -> Accuracy: 0.4894, MCC: -0.0344, F1: 0.5862

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49062 | val 2.00714
  Epoch 016 - train 0.34324 | val 3.21628
  Classification -> best τ=0.550 (val F1=0.4594)
  Directional -> Accuracy: 0.5455, MCC: 0.0506, F1: 0.6296

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48029 | val 2.33057
  Epoch 011 - train 0.42803 | val 2.74048
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61857 | val 0.87768
  Epoch 012 - train 0.54040 | val 2.37781
  Classification -> best τ=0.855 (val F1=0.2519)
  Directional -> Accuracy: 0.6786, MCC: 0.3581, F1: 0.6897

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49377 | val 1.03201
  Epoch 011 - train 0.44382 | val 1.33288
  Classification -> best τ=0.485 (val F1=0.3535)
  Directional -> Accuracy: 0.4737, MCC: -0.0101, F1: 0.6341

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55383 | val 2.51430
  Epoch 011 - train 0.52921 | val 2.57037
  Classification -> best τ=0.375 (val F1=0.1626)
  Directional -> Accuracy: 0.5741, MCC: 0.1448, F1: 0.6462

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50802 | val 0.89994
  Epoch 011 - train 0.48318 | val 0.77641
  Classification -> best τ=0.620 (val F1=0.1794)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59753 | val 1.14935

[I 2026-02-20 03:18:05,117] Trial 111 finished with value: 0.25139609098748017 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.00487169710792784, 'weight_decay': 7.005122704525887e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5256147474536624, 'early_stopping_min_delta': 0.007989628483805944}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.53398 | val 1.38139
  Classification -> best τ=0.490 (val F1=0.2136)
  Directional -> Accuracy: 0.4590, MCC: -0.0903, F1: 0.4000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25139609098748017
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59572 | val 1.16719
  Epoch 015 - train 0.43812 | val 2.41975
  Classification -> best τ=0.565 (val F1=0.2453)
  Directional -> Accuracy: 0.5325, MCC: 0.0266, F1: 0.3571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46534 | val 0.81629
  Epoch 012 - train 0.41815 | val 0.96348
  Classification -> best τ=0.590 (val F1=0.2431)
  Directional -> Accuracy: 0.6739, MCC: 0.3407, F1: 0.7059

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50526 | val 1.00912
  Epoch 012 - train 0.44283 | val 1.06810
  Classification -> best τ=0.485 (val F1=0.4151)
  Directional -> Accuracy: 0.5745, MCC: 0.1424, F1: 0.6875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59115 | val 1.96874
  Epoch 011 - train 0.56997 | val 2.75716
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53032 | val 4.26212
  Epoch 011 - train 0.48411 | val 5.04446
  Classification -> best τ=0.525 (val F1=0.2470)
  Directional -> Accuracy: 0.6078, MCC: 0.3334, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41525 | val 1.91951
  Epoch 011 - train 0.41977 | val 1.68191
  Classification -> best τ=0.385 (val F1=0.2928)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59301 | val 0.95744
  Epoch 011 - train 0.56590 | val 1.19632
  Classification -> best τ=0.405 (val F1=0.1170)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47054 | val 3.06428
  Epoch 011 - train 0.46348 | val 3.57014
  Classification -> best τ=0.615 (val F1=0.3295)
  Directional -> Accuracy: 0.5455, MCC: 0.1097, F1: 0.5238

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51709 | val 1.57869
  Epoch 012 - train 0.46000 | val 1.79927
  Classification -> best τ=0.495 (val F1=0.3039)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53753 | val 0.78745
  Epoch 011 - train 0.56216 | val 0.75437
  Classification -> best τ=0.480 (val F1=0.1508)
  Directional -> Accuracy: 0.5429, MCC: 0.1179, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51648 | val 2.50488
  Epoch 011 - train 0.47509 | val 2.37092
  Classification -> best τ=0.605 (val F1=0.2722)
  Directional -> Accuracy: 0.6800, MCC: 0.4032, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48714 | val 3.22265
  Epoch 012 - train 0.48553 | val 3.49995
  Classification -> best τ=0.360 (val F1=0.3055)
  Directional -> Accuracy: 0.6552, MCC: 0.3229, F1: 0.6000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48071 | val 2.36936
  Epoch 012 - train 0.45021 | val 3.29765
  Classification -> best τ=0.535 (val F1=0.2778)
  Directional -> Accuracy: 0.5581, MCC: 0.0901, F1: 0.4571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62771 | val 0.68231
  Epoch 011 - train 0.57992 | val 0.69462
  Classification -> best τ=0.580 (val F1=0.3430)
  Directional -> Accuracy: 0.5738, MCC: 0.1530, F1: 0.5357

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54649 | val 0.77378
  Epoch 012 - train 0.50258 | val 0.79791
  Classification -> best τ=0.655 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53028 | val 1.25671
  Epoch 011 - train 0.53280 | val 1.32991
  Classification -> best τ=0.425 (val F1=0.3360)
  Directional -> Accuracy: 0.6571, MCC: 0.3131, F1: 0.7333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55854 | val 1.75990
  Epoch 011 - train 0.54372 | val 1.94985
  Classification -> best τ=0.350 (val F1=0.1857)
  Directional -> Accuracy: 0.6271, MCC: 0.0492, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56389 | val 1.45213
  Epoch 011 - train 0.51648 | val 1.09114
  Classification -> best τ=0.520 (val F1=0.2110)
  Directional -> Accuracy: 0.5921, MCC: -0.0933, F1: 0.7438

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51463 | val 1.14298
  Epoch 012 - train 0.48657 | val 1.36082
  Classification -> best τ=0.660 (val F1=0.1356)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62521 | val 1.26519
  Epoch 020 - train 0.37869 | val 0.70802
  Epoch 022 - train 0.33777 | val 0.74086
  Classification -> best τ=0.515 (val F1=0.3778)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48663 | val 1.12718
  Epoch 012 - train 0.36842 | val 1.24150
  Classification -> best τ=0.535 (val F1=0.2174)
  Directional -> Accuracy: 0.6042, MCC: -0.0222, F1: 0.7467

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59639 | val 2.02688
  Epoch 011 - train 0.57814 | val 2.22483
  Classification -> best τ=0.525 (val F1=0.2732)
  Directional -> Accuracy: 0.5606, MCC: 0.1361, F1: 0.4314

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64286 | val 0.97076
  Epoch 013 - train 0.59431 | val 1.48658
  Classification -> best τ=0.590 (val F1=0.2575)
  Directional -> Accuracy: 0.5517, MCC: 0.1362, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60167 | val 1.19540
  Epoch 011 - train 0.55037 | val 1.43926
  Classification -> best τ=0.290 (val F1=0.2983)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61130 | val 0.77695
  Epoch 016 - train 0.41954 | val 0.85794
  Classification -> best τ=0.605 (val F1=0.3656)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52126 | val 1.47279
  Epoch 011 - train 0.49639 | val 1.46406
  Classification -> best τ=0.415 (val F1=0.2294)
  Directional -> Accuracy: 0.5000, MCC: -0.1274, F1: 0.1481

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63697 | val 0.70770
  Epoch 011 - train 0.56764 | val 0.82305
  Classification -> best τ=0.520 (val F1=0.1539)
  Directional -> Accuracy: 0.5814, MCC: 0.1400, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57505 | val 1.02707
  Epoch 011 - train 0.52658 | val 1.06505
  Classification -> best τ=0.380 (val F1=0.2235)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51209 | val 0.68719
  Epoch 020 - train 0.35114 | val 0.88293
  Classification -> best τ=0.535 (val F1=0.3203)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45766 | val 1.90984
  Epoch 011 - train 0.44905 | val 1.73939
  Classification -> best τ=0.565 (val F1=0.2112)
  Directional -> Accuracy: 0.4419, MCC: -0.1788, F1: 0.1429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52350 | val 1.10683
  Epoch 011 - train 0.48222 | val 1.14198
  Classification -> best τ=0.465 (val F1=0.0985)
  Directional -> Accuracy: 0.5116, MCC: -0.0724, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47833 | val 1.72416
  Epoch 011 - train 0.44029 | val 2.04496
  Classification -> best τ=0.370 (val F1=0.2369)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50871 | val 0.70953
  Epoch 019 - train 0.34389 | val 1.29692
  Classification -> best τ=0.235 (val F1=0.3785)
  Directional -> Accuracy: 0.5479, MCC: 0.1851, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.48518 | val 2.13524
  Epoch 012 - train 0.44883 | val 2.36630
  Classification -> best τ=0.405 (val F1=0.2182)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55333 | val 1.21831
  Epoch 011 - train 0.56030 | val 1.07754
  Classification -> best τ=0.450 (val F1=0.2757)
  Directional -> Accuracy: 0.5455, MCC: 0.1988, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54471 | val 0.72740
  Epoch 012 - train 0.50829 | val 0.71464
  Classification -> best τ=0.325 (val F1=0.3626)
  Directional -> Accuracy: 0.5672, MCC: 0.2006, F1: 0.5085

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54629 | val 1.29114
  Epoch 011 - train 0.54317 | val 1.22149
  Classification -> best τ=0.570 (val F1=0.2443)
  Directional -> Accuracy: 0.6512, MCC: 0.3246, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46576 | val 1.22220
  Epoch 011 - train 0.43023 | val 1.15821
  Classification -> best τ=0.795 (val F1=0.2236)
  Directional -> Accuracy: 0.5439, MCC: 0.0710, F1: 0.2778

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41975 | val 1.77409
  Epoch 011 - train 0.41523 | val 1.90537
  Classification -> best τ=0.560 (val F1=0.1978)
  Directional -> Accuracy: 0.5106, MCC: 0.0805, F1: 0.5106

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49656 | val 1.34799
  Epoch 013 - train 0.41655 | val 1.60861
  Classification -> best τ=0.340 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44606 | val 1.89686
  Epoch 011 - train 0.42289 | val 2.09150
  Classification -> best τ=0.530 (val F1=0.1724)
  Directional -> Accuracy: 0.6316, MCC: 0.2753, F1: 0.6111

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52835 | val 1.63126
  Epoch 013 - train 0.48702 | val 2.07958
  Classification -> best τ=0.325 (val F1=0.3331)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48026 | val 0.72172
  Epoch 011 - train 0.46710 | val 0.73158
  Classification -> best τ=0.485 (val F1=0.2912)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46178 | val 2.52009
  Epoch 011 - train 0.44505 | val 2.29637
  Classification -> best τ=0.500 (val F1=0.2100)
  Directional -> Accuracy: 0.5909, MCC: 0.1394, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47962 | val 2.13862
  Epoch 011 - train 0.48212 | val 2.53926
  Classification -> best τ=0.465 (val F1=0.2626)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61052 | val 1.48203
  Epoch 011 - train 0.56736 | val 1.71467
  Classification -> best τ=0.750 (val F1=0.3040)
  Directional -> Accuracy: 0.5179, MCC: 0.0621, F1: 0.4490

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50732 | val 1.57933
  Epoch 011 - train 0.44530 | val 1.45620
  Classification -> best τ=0.655 (val F1=0.3836)
  Directional -> Accuracy: 0.5088, MCC: 0.0799, F1: 0.6316

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64242 | val 0.71626
  Epoch 013 - train 0.53347 | val 1.32018
  Classification -> best τ=0.415 (val F1=0.2663)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52516 | val 0.73882
  Epoch 011 - train 0.49489 | val 0.72409
  Classification -> best τ=0.300 (val F1=0.1001)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58153 | val 1.29902

[I 2026-02-20 03:19:23,311] Trial 112 finished with value: 0.26086385822625036 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0037209389335047015, 'weight_decay': 9.923619346667092e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.3871313234983764, 'early_stopping_min_delta': 0.008545568982029286}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 015 - train 0.46429 | val 1.88330
  Classification -> best τ=0.475 (val F1=0.4613)
  Directional -> Accuracy: 0.4918, MCC: -0.0314, F1: 0.3922

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26086385822625036
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59515 | val 0.92294
  Epoch 014 - train 0.48841 | val 1.40100
  Classification -> best τ=0.580 (val F1=0.1989)
  Directional -> Accuracy: 0.5584, MCC: 0.0944, F1: 0.4516

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46906 | val 1.16560
  Epoch 012 - train 0.39713 | val 1.02847
  Classification -> best τ=0.385 (val F1=0.1654)
  Directional -> Accuracy: 0.5870, MCC: 0.1164, F1: 0.7164

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55488 | val 0.97970
  Epoch 017 - train 0.37175 | val 1.62639
  Classification -> best τ=0.610 (val F1=0.5016)
  Directional -> Accuracy: 0.5106, MCC: -0.0150, F1: 0.6230

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54543 | val 2.54759
  Epoch 012 - train 0.50954 | val 3.42189
  Classification -> best τ=0.475 (val F1=0.2330)
  Directional -> Accuracy: 0.4933, MCC: 0.1859, F1: 0.1364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41265 | val 7.46609
  Epoch 011 - train 0.45915 | val 4.53016
  Classification -> best τ=0.370 (val F1=0.5248)
  Directional -> Accuracy: 0.7059, MCC: 0.4114, F1: 0.7170

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37296 | val 2.41311
  Epoch 011 - train 0.33234 | val 2.02823
  Classification -> best τ=0.495 (val F1=0.2357)
  Directional -> Accuracy: 0.5532, MCC: 0.1151, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61724 | val 1.72079
  Epoch 015 - train 0.48628 | val 1.40390
  Classification -> best τ=0.710 (val F1=0.1239)
  Directional -> Accuracy: 0.5797, MCC: 0.0432, F1: 0.2564

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49849 | val 1.88412
  Epoch 011 - train 0.54177 | val 2.29925
  Classification -> best τ=0.635 (val F1=0.3295)
  Directional -> Accuracy: 0.6136, MCC: 0.1436, F1: 0.3200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57710 | val 0.73268
  Epoch 012 - train 0.52688 | val 0.79657
  Classification -> best τ=0.555 (val F1=0.1945)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58273 | val 0.71939
  Epoch 018 - train 0.41303 | val 1.12843
  Classification -> best τ=0.435 (val F1=0.2357)
  Directional -> Accuracy: 0.4429, MCC: -0.0402, F1: 0.5412

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51879 | val 2.82238
  Epoch 011 - train 0.50934 | val 3.67460
  Classification -> best τ=0.570 (val F1=0.3118)
  Directional -> Accuracy: 0.6400, MCC: 0.3215, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50735 | val 3.99118
  Epoch 011 - train 0.48564 | val 4.75991
  Classification -> best τ=0.190 (val F1=0.2172)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50640 | val 1.82619
  Epoch 011 - train 0.48529 | val 1.92392
  Classification -> best τ=0.385 (val F1=0.1953)
  Directional -> Accuracy: 0.4186, MCC: -0.1178, F1: 0.5283

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67459 | val 0.72309
  Epoch 014 - train 0.55451 | val 0.68253
  Classification -> best τ=0.285 (val F1=0.3336)
  Directional -> Accuracy: 0.5574, MCC: 0.1199, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59430 | val 0.91411
  Epoch 016 - train 0.39343 | val 0.98979
  Classification -> best τ=0.675 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52199 | val 1.52351
  Epoch 011 - train 0.50070 | val 2.39979
  Classification -> best τ=0.370 (val F1=0.1678)
  Directional -> Accuracy: 0.4857, MCC: -0.2259, F1: 0.6538

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58178 | val 1.60839
  Epoch 011 - train 0.54179 | val 1.70148
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51566 | val 1.33533
  Epoch 011 - train 0.51157 | val 1.78794
  Classification -> best τ=0.660 (val F1=0.1800)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58024 | val 1.48598
  Epoch 019 - train 0.38098 | val 1.49598
  Classification -> best τ=0.475 (val F1=0.3032)
  Directional -> Accuracy: 0.4462, MCC: 0.0307, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55625 | val 1.02843
  Epoch 016 - train 0.41980 | val 1.42732
  Classification -> best τ=0.655 (val F1=0.2385)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46397 | val 1.34793
  Epoch 011 - train 0.44479 | val 2.00498
  Classification -> best τ=0.630 (val F1=0.2190)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.6452

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56942 | val 1.80960
  Epoch 012 - train 0.51324 | val 1.93102
  Classification -> best τ=0.525 (val F1=0.1603)
  Directional -> Accuracy: 0.4394, MCC: -0.1240, F1: 0.4932

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61244 | val 1.44713
  Epoch 012 - train 0.58063 | val 2.29223
  Classification -> best τ=0.660 (val F1=0.4365)
  Directional -> Accuracy: 0.5862, MCC: 0.1564, F1: 0.6364

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52592 | val 3.60369
  Epoch 011 - train 0.50922 | val 3.18663
  Classification -> best τ=0.330 (val F1=0.1493)
  Directional -> Accuracy: 0.5606, MCC: 0.1233, F1: 0.5538

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51403 | val 1.10424
  Epoch 013 - train 0.58489 | val 0.73728
  Classification -> best τ=0.400 (val F1=0.3730)
  Directional -> Accuracy: 0.5714, MCC: 0.1762, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46370 | val 1.79615
  Epoch 011 - train 0.39821 | val 2.02721
  Classification -> best τ=0.550 (val F1=0.1925)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54019 | val 0.73907
  Epoch 016 - train 0.44418 | val 1.37593
  Classification -> best τ=0.605 (val F1=0.2804)
  Directional -> Accuracy: 0.5116, MCC: 0.0352, F1: 0.5333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64101 | val 0.68549
  Epoch 011 - train 0.57247 | val 0.69386
  Classification -> best τ=0.460 (val F1=0.2866)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52011 | val 1.95012
  Epoch 014 - train 0.44920 | val 1.77143
  Classification -> best τ=0.660 (val F1=0.3595)
  Directional -> Accuracy: 0.3902, MCC: -0.2308, F1: 0.4444

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47173 | val 7.26466
  Epoch 012 - train 0.38766 | val 5.89715
  Classification -> best τ=0.675 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0849, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47777 | val 1.46822
  Epoch 013 - train 0.39880 | val 1.64142
  Classification -> best τ=0.805 (val F1=0.1759)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53097 | val 1.87673
  Epoch 011 - train 0.48305 | val 2.14886
  Classification -> best τ=0.200 (val F1=0.2541)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48733 | val 0.96544
  Epoch 011 - train 0.48570 | val 0.92847
  Classification -> best τ=0.600 (val F1=0.2725)
  Directional -> Accuracy: 0.5205, MCC: 0.1499, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47555 | val 1.70061
  Epoch 012 - train 0.47842 | val 2.32374
  Classification -> best τ=0.465 (val F1=0.2182)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58909 | val 1.48665
  Epoch 014 - train 0.44306 | val 2.14822
  Classification -> best τ=0.350 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54879 | val 1.13972
  Epoch 011 - train 0.53101 | val 0.87221
  Classification -> best τ=0.360 (val F1=0.4655)
  Directional -> Accuracy: 0.5224, MCC: 0.0977, F1: 0.4667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52280 | val 0.77375
  Epoch 014 - train 0.44935 | val 1.41383
  Classification -> best τ=0.580 (val F1=0.3364)
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.3636

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46953 | val 1.71621
  Epoch 011 - train 0.41353 | val 1.45976
  Classification -> best τ=0.325 (val F1=0.3112)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46835 | val 1.06059
  Epoch 011 - train 0.44887 | val 0.94488
  Classification -> best τ=0.500 (val F1=0.3014)
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.5385

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52577 | val 0.89593
  Epoch 012 - train 0.53835 | val 1.27658
  Classification -> best τ=0.405 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43090 | val 3.13838
  Epoch 011 - train 0.46207 | val 3.44680
  Classification -> best τ=0.555 (val F1=0.0134)
  Directional -> Accuracy: 0.6053, MCC: 0.3693, F1: 0.4000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51545 | val 3.09357
  Epoch 011 - train 0.46840 | val 3.13724
  Classification -> best τ=0.115 (val F1=0.2806)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46051 | val 0.93401
  Epoch 011 - train 0.45965 | val 0.81631
  Classification -> best τ=0.605 (val F1=0.3855)
  Directional -> Accuracy: 0.5106, MCC: 0.1443, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52221 | val 1.49138
  Epoch 012 - train 0.40988 | val 1.33999
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47188 | val 4.23589
  Epoch 011 - train 0.42967 | val 4.91063
  Classification -> best τ=0.570 (val F1=0.5330)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55317 | val 1.26873
  Epoch 012 - train 0.49193 | val 2.68369
  Classification -> best τ=0.590 (val F1=0.2533)
  Directional -> Accuracy: 0.6071, MCC: 0.2455, F1: 0.5600

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55169 | val 0.75389
  Epoch 011 - train 0.51288 | val 1.01916
  Classification -> best τ=0.505 (val F1=0.4276)
  Directional -> Accuracy: 0.4912, MCC: 0.0084, F1: 0.5797

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59733 | val 0.79363
  Epoch 014 - train 0.51635 | val 1.43379
  Classification -> best τ=0.530 (val F1=0.2457)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48884 | val 0.71848
  Epoch 011 - train 0.47982 | val 0.74142
  Classification -> best τ=0.360 (val F1=0.1979)
  Directional -> Accuracy: 0.4464, MCC: -0.1995, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58872 | val 1.01585

[I 2026-02-20 03:20:43,293] Trial 113 finished with value: 0.26453841549364215 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.006280930290257859, 'weight_decay': 8.245916140742899e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.16288228176026898, 'early_stopping_min_delta': 0.008232689989008732}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.53302 | val 1.16241
  Classification -> best τ=0.505 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26453841549364215
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49568 | val 1.85810
  Epoch 011 - train 0.56099 | val 1.99113
  Classification -> best τ=0.600 (val F1=0.3280)
  Directional -> Accuracy: 0.5195, MCC: -0.0246, F1: 0.2449

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45429 | val 0.97256
  Epoch 011 - train 0.43169 | val 1.08439
  Classification -> best τ=0.505 (val F1=0.2707)
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.2069

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57881 | val 0.80958
  Epoch 017 - train 0.29375 | val 2.01173
  Classification -> best τ=0.830 (val F1=0.4719)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64692 | val 1.41486
  Epoch 016 - train 0.47526 | val 6.27451
  Classification -> best τ=0.455 (val F1=0.2065)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52351 | val 2.52041
  Epoch 011 - train 0.47330 | val 2.59124
  Classification -> best τ=0.480 (val F1=0.4051)
  Directional -> Accuracy: 0.5294, MCC: 0.0833, F1: 0.4545

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37833 | val 1.68272
  Epoch 012 - train 0.30576 | val 1.44916
  Classification -> best τ=0.320 (val F1=0.2357)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56500 | val 1.03947
  Epoch 013 - train 0.46635 | val 1.26356
  Classification -> best τ=0.410 (val F1=0.2938)
  Directional -> Accuracy: 0.5217, MCC: 0.1968, F1: 0.6024

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.30439 | val 5.95788
  Epoch 011 - train 0.30594 | val 6.17142
  Classification -> best τ=0.345 (val F1=0.1752)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43319 | val 1.64501
  Epoch 012 - train 0.39571 | val 2.01573
  Classification -> best τ=0.665 (val F1=0.3475)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53912 | val 0.87244
  Epoch 013 - train 0.38488 | val 1.16657
  Classification -> best τ=0.455 (val F1=0.1625)
  Directional -> Accuracy: 0.4857, MCC: -0.0589, F1: 0.3793

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60256 | val 2.08426
  Epoch 015 - train 0.40287 | val 4.48344
  Classification -> best τ=0.365 (val F1=0.2632)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46526 | val 5.10081
  Epoch 011 - train 0.43692 | val 5.13899
  Classification -> best τ=0.060 (val F1=0.2453)
  Directional -> Accuracy: 0.5862, MCC: 0.2381, F1: 0.3684

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42243 | val 7.05646
  Epoch 011 - train 0.41461 | val 6.16678
  Classification -> best τ=0.650 (val F1=0.2778)
  Directional -> Accuracy: 0.5116, MCC: -0.1237, F1: 0.0870

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64610 | val 1.00614
  Epoch 013 - train 0.54064 | val 2.22607
  Classification -> best τ=0.225 (val F1=0.3134)
  Directional -> Accuracy: 0.4754, MCC: -0.1281, F1: 0.6364

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49611 | val 0.69069
  Epoch 012 - train 0.44115 | val 1.19306
  Classification -> best τ=0.465 (val F1=0.1508)
  Directional -> Accuracy: 0.6923, MCC: 0.3947, F1: 0.5789

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53712 | val 1.96777
  Epoch 012 - train 0.47470 | val 2.51022
  Classification -> best τ=0.755 (val F1=0.3685)
  Directional -> Accuracy: 0.4857, MCC: 0.0150, F1: 0.3571

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56208 | val 1.37702
  Epoch 011 - train 0.63287 | val 1.27798
  Classification -> best τ=0.405 (val F1=0.3015)
  Directional -> Accuracy: 0.4237, MCC: -0.2560, F1: 0.5526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64776 | val 1.15038
  Epoch 017 - train 0.40466 | val 1.40753
  Classification -> best τ=0.700 (val F1=0.2236)
  Directional -> Accuracy: 0.3816, MCC: -0.1114, F1: 0.0784

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58401 | val 0.74804
  Epoch 011 - train 0.54500 | val 0.85438
  Classification -> best τ=0.500 (val F1=0.2712)
  Directional -> Accuracy: 0.4769, MCC: -0.0770, F1: 0.5526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47430 | val 0.88722
  Epoch 011 - train 0.46099 | val 0.88867
  Classification -> best τ=0.465 (val F1=0.2251)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49468 | val 0.76038
  Epoch 014 - train 0.34067 | val 0.72531
  Classification -> best τ=0.395 (val F1=0.4308)
  Directional -> Accuracy: 0.5833, MCC: 0.0710, F1: 0.6875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50342 | val 1.83832
  Epoch 011 - train 0.50149 | val 2.04478
  Classification -> best τ=0.405 (val F1=0.1167)
  Directional -> Accuracy: 0.5152, MCC: 0.0407, F1: 0.6364

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53455 | val 2.74894
  Epoch 011 - train 0.45626 | val 3.68930
  Classification -> best τ=0.695 (val F1=0.1826)
  Directional -> Accuracy: 0.4138, MCC: -0.1048, F1: 0.1053

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56507 | val 1.56681
  Epoch 012 - train 0.45773 | val 1.19987
  Classification -> best τ=0.360 (val F1=0.2140)
  Directional -> Accuracy: 0.5000, MCC: 0.0215, F1: 0.5600

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49195 | val 0.72510
  Epoch 012 - train 0.40880 | val 0.89769
  Classification -> best τ=0.465 (val F1=0.4472)
  Directional -> Accuracy: 0.4643, MCC: 0.0136, F1: 0.2105

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42028 | val 1.89022
  Epoch 011 - train 0.34833 | val 1.78730
  Classification -> best τ=0.635 (val F1=0.1925)
  Directional -> Accuracy: 0.5000, MCC: -0.0488, F1: 0.3429

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55019 | val 0.69162
  Epoch 012 - train 0.41529 | val 0.79926
  Classification -> best τ=0.540 (val F1=0.1702)
  Directional -> Accuracy: 0.4651, MCC: -0.1734, F1: 0.5965

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55374 | val 1.01210
  Epoch 012 - train 0.47576 | val 1.18818
  Classification -> best τ=0.355 (val F1=0.3077)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54340 | val 0.80094
  Epoch 019 - train 0.25165 | val 2.99133
  Classification -> best τ=0.545 (val F1=0.3870)
  Directional -> Accuracy: 0.4390, MCC: -0.1535, F1: 0.5306

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50366 | val 1.68083
  Epoch 012 - train 0.43341 | val 1.61254
  Classification -> best τ=0.645 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50200 | val 1.47896
  Epoch 013 - train 0.32487 | val 2.09507
  Classification -> best τ=0.565 (val F1=0.1820)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40432 | val 1.73747
  Epoch 011 - train 0.41632 | val 1.81407
  Classification -> best τ=0.355 (val F1=0.3474)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.46267 | val 0.76369
  Epoch 011 - train 0.45629 | val 0.75307
  Classification -> best τ=0.315 (val F1=0.3562)
  Directional -> Accuracy: 0.5479, MCC: 0.1481, F1: 0.4923

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54758 | val 2.19825
  Epoch 011 - train 0.50983 | val 2.84386
  Classification -> best τ=0.435 (val F1=0.3974)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50144 | val 1.77238
  Epoch 011 - train 0.48920 | val 2.40928
  Classification -> best τ=0.565 (val F1=0.2358)
  Directional -> Accuracy: 0.5000, MCC: 0.1457, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54688 | val 0.74834
  Epoch 011 - train 0.48554 | val 0.80403
  Classification -> best τ=0.195 (val F1=0.3767)
  Directional -> Accuracy: 0.5970, MCC: 0.1641, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39709 | val 1.36115
  Epoch 011 - train 0.37840 | val 1.48165
  Classification -> best τ=0.535 (val F1=0.2297)
  Directional -> Accuracy: 0.6047, MCC: 0.2739, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35765 | val 1.46363
  Epoch 011 - train 0.33436 | val 2.03768
  Classification -> best τ=0.185 (val F1=0.3191)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52409 | val 0.68961
  Epoch 020 - train 0.22537 | val 2.19413
  Classification -> best τ=0.790 (val F1=0.3871)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61635 | val 0.98373
  Epoch 013 - train 0.41045 | val 1.57513
  Classification -> best τ=0.285 (val F1=0.3825)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41729 | val 2.17929
  Epoch 011 - train 0.41450 | val 2.75511
  Classification -> best τ=0.430 (val F1=0.2041)
  Directional -> Accuracy: 0.6053, MCC: 0.2544, F1: 0.7170

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51730 | val 1.52795
  Epoch 011 - train 0.51793 | val 1.87954
  Classification -> best τ=0.455 (val F1=0.2603)
  Directional -> Accuracy: 0.5067, MCC: 0.0499, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43742 | val 0.86706
  Epoch 013 - train 0.31050 | val 1.50537
  Classification -> best τ=0.445 (val F1=0.4299)
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42917 | val 1.67313
  Epoch 013 - train 0.30209 | val 2.58525
  Classification -> best τ=0.750 (val F1=0.3690)
  Directional -> Accuracy: 0.4773, MCC: -0.0335, F1: 0.4889

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46482 | val 3.84990
  Epoch 014 - train 0.30623 | val 6.00745
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.47173 | val 2.85109
  Epoch 011 - train 0.43650 | val 2.42624
  Classification -> best τ=0.335 (val F1=0.1676)
  Directional -> Accuracy: 0.5893, MCC: 0.1895, F1: 0.7089

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54347 | val 1.56688
  Epoch 012 - train 0.47077 | val 2.35652
  Classification -> best τ=0.540 (val F1=0.2777)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62393 | val 0.93576
  Epoch 012 - train 0.47956 | val 1.09815
  Classification -> best τ=0.810 (val F1=0.2345)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48080 | val 0.67732
  Epoch 020 - train 0.16996 | val 1.23632
  Classification -> best τ=0.430 (val F1=0.2887)
  Directional -> Accuracy: 0.5893, MCC: 0.2033, F1: 0.6933

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62306 | val 1.93728

[I 2026-02-20 03:22:00,166] Trial 114 finished with value: 0.2798427166624599 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009924209219997962, 'weight_decay': 1.6078763827452348e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6860580173910986, 'early_stopping_min_delta': 0.008054571081577137}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.49231 | val 2.28218
  Classification -> best τ=0.445 (val F1=0.2921)
  Directional -> Accuracy: 0.5246, MCC: 0.0319, F1: 0.3830

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2798427166624599
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.73047 | val 0.74876
  Epoch 014 - train 0.55561 | val 2.65659
  Classification -> best τ=0.580 (val F1=0.2453)
  Directional -> Accuracy: 0.5325, MCC: -0.0490, F1: 0.0526

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58253 | val 1.50459
  Epoch 016 - train 0.38295 | val 3.26244
  Classification -> best τ=0.790 (val F1=0.1962)
  Directional -> Accuracy: 0.5652, MCC: 0.0870, F1: 0.6552

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66805 | val 0.70447
  Epoch 013 - train 0.57160 | val 0.84571
  Classification -> best τ=0.625 (val F1=0.3689)
  Directional -> Accuracy: 0.5745, MCC: 0.2727, F1: 0.3750

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58326 | val 2.60119
  Epoch 011 - train 0.54622 | val 2.28505
  Classification -> best τ=0.475 (val F1=0.2125)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59749 | val 0.68229
  Epoch 020 - train 0.34981 | val 1.33387
  Classification -> best τ=0.465 (val F1=0.4985)
  Directional -> Accuracy: 0.5686, MCC: 0.1775, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56477 | val 2.40738
  Epoch 011 - train 0.58924 | val 2.23481
  Classification -> best τ=0.555 (val F1=0.2037)
  Directional -> Accuracy: 0.6809, MCC: 0.3627, F1: 0.6512

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68430 | val 0.87632
  Epoch 016 - train 0.66701 | val 2.19663
  Classification -> best τ=0.520 (val F1=0.2287)
  Directional -> Accuracy: 0.5362, MCC: 0.1183, F1: 0.5429

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41675 | val 5.94728
  Epoch 011 - train 0.41415 | val 6.80021
  Classification -> best τ=0.565 (val F1=0.2168)
  Directional -> Accuracy: 0.5682, MCC: 0.1304, F1: 0.5128

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50258 | val 1.17899
  Epoch 011 - train 0.50527 | val 2.14987
  Classification -> best τ=0.545 (val F1=0.2129)
  Directional -> Accuracy: 0.5510, MCC: 0.1184, F1: 0.5600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66525 | val 0.84952
  Epoch 020 - train 0.36114 | val 1.24723
  Epoch 021 - train 0.34757 | val 1.22835
  Classification -> best τ=0.585 (val F1=0.2274)
  Directional -> Accuracy: 0.4714, MCC: -0.1141, F1: 0.3019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43151 | val 5.53091
  Epoch 012 - train 0.41790 | val 7.07849
  Classification -> best τ=0.720 (val F1=0.1675)
  Directional -> Accuracy: 0.4800, MCC: 0.0146, F1: 0.5938

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53351 | val 2.98110
  Epoch 012 - train 0.58261 | val 2.69477
  Classification -> best τ=0.260 (val F1=0.2943)
  Directional -> Accuracy: 0.4828, MCC: -0.1325, F1: 0.6512

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59938 | val 1.57209
  Epoch 016 - train 0.47522 | val 3.06045
  Classification -> best τ=0.220 (val F1=0.2596)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63291 | val 1.12853
  Epoch 014 - train 0.61519 | val 1.26251
  Classification -> best τ=0.310 (val F1=0.3798)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57672 | val 2.15780
  Epoch 012 - train 0.56348 | val 1.95087
  Classification -> best τ=0.365 (val F1=0.1802)
  Directional -> Accuracy: 0.4808, MCC: 0.0636, F1: 0.6301

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59182 | val 1.23294
  Epoch 012 - train 0.56883 | val 1.36477
  Classification -> best τ=0.505 (val F1=0.4341)
  Directional -> Accuracy: 0.5286, MCC: 0.0042, F1: 0.6526

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55906 | val 1.34252
  Epoch 011 - train 0.53568 | val 1.39233
  Classification -> best τ=0.690 (val F1=0.1302)
  Directional -> Accuracy: 0.3559, MCC: -0.1703, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56519 | val 2.75985
  Epoch 011 - train 0.56466 | val 3.26856
  Classification -> best τ=0.395 (val F1=0.2485)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62559 | val 1.65482
  Epoch 011 - train 0.59313 | val 2.93013
  Classification -> best τ=0.485 (val F1=0.3855)
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56286 | val 0.95204
  Epoch 011 - train 0.57371 | val 0.99969
  Classification -> best τ=0.470 (val F1=0.2701)
  Directional -> Accuracy: 0.3333, MCC: -0.3293, F1: 0.3421

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50165 | val 0.78387
  Epoch 011 - train 0.47540 | val 1.27776
  Classification -> best τ=0.435 (val F1=0.1803)
  Directional -> Accuracy: 0.5000, MCC: -0.0216, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59015 | val 2.85480
  Epoch 011 - train 0.59125 | val 2.90031
  Classification -> best τ=0.630 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58256 | val 1.05777
  Epoch 011 - train 0.57567 | val 1.21129
  Classification -> best τ=0.655 (val F1=0.1153)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61650 | val 1.22914
  Epoch 012 - train 0.60095 | val 0.88436
  Classification -> best τ=0.430 (val F1=0.1878)
  Directional -> Accuracy: 0.5455, MCC: 0.0741, F1: 0.4231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67982 | val 1.18053
  Epoch 018 - train 0.46865 | val 0.64967
  Classification -> best τ=0.440 (val F1=0.5533)
  Directional -> Accuracy: 0.4286, MCC: -0.1054, F1: 0.0588

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60833 | val 0.86107
  Epoch 013 - train 0.46056 | val 1.29826
  Classification -> best τ=0.450 (val F1=0.2774)
  Directional -> Accuracy: 0.6087, MCC: 0.3213, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60168 | val 1.56101
  Epoch 013 - train 0.54612 | val 2.44900
  Classification -> best τ=0.540 (val F1=0.3078)
  Directional -> Accuracy: 0.4651, MCC: 0.0024, F1: 0.3784

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61873 | val 1.24563
  Epoch 012 - train 0.55881 | val 1.00056
  Classification -> best τ=0.315 (val F1=0.2210)
  Directional -> Accuracy: 0.5789, MCC: 0.2374, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56068 | val 0.89702
  Epoch 015 - train 0.40919 | val 1.61161
  Classification -> best τ=0.630 (val F1=0.5290)
  Directional -> Accuracy: 0.5366, MCC: 0.0789, F1: 0.5366

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36677 | val 8.50002
  Epoch 011 - train 0.33602 | val 10.55392
  Classification -> best τ=0.705 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58337 | val 1.50300
  Epoch 014 - train 0.39458 | val 3.50647
  Classification -> best τ=0.600 (val F1=0.2513)
  Directional -> Accuracy: 0.4884, MCC: -0.0864, F1: 0.6207

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70758 | val 0.80716
  Epoch 014 - train 0.51299 | val 1.24287
  Classification -> best τ=0.620 (val F1=0.3349)
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61248 | val 0.70303
  Epoch 012 - train 0.57612 | val 0.93373
  Classification -> best τ=0.050 (val F1=0.3391)
  Directional -> Accuracy: 0.5616, MCC: 0.0658, F1: 0.6735

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.53959 | val 3.09018
  Epoch 015 - train 0.46115 | val 2.77122
  Classification -> best τ=0.445 (val F1=0.4082)
  Directional -> Accuracy: 0.5526, MCC: 0.1195, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51371 | val 1.50047
  Epoch 011 - train 0.46251 | val 1.59111
  Classification -> best τ=0.635 (val F1=0.2503)
  Directional -> Accuracy: 0.5682, MCC: 0.1304, F1: 0.5128

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55720 | val 0.81309
  Epoch 011 - train 0.52329 | val 0.90101
  Classification -> best τ=0.415 (val F1=0.3702)
  Directional -> Accuracy: 0.5075, MCC: 0.1999, F1: 0.2667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60327 | val 0.75132
  Epoch 014 - train 0.46532 | val 0.92936
  Classification -> best τ=0.535 (val F1=0.2486)
  Directional -> Accuracy: 0.5349, MCC: 0.1527, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50087 | val 3.00419
  Epoch 012 - train 0.43370 | val 5.17348
  Classification -> best τ=0.305 (val F1=0.2728)
  Directional -> Accuracy: 0.5439, MCC: 0.1085, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60624 | val 3.11388
  Epoch 012 - train 0.51081 | val 2.28175
  Classification -> best τ=0.355 (val F1=0.2957)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59661 | val 0.88418
  Epoch 016 - train 0.40661 | val 0.98456
  Classification -> best τ=0.480 (val F1=0.3957)
  Directional -> Accuracy: 0.3469, MCC: -0.1586, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57437 | val 2.11298
  Epoch 011 - train 0.46500 | val 1.62134
  Classification -> best τ=0.570 (val F1=0.0134)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59956 | val 1.71974
  Epoch 011 - train 0.57597 | val 1.26695
  Classification -> best τ=0.515 (val F1=0.3963)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58114 | val 1.10886
  Epoch 011 - train 0.47522 | val 1.19724
  Classification -> best τ=0.460 (val F1=0.4810)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65510 | val 1.12078
  Epoch 015 - train 0.40372 | val 1.81166
  Classification -> best τ=0.635 (val F1=0.2749)
  Directional -> Accuracy: 0.4091, MCC: -0.1283, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55707 | val 1.02840
  Epoch 011 - train 0.49260 | val 1.20061
  Classification -> best τ=0.495 (val F1=0.2357)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64341 | val 3.76808
  Epoch 013 - train 0.49510 | val 6.00856
  Classification -> best τ=0.795 (val F1=0.3057)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56921 | val 0.93175
  Epoch 012 - train 0.53874 | val 1.69802
  Classification -> best τ=0.565 (val F1=0.2157)
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60681 | val 2.24732
  Epoch 013 - train 0.63771 | val 2.00601
  Classification -> best τ=0.470 (val F1=0.3522)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68495 | val 2.62230
  Epoch 015 - train 0.48077 | val 1.48159
  Classification -> best τ=0.690 (val F1=0.2222)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57532 | val 6.06355
  Epoch 011 - train 0.53608 | val 6.45194

[I 2026-02-20 03:23:40,151] Trial 115 finished with value: 0.28441183406436493 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009998717482147887, 'weight_decay': 1.1308211086733871e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5937464403549231, 'early_stopping_min_delta': 0.00808921704327533}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.535 (val F1=0.3240)
  Directional -> Accuracy: 0.5410, MCC: 0.0692, F1: 0.2222

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28441183406436493
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61528 | val 1.44597
  Epoch 011 - train 0.71742 | val 1.65480
  Classification -> best τ=0.390 (val F1=0.0942)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63281 | val 0.87817
  Epoch 017 - train 0.65105 | val 1.28638
  Classification -> best τ=0.485 (val F1=0.2280)
  Directional -> Accuracy: 0.6087, MCC: 0.1812, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58332 | val 0.65805
  Epoch 020 - train 0.37268 | val 4.50535
  Classification -> best τ=0.840 (val F1=0.4719)
  Directional -> Accuracy: 0.5319, MCC: 0.1529, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63633 | val 1.41350
  Epoch 012 - train 0.61204 | val 0.82901
  Classification -> best τ=0.430 (val F1=0.2163)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63718 | val 1.89697
  Epoch 014 - train 0.51961 | val 2.80988
  Classification -> best τ=0.390 (val F1=0.3484)
  Directional -> Accuracy: 0.5882, MCC: 0.1673, F1: 0.6441

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51508 | val 0.89125
  Epoch 012 - train 0.42272 | val 2.32566
  Classification -> best τ=0.455 (val F1=0.2582)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63574 | val 1.51662
  Epoch 011 - train 0.61434 | val 1.04344
  Classification -> best τ=0.315 (val F1=0.1170)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39583 | val 5.27752
  Epoch 011 - train 0.35774 | val 6.25802
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59263 | val 1.64661
  Epoch 013 - train 0.44555 | val 2.86889
  Classification -> best τ=0.325 (val F1=0.2346)
  Directional -> Accuracy: 0.5918, MCC: 0.2435, F1: 0.6429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59337 | val 0.71884
  Epoch 018 - train 0.46486 | val 1.00143
  Classification -> best τ=0.660 (val F1=0.1620)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49502 | val 1.48126
  Epoch 011 - train 0.53728 | val 1.86250
  Classification -> best τ=0.400 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53911 | val 2.09616
  Epoch 012 - train 0.50681 | val 2.92126
  Classification -> best τ=0.260 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57196 | val 2.19378
  Epoch 012 - train 0.54412 | val 3.93607
  Classification -> best τ=0.440 (val F1=0.3606)
  Directional -> Accuracy: 0.5814, MCC: 0.1725, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70819 | val 1.49727
  Epoch 014 - train 0.63194 | val 1.27776
  Classification -> best τ=0.530 (val F1=0.2577)
  Directional -> Accuracy: 0.5574, MCC: 0.1243, F1: 0.4906

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66386 | val 2.67890
  Epoch 013 - train 0.51391 | val 6.11994
  Classification -> best τ=0.725 (val F1=0.2177)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55570 | val 1.69351
  Epoch 011 - train 0.54707 | val 2.51434
  Classification -> best τ=0.460 (val F1=0.1569)
  Directional -> Accuracy: 0.5714, MCC: 0.1210, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71164 | val 0.81017
  Epoch 016 - train 0.58228 | val 2.02535
  Classification -> best τ=0.530 (val F1=0.2673)
  Directional -> Accuracy: 0.3559, MCC: -0.1406, F1: 0.0500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53150 | val 13.69966
  Epoch 011 - train 0.55374 | val 15.77365
  Classification -> best τ=0.635 (val F1=0.0570)
  Directional -> Accuracy: 0.5000, MCC: 0.0587, F1: 0.4865

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66341 | val 0.98297
  Epoch 013 - train 0.54751 | val 0.92576
  Classification -> best τ=0.605 (val F1=0.2618)
  Directional -> Accuracy: 0.4462, MCC: 0.0307, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58772 | val 2.43858
  Epoch 014 - train 0.50440 | val 8.79060
  Classification -> best τ=0.520 (val F1=0.2281)
  Directional -> Accuracy: 0.4400, MCC: -0.0875, F1: 0.0455

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53073 | val 0.86233
  Epoch 011 - train 0.44387 | val 1.41292
  Classification -> best τ=0.470 (val F1=0.3555)
  Directional -> Accuracy: 0.5625, MCC: 0.3200, F1: 0.4878

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66723 | val 1.96436
  Epoch 011 - train 0.64836 | val 1.32942
  Classification -> best τ=0.405 (val F1=0.1673)
  Directional -> Accuracy: 0.5152, MCC: 0.0318, F1: 0.4286

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60115 | val 0.97757
  Epoch 012 - train 0.57855 | val 0.84919
  Classification -> best τ=0.550 (val F1=0.3450)
  Directional -> Accuracy: 0.5000, MCC: 0.0455, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63447 | val 1.18403
  Epoch 013 - train 0.61934 | val 0.97673
  Classification -> best τ=0.420 (val F1=0.1318)
  Directional -> Accuracy: 0.5455, MCC: 0.0741, F1: 0.4231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58194 | val 0.83411
  Epoch 013 - train 0.44129 | val 1.80628
  Classification -> best τ=0.475 (val F1=0.3656)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40620 | val 3.38346
  Epoch 011 - train 0.36502 | val 4.05288
  Classification -> best τ=0.455 (val F1=0.1925)
  Directional -> Accuracy: 0.5652, MCC: 0.2214, F1: 0.6296

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63003 | val 5.11357
  Epoch 011 - train 0.54143 | val 3.68604
  Classification -> best τ=0.630 (val F1=0.0905)
  Directional -> Accuracy: 0.4419, MCC: -0.0852, F1: 0.4286

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64587 | val 1.17779
  Epoch 015 - train 0.56876 | val 0.89706
  Classification -> best τ=0.425 (val F1=0.3440)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47019 | val 0.73506
  Epoch 011 - train 0.51579 | val 1.26079
  Classification -> best τ=0.545 (val F1=0.3069)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36754 | val 5.37186
  Epoch 011 - train 0.40805 | val 6.88629
  Classification -> best τ=0.615 (val F1=0.0468)
  Directional -> Accuracy: 0.5581, MCC: 0.1198, F1: 0.5778

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48934 | val 1.85939
  Epoch 011 - train 0.44638 | val 2.29951
  Classification -> best τ=0.665 (val F1=0.0296)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55528 | val 1.39284
  Epoch 012 - train 0.51497 | val 1.51557
  Classification -> best τ=0.370 (val F1=0.2461)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60026 | val 1.66314
  Epoch 017 - train 0.57624 | val 1.04965
  Classification -> best τ=0.290 (val F1=0.3809)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38743 | val 1.37964
  Epoch 011 - train 0.36095 | val 1.95525
  Classification -> best τ=0.465 (val F1=0.1085)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54233 | val 1.26899
  Epoch 012 - train 0.52956 | val 1.47687
  Classification -> best τ=0.630 (val F1=0.3028)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66278 | val 0.96263
  Epoch 020 - train 0.48205 | val 0.88304
  Epoch 029 - train 0.24199 | val 1.98684
  Classification -> best τ=0.275 (val F1=0.4141)
  Directional -> Accuracy: 0.4328, MCC: -0.0948, F1: 0.3667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45535 | val 2.50333
  Epoch 011 - train 0.42910 | val 2.60049
  Classification -> best τ=0.480 (val F1=0.2357)
  Directional -> Accuracy: 0.4419, MCC: -0.1294, F1: 0.5200

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52372 | val 2.38551
  Epoch 011 - train 0.51368 | val 1.68345
  Classification -> best τ=0.285 (val F1=0.1697)
  Directional -> Accuracy: 0.5614, MCC: 0.1304, F1: 0.5763

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59530 | val 1.19861
  Epoch 012 - train 0.55111 | val 1.86776
  Classification -> best τ=0.460 (val F1=0.2232)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59183 | val 0.71046
  Epoch 018 - train 0.42964 | val 0.67136
  Classification -> best τ=0.330 (val F1=0.3973)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.33993 | val 3.31919
  Epoch 011 - train 0.38438 | val 3.14405
  Classification -> best τ=0.745 (val F1=0.0134)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58174 | val 1.62108
  Epoch 014 - train 0.47866 | val 1.89989
  Classification -> best τ=0.400 (val F1=0.3620)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46241 | val 0.82915
  Epoch 020 - train 0.26794 | val 1.29832
  Epoch 021 - train 0.26127 | val 1.51740
  Classification -> best τ=0.685 (val F1=0.3301)
  Directional -> Accuracy: 0.5319, MCC: 0.0678, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50554 | val 0.84905
  Epoch 011 - train 0.47529 | val 0.90488
  Classification -> best τ=0.575 (val F1=0.3967)
  Directional -> Accuracy: 0.4318, MCC: -0.0300, F1: 0.0741

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50821 | val 1.95622
  Epoch 012 - train 0.54175 | val 2.52432
  Classification -> best τ=0.570 (val F1=0.0945)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61095 | val 1.57493
  Epoch 012 - train 0.56452 | val 2.14203
  Classification -> best τ=0.670 (val F1=0.2465)
  Directional -> Accuracy: 0.4821, MCC: -0.1659, F1: 0.6420

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52492 | val 1.56002
  Epoch 013 - train 0.42231 | val 1.74470
  Classification -> best τ=0.590 (val F1=0.3500)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61998 | val 0.72113
  Epoch 015 - train 0.58863 | val 1.35575
  Classification -> best τ=0.605 (val F1=0.3163)
  Directional -> Accuracy: 0.5000, MCC: -0.0225, F1: 0.6087

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68202 | val 0.92119
  Epoch 020 - train 0.50378 | val 0.70368
  Epoch 021 - train 0.50936 | val 0.80236
  Classification -> best τ=0.485 (val F1=0.2178)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.73665 | val 0.65133

[I 2026-02-20 03:25:19,808] Trial 116 finished with value: 0.23873833592433602 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009995436674048086, 'weight_decay': 1.2764741247378694e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6575043642607378, 'early_stopping_min_delta': 0.00804639602690436}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 020 - train 0.62728 | val 1.28048
  Classification -> best τ=0.335 (val F1=0.3586)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23873833592433602
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60334 | val 0.73776
  Epoch 011 - train 0.61268 | val 0.73733
  Classification -> best τ=0.545 (val F1=0.1989)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56563 | val 0.84304
  Epoch 013 - train 0.54474 | val 0.84961
  Classification -> best τ=0.490 (val F1=0.1953)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60941 | val 0.73470
  Epoch 014 - train 0.59439 | val 0.78034
  Classification -> best τ=0.520 (val F1=0.2212)
  Directional -> Accuracy: 0.5532, MCC: 0.2311, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62263 | val 2.13710
  Epoch 011 - train 0.62697 | val 2.17502
  Classification -> best τ=0.435 (val F1=0.1723)
  Directional -> Accuracy: 0.5067, MCC: 0.0646, F1: 0.3934

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56237 | val 0.67963
  Epoch 015 - train 0.54033 | val 0.71900
  Classification -> best τ=0.525 (val F1=0.4598)
  Directional -> Accuracy: 0.7451, MCC: 0.4883, F1: 0.7719

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54394 | val 1.62602
  Epoch 011 - train 0.54694 | val 1.67869
  Classification -> best τ=0.480 (val F1=0.1857)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60428 | val 0.84944
  Epoch 011 - train 0.61502 | val 0.84801
  Classification -> best τ=0.500 (val F1=0.1794)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59284 | val 1.51909
  Epoch 011 - train 0.58281 | val 1.63828
  Classification -> best τ=0.500 (val F1=0.2180)
  Directional -> Accuracy: 0.5227, MCC: 0.1108, F1: 0.5532

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57023 | val 0.72239
  Epoch 016 - train 0.58899 | val 0.72562
  Classification -> best τ=0.480 (val F1=0.2949)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59374 | val 0.81675
  Epoch 011 - train 0.59190 | val 0.81127
  Classification -> best τ=0.445 (val F1=0.1816)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60047 | val 1.96854
  Epoch 011 - train 0.60993 | val 1.99641
  Classification -> best τ=0.560 (val F1=0.2722)
  Directional -> Accuracy: 0.4400, MCC: -0.0902, F1: 0.5758

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59104 | val 1.88535
  Epoch 011 - train 0.58132 | val 1.93009
  Classification -> best τ=0.450 (val F1=0.2598)
  Directional -> Accuracy: 0.5345, MCC: 0.1000, F1: 0.2703

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57951 | val 1.97168
  Epoch 011 - train 0.56861 | val 2.02424
  Classification -> best τ=0.475 (val F1=0.2504)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61498 | val 0.66038
  Epoch 018 - train 0.57816 | val 0.69681
  Classification -> best τ=0.300 (val F1=0.3336)
  Directional -> Accuracy: 0.5410, MCC: 0.0906, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62750 | val 0.72120
  Epoch 011 - train 0.63382 | val 0.71450
  Classification -> best τ=0.530 (val F1=0.1802)
  Directional -> Accuracy: 0.5577, MCC: 0.0863, F1: 0.3030

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56230 | val 0.91242
  Epoch 012 - train 0.55845 | val 0.94112
  Classification -> best τ=0.390 (val F1=0.2172)
  Directional -> Accuracy: 0.5857, MCC: 0.2306, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61159 | val 1.76696
  Epoch 011 - train 0.60841 | val 1.78115
  Classification -> best τ=0.540 (val F1=0.1857)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60158 | val 1.02899
  Epoch 011 - train 0.59935 | val 1.08429
  Classification -> best τ=0.515 (val F1=0.1217)
  Directional -> Accuracy: 0.5789, MCC: -0.0698, F1: 0.7288

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58891 | val 0.92098
  Epoch 011 - train 0.58763 | val 0.93885
  Classification -> best τ=0.570 (val F1=0.2249)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58574 | val 0.73872
  Epoch 011 - train 0.58001 | val 0.74930
  Classification -> best τ=0.540 (val F1=0.1582)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59323 | val 0.94090
  Epoch 011 - train 0.57970 | val 0.94885
  Classification -> best τ=0.505 (val F1=0.1521)
  Directional -> Accuracy: 0.5625, MCC: 0.0121, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62524 | val 1.08037
  Epoch 011 - train 0.61595 | val 1.10226
  Classification -> best τ=0.560 (val F1=0.1688)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62256 | val 0.87047
  Epoch 013 - train 0.62359 | val 0.88603
  Classification -> best τ=0.535 (val F1=0.3342)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61362 | val 1.08860
  Epoch 011 - train 0.59371 | val 1.08786
  Classification -> best τ=0.520 (val F1=0.1688)
  Directional -> Accuracy: 0.5000, MCC: -0.0260, F1: 0.3529

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59832 | val 0.70528
  Epoch 013 - train 0.57516 | val 0.70821
  Classification -> best τ=0.565 (val F1=0.4124)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57042 | val 0.69531
  Epoch 011 - train 0.56801 | val 0.70159
  Classification -> best τ=0.530 (val F1=0.1741)
  Directional -> Accuracy: 0.4783, MCC: -0.0496, F1: 0.4286

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64648 | val 0.96228
  Epoch 011 - train 0.63470 | val 0.98907
  Classification -> best τ=0.460 (val F1=0.1309)
  Directional -> Accuracy: 0.4651, MCC: -0.0140, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60811 | val 0.73253
  Epoch 014 - train 0.59192 | val 0.74287
  Classification -> best τ=0.445 (val F1=0.1656)
  Directional -> Accuracy: 0.5263, MCC: 0.1434, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60504 | val 0.81544
  Epoch 011 - train 0.61705 | val 0.83958
  Classification -> best τ=0.540 (val F1=0.2924)
  Directional -> Accuracy: 0.5610, MCC: 0.1065, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59274 | val 0.75172
  Epoch 011 - train 0.58583 | val 0.75568
  Classification -> best τ=0.515 (val F1=0.1325)
  Directional -> Accuracy: 0.4884, MCC: -0.0074, F1: 0.6333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62200 | val 0.74489
  Epoch 011 - train 0.63040 | val 0.75152
  Classification -> best τ=0.520 (val F1=0.1437)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58894 | val 1.02212
  Epoch 011 - train 0.57742 | val 1.02956
  Classification -> best τ=0.465 (val F1=0.0506)
  Directional -> Accuracy: 0.4400, MCC: -0.1664, F1: 0.5484

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58591 | val 0.63799
  Epoch 014 - train 0.55408 | val 0.67505
  Classification -> best τ=0.290 (val F1=0.3602)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60725 | val 0.72470
  Epoch 011 - train 0.61066 | val 0.76757
  Classification -> best τ=0.550 (val F1=0.3162)
  Directional -> Accuracy: 0.4737, MCC: -0.0778, F1: 0.1667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61670 | val 1.05487
  Epoch 011 - train 0.60805 | val 1.07233
  Classification -> best τ=0.465 (val F1=0.2757)
  Directional -> Accuracy: 0.5000, MCC: 0.0780, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56711 | val 0.70532
  Epoch 013 - train 0.56697 | val 0.69557
  Classification -> best τ=0.370 (val F1=0.3266)
  Directional -> Accuracy: 0.4925, MCC: 0.0335, F1: 0.4333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61005 | val 0.68940
  Epoch 011 - train 0.59789 | val 0.68896
  Classification -> best τ=0.460 (val F1=0.0493)
  Directional -> Accuracy: 0.6512, MCC: 0.3027, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57944 | val 1.14418
  Epoch 012 - train 0.56146 | val 1.15612
  Classification -> best τ=0.450 (val F1=0.2261)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59626 | val 1.20009
  Epoch 011 - train 0.59386 | val 1.23598
  Classification -> best τ=0.480 (val F1=0.2881)
  Directional -> Accuracy: 0.5319, MCC: 0.0918, F1: 0.5600

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61697 | val 0.61361
  Epoch 020 - train 0.53520 | val 0.64847
  Classification -> best τ=0.640 (val F1=0.4345)
  Directional -> Accuracy: 0.4286, MCC: 0.0691, F1: 0.5333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58129 | val 0.80316
  Epoch 011 - train 0.58566 | val 0.83737
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58994 | val 1.11379
  Epoch 011 - train 0.58224 | val 1.13479
  Classification -> best τ=0.455 (val F1=0.2673)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57771 | val 0.82061
  Epoch 014 - train 0.55207 | val 0.86466
  Classification -> best τ=0.505 (val F1=0.4379)
  Directional -> Accuracy: 0.5106, MCC: 0.0311, F1: 0.4103

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55787 | val 0.86971
  Epoch 011 - train 0.57988 | val 0.90642
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61304 | val 0.89061
  Epoch 011 - train 0.60605 | val 0.90744
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61098 | val 0.79379
  Epoch 014 - train 0.59043 | val 0.81657
  Classification -> best τ=0.520 (val F1=0.1267)
  Directional -> Accuracy: 0.5536, MCC: 0.0801, F1: 0.6753

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58625 | val 1.10880
  Epoch 011 - train 0.59449 | val 1.09836
  Classification -> best τ=0.490 (val F1=0.3170)
  Directional -> Accuracy: 0.4737, MCC: -0.0518, F1: 0.4643

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59426 | val 1.16250
  Epoch 011 - train 0.59911 | val 1.20249
  Classification -> best τ=0.470 (val F1=0.1042)
  Directional -> Accuracy: 0.4444, MCC: -0.1131, F1: 0.2105

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60082 | val 0.73183
  Epoch 011 - train 0.60245 | val 0.74676
  Classification -> best τ=0.530 (val F1=0.2060)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62005 | val 1.01507
  Epoch 011 - train 0.61933 | val 1.05806

[I 2026-02-20 03:26:52,103] Trial 117 finished with value: 0.21419619332511228 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00016359281815170304, 'weight_decay': 1.70277938846021e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.4693186463640812, 'early_stopping_min_delta': 0.009108768375431661}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.500 (val F1=0.1367)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21419619332511228
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58091 | val 4.37083
  Epoch 011 - train 0.57005 | val 5.36217
  Classification -> best τ=0.440 (val F1=0.1810)
  Directional -> Accuracy: 0.5065, MCC: 0.1199, F1: 0.6275

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64383 | val 0.86098
  Epoch 011 - train 0.55930 | val 0.99413
  Classification -> best τ=0.545 (val F1=0.2014)
  Directional -> Accuracy: 0.4783, MCC: -0.0615, F1: 0.5385

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57972 | val 0.81785
  Epoch 012 - train 0.62559 | val 0.79014
  Classification -> best τ=0.450 (val F1=0.4547)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69228 | val 0.71305
  Epoch 013 - train 0.66781 | val 0.80715
  Classification -> best τ=0.485 (val F1=0.1868)
  Directional -> Accuracy: 0.4933, MCC: 0.0134, F1: 0.4412

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66415 | val 0.94361
  Epoch 012 - train 0.60253 | val 1.97034
  Classification -> best τ=0.400 (val F1=0.4457)
  Directional -> Accuracy: 0.6275, MCC: 0.2536, F1: 0.6984

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60905 | val 2.10394
  Epoch 013 - train 0.38082 | val 4.49501
  Classification -> best τ=0.390 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64199 | val 1.18465
  Epoch 012 - train 0.63576 | val 0.85492
  Classification -> best τ=0.535 (val F1=0.3272)
  Directional -> Accuracy: 0.5507, MCC: 0.1175, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63813 | val 2.04375
  Epoch 015 - train 0.49059 | val 0.91117
  Classification -> best τ=0.500 (val F1=0.1052)
  Directional -> Accuracy: 0.5000, MCC: 0.0524, F1: 0.5217

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62157 | val 0.70193
  Epoch 012 - train 0.59585 | val 0.77271
  Classification -> best τ=0.465 (val F1=0.3781)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56565 | val 1.05889
  Epoch 011 - train 0.56139 | val 2.00241
  Classification -> best τ=0.555 (val F1=0.1240)
  Directional -> Accuracy: 0.5429, MCC: 0.0512, F1: 0.4286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58058 | val 0.93889
  Epoch 011 - train 0.57452 | val 2.65801
  Classification -> best τ=0.530 (val F1=0.3869)
  Directional -> Accuracy: 0.5600, MCC: 0.0898, F1: 0.3125

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55621 | val 2.05563
  Epoch 011 - train 0.56753 | val 2.45342
  Classification -> best τ=0.280 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58869 | val 3.55001
  Epoch 012 - train 0.51661 | val 3.40030
  Classification -> best τ=0.415 (val F1=0.2940)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60186 | val 0.85730
  Epoch 013 - train 0.67720 | val 0.64886
  Classification -> best τ=0.290 (val F1=0.3336)
  Directional -> Accuracy: 0.5738, MCC: 0.1731, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60059 | val 0.85294
  Epoch 018 - train 0.50945 | val 1.36668
  Classification -> best τ=0.490 (val F1=0.2693)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55739 | val 1.61006
  Epoch 011 - train 0.54640 | val 1.43295
  Classification -> best τ=0.485 (val F1=0.2997)
  Directional -> Accuracy: 0.6714, MCC: 0.3917, F1: 0.7629

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66839 | val 1.01452
  Epoch 011 - train 0.69383 | val 0.91633
  Classification -> best τ=0.405 (val F1=0.3015)
  Directional -> Accuracy: 0.3559, MCC: -0.3531, F1: 0.4722

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64221 | val 2.02454
  Epoch 011 - train 0.58519 | val 3.50328
  Classification -> best τ=0.185 (val F1=0.1512)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65178 | val 1.20746
  Epoch 013 - train 0.56173 | val 2.33721
  Classification -> best τ=0.595 (val F1=0.1348)
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64481 | val 0.72221
  Epoch 020 - train 0.52267 | val 6.67147
  Epoch 022 - train 0.49644 | val 8.79798
  Classification -> best τ=0.545 (val F1=0.2385)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61559 | val 0.80625
  Epoch 013 - train 0.55059 | val 0.82625
  Classification -> best τ=0.425 (val F1=0.2174)
  Directional -> Accuracy: 0.6042, MCC: 0.2046, F1: 0.6545

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66926 | val 1.26299
  Epoch 013 - train 0.66366 | val 0.98348
  Classification -> best τ=0.475 (val F1=0.2093)
  Directional -> Accuracy: 0.4394, MCC: -0.1226, F1: 0.3934

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71406 | val 0.76618
  Epoch 012 - train 0.69822 | val 0.73285
  Classification -> best τ=0.505 (val F1=0.2743)
  Directional -> Accuracy: 0.4483, MCC: -0.0861, F1: 0.4483

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57317 | val 20.54359
  Epoch 012 - train 0.60761 | val 2.50198
  Classification -> best τ=0.535 (val F1=0.2319)
  Directional -> Accuracy: 0.5152, MCC: 0.0304, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57519 | val 1.29577
  Epoch 018 - train 0.43962 | val 1.14391
  Classification -> best τ=0.535 (val F1=0.4795)
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52704 | val 1.79720
  Epoch 011 - train 0.48840 | val 2.05508
  Classification -> best τ=0.420 (val F1=0.1925)
  Directional -> Accuracy: 0.5435, MCC: 0.3063, F1: 0.6557

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61335 | val 0.82290
  Epoch 020 - train 0.69924 | val 0.96747
  Epoch 021 - train 0.58982 | val 1.03337
  Classification -> best τ=0.545 (val F1=0.3177)
  Directional -> Accuracy: 0.5349, MCC: 0.0593, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63762 | val 1.75107
  Epoch 011 - train 0.61617 | val 0.80934
  Classification -> best τ=0.575 (val F1=0.1939)
  Directional -> Accuracy: 0.5614, MCC: 0.1505, F1: 0.5455

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60743 | val 0.82052
  Epoch 016 - train 0.45847 | val 0.86378
  Classification -> best τ=0.485 (val F1=0.2942)
  Directional -> Accuracy: 0.4878, MCC: -0.0191, F1: 0.4878

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54050 | val 2.94485
  Epoch 013 - train 0.52016 | val 4.95574
  Classification -> best τ=0.610 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.1508, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69664 | val 0.63105
  Epoch 020 - train 0.64742 | val 0.61980
  Epoch 022 - train 0.67353 | val 0.68943
  Classification -> best τ=0.705 (val F1=0.1167)
  Directional -> Accuracy: 0.4651, MCC: -0.0154, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61649 | val 1.18352
  Epoch 011 - train 0.59163 | val 0.90461
  Classification -> best τ=0.330 (val F1=0.2680)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56543 | val 2.14003
  Epoch 012 - train 0.56806 | val 1.16651
  Classification -> best τ=0.415 (val F1=0.3773)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47286 | val 1.33578
  Epoch 020 - train 0.22942 | val 5.81944
  Epoch 021 - train 0.25713 | val 5.25717
  Classification -> best τ=0.640 (val F1=0.4714)
  Directional -> Accuracy: 0.5526, MCC: 0.1195, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49952 | val 1.35304
  Epoch 011 - train 0.47692 | val 1.91875
  Classification -> best τ=0.405 (val F1=0.2920)
  Directional -> Accuracy: 0.4545, MCC: -0.0788, F1: 0.5556

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56724 | val 0.86275
  Epoch 011 - train 0.56767 | val 0.80438
  Classification -> best τ=0.520 (val F1=0.1978)
  Directional -> Accuracy: 0.4179, MCC: -0.1007, F1: 0.2041

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51967 | val 1.36261
  Epoch 015 - train 0.41564 | val 1.21134
  Classification -> best τ=0.535 (val F1=0.1846)
  Directional -> Accuracy: 0.6047, MCC: 0.2529, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56430 | val 0.73874
  Epoch 014 - train 0.53341 | val 1.03420
  Classification -> best τ=0.375 (val F1=0.2382)
  Directional -> Accuracy: 0.5439, MCC: 0.1605, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57117 | val 1.10181
  Epoch 013 - train 0.54088 | val 0.88442
  Classification -> best τ=0.190 (val F1=0.2915)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57732 | val 1.23981
  Epoch 017 - train 0.45373 | val 0.71692
  Classification -> best τ=0.700 (val F1=0.3482)
  Directional -> Accuracy: 0.4082, MCC: -0.0343, F1: 0.4912

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.46321 | val 4.04179
  Epoch 011 - train 0.39984 | val 4.44677
  Classification -> best τ=0.585 (val F1=0.0134)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67662 | val 0.76065
  Epoch 020 - train 0.60480 | val 3.02600
  Epoch 024 - train 0.49503 | val 2.64224
  Classification -> best τ=0.600 (val F1=0.3289)
  Directional -> Accuracy: 0.5067, MCC: 0.0499, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50539 | val 1.15955
  Epoch 011 - train 0.47556 | val 1.57006
  Classification -> best τ=0.590 (val F1=0.2593)
  Directional -> Accuracy: 0.4681, MCC: -0.1036, F1: 0.6032

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68095 | val 1.17156
  Epoch 013 - train 0.49700 | val 1.52998
  Classification -> best τ=0.390 (val F1=0.3550)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60225 | val 1.73454
  Epoch 011 - train 0.53393 | val 0.77908
  Classification -> best τ=0.555 (val F1=0.6172)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60835 | val 0.76819
  Epoch 015 - train 0.64290 | val 0.78910
  Classification -> best τ=0.715 (val F1=0.1914)
  Directional -> Accuracy: 0.4286, MCC: -0.1260, F1: 0.3333

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60537 | val 2.17585
  Epoch 012 - train 0.58349 | val 1.45703
  Classification -> best τ=0.655 (val F1=0.3735)
  Directional -> Accuracy: 0.4737, MCC: -0.1078, F1: 0.2105

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58229 | val 1.74625
  Epoch 020 - train 0.53441 | val 0.73992
  Epoch 021 - train 0.51023 | val 5.21059
  Classification -> best τ=0.465 (val F1=0.3787)
  Directional -> Accuracy: 0.4815, MCC: -0.0889, F1: 0.6216

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59178 | val 1.14111
  Epoch 014 - train 0.58364 | val 7.82137
  Classification -> best τ=0.585 (val F1=0.1250)
  Directional -> Accuracy: 0.4821, MCC: -0.0766, F1: 0.6133

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64290 | val 1.25003

[I 2026-02-20 03:28:32,824] Trial 118 finished with value: 0.2756254394670037 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008040577848671647, 'weight_decay': 5.618415785983566e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6995407376613904, 'early_stopping_min_delta': 0.007415857486348726}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.59146 | val 1.83686
  Classification -> best τ=0.445 (val F1=0.3586)
  Directional -> Accuracy: 0.5410, MCC: 0.0864, F1: 0.5484

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2756254394670037
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69638 | val 1.09155
  Epoch 013 - train 0.63144 | val 0.78729
  Classification -> best τ=0.420 (val F1=0.0627)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57451 | val 1.23110
  Epoch 013 - train 0.53777 | val 1.51154
  Classification -> best τ=0.405 (val F1=0.0604)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63094 | val 0.69587
  Epoch 013 - train 0.60307 | val 0.72930
  Classification -> best τ=0.565 (val F1=0.4547)
  Directional -> Accuracy: 0.5532, MCC: 0.0872, F1: 0.6441

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66141 | val 0.79058
  Epoch 011 - train 0.65688 | val 1.03574
  Classification -> best τ=0.365 (val F1=0.1475)
  Directional -> Accuracy: 0.4800, MCC: 0.0100, F1: 0.3390

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51783 | val 1.91372
  Epoch 011 - train 0.56550 | val 1.17967
  Classification -> best τ=0.555 (val F1=0.3795)
  Directional -> Accuracy: 0.4314, MCC: -0.1253, F1: 0.2564

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61404 | val 0.78551
  Epoch 013 - train 0.62193 | val 0.71198
  Classification -> best τ=0.485 (val F1=0.3273)
  Directional -> Accuracy: 0.6170, MCC: 0.2428, F1: 0.5263

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65168 | val 0.76236
  Epoch 011 - train 0.64554 | val 0.90592
  Classification -> best τ=0.600 (val F1=0.1239)
  Directional -> Accuracy: 0.5217, MCC: 0.0249, F1: 0.4407

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57516 | val 0.85915
  Epoch 011 - train 0.49936 | val 0.83857
  Classification -> best τ=0.620 (val F1=0.3236)
  Directional -> Accuracy: 0.5227, MCC: 0.0906, F1: 0.5333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62320 | val 0.88088
  Epoch 012 - train 0.58487 | val 1.04940
  Classification -> best τ=0.410 (val F1=0.1945)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61640 | val 0.84642
  Epoch 011 - train 0.62031 | val 1.29952
  Classification -> best τ=0.495 (val F1=0.2853)
  Directional -> Accuracy: 0.4429, MCC: 0.0160, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60148 | val 1.53077
  Epoch 013 - train 0.59478 | val 1.57422
  Classification -> best τ=0.470 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58343 | val 1.07337
  Epoch 011 - train 0.60804 | val 1.31032
  Classification -> best τ=0.390 (val F1=0.1635)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57225 | val 0.87491
  Epoch 011 - train 0.57492 | val 1.06157
  Classification -> best τ=0.525 (val F1=0.2004)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65930 | val 0.78011
  Epoch 014 - train 0.59866 | val 0.63812
  Classification -> best τ=0.340 (val F1=0.3212)
  Directional -> Accuracy: 0.5574, MCC: 0.1236, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60342 | val 1.26441
  Epoch 011 - train 0.57888 | val 1.63919
  Classification -> best τ=0.575 (val F1=0.3475)
  Directional -> Accuracy: 0.5577, MCC: 0.0949, F1: 0.4390

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63735 | val 0.82668
  Epoch 011 - train 0.62462 | val 0.81848
  Classification -> best τ=0.430 (val F1=0.2834)
  Directional -> Accuracy: 0.5857, MCC: 0.1721, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61596 | val 1.28612
  Epoch 011 - train 0.63590 | val 0.91014
  Classification -> best τ=0.470 (val F1=0.2596)
  Directional -> Accuracy: 0.5085, MCC: -0.2297, F1: 0.6667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68452 | val 0.73961
  Epoch 014 - train 0.66494 | val 0.84524
  Classification -> best τ=0.405 (val F1=0.1917)
  Directional -> Accuracy: 0.5526, MCC: 0.1704, F1: 0.5405

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67757 | val 0.71273
  Epoch 012 - train 0.62781 | val 0.69029
  Classification -> best τ=0.715 (val F1=0.1822)
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64118 | val 0.77185
  Epoch 011 - train 0.61691 | val 1.10411
  Classification -> best τ=0.635 (val F1=0.2906)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56087 | val 2.32518
  Epoch 012 - train 0.56202 | val 1.94207
  Classification -> best τ=0.505 (val F1=0.2477)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66005 | val 0.80914
  Epoch 011 - train 0.66632 | val 1.10839
  Classification -> best τ=0.565 (val F1=0.2086)
  Directional -> Accuracy: 0.5152, MCC: 0.1240, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65827 | val 0.86718
  Epoch 014 - train 0.60019 | val 1.31321
  Classification -> best τ=0.585 (val F1=0.3187)
  Directional -> Accuracy: 0.5172, MCC: 0.1165, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66756 | val 0.89202
  Epoch 011 - train 0.67579 | val 0.79738
  Classification -> best τ=0.465 (val F1=0.2319)
  Directional -> Accuracy: 0.5000, MCC: -0.0260, F1: 0.3529

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61356 | val 0.68192
  Epoch 019 - train 0.61833 | val 0.78293
  Classification -> best τ=0.305 (val F1=0.4082)
  Directional -> Accuracy: 0.6429, MCC: 0.2725, F1: 0.6875

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59159 | val 0.99177
  Epoch 011 - train 0.59060 | val 1.04890
  Classification -> best τ=0.430 (val F1=0.1925)
  Directional -> Accuracy: 0.5435, MCC: 0.2115, F1: 0.6316

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66430 | val 0.67624
  Epoch 020 - train 0.61344 | val 0.73072
  Epoch 025 - train 0.54395 | val 1.91395
  Classification -> best τ=0.585 (val F1=0.4057)
  Directional -> Accuracy: 0.4651, MCC: -0.0295, F1: 0.4390

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62641 | val 1.54719
  Epoch 014 - train 0.54901 | val 1.24886
  Classification -> best τ=0.400 (val F1=0.1083)
  Directional -> Accuracy: 0.4737, MCC: -0.1888, F1: 0.6250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53607 | val 0.78184
  Epoch 011 - train 0.52705 | val 0.72719
  Classification -> best τ=0.520 (val F1=0.2774)
  Directional -> Accuracy: 0.4878, MCC: -0.0263, F1: 0.5116

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55751 | val 3.87344
  Epoch 012 - train 0.45410 | val 5.59135
  Classification -> best τ=0.660 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61772 | val 0.77386
  Epoch 016 - train 0.44963 | val 1.03364
  Classification -> best τ=0.735 (val F1=0.1654)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60853 | val 1.01212
  Epoch 012 - train 0.52185 | val 1.08232
  Classification -> best τ=0.450 (val F1=0.2941)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66107 | val 0.72193
  Epoch 012 - train 0.64525 | val 0.68955
  Classification -> best τ=0.470 (val F1=0.2952)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52981 | val 0.96463
  Epoch 011 - train 0.50254 | val 1.00672
  Classification -> best τ=0.445 (val F1=0.2182)
  Directional -> Accuracy: 0.5263, MCC: 0.0580, F1: 0.6087

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58025 | val 0.79426
  Epoch 011 - train 0.63046 | val 0.77748
  Classification -> best τ=0.465 (val F1=0.3283)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62641 | val 0.81399
  Epoch 014 - train 0.56858 | val 0.71247
  Classification -> best τ=0.290 (val F1=0.2999)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57518 | val 0.81426
  Epoch 016 - train 0.40372 | val 0.85579
  Classification -> best τ=0.415 (val F1=0.3264)
  Directional -> Accuracy: 0.6744, MCC: 0.3671, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61088 | val 1.35631
  Epoch 012 - train 0.56962 | val 2.67414
  Classification -> best τ=0.465 (val F1=0.1803)
  Directional -> Accuracy: 0.4737, MCC: -0.0101, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57649 | val 0.72946
  Epoch 014 - train 0.44016 | val 0.81370
  Classification -> best τ=0.505 (val F1=0.2459)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69935 | val 0.66407
  Epoch 019 - train 0.55828 | val 0.77195
  Classification -> best τ=0.395 (val F1=0.4708)
  Directional -> Accuracy: 0.3469, MCC: -0.1852, F1: 0.4483

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52174 | val 1.05979
  Epoch 011 - train 0.52929 | val 1.21547
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64856 | val 0.72447
  Epoch 020 - train 0.60957 | val 0.87504
  Epoch 024 - train 0.58049 | val 0.90887
  Classification -> best τ=0.535 (val F1=0.3496)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64906 | val 0.75826
  Epoch 011 - train 0.62272 | val 0.73968
  Classification -> best τ=0.465 (val F1=0.2470)
  Directional -> Accuracy: 0.5745, MCC: 0.2144, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57475 | val 0.88026
  Epoch 011 - train 0.54017 | val 0.86313
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63304 | val 0.77624
  Epoch 016 - train 0.63099 | val 1.12162
  Classification -> best τ=0.570 (val F1=0.5547)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62273 | val 0.69838
  Epoch 011 - train 0.62715 | val 0.71297
  Classification -> best τ=0.620 (val F1=0.2524)
  Directional -> Accuracy: 0.4464, MCC: -0.1049, F1: 0.4561

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59878 | val 0.76199
  Epoch 012 - train 0.58850 | val 0.74504
  Classification -> best τ=0.415 (val F1=0.2530)
  Directional -> Accuracy: 0.5263, MCC: 0.0808, F1: 0.5970

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65410 | val 0.69221
  Epoch 019 - train 0.58588 | val 0.82592
  Classification -> best τ=0.525 (val F1=0.3807)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65044 | val 0.91945
  Epoch 011 - train 0.62036 | val 1.90916
  Classification -> best τ=0.500 (val F1=0.1145)
  Directional -> Accuracy: 0.4464, MCC: -0.1995, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64644 | val 0.72147

[I 2026-02-20 03:29:39,448] Trial 119 finished with value: 0.25606964498092655 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.007775246769400176, 'weight_decay': 1.2063990723291863e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6783025688462951, 'early_stopping_min_delta': 0.007392179795089497}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 017 - train 0.57925 | val 1.19554
  Classification -> best τ=0.440 (val F1=0.3103)
  Directional -> Accuracy: 0.5410, MCC: 0.1293, F1: 0.6316

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25606964498092655
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60559 | val 1.47751
  Epoch 013 - train 0.59120 | val 2.80706
  Classification -> best τ=0.640 (val F1=0.2453)
  Directional -> Accuracy: 0.5065, MCC: -0.0745, F1: 0.1739

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55170 | val 0.95282
  Epoch 011 - train 0.55622 | val 1.09976
  Classification -> best τ=0.510 (val F1=0.2722)
  Directional -> Accuracy: 0.6522, MCC: 0.2820, F1: 0.7419

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54784 | val 1.04925
  Epoch 011 - train 0.63173 | val 0.93527
  Classification -> best τ=0.510 (val F1=0.3296)
  Directional -> Accuracy: 0.4255, MCC: -0.1988, F1: 0.5424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62288 | val 2.27742
  Epoch 011 - train 0.61965 | val 2.63024
  Classification -> best τ=0.455 (val F1=0.2163)
  Directional -> Accuracy: 0.5067, MCC: 0.0727, F1: 0.3729

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50341 | val 1.14828
  Epoch 011 - train 0.49199 | val 1.46933
  Classification -> best τ=0.505 (val F1=0.4255)
  Directional -> Accuracy: 0.7451, MCC: 0.5302, F1: 0.8000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38863 | val 5.36742
  Epoch 011 - train 0.38516 | val 3.30004
  Classification -> best τ=0.580 (val F1=0.2335)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63893 | val 1.50770
  Epoch 011 - train 0.59137 | val 1.27088
  Classification -> best τ=0.435 (val F1=0.1667)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58963 | val 3.09142
  Epoch 015 - train 0.43706 | val 4.40713
  Classification -> best τ=0.165 (val F1=0.1214)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56982 | val 1.70898
  Epoch 011 - train 0.53770 | val 1.36287
  Classification -> best τ=0.475 (val F1=0.3781)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55472 | val 0.77289
  Epoch 011 - train 0.60588 | val 0.72483
  Classification -> best τ=0.550 (val F1=0.0141)
  Directional -> Accuracy: 0.4714, MCC: -0.0335, F1: 0.4789

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55486 | val 2.64758
  Epoch 011 - train 0.52742 | val 3.44761
  Classification -> best τ=0.550 (val F1=0.0490)
  Directional -> Accuracy: 0.4400, MCC: -0.0963, F1: 0.5172

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56972 | val 1.86284
  Epoch 011 - train 0.58620 | val 2.83068
  Classification -> best τ=0.235 (val F1=0.2172)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64540 | val 1.77524
  Epoch 012 - train 0.51727 | val 2.45516
  Classification -> best τ=0.395 (val F1=0.2504)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60553 | val 0.70104
  Epoch 013 - train 0.54333 | val 0.75317
  Classification -> best τ=0.315 (val F1=0.3134)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59389 | val 0.77527
  Epoch 013 - train 0.49455 | val 1.17657
  Classification -> best τ=0.565 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54373 | val 1.25175
  Epoch 011 - train 0.51065 | val 1.27912
  Classification -> best τ=0.380 (val F1=0.2039)
  Directional -> Accuracy: 0.5143, MCC: -0.1024, F1: 0.6731

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56627 | val 0.81353
  Epoch 013 - train 0.48701 | val 0.90120
  Classification -> best τ=0.600 (val F1=0.0603)
  Directional -> Accuracy: 0.4407, MCC: -0.0219, F1: 0.4000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57632 | val 2.21612
  Epoch 011 - train 0.62785 | val 2.27054
  Classification -> best τ=0.665 (val F1=0.1560)
  Directional -> Accuracy: 0.3947, MCC: -0.0933, F1: 0.2069

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64154 | val 1.17679
  Epoch 011 - train 0.62503 | val 1.05555
  Classification -> best τ=0.435 (val F1=0.1715)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56538 | val 1.35740
  Epoch 013 - train 0.49713 | val 1.06404
  Classification -> best τ=0.480 (val F1=0.2756)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56404 | val 0.93297
  Epoch 018 - train 0.35442 | val 3.11660
  Classification -> best τ=0.330 (val F1=0.3555)
  Directional -> Accuracy: 0.4583, MCC: 0.1627, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58187 | val 1.76875
  Epoch 011 - train 0.59405 | val 2.38641
  Classification -> best τ=0.515 (val F1=0.3242)
  Directional -> Accuracy: 0.5303, MCC: 0.0845, F1: 0.6517

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60451 | val 2.58016
  Epoch 011 - train 0.55622 | val 2.97555
  Classification -> best τ=0.575 (val F1=0.3282)
  Directional -> Accuracy: 0.4828, MCC: -0.0253, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63009 | val 1.13677
  Epoch 016 - train 0.54932 | val 1.07294
  Classification -> best τ=0.525 (val F1=0.1493)
  Directional -> Accuracy: 0.5455, MCC: 0.1482, F1: 0.6341

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61903 | val 0.68889
  Epoch 013 - train 0.52701 | val 0.79153
  Classification -> best τ=0.560 (val F1=0.3629)
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41295 | val 1.48324
  Epoch 011 - train 0.49796 | val 0.92628
  Classification -> best τ=0.460 (val F1=0.1741)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57906 | val 1.06466
  Epoch 012 - train 0.50823 | val 0.71412
  Classification -> best τ=0.505 (val F1=0.1872)
  Directional -> Accuracy: 0.5116, MCC: 0.1323, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58556 | val 0.92447
  Epoch 011 - train 0.57852 | val 0.92965
  Classification -> best τ=0.455 (val F1=0.2225)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57335 | val 0.80549
  Epoch 018 - train 0.42272 | val 0.71166
  Classification -> best τ=0.545 (val F1=0.3158)
  Directional -> Accuracy: 0.6585, MCC: 0.3096, F1: 0.7083

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43015 | val 2.39955
  Epoch 011 - train 0.47269 | val 1.88206
  Classification -> best τ=0.535 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49587 | val 1.96159
  Epoch 014 - train 0.40838 | val 1.82238
  Classification -> best τ=0.495 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50871 | val 1.41878
  Epoch 011 - train 0.50338 | val 1.85701
  Classification -> best τ=0.490 (val F1=0.3115)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56479 | val 0.69706
  Epoch 012 - train 0.52367 | val 0.90981
  Classification -> best τ=0.435 (val F1=0.2654)
  Directional -> Accuracy: 0.5616, MCC: 0.2443, F1: 0.4286

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42184 | val 2.25344
  Epoch 011 - train 0.37823 | val 1.62866
  Classification -> best τ=0.435 (val F1=0.1890)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52725 | val 1.14483
  Epoch 011 - train 0.53449 | val 1.26019
  Classification -> best τ=0.460 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54438 | val 0.90407
  Epoch 011 - train 0.57981 | val 0.97727
  Classification -> best τ=0.360 (val F1=0.3767)
  Directional -> Accuracy: 0.5373, MCC: -0.0044, F1: 0.6593

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50992 | val 0.92466
  Epoch 018 - train 0.38805 | val 1.65225
  Classification -> best τ=0.375 (val F1=0.3499)
  Directional -> Accuracy: 0.6744, MCC: 0.3810, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55946 | val 1.81804
  Epoch 011 - train 0.48020 | val 2.73075
  Classification -> best τ=0.370 (val F1=0.2487)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46731 | val 0.84201
  Epoch 011 - train 0.37687 | val 0.85011
  Classification -> best τ=0.540 (val F1=0.2722)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50535 | val 1.09043
  Epoch 013 - train 0.46202 | val 1.09071
  Classification -> best τ=0.500 (val F1=0.4345)
  Directional -> Accuracy: 0.5510, MCC: 0.0562, F1: 0.4211

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38549 | val 3.01470
  Epoch 011 - train 0.41225 | val 3.40955
  Classification -> best τ=0.505 (val F1=0.2041)
  Directional -> Accuracy: 0.6053, MCC: 0.2064, F1: 0.6341

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56476 | val 1.57090
  Epoch 012 - train 0.53069 | val 1.75972
  Classification -> best τ=0.325 (val F1=0.3844)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48581 | val 0.98785
  Epoch 011 - train 0.42308 | val 1.27336
  Classification -> best τ=0.505 (val F1=0.2593)
  Directional -> Accuracy: 0.4681, MCC: -0.0644, F1: 0.2424

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45065 | val 1.43029
  Epoch 011 - train 0.43221 | val 1.27299
  Classification -> best τ=0.500 (val F1=0.2100)
  Directional -> Accuracy: 0.6136, MCC: 0.1925, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49634 | val 2.09476
  Epoch 012 - train 0.46300 | val 1.74809
  Classification -> best τ=0.535 (val F1=0.1387)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62110 | val 0.91290
  Epoch 014 - train 0.60155 | val 0.97712
  Classification -> best τ=0.420 (val F1=0.2985)
  Directional -> Accuracy: 0.6071, MCC: 0.2339, F1: 0.7179

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51720 | val 1.14452
  Epoch 011 - train 0.50059 | val 1.60004
  Classification -> best τ=0.530 (val F1=0.3538)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63238 | val 0.80639
  Epoch 013 - train 0.66078 | val 1.32254
  Classification -> best τ=0.610 (val F1=0.3639)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57428 | val 0.70804
  Epoch 012 - train 0.51989 | val 0.82428
  Classification -> best τ=0.495 (val F1=0.1900)
  Directional -> Accuracy: 0.5179, MCC: 0.0167, F1: 0.6400

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62852 | val 0.99013

[I 2026-02-20 03:31:12,047] Trial 120 finished with value: 0.25398680386770234 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.003146724814187517, 'weight_decay': 5.929562332837961e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.46256344637543023, 'early_stopping_min_delta': 0.008544375533840992}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.53215 | val 0.75823
  Classification -> best τ=0.435 (val F1=0.2626)
  Directional -> Accuracy: 0.5082, MCC: -0.0196, F1: 0.2500

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25398680386770234
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63236 | val 1.71901
  Epoch 011 - train 0.62725 | val 1.49838
  Classification -> best τ=0.410 (val F1=0.0942)
  Directional -> Accuracy: 0.4545, MCC: -0.0149, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54316 | val 1.15184
  Epoch 011 - train 0.57679 | val 2.22619
  Classification -> best τ=0.480 (val F1=0.2389)
  Directional -> Accuracy: 0.4565, MCC: -0.0766, F1: 0.4681

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62257 | val 1.07096
  Epoch 011 - train 0.58733 | val 0.88092
  Classification -> best τ=0.385 (val F1=0.3740)
  Directional -> Accuracy: 0.5745, MCC: 0.2247, F1: 0.7143

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67565 | val 0.76186
  Epoch 011 - train 0.68023 | val 0.90898
  Classification -> best τ=0.440 (val F1=0.2086)
  Directional -> Accuracy: 0.6000, MCC: 0.2021, F1: 0.6154

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56107 | val 1.36520
  Epoch 015 - train 0.47734 | val 3.39636
  Classification -> best τ=0.525 (val F1=0.5632)
  Directional -> Accuracy: 0.6863, MCC: 0.4015, F1: 0.6522

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61374 | val 2.40158
  Epoch 012 - train 0.53641 | val 3.33401
  Classification -> best τ=0.550 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67863 | val 0.74006
  Epoch 014 - train 0.66301 | val 0.73584
  Classification -> best τ=0.435 (val F1=0.3344)
  Directional -> Accuracy: 0.4493, MCC: 0.0062, F1: 0.5366

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53308 | val 2.79803
  Epoch 015 - train 0.36153 | val 6.23833
  Classification -> best τ=0.505 (val F1=0.3295)
  Directional -> Accuracy: 0.4318, MCC: 0.1269, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55277 | val 4.13387
  Epoch 011 - train 0.58161 | val 3.81130
  Classification -> best τ=0.270 (val F1=0.2408)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63656 | val 0.85494
  Epoch 011 - train 0.65003 | val 0.80586
  Classification -> best τ=0.565 (val F1=0.1374)
  Directional -> Accuracy: 0.5000, MCC: -0.0339, F1: 0.3860

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62071 | val 1.35989
  Epoch 011 - train 0.57668 | val 3.04998
  Classification -> best τ=0.420 (val F1=0.0891)
  Directional -> Accuracy: 0.5000, MCC: -0.0310, F1: 0.3590

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62072 | val 6.58115
  Epoch 011 - train 0.59927 | val 5.74080
  Classification -> best τ=0.185 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58623 | val 3.18064
  Epoch 012 - train 0.56601 | val 1.97873
  Classification -> best τ=0.525 (val F1=0.3221)
  Directional -> Accuracy: 0.5116, MCC: 0.0044, F1: 0.4324

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64749 | val 0.64908
  Epoch 018 - train 0.74450 | val 0.62902
  Classification -> best τ=0.310 (val F1=0.2928)
  Directional -> Accuracy: 0.5738, MCC: 0.1844, F1: 0.6829

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69472 | val 0.69759
  Epoch 014 - train 0.67869 | val 0.86310
  Classification -> best τ=0.540 (val F1=0.3169)
  Directional -> Accuracy: 0.5962, MCC: 0.2673, F1: 0.2222

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60743 | val 1.79456
  Epoch 011 - train 0.54942 | val 2.20097
  Classification -> best τ=0.735 (val F1=0.1539)
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69042 | val 0.73654
  Epoch 011 - train 0.64948 | val 0.88380
  Classification -> best τ=0.320 (val F1=0.3333)
  Directional -> Accuracy: 0.3390, MCC: -0.3200, F1: 0.4000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63009 | val 1.13537
  Epoch 011 - train 0.62948 | val 0.87011
  Classification -> best τ=0.505 (val F1=0.2110)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65499 | val 0.74754
  Epoch 016 - train 0.58071 | val 1.44916
  Classification -> best τ=0.570 (val F1=0.1279)
  Directional -> Accuracy: 0.4615, MCC: 0.0668, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64665 | val 0.97444
  Epoch 012 - train 0.63999 | val 0.96621
  Classification -> best τ=0.485 (val F1=0.2656)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59223 | val 0.71514
  Epoch 011 - train 0.54447 | val 0.99100
  Classification -> best τ=0.585 (val F1=0.3544)
  Directional -> Accuracy: 0.4792, MCC: -0.1816, F1: 0.6154

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66898 | val 0.77138
  Epoch 012 - train 0.61514 | val 1.41845
  Classification -> best τ=0.515 (val F1=0.2411)
  Directional -> Accuracy: 0.5152, MCC: 0.0304, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69743 | val 1.27825
  Epoch 011 - train 0.65289 | val 1.05726
  Classification -> best τ=0.640 (val F1=0.1280)
  Directional -> Accuracy: 0.3621, MCC: -0.3127, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66231 | val 0.85684
  Epoch 013 - train 0.66424 | val 1.11921
  Classification -> best τ=0.605 (val F1=0.1878)
  Directional -> Accuracy: 0.5455, MCC: 0.0747, F1: 0.1667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63726 | val 0.66843
  Epoch 017 - train 0.61173 | val 0.94539
  Classification -> best τ=0.520 (val F1=0.4352)
  Directional -> Accuracy: 0.5357, MCC: 0.0839, F1: 0.5357

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50707 | val 2.36580
  Epoch 011 - train 0.44574 | val 3.40962
  Classification -> best τ=0.450 (val F1=0.0933)
  Directional -> Accuracy: 0.5217, MCC: 0.2095, F1: 0.6333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66816 | val 0.81511
  Epoch 014 - train 0.60654 | val 0.93173
  Classification -> best τ=0.615 (val F1=0.1872)
  Directional -> Accuracy: 0.4186, MCC: -0.1027, F1: 0.3243

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63154 | val 1.22007
  Epoch 014 - train 0.56239 | val 1.16281
  Classification -> best τ=0.365 (val F1=0.1264)
  Directional -> Accuracy: 0.5263, MCC: 0.0339, F1: 0.5846

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63384 | val 0.95463
  Epoch 011 - train 0.54241 | val 0.90905
  Classification -> best τ=0.575 (val F1=0.2833)
  Directional -> Accuracy: 0.5122, MCC: 0.1407, F1: 0.2308

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50605 | val 18.30394
  Epoch 011 - train 0.47588 | val 23.04930
  Classification -> best τ=0.620 (val F1=0.2683)
  Directional -> Accuracy: 0.5349, MCC: 0.1579, F1: 0.0909

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61168 | val 1.67081
  Epoch 014 - train 0.51866 | val 1.46938
  Classification -> best τ=0.730 (val F1=0.0296)
  Directional -> Accuracy: 0.4186, MCC: -0.2261, F1: 0.5455

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59458 | val 1.56588
  Epoch 012 - train 0.54776 | val 1.34647
  Classification -> best τ=0.235 (val F1=0.3453)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61957 | val 0.66129
  Epoch 015 - train 0.56099 | val 0.90332
  Classification -> best τ=0.335 (val F1=0.3832)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54970 | val 2.09414
  Epoch 011 - train 0.62262 | val 2.04963
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61702 | val 0.76985
  Epoch 017 - train 0.54984 | val 0.86036
  Classification -> best τ=0.620 (val F1=0.2031)
  Directional -> Accuracy: 0.5000, MCC: -0.0554, F1: 0.1538

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62287 | val 0.77995
  Epoch 016 - train 0.61685 | val 0.70380
  Classification -> best τ=0.345 (val F1=0.3431)
  Directional -> Accuracy: 0.5821, MCC: 0.2129, F1: 0.5484

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55167 | val 1.47885
  Epoch 013 - train 0.45292 | val 1.41640
  Classification -> best τ=0.610 (val F1=0.2740)
  Directional -> Accuracy: 0.5349, MCC: 0.1527, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55040 | val 2.04302
  Epoch 012 - train 0.49466 | val 2.86320
  Classification -> best τ=0.410 (val F1=0.2282)
  Directional -> Accuracy: 0.4561, MCC: -0.0705, F1: 0.5634

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55414 | val 1.28049
  Epoch 012 - train 0.49677 | val 1.69586
  Classification -> best τ=0.205 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61294 | val 0.67802
  Epoch 020 - train 0.46123 | val 0.74107
  Epoch 021 - train 0.44835 | val 0.81131
  Classification -> best τ=0.685 (val F1=0.4345)
  Directional -> Accuracy: 0.4286, MCC: 0.0335, F1: 0.5172

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54341 | val 3.97202
  Epoch 011 - train 0.55754 | val 3.55515
  Classification -> best τ=0.605 (val F1=0.3223)
  Directional -> Accuracy: 0.4211, MCC: -0.2485, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60634 | val 2.49343
  Epoch 012 - train 0.57184 | val 2.14787
  Classification -> best τ=0.315 (val F1=0.4607)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54045 | val 2.04450
  Epoch 012 - train 0.53400 | val 1.21272
  Classification -> best τ=0.520 (val F1=0.3669)
  Directional -> Accuracy: 0.4468, MCC: -0.1357, F1: 0.1333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58803 | val 1.32516
  Epoch 011 - train 0.61141 | val 1.98788
  Classification -> best τ=0.650 (val F1=0.3967)
  Directional -> Accuracy: 0.4545, MCC: 0.1329, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63207 | val 0.70788
  Epoch 012 - train 0.54699 | val 1.06653
  Classification -> best τ=0.735 (val F1=0.5657)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65755 | val 0.82050
  Epoch 016 - train 0.58405 | val 1.17689
  Classification -> best τ=0.550 (val F1=0.1382)
  Directional -> Accuracy: 0.3571, MCC: -0.3510, F1: 0.4857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64102 | val 1.04513
  Epoch 017 - train 0.54377 | val 1.01138
  Classification -> best τ=0.475 (val F1=0.3119)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60188 | val 4.17550
  Epoch 011 - train 0.66953 | val 2.38711
  Classification -> best τ=0.530 (val F1=0.0666)
  Directional -> Accuracy: 0.5185, MCC: 0.0131, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62122 | val 0.84751
  Epoch 011 - train 0.88807 | val 1.16597
  Classification -> best τ=0.470 (val F1=0.3000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67833 | val 2.44681
  Epoch 020 - train 0.63681 | val 0.96108

[I 2026-02-20 03:32:53,428] Trial 121 finished with value: 0.2607726793335764 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.008467187464141834, 'weight_decay': 8.59320244835892e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.596051196550462, 'early_stopping_min_delta': 0.008230914169960588}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 023 - train 0.62561 | val 1.75179
  Classification -> best τ=0.300 (val F1=0.2847)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2607726793335764
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58558 | val 2.40392
  Epoch 011 - train 0.57969 | val 2.88816
  Classification -> best τ=0.410 (val F1=0.1989)
  Directional -> Accuracy: 0.5584, MCC: 0.1289, F1: 0.5641

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59418 | val 0.91505
  Epoch 013 - train 0.51868 | val 0.97434
  Classification -> best τ=0.530 (val F1=0.0604)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58600 | val 0.94042
  Epoch 012 - train 0.60597 | val 0.88045
  Classification -> best τ=0.480 (val F1=0.5017)
  Directional -> Accuracy: 0.5957, MCC: 0.2064, F1: 0.7077

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60368 | val 3.33997
  Epoch 011 - train 0.60298 | val 0.92879
  Classification -> best τ=0.375 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57829 | val 2.88458
  Epoch 013 - train 0.52899 | val 4.67652
  Classification -> best τ=0.380 (val F1=0.4876)
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.7123

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59892 | val 0.77339
  Epoch 014 - train 0.42551 | val 3.78826
  Classification -> best τ=0.505 (val F1=0.3394)
  Directional -> Accuracy: 0.5532, MCC: 0.1126, F1: 0.5882

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69216 | val 0.74453
  Epoch 017 - train 0.61440 | val 1.16681
  Classification -> best τ=0.485 (val F1=0.2852)
  Directional -> Accuracy: 0.4203, MCC: 0.1002, F1: 0.5833

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54034 | val 2.46619
  Epoch 011 - train 0.50136 | val 2.58976
  Classification -> best τ=0.510 (val F1=0.3236)
  Directional -> Accuracy: 0.5682, MCC: 0.0691, F1: 0.3871

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60612 | val 0.75314
  Epoch 011 - train 0.59565 | val 0.69871
  Classification -> best τ=0.525 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56757 | val 0.89181
  Epoch 012 - train 0.59694 | val 0.84703
  Classification -> best τ=0.500 (val F1=0.1816)
  Directional -> Accuracy: 0.5143, MCC: 0.0083, F1: 0.4333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51605 | val 1.74257
  Epoch 012 - train 0.53504 | val 1.81385
  Classification -> best τ=0.415 (val F1=0.2778)
  Directional -> Accuracy: 0.5800, MCC: 0.1474, F1: 0.5116

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59742 | val 2.86889
  Epoch 013 - train 0.54152 | val 3.61011
  Classification -> best τ=0.405 (val F1=0.2213)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57680 | val 1.98195
  Epoch 014 - train 0.55413 | val 4.47765
  Classification -> best τ=0.540 (val F1=0.3295)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60271 | val 0.64730
  Epoch 013 - train 0.60260 | val 0.75696
  Classification -> best τ=0.210 (val F1=0.3454)
  Directional -> Accuracy: 0.5246, MCC: 0.0486, F1: 0.6329

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60874 | val 0.93051
  Epoch 012 - train 0.66221 | val 1.45058
  Classification -> best τ=0.545 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50024 | val 1.07389
  Epoch 011 - train 0.51852 | val 1.99968
  Classification -> best τ=0.540 (val F1=0.1125)
  Directional -> Accuracy: 0.4429, MCC: -0.0765, F1: 0.2041

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59437 | val 1.06876
  Epoch 011 - train 0.60581 | val 1.38601
  Classification -> best τ=0.405 (val F1=0.0405)
  Directional -> Accuracy: 0.6102, MCC: 0.0423, F1: 0.7416

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59813 | val 3.30777
  Epoch 011 - train 0.56118 | val 2.55386
  Classification -> best τ=0.650 (val F1=0.1800)
  Directional -> Accuracy: 0.4079, MCC: -0.1030, F1: 0.3284

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57711 | val 1.42747
  Epoch 011 - train 0.54805 | val 1.49720
  Classification -> best τ=0.550 (val F1=0.1715)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60172 | val 0.94199
  Epoch 011 - train 0.59093 | val 0.80149
  Classification -> best τ=0.520 (val F1=0.2369)
  Directional -> Accuracy: 0.3333, MCC: -0.3234, F1: 0.3056

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52102 | val 2.21727
  Epoch 011 - train 0.57799 | val 0.76060
  Classification -> best τ=0.600 (val F1=0.1399)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58433 | val 2.68559
  Epoch 012 - train 0.56815 | val 4.37131
  Classification -> best τ=0.520 (val F1=0.1318)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61211 | val 1.60438
  Epoch 015 - train 0.68638 | val 1.08299
  Classification -> best τ=0.615 (val F1=0.3436)
  Directional -> Accuracy: 0.5862, MCC: 0.1649, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61368 | val 1.39801
  Epoch 020 - train 0.44790 | val 1.47779
  Epoch 021 - train 0.45689 | val 2.82946
  Classification -> best τ=0.525 (val F1=0.1058)
  Directional -> Accuracy: 0.5606, MCC: 0.1103, F1: 0.2927

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68377 | val 0.68756
  Epoch 016 - train 0.51569 | val 1.11874
  Classification -> best τ=0.530 (val F1=0.3807)
  Directional -> Accuracy: 0.5714, MCC: 0.1762, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56267 | val 1.51525
  Epoch 011 - train 0.49094 | val 1.65233
  Classification -> best τ=0.455 (val F1=0.2774)
  Directional -> Accuracy: 0.6522, MCC: 0.3269, F1: 0.6522

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61457 | val 0.78154
  Epoch 011 - train 0.64162 | val 0.88801
  Classification -> best τ=0.505 (val F1=0.0889)
  Directional -> Accuracy: 0.5116, MCC: 0.0866, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62607 | val 1.07382
  Epoch 015 - train 0.59111 | val 2.42078
  Classification -> best τ=0.380 (val F1=0.3618)
  Directional -> Accuracy: 0.5263, MCC: 0.1888, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49576 | val 1.11944
  Epoch 011 - train 0.51104 | val 1.41273
  Classification -> best τ=0.500 (val F1=0.3069)
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50145 | val 8.36596
  Epoch 011 - train 0.46202 | val 8.90197
  Classification -> best τ=0.550 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56645 | val 1.06054
  Epoch 013 - train 0.44397 | val 0.89819
  Classification -> best τ=0.590 (val F1=0.1820)
  Directional -> Accuracy: 0.5116, MCC: -0.0323, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54286 | val 1.33718
  Epoch 011 - train 0.53507 | val 1.13534
  Classification -> best τ=0.450 (val F1=0.2806)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58290 | val 0.97957
  Epoch 017 - train 0.43707 | val 0.89066
  Classification -> best τ=0.185 (val F1=0.3602)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61842 | val 1.38720
  Epoch 017 - train 0.46238 | val 3.96384
  Classification -> best τ=0.525 (val F1=0.4082)
  Directional -> Accuracy: 0.5526, MCC: 0.1291, F1: 0.6531

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63050 | val 0.80900
  Epoch 011 - train 0.52492 | val 0.92903
  Classification -> best τ=0.450 (val F1=0.3792)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55713 | val 0.93301
  Epoch 011 - train 0.56184 | val 0.94233
  Classification -> best τ=0.335 (val F1=0.3767)
  Directional -> Accuracy: 0.5821, MCC: 0.1357, F1: 0.6500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54079 | val 1.03508
  Epoch 017 - train 0.43420 | val 1.03319
  Classification -> best τ=0.485 (val F1=0.2917)
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56336 | val 1.29699
  Epoch 012 - train 0.57916 | val 1.08094
  Classification -> best τ=0.295 (val F1=0.2665)
  Directional -> Accuracy: 0.5439, MCC: 0.1810, F1: 0.6579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57351 | val 0.65500
  Epoch 020 - train 0.35194 | val 0.90883
  Classification -> best τ=0.425 (val F1=0.3135)
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.5385

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54408 | val 0.93923
  Epoch 019 - train 0.33948 | val 0.83904
  Classification -> best τ=0.620 (val F1=0.4345)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44872 | val 3.36938
  Epoch 011 - train 0.36757 | val 3.57393
  Classification -> best τ=0.535 (val F1=0.0134)
  Directional -> Accuracy: 0.5526, MCC: 0.2777, F1: 0.2609

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57245 | val 1.63992
  Epoch 011 - train 0.55346 | val 1.27045
  Classification -> best τ=0.550 (val F1=0.2014)
  Directional -> Accuracy: 0.5467, MCC: 0.1118, F1: 0.3200

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55396 | val 1.00253
  Epoch 011 - train 0.53330 | val 1.10877
  Classification -> best τ=0.450 (val F1=0.2593)
  Directional -> Accuracy: 0.5106, MCC: 0.1443, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42986 | val 3.28390
  Epoch 011 - train 0.39452 | val 4.03959
  Classification -> best τ=0.600 (val F1=0.3967)
  Directional -> Accuracy: 0.4091, MCC: -0.1283, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54298 | val 1.50288
  Epoch 013 - train 0.46530 | val 4.46674
  Classification -> best τ=0.535 (val F1=0.6130)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61535 | val 2.32742
  Epoch 011 - train 0.61228 | val 1.66408
  Classification -> best τ=0.535 (val F1=0.1463)
  Directional -> Accuracy: 0.5357, MCC: 0.0716, F1: 0.5517

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62111 | val 0.74104
  Epoch 014 - train 0.59532 | val 0.75400
  Classification -> best τ=0.500 (val F1=0.4103)
  Directional -> Accuracy: 0.5614, MCC: 0.1491, F1: 0.6154

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58631 | val 0.71464
  Epoch 014 - train 0.53007 | val 0.88407
  Classification -> best τ=0.640 (val F1=0.2570)
  Directional -> Accuracy: 0.4630, MCC: -0.0771, F1: 0.4912

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65274 | val 0.69513
  Epoch 011 - train 0.63525 | val 0.87926
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62594 | val 1.02253

[I 2026-02-20 03:34:34,465] Trial 122 finished with value: 0.2644598572689038 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.004854221022789348, 'weight_decay': 6.597536540780553e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6979854294386676, 'early_stopping_min_delta': 0.007578426338927984}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.58500 | val 1.32027
  Classification -> best τ=0.515 (val F1=0.2544)
  Directional -> Accuracy: 0.6066, MCC: 0.2231, F1: 0.6250

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2644598572689038
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65032 | val 2.28180
  Epoch 011 - train 0.63778 | val 5.61138
  Classification -> best τ=0.510 (val F1=0.2453)
  Directional -> Accuracy: 0.5325, MCC: 0.0120, F1: 0.2800

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67013 | val 1.07134
  Epoch 015 - train 0.58663 | val 1.57166
  Classification -> best τ=0.420 (val F1=0.2918)
  Directional -> Accuracy: 0.5870, MCC: 0.1236, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57935 | val 0.74117
  Epoch 011 - train 0.59461 | val 1.02146
  Classification -> best τ=0.530 (val F1=0.3477)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65042 | val 0.84513
  Epoch 013 - train 0.61821 | val 0.84061
  Classification -> best τ=0.635 (val F1=0.1590)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52697 | val 2.46673
  Epoch 018 - train 0.61738 | val 2.38362
  Classification -> best τ=0.530 (val F1=0.4051)
  Directional -> Accuracy: 0.4706, MCC: -0.0398, F1: 0.3721

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58720 | val 0.81956
  Epoch 020 - train 0.37387 | val 2.36256
  Epoch 021 - train 0.38488 | val 1.80989
  Classification -> best τ=0.490 (val F1=0.4752)
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.1538

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68508 | val 0.80072
  Epoch 020 - train 0.64508 | val 0.68468
  Epoch 025 - train 0.63008 | val 1.32058
  Classification -> best τ=0.560 (val F1=0.2872)
  Directional -> Accuracy: 0.4638, MCC: 0.0075, F1: 0.5195

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.84260 | val 2.28081
  Epoch 013 - train 0.60271 | val 2.16831
  Classification -> best τ=0.360 (val F1=0.1752)
  Directional -> Accuracy: 0.4318, MCC: 0.0417, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59290 | val 4.08070
  Epoch 011 - train 0.56956 | val 3.11925
  Classification -> best τ=0.510 (val F1=0.1978)
  Directional -> Accuracy: 0.5918, MCC: 0.2435, F1: 0.6429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59731 | val 0.82359
  Epoch 012 - train 0.65412 | val 0.84239
  Classification -> best τ=0.265 (val F1=0.2576)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60088 | val 0.93452
  Epoch 015 - train 0.54764 | val 1.49700
  Classification -> best τ=0.490 (val F1=0.3094)
  Directional -> Accuracy: 0.5000, MCC: 0.0489, F1: 0.5902

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55205 | val 1.47319
  Epoch 011 - train 0.54240 | val 1.95704
  Classification -> best τ=0.420 (val F1=0.1234)
  Directional -> Accuracy: 0.6207, MCC: 0.2756, F1: 0.6944

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60850 | val 2.48977
  Epoch 011 - train 0.55687 | val 3.55043
  Classification -> best τ=0.605 (val F1=0.1711)
  Directional -> Accuracy: 0.5116, MCC: -0.0316, F1: 0.3226

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71113 | val 0.64363
  Epoch 014 - train 0.65324 | val 0.68939
  Classification -> best τ=0.415 (val F1=0.3322)
  Directional -> Accuracy: 0.5410, MCC: 0.0843, F1: 0.6316

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61222 | val 0.99388
  Epoch 011 - train 0.61588 | val 0.86014
  Classification -> best τ=0.485 (val F1=0.4288)
  Directional -> Accuracy: 0.5192, MCC: -0.0157, F1: 0.2424

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62048 | val 1.05926
  Epoch 011 - train 0.63466 | val 1.27896
  Classification -> best τ=0.455 (val F1=0.2761)
  Directional -> Accuracy: 0.5857, MCC: 0.1518, F1: 0.6588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64234 | val 0.95547
  Epoch 015 - train 0.61134 | val 0.94615
  Classification -> best τ=0.355 (val F1=0.3015)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69735 | val 0.69803
  Epoch 011 - train 0.68725 | val 0.77846
  Classification -> best τ=0.620 (val F1=0.2395)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66244 | val 0.90173
  Epoch 011 - train 0.64656 | val 1.05810
  Classification -> best τ=0.420 (val F1=0.0886)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63923 | val 0.94342
  Epoch 011 - train 0.64966 | val 1.93213
  Classification -> best τ=0.745 (val F1=0.2656)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61912 | val 2.55255
  Epoch 014 - train 0.56989 | val 2.52411
  Classification -> best τ=0.400 (val F1=0.4330)
  Directional -> Accuracy: 0.3542, MCC: -0.2711, F1: 0.3922

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68517 | val 1.10707
  Epoch 012 - train 0.64208 | val 0.80748
  Classification -> best τ=0.615 (val F1=0.2797)
  Directional -> Accuracy: 0.5152, MCC: 0.0381, F1: 0.6279

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67448 | val 1.25737
  Epoch 012 - train 0.62632 | val 2.70303
  Classification -> best τ=0.510 (val F1=0.2914)
  Directional -> Accuracy: 0.5345, MCC: 0.1655, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62429 | val 3.72830
  Epoch 011 - train 0.61737 | val 2.46354
  Classification -> best τ=0.525 (val F1=0.1446)
  Directional -> Accuracy: 0.5303, MCC: 0.0429, F1: 0.4151

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61977 | val 0.91163
  Epoch 015 - train 0.55483 | val 0.74447
  Classification -> best τ=0.490 (val F1=0.3216)
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65403 | val 1.53181
  Epoch 011 - train 0.53742 | val 1.99604
  Classification -> best τ=0.550 (val F1=0.3464)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68629 | val 0.97530
  Epoch 013 - train 0.66321 | val 0.72395
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70575 | val 0.83429
  Epoch 011 - train 0.71326 | val 1.13251
  Classification -> best τ=0.590 (val F1=0.1944)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52848 | val 0.65761
  Epoch 020 - train 0.39159 | val 0.84281
  Classification -> best τ=0.660 (val F1=0.4208)
  Directional -> Accuracy: 0.4878, MCC: 0.0108, F1: 0.3636

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59722 | val 0.70005
  Epoch 011 - train 0.54983 | val 0.84641
  Classification -> best τ=0.555 (val F1=0.1869)
  Directional -> Accuracy: 0.5116, MCC: 0.0318, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59533 | val 1.93806
  Epoch 012 - train 0.49403 | val 1.91312
  Classification -> best τ=0.640 (val F1=0.1557)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64671 | val 0.86725
  Epoch 013 - train 0.72073 | val 1.07902
  Classification -> best τ=0.590 (val F1=0.2320)
  Directional -> Accuracy: 0.6200, MCC: 0.2539, F1: 0.7246

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58002 | val 1.96791
  Epoch 015 - train 0.49874 | val 2.29769
  Classification -> best τ=0.170 (val F1=0.3918)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60150 | val 2.41624
  Epoch 011 - train 0.62693 | val 2.47843
  Classification -> best τ=0.450 (val F1=0.0925)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68110 | val 1.03050
  Epoch 012 - train 0.80460 | val 0.84602
  Classification -> best τ=0.570 (val F1=0.3121)
  Directional -> Accuracy: 0.5455, MCC: 0.1668, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63784 | val 0.85531
  Epoch 011 - train 0.59059 | val 0.90281
  Classification -> best τ=0.430 (val F1=0.3626)
  Directional -> Accuracy: 0.5522, MCC: 0.2067, F1: 0.4444

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50238 | val 1.13350
  Epoch 011 - train 0.52036 | val 1.06617
  Classification -> best τ=0.480 (val F1=0.1222)
  Directional -> Accuracy: 0.6047, MCC: 0.2529, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67035 | val 0.98106
  Epoch 014 - train 0.53869 | val 1.30356
  Classification -> best τ=0.445 (val F1=0.1677)
  Directional -> Accuracy: 0.5263, MCC: 0.0882, F1: 0.6087

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61113 | val 1.91039
  Epoch 011 - train 0.58753 | val 1.22633
  Classification -> best τ=0.500 (val F1=0.3321)
  Directional -> Accuracy: 0.4468, MCC: 0.0220, F1: 0.3500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61677 | val 0.91489
  Epoch 018 - train 0.48479 | val 0.99090
  Classification -> best τ=0.365 (val F1=0.3125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48731 | val 1.26077
  Epoch 011 - train 0.44802 | val 2.31760
  Classification -> best τ=0.540 (val F1=0.2041)
  Directional -> Accuracy: 0.5526, MCC: 0.1132, F1: 0.6909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63508 | val 1.54522
  Epoch 020 - train 0.58629 | val 1.47132
  Epoch 023 - train 0.56947 | val 1.41452
  Classification -> best τ=0.345 (val F1=0.2924)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60177 | val 0.73114
  Epoch 015 - train 0.46101 | val 1.20594
  Classification -> best τ=0.525 (val F1=0.2593)
  Directional -> Accuracy: 0.5106, MCC: 0.0617, F1: 0.2069

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62903 | val 0.81570
  Epoch 013 - train 0.44820 | val 1.37246
  Classification -> best τ=0.490 (val F1=0.0097)
  Directional -> Accuracy: 0.5682, MCC: 0.0843, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53312 | val 1.53579
  Epoch 011 - train 0.49728 | val 2.37325
  Classification -> best τ=0.505 (val F1=0.5330)
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66858 | val 1.79222
  Epoch 013 - train 0.61863 | val 2.23145
  Classification -> best τ=0.505 (val F1=0.2465)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68920 | val 0.79925
  Epoch 012 - train 0.56448 | val 1.12429
  Classification -> best τ=0.510 (val F1=0.3973)
  Directional -> Accuracy: 0.4912, MCC: -0.0304, F1: 0.4082

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65305 | val 1.15287
  Epoch 012 - train 0.60177 | val 11.17097
  Classification -> best τ=0.410 (val F1=0.2618)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62539 | val 2.72514
  Epoch 011 - train 0.65326 | val 2.07327
  Classification -> best τ=0.500 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.5424

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64346 | val 3.29032
  Epoch 011 - train 0.61808 | val 3.47040

[I 2026-02-20 03:36:18,614] Trial 123 finished with value: 0.26487541769749234 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.00970487559220915, 'weight_decay': 1.1160124015212812e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5873573850454514, 'early_stopping_min_delta': 0.0072537105575713485}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.315 (val F1=0.3948)
  Directional -> Accuracy: 0.5738, MCC: 0.1425, F1: 0.4091

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26487541769749234
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47768 | val 1.95859
  Epoch 011 - train 0.44669 | val 2.71514
  Classification -> best τ=0.525 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48751 | val 1.03137
  Epoch 011 - train 0.43067 | val 1.60720
  Classification -> best τ=0.470 (val F1=0.2173)
  Directional -> Accuracy: 0.5870, MCC: 0.1252, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55510 | val 0.79126
  Epoch 011 - train 0.52657 | val 0.78103
  Classification -> best τ=0.340 (val F1=0.3518)
  Directional -> Accuracy: 0.4894, MCC: -0.0440, F1: 0.5714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59373 | val 3.51929
  Epoch 011 - train 0.55891 | val 4.51666
  Classification -> best τ=0.640 (val F1=0.1723)
  Directional -> Accuracy: 0.5333, MCC: 0.0760, F1: 0.5333

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41091 | val 1.58126
  Epoch 011 - train 0.39586 | val 2.02923
  Classification -> best τ=0.425 (val F1=0.4692)
  Directional -> Accuracy: 0.5686, MCC: 0.2303, F1: 0.3889

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38210 | val 2.98776
  Epoch 011 - train 0.33614 | val 3.21066
  Classification -> best τ=0.650 (val F1=0.3095)
  Directional -> Accuracy: 0.5532, MCC: 0.1043, F1: 0.4878

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52599 | val 1.06768
  Epoch 012 - train 0.48355 | val 1.09398
  Classification -> best τ=0.490 (val F1=0.1781)
  Directional -> Accuracy: 0.4348, MCC: -0.0468, F1: 0.5063

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42087 | val 7.71080
  Epoch 011 - train 0.34687 | val 8.08713
  Classification -> best τ=0.570 (val F1=0.1590)
  Directional -> Accuracy: 0.5000, MCC: -0.1203, F1: 0.2143

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45514 | val 2.89590
  Epoch 012 - train 0.39659 | val 3.24225
  Classification -> best τ=0.480 (val F1=0.2129)
  Directional -> Accuracy: 0.6327, MCC: 0.2464, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52383 | val 0.89262
  Epoch 011 - train 0.52498 | val 1.04048
  Classification -> best τ=0.515 (val F1=0.2213)
  Directional -> Accuracy: 0.5143, MCC: 0.1443, F1: 0.6047

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57969 | val 2.17782
  Epoch 012 - train 0.50087 | val 2.88139
  Classification -> best τ=0.350 (val F1=0.3118)
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48157 | val 3.48802
  Epoch 011 - train 0.47371 | val 3.93951
  Classification -> best τ=0.200 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49078 | val 1.97212
  Epoch 012 - train 0.40185 | val 2.46434
  Classification -> best τ=0.460 (val F1=0.2596)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55462 | val 1.07865
  Epoch 011 - train 0.52728 | val 1.07870
  Classification -> best τ=0.500 (val F1=0.3523)
  Directional -> Accuracy: 0.5738, MCC: 0.1504, F1: 0.5517

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64459 | val 0.90648
  Epoch 013 - train 0.53208 | val 1.54417
  Classification -> best τ=0.565 (val F1=0.2177)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49217 | val 1.64429
  Epoch 011 - train 0.47535 | val 0.91699
  Classification -> best τ=0.265 (val F1=0.2927)
  Directional -> Accuracy: 0.5286, MCC: -0.0318, F1: 0.6796

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57460 | val 1.01813
  Epoch 012 - train 0.51911 | val 1.12545
  Classification -> best τ=0.435 (val F1=0.1857)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54548 | val 1.58156
  Epoch 011 - train 0.48413 | val 2.13218
  Classification -> best τ=0.760 (val F1=0.2219)
  Directional -> Accuracy: 0.5263, MCC: 0.0538, F1: 0.5714

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62463 | val 1.27185
  Epoch 016 - train 0.49921 | val 1.59676
  Classification -> best τ=0.560 (val F1=0.1501)
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57636 | val 0.72021
  Epoch 016 - train 0.42724 | val 1.21759
  Classification -> best τ=0.625 (val F1=0.3214)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49971 | val 2.04479
  Epoch 012 - train 0.38645 | val 3.88068
  Classification -> best τ=0.335 (val F1=0.2190)
  Directional -> Accuracy: 0.6250, MCC: 0.3055, F1: 0.6400

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55714 | val 0.95417
  Epoch 011 - train 0.58015 | val 1.44875
  Classification -> best τ=0.350 (val F1=0.1547)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48240 | val 3.20089
  Epoch 011 - train 0.46096 | val 3.12855
  Classification -> best τ=0.480 (val F1=0.1268)
  Directional -> Accuracy: 0.4483, MCC: -0.0951, F1: 0.4667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53516 | val 1.86255
  Epoch 011 - train 0.50375 | val 1.64746
  Classification -> best τ=0.465 (val F1=0.2543)
  Directional -> Accuracy: 0.5000, MCC: 0.0215, F1: 0.5600

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49070 | val 0.67517
  Epoch 012 - train 0.40389 | val 0.97323
  Classification -> best τ=0.685 (val F1=0.4352)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46562 | val 1.09507
  Epoch 011 - train 0.44009 | val 1.39701
  Classification -> best τ=0.515 (val F1=0.1925)
  Directional -> Accuracy: 0.4348, MCC: -0.1801, F1: 0.2778

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56494 | val 1.19399
  Epoch 011 - train 0.53732 | val 1.25198
  Classification -> best τ=0.500 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0454, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55867 | val 0.76797
  Epoch 013 - train 0.43243 | val 0.92417
  Classification -> best τ=0.450 (val F1=0.2648)
  Directional -> Accuracy: 0.4561, MCC: 0.0241, F1: 0.1622

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50549 | val 0.71055
  Epoch 011 - train 0.50782 | val 0.70615
  Classification -> best τ=0.540 (val F1=0.2202)
  Directional -> Accuracy: 0.4634, MCC: -0.0966, F1: 0.5417

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39883 | val 5.10074
  Epoch 011 - train 0.36451 | val 6.22780
  Classification -> best τ=0.530 (val F1=0.1574)
  Directional -> Accuracy: 0.5814, MCC: 0.1689, F1: 0.6087

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51080 | val 1.39038
  Epoch 013 - train 0.36186 | val 1.45095
  Classification -> best τ=0.410 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44852 | val 1.30392
  Epoch 011 - train 0.39454 | val 1.35901
  Classification -> best τ=0.580 (val F1=0.2870)
  Directional -> Accuracy: 0.4400, MCC: -0.2235, F1: 0.5882

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43963 | val 1.00571
  Epoch 011 - train 0.46793 | val 0.97757
  Classification -> best τ=0.430 (val F1=0.2464)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51346 | val 3.51562
  Epoch 011 - train 0.44313 | val 3.43301
  Classification -> best τ=0.410 (val F1=0.4714)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48538 | val 1.56112
  Epoch 011 - train 0.44168 | val 1.65800
  Classification -> best τ=0.230 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59732 | val 0.71790
  Epoch 011 - train 0.56584 | val 0.85975
  Classification -> best τ=0.660 (val F1=0.2264)
  Directional -> Accuracy: 0.4627, MCC: 0.1532, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66715 | val 0.76927
  Epoch 012 - train 0.60540 | val 1.02549
  Classification -> best τ=0.535 (val F1=0.3099)
  Directional -> Accuracy: 0.5814, MCC: 0.1746, F1: 0.5263

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41582 | val 1.81359
  Epoch 012 - train 0.36668 | val 2.99095
  Classification -> best τ=0.405 (val F1=0.2261)
  Directional -> Accuracy: 0.5263, MCC: 0.0970, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49475 | val 1.39110
  Epoch 011 - train 0.52321 | val 4.88158
  Classification -> best τ=0.450 (val F1=0.3014)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49476 | val 1.19514
  Epoch 013 - train 0.34156 | val 1.58878
  Classification -> best τ=0.245 (val F1=0.4188)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51758 | val 1.10938
  Epoch 011 - train 0.46987 | val 1.43956
  Classification -> best τ=0.545 (val F1=0.1461)
  Directional -> Accuracy: 0.5526, MCC: 0.1566, F1: 0.4138

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47594 | val 1.49588
  Epoch 011 - train 0.45856 | val 1.53515
  Classification -> best τ=0.480 (val F1=0.1752)
  Directional -> Accuracy: 0.5200, MCC: 0.0392, F1: 0.5000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49071 | val 0.84968
  Epoch 014 - train 0.28378 | val 1.08738
  Classification -> best τ=0.535 (val F1=0.5869)
  Directional -> Accuracy: 0.4681, MCC: -0.0678, F1: 0.5098

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37496 | val 1.94751
  Epoch 011 - train 0.35353 | val 2.15314
  Classification -> best τ=0.745 (val F1=0.3967)
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50329 | val 3.03982
  Epoch 013 - train 0.45719 | val 4.84894
  Classification -> best τ=0.610 (val F1=0.2887)
  Directional -> Accuracy: 0.3878, MCC: -0.0475, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48810 | val 2.94114
  Epoch 011 - train 0.46770 | val 3.06107
  Classification -> best τ=0.590 (val F1=0.1085)
  Directional -> Accuracy: 0.5000, MCC: 0.1192, F1: 0.1765

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40035 | val 1.22721
  Epoch 011 - train 0.38165 | val 1.42003
  Classification -> best τ=0.515 (val F1=0.3119)
  Directional -> Accuracy: 0.4737, MCC: -0.0301, F1: 0.5714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55539 | val 0.83039
  Epoch 012 - train 0.51789 | val 0.91608
  Classification -> best τ=0.590 (val F1=0.2749)
  Directional -> Accuracy: 0.5926, MCC: 0.2085, F1: 0.6944

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53887 | val 0.90207
  Epoch 013 - train 0.41646 | val 0.91867
  Classification -> best τ=0.610 (val F1=0.3039)
  Directional -> Accuracy: 0.4286, MCC: -0.2466, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62595 | val 1.11830

[I 2026-02-20 03:37:33,238] Trial 124 finished with value: 0.2673115993189379 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005443371689341348, 'weight_decay': 5.573980547065692e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.8783413565765538, 'early_stopping_min_delta': 0.008537972625071832}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 017 - train 0.41185 | val 1.21319
  Classification -> best τ=0.350 (val F1=0.4043)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2673115993189379
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57647 | val 3.03622
  Epoch 011 - train 0.56874 | val 2.80858
  Classification -> best τ=0.405 (val F1=0.1843)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47491 | val 1.56974
  Epoch 012 - train 0.43746 | val 2.16477
  Classification -> best τ=0.465 (val F1=0.1812)
  Directional -> Accuracy: 0.5870, MCC: 0.1252, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57260 | val 0.87509
  Epoch 011 - train 0.60331 | val 0.78790
  Classification -> best τ=0.495 (val F1=0.5063)
  Directional -> Accuracy: 0.5319, MCC: 0.0245, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56442 | val 4.03217
  Epoch 011 - train 0.56121 | val 2.84709
  Classification -> best τ=0.495 (val F1=0.1961)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47359 | val 1.92843
  Epoch 012 - train 0.40727 | val 3.08409
  Classification -> best τ=0.625 (val F1=0.3309)
  Directional -> Accuracy: 0.4510, MCC: -0.0806, F1: 0.1765

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35457 | val 9.29357
  Epoch 011 - train 0.36526 | val 9.06494
  Classification -> best τ=0.515 (val F1=0.3430)
  Directional -> Accuracy: 0.5745, MCC: 0.2667, F1: 0.2308

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57811 | val 1.12560
  Epoch 011 - train 0.57428 | val 1.00181
  Classification -> best τ=0.490 (val F1=0.0934)
  Directional -> Accuracy: 0.4348, MCC: 0.0455, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58027 | val 2.43410
  Epoch 012 - train 0.51887 | val 2.29564
  Classification -> best τ=0.390 (val F1=0.1214)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56465 | val 2.07197
  Epoch 012 - train 0.48126 | val 1.96150
  Classification -> best τ=0.490 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55887 | val 0.97312
  Epoch 012 - train 0.53622 | val 0.96877
  Classification -> best τ=0.365 (val F1=0.2241)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54551 | val 2.95281
  Epoch 011 - train 0.48541 | val 3.50686
  Classification -> best τ=0.550 (val F1=0.2550)
  Directional -> Accuracy: 0.6000, MCC: 0.1839, F1: 0.4737

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52333 | val 1.74190
  Epoch 011 - train 0.51375 | val 2.26551
  Classification -> best τ=0.380 (val F1=0.2172)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51459 | val 2.49497
  Epoch 011 - train 0.45892 | val 3.75742
  Classification -> best τ=0.365 (val F1=0.1700)
  Directional -> Accuracy: 0.6047, MCC: 0.1870, F1: 0.5143

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62508 | val 0.82396
  Epoch 013 - train 0.55438 | val 1.30946
  Classification -> best τ=0.360 (val F1=0.2739)
  Directional -> Accuracy: 0.5738, MCC: 0.1731, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52526 | val 1.25196
  Epoch 011 - train 0.56709 | val 3.40290
  Classification -> best τ=0.490 (val F1=0.1706)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50312 | val 1.67716
  Epoch 011 - train 0.50492 | val 1.54543
  Classification -> best τ=0.465 (val F1=0.2000)
  Directional -> Accuracy: 0.5571, MCC: 0.0876, F1: 0.6437

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56417 | val 1.12829
  Epoch 011 - train 0.54518 | val 1.21254
  Classification -> best τ=0.625 (val F1=0.0981)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57255 | val 0.98660
  Epoch 011 - train 0.58944 | val 0.92445
  Classification -> best τ=0.690 (val F1=0.1560)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52747 | val 2.91773
  Epoch 011 - train 0.52661 | val 2.13762
  Classification -> best τ=0.525 (val F1=0.1279)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51983 | val 1.32413
  Epoch 011 - train 0.51318 | val 1.05666
  Classification -> best τ=0.570 (val F1=0.2691)
  Directional -> Accuracy: 0.3333, MCC: -0.3219, F1: 0.2857

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54124 | val 0.70749
  Epoch 011 - train 0.52810 | val 0.83533
  Classification -> best τ=0.540 (val F1=0.2000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60444 | val 2.11136
  Epoch 013 - train 0.49729 | val 3.18748
  Classification -> best τ=0.870 (val F1=0.1318)
  Directional -> Accuracy: 0.5606, MCC: 0.1571, F1: 0.3556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55276 | val 2.42433
  Epoch 011 - train 0.52420 | val 2.50083
  Classification -> best τ=0.765 (val F1=0.2583)
  Directional -> Accuracy: 0.5690, MCC: 0.2256, F1: 0.4898

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51834 | val 1.73643
  Epoch 011 - train 0.52788 | val 2.92660
  Classification -> best τ=0.405 (val F1=0.2453)
  Directional -> Accuracy: 0.5303, MCC: 0.0707, F1: 0.5507

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58614 | val 1.41989
  Epoch 017 - train 0.37757 | val 2.09542
  Classification -> best τ=0.325 (val F1=0.3656)
  Directional -> Accuracy: 0.5179, MCC: 0.0054, F1: 0.5970

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42658 | val 2.55398
  Epoch 011 - train 0.47473 | val 2.71447
  Classification -> best τ=0.485 (val F1=0.1925)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58682 | val 2.65990
  Epoch 012 - train 0.58465 | val 2.85867
  Classification -> best τ=0.575 (val F1=0.1818)
  Directional -> Accuracy: 0.6047, MCC: 0.1818, F1: 0.7463

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59488 | val 0.95826
  Epoch 011 - train 0.56324 | val 0.97280
  Classification -> best τ=0.405 (val F1=0.1415)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49662 | val 0.84473
  Epoch 011 - train 0.44629 | val 0.81570
  Classification -> best τ=0.645 (val F1=0.4193)
  Directional -> Accuracy: 0.4878, MCC: 0.1469, F1: 0.0870

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45505 | val 3.27211
  Epoch 011 - train 0.39249 | val 3.02116
  Classification -> best τ=0.560 (val F1=0.1869)
  Directional -> Accuracy: 0.6744, MCC: 0.3514, F1: 0.6818

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44024 | val 1.92204
  Epoch 012 - train 0.39771 | val 1.77348
  Classification -> best τ=0.660 (val F1=0.1759)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46070 | val 2.03222
  Epoch 011 - train 0.42551 | val 1.87922
  Classification -> best τ=0.450 (val F1=0.3605)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56514 | val 2.94830
  Epoch 012 - train 0.51267 | val 4.44582
  Classification -> best τ=0.420 (val F1=0.3570)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43397 | val 3.22992
  Epoch 011 - train 0.39522 | val 3.64229
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47890 | val 1.52434
  Epoch 011 - train 0.47862 | val 1.98343
  Classification -> best τ=0.545 (val F1=0.3895)
  Directional -> Accuracy: 0.5455, MCC: 0.0856, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49084 | val 0.85560
  Epoch 012 - train 0.46155 | val 1.13784
  Classification -> best τ=0.330 (val F1=0.3431)
  Directional -> Accuracy: 0.4776, MCC: -0.0352, F1: 0.4928

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48495 | val 1.23640
  Epoch 013 - train 0.39428 | val 1.19399
  Classification -> best τ=0.350 (val F1=0.3343)
  Directional -> Accuracy: 0.6279, MCC: 0.2632, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51578 | val 2.52826
  Epoch 011 - train 0.54413 | val 2.89300
  Classification -> best τ=0.370 (val F1=0.2095)
  Directional -> Accuracy: 0.4912, MCC: 0.0132, F1: 0.5915

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42096 | val 1.55300
  Epoch 012 - train 0.35275 | val 2.17895
  Classification -> best τ=0.625 (val F1=0.3544)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48065 | val 1.19260
  Epoch 014 - train 0.42236 | val 1.84036
  Classification -> best τ=0.360 (val F1=0.2238)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51428 | val 1.68500
  Epoch 011 - train 0.40150 | val 1.74575
  Classification -> best τ=0.595 (val F1=0.2227)
  Directional -> Accuracy: 0.5526, MCC: 0.2134, F1: 0.3200

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48648 | val 2.55564
  Epoch 011 - train 0.48394 | val 3.76060
  Classification -> best τ=0.515 (val F1=0.2135)
  Directional -> Accuracy: 0.4800, MCC: -0.0944, F1: 0.0930

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46424 | val 1.50254
  Epoch 011 - train 0.43314 | val 1.90834
  Classification -> best τ=0.555 (val F1=0.3776)
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37385 | val 2.24105
  Epoch 011 - train 0.32200 | val 2.27035
  Classification -> best τ=0.585 (val F1=0.2749)
  Directional -> Accuracy: 0.4318, MCC: -0.0435, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46826 | val 2.02611
  Epoch 012 - train 0.41684 | val 2.34326
  Classification -> best τ=0.475 (val F1=0.6325)
  Directional -> Accuracy: 0.5306, MCC: 0.1175, F1: 0.5306

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61568 | val 2.07344
  Epoch 011 - train 0.55741 | val 2.33260
  Classification -> best τ=0.545 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46664 | val 1.14104
  Epoch 012 - train 0.45390 | val 1.35511
  Classification -> best τ=0.595 (val F1=0.3819)
  Directional -> Accuracy: 0.5614, MCC: 0.1968, F1: 0.6575

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56650 | val 1.07195
  Epoch 012 - train 0.50896 | val 1.53945
  Classification -> best τ=0.520 (val F1=0.2011)
  Directional -> Accuracy: 0.5556, MCC: 0.1201, F1: 0.5200

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49290 | val 2.29184
  Epoch 012 - train 0.46209 | val 2.06129
  Classification -> best τ=0.395 (val F1=0.1001)
  Directional -> Accuracy: 0.5179, MCC: 0.0146, F1: 0.6494

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57276 | val 1.87708

[I 2026-02-20 03:40:15,011] Trial 125 finished with value: 0.24768682242803297 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007600429589087169, 'weight_decay': 2.178796792699855e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.7354202387493531, 'early_stopping_min_delta': 0.008182529034731819}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.52120 | val 3.14021
  Classification -> best τ=0.445 (val F1=0.3103)
  Directional -> Accuracy: 0.5082, MCC: 0.1196, F1: 0.6512

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24768682242803297
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62215 | val 0.77923
  Epoch 012 - train 0.61060 | val 0.86579
  Classification -> best τ=0.405 (val F1=0.0158)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61256 | val 0.71472
  Epoch 012 - train 0.59867 | val 0.70464
  Classification -> best τ=0.420 (val F1=0.1780)
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60194 | val 0.72403
  Epoch 012 - train 0.59023 | val 0.69296
  Classification -> best τ=0.560 (val F1=0.2276)
  Directional -> Accuracy: 0.4681, MCC: -0.0135, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65073 | val 0.71300
  Epoch 013 - train 0.61407 | val 0.89061
  Classification -> best τ=0.445 (val F1=0.1723)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60080 | val 0.68094
  Epoch 017 - train 0.52951 | val 0.68816
  Classification -> best τ=0.455 (val F1=0.4858)
  Directional -> Accuracy: 0.4510, MCC: -0.1525, F1: 0.5758

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59087 | val 0.84470
  Epoch 013 - train 0.62705 | val 0.97751
  Classification -> best τ=0.480 (val F1=0.1644)
  Directional -> Accuracy: 0.5319, MCC: 0.0603, F1: 0.4500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68425 | val 0.69270
  Epoch 018 - train 0.62203 | val 0.72501
  Classification -> best τ=0.510 (val F1=0.2844)
  Directional -> Accuracy: 0.4638, MCC: -0.0274, F1: 0.4789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57984 | val 0.93203
  Epoch 013 - train 0.54922 | val 0.95924
  Classification -> best τ=0.385 (val F1=0.2192)
  Directional -> Accuracy: 0.4545, MCC: -0.2306, F1: 0.1429

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59344 | val 0.75720
  Epoch 012 - train 0.60442 | val 0.79284
  Classification -> best τ=0.530 (val F1=0.2788)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58659 | val 0.74922
  Epoch 012 - train 0.56493 | val 0.74614
  Classification -> best τ=0.535 (val F1=0.1622)
  Directional -> Accuracy: 0.4429, MCC: -0.0775, F1: 0.4800

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65798 | val 0.74250
  Epoch 012 - train 0.60341 | val 0.88028
  Classification -> best τ=0.325 (val F1=0.1667)
  Directional -> Accuracy: 0.6600, MCC: 0.3634, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56317 | val 1.57600
  Epoch 014 - train 0.54126 | val 2.17483
  Classification -> best τ=0.390 (val F1=0.2630)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59595 | val 0.90736
  Epoch 011 - train 0.60007 | val 0.78948
  Classification -> best τ=0.495 (val F1=0.2103)
  Directional -> Accuracy: 0.4884, MCC: 0.0880, F1: 0.6071

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63802 | val 0.62250
  Epoch 020 - train 0.56292 | val 0.63518
  Classification -> best τ=0.285 (val F1=0.3383)
  Directional -> Accuracy: 0.5410, MCC: 0.0825, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63288 | val 0.86283
  Epoch 013 - train 0.55169 | val 1.13571
  Classification -> best τ=0.565 (val F1=0.2705)
  Directional -> Accuracy: 0.6923, MCC: 0.3858, F1: 0.6000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60754 | val 0.89208
  Epoch 012 - train 0.62350 | val 0.79779
  Classification -> best τ=0.705 (val F1=0.3271)
  Directional -> Accuracy: 0.5143, MCC: 0.1130, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63415 | val 0.90198
  Epoch 011 - train 0.60406 | val 0.89395
  Classification -> best τ=0.540 (val F1=0.1667)
  Directional -> Accuracy: 0.4746, MCC: -0.2087, F1: 0.6173

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65576 | val 1.11010
  Epoch 011 - train 0.63733 | val 1.18826
  Classification -> best τ=0.360 (val F1=0.0706)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66407 | val 0.84399
  Epoch 014 - train 0.57992 | val 1.03846
  Classification -> best τ=0.435 (val F1=0.2820)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64443 | val 0.80860
  Epoch 012 - train 0.62354 | val 0.82598
  Classification -> best τ=0.490 (val F1=0.2800)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61750 | val 0.78991
  Epoch 020 - train 0.56059 | val 1.64570
  Classification -> best τ=0.375 (val F1=0.4568)
  Directional -> Accuracy: 0.5000, MCC: 0.0436, F1: 0.5200

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63221 | val 0.84304
  Epoch 017 - train 0.55431 | val 1.23174
  Classification -> best τ=0.575 (val F1=0.3482)
  Directional -> Accuracy: 0.5303, MCC: 0.0707, F1: 0.6265

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61148 | val 0.70443
  Epoch 011 - train 0.64088 | val 0.72452
  Classification -> best τ=0.545 (val F1=0.2379)
  Directional -> Accuracy: 0.5862, MCC: 0.1841, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62452 | val 0.76383
  Epoch 011 - train 0.65194 | val 0.73643
  Classification -> best τ=0.455 (val F1=0.2390)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59128 | val 0.64816
  Epoch 020 - train 0.50792 | val 1.08700
  Classification -> best τ=0.785 (val F1=0.3807)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55458 | val 1.02335
  Epoch 011 - train 0.60179 | val 1.07299
  Classification -> best τ=0.465 (val F1=0.2774)
  Directional -> Accuracy: 0.4565, MCC: -0.0877, F1: 0.4186

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58853 | val 0.70917
  Epoch 011 - train 0.60537 | val 0.72516
  Classification -> best τ=0.595 (val F1=0.2804)
  Directional -> Accuracy: 0.4884, MCC: -0.0511, F1: 0.5600

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67117 | val 0.71842
  Epoch 014 - train 0.59229 | val 0.80587
  Classification -> best τ=0.380 (val F1=0.3561)
  Directional -> Accuracy: 0.5439, MCC: 0.2554, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63036 | val 0.65480
  Epoch 020 - train 0.46851 | val 1.10467
  Classification -> best τ=0.550 (val F1=0.4208)
  Directional -> Accuracy: 0.5122, MCC: -0.0202, F1: 0.6296

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57761 | val 1.47116
  Epoch 011 - train 0.58217 | val 2.25604
  Classification -> best τ=0.585 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0849, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63381 | val 0.69906
  Epoch 015 - train 0.59932 | val 0.86162
  Classification -> best τ=0.455 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56941 | val 0.92823
  Epoch 011 - train 0.54051 | val 0.97366
  Classification -> best τ=0.565 (val F1=0.2870)
  Directional -> Accuracy: 0.4400, MCC: -0.1811, F1: 0.5625

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60582 | val 0.76306
  Epoch 012 - train 0.59980 | val 0.86225
  Classification -> best τ=0.390 (val F1=0.3602)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66652 | val 0.70175
  Epoch 012 - train 0.62966 | val 0.69856
  Classification -> best τ=0.490 (val F1=0.2182)
  Directional -> Accuracy: 0.5789, MCC: 0.1615, F1: 0.6190

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62623 | val 0.83588
  Epoch 011 - train 0.62768 | val 0.82679
  Classification -> best τ=0.530 (val F1=0.3221)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60495 | val 0.95826
  Epoch 011 - train 0.61263 | val 1.03182
  Classification -> best τ=0.440 (val F1=0.2890)
  Directional -> Accuracy: 0.6119, MCC: 0.2104, F1: 0.7400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59703 | val 0.75941
  Epoch 011 - train 0.59930 | val 0.78246
  Classification -> best τ=0.430 (val F1=0.2251)
  Directional -> Accuracy: 0.7442, MCC: 0.4881, F1: 0.7556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59911 | val 0.75498
  Epoch 011 - train 0.56766 | val 0.86334
  Classification -> best τ=0.375 (val F1=0.1851)
  Directional -> Accuracy: 0.4912, MCC: 0.0663, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56436 | val 0.86043
  Epoch 011 - train 0.49475 | val 0.95731
  Classification -> best τ=0.405 (val F1=0.2403)
  Directional -> Accuracy: 0.4255, MCC: 0.0391, F1: 0.2286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54294 | val 0.66343
  Epoch 015 - train 0.51848 | val 0.69375
  Classification -> best τ=0.440 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.55547 | val 1.48891
  Epoch 012 - train 0.50814 | val 1.51673
  Classification -> best τ=0.490 (val F1=0.0134)
  Directional -> Accuracy: 0.5526, MCC: 0.2134, F1: 0.3200

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60057 | val 0.80171
  Epoch 012 - train 0.63739 | val 0.83299
  Classification -> best τ=0.435 (val F1=0.4082)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61489 | val 0.72252
  Epoch 011 - train 0.62338 | val 0.71993
  Classification -> best τ=0.455 (val F1=0.4159)
  Directional -> Accuracy: 0.5319, MCC: 0.0792, F1: 0.4211

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58341 | val 0.77518
  Epoch 013 - train 0.59006 | val 0.93053
  Classification -> best τ=0.525 (val F1=0.2874)
  Directional -> Accuracy: 0.5455, MCC: 0.0981, F1: 0.5652

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61240 | val 0.69431
  Epoch 020 - train 0.51594 | val 0.67577
  Classification -> best τ=0.505 (val F1=0.2530)
  Directional -> Accuracy: 0.4082, MCC: 0.1149, F1: 0.5672

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61009 | val 0.71374
  Epoch 012 - train 0.59739 | val 0.70929
  Classification -> best τ=0.545 (val F1=0.2028)
  Directional -> Accuracy: 0.5000, MCC: -0.0340, F1: 0.6000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59880 | val 1.67383
  Epoch 012 - train 0.62896 | val 1.24128
  Classification -> best τ=0.535 (val F1=0.4552)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59798 | val 1.07867
  Epoch 012 - train 0.63477 | val 1.17767
  Classification -> best τ=0.405 (val F1=0.2766)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59609 | val 0.93798
  Epoch 011 - train 0.57359 | val 0.97035
  Classification -> best τ=0.460 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 03:40:58,259] Trial 126 finished with value: 0.2642410547106118 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.006116789537775575, 'weight_decay': 1.5573162030720703e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.5418488709059154, 'early_stopping_min_delta': 0.007017365462516287}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 010 - train 0.64949 | val 0.91911
  Epoch 011 - train 0.59043 | val 1.03001
  Classification -> best τ=0.510 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2642410547106118
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66477 | val 0.73363
  Epoch 011 - train 0.61647 | val 0.80673
  Classification -> best τ=0.445 (val F1=0.0020)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55889 | val 1.06238
  Epoch 011 - train 0.55597 | val 1.06201
  Classification -> best τ=0.485 (val F1=0.1236)
  Directional -> Accuracy: 0.5435, MCC: 0.0658, F1: 0.6038

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55641 | val 2.81971
  Epoch 011 - train 0.54973 | val 3.03413
  Classification -> best τ=0.145 (val F1=0.3080)
  Directional -> Accuracy: 0.6383, MCC: 0.3020, F1: 0.7302

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65282 | val 2.51270
  Epoch 014 - train 0.69194 | val 1.69215
  Classification -> best τ=0.525 (val F1=0.1631)
  Directional -> Accuracy: 0.5600, MCC: 0.0804, F1: 0.6733

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64580 | val 1.81872
  Epoch 018 - train 0.50656 | val 3.14100
  Classification -> best τ=0.625 (val F1=0.3244)
  Directional -> Accuracy: 0.6471, MCC: 0.3202, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44982 | val 5.42409
  Epoch 011 - train 0.42480 | val 6.13595
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64880 | val 0.85070
  Epoch 013 - train 0.58842 | val 0.92832
  Classification -> best τ=0.485 (val F1=0.2557)
  Directional -> Accuracy: 0.5217, MCC: 0.1376, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46270 | val 4.28204
  Epoch 011 - train 0.43237 | val 4.78969
  Classification -> best τ=0.575 (val F1=0.1823)
  Directional -> Accuracy: 0.5227, MCC: 0.0906, F1: 0.5333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49209 | val 5.33511
  Epoch 011 - train 0.53894 | val 5.67131
  Classification -> best τ=0.395 (val F1=0.1978)
  Directional -> Accuracy: 0.5918, MCC: 0.2269, F1: 0.6296

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57331 | val 0.80231
  Epoch 012 - train 0.53073 | val 1.05678
  Classification -> best τ=0.610 (val F1=0.2892)
  Directional -> Accuracy: 0.5571, MCC: 0.0123, F1: 0.2051

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52473 | val 2.74907
  Epoch 011 - train 0.56444 | val 3.37516
  Classification -> best τ=0.445 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58630 | val 0.99662
  Epoch 014 - train 0.48536 | val 1.27608
  Classification -> best τ=0.905 (val F1=0.2769)
  Directional -> Accuracy: 0.5172, MCC: 0.0778, F1: 0.1250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58541 | val 2.47295
  Epoch 012 - train 0.56005 | val 1.92494
  Classification -> best τ=0.370 (val F1=0.2596)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61861 | val 0.84416
  Epoch 012 - train 0.57072 | val 1.25523
  Classification -> best τ=0.380 (val F1=0.4005)
  Directional -> Accuracy: 0.5082, MCC: 0.0098, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65453 | val 2.34270
  Epoch 011 - train 0.63244 | val 2.86970
  Classification -> best τ=0.490 (val F1=0.1706)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58597 | val 1.27708
  Epoch 011 - train 0.57752 | val 1.22818
  Classification -> best τ=0.425 (val F1=0.3298)
  Directional -> Accuracy: 0.5571, MCC: 0.0890, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58789 | val 2.22276
  Epoch 011 - train 0.56414 | val 2.35518
  Classification -> best τ=0.825 (val F1=0.2673)
  Directional -> Accuracy: 0.6610, MCC: 0.2429, F1: 0.7872

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57150 | val 2.91326
  Epoch 011 - train 0.55350 | val 3.04842
  Classification -> best τ=0.510 (val F1=0.1734)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58925 | val 1.15880
  Epoch 011 - train 0.57731 | val 1.31791
  Classification -> best τ=0.460 (val F1=0.1632)
  Directional -> Accuracy: 0.4462, MCC: 0.0531, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63800 | val 0.77638
  Epoch 015 - train 0.50340 | val 1.27553
  Classification -> best τ=0.535 (val F1=0.2366)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56853 | val 1.01276
  Epoch 020 - train 0.36760 | val 1.18523
  Epoch 023 - train 0.24396 | val 1.51223
  Classification -> best τ=0.340 (val F1=0.4718)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68015 | val 2.17479
  Epoch 012 - train 0.60979 | val 3.32809
  Classification -> best τ=0.640 (val F1=0.1878)
  Directional -> Accuracy: 0.4242, MCC: -0.2208, F1: 0.0952

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64903 | val 1.21157
  Epoch 013 - train 0.58584 | val 2.15653
  Classification -> best τ=0.780 (val F1=0.2914)
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58437 | val 5.63893
  Epoch 011 - train 0.54194 | val 8.29130
  Classification -> best τ=0.475 (val F1=0.1878)
  Directional -> Accuracy: 0.6061, MCC: 0.2039, F1: 0.5357

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55294 | val 2.63290
  Epoch 013 - train 0.47445 | val 5.67718
  Classification -> best τ=0.515 (val F1=0.4330)
  Directional -> Accuracy: 0.5893, MCC: 0.2195, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47507 | val 2.43140
  Epoch 011 - train 0.42066 | val 2.78823
  Classification -> best τ=0.460 (val F1=0.1925)
  Directional -> Accuracy: 0.5870, MCC: 0.3716, F1: 0.6780

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61795 | val 0.75713
  Epoch 020 - train 0.51119 | val 0.79278
  Epoch 022 - train 0.41319 | val 1.34769
  Classification -> best τ=0.610 (val F1=0.3417)
  Directional -> Accuracy: 0.5814, MCC: 0.1400, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63836 | val 0.77517
  Epoch 013 - train 0.60246 | val 1.20795
  Classification -> best τ=0.315 (val F1=0.2370)
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70744 | val 0.72930
  Epoch 011 - train 0.62918 | val 0.72976
  Classification -> best τ=0.560 (val F1=0.1380)
  Directional -> Accuracy: 0.6098, MCC: 0.2516, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55627 | val 0.87507
  Epoch 011 - train 0.53009 | val 0.99032
  Classification -> best τ=0.610 (val F1=0.5449)
  Directional -> Accuracy: 0.4419, MCC: -0.1142, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66160 | val 1.03107
  Epoch 016 - train 0.50110 | val 1.73114
  Classification -> best τ=0.725 (val F1=0.1161)
  Directional -> Accuracy: 0.3953, MCC: -0.2203, F1: 0.1333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66128 | val 0.75368
  Epoch 011 - train 0.56198 | val 0.74376
  Classification -> best τ=0.485 (val F1=0.2642)
  Directional -> Accuracy: 0.5400, MCC: 0.0771, F1: 0.5660

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68170 | val 0.71549
  Epoch 014 - train 0.60563 | val 0.71314
  Classification -> best τ=0.420 (val F1=0.3396)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54458 | val 1.04638
  Epoch 011 - train 0.63800 | val 1.12262
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64477 | val 0.97440
  Epoch 015 - train 0.51289 | val 1.22897
  Classification -> best τ=0.295 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67150 | val 0.89652
  Epoch 013 - train 0.58724 | val 0.80186
  Classification -> best τ=0.630 (val F1=0.3542)
  Directional -> Accuracy: 0.4627, MCC: 0.0930, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56182 | val 0.81917
  Epoch 012 - train 0.47792 | val 0.71599
  Classification -> best τ=0.430 (val F1=0.2031)
  Directional -> Accuracy: 0.6279, MCC: 0.2967, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48544 | val 3.65571
  Epoch 011 - train 0.46642 | val 2.85734
  Classification -> best τ=0.610 (val F1=0.1851)
  Directional -> Accuracy: 0.3509, MCC: -0.2996, F1: 0.3273

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56840 | val 0.72324
  Epoch 011 - train 0.58778 | val 0.73355
  Classification -> best τ=0.420 (val F1=0.3516)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55719 | val 0.83523
  Epoch 016 - train 0.40100 | val 3.11502
  Classification -> best τ=0.375 (val F1=0.3894)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47958 | val 2.90837
  Epoch 011 - train 0.46963 | val 2.72744
  Classification -> best τ=0.560 (val F1=0.0134)
  Directional -> Accuracy: 0.5000, MCC: 0.0326, F1: 0.3448

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62762 | val 1.24130
  Epoch 014 - train 0.56597 | val 1.66173
  Classification -> best τ=0.400 (val F1=0.2655)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64099 | val 0.72742
  Epoch 014 - train 0.50082 | val 1.03092
  Classification -> best τ=0.430 (val F1=0.4575)
  Directional -> Accuracy: 0.4894, MCC: -0.0617, F1: 0.6364

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52308 | val 1.06409
  Epoch 011 - train 0.47767 | val 0.98321
  Classification -> best τ=0.665 (val F1=0.5609)
  Directional -> Accuracy: 0.5909, MCC: 0.2042, F1: 0.5909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54338 | val 1.31418
  Epoch 012 - train 0.49730 | val 1.77412
  Classification -> best τ=0.715 (val F1=0.2626)
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65376 | val 1.45370
  Epoch 012 - train 0.60006 | val 1.60300
  Classification -> best τ=0.640 (val F1=0.2943)
  Directional -> Accuracy: 0.5179, MCC: 0.1659, F1: 0.2286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62278 | val 1.43817
  Epoch 016 - train 0.47623 | val 1.51047
  Classification -> best τ=0.710 (val F1=0.3883)
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62081 | val 0.94829
  Epoch 012 - train 0.58683 | val 2.17680
  Classification -> best τ=0.535 (val F1=0.1866)
  Directional -> Accuracy: 0.6111, MCC: 0.2488, F1: 0.7042

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68986 | val 1.06995
  Epoch 014 - train 0.54799 | val 3.87513
  Classification -> best τ=0.360 (val F1=0.2060)
  Directional -> Accuracy: 0.4107, MCC: -0.2033, F1: 0.1538

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62640 | val 1.04094

[I 2026-02-20 03:42:36,402] Trial 127 finished with value: 0.255210619702652 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.007942317888417507, 'weight_decay': 9.379967089829423e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6227181839318187, 'early_stopping_min_delta': 0.00909780849797031}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.60672 | val 1.70633
  Classification -> best τ=0.495 (val F1=0.2866)
  Directional -> Accuracy: 0.5082, MCC: 0.1753, F1: 0.6591

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.255210619702652
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59198 | val 1.99819
  Epoch 012 - train 0.56404 | val 2.27321
  Classification -> best τ=0.585 (val F1=0.2851)
  Directional -> Accuracy: 0.5195, MCC: -0.0423, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54328 | val 1.02124
  Epoch 011 - train 0.54160 | val 1.08370
  Classification -> best τ=0.465 (val F1=0.1313)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57644 | val 0.69910
  Epoch 018 - train 0.51792 | val 0.95767
  Classification -> best τ=0.570 (val F1=0.3143)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58841 | val 2.07238
  Epoch 011 - train 0.60311 | val 2.24380
  Classification -> best τ=0.415 (val F1=0.1154)
  Directional -> Accuracy: 0.5067, MCC: -0.0747, F1: 0.6476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50456 | val 1.42487
  Epoch 012 - train 0.49270 | val 1.30814
  Classification -> best τ=0.490 (val F1=0.4513)
  Directional -> Accuracy: 0.8039, MCC: 0.6066, F1: 0.8214

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51206 | val 2.88284
  Epoch 011 - train 0.51022 | val 2.80825
  Classification -> best τ=0.570 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60857 | val 0.78901
  Epoch 011 - train 0.58974 | val 0.78488
  Classification -> best τ=0.410 (val F1=0.3180)
  Directional -> Accuracy: 0.4928, MCC: 0.1234, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52006 | val 1.81324
  Epoch 011 - train 0.53524 | val 1.91645
  Classification -> best τ=0.480 (val F1=0.2594)
  Directional -> Accuracy: 0.6136, MCC: 0.2805, F1: 0.6222

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57001 | val 0.99101
  Epoch 011 - train 0.56161 | val 0.99345
  Classification -> best τ=0.465 (val F1=0.1978)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54618 | val 0.75923
  Epoch 011 - train 0.53125 | val 0.74968
  Classification -> best τ=0.385 (val F1=0.2241)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56150 | val 2.44681
  Epoch 011 - train 0.54490 | val 2.64618
  Classification -> best τ=0.535 (val F1=0.2500)
  Directional -> Accuracy: 0.6000, MCC: 0.2059, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54740 | val 2.33893
  Epoch 011 - train 0.53931 | val 2.51475
  Classification -> best τ=0.410 (val F1=0.1651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54513 | val 2.02742
  Epoch 011 - train 0.52862 | val 2.17936
  Classification -> best τ=0.530 (val F1=0.2778)
  Directional -> Accuracy: 0.5349, MCC: 0.0468, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58649 | val 0.85334
  Epoch 012 - train 0.56558 | val 0.92660
  Classification -> best τ=0.485 (val F1=0.2739)
  Directional -> Accuracy: 0.5246, MCC: 0.0464, F1: 0.6027

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59543 | val 0.76501
  Epoch 011 - train 0.58642 | val 0.74454
  Classification -> best τ=0.535 (val F1=0.1945)
  Directional -> Accuracy: 0.4808, MCC: -0.0065, F1: 0.5574

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54938 | val 1.16411
  Epoch 011 - train 0.54605 | val 1.13368
  Classification -> best τ=0.380 (val F1=0.2927)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57665 | val 1.68001
  Epoch 011 - train 0.55753 | val 1.63414
  Classification -> best τ=0.660 (val F1=0.1857)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57026 | val 1.83385
  Epoch 011 - train 0.56561 | val 2.03302
  Classification -> best τ=0.540 (val F1=0.1923)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58124 | val 1.15239
  Epoch 011 - train 0.55705 | val 1.17145
  Classification -> best τ=0.450 (val F1=0.2013)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53932 | val 0.81444
  Epoch 013 - train 0.50392 | val 1.13822
  Classification -> best τ=0.535 (val F1=0.2371)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53341 | val 0.98619
  Epoch 011 - train 0.53915 | val 1.02959
  Classification -> best τ=0.505 (val F1=0.1198)
  Directional -> Accuracy: 0.5625, MCC: 0.0770, F1: 0.6441

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58311 | val 1.55877
  Epoch 011 - train 0.55515 | val 1.53153
  Classification -> best τ=0.555 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59914 | val 1.02238
  Epoch 011 - train 0.59247 | val 1.13129
  Classification -> best τ=0.585 (val F1=0.3282)
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57578 | val 1.71028
  Epoch 011 - train 0.55994 | val 1.81768
  Classification -> best τ=0.465 (val F1=0.2371)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57980 | val 0.65429
  Epoch 015 - train 0.52577 | val 0.65929
  Classification -> best τ=0.590 (val F1=0.4646)
  Directional -> Accuracy: 0.4464, MCC: -0.0207, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51142 | val 0.87514
  Epoch 011 - train 0.50384 | val 0.88911
  Classification -> best τ=0.480 (val F1=0.1925)
  Directional -> Accuracy: 0.4565, MCC: -0.1424, F1: 0.2857

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59176 | val 0.99583
  Epoch 011 - train 0.60196 | val 1.10400
  Classification -> best τ=0.555 (val F1=0.1818)
  Directional -> Accuracy: 0.4884, MCC: -0.0680, F1: 0.5769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55998 | val 0.87934
  Epoch 011 - train 0.56451 | val 0.91524
  Classification -> best τ=0.480 (val F1=0.1914)
  Directional -> Accuracy: 0.4912, MCC: -0.1288, F1: 0.6329

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58796 | val 0.75730
  Epoch 011 - train 0.55204 | val 0.75332
  Classification -> best τ=0.515 (val F1=0.3844)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57026 | val 0.78797
  Epoch 011 - train 0.55880 | val 0.80320
  Classification -> best τ=0.470 (val F1=0.1171)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57353 | val 0.87045
  Epoch 011 - train 0.54806 | val 0.86546
  Classification -> best τ=0.480 (val F1=0.1667)
  Directional -> Accuracy: 0.4884, MCC: 0.0724, F1: 0.1538

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53916 | val 1.23360
  Epoch 011 - train 0.55521 | val 1.22930
  Classification -> best τ=0.485 (val F1=0.1265)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55250 | val 0.92928
  Epoch 012 - train 0.53223 | val 1.16576
  Classification -> best τ=0.400 (val F1=0.3602)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56148 | val 1.19575
  Epoch 011 - train 0.53957 | val 1.27093
  Classification -> best τ=0.445 (val F1=0.1826)
  Directional -> Accuracy: 0.5263, MCC: 0.0976, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55334 | val 0.87246
  Epoch 011 - train 0.54946 | val 0.85674
  Classification -> best τ=0.460 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54871 | val 0.73104
  Epoch 012 - train 0.52722 | val 0.72662
  Classification -> best τ=0.335 (val F1=0.3521)
  Directional -> Accuracy: 0.5522, MCC: 0.2509, F1: 0.4000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57581 | val 0.76614
  Epoch 011 - train 0.54924 | val 0.78575
  Classification -> best τ=0.550 (val F1=0.1674)
  Directional -> Accuracy: 0.4884, MCC: -0.0162, F1: 0.3889

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54860 | val 0.87860
  Epoch 012 - train 0.52872 | val 0.91883
  Classification -> best τ=0.450 (val F1=0.2207)
  Directional -> Accuracy: 0.4561, MCC: -0.0820, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52939 | val 1.28044
  Epoch 011 - train 0.52975 | val 1.36950
  Classification -> best τ=0.515 (val F1=0.2057)
  Directional -> Accuracy: 0.4468, MCC: -0.0645, F1: 0.4583

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57873 | val 0.64516
  Epoch 017 - train 0.52436 | val 0.70462
  Classification -> best τ=0.585 (val F1=0.4345)
  Directional -> Accuracy: 0.5510, MCC: 0.0341, F1: 0.3889

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59850 | val 1.31799
  Epoch 011 - train 0.54670 | val 1.43742
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54815 | val 1.28854
  Epoch 011 - train 0.51753 | val 1.31802
  Classification -> best τ=0.410 (val F1=0.2535)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58196 | val 1.27706
  Epoch 011 - train 0.59540 | val 1.37496
  Classification -> best τ=0.420 (val F1=0.2382)
  Directional -> Accuracy: 0.5532, MCC: 0.1229, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51247 | val 1.24545
  Epoch 011 - train 0.49434 | val 1.31204
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58597 | val 0.70555
  Epoch 020 - train 0.51433 | val 0.73122
  Classification -> best τ=0.455 (val F1=0.1443)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59494 | val 0.88513
  Epoch 011 - train 0.59729 | val 0.89702
  Classification -> best τ=0.490 (val F1=0.1387)
  Directional -> Accuracy: 0.4286, MCC: -0.2777, F1: 0.5897

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54658 | val 1.14197
  Epoch 011 - train 0.55260 | val 1.22511
  Classification -> best τ=0.565 (val F1=0.4552)
  Directional -> Accuracy: 0.5439, MCC: 0.1332, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56497 | val 0.82973
  Epoch 011 - train 0.54886 | val 0.84266
  Classification -> best τ=0.530 (val F1=0.1626)
  Directional -> Accuracy: 0.5000, MCC: 0.1324, F1: 0.0690

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54433 | val 0.95126
  Epoch 013 - train 0.53619 | val 1.11712
  Classification -> best τ=0.595 (val F1=0.1085)
  Directional -> Accuracy: 0.4643, MCC: -0.0879, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58132 | val 0.73969
  Epoch 011 - train 0.58588 | val 0.77351

[I 2026-02-20 03:43:52,055] Trial 128 finished with value: 0.2302405331284762 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0003304143043899059, 'weight_decay': 1.4034161679143224e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.7782311465153905, 'early_stopping_min_delta': 0.008761382155270215}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.545 (val F1=0.2544)
  Directional -> Accuracy: 0.4426, MCC: -0.1370, F1: 0.3200

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2302405331284762
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59410 | val 0.85373
  Epoch 016 - train 0.49036 | val 1.78108
  Classification -> best τ=0.580 (val F1=0.1989)
  Directional -> Accuracy: 0.5065, MCC: -0.1072, F1: 0.0952

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55568 | val 0.74557
  Epoch 011 - train 0.48155 | val 0.82085
  Classification -> best τ=0.425 (val F1=0.1433)
  Directional -> Accuracy: 0.5217, MCC: -0.1870, F1: 0.6857

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53446 | val 0.88515
  Epoch 011 - train 0.49784 | val 1.14985
  Classification -> best τ=0.555 (val F1=0.1948)
  Directional -> Accuracy: 0.4255, MCC: -0.1737, F1: 0.5091

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62323 | val 1.10769
  Epoch 012 - train 0.55666 | val 2.07244
  Classification -> best τ=0.380 (val F1=0.2163)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43933 | val 2.40990
  Epoch 011 - train 0.40306 | val 3.60031
  Classification -> best τ=0.430 (val F1=0.4427)
  Directional -> Accuracy: 0.7451, MCC: 0.5039, F1: 0.7347

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43578 | val 2.80204
  Epoch 011 - train 0.39736 | val 3.21180
  Classification -> best τ=0.445 (val F1=0.2582)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59216 | val 0.95466
  Epoch 012 - train 0.57621 | val 1.02109
  Classification -> best τ=0.345 (val F1=0.2013)
  Directional -> Accuracy: 0.4493, MCC: -0.0307, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41133 | val 1.83726
  Epoch 015 - train 0.42246 | val 1.97729
  Classification -> best τ=0.420 (val F1=0.0548)
  Directional -> Accuracy: 0.3864, MCC: -0.1436, F1: 0.5091

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57423 | val 1.29940
  Epoch 011 - train 0.56426 | val 1.23319
  Classification -> best τ=0.620 (val F1=0.3461)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52120 | val 0.76630
  Epoch 011 - train 0.49972 | val 0.80558
  Classification -> best τ=0.620 (val F1=0.2436)
  Directional -> Accuracy: 0.5143, MCC: -0.0085, F1: 0.3929

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57374 | val 3.03497
  Epoch 011 - train 0.53898 | val 3.50204
  Classification -> best τ=0.690 (val F1=0.3151)
  Directional -> Accuracy: 0.5200, MCC: 0.0537, F1: 0.5385

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49811 | val 3.22537
  Epoch 012 - train 0.47796 | val 3.72759
  Classification -> best τ=0.255 (val F1=0.1578)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54917 | val 2.61790
  Epoch 012 - train 0.46552 | val 3.20211
  Classification -> best τ=0.430 (val F1=0.2108)
  Directional -> Accuracy: 0.5814, MCC: 0.1280, F1: 0.4375

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59318 | val 0.63223
  Epoch 011 - train 0.57100 | val 0.65203
  Classification -> best τ=0.365 (val F1=0.2574)
  Directional -> Accuracy: 0.5574, MCC: 0.1602, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63771 | val 0.67917
  Epoch 020 - train 0.42871 | val 1.32185
  Classification -> best τ=0.565 (val F1=0.2395)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56966 | val 1.29045
  Epoch 015 - train 0.45412 | val 1.45700
  Classification -> best τ=0.530 (val F1=0.3265)
  Directional -> Accuracy: 0.5857, MCC: 0.1674, F1: 0.6133

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60577 | val 1.70297
  Epoch 013 - train 0.49510 | val 1.69184
  Classification -> best τ=0.805 (val F1=0.2294)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64602 | val 1.03037
  Epoch 019 - train 0.47192 | val 1.72749
  Classification -> best τ=0.460 (val F1=0.2893)
  Directional -> Accuracy: 0.6447, MCC: 0.2082, F1: 0.7477

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56260 | val 0.99612
  Epoch 011 - train 0.55443 | val 0.95217
  Classification -> best τ=0.245 (val F1=0.2117)
  Directional -> Accuracy: 0.5538, MCC: 0.1985, F1: 0.4912

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53965 | val 1.12948
  Epoch 011 - train 0.50831 | val 1.03402
  Classification -> best τ=0.230 (val F1=0.2434)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52169 | val 0.70201
  Epoch 018 - train 0.31589 | val 1.84657
  Classification -> best τ=0.670 (val F1=0.2892)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57123 | val 1.25780
  Epoch 011 - train 0.53232 | val 1.40035
  Classification -> best τ=0.660 (val F1=0.1248)
  Directional -> Accuracy: 0.5303, MCC: 0.1054, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61831 | val 1.13406
  Epoch 011 - train 0.60948 | val 1.35974
  Classification -> best τ=0.605 (val F1=0.1826)
  Directional -> Accuracy: 0.4483, MCC: 0.0461, F1: 0.1111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55877 | val 1.06622
  Epoch 013 - train 0.49387 | val 1.21214
  Classification -> best τ=0.585 (val F1=0.2494)
  Directional -> Accuracy: 0.5000, MCC: -0.0260, F1: 0.3529

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57507 | val 0.86072
  Epoch 020 - train 0.37180 | val 1.23067
  Epoch 021 - train 0.36473 | val 1.21564
  Classification -> best τ=0.540 (val F1=0.4795)
  Directional -> Accuracy: 0.4643, MCC: 0.0136, F1: 0.2105

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55161 | val 0.77613
  Epoch 011 - train 0.50779 | val 1.06345
  Classification -> best τ=0.445 (val F1=0.2857)
  Directional -> Accuracy: 0.5435, MCC: -0.0245, F1: 0.1600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62373 | val 1.30323
  Epoch 013 - train 0.54917 | val 1.39045
  Classification -> best τ=0.625 (val F1=0.2422)
  Directional -> Accuracy: 0.5581, MCC: 0.1297, F1: 0.5778

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60103 | val 0.95256
  Epoch 014 - train 0.54747 | val 1.11780
  Classification -> best τ=0.385 (val F1=0.2848)
  Directional -> Accuracy: 0.5439, MCC: 0.3032, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59473 | val 0.98341
  Epoch 013 - train 0.47917 | val 1.16171
  Classification -> best τ=0.385 (val F1=0.3069)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47005 | val 5.36422
  Epoch 011 - train 0.48791 | val 5.57816
  Classification -> best τ=0.685 (val F1=0.4449)
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56755 | val 0.79282
  Epoch 014 - train 0.44882 | val 0.75814
  Classification -> best τ=0.395 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46988 | val 1.74612
  Epoch 011 - train 0.50284 | val 1.66964
  Classification -> best τ=0.425 (val F1=0.2290)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55762 | val 0.90824
  Epoch 011 - train 0.50952 | val 1.02223
  Classification -> best τ=0.220 (val F1=0.3602)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51213 | val 1.08300
  Epoch 011 - train 0.45105 | val 1.50970
  Classification -> best τ=0.400 (val F1=0.0925)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50778 | val 0.72772
  Epoch 011 - train 0.48095 | val 0.88059
  Classification -> best τ=0.470 (val F1=0.3464)
  Directional -> Accuracy: 0.5000, MCC: 0.0780, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57448 | val 0.80360
  Epoch 011 - train 0.58141 | val 0.82094
  Classification -> best τ=0.325 (val F1=0.3180)
  Directional -> Accuracy: 0.5075, MCC: 0.1239, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58266 | val 1.17375
  Epoch 012 - train 0.57556 | val 0.77682
  Classification -> best τ=0.570 (val F1=0.2741)
  Directional -> Accuracy: 0.6744, MCC: 0.3671, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51250 | val 2.15960
  Epoch 011 - train 0.45355 | val 1.06038
  Classification -> best τ=0.240 (val F1=0.2390)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51023 | val 2.28427
  Epoch 012 - train 0.42797 | val 2.92521
  Classification -> best τ=0.400 (val F1=0.2232)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53959 | val 1.00895
  Epoch 011 - train 0.56522 | val 0.74031
  Classification -> best τ=0.525 (val F1=0.3957)
  Directional -> Accuracy: 0.3878, MCC: -0.0228, F1: 0.5161

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61689 | val 1.77686
  Epoch 011 - train 0.64771 | val 1.68311
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56793 | val 1.88093
  Epoch 011 - train 0.50120 | val 1.83368
  Classification -> best τ=0.390 (val F1=0.1723)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50013 | val 1.00871
  Epoch 011 - train 0.48655 | val 1.07106
  Classification -> best τ=0.445 (val F1=0.3669)
  Directional -> Accuracy: 0.5106, MCC: 0.0081, F1: 0.6462

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50711 | val 2.18508
  Epoch 011 - train 0.48596 | val 2.34854
  Classification -> best τ=0.590 (val F1=0.0934)
  Directional -> Accuracy: 0.3864, MCC: -0.2503, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64299 | val 3.90648
  Epoch 011 - train 0.57127 | val 4.34062
  Classification -> best τ=0.630 (val F1=0.1890)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60372 | val 5.10780
  Epoch 012 - train 0.54339 | val 5.70169
  Classification -> best τ=0.515 (val F1=0.2958)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56625 | val 1.69407
  Epoch 014 - train 0.43118 | val 1.45694
  Classification -> best τ=0.505 (val F1=0.3535)
  Directional -> Accuracy: 0.5088, MCC: 0.0799, F1: 0.6316

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62414 | val 0.72049
  Epoch 014 - train 0.55912 | val 0.97010
  Classification -> best τ=0.505 (val F1=0.2874)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56535 | val 0.72927
  Epoch 014 - train 0.43705 | val 1.29370
  Classification -> best τ=0.605 (val F1=0.2747)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68499 | val 0.83988

[I 2026-02-20 03:45:13,176] Trial 129 finished with value: 0.2549122915612296 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.00450899111061097, 'weight_decay': 7.160484887882833e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.7073655757442533, 'early_stopping_min_delta': 0.007979531167591024}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.59764 | val 1.02772
  Classification -> best τ=0.300 (val F1=0.3103)
  Directional -> Accuracy: 0.6066, MCC: 0.2291, F1: 0.6364

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2549122915612296
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64558 | val 0.66962
  Epoch 013 - train 0.64425 | val 0.67010
  Classification -> best τ=0.535 (val F1=0.1989)
  Directional -> Accuracy: 0.5455, MCC: 0.0392, F1: 0.2553

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64371 | val 0.73913
  Epoch 011 - train 0.64208 | val 0.74099
  Classification -> best τ=0.495 (val F1=0.0280)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65467 | val 0.68552
  Epoch 020 - train 0.63744 | val 0.69682
  Epoch 021 - train 0.62881 | val 0.69886
  Classification -> best τ=0.475 (val F1=0.2943)
  Directional -> Accuracy: 0.4681, MCC: -0.0653, F1: 0.4898

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67429 | val 0.96287
  Epoch 011 - train 0.65627 | val 0.99017
  Classification -> best τ=0.515 (val F1=0.2065)
  Directional -> Accuracy: 0.5067, MCC: 0.0646, F1: 0.3934

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60277 | val 0.72670
  Epoch 014 - train 0.61089 | val 0.75732
  Classification -> best τ=0.445 (val F1=0.4711)
  Directional -> Accuracy: 0.6863, MCC: 0.3723, F1: 0.7333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62811 | val 1.35813
  Epoch 011 - train 0.62374 | val 1.35918
  Classification -> best τ=0.575 (val F1=0.3273)
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65932 | val 0.96273
  Epoch 011 - train 0.65732 | val 0.96787
  Classification -> best τ=0.485 (val F1=0.2001)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65292 | val 0.80852
  Epoch 011 - train 0.64823 | val 0.82549
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63005 | val 0.68041
  Epoch 020 - train 0.61726 | val 0.67892
  Epoch 021 - train 0.62601 | val 0.68059
  Classification -> best τ=0.550 (val F1=0.3475)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65211 | val 0.76427
  Epoch 011 - train 0.64821 | val 0.76085
  Classification -> best τ=0.445 (val F1=0.2220)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63274 | val 1.21001
  Epoch 011 - train 0.65437 | val 1.22216
  Classification -> best τ=0.550 (val F1=0.2562)
  Directional -> Accuracy: 0.4600, MCC: -0.0655, F1: 0.4906

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62241 | val 1.05607
  Epoch 011 - train 0.63611 | val 1.07072
  Classification -> best τ=0.535 (val F1=0.2080)
  Directional -> Accuracy: 0.5517, MCC: 0.1037, F1: 0.5667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62258 | val 0.89670
  Epoch 014 - train 0.60963 | val 0.95073
  Classification -> best τ=0.660 (val F1=0.2108)
  Directional -> Accuracy: 0.4651, MCC: -0.1185, F1: 0.3030

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65445 | val 0.66555
  Epoch 014 - train 0.64603 | val 0.67151
  Classification -> best τ=0.315 (val F1=0.3268)
  Directional -> Accuracy: 0.5574, MCC: 0.1142, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66377 | val 0.81426
  Epoch 011 - train 0.64236 | val 0.81274
  Classification -> best τ=0.560 (val F1=0.2743)
  Directional -> Accuracy: 0.5577, MCC: 0.1512, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62353 | val 0.78476
  Epoch 011 - train 0.61159 | val 0.79355
  Classification -> best τ=0.515 (val F1=0.2516)
  Directional -> Accuracy: 0.5714, MCC: 0.1447, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62731 | val 1.43313
  Epoch 011 - train 0.63252 | val 1.44429
  Classification -> best τ=0.505 (val F1=0.0349)
  Directional -> Accuracy: 0.6441, MCC: 0.1703, F1: 0.7789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63993 | val 0.76059
  Epoch 015 - train 0.64573 | val 0.79975
  Classification -> best τ=0.680 (val F1=0.1923)
  Directional -> Accuracy: 0.3947, MCC: -0.1200, F1: 0.2812

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63741 | val 0.79767
  Epoch 011 - train 0.63485 | val 0.80044
  Classification -> best τ=0.510 (val F1=0.0054)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63411 | val 0.79608
  Epoch 013 - train 0.63089 | val 0.78305
  Classification -> best τ=0.515 (val F1=0.1899)
  Directional -> Accuracy: 0.4933, MCC: -0.0727, F1: 0.6122

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64362 | val 0.82418
  Epoch 011 - train 0.63997 | val 0.82946
  Classification -> best τ=0.500 (val F1=0.1474)
  Directional -> Accuracy: 0.4167, MCC: 0.0325, F1: 0.2222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65951 | val 0.76250
  Epoch 011 - train 0.66557 | val 0.76851
  Classification -> best τ=0.520 (val F1=0.1558)
  Directional -> Accuracy: 0.4848, MCC: -0.0442, F1: 0.1905

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66224 | val 0.80476
  Epoch 012 - train 0.65147 | val 0.81871
  Classification -> best τ=0.540 (val F1=0.2653)
  Directional -> Accuracy: 0.5345, MCC: 0.1064, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65136 | val 1.32677
  Epoch 011 - train 0.64115 | val 1.35661
  Classification -> best τ=0.465 (val F1=0.2049)
  Directional -> Accuracy: 0.4848, MCC: -0.0196, F1: 0.5143

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65075 | val 0.66505
  Epoch 018 - train 0.63770 | val 0.68111
  Classification -> best τ=0.450 (val F1=0.3780)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62365 | val 0.75740
  Epoch 011 - train 0.61723 | val 0.76709
  Classification -> best τ=0.525 (val F1=0.1925)
  Directional -> Accuracy: 0.4783, MCC: 0.1870, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66715 | val 0.71005
  Epoch 016 - train 0.66546 | val 0.75424
  Classification -> best τ=0.555 (val F1=0.1874)
  Directional -> Accuracy: 0.5581, MCC: 0.0852, F1: 0.6275

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67460 | val 0.64961
  Epoch 015 - train 0.65076 | val 0.65920
  Classification -> best τ=0.420 (val F1=0.4443)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65740 | val 0.72451
  Epoch 011 - train 0.65271 | val 0.72475
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64128 | val 0.72118
  Epoch 011 - train 0.65677 | val 0.72337
  Classification -> best τ=0.485 (val F1=0.1869)
  Directional -> Accuracy: 0.4884, MCC: -0.0528, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66702 | val 0.75267
  Epoch 011 - train 0.67382 | val 0.75149
  Classification -> best τ=0.535 (val F1=0.1005)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62912 | val 0.82248
  Epoch 011 - train 0.64486 | val 0.82668
  Classification -> best τ=0.500 (val F1=0.0757)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63729 | val 0.65746
  Epoch 020 - train 0.60515 | val 0.64514
  Epoch 023 - train 0.60849 | val 0.64860
  Classification -> best τ=0.390 (val F1=0.3520)
  Directional -> Accuracy: 0.5479, MCC: 0.1207, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67050 | val 0.78406
  Epoch 011 - train 0.64344 | val 0.80143
  Classification -> best τ=0.485 (val F1=0.2357)
  Directional -> Accuracy: 0.4211, MCC: -0.1588, F1: 0.4500

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64622 | val 0.97193
  Epoch 011 - train 0.66073 | val 0.97077
  Classification -> best τ=0.505 (val F1=0.0230)
  Directional -> Accuracy: 0.5682, MCC: 0.2471, F1: 0.6780

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63079 | val 0.65348
  Epoch 016 - train 0.60900 | val 0.65963
  Classification -> best τ=0.335 (val F1=0.3936)
  Directional -> Accuracy: 0.5522, MCC: 0.1393, F1: 0.5312

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66650 | val 0.69420
  Epoch 011 - train 0.65780 | val 0.69372
  Classification -> best τ=0.480 (val F1=0.2297)
  Directional -> Accuracy: 0.4651, MCC: -0.0746, F1: 0.5106

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61979 | val 0.79064
  Epoch 011 - train 0.61132 | val 0.79475
  Classification -> best τ=0.460 (val F1=0.1677)
  Directional -> Accuracy: 0.5263, MCC: 0.0556, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64474 | val 0.81514
  Epoch 011 - train 0.64263 | val 0.82296
  Classification -> best τ=0.480 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65991 | val 0.65205
  Epoch 020 - train 0.60759 | val 0.62003
  Epoch 030 - train 0.58623 | val 0.61386
  Classification -> best τ=0.410 (val F1=0.4386)
  Directional -> Accuracy: 0.4082, MCC: 0.1572, F1: 0.5538

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66314 | val 0.75437
  Epoch 011 - train 0.63752 | val 0.76082
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65248 | val 0.88509
  Epoch 011 - train 0.62847 | val 0.89403
  Classification -> best τ=0.460 (val F1=0.1210)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64418 | val 0.74482
  Epoch 011 - train 0.65429 | val 0.73787
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62975 | val 0.76507
  Epoch 011 - train 0.63444 | val 0.77060
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66767 | val 0.78740
  Epoch 011 - train 0.66348 | val 0.78853
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65230 | val 0.82732
  Epoch 011 - train 0.66104 | val 0.82322
  Classification -> best τ=0.405 (val F1=0.1328)
  Directional -> Accuracy: 0.6607, MCC: 0.3250, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64980 | val 0.94273
  Epoch 011 - train 0.63424 | val 0.95172
  Classification -> best τ=0.535 (val F1=0.0996)
  Directional -> Accuracy: 0.5263, MCC: 0.1409, F1: 0.6494

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65472 | val 0.69922
  Epoch 013 - train 0.66063 | val 0.70490
  Classification -> best τ=0.530 (val F1=0.2360)
  Directional -> Accuracy: 0.6111, MCC: 0.2825, F1: 0.4878

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63573 | val 0.71824
  Epoch 013 - train 0.63630 | val 0.71771
  Classification -> best τ=0.555 (val F1=0.1801)
  Directional -> Accuracy: 0.4643, MCC: -0.1397, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66423 | val 0.67891
  Epoch 020 - train 0.64944 | val 0.73786
  Epoch 021 - train 0.63827 | val 0.74987

[I 2026-02-20 03:46:37,800] Trial 130 finished with value: 0.19237788298275504 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 6.205206474213295e-05, 'weight_decay': 3.455429956891048e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6285146131110803, 'early_stopping_min_delta': 0.008355808475751502}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.470 (val F1=0.2187)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19237788298275504
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64451 | val 1.00607
  Epoch 017 - train 0.51571 | val 2.61229
  Classification -> best τ=0.465 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57031 | val 1.65710
  Epoch 012 - train 0.51231 | val 1.33087
  Classification -> best τ=0.405 (val F1=0.3126)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57909 | val 0.78120
  Epoch 012 - train 0.55520 | val 1.00479
  Classification -> best τ=0.510 (val F1=0.1979)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58761 | val 1.08456
  Epoch 011 - train 0.57589 | val 1.15140
  Classification -> best τ=0.445 (val F1=0.2651)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58247 | val 2.57967
  Epoch 014 - train 0.44006 | val 4.75760
  Classification -> best τ=0.490 (val F1=0.4851)
  Directional -> Accuracy: 0.6200, MCC: 0.2446, F1: 0.6885

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59793 | val 0.98955
  Epoch 014 - train 0.39727 | val 2.20721
  Classification -> best τ=0.645 (val F1=0.1684)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64054 | val 0.95313
  Epoch 013 - train 0.60709 | val 2.33911
  Classification -> best τ=0.500 (val F1=0.1765)
  Directional -> Accuracy: 0.5147, MCC: 0.1463, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51434 | val 1.56684
  Epoch 015 - train 0.25764 | val 7.18389
  Classification -> best τ=0.520 (val F1=0.2753)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51793 | val 3.83128
  Epoch 013 - train 0.38501 | val 3.58335
  Classification -> best τ=0.355 (val F1=0.2443)
  Directional -> Accuracy: 0.4583, MCC: 0.0258, F1: 0.5938

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56071 | val 1.58833
  Epoch 012 - train 0.54399 | val 0.84300
  Classification -> best τ=0.620 (val F1=0.2693)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60608 | val 0.96777
  Epoch 013 - train 0.51241 | val 1.07753
  Classification -> best τ=0.435 (val F1=0.3231)
  Directional -> Accuracy: 0.6122, MCC: 0.2041, F1: 0.5128

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51061 | val 1.21390
  Epoch 011 - train 0.50924 | val 1.85258
  Classification -> best τ=0.485 (val F1=0.2487)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52416 | val 4.73176
  Epoch 011 - train 0.49004 | val 4.71750
  Classification -> best τ=0.755 (val F1=0.0272)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.0952

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60455 | val 1.37023
  Epoch 012 - train 0.57758 | val 1.52384
  Classification -> best τ=0.515 (val F1=0.3596)
  Directional -> Accuracy: 0.5167, MCC: 0.0385, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55157 | val 2.87464
  Epoch 011 - train 0.48207 | val 3.59575
  Classification -> best τ=0.505 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62381 | val 1.01599
  Epoch 013 - train 0.55845 | val 1.16438
  Classification -> best τ=0.400 (val F1=0.2155)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67023 | val 0.98095
  Epoch 011 - train 0.62555 | val 1.15166
  Classification -> best τ=0.720 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58707 | val 1.55559
  Epoch 013 - train 0.56143 | val 1.99797
  Classification -> best τ=0.435 (val F1=0.1612)
  Directional -> Accuracy: 0.5333, MCC: 0.1373, F1: 0.5070

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59464 | val 1.36568
  Epoch 012 - train 0.55477 | val 1.86938
  Classification -> best τ=0.375 (val F1=0.2522)
  Directional -> Accuracy: 0.5781, MCC: 0.2042, F1: 0.5574

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59147 | val 1.37963
  Epoch 011 - train 0.57154 | val 1.42606
  Classification -> best τ=0.755 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67474 | val 2.17072
  Epoch 014 - train 0.54583 | val 0.71957
  Classification -> best τ=0.550 (val F1=0.3732)
  Directional -> Accuracy: 0.4468, MCC: 0.1299, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59435 | val 2.07418
  Epoch 012 - train 0.59611 | val 4.15962
  Classification -> best τ=0.530 (val F1=0.0905)
  Directional -> Accuracy: 0.5077, MCC: 0.0384, F1: 0.2381

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63953 | val 0.72110
  Epoch 018 - train 0.57730 | val 1.03102
  Classification -> best τ=0.540 (val F1=0.3421)
  Directional -> Accuracy: 0.4211, MCC: -0.1512, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67135 | val 1.16401
  Epoch 017 - train 0.55924 | val 1.29997
  Classification -> best τ=0.460 (val F1=0.2192)
  Directional -> Accuracy: 0.4923, MCC: 0.0112, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57587 | val 1.54831
  Epoch 013 - train 0.48568 | val 2.57577
  Classification -> best τ=0.510 (val F1=0.4723)
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57987 | val 1.77793
  Epoch 011 - train 0.59246 | val 1.85726
  Classification -> best τ=0.560 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56260 | val 1.94731
  Epoch 011 - train 0.56772 | val 10.98227
  Classification -> best τ=0.505 (val F1=0.0595)
  Directional -> Accuracy: 0.6190, MCC: 0.2340, F1: 0.6522

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57184 | val 1.01112
  Epoch 012 - train 0.53135 | val 1.55179
  Classification -> best τ=0.480 (val F1=0.1778)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57592 | val 0.85193
  Epoch 011 - train 0.54536 | val 0.74429
  Classification -> best τ=0.635 (val F1=0.0591)
  Directional -> Accuracy: 0.5500, MCC: 0.0580, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54872 | val 0.73116
  Epoch 011 - train 0.52468 | val 0.75099
  Classification -> best τ=0.395 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0155, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55655 | val 1.00235
  Epoch 014 - train 0.44613 | val 1.54991
  Classification -> best τ=0.615 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69759 | val 0.78515
  Epoch 016 - train 0.60216 | val 0.86585
  Classification -> best τ=0.340 (val F1=0.3987)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65885 | val 0.62433
  Epoch 020 - train 0.57994 | val 1.01053
  Classification -> best τ=0.375 (val F1=0.4023)
  Directional -> Accuracy: 0.5278, MCC: 0.0905, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51254 | val 2.40511
  Epoch 011 - train 0.50214 | val 2.51616
  Classification -> best τ=0.270 (val F1=0.1607)
  Directional -> Accuracy: 0.4884, MCC: -0.0179, F1: 0.5417

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69247 | val 0.81543
  Epoch 017 - train 0.48920 | val 1.32880
  Classification -> best τ=0.465 (val F1=0.4292)
  Directional -> Accuracy: 0.5303, MCC: 0.2518, F1: 0.3404

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50652 | val 3.58842
  Epoch 014 - train 0.35383 | val 1.29041
  Classification -> best τ=0.515 (val F1=0.1822)
  Directional -> Accuracy: 0.4762, MCC: -0.0107, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56627 | val 1.92613
  Epoch 011 - train 0.56766 | val 2.08393
  Classification -> best τ=0.600 (val F1=0.2450)
  Directional -> Accuracy: 0.4643, MCC: -0.0667, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60054 | val 1.76259
  Epoch 011 - train 0.53674 | val 3.17902
  Classification -> best τ=0.470 (val F1=0.3397)
  Directional -> Accuracy: 0.5870, MCC: 0.0324, F1: 0.7164

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54975 | val 0.77295
  Epoch 020 - train 0.51300 | val 1.05397
  Epoch 022 - train 0.34890 | val 0.87134
  Classification -> best τ=0.360 (val F1=0.4855)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57830 | val 3.58067
  Epoch 012 - train 0.50797 | val 1.76722
  Classification -> best τ=0.620 (val F1=0.2633)
  Directional -> Accuracy: 0.5000, MCC: 0.0267, F1: 0.6263

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48378 | val 1.94802
  Epoch 012 - train 0.42168 | val 1.70194
  Classification -> best τ=0.440 (val F1=0.0271)
  Directional -> Accuracy: 0.4889, MCC: -0.0048, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47489 | val 2.80949
  Epoch 012 - train 0.41797 | val 3.46928
  Classification -> best τ=0.605 (val F1=0.4082)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66817 | val 0.80057
  Epoch 020 - train 0.54487 | val 0.88419
  Epoch 021 - train 0.50832 | val 0.78254
  Classification -> best τ=0.640 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61005 | val 0.96662
  Epoch 011 - train 0.62382 | val 1.34050
  Classification -> best τ=0.630 (val F1=0.2681)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48671 | val 1.55893
  Epoch 012 - train 0.50323 | val 1.21301
  Classification -> best τ=0.475 (val F1=0.3526)
  Directional -> Accuracy: 0.5536, MCC: 0.1555, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65667 | val 1.20659
  Epoch 011 - train 0.61316 | val 0.87159
  Classification -> best τ=0.470 (val F1=0.2486)
  Directional -> Accuracy: 0.5472, MCC: 0.1004, F1: 0.6471

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54292 | val 3.59328
  Epoch 011 - train 0.56768 | val 3.71229
  Classification -> best τ=0.725 (val F1=0.2291)
  Directional -> Accuracy: 0.3818, MCC: -0.2940, F1: 0.0556

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58279 | val 0.91088

[I 2026-02-20 03:48:45,875] Trial 131 finished with value: 0.2583463651634716 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009952606062447435, 'weight_decay': 1.9722547647165445e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.21310991177331218, 'early_stopping_min_delta': 0.005300659082616811}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.55313 | val 1.54238
  Classification -> best τ=0.555 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2583463651634716
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51610 | val 1.04749
  Epoch 011 - train 0.48405 | val 1.63195
  Classification -> best τ=0.490 (val F1=0.3286)
  Directional -> Accuracy: 0.6053, MCC: 0.1868, F1: 0.3750

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40672 | val 0.76683
  Epoch 012 - train 0.36026 | val 0.83801
  Classification -> best τ=0.400 (val F1=0.2110)
  Directional -> Accuracy: 0.5556, MCC: 0.0225, F1: 0.6774

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54216 | val 1.12360
  Epoch 014 - train 0.37472 | val 1.62304
  Classification -> best τ=0.585 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42065 | val 4.79981
  Epoch 011 - train 0.40700 | val 3.72966
  Classification -> best τ=0.190 (val F1=0.0520)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50335 | val 0.88949
  Epoch 014 - train 0.30890 | val 1.51467
  Classification -> best τ=0.530 (val F1=0.4611)
  Directional -> Accuracy: 0.7600, MCC: 0.5224, F1: 0.7600

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32501 | val 1.03709
  Epoch 011 - train 0.29345 | val 1.25398
  Classification -> best τ=0.695 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.50825 | val 1.48382
  Epoch 012 - train 0.41278 | val 1.86865
  Classification -> best τ=0.340 (val F1=0.2220)
  Directional -> Accuracy: 0.4559, MCC: 0.1465, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36005 | val 2.21375
  Epoch 012 - train 0.31878 | val 2.69639
  Classification -> best τ=0.480 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38573 | val 1.31519
  Epoch 011 - train 0.38185 | val 1.25017
  Classification -> best τ=0.555 (val F1=0.1608)
  Directional -> Accuracy: 0.6250, MCC: 0.2469, F1: 0.5909

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45987 | val 1.15475
  Epoch 012 - train 0.37603 | val 1.25255
  Classification -> best τ=0.445 (val F1=0.1607)
  Directional -> Accuracy: 0.4638, MCC: -0.1168, F1: 0.3273

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50323 | val 0.75816
  Epoch 013 - train 0.37436 | val 1.05017
  Classification -> best τ=0.505 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41527 | val 1.93511
  Epoch 011 - train 0.36806 | val 2.25353
  Classification -> best τ=0.315 (val F1=0.1193)
  Directional -> Accuracy: 0.5789, MCC: 0.2796, F1: 0.7073

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41307 | val 2.05983
  Epoch 012 - train 0.35116 | val 2.68135
  Classification -> best τ=0.465 (val F1=0.2083)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52072 | val 1.45647
  Epoch 012 - train 0.44136 | val 2.38767
  Classification -> best τ=0.515 (val F1=0.3774)
  Directional -> Accuracy: 0.5500, MCC: 0.1028, F1: 0.5970

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45219 | val 1.19558
  Epoch 011 - train 0.42867 | val 1.73786
  Classification -> best τ=0.565 (val F1=0.3516)
  Directional -> Accuracy: 0.4118, MCC: -0.1489, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47840 | val 1.12735
  Epoch 011 - train 0.47835 | val 1.08811
  Classification -> best τ=0.510 (val F1=0.4077)
  Directional -> Accuracy: 0.6087, MCC: 0.2144, F1: 0.7033

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45594 | val 5.90088
  Epoch 011 - train 0.41879 | val 6.53873
  Classification -> best τ=0.930 (val F1=0.0354)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51899 | val 0.72520
  Epoch 013 - train 0.40527 | val 1.88443
  Classification -> best τ=0.475 (val F1=0.2621)
  Directional -> Accuracy: 0.6133, MCC: 0.1430, F1: 0.7184

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48128 | val 1.83025
  Epoch 012 - train 0.39810 | val 1.58362
  Classification -> best τ=0.645 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44621 | val 1.37339
  Epoch 011 - train 0.42798 | val 1.63947
  Classification -> best τ=0.580 (val F1=0.2676)
  Directional -> Accuracy: 0.4865, MCC: 0.0843, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47342 | val 1.43859
  Epoch 015 - train 0.29478 | val 1.66471
  Classification -> best τ=0.265 (val F1=0.3678)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.48036 | val 2.29096
  Epoch 011 - train 0.47600 | val 2.25275
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56455 | val 0.83662
  Epoch 011 - train 0.50255 | val 0.95447
  Classification -> best τ=0.595 (val F1=0.2799)
  Directional -> Accuracy: 0.4211, MCC: -0.1141, F1: 0.2979

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45635 | val 1.69360
  Epoch 011 - train 0.41301 | val 1.42054
  Classification -> best τ=0.390 (val F1=0.1736)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44819 | val 2.23270
  Epoch 012 - train 0.37891 | val 2.64387
  Classification -> best τ=0.585 (val F1=0.4629)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38909 | val 2.83657
  Epoch 011 - train 0.36393 | val 3.23482
  Classification -> best τ=0.680 (val F1=0.3669)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46073 | val 1.97946
  Epoch 011 - train 0.40479 | val 2.18683
  Classification -> best τ=0.515 (val F1=0.1132)
  Directional -> Accuracy: 0.5714, MCC: 0.1667, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44774 | val 2.27301
  Epoch 011 - train 0.40723 | val 2.31796
  Classification -> best τ=0.440 (val F1=0.1388)
  Directional -> Accuracy: 0.5714, MCC: 0.3394, F1: 0.3684

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40711 | val 1.55026
  Epoch 011 - train 0.37674 | val 1.69327
  Classification -> best τ=0.455 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45759 | val 0.93837
  Epoch 013 - train 0.34971 | val 1.17041
  Classification -> best τ=0.650 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42823 | val 2.47571
  Epoch 011 - train 0.37208 | val 2.28156
  Classification -> best τ=0.465 (val F1=0.2646)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45327 | val 1.03766
  Epoch 011 - train 0.40377 | val 1.14297
  Classification -> best τ=0.470 (val F1=0.2978)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60167 | val 0.64346
  Epoch 012 - train 0.51869 | val 0.90743
  Classification -> best τ=0.360 (val F1=0.3593)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42262 | val 1.90164
  Epoch 011 - train 0.41094 | val 1.93689
  Classification -> best τ=0.270 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51106 | val 1.12303
  Epoch 012 - train 0.40670 | val 1.36580
  Classification -> best τ=0.570 (val F1=0.4270)
  Directional -> Accuracy: 0.5152, MCC: 0.2249, F1: 0.3043

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.29454 | val 1.32916
  Epoch 011 - train 0.28465 | val 1.21751
  Classification -> best τ=0.460 (val F1=0.3001)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39692 | val 2.15334
  Epoch 011 - train 0.41706 | val 2.17566
  Classification -> best τ=0.230 (val F1=0.2203)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36349 | val 1.46148
  Epoch 011 - train 0.33637 | val 1.60696
  Classification -> best τ=0.550 (val F1=0.3611)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39748 | val 0.67620
  Epoch 013 - train 0.33775 | val 0.70057
  Classification -> best τ=0.420 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46906 | val 1.65459
  Epoch 011 - train 0.44974 | val 1.97992
  Classification -> best τ=0.315 (val F1=0.3163)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45955 | val 0.92628
  Epoch 012 - train 0.37390 | val 1.06696
  Classification -> best τ=0.615 (val F1=0.2125)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34018 | val 1.86331
  Epoch 011 - train 0.33836 | val 2.06012
  Classification -> best τ=0.630 (val F1=0.4082)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43662 | val 1.05282
  Epoch 016 - train 0.22004 | val 1.58619
  Classification -> best τ=0.225 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46527 | val 1.89450
  Epoch 011 - train 0.47184 | val 2.47802
  Classification -> best τ=0.265 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39190 | val 3.54236
  Epoch 011 - train 0.37714 | val 3.95764
  Classification -> best τ=0.720 (val F1=0.2385)
  Directional -> Accuracy: 0.5179, MCC: 0.0187, F1: 0.3077

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43451 | val 0.92643
  Epoch 012 - train 0.41407 | val 1.04133
  Classification -> best τ=0.620 (val F1=0.1668)
  Directional -> Accuracy: 0.6792, MCC: 0.3671, F1: 0.6531

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42102 | val 3.43772
  Epoch 011 - train 0.39132 | val 4.20861
  Classification -> best τ=0.895 (val F1=0.0489)
  Directional -> Accuracy: 0.5455, MCC: 0.1437, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 03:49:39,314] Trial 132 finished with value: 0.259150754892102 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.006613311350711599, 'weight_decay': 3.772074448987078e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5037383373491998, 'early_stopping_min_delta': 0.007582088303966697}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 010 - train 0.50258 | val 1.63625
  Epoch 011 - train 0.43923 | val 1.60590
  Classification -> best τ=0.375 (val F1=0.1138)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.259150754892102
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56057 | val 1.46398
  Epoch 013 - train 0.50086 | val 2.03327
  Classification -> best τ=0.630 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1234, F1: 0.4074

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57830 | val 1.11929
  Epoch 014 - train 0.38288 | val 1.76435
  Classification -> best τ=0.315 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47425 | val 1.12690
  Epoch 011 - train 0.43311 | val 1.28880
  Classification -> best τ=0.495 (val F1=0.4104)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54534 | val 2.92600
  Epoch 011 - train 0.52016 | val 1.46400
  Classification -> best τ=0.150 (val F1=0.0136)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43212 | val 0.90662
  Epoch 012 - train 0.37160 | val 0.90886
  Classification -> best τ=0.510 (val F1=0.4930)
  Directional -> Accuracy: 0.7400, MCC: 0.4804, F1: 0.7451

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45887 | val 0.92530
  Epoch 011 - train 0.36611 | val 0.79042
  Classification -> best τ=0.585 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52603 | val 2.08080
  Epoch 011 - train 0.50817 | val 1.98586
  Classification -> best τ=0.465 (val F1=0.2530)
  Directional -> Accuracy: 0.5735, MCC: 0.2400, F1: 0.6027

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42868 | val 1.33917
  Epoch 013 - train 0.28628 | val 2.08659
  Classification -> best τ=0.530 (val F1=0.3632)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.5143

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43971 | val 1.34581
  Epoch 011 - train 0.38068 | val 1.71793
  Classification -> best τ=0.540 (val F1=0.1411)
  Directional -> Accuracy: 0.5833, MCC: 0.1302, F1: 0.4444

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52949 | val 1.28576
  Epoch 013 - train 0.44707 | val 0.78860
  Classification -> best τ=0.440 (val F1=0.3041)
  Directional -> Accuracy: 0.3913, MCC: -0.1540, F1: 0.5435

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49693 | val 1.11685
  Epoch 011 - train 0.53281 | val 1.11001
  Classification -> best τ=0.485 (val F1=0.4196)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63927 | val 2.14253
  Epoch 014 - train 0.41046 | val 4.07127
  Classification -> best τ=0.455 (val F1=0.1576)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54060 | val 0.82149
  Epoch 014 - train 0.33917 | val 1.42196
  Classification -> best τ=0.645 (val F1=0.2902)
  Directional -> Accuracy: 0.5000, MCC: -0.0338, F1: 0.3636

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67513 | val 0.78000
  Epoch 014 - train 0.41510 | val 1.06022
  Classification -> best τ=0.330 (val F1=0.3994)
  Directional -> Accuracy: 0.5167, MCC: 0.0467, F1: 0.6420

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54346 | val 1.48512
  Epoch 013 - train 0.45871 | val 2.26977
  Classification -> best τ=0.500 (val F1=0.2141)
  Directional -> Accuracy: 0.5294, MCC: 0.0922, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63548 | val 0.73943
  Epoch 017 - train 0.41253 | val 1.33124
  Classification -> best τ=0.310 (val F1=0.3809)
  Directional -> Accuracy: 0.5797, MCC: 0.1655, F1: 0.5797

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51376 | val 1.78285
  Epoch 012 - train 0.44776 | val 1.93516
  Classification -> best τ=0.620 (val F1=0.2276)
  Directional -> Accuracy: 0.5345, MCC: 0.2498, F1: 0.4490

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45741 | val 2.17870
  Epoch 012 - train 0.41106 | val 1.83136
  Classification -> best τ=0.265 (val F1=0.2004)
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.4857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63423 | val 0.73504
  Epoch 016 - train 0.58758 | val 0.91679
  Classification -> best τ=0.335 (val F1=0.2803)
  Directional -> Accuracy: 0.4531, MCC: 0.0191, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45476 | val 1.61274
  Epoch 011 - train 0.47802 | val 1.72242
  Classification -> best τ=0.325 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51840 | val 0.83738
  Epoch 018 - train 0.27929 | val 1.71546
  Classification -> best τ=0.645 (val F1=0.3285)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54877 | val 1.82969
  Epoch 011 - train 0.55818 | val 1.34905
  Classification -> best τ=0.445 (val F1=0.2057)
  Directional -> Accuracy: 0.4923, MCC: -0.0126, F1: 0.4407

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63342 | val 0.72837
  Epoch 017 - train 0.49669 | val 1.01888
  Classification -> best τ=0.685 (val F1=0.3482)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55591 | val 1.20230
  Epoch 011 - train 0.51055 | val 1.56060
  Classification -> best τ=0.540 (val F1=0.1736)
  Directional -> Accuracy: 0.4462, MCC: -0.1400, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60050 | val 1.80505
  Epoch 014 - train 0.39325 | val 2.08331
  Classification -> best τ=0.480 (val F1=0.4399)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41269 | val 3.74449
  Epoch 011 - train 0.32704 | val 4.58776
  Classification -> best τ=0.855 (val F1=0.2726)
  Directional -> Accuracy: 0.5333, MCC: 0.2428, F1: 0.6316

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47340 | val 0.93571
  Epoch 012 - train 0.43103 | val 1.12954
  Classification -> best τ=0.580 (val F1=0.2161)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44786 | val 1.57754
  Epoch 011 - train 0.40845 | val 1.72955
  Classification -> best τ=0.490 (val F1=0.2478)
  Directional -> Accuracy: 0.5179, MCC: 0.1037, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40259 | val 0.98759
  Epoch 011 - train 0.40567 | val 0.81510
  Classification -> best τ=0.565 (val F1=0.2414)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50799 | val 0.73400
  Epoch 020 - train 0.12414 | val 0.97094
  Classification -> best τ=0.355 (val F1=0.4553)
  Directional -> Accuracy: 0.4524, MCC: -0.1003, F1: 0.4103

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48767 | val 0.95319
  Epoch 014 - train 0.31007 | val 1.09205
  Classification -> best τ=0.465 (val F1=0.3385)
  Directional -> Accuracy: 0.5476, MCC: 0.1711, F1: 0.4242

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61601 | val 0.71286
  Epoch 016 - train 0.44743 | val 0.97561
  Classification -> best τ=0.670 (val F1=0.3574)
  Directional -> Accuracy: 0.4898, MCC: 0.0160, F1: 0.3243

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59513 | val 0.78888
  Epoch 014 - train 0.46876 | val 0.85276
  Classification -> best τ=0.390 (val F1=0.4063)
  Directional -> Accuracy: 0.5417, MCC: 0.0935, F1: 0.5479

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53858 | val 1.62405
  Epoch 011 - train 0.50593 | val 1.92641
  Classification -> best τ=0.690 (val F1=0.1818)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60121 | val 1.19133
  Epoch 014 - train 0.40328 | val 1.41585
  Classification -> best τ=0.225 (val F1=0.4538)
  Directional -> Accuracy: 0.6212, MCC: 0.2911, F1: 0.6032

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45139 | val 1.40011
  Epoch 013 - train 0.28645 | val 1.35740
  Classification -> best τ=0.300 (val F1=0.3001)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52095 | val 0.99192
  Epoch 012 - train 0.47579 | val 1.30837
  Classification -> best τ=0.325 (val F1=0.2450)
  Directional -> Accuracy: 0.5714, MCC: 0.1708, F1: 0.6129

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50973 | val 1.39832
  Epoch 011 - train 0.44265 | val 2.05614
  Classification -> best τ=0.490 (val F1=0.1641)
  Directional -> Accuracy: 0.5217, MCC: -0.0040, F1: 0.6071

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48271 | val 1.48453
  Epoch 012 - train 0.40892 | val 0.94580
  Classification -> best τ=0.340 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58833 | val 0.83113
  Epoch 012 - train 0.48019 | val 0.74717
  Classification -> best τ=0.300 (val F1=0.2600)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37228 | val 4.09653
  Epoch 011 - train 0.37454 | val 4.08000
  Classification -> best τ=0.680 (val F1=0.4000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43568 | val 1.58169
  Epoch 011 - train 0.43733 | val 1.79506
  Classification -> best τ=0.485 (val F1=0.4277)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52148 | val 1.16403
  Epoch 014 - train 0.27834 | val 1.83359
  Classification -> best τ=0.820 (val F1=0.3458)
  Directional -> Accuracy: 0.3958, MCC: -0.0457, F1: 0.5085

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54248 | val 1.29133
  Epoch 011 - train 0.52699 | val 1.23145
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39987 | val 5.16820
  Epoch 011 - train 0.38555 | val 4.77536
  Classification -> best τ=0.820 (val F1=0.4174)
  Directional -> Accuracy: 0.5536, MCC: 0.1444, F1: 0.6377

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59969 | val 0.85732
  Epoch 011 - train 0.53962 | val 0.80286
  Classification -> best τ=0.685 (val F1=0.2442)
  Directional -> Accuracy: 0.5472, MCC: 0.0956, F1: 0.5385

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44341 | val 4.34606
  Epoch 012 - train 0.34438 | val 3.12939
  Classification -> best τ=0.885 (val F1=0.1605)
  Directional -> Accuracy: 0.4182, MCC: -0.2537, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49060 | val 0.86412
  Epoch 011 - train 0.44564 | val 1.03743

[I 2026-02-20 03:51:17,044] Trial 133 finished with value: 0.2839877253934013 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007293553970323652, 'weight_decay': 5.126820678662862e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.4233848837959232, 'early_stopping_min_delta': 0.005025235680574075}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.455 (val F1=0.1165)
  Directional -> Accuracy: 0.5000, MCC: 0.0080, F1: 0.5455

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2839877253934013
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53924 | val 1.07835
  Epoch 011 - train 0.52446 | val 0.98377
  Classification -> best τ=0.340 (val F1=0.2082)
  Directional -> Accuracy: 0.4474, MCC: -0.0503, F1: 0.5625

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44976 | val 1.78881
  Epoch 011 - train 0.38439 | val 1.88965
  Classification -> best τ=0.290 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0842, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56810 | val 0.92315
  Epoch 013 - train 0.39341 | val 1.34974
  Classification -> best τ=0.345 (val F1=0.3878)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58692 | val 2.00796
  Epoch 015 - train 0.42436 | val 2.47810
  Classification -> best τ=0.205 (val F1=0.1805)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53315 | val 1.15071
  Epoch 013 - train 0.30295 | val 1.27225
  Classification -> best τ=0.580 (val F1=0.5167)
  Directional -> Accuracy: 0.6200, MCC: 0.3170, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51137 | val 1.89035
  Epoch 012 - train 0.35576 | val 0.78246
  Classification -> best τ=0.590 (val F1=0.2699)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59779 | val 1.45692
  Epoch 013 - train 0.49932 | val 3.07268
  Classification -> best τ=0.475 (val F1=0.2163)
  Directional -> Accuracy: 0.4853, MCC: 0.0333, F1: 0.5070

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59331 | val 1.28378
  Epoch 017 - train 0.33488 | val 2.90857
  Classification -> best τ=0.445 (val F1=0.1657)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40378 | val 1.23109
  Epoch 011 - train 0.41020 | val 1.26631
  Classification -> best τ=0.590 (val F1=0.1221)
  Directional -> Accuracy: 0.6667, MCC: 0.3167, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44475 | val 1.51935
  Epoch 011 - train 0.41185 | val 1.94964
  Classification -> best τ=0.455 (val F1=0.2293)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51280 | val 1.02580
  Epoch 011 - train 0.45287 | val 1.30270
  Classification -> best τ=0.350 (val F1=0.3716)
  Directional -> Accuracy: 0.5306, MCC: 0.0060, F1: 0.3030

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49121 | val 2.14497
  Epoch 012 - train 0.39967 | val 3.63825
  Classification -> best τ=0.560 (val F1=0.2741)
  Directional -> Accuracy: 0.7018, MCC: 0.4067, F1: 0.6909

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46453 | val 1.11083
  Epoch 011 - train 0.45899 | val 1.41097
  Classification -> best τ=0.455 (val F1=0.2018)
  Directional -> Accuracy: 0.4048, MCC: -0.1691, F1: 0.4681

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67302 | val 0.71837
  Epoch 015 - train 0.54981 | val 0.80286
  Classification -> best τ=0.295 (val F1=0.3138)
  Directional -> Accuracy: 0.4333, MCC: -0.1383, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45084 | val 3.41472
  Epoch 012 - train 0.51363 | val 4.18911
  Classification -> best τ=0.650 (val F1=0.2429)
  Directional -> Accuracy: 0.5098, MCC: 0.0295, F1: 0.5098

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47542 | val 1.25499
  Epoch 011 - train 0.48239 | val 1.85709
  Classification -> best τ=0.845 (val F1=0.1709)
  Directional -> Accuracy: 0.4493, MCC: -0.1304, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49131 | val 2.26941
  Epoch 011 - train 0.47569 | val 2.46078
  Classification -> best τ=0.520 (val F1=0.1905)
  Directional -> Accuracy: 0.4828, MCC: -0.2627, F1: 0.6429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55205 | val 1.23990
  Epoch 012 - train 0.48914 | val 1.25587
  Classification -> best τ=0.370 (val F1=0.2182)
  Directional -> Accuracy: 0.4800, MCC: 0.1601, F1: 0.2909

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64294 | val 1.30994
  Epoch 015 - train 0.39138 | val 1.69486
  Classification -> best τ=0.140 (val F1=0.3140)
  Directional -> Accuracy: 0.5312, MCC: 0.0196, F1: 0.6154

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50515 | val 1.47551
  Epoch 011 - train 0.48126 | val 1.33504
  Classification -> best τ=0.585 (val F1=0.3219)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40834 | val 2.02014
  Epoch 011 - train 0.39261 | val 1.94379
  Classification -> best τ=0.440 (val F1=0.3678)
  Directional -> Accuracy: 0.5319, MCC: 0.0301, F1: 0.6071

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51875 | val 3.88245
  Epoch 011 - train 0.50804 | val 3.12794
  Classification -> best τ=0.575 (val F1=0.2546)
  Directional -> Accuracy: 0.4462, MCC: -0.1142, F1: 0.2800

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64148 | val 0.70864
  Epoch 014 - train 0.62379 | val 0.89957
  Classification -> best τ=0.490 (val F1=0.3332)
  Directional -> Accuracy: 0.5088, MCC: 0.0025, F1: 0.5625

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52313 | val 4.08468
  Epoch 011 - train 0.46748 | val 6.77365
  Classification -> best τ=0.585 (val F1=0.1778)
  Directional -> Accuracy: 0.4923, MCC: 0.0154, F1: 0.6024

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52928 | val 2.06167
  Epoch 012 - train 0.43785 | val 2.78909
  Classification -> best τ=0.540 (val F1=0.5376)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43201 | val 3.23602
  Epoch 011 - train 0.36757 | val 2.87595
  Classification -> best τ=0.700 (val F1=0.1048)
  Directional -> Accuracy: 0.3778, MCC: -0.2110, F1: 0.4167

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53669 | val 0.70487
  Epoch 012 - train 0.39633 | val 0.72648
  Classification -> best τ=0.550 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.2402, F1: 0.2222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42224 | val 2.42285
  Epoch 011 - train 0.45319 | val 2.85873
  Classification -> best τ=0.230 (val F1=0.2011)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44976 | val 1.64252
  Epoch 013 - train 0.31923 | val 2.83688
  Classification -> best τ=0.560 (val F1=0.1918)
  Directional -> Accuracy: 0.5500, MCC: 0.1111, F1: 0.5500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66952 | val 0.71438
  Epoch 019 - train 0.28166 | val 0.95094
  Classification -> best τ=0.300 (val F1=0.5027)
  Directional -> Accuracy: 0.5476, MCC: 0.1228, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46462 | val 1.00637
  Epoch 012 - train 0.33605 | val 1.02970
  Classification -> best τ=0.555 (val F1=0.3337)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41508 | val 0.99986
  Epoch 011 - train 0.37380 | val 1.33039
  Classification -> best τ=0.580 (val F1=0.3093)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60128 | val 1.12065
  Epoch 013 - train 0.54848 | val 0.92775
  Classification -> best τ=0.400 (val F1=0.4023)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64424 | val 1.08782
  Epoch 018 - train 0.35407 | val 1.63061
  Classification -> best τ=0.370 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46806 | val 1.36252
  Epoch 011 - train 0.54190 | val 1.16374
  Classification -> best τ=0.540 (val F1=0.1563)
  Directional -> Accuracy: 0.5606, MCC: -0.1065, F1: 0.7184

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35205 | val 1.13416
  Epoch 012 - train 0.27503 | val 1.42341
  Classification -> best τ=0.510 (val F1=0.2618)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62146 | val 0.73951
  Epoch 014 - train 0.47029 | val 1.78508
  Classification -> best τ=0.485 (val F1=0.2622)
  Directional -> Accuracy: 0.5357, MCC: 0.0576, F1: 0.4583

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45019 | val 2.16272
  Epoch 011 - train 0.42634 | val 1.35456
  Classification -> best τ=0.400 (val F1=0.3749)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48198 | val 0.99627
  Epoch 015 - train 0.31117 | val 1.12443
  Classification -> best τ=0.275 (val F1=0.4973)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50251 | val 0.99613
  Epoch 012 - train 0.45559 | val 1.18261
  Classification -> best τ=0.390 (val F1=0.3081)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51600 | val 0.72681
  Epoch 016 - train 0.26021 | val 0.79507
  Classification -> best τ=0.475 (val F1=0.5101)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43814 | val 1.12332
  Epoch 011 - train 0.40352 | val 1.19605
  Classification -> best τ=0.510 (val F1=0.0658)
  Directional -> Accuracy: 0.4762, MCC: -0.1217, F1: 0.5926

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40268 | val 1.15703
  Epoch 011 - train 0.37028 | val 1.11146
  Classification -> best τ=0.515 (val F1=0.2689)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50645 | val 8.63113
  Epoch 011 - train 0.46452 | val 8.91446
  Classification -> best τ=0.475 (val F1=0.0602)
  Directional -> Accuracy: 0.3273, MCC: -0.4033, F1: 0.4478

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45206 | val 3.55492
  Epoch 011 - train 0.41578 | val 3.70340
  Classification -> best τ=0.885 (val F1=0.2143)
  Directional -> Accuracy: 0.5357, MCC: 0.0675, F1: 0.2353

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61367 | val 1.07727
  Epoch 013 - train 0.55620 | val 1.14554
  Classification -> best τ=0.445 (val F1=0.1770)
  Directional -> Accuracy: 0.5283, MCC: 0.0662, F1: 0.4444

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46678 | val 3.35535
  Epoch 011 - train 0.46496 | val 4.10494
  Classification -> best τ=0.585 (val F1=0.2107)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57394 | val 1.08632

[I 2026-02-20 03:52:49,877] Trial 134 finished with value: 0.2676168619075798 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008112652005259421, 'weight_decay': 1.088325295246139e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.39081989754269103, 'early_stopping_min_delta': 0.004758047996156107}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.48229 | val 1.30457
  Classification -> best τ=0.455 (val F1=0.2507)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2676168619075798
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53267 | val 1.66077
  Epoch 012 - train 0.47131 | val 3.14969
  Classification -> best τ=0.660 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53321 | val 0.69627
  Epoch 020 - train 0.28160 | val 0.88258
  Classification -> best τ=0.095 (val F1=0.2670)
  Directional -> Accuracy: 0.6222, MCC: 0.2030, F1: 0.7018

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46028 | val 0.92277
  Epoch 012 - train 0.41718 | val 0.93263
  Classification -> best τ=0.540 (val F1=0.3577)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44770 | val 2.33723
  Epoch 011 - train 0.44855 | val 1.34126
  Classification -> best τ=0.120 (val F1=0.0759)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49509 | val 1.32579
  Epoch 013 - train 0.38641 | val 0.97850
  Classification -> best τ=0.740 (val F1=0.4602)
  Directional -> Accuracy: 0.6600, MCC: 0.3669, F1: 0.5854

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64597 | val 0.77914
  Epoch 011 - train 0.68162 | val 0.87963
  Classification -> best τ=0.360 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51845 | val 1.70789
  Epoch 011 - train 0.45826 | val 2.72726
  Classification -> best τ=0.370 (val F1=0.2506)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45666 | val 1.63910
  Epoch 015 - train 0.31135 | val 0.96498
  Classification -> best τ=0.555 (val F1=0.2753)
  Directional -> Accuracy: 0.5000, MCC: 0.1291, F1: 0.6038

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47504 | val 1.58559
  Epoch 012 - train 0.44438 | val 2.12657
  Classification -> best τ=0.590 (val F1=0.3616)
  Directional -> Accuracy: 0.5625, MCC: 0.0808, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62804 | val 0.69716
  Epoch 020 - train 0.34991 | val 2.47727
  Classification -> best τ=0.460 (val F1=0.2667)
  Directional -> Accuracy: 0.4638, MCC: -0.0010, F1: 0.5316

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61533 | val 1.08167
  Epoch 017 - train 0.43558 | val 0.93956
  Classification -> best τ=0.565 (val F1=0.4059)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51021 | val 1.79419
  Epoch 012 - train 0.41197 | val 2.70851
  Classification -> best τ=0.715 (val F1=0.3027)
  Directional -> Accuracy: 0.4737, MCC: -0.0557, F1: 0.2105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45551 | val 0.75319
  Epoch 017 - train 0.25071 | val 1.51946
  Classification -> best τ=0.760 (val F1=0.2521)
  Directional -> Accuracy: 0.5238, MCC: 0.0673, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52206 | val 1.42082
  Epoch 012 - train 0.48530 | val 1.83336
  Classification -> best τ=0.280 (val F1=0.1363)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51050 | val 3.49079
  Epoch 016 - train 0.34957 | val 5.94970
  Classification -> best τ=0.570 (val F1=0.3237)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54987 | val 1.24011
  Epoch 017 - train 0.39512 | val 2.73845
  Classification -> best τ=0.480 (val F1=0.2600)
  Directional -> Accuracy: 0.5652, MCC: 0.1192, F1: 0.6154

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48388 | val 3.31914
  Epoch 011 - train 0.46733 | val 4.04012
  Classification -> best τ=0.270 (val F1=0.2787)
  Directional -> Accuracy: 0.4828, MCC: -0.2238, F1: 0.6341

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47320 | val 1.43464
  Epoch 011 - train 0.46558 | val 1.90285
  Classification -> best τ=0.580 (val F1=0.1773)
  Directional -> Accuracy: 0.4400, MCC: 0.0748, F1: 0.1923

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54154 | val 1.50252
  Epoch 015 - train 0.48936 | val 2.10331
  Classification -> best τ=0.315 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: -0.0149, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45707 | val 1.51976
  Epoch 011 - train 0.44224 | val 1.39287
  Classification -> best τ=0.595 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49978 | val 0.77512
  Epoch 020 - train 0.28461 | val 1.38659
  Classification -> best τ=0.660 (val F1=0.4624)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54935 | val 1.45943
  Epoch 011 - train 0.53496 | val 1.14271
  Classification -> best τ=0.355 (val F1=0.0526)
  Directional -> Accuracy: 0.4769, MCC: -0.1014, F1: 0.6304

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54483 | val 1.33906
  Epoch 012 - train 0.49416 | val 1.27325
  Classification -> best τ=0.445 (val F1=0.2091)
  Directional -> Accuracy: 0.5263, MCC: 0.0423, F1: 0.5714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58173 | val 1.45184
  Epoch 011 - train 0.58214 | val 1.88984
  Classification -> best τ=0.570 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49436 | val 2.32500
  Epoch 011 - train 0.41936 | val 2.98109
  Classification -> best τ=0.525 (val F1=0.2390)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47849 | val 3.11393
  Epoch 011 - train 0.44658 | val 3.29512
  Classification -> best τ=0.590 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61836 | val 0.79444
  Epoch 017 - train 0.40822 | val 2.13101
  Classification -> best τ=0.570 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52368 | val 2.03910
  Epoch 011 - train 0.47728 | val 2.36283
  Classification -> best τ=0.520 (val F1=0.3172)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56475 | val 1.33605
  Epoch 011 - train 0.51038 | val 1.25896
  Classification -> best τ=0.530 (val F1=0.2414)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49334 | val 0.62451
  Epoch 019 - train 0.27099 | val 1.24897
  Classification -> best τ=0.510 (val F1=0.4067)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51111 | val 0.72661
  Epoch 011 - train 0.48396 | val 0.76998
  Classification -> best τ=0.390 (val F1=0.2357)
  Directional -> Accuracy: 0.4524, MCC: -0.0391, F1: 0.2069

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45057 | val 0.76581
  Epoch 012 - train 0.39102 | val 0.84117
  Classification -> best τ=0.590 (val F1=0.3886)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61262 | val 0.93151
  Epoch 016 - train 0.41960 | val 1.15437
  Classification -> best τ=0.295 (val F1=0.3576)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43997 | val 1.26567
  Epoch 011 - train 0.42961 | val 1.92258
  Classification -> best τ=0.715 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55182 | val 1.38077
  Epoch 019 - train 0.27910 | val 1.21663
  Classification -> best τ=0.735 (val F1=0.3212)
  Directional -> Accuracy: 0.6515, MCC: 0.4355, F1: 0.5818

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36985 | val 1.12121
  Epoch 011 - train 0.33743 | val 1.25427
  Classification -> best τ=0.450 (val F1=0.3001)
  Directional -> Accuracy: 0.7381, MCC: 0.4835, F1: 0.7317

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42366 | val 2.78260
  Epoch 011 - train 0.44036 | val 2.92588
  Classification -> best τ=0.520 (val F1=0.2382)
  Directional -> Accuracy: 0.5357, MCC: 0.0620, F1: 0.4800

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39894 | val 1.96514
  Epoch 011 - train 0.40801 | val 2.12389
  Classification -> best τ=0.570 (val F1=0.3906)
  Directional -> Accuracy: 0.4348, MCC: -0.0094, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52580 | val 0.91548
  Epoch 013 - train 0.40012 | val 1.33816
  Classification -> best τ=0.575 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51977 | val 1.37208
  Epoch 013 - train 0.44059 | val 1.74938
  Classification -> best τ=0.665 (val F1=0.3146)
  Directional -> Accuracy: 0.4595, MCC: -0.0767, F1: 0.5455

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50884 | val 1.57087
  Epoch 013 - train 0.39262 | val 1.89141
  Classification -> best τ=0.430 (val F1=0.2174)
  Directional -> Accuracy: 0.6000, MCC: 0.2070, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45257 | val 1.55007
  Epoch 011 - train 0.45321 | val 1.61115
  Classification -> best τ=0.600 (val F1=0.3612)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47956 | val 0.69594
  Epoch 017 - train 0.30498 | val 0.89648
  Classification -> best τ=0.555 (val F1=0.5261)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56959 | val 1.35784
  Epoch 011 - train 0.54036 | val 1.54083
  Classification -> best τ=0.560 (val F1=0.1647)
  Directional -> Accuracy: 0.4909, MCC: 0.0852, F1: 0.2222

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47745 | val 1.97403
  Epoch 011 - train 0.41599 | val 2.45196
  Classification -> best τ=0.620 (val F1=0.2311)
  Directional -> Accuracy: 0.5536, MCC: 0.1897, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54871 | val 2.75301
  Epoch 012 - train 0.49682 | val 1.25111
  Classification -> best τ=0.710 (val F1=0.2442)
  Directional -> Accuracy: 0.5283, MCC: 0.0707, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49103 | val 2.44696
  Epoch 012 - train 0.47070 | val 2.98902
  Classification -> best τ=0.930 (val F1=0.1186)
  Directional -> Accuracy: 0.4545, MCC: -0.0942, F1: 0.4828

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48056 | val 0.97489

[I 2026-02-20 03:54:29,175] Trial 135 finished with value: 0.2747636695273255 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005397403230438208, 'weight_decay': 5.155570513261754e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.42648925239729596, 'early_stopping_min_delta': 0.00493490662319631}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.49150 | val 0.99562
  Classification -> best τ=0.380 (val F1=0.0476)
  Directional -> Accuracy: 0.4667, MCC: -0.0704, F1: 0.6190

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2747636695273255
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53626 | val 1.15662
  Epoch 011 - train 0.51798 | val 0.89915
  Classification -> best τ=0.430 (val F1=0.2627)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57891 | val 1.53402
  Epoch 013 - train 0.42345 | val 1.77006
  Classification -> best τ=0.465 (val F1=0.2440)
  Directional -> Accuracy: 0.5778, MCC: 0.1058, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52718 | val 2.25791
  Epoch 017 - train 0.36624 | val 2.08871
  Classification -> best τ=0.610 (val F1=0.4040)
  Directional -> Accuracy: 0.5870, MCC: 0.1741, F1: 0.5957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55581 | val 1.19466
  Epoch 015 - train 0.42519 | val 1.34400
  Classification -> best τ=0.545 (val F1=0.0747)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60258 | val 1.15462
  Epoch 016 - train 0.37850 | val 1.40067
  Classification -> best τ=0.720 (val F1=0.4745)
  Directional -> Accuracy: 0.7400, MCC: 0.4851, F1: 0.7347

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35344 | val 0.84782
  Epoch 011 - train 0.35507 | val 0.85852
  Classification -> best τ=0.605 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55035 | val 1.01171
  Epoch 012 - train 0.47591 | val 1.45415
  Classification -> best τ=0.755 (val F1=0.2536)
  Directional -> Accuracy: 0.5147, MCC: 0.0177, F1: 0.4407

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42664 | val 1.30592
  Epoch 013 - train 0.31288 | val 1.82053
  Classification -> best τ=0.715 (val F1=0.2657)
  Directional -> Accuracy: 0.5476, MCC: 0.1105, F1: 0.5366

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42249 | val 1.50988
  Epoch 011 - train 0.41145 | val 1.89258
  Classification -> best τ=0.600 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.2140, F1: 0.6154

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65990 | val 0.90833
  Epoch 018 - train 0.56551 | val 1.17136
  Classification -> best τ=0.610 (val F1=0.1839)
  Directional -> Accuracy: 0.5217, MCC: 0.0324, F1: 0.4590

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53821 | val 0.74641
  Epoch 013 - train 0.44728 | val 0.77881
  Classification -> best τ=0.550 (val F1=0.2498)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49990 | val 3.75492
  Epoch 013 - train 0.38787 | val 3.92960
  Classification -> best τ=0.235 (val F1=0.2667)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41172 | val 2.13236
  Epoch 011 - train 0.39487 | val 2.92401
  Classification -> best τ=0.470 (val F1=0.1878)
  Directional -> Accuracy: 0.3810, MCC: -0.2202, F1: 0.4800

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59722 | val 0.73900
  Epoch 014 - train 0.50556 | val 0.88148
  Classification -> best τ=0.280 (val F1=0.3196)
  Directional -> Accuracy: 0.4833, MCC: -0.0467, F1: 0.6173

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45914 | val 27.89842
  Epoch 011 - train 0.44954 | val 45.04485
  Classification -> best τ=0.565 (val F1=0.3592)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55561 | val 1.18162
  Epoch 015 - train 0.37801 | val 0.94304
  Classification -> best τ=0.530 (val F1=0.4038)
  Directional -> Accuracy: 0.5507, MCC: 0.1234, F1: 0.5079

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52801 | val 2.39013
  Epoch 011 - train 0.47274 | val 2.62493
  Classification -> best τ=0.740 (val F1=0.0827)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50466 | val 1.51604
  Epoch 011 - train 0.49092 | val 1.60883
  Classification -> best τ=0.645 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58441 | val 1.07169
  Epoch 014 - train 0.44545 | val 2.25495
  Classification -> best τ=0.315 (val F1=0.2306)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52999 | val 1.57095
  Epoch 011 - train 0.48619 | val 1.56049
  Classification -> best τ=0.585 (val F1=0.2771)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46206 | val 1.11899
  Epoch 011 - train 0.42931 | val 1.11399
  Classification -> best τ=0.675 (val F1=0.2164)
  Directional -> Accuracy: 0.4255, MCC: 0.0834, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52413 | val 2.87433
  Epoch 011 - train 0.48206 | val 3.70459
  Classification -> best τ=0.560 (val F1=0.1350)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61532 | val 1.20968
  Epoch 013 - train 0.49886 | val 1.72682
  Classification -> best τ=0.610 (val F1=0.3305)
  Directional -> Accuracy: 0.5263, MCC: 0.0423, F1: 0.5714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57518 | val 0.90684
  Epoch 012 - train 0.51603 | val 0.81991
  Classification -> best τ=0.495 (val F1=0.2774)
  Directional -> Accuracy: 0.4769, MCC: -0.0197, F1: 0.6047

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51052 | val 1.58640
  Epoch 011 - train 0.43983 | val 1.71894
  Classification -> best τ=0.595 (val F1=0.2538)
  Directional -> Accuracy: 0.5273, MCC: 0.1023, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42896 | val 2.42299
  Epoch 011 - train 0.44081 | val 2.53811
  Classification -> best τ=0.715 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58942 | val 1.09170
  Epoch 012 - train 0.64221 | val 0.88827
  Classification -> best τ=0.585 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48562 | val 1.28490
  Epoch 011 - train 0.45556 | val 1.25127
  Classification -> best τ=0.320 (val F1=0.2305)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44589 | val 1.64206
  Epoch 011 - train 0.42499 | val 1.30870
  Classification -> best τ=0.575 (val F1=0.1457)
  Directional -> Accuracy: 0.6000, MCC: 0.1755, F1: 0.6800

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49295 | val 0.68534
  Epoch 020 - train 0.13230 | val 0.61388
  Classification -> best τ=0.570 (val F1=0.5251)
  Directional -> Accuracy: 0.4524, MCC: -0.0830, F1: 0.5660

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45377 | val 3.62156
  Epoch 011 - train 0.42338 | val 4.03361
  Classification -> best τ=0.315 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1276, F1: 0.6250

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46147 | val 0.87179
  Epoch 012 - train 0.36669 | val 1.09483
  Classification -> best τ=0.475 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51334 | val 2.33948
  Epoch 011 - train 0.52855 | val 3.26932
  Classification -> best τ=0.465 (val F1=0.3450)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45182 | val 2.77041
  Epoch 011 - train 0.41837 | val 2.69116
  Classification -> best τ=0.825 (val F1=0.2804)
  Directional -> Accuracy: 0.5814, MCC: 0.1673, F1: 0.4706

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58173 | val 1.00399
  Epoch 011 - train 0.56554 | val 0.72279
  Classification -> best τ=0.490 (val F1=0.3206)
  Directional -> Accuracy: 0.4091, MCC: -0.1445, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41006 | val 0.88581
  Epoch 014 - train 0.26483 | val 2.00109
  Classification -> best τ=0.395 (val F1=0.2464)
  Directional -> Accuracy: 0.6667, MCC: 0.3319, F1: 0.7083

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43771 | val 1.14739
  Epoch 011 - train 0.41773 | val 1.89612
  Classification -> best τ=0.435 (val F1=0.2026)
  Directional -> Accuracy: 0.5357, MCC: 0.0716, F1: 0.5185

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42542 | val 1.59252
  Epoch 011 - train 0.40884 | val 1.87032
  Classification -> best τ=0.555 (val F1=0.2268)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49300 | val 0.66601
  Epoch 013 - train 0.37726 | val 0.70980
  Classification -> best τ=0.605 (val F1=0.5075)
  Directional -> Accuracy: 0.4375, MCC: 0.1482, F1: 0.5424

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46716 | val 1.64227
  Epoch 011 - train 0.44367 | val 1.51660
  Classification -> best τ=0.335 (val F1=0.4230)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41234 | val 0.86289
  Epoch 011 - train 0.36115 | val 0.86017
  Classification -> best τ=0.505 (val F1=0.3500)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45795 | val 1.78483
  Epoch 011 - train 0.39585 | val 1.75213
  Classification -> best τ=0.600 (val F1=0.3612)
  Directional -> Accuracy: 0.3571, MCC: -0.2759, F1: 0.0690

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43116 | val 0.73233
  Epoch 019 - train 0.22767 | val 0.85065
  Classification -> best τ=0.860 (val F1=0.5421)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50573 | val 2.56226
  Epoch 012 - train 0.45614 | val 2.11507
  Classification -> best τ=0.550 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46252 | val 4.04226
  Epoch 011 - train 0.47617 | val 3.93771
  Classification -> best τ=0.885 (val F1=0.2493)
  Directional -> Accuracy: 0.5357, MCC: 0.0791, F1: 0.5667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59412 | val 0.83613
  Epoch 014 - train 0.43493 | val 0.96278
  Classification -> best τ=0.360 (val F1=0.1646)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44504 | val 3.02785
  Epoch 011 - train 0.38981 | val 4.07472
  Classification -> best τ=0.845 (val F1=0.1605)
  Directional -> Accuracy: 0.5273, MCC: 0.0817, F1: 0.4348

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48457 | val 0.97615
  Epoch 011 - train 0.48250 | val 0.85752

[I 2026-02-20 03:56:02,584] Trial 136 finished with value: 0.2747460220622952 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005225353940634233, 'weight_decay': 5.181133321264884e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.2870265316743308, 'early_stopping_min_delta': 0.005165408308786007}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.430 (val F1=0.3178)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2747460220622952
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59558 | val 0.98894
  Epoch 011 - train 0.55228 | val 1.13035
  Classification -> best τ=0.410 (val F1=0.2057)
  Directional -> Accuracy: 0.4474, MCC: -0.0412, F1: 0.5800

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51137 | val 1.31588
  Epoch 012 - train 0.46077 | val 1.35678
  Classification -> best τ=0.635 (val F1=0.1764)
  Directional -> Accuracy: 0.5333, MCC: 0.0931, F1: 0.5333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48996 | val 1.34941
  Epoch 011 - train 0.46619 | val 1.53985
  Classification -> best τ=0.505 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53279 | val 2.39270
  Epoch 011 - train 0.50267 | val 2.50828
  Classification -> best τ=0.075 (val F1=0.2920)
  Directional -> Accuracy: 0.5946, MCC: 0.1805, F1: 0.6341

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48667 | val 1.12006
  Epoch 012 - train 0.37773 | val 1.77627
  Classification -> best τ=0.605 (val F1=0.4602)
  Directional -> Accuracy: 0.6600, MCC: 0.3669, F1: 0.5854

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37765 | val 0.89960
  Epoch 011 - train 0.37229 | val 1.00337
  Classification -> best τ=0.510 (val F1=0.2208)
  Directional -> Accuracy: 0.5435, MCC: 0.0790, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65317 | val 0.67845
  Epoch 020 - train 0.47445 | val 0.74602
  Classification -> best τ=0.435 (val F1=0.2605)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44751 | val 1.08525
  Epoch 016 - train 0.35567 | val 1.63825
  Classification -> best τ=0.425 (val F1=0.1873)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46042 | val 2.01326
  Epoch 011 - train 0.40372 | val 2.17569
  Classification -> best τ=0.635 (val F1=0.2443)
  Directional -> Accuracy: 0.6250, MCC: 0.3228, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52108 | val 1.20334
  Epoch 014 - train 0.36071 | val 1.38893
  Classification -> best τ=0.280 (val F1=0.2951)
  Directional -> Accuracy: 0.4638, MCC: 0.1815, F1: 0.6105

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52248 | val 0.74593
  Epoch 020 - train 0.35038 | val 0.62677
  Classification -> best τ=0.475 (val F1=0.5295)
  Directional -> Accuracy: 0.6735, MCC: 0.3447, F1: 0.5294

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61183 | val 0.94421
  Epoch 018 - train 0.36080 | val 3.38671
  Classification -> best τ=0.440 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46751 | val 2.28158
  Epoch 011 - train 0.45542 | val 2.60451
  Classification -> best τ=0.340 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57598 | val 0.63596
  Epoch 012 - train 0.52883 | val 0.65384
  Classification -> best τ=0.615 (val F1=0.3642)
  Directional -> Accuracy: 0.5333, MCC: 0.1336, F1: 0.1765

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42125 | val 2.29821
  Epoch 012 - train 0.40045 | val 3.10091
  Classification -> best τ=0.575 (val F1=0.2571)
  Directional -> Accuracy: 0.5686, MCC: 0.1560, F1: 0.0833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53250 | val 1.06429
  Epoch 012 - train 0.47776 | val 1.03649
  Classification -> best τ=0.560 (val F1=0.2732)
  Directional -> Accuracy: 0.5652, MCC: 0.1258, F1: 0.5946

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55980 | val 1.73301
  Epoch 011 - train 0.50814 | val 1.57195
  Classification -> best τ=0.745 (val F1=0.1731)
  Directional -> Accuracy: 0.3103, MCC: -0.3482, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48891 | val 1.14769
  Epoch 012 - train 0.47178 | val 1.57700
  Classification -> best τ=0.810 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53415 | val 1.10847
  Epoch 013 - train 0.52961 | val 1.27407
  Classification -> best τ=0.660 (val F1=0.2234)
  Directional -> Accuracy: 0.4062, MCC: -0.1475, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45001 | val 1.09767
  Epoch 011 - train 0.41788 | val 1.01731
  Classification -> best τ=0.515 (val F1=0.2871)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53144 | val 2.02175
  Epoch 012 - train 0.46823 | val 1.99268
  Classification -> best τ=0.540 (val F1=0.3237)
  Directional -> Accuracy: 0.4468, MCC: 0.0837, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54312 | val 2.22043
  Epoch 011 - train 0.50433 | val 2.21716
  Classification -> best τ=0.600 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55766 | val 2.07417
  Epoch 012 - train 0.50627 | val 1.85802
  Classification -> best τ=0.645 (val F1=0.2799)
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49263 | val 1.55818
  Epoch 012 - train 0.50781 | val 1.23513
  Classification -> best τ=0.805 (val F1=0.2055)
  Directional -> Accuracy: 0.5077, MCC: 0.0105, F1: 0.4667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45122 | val 1.44152
  Epoch 011 - train 0.43751 | val 1.64252
  Classification -> best τ=0.550 (val F1=0.1706)
  Directional -> Accuracy: 0.5636, MCC: 0.2731, F1: 0.3684

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43731 | val 4.15687
  Epoch 011 - train 0.43397 | val 4.47061
  Classification -> best τ=0.805 (val F1=0.0385)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.4706

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56293 | val 1.11186
  Epoch 011 - train 0.51335 | val 1.18064
  Classification -> best τ=0.480 (val F1=0.1698)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.2581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48007 | val 1.32628
  Epoch 011 - train 0.46479 | val 1.40145
  Classification -> best τ=0.345 (val F1=0.2614)
  Directional -> Accuracy: 0.5714, MCC: 0.2632, F1: 0.4286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44651 | val 1.42236
  Epoch 011 - train 0.44640 | val 1.79555
  Classification -> best τ=0.525 (val F1=0.1183)
  Directional -> Accuracy: 0.6250, MCC: 0.2389, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51446 | val 0.62215
  Epoch 019 - train 0.26520 | val 0.65833
  Classification -> best τ=0.480 (val F1=0.5210)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44400 | val 0.83199
  Epoch 011 - train 0.46472 | val 0.97852
  Classification -> best τ=0.485 (val F1=0.2066)
  Directional -> Accuracy: 0.4524, MCC: -0.0464, F1: 0.2581

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47481 | val 0.89202
  Epoch 012 - train 0.42292 | val 0.96111
  Classification -> best τ=0.440 (val F1=0.2645)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52344 | val 1.82389
  Epoch 011 - train 0.49172 | val 1.92888
  Classification -> best τ=0.335 (val F1=0.2978)
  Directional -> Accuracy: 0.5556, MCC: 0.1936, F1: 0.4483

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48050 | val 1.82191
  Epoch 011 - train 0.44410 | val 1.70882
  Classification -> best τ=0.665 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50885 | val 1.23032
  Epoch 012 - train 0.42806 | val 1.70881
  Classification -> best τ=0.515 (val F1=0.4292)
  Directional -> Accuracy: 0.6515, MCC: 0.3164, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44225 | val 2.89811
  Epoch 011 - train 0.40705 | val 2.60331
  Classification -> best τ=0.505 (val F1=0.1507)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53441 | val 0.89520
  Epoch 011 - train 0.51057 | val 1.03827
  Classification -> best τ=0.430 (val F1=0.2327)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40678 | val 1.48510
  Epoch 011 - train 0.37536 | val 1.66990
  Classification -> best τ=0.505 (val F1=0.3771)
  Directional -> Accuracy: 0.5870, MCC: 0.0324, F1: 0.7164

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54528 | val 0.89648
  Epoch 013 - train 0.42515 | val 1.08690
  Classification -> best τ=0.315 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53943 | val 1.14135
  Epoch 013 - train 0.49020 | val 1.55344
  Classification -> best τ=0.455 (val F1=0.2493)
  Directional -> Accuracy: 0.4865, MCC: -0.0045, F1: 0.6481

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49867 | val 0.92270
  Epoch 012 - train 0.45277 | val 1.01220
  Classification -> best τ=0.430 (val F1=0.3500)
  Directional -> Accuracy: 0.5111, MCC: 0.0217, F1: 0.5217

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47810 | val 1.28379
  Epoch 011 - train 0.45107 | val 1.38629
  Classification -> best τ=0.610 (val F1=0.4082)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.4211

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50848 | val 1.04214
  Epoch 012 - train 0.49049 | val 1.21986
  Classification -> best τ=0.800 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56201 | val 1.73719
  Epoch 011 - train 0.57429 | val 1.48536
  Classification -> best τ=0.495 (val F1=0.1232)
  Directional -> Accuracy: 0.4909, MCC: -0.2193, F1: 0.6585

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42036 | val 2.87186
  Epoch 011 - train 0.41671 | val 3.37005
  Classification -> best τ=0.740 (val F1=0.1910)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52555 | val 0.91119
  Epoch 011 - train 0.53349 | val 0.89972
  Classification -> best τ=0.735 (val F1=0.2064)
  Directional -> Accuracy: 0.5660, MCC: 0.1373, F1: 0.5306

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57062 | val 2.24400
  Epoch 012 - train 0.53228 | val 2.20207
  Classification -> best τ=0.790 (val F1=0.1881)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57667 | val 0.77924

[I 2026-02-20 03:57:36,251] Trial 137 finished with value: 0.2608151905496589 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0035908526201780494, 'weight_decay': 5.427127609894763e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.23568636222047382, 'early_stopping_min_delta': 0.005481245752084031}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 014 - train 0.42048 | val 0.82462
  Classification -> best τ=0.535 (val F1=0.2333)
  Directional -> Accuracy: 0.5333, MCC: 0.0963, F1: 0.6216

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2608151905496589
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52837 | val 0.92577
  Epoch 011 - train 0.48309 | val 1.03264
  Classification -> best τ=0.555 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41980 | val 1.33389
  Epoch 011 - train 0.41307 | val 1.33801
  Classification -> best τ=0.365 (val F1=0.1093)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45409 | val 0.87034
  Epoch 011 - train 0.45520 | val 1.29293
  Classification -> best τ=0.370 (val F1=0.4104)
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.5769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54226 | val 1.47129
  Epoch 011 - train 0.51635 | val 1.48197
  Classification -> best τ=0.255 (val F1=0.2920)
  Directional -> Accuracy: 0.5811, MCC: 0.1585, F1: 0.6076

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52350 | val 0.70571
  Epoch 011 - train 0.48251 | val 0.77384
  Classification -> best τ=0.635 (val F1=0.3307)
  Directional -> Accuracy: 0.5400, MCC: 0.1375, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43561 | val 1.33136
  Epoch 012 - train 0.38312 | val 1.63448
  Classification -> best τ=0.555 (val F1=0.2739)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63287 | val 1.18239
  Epoch 014 - train 0.49543 | val 1.40143
  Classification -> best τ=0.120 (val F1=0.2755)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42806 | val 1.07671
  Epoch 012 - train 0.34670 | val 1.45365
  Classification -> best τ=0.555 (val F1=0.1795)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43867 | val 2.64426
  Epoch 011 - train 0.43897 | val 3.52989
  Classification -> best τ=0.700 (val F1=0.2443)
  Directional -> Accuracy: 0.7083, MCC: 0.4256, F1: 0.6957

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48897 | val 6.05190
  Epoch 011 - train 0.48390 | val 1.14630
  Classification -> best τ=0.530 (val F1=0.2355)
  Directional -> Accuracy: 0.4783, MCC: 0.0504, F1: 0.5610

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61922 | val 0.73996
  Epoch 015 - train 0.36432 | val 0.98002
  Classification -> best τ=0.375 (val F1=0.2173)
  Directional -> Accuracy: 0.5714, MCC: 0.1126, F1: 0.4324

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47578 | val 2.07007
  Epoch 012 - train 0.36155 | val 3.76324
  Classification -> best τ=0.545 (val F1=0.3241)
  Directional -> Accuracy: 0.5965, MCC: 0.2023, F1: 0.5490

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44768 | val 2.67347
  Epoch 012 - train 0.36427 | val 2.45604
  Classification -> best τ=0.495 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57320 | val 1.13582
  Epoch 014 - train 0.45836 | val 1.54267
  Classification -> best τ=0.285 (val F1=0.3391)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5714

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50047 | val 1.45132
  Epoch 014 - train 0.38847 | val 4.20533
  Classification -> best τ=0.735 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59594 | val 0.96398
  Epoch 015 - train 0.44198 | val 1.05163
  Classification -> best τ=0.530 (val F1=0.2972)
  Directional -> Accuracy: 0.5507, MCC: 0.0948, F1: 0.5867

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51738 | val 2.09013
  Epoch 011 - train 0.51004 | val 1.83030
  Classification -> best τ=0.665 (val F1=0.2904)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48641 | val 1.06803
  Epoch 012 - train 0.43335 | val 0.94597
  Classification -> best τ=0.540 (val F1=0.1938)
  Directional -> Accuracy: 0.5467, MCC: 0.0872, F1: 0.5952

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57949 | val 1.76297
  Epoch 013 - train 0.43962 | val 1.65194
  Classification -> best τ=0.520 (val F1=0.3536)
  Directional -> Accuracy: 0.4688, MCC: 0.0966, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52959 | val 1.26360
  Epoch 011 - train 0.50838 | val 1.24455
  Classification -> best τ=0.390 (val F1=0.2614)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51097 | val 1.92878
  Epoch 012 - train 0.47913 | val 1.79380
  Classification -> best τ=0.450 (val F1=0.2784)
  Directional -> Accuracy: 0.6383, MCC: 0.1524, F1: 0.7671

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52894 | val 2.57351
  Epoch 011 - train 0.50105 | val 3.37363
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62071 | val 0.98768
  Epoch 012 - train 0.55132 | val 0.88718
  Classification -> best τ=0.645 (val F1=0.2789)
  Directional -> Accuracy: 0.4737, MCC: 0.0518, F1: 0.2500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57049 | val 1.37945
  Epoch 012 - train 0.47901 | val 2.06743
  Classification -> best τ=0.560 (val F1=0.1348)
  Directional -> Accuracy: 0.5538, MCC: 0.1218, F1: 0.5915

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44407 | val 2.57557
  Epoch 011 - train 0.41973 | val 2.63528
  Classification -> best τ=0.575 (val F1=0.3220)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40321 | val 3.59657
  Epoch 011 - train 0.38706 | val 4.14919
  Classification -> best τ=0.630 (val F1=0.2726)
  Directional -> Accuracy: 0.5556, MCC: 0.2103, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49435 | val 0.76483
  Epoch 012 - train 0.46985 | val 0.78426
  Classification -> best τ=0.500 (val F1=0.0168)
  Directional -> Accuracy: 0.5952, MCC: 0.1407, F1: 0.6909

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52528 | val 0.96732
  Epoch 011 - train 0.47528 | val 1.05537
  Classification -> best τ=0.465 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44838 | val 1.13104
  Epoch 013 - train 0.42597 | val 1.59047
  Classification -> best τ=0.540 (val F1=0.1457)
  Directional -> Accuracy: 0.6000, MCC: 0.1830, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57466 | val 0.69260
  Epoch 014 - train 0.36808 | val 0.82383
  Classification -> best τ=0.480 (val F1=0.3630)
  Directional -> Accuracy: 0.5000, MCC: 0.0332, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48996 | val 1.44981
  Epoch 011 - train 0.45315 | val 1.59772
  Classification -> best τ=0.340 (val F1=0.2357)
  Directional -> Accuracy: 0.6429, MCC: 0.3190, F1: 0.6154

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40542 | val 0.87796
  Epoch 011 - train 0.40212 | val 1.07723
  Classification -> best τ=0.450 (val F1=0.4100)
  Directional -> Accuracy: 0.4082, MCC: -0.2189, F1: 0.5085

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53887 | val 0.98500
  Epoch 011 - train 0.50169 | val 1.32615
  Classification -> best τ=0.360 (val F1=0.2403)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48907 | val 2.27799
  Epoch 011 - train 0.44157 | val 2.96194
  Classification -> best τ=0.420 (val F1=0.2717)
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.6774

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62891 | val 1.13079
  Epoch 014 - train 0.48782 | val 1.48168
  Classification -> best τ=0.310 (val F1=0.3855)
  Directional -> Accuracy: 0.5000, MCC: 0.1371, F1: 0.3265

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36380 | val 1.06589
  Epoch 011 - train 0.37684 | val 0.98999
  Classification -> best τ=0.525 (val F1=0.1857)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51039 | val 1.92850
  Epoch 014 - train 0.33378 | val 3.03714
  Classification -> best τ=0.615 (val F1=0.2717)
  Directional -> Accuracy: 0.5536, MCC: 0.0962, F1: 0.4898

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42348 | val 0.71532
  Epoch 013 - train 0.35079 | val 0.80684
  Classification -> best τ=0.445 (val F1=0.3334)
  Directional -> Accuracy: 0.3696, MCC: -0.1859, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51795 | val 0.74014
  Epoch 013 - train 0.33627 | val 0.97145
  Classification -> best τ=0.480 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49441 | val 1.56283
  Epoch 011 - train 0.49846 | val 1.52034
  Classification -> best τ=0.335 (val F1=0.3209)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55502 | val 1.26050
  Epoch 012 - train 0.45810 | val 0.75798
  Classification -> best τ=0.515 (val F1=0.2000)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43148 | val 1.07959
  Epoch 012 - train 0.37711 | val 1.28247
  Classification -> best τ=0.605 (val F1=0.5601)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53649 | val 1.00282
  Epoch 014 - train 0.43345 | val 1.28541
  Classification -> best τ=0.870 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49397 | val 2.83726
  Epoch 012 - train 0.45839 | val 3.05086
  Classification -> best τ=0.575 (val F1=0.2132)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54662 | val 1.65397
  Epoch 015 - train 0.39897 | val 2.37735
  Classification -> best τ=0.810 (val F1=0.4159)
  Directional -> Accuracy: 0.5536, MCC: 0.1555, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50766 | val 1.74950
  Epoch 011 - train 0.48111 | val 1.31055
  Classification -> best τ=0.620 (val F1=0.0148)
  Directional -> Accuracy: 0.5094, MCC: 0.0770, F1: 0.1333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45166 | val 3.24857
  Epoch 012 - train 0.40207 | val 4.47436
  Classification -> best τ=0.855 (val F1=0.3303)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59599 | val 0.71428
  Epoch 011 - train 0.55240 | val 0.77429

[I 2026-02-20 03:59:07,481] Trial 138 finished with value: 0.2610758131447974 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005475551020177439, 'weight_decay': 7.852870066152965e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.40491269614915854, 'early_stopping_min_delta': 0.005054530306471036}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.555 (val F1=0.1489)
  Directional -> Accuracy: 0.4667, MCC: -0.0704, F1: 0.4286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2610758131447974
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55271 | val 1.24883
  Epoch 011 - train 0.56411 | val 1.48376
  Classification -> best τ=0.400 (val F1=0.2176)
  Directional -> Accuracy: 0.4605, MCC: -0.0306, F1: 0.5495

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61481 | val 0.80743
  Epoch 013 - train 0.49016 | val 0.74882
  Classification -> best τ=0.390 (val F1=0.3022)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54734 | val 0.87303
  Epoch 017 - train 0.36253 | val 0.87735
  Classification -> best τ=0.370 (val F1=0.4890)
  Directional -> Accuracy: 0.4130, MCC: -0.1741, F1: 0.4255

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56044 | val 3.03559
  Epoch 014 - train 0.46458 | val 4.45272
  Classification -> best τ=0.205 (val F1=0.2920)
  Directional -> Accuracy: 0.5811, MCC: 0.1515, F1: 0.6265

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49825 | val 0.90461
  Epoch 011 - train 0.46152 | val 0.87820
  Classification -> best τ=0.545 (val F1=0.4947)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41143 | val 1.05938
  Epoch 011 - train 0.37187 | val 1.35365
  Classification -> best τ=0.520 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53443 | val 1.58746
  Epoch 011 - train 0.54048 | val 1.59911
  Classification -> best τ=0.750 (val F1=0.1753)
  Directional -> Accuracy: 0.5735, MCC: -0.0751, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44939 | val 1.10638
  Epoch 012 - train 0.36937 | val 1.86199
  Classification -> best τ=0.625 (val F1=0.1873)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47455 | val 1.50595
  Epoch 012 - train 0.42214 | val 2.55413
  Classification -> best τ=0.650 (val F1=0.2784)
  Directional -> Accuracy: 0.6042, MCC: 0.2100, F1: 0.5778

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43389 | val 0.72574
  Epoch 011 - train 0.43295 | val 0.77783
  Classification -> best τ=0.565 (val F1=0.2691)
  Directional -> Accuracy: 0.4203, MCC: -0.0585, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52459 | val 1.30905
  Epoch 011 - train 0.48208 | val 1.77880
  Classification -> best τ=0.460 (val F1=0.2687)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50898 | val 2.68660
  Epoch 014 - train 0.36861 | val 3.19411
  Classification -> best τ=0.625 (val F1=0.2083)
  Directional -> Accuracy: 0.5263, MCC: 0.1326, F1: 0.1818

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51604 | val 1.15955
  Epoch 011 - train 0.45876 | val 1.20231
  Classification -> best τ=0.420 (val F1=0.3131)
  Directional -> Accuracy: 0.4286, MCC: -0.1783, F1: 0.2941

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55055 | val 0.79896
  Epoch 011 - train 0.54250 | val 0.81581
  Classification -> best τ=0.420 (val F1=0.2393)
  Directional -> Accuracy: 0.5500, MCC: 0.1214, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51834 | val 3.04629
  Epoch 015 - train 0.37620 | val 3.89572
  Classification -> best τ=0.570 (val F1=0.2667)
  Directional -> Accuracy: 0.5098, MCC: 0.0780, F1: 0.5902

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56491 | val 0.98573
  Epoch 014 - train 0.45642 | val 1.02078
  Classification -> best τ=0.460 (val F1=0.3067)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52938 | val 1.58975
  Epoch 011 - train 0.53249 | val 1.60197
  Classification -> best τ=0.465 (val F1=0.1176)
  Directional -> Accuracy: 0.6207, MCC: 0.1135, F1: 0.7381

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47517 | val 1.36159
  Epoch 011 - train 0.47148 | val 1.50639
  Classification -> best τ=0.240 (val F1=0.1958)
  Directional -> Accuracy: 0.5600, MCC: 0.2923, F1: 0.4590

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52912 | val 0.88580
  Epoch 012 - train 0.44886 | val 1.14839
  Classification -> best τ=0.655 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48622 | val 1.61465
  Epoch 011 - train 0.46979 | val 1.78645
  Classification -> best τ=0.375 (val F1=0.1921)
  Directional -> Accuracy: 0.5405, MCC: 0.1819, F1: 0.3929

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54082 | val 0.78251
  Epoch 015 - train 0.36487 | val 1.48088
  Classification -> best τ=0.360 (val F1=0.3214)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56016 | val 2.43004
  Epoch 011 - train 0.54979 | val 3.24385
  Classification -> best τ=0.430 (val F1=0.1087)
  Directional -> Accuracy: 0.5385, MCC: 0.0919, F1: 0.6591

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59095 | val 1.56486
  Epoch 011 - train 0.53337 | val 0.99175
  Classification -> best τ=0.580 (val F1=0.3191)
  Directional -> Accuracy: 0.5439, MCC: 0.1313, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50810 | val 2.73116
  Epoch 011 - train 0.48262 | val 3.16095
  Classification -> best τ=0.435 (val F1=0.1187)
  Directional -> Accuracy: 0.4923, MCC: 0.0632, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47018 | val 2.01416
  Epoch 012 - train 0.41897 | val 2.09909
  Classification -> best τ=0.775 (val F1=0.3563)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41204 | val 3.37140
  Epoch 011 - train 0.38601 | val 3.67831
  Classification -> best τ=0.605 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53158 | val 1.17298
  Epoch 011 - train 0.50864 | val 1.32652
  Classification -> best τ=0.375 (val F1=0.1803)
  Directional -> Accuracy: 0.5238, MCC: -0.1171, F1: 0.6774

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44912 | val 2.08674
  Epoch 011 - train 0.45051 | val 2.54520
  Classification -> best τ=0.295 (val F1=0.2614)
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38787 | val 1.26097
  Epoch 012 - train 0.38652 | val 1.42872
  Classification -> best τ=0.565 (val F1=0.3296)
  Directional -> Accuracy: 0.5000, MCC: -0.0580, F1: 0.6154

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51594 | val 1.04108
  Epoch 018 - train 0.33670 | val 1.34063
  Classification -> best τ=0.510 (val F1=0.4673)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49804 | val 0.79655
  Epoch 013 - train 0.41089 | val 0.85225
  Classification -> best τ=0.510 (val F1=0.3678)
  Directional -> Accuracy: 0.4048, MCC: -0.2368, F1: 0.5098

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43157 | val 0.98726
  Epoch 011 - train 0.40517 | val 0.98885
  Classification -> best τ=0.385 (val F1=0.3142)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58619 | val 1.03499
  Epoch 015 - train 0.43899 | val 1.24611
  Classification -> best τ=0.370 (val F1=0.3815)
  Directional -> Accuracy: 0.5139, MCC: 0.0820, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50258 | val 3.03327
  Epoch 012 - train 0.42732 | val 4.46780
  Classification -> best τ=0.285 (val F1=0.2717)
  Directional -> Accuracy: 0.5581, MCC: 0.2676, F1: 0.6885

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55632 | val 0.76420
  Epoch 012 - train 0.51878 | val 0.80711
  Classification -> best τ=0.410 (val F1=0.3366)
  Directional -> Accuracy: 0.6212, MCC: 0.1954, F1: 0.7126

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44201 | val 1.24867
  Epoch 011 - train 0.36522 | val 1.77429
  Classification -> best τ=0.450 (val F1=0.3001)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52553 | val 1.31030
  Epoch 011 - train 0.50875 | val 1.50179
  Classification -> best τ=0.530 (val F1=0.0804)
  Directional -> Accuracy: 0.5179, MCC: -0.0404, F1: 0.1290

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42298 | val 1.26454
  Epoch 011 - train 0.43224 | val 1.42894
  Classification -> best τ=0.520 (val F1=0.2539)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45400 | val 0.86481
  Epoch 013 - train 0.39646 | val 0.88785
  Classification -> best τ=0.380 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61617 | val 1.45488
  Epoch 015 - train 0.44521 | val 2.62990
  Classification -> best τ=0.195 (val F1=0.4182)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45229 | val 0.82706
  Epoch 011 - train 0.44494 | val 0.89677
  Classification -> best τ=0.520 (val F1=0.4438)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48861 | val 1.24707
  Epoch 011 - train 0.44676 | val 1.36413
  Classification -> best τ=0.620 (val F1=0.2500)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.2581

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49194 | val 0.90995
  Epoch 013 - train 0.39668 | val 1.01309
  Classification -> best τ=0.615 (val F1=0.3311)
  Directional -> Accuracy: 0.6250, MCC: 0.3651, F1: 0.6400

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56105 | val 1.29117
  Epoch 012 - train 0.52179 | val 1.11679
  Classification -> best τ=0.465 (val F1=0.2686)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.5200

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45227 | val 3.07000
  Epoch 011 - train 0.43955 | val 2.91354
  Classification -> best τ=0.820 (val F1=0.2649)
  Directional -> Accuracy: 0.5536, MCC: 0.1897, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61726 | val 1.02040
  Epoch 014 - train 0.50564 | val 1.04537
  Classification -> best τ=0.565 (val F1=0.2486)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43925 | val 3.53916
  Epoch 011 - train 0.41426 | val 2.32687
  Classification -> best τ=0.880 (val F1=0.0236)
  Directional -> Accuracy: 0.5091, MCC: 0.0014, F1: 0.5846

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62836 | val 2.62441

[I 2026-02-20 04:00:37,612] Trial 139 finished with value: 0.2762312673411787 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0045621872834133975, 'weight_decay': 4.429966248648082e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.3089097222051782, 'early_stopping_min_delta': 0.009444709826604421}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 014 - train 0.50956 | val 3.51969
  Classification -> best τ=0.575 (val F1=0.2354)
  Directional -> Accuracy: 0.6333, MCC: 0.2736, F1: 0.5417

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2762312673411787
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51224 | val 1.85540
  Epoch 011 - train 0.48272 | val 1.57337
  Classification -> best τ=0.440 (val F1=0.3013)
  Directional -> Accuracy: 0.6053, MCC: 0.1906, F1: 0.5161

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60056 | val 1.78764
  Epoch 014 - train 0.46545 | val 2.78340
  Classification -> best τ=0.440 (val F1=0.1857)
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48903 | val 1.03993
  Epoch 011 - train 0.48327 | val 0.96377
  Classification -> best τ=0.550 (val F1=0.3882)
  Directional -> Accuracy: 0.5000, MCC: 0.0766, F1: 0.1481

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50515 | val 2.23084
  Epoch 011 - train 0.46832 | val 2.24930
  Classification -> best τ=0.210 (val F1=0.1808)
  Directional -> Accuracy: 0.5676, MCC: 0.1294, F1: 0.6000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47468 | val 1.02734
  Epoch 011 - train 0.40859 | val 1.06586
  Classification -> best τ=0.560 (val F1=0.4247)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49887 | val 0.86217
  Epoch 011 - train 0.35369 | val 1.03715
  Classification -> best τ=0.510 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: -0.0455, F1: 0.4545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57007 | val 1.31340
  Epoch 011 - train 0.56665 | val 1.30887
  Classification -> best τ=0.260 (val F1=0.1783)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44550 | val 1.39954
  Epoch 011 - train 0.44028 | val 1.59766
  Classification -> best τ=0.455 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45734 | val 1.66029
  Epoch 012 - train 0.40162 | val 2.59358
  Classification -> best τ=0.655 (val F1=0.2784)
  Directional -> Accuracy: 0.6667, MCC: 0.3130, F1: 0.5294

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56470 | val 1.06299
  Epoch 011 - train 0.48659 | val 1.11613
  Classification -> best τ=0.285 (val F1=0.2971)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57814 | val 0.67282
  Epoch 020 - train 0.45963 | val 0.80218
  Classification -> best τ=0.340 (val F1=0.4191)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46040 | val 1.96296
  Epoch 012 - train 0.39743 | val 3.40936
  Classification -> best τ=0.570 (val F1=0.2650)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42193 | val 1.97037
  Epoch 012 - train 0.37390 | val 2.55639
  Classification -> best τ=0.315 (val F1=0.3536)
  Directional -> Accuracy: 0.4762, MCC: -0.0478, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59428 | val 0.73846
  Epoch 014 - train 0.55709 | val 0.73241
  Classification -> best τ=0.300 (val F1=0.2902)
  Directional -> Accuracy: 0.4667, MCC: -0.1111, F1: 0.6190

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44662 | val 2.66294
  Epoch 011 - train 0.42300 | val 3.07902
  Classification -> best τ=0.415 (val F1=0.2667)
  Directional -> Accuracy: 0.4314, MCC: -0.0965, F1: 0.5672

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54198 | val 0.63411
  Epoch 020 - train 0.35125 | val 1.13348
  Classification -> best τ=0.220 (val F1=0.3809)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48656 | val 3.50102
  Epoch 011 - train 0.48485 | val 4.34563
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46757 | val 1.23193
  Epoch 011 - train 0.50170 | val 1.53859
  Classification -> best τ=0.545 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61292 | val 0.91024
  Epoch 014 - train 0.48949 | val 1.25095
  Classification -> best τ=0.695 (val F1=0.2234)
  Directional -> Accuracy: 0.4375, MCC: 0.0129, F1: 0.1429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49872 | val 1.39747
  Epoch 011 - train 0.45970 | val 1.31159
  Classification -> best τ=0.275 (val F1=0.2457)
  Directional -> Accuracy: 0.6081, MCC: 0.2424, F1: 0.5915

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55261 | val 1.51504
  Epoch 011 - train 0.46888 | val 1.02366
  Classification -> best τ=0.530 (val F1=0.1723)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51918 | val 1.36413
  Epoch 011 - train 0.53267 | val 1.57496
  Classification -> best τ=0.400 (val F1=0.1157)
  Directional -> Accuracy: 0.5077, MCC: 0.0058, F1: 0.6444

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51808 | val 1.31252
  Epoch 011 - train 0.49764 | val 1.55988
  Classification -> best τ=0.635 (val F1=0.2644)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53749 | val 2.93070
  Epoch 011 - train 0.52392 | val 4.10059
  Classification -> best τ=0.305 (val F1=0.1793)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41624 | val 3.06810
  Epoch 011 - train 0.42907 | val 3.62523
  Classification -> best τ=0.445 (val F1=0.2040)
  Directional -> Accuracy: 0.5091, MCC: -0.0141, F1: 0.5970

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41943 | val 3.58626
  Epoch 011 - train 0.42718 | val 3.89834
  Classification -> best τ=0.690 (val F1=0.3039)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55557 | val 0.73335
  Epoch 011 - train 0.49889 | val 0.73916
  Classification -> best τ=0.550 (val F1=0.1698)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48684 | val 1.08360
  Epoch 011 - train 0.47728 | val 1.13872
  Classification -> best τ=0.290 (val F1=0.2971)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48724 | val 2.09508
  Epoch 011 - train 0.45954 | val 2.20762
  Classification -> best τ=0.515 (val F1=0.0601)
  Directional -> Accuracy: 0.6250, MCC: 0.2335, F1: 0.6809

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55462 | val 0.62553
  Epoch 020 - train 0.31337 | val 0.67594
  Classification -> best τ=0.660 (val F1=0.4673)
  Directional -> Accuracy: 0.5000, MCC: -0.0046, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46549 | val 1.32727
  Epoch 011 - train 0.44804 | val 1.37402
  Classification -> best τ=0.500 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46869 | val 0.93562
  Epoch 011 - train 0.43862 | val 0.94298
  Classification -> best τ=0.475 (val F1=0.3069)
  Directional -> Accuracy: 0.5510, MCC: 0.1535, F1: 0.7027

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55923 | val 0.84045
  Epoch 012 - train 0.50315 | val 0.91079
  Classification -> best τ=0.415 (val F1=0.3215)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47590 | val 1.71870
  Epoch 011 - train 0.46530 | val 1.50484
  Classification -> best τ=0.270 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48683 | val 1.33290
  Epoch 011 - train 0.48752 | val 1.57517
  Classification -> best τ=0.645 (val F1=0.2618)
  Directional -> Accuracy: 0.6364, MCC: 0.2911, F1: 0.6471

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40336 | val 0.88836
  Epoch 011 - train 0.40060 | val 0.93819
  Classification -> best τ=0.485 (val F1=0.1857)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58431 | val 0.89816
  Epoch 011 - train 0.55385 | val 0.99675
  Classification -> best τ=0.460 (val F1=0.2110)
  Directional -> Accuracy: 0.4286, MCC: -0.1925, F1: 0.2381

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43041 | val 1.21473
  Epoch 011 - train 0.44545 | val 1.45974
  Classification -> best τ=0.525 (val F1=0.2488)
  Directional -> Accuracy: 0.5870, MCC: 0.1594, F1: 0.6415

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50541 | val 0.95936
  Epoch 015 - train 0.43225 | val 1.01856
  Classification -> best τ=0.175 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52347 | val 1.35582
  Epoch 011 - train 0.48070 | val 1.29404
  Classification -> best τ=0.355 (val F1=0.3533)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47264 | val 1.18335
  Epoch 011 - train 0.43330 | val 1.00141
  Classification -> best τ=0.550 (val F1=0.1257)
  Directional -> Accuracy: 0.5111, MCC: 0.0134, F1: 0.6071

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58043 | val 0.99356
  Epoch 011 - train 0.50277 | val 0.94864
  Classification -> best τ=0.545 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.0741

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55442 | val 1.32820
  Epoch 011 - train 0.49373 | val 1.58647
  Classification -> best τ=0.490 (val F1=0.2015)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56956 | val 1.05718
  Epoch 011 - train 0.56816 | val 1.17107
  Classification -> best τ=0.575 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43809 | val 1.28031
  Epoch 011 - train 0.41774 | val 1.31034
  Classification -> best τ=0.565 (val F1=0.2308)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59207 | val 2.41967
  Epoch 011 - train 0.55392 | val 2.02800
  Classification -> best τ=0.570 (val F1=0.2064)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51189 | val 3.45875
  Epoch 011 - train 0.47928 | val 3.32361
  Classification -> best τ=0.755 (val F1=0.2114)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62669 | val 0.99142

[I 2026-02-20 04:02:10,813] Trial 140 finished with value: 0.25380248219435453 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.004288853821883112, 'weight_decay': 3.823962099842607e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.4657723938879249, 'early_stopping_min_delta': 0.009721429788852728}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 018 - train 0.43076 | val 1.30364
  Classification -> best τ=0.375 (val F1=0.2513)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25380248219435453
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53893 | val 2.35645
  Epoch 013 - train 0.42654 | val 2.22926
  Classification -> best τ=0.775 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0033, F1: 0.3077

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47058 | val 1.25943
  Epoch 013 - train 0.36035 | val 1.16913
  Classification -> best τ=0.410 (val F1=0.2471)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56617 | val 0.74384
  Epoch 011 - train 0.55573 | val 0.76823
  Classification -> best τ=0.615 (val F1=0.3835)
  Directional -> Accuracy: 0.5000, MCC: 0.0547, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48192 | val 2.82827
  Epoch 011 - train 0.50177 | val 3.50522
  Classification -> best τ=0.290 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51928 | val 1.40063
  Epoch 011 - train 0.44988 | val 1.31323
  Classification -> best τ=0.635 (val F1=0.2964)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35864 | val 1.13288
  Epoch 011 - train 0.32960 | val 1.01958
  Classification -> best τ=0.490 (val F1=0.1877)
  Directional -> Accuracy: 0.5435, MCC: 0.1557, F1: 0.0870

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53429 | val 1.64332
  Epoch 012 - train 0.45912 | val 1.99879
  Classification -> best τ=0.070 (val F1=0.2272)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57140 | val 4.98975
  Epoch 017 - train 0.28552 | val 6.94664
  Classification -> best τ=0.060 (val F1=0.1657)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46678 | val 3.96899
  Epoch 011 - train 0.46172 | val 4.32552
  Classification -> best τ=0.610 (val F1=0.3441)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58226 | val 0.94070
  Epoch 017 - train 0.38931 | val 0.84534
  Classification -> best τ=0.480 (val F1=0.3141)
  Directional -> Accuracy: 0.4638, MCC: 0.0348, F1: 0.5647

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60297 | val 1.86712
  Epoch 014 - train 0.41838 | val 2.18223
  Classification -> best τ=0.480 (val F1=0.4488)
  Directional -> Accuracy: 0.6735, MCC: 0.3783, F1: 0.4667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42289 | val 3.38316
  Epoch 011 - train 0.39108 | val 3.71988
  Classification -> best τ=0.630 (val F1=0.1601)
  Directional -> Accuracy: 0.5614, MCC: 0.1950, F1: 0.3243

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47881 | val 0.95934
  Epoch 012 - train 0.40469 | val 0.98123
  Classification -> best τ=0.375 (val F1=0.3070)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60745 | val 1.04691
  Epoch 015 - train 0.47439 | val 1.18294
  Classification -> best τ=0.485 (val F1=0.3477)
  Directional -> Accuracy: 0.5833, MCC: 0.1690, F1: 0.5455

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54666 | val 1.84337
  Epoch 014 - train 0.35531 | val 3.64922
  Classification -> best τ=0.620 (val F1=0.2720)
  Directional -> Accuracy: 0.5098, MCC: 0.0780, F1: 0.5902

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59299 | val 0.84820
  Epoch 012 - train 0.48722 | val 0.88901
  Classification -> best τ=0.415 (val F1=0.3486)
  Directional -> Accuracy: 0.5217, MCC: -0.0357, F1: 0.6733

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54129 | val 1.29911
  Epoch 012 - train 0.45859 | val 1.80311
  Classification -> best τ=0.560 (val F1=0.1179)
  Directional -> Accuracy: 0.4828, MCC: -0.1918, F1: 0.6250

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47573 | val 2.49613
  Epoch 011 - train 0.47938 | val 2.93697
  Classification -> best τ=0.475 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59639 | val 1.09602
  Epoch 019 - train 0.40515 | val 2.19545
  Classification -> best τ=0.595 (val F1=0.2326)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48658 | val 1.04637
  Epoch 011 - train 0.44512 | val 1.16267
  Classification -> best τ=0.165 (val F1=0.1895)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47575 | val 3.41535
  Epoch 012 - train 0.40721 | val 1.96158
  Classification -> best τ=0.445 (val F1=0.2784)
  Directional -> Accuracy: 0.5957, MCC: 0.0121, F1: 0.7324

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52469 | val 3.21114
  Epoch 011 - train 0.50654 | val 4.28227
  Classification -> best τ=0.670 (val F1=0.2376)
  Directional -> Accuracy: 0.4308, MCC: -0.2175, F1: 0.0513

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62266 | val 0.71548
  Epoch 011 - train 0.62652 | val 0.72712
  Classification -> best τ=0.605 (val F1=0.3421)
  Directional -> Accuracy: 0.4912, MCC: 0.0353, F1: 0.4082

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48182 | val 1.96428
  Epoch 011 - train 0.51203 | val 2.64484
  Classification -> best τ=0.550 (val F1=0.2111)
  Directional -> Accuracy: 0.4923, MCC: 0.0112, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49143 | val 1.03827
  Epoch 013 - train 0.40797 | val 1.46482
  Classification -> best τ=0.280 (val F1=0.5489)
  Directional -> Accuracy: 0.5455, MCC: 0.1365, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40876 | val 3.59730
  Epoch 011 - train 0.36447 | val 4.45692
  Classification -> best τ=0.710 (val F1=0.1932)
  Directional -> Accuracy: 0.3778, MCC: -0.1941, F1: 0.5172

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51542 | val 1.03539
  Epoch 015 - train 0.37348 | val 0.90844
  Classification -> best τ=0.605 (val F1=0.1353)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44113 | val 2.55849
  Epoch 011 - train 0.41134 | val 2.24820
  Classification -> best τ=0.640 (val F1=0.0349)
  Directional -> Accuracy: 0.4107, MCC: -0.1694, F1: 0.0571

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39986 | val 1.23637
  Epoch 011 - train 0.37899 | val 1.23619
  Classification -> best τ=0.620 (val F1=0.2774)
  Directional -> Accuracy: 0.5500, MCC: 0.1111, F1: 0.5500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62592 | val 0.80508
  Epoch 011 - train 0.62188 | val 0.89750
  Classification -> best τ=0.675 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44340 | val 1.25644
  Epoch 011 - train 0.40259 | val 2.19248
  Classification -> best τ=0.385 (val F1=0.2901)
  Directional -> Accuracy: 0.4048, MCC: -0.2460, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40056 | val 1.05097
  Epoch 011 - train 0.40525 | val 0.94860
  Classification -> best τ=0.570 (val F1=0.2969)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56405 | val 0.90100
  Epoch 014 - train 0.48567 | val 1.61047
  Classification -> best τ=0.285 (val F1=0.4114)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49369 | val 2.62215
  Epoch 011 - train 0.44679 | val 2.72112
  Classification -> best τ=0.755 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52860 | val 0.95204
  Epoch 011 - train 0.51150 | val 1.07683
  Classification -> best τ=0.600 (val F1=0.1279)
  Directional -> Accuracy: 0.5606, MCC: 0.1226, F1: 0.5915

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44943 | val 0.82242
  Epoch 015 - train 0.26024 | val 2.07064
  Classification -> best τ=0.665 (val F1=0.2618)
  Directional -> Accuracy: 0.5476, MCC: 0.1494, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48063 | val 1.04673
  Epoch 011 - train 0.47583 | val 1.41451
  Classification -> best τ=0.610 (val F1=0.1508)
  Directional -> Accuracy: 0.5893, MCC: 0.1776, F1: 0.3429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45325 | val 1.38908
  Epoch 012 - train 0.35865 | val 1.55436
  Classification -> best τ=0.485 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46882 | val 0.78285
  Epoch 019 - train 0.24364 | val 0.82694
  Classification -> best τ=0.345 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59482 | val 2.01820
  Epoch 016 - train 0.43509 | val 1.12982
  Classification -> best τ=0.125 (val F1=0.3426)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52398 | val 3.48677
  Epoch 013 - train 0.33960 | val 5.49709
  Classification -> best τ=0.475 (val F1=0.5976)
  Directional -> Accuracy: 0.4667, MCC: -0.2109, F1: 0.6364

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49531 | val 0.89866
  Epoch 015 - train 0.37404 | val 1.59487
  Classification -> best τ=0.475 (val F1=0.5593)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45137 | val 0.80096
  Epoch 011 - train 0.42497 | val 0.83944
  Classification -> best τ=0.445 (val F1=0.1667)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50452 | val 2.48919
  Epoch 011 - train 0.47148 | val 2.85442
  Classification -> best τ=0.510 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41823 | val 2.94849
  Epoch 011 - train 0.40821 | val 2.61616
  Classification -> best τ=0.710 (val F1=0.2649)
  Directional -> Accuracy: 0.5714, MCC: 0.1992, F1: 0.2500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54296 | val 0.90955
  Epoch 012 - train 0.53972 | val 0.77309
  Classification -> best τ=0.605 (val F1=0.1133)
  Directional -> Accuracy: 0.4717, MCC: -0.0707, F1: 0.1250

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59970 | val 2.83864
  Epoch 011 - train 0.55368 | val 3.46295
  Classification -> best τ=0.885 (val F1=0.1210)
  Directional -> Accuracy: 0.4909, MCC: -0.0452, F1: 0.5882

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48434 | val 1.61784

[I 2026-02-20 04:03:52,016] Trial 141 finished with value: 0.27433218302682594 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005688194219831858, 'weight_decay': 4.60768748367708e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.3045141273615421, 'early_stopping_min_delta': 0.009485811638978693}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.43587 | val 1.81492
  Classification -> best τ=0.495 (val F1=0.2749)
  Directional -> Accuracy: 0.5500, MCC: 0.1179, F1: 0.6087

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27433218302682594
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50125 | val 1.56597
  Epoch 011 - train 0.46151 | val 1.97839
  Classification -> best τ=0.765 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0371, F1: 0.1818

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58678 | val 0.90507
  Epoch 016 - train 0.42005 | val 1.53596
  Classification -> best τ=0.415 (val F1=0.2025)
  Directional -> Accuracy: 0.4444, MCC: -0.1022, F1: 0.4681

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51073 | val 0.90468
  Epoch 012 - train 0.48731 | val 0.83439
  Classification -> best τ=0.680 (val F1=0.3835)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53797 | val 1.63081
  Epoch 012 - train 0.51754 | val 1.31960
  Classification -> best τ=0.285 (val F1=0.1627)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40949 | val 0.99161
  Epoch 011 - train 0.39392 | val 1.20052
  Classification -> best τ=0.285 (val F1=0.5570)
  Directional -> Accuracy: 0.6000, MCC: 0.1961, F1: 0.6429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51111 | val 1.74039
  Epoch 016 - train 0.28860 | val 1.15302
  Classification -> best τ=0.715 (val F1=0.4056)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58386 | val 2.70441
  Epoch 011 - train 0.56257 | val 3.03373
  Classification -> best τ=0.525 (val F1=0.2878)
  Directional -> Accuracy: 0.4412, MCC: 0.1743, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52535 | val 4.30109
  Epoch 016 - train 0.44805 | val 2.75360
  Classification -> best τ=0.395 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0807, F1: 0.3571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43497 | val 2.05593
  Epoch 011 - train 0.42323 | val 1.52965
  Classification -> best τ=0.545 (val F1=0.1465)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59672 | val 0.83192
  Epoch 017 - train 0.35550 | val 1.54263
  Classification -> best τ=0.370 (val F1=0.2208)
  Directional -> Accuracy: 0.4493, MCC: -0.0913, F1: 0.4242

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61374 | val 0.83159
  Epoch 017 - train 0.38256 | val 0.82466
  Classification -> best τ=0.705 (val F1=0.4059)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53781 | val 0.85286
  Epoch 013 - train 0.37996 | val 1.60955
  Classification -> best τ=0.800 (val F1=0.2741)
  Directional -> Accuracy: 0.4912, MCC: -0.0100, F1: 0.3256

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36425 | val 1.99686
  Epoch 011 - train 0.35601 | val 2.06376
  Classification -> best τ=0.395 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55663 | val 1.31755
  Epoch 012 - train 0.49376 | val 2.01675
  Classification -> best τ=0.405 (val F1=0.3852)
  Directional -> Accuracy: 0.5167, MCC: 0.0603, F1: 0.6588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70270 | val 0.99700
  Epoch 015 - train 0.41812 | val 1.71238
  Classification -> best τ=0.815 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53722 | val 1.73754
  Epoch 011 - train 0.50225 | val 1.88489
  Classification -> best τ=0.595 (val F1=0.1890)
  Directional -> Accuracy: 0.6087, MCC: 0.2060, F1: 0.6824

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56241 | val 1.40774
  Epoch 011 - train 0.52873 | val 1.57603
  Classification -> best τ=0.605 (val F1=0.1842)
  Directional -> Accuracy: 0.3621, MCC: -0.1694, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47030 | val 1.86324
  Epoch 012 - train 0.44145 | val 2.80844
  Classification -> best τ=0.215 (val F1=0.1962)
  Directional -> Accuracy: 0.5867, MCC: -0.0278, F1: 0.7350

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53413 | val 1.48472
  Epoch 011 - train 0.51233 | val 1.34762
  Classification -> best τ=0.300 (val F1=0.1755)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42516 | val 1.71482
  Epoch 011 - train 0.43604 | val 1.59202
  Classification -> best τ=0.700 (val F1=0.3769)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53169 | val 1.10326
  Epoch 018 - train 0.31262 | val 1.97388
  Classification -> best τ=0.435 (val F1=0.4059)
  Directional -> Accuracy: 0.4043, MCC: -0.0999, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54591 | val 2.18343
  Epoch 012 - train 0.51033 | val 3.57395
  Classification -> best τ=0.485 (val F1=0.2327)
  Directional -> Accuracy: 0.4769, MCC: -0.0507, F1: 0.1905

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49331 | val 0.70728
  Epoch 011 - train 0.45467 | val 0.79201
  Classification -> best τ=0.610 (val F1=0.3421)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58940 | val 2.51989
  Epoch 014 - train 0.43928 | val 3.67606
  Classification -> best τ=0.565 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46073 | val 1.39112
  Epoch 011 - train 0.42363 | val 1.30345
  Classification -> best τ=0.740 (val F1=0.2446)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62363 | val 3.87494
  Epoch 011 - train 0.58456 | val 3.38060
  Classification -> best τ=0.795 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48635 | val 1.30706
  Epoch 012 - train 0.38225 | val 1.10883
  Classification -> best τ=0.565 (val F1=0.1667)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51415 | val 1.56679
  Epoch 011 - train 0.49098 | val 1.84690
  Classification -> best τ=0.275 (val F1=0.2096)
  Directional -> Accuracy: 0.5000, MCC: 0.0460, F1: 0.4167

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50172 | val 0.84017
  Epoch 011 - train 0.43711 | val 0.95311
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55541 | val 0.71882
  Epoch 016 - train 0.37542 | val 0.82516
  Classification -> best τ=0.500 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0195, F1: 0.6071

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39619 | val 0.85675
  Epoch 011 - train 0.37389 | val 0.79225
  Classification -> best τ=0.530 (val F1=0.4083)
  Directional -> Accuracy: 0.4524, MCC: -0.0310, F1: 0.1481

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40668 | val 0.93007
  Epoch 011 - train 0.36257 | val 1.24778
  Classification -> best τ=0.445 (val F1=0.3541)
  Directional -> Accuracy: 0.3878, MCC: -0.2164, F1: 0.3182

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57862 | val 1.29477
  Epoch 013 - train 0.43144 | val 1.76683
  Classification -> best τ=0.465 (val F1=0.2957)
  Directional -> Accuracy: 0.5278, MCC: 0.0988, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39792 | val 2.74755
  Epoch 011 - train 0.38242 | val 3.56266
  Classification -> best τ=0.785 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49042 | val 1.38365
  Epoch 012 - train 0.43128 | val 1.21185
  Classification -> best τ=0.310 (val F1=0.4042)
  Directional -> Accuracy: 0.6515, MCC: 0.2901, F1: 0.6933

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40523 | val 0.94548
  Epoch 011 - train 0.36805 | val 0.98982
  Classification -> best τ=0.440 (val F1=0.2067)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49512 | val 1.58831
  Epoch 013 - train 0.37995 | val 2.64379
  Classification -> best τ=0.380 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: -0.0051, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47650 | val 1.03913
  Epoch 012 - train 0.39322 | val 1.15047
  Classification -> best τ=0.510 (val F1=0.4547)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49462 | val 0.78786
  Epoch 013 - train 0.30689 | val 0.70752
  Classification -> best τ=0.335 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45871 | val 2.14252
  Epoch 011 - train 0.43908 | val 3.22483
  Classification -> best τ=0.500 (val F1=0.2700)
  Directional -> Accuracy: 0.5405, MCC: 0.1901, F1: 0.6731

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44955 | val 0.80942
  Epoch 012 - train 0.35743 | val 0.92401
  Classification -> best τ=0.580 (val F1=0.0271)
  Directional -> Accuracy: 0.4667, MCC: -0.0696, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52912 | val 0.77023
  Epoch 011 - train 0.45927 | val 0.86352
  Classification -> best τ=0.520 (val F1=0.2010)
  Directional -> Accuracy: 0.4524, MCC: -0.0313, F1: 0.3429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46497 | val 0.93999
  Epoch 012 - train 0.34527 | val 0.96579
  Classification -> best τ=0.705 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60285 | val 2.63106
  Epoch 013 - train 0.45099 | val 3.71677
  Classification -> best τ=0.625 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40447 | val 2.57269
  Epoch 011 - train 0.38066 | val 1.84133
  Classification -> best τ=0.800 (val F1=0.2649)
  Directional -> Accuracy: 0.4821, MCC: -0.0875, F1: 0.1714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50809 | val 0.84744
  Epoch 011 - train 0.50465 | val 0.90233
  Classification -> best τ=0.490 (val F1=0.2369)
  Directional -> Accuracy: 0.5283, MCC: 0.0588, F1: 0.6479

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48828 | val 3.74391
  Epoch 011 - train 0.43258 | val 5.11706
  Classification -> best τ=0.500 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54382 | val 1.27480

[I 2026-02-20 04:05:30,621] Trial 142 finished with value: 0.26550561382802873 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007197025151737402, 'weight_decay': 5.798254604775551e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.4205463660680458, 'early_stopping_min_delta': 0.009143887885306507}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.41959 | val 1.32837
  Classification -> best τ=0.330 (val F1=0.2124)
  Directional -> Accuracy: 0.4500, MCC: -0.0965, F1: 0.4762

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26550561382802873
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54595 | val 1.74886
  Epoch 011 - train 0.51940 | val 2.09422
  Classification -> best τ=0.460 (val F1=0.2082)
  Directional -> Accuracy: 0.5000, MCC: 0.1653, F1: 0.6346

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54155 | val 1.27004
  Epoch 014 - train 0.43548 | val 1.05910
  Classification -> best τ=0.405 (val F1=0.3119)
  Directional -> Accuracy: 0.5778, MCC: 0.0618, F1: 0.7077

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49816 | val 1.30834
  Epoch 012 - train 0.45395 | val 1.38911
  Classification -> best τ=0.500 (val F1=0.2941)
  Directional -> Accuracy: 0.4130, MCC: -0.2249, F1: 0.0690

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51827 | val 3.04511
  Epoch 011 - train 0.48477 | val 2.40415
  Classification -> best τ=0.250 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41111 | val 1.10616
  Epoch 011 - train 0.38444 | val 1.79135
  Classification -> best τ=0.625 (val F1=0.3612)
  Directional -> Accuracy: 0.4800, MCC: -0.0118, F1: 0.1333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44904 | val 0.69331
  Epoch 015 - train 0.33754 | val 0.73402
  Classification -> best τ=0.625 (val F1=0.4559)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54118 | val 1.52185
  Epoch 011 - train 0.52130 | val 1.66373
  Classification -> best τ=0.310 (val F1=0.3636)
  Directional -> Accuracy: 0.4559, MCC: 0.1097, F1: 0.5747

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43120 | val 3.17383
  Epoch 011 - train 0.39510 | val 3.02906
  Classification -> best τ=0.580 (val F1=0.0668)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47033 | val 0.98017
  Epoch 011 - train 0.46935 | val 1.07651
  Classification -> best τ=0.605 (val F1=0.2233)
  Directional -> Accuracy: 0.4583, MCC: 0.0258, F1: 0.5938

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47099 | val 0.67014
  Epoch 020 - train 0.27445 | val 0.84485
  Classification -> best τ=0.310 (val F1=0.4167)
  Directional -> Accuracy: 0.4783, MCC: -0.0232, F1: 0.4706

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50821 | val 0.68077
  Epoch 020 - train 0.33237 | val 0.96623
  Classification -> best τ=0.740 (val F1=0.3590)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47864 | val 3.27434
  Epoch 012 - train 0.42951 | val 5.07518
  Classification -> best τ=0.520 (val F1=0.2218)
  Directional -> Accuracy: 0.4561, MCC: -0.0860, F1: 0.4151

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43751 | val 1.83897
  Epoch 011 - train 0.43510 | val 2.47465
  Classification -> best τ=0.250 (val F1=0.2522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57878 | val 0.83887
  Epoch 011 - train 0.53776 | val 0.91064
  Classification -> best τ=0.405 (val F1=0.2516)
  Directional -> Accuracy: 0.5167, MCC: 0.0431, F1: 0.6329

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48617 | val 2.12756
  Epoch 012 - train 0.44668 | val 3.33048
  Classification -> best τ=0.680 (val F1=0.2951)
  Directional -> Accuracy: 0.5098, MCC: 0.0661, F1: 0.5763

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50055 | val 0.85208
  Epoch 012 - train 0.46453 | val 1.00940
  Classification -> best τ=0.685 (val F1=0.3700)
  Directional -> Accuracy: 0.5362, MCC: 0.0367, F1: 0.6522

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53324 | val 2.02552
  Epoch 011 - train 0.52962 | val 2.31793
  Classification -> best τ=0.770 (val F1=0.0732)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52712 | val 0.99487
  Epoch 011 - train 0.53103 | val 1.05019
  Classification -> best τ=0.495 (val F1=0.0159)
  Directional -> Accuracy: 0.5333, MCC: -0.0375, F1: 0.6535

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52524 | val 0.97043
  Epoch 011 - train 0.50581 | val 0.92483
  Classification -> best τ=0.375 (val F1=0.1755)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48287 | val 1.33412
  Epoch 011 - train 0.49296 | val 1.40041
  Classification -> best τ=0.575 (val F1=0.3734)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53641 | val 1.04631
  Epoch 013 - train 0.42077 | val 2.11929
  Classification -> best τ=0.540 (val F1=0.4828)
  Directional -> Accuracy: 0.4681, MCC: 0.0598, F1: 0.3902

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51383 | val 1.60350
  Epoch 012 - train 0.48155 | val 1.70152
  Classification -> best τ=0.500 (val F1=0.2216)
  Directional -> Accuracy: 0.5385, MCC: 0.1011, F1: 0.3750

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54423 | val 0.95202
  Epoch 011 - train 0.51187 | val 0.97576
  Classification -> best τ=0.400 (val F1=0.2010)
  Directional -> Accuracy: 0.4737, MCC: -0.0887, F1: 0.5588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55319 | val 1.28515
  Epoch 011 - train 0.53741 | val 1.52396
  Classification -> best τ=0.565 (val F1=0.1565)
  Directional -> Accuracy: 0.5077, MCC: 0.0359, F1: 0.5789

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47718 | val 2.62242
  Epoch 011 - train 0.44200 | val 2.75856
  Classification -> best τ=0.520 (val F1=0.2376)
  Directional -> Accuracy: 0.5455, MCC: 0.0864, F1: 0.5763

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49095 | val 2.05707
  Epoch 011 - train 0.44167 | val 2.10805
  Classification -> best τ=0.520 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56556 | val 0.76499
  Epoch 015 - train 0.46018 | val 1.06662
  Classification -> best τ=0.395 (val F1=0.1803)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54221 | val 1.52434
  Epoch 011 - train 0.49034 | val 1.71643
  Classification -> best τ=0.455 (val F1=0.2999)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43730 | val 1.79161
  Epoch 011 - train 0.41723 | val 2.16670
  Classification -> best τ=0.555 (val F1=0.1457)
  Directional -> Accuracy: 0.5750, MCC: 0.1234, F1: 0.6531

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54947 | val 1.07892
  Epoch 017 - train 0.36730 | val 0.83630
  Classification -> best τ=0.345 (val F1=0.4879)
  Directional -> Accuracy: 0.4524, MCC: -0.0826, F1: 0.5490

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49835 | val 2.18876
  Epoch 011 - train 0.42556 | val 2.47761
  Classification -> best τ=0.435 (val F1=0.1707)
  Directional -> Accuracy: 0.5952, MCC: 0.2835, F1: 0.4848

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46001 | val 0.87208
  Epoch 011 - train 0.42888 | val 1.02148
  Classification -> best τ=0.465 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57062 | val 0.78125
  Epoch 015 - train 0.45768 | val 0.90576
  Classification -> best τ=0.290 (val F1=0.3477)
  Directional -> Accuracy: 0.5833, MCC: 0.1890, F1: 0.5714

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48179 | val 2.82352
  Epoch 011 - train 0.45818 | val 2.38088
  Classification -> best τ=0.470 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47675 | val 0.87496
  Epoch 011 - train 0.44515 | val 0.82387
  Classification -> best τ=0.445 (val F1=0.4538)
  Directional -> Accuracy: 0.6515, MCC: 0.2834, F1: 0.7013

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38360 | val 1.01716
  Epoch 011 - train 0.36586 | val 1.08467
  Classification -> best τ=0.490 (val F1=0.2106)
  Directional -> Accuracy: 0.5952, MCC: 0.2427, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44669 | val 1.00412
  Epoch 011 - train 0.42553 | val 1.55914
  Classification -> best τ=0.420 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41363 | val 1.09355
  Epoch 011 - train 0.37948 | val 1.16054
  Classification -> best τ=0.475 (val F1=0.2852)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49274 | val 0.87786
  Epoch 014 - train 0.38382 | val 0.83340
  Classification -> best τ=0.335 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50696 | val 1.39592
  Epoch 011 - train 0.49310 | val 1.38208
  Classification -> best τ=0.235 (val F1=0.3823)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48996 | val 0.84462
  Epoch 013 - train 0.42828 | val 1.48560
  Classification -> best τ=0.415 (val F1=0.2092)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49376 | val 1.36122
  Epoch 011 - train 0.41906 | val 1.30146
  Classification -> best τ=0.610 (val F1=0.3612)
  Directional -> Accuracy: 0.3571, MCC: -0.2759, F1: 0.0690

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51838 | val 1.42263
  Epoch 017 - train 0.28282 | val 1.00882
  Classification -> best τ=0.670 (val F1=0.4216)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55152 | val 1.33289
  Epoch 011 - train 0.55992 | val 1.42300
  Classification -> best τ=0.470 (val F1=0.1372)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45229 | val 2.19342
  Epoch 011 - train 0.41875 | val 2.25641
  Classification -> best τ=0.605 (val F1=0.2640)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50974 | val 0.80663
  Epoch 011 - train 0.49979 | val 0.82804
  Classification -> best τ=0.465 (val F1=0.1801)
  Directional -> Accuracy: 0.5660, MCC: 0.1375, F1: 0.6462

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48390 | val 4.56400
  Epoch 011 - train 0.47557 | val 5.72461
  Classification -> best τ=0.875 (val F1=0.0236)
  Directional -> Accuracy: 0.5636, MCC: 0.1258, F1: 0.6842

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51747 | val 1.44949

[I 2026-02-20 04:07:08,080] Trial 143 finished with value: 0.26790936210353494 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0029777500973153493, 'weight_decay': 7.0263470714891e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.43711898973095054, 'early_stopping_min_delta': 0.008860393208402085}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.46236 | val 1.80696
  Classification -> best τ=0.515 (val F1=0.1638)
  Directional -> Accuracy: 0.5500, MCC: 0.1307, F1: 0.6301

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26790936210353494
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52046 | val 1.28737
  Epoch 012 - train 0.54951 | val 1.06018
  Classification -> best τ=0.500 (val F1=0.2799)
  Directional -> Accuracy: 0.5132, MCC: 0.0530, F1: 0.5432

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48917 | val 0.76932
  Epoch 012 - train 0.43241 | val 1.16492
  Classification -> best τ=0.375 (val F1=0.2103)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52384 | val 1.58202
  Epoch 011 - train 0.47659 | val 1.50343
  Classification -> best τ=0.545 (val F1=0.3589)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58553 | val 1.21199
  Epoch 014 - train 0.46069 | val 3.08881
  Classification -> best τ=0.325 (val F1=0.1722)
  Directional -> Accuracy: 0.5811, MCC: 0.1585, F1: 0.6076

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46262 | val 1.09880
  Epoch 011 - train 0.40563 | val 1.02306
  Classification -> best τ=0.680 (val F1=0.2763)
  Directional -> Accuracy: 0.4800, MCC: -0.0175, F1: 0.2353

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46716 | val 1.58448
  Epoch 012 - train 0.41832 | val 1.33381
  Classification -> best τ=0.610 (val F1=0.2585)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54185 | val 0.83295
  Epoch 011 - train 0.52294 | val 0.93470
  Classification -> best τ=0.575 (val F1=0.2492)
  Directional -> Accuracy: 0.4559, MCC: 0.0100, F1: 0.5195

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52546 | val 2.09874
  Epoch 011 - train 0.49389 | val 1.85995
  Classification -> best τ=0.485 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48525 | val 3.16066
  Epoch 011 - train 0.46539 | val 4.18392
  Classification -> best τ=0.545 (val F1=0.2784)
  Directional -> Accuracy: 0.6250, MCC: 0.2698, F1: 0.6250

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60162 | val 1.25598
  Epoch 014 - train 0.49435 | val 1.70578
  Classification -> best τ=0.585 (val F1=0.3006)
  Directional -> Accuracy: 0.4058, MCC: -0.1424, F1: 0.5773

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63330 | val 0.93211
  Epoch 014 - train 0.45080 | val 0.68038
  Classification -> best τ=0.570 (val F1=0.4196)
  Directional -> Accuracy: 0.5510, MCC: 0.0782, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47370 | val 3.66631
  Epoch 011 - train 0.41338 | val 4.16404
  Classification -> best τ=0.455 (val F1=0.3147)
  Directional -> Accuracy: 0.6140, MCC: 0.2274, F1: 0.6333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48449 | val 2.70755
  Epoch 017 - train 0.36940 | val 1.22514
  Classification -> best τ=0.750 (val F1=0.2902)
  Directional -> Accuracy: 0.4762, MCC: -0.0912, F1: 0.3125

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60570 | val 1.51859
  Epoch 012 - train 0.57407 | val 1.28328
  Classification -> best τ=0.465 (val F1=0.2531)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47138 | val 2.98619
  Epoch 011 - train 0.45580 | val 3.31210
  Classification -> best τ=0.330 (val F1=0.3140)
  Directional -> Accuracy: 0.4902, MCC: 0.0183, F1: 0.5517

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61588 | val 0.78358
  Epoch 015 - train 0.52106 | val 1.09539
  Classification -> best τ=0.590 (val F1=0.2097)
  Directional -> Accuracy: 0.5362, MCC: 0.0906, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53739 | val 1.40757
  Epoch 012 - train 0.46651 | val 1.69812
  Classification -> best τ=0.845 (val F1=0.1291)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50279 | val 1.17232
  Epoch 011 - train 0.51954 | val 0.98769
  Classification -> best τ=0.680 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54458 | val 1.01288
  Epoch 012 - train 0.52167 | val 1.07441
  Classification -> best τ=0.635 (val F1=0.1517)
  Directional -> Accuracy: 0.4375, MCC: 0.0398, F1: 0.1000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53710 | val 1.52523
  Epoch 011 - train 0.50706 | val 1.84221
  Classification -> best τ=0.125 (val F1=0.2482)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51290 | val 0.96701
  Epoch 011 - train 0.47100 | val 0.95274
  Classification -> best τ=0.485 (val F1=0.1723)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63049 | val 1.17538
  Epoch 016 - train 0.50181 | val 1.42443
  Classification -> best τ=0.705 (val F1=0.1958)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62947 | val 0.72289
  Epoch 014 - train 0.51341 | val 0.84650
  Classification -> best τ=0.590 (val F1=0.3370)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53926 | val 1.62117
  Epoch 011 - train 0.53278 | val 1.60420
  Classification -> best τ=0.550 (val F1=0.2192)
  Directional -> Accuracy: 0.5077, MCC: 0.1701, F1: 0.6596

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57507 | val 1.09484
  Epoch 014 - train 0.45489 | val 1.74357
  Classification -> best τ=0.520 (val F1=0.4582)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43831 | val 2.47127
  Epoch 011 - train 0.47287 | val 2.23381
  Classification -> best τ=0.575 (val F1=0.1048)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58155 | val 0.76689
  Epoch 013 - train 0.46336 | val 0.96616
  Classification -> best τ=0.480 (val F1=0.1925)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.2000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51055 | val 1.56722
  Epoch 011 - train 0.46072 | val 1.90633
  Classification -> best τ=0.485 (val F1=0.0770)
  Directional -> Accuracy: 0.5000, MCC: 0.1222, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43421 | val 0.89901
  Epoch 013 - train 0.41762 | val 1.37777
  Classification -> best τ=0.450 (val F1=0.3296)
  Directional -> Accuracy: 0.6750, MCC: 0.3550, F1: 0.7547

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56200 | val 1.16779
  Epoch 016 - train 0.41114 | val 1.10228
  Classification -> best τ=0.410 (val F1=0.5198)
  Directional -> Accuracy: 0.5238, MCC: 0.1469, F1: 0.6552

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55558 | val 0.73515
  Epoch 015 - train 0.44321 | val 0.99754
  Classification -> best τ=0.480 (val F1=0.3337)
  Directional -> Accuracy: 0.4762, MCC: 0.0663, F1: 0.1538

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57119 | val 1.07178
  Epoch 011 - train 0.50249 | val 1.10887
  Classification -> best τ=0.455 (val F1=0.2609)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54704 | val 0.75760
  Epoch 012 - train 0.49045 | val 0.89956
  Classification -> best τ=0.495 (val F1=0.3534)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51577 | val 2.64941
  Epoch 011 - train 0.49536 | val 2.37996
  Classification -> best τ=0.330 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57794 | val 1.01723
  Epoch 014 - train 0.46690 | val 1.03635
  Classification -> best τ=0.225 (val F1=0.3525)
  Directional -> Accuracy: 0.6212, MCC: 0.2211, F1: 0.6753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50932 | val 0.75860
  Epoch 014 - train 0.37027 | val 0.93399
  Classification -> best τ=0.405 (val F1=0.3001)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48246 | val 1.46054
  Epoch 011 - train 0.47208 | val 2.40921
  Classification -> best τ=0.290 (val F1=0.1690)
  Directional -> Accuracy: 0.5714, MCC: 0.1432, F1: 0.5556

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42899 | val 1.20855
  Epoch 011 - train 0.39458 | val 1.09145
  Classification -> best τ=0.575 (val F1=0.5235)
  Directional -> Accuracy: 0.5652, MCC: 0.1434, F1: 0.6000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53299 | val 0.69391
  Epoch 016 - train 0.48695 | val 0.98083
  Classification -> best τ=0.310 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48968 | val 1.34360
  Epoch 011 - train 0.47757 | val 1.61134
  Classification -> best τ=0.210 (val F1=0.3053)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47463 | val 1.29276
  Epoch 011 - train 0.43217 | val 1.12265
  Classification -> best τ=0.490 (val F1=0.2712)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53066 | val 1.16172
  Epoch 013 - train 0.49695 | val 1.49484
  Classification -> best τ=0.555 (val F1=0.6124)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61292 | val 0.90632
  Epoch 018 - train 0.32582 | val 0.92153
  Classification -> best τ=0.660 (val F1=0.3149)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57715 | val 1.49092
  Epoch 012 - train 0.53285 | val 1.46181
  Classification -> best τ=0.540 (val F1=0.1605)
  Directional -> Accuracy: 0.4182, MCC: -0.1913, F1: 0.5000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62476 | val 1.43087
  Epoch 011 - train 0.62337 | val 1.22727
  Classification -> best τ=0.605 (val F1=0.3633)
  Directional -> Accuracy: 0.5536, MCC: 0.1444, F1: 0.6377

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62121 | val 1.20448
  Epoch 013 - train 0.54943 | val 2.30508
  Classification -> best τ=0.545 (val F1=0.3208)
  Directional -> Accuracy: 0.5094, MCC: 0.0124, F1: 0.5938

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48968 | val 6.96695
  Epoch 011 - train 0.49851 | val 6.73746
  Classification -> best τ=0.835 (val F1=0.2085)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51450 | val 1.89252
  Epoch 011 - train 0.49531 | val 2.11411

[I 2026-02-20 04:08:47,404] Trial 144 finished with value: 0.2743045580801636 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.004355868957670376, 'weight_decay': 8.560168253644882e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.34502270450290834, 'early_stopping_min_delta': 0.009482858683309767}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.555 (val F1=0.0326)
  Directional -> Accuracy: 0.5333, MCC: 0.1135, F1: 0.6410

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2743045580801636
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52023 | val 0.93883
  Epoch 011 - train 0.49257 | val 1.10554
  Classification -> best τ=0.700 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1910, F1: 0.3478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53002 | val 0.92896
  Epoch 011 - train 0.49064 | val 0.94979
  Classification -> best τ=0.380 (val F1=0.1186)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51893 | val 1.08172
  Epoch 011 - train 0.49551 | val 1.12021
  Classification -> best τ=0.390 (val F1=0.3251)
  Directional -> Accuracy: 0.4565, MCC: -0.1633, F1: 0.6032

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60576 | val 2.05261
  Epoch 014 - train 0.43944 | val 1.83735
  Classification -> best τ=0.315 (val F1=0.2739)
  Directional -> Accuracy: 0.5000, MCC: -0.0390, F1: 0.6022

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39039 | val 1.95948
  Epoch 011 - train 0.32948 | val 1.56379
  Classification -> best τ=0.270 (val F1=0.5155)
  Directional -> Accuracy: 0.7600, MCC: 0.5304, F1: 0.7931

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46381 | val 1.02301
  Epoch 011 - train 0.40070 | val 1.23459
  Classification -> best τ=0.640 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53252 | val 1.41447
  Epoch 011 - train 0.52913 | val 1.49425
  Classification -> best τ=0.450 (val F1=0.2506)
  Directional -> Accuracy: 0.5147, MCC: 0.1463, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34349 | val 0.94378
  Epoch 011 - train 0.32971 | val 0.92210
  Classification -> best τ=0.425 (val F1=0.1795)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.4865

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44086 | val 3.93984
  Epoch 011 - train 0.39052 | val 4.06314
  Classification -> best τ=0.715 (val F1=0.3433)
  Directional -> Accuracy: 0.6250, MCC: 0.2250, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64719 | val 0.81059
  Epoch 019 - train 0.36622 | val 1.68406
  Classification -> best τ=0.810 (val F1=0.2734)
  Directional -> Accuracy: 0.5797, MCC: 0.1256, F1: 0.4727

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54414 | val 1.23432
  Epoch 015 - train 0.36743 | val 0.78340
  Classification -> best τ=0.425 (val F1=0.2543)
  Directional -> Accuracy: 0.5714, MCC: 0.1016, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54082 | val 1.03896
  Epoch 013 - train 0.38692 | val 2.40188
  Classification -> best τ=0.810 (val F1=0.2428)
  Directional -> Accuracy: 0.4386, MCC: -0.1669, F1: 0.1111

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57923 | val 3.00914
  Epoch 015 - train 0.32175 | val 2.32009
  Classification -> best τ=0.725 (val F1=0.2902)
  Directional -> Accuracy: 0.4048, MCC: -0.2368, F1: 0.2424

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52315 | val 0.94532
  Epoch 011 - train 0.51418 | val 0.81077
  Classification -> best τ=0.575 (val F1=0.3477)
  Directional -> Accuracy: 0.5167, MCC: 0.0335, F1: 0.5397

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54500 | val 2.84939
  Epoch 013 - train 0.39444 | val 5.97361
  Classification -> best τ=0.580 (val F1=0.3847)
  Directional -> Accuracy: 0.5882, MCC: 0.2094, F1: 0.6182

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58159 | val 0.78551
  Epoch 014 - train 0.43183 | val 1.05868
  Classification -> best τ=0.200 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48670 | val 4.13066
  Epoch 011 - train 0.45888 | val 4.57588
  Classification -> best τ=0.560 (val F1=0.0354)
  Directional -> Accuracy: 0.3621, MCC: -0.1383, F1: 0.0513

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57525 | val 1.01430
  Epoch 018 - train 0.39293 | val 1.37401
  Classification -> best τ=0.455 (val F1=0.2673)
  Directional -> Accuracy: 0.6133, MCC: 0.1576, F1: 0.7071

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56306 | val 1.40302
  Epoch 015 - train 0.40404 | val 2.36807
  Classification -> best τ=0.490 (val F1=0.3229)
  Directional -> Accuracy: 0.4219, MCC: -0.0509, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47621 | val 1.41855
  Epoch 011 - train 0.42965 | val 1.16937
  Classification -> best τ=0.575 (val F1=0.3219)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57976 | val 2.14382
  Epoch 018 - train 0.25198 | val 0.69100
  Classification -> best τ=0.335 (val F1=0.3693)
  Directional -> Accuracy: 0.5532, MCC: 0.0446, F1: 0.6441

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63385 | val 1.10631
  Epoch 012 - train 0.56241 | val 1.83814
  Classification -> best τ=0.775 (val F1=0.2254)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63833 | val 1.14750
  Epoch 016 - train 0.49279 | val 1.24731
  Classification -> best τ=0.525 (val F1=0.3750)
  Directional -> Accuracy: 0.4912, MCC: -0.0199, F1: 0.5246

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55309 | val 4.09721
  Epoch 013 - train 0.45749 | val 4.70145
  Classification -> best τ=0.690 (val F1=0.2484)
  Directional -> Accuracy: 0.5385, MCC: 0.0750, F1: 0.5161

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41918 | val 2.02970
  Epoch 011 - train 0.43028 | val 3.40911
  Classification -> best τ=0.535 (val F1=0.3786)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38193 | val 3.21728
  Epoch 011 - train 0.38099 | val 3.75584
  Classification -> best τ=0.565 (val F1=0.0198)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59105 | val 1.46109
  Epoch 013 - train 0.43924 | val 1.09732
  Classification -> best τ=0.480 (val F1=0.1376)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54463 | val 1.25274
  Epoch 011 - train 0.53439 | val 1.52110
  Classification -> best τ=0.390 (val F1=0.0920)
  Directional -> Accuracy: 0.5536, MCC: 0.2311, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42009 | val 1.85297
  Epoch 013 - train 0.38363 | val 1.82723
  Classification -> best τ=0.540 (val F1=0.1608)
  Directional -> Accuracy: 0.6500, MCC: 0.2851, F1: 0.7200

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56366 | val 0.91247
  Epoch 019 - train 0.25187 | val 1.42837
  Classification -> best τ=0.745 (val F1=0.4846)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41915 | val 1.08078
  Epoch 011 - train 0.38948 | val 1.40030
  Classification -> best τ=0.530 (val F1=0.3036)
  Directional -> Accuracy: 0.4048, MCC: -0.2460, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41500 | val 1.35060
  Epoch 011 - train 0.36787 | val 1.86110
  Classification -> best τ=0.410 (val F1=0.2509)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62835 | val 0.65680
  Epoch 020 - train 0.40370 | val 2.64084
  Classification -> best τ=0.355 (val F1=0.2978)
  Directional -> Accuracy: 0.4722, MCC: -0.0319, F1: 0.4412

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50610 | val 1.62622
  Epoch 011 - train 0.44955 | val 2.06322
  Classification -> best τ=0.495 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53962 | val 0.87248
  Epoch 014 - train 0.38913 | val 1.43453
  Classification -> best τ=0.540 (val F1=0.3865)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42626 | val 1.09253
  Epoch 011 - train 0.34367 | val 1.12488
  Classification -> best τ=0.585 (val F1=0.1822)
  Directional -> Accuracy: 0.5476, MCC: 0.2644, F1: 0.2400

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45224 | val 1.73993
  Epoch 011 - train 0.39806 | val 1.64418
  Classification -> best τ=0.620 (val F1=0.1508)
  Directional -> Accuracy: 0.5714, MCC: 0.1240, F1: 0.4000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37126 | val 1.23085
  Epoch 012 - train 0.32777 | val 1.32092
  Classification -> best τ=0.345 (val F1=0.2326)
  Directional -> Accuracy: 0.5870, MCC: 0.0537, F1: 0.7077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51561 | val 0.73141
  Epoch 013 - train 0.40679 | val 1.03794
  Classification -> best τ=0.325 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52224 | val 1.37842
  Epoch 012 - train 0.47233 | val 1.09800
  Classification -> best τ=0.500 (val F1=0.3632)
  Directional -> Accuracy: 0.5541, MCC: 0.1473, F1: 0.2326

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46637 | val 1.07784
  Epoch 013 - train 0.33516 | val 1.25096
  Classification -> best τ=0.575 (val F1=0.2174)
  Directional -> Accuracy: 0.5111, MCC: 0.0314, F1: 0.4211

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45407 | val 1.09481
  Epoch 011 - train 0.45064 | val 1.17836
  Classification -> best τ=0.550 (val F1=0.4971)
  Directional -> Accuracy: 0.5714, MCC: 0.1840, F1: 0.5500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50127 | val 1.20271
  Epoch 013 - train 0.37453 | val 1.08629
  Classification -> best τ=0.750 (val F1=0.5131)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63226 | val 1.26086
  Epoch 012 - train 0.57992 | val 1.74251
  Classification -> best τ=0.365 (val F1=0.1605)
  Directional -> Accuracy: 0.5273, MCC: -0.1242, F1: 0.6905

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45180 | val 3.14499
  Epoch 011 - train 0.39175 | val 3.45289
  Classification -> best τ=0.590 (val F1=0.3556)
  Directional -> Accuracy: 0.5714, MCC: 0.1801, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67245 | val 0.81275
  Epoch 011 - train 0.64271 | val 0.86540
  Classification -> best τ=0.410 (val F1=0.2351)
  Directional -> Accuracy: 0.5283, MCC: 0.0631, F1: 0.6575

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46086 | val 2.69481
  Epoch 011 - train 0.42748 | val 4.02037
  Classification -> best τ=0.820 (val F1=0.0150)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47694 | val 1.19575

[I 2026-02-20 04:10:29,440] Trial 145 finished with value: 0.27023271240573704 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007062493970196515, 'weight_decay': 2.9927748187338884e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.2785954992808679, 'early_stopping_min_delta': 0.008630517229258079}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 012 - train 0.44645 | val 0.88161
  Classification -> best τ=0.430 (val F1=0.2006)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27023271240573704
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50403 | val 0.78919
  Epoch 011 - train 0.46976 | val 1.04205
  Classification -> best τ=0.520 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0822, F1: 0.5205

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56120 | val 1.24272
  Epoch 018 - train 0.32086 | val 2.43711
  Classification -> best τ=0.565 (val F1=0.1764)
  Directional -> Accuracy: 0.4444, MCC: -0.0507, F1: 0.3590

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64628 | val 0.89710
  Epoch 013 - train 0.54975 | val 0.83161
  Classification -> best τ=0.670 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54232 | val 2.07190
  Epoch 013 - train 0.44009 | val 1.60986
  Classification -> best τ=0.230 (val F1=0.1257)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43678 | val 1.06314
  Epoch 012 - train 0.33614 | val 1.22860
  Classification -> best τ=0.500 (val F1=0.4602)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43537 | val 1.61564
  Epoch 011 - train 0.38338 | val 1.34898
  Classification -> best τ=0.395 (val F1=0.1235)
  Directional -> Accuracy: 0.4783, MCC: -0.0169, F1: 0.6129

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62200 | val 1.13919
  Epoch 017 - train 0.40199 | val 1.63474
  Classification -> best τ=0.500 (val F1=0.3010)
  Directional -> Accuracy: 0.4559, MCC: 0.0824, F1: 0.5647

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39511 | val 1.85386
  Epoch 011 - train 0.36346 | val 1.29074
  Classification -> best τ=0.460 (val F1=0.0807)
  Directional -> Accuracy: 0.5000, MCC: -0.0782, F1: 0.2759

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49490 | val 1.23439
  Epoch 011 - train 0.48010 | val 1.20196
  Classification -> best τ=0.570 (val F1=0.4025)
  Directional -> Accuracy: 0.5208, MCC: -0.1839, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56580 | val 0.91427
  Epoch 018 - train 0.35291 | val 1.20898
  Classification -> best τ=0.350 (val F1=0.3006)
  Directional -> Accuracy: 0.4638, MCC: -0.0483, F1: 0.4638

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53725 | val 0.72380
  Epoch 016 - train 0.38663 | val 0.89049
  Classification -> best τ=0.700 (val F1=0.3075)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59499 | val 1.42446
  Epoch 014 - train 0.37710 | val 2.55024
  Classification -> best τ=0.770 (val F1=0.2428)
  Directional -> Accuracy: 0.6667, MCC: 0.3329, F1: 0.6780

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41901 | val 2.51965
  Epoch 011 - train 0.38113 | val 2.21435
  Classification -> best τ=0.365 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58110 | val 0.74374
  Epoch 014 - train 0.52120 | val 0.65676
  Classification -> best τ=0.425 (val F1=0.3721)
  Directional -> Accuracy: 0.6167, MCC: 0.2446, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51580 | val 4.65771
  Epoch 013 - train 0.42159 | val 7.11738
  Classification -> best τ=0.630 (val F1=0.2571)
  Directional -> Accuracy: 0.5294, MCC: 0.0424, F1: 0.4545

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54522 | val 1.36796
  Epoch 015 - train 0.39971 | val 1.62098
  Classification -> best τ=0.660 (val F1=0.3506)
  Directional -> Accuracy: 0.5362, MCC: 0.1876, F1: 0.3043

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60493 | val 1.04710
  Epoch 011 - train 0.58585 | val 1.20514
  Classification -> best τ=0.465 (val F1=0.0660)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59992 | val 1.45997
  Epoch 018 - train 0.36705 | val 2.29343
  Classification -> best τ=0.565 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48412 | val 0.73083
  Epoch 020 - train 0.27522 | val 0.98076
  Classification -> best τ=0.925 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48174 | val 1.22616
  Epoch 011 - train 0.47353 | val 1.51940
  Classification -> best τ=0.485 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38486 | val 1.12646
  Epoch 011 - train 0.37480 | val 1.10446
  Classification -> best τ=0.475 (val F1=0.3878)
  Directional -> Accuracy: 0.7021, MCC: 0.3544, F1: 0.8000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52231 | val 2.00598
  Epoch 012 - train 0.46807 | val 2.10242
  Classification -> best τ=0.625 (val F1=0.1822)
  Directional -> Accuracy: 0.5231, MCC: 0.0879, F1: 0.2439

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51377 | val 2.13962
  Epoch 011 - train 0.48307 | val 1.55096
  Classification -> best τ=0.555 (val F1=0.2259)
  Directional -> Accuracy: 0.5088, MCC: 0.0199, F1: 0.5333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45422 | val 5.00150
  Epoch 011 - train 0.44113 | val 4.34790
  Classification -> best τ=0.365 (val F1=0.2702)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47662 | val 2.39539
  Epoch 012 - train 0.41183 | val 3.14002
  Classification -> best τ=0.575 (val F1=0.3563)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42519 | val 5.68420
  Epoch 011 - train 0.43167 | val 5.69253
  Classification -> best τ=0.615 (val F1=0.2756)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50457 | val 0.81177
  Epoch 012 - train 0.46531 | val 0.96669
  Classification -> best τ=0.545 (val F1=0.1291)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44456 | val 2.53333
  Epoch 011 - train 0.43348 | val 2.49336
  Classification -> best τ=0.530 (val F1=0.2277)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40271 | val 1.40456
  Epoch 012 - train 0.43219 | val 1.62854
  Classification -> best τ=0.655 (val F1=0.1918)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53405 | val 0.78563
  Epoch 012 - train 0.46044 | val 0.73173
  Classification -> best τ=0.680 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49082 | val 3.74596
  Epoch 011 - train 0.42092 | val 4.06139
  Classification -> best τ=0.500 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45238 | val 0.78948
  Epoch 012 - train 0.38392 | val 0.86293
  Classification -> best τ=0.700 (val F1=0.2969)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56619 | val 0.84598
  Epoch 012 - train 0.53699 | val 1.53644
  Classification -> best τ=0.180 (val F1=0.3313)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48178 | val 2.16880
  Epoch 011 - train 0.44082 | val 1.87534
  Classification -> best τ=0.360 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48682 | val 0.96608
  Epoch 011 - train 0.49034 | val 1.12658
  Classification -> best τ=0.460 (val F1=0.2778)
  Directional -> Accuracy: 0.6061, MCC: 0.1674, F1: 0.7400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46004 | val 0.86804
  Epoch 012 - train 0.39403 | val 1.12503
  Classification -> best τ=0.490 (val F1=0.2144)
  Directional -> Accuracy: 0.5952, MCC: 0.1961, F1: 0.5854

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42412 | val 2.07104
  Epoch 011 - train 0.43193 | val 2.16497
  Classification -> best τ=0.615 (val F1=0.1951)
  Directional -> Accuracy: 0.5000, MCC: -0.0601, F1: 0.2222

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49599 | val 1.17826
  Epoch 011 - train 0.40589 | val 1.28061
  Classification -> best τ=0.585 (val F1=0.4335)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50889 | val 0.96031
  Epoch 015 - train 0.33794 | val 0.88211
  Classification -> best τ=0.430 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55750 | val 1.28063
  Epoch 015 - train 0.49793 | val 1.35094
  Classification -> best τ=0.210 (val F1=0.4293)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47319 | val 1.15961
  Epoch 012 - train 0.40216 | val 0.95275
  Classification -> best τ=0.325 (val F1=0.2712)
  Directional -> Accuracy: 0.5333, MCC: 0.0950, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44104 | val 0.91157
  Epoch 011 - train 0.47094 | val 0.90637
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53232 | val 1.22243
  Epoch 012 - train 0.46164 | val 0.97764
  Classification -> best τ=0.645 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58024 | val 1.62050
  Epoch 011 - train 0.54457 | val 1.56876
  Classification -> best τ=0.340 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45415 | val 1.52708
  Epoch 011 - train 0.46442 | val 1.76585
  Classification -> best τ=0.655 (val F1=0.2308)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51329 | val 1.60218
  Epoch 011 - train 0.47953 | val 1.39679
  Classification -> best τ=0.515 (val F1=0.2279)
  Directional -> Accuracy: 0.5283, MCC: 0.0631, F1: 0.6575

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48637 | val 2.50036
  Epoch 012 - train 0.42064 | val 3.64513
  Classification -> best τ=0.500 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49539 | val 2.01599
  Epoch 011 - train 0.51304 | val 1.71961

[I 2026-02-20 04:12:14,321] Trial 146 finished with value: 0.2541558864343579 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005003497328642429, 'weight_decay': 4.834158361928626e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.36202988032255057, 'early_stopping_min_delta': 0.0045730241976362305}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.360 (val F1=0.1708)
  Directional -> Accuracy: 0.4667, MCC: -0.0733, F1: 0.4074

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2541558864343579
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69325 | val 0.80207
  Epoch 016 - train 0.62509 | val 0.82498
  Classification -> best τ=0.740 (val F1=0.2851)
  Directional -> Accuracy: 0.5065, MCC: -0.0745, F1: 0.1739

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62926 | val 1.22946
  Epoch 012 - train 0.67081 | val 1.19753
  Classification -> best τ=0.495 (val F1=0.2431)
  Directional -> Accuracy: 0.6087, MCC: 0.1780, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63090 | val 0.72132
  Epoch 013 - train 0.68532 | val 0.82811
  Classification -> best τ=0.485 (val F1=0.3251)
  Directional -> Accuracy: 0.6170, MCC: 0.2281, F1: 0.6897

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68493 | val 1.20171
  Epoch 011 - train 0.63834 | val 1.37869
  Classification -> best τ=0.585 (val F1=0.1590)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65311 | val 1.07363
  Epoch 012 - train 0.57201 | val 1.71095
  Classification -> best τ=0.485 (val F1=0.4457)
  Directional -> Accuracy: 0.5686, MCC: 0.1434, F1: 0.6944

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57568 | val 2.82827
  Epoch 012 - train 0.51957 | val 4.59818
  Classification -> best τ=0.520 (val F1=0.2390)
  Directional -> Accuracy: 0.5319, MCC: 0.2064, F1: 0.6765

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65119 | val 1.15154
  Epoch 011 - train 0.69442 | val 1.07916
  Classification -> best τ=0.395 (val F1=0.1994)
  Directional -> Accuracy: 0.4783, MCC: 0.1448, F1: 0.5909

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59331 | val 2.87949
  Epoch 011 - train 0.61692 | val 2.96869
  Classification -> best τ=0.545 (val F1=0.2601)
  Directional -> Accuracy: 0.6136, MCC: 0.1704, F1: 0.4516

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.73875 | val 0.85645
  Epoch 014 - train 0.61290 | val 1.50485
  Classification -> best τ=0.470 (val F1=0.4249)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65657 | val 0.87510
  Epoch 011 - train 0.62896 | val 0.86877
  Classification -> best τ=0.510 (val F1=0.1137)
  Directional -> Accuracy: 0.6857, MCC: 0.3475, F1: 0.5926

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64835 | val 3.63245
  Epoch 012 - train 0.65765 | val 3.09834
  Classification -> best τ=0.510 (val F1=0.1667)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60809 | val 2.48398
  Epoch 011 - train 0.62256 | val 2.73389
  Classification -> best τ=0.520 (val F1=0.2453)
  Directional -> Accuracy: 0.5517, MCC: 0.1588, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67128 | val 2.39023
  Epoch 013 - train 0.61807 | val 2.35455
  Classification -> best τ=0.260 (val F1=0.2103)
  Directional -> Accuracy: 0.4884, MCC: 0.1965, F1: 0.6333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68289 | val 0.68035
  Epoch 014 - train 0.69678 | val 0.99513
  Classification -> best τ=0.455 (val F1=0.2609)
  Directional -> Accuracy: 0.5246, MCC: 0.0468, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65453 | val 0.86642
  Epoch 012 - train 0.63963 | val 0.92250
  Classification -> best τ=0.485 (val F1=0.2449)
  Directional -> Accuracy: 0.5577, MCC: 0.1018, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62024 | val 0.82766
  Epoch 011 - train 0.61225 | val 0.82626
  Classification -> best τ=0.500 (val F1=0.2997)
  Directional -> Accuracy: 0.6000, MCC: 0.2312, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71590 | val 1.62630
  Epoch 011 - train 0.66551 | val 1.58012
  Classification -> best τ=0.655 (val F1=0.0519)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65058 | val 0.71587
  Epoch 016 - train 0.59677 | val 0.77590
  Classification -> best τ=0.705 (val F1=0.2236)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.73802 | val 0.97228
  Epoch 011 - train 0.68103 | val 0.86262
  Classification -> best τ=0.470 (val F1=0.1294)
  Directional -> Accuracy: 0.5385, MCC: 0.2138, F1: 0.4231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62877 | val 1.35347
  Epoch 016 - train 0.58386 | val 0.90224
  Classification -> best τ=0.415 (val F1=0.2982)
  Directional -> Accuracy: 0.4400, MCC: -0.1277, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62435 | val 0.72236
  Epoch 012 - train 0.61790 | val 0.78518
  Classification -> best τ=0.545 (val F1=0.3143)
  Directional -> Accuracy: 0.5000, MCC: -0.1854, F1: 0.6471

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65530 | val 1.20109
  Epoch 011 - train 0.65885 | val 1.45281
  Classification -> best τ=0.645 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69135 | val 1.16813
  Epoch 011 - train 0.64151 | val 1.37879
  Classification -> best τ=0.660 (val F1=0.2864)
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66879 | val 1.40149
  Epoch 012 - train 0.60838 | val 1.08940
  Classification -> best τ=0.330 (val F1=0.2983)
  Directional -> Accuracy: 0.4394, MCC: -0.1058, F1: 0.5542

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68487 | val 0.67646
  Epoch 020 - train 0.60937 | val 1.02527
  Classification -> best τ=0.555 (val F1=0.4388)
  Directional -> Accuracy: 0.5714, MCC: 0.2632, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53996 | val 1.53392
  Epoch 011 - train 0.61255 | val 1.82657
  Classification -> best τ=0.510 (val F1=0.1925)
  Directional -> Accuracy: 0.4565, MCC: -0.1123, F1: 0.3590

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71051 | val 0.91594
  Epoch 014 - train 0.61978 | val 0.94794
  Classification -> best τ=0.635 (val F1=0.2057)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66163 | val 0.76774
  Epoch 011 - train 0.63009 | val 0.81251
  Classification -> best τ=0.375 (val F1=0.1988)
  Directional -> Accuracy: 0.5263, MCC: 0.1888, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68203 | val 0.82832
  Epoch 011 - train 0.69581 | val 0.99167
  Classification -> best τ=0.450 (val F1=0.1991)
  Directional -> Accuracy: 0.6098, MCC: 0.2516, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64322 | val 1.14170
  Epoch 011 - train 0.62787 | val 1.22862
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.74463 | val 0.90702
  Epoch 011 - train 0.65121 | val 0.90092
  Classification -> best τ=0.510 (val F1=0.1667)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61367 | val 1.17517
  Epoch 011 - train 0.55402 | val 1.18152
  Classification -> best τ=0.465 (val F1=0.3120)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63407 | val 0.83954
  Epoch 017 - train 0.64225 | val 1.15589
  Classification -> best τ=0.615 (val F1=0.3996)
  Directional -> Accuracy: 0.5068, MCC: 0.1076, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69111 | val 1.14114
  Epoch 011 - train 0.79536 | val 1.24417
  Classification -> best τ=0.415 (val F1=0.2928)
  Directional -> Accuracy: 0.4474, MCC: -0.1715, F1: 0.6038

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68804 | val 1.26159
  Epoch 011 - train 0.66782 | val 1.12921
  Classification -> best τ=0.445 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63735 | val 0.70487
  Epoch 016 - train 0.58816 | val 0.75248
  Classification -> best τ=0.330 (val F1=0.4655)
  Directional -> Accuracy: 0.5522, MCC: 0.0734, F1: 0.6250

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59740 | val 0.87749
  Epoch 016 - train 0.57942 | val 1.23595
  Classification -> best τ=0.390 (val F1=0.2986)
  Directional -> Accuracy: 0.6512, MCC: 0.3246, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60655 | val 1.71627
  Epoch 011 - train 0.62429 | val 1.53527
  Classification -> best τ=0.275 (val F1=0.2547)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63717 | val 1.84398
  Epoch 012 - train 0.63551 | val 1.97901
  Classification -> best τ=0.560 (val F1=0.4890)
  Directional -> Accuracy: 0.4468, MCC: -0.0446, F1: 0.4348

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68251 | val 0.64536
  Epoch 020 - train 0.55218 | val 0.83360
  Classification -> best τ=0.275 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.81497 | val 1.42873
  Epoch 011 - train 0.63128 | val 1.41857
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63708 | val 1.32049
  Epoch 012 - train 0.60641 | val 1.34267
  Classification -> best τ=0.550 (val F1=0.3870)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64883 | val 0.78875
  Epoch 011 - train 0.64497 | val 0.75692
  Classification -> best τ=0.580 (val F1=0.3301)
  Directional -> Accuracy: 0.4681, MCC: -0.0926, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71663 | val 1.12450
  Epoch 011 - train 0.66012 | val 1.22591
  Classification -> best τ=0.475 (val F1=0.1455)
  Directional -> Accuracy: 0.6136, MCC: 0.2031, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64927 | val 1.43271
  Epoch 016 - train 0.57093 | val 3.39728
  Classification -> best τ=0.420 (val F1=0.2626)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72170 | val 1.10464
  Epoch 014 - train 0.66777 | val 1.35227
  Classification -> best τ=0.835 (val F1=0.1914)
  Directional -> Accuracy: 0.4286, MCC: -0.2067, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63463 | val 0.83322
  Epoch 011 - train 0.61330 | val 0.84257
  Classification -> best τ=0.580 (val F1=0.2630)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68453 | val 1.06180
  Epoch 011 - train 0.64286 | val 1.14007
  Classification -> best τ=0.425 (val F1=0.1626)
  Directional -> Accuracy: 0.5926, MCC: 0.1819, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69407 | val 0.72146
  Epoch 013 - train 0.59105 | val 0.70744
  Classification -> best τ=0.415 (val F1=0.2097)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68488 | val 0.95644

[I 2026-02-20 04:15:21,004] Trial 147 finished with value: 0.2555139248474697 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0036481730237094764, 'weight_decay': 9.432342507133985e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.2627723937062581, 'early_stopping_min_delta': 0.005107380226022534}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 011 - train 0.67619 | val 0.98139
  Classification -> best τ=0.525 (val F1=0.3074)
  Directional -> Accuracy: 0.5082, MCC: -0.0338, F1: 0.1667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2555139248474697
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59382 | val 1.17816
  Epoch 013 - train 0.56503 | val 1.60575
  Classification -> best τ=0.695 (val F1=0.1997)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55221 | val 0.69409
  Epoch 011 - train 0.56545 | val 0.69844
  Classification -> best τ=0.420 (val F1=0.1421)
  Directional -> Accuracy: 0.5532, MCC: 0.0485, F1: 0.6769

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57431 | val 0.83407
  Epoch 012 - train 0.58440 | val 0.82500
  Classification -> best τ=0.475 (val F1=0.2173)
  Directional -> Accuracy: 0.5208, MCC: 0.0527, F1: 0.5106

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62514 | val 0.99753
  Epoch 011 - train 0.62205 | val 0.92307
  Classification -> best τ=0.455 (val F1=0.1988)
  Directional -> Accuracy: 0.4868, MCC: 0.0747, F1: 0.1702

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51074 | val 1.04264
  Epoch 012 - train 0.51537 | val 1.26739
  Classification -> best τ=0.550 (val F1=0.4574)
  Directional -> Accuracy: 0.6346, MCC: 0.3340, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51443 | val 1.62036
  Epoch 011 - train 0.47858 | val 1.55796
  Classification -> best τ=0.550 (val F1=0.2673)
  Directional -> Accuracy: 0.5306, MCC: 0.1014, F1: 0.3030

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63266 | val 1.02949
  Epoch 011 - train 0.62622 | val 1.09540
  Classification -> best τ=0.550 (val F1=0.0778)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51037 | val 2.27017
  Epoch 011 - train 0.56096 | val 2.54302
  Classification -> best τ=0.535 (val F1=0.2229)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56704 | val 0.76108
  Epoch 011 - train 0.59843 | val 0.79430
  Classification -> best τ=0.675 (val F1=0.3855)
  Directional -> Accuracy: 0.6429, MCC: 0.1991, F1: 0.1176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60089 | val 0.97477
  Epoch 012 - train 0.54573 | val 0.97453
  Classification -> best τ=0.335 (val F1=0.2050)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54042 | val 1.83111
  Epoch 011 - train 0.55699 | val 1.78281
  Classification -> best τ=0.565 (val F1=0.1877)
  Directional -> Accuracy: 0.5490, MCC: 0.1073, F1: 0.5660

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58487 | val 1.12025
  Epoch 011 - train 0.56018 | val 1.19446
  Classification -> best τ=0.530 (val F1=0.2394)
  Directional -> Accuracy: 0.6949, MCC: 0.4076, F1: 0.6538

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55587 | val 1.75189
  Epoch 012 - train 0.56279 | val 2.34689
  Classification -> best τ=0.450 (val F1=0.0552)
  Directional -> Accuracy: 0.5909, MCC: 0.1614, F1: 0.3571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57886 | val 0.89003
  Epoch 013 - train 0.56090 | val 1.02863
  Classification -> best τ=0.305 (val F1=0.3568)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53013 | val 2.77757
  Epoch 012 - train 0.53547 | val 4.04682
  Classification -> best τ=0.585 (val F1=0.3315)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59950 | val 0.87431
  Epoch 013 - train 0.56683 | val 1.03659
  Classification -> best τ=0.640 (val F1=0.2699)
  Directional -> Accuracy: 0.5634, MCC: 0.2056, F1: 0.4151

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60842 | val 1.30803
  Epoch 011 - train 0.58435 | val 1.37989
  Classification -> best τ=0.635 (val F1=0.1754)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59138 | val 2.80573
  Epoch 011 - train 0.57037 | val 2.90487
  Classification -> best τ=0.310 (val F1=0.1481)
  Directional -> Accuracy: 0.5584, MCC: 0.1671, F1: 0.5641

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59903 | val 1.02603
  Epoch 019 - train 0.50452 | val 1.16551
  Classification -> best τ=0.400 (val F1=0.3240)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60604 | val 0.82374
  Epoch 016 - train 0.51508 | val 0.71929
  Classification -> best τ=0.485 (val F1=0.3441)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54593 | val 0.95469
  Epoch 012 - train 0.49948 | val 1.45412
  Classification -> best τ=0.485 (val F1=0.3590)
  Directional -> Accuracy: 0.4898, MCC: -0.1107, F1: 0.6032

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57570 | val 1.12530
  Epoch 011 - train 0.61246 | val 1.19005
  Classification -> best τ=0.620 (val F1=0.1834)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61490 | val 0.97145
  Epoch 011 - train 0.61310 | val 0.92404
  Classification -> best τ=0.700 (val F1=0.2992)
  Directional -> Accuracy: 0.4746, MCC: 0.0582, F1: 0.3111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57087 | val 1.06135
  Epoch 011 - train 0.54791 | val 0.93226
  Classification -> best τ=0.370 (val F1=0.3155)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58629 | val 0.67333
  Epoch 013 - train 0.52393 | val 0.71657
  Classification -> best τ=0.585 (val F1=0.4805)
  Directional -> Accuracy: 0.5789, MCC: 0.2202, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55457 | val 1.73158
  Epoch 011 - train 0.53505 | val 1.85283
  Classification -> best τ=0.505 (val F1=0.2287)
  Directional -> Accuracy: 0.5833, MCC: 0.0510, F1: 0.1667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57185 | val 0.95036
  Epoch 011 - train 0.56013 | val 1.04823
  Classification -> best τ=0.440 (val F1=0.1264)
  Directional -> Accuracy: 0.6364, MCC: 0.2256, F1: 0.7143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57154 | val 0.93015
  Epoch 013 - train 0.51937 | val 1.07506
  Classification -> best τ=0.390 (val F1=0.2755)
  Directional -> Accuracy: 0.5517, MCC: 0.2600, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55190 | val 0.87614
  Epoch 020 - train 0.52600 | val 0.68542
  Classification -> best τ=0.640 (val F1=0.3344)
  Directional -> Accuracy: 0.5581, MCC: 0.1150, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56953 | val 1.04651
  Epoch 011 - train 0.60101 | val 1.24264
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60943 | val 1.05513
  Epoch 011 - train 0.55202 | val 1.17789
  Classification -> best τ=0.545 (val F1=0.1715)
  Directional -> Accuracy: 0.4667, MCC: -0.0262, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57741 | val 0.85634
  Epoch 011 - train 0.55581 | val 0.92751
  Classification -> best τ=0.510 (val F1=0.2335)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56546 | val 1.94843
  Epoch 011 - train 0.54151 | val 1.63794
  Classification -> best τ=0.490 (val F1=0.2823)
  Directional -> Accuracy: 0.5135, MCC: 0.0903, F1: 0.4375

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.54502 | val 0.71300
  Epoch 011 - train 0.57178 | val 0.72519
  Classification -> best τ=0.445 (val F1=0.3223)
  Directional -> Accuracy: 0.5385, MCC: 0.0829, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56265 | val 1.11630
  Epoch 011 - train 0.54003 | val 1.12802
  Classification -> best τ=0.415 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54437 | val 0.82672
  Epoch 012 - train 0.53647 | val 1.02186
  Classification -> best τ=0.410 (val F1=0.4157)
  Directional -> Accuracy: 0.5000, MCC: 0.1366, F1: 0.3200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57250 | val 0.91148
  Epoch 011 - train 0.55436 | val 1.02638
  Classification -> best τ=0.525 (val F1=0.1085)
  Directional -> Accuracy: 0.3636, MCC: -0.2928, F1: 0.4615

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56934 | val 1.42765
  Epoch 011 - train 0.51762 | val 1.08102
  Classification -> best τ=0.450 (val F1=0.1753)
  Directional -> Accuracy: 0.5000, MCC: -0.0347, F1: 0.3256

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49484 | val 2.11299
  Epoch 011 - train 0.45005 | val 1.96877
  Classification -> best τ=0.440 (val F1=0.2233)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7143

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55185 | val 0.91326
  Epoch 011 - train 0.51521 | val 0.81371
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58568 | val 0.83112
  Epoch 011 - train 0.59123 | val 0.82043
  Classification -> best τ=0.455 (val F1=0.2548)
  Directional -> Accuracy: 0.4872, MCC: -0.0882, F1: 0.6154

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57552 | val 1.30785
  Epoch 011 - train 0.57448 | val 1.35035
  Classification -> best τ=0.510 (val F1=0.1523)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57408 | val 0.95424
  Epoch 011 - train 0.54553 | val 1.11753
  Classification -> best τ=0.475 (val F1=0.3393)
  Directional -> Accuracy: 0.5417, MCC: 0.0962, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51570 | val 1.16405
  Epoch 011 - train 0.55524 | val 1.16489
  Classification -> best τ=0.605 (val F1=0.2774)
  Directional -> Accuracy: 0.4222, MCC: -0.1685, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48077 | val 1.76879
  Epoch 011 - train 0.50583 | val 1.90530
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60950 | val 1.25324
  Epoch 011 - train 0.58502 | val 1.43285
  Classification -> best τ=0.360 (val F1=0.2477)
  Directional -> Accuracy: 0.5439, MCC: 0.1801, F1: 0.3810

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55934 | val 2.55949
  Epoch 011 - train 0.55072 | val 2.52579
  Classification -> best τ=0.600 (val F1=0.3208)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59553 | val 1.76340
  Epoch 011 - train 0.62543 | val 1.71135
  Classification -> best τ=0.325 (val F1=0.1676)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56283 | val 1.28132
  Epoch 011 - train 0.56699 | val 1.16885
  Classification -> best τ=0.655 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 04:16:00,469] Trial 148 finished with value: 0.2356754333029215 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.00242780035526008, 'weight_decay': 6.637787002870505e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.5563177988344288, 'early_stopping_min_delta': 0.008059475677982037}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 010 - train 0.59441 | val 0.95246
  Epoch 011 - train 0.57943 | val 0.98106
  Classification -> best τ=0.495 (val F1=0.2653)
  Directional -> Accuracy: 0.4839, MCC: -0.0505, F1: 0.3333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2356754333029215
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59764 | val 0.74714
  Epoch 013 - train 0.58736 | val 0.68666
  Classification -> best τ=0.475 (val F1=0.2125)
  Directional -> Accuracy: 0.5921, MCC: 0.1774, F1: 0.5507

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55826 | val 0.68245
  Epoch 012 - train 0.53861 | val 0.71792
  Classification -> best τ=0.425 (val F1=0.3487)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59237 | val 0.70411
  Epoch 012 - train 0.59047 | val 0.78712
  Classification -> best τ=0.565 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63731 | val 0.94307
  Epoch 020 - train 0.58709 | val 0.82625
  Classification -> best τ=0.405 (val F1=0.2030)
  Directional -> Accuracy: 0.6081, MCC: 0.2579, F1: 0.7290

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63208 | val 0.70145
  Epoch 017 - train 0.51578 | val 1.08322
  Classification -> best τ=0.460 (val F1=0.3984)
  Directional -> Accuracy: 0.6600, MCC: 0.3516, F1: 0.6047

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60525 | val 0.71427
  Epoch 011 - train 0.62278 | val 0.70865
  Classification -> best τ=0.515 (val F1=0.2585)
  Directional -> Accuracy: 0.6522, MCC: 0.3068, F1: 0.6522

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67912 | val 0.73420
  Epoch 013 - train 0.66286 | val 0.75618
  Classification -> best τ=0.460 (val F1=0.2195)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52815 | val 0.84454
  Epoch 013 - train 0.52403 | val 1.23458
  Classification -> best τ=0.425 (val F1=0.2657)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59431 | val 0.81051
  Epoch 011 - train 0.62575 | val 0.80520
  Classification -> best τ=0.500 (val F1=0.2233)
  Directional -> Accuracy: 0.6667, MCC: 0.3228, F1: 0.6190

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58976 | val 0.81137
  Epoch 012 - train 0.56878 | val 0.82343
  Classification -> best τ=0.490 (val F1=0.2293)
  Directional -> Accuracy: 0.4203, MCC: -0.0401, F1: 0.5745

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66919 | val 0.81744
  Epoch 012 - train 0.67899 | val 0.66915
  Classification -> best τ=0.400 (val F1=0.2543)
  Directional -> Accuracy: 0.5102, MCC: 0.0017, F1: 0.4286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54463 | val 1.35305
  Epoch 012 - train 0.52515 | val 1.71028
  Classification -> best τ=0.490 (val F1=0.1937)
  Directional -> Accuracy: 0.5439, MCC: 0.1004, F1: 0.6579

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54938 | val 1.75673
  Epoch 011 - train 0.53936 | val 1.85257
  Classification -> best τ=0.345 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62977 | val 0.70788
  Epoch 018 - train 0.55086 | val 0.78575
  Classification -> best τ=0.465 (val F1=0.3196)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.5333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59334 | val 0.84245
  Epoch 011 - train 0.56703 | val 0.73530
  Classification -> best τ=0.465 (val F1=0.0730)
  Directional -> Accuracy: 0.4510, MCC: -0.0199, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61496 | val 0.71210
  Epoch 012 - train 0.65619 | val 0.77911
  Classification -> best τ=0.375 (val F1=0.3486)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60448 | val 1.23576
  Epoch 011 - train 0.56754 | val 1.49548
  Classification -> best τ=0.630 (val F1=0.1913)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62105 | val 1.35940
  Epoch 014 - train 0.57947 | val 1.47608
  Classification -> best τ=0.545 (val F1=0.2220)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62346 | val 0.81226
  Epoch 014 - train 0.59422 | val 0.84730
  Classification -> best τ=0.640 (val F1=0.2600)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64539 | val 0.71850
  Epoch 016 - train 0.60036 | val 0.85784
  Classification -> best τ=0.510 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60738 | val 0.68317
  Epoch 015 - train 0.53852 | val 0.73571
  Classification -> best τ=0.595 (val F1=0.1978)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65925 | val 0.74380
  Epoch 019 - train 0.64041 | val 0.98311
  Classification -> best τ=0.380 (val F1=0.1650)
  Directional -> Accuracy: 0.5846, MCC: 0.1723, F1: 0.6400

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63746 | val 0.74081
  Epoch 013 - train 0.55274 | val 0.96701
  Classification -> best τ=0.505 (val F1=0.2789)
  Directional -> Accuracy: 0.5263, MCC: -0.0014, F1: 0.6301

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62601 | val 0.78936
  Epoch 011 - train 0.61823 | val 0.84688
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59377 | val 0.73223
  Epoch 013 - train 0.55481 | val 0.93301
  Classification -> best τ=0.555 (val F1=0.4120)
  Directional -> Accuracy: 0.4545, MCC: -0.0319, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58515 | val 1.32064
  Epoch 013 - train 0.52230 | val 1.10973
  Classification -> best τ=0.545 (val F1=0.2726)
  Directional -> Accuracy: 0.6000, MCC: 0.3975, F1: 0.6786

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60665 | val 0.74634
  Epoch 011 - train 0.55967 | val 0.72374
  Classification -> best τ=0.610 (val F1=0.0700)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59578 | val 0.75774
  Epoch 011 - train 0.60900 | val 0.80482
  Classification -> best τ=0.485 (val F1=0.2066)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58151 | val 0.90629
  Epoch 017 - train 0.53478 | val 1.14748
  Classification -> best τ=0.485 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60038 | val 0.72204
  Epoch 011 - train 0.58039 | val 1.03374
  Classification -> best τ=0.575 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58533 | val 0.71682
  Epoch 020 - train 0.50726 | val 1.43447
  Classification -> best τ=0.660 (val F1=0.2646)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59065 | val 0.70179
  Epoch 016 - train 0.45817 | val 0.94065
  Classification -> best τ=0.485 (val F1=0.3461)
  Directional -> Accuracy: 0.5306, MCC: 0.0183, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62010 | val 0.69368
  Epoch 015 - train 0.59961 | val 0.73809
  Classification -> best τ=0.385 (val F1=0.3815)
  Directional -> Accuracy: 0.5000, MCC: 0.0555, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58104 | val 1.18499
  Epoch 011 - train 0.55753 | val 1.30046
  Classification -> best τ=0.410 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64976 | val 0.78091
  Epoch 011 - train 0.61123 | val 0.81883
  Classification -> best τ=0.445 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48963 | val 0.79209
  Epoch 012 - train 0.46515 | val 1.07119
  Classification -> best τ=0.440 (val F1=0.2067)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59074 | val 0.95576
  Epoch 011 - train 0.57220 | val 0.74758
  Classification -> best τ=0.455 (val F1=0.2327)
  Directional -> Accuracy: 0.5714, MCC: 0.1623, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48937 | val 1.23158
  Epoch 011 - train 0.45942 | val 1.25498
  Classification -> best τ=0.545 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62179 | val 0.66959
  Epoch 020 - train 0.45286 | val 0.76480
  Classification -> best τ=0.415 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60599 | val 0.78039
  Epoch 014 - train 0.54918 | val 0.76884
  Classification -> best τ=0.425 (val F1=0.2490)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57706 | val 0.73545
  Epoch 012 - train 0.54890 | val 0.75880
  Classification -> best τ=0.480 (val F1=0.3500)
  Directional -> Accuracy: 0.5778, MCC: 0.1692, F1: 0.5128

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58717 | val 0.78917
  Epoch 016 - train 0.53865 | val 0.71110
  Classification -> best τ=0.580 (val F1=0.5819)
  Directional -> Accuracy: 0.5714, MCC: 0.1840, F1: 0.5500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55565 | val 0.67521
  Epoch 016 - train 0.55779 | val 0.69822
  Classification -> best τ=0.545 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61407 | val 0.71318
  Epoch 011 - train 0.66001 | val 0.69078
  Classification -> best τ=0.540 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56491 | val 1.52111
  Epoch 011 - train 0.53456 | val 2.01721
  Classification -> best τ=0.590 (val F1=0.3006)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60528 | val 0.95890
  Epoch 013 - train 0.60847 | val 0.68564
  Classification -> best τ=0.625 (val F1=0.2064)
  Directional -> Accuracy: 0.5283, MCC: 0.0570, F1: 0.5283

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59296 | val 0.81251
  Epoch 015 - train 0.54557 | val 0.83402
  Classification -> best τ=0.555 (val F1=0.1881)
  Directional -> Accuracy: 0.4182, MCC: -0.2537, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60635 | val 0.69418

[I 2026-02-20 04:16:58,217] Trial 149 finished with value: 0.26429979565917006 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006090787793561689, 'weight_decay': 1.1596336252500219e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.11458099998271257, 'early_stopping_min_delta': 0.008383183890025318}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 018 - train 0.56440 | val 0.88655
  Classification -> best τ=0.525 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26429979565917006
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68649 | val 0.66431
  Epoch 014 - train 0.67401 | val 0.66392
  Classification -> best τ=0.410 (val F1=0.2158)
  Directional -> Accuracy: 0.5921, MCC: 0.1774, F1: 0.5507

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70744 | val 0.73850
  Epoch 011 - train 0.71165 | val 0.73768
  Classification -> best τ=0.495 (val F1=0.0318)
  Directional -> Accuracy: 0.4889, MCC: 0.1591, F1: 0.2581

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67991 | val 0.70910
  Epoch 011 - train 0.69302 | val 0.70890
  Classification -> best τ=0.545 (val F1=0.1978)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68681 | val 0.77940
  Epoch 011 - train 0.67983 | val 0.78918
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70143 | val 0.72617
  Epoch 011 - train 0.69605 | val 0.72448
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69180 | val 0.98685
  Epoch 011 - train 0.69750 | val 0.98565
  Classification -> best τ=0.445 (val F1=0.1251)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69403 | val 0.74577
  Epoch 011 - train 0.69594 | val 0.74694
  Classification -> best τ=0.470 (val F1=0.2445)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67899 | val 0.73831
  Epoch 011 - train 0.67686 | val 0.74358
  Classification -> best τ=0.505 (val F1=0.2753)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69466 | val 0.67253
  Epoch 018 - train 0.68848 | val 0.67446
  Classification -> best τ=0.455 (val F1=0.3096)
  Directional -> Accuracy: 0.6250, MCC: 0.2845, F1: 0.6400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68131 | val 0.77484
  Epoch 011 - train 0.68029 | val 0.78031
  Classification -> best τ=0.535 (val F1=0.2480)
  Directional -> Accuracy: 0.6087, MCC: 0.1540, F1: 0.2286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69600 | val 0.98224
  Epoch 011 - train 0.70175 | val 0.98274
  Classification -> best τ=0.560 (val F1=0.1795)
  Directional -> Accuracy: 0.4898, MCC: 0.1193, F1: 0.6269

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69338 | val 0.70374
  Epoch 013 - train 0.68885 | val 0.70469
  Classification -> best τ=0.455 (val F1=0.2157)
  Directional -> Accuracy: 0.4912, MCC: -0.0199, F1: 0.5246

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72098 | val 0.92836
  Epoch 011 - train 0.72559 | val 0.93426
  Classification -> best τ=0.455 (val F1=0.2438)
  Directional -> Accuracy: 0.5476, MCC: 0.1220, F1: 0.5778

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69378 | val 0.66556
  Epoch 013 - train 0.68959 | val 0.66519
  Classification -> best τ=0.455 (val F1=0.1774)
  Directional -> Accuracy: 0.5167, MCC: 0.0358, F1: 0.4082

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69611 | val 0.72510
  Epoch 011 - train 0.69033 | val 0.72416
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68813 | val 0.64873
  Epoch 019 - train 0.68921 | val 0.64596
  Classification -> best τ=0.580 (val F1=0.3497)
  Directional -> Accuracy: 0.5942, MCC: 0.1867, F1: 0.7021

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71183 | val 1.11367
  Epoch 011 - train 0.70659 | val 1.11182
  Classification -> best τ=0.475 (val F1=0.1842)
  Directional -> Accuracy: 0.4483, MCC: -0.0132, F1: 0.4074

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69761 | val 0.70027
  Epoch 011 - train 0.68785 | val 0.70103
  Classification -> best τ=0.535 (val F1=0.1310)
  Directional -> Accuracy: 0.4933, MCC: 0.2178, F1: 0.2963

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.73649 | val 0.77648
  Epoch 011 - train 0.74097 | val 0.77627
  Classification -> best τ=0.565 (val F1=0.1398)
  Directional -> Accuracy: 0.5312, MCC: -0.0725, F1: 0.6739

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68128 | val 0.71886
  Epoch 011 - train 0.68573 | val 0.72045
  Classification -> best τ=0.475 (val F1=0.2204)
  Directional -> Accuracy: 0.6486, MCC: 0.2936, F1: 0.6750

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69348 | val 0.85683
  Epoch 011 - train 0.69797 | val 0.85569
  Classification -> best τ=0.465 (val F1=0.3678)
  Directional -> Accuracy: 0.6383, MCC: 0.2268, F1: 0.7119

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70348 | val 0.70029
  Epoch 011 - train 0.69199 | val 0.70064
  Classification -> best τ=0.495 (val F1=0.2371)
  Directional -> Accuracy: 0.5692, MCC: 0.1377, F1: 0.5882

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69193 | val 0.79347
  Epoch 011 - train 0.68607 | val 0.79154
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70098 | val 1.11599
  Epoch 011 - train 0.69612 | val 1.10879
  Classification -> best τ=0.540 (val F1=0.1565)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69009 | val 0.66990
  Epoch 020 - train 0.67692 | val 0.66149
  Classification -> best τ=0.420 (val F1=0.3750)
  Directional -> Accuracy: 0.4545, MCC: -0.1365, F1: 0.5588

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68704 | val 0.74603
  Epoch 011 - train 0.72634 | val 0.75111
  Classification -> best τ=0.505 (val F1=0.1383)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68627 | val 0.75155
  Epoch 011 - train 0.68610 | val 0.75295
  Classification -> best τ=0.480 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71576 | val 0.75689
  Epoch 011 - train 0.71621 | val 0.75569
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69753 | val 0.65838
  Epoch 020 - train 0.70111 | val 0.65607
  Classification -> best τ=0.580 (val F1=0.4114)
  Directional -> Accuracy: 0.4750, MCC: -0.0161, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69233 | val 0.69029
  Epoch 011 - train 0.68858 | val 0.69010
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69380 | val 0.75954
  Epoch 011 - train 0.70106 | val 0.76031
  Classification -> best τ=0.475 (val F1=0.2031)
  Directional -> Accuracy: 0.5714, MCC: 0.2781, F1: 0.4000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68866 | val 0.68537
  Epoch 011 - train 0.69730 | val 0.68489
  Classification -> best τ=0.450 (val F1=0.2509)
  Directional -> Accuracy: 0.5306, MCC: 0.0229, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70018 | val 0.68027
  Epoch 020 - train 0.68135 | val 0.67608
  Classification -> best τ=0.535 (val F1=0.2929)
  Directional -> Accuracy: 0.4861, MCC: 0.0691, F1: 0.2745

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69267 | val 0.82833
  Epoch 011 - train 0.68521 | val 0.83076
  Classification -> best τ=0.520 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69254 | val 0.68390
  Epoch 020 - train 0.68803 | val 0.67374
  Classification -> best τ=0.420 (val F1=0.3342)
  Directional -> Accuracy: 0.6212, MCC: 0.1929, F1: 0.7191

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69253 | val 0.71061
  Epoch 011 - train 0.69262 | val 0.71086
  Classification -> best τ=0.485 (val F1=0.1150)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5116

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70214 | val 0.73168
  Epoch 011 - train 0.68902 | val 0.72993
  Classification -> best τ=0.540 (val F1=0.2478)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67401 | val 0.71776
  Epoch 011 - train 0.67390 | val 0.71795
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67757 | val 0.64999
  Epoch 018 - train 0.67214 | val 0.64723
  Classification -> best τ=0.540 (val F1=0.4306)
  Directional -> Accuracy: 0.6250, MCC: 0.0327, F1: 0.1818

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68119 | val 0.69694
  Epoch 011 - train 0.69643 | val 0.69527
  Classification -> best τ=0.520 (val F1=0.1639)
  Directional -> Accuracy: 0.5135, MCC: 0.0131, F1: 0.2800

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69210 | val 0.67580
  Epoch 014 - train 0.68760 | val 0.67621
  Classification -> best τ=0.440 (val F1=0.2737)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69218 | val 0.68194
  Epoch 017 - train 0.70388 | val 0.68272
  Classification -> best τ=0.555 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68540 | val 0.72812
  Epoch 011 - train 0.68433 | val 0.73079
  Classification -> best τ=0.515 (val F1=0.2015)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69745 | val 0.94900
  Epoch 011 - train 0.70337 | val 0.95036
  Classification -> best τ=0.415 (val F1=0.1290)
  Directional -> Accuracy: 0.5636, MCC: 0.1047, F1: 0.6364

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70102 | val 0.74801
  Epoch 011 - train 0.70287 | val 0.74771
  Classification -> best τ=0.470 (val F1=0.1728)
  Directional -> Accuracy: 0.4464, MCC: -0.1019, F1: 0.4918

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70057 | val 0.72465
  Epoch 011 - train 0.70707 | val 0.72470
  Classification -> best τ=0.520 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71638 | val 0.73102
  Epoch 011 - train 0.70001 | val 0.72579
  Classification -> best τ=0.415 (val F1=0.1647)
  Directional -> Accuracy: 0.5455, MCC: 0.1631, F1: 0.3590

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69029 | val 0.68868
  Epoch 011 - train 0.69638 | val 0.68759

[I 2026-02-20 04:18:39,870] Trial 150 finished with value: 0.1882907043846723 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 4.130733555753693e-06, 'weight_decay': 5.041651927819065e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.5010692667133106, 'early_stopping_min_delta': 0.004867229992846685}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.470 (val F1=0.0035)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1882907043846723
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53942 | val 1.60633
  Epoch 012 - train 0.49909 | val 1.95093
  Classification -> best τ=0.250 (val F1=0.3227)
  Directional -> Accuracy: 0.4868, MCC: -0.0014, F1: 0.5185

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41435 | val 1.23040
  Epoch 011 - train 0.44358 | val 1.15517
  Classification -> best τ=0.500 (val F1=0.1591)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56597 | val 1.69758
  Epoch 012 - train 0.45577 | val 1.85345
  Classification -> best τ=0.605 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56197 | val 2.06357
  Epoch 013 - train 0.44351 | val 3.54095
  Classification -> best τ=0.340 (val F1=0.0520)
  Directional -> Accuracy: 0.5270, MCC: 0.0416, F1: 0.5783

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59256 | val 2.62197
  Epoch 014 - train 0.37713 | val 3.36119
  Classification -> best τ=0.450 (val F1=0.4291)
  Directional -> Accuracy: 0.6400, MCC: 0.2871, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39582 | val 0.73761
  Epoch 011 - train 0.38733 | val 0.79825
  Classification -> best τ=0.530 (val F1=0.2329)
  Directional -> Accuracy: 0.5435, MCC: 0.0767, F1: 0.4324

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56235 | val 1.00148
  Epoch 011 - train 0.55781 | val 1.47896
  Classification -> best τ=0.295 (val F1=0.3336)
  Directional -> Accuracy: 0.4118, MCC: 0.0280, F1: 0.5652

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54362 | val 0.97994
  Epoch 017 - train 0.20570 | val 1.06827
  Classification -> best τ=0.175 (val F1=0.1639)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46584 | val 1.27708
  Epoch 011 - train 0.36318 | val 0.97267
  Classification -> best τ=0.525 (val F1=0.3376)
  Directional -> Accuracy: 0.6250, MCC: 0.2492, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49821 | val 0.83252
  Epoch 012 - train 0.45217 | val 0.83410
  Classification -> best τ=0.575 (val F1=0.3633)
  Directional -> Accuracy: 0.4493, MCC: 0.0544, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71068 | val 0.73522
  Epoch 017 - train 0.41109 | val 0.72871
  Classification -> best τ=0.355 (val F1=0.3153)
  Directional -> Accuracy: 0.4694, MCC: -0.0474, F1: 0.4800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44526 | val 3.64251
  Epoch 011 - train 0.43201 | val 4.24459
  Classification -> best τ=0.475 (val F1=0.2258)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51498 | val 1.02504
  Epoch 016 - train 0.30991 | val 0.82878
  Classification -> best τ=0.460 (val F1=0.2438)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66597 | val 0.77804
  Epoch 017 - train 0.44908 | val 0.86642
  Classification -> best τ=0.345 (val F1=0.3844)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40833 | val 4.11334
  Epoch 011 - train 0.42008 | val 5.01529
  Classification -> best τ=0.440 (val F1=0.0730)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59860 | val 0.67440
  Epoch 017 - train 0.45955 | val 0.98118
  Classification -> best τ=0.605 (val F1=0.4453)
  Directional -> Accuracy: 0.4928, MCC: -0.0009, F1: 0.4615

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49801 | val 6.15673
  Epoch 012 - train 0.45291 | val 14.11112
  Classification -> best τ=0.395 (val F1=0.0980)
  Directional -> Accuracy: 0.5517, MCC: -0.0484, F1: 0.6829

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46908 | val 3.36998
  Epoch 011 - train 0.48007 | val 3.23465
  Classification -> best τ=0.520 (val F1=0.1091)
  Directional -> Accuracy: 0.4533, MCC: 0.1938, F1: 0.1633

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58267 | val 1.19694
  Epoch 011 - train 0.54995 | val 1.14888
  Classification -> best τ=0.465 (val F1=0.2968)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46570 | val 1.69653
  Epoch 011 - train 0.43107 | val 1.59083
  Classification -> best τ=0.560 (val F1=0.1838)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51073 | val 1.48027
  Epoch 020 - train 0.27258 | val 0.65612
  Classification -> best τ=0.645 (val F1=0.4593)
  Directional -> Accuracy: 0.4255, MCC: 0.0074, F1: 0.2703

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62812 | val 1.49910
  Epoch 016 - train 0.48259 | val 2.49859
  Classification -> best τ=0.565 (val F1=0.1031)
  Directional -> Accuracy: 0.4769, MCC: -0.0622, F1: 0.1053

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56915 | val 1.92427
  Epoch 011 - train 0.53609 | val 2.10107
  Classification -> best τ=0.480 (val F1=0.2963)
  Directional -> Accuracy: 0.4737, MCC: -0.0596, F1: 0.5161

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51158 | val 5.03791
  Epoch 011 - train 0.50234 | val 4.13832
  Classification -> best τ=0.555 (val F1=0.2484)
  Directional -> Accuracy: 0.5077, MCC: 0.0285, F1: 0.5556

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49654 | val 1.93882
  Epoch 013 - train 0.45417 | val 2.52797
  Classification -> best τ=0.735 (val F1=0.5272)
  Directional -> Accuracy: 0.4727, MCC: 0.0090, F1: 0.2564

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44100 | val 5.19435
  Epoch 011 - train 0.40977 | val 6.10064
  Classification -> best τ=0.850 (val F1=0.2097)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52721 | val 1.02845
  Epoch 012 - train 0.47960 | val 0.80000
  Classification -> best τ=0.510 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43397 | val 1.18366
  Epoch 011 - train 0.41031 | val 1.28225
  Classification -> best τ=0.440 (val F1=0.2718)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53982 | val 0.85224
  Epoch 012 - train 0.42325 | val 1.06484
  Classification -> best τ=0.490 (val F1=0.2774)
  Directional -> Accuracy: 0.4500, MCC: -0.1370, F1: 0.5417

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50504 | val 0.65363
  Epoch 020 - train 0.32912 | val 0.77651
  Classification -> best τ=0.300 (val F1=0.3532)
  Directional -> Accuracy: 0.4762, MCC: -0.0500, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50157 | val 1.40126
  Epoch 012 - train 0.41269 | val 1.60733
  Classification -> best τ=0.375 (val F1=0.3054)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44455 | val 1.05278
  Epoch 011 - train 0.40087 | val 1.15250
  Classification -> best τ=0.480 (val F1=0.1697)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57704 | val 2.14143
  Epoch 012 - train 0.45866 | val 3.71014
  Classification -> best τ=0.435 (val F1=0.3313)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40753 | val 3.70984
  Epoch 012 - train 0.35867 | val 4.84574
  Classification -> best τ=0.335 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62693 | val 0.76673
  Epoch 014 - train 0.50975 | val 1.33392
  Classification -> best τ=0.230 (val F1=0.3525)
  Directional -> Accuracy: 0.5758, MCC: 0.2168, F1: 0.5333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39847 | val 1.92092
  Epoch 012 - train 0.31311 | val 2.24567
  Classification -> best τ=0.485 (val F1=0.2464)
  Directional -> Accuracy: 0.5952, MCC: 0.1870, F1: 0.6222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49120 | val 0.96049
  Epoch 011 - train 0.41726 | val 0.95956
  Classification -> best τ=0.505 (val F1=0.2382)
  Directional -> Accuracy: 0.4643, MCC: -0.1371, F1: 0.2105

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41510 | val 1.59031
  Epoch 011 - train 0.35290 | val 2.04576
  Classification -> best τ=0.520 (val F1=0.2338)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51513 | val 1.48988
  Epoch 014 - train 0.37915 | val 0.93805
  Classification -> best τ=0.315 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55500 | val 1.03928
  Epoch 012 - train 0.49968 | val 0.82909
  Classification -> best τ=0.315 (val F1=0.2769)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42558 | val 0.82450
  Epoch 012 - train 0.38406 | val 0.97525
  Classification -> best τ=0.525 (val F1=0.2582)
  Directional -> Accuracy: 0.5556, MCC: 0.1266, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44029 | val 1.72857
  Epoch 012 - train 0.34901 | val 1.78097
  Classification -> best τ=0.710 (val F1=0.2500)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52928 | val 0.90202
  Epoch 019 - train 0.19843 | val 1.27454
  Classification -> best τ=0.860 (val F1=0.3311)
  Directional -> Accuracy: 0.4583, MCC: 0.1155, F1: 0.5517

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59489 | val 1.81422
  Epoch 011 - train 0.56857 | val 1.83014
  Classification -> best τ=0.285 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42900 | val 3.91751
  Epoch 011 - train 0.37031 | val 3.91945
  Classification -> best τ=0.755 (val F1=0.2338)
  Directional -> Accuracy: 0.4464, MCC: -0.1444, F1: 0.2439

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49937 | val 1.22024
  Epoch 012 - train 0.45377 | val 1.51737
  Classification -> best τ=0.485 (val F1=0.2127)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47583 | val 3.78611
  Epoch 011 - train 0.43980 | val 4.53580
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.41874 | val 2.11799
  Epoch 011 - train 0.42986 | val 2.15025

[I 2026-02-20 04:20:21,078] Trial 151 finished with value: 0.2563575188010487 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005776558422733938, 'weight_decay': 4.698221727027963e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.28609624636155595, 'early_stopping_min_delta': 0.009547643413903142}. Best is trial 88 with value: 0.2868500347884126.

  Classification -> best τ=0.560 (val F1=0.1536)
  Directional -> Accuracy: 0.6333, MCC: 0.2681, F1: 0.6333

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2563575188010487
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51751 | val 1.34766
  Epoch 011 - train 0.53544 | val 1.33344
  Classification -> best τ=0.485 (val F1=0.1635)
  Directional -> Accuracy: 0.5921, MCC: 0.1942, F1: 0.5867

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58746 | val 0.90747
  Epoch 013 - train 0.37406 | val 1.45014
  Classification -> best τ=0.385 (val F1=0.2670)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54740 | val 1.58781
  Epoch 011 - train 0.49109 | val 1.58804
  Classification -> best τ=0.415 (val F1=0.4500)
  Directional -> Accuracy: 0.6304, MCC: 0.3213, F1: 0.7302

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50287 | val 2.82269
  Epoch 011 - train 0.52727 | val 3.09880
  Classification -> best τ=0.585 (val F1=0.1839)
  Directional -> Accuracy: 0.5270, MCC: 0.0294, F1: 0.6067

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50264 | val 1.87724
  Epoch 013 - train 0.40258 | val 3.90214
  Classification -> best τ=0.485 (val F1=0.4493)
  Directional -> Accuracy: 0.5400, MCC: 0.0835, F1: 0.5306

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46751 | val 1.48744
  Epoch 015 - train 0.31382 | val 0.83676
  Classification -> best τ=0.420 (val F1=0.3301)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52269 | val 2.08429
  Epoch 011 - train 0.51920 | val 2.13558
  Classification -> best τ=0.435 (val F1=0.3010)
  Directional -> Accuracy: 0.4412, MCC: 0.0124, F1: 0.5366

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50812 | val 1.36237
  Epoch 016 - train 0.17004 | val 1.24458
  Classification -> best τ=0.235 (val F1=0.2168)
  Directional -> Accuracy: 0.5238, MCC: 0.1452, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42808 | val 2.50019
  Epoch 012 - train 0.36817 | val 3.61634
  Classification -> best τ=0.605 (val F1=0.2326)
  Directional -> Accuracy: 0.4792, MCC: 0.0563, F1: 0.5902

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55571 | val 0.80107
  Epoch 017 - train 0.34633 | val 4.11797
  Classification -> best τ=0.275 (val F1=0.2287)
  Directional -> Accuracy: 0.5072, MCC: 0.1200, F1: 0.5854

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56635 | val 1.53982
  Epoch 013 - train 0.43269 | val 1.40536
  Classification -> best τ=0.595 (val F1=0.4059)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46325 | val 2.66328
  Epoch 012 - train 0.38970 | val 3.33384
  Classification -> best τ=0.570 (val F1=0.1576)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49174 | val 3.01119
  Epoch 013 - train 0.34539 | val 2.75446
  Classification -> best τ=0.495 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60583 | val 1.44222
  Epoch 014 - train 0.52251 | val 1.96314
  Classification -> best τ=0.295 (val F1=0.3635)
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42057 | val 2.60945
  Epoch 011 - train 0.38931 | val 4.94221
  Classification -> best τ=0.590 (val F1=0.2370)
  Directional -> Accuracy: 0.4902, MCC: 0.0277, F1: 0.5667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58871 | val 0.83227
  Epoch 012 - train 0.56851 | val 1.02144
  Classification -> best τ=0.380 (val F1=0.3448)
  Directional -> Accuracy: 0.4783, MCC: -0.1200, F1: 0.6170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44713 | val 3.68920
  Epoch 011 - train 0.42289 | val 4.48621
  Classification -> best τ=0.380 (val F1=0.1336)
  Directional -> Accuracy: 0.5690, MCC: -0.1826, F1: 0.7253

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51262 | val 1.13570
  Epoch 012 - train 0.51909 | val 1.37973
  Classification -> best τ=0.400 (val F1=0.2216)
  Directional -> Accuracy: 0.5200, MCC: 0.0894, F1: 0.5135

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55080 | val 1.18044
  Epoch 013 - train 0.54027 | val 1.46358
  Classification -> best τ=0.895 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43343 | val 2.61366
  Epoch 011 - train 0.47184 | val 1.40418
  Classification -> best τ=0.415 (val F1=0.2482)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46422 | val 1.06538
  Epoch 011 - train 0.46069 | val 0.88457
  Classification -> best τ=0.595 (val F1=0.1854)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52686 | val 1.73039
  Epoch 011 - train 0.51892 | val 2.09216
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60735 | val 1.30153
  Epoch 014 - train 0.42072 | val 2.09882
  Classification -> best τ=0.050 (val F1=0.2485)
  Directional -> Accuracy: 0.5088, MCC: -0.0465, F1: 0.6216

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54235 | val 3.82574
  Epoch 013 - train 0.41289 | val 5.11738
  Classification -> best τ=0.730 (val F1=0.1985)
  Directional -> Accuracy: 0.5385, MCC: 0.1309, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47713 | val 2.86730
  Epoch 012 - train 0.47286 | val 1.63651
  Classification -> best τ=0.520 (val F1=0.5278)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57079 | val 0.91080
  Epoch 011 - train 0.50534 | val 0.96765
  Classification -> best τ=0.565 (val F1=0.2241)
  Directional -> Accuracy: 0.4889, MCC: 0.0485, F1: 0.5490

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68188 | val 0.98692
  Epoch 014 - train 0.38752 | val 1.15062
  Classification -> best τ=0.545 (val F1=0.1353)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58366 | val 1.17096
  Epoch 015 - train 0.39632 | val 2.49507
  Classification -> best τ=0.270 (val F1=0.2665)
  Directional -> Accuracy: 0.4821, MCC: 0.0027, F1: 0.4082

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41017 | val 0.84036
  Epoch 011 - train 0.39121 | val 0.89674
  Classification -> best τ=0.515 (val F1=0.3518)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53326 | val 0.73463
  Epoch 020 - train 0.23491 | val 0.75600
  Classification -> best τ=0.480 (val F1=0.4067)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48931 | val 1.51217
  Epoch 012 - train 0.42472 | val 1.60790
  Classification -> best τ=0.480 (val F1=0.0806)
  Directional -> Accuracy: 0.4762, MCC: -0.1062, F1: 0.5926

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45127 | val 1.04357
  Epoch 012 - train 0.35225 | val 1.46157
  Classification -> best τ=0.430 (val F1=0.4602)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53288 | val 1.02030
  Epoch 011 - train 0.50446 | val 1.23369
  Classification -> best τ=0.610 (val F1=0.2637)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45490 | val 2.50876
  Epoch 011 - train 0.42774 | val 3.19969
  Classification -> best τ=0.690 (val F1=0.2780)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56396 | val 1.29894
  Epoch 012 - train 0.46231 | val 1.47479
  Classification -> best τ=0.455 (val F1=0.3758)
  Directional -> Accuracy: 0.4848, MCC: 0.1648, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30455 | val 1.00684
  Epoch 012 - train 0.27071 | val 2.17076
  Classification -> best τ=0.400 (val F1=0.2067)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47609 | val 2.06467
  Epoch 011 - train 0.44912 | val 2.62642
  Classification -> best τ=0.345 (val F1=0.1997)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42683 | val 0.86090
  Epoch 013 - train 0.29989 | val 1.50282
  Classification -> best τ=0.435 (val F1=0.2815)
  Directional -> Accuracy: 0.5435, MCC: 0.0891, F1: 0.5882

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48697 | val 1.05545
  Epoch 011 - train 0.43382 | val 1.44045
  Classification -> best τ=0.495 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42096 | val 2.06623
  Epoch 011 - train 0.45879 | val 1.53551
  Classification -> best τ=0.410 (val F1=0.2722)
  Directional -> Accuracy: 0.5270, MCC: 0.0729, F1: 0.6067

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45982 | val 1.13523
  Epoch 011 - train 0.40620 | val 1.03931
  Classification -> best τ=0.530 (val F1=0.1890)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59242 | val 0.82633
  Epoch 016 - train 0.32220 | val 2.60796
  Classification -> best τ=0.560 (val F1=0.5819)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47562 | val 1.30900
  Epoch 011 - train 0.45277 | val 1.36210
  Classification -> best τ=0.580 (val F1=0.6110)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55506 | val 1.98675
  Epoch 013 - train 0.40798 | val 3.45601
  Classification -> best τ=0.395 (val F1=0.1605)
  Directional -> Accuracy: 0.4545, MCC: -0.2887, F1: 0.6250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42469 | val 2.67224
  Epoch 011 - train 0.38333 | val 2.40875
  Classification -> best τ=0.850 (val F1=0.3988)
  Directional -> Accuracy: 0.6250, MCC: 0.2717, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59002 | val 0.73744
  Epoch 013 - train 0.44931 | val 0.83107
  Classification -> best τ=0.450 (val F1=0.3010)
  Directional -> Accuracy: 0.6226, MCC: 0.2681, F1: 0.6970

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43170 | val 3.54374
  Epoch 011 - train 0.43165 | val 2.31089
  Classification -> best τ=0.755 (val F1=0.0465)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59829 | val 1.34591

[I 2026-02-20 04:22:03,807] Trial 152 finished with value: 0.27848599591418033 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007809976124734774, 'weight_decay': 4.0769653030534393e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.3084164152294214, 'early_stopping_min_delta': 0.009218394478319958}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.48430 | val 1.72212
  Classification -> best τ=0.430 (val F1=0.2712)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27848599591418033
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58273 | val 0.77673
  Epoch 014 - train 0.45186 | val 0.97546
  Classification -> best τ=0.505 (val F1=0.3286)
  Directional -> Accuracy: 0.5789, MCC: 0.1588, F1: 0.5556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49441 | val 2.12827
  Epoch 012 - train 0.45828 | val 1.61349
  Classification -> best τ=0.440 (val F1=0.2428)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58319 | val 0.69984
  Epoch 012 - train 0.52068 | val 0.68159
  Classification -> best τ=0.600 (val F1=0.3894)
  Directional -> Accuracy: 0.4565, MCC: -0.0756, F1: 0.3243

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.49987 | val 4.45367
  Epoch 012 - train 0.48866 | val 4.83496
  Classification -> best τ=0.160 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0427, F1: 0.6531

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45916 | val 1.27048
  Epoch 011 - train 0.40069 | val 1.06513
  Classification -> best τ=0.755 (val F1=0.3408)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47750 | val 0.77558
  Epoch 011 - train 0.48609 | val 0.91782
  Classification -> best τ=0.540 (val F1=0.1808)
  Directional -> Accuracy: 0.5217, MCC: 0.0169, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58247 | val 1.86697
  Epoch 011 - train 0.55106 | val 1.98892
  Classification -> best τ=0.145 (val F1=0.1651)
  Directional -> Accuracy: 0.4118, MCC: 0.0991, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55202 | val 0.64290
  Epoch 014 - train 0.48327 | val 0.76811
  Classification -> best τ=0.470 (val F1=0.3689)
  Directional -> Accuracy: 0.5952, MCC: 0.1578, F1: 0.4848

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47426 | val 2.90128
  Epoch 011 - train 0.45534 | val 2.86412
  Classification -> best τ=0.615 (val F1=0.2784)
  Directional -> Accuracy: 0.4792, MCC: 0.0242, F1: 0.5614

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71581 | val 1.38889
  Epoch 015 - train 0.47869 | val 1.36991
  Classification -> best τ=0.280 (val F1=0.2079)
  Directional -> Accuracy: 0.4783, MCC: -0.0139, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53351 | val 1.56291
  Epoch 011 - train 0.50400 | val 1.18192
  Classification -> best τ=0.540 (val F1=0.3590)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52301 | val 3.58825
  Epoch 015 - train 0.35917 | val 5.65542
  Classification -> best τ=0.750 (val F1=0.2554)
  Directional -> Accuracy: 0.5789, MCC: 0.2347, F1: 0.7000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43519 | val 3.41557
  Epoch 011 - train 0.39982 | val 3.08060
  Classification -> best τ=0.600 (val F1=0.1225)
  Directional -> Accuracy: 0.5952, MCC: 0.1940, F1: 0.2609

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.48988 | val 1.84876
  Epoch 011 - train 0.49553 | val 1.70294
  Classification -> best τ=0.165 (val F1=0.2878)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46625 | val 1.56586
  Epoch 011 - train 0.45319 | val 2.03231
  Classification -> best τ=0.580 (val F1=0.2971)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62742 | val 0.73470
  Epoch 012 - train 0.57793 | val 0.82469
  Classification -> best τ=0.755 (val F1=0.2948)
  Directional -> Accuracy: 0.5217, MCC: 0.0978, F1: 0.3774

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54441 | val 2.76893
  Epoch 011 - train 0.49689 | val 2.96209
  Classification -> best τ=0.825 (val F1=0.0732)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64645 | val 1.47727
  Epoch 013 - train 0.55769 | val 1.97881
  Classification -> best τ=0.545 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54341 | val 1.54653
  Epoch 012 - train 0.53934 | val 2.55185
  Classification -> best τ=0.425 (val F1=0.1755)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51900 | val 0.92895
  Epoch 011 - train 0.51214 | val 0.78871
  Classification -> best τ=0.540 (val F1=0.3525)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60313 | val 0.77781
  Epoch 013 - train 0.50275 | val 1.06877
  Classification -> best τ=0.480 (val F1=0.4078)
  Directional -> Accuracy: 0.5957, MCC: 0.1179, F1: 0.6885

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55665 | val 1.95364
  Epoch 011 - train 0.55587 | val 2.14350
  Classification -> best τ=0.630 (val F1=0.2543)
  Directional -> Accuracy: 0.4923, MCC: -0.0039, F1: 0.1081

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62409 | val 1.30113
  Epoch 014 - train 0.53218 | val 2.52715
  Classification -> best τ=0.470 (val F1=0.4074)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56498 | val 3.04533
  Epoch 012 - train 0.52986 | val 3.54397
  Classification -> best τ=0.660 (val F1=0.1565)
  Directional -> Accuracy: 0.5077, MCC: 0.0161, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43023 | val 2.03917
  Epoch 011 - train 0.40002 | val 1.49495
  Classification -> best τ=0.570 (val F1=0.1386)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42153 | val 5.49991
  Epoch 011 - train 0.37182 | val 6.06933
  Classification -> best τ=0.760 (val F1=0.2726)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61888 | val 0.77580
  Epoch 011 - train 0.57642 | val 0.79837
  Classification -> best τ=0.640 (val F1=0.0278)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50985 | val 1.57980
  Epoch 011 - train 0.48677 | val 1.80593
  Classification -> best τ=0.410 (val F1=0.2417)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40527 | val 1.37893
  Epoch 011 - train 0.38946 | val 1.76432
  Classification -> best τ=0.595 (val F1=0.3477)
  Directional -> Accuracy: 0.5250, MCC: 0.0661, F1: 0.5128

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60964 | val 0.75850
  Epoch 020 - train 0.46898 | val 1.03487
  Classification -> best τ=0.705 (val F1=0.4846)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53508 | val 1.61354
  Epoch 013 - train 0.42419 | val 0.81329
  Classification -> best τ=0.590 (val F1=0.2298)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58980 | val 0.89129
  Epoch 013 - train 0.41938 | val 2.22734
  Classification -> best τ=0.210 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56942 | val 1.05836
  Epoch 011 - train 0.54523 | val 1.49314
  Classification -> best τ=0.505 (val F1=0.3526)
  Directional -> Accuracy: 0.5278, MCC: 0.1569, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52105 | val 1.31542
  Epoch 011 - train 0.49696 | val 1.60219
  Classification -> best τ=0.625 (val F1=0.2780)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61539 | val 1.58689
  Epoch 014 - train 0.44111 | val 2.48963
  Classification -> best τ=0.225 (val F1=0.3201)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36371 | val 0.73960
  Epoch 012 - train 0.30367 | val 0.75080
  Classification -> best τ=0.555 (val F1=0.2106)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47753 | val 1.48099
  Epoch 011 - train 0.45023 | val 2.21352
  Classification -> best τ=0.380 (val F1=0.1684)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41156 | val 1.68124
  Epoch 011 - train 0.39923 | val 1.30897
  Classification -> best τ=0.545 (val F1=0.2877)
  Directional -> Accuracy: 0.5652, MCC: 0.1055, F1: 0.6296

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49348 | val 0.79620
  Epoch 013 - train 0.41838 | val 0.82139
  Classification -> best τ=0.340 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61409 | val 1.04236
  Epoch 017 - train 0.42144 | val 1.54750
  Classification -> best τ=0.350 (val F1=0.3725)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49073 | val 3.34024
  Epoch 016 - train 0.27979 | val 3.25383
  Classification -> best τ=0.465 (val F1=0.2712)
  Directional -> Accuracy: 0.5556, MCC: 0.1266, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57568 | val 1.14310
  Epoch 014 - train 0.59140 | val 1.49727
  Classification -> best τ=0.390 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0700, F1: 0.6897

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62317 | val 0.75650
  Epoch 012 - train 0.65819 | val 0.69946
  Classification -> best τ=0.695 (val F1=0.3300)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60068 | val 2.73373
  Epoch 012 - train 0.53570 | val 2.89613
  Classification -> best τ=0.545 (val F1=0.1884)
  Directional -> Accuracy: 0.5273, MCC: 0.2557, F1: 0.2353

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57607 | val 2.06736
  Epoch 011 - train 0.53477 | val 2.58149
  Classification -> best τ=0.760 (val F1=0.2649)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53838 | val 0.90327
  Epoch 012 - train 0.49339 | val 1.12563
  Classification -> best τ=0.605 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.0969, F1: 0.6364

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51738 | val 3.24604
  Epoch 012 - train 0.43518 | val 3.54146
  Classification -> best τ=0.715 (val F1=0.1605)
  Directional -> Accuracy: 0.5091, MCC: 0.0133, F1: 0.5424

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62026 | val 1.58099

[I 2026-02-20 04:23:46,569] Trial 153 finished with value: 0.2727532247949105 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.007660646540815329, 'weight_decay': 3.6681646438245023e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.32734663595950364, 'early_stopping_min_delta': 0.008967191328070202}. Best is trial 88 with value: 0.2868500347884126.

  Epoch 013 - train 0.56140 | val 2.60991
  Classification -> best τ=0.415 (val F1=0.2723)
  Directional -> Accuracy: 0.5833, MCC: 0.1965, F1: 0.6479

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2727532247949105
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56035 | val 0.92672
  Epoch 011 - train 0.57923 | val 0.78618
  Classification -> best τ=0.405 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62155 | val 1.22302
  Epoch 012 - train 0.54050 | val 1.26132
  Classification -> best τ=0.430 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61214 | val 1.25368
  Epoch 014 - train 0.43435 | val 2.50531
  Classification -> best τ=0.580 (val F1=0.3237)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54513 | val 4.77681
  Epoch 011 - train 0.58019 | val 4.31675
  Classification -> best τ=0.210 (val F1=0.2625)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49035 | val 1.57791
  Epoch 012 - train 0.42919 | val 0.90050
  Classification -> best τ=0.570 (val F1=0.4851)
  Directional -> Accuracy: 0.5800, MCC: 0.1574, F1: 0.6038

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40678 | val 1.56314
  Epoch 011 - train 0.36708 | val 1.59941
  Classification -> best τ=0.620 (val F1=0.2699)
  Directional -> Accuracy: 0.5000, MCC: -0.0766, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55234 | val 1.50129
  Epoch 011 - train 0.55053 | val 2.10105
  Classification -> best τ=0.305 (val F1=0.2190)
  Directional -> Accuracy: 0.4265, MCC: 0.1413, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48655 | val 1.82211
  Epoch 018 - train 0.17498 | val 1.40245
  Classification -> best τ=0.580 (val F1=0.1795)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.2609

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50234 | val 4.03376
  Epoch 011 - train 0.39313 | val 6.25561
  Classification -> best τ=0.670 (val F1=0.4197)
  Directional -> Accuracy: 0.6458, MCC: 0.2768, F1: 0.5854

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44969 | val 1.46675
  Epoch 011 - train 0.44867 | val 0.90996
  Classification -> best τ=0.480 (val F1=0.3006)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56260 | val 0.69517
  Epoch 014 - train 0.45305 | val 0.68792
  Classification -> best τ=0.520 (val F1=0.4498)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52022 | val 2.40869
  Epoch 012 - train 0.44648 | val 2.60299
  Classification -> best τ=0.575 (val F1=0.3338)
  Directional -> Accuracy: 0.5088, MCC: 0.0119, F1: 0.5882

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44384 | val 0.87541
  Epoch 011 - train 0.49436 | val 0.74861
  Classification -> best τ=0.375 (val F1=0.3073)
  Directional -> Accuracy: 0.4762, MCC: -0.0026, F1: 0.5600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55548 | val 1.23425
  Epoch 016 - train 0.41251 | val 1.24417
  Classification -> best τ=0.270 (val F1=0.3916)
  Directional -> Accuracy: 0.5833, MCC: 0.1675, F1: 0.5614

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50016 | val 1.52809
  Epoch 011 - train 0.44745 | val 1.94993
  Classification -> best τ=0.490 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55696 | val 0.83091
  Epoch 012 - train 0.58355 | val 27.28647
  Classification -> best τ=0.390 (val F1=0.3372)
  Directional -> Accuracy: 0.5217, MCC: -0.0081, F1: 0.6526

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53479 | val 2.83659
  Epoch 011 - train 0.50649 | val 3.40555
  Classification -> best τ=0.555 (val F1=0.2296)
  Directional -> Accuracy: 0.3103, MCC: -0.3482, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51430 | val 1.50891
  Epoch 011 - train 0.49401 | val 1.33165
  Classification -> best τ=0.580 (val F1=0.1539)
  Directional -> Accuracy: 0.4667, MCC: -0.0439, F1: 0.4872

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61985 | val 0.88870
  Epoch 015 - train 0.50669 | val 1.23369
  Classification -> best τ=0.265 (val F1=0.2843)
  Directional -> Accuracy: 0.4688, MCC: -0.0294, F1: 0.4516

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45859 | val 4.11074
  Epoch 011 - train 0.41432 | val 2.51423
  Classification -> best τ=0.420 (val F1=0.2403)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55764 | val 0.86138
  Epoch 016 - train 0.40135 | val 1.67903
  Classification -> best τ=0.510 (val F1=0.4554)
  Directional -> Accuracy: 0.5319, MCC: 0.1638, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58649 | val 1.25099
  Epoch 011 - train 0.54913 | val 1.44894
  Classification -> best τ=0.545 (val F1=0.1709)
  Directional -> Accuracy: 0.5077, MCC: 0.0103, F1: 0.5897

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66848 | val 0.94674
  Epoch 016 - train 0.45957 | val 1.96464
  Classification -> best τ=0.695 (val F1=0.3304)
  Directional -> Accuracy: 0.5263, MCC: 0.1125, F1: 0.4490

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62631 | val 2.24374
  Epoch 011 - train 0.56067 | val 2.50623
  Classification -> best τ=0.635 (val F1=0.1429)
  Directional -> Accuracy: 0.5231, MCC: 0.0624, F1: 0.5753

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49129 | val 2.04706
  Epoch 011 - train 0.44743 | val 2.31640
  Classification -> best τ=0.550 (val F1=0.4120)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40906 | val 5.08516
  Epoch 011 - train 0.37918 | val 5.98288
  Classification -> best τ=0.675 (val F1=0.4019)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53178 | val 1.89267
  Epoch 011 - train 0.50956 | val 2.04719
  Classification -> best τ=0.485 (val F1=0.0700)
  Directional -> Accuracy: 0.5952, MCC: 0.1578, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.49438 | val 1.87846
  Epoch 013 - train 0.40424 | val 2.29275
  Classification -> best τ=0.310 (val F1=0.2305)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44996 | val 0.98232
  Epoch 011 - train 0.38871 | val 0.90054
  Classification -> best τ=0.595 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59699 | val 0.86905
  Epoch 014 - train 0.49846 | val 1.08596
  Classification -> best τ=0.480 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49637 | val 4.05649
  Epoch 012 - train 0.38609 | val 3.10677
  Classification -> best τ=0.305 (val F1=0.2786)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45999 | val 1.23414
  Epoch 011 - train 0.39827 | val 1.18352
  Classification -> best τ=0.545 (val F1=0.3465)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56353 | val 0.68088
  Epoch 013 - train 0.46113 | val 0.99636
  Classification -> best τ=0.475 (val F1=0.3576)
  Directional -> Accuracy: 0.5139, MCC: 0.0652, F1: 0.4615

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45087 | val 3.56579
  Epoch 011 - train 0.41006 | val 4.86729
  Classification -> best τ=0.700 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50000 | val 1.24310
  Epoch 012 - train 0.47788 | val 1.04588
  Classification -> best τ=0.375 (val F1=0.3366)
  Directional -> Accuracy: 0.6061, MCC: 0.1678, F1: 0.6905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46043 | val 1.99372
  Epoch 011 - train 0.42070 | val 1.55017
  Classification -> best τ=0.360 (val F1=0.1715)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42264 | val 3.61224
  Epoch 012 - train 0.42063 | val 3.52814
  Classification -> best τ=0.300 (val F1=0.2530)
  Directional -> Accuracy: 0.5714, MCC: 0.1623, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53326 | val 1.07879
  Epoch 015 - train 0.30851 | val 1.41655
  Classification -> best τ=0.525 (val F1=0.5001)
  Directional -> Accuracy: 0.6304, MCC: 0.1490, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51362 | val 0.62325
  Epoch 017 - train 0.43029 | val 0.84235
  Classification -> best τ=0.285 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58705 | val 1.01367
  Epoch 015 - train 0.36516 | val 1.50776
  Classification -> best τ=0.505 (val F1=0.3383)
  Directional -> Accuracy: 0.5405, MCC: 0.1901, F1: 0.6731

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48328 | val 0.71204
  Epoch 011 - train 0.42834 | val 0.71036
  Classification -> best τ=0.510 (val F1=0.3500)
  Directional -> Accuracy: 0.5111, MCC: 0.0832, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48592 | val 0.98165
  Epoch 012 - train 0.44508 | val 1.17075
  Classification -> best τ=0.595 (val F1=0.4001)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51862 | val 1.73689
  Epoch 014 - train 0.41317 | val 1.50628
  Classification -> best τ=0.520 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58588 | val 2.05314
  Epoch 012 - train 0.49327 | val 2.00087
  Classification -> best τ=0.600 (val F1=0.2754)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50581 | val 2.63254
  Epoch 011 - train 0.46080 | val 3.63629
  Classification -> best τ=0.680 (val F1=0.2504)
  Directional -> Accuracy: 0.5000, MCC: -0.0039, F1: 0.4615

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66664 | val 0.70301
  Epoch 011 - train 0.62313 | val 0.76782
  Classification -> best τ=0.615 (val F1=0.2369)
  Directional -> Accuracy: 0.5283, MCC: 0.0863, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48924 | val 0.99626
  Epoch 012 - train 0.46569 | val 2.01087
  Classification -> best τ=0.785 (val F1=0.1815)
  Directional -> Accuracy: 0.4182, MCC: -0.2537, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51665 | val 0.74214
  Epoch 011 - train 0.51222 | val 0.82228

[I 2026-02-20 04:25:26,373] Trial 154 finished with value: 0.29985667076798134 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.00835173756674262, 'weight_decay': 6.256612197125085e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.19685541052669603, 'early_stopping_min_delta': 0.009790395908738146}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.505 (val F1=0.2749)
  Directional -> Accuracy: 0.6000, MCC: 0.2859, F1: 0.6923

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29985667076798134
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57282 | val 5.93862
  Epoch 011 - train 0.54046 | val 5.32867
  Classification -> best τ=0.350 (val F1=0.1623)
  Directional -> Accuracy: 0.4286, MCC: -0.1166, F1: 0.5769

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63369 | val 0.95719
  Epoch 012 - train 0.61263 | val 0.86221
  Classification -> best τ=0.480 (val F1=0.2431)
  Directional -> Accuracy: 0.5652, MCC: 0.1055, F1: 0.6296

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61230 | val 1.01714
  Epoch 012 - train 0.56539 | val 1.84937
  Classification -> best τ=0.450 (val F1=0.4547)
  Directional -> Accuracy: 0.5957, MCC: 0.2064, F1: 0.7077

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63856 | val 5.38217
  Epoch 013 - train 0.52350 | val 2.34760
  Classification -> best τ=0.555 (val F1=0.1780)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57964 | val 1.85485
  Epoch 011 - train 0.51771 | val 1.60667
  Classification -> best τ=0.570 (val F1=0.1178)
  Directional -> Accuracy: 0.4314, MCC: -0.1280, F1: 0.2162

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55273 | val 1.04944
  Epoch 012 - train 0.58424 | val 1.09504
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56481 | val 1.57791
  Epoch 011 - train 0.56211 | val 1.40674
  Classification -> best τ=0.585 (val F1=0.2558)
  Directional -> Accuracy: 0.5507, MCC: 0.0307, F1: 0.3673

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45715 | val 5.29337
  Epoch 011 - train 0.50455 | val 6.02684
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56935 | val 1.60188
  Epoch 011 - train 0.61014 | val 1.70258
  Classification -> best τ=0.430 (val F1=0.2223)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68267 | val 0.76245
  Epoch 012 - train 0.59216 | val 0.81919
  Classification -> best τ=0.550 (val F1=0.1508)
  Directional -> Accuracy: 0.5857, MCC: 0.0986, F1: 0.2564

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51982 | val 1.25844
  Epoch 011 - train 0.50683 | val 1.33992
  Classification -> best τ=0.500 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0296, F1: 0.2069

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54177 | val 1.40670
  Epoch 011 - train 0.55729 | val 1.28163
  Classification -> best τ=0.405 (val F1=0.1703)
  Directional -> Accuracy: 0.5517, MCC: 0.1843, F1: 0.2353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55946 | val 1.88347
  Epoch 012 - train 0.50931 | val 3.13269
  Classification -> best τ=0.505 (val F1=0.2266)
  Directional -> Accuracy: 0.4419, MCC: -0.0471, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71690 | val 0.78713
  Epoch 013 - train 0.67176 | val 0.74215
  Classification -> best τ=0.290 (val F1=0.3591)
  Directional -> Accuracy: 0.5246, MCC: 0.0795, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66654 | val 4.35480
  Epoch 017 - train 0.47156 | val 18.63027
  Classification -> best τ=0.670 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57216 | val 1.37732
  Epoch 011 - train 0.59044 | val 1.05917
  Classification -> best τ=0.560 (val F1=0.2205)
  Directional -> Accuracy: 0.6143, MCC: 0.2196, F1: 0.7097

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69253 | val 1.57044
  Epoch 011 - train 0.64787 | val 1.96573
  Classification -> best τ=0.515 (val F1=0.1302)
  Directional -> Accuracy: 0.5424, MCC: -0.1322, F1: 0.6897

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63064 | val 0.85023
  Epoch 011 - train 0.62835 | val 0.79833
  Classification -> best τ=0.435 (val F1=0.1535)
  Directional -> Accuracy: 0.6053, MCC: 0.1553, F1: 0.6875

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68101 | val 0.81442
  Epoch 014 - train 0.63401 | val 0.85824
  Classification -> best τ=0.715 (val F1=0.2249)
  Directional -> Accuracy: 0.4615, MCC: 0.0668, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56785 | val 1.57828
  Epoch 011 - train 0.54302 | val 1.68934
  Classification -> best τ=0.525 (val F1=0.2651)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63668 | val 0.97847
  Epoch 018 - train 0.47304 | val 3.09911
  Classification -> best τ=0.255 (val F1=0.3941)
  Directional -> Accuracy: 0.4583, MCC: -0.1080, F1: 0.5357

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63331 | val 1.24051
  Epoch 011 - train 0.59926 | val 1.46257
  Classification -> best τ=0.460 (val F1=0.2054)
  Directional -> Accuracy: 0.4697, MCC: -0.1768, F1: 0.6392

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66016 | val 0.71610
  Epoch 017 - train 0.54535 | val 1.96466
  Classification -> best τ=0.465 (val F1=0.3913)
  Directional -> Accuracy: 0.5345, MCC: 0.0951, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58910 | val 2.12454
  Epoch 011 - train 0.57495 | val 1.10550
  Classification -> best τ=0.310 (val F1=0.2382)
  Directional -> Accuracy: 0.5000, MCC: 0.0864, F1: 0.6374

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64342 | val 0.68143
  Epoch 012 - train 0.62773 | val 0.78463
  Classification -> best τ=0.465 (val F1=0.3951)
  Directional -> Accuracy: 0.5179, MCC: 0.1949, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53876 | val 1.32054
  Epoch 013 - train 0.52777 | val 1.01768
  Classification -> best τ=0.525 (val F1=0.1925)
  Directional -> Accuracy: 0.6739, MCC: 0.3330, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65086 | val 0.70642
  Epoch 012 - train 0.57983 | val 0.90484
  Classification -> best τ=0.520 (val F1=0.3533)
  Directional -> Accuracy: 0.5116, MCC: -0.0454, F1: 0.6182

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68088 | val 0.82274
  Epoch 013 - train 0.58999 | val 1.23224
  Classification -> best τ=0.500 (val F1=0.2529)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55791 | val 0.67005
  Epoch 020 - train 0.47846 | val 0.74559
  Classification -> best τ=0.495 (val F1=0.4576)
  Directional -> Accuracy: 0.5366, MCC: 0.0716, F1: 0.5581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56488 | val 1.87728
  Epoch 017 - train 0.34718 | val 2.72331
  Classification -> best τ=0.690 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54410 | val 2.16936
  Epoch 012 - train 0.44128 | val 3.08953
  Classification -> best τ=0.700 (val F1=0.1667)
  Directional -> Accuracy: 0.4419, MCC: -0.0944, F1: 0.2941

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62180 | val 0.70583
  Epoch 012 - train 0.56861 | val 0.70504
  Classification -> best τ=0.435 (val F1=0.3180)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59354 | val 0.69089
  Epoch 016 - train 0.49304 | val 0.84264
  Classification -> best τ=0.395 (val F1=0.2477)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52382 | val 2.21501
  Epoch 012 - train 0.46355 | val 1.81127
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.74606 | val 0.95525
  Epoch 013 - train 0.58321 | val 1.04298
  Classification -> best τ=0.485 (val F1=0.1821)
  Directional -> Accuracy: 0.5682, MCC: 0.2284, F1: 0.1739

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64726 | val 0.75788
  Epoch 011 - train 0.64271 | val 0.73805
  Classification -> best τ=0.375 (val F1=0.3936)
  Directional -> Accuracy: 0.5821, MCC: 0.1488, F1: 0.6316

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58061 | val 0.86519
  Epoch 012 - train 0.45135 | val 1.13592
  Classification -> best τ=0.550 (val F1=0.3300)
  Directional -> Accuracy: 0.4884, MCC: -0.0074, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54825 | val 1.38983
  Epoch 013 - train 0.47332 | val 1.97875
  Classification -> best τ=0.380 (val F1=0.2764)
  Directional -> Accuracy: 0.6140, MCC: 0.2236, F1: 0.5217

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51915 | val 3.14444
  Epoch 011 - train 0.50858 | val 2.83588
  Classification -> best τ=0.545 (val F1=0.0508)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53153 | val 0.79738
  Epoch 011 - train 0.51977 | val 0.86798
  Classification -> best τ=0.415 (val F1=0.3182)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47624 | val 2.86246
  Epoch 011 - train 0.45524 | val 3.67623
  Classification -> best τ=0.545 (val F1=0.2041)
  Directional -> Accuracy: 0.5789, MCC: 0.1556, F1: 0.6000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56827 | val 1.73957
  Epoch 012 - train 0.53878 | val 1.41726
  Classification -> best τ=0.490 (val F1=0.2782)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51385 | val 1.30923
  Epoch 011 - train 0.50243 | val 0.89473
  Classification -> best τ=0.550 (val F1=0.1122)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60677 | val 1.76000
  Epoch 014 - train 0.53240 | val 1.05205
  Classification -> best τ=0.360 (val F1=0.5115)
  Directional -> Accuracy: 0.5455, MCC: -0.1329, F1: 0.7059

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59881 | val 1.50258
  Epoch 014 - train 0.53584 | val 1.75220
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67332 | val 2.00841
  Epoch 012 - train 0.73424 | val 1.96035
  Classification -> best τ=0.630 (val F1=0.2465)
  Directional -> Accuracy: 0.4286, MCC: -0.2777, F1: 0.5897

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61415 | val 0.97542
  Epoch 014 - train 0.48959 | val 0.98065
  Classification -> best τ=0.635 (val F1=0.3170)
  Directional -> Accuracy: 0.5789, MCC: 0.2485, F1: 0.2000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62050 | val 1.69482
  Epoch 012 - train 0.55744 | val 1.72597
  Classification -> best τ=0.690 (val F1=0.2697)
  Directional -> Accuracy: 0.5741, MCC: 0.1448, F1: 0.6462

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63074 | val 2.59208
  Epoch 011 - train 0.59736 | val 1.77901
  Classification -> best τ=0.425 (val F1=0.2396)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65741 | val 0.70992

[I 2026-02-20 04:27:08,471] Trial 155 finished with value: 0.2409334010064001 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.008039104238814203, 'weight_decay': 1.4455753619681005e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.23417779022963348, 'early_stopping_min_delta': 0.00992808923448802}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 018 - train 0.51125 | val 2.25734
  Classification -> best τ=0.220 (val F1=0.3817)
  Directional -> Accuracy: 0.4754, MCC: -0.0244, F1: 0.5897

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2409334010064001
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53807 | val 2.13091
  Epoch 011 - train 0.50208 | val 1.46919
  Classification -> best τ=0.420 (val F1=0.1415)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61231 | val 0.77674
  Epoch 017 - train 0.38170 | val 0.75406
  Classification -> best τ=0.355 (val F1=0.2029)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51367 | val 2.51438
  Epoch 017 - train 0.43141 | val 0.90528
  Classification -> best τ=0.600 (val F1=0.2700)
  Directional -> Accuracy: 0.5870, MCC: 0.2249, F1: 0.7077

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61243 | val 1.30335
  Epoch 012 - train 0.53065 | val 2.15037
  Classification -> best τ=0.560 (val F1=0.1079)
  Directional -> Accuracy: 0.5135, MCC: -0.0016, F1: 0.6000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66508 | val 1.04373
  Epoch 017 - train 0.44519 | val 2.31370
  Classification -> best τ=0.865 (val F1=0.3933)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46252 | val 1.09464
  Epoch 011 - train 0.39213 | val 1.20639
  Classification -> best τ=0.545 (val F1=0.2739)
  Directional -> Accuracy: 0.6087, MCC: 0.2179, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54650 | val 1.11857
  Epoch 011 - train 0.54453 | val 1.30685
  Classification -> best τ=0.250 (val F1=0.2557)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44425 | val 3.92642
  Epoch 014 - train 0.30240 | val 1.99888
  Classification -> best τ=0.490 (val F1=0.2677)
  Directional -> Accuracy: 0.4286, MCC: -0.0807, F1: 0.5200

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60584 | val 1.99209
  Epoch 011 - train 0.54447 | val 2.02919
  Classification -> best τ=0.470 (val F1=0.2231)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59362 | val 0.81251
  Epoch 014 - train 0.45188 | val 1.33443
  Classification -> best τ=0.565 (val F1=0.1858)
  Directional -> Accuracy: 0.4638, MCC: 0.0099, F1: 0.5432

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52678 | val 0.74252
  Epoch 011 - train 0.51665 | val 1.64001
  Classification -> best τ=0.510 (val F1=0.1687)
  Directional -> Accuracy: 0.4898, MCC: 0.0161, F1: 0.5455

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50441 | val 1.22970
  Epoch 011 - train 0.46127 | val 2.16083
  Classification -> best τ=0.710 (val F1=0.2858)
  Directional -> Accuracy: 0.4912, MCC: -0.0129, F1: 0.4082

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39628 | val 0.66573
  Epoch 011 - train 0.40665 | val 0.99395
  Classification -> best τ=0.575 (val F1=0.2427)
  Directional -> Accuracy: 0.4762, MCC: -0.0673, F1: 0.3889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66377 | val 0.69494
  Epoch 019 - train 0.50500 | val 0.79821
  Classification -> best τ=0.355 (val F1=0.2446)
  Directional -> Accuracy: 0.5167, MCC: 0.0519, F1: 0.6506

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51599 | val 1.53097
  Epoch 011 - train 0.45796 | val 2.52063
  Classification -> best τ=0.470 (val F1=0.2326)
  Directional -> Accuracy: 0.4510, MCC: -0.0360, F1: 0.5882

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61076 | val 0.95720
  Epoch 016 - train 0.48206 | val 1.81159
  Classification -> best τ=0.540 (val F1=0.4375)
  Directional -> Accuracy: 0.4638, MCC: -0.0600, F1: 0.4308

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52477 | val 31.81454
  Epoch 011 - train 0.50959 | val 36.59480
  Classification -> best τ=0.245 (val F1=0.0516)
  Directional -> Accuracy: 0.6379, MCC: 0.1397, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54489 | val 1.07299
  Epoch 012 - train 0.47700 | val 2.10189
  Classification -> best τ=0.130 (val F1=0.1962)
  Directional -> Accuracy: 0.5733, MCC: 0.0915, F1: 0.6596

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51666 | val 1.50670
  Epoch 011 - train 0.48944 | val 1.54798
  Classification -> best τ=0.350 (val F1=0.2055)
  Directional -> Accuracy: 0.5312, MCC: 0.0891, F1: 0.5312

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54555 | val 2.11631
  Epoch 012 - train 0.48877 | val 1.40298
  Classification -> best τ=0.630 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59591 | val 0.81890
  Epoch 011 - train 0.55585 | val 0.77290
  Classification -> best τ=0.495 (val F1=0.1988)
  Directional -> Accuracy: 0.4255, MCC: 0.0834, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60384 | val 3.77776
  Epoch 016 - train 0.44987 | val 7.57578
  Classification -> best τ=0.535 (val F1=0.3468)
  Directional -> Accuracy: 0.4923, MCC: -0.0066, F1: 0.2326

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65387 | val 1.10724
  Epoch 013 - train 0.55222 | val 1.43849
  Classification -> best τ=0.495 (val F1=0.4373)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66954 | val 0.75549
  Epoch 015 - train 0.50446 | val 1.56599
  Classification -> best τ=0.740 (val F1=0.1393)
  Directional -> Accuracy: 0.5077, MCC: -0.0112, F1: 0.3043

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62404 | val 0.86098
  Epoch 014 - train 0.48167 | val 2.07759
  Classification -> best τ=0.485 (val F1=0.5656)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49503 | val 1.24128
  Epoch 011 - train 0.49460 | val 1.25728
  Classification -> best τ=0.485 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55190 | val 0.82354
  Epoch 012 - train 0.52525 | val 1.02913
  Classification -> best τ=0.580 (val F1=0.2582)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51537 | val 2.28146
  Epoch 013 - train 0.42333 | val 2.76288
  Classification -> best τ=0.415 (val F1=0.2725)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50747 | val 1.20458
  Epoch 011 - train 0.48274 | val 1.16847
  Classification -> best τ=0.565 (val F1=0.2414)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49753 | val 1.01757
  Epoch 012 - train 0.42634 | val 0.76325
  Classification -> best τ=0.725 (val F1=0.3501)
  Directional -> Accuracy: 0.4048, MCC: -0.2259, F1: 0.2424

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47839 | val 1.08963
  Epoch 011 - train 0.46221 | val 1.63115
  Classification -> best τ=0.490 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49620 | val 0.97860
  Epoch 012 - train 0.36773 | val 1.40308
  Classification -> best τ=0.295 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53749 | val 1.24376
  Epoch 011 - train 0.48639 | val 1.39622
  Classification -> best τ=0.500 (val F1=0.2267)
  Directional -> Accuracy: 0.5278, MCC: 0.2273, F1: 0.2917

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51298 | val 2.24764
  Epoch 011 - train 0.47649 | val 2.68763
  Classification -> best τ=0.350 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57001 | val 1.13529
  Epoch 012 - train 0.47446 | val 1.36118
  Classification -> best τ=0.175 (val F1=0.3342)
  Directional -> Accuracy: 0.6212, MCC: 0.2658, F1: 0.6269

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56698 | val 2.64736
  Epoch 016 - train 0.19953 | val 6.53842
  Classification -> best τ=0.745 (val F1=0.3828)
  Directional -> Accuracy: 0.4524, MCC: -0.0835, F1: 0.3429

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46967 | val 1.07977
  Epoch 012 - train 0.36856 | val 1.09744
  Classification -> best τ=0.340 (val F1=0.1886)
  Directional -> Accuracy: 0.6429, MCC: 0.3090, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43459 | val 3.08976
  Epoch 011 - train 0.34267 | val 3.70843
  Classification -> best τ=0.545 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50072 | val 2.70633
  Epoch 013 - train 0.42335 | val 2.42820
  Classification -> best τ=0.395 (val F1=0.2111)
  Directional -> Accuracy: 0.3750, MCC: 0.1080, F1: 0.5312

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50726 | val 1.14649
  Epoch 011 - train 0.44897 | val 1.12496
  Classification -> best τ=0.350 (val F1=0.3527)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44405 | val 1.64860
  Epoch 012 - train 0.38363 | val 2.21398
  Classification -> best τ=0.550 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: 0.1059, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48130 | val 1.42831
  Epoch 011 - train 0.47380 | val 1.46276
  Classification -> best τ=0.625 (val F1=0.0602)
  Directional -> Accuracy: 0.4524, MCC: -0.0700, F1: 0.4390

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56078 | val 1.19618
  Epoch 013 - train 0.35683 | val 1.52071
  Classification -> best τ=0.575 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56758 | val 1.48588
  Epoch 011 - train 0.52849 | val 1.76155
  Classification -> best τ=0.630 (val F1=0.2754)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55331 | val 2.75484
  Epoch 011 - train 0.51202 | val 2.80033
  Classification -> best τ=0.855 (val F1=0.3073)
  Directional -> Accuracy: 0.4821, MCC: -0.0069, F1: 0.6420

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66002 | val 0.69377
  Epoch 018 - train 0.46957 | val 1.83936
  Classification -> best τ=0.520 (val F1=0.1893)
  Directional -> Accuracy: 0.6038, MCC: 0.2109, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49658 | val 5.18969
  Epoch 011 - train 0.46982 | val 6.29692
  Classification -> best τ=0.860 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0759, F1: 0.6269

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59557 | val 0.80383

[I 2026-02-20 04:28:53,670] Trial 156 finished with value: 0.25007730694174507 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009928523735495742, 'weight_decay': 2.71917943171785e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.3698530773228933, 'early_stopping_min_delta': 0.009283426460634504}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 014 - train 0.47727 | val 1.10932
  Classification -> best τ=0.515 (val F1=0.2749)
  Directional -> Accuracy: 0.6000, MCC: 0.2045, F1: 0.6129

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25007730694174507
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55148 | val 2.06157
  Epoch 012 - train 0.51033 | val 2.77391
  Classification -> best τ=0.620 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0267, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57389 | val 1.72439
  Epoch 013 - train 0.41963 | val 1.73862
  Classification -> best τ=0.600 (val F1=0.3126)
  Directional -> Accuracy: 0.5111, MCC: 0.0710, F1: 0.4762

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48201 | val 1.25588
  Epoch 011 - train 0.46238 | val 1.81064
  Classification -> best τ=0.505 (val F1=0.0460)
  Directional -> Accuracy: 0.4130, MCC: -0.1709, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56479 | val 1.92324
  Epoch 011 - train 0.52905 | val 2.87051
  Classification -> best τ=0.485 (val F1=0.1716)
  Directional -> Accuracy: 0.5676, MCC: 0.1426, F1: 0.5676

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46354 | val 0.82515
  Epoch 011 - train 0.42314 | val 0.78879
  Classification -> best τ=0.585 (val F1=0.4493)
  Directional -> Accuracy: 0.4800, MCC: -0.0355, F1: 0.4583

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41322 | val 1.69998
  Epoch 011 - train 0.45045 | val 1.10798
  Classification -> best τ=0.625 (val F1=0.1537)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.1667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55208 | val 1.90677
  Epoch 011 - train 0.53892 | val 1.56003
  Classification -> best τ=0.570 (val F1=0.2102)
  Directional -> Accuracy: 0.5588, MCC: 0.0032, F1: 0.2857

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53523 | val 0.71668
  Epoch 015 - train 0.36056 | val 0.91512
  Classification -> best τ=0.385 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0807, F1: 0.3571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55084 | val 1.31255
  Epoch 013 - train 0.45814 | val 1.89859
  Classification -> best τ=0.805 (val F1=0.2764)
  Directional -> Accuracy: 0.6667, MCC: 0.3130, F1: 0.5294

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51116 | val 0.68968
  Epoch 011 - train 0.46509 | val 0.82897
  Classification -> best τ=0.415 (val F1=0.2776)
  Directional -> Accuracy: 0.4203, MCC: -0.0815, F1: 0.5238

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53097 | val 0.70228
  Epoch 014 - train 0.43221 | val 0.93117
  Classification -> best τ=0.390 (val F1=0.3961)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43812 | val 3.38580
  Epoch 011 - train 0.40906 | val 2.76247
  Classification -> best τ=0.500 (val F1=0.2083)
  Directional -> Accuracy: 0.5614, MCC: 0.1631, F1: 0.3902

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42170 | val 1.08996
  Epoch 011 - train 0.37380 | val 1.10369
  Classification -> best τ=0.555 (val F1=0.2083)
  Directional -> Accuracy: 0.5476, MCC: 0.0751, F1: 0.4571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65063 | val 0.62203
  Epoch 019 - train 0.45477 | val 0.81529
  Classification -> best τ=0.305 (val F1=0.3994)
  Directional -> Accuracy: 0.5833, MCC: 0.1714, F1: 0.6269

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48503 | val 2.00766
  Epoch 011 - train 0.47518 | val 3.59611
  Classification -> best τ=0.615 (val F1=0.3705)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55331 | val 1.01502
  Epoch 012 - train 0.48357 | val 1.16719
  Classification -> best τ=0.650 (val F1=0.4038)
  Directional -> Accuracy: 0.6522, MCC: 0.2964, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49855 | val 1.06414
  Epoch 019 - train 0.32845 | val 1.65306
  Classification -> best τ=0.730 (val F1=0.1291)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60047 | val 1.73257
  Epoch 013 - train 0.47991 | val 3.07829
  Classification -> best τ=0.445 (val F1=0.2673)
  Directional -> Accuracy: 0.5200, MCC: 0.1455, F1: 0.4545

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60092 | val 1.27432
  Epoch 016 - train 0.44249 | val 1.29432
  Classification -> best τ=0.160 (val F1=0.2522)
  Directional -> Accuracy: 0.4531, MCC: 0.0051, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45045 | val 2.57969
  Epoch 011 - train 0.43815 | val 2.51807
  Classification -> best τ=0.760 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48708 | val 0.70845
  Epoch 020 - train 0.19794 | val 0.85574
  Classification -> best τ=0.510 (val F1=0.4104)
  Directional -> Accuracy: 0.4255, MCC: -0.2030, F1: 0.5263

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51744 | val 3.67615
  Epoch 011 - train 0.51699 | val 3.35155
  Classification -> best τ=0.370 (val F1=0.1650)
  Directional -> Accuracy: 0.5692, MCC: 0.1460, F1: 0.5172

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62639 | val 0.97252
  Epoch 011 - train 0.57375 | val 1.16457
  Classification -> best τ=0.445 (val F1=0.2027)
  Directional -> Accuracy: 0.5439, MCC: 0.0157, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52429 | val 6.11142
  Epoch 011 - train 0.49017 | val 4.89793
  Classification -> best τ=0.525 (val F1=0.1122)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50196 | val 1.57086
  Epoch 011 - train 0.47683 | val 1.85795
  Classification -> best τ=0.880 (val F1=0.3858)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.36772 | val 4.36076
  Epoch 012 - train 0.37351 | val 5.76242
  Classification -> best τ=0.590 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: -0.0481, F1: 0.0909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61927 | val 1.37168
  Epoch 015 - train 0.51098 | val 1.03824
  Classification -> best τ=0.745 (val F1=0.1171)
  Directional -> Accuracy: 0.3571, MCC: -0.2501, F1: 0.2286

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54368 | val 0.95771
  Epoch 011 - train 0.53055 | val 0.95574
  Classification -> best τ=0.740 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53254 | val 1.01698
  Epoch 014 - train 0.36479 | val 1.96578
  Classification -> best τ=0.690 (val F1=0.1748)
  Directional -> Accuracy: 0.6000, MCC: 0.1846, F1: 0.6522

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44432 | val 1.37074
  Epoch 011 - train 0.39409 | val 1.79030
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57888 | val 1.93822
  Epoch 012 - train 0.51572 | val 2.12849
  Classification -> best τ=0.330 (val F1=0.2357)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.6875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50016 | val 0.98989
  Epoch 011 - train 0.41886 | val 1.23591
  Classification -> best τ=0.545 (val F1=0.2406)
  Directional -> Accuracy: 0.4490, MCC: -0.1155, F1: 0.5091

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67515 | val 0.69790
  Epoch 018 - train 0.48511 | val 1.76422
  Classification -> best τ=0.455 (val F1=0.4730)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47270 | val 3.18696
  Epoch 011 - train 0.43560 | val 3.20439
  Classification -> best τ=0.575 (val F1=0.0908)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54843 | val 1.11550
  Epoch 011 - train 0.53450 | val 1.09021
  Classification -> best τ=0.365 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46433 | val 1.39632
  Epoch 013 - train 0.26548 | val 2.12316
  Classification -> best τ=0.375 (val F1=0.3001)
  Directional -> Accuracy: 0.5952, MCC: 0.1850, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57084 | val 0.87439
  Epoch 012 - train 0.52160 | val 1.13437
  Classification -> best τ=0.415 (val F1=0.2868)
  Directional -> Accuracy: 0.5179, MCC: 0.0283, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52603 | val 1.09871
  Epoch 015 - train 0.34298 | val 1.52365
  Classification -> best τ=0.490 (val F1=0.2975)
  Directional -> Accuracy: 0.6087, MCC: 0.2132, F1: 0.6538

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56335 | val 1.34616
  Epoch 018 - train 0.43905 | val 0.76695
  Classification -> best τ=0.495 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52930 | val 1.48857
  Epoch 014 - train 0.37734 | val 1.22215
  Classification -> best τ=0.295 (val F1=0.3653)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43016 | val 0.99564
  Epoch 012 - train 0.44993 | val 1.24354
  Classification -> best τ=0.610 (val F1=0.5500)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48071 | val 1.20337
  Epoch 011 - train 0.42401 | val 1.48306
  Classification -> best τ=0.580 (val F1=0.2722)
  Directional -> Accuracy: 0.6190, MCC: 0.1936, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45082 | val 0.62698
  Epoch 020 - train 0.22507 | val 0.87874
  Classification -> best τ=0.810 (val F1=0.2902)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50727 | val 4.27212
  Epoch 011 - train 0.53314 | val 4.10336
  Classification -> best τ=0.385 (val F1=0.2292)
  Directional -> Accuracy: 0.4909, MCC: -0.2193, F1: 0.6585

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45689 | val 2.39386
  Epoch 011 - train 0.41776 | val 2.32419
  Classification -> best τ=0.850 (val F1=0.2680)
  Directional -> Accuracy: 0.4821, MCC: -0.0519, F1: 0.3556

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52108 | val 0.85588
  Epoch 011 - train 0.56660 | val 1.15037
  Classification -> best τ=0.495 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60513 | val 2.01192
  Epoch 013 - train 0.52462 | val 2.54799
  Classification -> best τ=0.820 (val F1=0.1763)
  Directional -> Accuracy: 0.4545, MCC: -0.1437, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53458 | val 1.47908
  Epoch 011 - train 0.55104 | val 1.43823

[I 2026-02-20 04:30:35,924] Trial 157 finished with value: 0.26780648794893386 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.007495016979017746, 'weight_decay': 8.365524993390265e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.1777831786884629, 'early_stopping_min_delta': 0.009191794513428971}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.580 (val F1=0.2691)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26780648794893386
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57402 | val 1.10491
  Epoch 012 - train 0.51932 | val 1.23852
  Classification -> best τ=0.690 (val F1=0.1135)
  Directional -> Accuracy: 0.5844, MCC: 0.1619, F1: 0.5429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54621 | val 0.71468
  Epoch 012 - train 0.45519 | val 0.79943
  Classification -> best τ=0.325 (val F1=0.2431)
  Directional -> Accuracy: 0.6304, MCC: 0.3012, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57606 | val 0.81457
  Epoch 017 - train 0.39329 | val 1.32727
  Classification -> best τ=0.860 (val F1=0.4419)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66612 | val 0.85195
  Epoch 016 - train 0.50468 | val 4.53045
  Classification -> best τ=0.440 (val F1=0.2474)
  Directional -> Accuracy: 0.4667, MCC: 0.0286, F1: 0.1304

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41884 | val 7.08230
  Epoch 011 - train 0.37774 | val 6.63407
  Classification -> best τ=0.460 (val F1=0.3369)
  Directional -> Accuracy: 0.5490, MCC: 0.1688, F1: 0.3784

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36867 | val 2.45228
  Epoch 011 - train 0.32927 | val 3.10684
  Classification -> best τ=0.565 (val F1=0.2887)
  Directional -> Accuracy: 0.5319, MCC: 0.0764, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59841 | val 0.92267
  Epoch 011 - train 0.58497 | val 0.85108
  Classification -> best τ=0.715 (val F1=0.2872)
  Directional -> Accuracy: 0.5652, MCC: -0.0455, F1: 0.1176

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43783 | val 6.97196
  Epoch 011 - train 0.39513 | val 7.75552
  Classification -> best τ=0.470 (val F1=0.1752)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57402 | val 2.72825
  Epoch 013 - train 0.47505 | val 3.67096
  Classification -> best τ=0.330 (val F1=0.3539)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54035 | val 0.75666
  Epoch 011 - train 0.55780 | val 0.72438
  Classification -> best τ=0.340 (val F1=0.2576)
  Directional -> Accuracy: 0.4429, MCC: -0.0227, F1: 0.5618

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62342 | val 1.46453
  Epoch 013 - train 0.46180 | val 2.51174
  Classification -> best τ=0.610 (val F1=0.1750)
  Directional -> Accuracy: 0.4600, MCC: -0.0655, F1: 0.4906

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49056 | val 1.87051
  Epoch 011 - train 0.48502 | val 2.10466
  Classification -> best τ=0.360 (val F1=0.1955)
  Directional -> Accuracy: 0.5345, MCC: 0.0806, F1: 0.6301

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44650 | val 1.20893
  Epoch 012 - train 0.37004 | val 1.51494
  Classification -> best τ=0.405 (val F1=0.1291)
  Directional -> Accuracy: 0.5116, MCC: -0.0186, F1: 0.3636

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55037 | val 0.80696
  Epoch 011 - train 0.52750 | val 0.77444
  Classification -> best τ=0.235 (val F1=0.2987)
  Directional -> Accuracy: 0.5410, MCC: 0.0958, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65884 | val 1.13953
  Epoch 012 - train 0.60367 | val 1.05808
  Classification -> best τ=0.460 (val F1=0.1212)
  Directional -> Accuracy: 0.6346, MCC: 0.2629, F1: 0.5957

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45818 | val 1.56936
  Epoch 011 - train 0.48705 | val 1.48145
  Classification -> best τ=0.795 (val F1=0.2637)
  Directional -> Accuracy: 0.4714, MCC: 0.0023, F1: 0.2449

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59048 | val 1.36753
  Epoch 014 - train 0.45359 | val 2.31252
  Classification -> best τ=0.770 (val F1=0.0754)
  Directional -> Accuracy: 0.4237, MCC: -0.0129, F1: 0.3200

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55206 | val 0.81607
  Epoch 011 - train 0.49879 | val 0.81872
  Classification -> best τ=0.470 (val F1=0.1764)
  Directional -> Accuracy: 0.5000, MCC: 0.2770, F1: 0.2963

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64680 | val 0.91231
  Epoch 014 - train 0.49985 | val 0.86152
  Classification -> best τ=0.260 (val F1=0.2117)
  Directional -> Accuracy: 0.5385, MCC: 0.2138, F1: 0.4231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51370 | val 0.93541
  Epoch 011 - train 0.52592 | val 0.88786
  Classification -> best τ=0.620 (val F1=0.2669)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44889 | val 4.66995
  Epoch 011 - train 0.38935 | val 5.87338
  Classification -> best τ=0.760 (val F1=0.2000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53153 | val 1.61426
  Epoch 011 - train 0.55497 | val 1.62152
  Classification -> best τ=0.335 (val F1=0.1664)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60128 | val 1.39545
  Epoch 011 - train 0.55587 | val 1.45507
  Classification -> best τ=0.740 (val F1=0.2629)
  Directional -> Accuracy: 0.4483, MCC: 0.0461, F1: 0.1111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58906 | val 0.89329
  Epoch 012 - train 0.54674 | val 1.30396
  Classification -> best τ=0.430 (val F1=0.1167)
  Directional -> Accuracy: 0.5152, MCC: 0.1086, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57847 | val 1.03669
  Epoch 014 - train 0.40302 | val 1.43022
  Classification -> best τ=0.405 (val F1=0.5049)
  Directional -> Accuracy: 0.5714, MCC: 0.1762, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41270 | val 1.53650
  Epoch 011 - train 0.39564 | val 1.45896
  Classification -> best τ=0.560 (val F1=0.2474)
  Directional -> Accuracy: 0.5217, MCC: -0.1870, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53735 | val 2.01378
  Epoch 011 - train 0.50262 | val 2.72867
  Classification -> best τ=0.530 (val F1=0.0364)
  Directional -> Accuracy: 0.5349, MCC: -0.1095, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55268 | val 1.41723
  Epoch 015 - train 0.45809 | val 1.10528
  Classification -> best τ=0.435 (val F1=0.3850)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59227 | val 0.81319
  Epoch 015 - train 0.54094 | val 0.72478
  Classification -> best τ=0.520 (val F1=0.3844)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40034 | val 7.86018
  Epoch 011 - train 0.34304 | val 8.90483
  Classification -> best τ=0.675 (val F1=0.1288)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59640 | val 0.73975
  Epoch 016 - train 0.52145 | val 1.14407
  Classification -> best τ=0.735 (val F1=0.1846)
  Directional -> Accuracy: 0.5349, MCC: 0.2554, F1: 0.2308

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47268 | val 1.88307
  Epoch 011 - train 0.41302 | val 1.73444
  Classification -> best τ=0.280 (val F1=0.3752)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52743 | val 1.03606
  Epoch 011 - train 0.48457 | val 1.56645
  Classification -> best τ=0.570 (val F1=0.1681)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47178 | val 0.75987
  Epoch 020 - train 0.38623 | val 0.82875
  Classification -> best τ=0.425 (val F1=0.3651)
  Directional -> Accuracy: 0.5789, MCC: 0.2928, F1: 0.7037

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56930 | val 1.09571
  Epoch 012 - train 0.50890 | val 1.50136
  Classification -> best τ=0.485 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65162 | val 0.84142
  Epoch 014 - train 0.54476 | val 0.95245
  Classification -> best τ=0.365 (val F1=0.2425)
  Directional -> Accuracy: 0.5224, MCC: 0.0684, F1: 0.5152

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62308 | val 1.32126
  Epoch 014 - train 0.43728 | val 1.61618
  Classification -> best τ=0.425 (val F1=0.2986)
  Directional -> Accuracy: 0.6744, MCC: 0.4004, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56548 | val 0.95726
  Epoch 012 - train 0.49572 | val 0.79021
  Classification -> best τ=0.210 (val F1=0.2925)
  Directional -> Accuracy: 0.5439, MCC: 0.1810, F1: 0.6579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50306 | val 1.16568
  Epoch 012 - train 0.44074 | val 1.59169
  Classification -> best τ=0.420 (val F1=0.2676)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52031 | val 0.94245
  Epoch 012 - train 0.45638 | val 0.72803
  Classification -> best τ=0.425 (val F1=0.2759)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43146 | val 1.78597
  Epoch 011 - train 0.43471 | val 2.15867
  Classification -> best τ=0.565 (val F1=0.2145)
  Directional -> Accuracy: 0.6053, MCC: 0.2806, F1: 0.4828

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55279 | val 2.23183
  Epoch 013 - train 0.43279 | val 3.06264
  Classification -> best τ=0.165 (val F1=0.2774)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54630 | val 1.39365
  Epoch 013 - train 0.41598 | val 1.11501
  Classification -> best τ=0.435 (val F1=0.2593)
  Directional -> Accuracy: 0.4681, MCC: -0.0607, F1: 0.3243

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53901 | val 1.54582
  Epoch 014 - train 0.39527 | val 1.85817
  Classification -> best τ=0.520 (val F1=0.2749)
  Directional -> Accuracy: 0.5909, MCC: 0.1474, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45595 | val 2.60873
  Epoch 011 - train 0.37505 | val 4.29335
  Classification -> best τ=0.590 (val F1=0.1890)
  Directional -> Accuracy: 0.4286, MCC: 0.0843, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60688 | val 2.33733
  Epoch 013 - train 0.45865 | val 3.19942
  Classification -> best τ=0.520 (val F1=0.2985)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49050 | val 1.29713
  Epoch 011 - train 0.45375 | val 1.58686
  Classification -> best τ=0.650 (val F1=0.3359)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64851 | val 0.85978
  Epoch 017 - train 0.44449 | val 1.06074
  Classification -> best τ=0.455 (val F1=0.2004)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55288 | val 1.38687
  Epoch 013 - train 0.48791 | val 1.27059
  Classification -> best τ=0.490 (val F1=0.2708)
  Directional -> Accuracy: 0.4107, MCC: -0.2435, F1: 0.0571

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67231 | val 1.19854
  Epoch 011 - train 0.62161 | val 1.10876

[I 2026-02-20 04:32:03,649] Trial 158 finished with value: 0.25017997658769126 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.006641013487268093, 'weight_decay': 6.996853435911234e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.43780987073555366, 'early_stopping_min_delta': 0.009447463505323132}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.420 (val F1=0.3901)
  Directional -> Accuracy: 0.5738, MCC: 0.1404, F1: 0.4348

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25017997658769126
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60446 | val 0.71641
  Epoch 011 - train 0.55970 | val 0.90274
  Classification -> best τ=0.650 (val F1=0.2510)
  Directional -> Accuracy: 0.5132, MCC: -0.1320, F1: 0.0513

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57224 | val 3.15391
  Epoch 014 - train 0.33522 | val 2.56032
  Classification -> best τ=0.375 (val F1=0.2285)
  Directional -> Accuracy: 0.6222, MCC: 0.2030, F1: 0.7018

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55373 | val 1.13495
  Epoch 014 - train 0.38022 | val 1.76571
  Classification -> best τ=0.765 (val F1=0.3237)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51001 | val 4.22950
  Epoch 011 - train 0.49999 | val 4.19780
  Classification -> best τ=0.310 (val F1=0.2593)
  Directional -> Accuracy: 0.5270, MCC: 0.0683, F1: 0.5070

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48922 | val 0.80918
  Epoch 013 - train 0.37480 | val 1.02233
  Classification -> best τ=0.700 (val F1=0.4247)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43640 | val 0.84292
  Epoch 017 - train 0.32228 | val 2.18613
  Classification -> best τ=0.685 (val F1=0.2204)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.1667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52842 | val 3.01781
  Epoch 011 - train 0.52068 | val 2.29543
  Classification -> best τ=0.485 (val F1=0.1599)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59700 | val 1.49773
  Epoch 013 - train 0.41331 | val 3.00014
  Classification -> best τ=0.405 (val F1=0.1657)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.2609

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46020 | val 4.04479
  Epoch 011 - train 0.46091 | val 3.90001
  Classification -> best τ=0.345 (val F1=0.1517)
  Directional -> Accuracy: 0.6458, MCC: 0.2940, F1: 0.6222

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57501 | val 1.12363
  Epoch 011 - train 0.55283 | val 1.48145
  Classification -> best τ=0.535 (val F1=0.1440)
  Directional -> Accuracy: 0.5217, MCC: 0.0511, F1: 0.4923

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62386 | val 0.65507
  Epoch 020 - train 0.39978 | val 0.93823
  Classification -> best τ=0.455 (val F1=0.3231)
  Directional -> Accuracy: 0.5918, MCC: 0.1589, F1: 0.4737

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50218 | val 1.82286
  Epoch 012 - train 0.38810 | val 2.67585
  Classification -> best τ=0.775 (val F1=0.1181)
  Directional -> Accuracy: 0.4737, MCC: -0.0827, F1: 0.0625

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49693 | val 1.74406
  Epoch 011 - train 0.46488 | val 2.73158
  Classification -> best τ=0.650 (val F1=0.3172)
  Directional -> Accuracy: 0.4762, MCC: -0.0478, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58366 | val 1.22977
  Epoch 013 - train 0.46063 | val 1.26042
  Classification -> best τ=0.405 (val F1=0.3833)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6512

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51370 | val 2.06698
  Epoch 012 - train 0.48076 | val 3.44607
  Classification -> best τ=0.605 (val F1=0.1519)
  Directional -> Accuracy: 0.4902, MCC: 0.0277, F1: 0.5667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65018 | val 0.72512
  Epoch 011 - train 0.67731 | val 0.74139
  Classification -> best τ=0.690 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48988 | val 3.28520
  Epoch 011 - train 0.46079 | val 3.48290
  Classification -> best τ=0.335 (val F1=0.2429)
  Directional -> Accuracy: 0.5000, MCC: -0.0526, F1: 0.5915

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49674 | val 2.67675
  Epoch 011 - train 0.45660 | val 2.04798
  Classification -> best τ=0.580 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57963 | val 1.21945
  Epoch 012 - train 0.48812 | val 1.45374
  Classification -> best τ=0.330 (val F1=0.3099)
  Directional -> Accuracy: 0.5469, MCC: -0.0577, F1: 0.6947

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54277 | val 0.93877
  Epoch 020 - train 0.31921 | val 1.64651
  Classification -> best τ=0.880 (val F1=0.4089)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56379 | val 2.84005
  Epoch 014 - train 0.35241 | val 2.29751
  Classification -> best τ=0.330 (val F1=0.3678)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55580 | val 1.53200
  Epoch 011 - train 0.51007 | val 1.15033
  Classification -> best τ=0.540 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51962 | val 2.80124
  Epoch 011 - train 0.57697 | val 2.79194
  Classification -> best τ=0.655 (val F1=0.4222)
  Directional -> Accuracy: 0.4211, MCC: -0.1083, F1: 0.0571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53881 | val 1.96658
  Epoch 012 - train 0.47427 | val 3.37051
  Classification -> best τ=0.425 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48937 | val 3.02651
  Epoch 011 - train 0.42522 | val 3.55135
  Classification -> best τ=0.610 (val F1=0.2852)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35076 | val 4.89026
  Epoch 012 - train 0.26512 | val 5.53902
  Classification -> best τ=0.710 (val F1=0.2621)
  Directional -> Accuracy: 0.5333, MCC: 0.1478, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50024 | val 0.99841
  Epoch 011 - train 0.43083 | val 0.82840
  Classification -> best τ=0.680 (val F1=0.0446)
  Directional -> Accuracy: 0.5476, MCC: 0.0962, F1: 0.5778

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55917 | val 1.49209
  Epoch 012 - train 0.46116 | val 1.78893
  Classification -> best τ=0.435 (val F1=0.3039)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50166 | val 0.81385
  Epoch 015 - train 0.25627 | val 0.76155
  Classification -> best τ=0.445 (val F1=0.4139)
  Directional -> Accuracy: 0.5250, MCC: -0.0198, F1: 0.6545

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46185 | val 0.67040
  Epoch 014 - train 0.43340 | val 1.02724
  Classification -> best τ=0.375 (val F1=0.3823)
  Directional -> Accuracy: 0.4286, MCC: -0.1779, F1: 0.5862

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49344 | val 1.25422
  Epoch 015 - train 0.32811 | val 0.74977
  Classification -> best τ=0.720 (val F1=0.2066)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43521 | val 0.96820
  Epoch 012 - train 0.39177 | val 1.09966
  Classification -> best τ=0.520 (val F1=0.4158)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62556 | val 1.26442
  Epoch 015 - train 0.47156 | val 1.18360
  Classification -> best τ=0.390 (val F1=0.3131)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59219 | val 1.82129
  Epoch 011 - train 0.55119 | val 1.98831
  Classification -> best τ=0.250 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66004 | val 0.72598
  Epoch 015 - train 0.52396 | val 0.84411
  Classification -> best τ=0.110 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.1011, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48117 | val 0.79539
  Epoch 013 - train 0.32014 | val 1.05993
  Classification -> best τ=0.695 (val F1=0.2665)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56974 | val 0.98290
  Epoch 014 - train 0.42969 | val 1.00792
  Classification -> best τ=0.255 (val F1=0.3873)
  Directional -> Accuracy: 0.5714, MCC: 0.1550, F1: 0.5862

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37917 | val 1.62019
  Epoch 011 - train 0.34483 | val 1.27535
  Classification -> best τ=0.395 (val F1=0.4920)
  Directional -> Accuracy: 0.5870, MCC: 0.1244, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38877 | val 1.33502
  Epoch 014 - train 0.25365 | val 0.89708
  Classification -> best τ=0.425 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57901 | val 1.52288
  Epoch 015 - train 0.39644 | val 1.86733
  Classification -> best τ=0.485 (val F1=0.3523)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50664 | val 1.72963
  Epoch 014 - train 0.28551 | val 3.58282
  Classification -> best τ=0.580 (val F1=0.1890)
  Directional -> Accuracy: 0.5111, MCC: 0.0391, F1: 0.3529

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46601 | val 1.11416
  Epoch 011 - train 0.46183 | val 1.22738
  Classification -> best τ=0.445 (val F1=0.3333)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.6316

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44461 | val 1.11151
  Epoch 011 - train 0.41585 | val 1.10750
  Classification -> best τ=0.560 (val F1=0.4542)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.53292 | val 3.71629
  Epoch 011 - train 0.48958 | val 3.28070
  Classification -> best τ=0.605 (val F1=0.1769)
  Directional -> Accuracy: 0.5091, MCC: 0.0199, F1: 0.5263

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48489 | val 2.14454
  Epoch 011 - train 0.45786 | val 3.00631
  Classification -> best τ=0.420 (val F1=0.2308)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62864 | val 0.77824
  Epoch 014 - train 0.45744 | val 1.02837
  Classification -> best τ=0.800 (val F1=0.1668)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43401 | val 1.37957
  Epoch 011 - train 0.40155 | val 2.36928
  Classification -> best τ=0.620 (val F1=0.1352)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44761 | val 2.03148
  Epoch 011 - train 0.47140 | val 2.07352

[I 2026-02-20 04:33:37,425] Trial 159 finished with value: 0.27437489727679726 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00854232292338579, 'weight_decay': 5.903877833353003e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.260490239721801, 'early_stopping_min_delta': 0.009752307101532786}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.495 (val F1=0.2691)
  Directional -> Accuracy: 0.5833, MCC: 0.1710, F1: 0.4444

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27437489727679726
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59957 | val 1.59778
  Epoch 012 - train 0.56860 | val 1.93025
  Classification -> best τ=0.550 (val F1=0.2453)
  Directional -> Accuracy: 0.5455, MCC: 0.0504, F1: 0.3396

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54649 | val 1.18716
  Epoch 011 - train 0.55846 | val 1.29482
  Classification -> best τ=0.485 (val F1=0.1164)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60972 | val 1.11125
  Epoch 011 - train 0.56653 | val 1.13179
  Classification -> best τ=0.505 (val F1=0.3171)
  Directional -> Accuracy: 0.5745, MCC: 0.1413, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58046 | val 1.26971
  Epoch 011 - train 0.60218 | val 1.67073
  Classification -> best τ=0.485 (val F1=0.1210)
  Directional -> Accuracy: 0.5733, MCC: 0.1277, F1: 0.6364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50803 | val 1.12132
  Epoch 012 - train 0.48322 | val 1.19873
  Classification -> best τ=0.455 (val F1=0.4063)
  Directional -> Accuracy: 0.7255, MCC: 0.4957, F1: 0.7879

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48343 | val 2.56074
  Epoch 011 - train 0.51063 | val 2.83976
  Classification -> best τ=0.500 (val F1=0.2582)
  Directional -> Accuracy: 0.5745, MCC: 0.1882, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60038 | val 0.97849
  Epoch 011 - train 0.58737 | val 1.06370
  Classification -> best τ=0.485 (val F1=0.2656)
  Directional -> Accuracy: 0.5507, MCC: 0.1554, F1: 0.5634

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58628 | val 2.20217
  Epoch 011 - train 0.48678 | val 2.31323
  Classification -> best τ=0.490 (val F1=0.1502)
  Directional -> Accuracy: 0.6364, MCC: 0.2070, F1: 0.3846

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52985 | val 0.86735
  Epoch 014 - train 0.54312 | val 0.94782
  Classification -> best τ=0.560 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51357 | val 0.79452
  Epoch 011 - train 0.54887 | val 0.77347
  Classification -> best τ=0.490 (val F1=0.1816)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52032 | val 2.73648
  Epoch 011 - train 0.51989 | val 2.93964
  Classification -> best τ=0.530 (val F1=0.1802)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56431 | val 2.70246
  Epoch 011 - train 0.53377 | val 2.83034
  Classification -> best τ=0.520 (val F1=0.1578)
  Directional -> Accuracy: 0.6207, MCC: 0.3079, F1: 0.7105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52284 | val 2.75454
  Epoch 011 - train 0.52966 | val 2.81913
  Classification -> best τ=0.475 (val F1=0.1291)
  Directional -> Accuracy: 0.5116, MCC: -0.0880, F1: 0.1600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61548 | val 0.66694
  Epoch 014 - train 0.53043 | val 0.66587
  Classification -> best τ=0.315 (val F1=0.3134)
  Directional -> Accuracy: 0.5574, MCC: 0.1602, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53419 | val 0.92480
  Epoch 011 - train 0.54378 | val 1.24571
  Classification -> best τ=0.550 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55216 | val 1.32358
  Epoch 011 - train 0.55672 | val 1.31199
  Classification -> best τ=0.505 (val F1=0.2172)
  Directional -> Accuracy: 0.5571, MCC: 0.0795, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58804 | val 2.51938
  Epoch 011 - train 0.57414 | val 2.79261
  Classification -> best τ=0.510 (val F1=0.1789)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58055 | val 2.62901
  Epoch 011 - train 0.57766 | val 2.63338
  Classification -> best τ=0.505 (val F1=0.1846)
  Directional -> Accuracy: 0.4079, MCC: -0.1030, F1: 0.3284

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56766 | val 1.02056
  Epoch 011 - train 0.57918 | val 1.06909
  Classification -> best τ=0.515 (val F1=0.2357)
  Directional -> Accuracy: 0.5077, MCC: 0.0510, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55896 | val 0.78100
  Epoch 015 - train 0.49890 | val 1.01502
  Classification -> best τ=0.385 (val F1=0.3629)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54709 | val 1.52798
  Epoch 011 - train 0.53286 | val 1.63697
  Classification -> best τ=0.455 (val F1=0.2046)
  Directional -> Accuracy: 0.5208, MCC: 0.2619, F1: 0.4103

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57250 | val 1.17924
  Epoch 011 - train 0.54758 | val 1.30011
  Classification -> best τ=0.465 (val F1=0.1782)
  Directional -> Accuracy: 0.5606, MCC: 0.1361, F1: 0.4314

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62462 | val 1.17974
  Epoch 011 - train 0.58269 | val 1.22739
  Classification -> best τ=0.560 (val F1=0.1669)
  Directional -> Accuracy: 0.5000, MCC: 0.1208, F1: 0.3256

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57923 | val 1.22362
  Epoch 011 - train 0.56855 | val 1.36391
  Classification -> best τ=0.500 (val F1=0.2284)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57063 | val 0.69337
  Epoch 015 - train 0.52045 | val 0.75203
  Classification -> best τ=0.665 (val F1=0.5049)
  Directional -> Accuracy: 0.4643, MCC: 0.0541, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52121 | val 1.15520
  Epoch 011 - train 0.52514 | val 1.25810
  Classification -> best τ=0.520 (val F1=0.0731)
  Directional -> Accuracy: 0.4565, MCC: -0.2115, F1: 0.1379

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60145 | val 2.52295
  Epoch 011 - train 0.60369 | val 2.76587
  Classification -> best τ=0.455 (val F1=0.0295)
  Directional -> Accuracy: 0.4651, MCC: 0.1874, F1: 0.1481

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57280 | val 0.99666
  Epoch 011 - train 0.61049 | val 1.04242
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60380 | val 0.67911
  Epoch 017 - train 0.57578 | val 1.00899
  Classification -> best τ=0.530 (val F1=0.3844)
  Directional -> Accuracy: 0.5854, MCC: 0.1890, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53962 | val 0.91050
  Epoch 011 - train 0.55584 | val 0.91519
  Classification -> best τ=0.520 (val F1=0.2683)
  Directional -> Accuracy: 0.5581, MCC: 0.1676, F1: 0.2400

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55682 | val 1.11419
  Epoch 015 - train 0.53833 | val 1.14274
  Classification -> best τ=0.505 (val F1=0.0720)
  Directional -> Accuracy: 0.5349, MCC: 0.0282, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56793 | val 1.29675
  Epoch 011 - train 0.54334 | val 1.36168
  Classification -> best τ=0.465 (val F1=0.1952)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55633 | val 0.84548
  Epoch 013 - train 0.52021 | val 0.95187
  Classification -> best τ=0.390 (val F1=0.3773)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.55524 | val 1.24379
  Epoch 011 - train 0.58094 | val 1.46593
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58731 | val 0.88022
  Epoch 011 - train 0.56391 | val 0.83718
  Classification -> best τ=0.520 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55944 | val 0.70391
  Epoch 013 - train 0.50882 | val 0.71970
  Classification -> best τ=0.450 (val F1=0.3404)
  Directional -> Accuracy: 0.5075, MCC: -0.0785, F1: 0.6374

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56781 | val 0.84571
  Epoch 011 - train 0.55879 | val 0.84302
  Classification -> best τ=0.495 (val F1=0.1482)
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54020 | val 1.08314
  Epoch 013 - train 0.48263 | val 1.14195
  Classification -> best τ=0.390 (val F1=0.2984)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51770 | val 1.81046
  Epoch 011 - train 0.50544 | val 1.84509
  Classification -> best τ=0.515 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57410 | val 0.78136
  Epoch 016 - train 0.55398 | val 0.91682
  Classification -> best τ=0.520 (val F1=0.4345)
  Directional -> Accuracy: 0.5714, MCC: 0.0672, F1: 0.4000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56826 | val 1.01282
  Epoch 011 - train 0.52966 | val 1.08361
  Classification -> best τ=0.530 (val F1=0.3125)
  Directional -> Accuracy: 0.4211, MCC: -0.1492, F1: 0.3125

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53804 | val 1.65798
  Epoch 012 - train 0.52130 | val 1.70018
  Classification -> best τ=0.395 (val F1=0.2814)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55704 | val 0.71932
  Epoch 014 - train 0.55167 | val 0.80320
  Classification -> best τ=0.470 (val F1=0.3301)
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52845 | val 1.03225
  Epoch 011 - train 0.58104 | val 1.09095
  Classification -> best τ=0.480 (val F1=0.0315)
  Directional -> Accuracy: 0.5682, MCC: 0.1257, F1: 0.6122

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60391 | val 0.79930
  Epoch 011 - train 0.57692 | val 0.80115
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59916 | val 1.42834
  Epoch 013 - train 0.55427 | val 1.41514
  Classification -> best τ=0.740 (val F1=0.1548)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55007 | val 1.29320
  Epoch 011 - train 0.54695 | val 1.21669
  Classification -> best τ=0.550 (val F1=0.3836)
  Directional -> Accuracy: 0.5614, MCC: 0.1418, F1: 0.6032

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57449 | val 1.23501
  Epoch 011 - train 0.58737 | val 1.26575
  Classification -> best τ=0.530 (val F1=0.1280)
  Directional -> Accuracy: 0.4444, MCC: -0.1472, F1: 0.5588

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55663 | val 0.80083
  Epoch 011 - train 0.51991 | val 0.80267
  Classification -> best τ=0.505 (val F1=0.1794)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58978 | val 0.68559

[I 2026-02-20 04:35:09,789] Trial 160 finished with value: 0.21884635565221452 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0006322206369914587, 'weight_decay': 1.035838876500543e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6038167598100047, 'early_stopping_min_delta': 0.007861378419264832}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 018 - train 0.52082 | val 1.12105
  Classification -> best τ=0.385 (val F1=0.2612)
  Directional -> Accuracy: 0.3934, MCC: -0.2084, F1: 0.4638

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21884635565221452
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58482 | val 1.18629
  Epoch 014 - train 0.43064 | val 1.38110
  Classification -> best τ=0.620 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0409, F1: 0.3860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40313 | val 1.78127
  Epoch 011 - train 0.38990 | val 1.45064
  Classification -> best τ=0.525 (val F1=0.1941)
  Directional -> Accuracy: 0.6000, MCC: 0.1802, F1: 0.6538

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55569 | val 0.79848
  Epoch 012 - train 0.48637 | val 0.73990
  Classification -> best τ=0.530 (val F1=0.3237)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51808 | val 2.14151
  Epoch 011 - train 0.49947 | val 1.54237
  Classification -> best τ=0.230 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53364 | val 1.86721
  Epoch 013 - train 0.39183 | val 3.49539
  Classification -> best τ=0.580 (val F1=0.4556)
  Directional -> Accuracy: 0.6600, MCC: 0.3669, F1: 0.5854

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37914 | val 0.91452
  Epoch 011 - train 0.32705 | val 1.00090
  Classification -> best τ=0.585 (val F1=0.2701)
  Directional -> Accuracy: 0.6087, MCC: 0.2496, F1: 0.4000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54571 | val 1.42569
  Epoch 011 - train 0.50914 | val 0.94748
  Classification -> best τ=0.430 (val F1=0.1640)
  Directional -> Accuracy: 0.4265, MCC: -0.0328, F1: 0.5185

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44925 | val 0.88527
  Epoch 011 - train 0.35527 | val 0.96874
  Classification -> best τ=0.410 (val F1=0.1795)
  Directional -> Accuracy: 0.5000, MCC: -0.0595, F1: 0.3226

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54697 | val 2.87901
  Epoch 014 - train 0.35388 | val 2.13648
  Classification -> best τ=0.465 (val F1=0.2233)
  Directional -> Accuracy: 0.4375, MCC: -0.0263, F1: 0.5970

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54770 | val 1.23649
  Epoch 020 - train 0.32443 | val 0.87638
  Classification -> best τ=0.355 (val F1=0.2679)
  Directional -> Accuracy: 0.5072, MCC: -0.0017, F1: 0.4333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58726 | val 0.65667
  Epoch 018 - train 0.34889 | val 0.72892
  Classification -> best τ=0.505 (val F1=0.4037)
  Directional -> Accuracy: 0.5918, MCC: 0.1557, F1: 0.4444

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48117 | val 2.84837
  Epoch 012 - train 0.39294 | val 3.70347
  Classification -> best τ=0.710 (val F1=0.1898)
  Directional -> Accuracy: 0.5088, MCC: 0.0230, F1: 0.4400

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47421 | val 1.65539
  Epoch 013 - train 0.36464 | val 1.87643
  Classification -> best τ=0.350 (val F1=0.2522)
  Directional -> Accuracy: 0.6190, MCC: 0.2781, F1: 0.6522

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54299 | val 1.25759
  Epoch 014 - train 0.44737 | val 1.15566
  Classification -> best τ=0.615 (val F1=0.2261)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.1250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43348 | val 4.21129
  Epoch 012 - train 0.38704 | val 6.29647
  Classification -> best τ=0.470 (val F1=0.4068)
  Directional -> Accuracy: 0.5686, MCC: 0.1115, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48493 | val 1.25815
  Epoch 011 - train 0.43980 | val 1.51512
  Classification -> best τ=0.735 (val F1=0.3700)
  Directional -> Accuracy: 0.6377, MCC: 0.2725, F1: 0.7126

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51004 | val 2.72382
  Epoch 011 - train 0.47779 | val 2.93739
  Classification -> best τ=0.740 (val F1=0.1731)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52179 | val 1.14655
  Epoch 012 - train 0.47176 | val 1.23126
  Classification -> best τ=0.330 (val F1=0.1769)
  Directional -> Accuracy: 0.5600, MCC: 0.0577, F1: 0.6526

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48481 | val 0.92000
  Epoch 011 - train 0.45990 | val 0.98136
  Classification -> best τ=0.195 (val F1=0.2522)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47661 | val 1.25804
  Epoch 011 - train 0.42856 | val 1.39772
  Classification -> best τ=0.485 (val F1=0.2572)
  Directional -> Accuracy: 0.6081, MCC: 0.2146, F1: 0.6329

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46873 | val 0.62495
  Epoch 020 - train 0.20800 | val 1.75474
  Classification -> best τ=0.470 (val F1=0.4000)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53007 | val 2.15247
  Epoch 011 - train 0.51985 | val 2.42907
  Classification -> best τ=0.210 (val F1=0.2315)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73120 | val 0.71554
  Epoch 013 - train 0.67452 | val 0.72398
  Classification -> best τ=0.400 (val F1=0.3680)
  Directional -> Accuracy: 0.5439, MCC: 0.0737, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55437 | val 2.41182
  Epoch 011 - train 0.50196 | val 2.02060
  Classification -> best τ=0.390 (val F1=0.1122)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46374 | val 1.85692
  Epoch 011 - train 0.45308 | val 2.02388
  Classification -> best τ=0.590 (val F1=0.3220)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44107 | val 3.19169
  Epoch 011 - train 0.41825 | val 3.10971
  Classification -> best τ=0.690 (val F1=0.2097)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59195 | val 0.75126
  Epoch 013 - train 0.54126 | val 0.90701
  Classification -> best τ=0.585 (val F1=0.1635)
  Directional -> Accuracy: 0.5476, MCC: 0.1434, F1: 0.5128

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54408 | val 1.79244
  Epoch 011 - train 0.48965 | val 2.22626
  Classification -> best τ=0.330 (val F1=0.2315)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46858 | val 1.35419
  Epoch 011 - train 0.42182 | val 1.32060
  Classification -> best τ=0.570 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58716 | val 0.61509
  Epoch 020 - train 0.37126 | val 0.62607
  Classification -> best τ=0.380 (val F1=0.4146)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51962 | val 0.98506
  Epoch 016 - train 0.28285 | val 1.07693
  Classification -> best τ=0.765 (val F1=0.1804)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38609 | val 1.38364
  Epoch 011 - train 0.34395 | val 1.31854
  Classification -> best τ=0.565 (val F1=0.2969)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58822 | val 1.77769
  Epoch 011 - train 0.57308 | val 1.18388
  Classification -> best τ=0.455 (val F1=0.2382)
  Directional -> Accuracy: 0.4583, MCC: 0.0466, F1: 0.0930

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49319 | val 2.36768
  Epoch 011 - train 0.48638 | val 2.37160
  Classification -> best τ=0.400 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63913 | val 0.83039
  Epoch 014 - train 0.50534 | val 1.26620
  Classification -> best τ=0.170 (val F1=0.3855)
  Directional -> Accuracy: 0.6364, MCC: 0.2358, F1: 0.7447

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37599 | val 1.20899
  Epoch 011 - train 0.41928 | val 1.47388
  Classification -> best τ=0.395 (val F1=0.2409)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55874 | val 0.87021
  Epoch 014 - train 0.42727 | val 1.17688
  Classification -> best τ=0.475 (val F1=0.2530)
  Directional -> Accuracy: 0.4643, MCC: -0.0667, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43605 | val 1.42877
  Epoch 011 - train 0.36027 | val 1.15519
  Classification -> best τ=0.420 (val F1=0.3146)
  Directional -> Accuracy: 0.5435, MCC: -0.2118, F1: 0.7042

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57231 | val 0.90159
  Epoch 014 - train 0.40327 | val 0.79729
  Classification -> best τ=0.365 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58346 | val 0.71326
  Epoch 020 - train 0.36764 | val 0.89470
  Classification -> best τ=0.270 (val F1=0.4068)
  Directional -> Accuracy: 0.4595, MCC: -0.1712, F1: 0.6296

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42675 | val 1.42689
  Epoch 011 - train 0.37803 | val 1.32751
  Classification -> best τ=0.465 (val F1=0.2712)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43982 | val 1.58539
  Epoch 011 - train 0.41099 | val 1.73477
  Classification -> best τ=0.670 (val F1=0.2500)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48224 | val 1.30359
  Epoch 013 - train 0.34461 | val 1.08936
  Classification -> best τ=0.655 (val F1=0.4385)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67952 | val 0.84241
  Epoch 019 - train 0.43087 | val 2.45829
  Classification -> best τ=0.545 (val F1=0.3398)
  Directional -> Accuracy: 0.4000, MCC: -0.3357, F1: 0.5600

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42964 | val 3.50302
  Epoch 011 - train 0.40787 | val 3.50639
  Classification -> best τ=0.535 (val F1=0.3233)
  Directional -> Accuracy: 0.5357, MCC: 0.0702, F1: 0.5185

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54508 | val 1.38303
  Epoch 012 - train 0.46366 | val 3.14357
  Classification -> best τ=0.625 (val F1=0.1413)
  Directional -> Accuracy: 0.4717, MCC: -0.0698, F1: 0.5625

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56546 | val 3.40159
  Epoch 012 - train 0.49447 | val 2.56858
  Classification -> best τ=0.870 (val F1=0.3278)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57870 | val 1.07990

[I 2026-02-20 04:36:45,918] Trial 161 finished with value: 0.28158587363520476 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00502506932939573, 'weight_decay': 4.1944329293746804e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.16860778401132684, 'early_stopping_min_delta': 0.008928591064585127}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 012 - train 0.50870 | val 1.61271
  Classification -> best τ=0.495 (val F1=0.2623)
  Directional -> Accuracy: 0.4333, MCC: -0.1307, F1: 0.4516

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28158587363520476
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55031 | val 1.45507
  Epoch 012 - train 0.48265 | val 2.11940
  Classification -> best τ=0.385 (val F1=0.2510)
  Directional -> Accuracy: 0.4079, MCC: -0.2009, F1: 0.3284

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48381 | val 0.99381
  Epoch 011 - train 0.48351 | val 1.19257
  Classification -> best τ=0.565 (val F1=0.2227)
  Directional -> Accuracy: 0.5111, MCC: 0.0260, F1: 0.5417

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60944 | val 0.89864
  Epoch 011 - train 0.64228 | val 0.85119
  Classification -> best τ=0.650 (val F1=0.3237)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51924 | val 1.51281
  Epoch 012 - train 0.47445 | val 1.50811
  Classification -> best τ=0.370 (val F1=0.1269)
  Directional -> Accuracy: 0.4865, MCC: -0.0890, F1: 0.6122

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49439 | val 1.57929
  Epoch 013 - train 0.32413 | val 1.80692
  Classification -> best τ=0.690 (val F1=0.4611)
  Directional -> Accuracy: 0.5000, MCC: 0.0742, F1: 0.1379

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40218 | val 1.06740
  Epoch 012 - train 0.35942 | val 1.09738
  Classification -> best τ=0.530 (val F1=0.3069)
  Directional -> Accuracy: 0.4130, MCC: -0.2143, F1: 0.2286

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59862 | val 1.20483
  Epoch 015 - train 0.42982 | val 3.19434
  Classification -> best τ=0.400 (val F1=0.3383)
  Directional -> Accuracy: 0.5147, MCC: 0.1902, F1: 0.5926

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54496 | val 2.25689
  Epoch 013 - train 0.40375 | val 2.67994
  Classification -> best τ=0.645 (val F1=0.1873)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46066 | val 1.22006
  Epoch 011 - train 0.42571 | val 1.94918
  Classification -> best τ=0.665 (val F1=0.2822)
  Directional -> Accuracy: 0.4792, MCC: -0.0639, F1: 0.3902

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43247 | val 1.03066
  Epoch 011 - train 0.45476 | val 1.40492
  Classification -> best τ=0.415 (val F1=0.2725)
  Directional -> Accuracy: 0.4058, MCC: -0.1424, F1: 0.5773

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50348 | val 1.08106
  Epoch 011 - train 0.49087 | val 1.42525
  Classification -> best τ=0.445 (val F1=0.3146)
  Directional -> Accuracy: 0.6327, MCC: 0.2673, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49113 | val 3.38340
  Epoch 012 - train 0.46339 | val 3.60154
  Classification -> best τ=0.530 (val F1=0.1651)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52621 | val 0.98500
  Epoch 013 - train 0.46223 | val 0.69867
  Classification -> best τ=0.395 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62700 | val 0.79497
  Epoch 016 - train 0.44500 | val 1.13968
  Classification -> best τ=0.320 (val F1=0.2878)
  Directional -> Accuracy: 0.4833, MCC: -0.0405, F1: 0.5974

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48876 | val 1.96632
  Epoch 011 - train 0.47427 | val 2.09138
  Classification -> best τ=0.720 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61199 | val 1.33707
  Epoch 014 - train 0.44441 | val 1.09737
  Classification -> best τ=0.200 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50065 | val 1.54476
  Epoch 011 - train 0.47618 | val 1.84727
  Classification -> best τ=0.415 (val F1=0.1336)
  Directional -> Accuracy: 0.6379, MCC: 0.1383, F1: 0.7692

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51859 | val 2.13851
  Epoch 012 - train 0.45491 | val 2.42926
  Classification -> best τ=0.550 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51433 | val 1.28784
  Epoch 011 - train 0.53909 | val 1.46974
  Classification -> best τ=0.555 (val F1=0.2600)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52123 | val 1.41438
  Epoch 011 - train 0.51998 | val 1.28132
  Classification -> best τ=0.115 (val F1=0.1895)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52652 | val 1.22475
  Epoch 013 - train 0.48099 | val 1.33683
  Classification -> best τ=0.425 (val F1=0.3308)
  Directional -> Accuracy: 0.5532, MCC: -0.0837, F1: 0.6957

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53056 | val 1.41761
  Epoch 011 - train 0.52784 | val 1.50336
  Classification -> best τ=0.445 (val F1=0.1482)
  Directional -> Accuracy: 0.4769, MCC: -0.0507, F1: 0.1905

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64016 | val 3.92978
  Epoch 013 - train 0.43936 | val 3.35401
  Classification -> best τ=0.760 (val F1=0.1700)
  Directional -> Accuracy: 0.6140, MCC: 0.2258, F1: 0.7381

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54199 | val 0.91595
  Epoch 012 - train 0.50060 | val 1.22729
  Classification -> best τ=0.365 (val F1=0.1575)
  Directional -> Accuracy: 0.4923, MCC: 0.0445, F1: 0.6374

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52151 | val 1.57370
  Epoch 011 - train 0.47813 | val 1.90373
  Classification -> best τ=0.720 (val F1=0.3563)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41705 | val 3.29515
  Epoch 011 - train 0.36372 | val 3.34657
  Classification -> best τ=0.475 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50431 | val 0.76737
  Epoch 012 - train 0.49403 | val 1.19416
  Classification -> best τ=0.420 (val F1=0.1964)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52378 | val 1.62375
  Epoch 011 - train 0.48368 | val 1.80754
  Classification -> best τ=0.775 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59122 | val 1.17617
  Epoch 015 - train 0.48413 | val 1.24225
  Classification -> best τ=0.295 (val F1=0.5136)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52650 | val 0.67581
  Epoch 020 - train 0.15852 | val 0.72089
  Classification -> best τ=0.650 (val F1=0.4266)
  Directional -> Accuracy: 0.5000, MCC: 0.0142, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47397 | val 1.04592
  Epoch 013 - train 0.30187 | val 1.70910
  Classification -> best τ=0.400 (val F1=0.1324)
  Directional -> Accuracy: 0.4286, MCC: -0.1090, F1: 0.1429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46044 | val 1.09028
  Epoch 011 - train 0.40037 | val 1.17988
  Classification -> best τ=0.590 (val F1=0.2969)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64573 | val 0.72987
  Epoch 015 - train 0.44030 | val 1.34103
  Classification -> best τ=0.435 (val F1=0.3986)
  Directional -> Accuracy: 0.5000, MCC: 0.0645, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52702 | val 1.95062
  Epoch 011 - train 0.45593 | val 2.25247
  Classification -> best τ=0.310 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49994 | val 1.06105
  Epoch 011 - train 0.50281 | val 1.20819
  Classification -> best τ=0.385 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41070 | val 1.08887
  Epoch 011 - train 0.26565 | val 1.53405
  Classification -> best τ=0.290 (val F1=0.2067)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46073 | val 1.19600
  Epoch 013 - train 0.36244 | val 2.15503
  Classification -> best τ=0.415 (val F1=0.2268)
  Directional -> Accuracy: 0.5536, MCC: 0.0837, F1: 0.3902

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41650 | val 1.35162
  Epoch 012 - train 0.42099 | val 1.26720
  Classification -> best τ=0.445 (val F1=0.3451)
  Directional -> Accuracy: 0.5652, MCC: -0.0153, F1: 0.6970

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48370 | val 0.67606
  Epoch 015 - train 0.45221 | val 0.74950
  Classification -> best τ=0.420 (val F1=0.6022)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55004 | val 1.00730
  Epoch 015 - train 0.33596 | val 1.57901
  Classification -> best τ=0.055 (val F1=0.3577)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46944 | val 1.23676
  Epoch 017 - train 0.19523 | val 1.02627
  Classification -> best τ=0.580 (val F1=0.3371)
  Directional -> Accuracy: 0.5778, MCC: 0.3055, F1: 0.2963

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38515 | val 1.05311
  Epoch 011 - train 0.41069 | val 1.03602
  Classification -> best τ=0.500 (val F1=0.0503)
  Directional -> Accuracy: 0.6190, MCC: 0.1964, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44878 | val 0.88827
  Epoch 012 - train 0.31669 | val 1.13856
  Classification -> best τ=0.400 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54331 | val 2.76862
  Epoch 012 - train 0.49486 | val 3.60365
  Classification -> best τ=0.560 (val F1=0.2283)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47099 | val 1.92936
  Epoch 011 - train 0.44423 | val 2.20917
  Classification -> best τ=0.420 (val F1=0.3236)
  Directional -> Accuracy: 0.5357, MCC: 0.1073, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48354 | val 1.09543
  Epoch 011 - train 0.49452 | val 1.27705
  Classification -> best τ=0.555 (val F1=0.2203)
  Directional -> Accuracy: 0.5849, MCC: 0.1739, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41378 | val 3.05304
  Epoch 012 - train 0.37705 | val 3.73848
  Classification -> best τ=0.820 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: -0.1093, F1: 0.6027

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55077 | val 0.91084

[I 2026-02-20 04:38:18,833] Trial 162 finished with value: 0.2705126638939739 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006231822642248309, 'weight_decay': 3.261015783426177e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.11006347453649963, 'early_stopping_min_delta': 0.008917543111518836}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 012 - train 0.46384 | val 1.84030
  Classification -> best τ=0.435 (val F1=0.2337)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2705126638939739
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52969 | val 1.52952
  Epoch 012 - train 0.53457 | val 1.04076
  Classification -> best τ=0.355 (val F1=0.2290)
  Directional -> Accuracy: 0.4868, MCC: 0.0573, F1: 0.5979

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44578 | val 1.76709
  Epoch 012 - train 0.39119 | val 1.32564
  Classification -> best τ=0.260 (val F1=0.1691)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56422 | val 1.05134
  Epoch 012 - train 0.52036 | val 0.91857
  Classification -> best τ=0.255 (val F1=0.4078)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48230 | val 3.64120
  Epoch 011 - train 0.45057 | val 3.76385
  Classification -> best τ=0.270 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49121 | val 1.48399
  Epoch 012 - train 0.42655 | val 1.11385
  Classification -> best τ=0.565 (val F1=0.4556)
  Directional -> Accuracy: 0.6800, MCC: 0.4208, F1: 0.6000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49194 | val 1.17516
  Epoch 014 - train 0.35427 | val 0.87133
  Classification -> best τ=0.400 (val F1=0.2593)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.6567

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55255 | val 1.65529
  Epoch 011 - train 0.49886 | val 2.45254
  Classification -> best τ=0.205 (val F1=0.2481)
  Directional -> Accuracy: 0.4412, MCC: 0.0509, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48366 | val 1.26354
  Epoch 011 - train 0.45216 | val 1.33031
  Classification -> best τ=0.655 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52400 | val 1.63683
  Epoch 011 - train 0.47213 | val 1.95935
  Classification -> best τ=0.605 (val F1=0.2233)
  Directional -> Accuracy: 0.6875, MCC: 0.3687, F1: 0.6512

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50439 | val 2.00824
  Epoch 015 - train 0.34255 | val 0.78810
  Classification -> best τ=0.350 (val F1=0.1858)
  Directional -> Accuracy: 0.4928, MCC: 0.0527, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58318 | val 0.72351
  Epoch 015 - train 0.38523 | val 0.89821
  Classification -> best τ=0.495 (val F1=0.4037)
  Directional -> Accuracy: 0.6327, MCC: 0.2673, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42399 | val 3.44665
  Epoch 011 - train 0.40063 | val 3.37449
  Classification -> best τ=0.170 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44362 | val 3.07692
  Epoch 011 - train 0.44339 | val 3.40599
  Classification -> best τ=0.350 (val F1=0.0875)
  Directional -> Accuracy: 0.5238, MCC: 0.0026, F1: 0.3333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.50734 | val 1.36500
  Epoch 012 - train 0.52054 | val 1.51990
  Classification -> best τ=0.240 (val F1=0.2212)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53554 | val 0.85155
  Epoch 016 - train 0.41215 | val 2.39877
  Classification -> best τ=0.675 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0287, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54210 | val 0.84930
  Epoch 011 - train 0.54155 | val 1.17143
  Classification -> best τ=0.400 (val F1=0.0917)
  Directional -> Accuracy: 0.5797, MCC: 0.1427, F1: 0.6742

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47116 | val 1.91082
  Epoch 011 - train 0.45786 | val 1.87429
  Classification -> best τ=0.305 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51879 | val 2.05122
  Epoch 011 - train 0.52310 | val 2.84368
  Classification -> best τ=0.490 (val F1=0.0842)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56700 | val 1.38960
  Epoch 016 - train 0.36401 | val 1.90560
  Classification -> best τ=0.455 (val F1=0.2103)
  Directional -> Accuracy: 0.4531, MCC: 0.0899, F1: 0.1463

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49811 | val 0.87804
  Epoch 011 - train 0.46616 | val 1.12154
  Classification -> best τ=0.645 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52829 | val 1.51377
  Epoch 015 - train 0.38969 | val 0.74743
  Classification -> best τ=0.495 (val F1=0.4104)
  Directional -> Accuracy: 0.4043, MCC: -0.0121, F1: 0.1765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53616 | val 0.92411
  Epoch 011 - train 0.50911 | val 1.40539
  Classification -> best τ=0.530 (val F1=0.1906)
  Directional -> Accuracy: 0.5231, MCC: 0.1014, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59578 | val 1.06478
  Epoch 011 - train 0.61723 | val 1.38512
  Classification -> best τ=0.600 (val F1=0.3304)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54513 | val 1.73516
  Epoch 011 - train 0.50393 | val 2.05828
  Classification -> best τ=0.580 (val F1=0.1985)
  Directional -> Accuracy: 0.5385, MCC: 0.0649, F1: 0.4231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45805 | val 1.28379
  Epoch 011 - train 0.43339 | val 1.36043
  Classification -> best τ=0.615 (val F1=0.3563)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47264 | val 3.46600
  Epoch 012 - train 0.41608 | val 4.69348
  Classification -> best τ=0.485 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52623 | val 1.01425
  Epoch 011 - train 0.49153 | val 0.82113
  Classification -> best τ=0.470 (val F1=0.1434)
  Directional -> Accuracy: 0.6190, MCC: 0.2477, F1: 0.6364

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47991 | val 1.71661
  Epoch 011 - train 0.43767 | val 1.73691
  Classification -> best τ=0.555 (val F1=0.1913)
  Directional -> Accuracy: 0.5000, MCC: 0.1222, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45348 | val 2.43163
  Epoch 011 - train 0.40906 | val 2.64958
  Classification -> best τ=0.395 (val F1=0.2957)
  Directional -> Accuracy: 0.6500, MCC: 0.2851, F1: 0.7200

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51587 | val 0.66873
  Epoch 016 - train 0.36292 | val 0.85307
  Classification -> best τ=0.645 (val F1=0.4110)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46407 | val 1.58247
  Epoch 013 - train 0.32569 | val 3.01722
  Classification -> best τ=0.450 (val F1=0.2844)
  Directional -> Accuracy: 0.4762, MCC: -0.1249, F1: 0.6071

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46405 | val 1.33879
  Epoch 011 - train 0.44944 | val 1.56331
  Classification -> best τ=0.615 (val F1=0.2969)
  Directional -> Accuracy: 0.4898, MCC: -0.0217, F1: 0.5098

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60408 | val 0.79219
  Epoch 014 - train 0.48564 | val 0.85624
  Classification -> best τ=0.350 (val F1=0.4023)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50646 | val 2.02802
  Epoch 011 - train 0.46369 | val 2.18971
  Classification -> best τ=0.630 (val F1=0.3227)
  Directional -> Accuracy: 0.5814, MCC: 0.1835, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51818 | val 1.16961
  Epoch 012 - train 0.41456 | val 1.29451
  Classification -> best τ=0.335 (val F1=0.2972)
  Directional -> Accuracy: 0.5606, MCC: 0.1048, F1: 0.6133

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48101 | val 0.86216
  Epoch 014 - train 0.31134 | val 1.10976
  Classification -> best τ=0.670 (val F1=0.2618)
  Directional -> Accuracy: 0.5714, MCC: 0.2197, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54400 | val 2.40607
  Epoch 014 - train 0.34428 | val 3.61334
  Classification -> best τ=0.470 (val F1=0.2755)
  Directional -> Accuracy: 0.5179, MCC: 0.0283, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39518 | val 2.35789
  Epoch 011 - train 0.37672 | val 1.72815
  Classification -> best τ=0.545 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54335 | val 0.79700
  Epoch 014 - train 0.42087 | val 0.75304
  Classification -> best τ=0.255 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51796 | val 2.40930
  Epoch 011 - train 0.49711 | val 1.50866
  Classification -> best τ=0.200 (val F1=0.2996)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43227 | val 0.82024
  Epoch 012 - train 0.36005 | val 1.82716
  Classification -> best τ=0.410 (val F1=0.3500)
  Directional -> Accuracy: 0.4889, MCC: -0.0134, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40775 | val 1.59090
  Epoch 011 - train 0.40751 | val 1.53636
  Classification -> best τ=0.590 (val F1=0.3612)
  Directional -> Accuracy: 0.3810, MCC: -0.2582, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59030 | val 1.17151
  Epoch 012 - train 0.55749 | val 1.26458
  Classification -> best τ=0.670 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56037 | val 1.35806
  Epoch 012 - train 0.46479 | val 2.38240
  Classification -> best τ=0.505 (val F1=0.2735)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50715 | val 1.90288
  Epoch 011 - train 0.50276 | val 2.14341
  Classification -> best τ=0.655 (val F1=0.3536)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63713 | val 1.33668
  Epoch 015 - train 0.49729 | val 1.55956
  Classification -> best τ=0.585 (val F1=0.1787)
  Directional -> Accuracy: 0.4906, MCC: -0.0113, F1: 0.3415

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51926 | val 2.54824
  Epoch 012 - train 0.44721 | val 3.17000
  Classification -> best τ=0.485 (val F1=0.2036)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51572 | val 1.35719
  Epoch 011 - train 0.49458 | val 1.55844

[I 2026-02-20 04:39:49,339] Trial 163 finished with value: 0.2687083185133181 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00453975035897519, 'weight_decay': 4.062664693065278e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.2226873437687503, 'early_stopping_min_delta': 0.008762652402786519}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.585 (val F1=0.1489)
  Directional -> Accuracy: 0.4500, MCC: -0.1025, F1: 0.4211

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2687083185133181
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59894 | val 0.73062
  Epoch 012 - train 0.54153 | val 1.23666
  Classification -> best τ=0.555 (val F1=0.1671)
  Directional -> Accuracy: 0.5658, MCC: 0.1620, F1: 0.5926

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64016 | val 0.88446
  Epoch 014 - train 0.40746 | val 1.04423
  Classification -> best τ=0.355 (val F1=0.2670)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57377 | val 2.30027
  Epoch 013 - train 0.53588 | val 1.74635
  Classification -> best τ=0.565 (val F1=0.2398)
  Directional -> Accuracy: 0.5217, MCC: 0.0288, F1: 0.6071

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54121 | val 4.33526
  Epoch 011 - train 0.50212 | val 4.68199
  Classification -> best τ=0.505 (val F1=0.1537)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45457 | val 1.34962
  Epoch 013 - train 0.36293 | val 2.34856
  Classification -> best τ=0.440 (val F1=0.4493)
  Directional -> Accuracy: 0.7400, MCC: 0.5047, F1: 0.7111

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44740 | val 2.03025
  Epoch 011 - train 0.47339 | val 1.38974
  Classification -> best τ=0.630 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60200 | val 0.86249
  Epoch 011 - train 0.57242 | val 0.96051
  Classification -> best τ=0.440 (val F1=0.2109)
  Directional -> Accuracy: 0.4118, MCC: -0.0868, F1: 0.4872

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41748 | val 5.38987
  Epoch 011 - train 0.37132 | val 6.09453
  Classification -> best τ=0.715 (val F1=0.3524)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53585 | val 1.94216
  Epoch 011 - train 0.52557 | val 1.50530
  Classification -> best τ=0.750 (val F1=0.2233)
  Directional -> Accuracy: 0.6042, MCC: 0.1732, F1: 0.4571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62946 | val 0.67249
  Epoch 020 - train 0.36475 | val 1.12453
  Classification -> best τ=0.610 (val F1=0.3294)
  Directional -> Accuracy: 0.5072, MCC: 0.0170, F1: 0.4688

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60018 | val 0.79950
  Epoch 013 - train 0.51401 | val 1.35329
  Classification -> best τ=0.490 (val F1=0.2877)
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60896 | val 2.29550
  Epoch 012 - train 0.54204 | val 3.54818
  Classification -> best τ=0.575 (val F1=0.2202)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59410 | val 3.48756
  Epoch 011 - train 0.54147 | val 3.42124
  Classification -> best τ=0.470 (val F1=0.1522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61355 | val 1.76578
  Epoch 012 - train 0.61268 | val 1.62410
  Classification -> best τ=0.380 (val F1=0.0599)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46026 | val 4.43491
  Epoch 011 - train 0.44523 | val 5.20132
  Classification -> best τ=0.480 (val F1=0.2778)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61138 | val 0.66402
  Epoch 019 - train 0.58362 | val 1.02584
  Classification -> best τ=0.630 (val F1=0.3515)
  Directional -> Accuracy: 0.4928, MCC: 0.0433, F1: 0.2857

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56331 | val 3.19188
  Epoch 011 - train 0.52705 | val 3.40941
  Classification -> best τ=0.345 (val F1=0.2135)
  Directional -> Accuracy: 0.5690, MCC: -0.0715, F1: 0.7126

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55151 | val 1.96068
  Epoch 013 - train 0.44637 | val 1.64734
  Classification -> best τ=0.460 (val F1=0.2082)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58919 | val 0.86340
  Epoch 012 - train 0.52544 | val 1.01333
  Classification -> best τ=0.420 (val F1=0.2656)
  Directional -> Accuracy: 0.4688, MCC: 0.0381, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47008 | val 1.80882
  Epoch 011 - train 0.49808 | val 2.27629
  Classification -> best τ=0.520 (val F1=0.2246)
  Directional -> Accuracy: 0.3514, MCC: -0.2915, F1: 0.1429

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52148 | val 2.44713
  Epoch 011 - train 0.49124 | val 3.26496
  Classification -> best τ=0.490 (val F1=0.3251)
  Directional -> Accuracy: 0.5319, MCC: 0.2722, F1: 0.4211

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54057 | val 5.15417
  Epoch 011 - train 0.55316 | val 3.03544
  Classification -> best τ=0.190 (val F1=0.1097)
  Directional -> Accuracy: 0.4923, MCC: -0.0443, F1: 0.6374

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56468 | val 1.26776
  Epoch 011 - train 0.54712 | val 1.40331
  Classification -> best τ=0.575 (val F1=0.2345)
  Directional -> Accuracy: 0.4561, MCC: 0.0076, F1: 0.2051

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57105 | val 0.82511
  Epoch 012 - train 0.51149 | val 0.79835
  Classification -> best τ=0.350 (val F1=0.1974)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52794 | val 0.91292
  Epoch 013 - train 0.42450 | val 1.06011
  Classification -> best τ=0.640 (val F1=0.4306)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58110 | val 2.47600
  Epoch 011 - train 0.51050 | val 2.67292
  Classification -> best τ=0.840 (val F1=0.2097)
  Directional -> Accuracy: 0.6222, MCC: 0.2949, F1: 0.6383

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57919 | val 0.89240
  Epoch 013 - train 0.45110 | val 0.85402
  Classification -> best τ=0.535 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55897 | val 1.10472
  Epoch 011 - train 0.51821 | val 1.16493
  Classification -> best τ=0.345 (val F1=0.2718)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52896 | val 0.88770
  Epoch 011 - train 0.49651 | val 0.90711
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50018 | val 1.00661
  Epoch 015 - train 0.33705 | val 1.48421
  Classification -> best τ=0.650 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46225 | val 1.12978
  Epoch 011 - train 0.38159 | val 1.20095
  Classification -> best τ=0.480 (val F1=0.0769)
  Directional -> Accuracy: 0.5238, MCC: -0.0214, F1: 0.6552

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63236 | val 0.80137
  Epoch 011 - train 0.60668 | val 0.86821
  Classification -> best τ=0.620 (val F1=0.2399)
  Directional -> Accuracy: 0.4898, MCC: -0.0835, F1: 0.6269

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66599 | val 0.88252
  Epoch 013 - train 0.55888 | val 0.72476
  Classification -> best τ=0.275 (val F1=0.3801)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57608 | val 1.89929
  Epoch 011 - train 0.50420 | val 2.14172
  Classification -> best τ=0.255 (val F1=0.3417)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56469 | val 1.11605
  Epoch 012 - train 0.50622 | val 1.41854
  Classification -> best τ=0.295 (val F1=0.2409)
  Directional -> Accuracy: 0.5909, MCC: 0.1056, F1: 0.7158

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41068 | val 1.44378
  Epoch 012 - train 0.43216 | val 1.23844
  Classification -> best τ=0.530 (val F1=0.1822)
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53188 | val 2.47990
  Epoch 011 - train 0.48900 | val 3.71206
  Classification -> best τ=0.385 (val F1=0.2541)
  Directional -> Accuracy: 0.4643, MCC: -0.0534, F1: 0.5161

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51713 | val 0.86084
  Epoch 014 - train 0.38352 | val 1.03917
  Classification -> best τ=0.600 (val F1=0.3372)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49973 | val 0.93473
  Epoch 011 - train 0.47307 | val 0.94928
  Classification -> best τ=0.375 (val F1=0.0636)
  Directional -> Accuracy: 0.5833, MCC: -0.0591, F1: 0.1667

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53769 | val 0.93627
  Epoch 012 - train 0.52150 | val 1.22647
  Classification -> best τ=0.365 (val F1=0.4273)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44974 | val 1.67660
  Epoch 011 - train 0.46363 | val 2.77103
  Classification -> best τ=0.375 (val F1=0.1890)
  Directional -> Accuracy: 0.4444, MCC: -0.2614, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61735 | val 0.79557
  Epoch 011 - train 0.60496 | val 0.80035
  Classification -> best τ=0.430 (val F1=0.4588)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51719 | val 1.23009
  Epoch 011 - train 0.48524 | val 1.19925
  Classification -> best τ=0.460 (val F1=0.2974)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54493 | val 1.64433
  Epoch 011 - train 0.50996 | val 1.59462
  Classification -> best τ=0.540 (val F1=0.1647)
  Directional -> Accuracy: 0.4727, MCC: -0.0279, F1: 0.4082

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42212 | val 4.11136
  Epoch 011 - train 0.41918 | val 3.92964
  Classification -> best τ=0.670 (val F1=0.3814)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55940 | val 0.92760
  Epoch 011 - train 0.56910 | val 0.81311
  Classification -> best τ=0.455 (val F1=0.1508)
  Directional -> Accuracy: 0.5660, MCC: 0.1493, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60511 | val 1.10202
  Epoch 012 - train 0.54027 | val 1.64613
  Classification -> best τ=0.755 (val F1=0.2228)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61308 | val 0.90958

[I 2026-02-20 04:41:21,155] Trial 164 finished with value: 0.24830678712800305 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009988886868307, 'weight_decay': 1.6609874637759593e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.1657316461705441, 'early_stopping_min_delta': 0.008530146202517448}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 014 - train 0.50213 | val 1.57466
  Classification -> best τ=0.565 (val F1=0.2810)
  Directional -> Accuracy: 0.5500, MCC: 0.1237, F1: 0.6197

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24830678712800305
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49945 | val 2.30994
  Epoch 011 - train 0.49099 | val 2.09270
  Classification -> best τ=0.775 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42768 | val 2.41382
  Epoch 012 - train 0.34141 | val 3.03133
  Classification -> best τ=0.360 (val F1=0.2073)
  Directional -> Accuracy: 0.6667, MCC: 0.4456, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53638 | val 0.90530
  Epoch 013 - train 0.37097 | val 1.29122
  Classification -> best τ=0.675 (val F1=0.4249)
  Directional -> Accuracy: 0.5652, MCC: 0.1724, F1: 0.4444

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59748 | val 1.08004
  Epoch 012 - train 0.55661 | val 0.99165
  Classification -> best τ=0.460 (val F1=0.1401)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46311 | val 0.98613
  Epoch 013 - train 0.35699 | val 1.25754
  Classification -> best τ=0.475 (val F1=0.4414)
  Directional -> Accuracy: 0.7000, MCC: 0.4361, F1: 0.6512

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38407 | val 1.22155
  Epoch 011 - train 0.34006 | val 1.27097
  Classification -> best τ=0.595 (val F1=0.0194)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58586 | val 1.45957
  Epoch 013 - train 0.47005 | val 2.47673
  Classification -> best τ=0.300 (val F1=0.3071)
  Directional -> Accuracy: 0.4412, MCC: 0.1135, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38359 | val 6.48370
  Epoch 011 - train 0.29298 | val 6.53734
  Classification -> best τ=0.890 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32925 | val 3.16475
  Epoch 011 - train 0.31989 | val 2.62429
  Classification -> best τ=0.475 (val F1=0.2764)
  Directional -> Accuracy: 0.5208, MCC: -0.0242, F1: 0.3030

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54930 | val 2.07606
  Epoch 015 - train 0.40232 | val 0.71006
  Classification -> best τ=0.540 (val F1=0.2557)
  Directional -> Accuracy: 0.4783, MCC: -0.0139, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59286 | val 0.66353
  Epoch 016 - train 0.55768 | val 0.85222
  Classification -> best τ=0.550 (val F1=0.4196)
  Directional -> Accuracy: 0.6531, MCC: 0.3010, F1: 0.4848

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41990 | val 1.67320
  Epoch 011 - train 0.45324 | val 1.58382
  Classification -> best τ=0.630 (val F1=0.0115)
  Directional -> Accuracy: 0.4737, MCC: -0.0496, F1: 0.3750

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45389 | val 0.86504
  Epoch 011 - train 0.40595 | val 0.91946
  Classification -> best τ=0.685 (val F1=0.1801)
  Directional -> Accuracy: 0.4524, MCC: -0.1220, F1: 0.3429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55658 | val 1.57762
  Epoch 013 - train 0.47467 | val 1.70519
  Classification -> best τ=0.255 (val F1=0.2692)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41759 | val 2.70174
  Epoch 011 - train 0.43042 | val 2.16342
  Classification -> best τ=0.465 (val F1=0.0703)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50141 | val 0.92999
  Epoch 012 - train 0.40222 | val 1.29067
  Classification -> best τ=0.425 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.0753, F1: 0.6517

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48372 | val 1.97478
  Epoch 011 - train 0.45673 | val 2.11900
  Classification -> best τ=0.545 (val F1=0.1137)
  Directional -> Accuracy: 0.4310, MCC: 0.1135, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43009 | val 1.44764
  Epoch 011 - train 0.39777 | val 2.01685
  Classification -> best τ=0.525 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45419 | val 3.00218
  Epoch 011 - train 0.45553 | val 2.47161
  Classification -> best τ=0.405 (val F1=0.2166)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46788 | val 1.84876
  Epoch 011 - train 0.43990 | val 1.55163
  Classification -> best τ=0.440 (val F1=0.2558)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60029 | val 0.76752
  Epoch 017 - train 0.26510 | val 0.83538
  Classification -> best τ=0.305 (val F1=0.3678)
  Directional -> Accuracy: 0.5319, MCC: 0.2287, F1: 0.4500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55232 | val 1.08195
  Epoch 011 - train 0.53122 | val 1.00587
  Classification -> best τ=0.445 (val F1=0.2160)
  Directional -> Accuracy: 0.5231, MCC: 0.0564, F1: 0.4151

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55433 | val 1.18801
  Epoch 015 - train 0.40970 | val 1.92256
  Classification -> best τ=0.530 (val F1=0.3305)
  Directional -> Accuracy: 0.5614, MCC: 0.1304, F1: 0.5763

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47167 | val 2.67372
  Epoch 011 - train 0.44841 | val 2.31143
  Classification -> best τ=0.610 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0428, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45078 | val 2.14778
  Epoch 011 - train 0.45084 | val 2.32762
  Classification -> best τ=0.530 (val F1=0.3472)
  Directional -> Accuracy: 0.5455, MCC: 0.2064, F1: 0.3590

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49245 | val 1.34741
  Epoch 011 - train 0.44933 | val 1.04604
  Classification -> best τ=0.720 (val F1=0.1981)
  Directional -> Accuracy: 0.4222, MCC: -0.1540, F1: 0.3810

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58821 | val 0.97285
  Epoch 013 - train 0.46268 | val 1.02571
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42709 | val 1.89016
  Epoch 011 - train 0.37199 | val 2.09321
  Classification -> best τ=0.355 (val F1=0.2976)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46951 | val 1.29295
  Epoch 011 - train 0.43631 | val 1.62032
  Classification -> best τ=0.485 (val F1=0.1459)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50062 | val 0.98523
  Epoch 012 - train 0.37306 | val 0.85769
  Classification -> best τ=0.535 (val F1=0.3001)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51828 | val 1.59968
  Epoch 014 - train 0.31422 | val 0.92022
  Classification -> best τ=0.615 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40441 | val 1.09643
  Epoch 011 - train 0.36526 | val 1.21058
  Classification -> best τ=0.350 (val F1=0.2609)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51414 | val 1.28018
  Epoch 011 - train 0.48858 | val 2.38065
  Classification -> best τ=0.330 (val F1=0.3095)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38660 | val 2.04572
  Epoch 011 - train 0.30677 | val 1.80768
  Classification -> best τ=0.750 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49771 | val 1.29739
  Epoch 012 - train 0.42181 | val 1.48869
  Classification -> best τ=0.250 (val F1=0.3855)
  Directional -> Accuracy: 0.5758, MCC: 0.0795, F1: 0.6889

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26767 | val 2.18076
  Epoch 011 - train 0.24532 | val 1.64460
  Classification -> best τ=0.395 (val F1=0.2067)
  Directional -> Accuracy: 0.6190, MCC: 0.2409, F1: 0.6190

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46964 | val 3.50179
  Epoch 012 - train 0.39583 | val 4.43485
  Classification -> best τ=0.415 (val F1=0.2725)
  Directional -> Accuracy: 0.5357, MCC: 0.0769, F1: 0.5357

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35006 | val 1.19196
  Epoch 011 - train 0.29756 | val 1.22400
  Classification -> best τ=0.445 (val F1=0.3367)
  Directional -> Accuracy: 0.5435, MCC: -0.0917, F1: 0.6866

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46322 | val 0.98095
  Epoch 011 - train 0.49192 | val 1.09985
  Classification -> best τ=0.480 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46002 | val 1.51026
  Epoch 011 - train 0.42214 | val 1.50813
  Classification -> best τ=0.210 (val F1=0.3823)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35066 | val 1.48758
  Epoch 012 - train 0.28809 | val 1.20032
  Classification -> best τ=0.520 (val F1=0.4625)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45059 | val 1.42722
  Epoch 011 - train 0.38260 | val 2.10552
  Classification -> best τ=0.540 (val F1=0.4277)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.5652

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51156 | val 1.22313
  Epoch 011 - train 0.49418 | val 1.15478
  Classification -> best τ=0.575 (val F1=0.5421)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50103 | val 1.97481
  Epoch 011 - train 0.44488 | val 2.08394
  Classification -> best τ=0.440 (val F1=0.1683)
  Directional -> Accuracy: 0.5091, MCC: 0.0267, F1: 0.5091

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43783 | val 2.55736
  Epoch 011 - train 0.40163 | val 2.62816
  Classification -> best τ=0.605 (val F1=0.2308)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49231 | val 1.53967
  Epoch 011 - train 0.48228 | val 1.36588
  Classification -> best τ=0.470 (val F1=0.2229)
  Directional -> Accuracy: 0.5472, MCC: 0.1056, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53963 | val 2.44962
  Epoch 017 - train 0.23635 | val 4.88252
  Classification -> best τ=0.870 (val F1=0.3133)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50973 | val 1.32563
  Epoch 011 - train 0.50794 | val 0.87588

[I 2026-02-20 04:42:50,280] Trial 165 finished with value: 0.2630810932526411 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.008345963201225104, 'weight_decay': 6.130002598785536e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.18696629610196844, 'early_stopping_min_delta': 0.00935555937467189}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.570 (val F1=0.3108)
  Directional -> Accuracy: 0.5667, MCC: 0.1733, F1: 0.6486

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2630810932526411
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57807 | val 0.78371
  Epoch 013 - train 0.46572 | val 1.29530
  Classification -> best τ=0.575 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1194, F1: 0.5075

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44806 | val 0.94894
  Epoch 012 - train 0.43342 | val 1.01801
  Classification -> best τ=0.580 (val F1=0.2704)
  Directional -> Accuracy: 0.5778, MCC: 0.3149, F1: 0.4571

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50538 | val 1.17195
  Epoch 012 - train 0.43622 | val 1.02286
  Classification -> best τ=0.410 (val F1=0.3140)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50039 | val 3.09703
  Epoch 011 - train 0.50166 | val 3.46767
  Classification -> best τ=0.220 (val F1=0.1115)
  Directional -> Accuracy: 0.5135, MCC: -0.1005, F1: 0.6727

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45453 | val 1.12056
  Epoch 012 - train 0.39280 | val 0.83782
  Classification -> best τ=0.535 (val F1=0.4930)
  Directional -> Accuracy: 0.6400, MCC: 0.3524, F1: 0.5263

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47829 | val 1.00339
  Epoch 013 - train 0.37067 | val 0.75904
  Classification -> best τ=0.510 (val F1=0.3621)
  Directional -> Accuracy: 0.5652, MCC: 0.1284, F1: 0.3750

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58300 | val 2.02616
  Epoch 012 - train 0.51055 | val 1.23015
  Classification -> best τ=0.440 (val F1=0.2170)
  Directional -> Accuracy: 0.5294, MCC: 0.2143, F1: 0.6000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59974 | val 2.04004
  Epoch 011 - train 0.46452 | val 2.24331
  Classification -> best τ=0.520 (val F1=0.2566)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51895 | val 0.76068
  Epoch 013 - train 0.37701 | val 1.13039
  Classification -> best τ=0.590 (val F1=0.2285)
  Directional -> Accuracy: 0.5625, MCC: 0.0808, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56240 | val 1.11015
  Epoch 020 - train 0.45657 | val 0.98665
  Epoch 025 - train 0.24452 | val 1.17801
  Classification -> best τ=0.235 (val F1=0.4165)
  Directional -> Accuracy: 0.4783, MCC: 0.0155, F1: 0.5263

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56263 | val 0.74334
  Epoch 014 - train 0.40641 | val 1.47010
  Classification -> best τ=0.380 (val F1=0.4196)
  Directional -> Accuracy: 0.6122, MCC: 0.2017, F1: 0.4865

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44489 | val 2.76612
  Epoch 011 - train 0.48018 | val 2.15033
  Classification -> best τ=0.575 (val F1=0.4222)
  Directional -> Accuracy: 0.4561, MCC: -0.1248, F1: 0.5867

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45073 | val 0.92827
  Epoch 011 - train 0.41874 | val 1.04787
  Classification -> best τ=0.270 (val F1=0.3073)
  Directional -> Accuracy: 0.4524, MCC: -0.0464, F1: 0.5660

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61996 | val 0.69513
  Epoch 019 - train 0.41044 | val 0.69586
  Classification -> best τ=0.260 (val F1=0.3919)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57541 | val 1.59506
  Epoch 014 - train 0.37630 | val 1.33764
  Classification -> best τ=0.485 (val F1=0.0709)
  Directional -> Accuracy: 0.4706, MCC: 0.0338, F1: 0.6087

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57749 | val 0.80005
  Epoch 015 - train 0.42377 | val 1.55244
  Classification -> best τ=0.615 (val F1=0.3819)
  Directional -> Accuracy: 0.5217, MCC: 0.1352, F1: 0.2979

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56119 | val 1.64106
  Epoch 011 - train 0.56542 | val 1.95548
  Classification -> best τ=0.305 (val F1=0.2429)
  Directional -> Accuracy: 0.4138, MCC: -0.3235, F1: 0.5641

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48368 | val 2.23688
  Epoch 011 - train 0.45536 | val 3.29645
  Classification -> best τ=0.480 (val F1=0.2004)
  Directional -> Accuracy: 0.4533, MCC: 0.0801, F1: 0.2545

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54500 | val 1.47453
  Epoch 011 - train 0.48925 | val 1.14495
  Classification -> best τ=0.385 (val F1=0.2166)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46297 | val 1.81673
  Epoch 013 - train 0.41853 | val 1.84999
  Classification -> best τ=0.670 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55964 | val 1.77904
  Epoch 017 - train 0.47919 | val 1.46588
  Classification -> best τ=0.475 (val F1=0.3262)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60523 | val 2.01015
  Epoch 013 - train 0.44480 | val 2.37714
  Classification -> best τ=0.670 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57695 | val 1.20499
  Epoch 013 - train 0.48587 | val 2.21623
  Classification -> best τ=0.710 (val F1=0.2875)
  Directional -> Accuracy: 0.4912, MCC: 0.0739, F1: 0.3256

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50217 | val 2.03193
  Epoch 011 - train 0.47424 | val 2.36040
  Classification -> best τ=0.655 (val F1=0.2083)
  Directional -> Accuracy: 0.4769, MCC: -0.0548, F1: 0.4138

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44595 | val 1.66027
  Epoch 011 - train 0.42525 | val 1.71145
  Classification -> best τ=0.650 (val F1=0.2852)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40333 | val 6.60590
  Epoch 012 - train 0.34574 | val 8.72580
  Classification -> best τ=0.610 (val F1=0.2621)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52736 | val 3.21075
  Epoch 012 - train 0.48455 | val 3.30880
  Classification -> best τ=0.565 (val F1=0.0574)
  Directional -> Accuracy: 0.5952, MCC: 0.1795, F1: 0.6383

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50484 | val 1.24795
  Epoch 012 - train 0.43983 | val 1.29555
  Classification -> best τ=0.120 (val F1=0.2614)
  Directional -> Accuracy: 0.5714, MCC: 0.1265, F1: 0.6250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45782 | val 0.84657
  Epoch 011 - train 0.36342 | val 0.83435
  Classification -> best τ=0.655 (val F1=0.4181)
  Directional -> Accuracy: 0.4500, MCC: -0.0335, F1: 0.1538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60474 | val 0.66331
  Epoch 014 - train 0.48255 | val 1.05327
  Classification -> best τ=0.740 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.2132, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47608 | val 0.94100
  Epoch 012 - train 0.43741 | val 1.21873
  Classification -> best τ=0.445 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56720 | val 0.91998
  Epoch 016 - train 0.40572 | val 1.27918
  Classification -> best τ=0.540 (val F1=0.4278)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62705 | val 0.72571
  Epoch 013 - train 0.48669 | val 0.91614
  Classification -> best τ=0.370 (val F1=0.3380)
  Directional -> Accuracy: 0.5417, MCC: 0.1076, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52929 | val 1.52475
  Epoch 011 - train 0.47123 | val 1.83169
  Classification -> best τ=0.690 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61986 | val 0.69520
  Epoch 011 - train 0.61352 | val 0.83451
  Classification -> best τ=0.685 (val F1=0.2951)
  Directional -> Accuracy: 0.4545, MCC: 0.0207, F1: 0.2500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58218 | val 0.81580
  Epoch 011 - train 0.52022 | val 0.89528
  Classification -> best τ=0.390 (val F1=0.1715)
  Directional -> Accuracy: 0.5952, MCC: 0.1961, F1: 0.5854

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51973 | val 1.19470
  Epoch 011 - train 0.44626 | val 1.33352
  Classification -> best τ=0.630 (val F1=0.1913)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41773 | val 0.96370
  Epoch 012 - train 0.36160 | val 1.09123
  Classification -> best τ=0.265 (val F1=0.3397)
  Directional -> Accuracy: 0.6304, MCC: 0.1493, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53711 | val 0.77953
  Epoch 016 - train 0.32501 | val 0.95885
  Classification -> best τ=0.265 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54786 | val 0.88625
  Epoch 014 - train 0.34344 | val 1.88322
  Classification -> best τ=0.220 (val F1=0.4182)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42978 | val 0.83390
  Epoch 012 - train 0.37003 | val 1.34619
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51910 | val 1.07214
  Epoch 011 - train 0.48867 | val 1.10273
  Classification -> best τ=0.530 (val F1=0.2408)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58388 | val 2.32998
  Epoch 018 - train 0.30784 | val 1.25896
  Classification -> best τ=0.710 (val F1=0.4542)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62615 | val 2.52370
  Epoch 015 - train 0.44201 | val 3.05183
  Classification -> best τ=0.545 (val F1=0.2132)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45658 | val 2.20454
  Epoch 011 - train 0.41709 | val 2.54671
  Classification -> best τ=0.240 (val F1=0.2640)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61501 | val 0.85723
  Epoch 015 - train 0.42996 | val 2.01040
  Classification -> best τ=0.645 (val F1=0.2064)
  Directional -> Accuracy: 0.5283, MCC: 0.1124, F1: 0.2424

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46725 | val 3.11125
  Epoch 012 - train 0.38779 | val 3.24433
  Classification -> best τ=0.870 (val F1=0.1881)
  Directional -> Accuracy: 0.5455, MCC: 0.0755, F1: 0.6753

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46516 | val 0.81379

[I 2026-02-20 04:44:26,434] Trial 166 finished with value: 0.28208596193930696 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006232200177445509, 'weight_decay': 4.2187215477313603e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5567275293411064, 'early_stopping_min_delta': 0.0091013582361102}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.45067 | val 0.75497
  Classification -> best τ=0.530 (val F1=0.2691)
  Directional -> Accuracy: 0.5333, MCC: 0.1261, F1: 0.6500

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28208596193930696
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64796 | val 1.16165
  Epoch 011 - train 0.60667 | val 0.96285
  Classification -> best τ=0.350 (val F1=0.1360)
  Directional -> Accuracy: 0.5844, MCC: 0.2106, F1: 0.6279

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55770 | val 0.93750
  Epoch 012 - train 0.47423 | val 1.08843
  Classification -> best τ=0.345 (val F1=0.3063)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59126 | val 1.31264
  Epoch 011 - train 0.53598 | val 0.94241
  Classification -> best τ=0.560 (val F1=0.2223)
  Directional -> Accuracy: 0.4468, MCC: -0.1053, F1: 0.4583

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61948 | val 1.39529
  Epoch 011 - train 0.60739 | val 2.74320
  Classification -> best τ=0.205 (val F1=0.1283)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58765 | val 2.94961
  Epoch 011 - train 0.60068 | val 4.45185
  Classification -> best τ=0.290 (val F1=0.3484)
  Directional -> Accuracy: 0.6863, MCC: 0.3884, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42578 | val 5.02010
  Epoch 011 - train 0.34773 | val 6.01955
  Classification -> best τ=0.645 (val F1=0.2928)
  Directional -> Accuracy: 0.6170, MCC: 0.2428, F1: 0.5263

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65725 | val 0.76888
  Epoch 012 - train 0.61976 | val 1.01749
  Classification -> best τ=0.360 (val F1=0.2371)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55240 | val 3.09731
  Epoch 011 - train 0.48754 | val 2.91739
  Classification -> best τ=0.520 (val F1=0.1752)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50730 | val 4.66781
  Epoch 012 - train 0.61850 | val 2.37796
  Classification -> best τ=0.630 (val F1=0.5112)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54192 | val 2.11883
  Epoch 011 - train 0.56118 | val 1.32606
  Classification -> best τ=0.445 (val F1=0.2262)
  Directional -> Accuracy: 0.4429, MCC: 0.1043, F1: 0.6061

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52939 | val 3.70316
  Epoch 011 - train 0.58177 | val 2.54277
  Classification -> best τ=0.555 (val F1=0.2151)
  Directional -> Accuracy: 0.5600, MCC: 0.1143, F1: 0.5217

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54408 | val 1.99840
  Epoch 011 - train 0.61985 | val 1.78115
  Classification -> best τ=0.515 (val F1=0.1703)
  Directional -> Accuracy: 0.5345, MCC: 0.0772, F1: 0.4000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57385 | val 1.09267
  Epoch 011 - train 0.56158 | val 1.45357
  Classification -> best τ=0.400 (val F1=0.2454)
  Directional -> Accuracy: 0.4884, MCC: 0.0880, F1: 0.6071

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58842 | val 0.82669
  Epoch 012 - train 0.57380 | val 1.03652
  Classification -> best τ=0.435 (val F1=0.2825)
  Directional -> Accuracy: 0.5410, MCC: 0.1035, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58037 | val 0.72625
  Epoch 020 - train 0.44126 | val 1.01948
  Epoch 022 - train 0.42974 | val 0.95591
  Classification -> best τ=0.720 (val F1=0.2177)
  Directional -> Accuracy: 0.4615, MCC: -0.1409, F1: 0.2222

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54450 | val 2.13902
  Epoch 012 - train 0.49471 | val 3.00435
  Classification -> best τ=0.350 (val F1=0.2605)
  Directional -> Accuracy: 0.5286, MCC: -0.0318, F1: 0.6796

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61322 | val 2.15133
  Epoch 011 - train 0.56764 | val 1.94511
  Classification -> best τ=0.425 (val F1=0.2294)
  Directional -> Accuracy: 0.6441, MCC: 0.1506, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58891 | val 0.86303
  Epoch 015 - train 0.55847 | val 1.33232
  Classification -> best τ=0.685 (val F1=0.1095)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57213 | val 1.90491
  Epoch 013 - train 0.51991 | val 1.63062
  Classification -> best τ=0.785 (val F1=0.2249)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54504 | val 1.41792
  Epoch 011 - train 0.53165 | val 1.19258
  Classification -> best τ=0.515 (val F1=0.2696)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49996 | val 0.73439
  Epoch 011 - train 0.58213 | val 1.79724
  Classification -> best τ=0.505 (val F1=0.1521)
  Directional -> Accuracy: 0.6250, MCC: 0.0778, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57449 | val 1.43818
  Epoch 011 - train 0.54303 | val 2.15324
  Classification -> best τ=0.510 (val F1=0.1860)
  Directional -> Accuracy: 0.3788, MCC: -0.2481, F1: 0.3051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61825 | val 2.00425
  Epoch 011 - train 0.60862 | val 2.23372
  Classification -> best τ=0.350 (val F1=0.1597)
  Directional -> Accuracy: 0.4655, MCC: 0.0148, F1: 0.3111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60122 | val 0.94311
  Epoch 011 - train 0.59311 | val 0.83002
  Classification -> best τ=0.330 (val F1=0.3663)
  Directional -> Accuracy: 0.5152, MCC: 0.0684, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56641 | val 0.71844
  Epoch 013 - train 0.51894 | val 1.27302
  Classification -> best τ=0.610 (val F1=0.3993)
  Directional -> Accuracy: 0.5536, MCC: 0.2640, F1: 0.3590

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45957 | val 1.90986
  Epoch 011 - train 0.45089 | val 1.51132
  Classification -> best τ=0.385 (val F1=0.2774)
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.6349

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55932 | val 1.38611
  Epoch 011 - train 0.58892 | val 1.00694
  Classification -> best τ=0.505 (val F1=0.0653)
  Directional -> Accuracy: 0.5814, MCC: 0.2040, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61993 | val 1.06352
  Epoch 011 - train 0.55871 | val 1.03344
  Classification -> best τ=0.410 (val F1=0.1840)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57692 | val 0.81027
  Epoch 017 - train 0.40144 | val 1.02820
  Classification -> best τ=0.420 (val F1=0.3069)
  Directional -> Accuracy: 0.4878, MCC: -0.2104, F1: 0.6557

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56921 | val 3.29259
  Epoch 012 - train 0.52334 | val 4.76568
  Classification -> best τ=0.770 (val F1=0.2683)
  Directional -> Accuracy: 0.4419, MCC: -0.1463, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52197 | val 2.28562
  Epoch 012 - train 0.47793 | val 3.40445
  Classification -> best τ=0.500 (val F1=0.2533)
  Directional -> Accuracy: 0.5116, MCC: -0.0724, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52703 | val 1.50695
  Epoch 011 - train 0.52741 | val 1.63834
  Classification -> best τ=0.700 (val F1=0.4192)
  Directional -> Accuracy: 0.4600, MCC: -0.0237, F1: 0.1290

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52247 | val 1.26486
  Epoch 012 - train 0.52160 | val 1.22204
  Classification -> best τ=0.230 (val F1=0.3337)
  Directional -> Accuracy: 0.5068, MCC: 0.1076, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.57537 | val 0.74059
  Epoch 012 - train 0.55004 | val 0.74779
  Classification -> best τ=0.410 (val F1=0.2182)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63164 | val 1.56258
  Epoch 011 - train 0.58678 | val 2.04110
  Classification -> best τ=0.235 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57115 | val 1.01886
  Epoch 013 - train 0.48403 | val 1.30801
  Classification -> best τ=0.175 (val F1=0.4655)
  Directional -> Accuracy: 0.4179, MCC: -0.1409, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47229 | val 4.18931
  Epoch 012 - train 0.40314 | val 1.10142
  Classification -> best τ=0.695 (val F1=0.2652)
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49120 | val 1.31021
  Epoch 011 - train 0.52648 | val 1.64318
  Classification -> best τ=0.620 (val F1=0.3129)
  Directional -> Accuracy: 0.5263, MCC: 0.0145, F1: 0.1290

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51644 | val 1.24420
  Epoch 011 - train 0.46995 | val 1.84451
  Classification -> best τ=0.580 (val F1=0.2960)
  Directional -> Accuracy: 0.4468, MCC: 0.0497, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46535 | val 1.32690
  Epoch 013 - train 0.53869 | val 1.24210
  Classification -> best τ=0.295 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54298 | val 2.16035
  Epoch 012 - train 0.59567 | val 1.38892
  Classification -> best τ=0.360 (val F1=0.4223)
  Directional -> Accuracy: 0.5526, MCC: 0.0965, F1: 0.6047

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56809 | val 1.92534
  Epoch 012 - train 0.53340 | val 3.38018
  Classification -> best τ=0.260 (val F1=0.2512)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64660 | val 1.89788
  Epoch 012 - train 0.73448 | val 1.54693
  Classification -> best τ=0.635 (val F1=0.3301)
  Directional -> Accuracy: 0.5745, MCC: 0.1506, F1: 0.5652

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45772 | val 2.43976
  Epoch 011 - train 0.43005 | val 2.78157
  Classification -> best τ=0.675 (val F1=0.5609)
  Directional -> Accuracy: 0.5227, MCC: 0.0867, F1: 0.4878

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58781 | val 2.46038
  Epoch 012 - train 0.47469 | val 5.15339
  Classification -> best τ=0.620 (val F1=0.5500)
  Directional -> Accuracy: 0.5306, MCC: 0.1936, F1: 0.5818

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54833 | val 4.55816
  Epoch 012 - train 0.52574 | val 6.18856
  Classification -> best τ=0.610 (val F1=0.2727)
  Directional -> Accuracy: 0.6429, MCC: 0.3510, F1: 0.5652

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49200 | val 2.04592
  Epoch 011 - train 0.53330 | val 2.91863
  Classification -> best τ=0.400 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64655 | val 0.68358
  Epoch 020 - train 0.49133 | val 0.97176
  Classification -> best τ=0.560 (val F1=0.2710)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59071 | val 0.95805
  Epoch 011 - train 0.65170 | val 6.71294
  Classification -> best τ=0.605 (val F1=0.1344)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59750 | val 1.02591

[I 2026-02-20 04:45:44,763] Trial 167 finished with value: 0.2747206505515928 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.00708086994848936, 'weight_decay': 8.213751619134905e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0834389665523338, 'early_stopping_min_delta': 0.009137221081204693}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 012 - train 0.53979 | val 1.39433
  Classification -> best τ=0.440 (val F1=0.3457)
  Directional -> Accuracy: 0.5246, MCC: 0.0397, F1: 0.4528

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2747206505515928
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62957 | val 0.83542
  Epoch 014 - train 0.49879 | val 1.96073
  Classification -> best τ=0.660 (val F1=0.3013)
  Directional -> Accuracy: 0.5263, MCC: -0.0371, F1: 0.1818

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52381 | val 0.91236
  Epoch 013 - train 0.39258 | val 0.81008
  Classification -> best τ=0.480 (val F1=0.1273)
  Directional -> Accuracy: 0.5778, MCC: 0.3669, F1: 0.4242

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54414 | val 1.06920
  Epoch 011 - train 0.49165 | val 1.10366
  Classification -> best τ=0.595 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1286, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52655 | val 2.17714
  Epoch 011 - train 0.55743 | val 1.67243
  Classification -> best τ=0.220 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45336 | val 1.75134
  Epoch 012 - train 0.41187 | val 2.83752
  Classification -> best τ=0.685 (val F1=0.5167)
  Directional -> Accuracy: 0.6400, MCC: 0.3524, F1: 0.5263

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43896 | val 3.16811
  Epoch 013 - train 0.29391 | val 2.09547
  Classification -> best τ=0.535 (val F1=0.3624)
  Directional -> Accuracy: 0.6087, MCC: 0.2936, F1: 0.6897

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52924 | val 1.90192
  Epoch 011 - train 0.49749 | val 1.67867
  Classification -> best τ=0.545 (val F1=0.2361)
  Directional -> Accuracy: 0.5735, MCC: 0.2056, F1: 0.5797

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49325 | val 1.35280
  Epoch 011 - train 0.44757 | val 1.26618
  Classification -> best τ=0.485 (val F1=0.1657)
  Directional -> Accuracy: 0.3810, MCC: -0.2123, F1: 0.4091

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61529 | val 0.88056
  Epoch 016 - train 0.44908 | val 1.03730
  Classification -> best τ=0.300 (val F1=0.2925)
  Directional -> Accuracy: 0.6042, MCC: 0.2100, F1: 0.5778

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48550 | val 1.50149
  Epoch 011 - train 0.48595 | val 1.58269
  Classification -> best τ=0.410 (val F1=0.1304)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54268 | val 0.67580
  Epoch 015 - train 0.41878 | val 0.87894
  Classification -> best τ=0.465 (val F1=0.4196)
  Directional -> Accuracy: 0.6122, MCC: 0.2076, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56399 | val 2.46080
  Epoch 011 - train 0.50605 | val 3.83060
  Classification -> best τ=0.330 (val F1=0.1724)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45758 | val 5.54619
  Epoch 012 - train 0.36350 | val 6.52704
  Classification -> best τ=0.580 (val F1=0.2571)
  Directional -> Accuracy: 0.4286, MCC: -0.1946, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54829 | val 6.03943
  Epoch 011 - train 0.55591 | val 11.14753
  Classification -> best τ=0.515 (val F1=0.2531)
  Directional -> Accuracy: 0.3833, MCC: -0.2508, F1: 0.2449

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51853 | val 1.26659
  Epoch 011 - train 0.45768 | val 1.05169
  Classification -> best τ=0.605 (val F1=0.2571)
  Directional -> Accuracy: 0.5098, MCC: -0.1178, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53834 | val 1.56395
  Epoch 012 - train 0.49119 | val 1.42582
  Classification -> best τ=0.690 (val F1=0.2076)
  Directional -> Accuracy: 0.5072, MCC: 0.0765, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49719 | val 2.77606
  Epoch 011 - train 0.50365 | val 2.81152
  Classification -> best τ=0.530 (val F1=0.1842)
  Directional -> Accuracy: 0.3621, MCC: -0.1694, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51687 | val 2.11287
  Epoch 011 - train 0.51079 | val 2.97420
  Classification -> best τ=0.730 (val F1=0.1773)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52425 | val 1.51553
  Epoch 013 - train 0.42621 | val 2.64139
  Classification -> best τ=0.270 (val F1=0.3140)
  Directional -> Accuracy: 0.5000, MCC: 0.0149, F1: 0.5152

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43535 | val 2.57466
  Epoch 011 - train 0.41908 | val 2.93697
  Classification -> best τ=0.670 (val F1=0.2701)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52209 | val 1.30049
  Epoch 011 - train 0.50129 | val 0.89804
  Classification -> best τ=0.630 (val F1=0.3251)
  Directional -> Accuracy: 0.6383, MCC: 0.1524, F1: 0.7671

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50404 | val 2.05832
  Epoch 012 - train 0.49486 | val 1.74650
  Classification -> best τ=0.540 (val F1=0.2192)
  Directional -> Accuracy: 0.4923, MCC: -0.0095, F1: 0.3529

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54951 | val 1.04667
  Epoch 011 - train 0.50482 | val 1.09402
  Classification -> best τ=0.530 (val F1=0.2147)
  Directional -> Accuracy: 0.4737, MCC: -0.0169, F1: 0.4231

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48367 | val 1.27717
  Epoch 011 - train 0.50867 | val 1.05088
  Classification -> best τ=0.655 (val F1=0.1565)
  Directional -> Accuracy: 0.5231, MCC: 0.0082, F1: 0.0606

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60320 | val 2.42889
  Epoch 013 - train 0.39149 | val 3.72156
  Classification -> best τ=0.615 (val F1=0.3786)
  Directional -> Accuracy: 0.4545, MCC: -0.0256, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43035 | val 2.60734
  Epoch 011 - train 0.38860 | val 3.21840
  Classification -> best τ=0.635 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55641 | val 1.16122
  Epoch 011 - train 0.52600 | val 1.30484
  Classification -> best τ=0.520 (val F1=0.0323)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46434 | val 1.65791
  Epoch 011 - train 0.43623 | val 1.68904
  Classification -> best τ=0.430 (val F1=0.1997)
  Directional -> Accuracy: 0.5714, MCC: 0.2952, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.34585 | val 2.90632
  Epoch 011 - train 0.35265 | val 3.38782
  Classification -> best τ=0.530 (val F1=0.4345)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39319 | val 1.34838
  Epoch 011 - train 0.37050 | val 1.44422
  Classification -> best τ=0.500 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.1489, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49717 | val 3.72798
  Epoch 012 - train 0.40403 | val 4.28668
  Classification -> best τ=0.555 (val F1=0.2357)
  Directional -> Accuracy: 0.5952, MCC: 0.2835, F1: 0.4848

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51970 | val 1.42489
  Epoch 013 - train 0.38122 | val 2.34004
  Classification -> best τ=0.430 (val F1=0.3991)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51761 | val 1.83359
  Epoch 011 - train 0.51575 | val 2.12330
  Classification -> best τ=0.700 (val F1=0.1838)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44216 | val 4.08045
  Epoch 011 - train 0.42552 | val 4.64949
  Classification -> best τ=0.465 (val F1=0.2780)
  Directional -> Accuracy: 0.5581, MCC: 0.1169, F1: 0.5581

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46986 | val 1.79344
  Epoch 011 - train 0.47193 | val 2.10864
  Classification -> best τ=0.540 (val F1=0.3254)
  Directional -> Accuracy: 0.4394, MCC: -0.0881, F1: 0.4127

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53201 | val 0.99232
  Epoch 014 - train 0.33988 | val 1.23036
  Classification -> best τ=0.480 (val F1=0.3321)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44331 | val 1.16124
  Epoch 011 - train 0.44119 | val 1.17305
  Classification -> best τ=0.380 (val F1=0.2327)
  Directional -> Accuracy: 0.4464, MCC: -0.0801, F1: 0.5753

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41489 | val 1.19899
  Epoch 011 - train 0.37710 | val 2.21503
  Classification -> best τ=0.575 (val F1=0.3771)
  Directional -> Accuracy: 0.4565, MCC: 0.0586, F1: 0.3243

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48317 | val 1.46046
  Epoch 015 - train 0.33711 | val 2.21134
  Classification -> best τ=0.350 (val F1=0.6022)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51723 | val 3.60916
  Epoch 011 - train 0.54420 | val 3.92598
  Classification -> best τ=0.495 (val F1=0.2982)
  Directional -> Accuracy: 0.4730, MCC: -0.0493, F1: 0.6061

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52128 | val 1.93788
  Epoch 012 - train 0.42517 | val 2.39541
  Classification -> best τ=0.435 (val F1=0.2874)
  Directional -> Accuracy: 0.4444, MCC: -0.1110, F1: 0.3243

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51317 | val 1.46543
  Epoch 016 - train 0.33413 | val 1.87733
  Classification -> best τ=0.365 (val F1=0.4277)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47784 | val 2.26420
  Epoch 015 - train 0.31451 | val 1.68499
  Classification -> best τ=0.690 (val F1=0.4606)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56060 | val 5.90769
  Epoch 011 - train 0.57276 | val 6.50610
  Classification -> best τ=0.320 (val F1=0.2981)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38329 | val 3.03970
  Epoch 011 - train 0.37449 | val 3.89908
  Classification -> best τ=0.580 (val F1=0.3249)
  Directional -> Accuracy: 0.5536, MCC: 0.1444, F1: 0.6377

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60054 | val 1.27498
  Epoch 012 - train 0.49788 | val 1.02670
  Classification -> best τ=0.585 (val F1=0.0705)
  Directional -> Accuracy: 0.4717, MCC: -0.0707, F1: 0.1250

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39429 | val 9.76844
  Epoch 012 - train 0.40918 | val 8.47711
  Classification -> best τ=0.770 (val F1=0.1254)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48008 | val 2.43332

[I 2026-02-20 04:49:10,441] Trial 168 finished with value: 0.2770185209906753 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.006678452058760804, 'weight_decay': 4.137396767701267e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5461925866847192, 'early_stopping_min_delta': 0.009790871734456714}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.44016 | val 2.21562
  Classification -> best τ=0.410 (val F1=0.2966)
  Directional -> Accuracy: 0.5000, MCC: 0.0034, F1: 0.5161

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2770185209906753
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58858 | val 0.96071
  Epoch 014 - train 0.46822 | val 0.90660
  Classification -> best τ=0.610 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0371, F1: 0.1818

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48846 | val 1.88555
  Epoch 011 - train 0.44000 | val 2.05672
  Classification -> best τ=0.570 (val F1=0.1764)
  Directional -> Accuracy: 0.4889, MCC: 0.0900, F1: 0.3429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53776 | val 1.03154
  Epoch 011 - train 0.50155 | val 1.16084
  Classification -> best τ=0.450 (val F1=0.4459)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55533 | val 1.26943
  Epoch 014 - train 0.45156 | val 1.46618
  Classification -> best τ=0.520 (val F1=0.1537)
  Directional -> Accuracy: 0.4865, MCC: 0.1537, F1: 0.0952

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49159 | val 1.57950
  Epoch 012 - train 0.42411 | val 1.77598
  Classification -> best τ=0.575 (val F1=0.4753)
  Directional -> Accuracy: 0.4000, MCC: -0.2065, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40490 | val 3.10026
  Epoch 011 - train 0.38277 | val 3.16638
  Classification -> best τ=0.530 (val F1=0.2739)
  Directional -> Accuracy: 0.5000, MCC: -0.0077, F1: 0.4390

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55990 | val 2.25621
  Epoch 012 - train 0.48582 | val 1.80371
  Classification -> best τ=0.580 (val F1=0.2835)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.4074

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43391 | val 3.86204
  Epoch 011 - train 0.39095 | val 5.40674
  Classification -> best τ=0.565 (val F1=0.3632)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.5106

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45035 | val 1.40358
  Epoch 014 - train 0.33332 | val 2.59540
  Classification -> best τ=0.455 (val F1=0.1975)
  Directional -> Accuracy: 0.5833, MCC: 0.1449, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45719 | val 1.72415
  Epoch 011 - train 0.44124 | val 2.49586
  Classification -> best τ=0.460 (val F1=0.1858)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47752 | val 0.67270
  Epoch 019 - train 0.29915 | val 0.61252
  Classification -> best τ=0.700 (val F1=0.4498)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46314 | val 4.72933
  Epoch 011 - train 0.45347 | val 4.81968
  Classification -> best τ=0.250 (val F1=0.1576)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39991 | val 4.24992
  Epoch 011 - train 0.33722 | val 4.55835
  Classification -> best τ=0.405 (val F1=0.1189)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57595 | val 0.75470
  Epoch 014 - train 0.47523 | val 0.85351
  Classification -> best τ=0.585 (val F1=0.3748)
  Directional -> Accuracy: 0.5667, MCC: 0.1576, F1: 0.4091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45158 | val 1.09416
  Epoch 011 - train 0.46129 | val 1.25628
  Classification -> best τ=0.445 (val F1=0.3067)
  Directional -> Accuracy: 0.4902, MCC: 0.0183, F1: 0.5517

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51232 | val 1.05439
  Epoch 013 - train 0.44127 | val 0.98889
  Classification -> best τ=0.320 (val F1=0.3067)
  Directional -> Accuracy: 0.6232, MCC: 0.2776, F1: 0.7292

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51025 | val 4.77024
  Epoch 011 - train 0.48603 | val 4.74237
  Classification -> best τ=0.580 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49059 | val 1.30819
  Epoch 012 - train 0.44024 | val 2.33676
  Classification -> best τ=0.440 (val F1=0.2128)
  Directional -> Accuracy: 0.4400, MCC: 0.1667, F1: 0.1250

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47388 | val 1.92949
  Epoch 011 - train 0.46877 | val 1.64310
  Classification -> best τ=0.445 (val F1=0.2359)
  Directional -> Accuracy: 0.5312, MCC: 0.0487, F1: 0.5833

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44483 | val 1.11282
  Epoch 011 - train 0.42818 | val 1.08512
  Classification -> best τ=0.560 (val F1=0.3162)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48940 | val 1.29169
  Epoch 011 - train 0.45828 | val 1.23926
  Classification -> best τ=0.490 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56105 | val 1.12552
  Epoch 012 - train 0.49486 | val 1.22761
  Classification -> best τ=0.505 (val F1=0.2037)
  Directional -> Accuracy: 0.6154, MCC: 0.2335, F1: 0.6575

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54149 | val 1.23145
  Epoch 011 - train 0.49888 | val 1.67479
  Classification -> best τ=0.570 (val F1=0.2944)
  Directional -> Accuracy: 0.5088, MCC: 0.0112, F1: 0.5484

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54281 | val 2.08834
  Epoch 011 - train 0.52131 | val 2.52424
  Classification -> best τ=0.615 (val F1=0.1985)
  Directional -> Accuracy: 0.5077, MCC: -0.0632, F1: 0.0588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50526 | val 1.41900
  Epoch 013 - train 0.41871 | val 2.25567
  Classification -> best τ=0.525 (val F1=0.4688)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41563 | val 2.28629
  Epoch 011 - train 0.38897 | val 2.01576
  Classification -> best τ=0.565 (val F1=0.2726)
  Directional -> Accuracy: 0.5333, MCC: 0.2428, F1: 0.6316

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52783 | val 1.50991
  Epoch 011 - train 0.50669 | val 1.04435
  Classification -> best τ=0.430 (val F1=0.1876)
  Directional -> Accuracy: 0.5952, MCC: 0.2439, F1: 0.5641

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.49046 | val 1.29232
  Epoch 011 - train 0.48730 | val 1.28005
  Classification -> best τ=0.370 (val F1=0.2315)
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42695 | val 2.63905
  Epoch 014 - train 0.32836 | val 2.86697
  Classification -> best τ=0.505 (val F1=0.2618)
  Directional -> Accuracy: 0.6500, MCC: 0.3237, F1: 0.7500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54567 | val 0.67125
  Epoch 020 - train 0.14718 | val 1.01071
  Epoch 021 - train 0.13250 | val 1.12187
  Classification -> best τ=0.625 (val F1=0.4846)
  Directional -> Accuracy: 0.4286, MCC: -0.1809, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54030 | val 2.44939
  Epoch 012 - train 0.52271 | val 2.83241
  Classification -> best τ=0.565 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44521 | val 1.44297
  Epoch 012 - train 0.41508 | val 1.32658
  Classification -> best τ=0.685 (val F1=0.2969)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55898 | val 2.43605
  Epoch 013 - train 0.47727 | val 2.57087
  Classification -> best τ=0.265 (val F1=0.3366)
  Directional -> Accuracy: 0.5278, MCC: 0.0905, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39638 | val 3.99825
  Epoch 011 - train 0.37720 | val 5.33616
  Classification -> best τ=0.540 (val F1=0.3385)
  Directional -> Accuracy: 0.6279, MCC: 0.2567, F1: 0.5789

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52486 | val 0.83353
  Epoch 012 - train 0.45816 | val 1.07998
  Classification -> best τ=0.365 (val F1=0.2972)
  Directional -> Accuracy: 0.6212, MCC: 0.2145, F1: 0.6835

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35999 | val 1.32032
  Epoch 011 - train 0.32810 | val 2.01260
  Classification -> best τ=0.505 (val F1=0.2292)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49853 | val 1.14007
  Epoch 011 - train 0.46795 | val 1.22212
  Classification -> best τ=0.415 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.1149, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48963 | val 0.88918
  Epoch 011 - train 0.48269 | val 1.37700
  Classification -> best τ=0.560 (val F1=0.4336)
  Directional -> Accuracy: 0.5652, MCC: -0.0153, F1: 0.6970

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43959 | val 0.86579
  Epoch 011 - train 0.46386 | val 0.84384
  Classification -> best τ=0.515 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54177 | val 1.99223
  Epoch 012 - train 0.48674 | val 2.50535
  Classification -> best τ=0.525 (val F1=0.2236)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43272 | val 1.49277
  Epoch 011 - train 0.40234 | val 2.02740
  Classification -> best τ=0.615 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.1613, F1: 0.6545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40265 | val 1.41139
  Epoch 011 - train 0.37597 | val 1.54769
  Classification -> best τ=0.515 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1291, F1: 0.1935

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52308 | val 1.29540
  Epoch 013 - train 0.36704 | val 1.15918
  Classification -> best τ=0.530 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.52842 | val 2.12593
  Epoch 011 - train 0.55467 | val 2.42758
  Classification -> best τ=0.505 (val F1=0.1508)
  Directional -> Accuracy: 0.4000, MCC: -0.2346, F1: 0.4923

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48510 | val 2.67492
  Epoch 011 - train 0.45980 | val 2.82784
  Classification -> best τ=0.635 (val F1=0.3432)
  Directional -> Accuracy: 0.5714, MCC: 0.2072, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57102 | val 0.96401
  Epoch 011 - train 0.51245 | val 1.06320
  Classification -> best τ=0.490 (val F1=0.1847)
  Directional -> Accuracy: 0.4717, MCC: -0.0800, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41209 | val 3.81129
  Epoch 011 - train 0.40232 | val 5.62198
  Classification -> best τ=0.690 (val F1=0.1186)
  Directional -> Accuracy: 0.4727, MCC: -0.0752, F1: 0.5538

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57425 | val 1.61535
  Epoch 013 - train 0.43014 | val 2.31885

[I 2026-02-20 04:52:27,944] Trial 169 finished with value: 0.282724376826139 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.003730517950146371, 'weight_decay': 2.8899148279397493e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5857171651812426, 'early_stopping_min_delta': 0.009770792541208141}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.435 (val F1=0.3297)
  Directional -> Accuracy: 0.5833, MCC: 0.1668, F1: 0.5763

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.282724376826139
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.73555 | val 0.81354
  Epoch 013 - train 0.48596 | val 1.35525
  Classification -> best τ=0.635 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52990 | val 2.17989
  Epoch 013 - train 0.39628 | val 2.66062
  Classification -> best τ=0.385 (val F1=0.1273)
  Directional -> Accuracy: 0.6222, MCC: 0.2030, F1: 0.7018

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54294 | val 1.88407
  Epoch 011 - train 0.55918 | val 1.91415
  Classification -> best τ=0.520 (val F1=0.3482)
  Directional -> Accuracy: 0.5217, MCC: 0.2041, F1: 0.1538

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51363 | val 1.83068
  Epoch 012 - train 0.48231 | val 0.80601
  Classification -> best τ=0.310 (val F1=0.2357)
  Directional -> Accuracy: 0.4595, MCC: -0.0932, F1: 0.5122

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51920 | val 1.44869
  Epoch 013 - train 0.39712 | val 7.98143
  Classification -> best τ=0.485 (val F1=0.4414)
  Directional -> Accuracy: 0.7200, MCC: 0.4423, F1: 0.7200

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40542 | val 1.26221
  Epoch 012 - train 0.35055 | val 1.55048
  Classification -> best τ=0.540 (val F1=0.1113)
  Directional -> Accuracy: 0.4130, MCC: -0.2018, F1: 0.2703

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51754 | val 2.20163
  Epoch 011 - train 0.51556 | val 1.61514
  Classification -> best τ=0.430 (val F1=0.2766)
  Directional -> Accuracy: 0.5147, MCC: 0.1115, F1: 0.5479

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43025 | val 1.66558
  Epoch 012 - train 0.30120 | val 2.79920
  Classification -> best τ=0.430 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47951 | val 1.98385
  Epoch 012 - train 0.40359 | val 5.34036
  Classification -> best τ=0.450 (val F1=0.2784)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42497 | val 2.89174
  Epoch 011 - train 0.40452 | val 3.56215
  Classification -> best τ=0.475 (val F1=0.1304)
  Directional -> Accuracy: 0.4348, MCC: 0.0376, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55881 | val 0.90566
  Epoch 014 - train 0.39585 | val 0.87602
  Classification -> best τ=0.590 (val F1=0.4916)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48222 | val 7.21727
  Epoch 011 - train 0.52454 | val 6.73342
  Classification -> best τ=0.440 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42260 | val 3.84121
  Epoch 011 - train 0.39303 | val 4.97972
  Classification -> best τ=0.680 (val F1=0.3114)
  Directional -> Accuracy: 0.4286, MCC: -0.1647, F1: 0.3333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59799 | val 0.87606
  Epoch 013 - train 0.49643 | val 1.48535
  Classification -> best τ=0.335 (val F1=0.3281)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44363 | val 0.96000
  Epoch 011 - train 0.41034 | val 0.87460
  Classification -> best τ=0.495 (val F1=0.0188)
  Directional -> Accuracy: 0.5686, MCC: 0.1225, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52320 | val 0.84377
  Epoch 012 - train 0.48237 | val 0.94233
  Classification -> best τ=0.305 (val F1=0.1512)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54742 | val 3.40386
  Epoch 012 - train 0.49846 | val 3.79053
  Classification -> best τ=0.610 (val F1=0.1913)
  Directional -> Accuracy: 0.4138, MCC: 0.0725, F1: 0.1500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50144 | val 2.53707
  Epoch 011 - train 0.48092 | val 2.29308
  Classification -> best τ=0.580 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55313 | val 1.55881
  Epoch 012 - train 0.46171 | val 1.80333
  Classification -> best τ=0.595 (val F1=0.2409)
  Directional -> Accuracy: 0.4844, MCC: 0.0187, F1: 0.4407

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48034 | val 1.88124
  Epoch 011 - train 0.46887 | val 1.85761
  Classification -> best τ=0.335 (val F1=0.2204)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64378 | val 0.81222
  Epoch 013 - train 0.42557 | val 1.11735
  Classification -> best τ=0.490 (val F1=0.3458)
  Directional -> Accuracy: 0.3404, MCC: -0.3135, F1: 0.3922

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50835 | val 2.04114
  Epoch 011 - train 0.53787 | val 1.63843
  Classification -> best τ=0.650 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51837 | val 1.19877
  Epoch 011 - train 0.48712 | val 1.52265
  Classification -> best τ=0.485 (val F1=0.1700)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49745 | val 1.48691
  Epoch 012 - train 0.45419 | val 2.23836
  Classification -> best τ=0.745 (val F1=0.2451)
  Directional -> Accuracy: 0.5231, MCC: 0.0147, F1: 0.1622

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56049 | val 1.14074
  Epoch 013 - train 0.45177 | val 1.69906
  Classification -> best τ=0.425 (val F1=0.4399)
  Directional -> Accuracy: 0.5091, MCC: 0.0913, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43340 | val 1.90139
  Epoch 011 - train 0.43290 | val 1.93132
  Classification -> best τ=0.615 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55498 | val 2.99268
  Epoch 011 - train 0.56442 | val 3.04721
  Classification -> best τ=0.450 (val F1=0.1291)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51362 | val 1.45922
  Epoch 012 - train 0.44092 | val 1.70816
  Classification -> best τ=0.380 (val F1=0.3143)
  Directional -> Accuracy: 0.5179, MCC: 0.1949, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53528 | val 1.20884
  Epoch 011 - train 0.33947 | val 2.24693
  Classification -> best τ=0.540 (val F1=0.2774)
  Directional -> Accuracy: 0.5250, MCC: 0.0553, F1: 0.5366

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48954 | val 0.77600
  Epoch 013 - train 0.45214 | val 1.20573
  Classification -> best τ=0.495 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: -0.0046, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.30368 | val 1.66280
  Epoch 011 - train 0.29763 | val 1.71257
  Classification -> best τ=0.615 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: -0.0391, F1: 0.2069

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47431 | val 1.13527
  Epoch 011 - train 0.40351 | val 1.30424
  Classification -> best τ=0.425 (val F1=0.3142)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52593 | val 4.26516
  Epoch 011 - train 0.50984 | val 3.88408
  Classification -> best τ=0.395 (val F1=0.2618)
  Directional -> Accuracy: 0.5556, MCC: 0.1487, F1: 0.5152

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44910 | val 2.88208
  Epoch 011 - train 0.40630 | val 3.43245
  Classification -> best τ=0.490 (val F1=0.2717)
  Directional -> Accuracy: 0.5116, MCC: 0.0179, F1: 0.4324

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45905 | val 1.43204
  Epoch 011 - train 0.42779 | val 1.66362
  Classification -> best τ=0.455 (val F1=0.4641)
  Directional -> Accuracy: 0.4545, MCC: -0.0045, F1: 0.3077

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36120 | val 1.73863
  Epoch 011 - train 0.32273 | val 2.09461
  Classification -> best τ=0.515 (val F1=0.2768)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48849 | val 2.00918
  Epoch 011 - train 0.50066 | val 1.59465
  Classification -> best τ=0.590 (val F1=0.1913)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46174 | val 1.73183
  Epoch 012 - train 0.38288 | val 1.31978
  Classification -> best τ=0.530 (val F1=0.2254)
  Directional -> Accuracy: 0.4565, MCC: 0.0086, F1: 0.3902

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48806 | val 1.04385
  Epoch 015 - train 0.37972 | val 1.80437
  Classification -> best τ=0.295 (val F1=0.6022)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56081 | val 3.19122
  Epoch 011 - train 0.50620 | val 3.79300
  Classification -> best τ=0.550 (val F1=0.1787)
  Directional -> Accuracy: 0.5135, MCC: 0.0910, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46052 | val 1.48358
  Epoch 013 - train 0.38895 | val 1.91690
  Classification -> best τ=0.640 (val F1=0.2000)
  Directional -> Accuracy: 0.5111, MCC: 0.0217, F1: 0.5217

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53361 | val 1.15470
  Epoch 018 - train 0.22848 | val 1.06629
  Classification -> best τ=0.655 (val F1=0.4971)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46395 | val 1.35196
  Epoch 017 - train 0.34322 | val 1.16250
  Classification -> best τ=0.730 (val F1=0.5421)
  Directional -> Accuracy: 0.3750, MCC: -0.1325, F1: 0.4643

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55208 | val 1.63182
  Epoch 011 - train 0.54942 | val 2.24592
  Classification -> best τ=0.455 (val F1=0.1210)
  Directional -> Accuracy: 0.4727, MCC: -0.1695, F1: 0.6234

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53728 | val 2.60910
  Epoch 011 - train 0.48106 | val 2.57655
  Classification -> best τ=0.300 (val F1=0.2696)
  Directional -> Accuracy: 0.5893, MCC: 0.2270, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51814 | val 1.16544
  Epoch 011 - train 0.50786 | val 1.43538
  Classification -> best τ=0.450 (val F1=0.2457)
  Directional -> Accuracy: 0.5472, MCC: 0.1134, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45828 | val 4.38532
  Epoch 012 - train 0.42058 | val 5.71116
  Classification -> best τ=0.400 (val F1=0.2448)
  Directional -> Accuracy: 0.5455, MCC: 0.0733, F1: 0.6479

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49570 | val 3.05565

[I 2026-02-20 04:55:43,106] Trial 170 finished with value: 0.2648812238937859 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.006745650715278951, 'weight_decay': 2.1108839208768767e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5586593831337255, 'early_stopping_min_delta': 0.009791474296028797}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.50545 | val 2.98542
  Classification -> best τ=0.445 (val F1=0.2231)
  Directional -> Accuracy: 0.5333, MCC: 0.1261, F1: 0.6500

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2648812238937859
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53718 | val 1.27197
  Epoch 012 - train 0.50460 | val 1.69590
  Classification -> best τ=0.400 (val F1=0.2836)
  Directional -> Accuracy: 0.4605, MCC: -0.0251, F1: 0.5591

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49237 | val 1.37391
  Epoch 011 - train 0.43917 | val 1.44384
  Classification -> best τ=0.565 (val F1=0.0492)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54239 | val 0.92918
  Epoch 011 - train 0.50081 | val 0.82544
  Classification -> best τ=0.460 (val F1=0.3673)
  Directional -> Accuracy: 0.5652, MCC: 0.1510, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52508 | val 1.02073
  Epoch 012 - train 0.49743 | val 1.17684
  Classification -> best τ=0.545 (val F1=0.1839)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46366 | val 0.86291
  Epoch 013 - train 0.43584 | val 1.05674
  Classification -> best τ=0.600 (val F1=0.4364)
  Directional -> Accuracy: 0.5400, MCC: 0.1375, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36284 | val 2.84016
  Epoch 011 - train 0.30992 | val 1.81512
  Classification -> best τ=0.505 (val F1=0.2739)
  Directional -> Accuracy: 0.4130, MCC: -0.2249, F1: 0.5714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57681 | val 1.36996
  Epoch 011 - train 0.52789 | val 1.35812
  Classification -> best τ=0.390 (val F1=0.3071)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39185 | val 3.80959
  Epoch 011 - train 0.36414 | val 4.36999
  Classification -> best τ=0.530 (val F1=0.0102)
  Directional -> Accuracy: 0.4524, MCC: -0.0700, F1: 0.4651

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47978 | val 1.42843
  Epoch 011 - train 0.41196 | val 1.94278
  Classification -> best τ=0.575 (val F1=0.2764)
  Directional -> Accuracy: 0.5833, MCC: 0.1302, F1: 0.4444

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49818 | val 1.23991
  Epoch 013 - train 0.41506 | val 2.02643
  Classification -> best τ=0.470 (val F1=0.3208)
  Directional -> Accuracy: 0.5217, MCC: 0.0232, F1: 0.4407

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51397 | val 0.73886
  Epoch 012 - train 0.44292 | val 0.66775
  Classification -> best τ=0.495 (val F1=0.4916)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71641 | val 2.67787
  Epoch 013 - train 0.45301 | val 3.91638
  Classification -> best τ=0.370 (val F1=0.2667)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41975 | val 2.70724
  Epoch 011 - train 0.37091 | val 3.20459
  Classification -> best τ=0.560 (val F1=0.2176)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.0909

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57557 | val 0.95930
  Epoch 015 - train 0.46180 | val 1.75485
  Classification -> best τ=0.280 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.2294, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47294 | val 3.01707
  Epoch 011 - train 0.42441 | val 2.45564
  Classification -> best τ=0.560 (val F1=0.1455)
  Directional -> Accuracy: 0.4902, MCC: -0.1325, F1: 0.1333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54965 | val 0.98572
  Epoch 011 - train 0.52701 | val 1.01870
  Classification -> best τ=0.790 (val F1=0.3858)
  Directional -> Accuracy: 0.5797, MCC: 0.1533, F1: 0.6133

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54198 | val 5.07653
  Epoch 011 - train 0.49916 | val 5.20659
  Classification -> best τ=0.610 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49594 | val 1.87491
  Epoch 011 - train 0.49449 | val 2.17105
  Classification -> best τ=0.415 (val F1=0.1621)
  Directional -> Accuracy: 0.5333, MCC: 0.0546, F1: 0.5882

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54593 | val 1.51753
  Epoch 013 - train 0.46205 | val 1.74304
  Classification -> best τ=0.510 (val F1=0.2626)
  Directional -> Accuracy: 0.4844, MCC: 0.2206, F1: 0.1951

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44888 | val 1.00433
  Epoch 011 - train 0.46540 | val 1.30351
  Classification -> best τ=0.400 (val F1=0.1771)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56221 | val 0.97070
  Epoch 014 - train 0.43723 | val 1.05766
  Classification -> best τ=0.560 (val F1=0.2818)
  Directional -> Accuracy: 0.3830, MCC: -0.1090, F1: 0.2162

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51426 | val 2.19480
  Epoch 011 - train 0.50817 | val 1.85489
  Classification -> best τ=0.550 (val F1=0.1925)
  Directional -> Accuracy: 0.4615, MCC: -0.1112, F1: 0.1026

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52881 | val 1.45863
  Epoch 011 - train 0.50995 | val 1.60505
  Classification -> best τ=0.490 (val F1=0.1326)
  Directional -> Accuracy: 0.5263, MCC: 0.0255, F1: 0.5970

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47280 | val 5.01634
  Epoch 011 - train 0.45937 | val 4.71929
  Classification -> best τ=0.530 (val F1=0.1313)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43631 | val 1.10258
  Epoch 012 - train 0.40226 | val 1.09096
  Classification -> best τ=0.540 (val F1=0.4075)
  Directional -> Accuracy: 0.5091, MCC: 0.1077, F1: 0.3077

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38697 | val 2.60192
  Epoch 011 - train 0.40348 | val 2.67573
  Classification -> best τ=0.570 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51814 | val 1.29171
  Epoch 011 - train 0.48025 | val 1.29332
  Classification -> best τ=0.475 (val F1=0.2178)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47414 | val 1.19643
  Epoch 011 - train 0.45985 | val 1.28635
  Classification -> best τ=0.445 (val F1=0.1771)
  Directional -> Accuracy: 0.6071, MCC: 0.1883, F1: 0.6857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37519 | val 3.31080
  Epoch 011 - train 0.38712 | val 3.55066
  Classification -> best τ=0.485 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1111, F1: 0.5500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45618 | val 2.89568
  Epoch 011 - train 0.46830 | val 2.75850
  Classification -> best τ=0.500 (val F1=0.2102)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47934 | val 7.73255
  Epoch 012 - train 0.37535 | val 8.65390
  Classification -> best τ=0.585 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50045 | val 1.06154
  Epoch 011 - train 0.46960 | val 1.16792
  Classification -> best τ=0.500 (val F1=0.4778)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49436 | val 2.03344
  Epoch 011 - train 0.50133 | val 2.28779
  Classification -> best τ=0.480 (val F1=0.2001)
  Directional -> Accuracy: 0.5278, MCC: 0.1750, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55321 | val 3.82123
  Epoch 013 - train 0.39381 | val 3.77164
  Classification -> best τ=0.390 (val F1=0.4228)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48689 | val 0.86967
  Epoch 013 - train 0.37765 | val 1.15712
  Classification -> best τ=0.315 (val F1=0.3525)
  Directional -> Accuracy: 0.5909, MCC: 0.1666, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41862 | val 1.81514
  Epoch 014 - train 0.36057 | val 2.55744
  Classification -> best τ=0.520 (val F1=0.3287)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54111 | val 1.36350
  Epoch 011 - train 0.49379 | val 1.51995
  Classification -> best τ=0.495 (val F1=0.2110)
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43023 | val 0.82980
  Epoch 011 - train 0.40203 | val 0.96317
  Classification -> best τ=0.510 (val F1=0.2441)
  Directional -> Accuracy: 0.5870, MCC: 0.1074, F1: 0.6780

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49585 | val 0.77220
  Epoch 012 - train 0.42616 | val 0.91529
  Classification -> best τ=0.410 (val F1=0.3090)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50740 | val 2.36995
  Epoch 011 - train 0.46212 | val 2.67974
  Classification -> best τ=0.410 (val F1=0.2996)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44011 | val 1.47780
  Epoch 011 - train 0.41337 | val 1.32641
  Classification -> best τ=0.500 (val F1=0.3371)
  Directional -> Accuracy: 0.4444, MCC: -0.1395, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35595 | val 1.32833
  Epoch 011 - train 0.32682 | val 1.46020
  Classification -> best τ=0.535 (val F1=0.3333)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48143 | val 0.91113
  Epoch 014 - train 0.30198 | val 0.89332
  Classification -> best τ=0.565 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54670 | val 2.04221
  Epoch 011 - train 0.54668 | val 2.41287
  Classification -> best τ=0.545 (val F1=0.1154)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46900 | val 3.57756
  Epoch 011 - train 0.44976 | val 3.70450
  Classification -> best τ=0.745 (val F1=0.2680)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50057 | val 1.08521
  Epoch 011 - train 0.45807 | val 1.11097
  Classification -> best τ=0.525 (val F1=0.0932)
  Directional -> Accuracy: 0.3774, MCC: -0.2591, F1: 0.2326

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43071 | val 4.13574
  Epoch 011 - train 0.43577 | val 4.43003
  Classification -> best τ=0.725 (val F1=0.0580)
  Directional -> Accuracy: 0.4000, MCC: -0.1976, F1: 0.4000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48567 | val 2.35222

[I 2026-02-20 04:58:56,438] Trial 171 finished with value: 0.2559228229170283 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0036576446933484475, 'weight_decay': 3.070129639858422e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5159761014191495, 'early_stopping_min_delta': 0.00964369897772793}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.46131 | val 1.99929
  Classification -> best τ=0.495 (val F1=0.0473)
  Directional -> Accuracy: 0.5833, MCC: 0.1965, F1: 0.6479

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2559228229170283
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63743 | val 0.70797
  Epoch 014 - train 0.51081 | val 0.79331
  Classification -> best τ=0.420 (val F1=0.2919)
  Directional -> Accuracy: 0.4737, MCC: -0.0092, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41957 | val 1.96527
  Epoch 012 - train 0.41570 | val 2.35822
  Classification -> best τ=0.310 (val F1=0.1844)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.1429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52413 | val 0.89291
  Epoch 012 - train 0.51377 | val 0.85623
  Classification -> best τ=0.485 (val F1=0.3308)
  Directional -> Accuracy: 0.5652, MCC: 0.1679, F1: 0.6970

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50974 | val 2.32356
  Epoch 011 - train 0.50118 | val 2.05494
  Classification -> best τ=0.565 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49947 | val 1.65956
  Epoch 012 - train 0.45322 | val 1.67426
  Classification -> best τ=0.495 (val F1=0.5167)
  Directional -> Accuracy: 0.7400, MCC: 0.4931, F1: 0.7234

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40454 | val 1.08947
  Epoch 012 - train 0.34277 | val 1.41174
  Classification -> best τ=0.520 (val F1=0.2699)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.1538

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46618 | val 2.13467
  Epoch 012 - train 0.41078 | val 1.77303
  Classification -> best τ=0.850 (val F1=0.2102)
  Directional -> Accuracy: 0.6029, MCC: 0.0974, F1: 0.3077

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39114 | val 1.29687
  Epoch 011 - train 0.39168 | val 1.14458
  Classification -> best τ=0.415 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44135 | val 1.78088
  Epoch 012 - train 0.39271 | val 2.01186
  Classification -> best τ=0.475 (val F1=0.2771)
  Directional -> Accuracy: 0.6458, MCC: 0.2656, F1: 0.5143

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44313 | val 2.50898
  Epoch 012 - train 0.40303 | val 2.95592
  Classification -> best τ=0.500 (val F1=0.1424)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53962 | val 0.68751
  Epoch 017 - train 0.36118 | val 0.72546
  Classification -> best τ=0.490 (val F1=0.3590)
  Directional -> Accuracy: 0.5102, MCC: -0.0499, F1: 0.2500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52319 | val 2.99032
  Epoch 011 - train 0.48317 | val 3.75554
  Classification -> best τ=0.515 (val F1=0.2428)
  Directional -> Accuracy: 0.6140, MCC: 0.2320, F1: 0.5926

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42166 | val 1.03067
  Epoch 013 - train 0.31992 | val 2.64674
  Classification -> best τ=0.680 (val F1=0.2942)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.73510 | val 0.66900
  Epoch 013 - train 0.51203 | val 1.01787
  Classification -> best τ=0.400 (val F1=0.3584)
  Directional -> Accuracy: 0.5167, MCC: 0.0467, F1: 0.6420

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49753 | val 1.08579
  Epoch 012 - train 0.41135 | val 1.93999
  Classification -> best τ=0.495 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49348 | val 0.87931
  Epoch 011 - train 0.45886 | val 0.99367
  Classification -> best τ=0.455 (val F1=0.1823)
  Directional -> Accuracy: 0.5507, MCC: 0.0764, F1: 0.6931

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52347 | val 3.67687
  Epoch 011 - train 0.55861 | val 3.24778
  Classification -> best τ=0.610 (val F1=0.1842)
  Directional -> Accuracy: 0.5345, MCC: 0.2183, F1: 0.4706

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48243 | val 1.63270
  Epoch 011 - train 0.48622 | val 2.38887
  Classification -> best τ=0.425 (val F1=0.2220)
  Directional -> Accuracy: 0.3867, MCC: -0.1653, F1: 0.3235

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49057 | val 1.62212
  Epoch 012 - train 0.45215 | val 1.84793
  Classification -> best τ=0.385 (val F1=0.2428)
  Directional -> Accuracy: 0.5000, MCC: -0.0355, F1: 0.5789

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45428 | val 1.96646
  Epoch 011 - train 0.40737 | val 2.30878
  Classification -> best τ=0.455 (val F1=0.1849)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56354 | val 1.02458
  Epoch 016 - train 0.39911 | val 2.19673
  Classification -> best τ=0.335 (val F1=0.3308)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.49559 | val 1.95381
  Epoch 012 - train 0.45537 | val 1.75796
  Classification -> best τ=0.460 (val F1=0.2830)
  Directional -> Accuracy: 0.4769, MCC: -0.0464, F1: 0.4848

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53471 | val 1.47718
  Epoch 011 - train 0.51199 | val 1.38860
  Classification -> best τ=0.665 (val F1=0.2345)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49219 | val 4.25402
  Epoch 011 - train 0.48701 | val 3.82978
  Classification -> best τ=0.740 (val F1=0.0193)
  Directional -> Accuracy: 0.4923, MCC: -0.1163, F1: 0.0571

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46777 | val 1.48459
  Epoch 013 - train 0.36831 | val 1.67108
  Classification -> best τ=0.495 (val F1=0.4973)
  Directional -> Accuracy: 0.5091, MCC: 0.0913, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44115 | val 3.11896
  Epoch 011 - train 0.40871 | val 2.75972
  Classification -> best τ=0.680 (val F1=0.2097)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54509 | val 0.78876
  Epoch 011 - train 0.49045 | val 0.82181
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46047 | val 1.52228
  Epoch 011 - train 0.44424 | val 1.48648
  Classification -> best τ=0.275 (val F1=0.3155)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37512 | val 3.55969
  Epoch 011 - train 0.35518 | val 3.78362
  Classification -> best τ=0.555 (val F1=0.1918)
  Directional -> Accuracy: 0.4750, MCC: -0.0056, F1: 0.3636

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45498 | val 1.30580
  Epoch 011 - train 0.44398 | val 1.84665
  Classification -> best τ=0.465 (val F1=0.2764)
  Directional -> Accuracy: 0.5238, MCC: 0.0853, F1: 0.6154

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51673 | val 2.07386
  Epoch 013 - train 0.39394 | val 1.91022
  Classification -> best τ=0.460 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44374 | val 1.47764
  Epoch 011 - train 0.44375 | val 1.38606
  Classification -> best τ=0.425 (val F1=0.2150)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55187 | val 1.77805
  Epoch 011 - train 0.56285 | val 2.03760
  Classification -> best τ=0.330 (val F1=0.2676)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47807 | val 2.53385
  Epoch 011 - train 0.44995 | val 4.08675
  Classification -> best τ=0.600 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54061 | val 0.89376
  Epoch 012 - train 0.47450 | val 0.83834
  Classification -> best τ=0.435 (val F1=0.3855)
  Directional -> Accuracy: 0.7273, MCC: 0.4758, F1: 0.7353

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37822 | val 1.53842
  Epoch 011 - train 0.33171 | val 1.85617
  Classification -> best τ=0.450 (val F1=0.2439)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45507 | val 2.36315
  Epoch 011 - train 0.46074 | val 2.54145
  Classification -> best τ=0.545 (val F1=0.2332)
  Directional -> Accuracy: 0.6250, MCC: 0.2514, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43012 | val 1.04286
  Epoch 011 - train 0.38889 | val 1.21641
  Classification -> best τ=0.460 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47905 | val 0.82318
  Epoch 013 - train 0.39307 | val 0.96031
  Classification -> best τ=0.545 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50598 | val 2.54107
  Epoch 011 - train 0.51594 | val 2.75513
  Classification -> best τ=0.435 (val F1=0.2542)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43996 | val 2.48019
  Epoch 012 - train 0.38774 | val 2.48534
  Classification -> best τ=0.430 (val F1=0.4375)
  Directional -> Accuracy: 0.4667, MCC: -0.1221, F1: 0.6129

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44699 | val 1.06046
  Epoch 016 - train 0.28855 | val 1.97364
  Classification -> best τ=0.685 (val F1=0.3612)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50208 | val 0.82116
  Epoch 018 - train 0.23434 | val 1.17045
  Classification -> best τ=0.730 (val F1=0.5689)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56806 | val 5.70658
  Epoch 011 - train 0.52774 | val 4.74168
  Classification -> best τ=0.425 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43213 | val 2.03148
  Epoch 011 - train 0.41139 | val 2.82449
  Classification -> best τ=0.575 (val F1=0.2143)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57415 | val 0.98381
  Epoch 012 - train 0.46109 | val 1.01426
  Classification -> best τ=0.575 (val F1=0.1126)
  Directional -> Accuracy: 0.4717, MCC: -0.0707, F1: 0.1250

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43650 | val 7.01620
  Epoch 012 - train 0.38722 | val 9.53527
  Classification -> best τ=0.860 (val F1=0.1884)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48720 | val 2.84230

[I 2026-02-20 05:02:20,033] Trial 172 finished with value: 0.26039537543195973 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.005020853897940507, 'weight_decay': 4.3580375167090407e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6433408836992182, 'early_stopping_min_delta': 0.009858714314641864}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.45545 | val 2.79962
  Classification -> best τ=0.460 (val F1=0.2637)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26039537543195973
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57230 | val 0.67763
  Epoch 012 - train 0.54366 | val 0.82339
  Classification -> best τ=0.430 (val F1=0.2036)
  Directional -> Accuracy: 0.5132, MCC: -0.0693, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52839 | val 2.10092
  Epoch 012 - train 0.43371 | val 1.32292
  Classification -> best τ=0.515 (val F1=0.0492)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59940 | val 0.69448
  Epoch 013 - train 0.58001 | val 0.95119
  Classification -> best τ=0.505 (val F1=0.3262)
  Directional -> Accuracy: 0.5000, MCC: -0.0547, F1: 0.6462

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52715 | val 2.62489
  Epoch 011 - train 0.50802 | val 3.03261
  Classification -> best τ=0.430 (val F1=0.2056)
  Directional -> Accuracy: 0.4730, MCC: 0.0041, F1: 0.2353

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49623 | val 1.95686
  Epoch 012 - train 0.44060 | val 2.19222
  Classification -> best τ=0.560 (val F1=0.5169)
  Directional -> Accuracy: 0.6600, MCC: 0.3200, F1: 0.7018

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44873 | val 1.15573
  Epoch 012 - train 0.34647 | val 0.93469
  Classification -> best τ=0.485 (val F1=0.2912)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.1538

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53871 | val 1.92830
  Epoch 011 - train 0.53472 | val 1.91336
  Classification -> best τ=0.300 (val F1=0.2605)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45095 | val 1.68062
  Epoch 011 - train 0.38584 | val 1.98929
  Classification -> best τ=0.510 (val F1=0.2753)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51562 | val 2.15449
  Epoch 011 - train 0.43595 | val 2.09094
  Classification -> best τ=0.560 (val F1=0.3616)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49414 | val 1.63649
  Epoch 012 - train 0.44755 | val 1.90218
  Classification -> best τ=0.300 (val F1=0.2667)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56491 | val 0.66400
  Epoch 016 - train 0.37398 | val 0.97785
  Classification -> best τ=0.755 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45654 | val 4.70908
  Epoch 011 - train 0.44049 | val 6.43258
  Classification -> best τ=0.535 (val F1=0.2962)
  Directional -> Accuracy: 0.6667, MCC: 0.3337, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45998 | val 3.07611
  Epoch 011 - train 0.37895 | val 2.27286
  Classification -> best τ=0.490 (val F1=0.1475)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61447 | val 0.91118
  Epoch 014 - train 0.47752 | val 0.87750
  Classification -> best τ=0.220 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49311 | val 1.14739
  Epoch 012 - train 0.46861 | val 2.26651
  Classification -> best τ=0.445 (val F1=0.3469)
  Directional -> Accuracy: 0.4706, MCC: -0.0572, F1: 0.4490

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54548 | val 1.10799
  Epoch 012 - train 0.50117 | val 1.02129
  Classification -> best τ=0.360 (val F1=0.2659)
  Directional -> Accuracy: 0.6377, MCC: 0.2951, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58418 | val 4.50630
  Epoch 012 - train 0.57799 | val 4.91353
  Classification -> best τ=0.485 (val F1=0.1387)
  Directional -> Accuracy: 0.5690, MCC: -0.1826, F1: 0.7253

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60549 | val 1.13961
  Epoch 013 - train 0.47421 | val 1.10391
  Classification -> best τ=0.690 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50226 | val 1.77885
  Epoch 013 - train 0.45670 | val 2.42208
  Classification -> best τ=0.465 (val F1=0.2327)
  Directional -> Accuracy: 0.4531, MCC: 0.0577, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50015 | val 1.32985
  Epoch 013 - train 0.41622 | val 1.51719
  Classification -> best τ=0.600 (val F1=0.2701)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52627 | val 0.98399
  Epoch 011 - train 0.48722 | val 0.87644
  Classification -> best τ=0.530 (val F1=0.2295)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53726 | val 0.97502
  Epoch 011 - train 0.49739 | val 1.07689
  Classification -> best τ=0.570 (val F1=0.1482)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55468 | val 1.36283
  Epoch 011 - train 0.54442 | val 1.83135
  Classification -> best τ=0.540 (val F1=0.2109)
  Directional -> Accuracy: 0.4386, MCC: -0.0981, F1: 0.4074

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52557 | val 4.32809
  Epoch 011 - train 0.49060 | val 4.03772
  Classification -> best τ=0.625 (val F1=0.1565)
  Directional -> Accuracy: 0.5692, MCC: 0.1366, F1: 0.5484

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49407 | val 1.22556
  Epoch 011 - train 0.46313 | val 1.41992
  Classification -> best τ=0.520 (val F1=0.3889)
  Directional -> Accuracy: 0.4727, MCC: 0.0585, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51367 | val 5.48255
  Epoch 011 - train 0.48965 | val 6.37710
  Classification -> best τ=0.560 (val F1=0.2097)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55326 | val 1.55364
  Epoch 011 - train 0.56995 | val 1.47779
  Classification -> best τ=0.490 (val F1=0.0323)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53545 | val 1.31182
  Epoch 011 - train 0.52987 | val 1.42612
  Classification -> best τ=0.465 (val F1=0.1706)
  Directional -> Accuracy: 0.5714, MCC: 0.0950, F1: 0.7000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45896 | val 3.65636
  Epoch 011 - train 0.43561 | val 4.06979
  Classification -> best τ=0.515 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52303 | val 0.85077
  Epoch 020 - train 0.22134 | val 0.68610
  Epoch 021 - train 0.15192 | val 0.71017
  Classification -> best τ=0.380 (val F1=0.4083)
  Directional -> Accuracy: 0.4286, MCC: -0.2530, F1: 0.0769

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51101 | val 1.50610
  Epoch 012 - train 0.51590 | val 1.57849
  Classification -> best τ=0.520 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52568 | val 1.26473
  Epoch 011 - train 0.47962 | val 1.32392
  Classification -> best τ=0.490 (val F1=0.3541)
  Directional -> Accuracy: 0.4490, MCC: -0.0851, F1: 0.3415

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59531 | val 1.90618
  Epoch 013 - train 0.52090 | val 2.05811
  Classification -> best τ=0.305 (val F1=0.3815)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40563 | val 2.42229
  Epoch 011 - train 0.41398 | val 3.61237
  Classification -> best τ=0.540 (val F1=0.2151)
  Directional -> Accuracy: 0.5116, MCC: 0.0074, F1: 0.1600

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50138 | val 0.88764
  Epoch 012 - train 0.46946 | val 0.85586
  Classification -> best τ=0.310 (val F1=0.3525)
  Directional -> Accuracy: 0.5455, MCC: 0.0045, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42722 | val 1.57258
  Epoch 011 - train 0.39523 | val 1.69248
  Classification -> best τ=0.415 (val F1=0.1857)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53371 | val 0.99083
  Epoch 011 - train 0.49386 | val 1.02248
  Classification -> best τ=0.525 (val F1=0.2382)
  Directional -> Accuracy: 0.4286, MCC: -0.2067, F1: 0.2000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45898 | val 1.08025
  Epoch 011 - train 0.43364 | val 0.96993
  Classification -> best τ=0.500 (val F1=0.2852)
  Directional -> Accuracy: 0.5652, MCC: 0.0309, F1: 0.6774

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48258 | val 0.94649
  Epoch 017 - train 0.40216 | val 1.05452
  Classification -> best τ=0.215 (val F1=0.6022)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49363 | val 3.53403
  Epoch 011 - train 0.50213 | val 3.65597
  Classification -> best τ=0.525 (val F1=0.4668)
  Directional -> Accuracy: 0.4865, MCC: -0.0153, F1: 0.5870

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55282 | val 2.52749
  Epoch 013 - train 0.43032 | val 1.58857
  Classification -> best τ=0.530 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37962 | val 1.09706
  Epoch 011 - train 0.39741 | val 1.20979
  Classification -> best τ=0.495 (val F1=0.2100)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54156 | val 1.05873
  Epoch 013 - train 0.37686 | val 1.11710
  Classification -> best τ=0.720 (val F1=0.3895)
  Directional -> Accuracy: 0.3958, MCC: -0.0176, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61296 | val 2.34600
  Epoch 011 - train 0.57101 | val 2.23648
  Classification -> best τ=0.510 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43963 | val 2.57154
  Epoch 011 - train 0.43057 | val 3.29159
  Classification -> best τ=0.650 (val F1=0.3491)
  Directional -> Accuracy: 0.5536, MCC: 0.1284, F1: 0.6154

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54122 | val 1.72217
  Epoch 011 - train 0.54181 | val 2.54208
  Classification -> best τ=0.560 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1005, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47400 | val 5.61546
  Epoch 012 - train 0.46031 | val 5.59678
  Classification -> best τ=0.865 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: -0.0892, F1: 0.5797

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51950 | val 1.50609

[I 2026-02-20 05:05:42,142] Trial 173 finished with value: 0.265276200185412 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.004236571226054918, 'weight_decay': 2.7007805458286595e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5769123710525152, 'early_stopping_min_delta': 0.009971227994905405}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.48446 | val 1.27301
  Classification -> best τ=0.375 (val F1=0.0569)
  Directional -> Accuracy: 0.4667, MCC: -0.0766, F1: 0.3846

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.265276200185412
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60444 | val 0.79391
  Epoch 011 - train 0.55003 | val 0.67522
  Classification -> best τ=0.475 (val F1=0.2771)
  Directional -> Accuracy: 0.5000, MCC: -0.0993, F1: 0.1739

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61230 | val 1.46707
  Epoch 013 - train 0.38482 | val 2.59662
  Classification -> best τ=0.590 (val F1=0.2523)
  Directional -> Accuracy: 0.5778, MCC: 0.2021, F1: 0.5581

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61705 | val 0.83706
  Epoch 012 - train 0.55152 | val 1.12345
  Classification -> best τ=0.465 (val F1=0.1723)
  Directional -> Accuracy: 0.4783, MCC: -0.0658, F1: 0.5714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53749 | val 1.49479
  Epoch 011 - train 0.55541 | val 2.99105
  Classification -> best τ=0.410 (val F1=0.2312)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52033 | val 1.09195
  Epoch 012 - train 0.41436 | val 1.16704
  Classification -> best τ=0.615 (val F1=0.3968)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40610 | val 3.53050
  Epoch 011 - train 0.34331 | val 3.93770
  Classification -> best τ=0.510 (val F1=0.1235)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52694 | val 2.14993
  Epoch 012 - train 0.46315 | val 2.55440
  Classification -> best τ=0.165 (val F1=0.2280)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44910 | val 1.60175
  Epoch 011 - train 0.35563 | val 2.32010
  Classification -> best τ=0.445 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47317 | val 1.34384
  Epoch 011 - train 0.42174 | val 1.61186
  Classification -> best τ=0.530 (val F1=0.4025)
  Directional -> Accuracy: 0.5208, MCC: -0.1839, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50498 | val 1.33893
  Epoch 012 - train 0.44538 | val 1.49564
  Classification -> best τ=0.515 (val F1=0.1552)
  Directional -> Accuracy: 0.5217, MCC: 0.0811, F1: 0.5352

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62106 | val 1.02373
  Epoch 015 - train 0.40978 | val 1.73622
  Classification -> best τ=0.515 (val F1=0.4037)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55881 | val 2.03908
  Epoch 012 - train 0.51136 | val 2.76827
  Classification -> best τ=0.450 (val F1=0.2667)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46518 | val 1.76971
  Epoch 012 - train 0.38468 | val 2.05982
  Classification -> best τ=0.505 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55909 | val 1.03321
  Epoch 011 - train 0.55953 | val 0.95354
  Classification -> best τ=0.230 (val F1=0.3635)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53887 | val 1.16331
  Epoch 014 - train 0.45222 | val 1.20620
  Classification -> best τ=0.420 (val F1=0.2732)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60651 | val 1.00985
  Epoch 014 - train 0.47081 | val 1.37010
  Classification -> best τ=0.215 (val F1=0.3589)
  Directional -> Accuracy: 0.6667, MCC: 0.3889, F1: 0.7579

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57091 | val 3.06740
  Epoch 011 - train 0.56886 | val 3.06619
  Classification -> best τ=0.380 (val F1=0.1336)
  Directional -> Accuracy: 0.6552, MCC: 0.2079, F1: 0.7778

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54661 | val 1.10130
  Epoch 012 - train 0.50731 | val 1.21745
  Classification -> best τ=0.395 (val F1=0.2177)
  Directional -> Accuracy: 0.5733, MCC: 0.3120, F1: 0.4839

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54572 | val 1.02150
  Epoch 013 - train 0.50937 | val 1.39908
  Classification -> best τ=0.455 (val F1=0.3305)
  Directional -> Accuracy: 0.5000, MCC: -0.0579, F1: 0.6000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51919 | val 1.55322
  Epoch 011 - train 0.52476 | val 1.51273
  Classification -> best τ=0.385 (val F1=0.1180)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50263 | val 0.76223
  Epoch 012 - train 0.47739 | val 1.60188
  Classification -> best τ=0.630 (val F1=0.3262)
  Directional -> Accuracy: 0.5106, MCC: -0.2718, F1: 0.6761

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55290 | val 24.66819
  Epoch 011 - train 0.50651 | val 28.89738
  Classification -> best τ=0.385 (val F1=0.0063)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59336 | val 1.09798
  Epoch 012 - train 0.52679 | val 1.38258
  Classification -> best τ=0.550 (val F1=0.2010)
  Directional -> Accuracy: 0.5439, MCC: -0.0241, F1: 0.6905

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54226 | val 3.93328
  Epoch 011 - train 0.53049 | val 2.68043
  Classification -> best τ=0.540 (val F1=0.0829)
  Directional -> Accuracy: 0.4615, MCC: -0.0631, F1: 0.5977

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58279 | val 2.05207
  Epoch 013 - train 0.44342 | val 2.27974
  Classification -> best τ=0.790 (val F1=0.4450)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50859 | val 1.66588
  Epoch 011 - train 0.44507 | val 1.83682
  Classification -> best τ=0.625 (val F1=0.3407)
  Directional -> Accuracy: 0.5333, MCC: 0.3022, F1: 0.6441

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55082 | val 1.79616
  Epoch 011 - train 0.52162 | val 1.78942
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50826 | val 1.38348
  Epoch 011 - train 0.49591 | val 1.49016
  Classification -> best τ=0.315 (val F1=0.2665)
  Directional -> Accuracy: 0.6607, MCC: 0.3111, F1: 0.7397

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40226 | val 0.99589
  Epoch 011 - train 0.43774 | val 1.04116
  Classification -> best τ=0.690 (val F1=0.1918)
  Directional -> Accuracy: 0.4750, MCC: 0.0380, F1: 0.2222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50723 | val 1.07150
  Epoch 013 - train 0.46032 | val 1.19581
  Classification -> best τ=0.500 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41599 | val 1.07973
  Epoch 013 - train 0.35478 | val 2.77610
  Classification -> best τ=0.745 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: -0.0605, F1: 0.3429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46910 | val 1.38560
  Epoch 011 - train 0.45503 | val 1.13604
  Classification -> best τ=0.340 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58353 | val 2.40724
  Epoch 011 - train 0.59083 | val 1.95743
  Classification -> best τ=0.250 (val F1=0.4032)
  Directional -> Accuracy: 0.5278, MCC: 0.0688, F1: 0.5278

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47497 | val 3.74711
  Epoch 011 - train 0.49729 | val 4.81115
  Classification -> best τ=0.750 (val F1=0.1334)
  Directional -> Accuracy: 0.4884, MCC: -0.0849, F1: 0.0833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57505 | val 1.18681
  Epoch 017 - train 0.36889 | val 1.43278
  Classification -> best τ=0.690 (val F1=0.3796)
  Directional -> Accuracy: 0.4697, MCC: 0.0397, F1: 0.3137

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40991 | val 2.01702
  Epoch 012 - train 0.37020 | val 2.34726
  Classification -> best τ=0.535 (val F1=0.3589)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56086 | val 1.15869
  Epoch 012 - train 0.48758 | val 1.16056
  Classification -> best τ=0.540 (val F1=0.2724)
  Directional -> Accuracy: 0.5536, MCC: 0.1100, F1: 0.5455

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46744 | val 1.50533
  Epoch 013 - train 0.38463 | val 3.29397
  Classification -> best τ=0.675 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56683 | val 0.92876
  Epoch 015 - train 0.41327 | val 0.99338
  Classification -> best τ=0.300 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52952 | val 1.87472
  Epoch 011 - train 0.50104 | val 2.78385
  Classification -> best τ=0.450 (val F1=0.3337)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51188 | val 1.31187
  Epoch 013 - train 0.43920 | val 1.38974
  Classification -> best τ=0.565 (val F1=0.2874)
  Directional -> Accuracy: 0.4444, MCC: -0.1139, F1: 0.2857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52581 | val 1.07229
  Epoch 013 - train 0.38297 | val 1.61531
  Classification -> best τ=0.390 (val F1=0.3118)
  Directional -> Accuracy: 0.5714, MCC: 0.2041, F1: 0.5263

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43224 | val 1.08796
  Epoch 012 - train 0.41031 | val 0.94192
  Classification -> best τ=0.800 (val F1=0.1371)
  Directional -> Accuracy: 0.5625, MCC: 0.0562, F1: 0.4000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58508 | val 3.91242
  Epoch 011 - train 0.58273 | val 3.51530
  Classification -> best τ=0.565 (val F1=0.1769)
  Directional -> Accuracy: 0.3455, MCC: -0.3950, F1: 0.4857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47886 | val 2.57837
  Epoch 011 - train 0.45012 | val 3.39090
  Classification -> best τ=0.705 (val F1=0.1477)
  Directional -> Accuracy: 0.5893, MCC: 0.2147, F1: 0.6567

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51661 | val 0.96064
  Epoch 011 - train 0.51187 | val 0.93177
  Classification -> best τ=0.620 (val F1=0.3104)
  Directional -> Accuracy: 0.5094, MCC: 0.0067, F1: 0.6486

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52811 | val 7.18437
  Epoch 012 - train 0.45263 | val 8.40614
  Classification -> best τ=0.845 (val F1=0.0489)
  Directional -> Accuracy: 0.5091, MCC: -0.0125, F1: 0.6197

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51180 | val 0.90808

[I 2026-02-20 05:09:07,175] Trial 174 finished with value: 0.2486143797931669 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00834035947138525, 'weight_decay': 3.9029680379886694e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.7341494588804943, 'early_stopping_min_delta': 0.009009868887952587}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.45766 | val 0.92616
  Classification -> best τ=0.405 (val F1=0.2124)
  Directional -> Accuracy: 0.5000, MCC: -0.0229, F1: 0.2857

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2486143797931669
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59028 | val 0.78964
  Epoch 013 - train 0.55885 | val 0.80572
  Classification -> best τ=0.680 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44485 | val 1.44822
  Epoch 012 - train 0.41582 | val 1.52772
  Classification -> best τ=0.310 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49265 | val 0.87039
  Epoch 011 - train 0.45396 | val 0.91516
  Classification -> best τ=0.560 (val F1=0.3171)
  Directional -> Accuracy: 0.5217, MCC: 0.0382, F1: 0.5600

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51559 | val 5.63663
  Epoch 012 - train 0.44364 | val 4.47599
  Classification -> best τ=0.430 (val F1=0.2593)
  Directional -> Accuracy: 0.5676, MCC: 0.1122, F1: 0.6522

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50638 | val 1.50544
  Epoch 012 - train 0.47050 | val 2.15477
  Classification -> best τ=0.485 (val F1=0.4259)
  Directional -> Accuracy: 0.6200, MCC: 0.2400, F1: 0.6780

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33144 | val 1.90110
  Epoch 011 - train 0.30899 | val 3.28468
  Classification -> best τ=0.485 (val F1=0.1235)
  Directional -> Accuracy: 0.5435, MCC: 0.0870, F1: 0.5333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52895 | val 1.49659
  Epoch 012 - train 0.47696 | val 1.83161
  Classification -> best τ=0.435 (val F1=0.2473)
  Directional -> Accuracy: 0.4853, MCC: 0.2030, F1: 0.5977

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42658 | val 1.58461
  Epoch 012 - train 0.30545 | val 3.47997
  Classification -> best τ=0.595 (val F1=0.3632)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50791 | val 2.86437
  Epoch 011 - train 0.51280 | val 2.30855
  Classification -> best τ=0.520 (val F1=0.1456)
  Directional -> Accuracy: 0.5625, MCC: 0.0646, F1: 0.3226

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44830 | val 2.25953
  Epoch 012 - train 0.45483 | val 1.66133
  Classification -> best τ=0.450 (val F1=0.1655)
  Directional -> Accuracy: 0.4348, MCC: 0.0115, F1: 0.5806

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58001 | val 0.81086
  Epoch 011 - train 0.53486 | val 0.96387
  Classification -> best τ=0.415 (val F1=0.1428)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53022 | val 3.18706
  Epoch 011 - train 0.49856 | val 2.79836
  Classification -> best τ=0.470 (val F1=0.2944)
  Directional -> Accuracy: 0.5614, MCC: 0.1915, F1: 0.6914

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41567 | val 3.98748
  Epoch 011 - train 0.42465 | val 4.61962
  Classification -> best τ=0.535 (val F1=0.1754)
  Directional -> Accuracy: 0.5714, MCC: 0.1083, F1: 0.3571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57211 | val 0.83477
  Epoch 012 - train 0.53271 | val 1.13628
  Classification -> best τ=0.260 (val F1=0.3596)
  Directional -> Accuracy: 0.5333, MCC: 0.0727, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57714 | val 1.45041
  Epoch 016 - train 0.41339 | val 1.76734
  Classification -> best τ=0.420 (val F1=0.3578)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49443 | val 1.13768
  Epoch 011 - train 0.48127 | val 1.38451
  Classification -> best τ=0.510 (val F1=0.2557)
  Directional -> Accuracy: 0.4928, MCC: -0.0051, F1: 0.4776

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53693 | val 5.06753
  Epoch 011 - train 0.53018 | val 5.66964
  Classification -> best τ=0.640 (val F1=0.2634)
  Directional -> Accuracy: 0.3448, MCC: -0.2076, F1: 0.1739

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51103 | val 2.12138
  Epoch 012 - train 0.45749 | val 2.76604
  Classification -> best τ=0.515 (val F1=0.1905)
  Directional -> Accuracy: 0.6133, MCC: 0.2286, F1: 0.6506

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50833 | val 0.92093
  Epoch 011 - train 0.47810 | val 1.62507
  Classification -> best τ=0.610 (val F1=0.2234)
  Directional -> Accuracy: 0.4375, MCC: 0.1076, F1: 0.0526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42278 | val 2.49252
  Epoch 011 - train 0.46616 | val 1.87955
  Classification -> best τ=0.625 (val F1=0.2128)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58670 | val 0.85301
  Epoch 012 - train 0.50020 | val 0.79641
  Classification -> best τ=0.465 (val F1=0.3251)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50509 | val 1.66304
  Epoch 012 - train 0.54664 | val 1.47528
  Classification -> best τ=0.455 (val F1=0.3086)
  Directional -> Accuracy: 0.4923, MCC: -0.0066, F1: 0.2326

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50347 | val 1.52334
  Epoch 011 - train 0.48493 | val 2.10581
  Classification -> best τ=0.705 (val F1=0.2942)
  Directional -> Accuracy: 0.5263, MCC: 0.0784, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49813 | val 5.77651
  Epoch 011 - train 0.49132 | val 4.94819
  Classification -> best τ=0.830 (val F1=0.2451)
  Directional -> Accuracy: 0.5231, MCC: 0.0118, F1: 0.1143

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54951 | val 1.70571
  Epoch 013 - train 0.35658 | val 2.75609
  Classification -> best τ=0.430 (val F1=0.4001)
  Directional -> Accuracy: 0.5091, MCC: 0.0410, F1: 0.4706

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39046 | val 2.88522
  Epoch 011 - train 0.44086 | val 1.82739
  Classification -> best τ=0.605 (val F1=0.1383)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56712 | val 0.89760
  Epoch 011 - train 0.54983 | val 0.84885
  Classification -> best τ=0.515 (val F1=0.1021)
  Directional -> Accuracy: 0.5476, MCC: 0.1434, F1: 0.5128

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45918 | val 1.17583
  Epoch 011 - train 0.41084 | val 1.24100
  Classification -> best τ=0.740 (val F1=0.3181)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41759 | val 1.06042
  Epoch 012 - train 0.38745 | val 1.22832
  Classification -> best τ=0.560 (val F1=0.1457)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53140 | val 0.84645
  Epoch 013 - train 0.54484 | val 1.32396
  Classification -> best τ=0.505 (val F1=0.3501)
  Directional -> Accuracy: 0.4524, MCC: -0.1228, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46358 | val 1.04755
  Epoch 013 - train 0.37499 | val 1.65042
  Classification -> best τ=0.540 (val F1=0.1195)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46937 | val 1.27969
  Epoch 011 - train 0.44216 | val 1.54545
  Classification -> best τ=0.420 (val F1=0.3957)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57188 | val 1.20176
  Epoch 012 - train 0.51288 | val 2.79840
  Classification -> best τ=0.655 (val F1=0.2697)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.2041

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38380 | val 2.69491
  Epoch 011 - train 0.34583 | val 3.33408
  Classification -> best τ=0.730 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49539 | val 1.41410
  Epoch 011 - train 0.45039 | val 2.10497
  Classification -> best τ=0.425 (val F1=0.2576)
  Directional -> Accuracy: 0.6061, MCC: 0.1509, F1: 0.7292

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48576 | val 2.03335
  Epoch 011 - train 0.34382 | val 2.39122
  Classification -> best τ=0.370 (val F1=0.1745)
  Directional -> Accuracy: 0.6190, MCC: 0.2364, F1: 0.6364

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46880 | val 1.55967
  Epoch 011 - train 0.50336 | val 1.64846
  Classification -> best τ=0.415 (val F1=0.2530)
  Directional -> Accuracy: 0.4286, MCC: -0.1309, F1: 0.4667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50507 | val 1.09598
  Epoch 011 - train 0.46247 | val 1.16176
  Classification -> best τ=0.545 (val F1=0.4454)
  Directional -> Accuracy: 0.5435, MCC: -0.0086, F1: 0.6557

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53541 | val 0.81482
  Epoch 017 - train 0.27818 | val 1.24551
  Classification -> best τ=0.345 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54661 | val 2.42647
  Epoch 011 - train 0.51407 | val 2.71476
  Classification -> best τ=0.585 (val F1=0.1647)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48921 | val 2.03537
  Epoch 014 - train 0.30668 | val 2.49803
  Classification -> best τ=0.410 (val F1=0.2582)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49484 | val 2.12865
  Epoch 014 - train 0.29148 | val 1.95925
  Classification -> best τ=0.455 (val F1=0.4901)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50588 | val 1.44684
  Epoch 014 - train 0.39717 | val 1.37932
  Classification -> best τ=0.635 (val F1=0.2300)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55352 | val 1.93606
  Epoch 012 - train 0.47854 | val 2.59002
  Classification -> best τ=0.545 (val F1=0.1154)
  Directional -> Accuracy: 0.2727, MCC: -0.4582, F1: 0.3103

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47205 | val 3.95327
  Epoch 011 - train 0.43989 | val 3.98202
  Classification -> best τ=0.610 (val F1=0.2649)
  Directional -> Accuracy: 0.5714, MCC: 0.1801, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53714 | val 0.90525
  Epoch 011 - train 0.52121 | val 0.95192
  Classification -> best τ=0.420 (val F1=0.2279)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48433 | val 4.19453
  Epoch 011 - train 0.50321 | val 2.65468
  Classification -> best τ=0.735 (val F1=0.1655)
  Directional -> Accuracy: 0.5636, MCC: 0.1170, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49417 | val 2.08183

[I 2026-02-20 05:12:23,625] Trial 175 finished with value: 0.25987040486179863 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.006187525866350119, 'weight_decay': 3.2525958503940653e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5317247943016841, 'early_stopping_min_delta': 0.009612624650125417}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 012 - train 0.45710 | val 2.29308
  Classification -> best τ=0.560 (val F1=0.2354)
  Directional -> Accuracy: 0.5500, MCC: 0.1044, F1: 0.3077

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25987040486179863
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64052 | val 0.75067
  Epoch 011 - train 0.64639 | val 0.75207
  Classification -> best τ=0.520 (val F1=0.2412)
  Directional -> Accuracy: 0.5132, MCC: -0.0693, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67237 | val 0.75755
  Epoch 011 - train 0.66760 | val 0.76110
  Classification -> best τ=0.455 (val F1=0.1469)
  Directional -> Accuracy: 0.5333, MCC: -0.1089, F1: 0.6866

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67961 | val 0.68940
  Epoch 011 - train 0.67472 | val 0.68805
  Classification -> best τ=0.475 (val F1=0.3251)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65816 | val 0.74319
  Epoch 011 - train 0.65554 | val 0.75050
  Classification -> best τ=0.495 (val F1=0.1394)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66129 | val 0.73912
  Epoch 011 - train 0.65654 | val 0.73405
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65937 | val 0.75562
  Epoch 011 - train 0.66399 | val 0.76150
  Classification -> best τ=0.545 (val F1=0.0882)
  Directional -> Accuracy: 0.4348, MCC: -0.1881, F1: 0.1875

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66722 | val 0.74850
  Epoch 011 - train 0.66585 | val 0.74970
  Classification -> best τ=0.485 (val F1=0.1712)
  Directional -> Accuracy: 0.5294, MCC: 0.0921, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69392 | val 0.79735
  Epoch 011 - train 0.68310 | val 0.82598
  Classification -> best τ=0.485 (val F1=0.1228)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.3750

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66593 | val 0.81832
  Epoch 011 - train 0.64535 | val 0.82935
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64887 | val 1.04369
  Epoch 011 - train 0.64736 | val 1.04858
  Classification -> best τ=0.480 (val F1=0.2480)
  Directional -> Accuracy: 0.4348, MCC: -0.0495, F1: 0.5301

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66860 | val 0.71191
  Epoch 011 - train 0.66043 | val 0.71396
  Classification -> best τ=0.495 (val F1=0.0138)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68016 | val 0.70246
  Epoch 011 - train 0.67573 | val 0.70389
  Classification -> best τ=0.535 (val F1=0.1527)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62366 | val 0.77682
  Epoch 011 - train 0.64191 | val 0.78832
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68219 | val 0.65993
  Epoch 020 - train 0.67206 | val 0.66049
  Epoch 024 - train 0.66453 | val 0.66202
  Classification -> best τ=0.325 (val F1=0.1958)
  Directional -> Accuracy: 0.6000, MCC: 0.2683, F1: 0.7000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66262 | val 0.81870
  Epoch 011 - train 0.65907 | val 0.82662
  Classification -> best τ=0.520 (val F1=0.0907)
  Directional -> Accuracy: 0.4706, MCC: -0.1160, F1: 0.2703

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67366 | val 0.69814
  Epoch 014 - train 0.65478 | val 0.69872
  Classification -> best τ=0.520 (val F1=0.1627)
  Directional -> Accuracy: 0.5507, MCC: 0.1122, F1: 0.5373

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65818 | val 1.16287
  Epoch 011 - train 0.66591 | val 1.17751
  Classification -> best τ=0.495 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66164 | val 1.28999
  Epoch 011 - train 0.67081 | val 1.29842
  Classification -> best τ=0.440 (val F1=0.1091)
  Directional -> Accuracy: 0.5200, MCC: 0.3015, F1: 0.3333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65055 | val 0.80458
  Epoch 011 - train 0.63541 | val 0.80613
  Classification -> best τ=0.470 (val F1=0.2234)
  Directional -> Accuracy: 0.4531, MCC: 0.0359, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65318 | val 1.10298
  Epoch 011 - train 0.65023 | val 1.11800
  Classification -> best τ=0.455 (val F1=0.0472)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66946 | val 0.75105
  Epoch 011 - train 0.67214 | val 0.75042
  Classification -> best τ=0.500 (val F1=0.0866)
  Directional -> Accuracy: 0.5319, MCC: -0.2403, F1: 0.6944

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67593 | val 0.69549
  Epoch 016 - train 0.67565 | val 0.70986
  Classification -> best τ=0.470 (val F1=0.2315)
  Directional -> Accuracy: 0.5077, MCC: 0.0239, F1: 0.3846

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66602 | val 0.66960
  Epoch 020 - train 0.66720 | val 0.66976
  Classification -> best τ=0.555 (val F1=0.2478)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67614 | val 0.74708
  Epoch 011 - train 0.67636 | val 0.75129
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64938 | val 0.65494
  Epoch 016 - train 0.63075 | val 0.67100
  Classification -> best τ=0.575 (val F1=0.3815)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69985 | val 0.72300
  Epoch 011 - train 0.69838 | val 0.72655
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66665 | val 1.03664
  Epoch 011 - train 0.66907 | val 1.04937
  Classification -> best τ=0.530 (val F1=0.1171)
  Directional -> Accuracy: 0.4762, MCC: 0.0323, F1: 0.3529

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65536 | val 0.66863
  Epoch 017 - train 0.63458 | val 0.66759
  Classification -> best τ=0.470 (val F1=0.2543)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66545 | val 0.70598
  Epoch 011 - train 0.64320 | val 0.71879
  Classification -> best τ=0.525 (val F1=0.0374)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66026 | val 0.66311
  Epoch 017 - train 0.64034 | val 0.66413
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67220 | val 0.79777
  Epoch 011 - train 0.66370 | val 0.81091
  Classification -> best τ=0.525 (val F1=0.0806)
  Directional -> Accuracy: 0.4762, MCC: -0.1062, F1: 0.5926

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65604 | val 0.72312
  Epoch 011 - train 0.64137 | val 0.72395
  Classification -> best τ=0.535 (val F1=0.0648)
  Directional -> Accuracy: 0.5306, MCC: 0.0127, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66193 | val 0.68711
  Epoch 011 - train 0.66264 | val 0.68584
  Classification -> best τ=0.495 (val F1=0.0745)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66908 | val 0.91735
  Epoch 011 - train 0.67632 | val 0.92777
  Classification -> best τ=0.510 (val F1=0.2587)
  Directional -> Accuracy: 0.5814, MCC: 0.1993, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66607 | val 0.68597
  Epoch 015 - train 0.65488 | val 0.69661
  Classification -> best τ=0.405 (val F1=0.3855)
  Directional -> Accuracy: 0.5606, MCC: 0.0799, F1: 0.6420

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67910 | val 0.69589
  Epoch 011 - train 0.68759 | val 0.69652
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64524 | val 0.73652
  Epoch 011 - train 0.64722 | val 0.73559
  Classification -> best τ=0.500 (val F1=0.1913)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65783 | val 0.97304
  Epoch 011 - train 0.65717 | val 0.97998
  Classification -> best τ=0.485 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65301 | val 0.69143
  Epoch 020 - train 0.62566 | val 0.66636
  Epoch 030 - train 0.61071 | val 0.65509
  Epoch 035 - train 0.61813 | val 0.65238
  Classification -> best τ=0.455 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64357 | val 0.67709
  Epoch 016 - train 0.63839 | val 0.68719
  Classification -> best τ=0.525 (val F1=0.3278)
  Directional -> Accuracy: 0.5270, MCC: 0.0816, F1: 0.6237

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67590 | val 0.79788
  Epoch 013 - train 0.66376 | val 0.78886
  Classification -> best τ=0.495 (val F1=0.3371)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67430 | val 0.70247
  Epoch 011 - train 0.68136 | val 0.70439
  Classification -> best τ=0.505 (val F1=0.0765)
  Directional -> Accuracy: 0.5238, MCC: -0.0525, F1: 0.6552

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70329 | val 0.70666
  Epoch 019 - train 0.68465 | val 0.71513
  Classification -> best τ=0.410 (val F1=0.4682)
  Directional -> Accuracy: 0.5625, MCC: 0.0348, F1: 0.3636

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67322 | val 0.76524
  Epoch 011 - train 0.66980 | val 0.76988
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65503 | val 0.69484
  Epoch 014 - train 0.64955 | val 0.71117
  Classification -> best τ=0.475 (val F1=0.2385)
  Directional -> Accuracy: 0.4821, MCC: -0.0619, F1: 0.2927

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67185 | val 0.69355
  Epoch 014 - train 0.65111 | val 0.69193
  Classification -> best τ=0.535 (val F1=0.1801)
  Directional -> Accuracy: 0.5283, MCC: 0.0863, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63708 | val 1.07282
  Epoch 011 - train 0.64557 | val 1.09650
  Classification -> best τ=0.505 (val F1=0.1352)
  Directional -> Accuracy: 0.5273, MCC: 0.1093, F1: 0.3500

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64914 | val 0.75286

[I 2026-02-20 05:15:59,838] Trial 176 finished with value: 0.1689116414672733 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 1.9094943325895168e-05, 'weight_decay': 1.7642378474397106e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6724449944416899, 'early_stopping_min_delta': 0.00936296308455994}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 014 - train 0.64055 | val 0.79200
  Classification -> best τ=0.435 (val F1=0.2789)
  Directional -> Accuracy: 0.4500, MCC: -0.0943, F1: 0.5217

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1689116414672733
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59158 | val 1.49666
  Epoch 011 - train 0.55875 | val 1.34967
  Classification -> best τ=0.545 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61467 | val 0.97237
  Epoch 011 - train 0.57257 | val 1.08502
  Classification -> best τ=0.610 (val F1=0.2073)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58591 | val 0.86082
  Epoch 018 - train 0.46590 | val 1.05503
  Classification -> best τ=0.440 (val F1=0.4142)
  Directional -> Accuracy: 0.5217, MCC: 0.0733, F1: 0.3889

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51361 | val 2.01512
  Epoch 011 - train 0.51646 | val 1.47792
  Classification -> best τ=0.410 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53246 | val 2.01008
  Epoch 012 - train 0.42978 | val 1.32445
  Classification -> best τ=0.415 (val F1=0.4787)
  Directional -> Accuracy: 0.7600, MCC: 0.5194, F1: 0.7778

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41791 | val 3.10986
  Epoch 011 - train 0.33733 | val 1.37208
  Classification -> best τ=0.570 (val F1=0.1947)
  Directional -> Accuracy: 0.4783, MCC: -0.2041, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52789 | val 1.30145
  Epoch 011 - train 0.49164 | val 1.05672
  Classification -> best τ=0.385 (val F1=0.3051)
  Directional -> Accuracy: 0.4412, MCC: 0.0509, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50536 | val 0.73171
  Epoch 019 - train 0.27353 | val 1.27236
  Classification -> best τ=0.115 (val F1=0.3094)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47654 | val 1.38939
  Epoch 011 - train 0.58069 | val 1.57785
  Classification -> best τ=0.575 (val F1=0.1928)
  Directional -> Accuracy: 0.5000, MCC: 0.0053, F1: 0.4783

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53763 | val 1.87399
  Epoch 011 - train 0.51238 | val 2.31224
  Classification -> best τ=0.355 (val F1=0.2287)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57914 | val 0.68785
  Epoch 014 - train 0.45570 | val 0.97361
  Classification -> best τ=0.535 (val F1=0.4196)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56990 | val 2.97213
  Epoch 011 - train 0.47276 | val 3.49155
  Classification -> best τ=0.360 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39294 | val 4.58146
  Epoch 011 - train 0.37777 | val 4.47739
  Classification -> best τ=0.435 (val F1=0.1550)
  Directional -> Accuracy: 0.5476, MCC: 0.1711, F1: 0.6275

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60525 | val 1.49834
  Epoch 012 - train 0.54730 | val 1.22256
  Classification -> best τ=0.350 (val F1=0.4048)
  Directional -> Accuracy: 0.4833, MCC: -0.0519, F1: 0.6265

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49011 | val 1.54105
  Epoch 011 - train 0.47365 | val 1.10085
  Classification -> best τ=0.510 (val F1=0.1493)
  Directional -> Accuracy: 0.5882, MCC: 0.1583, F1: 0.2759

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63020 | val 1.13063
  Epoch 012 - train 0.45885 | val 1.05463
  Classification -> best τ=0.525 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58370 | val 6.41131
  Epoch 011 - train 0.51803 | val 6.46184
  Classification -> best τ=0.660 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53002 | val 1.62768
  Epoch 012 - train 0.42481 | val 1.96109
  Classification -> best τ=0.590 (val F1=0.2632)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54494 | val 0.98427
  Epoch 011 - train 0.49986 | val 1.14650
  Classification -> best τ=0.465 (val F1=0.1982)
  Directional -> Accuracy: 0.5312, MCC: 0.0683, F1: 0.5588

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52671 | val 1.38393
  Epoch 011 - train 0.43467 | val 1.68645
  Classification -> best τ=0.480 (val F1=0.3161)
  Directional -> Accuracy: 0.4730, MCC: 0.1495, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56429 | val 1.07546
  Epoch 012 - train 0.46840 | val 1.26270
  Classification -> best τ=0.450 (val F1=0.3251)
  Directional -> Accuracy: 0.4681, MCC: 0.0598, F1: 0.3902

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51245 | val 1.17316
  Epoch 011 - train 0.53021 | val 1.28338
  Classification -> best τ=0.565 (val F1=0.0835)
  Directional -> Accuracy: 0.5077, MCC: 0.0443, F1: 0.2000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59467 | val 1.22926
  Epoch 011 - train 0.51092 | val 1.16727
  Classification -> best τ=0.590 (val F1=0.3727)
  Directional -> Accuracy: 0.4737, MCC: 0.0115, F1: 0.3478

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53960 | val 1.46965
  Epoch 011 - train 0.45964 | val 2.68158
  Classification -> best τ=0.580 (val F1=0.0406)
  Directional -> Accuracy: 0.5538, MCC: 0.0975, F1: 0.4314

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49997 | val 1.64831
  Epoch 012 - train 0.45450 | val 1.97373
  Classification -> best τ=0.535 (val F1=0.3563)
  Directional -> Accuracy: 0.5636, MCC: 0.1981, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50681 | val 1.70122
  Epoch 011 - train 0.44186 | val 1.10160
  Classification -> best τ=0.550 (val F1=0.2726)
  Directional -> Accuracy: 0.6000, MCC: 0.3120, F1: 0.6538

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53776 | val 0.76934
  Epoch 011 - train 0.47752 | val 0.98380
  Classification -> best τ=0.450 (val F1=0.1250)
  Directional -> Accuracy: 0.5952, MCC: 0.1795, F1: 0.6383

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51944 | val 1.72496
  Epoch 011 - train 0.46330 | val 1.94617
  Classification -> best τ=0.345 (val F1=0.0926)
  Directional -> Accuracy: 0.5357, MCC: 0.0081, F1: 0.6579

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49029 | val 3.13015
  Epoch 011 - train 0.43710 | val 2.57505
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50674 | val 1.27749
  Epoch 014 - train 0.42291 | val 1.02750
  Classification -> best τ=0.545 (val F1=0.5210)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53909 | val 3.79475
  Epoch 011 - train 0.51667 | val 3.79609
  Classification -> best τ=0.460 (val F1=0.2646)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47425 | val 1.09363
  Epoch 011 - train 0.44889 | val 1.05001
  Classification -> best τ=0.530 (val F1=0.2399)
  Directional -> Accuracy: 0.5306, MCC: 0.0708, F1: 0.5106

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58335 | val 1.95280
  Epoch 011 - train 0.52520 | val 2.03914
  Classification -> best τ=0.545 (val F1=0.2968)
  Directional -> Accuracy: 0.4444, MCC: -0.0189, F1: 0.0476

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49778 | val 3.84975
  Epoch 012 - train 0.40052 | val 3.12147
  Classification -> best τ=0.505 (val F1=0.2000)
  Directional -> Accuracy: 0.4651, MCC: -0.0746, F1: 0.4103

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54606 | val 0.86728
  Epoch 012 - train 0.45242 | val 0.87360
  Classification -> best τ=0.425 (val F1=0.3634)
  Directional -> Accuracy: 0.5909, MCC: 0.1513, F1: 0.6582

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41997 | val 1.14785
  Epoch 011 - train 0.40355 | val 1.11881
  Classification -> best τ=0.455 (val F1=0.0959)
  Directional -> Accuracy: 0.6190, MCC: 0.2477, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50957 | val 2.14507
  Epoch 012 - train 0.43993 | val 1.97962
  Classification -> best τ=0.440 (val F1=0.2450)
  Directional -> Accuracy: 0.3929, MCC: -0.2205, F1: 0.3462

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47719 | val 1.89420
  Epoch 011 - train 0.37147 | val 2.66756
  Classification -> best τ=0.520 (val F1=0.2539)
  Directional -> Accuracy: 0.4783, MCC: 0.0040, F1: 0.4783

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52096 | val 0.92656
  Epoch 015 - train 0.34634 | val 0.97531
  Classification -> best τ=0.415 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56231 | val 3.76687
  Epoch 012 - train 0.48508 | val 2.72456
  Classification -> best τ=0.500 (val F1=0.2693)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52521 | val 2.72036
  Epoch 011 - train 0.47998 | val 2.25234
  Classification -> best τ=0.545 (val F1=0.2668)
  Directional -> Accuracy: 0.6000, MCC: 0.2145, F1: 0.6786

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37277 | val 1.48900
  Epoch 011 - train 0.34698 | val 1.48502
  Classification -> best τ=0.520 (val F1=0.3612)
  Directional -> Accuracy: 0.3810, MCC: -0.1936, F1: 0.2353

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47925 | val 0.84804
  Epoch 012 - train 0.34545 | val 1.09439
  Classification -> best τ=0.650 (val F1=0.5689)
  Directional -> Accuracy: 0.4375, MCC: -0.0348, F1: 0.4706

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67641 | val 1.27213
  Epoch 011 - train 0.56356 | val 1.78131
  Classification -> best τ=0.525 (val F1=0.0236)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47374 | val 2.90323
  Epoch 011 - train 0.40137 | val 3.11548
  Classification -> best τ=0.595 (val F1=0.2720)
  Directional -> Accuracy: 0.5536, MCC: 0.2187, F1: 0.6753

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55393 | val 0.89709
  Epoch 012 - train 0.50184 | val 1.31529
  Classification -> best τ=0.630 (val F1=0.0593)
  Directional -> Accuracy: 0.4906, MCC: -0.0037, F1: 0.0690

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45425 | val 7.57609
  Epoch 012 - train 0.36917 | val 5.16480
  Classification -> best τ=0.510 (val F1=0.1571)
  Directional -> Accuracy: 0.5636, MCC: 0.1555, F1: 0.7000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53559 | val 1.89453
  Epoch 011 - train 0.46230 | val 1.98185
  Classification -> best τ=0.465 (val F1=0.2130)
  Directional -> Accuracy: 0.5500, MCC: 0.1307, F1: 0.6301

[I 2026-02-20 05:19:16,873] Trial 177 finished with value: 0.24894329720292538 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0031775460020190996, 'weight_decay': 6.932907153939033e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.4769355950379478, 'early_stopping_min_delta': 0.009196245056876124}. Best is trial 154 with value: 0.29985667076798134.

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24894329720292538
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62677 | val 0.76179
  Epoch 011 - train 0.59436 | val 0.90848
  Classification -> best τ=0.545 (val F1=0.3013)
  Directional -> Accuracy: 0.5658, MCC: 0.1243, F1: 0.5217

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61871 | val 0.92052
  Epoch 011 - train 0.59855 | val 1.06905
  Classification -> best τ=0.420 (val F1=0.1478)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69071 | val 1.09057
  Epoch 017 - train 0.53582 | val 0.86311
  Classification -> best τ=0.745 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1945, F1: 0.2759

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65111 | val 3.07259
  Epoch 011 - train 0.62012 | val 3.82177
  Classification -> best τ=0.415 (val F1=0.3206)
  Directional -> Accuracy: 0.5270, MCC: -0.1079, F1: 0.6903

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63618 | val 0.64552
  Epoch 015 - train 0.52395 | val 0.66059
  Classification -> best τ=0.490 (val F1=0.4947)
  Directional -> Accuracy: 0.6200, MCC: 0.2519, F1: 0.6984

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55919 | val 1.75824
  Epoch 011 - train 0.52509 | val 1.88910
  Classification -> best τ=0.540 (val F1=0.1745)
  Directional -> Accuracy: 0.5652, MCC: 0.1461, F1: 0.2857

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65418 | val 0.83904
  Epoch 017 - train 0.61720 | val 1.09313
  Classification -> best τ=0.450 (val F1=0.3071)
  Directional -> Accuracy: 0.5441, MCC: 0.1757, F1: 0.5753

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51085 | val 5.99596
  Epoch 014 - train 0.42418 | val 6.48229
  Classification -> best τ=0.580 (val F1=0.2168)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52511 | val 3.53784
  Epoch 011 - train 0.45647 | val 3.96692
  Classification -> best τ=0.645 (val F1=0.2988)
  Directional -> Accuracy: 0.5208, MCC: 0.0420, F1: 0.4889

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64588 | val 1.08418
  Epoch 017 - train 0.48252 | val 1.19445
  Classification -> best τ=0.490 (val F1=0.2664)
  Directional -> Accuracy: 0.4493, MCC: 0.0544, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66174 | val 0.67079
  Epoch 020 - train 0.51970 | val 2.53711
  Epoch 021 - train 0.50443 | val 2.35929
  Classification -> best τ=0.440 (val F1=0.4037)
  Directional -> Accuracy: 0.6122, MCC: 0.2076, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59090 | val 0.72871
  Epoch 012 - train 0.58643 | val 0.97792
  Classification -> best τ=0.530 (val F1=0.1923)
  Directional -> Accuracy: 0.5965, MCC: 0.2739, F1: 0.7089

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58141 | val 0.88725
  Epoch 015 - train 0.50615 | val 0.78473
  Classification -> best τ=0.480 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62192 | val 0.65804
  Epoch 013 - train 0.60872 | val 0.62511
  Classification -> best τ=0.330 (val F1=0.4219)
  Directional -> Accuracy: 0.5500, MCC: 0.1028, F1: 0.4906

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59112 | val 4.72632
  Epoch 011 - train 0.56072 | val 3.51279
  Classification -> best τ=0.565 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67130 | val 0.66536
  Epoch 015 - train 0.62544 | val 0.72652
  Classification -> best τ=0.440 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64600 | val 0.83539
  Epoch 011 - train 0.64433 | val 0.84055
  Classification -> best τ=0.750 (val F1=0.0732)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60555 | val 0.85359
  Epoch 011 - train 0.57253 | val 1.08010
  Classification -> best τ=0.450 (val F1=0.2004)
  Directional -> Accuracy: 0.5733, MCC: 0.1879, F1: 0.5789

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60436 | val 0.74037
  Epoch 011 - train 0.60919 | val 0.78750
  Classification -> best τ=0.540 (val F1=0.2846)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58965 | val 1.43530
  Epoch 011 - train 0.56459 | val 1.35104
  Classification -> best τ=0.780 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64261 | val 0.80707
  Epoch 011 - train 0.56264 | val 0.80898
  Classification -> best τ=0.515 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63970 | val 1.26977
  Epoch 011 - train 0.63789 | val 1.45976
  Classification -> best τ=0.505 (val F1=0.2979)
  Directional -> Accuracy: 0.4615, MCC: -0.1162, F1: 0.5977

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69083 | val 0.70657
  Epoch 012 - train 0.64218 | val 0.71691
  Classification -> best τ=0.615 (val F1=0.3833)
  Directional -> Accuracy: 0.5088, MCC: 0.0801, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65533 | val 1.13468
  Epoch 012 - train 0.61684 | val 0.71218
  Classification -> best τ=0.520 (val F1=0.1348)
  Directional -> Accuracy: 0.5385, MCC: 0.0619, F1: 0.3478

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62037 | val 1.02593
  Epoch 016 - train 0.52419 | val 1.20893
  Classification -> best τ=0.505 (val F1=0.4183)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53140 | val 3.52982
  Epoch 011 - train 0.52179 | val 4.12480
  Classification -> best τ=0.590 (val F1=0.1099)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65863 | val 0.75531
  Epoch 011 - train 0.67167 | val 0.78643
  Classification -> best τ=0.505 (val F1=0.0849)
  Directional -> Accuracy: 0.5714, MCC: 0.1840, F1: 0.5500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61028 | val 0.85990
  Epoch 015 - train 0.54072 | val 1.22493
  Classification -> best τ=0.640 (val F1=0.1913)
  Directional -> Accuracy: 0.4643, MCC: -0.1020, F1: 0.5455

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49899 | val 1.08114
  Epoch 011 - train 0.58049 | val 1.21604
  Classification -> best τ=0.565 (val F1=0.0601)
  Directional -> Accuracy: 0.6250, MCC: 0.2389, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64509 | val 0.69654
  Epoch 014 - train 0.57850 | val 0.70007
  Classification -> best τ=0.600 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65506 | val 0.71084
  Epoch 014 - train 0.55535 | val 0.97771
  Classification -> best τ=0.790 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65020 | val 0.75335
  Epoch 012 - train 0.59838 | val 0.84209
  Classification -> best τ=0.310 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67624 | val 0.72646
  Epoch 017 - train 0.53448 | val 0.95855
  Classification -> best τ=0.705 (val F1=0.2637)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67755 | val 1.55066
  Epoch 011 - train 0.64717 | val 1.79727
  Classification -> best τ=0.465 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63458 | val 0.66468
  Epoch 015 - train 0.56444 | val 0.75118
  Classification -> best τ=0.305 (val F1=0.3855)
  Directional -> Accuracy: 0.6515, MCC: 0.3276, F1: 0.6567

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56128 | val 0.69765
  Epoch 011 - train 0.52784 | val 0.79310
  Classification -> best τ=0.510 (val F1=0.2193)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51737 | val 1.04042
  Epoch 011 - train 0.50724 | val 1.34369
  Classification -> best τ=0.480 (val F1=0.2110)
  Directional -> Accuracy: 0.4286, MCC: -0.1309, F1: 0.4667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51009 | val 1.39275
  Epoch 012 - train 0.49053 | val 2.18621
  Classification -> best τ=0.305 (val F1=0.2474)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61690 | val 1.39626
  Epoch 013 - train 0.47783 | val 1.20247
  Classification -> best τ=0.480 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63664 | val 0.89817
  Epoch 014 - train 0.57155 | val 1.47864
  Classification -> best τ=0.480 (val F1=0.3134)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55930 | val 1.10881
  Epoch 011 - train 0.59347 | val 1.24249
  Classification -> best τ=0.565 (val F1=0.1890)
  Directional -> Accuracy: 0.6000, MCC: 0.2257, F1: 0.6897

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61740 | val 1.22570
  Epoch 011 - train 0.63233 | val 1.10925
  Classification -> best τ=0.470 (val F1=0.2408)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56341 | val 1.01588
  Epoch 013 - train 0.54170 | val 1.23594
  Classification -> best τ=0.460 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70837 | val 0.68091
  Epoch 020 - train 0.58024 | val 1.51692
  Classification -> best τ=0.620 (val F1=0.1769)
  Directional -> Accuracy: 0.5636, MCC: 0.1144, F1: 0.6129

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59117 | val 1.40863
  Epoch 012 - train 0.52939 | val 1.95504
  Classification -> best τ=0.365 (val F1=0.3526)
  Directional -> Accuracy: 0.5179, MCC: 0.0766, F1: 0.6301

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68363 | val 0.72082
  Epoch 014 - train 0.64686 | val 0.92972
  Classification -> best τ=0.560 (val F1=0.2570)
  Directional -> Accuracy: 0.4528, MCC: -0.1004, F1: 0.2564

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55615 | val 4.65292
  Epoch 012 - train 0.52890 | val 5.35309
  Classification -> best τ=0.600 (val F1=0.1682)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59102 | val 1.55325

[I 2026-02-20 05:21:21,444] Trial 178 finished with value: 0.25171835680665283 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.004843067509112041, 'weight_decay': 4.0088390359806185e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.205755539129878, 'early_stopping_min_delta': 0.008243704827710387}. Best is trial 154 with value: 0.29985667076798134.

  Epoch 011 - train 0.57252 | val 1.64711
  Classification -> best τ=0.475 (val F1=0.0448)
  Directional -> Accuracy: 0.5333, MCC: 0.0804, F1: 0.5882

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25171835680665283
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58419 | val 1.12545
  Epoch 013 - train 0.56468 | val 1.81146
  Classification -> best τ=0.365 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: 0.0206, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55344 | val 0.79602
  Epoch 011 - train 0.55074 | val 0.85540
  Classification -> best τ=0.360 (val F1=0.0706)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58342 | val 0.83883
  Epoch 012 - train 0.50987 | val 0.89830
  Classification -> best τ=0.590 (val F1=0.3285)
  Directional -> Accuracy: 0.5000, MCC: 0.0766, F1: 0.1481

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58512 | val 1.39563
  Epoch 012 - train 0.56036 | val 1.57087
  Classification -> best τ=0.405 (val F1=0.0788)
  Directional -> Accuracy: 0.5946, MCC: 0.1725, F1: 0.6875

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65230 | val 0.72012
  Epoch 017 - train 0.54790 | val 0.95565
  Classification -> best τ=0.595 (val F1=0.4782)
  Directional -> Accuracy: 0.7400, MCC: 0.4851, F1: 0.7347

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46671 | val 0.75443
  Epoch 012 - train 0.45876 | val 0.83333
  Classification -> best τ=0.455 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61553 | val 0.77105
  Epoch 011 - train 0.61641 | val 0.80726
  Classification -> best τ=0.665 (val F1=0.1718)
  Directional -> Accuracy: 0.5588, MCC: -0.0300, F1: 0.2105

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54964 | val 0.83797
  Epoch 015 - train 0.43050 | val 2.38885
  Classification -> best τ=0.510 (val F1=0.2753)
  Directional -> Accuracy: 0.5238, MCC: -0.0323, F1: 0.2857

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57777 | val 1.14959
  Epoch 013 - train 0.53714 | val 1.48744
  Classification -> best τ=0.455 (val F1=0.3376)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52730 | val 1.09722
  Epoch 011 - train 0.52005 | val 1.09148
  Classification -> best τ=0.460 (val F1=0.2216)
  Directional -> Accuracy: 0.5217, MCC: 0.0324, F1: 0.4590

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57691 | val 1.06903
  Epoch 016 - train 0.53203 | val 1.35153
  Classification -> best τ=0.465 (val F1=0.2543)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49227 | val 1.83372
  Epoch 011 - train 0.49047 | val 2.23878
  Classification -> best τ=0.400 (val F1=0.2391)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53483 | val 1.63041
  Epoch 012 - train 0.50965 | val 1.74855
  Classification -> best τ=0.455 (val F1=0.1991)
  Directional -> Accuracy: 0.4048, MCC: -0.1664, F1: 0.4898

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65392 | val 0.63118
  Epoch 020 - train 0.58964 | val 0.71988
  Epoch 023 - train 0.49483 | val 0.88868
  Classification -> best τ=0.525 (val F1=0.4219)
  Directional -> Accuracy: 0.5167, MCC: 0.0370, F1: 0.3830

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55819 | val 0.77570
  Epoch 011 - train 0.53053 | val 0.73409
  Classification -> best τ=0.415 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52823 | val 0.99913
  Epoch 012 - train 0.52858 | val 1.00318
  Classification -> best τ=0.605 (val F1=0.2738)
  Directional -> Accuracy: 0.5507, MCC: 0.1801, F1: 0.3922

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57919 | val 1.61108
  Epoch 011 - train 0.59806 | val 1.49751
  Classification -> best τ=0.715 (val F1=0.1731)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57157 | val 1.60004
  Epoch 013 - train 0.51842 | val 1.27965
  Classification -> best τ=0.540 (val F1=0.1609)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61349 | val 1.27119
  Epoch 013 - train 0.54675 | val 1.32627
  Classification -> best τ=0.365 (val F1=0.3140)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56355 | val 0.89017
  Epoch 011 - train 0.61463 | val 0.82531
  Classification -> best τ=0.665 (val F1=0.1808)
  Directional -> Accuracy: 0.3649, MCC: -0.2608, F1: 0.1455

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56619 | val 0.93162
  Epoch 019 - train 0.35039 | val 1.13360
  Classification -> best τ=0.415 (val F1=0.3732)
  Directional -> Accuracy: 0.4255, MCC: 0.0834, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65376 | val 0.91224
  Epoch 013 - train 0.58171 | val 1.15414
  Classification -> best τ=0.475 (val F1=0.2437)
  Directional -> Accuracy: 0.4615, MCC: -0.1011, F1: 0.5783

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57762 | val 0.69971
  Epoch 020 - train 0.45052 | val 0.98678
  Epoch 023 - train 0.41932 | val 1.04112
  Classification -> best τ=0.855 (val F1=0.3833)
  Directional -> Accuracy: 0.5263, MCC: 0.1434, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62949 | val 1.13815
  Epoch 012 - train 0.59220 | val 0.74088
  Classification -> best τ=0.660 (val F1=0.1565)
  Directional -> Accuracy: 0.5692, MCC: 0.1509, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55162 | val 0.93115
  Epoch 017 - train 0.43049 | val 0.85479
  Classification -> best τ=0.645 (val F1=0.4560)
  Directional -> Accuracy: 0.6182, MCC: 0.3130, F1: 0.5333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56567 | val 1.48865
  Epoch 011 - train 0.53566 | val 1.53775
  Classification -> best τ=0.490 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60861 | val 0.86382
  Epoch 012 - train 0.62182 | val 1.01895
  Classification -> best τ=0.660 (val F1=0.0430)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58116 | val 0.76951
  Epoch 011 - train 0.54650 | val 0.83086
  Classification -> best τ=0.440 (val F1=0.1949)
  Directional -> Accuracy: 0.5179, MCC: 0.1613, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55455 | val 3.79303
  Epoch 012 - train 0.50778 | val 3.80301
  Classification -> best τ=0.370 (val F1=0.3518)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49840 | val 1.42114
  Epoch 011 - train 0.51729 | val 1.38735
  Classification -> best τ=0.570 (val F1=0.5410)
  Directional -> Accuracy: 0.4762, MCC: -0.0500, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57344 | val 0.70261
  Epoch 014 - train 0.47493 | val 0.66114
  Classification -> best τ=0.615 (val F1=0.1604)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58029 | val 0.89714
  Epoch 013 - train 0.47712 | val 0.87968
  Classification -> best τ=0.430 (val F1=0.3136)
  Directional -> Accuracy: 0.5102, MCC: -0.0334, F1: 0.6471

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56582 | val 0.74160
  Epoch 012 - train 0.55139 | val 0.77744
  Classification -> best τ=0.395 (val F1=0.3846)
  Directional -> Accuracy: 0.5556, MCC: 0.1685, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62546 | val 0.77670
  Epoch 012 - train 0.61828 | val 0.78707
  Classification -> best τ=0.255 (val F1=0.3417)
  Directional -> Accuracy: 0.5814, MCC: 0.1736, F1: 0.4375

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56400 | val 0.73238
  Epoch 011 - train 0.58647 | val 0.76772
  Classification -> best τ=0.370 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44575 | val 2.53889
  Epoch 014 - train 0.33974 | val 2.26843
  Classification -> best τ=0.595 (val F1=0.2618)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54922 | val 0.93866
  Epoch 011 - train 0.54299 | val 0.94278
  Classification -> best τ=0.620 (val F1=0.1913)
  Directional -> Accuracy: 0.5536, MCC: 0.0862, F1: 0.4186

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58753 | val 0.70317
  Epoch 016 - train 0.39674 | val 0.89203
  Classification -> best τ=0.335 (val F1=0.3451)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53845 | val 0.74045
  Epoch 020 - train 0.39072 | val 0.71948
  Epoch 023 - train 0.31950 | val 0.70977
  Classification -> best τ=0.350 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59230 | val 0.85624
  Epoch 011 - train 0.58609 | val 0.90364
  Classification -> best τ=0.490 (val F1=0.2782)
  Directional -> Accuracy: 0.5000, MCC: 0.0230, F1: 0.6186

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52379 | val 2.53281
  Epoch 011 - train 0.49734 | val 3.16775
  Classification -> best τ=0.540 (val F1=0.3371)
  Directional -> Accuracy: 0.5111, MCC: 0.0629, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67232 | val 0.82292
  Epoch 011 - train 0.64871 | val 0.79585
  Classification -> best τ=0.565 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.0741

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57968 | val 0.68758
  Epoch 012 - train 0.53435 | val 0.66726
  Classification -> best τ=0.605 (val F1=0.4176)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60340 | val 0.67569
  Epoch 011 - train 0.64280 | val 0.67226
  Classification -> best τ=0.600 (val F1=0.1784)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62732 | val 0.84034
  Epoch 011 - train 0.61226 | val 0.83298
  Classification -> best τ=0.580 (val F1=0.1694)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58346 | val 0.88996
  Epoch 011 - train 0.56096 | val 0.87694
  Classification -> best τ=0.530 (val F1=0.1668)
  Directional -> Accuracy: 0.5660, MCC: 0.2315, F1: 0.3030

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55476 | val 1.81254
  Epoch 011 - train 0.54689 | val 1.29487
  Classification -> best τ=0.485 (val F1=0.1200)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60477 | val 1.01981
  Epoch 011 - train 0.58131 | val 1.07760

[I 2026-02-20 05:22:25,161] Trial 179 finished with value: 0.26597897239338375 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.007212624220294592, 'weight_decay': 5.851530983544103e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6308460488757925, 'early_stopping_min_delta': 0.008667293938887837}. Best is trial 154 with value: 0.29985667076798134.

  Classification -> best τ=0.465 (val F1=0.2124)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26597897239338375
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61613 | val 1.28576
  Epoch 014 - train 0.59815 | val 0.72046
  Classification -> best τ=0.665 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45421 | val 0.81253
  Epoch 011 - train 0.43075 | val 0.97286
  Classification -> best τ=0.365 (val F1=0.3353)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61332 | val 0.66587
  Epoch 017 - train 0.40416 | val 1.13595
  Classification -> best τ=0.720 (val F1=0.3237)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5106

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60350 | val 1.07031
  Epoch 017 - train 0.46460 | val 1.25273
  Classification -> best τ=0.590 (val F1=0.3491)
  Directional -> Accuracy: 0.4730, MCC: -0.1074, F1: 0.5895

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57457 | val 2.72100
  Epoch 013 - train 0.40649 | val 2.14772
  Classification -> best τ=0.730 (val F1=0.4862)
  Directional -> Accuracy: 0.6600, MCC: 0.3669, F1: 0.5854

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41384 | val 0.97289
  Epoch 011 - train 0.43573 | val 0.87877
  Classification -> best τ=0.615 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61237 | val 1.15051
  Epoch 015 - train 0.47969 | val 2.27293
  Classification -> best τ=0.175 (val F1=0.2445)
  Directional -> Accuracy: 0.4265, MCC: 0.0751, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40293 | val 0.76195
  Epoch 011 - train 0.33697 | val 1.77169
  Classification -> best τ=0.600 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.2222

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43728 | val 1.58620
  Epoch 011 - train 0.41397 | val 3.22668
  Classification -> best τ=0.490 (val F1=0.3433)
  Directional -> Accuracy: 0.6250, MCC: 0.2308, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49632 | val 0.82550
  Epoch 013 - train 0.42664 | val 1.13315
  Classification -> best τ=0.635 (val F1=0.1607)
  Directional -> Accuracy: 0.4638, MCC: -0.1168, F1: 0.3273

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47336 | val 1.09049
  Epoch 012 - train 0.41404 | val 1.06765
  Classification -> best τ=0.420 (val F1=0.3007)
  Directional -> Accuracy: 0.6122, MCC: 0.2027, F1: 0.4242

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50197 | val 2.51827
  Epoch 012 - train 0.44240 | val 3.58037
  Classification -> best τ=0.770 (val F1=0.3827)
  Directional -> Accuracy: 0.5088, MCC: 0.0248, F1: 0.4167

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55440 | val 2.84406
  Epoch 014 - train 0.33721 | val 2.25514
  Classification -> best τ=0.685 (val F1=0.2557)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.1000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57765 | val 0.89658
  Epoch 016 - train 0.41039 | val 1.06350
  Classification -> best τ=0.480 (val F1=0.3706)
  Directional -> Accuracy: 0.6000, MCC: 0.2004, F1: 0.5862

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46892 | val 0.73663
  Epoch 011 - train 0.43556 | val 1.05539
  Classification -> best τ=0.580 (val F1=0.3219)
  Directional -> Accuracy: 0.4510, MCC: -0.0858, F1: 0.4615

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63082 | val 0.97031
  Epoch 020 - train 0.42742 | val 1.01537
  Epoch 022 - train 0.30920 | val 1.76101
  Classification -> best τ=0.875 (val F1=0.4045)
  Directional -> Accuracy: 0.5217, MCC: 0.1839, F1: 0.2326

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51738 | val 2.25381
  Epoch 011 - train 0.45108 | val 2.39285
  Classification -> best τ=0.690 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47208 | val 3.46495
  Epoch 011 - train 0.48289 | val 2.95940
  Classification -> best τ=0.605 (val F1=0.2511)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48942 | val 2.68533
  Epoch 012 - train 0.45261 | val 2.76450
  Classification -> best τ=0.600 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45308 | val 1.44760
  Epoch 011 - train 0.45985 | val 1.33600
  Classification -> best τ=0.495 (val F1=0.3495)
  Directional -> Accuracy: 0.5270, MCC: 0.2665, F1: 0.2553

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61647 | val 0.98425
  Epoch 020 - train 0.40315 | val 3.01031
  Epoch 024 - train 0.21420 | val 2.86037
  Classification -> best τ=0.465 (val F1=0.4252)
  Directional -> Accuracy: 0.4468, MCC: 0.2057, F1: 0.1875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54614 | val 1.76586
  Epoch 012 - train 0.49747 | val 1.90069
  Classification -> best τ=0.645 (val F1=0.3118)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66150 | val 1.04684
  Epoch 014 - train 0.56825 | val 2.23644
  Classification -> best τ=0.415 (val F1=0.2896)
  Directional -> Accuracy: 0.4912, MCC: -0.1288, F1: 0.6329

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59193 | val 4.91519
  Epoch 011 - train 0.58237 | val 2.98676
  Classification -> best τ=0.430 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: -0.0220, F1: 0.5952

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52601 | val 1.39833
  Epoch 011 - train 0.46563 | val 1.27747
  Classification -> best τ=0.625 (val F1=0.5155)
  Directional -> Accuracy: 0.4909, MCC: 0.0659, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45362 | val 6.71003
  Epoch 015 - train 0.26967 | val 9.14147
  Classification -> best τ=0.725 (val F1=0.3669)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57880 | val 0.76397
  Epoch 013 - train 0.45667 | val 1.30580
  Classification -> best τ=0.620 (val F1=0.1171)
  Directional -> Accuracy: 0.5476, MCC: 0.1260, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47503 | val 1.87440
  Epoch 011 - train 0.43681 | val 2.07324
  Classification -> best τ=0.305 (val F1=0.1771)
  Directional -> Accuracy: 0.5536, MCC: 0.2640, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45759 | val 1.25074
  Epoch 012 - train 0.36872 | val 1.43426
  Classification -> best τ=0.510 (val F1=0.1459)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50709 | val 0.62951
  Epoch 020 - train 0.13796 | val 1.12330
  Classification -> best τ=0.570 (val F1=0.4846)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55769 | val 0.84301
  Epoch 012 - train 0.45714 | val 1.04803
  Classification -> best τ=0.445 (val F1=0.3264)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55738 | val 0.87566
  Epoch 013 - train 0.41440 | val 0.90369
  Classification -> best τ=0.605 (val F1=0.4342)
  Directional -> Accuracy: 0.4490, MCC: -0.1229, F1: 0.5263

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59909 | val 0.73519
  Epoch 014 - train 0.46748 | val 1.23603
  Classification -> best τ=0.275 (val F1=0.3477)
  Directional -> Accuracy: 0.5417, MCC: 0.1239, F1: 0.4923

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50224 | val 2.53957
  Epoch 011 - train 0.42501 | val 3.25104
  Classification -> best τ=0.750 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51987 | val 1.27929
  Epoch 018 - train 0.34292 | val 3.33698
  Classification -> best τ=0.895 (val F1=0.3260)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36296 | val 2.40957
  Epoch 011 - train 0.31508 | val 1.48127
  Classification -> best τ=0.420 (val F1=0.3001)
  Directional -> Accuracy: 0.5476, MCC: 0.1228, F1: 0.4571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53911 | val 0.93389
  Epoch 012 - train 0.45464 | val 2.31937
  Classification -> best τ=0.450 (val F1=0.1615)
  Directional -> Accuracy: 0.5714, MCC: 0.2067, F1: 0.1429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41033 | val 1.04507
  Epoch 011 - train 0.33833 | val 1.08801
  Classification -> best τ=0.355 (val F1=0.2877)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44267 | val 0.71714
  Epoch 011 - train 0.36848 | val 0.95980
  Classification -> best τ=0.360 (val F1=0.3476)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53899 | val 1.14336
  Epoch 015 - train 0.46067 | val 1.24394
  Classification -> best τ=0.235 (val F1=0.4068)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57154 | val 2.80640
  Epoch 014 - train 0.38622 | val 1.06319
  Classification -> best τ=0.440 (val F1=0.5750)
  Directional -> Accuracy: 0.4667, MCC: -0.0632, F1: 0.3333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55759 | val 0.80970
  Epoch 012 - train 0.48025 | val 0.99611
  Classification -> best τ=0.695 (val F1=0.3612)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.1538

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43257 | val 2.88964
  Epoch 011 - train 0.35675 | val 2.36517
  Classification -> best τ=0.660 (val F1=0.3672)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55950 | val 2.35127
  Epoch 011 - train 0.49013 | val 3.12293
  Classification -> best τ=0.580 (val F1=0.1129)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41709 | val 3.73143
  Epoch 011 - train 0.42330 | val 2.99236
  Classification -> best τ=0.850 (val F1=0.2227)
  Directional -> Accuracy: 0.5357, MCC: 0.0620, F1: 0.3500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51602 | val 3.33532
  Epoch 011 - train 0.49570 | val 4.52398
  Classification -> best τ=0.635 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1039, F1: 0.4783

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48364 | val 5.29747
  Epoch 012 - train 0.42325 | val 4.52948
  Classification -> best τ=0.505 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53719 | val 1.13313
  Epoch 011 - train 0.48709 | val 1.48280

[I 2026-02-20 05:24:03,391] Trial 180 finished with value: 0.30107335520239253 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008468233957807205, 'weight_decay': 1.2331004650086251e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5622853049319301, 'early_stopping_min_delta': 0.009635871151392715}. Best is trial 180 with value: 0.30107335520239253.

  Classification -> best τ=0.420 (val F1=0.2006)
  Directional -> Accuracy: 0.6167, MCC: 0.2401, F1: 0.6349

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.30107335520239253
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50983 | val 2.82321
  Epoch 011 - train 0.50772 | val 2.86340
  Classification -> best τ=0.440 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1184, F1: 0.3043

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41684 | val 1.06916
  Epoch 011 - train 0.38575 | val 1.19245
  Classification -> best τ=0.345 (val F1=0.2029)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54716 | val 0.92086
  Epoch 014 - train 0.36272 | val 1.36640
  Classification -> best τ=0.660 (val F1=0.3882)
  Directional -> Accuracy: 0.5652, MCC: 0.1374, F1: 0.5455

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48308 | val 1.09533
  Epoch 011 - train 0.44480 | val 1.48527
  Classification -> best τ=0.510 (val F1=0.1079)
  Directional -> Accuracy: 0.5270, MCC: 0.0253, F1: 0.6154

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59353 | val 2.69191
  Epoch 015 - train 0.32803 | val 3.08181
  Classification -> best τ=0.580 (val F1=0.4753)
  Directional -> Accuracy: 0.7200, MCC: 0.4391, F1: 0.7308

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42838 | val 1.09098
  Epoch 011 - train 0.39646 | val 1.15083
  Classification -> best τ=0.485 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60097 | val 1.94918
  Epoch 013 - train 0.43814 | val 2.34253
  Classification -> best τ=0.480 (val F1=0.1294)
  Directional -> Accuracy: 0.4265, MCC: 0.1413, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41003 | val 1.07760
  Epoch 014 - train 0.24321 | val 1.45411
  Classification -> best τ=0.415 (val F1=0.1228)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43022 | val 2.22110
  Epoch 011 - train 0.41944 | val 3.16737
  Classification -> best τ=0.705 (val F1=0.3376)
  Directional -> Accuracy: 0.6042, MCC: 0.1746, F1: 0.2963

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60210 | val 0.89908
  Epoch 020 - train 0.46813 | val 0.82882
  Epoch 022 - train 0.43269 | val 0.98625
  Classification -> best τ=0.480 (val F1=0.3318)
  Directional -> Accuracy: 0.5072, MCC: 0.0562, F1: 0.5278

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56812 | val 0.92492
  Epoch 011 - train 0.51314 | val 1.11464
  Classification -> best τ=0.420 (val F1=0.3590)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53296 | val 2.99267
  Epoch 013 - train 0.37539 | val 4.86737
  Classification -> best τ=0.415 (val F1=0.1724)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50460 | val 0.65636
  Epoch 020 - train 0.25247 | val 1.09922
  Epoch 022 - train 0.16359 | val 1.26398
  Classification -> best τ=0.520 (val F1=0.3172)
  Directional -> Accuracy: 0.5714, MCC: 0.2781, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66247 | val 0.89097
  Epoch 011 - train 0.62546 | val 0.72683
  Classification -> best τ=0.525 (val F1=0.3774)
  Directional -> Accuracy: 0.6000, MCC: 0.2121, F1: 0.5200

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51225 | val 2.80774
  Epoch 012 - train 0.45393 | val 3.70685
  Classification -> best τ=0.530 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61163 | val 1.20473
  Epoch 016 - train 0.45842 | val 1.76554
  Classification -> best τ=0.405 (val F1=0.3589)
  Directional -> Accuracy: 0.5797, MCC: 0.1465, F1: 0.6882

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65666 | val 0.78806
  Epoch 011 - train 0.56563 | val 0.85507
  Classification -> best τ=0.810 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48870 | val 1.91300
  Epoch 011 - train 0.46682 | val 2.35409
  Classification -> best τ=0.690 (val F1=0.2220)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57977 | val 1.10953
  Epoch 012 - train 0.51740 | val 1.40689
  Classification -> best τ=0.255 (val F1=0.2077)
  Directional -> Accuracy: 0.4531, MCC: 0.0359, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49482 | val 2.09582
  Epoch 011 - train 0.47533 | val 1.81615
  Classification -> best τ=0.620 (val F1=0.2588)
  Directional -> Accuracy: 0.4865, MCC: 0.1332, F1: 0.1739

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54432 | val 2.44231
  Epoch 018 - train 0.33124 | val 3.46359
  Classification -> best τ=0.630 (val F1=0.4104)
  Directional -> Accuracy: 0.4043, MCC: -0.0121, F1: 0.1765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51195 | val 2.17503
  Epoch 011 - train 0.56757 | val 2.43722
  Classification -> best τ=0.555 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50794 | val 2.46640
  Epoch 012 - train 0.44537 | val 3.09320
  Classification -> best τ=0.605 (val F1=0.3332)
  Directional -> Accuracy: 0.4386, MCC: -0.0639, F1: 0.2727

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54892 | val 2.08411
  Epoch 012 - train 0.51315 | val 2.49672
  Classification -> best τ=0.730 (val F1=0.1320)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52756 | val 1.02099
  Epoch 011 - train 0.51311 | val 1.22456
  Classification -> best τ=0.385 (val F1=0.3436)
  Directional -> Accuracy: 0.5818, MCC: 0.2155, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41895 | val 4.22354
  Epoch 011 - train 0.33006 | val 4.71173
  Classification -> best τ=0.770 (val F1=0.1048)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67266 | val 0.74751
  Epoch 013 - train 0.50531 | val 0.81967
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46439 | val 1.78198
  Epoch 012 - train 0.40528 | val 2.05429
  Classification -> best τ=0.330 (val F1=0.3143)
  Directional -> Accuracy: 0.5714, MCC: 0.2187, F1: 0.4783

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49475 | val 0.99510
  Epoch 013 - train 0.29303 | val 1.24607
  Classification -> best τ=0.485 (val F1=0.1748)
  Directional -> Accuracy: 0.5750, MCC: 0.1297, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49349 | val 0.75919
  Epoch 011 - train 0.41652 | val 0.99637
  Classification -> best τ=0.520 (val F1=0.3656)
  Directional -> Accuracy: 0.5000, MCC: 0.0142, F1: 0.5532

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41801 | val 1.27226
  Epoch 011 - train 0.39280 | val 1.06404
  Classification -> best τ=0.390 (val F1=0.2357)
  Directional -> Accuracy: 0.4524, MCC: -0.1513, F1: 0.5660

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42999 | val 1.32436
  Epoch 011 - train 0.37650 | val 1.22484
  Classification -> best τ=0.565 (val F1=0.2399)
  Directional -> Accuracy: 0.4286, MCC: -0.1293, F1: 0.3000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58653 | val 1.98383
  Epoch 013 - train 0.48701 | val 3.61391
  Classification -> best τ=0.320 (val F1=0.4032)
  Directional -> Accuracy: 0.5556, MCC: 0.1685, F1: 0.4839

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53653 | val 3.28042
  Epoch 011 - train 0.45494 | val 3.89565
  Classification -> best τ=0.510 (val F1=0.3742)
  Directional -> Accuracy: 0.5349, MCC: 0.0733, F1: 0.2857

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47761 | val 1.72892
  Epoch 011 - train 0.42950 | val 1.68708
  Classification -> best τ=0.745 (val F1=0.3420)
  Directional -> Accuracy: 0.6364, MCC: 0.2807, F1: 0.6571

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35045 | val 1.23213
  Epoch 011 - train 0.26019 | val 1.88841
  Classification -> best τ=0.445 (val F1=0.2132)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42990 | val 3.47435
  Epoch 011 - train 0.38045 | val 3.62549
  Classification -> best τ=0.450 (val F1=0.2450)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.4828

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35169 | val 1.15541
  Epoch 011 - train 0.34008 | val 2.08706
  Classification -> best τ=0.565 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41684 | val 0.89059
  Epoch 012 - train 0.29520 | val 0.73334
  Classification -> best τ=0.370 (val F1=0.3378)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59943 | val 1.39073
  Epoch 015 - train 0.45122 | val 0.87754
  Classification -> best τ=0.385 (val F1=0.3785)
  Directional -> Accuracy: 0.5135, MCC: 0.0910, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41147 | val 1.13860
  Epoch 012 - train 0.37528 | val 1.28341
  Classification -> best τ=0.650 (val F1=0.2174)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38665 | val 1.87805
  Epoch 011 - train 0.39161 | val 1.83509
  Classification -> best τ=0.430 (val F1=0.2408)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51599 | val 1.12972
  Epoch 011 - train 0.52092 | val 1.30177
  Classification -> best τ=0.770 (val F1=0.5557)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.52385 | val 3.68701
  Epoch 011 - train 0.48458 | val 4.21605
  Classification -> best τ=0.310 (val F1=0.0251)
  Directional -> Accuracy: 0.4545, MCC: -0.1162, F1: 0.5312

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45209 | val 3.40570
  Epoch 011 - train 0.42505 | val 3.47889
  Classification -> best τ=0.570 (val F1=0.4089)
  Directional -> Accuracy: 0.5714, MCC: 0.2566, F1: 0.6842

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59263 | val 0.96657
  Epoch 011 - train 0.54599 | val 1.47007
  Classification -> best τ=0.430 (val F1=0.1818)
  Directional -> Accuracy: 0.5849, MCC: 0.1825, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53685 | val 3.58455
  Epoch 011 - train 0.49510 | val 3.04037
  Classification -> best τ=0.750 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54458 | val 1.59605
  Epoch 011 - train 0.54817 | val 1.87254

[I 2026-02-20 05:25:35,756] Trial 181 finished with value: 0.261179282773121 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008434477630004248, 'weight_decay': 1.2356177601057693e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5568044650799513, 'early_stopping_min_delta': 0.009666509230578482}. Best is trial 180 with value: 0.30107335520239253.

  Classification -> best τ=0.555 (val F1=0.2124)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.261179282773121
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52443 | val 1.70587
  Epoch 011 - train 0.49005 | val 1.85494
  Classification -> best τ=0.500 (val F1=0.3013)
  Directional -> Accuracy: 0.4868, MCC: -0.0468, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49040 | val 1.39268
  Epoch 013 - train 0.33522 | val 1.62226
  Classification -> best τ=0.420 (val F1=0.2471)
  Directional -> Accuracy: 0.6667, MCC: 0.3086, F1: 0.7619

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49774 | val 0.80386
  Epoch 011 - train 0.49536 | val 0.83793
  Classification -> best τ=0.570 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59959 | val 1.10336
  Epoch 012 - train 0.53769 | val 0.93729
  Classification -> best τ=0.470 (val F1=0.0520)
  Directional -> Accuracy: 0.5946, MCC: 0.1829, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57103 | val 0.80587
  Epoch 011 - train 0.50473 | val 0.79204
  Classification -> best τ=0.450 (val F1=0.3984)
  Directional -> Accuracy: 0.5000, MCC: 0.0065, F1: 0.4681

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39833 | val 0.94672
  Epoch 011 - train 0.34223 | val 1.15710
  Classification -> best τ=0.600 (val F1=0.2208)
  Directional -> Accuracy: 0.5652, MCC: 0.1348, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58655 | val 1.24076
  Epoch 011 - train 0.56584 | val 1.57207
  Classification -> best τ=0.175 (val F1=0.2463)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49748 | val 1.67472
  Epoch 017 - train 0.28370 | val 6.79882
  Classification -> best τ=0.560 (val F1=0.2168)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.5882

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45863 | val 1.82479
  Epoch 012 - train 0.39445 | val 2.60304
  Classification -> best τ=0.575 (val F1=0.2753)
  Directional -> Accuracy: 0.6042, MCC: 0.2494, F1: 0.6275

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55557 | val 0.99144
  Epoch 014 - train 0.39433 | val 1.09815
  Classification -> best τ=0.545 (val F1=0.2091)
  Directional -> Accuracy: 0.5072, MCC: -0.0112, F1: 0.4138

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58280 | val 0.73562
  Epoch 018 - train 0.37729 | val 1.17738
  Classification -> best τ=0.370 (val F1=0.4415)
  Directional -> Accuracy: 0.5714, MCC: 0.1044, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50240 | val 2.14263
  Epoch 012 - train 0.40300 | val 3.29204
  Classification -> best τ=0.335 (val F1=0.2099)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41515 | val 1.80926
  Epoch 013 - train 0.33621 | val 1.06203
  Classification -> best τ=0.675 (val F1=0.2774)
  Directional -> Accuracy: 0.5000, MCC: 0.1319, F1: 0.6316

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67864 | val 0.78418
  Epoch 015 - train 0.49903 | val 1.13361
  Classification -> best τ=0.320 (val F1=0.4048)
  Directional -> Accuracy: 0.4833, MCC: -0.0338, F1: 0.5231

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51915 | val 2.69656
  Epoch 014 - train 0.35930 | val 3.27890
  Classification -> best τ=0.660 (val F1=0.2837)
  Directional -> Accuracy: 0.5686, MCC: 0.1115, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59526 | val 0.83718
  Epoch 013 - train 0.46883 | val 0.97509
  Classification -> best τ=0.805 (val F1=0.3159)
  Directional -> Accuracy: 0.5217, MCC: 0.0978, F1: 0.3774

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48311 | val 1.92498
  Epoch 012 - train 0.46260 | val 3.04669
  Classification -> best τ=0.360 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49295 | val 2.47157
  Epoch 011 - train 0.46749 | val 3.11601
  Classification -> best τ=0.215 (val F1=0.2167)
  Directional -> Accuracy: 0.5867, MCC: 0.0680, F1: 0.7048

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56848 | val 0.96569
  Epoch 017 - train 0.43816 | val 1.52867
  Classification -> best τ=0.205 (val F1=0.3099)
  Directional -> Accuracy: 0.4844, MCC: 0.1315, F1: 0.2667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58845 | val 1.08933
  Epoch 012 - train 0.46561 | val 1.28635
  Classification -> best τ=0.110 (val F1=0.3848)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45321 | val 3.42711
  Epoch 012 - train 0.41454 | val 1.79651
  Classification -> best τ=0.555 (val F1=0.2779)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54563 | val 3.25811
  Epoch 011 - train 0.49012 | val 2.79788
  Classification -> best τ=0.550 (val F1=0.2044)
  Directional -> Accuracy: 0.4769, MCC: -0.0438, F1: 0.4138

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56534 | val 1.29334
  Epoch 011 - train 0.53557 | val 1.49326
  Classification -> best τ=0.565 (val F1=0.2875)
  Directional -> Accuracy: 0.4737, MCC: 0.0014, F1: 0.3750

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55146 | val 2.76627
  Epoch 012 - train 0.45455 | val 3.27551
  Classification -> best τ=0.725 (val F1=0.2055)
  Directional -> Accuracy: 0.5231, MCC: 0.0147, F1: 0.1622

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51361 | val 1.48512
  Epoch 012 - train 0.46329 | val 1.39795
  Classification -> best τ=0.345 (val F1=0.3749)
  Directional -> Accuracy: 0.5273, MCC: 0.0828, F1: 0.4800

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42001 | val 4.11496
  Epoch 011 - train 0.40167 | val 4.17315
  Classification -> best τ=0.650 (val F1=0.0385)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54863 | val 0.80934
  Epoch 012 - train 0.53284 | val 0.94673
  Classification -> best τ=0.495 (val F1=0.3347)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51833 | val 1.20610
  Epoch 012 - train 0.44042 | val 1.84284
  Classification -> best τ=0.710 (val F1=0.2976)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51145 | val 1.35207
  Epoch 014 - train 0.38721 | val 0.94217
  Classification -> best τ=0.690 (val F1=0.5105)
  Directional -> Accuracy: 0.4250, MCC: -0.1372, F1: 0.4103

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51881 | val 0.93978
  Epoch 012 - train 0.46071 | val 0.81004
  Classification -> best τ=0.490 (val F1=0.3656)
  Directional -> Accuracy: 0.5238, MCC: 0.0983, F1: 0.6296

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54120 | val 1.54530
  Epoch 011 - train 0.48179 | val 1.29799
  Classification -> best τ=0.400 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51465 | val 1.11504
  Epoch 012 - train 0.38030 | val 1.43154
  Classification -> best τ=0.345 (val F1=0.4120)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63064 | val 0.93081
  Epoch 014 - train 0.51052 | val 1.30509
  Classification -> best τ=0.325 (val F1=0.3145)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51679 | val 1.72574
  Epoch 011 - train 0.47236 | val 1.83023
  Classification -> best τ=0.300 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55217 | val 0.88699
  Epoch 011 - train 0.51015 | val 1.13515
  Classification -> best τ=0.385 (val F1=0.2357)
  Directional -> Accuracy: 0.5909, MCC: 0.1070, F1: 0.7327

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33934 | val 1.16286
  Epoch 011 - train 0.33985 | val 1.19530
  Classification -> best τ=0.395 (val F1=0.2292)
  Directional -> Accuracy: 0.6190, MCC: 0.2409, F1: 0.6190

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47001 | val 1.68289
  Epoch 013 - train 0.34509 | val 1.70684
  Classification -> best τ=0.405 (val F1=0.2450)
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44741 | val 0.85715
  Epoch 013 - train 0.25462 | val 1.13080
  Classification -> best τ=0.535 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57457 | val 0.86989
  Epoch 015 - train 0.34703 | val 0.91619
  Classification -> best τ=0.395 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51235 | val 1.04989
  Epoch 011 - train 0.46375 | val 0.81704
  Classification -> best τ=0.245 (val F1=0.2696)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49218 | val 1.35305
  Epoch 013 - train 0.36649 | val 0.88787
  Classification -> best τ=0.435 (val F1=0.2174)
  Directional -> Accuracy: 0.5111, MCC: 0.0048, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61526 | val 0.79600
  Epoch 011 - train 0.52075 | val 1.36484
  Classification -> best τ=0.550 (val F1=0.3273)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44523 | val 0.68529
  Epoch 016 - train 0.30385 | val 1.42439
  Classification -> best τ=0.845 (val F1=0.5557)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.53483 | val 5.10035
  Epoch 011 - train 0.50561 | val 5.51081
  Classification -> best τ=0.490 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42858 | val 3.31198
  Epoch 011 - train 0.39430 | val 3.82219
  Classification -> best τ=0.470 (val F1=0.5017)
  Directional -> Accuracy: 0.4821, MCC: -0.0384, F1: 0.4528

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55311 | val 2.20010
  Epoch 012 - train 0.49851 | val 2.42577
  Classification -> best τ=0.660 (val F1=0.0406)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48250 | val 3.76840
  Epoch 011 - train 0.47394 | val 4.82233
  Classification -> best τ=0.890 (val F1=0.1154)
  Directional -> Accuracy: 0.5091, MCC: 0.1249, F1: 0.1818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53049 | val 0.78344

[I 2026-02-20 05:27:08,906] Trial 182 finished with value: 0.2771453668269757 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005747668285207924, 'weight_decay': 1.0007126649279282e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5781754125401858, 'early_stopping_min_delta': 0.00945517273782568}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 018 - train 0.38246 | val 1.20483
  Classification -> best τ=0.310 (val F1=0.1138)
  Directional -> Accuracy: 0.5833, MCC: 0.2813, F1: 0.6914

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2771453668269757
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57057 | val 1.73633
  Epoch 013 - train 0.45767 | val 3.50534
  Classification -> best τ=0.485 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: 0.0306, F1: 0.3396

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46135 | val 1.39851
  Epoch 012 - train 0.42356 | val 1.33744
  Classification -> best τ=0.320 (val F1=0.1621)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50957 | val 0.93720
  Epoch 011 - train 0.48685 | val 1.13443
  Classification -> best τ=0.685 (val F1=0.3140)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43546 | val 3.08201
  Epoch 011 - train 0.36959 | val 4.53348
  Classification -> best τ=0.125 (val F1=0.1235)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54149 | val 0.72970
  Epoch 013 - train 0.42096 | val 1.16492
  Classification -> best τ=0.405 (val F1=0.4787)
  Directional -> Accuracy: 0.6600, MCC: 0.3669, F1: 0.5854

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36690 | val 0.72335
  Epoch 011 - train 0.35577 | val 0.74728
  Classification -> best τ=0.670 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59815 | val 2.00863
  Epoch 014 - train 0.49205 | val 1.74308
  Classification -> best τ=0.455 (val F1=0.2481)
  Directional -> Accuracy: 0.4412, MCC: 0.1743, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45493 | val 0.85552
  Epoch 018 - train 0.23798 | val 1.82563
  Classification -> best τ=0.140 (val F1=0.1639)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41910 | val 1.15627
  Epoch 011 - train 0.41213 | val 1.26768
  Classification -> best τ=0.370 (val F1=0.2497)
  Directional -> Accuracy: 0.3958, MCC: -0.1690, F1: 0.5246

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50705 | val 1.36998
  Epoch 013 - train 0.41281 | val 2.56295
  Classification -> best τ=0.345 (val F1=0.2776)
  Directional -> Accuracy: 0.5362, MCC: 0.0392, F1: 0.4286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57766 | val 0.81993
  Epoch 011 - train 0.59025 | val 0.98853
  Classification -> best τ=0.390 (val F1=0.3231)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50411 | val 2.50706
  Epoch 011 - train 0.49206 | val 2.50914
  Classification -> best τ=0.490 (val F1=0.3147)
  Directional -> Accuracy: 0.5789, MCC: 0.1996, F1: 0.4286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42467 | val 3.43145
  Epoch 011 - train 0.42318 | val 3.81686
  Classification -> best τ=0.420 (val F1=0.1801)
  Directional -> Accuracy: 0.5000, MCC: -0.0754, F1: 0.2222

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57863 | val 0.62310
  Epoch 015 - train 0.43056 | val 0.85442
  Classification -> best τ=0.290 (val F1=0.4447)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54503 | val 3.47430
  Epoch 011 - train 0.49174 | val 2.75250
  Classification -> best τ=0.420 (val F1=0.2084)
  Directional -> Accuracy: 0.5294, MCC: 0.0352, F1: 0.4286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65475 | val 0.76031
  Epoch 016 - train 0.53814 | val 1.26583
  Classification -> best τ=0.520 (val F1=0.3339)
  Directional -> Accuracy: 0.5362, MCC: 0.0565, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44528 | val 2.13556
  Epoch 011 - train 0.46332 | val 2.27097
  Classification -> best τ=0.390 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49594 | val 1.26812
  Epoch 011 - train 0.52681 | val 1.04311
  Classification -> best τ=0.370 (val F1=0.1918)
  Directional -> Accuracy: 0.5067, MCC: 0.1594, F1: 0.3934

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53722 | val 0.98913
  Epoch 011 - train 0.50761 | val 0.94253
  Classification -> best τ=0.345 (val F1=0.2843)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51687 | val 1.16764
  Epoch 011 - train 0.48565 | val 1.40005
  Classification -> best τ=0.440 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49149 | val 0.68343
  Epoch 015 - train 0.44194 | val 0.71499
  Classification -> best τ=0.455 (val F1=0.3214)
  Directional -> Accuracy: 0.5957, MCC: 0.0615, F1: 0.7164

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56103 | val 1.53095
  Epoch 012 - train 0.52467 | val 1.96275
  Classification -> best τ=0.585 (val F1=0.2509)
  Directional -> Accuracy: 0.5385, MCC: 0.1688, F1: 0.2105

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61747 | val 0.75694
  Epoch 014 - train 0.48947 | val 1.55859
  Classification -> best τ=0.690 (val F1=0.3833)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49895 | val 2.25254
  Epoch 011 - train 0.47688 | val 2.01154
  Classification -> best τ=0.625 (val F1=0.1565)
  Directional -> Accuracy: 0.5538, MCC: 0.1327, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54483 | val 1.90519
  Epoch 011 - train 0.49453 | val 1.83856
  Classification -> best τ=0.520 (val F1=0.3563)
  Directional -> Accuracy: 0.4727, MCC: -0.0669, F1: 0.5246

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41545 | val 5.31989
  Epoch 011 - train 0.39351 | val 5.42524
  Classification -> best τ=0.750 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53875 | val 1.53171
  Epoch 011 - train 0.50428 | val 1.79140
  Classification -> best τ=0.450 (val F1=0.1514)
  Directional -> Accuracy: 0.4048, MCC: -0.1340, F1: 0.2424

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48454 | val 1.04536
  Epoch 011 - train 0.46291 | val 1.11875
  Classification -> best τ=0.320 (val F1=0.2315)
  Directional -> Accuracy: 0.5893, MCC: 0.1553, F1: 0.6567

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38293 | val 0.91271
  Epoch 011 - train 0.37222 | val 0.93081
  Classification -> best τ=0.615 (val F1=0.2774)
  Directional -> Accuracy: 0.5000, MCC: 0.0205, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45643 | val 0.77869
  Epoch 011 - train 0.38606 | val 0.86526
  Classification -> best τ=0.680 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0195, F1: 0.2308

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44008 | val 1.03883
  Epoch 012 - train 0.32034 | val 1.72887
  Classification -> best τ=0.280 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43769 | val 0.94317
  Epoch 011 - train 0.41756 | val 1.18380
  Classification -> best τ=0.610 (val F1=0.1679)
  Directional -> Accuracy: 0.4694, MCC: -0.1140, F1: 0.5938

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62798 | val 0.62407
  Epoch 016 - train 0.51706 | val 1.15129
  Classification -> best τ=0.275 (val F1=0.4460)
  Directional -> Accuracy: 0.5694, MCC: 0.1429, F1: 0.5867

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52303 | val 1.65674
  Epoch 011 - train 0.50779 | val 1.67485
  Classification -> best τ=0.760 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47641 | val 0.97019
  Epoch 012 - train 0.46310 | val 1.30203
  Classification -> best τ=0.290 (val F1=0.3634)
  Directional -> Accuracy: 0.5455, MCC: 0.0874, F1: 0.5833

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48764 | val 1.08595
  Epoch 011 - train 0.39452 | val 1.18053
  Classification -> best τ=0.430 (val F1=0.1243)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44294 | val 3.19328
  Epoch 012 - train 0.36293 | val 4.54877
  Classification -> best τ=0.340 (val F1=0.2256)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51031 | val 1.67660
  Epoch 013 - train 0.33295 | val 1.97111
  Classification -> best τ=0.430 (val F1=0.3611)
  Directional -> Accuracy: 0.5000, MCC: 0.0826, F1: 0.4651

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52492 | val 0.97746
  Epoch 012 - train 0.43828 | val 0.90286
  Classification -> best τ=0.385 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60007 | val 1.60117
  Epoch 014 - train 0.43786 | val 2.46296
  Classification -> best τ=0.265 (val F1=0.3527)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41494 | val 1.31577
  Epoch 012 - train 0.35091 | val 0.82081
  Classification -> best τ=0.545 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: 0.0764, F1: 0.4615

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50804 | val 1.12740
  Epoch 012 - train 0.46947 | val 1.20658
  Classification -> best τ=0.575 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.0741

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45437 | val 1.48296
  Epoch 011 - train 0.41941 | val 1.41189
  Classification -> best τ=0.600 (val F1=0.4176)
  Directional -> Accuracy: 0.5208, MCC: 0.2176, F1: 0.5818

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54705 | val 3.65170
  Epoch 011 - train 0.52491 | val 4.04480
  Classification -> best τ=0.345 (val F1=0.0782)
  Directional -> Accuracy: 0.5091, MCC: -0.1773, F1: 0.6747

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39891 | val 2.70047
  Epoch 011 - train 0.38715 | val 2.96315
  Classification -> best τ=0.695 (val F1=0.3729)
  Directional -> Accuracy: 0.5714, MCC: 0.2276, F1: 0.6757

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54401 | val 1.47805
  Epoch 012 - train 0.45568 | val 2.26931
  Classification -> best τ=0.555 (val F1=0.1479)
  Directional -> Accuracy: 0.3774, MCC: -0.2450, F1: 0.3774

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44272 | val 4.33860
  Epoch 011 - train 0.39926 | val 5.58636
  Classification -> best τ=0.935 (val F1=0.2121)
  Directional -> Accuracy: 0.5455, MCC: 0.1437, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53955 | val 1.40722

[I 2026-02-20 05:28:37,352] Trial 183 finished with value: 0.26695894048314955 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005970366899664601, 'weight_decay': 1.1578716612734262e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5799093244715806, 'early_stopping_min_delta': 0.009318821379519388}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.33866 | val 1.24724
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26695894048314955
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51649 | val 1.30178
  Epoch 011 - train 0.49628 | val 1.36338
  Classification -> best τ=0.655 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43102 | val 2.21187
  Epoch 012 - train 0.35392 | val 3.22353
  Classification -> best τ=0.380 (val F1=0.2670)
  Directional -> Accuracy: 0.5111, MCC: -0.1591, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54770 | val 0.88009
  Epoch 012 - train 0.55195 | val 1.05476
  Classification -> best τ=0.500 (val F1=0.4918)
  Directional -> Accuracy: 0.5217, MCC: 0.0318, F1: 0.5926

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62070 | val 0.83518
  Epoch 011 - train 0.57227 | val 1.20082
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39918 | val 1.17020
  Epoch 011 - train 0.34620 | val 1.40569
  Classification -> best τ=0.470 (val F1=0.3919)
  Directional -> Accuracy: 0.7600, MCC: 0.5290, F1: 0.7500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33306 | val 1.20391
  Epoch 011 - train 0.39686 | val 1.14471
  Classification -> best τ=0.495 (val F1=0.2593)
  Directional -> Accuracy: 0.5217, MCC: 0.0543, F1: 0.5600

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58402 | val 1.92860
  Epoch 012 - train 0.48782 | val 3.36686
  Classification -> best τ=0.170 (val F1=0.2445)
  Directional -> Accuracy: 0.3971, MCC: -0.0366, F1: 0.5591

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45018 | val 5.74192
  Epoch 013 - train 0.25435 | val 7.61166
  Classification -> best τ=0.675 (val F1=0.3689)
  Directional -> Accuracy: 0.6190, MCC: 0.1964, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39477 | val 2.50271
  Epoch 011 - train 0.43159 | val 3.60341
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51931 | val 0.78502
  Epoch 012 - train 0.42355 | val 0.86921
  Classification -> best τ=0.415 (val F1=0.3245)
  Directional -> Accuracy: 0.4928, MCC: 0.0112, F1: 0.4928

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55078 | val 1.11162
  Epoch 011 - train 0.59989 | val 0.77232
  Classification -> best τ=0.370 (val F1=0.1228)
  Directional -> Accuracy: 0.5102, MCC: 0.0545, F1: 0.5556

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50003 | val 1.48196
  Epoch 011 - train 0.47528 | val 1.27527
  Classification -> best τ=0.530 (val F1=0.2230)
  Directional -> Accuracy: 0.4035, MCC: -0.1933, F1: 0.4138

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40799 | val 2.14304
  Epoch 011 - train 0.39601 | val 2.32822
  Classification -> best τ=0.560 (val F1=0.2791)
  Directional -> Accuracy: 0.5000, MCC: -0.0338, F1: 0.3636

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62792 | val 0.87430
  Epoch 014 - train 0.52192 | val 1.06604
  Classification -> best τ=0.270 (val F1=0.3898)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5946

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43027 | val 4.28602
  Epoch 011 - train 0.45278 | val 4.29033
  Classification -> best τ=0.775 (val F1=0.2707)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58363 | val 2.16681
  Epoch 014 - train 0.41584 | val 1.31192
  Classification -> best τ=0.345 (val F1=0.2795)
  Directional -> Accuracy: 0.5797, MCC: 0.2293, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50975 | val 1.99251
  Epoch 012 - train 0.40523 | val 1.50983
  Classification -> best τ=0.760 (val F1=0.2559)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57801 | val 1.63272
  Epoch 013 - train 0.43551 | val 1.78772
  Classification -> best τ=0.240 (val F1=0.2004)
  Directional -> Accuracy: 0.5867, MCC: 0.1437, F1: 0.6517

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52150 | val 0.85451
  Epoch 011 - train 0.48013 | val 0.97106
  Classification -> best τ=0.480 (val F1=0.2945)
  Directional -> Accuracy: 0.4844, MCC: 0.0861, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55368 | val 1.27002
  Epoch 013 - train 0.51403 | val 1.58938
  Classification -> best τ=0.410 (val F1=0.2217)
  Directional -> Accuracy: 0.5811, MCC: 0.1954, F1: 0.5507

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60234 | val 1.17747
  Epoch 019 - train 0.35273 | val 1.25345
  Classification -> best τ=0.530 (val F1=0.3308)
  Directional -> Accuracy: 0.5106, MCC: 0.1957, F1: 0.4103

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59530 | val 2.52830
  Epoch 013 - train 0.47142 | val 4.63829
  Classification -> best τ=0.725 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59168 | val 0.85261
  Epoch 011 - train 0.59519 | val 0.93848
  Classification -> best τ=0.580 (val F1=0.3374)
  Directional -> Accuracy: 0.5263, MCC: -0.0115, F1: 0.6400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57137 | val 1.34457
  Epoch 011 - train 0.57083 | val 1.23332
  Classification -> best τ=0.470 (val F1=0.1741)
  Directional -> Accuracy: 0.6308, MCC: 0.2662, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40825 | val 1.99147
  Epoch 011 - train 0.41611 | val 1.61693
  Classification -> best τ=0.315 (val F1=0.2359)
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44737 | val 3.71010
  Epoch 012 - train 0.35417 | val 5.01613
  Classification -> best τ=0.560 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45696 | val 1.40769
  Epoch 011 - train 0.41362 | val 2.02826
  Classification -> best τ=0.545 (val F1=0.0694)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50038 | val 0.93801
  Epoch 012 - train 0.43923 | val 1.28482
  Classification -> best τ=0.555 (val F1=0.3558)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45391 | val 0.96248
  Epoch 013 - train 0.27203 | val 1.16667
  Classification -> best τ=0.505 (val F1=0.3239)
  Directional -> Accuracy: 0.6500, MCC: 0.2845, F1: 0.7083

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49259 | val 0.81977
  Epoch 012 - train 0.41445 | val 0.75531
  Classification -> best τ=0.370 (val F1=0.4035)
  Directional -> Accuracy: 0.5000, MCC: 0.0332, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47002 | val 1.09492
  Epoch 014 - train 0.28045 | val 1.34087
  Classification -> best τ=0.530 (val F1=0.1707)
  Directional -> Accuracy: 0.4762, MCC: 0.0663, F1: 0.1538

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56284 | val 0.85198
  Epoch 013 - train 0.42647 | val 0.90938
  Classification -> best τ=0.520 (val F1=0.2904)
  Directional -> Accuracy: 0.5510, MCC: 0.1535, F1: 0.7027

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48029 | val 1.30716
  Epoch 011 - train 0.45543 | val 1.21808
  Classification -> best τ=0.480 (val F1=0.3450)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49048 | val 1.74524
  Epoch 011 - train 0.44111 | val 2.24187
  Classification -> best τ=0.335 (val F1=0.1309)
  Directional -> Accuracy: 0.5581, MCC: 0.1788, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49211 | val 1.90737
  Epoch 011 - train 0.45537 | val 1.99484
  Classification -> best τ=0.495 (val F1=0.3001)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50554 | val 1.04179
  Epoch 011 - train 0.45850 | val 0.84186
  Classification -> best τ=0.425 (val F1=0.2464)
  Directional -> Accuracy: 0.5476, MCC: 0.0879, F1: 0.5957

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40522 | val 4.11296
  Epoch 011 - train 0.37441 | val 4.14027
  Classification -> best τ=0.625 (val F1=0.2450)
  Directional -> Accuracy: 0.4107, MCC: -0.1817, F1: 0.3774

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40280 | val 2.07804
  Epoch 011 - train 0.42123 | val 2.94637
  Classification -> best τ=0.165 (val F1=0.1720)
  Directional -> Accuracy: 0.5652, MCC: -0.0460, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44924 | val 0.88001
  Epoch 011 - train 0.39401 | val 0.88099
  Classification -> best τ=0.555 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58858 | val 0.78690
  Epoch 013 - train 0.47208 | val 1.31474
  Classification -> best τ=0.640 (val F1=0.1901)
  Directional -> Accuracy: 0.5405, MCC: 0.1712, F1: 0.1053

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50632 | val 1.89759
  Epoch 013 - train 0.35653 | val 1.89880
  Classification -> best τ=0.495 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.1561, F1: 0.5778

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63320 | val 1.05299
  Epoch 014 - train 0.42711 | val 1.46775
  Classification -> best τ=0.870 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66249 | val 1.20574
  Epoch 013 - train 0.31826 | val 1.71690
  Classification -> best τ=0.530 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56169 | val 1.40483
  Epoch 011 - train 0.54017 | val 2.17619
  Classification -> best τ=0.430 (val F1=0.3303)
  Directional -> Accuracy: 0.4909, MCC: -0.0575, F1: 0.5882

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47881 | val 2.13916
  Epoch 011 - train 0.39754 | val 2.45843
  Classification -> best τ=0.720 (val F1=0.3123)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57942 | val 1.25241
  Epoch 013 - train 0.43834 | val 2.31457
  Classification -> best τ=0.515 (val F1=0.0492)
  Directional -> Accuracy: 0.5283, MCC: 0.0607, F1: 0.4898

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42107 | val 6.67906
  Epoch 011 - train 0.40823 | val 8.42503
  Classification -> best τ=0.845 (val F1=0.0711)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57240 | val 0.74569

[I 2026-02-20 05:30:04,773] Trial 184 finished with value: 0.2544317294128724 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008412075397969319, 'weight_decay': 9.916845570716393e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6124332527328061, 'early_stopping_min_delta': 0.00952788706773109}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 015 - train 0.42668 | val 1.46635
  Classification -> best τ=0.515 (val F1=0.2749)
  Directional -> Accuracy: 0.6167, MCC: 0.2668, F1: 0.4390

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2544317294128724
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60292 | val 0.77466
  Epoch 018 - train 0.40650 | val 1.42606
  Classification -> best τ=0.690 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: 0.0206, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47234 | val 1.61836
  Epoch 011 - train 0.46184 | val 1.33009
  Classification -> best τ=0.315 (val F1=0.2769)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58219 | val 0.85831
  Epoch 012 - train 0.43756 | val 1.72613
  Classification -> best τ=0.615 (val F1=0.3237)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57372 | val 2.31903
  Epoch 012 - train 0.57845 | val 1.91269
  Classification -> best τ=0.180 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49884 | val 1.75782
  Epoch 012 - train 0.35010 | val 2.90279
  Classification -> best τ=0.550 (val F1=0.4414)
  Directional -> Accuracy: 0.7000, MCC: 0.4223, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40496 | val 0.80412
  Epoch 011 - train 0.33730 | val 0.80148
  Classification -> best τ=0.515 (val F1=0.2357)
  Directional -> Accuracy: 0.5000, MCC: -0.0766, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58823 | val 0.78678
  Epoch 013 - train 0.52375 | val 1.22688
  Classification -> best τ=0.425 (val F1=0.2727)
  Directional -> Accuracy: 0.5441, MCC: 0.1940, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36802 | val 3.87356
  Epoch 012 - train 0.27511 | val 4.63651
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49274 | val 3.83754
  Epoch 011 - train 0.45271 | val 1.07016
  Classification -> best τ=0.465 (val F1=0.2166)
  Directional -> Accuracy: 0.5417, MCC: 0.0295, F1: 0.3529

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51081 | val 1.05360
  Epoch 011 - train 0.46382 | val 1.33185
  Classification -> best τ=0.505 (val F1=0.3613)
  Directional -> Accuracy: 0.3913, MCC: -0.1516, F1: 0.5116

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52569 | val 0.70150
  Epoch 013 - train 0.41702 | val 0.75597
  Classification -> best τ=0.490 (val F1=0.4196)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41091 | val 2.53153
  Epoch 011 - train 0.35521 | val 2.71610
  Classification -> best τ=0.605 (val F1=0.2650)
  Directional -> Accuracy: 0.4561, MCC: -0.0993, F1: 0.5373

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50189 | val 1.03463
  Epoch 020 - train 0.28251 | val 1.56160
  Epoch 022 - train 0.28042 | val 1.51866
  Classification -> best τ=0.575 (val F1=0.2466)
  Directional -> Accuracy: 0.3810, MCC: -0.2211, F1: 0.4348

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59135 | val 0.85026
  Epoch 020 - train 0.32760 | val 0.98990
  Epoch 021 - train 0.31875 | val 0.87277
  Classification -> best τ=0.160 (val F1=0.3083)
  Directional -> Accuracy: 0.5500, MCC: 0.1028, F1: 0.5970

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43263 | val 1.70972
  Epoch 011 - train 0.43393 | val 3.09369
  Classification -> best τ=0.555 (val F1=0.2951)
  Directional -> Accuracy: 0.6078, MCC: 0.2313, F1: 0.2857

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55714 | val 0.97150
  Epoch 011 - train 0.53809 | val 1.02411
  Classification -> best τ=0.700 (val F1=0.3570)
  Directional -> Accuracy: 0.6232, MCC: 0.2620, F1: 0.6061

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56906 | val 1.77183
  Epoch 013 - train 0.45924 | val 2.31697
  Classification -> best τ=0.615 (val F1=0.2992)
  Directional -> Accuracy: 0.4138, MCC: 0.0725, F1: 0.1500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51991 | val 1.53366
  Epoch 011 - train 0.46005 | val 2.15378
  Classification -> best τ=0.545 (val F1=0.2450)
  Directional -> Accuracy: 0.5600, MCC: 0.0782, F1: 0.6374

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54815 | val 0.94723
  Epoch 012 - train 0.45817 | val 1.01805
  Classification -> best τ=0.420 (val F1=0.3140)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46844 | val 1.71821
  Epoch 011 - train 0.45081 | val 1.92741
  Classification -> best τ=0.340 (val F1=0.3161)
  Directional -> Accuracy: 0.4595, MCC: 0.0466, F1: 0.0909

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45466 | val 2.08161
  Epoch 012 - train 0.40324 | val 0.99769
  Classification -> best τ=0.465 (val F1=0.3251)
  Directional -> Accuracy: 0.5319, MCC: -0.0887, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54667 | val 1.75952
  Epoch 011 - train 0.50667 | val 1.66249
  Classification -> best τ=0.540 (val F1=0.1294)
  Directional -> Accuracy: 0.4615, MCC: -0.0994, F1: 0.1463

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62436 | val 0.78751
  Epoch 019 - train 0.30182 | val 1.96077
  Classification -> best τ=0.660 (val F1=0.3276)
  Directional -> Accuracy: 0.4035, MCC: -0.1576, F1: 0.1053

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50534 | val 2.04302
  Epoch 012 - train 0.46360 | val 2.40235
  Classification -> best τ=0.435 (val F1=0.2484)
  Directional -> Accuracy: 0.4923, MCC: -0.0507, F1: 0.2667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40787 | val 2.56823
  Epoch 011 - train 0.36636 | val 2.93736
  Classification -> best τ=0.175 (val F1=0.4001)
  Directional -> Accuracy: 0.5818, MCC: 0.2155, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38202 | val 4.45456
  Epoch 011 - train 0.37261 | val 4.72754
  Classification -> best τ=0.635 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.1857, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62922 | val 0.72140
  Epoch 016 - train 0.36474 | val 1.50166
  Classification -> best τ=0.595 (val F1=0.0323)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.49371 | val 1.64182
  Epoch 011 - train 0.46622 | val 1.63771
  Classification -> best τ=0.505 (val F1=0.1615)
  Directional -> Accuracy: 0.4286, MCC: -0.1054, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49787 | val 0.85449
  Epoch 011 - train 0.45027 | val 1.11565
  Classification -> best τ=0.505 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55149 | val 0.69573
  Epoch 016 - train 0.35675 | val 1.31946
  Classification -> best τ=0.435 (val F1=0.4435)
  Directional -> Accuracy: 0.4524, MCC: -0.1228, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45385 | val 1.97851
  Epoch 012 - train 0.34697 | val 1.67077
  Classification -> best τ=0.515 (val F1=0.1425)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56451 | val 1.30030
  Epoch 011 - train 0.50890 | val 1.47083
  Classification -> best τ=0.435 (val F1=0.1813)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56195 | val 0.92534
  Epoch 012 - train 0.50485 | val 1.42408
  Classification -> best τ=0.345 (val F1=0.3196)
  Directional -> Accuracy: 0.5000, MCC: 0.0472, F1: 0.4194

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51772 | val 2.10520
  Epoch 011 - train 0.53154 | val 2.37429
  Classification -> best τ=0.805 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58265 | val 0.95117
  Epoch 011 - train 0.53372 | val 0.88135
  Classification -> best τ=0.780 (val F1=0.2618)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33152 | val 7.47758
  Epoch 012 - train 0.22337 | val 8.93674
  Classification -> best τ=0.450 (val F1=0.2132)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45332 | val 1.26529
  Epoch 011 - train 0.41203 | val 2.27417
  Classification -> best τ=0.410 (val F1=0.1508)
  Directional -> Accuracy: 0.5000, MCC: -0.0499, F1: 0.2632

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46856 | val 0.95892
  Epoch 016 - train 0.29275 | val 1.27018
  Classification -> best τ=0.390 (val F1=0.1953)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42603 | val 1.06022
  Epoch 011 - train 0.41480 | val 1.01060
  Classification -> best τ=0.485 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59209 | val 0.87590
  Epoch 012 - train 0.54171 | val 1.13717
  Classification -> best τ=0.330 (val F1=0.3563)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52144 | val 0.79975
  Epoch 011 - train 0.49220 | val 0.95880
  Classification -> best τ=0.470 (val F1=0.2668)
  Directional -> Accuracy: 0.5333, MCC: 0.0709, F1: 0.6557

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47016 | val 1.07571
  Epoch 011 - train 0.45815 | val 1.12644
  Classification -> best τ=0.680 (val F1=0.3612)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.2069

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45407 | val 1.58948
  Epoch 011 - train 0.40263 | val 1.76764
  Classification -> best τ=0.615 (val F1=0.4385)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.51834 | val 2.04625
  Epoch 011 - train 0.54422 | val 2.46606
  Classification -> best τ=0.430 (val F1=0.2224)
  Directional -> Accuracy: 0.4000, MCC: -0.2236, F1: 0.4762

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42297 | val 2.93827
  Epoch 011 - train 0.39704 | val 3.44867
  Classification -> best τ=0.765 (val F1=0.2227)
  Directional -> Accuracy: 0.4821, MCC: -0.0619, F1: 0.2927

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.73963 | val 0.88638
  Epoch 019 - train 0.45524 | val 2.45875
  Classification -> best τ=0.115 (val F1=0.3500)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57880 | val 2.65528
  Epoch 011 - train 0.55880 | val 3.57030
  Classification -> best τ=0.660 (val F1=0.1780)
  Directional -> Accuracy: 0.5455, MCC: 0.0933, F1: 0.6914

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48795 | val 0.95472
  Epoch 011 - train 0.48205 | val 0.90721

[I 2026-02-20 05:31:38,681] Trial 185 finished with value: 0.2716588553980688 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007119361181791274, 'weight_decay': 1.4236869139843805e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.6890433797673716, 'early_stopping_min_delta': 0.009759901458502378}. Best is trial 180 with value: 0.30107335520239253.

  Classification -> best τ=0.310 (val F1=0.1203)
  Directional -> Accuracy: 0.5833, MCC: 0.2813, F1: 0.6914

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2716588553980688
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62174 | val 0.67652
  Epoch 013 - train 0.62284 | val 0.73202
  Classification -> best τ=0.445 (val F1=0.1833)
  Directional -> Accuracy: 0.6184, MCC: 0.2622, F1: 0.6329

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59111 | val 0.67811
  Epoch 018 - train 0.48680 | val 0.68709
  Classification -> best τ=0.415 (val F1=0.3654)
  Directional -> Accuracy: 0.6444, MCC: 0.2475, F1: 0.7419

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56898 | val 0.81709
  Epoch 012 - train 0.61291 | val 0.94171
  Classification -> best τ=0.550 (val F1=0.1383)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65249 | val 0.79588
  Epoch 012 - train 0.63970 | val 0.82973
  Classification -> best τ=0.440 (val F1=0.2230)
  Directional -> Accuracy: 0.5811, MCC: 0.1585, F1: 0.6076

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64283 | val 1.06004
  Epoch 016 - train 0.48477 | val 1.64436
  Classification -> best τ=0.500 (val F1=0.4259)
  Directional -> Accuracy: 0.6800, MCC: 0.3816, F1: 0.7419

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60208 | val 0.73865
  Epoch 011 - train 0.59154 | val 0.78333
  Classification -> best τ=0.510 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62921 | val 0.95772
  Epoch 012 - train 0.61247 | val 1.05188
  Classification -> best τ=0.490 (val F1=0.2536)
  Directional -> Accuracy: 0.5588, MCC: 0.1393, F1: 0.5312

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57652 | val 0.94318
  Epoch 013 - train 0.51876 | val 1.19176
  Classification -> best τ=0.305 (val F1=0.0679)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59483 | val 0.72353
  Epoch 016 - train 0.57707 | val 1.14319
  Classification -> best τ=0.520 (val F1=0.3441)
  Directional -> Accuracy: 0.5208, MCC: -0.0794, F1: 0.1481

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56891 | val 0.78251
  Epoch 011 - train 0.56523 | val 0.73222
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62353 | val 0.79588
  Epoch 013 - train 0.61924 | val 1.16189
  Classification -> best τ=0.440 (val F1=0.3729)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56604 | val 1.17789
  Epoch 012 - train 0.52210 | val 1.84889
  Classification -> best τ=0.490 (val F1=0.1002)
  Directional -> Accuracy: 0.3860, MCC: -0.2335, F1: 0.2857

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56372 | val 1.43951
  Epoch 011 - train 0.53710 | val 1.74380
  Classification -> best τ=0.370 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60216 | val 0.71512
  Epoch 014 - train 0.54875 | val 1.06871
  Classification -> best τ=0.365 (val F1=0.3387)
  Directional -> Accuracy: 0.6000, MCC: 0.2075, F1: 0.6471

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57743 | val 0.79221
  Epoch 013 - train 0.54140 | val 0.76584
  Classification -> best τ=0.550 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60173 | val 0.90748
  Epoch 013 - train 0.59470 | val 0.75255
  Classification -> best τ=0.405 (val F1=0.4077)
  Directional -> Accuracy: 0.6377, MCC: 0.2951, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60121 | val 1.04717
  Epoch 011 - train 0.58993 | val 1.05893
  Classification -> best τ=0.680 (val F1=0.0757)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62433 | val 1.21584
  Epoch 012 - train 0.61001 | val 1.22278
  Classification -> best τ=0.500 (val F1=0.2166)
  Directional -> Accuracy: 0.5467, MCC: 0.1588, F1: 0.5278

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63531 | val 0.70487
  Epoch 014 - train 0.58608 | val 0.91587
  Classification -> best τ=0.575 (val F1=0.2868)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63752 | val 0.68316
  Epoch 012 - train 0.63024 | val 0.69224
  Classification -> best τ=0.490 (val F1=0.2871)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57789 | val 0.75660
  Epoch 016 - train 0.50023 | val 0.78762
  Classification -> best τ=0.520 (val F1=0.3693)
  Directional -> Accuracy: 0.4681, MCC: 0.0118, F1: 0.4444

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61619 | val 0.80468
  Epoch 011 - train 0.66276 | val 0.82016
  Classification -> best τ=0.565 (val F1=0.2168)
  Directional -> Accuracy: 0.4308, MCC: -0.1377, F1: 0.3934

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61852 | val 0.75590
  Epoch 012 - train 0.56750 | val 0.78211
  Classification -> best τ=0.595 (val F1=0.3581)
  Directional -> Accuracy: 0.5614, MCC: 0.1400, F1: 0.5614

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61928 | val 0.85713
  Epoch 012 - train 0.60801 | val 1.36154
  Classification -> best τ=0.515 (val F1=0.0893)
  Directional -> Accuracy: 0.5231, MCC: 0.0484, F1: 0.5231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55529 | val 0.78257
  Epoch 015 - train 0.48528 | val 0.72617
  Classification -> best τ=0.565 (val F1=0.3574)
  Directional -> Accuracy: 0.4364, MCC: -0.1023, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58564 | val 1.01773
  Epoch 011 - train 0.52340 | val 1.21136
  Classification -> best τ=0.445 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62716 | val 0.67753
  Epoch 020 - train 0.53191 | val 0.73718
  Epoch 025 - train 0.47944 | val 0.82024
  Classification -> best τ=0.665 (val F1=0.3536)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60264 | val 0.72277
  Epoch 011 - train 0.61251 | val 0.76547
  Classification -> best τ=0.515 (val F1=0.2804)
  Directional -> Accuracy: 0.5893, MCC: 0.1659, F1: 0.6349

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57633 | val 0.65644
  Epoch 020 - train 0.52009 | val 0.89518
  Classification -> best τ=0.510 (val F1=0.3518)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59566 | val 0.93630
  Epoch 012 - train 0.59212 | val 1.08542
  Classification -> best τ=0.605 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56999 | val 0.84038
  Epoch 012 - train 0.52371 | val 1.18756
  Classification -> best τ=0.490 (val F1=0.2646)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55355 | val 0.73995
  Epoch 013 - train 0.50890 | val 0.82581
  Classification -> best τ=0.390 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62220 | val 0.69603
  Epoch 013 - train 0.61219 | val 0.78186
  Classification -> best τ=0.340 (val F1=0.3313)
  Directional -> Accuracy: 0.5000, MCC: 0.0555, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60237 | val 1.05423
  Epoch 011 - train 0.56674 | val 1.07483
  Classification -> best τ=0.495 (val F1=0.3078)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65553 | val 0.73551
  Epoch 011 - train 0.61881 | val 0.71906
  Classification -> best τ=0.480 (val F1=0.3280)
  Directional -> Accuracy: 0.6212, MCC: 0.2542, F1: 0.7525

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49677 | val 0.83028
  Epoch 011 - train 0.49295 | val 0.93794
  Classification -> best τ=0.460 (val F1=0.2439)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55972 | val 0.88291
  Epoch 011 - train 0.61239 | val 0.79210
  Classification -> best τ=0.410 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0274, F1: 0.5625

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48513 | val 1.09254
  Epoch 011 - train 0.44812 | val 1.28320
  Classification -> best τ=0.520 (val F1=0.1564)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56178 | val 0.64052
  Epoch 018 - train 0.45205 | val 0.68822
  Classification -> best τ=0.525 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58169 | val 0.80007
  Epoch 012 - train 0.56361 | val 1.22941
  Classification -> best τ=0.530 (val F1=0.2982)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57344 | val 0.88882
  Epoch 012 - train 0.56546 | val 0.86551
  Classification -> best τ=0.545 (val F1=0.3371)
  Directional -> Accuracy: 0.5111, MCC: 0.1474, F1: 0.0833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59393 | val 0.73465
  Epoch 020 - train 0.53561 | val 0.78433
  Epoch 026 - train 0.37844 | val 1.19429
  Classification -> best τ=0.260 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58829 | val 0.59720
  Epoch 020 - train 0.46791 | val 0.60519
  Epoch 030 - train 0.33193 | val 0.75732
  Epoch 031 - train 0.33155 | val 0.84422
  Classification -> best τ=0.700 (val F1=0.4105)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60106 | val 0.70076
  Epoch 011 - train 0.61548 | val 0.76332
  Classification -> best τ=0.595 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61897 | val 1.43049
  Epoch 011 - train 0.61444 | val 1.77344
  Classification -> best τ=0.585 (val F1=0.3401)
  Directional -> Accuracy: 0.5000, MCC: 0.0515, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63286 | val 0.69830
  Epoch 020 - train 0.50862 | val 0.89103
  Epoch 021 - train 0.51430 | val 0.97378
  Classification -> best τ=0.725 (val F1=0.3010)
  Directional -> Accuracy: 0.5283, MCC: 0.0863, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58877 | val 0.93202
  Epoch 012 - train 0.58293 | val 0.95637
  Classification -> best τ=0.535 (val F1=0.2577)
  Directional -> Accuracy: 0.6000, MCC: 0.2291, F1: 0.7105

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62713 | val 0.73958

[I 2026-02-20 05:32:34,723] Trial 186 finished with value: 0.27922388477939464 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.005517531140297216, 'weight_decay': 4.542147578129665e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1522262866674338, 'early_stopping_min_delta': 0.008997564831296528}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.56492 | val 0.72024
  Classification -> best τ=0.405 (val F1=0.2966)
  Directional -> Accuracy: 0.5500, MCC: 0.2112, F1: 0.6747

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27922388477939464
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63239 | val 0.76016
  Epoch 012 - train 0.60982 | val 0.77080
  Classification -> best τ=0.345 (val F1=0.1637)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54673 | val 0.68104
  Epoch 014 - train 0.55731 | val 0.70185
  Classification -> best τ=0.385 (val F1=0.2949)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60392 | val 0.71087
  Epoch 011 - train 0.63274 | val 0.72318
  Classification -> best τ=0.560 (val F1=0.0331)
  Directional -> Accuracy: 0.3696, MCC: -0.3213, F1: 0.0645

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64365 | val 0.71289
  Epoch 013 - train 0.64491 | val 0.92450
  Classification -> best τ=0.555 (val F1=0.0427)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61911 | val 0.88757
  Epoch 016 - train 0.52455 | val 1.58397
  Classification -> best τ=0.545 (val F1=0.4862)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56365 | val 1.37359
  Epoch 011 - train 0.56691 | val 1.27099
  Classification -> best τ=0.550 (val F1=0.2204)
  Directional -> Accuracy: 0.5435, MCC: 0.1286, F1: 0.6316

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63310 | val 0.88524
  Epoch 011 - train 0.63704 | val 0.95607
  Classification -> best τ=0.470 (val F1=0.1833)
  Directional -> Accuracy: 0.4706, MCC: 0.0888, F1: 0.5610

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59692 | val 1.12424
  Epoch 012 - train 0.52210 | val 0.78752
  Classification -> best τ=0.385 (val F1=0.1208)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59618 | val 0.91640
  Epoch 013 - train 0.56397 | val 0.79880
  Classification -> best τ=0.555 (val F1=0.2764)
  Directional -> Accuracy: 0.6458, MCC: 0.2714, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58536 | val 0.84916
  Epoch 011 - train 0.56304 | val 0.95345
  Classification -> best τ=0.485 (val F1=0.1858)
  Directional -> Accuracy: 0.3768, MCC: -0.2150, F1: 0.5376

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71752 | val 0.67683
  Epoch 015 - train 0.63200 | val 1.08443
  Classification -> best τ=0.505 (val F1=0.4037)
  Directional -> Accuracy: 0.5714, MCC: 0.1303, F1: 0.5116

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54716 | val 1.15158
  Epoch 017 - train 0.45801 | val 2.84835
  Classification -> best τ=0.530 (val F1=0.2741)
  Directional -> Accuracy: 0.6842, MCC: 0.3699, F1: 0.6786

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59623 | val 1.01953
  Epoch 012 - train 0.56946 | val 1.02761
  Classification -> best τ=0.510 (val F1=0.3203)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63764 | val 0.67495
  Epoch 020 - train 0.51579 | val 1.52660
  Epoch 022 - train 0.50584 | val 1.07569
  Classification -> best τ=0.490 (val F1=0.4139)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60965 | val 0.78691
  Epoch 011 - train 0.61148 | val 0.77153
  Classification -> best τ=0.570 (val F1=0.3333)
  Directional -> Accuracy: 0.3922, MCC: -0.1950, F1: 0.4561

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65034 | val 0.71854
  Epoch 012 - train 0.61761 | val 0.69118
  Classification -> best τ=0.620 (val F1=0.3206)
  Directional -> Accuracy: 0.5217, MCC: 0.1079, F1: 0.3529

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60770 | val 1.23797
  Epoch 011 - train 0.60981 | val 1.44219
  Classification -> best τ=0.680 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62695 | val 1.62517
  Epoch 012 - train 0.61325 | val 1.56502
  Classification -> best τ=0.480 (val F1=0.1769)
  Directional -> Accuracy: 0.6133, MCC: 0.1111, F1: 0.7521

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67359 | val 0.77710
  Epoch 013 - train 0.60618 | val 0.88210
  Classification -> best τ=0.350 (val F1=0.3421)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68527 | val 0.68562
  Epoch 012 - train 0.61141 | val 0.70830
  Classification -> best τ=0.500 (val F1=0.3185)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60480 | val 0.67998
  Epoch 020 - train 0.46826 | val 1.51787
  Epoch 024 - train 0.40226 | val 0.99362
  Classification -> best τ=0.485 (val F1=0.4104)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63325 | val 0.75995
  Epoch 011 - train 0.64626 | val 1.09727
  Classification -> best τ=0.475 (val F1=0.1117)
  Directional -> Accuracy: 0.5538, MCC: 0.1114, F1: 0.6329

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59813 | val 0.86185
  Epoch 014 - train 0.56522 | val 0.76778
  Classification -> best τ=0.600 (val F1=0.3604)
  Directional -> Accuracy: 0.4737, MCC: 0.0359, F1: 0.2857

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63844 | val 0.87839
  Epoch 011 - train 0.64194 | val 0.72738
  Classification -> best τ=0.390 (val F1=0.2177)
  Directional -> Accuracy: 0.5385, MCC: 0.1166, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56360 | val 0.68917
  Epoch 014 - train 0.48438 | val 1.11737
  Classification -> best τ=0.520 (val F1=0.5345)
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55485 | val 0.73227
  Epoch 012 - train 0.56458 | val 1.02404
  Classification -> best τ=0.515 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59757 | val 0.72306
  Epoch 011 - train 0.60545 | val 0.73514
  Classification -> best τ=0.565 (val F1=0.1452)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61893 | val 0.76756
  Epoch 011 - train 0.58207 | val 0.83155
  Classification -> best τ=0.505 (val F1=0.2841)
  Directional -> Accuracy: 0.5000, MCC: 0.1552, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61218 | val 0.70577
  Epoch 014 - train 0.58490 | val 1.19050
  Classification -> best τ=0.510 (val F1=0.3296)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62012 | val 0.70953
  Epoch 012 - train 0.59445 | val 0.70642
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56031 | val 0.72401
  Epoch 012 - train 0.56836 | val 1.00520
  Classification -> best τ=0.480 (val F1=0.3036)
  Directional -> Accuracy: 0.3810, MCC: -0.3052, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56090 | val 0.86947
  Epoch 015 - train 0.54469 | val 1.06402
  Classification -> best τ=0.665 (val F1=0.3465)
  Directional -> Accuracy: 0.3878, MCC: -0.2560, F1: 0.4828

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62087 | val 0.88626
  Epoch 017 - train 0.55014 | val 0.76002
  Classification -> best τ=0.355 (val F1=0.3593)
  Directional -> Accuracy: 0.5139, MCC: 0.0733, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60935 | val 0.92899
  Epoch 011 - train 0.57126 | val 0.92103
  Classification -> best τ=0.565 (val F1=0.3140)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64168 | val 0.79380
  Epoch 011 - train 0.63885 | val 0.82375
  Classification -> best τ=0.380 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52673 | val 0.84240
  Epoch 011 - train 0.56689 | val 0.78006
  Classification -> best τ=0.475 (val F1=0.2067)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54521 | val 0.79136
  Epoch 011 - train 0.55415 | val 0.86105
  Classification -> best τ=0.450 (val F1=0.2450)
  Directional -> Accuracy: 0.4286, MCC: -0.1309, F1: 0.4667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52684 | val 1.10804
  Epoch 015 - train 0.39933 | val 1.67087
  Classification -> best τ=0.410 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55697 | val 0.65311
  Epoch 016 - train 0.51345 | val 0.74136
  Classification -> best τ=0.460 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63044 | val 0.80517
  Epoch 020 - train 0.55669 | val 1.14470
  Epoch 023 - train 0.45940 | val 0.99186
  Classification -> best τ=0.375 (val F1=0.4563)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59236 | val 0.71010
  Epoch 012 - train 0.54279 | val 0.75599
  Classification -> best τ=0.475 (val F1=0.3500)
  Directional -> Accuracy: 0.6000, MCC: 0.2145, F1: 0.6786

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56147 | val 0.82012
  Epoch 017 - train 0.54756 | val 1.43108
  Classification -> best τ=0.435 (val F1=0.4588)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60332 | val 0.60762
  Epoch 020 - train 0.46878 | val 0.63458
  Epoch 026 - train 0.37911 | val 0.69605
  Classification -> best τ=0.760 (val F1=0.4867)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60731 | val 0.68977
  Epoch 011 - train 0.57587 | val 0.70423
  Classification -> best τ=0.525 (val F1=0.2291)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54539 | val 1.47543
  Epoch 011 - train 0.57465 | val 1.31174
  Classification -> best τ=0.595 (val F1=0.2311)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62017 | val 0.75031
  Epoch 012 - train 0.58963 | val 1.10363
  Classification -> best τ=0.515 (val F1=0.1568)
  Directional -> Accuracy: 0.5472, MCC: 0.2018, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59398 | val 1.24059
  Epoch 012 - train 0.59019 | val 0.94396
  Classification -> best τ=0.430 (val F1=0.2681)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57293 | val 0.69843

[I 2026-02-20 05:33:32,242] Trial 187 finished with value: 0.2824282386231047 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.0056633220668642105, 'weight_decay': 2.6206599127572186e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1591123154727199, 'early_stopping_min_delta': 0.009022976035357313}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 020 - train 0.51861 | val 0.78110
  Epoch 021 - train 0.51257 | val 0.78949
  Classification -> best τ=0.565 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0472, F1: 0.5797

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2824282386231047
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59607 | val 0.88116
  Epoch 012 - train 0.59966 | val 0.69948
  Classification -> best τ=0.550 (val F1=0.1430)
  Directional -> Accuracy: 0.5921, MCC: 0.1882, F1: 0.2051

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59184 | val 0.67165
  Epoch 012 - train 0.55240 | val 0.67599
  Classification -> best τ=0.435 (val F1=0.3306)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59292 | val 0.79252
  Epoch 012 - train 0.60510 | val 0.76234
  Classification -> best τ=0.520 (val F1=0.3114)
  Directional -> Accuracy: 0.4348, MCC: -0.2227, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64779 | val 0.84429
  Epoch 012 - train 0.64806 | val 0.93437
  Classification -> best τ=0.520 (val F1=0.2056)
  Directional -> Accuracy: 0.4865, MCC: 0.0016, F1: 0.4062

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60207 | val 0.67325
  Epoch 019 - train 0.47199 | val 1.74533
  Classification -> best τ=0.645 (val F1=0.4611)
  Directional -> Accuracy: 0.5200, MCC: 0.0801, F1: 0.3333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58714 | val 0.77265
  Epoch 011 - train 0.58440 | val 0.77304
  Classification -> best τ=0.500 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64320 | val 1.01315
  Epoch 011 - train 0.62619 | val 0.77383
  Classification -> best τ=0.525 (val F1=0.1391)
  Directional -> Accuracy: 0.3971, MCC: -0.0974, F1: 0.5060

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57569 | val 0.61129
  Epoch 019 - train 0.42626 | val 1.54113
  Classification -> best τ=0.405 (val F1=0.3689)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59540 | val 0.66283
  Epoch 019 - train 0.47797 | val 0.94847
  Classification -> best τ=0.585 (val F1=0.4748)
  Directional -> Accuracy: 0.6042, MCC: 0.1732, F1: 0.4571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60438 | val 0.79588
  Epoch 012 - train 0.57383 | val 0.82071
  Classification -> best τ=0.550 (val F1=0.1945)
  Directional -> Accuracy: 0.5942, MCC: 0.1061, F1: 0.2632

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63077 | val 0.88081
  Epoch 015 - train 0.60561 | val 1.97966
  Classification -> best τ=0.425 (val F1=0.1738)
  Directional -> Accuracy: 0.5918, MCC: 0.2285, F1: 0.1667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53133 | val 1.29669
  Epoch 012 - train 0.49751 | val 1.88681
  Classification -> best τ=0.460 (val F1=0.1724)
  Directional -> Accuracy: 0.3684, MCC: -0.2635, F1: 0.3793

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56919 | val 1.61711
  Epoch 012 - train 0.51444 | val 1.49877
  Classification -> best τ=0.315 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62880 | val 0.67593
  Epoch 015 - train 0.54997 | val 0.79852
  Classification -> best τ=0.440 (val F1=0.3477)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.5333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56377 | val 0.71014
  Epoch 013 - train 0.61189 | val 0.83661
  Classification -> best τ=0.485 (val F1=0.2078)
  Directional -> Accuracy: 0.6275, MCC: 0.2581, F1: 0.6122

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66760 | val 0.78051
  Epoch 016 - train 0.62295 | val 0.82083
  Classification -> best τ=0.415 (val F1=0.2341)
  Directional -> Accuracy: 0.5797, MCC: 0.1688, F1: 0.7071

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61095 | val 1.69757
  Epoch 011 - train 0.58039 | val 2.04522
  Classification -> best τ=0.555 (val F1=0.2612)
  Directional -> Accuracy: 0.4138, MCC: -0.2681, F1: 0.5405

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63108 | val 1.16179
  Epoch 012 - train 0.59474 | val 1.18583
  Classification -> best τ=0.480 (val F1=0.1905)
  Directional -> Accuracy: 0.5467, MCC: 0.0343, F1: 0.6383

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72741 | val 0.83268
  Epoch 011 - train 0.62915 | val 0.99975
  Classification -> best τ=0.465 (val F1=0.3421)
  Directional -> Accuracy: 0.5312, MCC: -0.0381, F1: 0.6591

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61926 | val 0.68854
  Epoch 014 - train 0.60393 | val 0.75187
  Classification -> best τ=0.450 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56853 | val 0.69335
  Epoch 011 - train 0.57045 | val 0.82109
  Classification -> best τ=0.545 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63210 | val 0.79289
  Epoch 016 - train 0.61917 | val 0.86515
  Classification -> best τ=0.555 (val F1=0.2376)
  Directional -> Accuracy: 0.5846, MCC: 0.1759, F1: 0.5424

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63414 | val 0.72137
  Epoch 011 - train 0.63101 | val 0.74688
  Classification -> best τ=0.635 (val F1=0.3254)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63702 | val 1.11562
  Epoch 012 - train 0.63511 | val 1.12372
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57590 | val 0.79594
  Epoch 016 - train 0.49567 | val 1.04612
  Classification -> best τ=0.655 (val F1=0.3889)
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57312 | val 0.84961
  Epoch 011 - train 0.60016 | val 0.98507
  Classification -> best τ=0.525 (val F1=0.2935)
  Directional -> Accuracy: 0.5111, MCC: -0.0900, F1: 0.2143

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60779 | val 0.74903
  Epoch 011 - train 0.60280 | val 0.74030
  Classification -> best τ=0.520 (val F1=0.1840)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64078 | val 0.80097
  Epoch 011 - train 0.61885 | val 0.78866
  Classification -> best τ=0.500 (val F1=0.1913)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55683 | val 0.74998
  Epoch 012 - train 0.55697 | val 0.81704
  Classification -> best τ=0.540 (val F1=0.4345)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63406 | val 0.73314
  Epoch 012 - train 0.55732 | val 0.69690
  Classification -> best τ=0.575 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63325 | val 0.75664
  Epoch 017 - train 0.52411 | val 0.82258
  Classification -> best τ=0.580 (val F1=0.3067)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54482 | val 0.80680
  Epoch 012 - train 0.51213 | val 0.93536
  Classification -> best τ=0.425 (val F1=0.3957)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63649 | val 0.73686
  Epoch 020 - train 0.56576 | val 0.70035
  Epoch 022 - train 0.50915 | val 1.03021
  Classification -> best τ=0.385 (val F1=0.3815)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61706 | val 0.92417
  Epoch 011 - train 0.60805 | val 0.97731
  Classification -> best τ=0.480 (val F1=0.3078)
  Directional -> Accuracy: 0.5116, MCC: 0.0217, F1: 0.4878

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64599 | val 0.75077
  Epoch 011 - train 0.62576 | val 0.82710
  Classification -> best τ=0.420 (val F1=0.4073)
  Directional -> Accuracy: 0.6061, MCC: 0.1863, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61716 | val 0.88986
  Epoch 011 - train 0.53398 | val 0.74988
  Classification -> best τ=0.510 (val F1=0.3001)
  Directional -> Accuracy: 0.6429, MCC: 0.3006, F1: 0.6154

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54418 | val 0.83599
  Epoch 011 - train 0.56520 | val 0.95474
  Classification -> best τ=0.495 (val F1=0.2816)
  Directional -> Accuracy: 0.5536, MCC: 0.1003, F1: 0.5098

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48342 | val 1.09507
  Epoch 011 - train 0.44192 | val 1.13536
  Classification -> best τ=0.480 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60218 | val 0.64275
  Epoch 017 - train 0.45812 | val 0.68066
  Classification -> best τ=0.410 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57824 | val 0.74913
  Epoch 012 - train 0.58765 | val 0.86095
  Classification -> best τ=0.485 (val F1=0.3817)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58563 | val 0.76071
  Epoch 012 - train 0.50875 | val 0.80664
  Classification -> best τ=0.560 (val F1=0.2000)
  Directional -> Accuracy: 0.5111, MCC: 0.0391, F1: 0.3529

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56831 | val 0.75936
  Epoch 017 - train 0.54059 | val 0.97568
  Classification -> best τ=0.310 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61120 | val 0.67892
  Epoch 018 - train 0.49438 | val 0.60677
  Classification -> best τ=0.560 (val F1=0.4682)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64227 | val 0.75684
  Epoch 011 - train 0.60404 | val 0.83009
  Classification -> best τ=0.670 (val F1=0.1784)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55241 | val 1.94002
  Epoch 011 - train 0.57960 | val 1.30192
  Classification -> best τ=0.575 (val F1=0.3318)
  Directional -> Accuracy: 0.5536, MCC: 0.1284, F1: 0.6154

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58787 | val 1.02098
  Epoch 012 - train 0.59463 | val 1.11664
  Classification -> best τ=0.540 (val F1=0.2407)
  Directional -> Accuracy: 0.5849, MCC: 0.1729, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61689 | val 0.93967
  Epoch 011 - train 0.61266 | val 0.85794
  Classification -> best τ=0.540 (val F1=0.1430)
  Directional -> Accuracy: 0.4000, MCC: -0.1991, F1: 0.2326

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58632 | val 0.91689

[I 2026-02-20 05:34:28,630] Trial 188 finished with value: 0.28687965457053294 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.005515234564037173, 'weight_decay': 3.2960265367755206e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1422740098865214, 'early_stopping_min_delta': 0.008965055716613697}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 015 - train 0.55770 | val 0.69401
  Classification -> best τ=0.495 (val F1=0.2124)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28687965457053294
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63000 | val 0.77596
  Epoch 013 - train 0.59292 | val 0.78157
  Classification -> best τ=0.500 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55784 | val 0.68431
  Epoch 013 - train 0.56582 | val 0.73777
  Classification -> best τ=0.455 (val F1=0.2949)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59416 | val 0.75292
  Epoch 011 - train 0.60528 | val 0.74305
  Classification -> best τ=0.525 (val F1=0.1964)
  Directional -> Accuracy: 0.4348, MCC: -0.1461, F1: 0.1333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65264 | val 0.92129
  Epoch 012 - train 0.65231 | val 0.72947
  Classification -> best τ=0.430 (val F1=0.1716)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57657 | val 0.88064
  Epoch 013 - train 0.59013 | val 1.26257
  Classification -> best τ=0.455 (val F1=0.4493)
  Directional -> Accuracy: 0.7400, MCC: 0.5047, F1: 0.7111

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57139 | val 0.95506
  Epoch 012 - train 0.56487 | val 1.14261
  Classification -> best τ=0.605 (val F1=0.3194)
  Directional -> Accuracy: 0.5652, MCC: 0.1241, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63528 | val 0.85014
  Epoch 011 - train 0.64559 | val 1.03595
  Classification -> best τ=0.450 (val F1=0.2481)
  Directional -> Accuracy: 0.4853, MCC: 0.1391, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53720 | val 1.02005
  Epoch 014 - train 0.53447 | val 1.05559
  Classification -> best τ=0.470 (val F1=0.2657)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60805 | val 0.76800
  Epoch 015 - train 0.51718 | val 1.17178
  Classification -> best τ=0.565 (val F1=0.4197)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60750 | val 0.78760
  Epoch 011 - train 0.56652 | val 0.83199
  Classification -> best τ=0.460 (val F1=0.1858)
  Directional -> Accuracy: 0.3913, MCC: -0.1583, F1: 0.4878

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61110 | val 0.81642
  Epoch 012 - train 0.61418 | val 0.80481
  Classification -> best τ=0.410 (val F1=0.1199)
  Directional -> Accuracy: 0.4898, MCC: 0.1862, F1: 0.6377

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55778 | val 1.16007
  Epoch 011 - train 0.51493 | val 0.97843
  Classification -> best τ=0.465 (val F1=0.2157)
  Directional -> Accuracy: 0.5263, MCC: 0.0675, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52165 | val 1.37000
  Epoch 011 - train 0.53705 | val 1.43432
  Classification -> best τ=0.570 (val F1=0.1754)
  Directional -> Accuracy: 0.5476, MCC: 0.0605, F1: 0.3871

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61344 | val 0.73794
  Epoch 013 - train 0.58833 | val 0.83309
  Classification -> best τ=0.365 (val F1=0.3669)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58010 | val 0.71966
  Epoch 018 - train 0.55088 | val 0.86657
  Classification -> best τ=0.475 (val F1=0.2298)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63516 | val 0.87031
  Epoch 012 - train 0.60757 | val 0.95791
  Classification -> best τ=0.725 (val F1=0.3104)
  Directional -> Accuracy: 0.5362, MCC: 0.1668, F1: 0.3333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59985 | val 1.06156
  Epoch 011 - train 0.62168 | val 1.05406
  Classification -> best τ=0.470 (val F1=0.0660)
  Directional -> Accuracy: 0.5345, MCC: -0.1805, F1: 0.6897

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58674 | val 1.61973
  Epoch 015 - train 0.56158 | val 2.54557
  Classification -> best τ=0.280 (val F1=0.2537)
  Directional -> Accuracy: 0.5733, MCC: 0.0915, F1: 0.6596

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61247 | val 0.94119
  Epoch 011 - train 0.61306 | val 0.91200
  Classification -> best τ=0.435 (val F1=0.3140)
  Directional -> Accuracy: 0.5156, MCC: 0.1672, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62838 | val 0.67160
  Epoch 016 - train 0.57684 | val 0.88356
  Classification -> best τ=0.505 (val F1=0.3495)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62601 | val 0.68138
  Epoch 020 - train 0.46555 | val 0.92601
  Epoch 025 - train 0.49452 | val 0.74595
  Classification -> best τ=0.415 (val F1=0.3251)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65144 | val 0.83820
  Epoch 011 - train 0.62897 | val 0.88289
  Classification -> best τ=0.500 (val F1=0.2037)
  Directional -> Accuracy: 0.5077, MCC: 0.0081, F1: 0.6190

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61873 | val 0.74102
  Epoch 011 - train 0.63696 | val 0.79456
  Classification -> best τ=0.510 (val F1=0.3191)
  Directional -> Accuracy: 0.5789, MCC: 0.1528, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61236 | val 1.18631
  Epoch 012 - train 0.64552 | val 0.98476
  Classification -> best τ=0.475 (val F1=0.1565)
  Directional -> Accuracy: 0.5846, MCC: 0.1798, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53920 | val 0.85393
  Epoch 015 - train 0.54970 | val 0.91948
  Classification -> best τ=0.490 (val F1=0.3887)
  Directional -> Accuracy: 0.5273, MCC: 0.0920, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61276 | val 1.14568
  Epoch 011 - train 0.54590 | val 0.98425
  Classification -> best τ=0.505 (val F1=0.1310)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60333 | val 0.68532
  Epoch 011 - train 0.61680 | val 0.69164
  Classification -> best τ=0.520 (val F1=0.1217)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62770 | val 0.71258
  Epoch 012 - train 0.61962 | val 0.92984
  Classification -> best τ=0.440 (val F1=0.2724)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61455 | val 0.67180
  Epoch 015 - train 0.49845 | val 0.79358
  Classification -> best τ=0.505 (val F1=0.3518)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61261 | val 0.87493
  Epoch 012 - train 0.60743 | val 0.83690
  Classification -> best τ=0.570 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0608, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59937 | val 0.81332
  Epoch 011 - train 0.57284 | val 0.75204
  Classification -> best τ=0.415 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57918 | val 0.70937
  Epoch 013 - train 0.53221 | val 0.87813
  Classification -> best τ=0.410 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61591 | val 0.74597
  Epoch 014 - train 0.60515 | val 0.89891
  Classification -> best τ=0.405 (val F1=0.3593)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60780 | val 0.91698
  Epoch 011 - train 0.58264 | val 0.87708
  Classification -> best τ=0.500 (val F1=0.3417)
  Directional -> Accuracy: 0.5814, MCC: 0.3129, F1: 0.7000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59195 | val 0.82187
  Epoch 011 - train 0.58389 | val 0.93790
  Classification -> best τ=0.535 (val F1=0.0528)
  Directional -> Accuracy: 0.4242, MCC: -0.0271, F1: 0.0500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50309 | val 0.78955
  Epoch 011 - train 0.51091 | val 0.79635
  Classification -> best τ=0.505 (val F1=0.2292)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53803 | val 0.84807
  Epoch 011 - train 0.56219 | val 0.85534
  Classification -> best τ=0.455 (val F1=0.2946)
  Directional -> Accuracy: 0.5536, MCC: 0.1899, F1: 0.6479

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51142 | val 1.43162
  Epoch 011 - train 0.46465 | val 1.46269
  Classification -> best τ=0.475 (val F1=0.3397)
  Directional -> Accuracy: 0.5652, MCC: -0.1709, F1: 0.7222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61571 | val 0.65288
  Epoch 020 - train 0.44945 | val 0.69982
  Epoch 021 - train 0.46580 | val 0.69806
  Classification -> best τ=0.360 (val F1=0.4469)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62460 | val 0.71421
  Epoch 013 - train 0.55978 | val 0.89503
  Classification -> best τ=0.485 (val F1=0.3332)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56334 | val 0.73735
  Epoch 012 - train 0.54855 | val 0.79307
  Classification -> best τ=0.440 (val F1=0.3287)
  Directional -> Accuracy: 0.5111, MCC: 0.0087, F1: 0.6452

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57846 | val 0.64532
  Epoch 017 - train 0.51117 | val 0.68180
  Classification -> best τ=0.380 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64844 | val 0.61940
  Epoch 020 - train 0.51332 | val 0.66386
  Epoch 026 - train 0.41619 | val 0.74025
  Classification -> best τ=0.490 (val F1=0.5514)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59429 | val 0.74783
  Epoch 011 - train 0.59906 | val 0.71343
  Classification -> best τ=0.585 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57074 | val 1.63186
  Epoch 011 - train 0.56043 | val 1.16260
  Classification -> best τ=0.665 (val F1=0.2143)
  Directional -> Accuracy: 0.5357, MCC: 0.0633, F1: 0.4348

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66180 | val 0.74912
  Epoch 016 - train 0.57791 | val 1.00118
  Classification -> best τ=0.545 (val F1=0.2415)
  Directional -> Accuracy: 0.4906, MCC: -0.0585, F1: 0.6400

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62920 | val 0.89217
  Epoch 011 - train 0.60805 | val 0.98847
  Classification -> best τ=0.500 (val F1=0.1605)
  Directional -> Accuracy: 0.4000, MCC: -0.2061, F1: 0.4407

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57893 | val 0.69056

[I 2026-02-20 05:35:24,031] Trial 189 finished with value: 0.2754614323587616 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.005430731867111182, 'weight_decay': 2.5526738107016494e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.156457303223239, 'early_stopping_min_delta': 0.008985504333583581}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 017 - train 0.50537 | val 0.91298
  Classification -> best τ=0.605 (val F1=0.2623)
  Directional -> Accuracy: 0.5333, MCC: 0.0620, F1: 0.4815

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2754614323587616
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59839 | val 0.89150
  Epoch 011 - train 0.56493 | val 0.83229
  Classification -> best τ=0.375 (val F1=0.1718)
  Directional -> Accuracy: 0.4737, MCC: 0.0671, F1: 0.6154

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55107 | val 0.97385
  Epoch 011 - train 0.51968 | val 0.81333
  Classification -> best τ=0.460 (val F1=0.1308)
  Directional -> Accuracy: 0.5778, MCC: 0.0618, F1: 0.7077

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56826 | val 0.75793
  Epoch 011 - train 0.53445 | val 0.90158
  Classification -> best τ=0.525 (val F1=0.3482)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61296 | val 1.23053
  Epoch 012 - train 0.61454 | val 0.75583
  Classification -> best τ=0.310 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57342 | val 0.97292
  Epoch 012 - train 0.60255 | val 0.73507
  Classification -> best τ=0.460 (val F1=0.4388)
  Directional -> Accuracy: 0.4400, MCC: -0.2009, F1: 0.5882

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54284 | val 0.80072
  Epoch 011 - train 0.47850 | val 0.91676
  Classification -> best τ=0.595 (val F1=0.2739)
  Directional -> Accuracy: 0.6087, MCC: 0.2340, F1: 0.4375

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61732 | val 0.73797
  Epoch 011 - train 0.59161 | val 0.91492
  Classification -> best τ=0.420 (val F1=0.2536)
  Directional -> Accuracy: 0.5441, MCC: 0.2144, F1: 0.5974

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52676 | val 1.89095
  Epoch 011 - train 0.47399 | val 1.20257
  Classification -> best τ=0.445 (val F1=0.1795)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55730 | val 0.96429
  Epoch 011 - train 0.55319 | val 1.33994
  Classification -> best τ=0.620 (val F1=0.2764)
  Directional -> Accuracy: 0.6458, MCC: 0.2817, F1: 0.4138

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57716 | val 0.69114
  Epoch 011 - train 0.54558 | val 0.86245
  Classification -> best τ=0.455 (val F1=0.2480)
  Directional -> Accuracy: 0.4638, MCC: -0.0301, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56072 | val 1.57709
  Epoch 013 - train 0.55666 | val 1.09447
  Classification -> best τ=0.360 (val F1=0.3567)
  Directional -> Accuracy: 0.5102, MCC: 0.0447, F1: 0.5385

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53282 | val 1.76719
  Epoch 012 - train 0.52317 | val 2.38220
  Classification -> best τ=0.470 (val F1=0.2630)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54027 | val 1.85664
  Epoch 012 - train 0.46867 | val 1.97199
  Classification -> best τ=0.535 (val F1=0.2172)
  Directional -> Accuracy: 0.4524, MCC: -0.0751, F1: 0.4889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58170 | val 0.83177
  Epoch 012 - train 0.58611 | val 0.87297
  Classification -> best τ=0.370 (val F1=0.3828)
  Directional -> Accuracy: 0.5500, MCC: 0.1558, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52748 | val 0.91605
  Epoch 011 - train 0.55255 | val 0.93381
  Classification -> best τ=0.490 (val F1=0.0211)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58062 | val 1.39668
  Epoch 014 - train 0.52640 | val 1.29238
  Classification -> best τ=0.280 (val F1=0.2795)
  Directional -> Accuracy: 0.6812, MCC: 0.4167, F1: 0.7660

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58944 | val 2.23620
  Epoch 011 - train 0.60185 | val 2.32847
  Classification -> best τ=0.425 (val F1=0.1336)
  Directional -> Accuracy: 0.6034, MCC: 0.0131, F1: 0.7416

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54992 | val 0.88454
  Epoch 012 - train 0.54465 | val 1.74512
  Classification -> best τ=0.490 (val F1=0.2182)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63954 | val 0.84570
  Epoch 012 - train 0.61381 | val 0.87721
  Classification -> best τ=0.340 (val F1=0.3948)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62793 | val 0.70304
  Epoch 020 - train 0.55523 | val 0.75679
  Epoch 023 - train 0.58006 | val 0.86625
  Classification -> best τ=0.315 (val F1=0.3491)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56283 | val 0.74890
  Epoch 012 - train 0.54333 | val 0.90667
  Classification -> best τ=0.520 (val F1=0.2064)
  Directional -> Accuracy: 0.5957, MCC: 0.0615, F1: 0.7164

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59132 | val 1.09817
  Epoch 011 - train 0.69600 | val 1.11931
  Classification -> best τ=0.440 (val F1=0.0650)
  Directional -> Accuracy: 0.5231, MCC: 0.0449, F1: 0.6265

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63987 | val 0.97966
  Epoch 011 - train 0.62883 | val 0.88484
  Classification -> best τ=0.530 (val F1=0.3604)
  Directional -> Accuracy: 0.6316, MCC: 0.2349, F1: 0.7200

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61047 | val 1.26268
  Epoch 013 - train 0.57734 | val 1.16934
  Classification -> best τ=0.520 (val F1=0.1348)
  Directional -> Accuracy: 0.4154, MCC: -0.1687, F1: 0.4062

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50820 | val 0.77427
  Epoch 014 - train 0.47979 | val 1.16937
  Classification -> best τ=0.645 (val F1=0.5345)
  Directional -> Accuracy: 0.5091, MCC: 0.0781, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49224 | val 2.16258
  Epoch 011 - train 0.45061 | val 2.19166
  Classification -> best τ=0.640 (val F1=0.1890)
  Directional -> Accuracy: 0.4444, MCC: -0.1022, F1: 0.4186

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54076 | val 1.26748
  Epoch 012 - train 0.56483 | val 1.41398
  Classification -> best τ=0.520 (val F1=0.0913)
  Directional -> Accuracy: 0.6429, MCC: 0.2762, F1: 0.6809

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51088 | val 1.17501
  Epoch 012 - train 0.55801 | val 1.17126
  Classification -> best τ=0.455 (val F1=0.1951)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55068 | val 2.32183
  Epoch 011 - train 0.48405 | val 4.00509
  Classification -> best τ=0.470 (val F1=0.1918)
  Directional -> Accuracy: 0.5250, MCC: 0.0553, F1: 0.5366

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53208 | val 0.74420
  Epoch 020 - train 0.50229 | val 0.68201
  Epoch 022 - train 0.47015 | val 0.88627
  Classification -> best τ=0.435 (val F1=0.5772)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54408 | val 0.88880
  Epoch 011 - train 0.51576 | val 0.95937
  Classification -> best τ=0.510 (val F1=0.3067)
  Directional -> Accuracy: 0.4286, MCC: -0.1083, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59551 | val 0.99691
  Epoch 011 - train 0.66753 | val 1.18884
  Classification -> best τ=0.535 (val F1=0.3465)
  Directional -> Accuracy: 0.4082, MCC: -0.2233, F1: 0.0645

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60713 | val 0.70801
  Epoch 011 - train 0.59774 | val 0.82921
  Classification -> best τ=0.355 (val F1=0.3366)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55174 | val 1.89666
  Epoch 011 - train 0.56905 | val 1.97433
  Classification -> best τ=0.560 (val F1=0.1270)
  Directional -> Accuracy: 0.5116, MCC: 0.0452, F1: 0.6182

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59130 | val 0.88756
  Epoch 012 - train 0.57953 | val 1.08897
  Classification -> best τ=0.310 (val F1=0.3525)
  Directional -> Accuracy: 0.5758, MCC: 0.1084, F1: 0.6585

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53898 | val 0.83858
  Epoch 011 - train 0.50868 | val 1.00449
  Classification -> best τ=0.525 (val F1=0.2292)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50245 | val 1.63694
  Epoch 011 - train 0.49483 | val 1.63259
  Classification -> best τ=0.645 (val F1=0.1354)
  Directional -> Accuracy: 0.5000, MCC: -0.1792, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45045 | val 0.83863
  Epoch 011 - train 0.45914 | val 1.04737
  Classification -> best τ=0.505 (val F1=0.4335)
  Directional -> Accuracy: 0.5870, MCC: 0.0726, F1: 0.6984

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49269 | val 0.69217
  Epoch 016 - train 0.51845 | val 0.69647
  Classification -> best τ=0.530 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57366 | val 0.69727
  Epoch 016 - train 0.52916 | val 1.19504
  Classification -> best τ=0.190 (val F1=0.4743)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59370 | val 1.06346
  Epoch 013 - train 0.52446 | val 1.98973
  Classification -> best τ=0.425 (val F1=0.2582)
  Directional -> Accuracy: 0.5556, MCC: 0.1110, F1: 0.6296

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55526 | val 0.81894
  Epoch 013 - train 0.57458 | val 1.02377
  Classification -> best τ=0.475 (val F1=0.3118)
  Directional -> Accuracy: 0.4286, MCC: -0.1021, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62078 | val 0.83872
  Epoch 020 - train 0.57565 | val 0.80187
  Epoch 022 - train 0.49879 | val 0.60795
  Classification -> best τ=0.685 (val F1=0.5131)
  Directional -> Accuracy: 0.3958, MCC: -0.0457, F1: 0.5085

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59666 | val 0.79059
  Epoch 011 - train 0.59715 | val 1.01139
  Classification -> best τ=0.555 (val F1=0.0414)
  Directional -> Accuracy: 0.4545, MCC: -0.2064, F1: 0.6053

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55617 | val 1.59014
  Epoch 011 - train 0.64856 | val 1.09542
  Classification -> best τ=0.710 (val F1=0.1502)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62008 | val 0.87087
  Epoch 011 - train 0.60427 | val 1.12121
  Classification -> best τ=0.575 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2080, F1: 0.6038

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57195 | val 0.99379
  Epoch 011 - train 0.56748 | val 2.21583
  Classification -> best τ=0.560 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58778 | val 0.71658

[I 2026-02-20 05:36:31,915] Trial 190 finished with value: 0.2623136674360262 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.005769072008973994, 'weight_decay': 2.3563202069665789e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1010987450783296, 'early_stopping_min_delta': 0.008802858540660916}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 012 - train 0.55052 | val 0.77772
  Classification -> best τ=0.330 (val F1=0.2637)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2623136674360262
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58765 | val 0.67478
  Epoch 012 - train 0.58338 | val 0.73182
  Classification -> best τ=0.465 (val F1=0.0739)
  Directional -> Accuracy: 0.5658, MCC: 0.0832, F1: 0.2979

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59602 | val 0.68365
  Epoch 012 - train 0.60518 | val 0.67958
  Classification -> best τ=0.485 (val F1=0.2523)
  Directional -> Accuracy: 0.6667, MCC: 0.3002, F1: 0.7368

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60561 | val 0.79506
  Epoch 012 - train 0.59343 | val 0.86494
  Classification -> best τ=0.510 (val F1=0.3678)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64376 | val 0.82075
  Epoch 015 - train 0.65911 | val 0.83581
  Classification -> best τ=0.525 (val F1=0.1079)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57494 | val 0.77082
  Epoch 018 - train 0.49649 | val 0.95333
  Classification -> best τ=0.600 (val F1=0.4611)
  Directional -> Accuracy: 0.4800, MCC: -0.0355, F1: 0.4583

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64523 | val 0.70901
  Epoch 014 - train 0.59409 | val 0.74263
  Classification -> best τ=0.500 (val F1=0.2593)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63298 | val 0.86739
  Epoch 011 - train 0.64233 | val 0.91173
  Classification -> best τ=0.430 (val F1=0.2708)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54447 | val 0.85411
  Epoch 019 - train 0.41381 | val 0.99827
  Classification -> best τ=0.400 (val F1=0.2168)
  Directional -> Accuracy: 0.4286, MCC: -0.1132, F1: 0.4545

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55615 | val 0.70880
  Epoch 012 - train 0.55089 | val 0.76829
  Classification -> best τ=0.510 (val F1=0.2784)
  Directional -> Accuracy: 0.5833, MCC: 0.1143, F1: 0.3333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59785 | val 0.85534
  Epoch 012 - train 0.54975 | val 0.82322
  Classification -> best τ=0.595 (val F1=0.1983)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64753 | val 0.70416
  Epoch 012 - train 0.60526 | val 0.73970
  Classification -> best τ=0.450 (val F1=0.2204)
  Directional -> Accuracy: 0.5714, MCC: 0.2535, F1: 0.6557

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54152 | val 1.00812
  Epoch 012 - train 0.50264 | val 0.82970
  Classification -> best τ=0.520 (val F1=0.1724)
  Directional -> Accuracy: 0.4211, MCC: -0.2092, F1: 0.1081

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55963 | val 1.19396
  Epoch 012 - train 0.52635 | val 1.46799
  Classification -> best τ=0.415 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60614 | val 0.75829
  Epoch 014 - train 0.54466 | val 1.23559
  Classification -> best τ=0.310 (val F1=0.3477)
  Directional -> Accuracy: 0.5167, MCC: 0.0405, F1: 0.6234

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58269 | val 0.92066
  Epoch 011 - train 0.60636 | val 0.86720
  Classification -> best τ=0.545 (val F1=0.1344)
  Directional -> Accuracy: 0.5490, MCC: 0.0546, F1: 0.3429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63000 | val 0.87335
  Epoch 013 - train 0.63301 | val 1.33843
  Classification -> best τ=0.600 (val F1=0.2789)
  Directional -> Accuracy: 0.5507, MCC: 0.1374, F1: 0.4746

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59644 | val 1.45439
  Epoch 012 - train 0.58500 | val 1.90921
  Classification -> best τ=0.595 (val F1=0.0067)
  Directional -> Accuracy: 0.6034, MCC: 0.1358, F1: 0.6933

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64235 | val 0.84547
  Epoch 016 - train 0.60130 | val 1.23704
  Classification -> best τ=0.470 (val F1=0.1962)
  Directional -> Accuracy: 0.5600, MCC: 0.1667, F1: 0.5600

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68967 | val 0.73656
  Epoch 013 - train 0.62361 | val 0.81974
  Classification -> best τ=0.515 (val F1=0.3071)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62600 | val 0.69924
  Epoch 013 - train 0.60007 | val 0.70893
  Classification -> best τ=0.500 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56574 | val 0.69255
  Epoch 019 - train 0.49411 | val 0.77787
  Classification -> best τ=0.520 (val F1=0.3693)
  Directional -> Accuracy: 0.4468, MCC: -0.1469, F1: 0.5357

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62560 | val 0.81476
  Epoch 012 - train 0.62559 | val 0.90537
  Classification -> best τ=0.555 (val F1=0.1925)
  Directional -> Accuracy: 0.4462, MCC: -0.1093, F1: 0.3333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60685 | val 0.84596
  Epoch 013 - train 0.58755 | val 0.96967
  Classification -> best τ=0.515 (val F1=0.3601)
  Directional -> Accuracy: 0.5439, MCC: 0.0420, F1: 0.6389

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62050 | val 1.00830
  Epoch 014 - train 0.62334 | val 0.80630
  Classification -> best τ=0.410 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57764 | val 0.82431
  Epoch 014 - train 0.60019 | val 0.96330
  Classification -> best τ=0.530 (val F1=0.4903)
  Directional -> Accuracy: 0.4909, MCC: -0.0410, F1: 0.5625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63689 | val 0.88343
  Epoch 011 - train 0.55848 | val 0.86590
  Classification -> best τ=0.460 (val F1=0.1310)
  Directional -> Accuracy: 0.5333, MCC: 0.0086, F1: 0.3636

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60893 | val 0.73701
  Epoch 011 - train 0.60667 | val 0.74838
  Classification -> best τ=0.620 (val F1=0.1680)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60630 | val 0.78440
  Epoch 012 - train 0.59904 | val 0.73021
  Classification -> best τ=0.410 (val F1=0.1718)
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56094 | val 0.66590
  Epoch 018 - train 0.51606 | val 0.75773
  Classification -> best τ=0.605 (val F1=0.3477)
  Directional -> Accuracy: 0.5750, MCC: 0.1560, F1: 0.5854

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61786 | val 0.78080
  Epoch 012 - train 0.62331 | val 0.91457
  Classification -> best τ=0.635 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56910 | val 0.71383
  Epoch 020 - train 0.35875 | val 1.20292
  Epoch 021 - train 0.41933 | val 2.82013
  Classification -> best τ=0.515 (val F1=0.3034)
  Directional -> Accuracy: 0.5714, MCC: 0.1946, F1: 0.5000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56595 | val 0.69739
  Epoch 013 - train 0.50046 | val 0.88301
  Classification -> best τ=0.390 (val F1=0.4120)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66023 | val 0.66954
  Epoch 013 - train 0.60516 | val 0.68516
  Classification -> best τ=0.425 (val F1=0.3007)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59280 | val 1.15966
  Epoch 011 - train 0.65956 | val 1.53971
  Classification -> best τ=0.550 (val F1=0.2631)
  Directional -> Accuracy: 0.5116, MCC: 0.1508, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65636 | val 0.74147
  Epoch 013 - train 0.66746 | val 0.73237
  Classification -> best τ=0.400 (val F1=0.3758)
  Directional -> Accuracy: 0.5152, MCC: 0.1917, F1: 0.3333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52184 | val 0.76011
  Epoch 014 - train 0.54389 | val 1.12201
  Classification -> best τ=0.645 (val F1=0.3260)
  Directional -> Accuracy: 0.4524, MCC: -0.1638, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58060 | val 0.77768
  Epoch 013 - train 0.49667 | val 0.96574
  Classification -> best τ=0.420 (val F1=0.2450)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46451 | val 1.42616
  Epoch 011 - train 0.43223 | val 1.44869
  Classification -> best τ=0.525 (val F1=0.2441)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54251 | val 0.65466
  Epoch 020 - train 0.41392 | val 0.66897
  Epoch 021 - train 0.46773 | val 0.70067
  Classification -> best τ=0.390 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63181 | val 0.68835
  Epoch 019 - train 0.49654 | val 1.32150
  Classification -> best τ=0.515 (val F1=0.3765)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54299 | val 0.76781
  Epoch 012 - train 0.51675 | val 0.83135
  Classification -> best τ=0.485 (val F1=0.1512)
  Directional -> Accuracy: 0.4667, MCC: -0.0950, F1: 0.5862

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59162 | val 0.63072
  Epoch 020 - train 0.39435 | val 0.58742
  Epoch 030 - train 0.20907 | val 0.77035
  Epoch 031 - train 0.17518 | val 0.86089
  Classification -> best τ=0.410 (val F1=0.5593)
  Directional -> Accuracy: 0.6190, MCC: 0.1925, F1: 0.7241

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55208 | val 0.60440
  Epoch 015 - train 0.52327 | val 0.75640
  Classification -> best τ=0.640 (val F1=0.4478)
  Directional -> Accuracy: 0.3958, MCC: -0.0176, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61122 | val 0.83204
  Epoch 011 - train 0.61279 | val 0.92833
  Classification -> best τ=0.560 (val F1=0.1399)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54125 | val 1.89215
  Epoch 011 - train 0.54354 | val 2.40463
  Classification -> best τ=0.685 (val F1=0.2227)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60946 | val 0.86609
  Epoch 018 - train 0.55980 | val 0.99817
  Classification -> best τ=0.840 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2151, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58379 | val 0.93365
  Epoch 012 - train 0.57128 | val 1.04120
  Classification -> best τ=0.535 (val F1=0.1985)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59919 | val 0.76108

[I 2026-02-20 05:37:30,613] Trial 191 finished with value: 0.2686509836106886 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006561823340149947, 'weight_decay': 1.4104092598732367e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1423499347619115, 'early_stopping_min_delta': 0.009172553768636177}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.59642 | val 0.80896
  Classification -> best τ=0.425 (val F1=0.2966)
  Directional -> Accuracy: 0.6000, MCC: 0.2313, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2686509836106886
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65416 | val 0.66568
  Epoch 015 - train 0.60778 | val 0.70185
  Classification -> best τ=0.575 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58646 | val 0.70850
  Epoch 015 - train 0.54250 | val 0.70329
  Classification -> best τ=0.425 (val F1=0.2073)
  Directional -> Accuracy: 0.6667, MCC: 0.3006, F1: 0.7541

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59901 | val 0.75466
  Epoch 017 - train 0.50633 | val 0.94062
  Classification -> best τ=0.465 (val F1=0.3678)
  Directional -> Accuracy: 0.4565, MCC: -0.0807, F1: 0.4186

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66623 | val 0.70017
  Epoch 020 - train 0.61952 | val 0.76751
  Classification -> best τ=0.310 (val F1=0.2962)
  Directional -> Accuracy: 0.4865, MCC: -0.0992, F1: 0.6200

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58341 | val 1.20447
  Epoch 014 - train 0.52680 | val 1.42414
  Classification -> best τ=0.440 (val F1=0.4751)
  Directional -> Accuracy: 0.6600, MCC: 0.3203, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65921 | val 0.84659
  Epoch 012 - train 0.62103 | val 0.78710
  Classification -> best τ=0.600 (val F1=0.2699)
  Directional -> Accuracy: 0.5217, MCC: 0.0200, F1: 0.2667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65203 | val 0.80422
  Epoch 012 - train 0.62878 | val 1.04552
  Classification -> best τ=0.530 (val F1=0.2727)
  Directional -> Accuracy: 0.4412, MCC: 0.0124, F1: 0.5366

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52764 | val 0.67820
  Epoch 012 - train 0.52793 | val 1.06735
  Classification -> best τ=0.415 (val F1=0.1639)
  Directional -> Accuracy: 0.4762, MCC: -0.1452, F1: 0.2143

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59166 | val 0.73890
  Epoch 016 - train 0.56710 | val 0.79491
  Classification -> best τ=0.505 (val F1=0.3433)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61016 | val 0.84216
  Epoch 012 - train 0.60023 | val 0.74046
  Classification -> best τ=0.415 (val F1=0.0867)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62720 | val 0.96593
  Epoch 013 - train 0.58136 | val 1.18512
  Classification -> best τ=0.525 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58428 | val 1.75017
  Epoch 013 - train 0.57912 | val 1.66566
  Classification -> best τ=0.400 (val F1=0.3160)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55462 | val 1.29420
  Epoch 011 - train 0.51834 | val 1.48683
  Classification -> best τ=0.350 (val F1=0.2522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64302 | val 0.74612
  Epoch 011 - train 0.62084 | val 0.64901
  Classification -> best τ=0.380 (val F1=0.3852)
  Directional -> Accuracy: 0.5500, MCC: 0.1155, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56093 | val 0.81382
  Epoch 013 - train 0.54220 | val 1.68562
  Classification -> best τ=0.515 (val F1=0.1960)
  Directional -> Accuracy: 0.5686, MCC: 0.0996, F1: 0.3529

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61335 | val 0.79578
  Epoch 012 - train 0.56475 | val 0.96172
  Classification -> best τ=0.615 (val F1=0.3217)
  Directional -> Accuracy: 0.4493, MCC: -0.0796, F1: 0.3448

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58415 | val 1.73353
  Epoch 011 - train 0.54124 | val 1.82199
  Classification -> best τ=0.555 (val F1=0.2429)
  Directional -> Accuracy: 0.5345, MCC: -0.1387, F1: 0.6824

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67226 | val 0.81391
  Epoch 012 - train 0.64843 | val 0.89883
  Classification -> best τ=0.525 (val F1=0.0589)
  Directional -> Accuracy: 0.4400, MCC: -0.0680, F1: 0.4167

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60481 | val 0.86408
  Epoch 014 - train 0.64494 | val 1.58556
  Classification -> best τ=0.355 (val F1=0.2843)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60396 | val 0.65512
  Epoch 019 - train 0.55831 | val 0.83820
  Classification -> best τ=0.500 (val F1=0.4422)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62173 | val 0.95296
  Epoch 011 - train 0.59961 | val 0.96491
  Classification -> best τ=0.485 (val F1=0.0912)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60250 | val 1.17375
  Epoch 011 - train 0.62377 | val 1.12147
  Classification -> best τ=0.475 (val F1=0.1157)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61138 | val 0.78252
  Epoch 011 - train 0.60535 | val 0.75296
  Classification -> best τ=0.555 (val F1=0.3550)
  Directional -> Accuracy: 0.4386, MCC: -0.1216, F1: 0.4667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62222 | val 0.87701
  Epoch 012 - train 0.58730 | val 0.99162
  Classification -> best τ=0.310 (val F1=0.1478)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59125 | val 0.86700
  Epoch 016 - train 0.52822 | val 0.74407
  Classification -> best τ=0.530 (val F1=0.4543)
  Directional -> Accuracy: 0.4364, MCC: -0.0913, F1: 0.2439

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55900 | val 0.84019
  Epoch 011 - train 0.53499 | val 0.94329
  Classification -> best τ=0.475 (val F1=0.1310)
  Directional -> Accuracy: 0.5111, MCC: 0.0402, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62234 | val 0.69302
  Epoch 011 - train 0.61940 | val 0.67982
  Classification -> best τ=0.570 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.1514, F1: 0.4783

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59574 | val 0.81383
  Epoch 012 - train 0.59781 | val 0.89359
  Classification -> best τ=0.320 (val F1=0.2892)
  Directional -> Accuracy: 0.5893, MCC: 0.1511, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60809 | val 0.78003
  Epoch 013 - train 0.55800 | val 0.75458
  Classification -> best τ=0.575 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57515 | val 1.19103
  Epoch 012 - train 0.56918 | val 1.97064
  Classification -> best τ=0.475 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52934 | val 0.99652
  Epoch 011 - train 0.55753 | val 1.04296
  Classification -> best τ=0.470 (val F1=0.2042)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63318 | val 0.76908
  Epoch 012 - train 0.56957 | val 0.77903
  Classification -> best τ=0.355 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59521 | val 0.64384
  Epoch 014 - train 0.65560 | val 0.96108
  Classification -> best τ=0.415 (val F1=0.4243)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64956 | val 0.83028
  Epoch 011 - train 0.62676 | val 0.82670
  Classification -> best τ=0.445 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61860 | val 0.73053
  Epoch 012 - train 0.63616 | val 0.73760
  Classification -> best τ=0.440 (val F1=0.3525)
  Directional -> Accuracy: 0.5758, MCC: 0.0867, F1: 0.6818

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53563 | val 0.82274
  Epoch 013 - train 0.52436 | val 1.10093
  Classification -> best τ=0.460 (val F1=0.2768)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56373 | val 0.84940
  Epoch 013 - train 0.51634 | val 0.79699
  Classification -> best τ=0.595 (val F1=0.1615)
  Directional -> Accuracy: 0.5536, MCC: 0.1448, F1: 0.0741

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58033 | val 0.98429
  Epoch 011 - train 0.52971 | val 1.03576
  Classification -> best τ=0.445 (val F1=0.3105)
  Directional -> Accuracy: 0.5652, MCC: -0.0153, F1: 0.6970

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59815 | val 0.72816
  Epoch 011 - train 0.55952 | val 0.76328
  Classification -> best τ=0.500 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66787 | val 0.69465
  Epoch 011 - train 0.64028 | val 0.69509
  Classification -> best τ=0.495 (val F1=0.3504)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54859 | val 0.77143
  Epoch 012 - train 0.53763 | val 0.90769
  Classification -> best τ=0.390 (val F1=0.4438)
  Directional -> Accuracy: 0.5333, MCC: 0.1059, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58353 | val 0.61523
  Epoch 020 - train 0.50365 | val 0.89374
  Classification -> best τ=0.615 (val F1=0.5593)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57572 | val 0.71527
  Epoch 020 - train 0.45283 | val 0.74353
  Epoch 022 - train 0.37544 | val 1.03150
  Classification -> best τ=0.490 (val F1=0.5514)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58105 | val 0.75470
  Epoch 011 - train 0.60218 | val 0.75460
  Classification -> best τ=0.615 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58026 | val 1.73577
  Epoch 011 - train 0.54746 | val 1.78097
  Classification -> best τ=0.705 (val F1=0.2143)
  Directional -> Accuracy: 0.5536, MCC: 0.1049, F1: 0.5283

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60782 | val 0.81293
  Epoch 014 - train 0.62562 | val 0.97527
  Classification -> best τ=0.680 (val F1=0.2064)
  Directional -> Accuracy: 0.5094, MCC: 0.0275, F1: 0.4091

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60359 | val 0.79037
  Epoch 011 - train 0.60063 | val 0.71782
  Classification -> best τ=0.440 (val F1=0.0593)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61105 | val 0.74106

[I 2026-02-20 05:38:27,165] Trial 192 finished with value: 0.27962198828925233 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008629717190270472, 'weight_decay': 3.3900778834129794e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.19247647707364, 'early_stopping_min_delta': 0.009113776887724004}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.56899 | val 0.71298
  Classification -> best τ=0.370 (val F1=0.1203)
  Directional -> Accuracy: 0.5667, MCC: 0.1997, F1: 0.6667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27962198828925233
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59111 | val 0.70233
  Epoch 015 - train 0.57625 | val 0.73243
  Classification -> best τ=0.510 (val F1=0.2510)
  Directional -> Accuracy: 0.5921, MCC: 0.1561, F1: 0.4561

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63080 | val 0.67940
  Epoch 012 - train 0.61982 | val 0.68049
  Classification -> best τ=0.505 (val F1=0.2523)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58039 | val 0.74565
  Epoch 014 - train 0.57803 | val 0.79961
  Classification -> best τ=0.440 (val F1=0.4104)
  Directional -> Accuracy: 0.5217, MCC: 0.0259, F1: 0.6207

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65996 | val 0.92368
  Epoch 011 - train 0.64550 | val 0.85612
  Classification -> best τ=0.410 (val F1=0.1414)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60422 | val 0.69206
  Epoch 016 - train 0.52814 | val 0.74153
  Classification -> best τ=0.620 (val F1=0.4556)
  Directional -> Accuracy: 0.4600, MCC: -0.0801, F1: 0.1290

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59449 | val 0.86345
  Epoch 011 - train 0.59663 | val 0.81272
  Classification -> best τ=0.520 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63591 | val 1.13287
  Epoch 013 - train 0.63847 | val 0.91043
  Classification -> best τ=0.415 (val F1=0.2870)
  Directional -> Accuracy: 0.4118, MCC: 0.0280, F1: 0.5652

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53274 | val 0.67176
  Epoch 013 - train 0.46062 | val 0.88520
  Classification -> best τ=0.380 (val F1=0.2100)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58028 | val 0.81035
  Epoch 012 - train 0.51489 | val 0.99987
  Classification -> best τ=0.425 (val F1=0.0826)
  Directional -> Accuracy: 0.5000, MCC: 0.1009, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56006 | val 0.95345
  Epoch 011 - train 0.59340 | val 0.72118
  Classification -> best τ=0.525 (val F1=0.1424)
  Directional -> Accuracy: 0.4348, MCC: -0.0994, F1: 0.4507

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65360 | val 0.74276
  Epoch 014 - train 0.59573 | val 0.87857
  Classification -> best τ=0.450 (val F1=0.1949)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56597 | val 2.75549
  Epoch 011 - train 0.56179 | val 2.63795
  Classification -> best τ=0.475 (val F1=0.3032)
  Directional -> Accuracy: 0.6842, MCC: 0.3894, F1: 0.7353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66569 | val 0.66611
  Epoch 020 - train 0.53955 | val 1.51645
  Classification -> best τ=0.485 (val F1=0.3172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65292 | val 0.74025
  Epoch 011 - train 0.61289 | val 0.79719
  Classification -> best τ=0.385 (val F1=0.3477)
  Directional -> Accuracy: 0.5333, MCC: 0.0668, F1: 0.5172

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66579 | val 0.76741
  Epoch 013 - train 0.56836 | val 0.85795
  Classification -> best τ=0.570 (val F1=0.2571)
  Directional -> Accuracy: 0.5294, MCC: -0.1282, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56000 | val 1.95227
  Epoch 012 - train 0.58943 | val 2.15625
  Classification -> best τ=0.410 (val F1=0.4041)
  Directional -> Accuracy: 0.6087, MCC: 0.2060, F1: 0.6824

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59143 | val 0.97492
  Epoch 013 - train 0.58514 | val 0.92873
  Classification -> best τ=0.640 (val F1=0.1774)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67742 | val 0.71867
  Epoch 018 - train 0.66154 | val 1.05118
  Classification -> best τ=0.535 (val F1=0.2216)
  Directional -> Accuracy: 0.5733, MCC: 0.2012, F1: 0.5676

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59344 | val 0.94588
  Epoch 017 - train 0.57440 | val 2.21285
  Classification -> best τ=0.485 (val F1=0.2914)
  Directional -> Accuracy: 0.4375, MCC: -0.0048, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63679 | val 0.69601
  Epoch 015 - train 0.60438 | val 0.79757
  Classification -> best τ=0.485 (val F1=0.3460)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60302 | val 0.97662
  Epoch 018 - train 0.49037 | val 0.80068
  Classification -> best τ=0.530 (val F1=0.3458)
  Directional -> Accuracy: 0.4043, MCC: -0.0615, F1: 0.2632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64299 | val 0.84007
  Epoch 011 - train 0.61842 | val 0.78235
  Classification -> best τ=0.610 (val F1=0.1512)
  Directional -> Accuracy: 0.4000, MCC: -0.1994, F1: 0.3810

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63969 | val 0.76535
  Epoch 013 - train 0.57414 | val 0.89917
  Classification -> best τ=0.515 (val F1=0.3329)
  Directional -> Accuracy: 0.4737, MCC: -0.0509, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62623 | val 0.69538
  Epoch 015 - train 0.55448 | val 0.72377
  Classification -> best τ=0.410 (val F1=0.1337)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57712 | val 0.64949
  Epoch 018 - train 0.48388 | val 0.83424
  Classification -> best τ=0.445 (val F1=0.4380)
  Directional -> Accuracy: 0.5455, MCC: 0.1257, F1: 0.4898

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59301 | val 0.73283
  Epoch 011 - train 0.61929 | val 0.81146
  Classification -> best τ=0.515 (val F1=0.0385)
  Directional -> Accuracy: 0.4444, MCC: -0.1022, F1: 0.4186

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61756 | val 0.68155
  Epoch 012 - train 0.57670 | val 0.72748
  Classification -> best τ=0.610 (val F1=0.2161)
  Directional -> Accuracy: 0.4524, MCC: -0.0700, F1: 0.4390

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59021 | val 1.08471
  Epoch 011 - train 0.56775 | val 1.12127
  Classification -> best τ=0.460 (val F1=0.2435)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65195 | val 0.77918
  Epoch 011 - train 0.58598 | val 0.80845
  Classification -> best τ=0.450 (val F1=0.4114)
  Directional -> Accuracy: 0.5250, MCC: 0.0056, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61908 | val 0.89261
  Epoch 012 - train 0.61038 | val 0.87474
  Classification -> best τ=0.465 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54786 | val 1.41268
  Epoch 011 - train 0.58094 | val 1.33832
  Classification -> best τ=0.600 (val F1=0.1286)
  Directional -> Accuracy: 0.4286, MCC: -0.1090, F1: 0.1429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57431 | val 0.74482
  Epoch 012 - train 0.51551 | val 0.95815
  Classification -> best τ=0.340 (val F1=0.3789)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63354 | val 0.62781
  Epoch 020 - train 0.51933 | val 0.69633
  Classification -> best τ=0.430 (val F1=0.4063)
  Directional -> Accuracy: 0.5417, MCC: 0.1076, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60357 | val 1.00641
  Epoch 012 - train 0.55899 | val 1.21578
  Classification -> best τ=0.625 (val F1=0.3140)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65778 | val 0.92383
  Epoch 011 - train 0.64365 | val 0.95346
  Classification -> best τ=0.505 (val F1=0.2951)
  Directional -> Accuracy: 0.4242, MCC: -0.1159, F1: 0.3871

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64750 | val 0.72171
  Epoch 014 - train 0.60886 | val 0.79932
  Classification -> best τ=0.480 (val F1=0.2144)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57853 | val 0.70886
  Epoch 012 - train 0.55857 | val 0.72444
  Classification -> best τ=0.555 (val F1=0.2478)
  Directional -> Accuracy: 0.6071, MCC: 0.2028, F1: 0.5217

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61263 | val 1.58293
  Epoch 012 - train 0.55073 | val 1.27735
  Classification -> best τ=0.355 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56219 | val 0.77255
  Epoch 017 - train 0.45439 | val 0.74505
  Classification -> best τ=0.570 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58847 | val 0.85410
  Epoch 011 - train 0.56421 | val 0.81201
  Classification -> best τ=0.555 (val F1=0.3510)
  Directional -> Accuracy: 0.4730, MCC: -0.0549, F1: 0.6214

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55192 | val 0.78639
  Epoch 012 - train 0.55118 | val 0.84149
  Classification -> best τ=0.400 (val F1=0.4632)
  Directional -> Accuracy: 0.5111, MCC: 0.0285, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59109 | val 0.78201
  Epoch 013 - train 0.56295 | val 1.17497
  Classification -> best τ=0.320 (val F1=0.4082)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59485 | val 0.75270
  Epoch 011 - train 0.60542 | val 0.68921
  Classification -> best τ=0.585 (val F1=0.5421)
  Directional -> Accuracy: 0.5417, MCC: 0.3464, F1: 0.6207

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58393 | val 0.75810
  Epoch 011 - train 0.55955 | val 0.83147
  Classification -> best τ=0.585 (val F1=0.2374)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62853 | val 1.04486
  Epoch 015 - train 0.53091 | val 2.28322
  Classification -> best τ=0.615 (val F1=0.4159)
  Directional -> Accuracy: 0.4821, MCC: -0.0187, F1: 0.5915

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58278 | val 1.11862
  Epoch 015 - train 0.56145 | val 0.95867
  Classification -> best τ=0.700 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61727 | val 0.84238
  Epoch 011 - train 0.57292 | val 0.96265
  Classification -> best τ=0.435 (val F1=0.0952)
  Directional -> Accuracy: 0.5455, MCC: 0.0780, F1: 0.6154

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58971 | val 0.76968

[I 2026-02-20 05:39:24,080] Trial 193 finished with value: 0.2851166132621383 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009950127236186117, 'weight_decay': 3.4194057794632483e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2133462300654767, 'early_stopping_min_delta': 0.008991607196211431}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.58232 | val 0.78868
  Classification -> best τ=0.420 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2851166132621383
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67877 | val 0.66737
  Epoch 015 - train 0.58725 | val 0.76047
  Classification -> best τ=0.550 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0412, F1: 0.2273

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62855 | val 0.68058
  Epoch 014 - train 0.58625 | val 0.67130
  Classification -> best τ=0.415 (val F1=0.1844)
  Directional -> Accuracy: 0.6667, MCC: 0.2984, F1: 0.7458

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63875 | val 0.69699
  Epoch 017 - train 0.50106 | val 1.37873
  Classification -> best τ=0.545 (val F1=0.3835)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65732 | val 0.69796
  Epoch 011 - train 0.64781 | val 0.74000
  Classification -> best τ=0.545 (val F1=0.1725)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55962 | val 1.01360
  Epoch 016 - train 0.55545 | val 2.17680
  Classification -> best τ=0.475 (val F1=0.3945)
  Directional -> Accuracy: 0.7400, MCC: 0.4802, F1: 0.7636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59655 | val 0.72026
  Epoch 014 - train 0.55704 | val 0.71952
  Classification -> best τ=0.650 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.1538

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66456 | val 0.75457
  Epoch 012 - train 0.64965 | val 0.75850
  Classification -> best τ=0.360 (val F1=0.2755)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51849 | val 0.77117
  Epoch 012 - train 0.52103 | val 1.00254
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56009 | val 0.83095
  Epoch 011 - train 0.56238 | val 0.89453
  Classification -> best τ=0.455 (val F1=0.1402)
  Directional -> Accuracy: 0.5208, MCC: 0.1212, F1: 0.5965

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59439 | val 0.69460
  Epoch 014 - train 0.57780 | val 0.91951
  Classification -> best τ=0.570 (val F1=0.2725)
  Directional -> Accuracy: 0.4928, MCC: -0.0361, F1: 0.4068

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59291 | val 0.75942
  Epoch 016 - train 0.54042 | val 1.16083
  Classification -> best τ=0.490 (val F1=0.1738)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60643 | val 1.02497
  Epoch 013 - train 0.55072 | val 1.33560
  Classification -> best τ=0.540 (val F1=0.2045)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54073 | val 0.89546
  Epoch 011 - train 0.53316 | val 0.97107
  Classification -> best τ=0.485 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64186 | val 0.68360
  Epoch 011 - train 0.58682 | val 0.65771
  Classification -> best τ=0.470 (val F1=0.3774)
  Directional -> Accuracy: 0.5167, MCC: 0.0335, F1: 0.4912

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66795 | val 0.68676
  Epoch 014 - train 0.55775 | val 0.79121
  Classification -> best τ=0.480 (val F1=0.1925)
  Directional -> Accuracy: 0.4510, MCC: -0.0425, F1: 0.5758

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63309 | val 0.70984
  Epoch 012 - train 0.66260 | val 0.74209
  Classification -> best τ=0.430 (val F1=0.3372)
  Directional -> Accuracy: 0.5217, MCC: 0.0285, F1: 0.5823

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60875 | val 1.37354
  Epoch 012 - train 0.59140 | val 1.50427
  Classification -> best τ=0.665 (val F1=0.1291)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64959 | val 1.15695
  Epoch 013 - train 0.62412 | val 1.15901
  Classification -> best τ=0.475 (val F1=0.1605)
  Directional -> Accuracy: 0.5333, MCC: 0.0439, F1: 0.5977

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59178 | val 0.83400
  Epoch 013 - train 0.55949 | val 1.06519
  Classification -> best τ=0.420 (val F1=0.3140)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64916 | val 0.68771
  Epoch 020 - train 0.61542 | val 0.78122
  Epoch 023 - train 0.56011 | val 0.69287
  Classification -> best τ=0.380 (val F1=0.2809)
  Directional -> Accuracy: 0.3378, MCC: -0.3185, F1: 0.3467

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62274 | val 0.89579
  Epoch 011 - train 0.59287 | val 0.89660
  Classification -> best τ=0.550 (val F1=0.1448)
  Directional -> Accuracy: 0.5319, MCC: -0.1702, F1: 0.6857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64685 | val 0.90296
  Epoch 013 - train 0.68049 | val 0.83928
  Classification -> best τ=0.455 (val F1=0.1650)
  Directional -> Accuracy: 0.5538, MCC: 0.1398, F1: 0.6742

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61950 | val 0.71894
  Epoch 012 - train 0.60183 | val 0.93345
  Classification -> best τ=0.685 (val F1=0.3550)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61156 | val 0.73069
  Epoch 011 - train 0.62225 | val 0.75596
  Classification -> best τ=0.540 (val F1=0.0123)
  Directional -> Accuracy: 0.4462, MCC: -0.1006, F1: 0.4857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64108 | val 0.81395
  Epoch 016 - train 0.55399 | val 1.21188
  Classification -> best τ=0.500 (val F1=0.4001)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62448 | val 0.92644
  Epoch 011 - train 0.53242 | val 1.05513
  Classification -> best τ=0.440 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61424 | val 0.68397
  Epoch 011 - train 0.60652 | val 0.68249
  Classification -> best τ=0.630 (val F1=0.1876)
  Directional -> Accuracy: 0.5476, MCC: 0.0700, F1: 0.6122

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65296 | val 0.73700
  Epoch 011 - train 0.62741 | val 0.79603
  Classification -> best τ=0.450 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61727 | val 0.96009
  Epoch 011 - train 0.61670 | val 0.75472
  Classification -> best τ=0.575 (val F1=0.2774)
  Directional -> Accuracy: 0.5750, MCC: 0.1372, F1: 0.6222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62345 | val 1.08556
  Epoch 012 - train 0.57009 | val 0.94061
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59957 | val 0.87626
  Epoch 012 - train 0.55655 | val 1.47840
  Classification -> best τ=0.655 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63432 | val 0.78939
  Epoch 012 - train 0.54591 | val 1.16647
  Classification -> best τ=0.290 (val F1=0.2509)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61832 | val 1.15618
  Epoch 012 - train 0.59444 | val 1.23038
  Classification -> best τ=0.500 (val F1=0.1838)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58411 | val 1.03202
  Epoch 011 - train 0.55973 | val 1.28941
  Classification -> best τ=0.400 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.0831, F1: 0.6000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64973 | val 0.73459
  Epoch 013 - train 0.59504 | val 0.77241
  Classification -> best τ=0.490 (val F1=0.1617)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63847 | val 0.72076
  Epoch 016 - train 0.48305 | val 0.85391
  Classification -> best τ=0.605 (val F1=0.2228)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58337 | val 0.75880
  Epoch 013 - train 0.56102 | val 0.85080
  Classification -> best τ=0.425 (val F1=0.1690)
  Directional -> Accuracy: 0.4286, MCC: -0.1432, F1: 0.4074

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57910 | val 1.03844
  Epoch 013 - train 0.46852 | val 1.15984
  Classification -> best τ=0.400 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56767 | val 0.84002
  Epoch 014 - train 0.54994 | val 1.11580
  Classification -> best τ=0.595 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61274 | val 0.72217
  Epoch 011 - train 0.67999 | val 0.82806
  Classification -> best τ=0.465 (val F1=0.3134)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57417 | val 0.79761
  Epoch 012 - train 0.53459 | val 0.92763
  Classification -> best τ=0.400 (val F1=0.2668)
  Directional -> Accuracy: 0.5111, MCC: 0.0069, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58341 | val 0.63791
  Epoch 020 - train 0.47771 | val 0.74551
  Classification -> best τ=0.495 (val F1=0.4082)
  Directional -> Accuracy: 0.6667, MCC: 0.3151, F1: 0.7586

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61593 | val 0.73049
  Epoch 011 - train 0.62924 | val 0.71870
  Classification -> best τ=0.565 (val F1=0.6292)
  Directional -> Accuracy: 0.4583, MCC: 0.0237, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58658 | val 0.72544
  Epoch 011 - train 0.59269 | val 0.85697
  Classification -> best τ=0.595 (val F1=0.2036)
  Directional -> Accuracy: 0.4909, MCC: 0.1150, F1: 0.1765

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55310 | val 1.27641
  Epoch 011 - train 0.56962 | val 1.69626
  Classification -> best τ=0.425 (val F1=0.2514)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63523 | val 1.22104
  Epoch 012 - train 0.59946 | val 1.23917
  Classification -> best τ=0.650 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1083, F1: 0.4545

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61378 | val 0.76048
  Epoch 011 - train 0.59780 | val 0.93642
  Classification -> best τ=0.375 (val F1=0.2121)
  Directional -> Accuracy: 0.5273, MCC: 0.0191, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59101 | val 0.92311

[I 2026-02-20 05:40:19,476] Trial 194 finished with value: 0.2479751942254467 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009965715432907914, 'weight_decay': 3.0736995874663624e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2049119155123282, 'early_stopping_min_delta': 0.008984635152970722}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.57397 | val 0.75492
  Classification -> best τ=0.430 (val F1=0.2160)
  Directional -> Accuracy: 0.4167, MCC: -0.1694, F1: 0.3860

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2479751942254467
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62651 | val 0.68298
  Epoch 016 - train 0.55639 | val 0.88645
  Classification -> best τ=0.445 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1104, F1: 0.4762

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64645 | val 0.69745
  Epoch 017 - train 0.58352 | val 0.71255
  Classification -> best τ=0.470 (val F1=0.4136)
  Directional -> Accuracy: 0.6222, MCC: 0.1967, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62227 | val 0.81767
  Epoch 011 - train 0.57366 | val 0.67788
  Classification -> best τ=0.545 (val F1=0.2514)
  Directional -> Accuracy: 0.5000, MCC: 0.0266, F1: 0.3429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67614 | val 0.91093
  Epoch 012 - train 0.66479 | val 0.83984
  Classification -> best τ=0.380 (val F1=0.2056)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68205 | val 0.63693
  Epoch 016 - train 0.54655 | val 0.69646
  Classification -> best τ=0.520 (val F1=0.4139)
  Directional -> Accuracy: 0.6200, MCC: 0.2442, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62884 | val 0.74344
  Epoch 011 - train 0.58546 | val 0.77931
  Classification -> best τ=0.460 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64523 | val 0.76990
  Epoch 014 - train 0.59521 | val 1.08293
  Classification -> best τ=0.335 (val F1=0.2445)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51973 | val 0.60001
  Epoch 012 - train 0.56631 | val 1.11976
  Classification -> best τ=0.350 (val F1=0.1657)
  Directional -> Accuracy: 0.4048, MCC: -0.2439, F1: 0.2424

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62501 | val 0.70685
  Epoch 017 - train 0.53615 | val 1.04188
  Classification -> best τ=0.590 (val F1=0.4025)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59437 | val 0.89100
  Epoch 012 - train 0.59240 | val 0.81438
  Classification -> best τ=0.680 (val F1=0.1607)
  Directional -> Accuracy: 0.5072, MCC: -0.0310, F1: 0.3704

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66558 | val 0.67236
  Epoch 013 - train 0.61921 | val 1.49043
  Classification -> best τ=0.445 (val F1=0.2687)
  Directional -> Accuracy: 0.5102, MCC: -0.0069, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58542 | val 1.03983
  Epoch 012 - train 0.59418 | val 2.01037
  Classification -> best τ=0.615 (val F1=0.2083)
  Directional -> Accuracy: 0.6842, MCC: 0.3682, F1: 0.6897

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51430 | val 1.88990
  Epoch 012 - train 0.54265 | val 1.59040
  Classification -> best τ=0.465 (val F1=0.3172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61216 | val 0.68340
  Epoch 013 - train 0.59582 | val 0.67833
  Classification -> best τ=0.380 (val F1=0.3748)
  Directional -> Accuracy: 0.5833, MCC: 0.1675, F1: 0.5614

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59876 | val 0.72830
  Epoch 014 - train 0.55787 | val 0.74782
  Classification -> best τ=0.480 (val F1=0.2530)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63489 | val 0.90196
  Epoch 014 - train 0.53790 | val 0.93489
  Classification -> best τ=0.700 (val F1=0.3411)
  Directional -> Accuracy: 0.5072, MCC: 0.0596, F1: 0.3704

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60398 | val 1.61523
  Epoch 011 - train 0.57939 | val 1.77019
  Classification -> best τ=0.640 (val F1=0.2207)
  Directional -> Accuracy: 0.3621, MCC: -0.2115, F1: 0.3273

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65380 | val 0.91371
  Epoch 011 - train 0.65277 | val 1.03891
  Classification -> best τ=0.365 (val F1=0.2004)
  Directional -> Accuracy: 0.5867, MCC: 0.0780, F1: 0.6990

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65769 | val 1.08310
  Epoch 012 - train 0.61279 | val 0.85490
  Classification -> best τ=0.550 (val F1=0.3010)
  Directional -> Accuracy: 0.4531, MCC: 0.0577, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64505 | val 0.66712
  Epoch 019 - train 0.56038 | val 1.01331
  Classification -> best τ=0.415 (val F1=0.2639)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62613 | val 0.69567
  Epoch 020 - train 0.44286 | val 0.99291
  Epoch 023 - train 0.53932 | val 1.13119
  Classification -> best τ=0.390 (val F1=0.3678)
  Directional -> Accuracy: 0.6383, MCC: 0.1728, F1: 0.7463

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66682 | val 0.96257
  Epoch 011 - train 0.63710 | val 0.89584
  Classification -> best τ=0.480 (val F1=0.2315)
  Directional -> Accuracy: 0.4615, MCC: -0.0959, F1: 0.5679

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61439 | val 0.70240
  Epoch 013 - train 0.57828 | val 0.74856
  Classification -> best τ=0.565 (val F1=0.2644)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66777 | val 0.72967
  Epoch 016 - train 0.59845 | val 0.73148
  Classification -> best τ=0.505 (val F1=0.2055)
  Directional -> Accuracy: 0.5077, MCC: 0.0020, F1: 0.4074

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58259 | val 0.83544
  Epoch 013 - train 0.55957 | val 0.80971
  Classification -> best τ=0.530 (val F1=0.4973)
  Directional -> Accuracy: 0.5273, MCC: 0.1695, F1: 0.3158

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58369 | val 1.09719
  Epoch 012 - train 0.53785 | val 1.31370
  Classification -> best τ=0.560 (val F1=0.3039)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65283 | val 0.69880
  Epoch 011 - train 0.65758 | val 0.69528
  Classification -> best τ=0.630 (val F1=0.1021)
  Directional -> Accuracy: 0.5714, MCC: 0.0700, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59055 | val 0.82221
  Epoch 012 - train 0.56392 | val 0.88805
  Classification -> best τ=0.245 (val F1=0.2058)
  Directional -> Accuracy: 0.5357, MCC: 0.1124, F1: 0.4800

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57401 | val 0.71973
  Epoch 012 - train 0.57486 | val 0.72086
  Classification -> best τ=0.600 (val F1=0.3477)
  Directional -> Accuracy: 0.4250, MCC: -0.1372, F1: 0.4103

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60010 | val 1.33988
  Epoch 012 - train 0.57606 | val 1.21668
  Classification -> best τ=0.585 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57554 | val 0.87722
  Epoch 011 - train 0.58561 | val 1.25766
  Classification -> best τ=0.545 (val F1=0.1846)
  Directional -> Accuracy: 0.4048, MCC: -0.1940, F1: 0.0741

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61794 | val 0.87869
  Epoch 013 - train 0.56030 | val 0.94627
  Classification -> best τ=0.445 (val F1=0.4158)
  Directional -> Accuracy: 0.5510, MCC: 0.0877, F1: 0.6207

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61757 | val 0.66134
  Epoch 015 - train 0.60466 | val 0.63772
  Classification -> best τ=0.405 (val F1=0.3366)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62980 | val 1.03627
  Epoch 014 - train 0.54191 | val 1.31248
  Classification -> best τ=0.375 (val F1=0.2324)
  Directional -> Accuracy: 0.5581, MCC: 0.1366, F1: 0.6275

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63543 | val 0.81666
  Epoch 013 - train 0.61455 | val 0.81393
  Classification -> best τ=0.660 (val F1=0.1822)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53747 | val 0.91522
  Epoch 013 - train 0.55017 | val 1.07735
  Classification -> best τ=0.375 (val F1=0.2768)
  Directional -> Accuracy: 0.7381, MCC: 0.4949, F1: 0.7179

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58159 | val 0.79964
  Epoch 013 - train 0.53232 | val 0.92801
  Classification -> best τ=0.425 (val F1=0.3217)
  Directional -> Accuracy: 0.5893, MCC: 0.2253, F1: 0.6462

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55888 | val 1.00163
  Epoch 012 - train 0.55643 | val 1.25481
  Classification -> best τ=0.490 (val F1=0.2804)
  Directional -> Accuracy: 0.4783, MCC: 0.0706, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60442 | val 0.64379
  Epoch 020 - train 0.37531 | val 0.67315
  Epoch 022 - train 0.36428 | val 0.68423
  Classification -> best τ=0.320 (val F1=0.4973)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60831 | val 1.05475
  Epoch 015 - train 0.61209 | val 0.74085
  Classification -> best τ=0.510 (val F1=0.2419)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57767 | val 0.76860
  Epoch 013 - train 0.57874 | val 0.87132
  Classification -> best τ=0.495 (val F1=0.1890)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60828 | val 0.74779
  Epoch 020 - train 0.51327 | val 1.40537
  Epoch 023 - train 0.56757 | val 1.64371
  Classification -> best τ=0.145 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57401 | val 0.70915
  Epoch 017 - train 0.42697 | val 0.82157
  Classification -> best τ=0.490 (val F1=0.5249)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60534 | val 0.70053
  Epoch 011 - train 0.58948 | val 0.69944
  Classification -> best τ=0.610 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58569 | val 1.49728
  Epoch 012 - train 0.52933 | val 2.05603
  Classification -> best τ=0.650 (val F1=0.2493)
  Directional -> Accuracy: 0.5536, MCC: 0.2676, F1: 0.6835

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61780 | val 0.96811
  Epoch 012 - train 0.58634 | val 1.42376
  Classification -> best τ=0.505 (val F1=0.2351)
  Directional -> Accuracy: 0.5283, MCC: 0.0546, F1: 0.6269

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61507 | val 1.09606
  Epoch 014 - train 0.56439 | val 0.94227
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63692 | val 0.69218

[I 2026-02-20 05:41:19,527] Trial 195 finished with value: 0.28003029532627394 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009912304814576145, 'weight_decay': 3.30126314848811e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0592462246046457, 'early_stopping_min_delta': 0.009136885086279398}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 015 - train 0.59979 | val 0.78014
  Classification -> best τ=0.385 (val F1=0.1138)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28003029532627394
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64138 | val 1.03053
  Epoch 012 - train 0.57388 | val 1.02576
  Classification -> best τ=0.450 (val F1=0.2200)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64639 | val 0.76032
  Epoch 013 - train 0.61800 | val 0.76328
  Classification -> best τ=0.395 (val F1=0.2204)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61336 | val 0.76823
  Epoch 017 - train 0.56172 | val 0.75504
  Classification -> best τ=0.570 (val F1=0.3171)
  Directional -> Accuracy: 0.4130, MCC: -0.1741, F1: 0.4255

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65123 | val 0.74898
  Epoch 013 - train 0.63947 | val 0.72181
  Classification -> best τ=0.510 (val F1=0.1918)
  Directional -> Accuracy: 0.5135, MCC: 0.2204, F1: 0.1818

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61161 | val 0.78573
  Epoch 015 - train 0.54474 | val 0.71574
  Classification -> best τ=0.470 (val F1=0.4414)
  Directional -> Accuracy: 0.5800, MCC: 0.2203, F1: 0.4324

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65603 | val 0.72076
  Epoch 014 - train 0.59882 | val 0.72871
  Classification -> best τ=0.575 (val F1=0.1537)
  Directional -> Accuracy: 0.4130, MCC: -0.1723, F1: 0.5091

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64783 | val 0.93339
  Epoch 012 - train 0.64520 | val 0.93456
  Classification -> best τ=0.435 (val F1=0.3208)
  Directional -> Accuracy: 0.4412, MCC: 0.1135, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53121 | val 0.72625
  Epoch 012 - train 0.47116 | val 1.04406
  Classification -> best τ=0.400 (val F1=0.1657)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.3784

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55796 | val 0.79855
  Epoch 012 - train 0.57825 | val 0.79546
  Classification -> best τ=0.500 (val F1=0.2784)
  Directional -> Accuracy: 0.6042, MCC: 0.1843, F1: 0.5128

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64290 | val 0.96716
  Epoch 014 - train 0.56880 | val 0.69628
  Classification -> best τ=0.525 (val F1=0.1607)
  Directional -> Accuracy: 0.5072, MCC: -0.0415, F1: 0.3462

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66147 | val 0.71869
  Epoch 019 - train 0.56464 | val 0.91502
  Classification -> best τ=0.490 (val F1=0.2187)
  Directional -> Accuracy: 0.5510, MCC: 0.0852, F1: 0.4762

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57653 | val 1.25350
  Epoch 012 - train 0.61255 | val 2.20601
  Classification -> best τ=0.525 (val F1=0.1181)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65938 | val 0.87395
  Epoch 012 - train 0.63575 | val 0.78815
  Classification -> best τ=0.595 (val F1=0.2337)
  Directional -> Accuracy: 0.4286, MCC: -0.2150, F1: 0.2000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58933 | val 0.70720
  Epoch 011 - train 0.59103 | val 0.72781
  Classification -> best τ=0.410 (val F1=0.3477)
  Directional -> Accuracy: 0.6167, MCC: 0.2400, F1: 0.6567

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57658 | val 1.07507
  Epoch 011 - train 0.55906 | val 0.97054
  Classification -> best τ=0.485 (val F1=0.3333)
  Directional -> Accuracy: 0.4706, MCC: -0.0497, F1: 0.4706

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64466 | val 0.72002
  Epoch 014 - train 0.60034 | val 1.16395
  Classification -> best τ=0.350 (val F1=0.2224)
  Directional -> Accuracy: 0.5797, MCC: 0.1885, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62998 | val 0.73376
  Epoch 019 - train 0.50622 | val 2.12930
  Classification -> best τ=0.535 (val F1=0.1905)
  Directional -> Accuracy: 0.5690, MCC: 0.0059, F1: 0.6914

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60974 | val 1.46738
  Epoch 012 - train 0.58437 | val 2.31282
  Classification -> best τ=0.535 (val F1=0.1031)
  Directional -> Accuracy: 0.3867, MCC: -0.1814, F1: 0.3611

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61436 | val 0.73530
  Epoch 014 - train 0.62609 | val 0.76289
  Classification -> best τ=0.430 (val F1=0.2522)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67114 | val 0.67165
  Epoch 016 - train 0.65021 | val 0.70422
  Classification -> best τ=0.390 (val F1=0.2957)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60473 | val 1.20374
  Epoch 020 - train 0.39829 | val 1.22474
  Epoch 024 - train 0.37271 | val 0.97241
  Classification -> best τ=0.635 (val F1=0.2727)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65820 | val 0.77484
  Epoch 015 - train 0.64130 | val 0.89167
  Classification -> best τ=0.435 (val F1=0.2673)
  Directional -> Accuracy: 0.5231, MCC: 0.0448, F1: 0.5507

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63882 | val 0.72253
  Epoch 014 - train 0.63350 | val 0.80760
  Classification -> best τ=0.520 (val F1=0.2944)
  Directional -> Accuracy: 0.5614, MCC: 0.1216, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63584 | val 0.70478
  Epoch 011 - train 0.58617 | val 0.69298
  Classification -> best τ=0.380 (val F1=0.1348)
  Directional -> Accuracy: 0.5538, MCC: 0.1211, F1: 0.2162

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63295 | val 0.60696
  Epoch 020 - train 0.46858 | val 0.85333
  Classification -> best τ=0.415 (val F1=0.4688)
  Directional -> Accuracy: 0.5273, MCC: 0.0669, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56312 | val 1.60500
  Epoch 011 - train 0.52201 | val 1.68056
  Classification -> best τ=0.460 (val F1=0.2756)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59732 | val 0.70955
  Epoch 020 - train 0.50839 | val 0.74027
  Epoch 022 - train 0.52241 | val 0.94833
  Classification -> best τ=0.620 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67334 | val 0.69669
  Epoch 014 - train 0.59132 | val 0.86650
  Classification -> best τ=0.495 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59581 | val 0.70396
  Epoch 020 - train 0.38590 | val 0.63190
  Epoch 030 - train 0.14283 | val 1.83726
  Classification -> best τ=0.545 (val F1=0.3671)
  Directional -> Accuracy: 0.5000, MCC: -0.0580, F1: 0.6154

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64075 | val 1.05152
  Epoch 012 - train 0.65256 | val 0.85369
  Classification -> best τ=0.585 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63145 | val 1.12226
  Epoch 012 - train 0.54746 | val 1.16504
  Classification -> best τ=0.455 (val F1=0.2357)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.6875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58686 | val 0.76888
  Epoch 015 - train 0.49124 | val 1.01871
  Classification -> best τ=0.405 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63065 | val 0.64924
  Epoch 012 - train 0.59956 | val 0.83713
  Classification -> best τ=0.395 (val F1=0.3366)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58130 | val 0.97332
  Epoch 012 - train 0.59638 | val 1.13570
  Classification -> best τ=0.460 (val F1=0.3078)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65014 | val 0.84464
  Epoch 011 - train 0.62896 | val 0.82090
  Classification -> best τ=0.375 (val F1=0.3603)
  Directional -> Accuracy: 0.5606, MCC: 0.0799, F1: 0.6420

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54552 | val 1.02222
  Epoch 012 - train 0.52684 | val 0.84548
  Classification -> best τ=0.350 (val F1=0.2658)
  Directional -> Accuracy: 0.7619, MCC: 0.5273, F1: 0.7619

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54856 | val 0.82139
  Epoch 011 - train 0.53158 | val 0.97741
  Classification -> best τ=0.445 (val F1=0.2450)
  Directional -> Accuracy: 0.6071, MCC: 0.2148, F1: 0.5926

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54766 | val 0.91356
  Epoch 011 - train 0.50913 | val 0.93020
  Classification -> best τ=0.400 (val F1=0.2474)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56712 | val 0.65804
  Epoch 014 - train 0.53289 | val 0.88069
  Classification -> best τ=0.495 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61431 | val 0.70155
  Epoch 011 - train 0.62799 | val 0.76465
  Classification -> best τ=0.575 (val F1=0.3765)
  Directional -> Accuracy: 0.5000, MCC: 0.0313, F1: 0.6337

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56670 | val 0.81960
  Epoch 012 - train 0.54943 | val 0.88946
  Classification -> best τ=0.500 (val F1=0.4080)
  Directional -> Accuracy: 0.5111, MCC: 0.0349, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65364 | val 0.58067
  Epoch 018 - train 0.54736 | val 0.71050
  Classification -> best τ=0.390 (val F1=0.6124)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57479 | val 0.71977
  Epoch 015 - train 0.49277 | val 0.70466
  Classification -> best τ=0.530 (val F1=0.6095)
  Directional -> Accuracy: 0.3958, MCC: -0.0176, F1: 0.5246

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58907 | val 0.76917
  Epoch 015 - train 0.53927 | val 0.72991
  Classification -> best τ=0.550 (val F1=0.0782)
  Directional -> Accuracy: 0.5273, MCC: -0.0090, F1: 0.6579

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59878 | val 1.43703
  Epoch 011 - train 0.60894 | val 1.82010
  Classification -> best τ=0.635 (val F1=0.2143)
  Directional -> Accuracy: 0.5536, MCC: 0.1032, F1: 0.3902

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61491 | val 1.09993
  Epoch 012 - train 0.59404 | val 1.14370
  Classification -> best τ=0.365 (val F1=0.1573)
  Directional -> Accuracy: 0.5660, MCC: 0.2496, F1: 0.7013

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60997 | val 0.96276
  Epoch 012 - train 0.59885 | val 0.89512
  Classification -> best τ=0.470 (val F1=0.0094)
  Directional -> Accuracy: 0.4182, MCC: -0.1554, F1: 0.3600

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59019 | val 0.70892
  Epoch 012 - train 0.63759 | val 0.75551

[I 2026-02-20 05:42:17,785] Trial 196 finished with value: 0.27202167539835886 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008850316713212153, 'weight_decay': 3.453654780044265e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1596145177363701, 'early_stopping_min_delta': 0.00912724480314869}. Best is trial 180 with value: 0.30107335520239253.

  Classification -> best τ=0.440 (val F1=0.2124)
  Directional -> Accuracy: 0.4167, MCC: -0.1823, F1: 0.3137

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27202167539835886
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58259 | val 0.72886
  Epoch 016 - train 0.59006 | val 1.19194
  Classification -> best τ=0.610 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0547, F1: 0.3200

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54698 | val 0.63496
  Epoch 019 - train 0.47443 | val 1.04403
  Classification -> best τ=0.440 (val F1=0.3123)
  Directional -> Accuracy: 0.5333, MCC: 0.0782, F1: 0.5532

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60210 | val 0.74502
  Epoch 014 - train 0.52332 | val 0.78046
  Classification -> best τ=0.550 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66360 | val 0.84539
  Epoch 012 - train 0.63182 | val 0.94881
  Classification -> best τ=0.495 (val F1=0.0813)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58198 | val 0.81350
  Epoch 011 - train 0.56110 | val 0.97298
  Classification -> best τ=0.520 (val F1=0.4787)
  Directional -> Accuracy: 0.7200, MCC: 0.4423, F1: 0.7200

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63819 | val 0.92866
  Epoch 011 - train 0.64088 | val 0.96407
  Classification -> best τ=0.525 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68198 | val 0.92950
  Epoch 012 - train 0.62143 | val 0.94938
  Classification -> best τ=0.505 (val F1=0.2931)
  Directional -> Accuracy: 0.5294, MCC: 0.0921, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53928 | val 0.68552
  Epoch 012 - train 0.51139 | val 1.24962
  Classification -> best τ=0.380 (val F1=0.1147)
  Directional -> Accuracy: 0.5238, MCC: -0.0786, F1: 0.1667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58264 | val 0.73384
  Epoch 012 - train 0.57478 | val 0.79977
  Classification -> best τ=0.395 (val F1=0.1402)
  Directional -> Accuracy: 0.4583, MCC: -0.0295, F1: 0.5357

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58532 | val 0.72492
  Epoch 013 - train 0.61629 | val 0.91142
  Classification -> best τ=0.510 (val F1=0.1424)
  Directional -> Accuracy: 0.4783, MCC: -0.0139, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66818 | val 0.74671
  Epoch 014 - train 0.68823 | val 0.82103
  Classification -> best τ=0.425 (val F1=0.1713)
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56796 | val 1.72926
  Epoch 011 - train 0.53301 | val 1.24491
  Classification -> best τ=0.480 (val F1=0.2830)
  Directional -> Accuracy: 0.6491, MCC: 0.2979, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57836 | val 1.21427
  Epoch 012 - train 0.55119 | val 1.52169
  Classification -> best τ=0.455 (val F1=0.2522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62746 | val 0.67171
  Epoch 011 - train 0.65599 | val 0.77584
  Classification -> best τ=0.390 (val F1=0.3362)
  Directional -> Accuracy: 0.5167, MCC: 0.0334, F1: 0.5246

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57427 | val 0.78614
  Epoch 011 - train 0.55528 | val 0.77252
  Classification -> best τ=0.455 (val F1=0.0789)
  Directional -> Accuracy: 0.5294, MCC: 0.1742, F1: 0.6364

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61526 | val 0.70509
  Epoch 012 - train 0.59763 | val 0.97968
  Classification -> best τ=0.505 (val F1=0.2341)
  Directional -> Accuracy: 0.5652, MCC: 0.1125, F1: 0.6875

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60743 | val 1.04598
  Epoch 012 - train 0.59608 | val 1.20323
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61291 | val 1.45763
  Epoch 012 - train 0.60604 | val 2.34155
  Classification -> best τ=0.515 (val F1=0.0861)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61306 | val 0.89495
  Epoch 014 - train 0.55123 | val 1.73730
  Classification -> best τ=0.440 (val F1=0.2946)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63499 | val 0.76386
  Epoch 015 - train 0.62112 | val 0.96536
  Classification -> best τ=0.515 (val F1=0.3219)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58184 | val 0.69947
  Epoch 018 - train 0.49414 | val 0.99492
  Classification -> best τ=0.520 (val F1=0.2727)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64085 | val 0.88949
  Epoch 011 - train 0.63861 | val 1.09153
  Classification -> best τ=0.620 (val F1=0.0835)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61733 | val 0.68627
  Epoch 013 - train 0.58471 | val 0.73123
  Classification -> best τ=0.545 (val F1=0.2952)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63480 | val 0.71338
  Epoch 011 - train 0.58627 | val 0.70146
  Classification -> best τ=0.395 (val F1=0.1121)
  Directional -> Accuracy: 0.4308, MCC: -0.2304, F1: 0.6022

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57786 | val 0.77637
  Epoch 015 - train 0.52568 | val 0.77868
  Classification -> best τ=0.455 (val F1=0.4688)
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49669 | val 0.83035
  Epoch 011 - train 0.50521 | val 1.05821
  Classification -> best τ=0.565 (val F1=0.2726)
  Directional -> Accuracy: 0.6000, MCC: 0.2388, F1: 0.6087

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61493 | val 0.69729
  Epoch 011 - train 0.60490 | val 0.70911
  Classification -> best τ=0.645 (val F1=0.1936)
  Directional -> Accuracy: 0.6190, MCC: 0.1978, F1: 0.7037

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65118 | val 0.72877
  Epoch 013 - train 0.57100 | val 0.79365
  Classification -> best τ=0.425 (val F1=0.2829)
  Directional -> Accuracy: 0.5714, MCC: 0.1206, F1: 0.6364

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69164 | val 0.85092
  Epoch 011 - train 0.71761 | val 0.73529
  Classification -> best τ=0.460 (val F1=0.4109)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60002 | val 1.12427
  Epoch 012 - train 0.58977 | val 0.81612
  Classification -> best τ=0.615 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57399 | val 1.16913
  Epoch 012 - train 0.55032 | val 1.32979
  Classification -> best τ=0.540 (val F1=0.1425)
  Directional -> Accuracy: 0.4524, MCC: -0.2343, F1: 0.6102

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56722 | val 0.78617
  Epoch 013 - train 0.50180 | val 0.81788
  Classification -> best τ=0.430 (val F1=0.4120)
  Directional -> Accuracy: 0.4286, MCC: -0.1811, F1: 0.5333

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63356 | val 0.68975
  Epoch 017 - train 0.58059 | val 0.94834
  Classification -> best τ=0.360 (val F1=0.3911)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66126 | val 0.99002
  Epoch 015 - train 0.51744 | val 1.41027
  Classification -> best τ=0.435 (val F1=0.3774)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62721 | val 0.86844
  Epoch 011 - train 0.62524 | val 0.90782
  Classification -> best τ=0.420 (val F1=0.2292)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72786 | val 1.67203
  Epoch 012 - train 0.56176 | val 1.08331
  Classification -> best τ=0.485 (val F1=0.4099)
  Directional -> Accuracy: 0.7381, MCC: 0.4835, F1: 0.7317

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61531 | val 0.81375
  Epoch 011 - train 0.60438 | val 0.71025
  Classification -> best τ=0.520 (val F1=0.2742)
  Directional -> Accuracy: 0.5714, MCC: 0.1309, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56397 | val 0.73613
  Epoch 011 - train 0.51980 | val 0.83119
  Classification -> best τ=0.410 (val F1=0.2800)
  Directional -> Accuracy: 0.5870, MCC: 0.1074, F1: 0.6780

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58426 | val 0.71196
  Epoch 019 - train 0.56876 | val 0.74037
  Classification -> best τ=0.560 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58664 | val 0.73935
  Epoch 020 - train 0.44194 | val 1.21818
  Epoch 023 - train 0.49483 | val 1.51260
  Classification -> best τ=0.460 (val F1=0.5541)
  Directional -> Accuracy: 0.5811, MCC: 0.2362, F1: 0.6804

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55947 | val 0.84214
  Epoch 013 - train 0.49965 | val 0.96405
  Classification -> best τ=0.515 (val F1=0.2236)
  Directional -> Accuracy: 0.5111, MCC: 0.0069, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60801 | val 0.57455
  Epoch 020 - train 0.47329 | val 0.48729
  Epoch 029 - train 0.33040 | val 0.59549
  Classification -> best τ=0.340 (val F1=0.6124)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61733 | val 0.61543
  Epoch 020 - train 0.48612 | val 0.47943
  Epoch 030 - train 0.40130 | val 0.59821
  Classification -> best τ=0.445 (val F1=0.5514)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57594 | val 0.80708
  Epoch 011 - train 0.55279 | val 0.84909
  Classification -> best τ=0.625 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55103 | val 2.20398
  Epoch 012 - train 0.57241 | val 2.55451
  Classification -> best τ=0.545 (val F1=0.3401)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60716 | val 1.39830
  Epoch 011 - train 0.58445 | val 1.85996
  Classification -> best τ=0.500 (val F1=0.1801)
  Directional -> Accuracy: 0.6038, MCC: 0.2069, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66462 | val 0.83815
  Epoch 011 - train 0.67231 | val 0.79400
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59388 | val 0.68938

[I 2026-02-20 05:43:14,919] Trial 197 finished with value: 0.27170827874450637 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008748539369441486, 'weight_decay': 2.7155812278974117e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9697805675602416, 'early_stopping_min_delta': 0.00886085647169313}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.60147 | val 0.70233
  Classification -> best τ=0.495 (val F1=0.2810)
  Directional -> Accuracy: 0.5667, MCC: 0.1565, F1: 0.6286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27170827874450637
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61251 | val 0.68494
  Epoch 011 - train 0.61634 | val 0.72262
  Classification -> best τ=0.375 (val F1=0.0933)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65104 | val 0.68418
  Epoch 017 - train 0.58774 | val 0.76744
  Classification -> best τ=0.410 (val F1=0.2798)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60484 | val 1.05442
  Epoch 011 - train 0.60955 | val 0.89162
  Classification -> best τ=0.630 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66564 | val 0.70371
  Epoch 013 - train 0.63420 | val 0.72065
  Classification -> best τ=0.530 (val F1=0.2601)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55445 | val 1.00533
  Epoch 015 - train 0.54489 | val 1.14232
  Classification -> best τ=0.680 (val F1=0.4947)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62579 | val 0.70428
  Epoch 014 - train 0.55600 | val 0.77650
  Classification -> best τ=0.465 (val F1=0.0635)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.1667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67011 | val 0.70703
  Epoch 017 - train 0.61175 | val 1.01793
  Classification -> best τ=0.655 (val F1=0.2361)
  Directional -> Accuracy: 0.5441, MCC: 0.0418, F1: 0.4151

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52112 | val 0.65009
  Epoch 012 - train 0.50888 | val 0.81034
  Classification -> best τ=0.335 (val F1=0.3158)
  Directional -> Accuracy: 0.4048, MCC: -0.1925, F1: 0.3590

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60498 | val 1.03581
  Epoch 012 - train 0.57904 | val 0.72988
  Classification -> best τ=0.395 (val F1=0.4022)
  Directional -> Accuracy: 0.6250, MCC: 0.2492, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62388 | val 0.71385
  Epoch 012 - train 0.57174 | val 0.76559
  Classification -> best τ=0.610 (val F1=0.1508)
  Directional -> Accuracy: 0.5507, MCC: 0.0650, F1: 0.4364

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68902 | val 0.83511
  Epoch 011 - train 0.69264 | val 0.93546
  Classification -> best τ=0.470 (val F1=0.2074)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57493 | val 1.40118
  Epoch 011 - train 0.54692 | val 2.20251
  Classification -> best τ=0.580 (val F1=0.2741)
  Directional -> Accuracy: 0.7018, MCC: 0.4045, F1: 0.7213

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58502 | val 1.05868
  Epoch 012 - train 0.55988 | val 1.42025
  Classification -> best τ=0.720 (val F1=0.1475)
  Directional -> Accuracy: 0.5714, MCC: 0.1070, F1: 0.3077

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64855 | val 0.65754
  Epoch 011 - train 0.64715 | val 0.66664
  Classification -> best τ=0.335 (val F1=0.3859)
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66519 | val 0.80628
  Epoch 013 - train 0.58130 | val 1.05626
  Classification -> best τ=0.545 (val F1=0.2837)
  Directional -> Accuracy: 0.5686, MCC: 0.2491, F1: 0.6562

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63821 | val 0.99502
  Epoch 012 - train 0.63126 | val 0.84786
  Classification -> best τ=0.625 (val F1=0.2693)
  Directional -> Accuracy: 0.5507, MCC: 0.0948, F1: 0.5867

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59909 | val 1.96097
  Epoch 011 - train 0.56695 | val 2.05719
  Classification -> best τ=0.450 (val F1=0.0811)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59277 | val 1.42244
  Epoch 013 - train 0.64879 | val 1.64069
  Classification -> best τ=0.460 (val F1=0.1243)
  Directional -> Accuracy: 0.5600, MCC: 0.1667, F1: 0.5600

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59868 | val 0.94119
  Epoch 013 - train 0.60630 | val 1.15736
  Classification -> best τ=0.555 (val F1=0.2932)
  Directional -> Accuracy: 0.4688, MCC: 0.1308, F1: 0.1905

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67516 | val 0.68058
  Epoch 016 - train 0.64230 | val 0.74320
  Classification -> best τ=0.385 (val F1=0.3045)
  Directional -> Accuracy: 0.5676, MCC: 0.1913, F1: 0.5000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60343 | val 0.69491
  Epoch 018 - train 0.48093 | val 0.94981
  Classification -> best τ=0.475 (val F1=0.3020)
  Directional -> Accuracy: 0.5532, MCC: 0.0446, F1: 0.6441

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63482 | val 0.91067
  Epoch 012 - train 0.62709 | val 1.17806
  Classification -> best τ=0.570 (val F1=0.1925)
  Directional -> Accuracy: 0.4615, MCC: -0.0769, F1: 0.3396

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62247 | val 0.78726
  Epoch 016 - train 0.57559 | val 0.79482
  Classification -> best τ=0.515 (val F1=0.2981)
  Directional -> Accuracy: 0.5614, MCC: 0.1304, F1: 0.5763

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62351 | val 0.75276
  Epoch 011 - train 0.62349 | val 0.72933
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56430 | val 0.83009
  Epoch 014 - train 0.52386 | val 1.33688
  Classification -> best τ=0.400 (val F1=0.5376)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57605 | val 1.12292
  Epoch 011 - train 0.51496 | val 1.41420
  Classification -> best τ=0.505 (val F1=0.0385)
  Directional -> Accuracy: 0.5333, MCC: -0.1844, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58889 | val 0.68036
  Epoch 011 - train 0.60706 | val 0.68968
  Classification -> best τ=0.605 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68001 | val 0.68823
  Epoch 014 - train 0.64775 | val 0.74109
  Classification -> best τ=0.500 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58830 | val 1.02578
  Epoch 013 - train 0.61012 | val 1.78977
  Classification -> best τ=0.520 (val F1=0.3518)
  Directional -> Accuracy: 0.6250, MCC: 0.2335, F1: 0.6809

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61551 | val 1.09048
  Epoch 012 - train 0.52095 | val 0.94349
  Classification -> best τ=0.450 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60230 | val 0.82353
  Epoch 012 - train 0.63716 | val 1.08525
  Classification -> best τ=0.500 (val F1=0.2357)
  Directional -> Accuracy: 0.6190, MCC: 0.2567, F1: 0.7333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57929 | val 0.73763
  Epoch 013 - train 0.49074 | val 1.00893
  Classification -> best τ=0.430 (val F1=0.3850)
  Directional -> Accuracy: 0.3878, MCC: -0.2291, F1: 0.4231

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60315 | val 0.72212
  Epoch 016 - train 0.59603 | val 1.26194
  Classification -> best τ=0.420 (val F1=0.4063)
  Directional -> Accuracy: 0.5278, MCC: 0.0828, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60124 | val 1.34761
  Epoch 012 - train 0.60170 | val 1.18397
  Classification -> best τ=0.325 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64189 | val 0.83895
  Epoch 011 - train 0.61463 | val 0.96754
  Classification -> best τ=0.515 (val F1=0.2899)
  Directional -> Accuracy: 0.5758, MCC: 0.0389, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51724 | val 0.70843
  Epoch 014 - train 0.48080 | val 0.83116
  Classification -> best τ=0.425 (val F1=0.2464)
  Directional -> Accuracy: 0.6429, MCC: 0.2821, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52406 | val 0.92092
  Epoch 012 - train 0.60402 | val 0.84364
  Classification -> best τ=0.390 (val F1=0.2725)
  Directional -> Accuracy: 0.4821, MCC: -0.0083, F1: 0.5538

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70208 | val 0.74417
  Epoch 015 - train 0.64656 | val 0.94511
  Classification -> best τ=0.495 (val F1=0.3438)
  Directional -> Accuracy: 0.4130, MCC: -0.1074, F1: 0.3721

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58971 | val 0.77223
  Epoch 011 - train 0.54245 | val 0.75290
  Classification -> best τ=0.550 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59654 | val 0.67606
  Epoch 019 - train 0.49348 | val 0.77672
  Classification -> best τ=0.305 (val F1=0.3934)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55696 | val 0.77359
  Epoch 013 - train 0.55077 | val 1.01328
  Classification -> best τ=0.495 (val F1=0.1890)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64527 | val 0.63452
  Epoch 020 - train 0.56295 | val 1.72695
  Classification -> best τ=0.295 (val F1=0.3851)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59556 | val 0.74877
  Epoch 013 - train 0.51266 | val 0.71313
  Classification -> best τ=0.540 (val F1=0.5249)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57285 | val 0.76080
  Epoch 011 - train 0.55361 | val 0.74984
  Classification -> best τ=0.660 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57383 | val 1.24881
  Epoch 011 - train 0.61754 | val 1.09734
  Classification -> best τ=0.335 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64502 | val 0.86350
  Epoch 014 - train 0.57021 | val 1.23667
  Classification -> best τ=0.440 (val F1=0.2801)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62954 | val 0.89518
  Epoch 011 - train 0.57513 | val 1.03977
  Classification -> best τ=0.510 (val F1=0.0885)
  Directional -> Accuracy: 0.5455, MCC: 0.1841, F1: 0.3243

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60166 | val 0.71815

[I 2026-02-20 05:44:12,249] Trial 198 finished with value: 0.26815065267423205 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009795490267670112, 'weight_decay': 1.9028768030795063e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0384919886741355, 'early_stopping_min_delta': 0.009260367113363047}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.57162 | val 0.69612
  Classification -> best τ=0.425 (val F1=0.2231)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26815065267423205
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60984 | val 0.69727
  Epoch 011 - train 0.57798 | val 0.70838
  Classification -> best τ=0.525 (val F1=0.1430)
  Directional -> Accuracy: 0.6053, MCC: 0.1835, F1: 0.4231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58479 | val 0.69327
  Epoch 013 - train 0.55514 | val 0.75818
  Classification -> best τ=0.460 (val F1=0.3126)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57716 | val 0.87606
  Epoch 014 - train 0.53293 | val 0.91615
  Classification -> best τ=0.540 (val F1=0.2793)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65789 | val 0.88084
  Epoch 012 - train 0.64988 | val 0.84323
  Classification -> best τ=0.445 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63588 | val 0.71975
  Epoch 014 - train 0.52452 | val 1.15936
  Classification -> best τ=0.445 (val F1=0.5175)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63809 | val 0.77719
  Epoch 011 - train 0.66573 | val 0.76423
  Classification -> best τ=0.540 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: -0.0382, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65083 | val 1.13538
  Epoch 011 - train 0.65638 | val 0.83750
  Classification -> best τ=0.430 (val F1=0.3110)
  Directional -> Accuracy: 0.4706, MCC: 0.0521, F1: 0.5385

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54891 | val 1.08584
  Epoch 012 - train 0.50396 | val 1.51496
  Classification -> best τ=0.280 (val F1=0.2100)
  Directional -> Accuracy: 0.4524, MCC: -0.1876, F1: 0.2069

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59991 | val 0.76423
  Epoch 012 - train 0.54450 | val 0.72743
  Classification -> best τ=0.435 (val F1=0.1608)
  Directional -> Accuracy: 0.6042, MCC: 0.1746, F1: 0.2963

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55079 | val 0.93283
  Epoch 012 - train 0.58839 | val 1.01253
  Classification -> best τ=0.505 (val F1=0.2301)
  Directional -> Accuracy: 0.4928, MCC: 0.0112, F1: 0.4928

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61222 | val 1.17146
  Epoch 012 - train 0.62284 | val 1.38513
  Classification -> best τ=0.495 (val F1=0.4196)
  Directional -> Accuracy: 0.6735, MCC: 0.3783, F1: 0.4667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58853 | val 0.81425
  Epoch 011 - train 0.62164 | val 0.80357
  Classification -> best τ=0.595 (val F1=0.2741)
  Directional -> Accuracy: 0.6842, MCC: 0.3894, F1: 0.7353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57906 | val 1.15031
  Epoch 012 - train 0.55963 | val 1.33600
  Classification -> best τ=0.475 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62468 | val 0.64673
  Epoch 020 - train 0.50086 | val 0.75486
  Epoch 021 - train 0.50342 | val 0.71398
  Classification -> best τ=0.320 (val F1=0.2902)
  Directional -> Accuracy: 0.5333, MCC: 0.0727, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59233 | val 0.72111
  Epoch 013 - train 0.60911 | val 0.72313
  Classification -> best τ=0.485 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63795 | val 0.77687
  Epoch 013 - train 0.56687 | val 0.85641
  Classification -> best τ=0.540 (val F1=0.2795)
  Directional -> Accuracy: 0.5797, MCC: 0.1576, F1: 0.7010

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61521 | val 1.13994
  Epoch 011 - train 0.61286 | val 1.12783
  Classification -> best τ=0.620 (val F1=0.1291)
  Directional -> Accuracy: 0.3621, MCC: -0.1694, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61062 | val 1.06302
  Epoch 012 - train 0.55189 | val 1.13577
  Classification -> best τ=0.665 (val F1=0.0357)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59839 | val 0.84765
  Epoch 013 - train 0.57764 | val 1.31498
  Classification -> best τ=0.485 (val F1=0.2752)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64128 | val 0.70929
  Epoch 012 - train 0.64238 | val 0.74071
  Classification -> best τ=0.570 (val F1=0.2989)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60566 | val 0.68811
  Epoch 020 - train 0.49084 | val 0.80412
  Epoch 024 - train 0.36246 | val 0.87869
  Classification -> best τ=0.325 (val F1=0.3678)
  Directional -> Accuracy: 0.5745, MCC: 0.2030, F1: 0.5833

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68307 | val 0.87898
  Epoch 011 - train 0.68948 | val 0.81962
  Classification -> best τ=0.505 (val F1=0.3606)
  Directional -> Accuracy: 0.6000, MCC: 0.2139, F1: 0.5357

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63821 | val 0.72978
  Epoch 014 - train 0.57530 | val 0.89515
  Classification -> best τ=0.740 (val F1=0.3144)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61421 | val 1.07622
  Epoch 012 - train 0.63060 | val 1.35666
  Classification -> best τ=0.465 (val F1=0.0817)
  Directional -> Accuracy: 0.4923, MCC: 0.0154, F1: 0.6024

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58692 | val 0.66309
  Epoch 014 - train 0.54310 | val 0.83128
  Classification -> best τ=0.555 (val F1=0.4914)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60313 | val 1.00361
  Epoch 013 - train 0.52626 | val 0.92178
  Classification -> best τ=0.495 (val F1=0.2935)
  Directional -> Accuracy: 0.4444, MCC: 0.0159, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60330 | val 0.69704
  Epoch 011 - train 0.61108 | val 0.69641
  Classification -> best τ=0.565 (val F1=0.1667)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63728 | val 0.78037
  Epoch 012 - train 0.61035 | val 0.84227
  Classification -> best τ=0.365 (val F1=0.2871)
  Directional -> Accuracy: 0.5893, MCC: 0.1659, F1: 0.6349

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59612 | val 0.68930
  Epoch 019 - train 0.48404 | val 3.00270
  Classification -> best τ=0.475 (val F1=0.3296)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61757 | val 0.92929
  Epoch 012 - train 0.56883 | val 1.18878
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63331 | val 0.83417
  Epoch 016 - train 0.52884 | val 1.60756
  Classification -> best τ=0.430 (val F1=0.3385)
  Directional -> Accuracy: 0.5714, MCC: 0.1158, F1: 0.6538

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57878 | val 0.91617
  Epoch 013 - train 0.55642 | val 0.88185
  Classification -> best τ=0.470 (val F1=0.2599)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65770 | val 0.64520
  Epoch 020 - train 0.58957 | val 0.77569
  Classification -> best τ=0.380 (val F1=0.3681)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58673 | val 1.18803
  Epoch 012 - train 0.55451 | val 1.38477
  Classification -> best τ=0.640 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64808 | val 0.74063
  Epoch 015 - train 0.64063 | val 0.80938
  Classification -> best τ=0.145 (val F1=0.3342)
  Directional -> Accuracy: 0.6364, MCC: 0.2358, F1: 0.7447

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51261 | val 0.80450
  Epoch 011 - train 0.62099 | val 0.97073
  Classification -> best τ=0.520 (val F1=0.2658)
  Directional -> Accuracy: 0.6667, MCC: 0.3364, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61577 | val 0.71204
  Epoch 011 - train 0.57744 | val 0.69356
  Classification -> best τ=0.530 (val F1=0.1913)
  Directional -> Accuracy: 0.5714, MCC: 0.1281, F1: 0.4783

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49306 | val 1.04261
  Epoch 011 - train 0.50178 | val 1.05975
  Classification -> best τ=0.420 (val F1=0.2118)
  Directional -> Accuracy: 0.5000, MCC: -0.2800, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53240 | val 0.69513
  Epoch 018 - train 0.49017 | val 0.73483
  Classification -> best τ=0.385 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64519 | val 0.64570
  Epoch 017 - train 0.59543 | val 0.77595
  Classification -> best τ=0.510 (val F1=0.3294)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63295 | val 0.79811
  Epoch 013 - train 0.57828 | val 0.75093
  Classification -> best τ=0.545 (val F1=0.3500)
  Directional -> Accuracy: 0.5111, MCC: 0.0199, F1: 0.5417

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63467 | val 0.58308
  Epoch 020 - train 0.44658 | val 0.74124
  Classification -> best τ=0.345 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57846 | val 0.79103
  Epoch 012 - train 0.55149 | val 0.62793
  Classification -> best τ=0.565 (val F1=0.5689)
  Directional -> Accuracy: 0.5625, MCC: 0.1627, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58851 | val 0.70308
  Epoch 011 - train 0.57279 | val 0.72402
  Classification -> best τ=0.565 (val F1=0.2036)
  Directional -> Accuracy: 0.5091, MCC: 0.1617, F1: 0.2286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60627 | val 2.28367
  Epoch 011 - train 0.56075 | val 2.34622
  Classification -> best τ=0.665 (val F1=0.2281)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62631 | val 0.79361
  Epoch 014 - train 0.62154 | val 0.91178
  Classification -> best τ=0.515 (val F1=0.1687)
  Directional -> Accuracy: 0.4717, MCC: -0.0587, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61827 | val 0.76280
  Epoch 011 - train 0.60975 | val 0.82651
  Classification -> best τ=0.575 (val F1=0.0322)
  Directional -> Accuracy: 0.4727, MCC: -0.0106, F1: 0.0645

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59454 | val 0.90957
  Epoch 012 - train 0.60709 | val 0.70525

[I 2026-02-20 05:45:11,372] Trial 199 finished with value: 0.27810912291017403 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007542007881421585, 'weight_decay': 3.3630358997393353e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0718062128105035, 'early_stopping_min_delta': 0.00898918206502215}. Best is trial 180 with value: 0.30107335520239253.

  Classification -> best τ=0.455 (val F1=0.2810)
  Directional -> Accuracy: 0.6000, MCC: 0.2086, F1: 0.6250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27810912291017403
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59413 | val 0.78588
  Epoch 012 - train 0.62405 | val 0.73945
  Classification -> best τ=0.475 (val F1=0.1635)
  Directional -> Accuracy: 0.5526, MCC: 0.1771, F1: 0.6222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56634 | val 0.68978
  Epoch 012 - train 0.58274 | val 0.69968
  Classification -> best τ=0.375 (val F1=0.3149)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61862 | val 0.67852
  Epoch 020 - train 0.46025 | val 1.09504
  Epoch 021 - train 0.53405 | val 0.83192
  Classification -> best τ=0.775 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67015 | val 0.89639
  Epoch 012 - train 0.64736 | val 0.96291
  Classification -> best τ=0.390 (val F1=0.2920)
  Directional -> Accuracy: 0.5541, MCC: 0.1180, F1: 0.5479

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60421 | val 0.79612
  Epoch 013 - train 0.53582 | val 0.86508
  Classification -> best τ=0.425 (val F1=0.4753)
  Directional -> Accuracy: 0.7800, MCC: 0.5604, F1: 0.7843

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63444 | val 0.87280
  Epoch 011 - train 0.61823 | val 0.89017
  Classification -> best τ=0.555 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64770 | val 0.81095
  Epoch 011 - train 0.65172 | val 0.78810
  Classification -> best τ=0.435 (val F1=0.2937)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51978 | val 1.03011
  Epoch 016 - train 0.53686 | val 1.23010
  Classification -> best τ=0.425 (val F1=0.0668)
  Directional -> Accuracy: 0.5952, MCC: 0.1407, F1: 0.4138

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58392 | val 0.71080
  Epoch 013 - train 0.54003 | val 0.77585
  Classification -> best τ=0.505 (val F1=0.3433)
  Directional -> Accuracy: 0.6667, MCC: 0.3495, F1: 0.4286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60629 | val 1.05434
  Epoch 011 - train 0.57051 | val 0.93428
  Classification -> best τ=0.490 (val F1=0.1983)
  Directional -> Accuracy: 0.5362, MCC: -0.0099, F1: 0.3043

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61646 | val 0.70162
  Epoch 011 - train 0.63121 | val 1.27321
  Classification -> best τ=0.455 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55181 | val 1.34220
  Epoch 011 - train 0.48557 | val 1.76661
  Classification -> best τ=0.545 (val F1=0.1181)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59768 | val 1.36711
  Epoch 012 - train 0.53090 | val 1.67763
  Classification -> best τ=0.500 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58922 | val 0.76812
  Epoch 011 - train 0.60804 | val 0.78958
  Classification -> best τ=0.455 (val F1=0.3919)
  Directional -> Accuracy: 0.5333, MCC: 0.0727, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59533 | val 0.71072
  Epoch 013 - train 0.56064 | val 0.86394
  Classification -> best τ=0.560 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62070 | val 0.79297
  Epoch 012 - train 0.59801 | val 0.89717
  Classification -> best τ=0.540 (val F1=0.2693)
  Directional -> Accuracy: 0.5362, MCC: 0.0716, F1: 0.5556

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62826 | val 0.93761
  Epoch 011 - train 0.61231 | val 1.03152
  Classification -> best τ=0.475 (val F1=0.2787)
  Directional -> Accuracy: 0.5000, MCC: -0.1645, F1: 0.6420

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60116 | val 0.83517
  Epoch 012 - train 0.63857 | val 0.96223
  Classification -> best τ=0.505 (val F1=0.1786)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60585 | val 0.83212
  Epoch 014 - train 0.57031 | val 0.95453
  Classification -> best τ=0.400 (val F1=0.3140)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63499 | val 0.65920
  Epoch 015 - train 0.65226 | val 0.73375
  Classification -> best τ=0.435 (val F1=0.3194)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60524 | val 0.68723
  Epoch 012 - train 0.56509 | val 0.70889
  Classification -> best τ=0.540 (val F1=0.2064)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64138 | val 0.84971
  Epoch 011 - train 0.62428 | val 0.71681
  Classification -> best τ=0.515 (val F1=0.1350)
  Directional -> Accuracy: 0.5231, MCC: 0.1014, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60665 | val 0.74827
  Epoch 013 - train 0.59727 | val 0.77188
  Classification -> best τ=0.420 (val F1=0.2027)
  Directional -> Accuracy: 0.5439, MCC: 0.0579, F1: 0.6176

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63996 | val 0.77996
  Epoch 013 - train 0.59754 | val 0.77251
  Classification -> best τ=0.400 (val F1=0.1599)
  Directional -> Accuracy: 0.4154, MCC: -0.1687, F1: 0.4062

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58801 | val 0.74002
  Epoch 018 - train 0.43068 | val 0.81640
  Classification -> best τ=0.565 (val F1=0.4399)
  Directional -> Accuracy: 0.4182, MCC: -0.1372, F1: 0.2727

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61426 | val 0.88570
  Epoch 012 - train 0.55573 | val 1.16964
  Classification -> best τ=0.520 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60348 | val 0.70001
  Epoch 011 - train 0.60266 | val 0.71634
  Classification -> best τ=0.585 (val F1=0.1217)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62870 | val 0.85437
  Epoch 011 - train 0.59279 | val 0.87185
  Classification -> best τ=0.510 (val F1=0.0629)
  Directional -> Accuracy: 0.5179, MCC: 0.1037, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57259 | val 0.70054
  Epoch 020 - train 0.36413 | val 1.03037
  Epoch 021 - train 0.39034 | val 0.97901
  Classification -> best τ=0.460 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65950 | val 0.92809
  Epoch 012 - train 0.57435 | val 0.84331
  Classification -> best τ=0.660 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0793, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57898 | val 1.70419
  Epoch 013 - train 0.52855 | val 1.64629
  Classification -> best τ=0.450 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54869 | val 0.72580
  Epoch 015 - train 0.46297 | val 1.33987
  Classification -> best τ=0.660 (val F1=0.3917)
  Directional -> Accuracy: 0.5306, MCC: 0.0349, F1: 0.6349

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62758 | val 0.84326
  Epoch 013 - train 0.60281 | val 0.86891
  Classification -> best τ=0.365 (val F1=0.3366)
  Directional -> Accuracy: 0.5417, MCC: 0.1155, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60433 | val 0.96314
  Epoch 011 - train 0.60374 | val 1.14612
  Classification -> best τ=0.490 (val F1=0.1874)
  Directional -> Accuracy: 0.5116, MCC: 0.0452, F1: 0.6182

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66732 | val 0.78495
  Epoch 012 - train 0.65899 | val 0.73835
  Classification -> best τ=0.330 (val F1=0.3280)
  Directional -> Accuracy: 0.6061, MCC: 0.1545, F1: 0.7111

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55767 | val 1.56105
  Epoch 013 - train 0.52478 | val 1.86564
  Classification -> best τ=0.370 (val F1=0.3001)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61264 | val 0.83721
  Epoch 011 - train 0.57096 | val 0.77926
  Classification -> best τ=0.360 (val F1=0.2530)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46900 | val 1.02867
  Epoch 011 - train 0.49824 | val 1.13778
  Classification -> best τ=0.480 (val F1=0.2504)
  Directional -> Accuracy: 0.4348, MCC: -0.1641, F1: 0.5185

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61335 | val 0.67792
  Epoch 016 - train 0.53168 | val 0.75773
  Classification -> best τ=0.495 (val F1=0.3161)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60365 | val 0.67562
  Epoch 013 - train 0.57268 | val 0.76139
  Classification -> best τ=0.370 (val F1=0.4293)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53980 | val 0.87845
  Epoch 012 - train 0.50441 | val 0.98983
  Classification -> best τ=0.520 (val F1=0.4080)
  Directional -> Accuracy: 0.5111, MCC: 0.0238, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59936 | val 0.66270
  Epoch 020 - train 0.55466 | val 0.67467
  Epoch 030 - train 0.46101 | val 0.66152
  Epoch 039 - train 0.28783 | val 0.80112
  Classification -> best τ=0.170 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63939 | val 0.71810
  Epoch 016 - train 0.58900 | val 0.84550
  Classification -> best τ=0.590 (val F1=0.6110)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62727 | val 0.78796
  Epoch 011 - train 0.61254 | val 0.73760
  Classification -> best τ=0.595 (val F1=0.2036)
  Directional -> Accuracy: 0.4182, MCC: -0.1377, F1: 0.2000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57955 | val 2.06415
  Epoch 011 - train 0.57114 | val 1.69058
  Classification -> best τ=0.365 (val F1=0.2632)
  Directional -> Accuracy: 0.5000, MCC: 0.0515, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61580 | val 0.93956
  Epoch 014 - train 0.60725 | val 1.25848
  Classification -> best τ=0.625 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1729, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61157 | val 0.90867
  Epoch 011 - train 0.59786 | val 0.89120
  Classification -> best τ=0.405 (val F1=0.2452)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60865 | val 0.73675

[I 2026-02-20 05:46:07,272] Trial 200 finished with value: 0.2736234945198351 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007249552017912134, 'weight_decay': 3.4290987563378453e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.078267820240218, 'early_stopping_min_delta': 0.00905740461937386}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.58779 | val 0.72860
  Classification -> best τ=0.415 (val F1=0.1020)
  Directional -> Accuracy: 0.6333, MCC: 0.3175, F1: 0.4500

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2736234945198351
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63776 | val 0.71981
  Epoch 019 - train 0.56873 | val 1.01040
  Classification -> best τ=0.520 (val F1=0.2510)
  Directional -> Accuracy: 0.6184, MCC: 0.2168, F1: 0.5246

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60441 | val 0.67614
  Epoch 012 - train 0.56260 | val 0.67558
  Classification -> best τ=0.395 (val F1=0.2428)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62794 | val 0.71484
  Epoch 012 - train 0.56311 | val 0.75849
  Classification -> best τ=0.550 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63077 | val 1.07573
  Epoch 012 - train 0.63777 | val 1.65871
  Classification -> best τ=0.405 (val F1=0.0520)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55805 | val 0.74828
  Epoch 013 - train 0.55044 | val 1.02697
  Classification -> best τ=0.480 (val F1=0.4414)
  Directional -> Accuracy: 0.5800, MCC: 0.2044, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59828 | val 0.70040
  Epoch 012 - train 0.57167 | val 0.70243
  Classification -> best τ=0.575 (val F1=0.1537)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.6269

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63476 | val 0.83371
  Epoch 011 - train 0.64173 | val 0.96354
  Classification -> best τ=0.480 (val F1=0.1251)
  Directional -> Accuracy: 0.4412, MCC: -0.0305, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53569 | val 0.87405
  Epoch 014 - train 0.47006 | val 0.93195
  Classification -> best τ=0.365 (val F1=0.1147)
  Directional -> Accuracy: 0.3571, MCC: -0.2582, F1: 0.4906

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56590 | val 0.80139
  Epoch 013 - train 0.50775 | val 0.90667
  Classification -> best τ=0.575 (val F1=0.3433)
  Directional -> Accuracy: 0.6042, MCC: 0.1697, F1: 0.4242

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56709 | val 0.89311
  Epoch 011 - train 0.60727 | val 1.10795
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62085 | val 0.73908
  Epoch 015 - train 0.61100 | val 1.11867
  Classification -> best τ=0.590 (val F1=0.2495)
  Directional -> Accuracy: 0.6327, MCC: 0.2673, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52237 | val 1.43371
  Epoch 013 - train 0.47966 | val 1.79466
  Classification -> best τ=0.595 (val F1=0.2741)
  Directional -> Accuracy: 0.5614, MCC: 0.1452, F1: 0.4444

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56728 | val 0.95542
  Epoch 013 - train 0.56797 | val 1.31128
  Classification -> best τ=0.410 (val F1=0.2438)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61034 | val 0.66056
  Epoch 011 - train 0.57885 | val 0.69760
  Classification -> best τ=0.385 (val F1=0.3145)
  Directional -> Accuracy: 0.5333, MCC: 0.0707, F1: 0.6000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55408 | val 0.79474
  Epoch 015 - train 0.51022 | val 1.23739
  Classification -> best τ=0.500 (val F1=0.2141)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61656 | val 0.77165
  Epoch 012 - train 0.55953 | val 0.80982
  Classification -> best τ=0.430 (val F1=0.1376)
  Directional -> Accuracy: 0.4928, MCC: -0.0874, F1: 0.6316

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58622 | val 1.14747
  Epoch 011 - train 0.61701 | val 1.31171
  Classification -> best τ=0.535 (val F1=0.0849)
  Directional -> Accuracy: 0.4310, MCC: -0.2692, F1: 0.5714

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58185 | val 1.87496
  Epoch 012 - train 0.61545 | val 2.06514
  Classification -> best τ=0.490 (val F1=0.2253)
  Directional -> Accuracy: 0.5067, MCC: 0.0328, F1: 0.5316

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64190 | val 0.93789
  Epoch 014 - train 0.61318 | val 0.88861
  Classification -> best τ=0.360 (val F1=0.3948)
  Directional -> Accuracy: 0.5000, MCC: 0.0579, F1: 0.4483

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63523 | val 0.73298
  Epoch 012 - train 0.62202 | val 0.74870
  Classification -> best τ=0.555 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60128 | val 0.69442
  Epoch 012 - train 0.56848 | val 0.75737
  Classification -> best τ=0.510 (val F1=0.2559)
  Directional -> Accuracy: 0.5957, MCC: 0.0392, F1: 0.7246

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62410 | val 1.21447
  Epoch 011 - train 0.61064 | val 0.94828
  Classification -> best τ=0.365 (val F1=0.2371)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58334 | val 0.75756
  Epoch 013 - train 0.57067 | val 0.90212
  Classification -> best τ=0.560 (val F1=0.3109)
  Directional -> Accuracy: 0.4737, MCC: -0.0509, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67231 | val 0.77630
  Epoch 012 - train 0.63405 | val 0.97953
  Classification -> best τ=0.470 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0971, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60465 | val 0.61612
  Epoch 020 - train 0.45275 | val 0.84019
  Epoch 021 - train 0.45619 | val 0.97748
  Classification -> best τ=0.565 (val F1=0.5644)
  Directional -> Accuracy: 0.4909, MCC: 0.0516, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56153 | val 0.90979
  Epoch 011 - train 0.58657 | val 1.46112
  Classification -> best τ=0.450 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61609 | val 0.68969
  Epoch 012 - train 0.58113 | val 0.77817
  Classification -> best τ=0.630 (val F1=0.1291)
  Directional -> Accuracy: 0.5238, MCC: 0.0142, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64137 | val 0.95686
  Epoch 012 - train 0.59585 | val 0.91864
  Classification -> best τ=0.305 (val F1=0.2892)
  Directional -> Accuracy: 0.6250, MCC: 0.2281, F1: 0.7123

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59917 | val 0.71337
  Epoch 011 - train 0.57863 | val 0.73493
  Classification -> best τ=0.480 (val F1=0.3477)
  Directional -> Accuracy: 0.4750, MCC: -0.0453, F1: 0.4878

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57701 | val 0.90824
  Epoch 012 - train 0.60107 | val 1.44993
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56044 | val 0.98982
  Epoch 019 - train 0.45042 | val 1.07186
  Classification -> best τ=0.460 (val F1=0.3034)
  Directional -> Accuracy: 0.5000, MCC: 0.0588, F1: 0.3636

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57769 | val 0.74445
  Epoch 016 - train 0.42029 | val 1.15039
  Classification -> best τ=0.565 (val F1=0.4342)
  Directional -> Accuracy: 0.5102, MCC: -0.1358, F1: 0.6757

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60645 | val 1.08620
  Epoch 017 - train 0.56768 | val 1.41616
  Classification -> best τ=0.435 (val F1=0.3681)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61127 | val 0.73682
  Epoch 012 - train 0.57740 | val 0.83365
  Classification -> best τ=0.485 (val F1=0.3158)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66692 | val 0.86351
  Epoch 012 - train 0.62606 | val 1.09271
  Classification -> best τ=0.465 (val F1=0.3091)
  Directional -> Accuracy: 0.5606, MCC: -0.1065, F1: 0.7184

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55093 | val 0.95498
  Epoch 011 - train 0.55517 | val 1.23215
  Classification -> best τ=0.470 (val F1=0.2439)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51295 | val 0.80612
  Epoch 014 - train 0.54600 | val 0.97025
  Classification -> best τ=0.440 (val F1=0.2530)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57061 | val 1.04189
  Epoch 014 - train 0.47424 | val 1.44654
  Classification -> best τ=0.400 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59105 | val 0.81742
  Epoch 015 - train 0.54495 | val 0.76106
  Classification -> best τ=0.490 (val F1=0.3006)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60583 | val 0.71167
  Epoch 017 - train 0.53380 | val 0.87555
  Classification -> best τ=0.485 (val F1=0.3548)
  Directional -> Accuracy: 0.5270, MCC: 0.1140, F1: 0.6535

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61719 | val 0.83104
  Epoch 012 - train 0.56697 | val 0.76889
  Classification -> best τ=0.420 (val F1=0.3371)
  Directional -> Accuracy: 0.4889, MCC: -0.0314, F1: 0.5660

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63180 | val 0.67509
  Epoch 019 - train 0.52159 | val 0.68475
  Classification -> best τ=0.510 (val F1=0.5593)
  Directional -> Accuracy: 0.5952, MCC: 0.1407, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62330 | val 0.61392
  Epoch 014 - train 0.59618 | val 0.61621
  Classification -> best τ=0.635 (val F1=0.5557)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59701 | val 0.69427
  Epoch 011 - train 0.59101 | val 0.69335
  Classification -> best τ=0.520 (val F1=0.2291)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60073 | val 1.58228
  Epoch 011 - train 0.57474 | val 1.25735
  Classification -> best τ=0.465 (val F1=0.2311)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61442 | val 1.21115
  Epoch 011 - train 0.56890 | val 1.43092
  Classification -> best τ=0.515 (val F1=0.3328)
  Directional -> Accuracy: 0.4528, MCC: -0.1599, F1: 0.6027

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63513 | val 0.81591
  Epoch 012 - train 0.60848 | val 0.80345
  Classification -> best τ=0.550 (val F1=0.2228)
  Directional -> Accuracy: 0.4000, MCC: -0.2527, F1: 0.0571

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61932 | val 0.68078

[I 2026-02-20 05:47:08,116] Trial 201 finished with value: 0.2762100467998647 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00827971014829871, 'weight_decay': 2.8358793538644204e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9960119380643786, 'early_stopping_min_delta': 0.008632208767259971}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.53831 | val 0.86185
  Classification -> best τ=0.460 (val F1=0.2332)
  Directional -> Accuracy: 0.6000, MCC: 0.2045, F1: 0.6129

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2762100467998647
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61026 | val 0.73322
  Epoch 012 - train 0.57354 | val 0.87311
  Classification -> best τ=0.460 (val F1=0.2082)
  Directional -> Accuracy: 0.6447, MCC: 0.2940, F1: 0.6301

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58632 | val 0.67536
  Epoch 012 - train 0.56799 | val 0.69251
  Classification -> best τ=0.450 (val F1=0.2713)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60894 | val 0.76922
  Epoch 012 - train 0.58341 | val 0.88889
  Classification -> best τ=0.630 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63814 | val 0.88720
  Epoch 011 - train 0.63775 | val 1.00011
  Classification -> best τ=0.460 (val F1=0.1745)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59242 | val 0.85801
  Epoch 014 - train 0.53775 | val 1.29937
  Classification -> best τ=0.550 (val F1=0.4342)
  Directional -> Accuracy: 0.7000, MCC: 0.4223, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60518 | val 0.73426
  Epoch 011 - train 0.60081 | val 0.76360
  Classification -> best τ=0.635 (val F1=0.2208)
  Directional -> Accuracy: 0.5870, MCC: 0.1774, F1: 0.4242

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65208 | val 0.74251
  Epoch 013 - train 0.70629 | val 0.74050
  Classification -> best τ=0.465 (val F1=0.2460)
  Directional -> Accuracy: 0.3971, MCC: -0.0366, F1: 0.5591

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54216 | val 0.66436
  Epoch 013 - train 0.51928 | val 1.33166
  Classification -> best τ=0.355 (val F1=0.2263)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57489 | val 0.93029
  Epoch 017 - train 0.52997 | val 1.19427
  Classification -> best τ=0.640 (val F1=0.4025)
  Directional -> Accuracy: 0.5833, MCC: 0.1193, F1: 0.1667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57584 | val 0.73345
  Epoch 011 - train 0.60599 | val 0.72639
  Classification -> best τ=0.545 (val F1=0.0867)
  Directional -> Accuracy: 0.4348, MCC: -0.1442, F1: 0.3607

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58154 | val 0.95105
  Epoch 011 - train 0.61910 | val 0.99292
  Classification -> best τ=0.490 (val F1=0.2021)
  Directional -> Accuracy: 0.4490, MCC: -0.1091, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56173 | val 1.01850
  Epoch 013 - train 0.56739 | val 1.97849
  Classification -> best τ=0.485 (val F1=0.3108)
  Directional -> Accuracy: 0.4035, MCC: -0.1933, F1: 0.4138

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55468 | val 1.26009
  Epoch 011 - train 0.51641 | val 1.33040
  Classification -> best τ=0.420 (val F1=0.2636)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62940 | val 0.67592
  Epoch 011 - train 0.61591 | val 0.67873
  Classification -> best τ=0.490 (val F1=0.3320)
  Directional -> Accuracy: 0.5333, MCC: 0.0680, F1: 0.4815

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61705 | val 0.74247
  Epoch 011 - train 0.59735 | val 0.73624
  Classification -> best τ=0.420 (val F1=0.3219)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58211 | val 0.97920
  Epoch 013 - train 0.61405 | val 0.91797
  Classification -> best τ=0.460 (val F1=0.2616)
  Directional -> Accuracy: 0.5362, MCC: 0.0804, F1: 0.5294

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57587 | val 1.32598
  Epoch 011 - train 0.59137 | val 1.50082
  Classification -> best τ=0.635 (val F1=0.1774)
  Directional -> Accuracy: 0.3793, MCC: -0.1669, F1: 0.3333

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60740 | val 1.04627
  Epoch 012 - train 0.56883 | val 1.09287
  Classification -> best τ=0.580 (val F1=0.2004)
  Directional -> Accuracy: 0.5333, MCC: 0.1238, F1: 0.5205

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64286 | val 0.72907
  Epoch 016 - train 0.54700 | val 1.88471
  Classification -> best τ=0.335 (val F1=0.3948)
  Directional -> Accuracy: 0.4375, MCC: -0.0185, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62276 | val 0.75364
  Epoch 014 - train 0.56651 | val 0.73177
  Classification -> best τ=0.475 (val F1=0.3219)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60251 | val 0.76266
  Epoch 020 - train 0.49799 | val 0.71256
  Epoch 026 - train 0.40756 | val 0.88925
  Classification -> best τ=0.465 (val F1=0.3212)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63462 | val 0.95585
  Epoch 012 - train 0.61531 | val 1.08217
  Classification -> best τ=0.590 (val F1=0.2406)
  Directional -> Accuracy: 0.4000, MCC: -0.2010, F1: 0.3390

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59054 | val 0.81684
  Epoch 013 - train 0.58734 | val 0.95459
  Classification -> best τ=0.590 (val F1=0.3276)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68010 | val 0.89598
  Epoch 012 - train 0.63325 | val 0.75722
  Classification -> best τ=0.420 (val F1=0.0268)
  Directional -> Accuracy: 0.4615, MCC: -0.0664, F1: 0.5205

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67697 | val 0.86465
  Epoch 017 - train 0.60322 | val 0.77320
  Classification -> best τ=0.545 (val F1=0.4002)
  Directional -> Accuracy: 0.4909, MCC: 0.0516, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54768 | val 1.23300
  Epoch 011 - train 0.52810 | val 1.37984
  Classification -> best τ=0.485 (val F1=0.0777)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.2963

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57641 | val 0.72744
  Epoch 012 - train 0.59214 | val 0.74777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63906 | val 0.79706
  Epoch 011 - train 0.59058 | val 0.81815
  Classification -> best τ=0.495 (val F1=0.2478)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60594 | val 0.72858
  Epoch 016 - train 0.52501 | val 1.92544
  Classification -> best τ=0.420 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65805 | val 0.87264
  Epoch 013 - train 0.62189 | val 0.77934
  Classification -> best τ=0.605 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0754, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57894 | val 0.97118
  Epoch 011 - train 0.54525 | val 1.14524
  Classification -> best τ=0.575 (val F1=0.1286)
  Directional -> Accuracy: 0.4286, MCC: -0.1194, F1: 0.0769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62692 | val 0.85837
  Epoch 014 - train 0.56482 | val 0.87174
  Classification -> best τ=0.360 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60565 | val 0.76051
  Epoch 015 - train 0.62070 | val 0.76682
  Classification -> best τ=0.300 (val F1=0.4246)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62241 | val 1.00830
  Epoch 011 - train 0.58810 | val 1.04817
  Classification -> best τ=0.430 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62564 | val 0.80662
  Epoch 012 - train 0.56514 | val 0.89867
  Classification -> best τ=0.365 (val F1=0.2117)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52459 | val 0.93022
  Epoch 012 - train 0.53279 | val 1.37048
  Classification -> best τ=0.430 (val F1=0.3001)
  Directional -> Accuracy: 0.6905, MCC: 0.3838, F1: 0.7347

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55353 | val 0.91112
  Epoch 011 - train 0.53962 | val 0.83939
  Classification -> best τ=0.465 (val F1=0.2804)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53168 | val 1.36987
  Epoch 011 - train 0.50243 | val 1.34724
  Classification -> best τ=0.365 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65285 | val 0.83028
  Epoch 012 - train 0.55979 | val 0.67133
  Classification -> best τ=0.475 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58736 | val 0.89105
  Epoch 011 - train 0.58248 | val 0.86296
  Classification -> best τ=0.500 (val F1=0.3778)
  Directional -> Accuracy: 0.4865, MCC: -0.0165, F1: 0.5778

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56795 | val 0.75621
  Epoch 012 - train 0.53149 | val 0.82704
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65357 | val 0.67543
  Epoch 020 - train 0.53995 | val 0.75740
  Epoch 027 - train 0.45601 | val 0.69332
  Classification -> best τ=0.445 (val F1=0.4588)
  Directional -> Accuracy: 0.6429, MCC: 0.3203, F1: 0.7619

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57363 | val 0.63719
  Epoch 017 - train 0.48668 | val 0.60763
  Classification -> best τ=0.640 (val F1=0.5249)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59393 | val 0.69483
  Epoch 011 - train 0.58983 | val 0.74169
  Classification -> best τ=0.515 (val F1=0.1730)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61829 | val 1.01426
  Epoch 011 - train 0.63229 | val 1.29838
  Classification -> best τ=0.505 (val F1=0.2640)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60130 | val 0.73119
  Epoch 016 - train 0.58727 | val 0.85906
  Classification -> best τ=0.540 (val F1=0.1573)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62757 | val 0.82611
  Epoch 012 - train 0.60274 | val 0.92791
  Classification -> best τ=0.540 (val F1=0.1655)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62683 | val 0.67488

[I 2026-02-20 05:48:04,337] Trial 202 finished with value: 0.26110918840571695 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007289182156006844, 'weight_decay': 2.124345958287627e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1227038975571173, 'early_stopping_min_delta': 0.008896989648480572}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 015 - train 0.57434 | val 0.71066
  Classification -> best τ=0.435 (val F1=0.2006)
  Directional -> Accuracy: 0.5167, MCC: 0.1248, F1: 0.6588

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26110918840571695
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63738 | val 0.70805
  Epoch 015 - train 0.60059 | val 0.73648
  Classification -> best τ=0.470 (val F1=0.2200)
  Directional -> Accuracy: 0.5263, MCC: 0.0910, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59983 | val 0.67640
  Epoch 013 - train 0.53942 | val 0.68619
  Classification -> best τ=0.440 (val F1=0.3022)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57741 | val 0.79479
  Epoch 012 - train 0.54873 | val 1.01096
  Classification -> best τ=0.565 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62588 | val 0.83744
  Epoch 012 - train 0.60989 | val 1.24121
  Classification -> best τ=0.535 (val F1=0.1716)
  Directional -> Accuracy: 0.5405, MCC: 0.0136, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61381 | val 0.86013
  Epoch 013 - train 0.55509 | val 0.85486
  Classification -> best τ=0.415 (val F1=0.4851)
  Directional -> Accuracy: 0.7000, MCC: 0.4344, F1: 0.7619

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61532 | val 0.75207
  Epoch 011 - train 0.61350 | val 0.72846
  Classification -> best τ=0.550 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: -0.0229, F1: 0.5862

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64871 | val 0.74486
  Epoch 018 - train 0.61328 | val 1.30528
  Classification -> best τ=0.530 (val F1=0.2140)
  Directional -> Accuracy: 0.5441, MCC: 0.1027, F1: 0.5079

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52905 | val 0.99015
  Epoch 012 - train 0.51012 | val 1.52911
  Classification -> best τ=0.350 (val F1=0.2453)
  Directional -> Accuracy: 0.5238, MCC: -0.0525, F1: 0.2308

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56560 | val 0.79831
  Epoch 014 - train 0.50138 | val 1.44245
  Classification -> best τ=0.575 (val F1=0.3616)
  Directional -> Accuracy: 0.5833, MCC: 0.1187, F1: 0.3750

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67102 | val 0.78866
  Epoch 011 - train 0.65077 | val 0.71178
  Classification -> best τ=0.555 (val F1=0.1983)
  Directional -> Accuracy: 0.5362, MCC: 0.0111, F1: 0.3600

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70081 | val 0.98451
  Epoch 012 - train 0.65131 | val 1.18318
  Classification -> best τ=0.330 (val F1=0.2883)
  Directional -> Accuracy: 0.5714, MCC: 0.1237, F1: 0.4878

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59048 | val 1.55319
  Epoch 014 - train 0.53218 | val 1.62678
  Classification -> best τ=0.480 (val F1=0.2162)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64511 | val 0.91234
  Epoch 014 - train 0.60535 | val 0.96966
  Classification -> best τ=0.455 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62960 | val 0.71528
  Epoch 014 - train 0.58079 | val 0.85382
  Classification -> best τ=0.380 (val F1=0.3774)
  Directional -> Accuracy: 0.5500, MCC: 0.1001, F1: 0.5574

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61299 | val 0.73350
  Epoch 011 - train 0.62329 | val 0.71567
  Classification -> best τ=0.475 (val F1=0.3000)
  Directional -> Accuracy: 0.4118, MCC: -0.1489, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59492 | val 0.78005
  Epoch 012 - train 0.58589 | val 0.85914
  Classification -> best τ=0.585 (val F1=0.3372)
  Directional -> Accuracy: 0.5942, MCC: 0.2287, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61991 | val 1.36882
  Epoch 013 - train 0.56814 | val 1.72746
  Classification -> best τ=0.540 (val F1=0.2547)
  Directional -> Accuracy: 0.6207, MCC: 0.0677, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59953 | val 1.65028
  Epoch 012 - train 0.61604 | val 2.89952
  Classification -> best τ=0.620 (val F1=0.2182)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61123 | val 0.89006
  Epoch 012 - train 0.65825 | val 0.81165
  Classification -> best τ=0.620 (val F1=0.2600)
  Directional -> Accuracy: 0.4219, MCC: -0.0509, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63985 | val 0.86398
  Epoch 012 - train 0.58097 | val 0.82387
  Classification -> best τ=0.460 (val F1=0.2403)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61648 | val 0.70160
  Epoch 020 - train 0.58108 | val 0.98692
  Epoch 021 - train 0.50231 | val 0.88499
  Classification -> best τ=0.395 (val F1=0.3678)
  Directional -> Accuracy: 0.5532, MCC: 0.0843, F1: 0.6182

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63911 | val 1.10907
  Epoch 013 - train 0.59975 | val 1.44423
  Classification -> best τ=0.480 (val F1=0.2254)
  Directional -> Accuracy: 0.5385, MCC: 0.0777, F1: 0.5312

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61108 | val 2.73408
  Epoch 011 - train 0.69821 | val 1.51034
  Classification -> best τ=0.475 (val F1=0.2981)
  Directional -> Accuracy: 0.5439, MCC: 0.0737, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64300 | val 1.05801
  Epoch 011 - train 0.62758 | val 0.95404
  Classification -> best τ=0.550 (val F1=0.1415)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58334 | val 0.82085
  Epoch 013 - train 0.51995 | val 1.39608
  Classification -> best τ=0.630 (val F1=0.3786)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57203 | val 1.54767
  Epoch 011 - train 0.53170 | val 1.81914
  Classification -> best τ=0.435 (val F1=0.0155)
  Directional -> Accuracy: 0.5333, MCC: 0.0086, F1: 0.3636

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60965 | val 0.68763
  Epoch 016 - train 0.50924 | val 0.71317
  Classification -> best τ=0.595 (val F1=0.1005)
  Directional -> Accuracy: 0.5714, MCC: 0.1667, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60298 | val 0.77379
  Epoch 012 - train 0.58770 | val 0.82492
  Classification -> best τ=0.380 (val F1=0.2354)
  Directional -> Accuracy: 0.5536, MCC: 0.2640, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62062 | val 0.78331
  Epoch 011 - train 0.63350 | val 0.71141
  Classification -> best τ=0.525 (val F1=0.2414)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61442 | val 0.95001
  Epoch 012 - train 0.60887 | val 0.91501
  Classification -> best τ=0.630 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69031 | val 0.72349
  Epoch 018 - train 0.49428 | val 1.17611
  Classification -> best τ=0.450 (val F1=0.3034)
  Directional -> Accuracy: 0.5000, MCC: -0.0976, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55152 | val 0.98274
  Epoch 013 - train 0.43179 | val 1.41279
  Classification -> best τ=0.520 (val F1=0.4158)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58709 | val 0.77809
  Epoch 013 - train 0.60099 | val 0.74410
  Classification -> best τ=0.350 (val F1=0.3593)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60564 | val 0.83875
  Epoch 014 - train 0.58359 | val 1.68729
  Classification -> best τ=0.425 (val F1=0.2057)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62887 | val 0.90651
  Epoch 016 - train 0.55894 | val 1.07662
  Classification -> best τ=0.355 (val F1=0.3787)
  Directional -> Accuracy: 0.6212, MCC: 0.3061, F1: 0.5902

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54888 | val 0.85759
  Epoch 013 - train 0.59434 | val 1.43535
  Classification -> best τ=0.445 (val F1=0.2292)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51419 | val 0.84046
  Epoch 013 - train 0.51082 | val 0.80677
  Classification -> best τ=0.385 (val F1=0.3280)
  Directional -> Accuracy: 0.5179, MCC: 0.1353, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57905 | val 1.24716
  Epoch 011 - train 0.62716 | val 1.31475
  Classification -> best τ=0.450 (val F1=0.1369)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60604 | val 0.75492
  Epoch 015 - train 0.52763 | val 0.79598
  Classification -> best τ=0.460 (val F1=0.2928)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63894 | val 0.71681
  Epoch 014 - train 0.63600 | val 0.81519
  Classification -> best τ=0.470 (val F1=0.2869)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57637 | val 0.74511
  Epoch 012 - train 0.54479 | val 0.79776
  Classification -> best τ=0.495 (val F1=0.3190)
  Directional -> Accuracy: 0.5778, MCC: 0.1778, F1: 0.6780

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58811 | val 0.73718
  Epoch 011 - train 0.53288 | val 0.79478
  Classification -> best τ=0.565 (val F1=0.4082)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65528 | val 0.82655
  Epoch 014 - train 0.61333 | val 0.67608
  Classification -> best τ=0.540 (val F1=0.5249)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61018 | val 1.02345
  Epoch 011 - train 0.59045 | val 0.94880
  Classification -> best τ=0.650 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60787 | val 1.04991
  Epoch 012 - train 0.53290 | val 1.68661
  Classification -> best τ=0.565 (val F1=0.3988)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61383 | val 0.85254
  Epoch 014 - train 0.58996 | val 1.24047
  Classification -> best τ=0.445 (val F1=0.2229)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62533 | val 1.14919
  Epoch 017 - train 0.57956 | val 1.00919
  Classification -> best τ=0.625 (val F1=0.2728)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58506 | val 0.68735

[I 2026-02-20 05:49:01,760] Trial 203 finished with value: 0.27822400428257027 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00961448486865448, 'weight_decay': 3.5693427107986387e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2290785521849423, 'early_stopping_min_delta': 0.009356596015804313}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.59633 | val 0.78696
  Classification -> best τ=0.525 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27822400428257027
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56708 | val 1.05755
  Epoch 012 - train 0.58250 | val 1.21623
  Classification -> best τ=0.460 (val F1=0.2125)
  Directional -> Accuracy: 0.5658, MCC: 0.1545, F1: 0.5823

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58623 | val 0.67722
  Epoch 011 - train 0.56777 | val 0.68489
  Classification -> best τ=0.485 (val F1=0.3265)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63109 | val 0.73609
  Epoch 018 - train 0.50905 | val 0.89846
  Classification -> best τ=0.455 (val F1=0.2818)
  Directional -> Accuracy: 0.6087, MCC: 0.2145, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67143 | val 0.74682
  Epoch 012 - train 0.63706 | val 0.81796
  Classification -> best τ=0.435 (val F1=0.1462)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57435 | val 0.86552
  Epoch 011 - train 0.54046 | val 0.73382
  Classification -> best τ=0.505 (val F1=0.5298)
  Directional -> Accuracy: 0.6600, MCC: 0.3309, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59083 | val 0.69655
  Epoch 011 - train 0.59624 | val 0.88811
  Classification -> best τ=0.540 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65181 | val 1.03889
  Epoch 014 - train 0.61617 | val 1.50690
  Classification -> best τ=0.470 (val F1=0.2823)
  Directional -> Accuracy: 0.4412, MCC: -0.0174, F1: 0.5128

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57957 | val 0.63565
  Epoch 012 - train 0.51071 | val 0.78522
  Classification -> best τ=0.450 (val F1=0.0668)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61685 | val 0.77980
  Epoch 012 - train 0.58481 | val 0.90957
  Classification -> best τ=0.410 (val F1=0.1221)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57900 | val 0.82494
  Epoch 012 - train 0.54735 | val 0.84337
  Classification -> best τ=0.530 (val F1=0.0263)
  Directional -> Accuracy: 0.5942, MCC: 0.1207, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58775 | val 0.70414
  Epoch 019 - train 0.55355 | val 0.92132
  Classification -> best τ=0.355 (val F1=0.3618)
  Directional -> Accuracy: 0.5714, MCC: 0.2278, F1: 0.6441

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52260 | val 1.06675
  Epoch 014 - train 0.46787 | val 1.05370
  Classification -> best τ=0.460 (val F1=0.2874)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59070 | val 1.29526
  Epoch 011 - train 0.56729 | val 1.71751
  Classification -> best τ=0.515 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61210 | val 0.63625
  Epoch 015 - train 0.58865 | val 0.71015
  Classification -> best τ=0.435 (val F1=0.3774)
  Directional -> Accuracy: 0.5500, MCC: 0.1558, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57455 | val 0.88226
  Epoch 011 - train 0.54671 | val 0.80105
  Classification -> best τ=0.510 (val F1=0.2837)
  Directional -> Accuracy: 0.5098, MCC: 0.2266, F1: 0.6479

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63900 | val 0.70164
  Epoch 012 - train 0.60054 | val 0.94650
  Classification -> best τ=0.635 (val F1=0.2778)
  Directional -> Accuracy: 0.5507, MCC: 0.1300, F1: 0.4918

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61380 | val 1.05941
  Epoch 011 - train 0.60573 | val 1.16173
  Classification -> best τ=0.560 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61508 | val 0.81533
  Epoch 012 - train 0.64873 | val 1.43606
  Classification -> best τ=0.475 (val F1=0.1653)
  Directional -> Accuracy: 0.5733, MCC: 0.1312, F1: 0.6279

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63454 | val 0.67352
  Epoch 017 - train 0.62276 | val 0.97352
  Classification -> best τ=0.345 (val F1=0.3421)
  Directional -> Accuracy: 0.4688, MCC: 0.0381, F1: 0.3200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62167 | val 0.97751
  Epoch 012 - train 0.59411 | val 0.89257
  Classification -> best τ=0.485 (val F1=0.3162)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58676 | val 0.67284
  Epoch 018 - train 0.47099 | val 1.04319
  Classification -> best τ=0.405 (val F1=0.3458)
  Directional -> Accuracy: 0.4468, MCC: 0.1299, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63758 | val 0.91718
  Epoch 011 - train 0.61968 | val 0.95312
  Classification -> best τ=0.445 (val F1=0.1650)
  Directional -> Accuracy: 0.5231, MCC: 0.0442, F1: 0.6173

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60908 | val 0.72768
  Epoch 017 - train 0.53513 | val 0.70609
  Classification -> best τ=0.500 (val F1=0.4373)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60598 | val 0.95237
  Epoch 011 - train 0.61343 | val 1.05684
  Classification -> best τ=0.540 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0808, F1: 0.5455

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57723 | val 0.77215
  Epoch 015 - train 0.53468 | val 0.97027
  Classification -> best τ=0.585 (val F1=0.4947)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56241 | val 0.93506
  Epoch 012 - train 0.52521 | val 1.21885
  Classification -> best τ=0.540 (val F1=0.2035)
  Directional -> Accuracy: 0.4889, MCC: 0.2285, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60961 | val 0.77813
  Epoch 011 - train 0.58945 | val 0.76204
  Classification -> best τ=0.660 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66101 | val 0.73216
  Epoch 011 - train 0.65733 | val 0.77507
  Classification -> best τ=0.480 (val F1=0.1951)
  Directional -> Accuracy: 0.4643, MCC: -0.0246, F1: 0.3478

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56371 | val 0.72788
  Epoch 014 - train 0.53764 | val 0.93256
  Classification -> best τ=0.505 (val F1=0.2414)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58560 | val 0.79183
  Epoch 012 - train 0.56536 | val 1.20112
  Classification -> best τ=0.600 (val F1=0.3501)
  Directional -> Accuracy: 0.5714, MCC: 0.1348, F1: 0.4706

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57181 | val 0.87609
  Epoch 012 - train 0.54151 | val 1.12937
  Classification -> best τ=0.445 (val F1=0.2042)
  Directional -> Accuracy: 0.5238, MCC: -0.0387, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53888 | val 0.75929
  Epoch 013 - train 0.49924 | val 0.94362
  Classification -> best τ=0.480 (val F1=0.3574)
  Directional -> Accuracy: 0.5102, MCC: -0.0696, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63315 | val 0.71320
  Epoch 015 - train 0.55351 | val 0.87787
  Classification -> best τ=0.325 (val F1=0.3815)
  Directional -> Accuracy: 0.5278, MCC: 0.0905, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64530 | val 0.87458
  Epoch 011 - train 0.61281 | val 0.87109
  Classification -> best τ=0.525 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61133 | val 0.88376
  Epoch 011 - train 0.59412 | val 0.85221
  Classification -> best τ=0.550 (val F1=0.2899)
  Directional -> Accuracy: 0.5152, MCC: 0.0448, F1: 0.5294

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62823 | val 0.73378
  Epoch 011 - train 0.52082 | val 0.74092
  Classification -> best τ=0.475 (val F1=0.2658)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57069 | val 0.90232
  Epoch 011 - train 0.58581 | val 0.78227
  Classification -> best τ=0.460 (val F1=0.2110)
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50384 | val 1.10915
  Epoch 011 - train 0.55105 | val 1.06941
  Classification -> best τ=0.430 (val F1=0.0586)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56627 | val 0.66538
  Epoch 020 - train 0.38906 | val 0.67899
  Epoch 030 - train 0.24034 | val 0.79496
  Epoch 034 - train 0.18926 | val 0.89413
  Classification -> best τ=0.265 (val F1=0.5536)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59834 | val 0.69706
  Epoch 017 - train 0.57693 | val 0.82731
  Classification -> best τ=0.435 (val F1=0.3263)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55787 | val 0.77050
  Epoch 014 - train 0.51755 | val 1.00361
  Classification -> best τ=0.500 (val F1=0.3500)
  Directional -> Accuracy: 0.5778, MCC: 0.1935, F1: 0.6885

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64780 | val 0.67498
  Epoch 020 - train 0.45348 | val 0.64569
  Epoch 030 - train 0.33596 | val 0.50103
  Epoch 039 - train 0.11978 | val 0.66597
  Classification -> best τ=0.425 (val F1=0.7845)
  Directional -> Accuracy: 0.5238, MCC: -0.0152, F1: 0.6296

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58635 | val 0.67831
  Epoch 012 - train 0.56853 | val 0.69121
  Classification -> best τ=0.555 (val F1=0.4385)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59694 | val 0.69745
  Epoch 011 - train 0.56543 | val 0.71191
  Classification -> best τ=0.615 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56936 | val 1.31988
  Epoch 011 - train 0.55817 | val 1.69853
  Classification -> best τ=0.550 (val F1=0.2143)
  Directional -> Accuracy: 0.5357, MCC: 0.0625, F1: 0.4091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63648 | val 0.85180
  Epoch 012 - train 0.62929 | val 0.79515
  Classification -> best τ=0.600 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1039, F1: 0.4783

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60671 | val 0.80235
  Epoch 014 - train 0.55094 | val 1.02227
  Classification -> best τ=0.515 (val F1=0.0733)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59173 | val 0.89341

[I 2026-02-20 05:49:58,200] Trial 204 finished with value: 0.2790288818598844 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006330596085995687, 'weight_decay': 3.344662929677465e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.213716933394414, 'early_stopping_min_delta': 0.009375327294963666}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.56800 | val 0.99414
  Classification -> best τ=0.405 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.0398, F1: 0.1667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2790288818598844
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58015 | val 0.76481
  Epoch 012 - train 0.60803 | val 0.82361
  Classification -> best τ=0.440 (val F1=0.1299)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58901 | val 0.72061
  Epoch 017 - train 0.54633 | val 0.67464
  Classification -> best τ=0.435 (val F1=0.2713)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57771 | val 0.80279
  Epoch 018 - train 0.48754 | val 1.10423
  Classification -> best τ=0.500 (val F1=0.3140)
  Directional -> Accuracy: 0.5435, MCC: 0.0756, F1: 0.6316

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64990 | val 0.87073
  Epoch 014 - train 0.65585 | val 0.72651
  Classification -> best τ=0.525 (val F1=0.1971)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57885 | val 0.68934
  Epoch 011 - train 0.61797 | val 0.66937
  Classification -> best τ=0.480 (val F1=0.4247)
  Directional -> Accuracy: 0.7400, MCC: 0.4787, F1: 0.7547

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59314 | val 0.73591
  Epoch 011 - train 0.58746 | val 0.68420
  Classification -> best τ=0.480 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65345 | val 0.78616
  Epoch 015 - train 0.62166 | val 1.01493
  Classification -> best τ=0.605 (val F1=0.3110)
  Directional -> Accuracy: 0.4853, MCC: -0.1115, F1: 0.2857

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54439 | val 1.02755
  Epoch 012 - train 0.50426 | val 1.30410
  Classification -> best τ=0.375 (val F1=0.2075)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.1818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61682 | val 0.80102
  Epoch 019 - train 0.46752 | val 1.04566
  Classification -> best τ=0.695 (val F1=0.4022)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60092 | val 0.78487
  Epoch 011 - train 0.60388 | val 0.84119
  Classification -> best τ=0.590 (val F1=0.2307)
  Directional -> Accuracy: 0.5652, MCC: -0.1033, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67459 | val 0.82848
  Epoch 013 - train 0.59025 | val 1.14145
  Classification -> best τ=0.340 (val F1=0.4196)
  Directional -> Accuracy: 0.4898, MCC: 0.0161, F1: 0.5455

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57328 | val 1.00917
  Epoch 012 - train 0.52626 | val 1.44822
  Classification -> best τ=0.590 (val F1=0.1724)
  Directional -> Accuracy: 0.4386, MCC: -0.1420, F1: 0.2000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56711 | val 1.09905
  Epoch 011 - train 0.57052 | val 1.39883
  Classification -> best τ=0.380 (val F1=0.3172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64787 | val 0.64668
  Epoch 011 - train 0.63630 | val 0.65360
  Classification -> best τ=0.425 (val F1=0.3916)
  Directional -> Accuracy: 0.5333, MCC: 0.0727, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62132 | val 0.68230
  Epoch 018 - train 0.56387 | val 0.84741
  Classification -> best τ=0.520 (val F1=0.2141)
  Directional -> Accuracy: 0.5098, MCC: 0.2266, F1: 0.6479

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65312 | val 0.76364
  Epoch 017 - train 0.58827 | val 0.96819
  Classification -> best τ=0.360 (val F1=0.4517)
  Directional -> Accuracy: 0.5362, MCC: 0.0180, F1: 0.6863

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58630 | val 1.33284
  Epoch 011 - train 0.60937 | val 1.24276
  Classification -> best τ=0.570 (val F1=0.0462)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62607 | val 1.26114
  Epoch 012 - train 0.61331 | val 1.12036
  Classification -> best τ=0.430 (val F1=0.2182)
  Directional -> Accuracy: 0.6267, MCC: 0.1601, F1: 0.7455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61787 | val 0.88529
  Epoch 016 - train 0.59037 | val 0.97242
  Classification -> best τ=0.280 (val F1=0.3948)
  Directional -> Accuracy: 0.4062, MCC: -0.1050, F1: 0.0952

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64011 | val 0.75186
  Epoch 012 - train 0.60026 | val 0.90364
  Classification -> best τ=0.505 (val F1=0.3495)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59206 | val 0.69679
  Epoch 020 - train 0.50448 | val 1.17386
  Epoch 024 - train 0.42782 | val 1.18362
  Classification -> best τ=0.320 (val F1=0.3693)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63768 | val 1.00874
  Epoch 011 - train 0.61656 | val 0.81328
  Classification -> best τ=0.625 (val F1=0.1350)
  Directional -> Accuracy: 0.4615, MCC: -0.0866, F1: 0.2222

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57207 | val 0.78847
  Epoch 013 - train 0.54904 | val 0.84344
  Classification -> best τ=0.565 (val F1=0.2875)
  Directional -> Accuracy: 0.5439, MCC: 0.0906, F1: 0.5667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63734 | val 0.92388
  Epoch 011 - train 0.64088 | val 0.84140
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58199 | val 0.62811
  Epoch 017 - train 0.46132 | val 1.00347
  Classification -> best τ=0.590 (val F1=0.4075)
  Directional -> Accuracy: 0.4727, MCC: 0.0585, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57184 | val 0.85031
  Epoch 013 - train 0.57709 | val 0.88596
  Classification -> best τ=0.550 (val F1=0.3407)
  Directional -> Accuracy: 0.4889, MCC: 0.2285, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61204 | val 0.67410
  Epoch 018 - train 0.56020 | val 0.85376
  Classification -> best τ=0.575 (val F1=0.2582)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61285 | val 0.81990
  Epoch 014 - train 0.57879 | val 0.93600
  Classification -> best τ=0.315 (val F1=0.2371)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58590 | val 0.67365
  Epoch 020 - train 0.46801 | val 0.84840
  Classification -> best τ=0.450 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59522 | val 1.07260
  Epoch 013 - train 0.58822 | val 0.79031
  Classification -> best τ=0.675 (val F1=0.3501)
  Directional -> Accuracy: 0.4524, MCC: -0.1342, F1: 0.2581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60672 | val 1.12986
  Epoch 012 - train 0.58102 | val 1.68016
  Classification -> best τ=0.455 (val F1=0.1425)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56630 | val 0.72322
  Epoch 013 - train 0.56204 | val 0.84984
  Classification -> best τ=0.405 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59500 | val 0.72644
  Epoch 016 - train 0.57106 | val 1.05027
  Classification -> best τ=0.345 (val F1=0.3450)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64152 | val 0.90600
  Epoch 012 - train 0.60392 | val 1.18784
  Classification -> best τ=0.435 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59365 | val 0.88753
  Epoch 011 - train 0.57803 | val 0.88846
  Classification -> best τ=0.465 (val F1=0.2576)
  Directional -> Accuracy: 0.5909, MCC: 0.1026, F1: 0.7216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54383 | val 0.78350
  Epoch 011 - train 0.52450 | val 1.04129
  Classification -> best τ=0.625 (val F1=0.2618)
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55424 | val 0.83310
  Epoch 011 - train 0.52983 | val 0.80678
  Classification -> best τ=0.420 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54913 | val 1.13039
  Epoch 011 - train 0.53298 | val 1.03930
  Classification -> best τ=0.505 (val F1=0.0726)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56892 | val 0.66564
  Epoch 020 - train 0.44665 | val 0.69169
  Epoch 021 - train 0.46019 | val 0.69995
  Classification -> best τ=0.450 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62516 | val 0.64852
  Epoch 019 - train 0.52857 | val 0.74051
  Classification -> best τ=0.480 (val F1=0.4047)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56950 | val 0.82569
  Epoch 013 - train 0.54943 | val 0.78517
  Classification -> best τ=0.505 (val F1=0.3371)
  Directional -> Accuracy: 0.5333, MCC: 0.0629, F1: 0.6038

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59275 | val 0.60277
  Epoch 020 - train 0.48072 | val 0.76066
  Epoch 021 - train 0.47377 | val 0.69978
  Classification -> best τ=0.315 (val F1=0.5601)
  Directional -> Accuracy: 0.6190, MCC: 0.2107, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55269 | val 0.62683
  Epoch 016 - train 0.51987 | val 0.67933
  Classification -> best τ=0.615 (val F1=0.4682)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58308 | val 0.78262
  Epoch 011 - train 0.58193 | val 0.74231
  Classification -> best τ=0.665 (val F1=0.2396)
  Directional -> Accuracy: 0.3636, MCC: -0.2878, F1: 0.4262

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59277 | val 1.13824
  Epoch 011 - train 0.59178 | val 1.27876
  Classification -> best τ=0.505 (val F1=0.2632)
  Directional -> Accuracy: 0.5357, MCC: 0.1303, F1: 0.6486

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59459 | val 0.88190
  Epoch 012 - train 0.61166 | val 1.03293
  Classification -> best τ=0.550 (val F1=0.0798)
  Directional -> Accuracy: 0.5472, MCC: 0.1208, F1: 0.4000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63584 | val 1.01371
  Epoch 017 - train 0.58505 | val 0.85538
  Classification -> best τ=0.525 (val F1=0.1290)
  Directional -> Accuracy: 0.3818, MCC: -0.2379, F1: 0.2273

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58815 | val 0.72830

[I 2026-02-20 05:50:56,758] Trial 205 finished with value: 0.2802486796677505 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006024513988096626, 'weight_decay': 1.4223169220272476e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2170850976586158, 'early_stopping_min_delta': 0.009356661563315336}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.61712 | val 0.72021
  Classification -> best τ=0.500 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0062, F1: 0.0645

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2802486796677505
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61443 | val 0.76809
  Epoch 012 - train 0.59238 | val 0.78464
  Classification -> best τ=0.430 (val F1=0.1718)
  Directional -> Accuracy: 0.5526, MCC: 0.1059, F1: 0.5278

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57317 | val 0.69513
  Epoch 011 - train 0.57728 | val 0.67603
  Classification -> best τ=0.480 (val F1=0.2471)
  Directional -> Accuracy: 0.5556, MCC: 0.1160, F1: 0.5833

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59228 | val 0.86704
  Epoch 012 - train 0.58479 | val 0.70892
  Classification -> best τ=0.605 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65368 | val 0.87483
  Epoch 012 - train 0.64859 | val 0.96031
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60567 | val 1.05619
  Epoch 013 - train 0.52208 | val 0.98387
  Classification -> best τ=0.535 (val F1=0.3992)
  Directional -> Accuracy: 0.5400, MCC: 0.0709, F1: 0.6567

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65045 | val 0.71619
  Epoch 011 - train 0.64523 | val 0.71542
  Classification -> best τ=0.520 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64114 | val 0.96531
  Epoch 012 - train 0.60588 | val 0.94963
  Classification -> best τ=0.420 (val F1=0.2810)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61861 | val 0.88537
  Epoch 012 - train 0.54009 | val 1.15493
  Classification -> best τ=0.360 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60125 | val 0.72395
  Epoch 012 - train 0.58397 | val 0.89731
  Classification -> best τ=0.485 (val F1=0.2822)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58182 | val 0.91358
  Epoch 011 - train 0.58904 | val 0.81355
  Classification -> best τ=0.430 (val F1=0.1304)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63325 | val 0.76750
  Epoch 011 - train 0.61902 | val 0.74430
  Classification -> best τ=0.465 (val F1=0.2074)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56605 | val 1.25562
  Epoch 012 - train 0.52368 | val 2.02276
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56295 | val 1.26343
  Epoch 011 - train 0.52421 | val 1.54322
  Classification -> best τ=0.330 (val F1=0.3070)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59765 | val 0.68642
  Epoch 011 - train 0.58824 | val 0.71412
  Classification -> best τ=0.465 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1155, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60152 | val 0.80061
  Epoch 016 - train 0.53261 | val 0.86983
  Classification -> best τ=0.590 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0199, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57242 | val 0.85676
  Epoch 012 - train 0.59012 | val 0.95306
  Classification -> best τ=0.355 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59415 | val 1.06976
  Epoch 011 - train 0.59125 | val 1.31797
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62528 | val 1.04139
  Epoch 012 - train 0.63813 | val 0.94382
  Classification -> best τ=0.525 (val F1=0.0659)
  Directional -> Accuracy: 0.4800, MCC: -0.0436, F1: 0.5301

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61589 | val 0.86619
  Epoch 011 - train 0.63003 | val 1.36374
  Classification -> best τ=0.470 (val F1=0.2614)
  Directional -> Accuracy: 0.4531, MCC: -0.1389, F1: 0.5455

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60935 | val 0.67712
  Epoch 012 - train 0.63987 | val 0.67850
  Classification -> best τ=0.590 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57861 | val 0.68458
  Epoch 015 - train 0.51695 | val 0.74518
  Classification -> best τ=0.455 (val F1=0.2247)
  Directional -> Accuracy: 0.6383, MCC: 0.1871, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62905 | val 0.80687
  Epoch 011 - train 0.62296 | val 0.70310
  Classification -> best τ=0.440 (val F1=0.0992)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62456 | val 0.70867
  Epoch 011 - train 0.60112 | val 0.73239
  Classification -> best τ=0.520 (val F1=0.3604)
  Directional -> Accuracy: 0.4912, MCC: -0.1095, F1: 0.6234

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62191 | val 0.77692
  Epoch 012 - train 0.61380 | val 0.71925
  Classification -> best τ=0.535 (val F1=0.1565)
  Directional -> Accuracy: 0.5077, MCC: -0.0202, F1: 0.2381

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58052 | val 0.76026
  Epoch 016 - train 0.50226 | val 1.07923
  Classification -> best τ=0.730 (val F1=0.4201)
  Directional -> Accuracy: 0.4545, MCC: -0.0256, F1: 0.1176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57679 | val 0.70964
  Epoch 011 - train 0.59446 | val 0.79319
  Classification -> best τ=0.465 (val F1=0.1160)
  Directional -> Accuracy: 0.5111, MCC: 0.0260, F1: 0.4762

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60442 | val 0.68649
  Epoch 011 - train 0.61108 | val 0.69615
  Classification -> best τ=0.515 (val F1=0.1964)
  Directional -> Accuracy: 0.4048, MCC: -0.2970, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60836 | val 0.94599
  Epoch 013 - train 0.53302 | val 1.22203
  Classification -> best τ=0.420 (val F1=0.2870)
  Directional -> Accuracy: 0.5714, MCC: 0.2952, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57620 | val 1.13468
  Epoch 018 - train 0.50936 | val 1.35568
  Classification -> best τ=0.435 (val F1=0.4109)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57516 | val 0.83283
  Epoch 011 - train 0.57104 | val 0.77144
  Classification -> best τ=0.595 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0830, F1: 0.3448

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58377 | val 0.99230
  Epoch 011 - train 0.58971 | val 0.82389
  Classification -> best τ=0.495 (val F1=0.2238)
  Directional -> Accuracy: 0.4048, MCC: -0.1682, F1: 0.1935

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56537 | val 0.78857
  Epoch 013 - train 0.49518 | val 0.95980
  Classification -> best τ=0.495 (val F1=0.3957)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62015 | val 0.70753
  Epoch 014 - train 0.54525 | val 0.84382
  Classification -> best τ=0.355 (val F1=0.3450)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60102 | val 0.79087
  Epoch 012 - train 0.60335 | val 0.92308
  Classification -> best τ=0.510 (val F1=0.2878)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62257 | val 0.79861
  Epoch 011 - train 0.62127 | val 0.84700
  Classification -> best τ=0.450 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54877 | val 0.78238
  Epoch 011 - train 0.53082 | val 0.89038
  Classification -> best τ=0.485 (val F1=0.3218)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57824 | val 0.79906
  Epoch 011 - train 0.54574 | val 0.72923
  Classification -> best τ=0.415 (val F1=0.2110)
  Directional -> Accuracy: 0.5357, MCC: 0.1371, F1: 0.6286

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49710 | val 1.54446
  Epoch 011 - train 0.48194 | val 1.69636
  Classification -> best τ=0.455 (val F1=0.1709)
  Directional -> Accuracy: 0.5435, MCC: -0.0917, F1: 0.6866

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58205 | val 0.67543
  Epoch 020 - train 0.49140 | val 0.66680
  Epoch 027 - train 0.43474 | val 0.76766
  Classification -> best τ=0.245 (val F1=0.5489)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61556 | val 0.80834
  Epoch 012 - train 0.60517 | val 0.95885
  Classification -> best τ=0.405 (val F1=0.2773)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60086 | val 0.74165
  Epoch 015 - train 0.51114 | val 0.98643
  Classification -> best τ=0.495 (val F1=0.2582)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59271 | val 0.66440
  Epoch 020 - train 0.44171 | val 0.62543
  Epoch 026 - train 0.46777 | val 0.82561
  Classification -> best τ=0.505 (val F1=0.5000)
  Directional -> Accuracy: 0.6190, MCC: 0.1936, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58627 | val 0.65455
  Epoch 020 - train 0.45475 | val 0.68690
  Epoch 022 - train 0.45663 | val 0.64941
  Classification -> best τ=0.680 (val F1=0.4478)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58262 | val 0.68648
  Epoch 011 - train 0.59848 | val 0.68926
  Classification -> best τ=0.615 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55699 | val 1.65011
  Epoch 011 - train 0.56698 | val 1.59794
  Classification -> best τ=0.620 (val F1=0.3432)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61061 | val 0.70969
  Epoch 012 - train 0.57165 | val 0.84062
  Classification -> best τ=0.560 (val F1=0.2064)
  Directional -> Accuracy: 0.5660, MCC: 0.2804, F1: 0.2581

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61693 | val 0.95405
  Epoch 017 - train 0.54438 | val 1.18037
  Classification -> best τ=0.545 (val F1=0.2625)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60798 | val 0.73601

[I 2026-02-20 05:51:49,303] Trial 206 finished with value: 0.25649562591216557 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.004897999265114705, 'weight_decay': 2.515188145671357e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.239782883884889, 'early_stopping_min_delta': 0.009401236870632221}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 015 - train 0.58081 | val 0.73585
  Classification -> best τ=0.470 (val F1=0.1933)
  Directional -> Accuracy: 0.4833, MCC: -0.0667, F1: 0.2439

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25649562591216557
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56562 | val 0.78762
  Epoch 015 - train 0.57065 | val 1.17107
  Classification -> best τ=0.535 (val F1=0.2200)
  Directional -> Accuracy: 0.5789, MCC: 0.1259, F1: 0.4286

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55785 | val 0.68700
  Epoch 020 - train 0.42683 | val 0.68929
  Epoch 022 - train 0.39185 | val 0.69439
  Classification -> best τ=0.435 (val F1=0.3006)
  Directional -> Accuracy: 0.4889, MCC: 0.0165, F1: 0.4651

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58225 | val 0.77945
  Epoch 012 - train 0.59448 | val 0.79699
  Classification -> best τ=0.500 (val F1=0.3512)
  Directional -> Accuracy: 0.4348, MCC: -0.1234, F1: 0.3158

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63240 | val 0.73991
  Epoch 011 - train 0.61312 | val 0.80165
  Classification -> best τ=0.495 (val F1=0.2030)
  Directional -> Accuracy: 0.5000, MCC: -0.1401, F1: 0.6606

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58371 | val 0.76457
  Epoch 013 - train 0.55955 | val 1.08296
  Classification -> best τ=0.515 (val F1=0.3984)
  Directional -> Accuracy: 0.7000, MCC: 0.4193, F1: 0.7541

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60698 | val 0.69513
  Epoch 014 - train 0.53493 | val 0.73453
  Classification -> best τ=0.500 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63000 | val 0.92368
  Epoch 011 - train 0.64167 | val 1.24181
  Classification -> best τ=0.435 (val F1=0.2228)
  Directional -> Accuracy: 0.4265, MCC: 0.1413, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51572 | val 0.93323
  Epoch 013 - train 0.44987 | val 0.67866
  Classification -> best τ=0.415 (val F1=0.1657)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.4444

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55833 | val 0.76265
  Epoch 012 - train 0.61184 | val 0.74890
  Classification -> best τ=0.505 (val F1=0.2233)
  Directional -> Accuracy: 0.6875, MCC: 0.3620, F1: 0.6341

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59652 | val 0.77776
  Epoch 011 - train 0.56875 | val 0.81616
  Classification -> best τ=0.490 (val F1=0.1607)
  Directional -> Accuracy: 0.4928, MCC: -0.0562, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67486 | val 0.77350
  Epoch 012 - train 0.67673 | val 0.74292
  Classification -> best τ=0.390 (val F1=0.2322)
  Directional -> Accuracy: 0.5306, MCC: 0.0724, F1: 0.5306

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54360 | val 0.97188
  Epoch 013 - train 0.52423 | val 1.40157
  Classification -> best τ=0.405 (val F1=0.1512)
  Directional -> Accuracy: 0.6140, MCC: 0.2274, F1: 0.6333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57199 | val 1.28437
  Epoch 012 - train 0.58403 | val 1.32195
  Classification -> best τ=0.475 (val F1=0.2438)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58823 | val 0.67289
  Epoch 016 - train 0.52835 | val 0.95725
  Classification -> best τ=0.435 (val F1=0.3844)
  Directional -> Accuracy: 0.5667, MCC: 0.1345, F1: 0.5938

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56884 | val 0.78310
  Epoch 011 - train 0.58663 | val 0.80802
  Classification -> best τ=0.485 (val F1=0.0692)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58590 | val 0.82159
  Epoch 012 - train 0.59948 | val 0.83547
  Classification -> best τ=0.370 (val F1=0.2341)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62474 | val 1.01372
  Epoch 011 - train 0.61679 | val 1.25900
  Classification -> best τ=0.555 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61186 | val 2.18187
  Epoch 013 - train 0.58494 | val 1.94916
  Classification -> best τ=0.470 (val F1=0.1605)
  Directional -> Accuracy: 0.5733, MCC: 0.1524, F1: 0.6098

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63705 | val 0.94656
  Epoch 015 - train 0.57588 | val 0.77758
  Classification -> best τ=0.445 (val F1=0.2770)
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63481 | val 0.78900
  Epoch 012 - train 0.61830 | val 0.69967
  Classification -> best τ=0.450 (val F1=0.3006)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59706 | val 0.67852
  Epoch 018 - train 0.46343 | val 1.12043
  Classification -> best τ=0.460 (val F1=0.4078)
  Directional -> Accuracy: 0.6596, MCC: 0.2653, F1: 0.7333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60855 | val 0.98991
  Epoch 012 - train 0.60354 | val 1.02055
  Classification -> best τ=0.675 (val F1=0.1350)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60926 | val 0.72788
  Epoch 012 - train 0.56229 | val 0.75606
  Classification -> best τ=0.630 (val F1=0.3727)
  Directional -> Accuracy: 0.5263, MCC: 0.0784, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62839 | val 0.72660
  Epoch 011 - train 0.60018 | val 0.90829
  Classification -> best τ=0.495 (val F1=0.1565)
  Directional -> Accuracy: 0.4462, MCC: -0.0974, F1: 0.5385

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62722 | val 0.65035
  Epoch 015 - train 0.54725 | val 0.75787
  Classification -> best τ=0.465 (val F1=0.5489)
  Directional -> Accuracy: 0.5091, MCC: 0.0267, F1: 0.5091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56552 | val 1.01545
  Epoch 012 - train 0.54049 | val 1.13112
  Classification -> best τ=0.455 (val F1=0.1310)
  Directional -> Accuracy: 0.4889, MCC: 0.0485, F1: 0.5490

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61991 | val 0.75807
  Epoch 011 - train 0.62265 | val 0.75008
  Classification -> best τ=0.600 (val F1=0.1376)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.4878

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63587 | val 0.71099
  Epoch 014 - train 0.60924 | val 0.76719
  Classification -> best τ=0.355 (val F1=0.2614)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59609 | val 0.72987
  Epoch 013 - train 0.55841 | val 0.70647
  Classification -> best τ=0.540 (val F1=0.1943)
  Directional -> Accuracy: 0.6500, MCC: 0.3015, F1: 0.7407

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63642 | val 0.88021
  Epoch 014 - train 0.58790 | val 0.88760
  Classification -> best τ=0.660 (val F1=0.3501)
  Directional -> Accuracy: 0.5714, MCC: 0.1348, F1: 0.4706

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56523 | val 1.18250
  Epoch 011 - train 0.54309 | val 0.95711
  Classification -> best τ=0.440 (val F1=0.2786)
  Directional -> Accuracy: 0.4524, MCC: -0.0535, F1: 0.3030

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55979 | val 0.71093
  Epoch 015 - train 0.51089 | val 1.29849
  Classification -> best τ=0.365 (val F1=0.4404)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64774 | val 0.67324
  Epoch 013 - train 0.60909 | val 0.66605
  Classification -> best τ=0.355 (val F1=0.3313)
  Directional -> Accuracy: 0.5000, MCC: 0.0555, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62518 | val 1.09336
  Epoch 011 - train 0.60076 | val 1.03129
  Classification -> best τ=0.560 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62058 | val 0.90279
  Epoch 011 - train 0.61312 | val 0.93774
  Classification -> best τ=0.340 (val F1=0.2674)
  Directional -> Accuracy: 0.6212, MCC: 0.2453, F1: 0.6479

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52079 | val 0.87575
  Epoch 011 - train 0.50432 | val 0.89433
  Classification -> best τ=0.500 (val F1=0.2858)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57068 | val 0.79856
  Epoch 011 - train 0.54679 | val 0.93779
  Classification -> best τ=0.450 (val F1=0.1832)
  Directional -> Accuracy: 0.4821, MCC: -0.0494, F1: 0.4082

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49958 | val 1.62267
  Epoch 011 - train 0.49974 | val 1.81587
  Classification -> best τ=0.455 (val F1=0.2504)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60121 | val 0.65006
  Epoch 019 - train 0.44656 | val 0.72982
  Classification -> best τ=0.390 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61211 | val 0.80245
  Epoch 014 - train 0.57852 | val 0.88464
  Classification -> best τ=0.410 (val F1=0.3426)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56743 | val 0.76787
  Epoch 012 - train 0.58809 | val 0.77130
  Classification -> best τ=0.375 (val F1=0.4632)
  Directional -> Accuracy: 0.4222, MCC: -0.1613, F1: 0.2778

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60575 | val 0.63491
  Epoch 017 - train 0.54795 | val 0.67255
  Classification -> best τ=0.495 (val F1=0.5092)
  Directional -> Accuracy: 0.6429, MCC: 0.2582, F1: 0.7458

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58739 | val 0.66876
  Epoch 017 - train 0.51605 | val 0.64784
  Classification -> best τ=0.610 (val F1=0.5261)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64237 | val 0.76050
  Epoch 011 - train 0.62138 | val 0.73865
  Classification -> best τ=0.595 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58404 | val 1.45735
  Epoch 011 - train 0.55422 | val 1.37142
  Classification -> best τ=0.560 (val F1=0.3526)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60655 | val 0.87005
  Epoch 012 - train 0.58935 | val 0.74860
  Classification -> best τ=0.610 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1776, F1: 0.5417

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63905 | val 0.96081
  Epoch 012 - train 0.59913 | val 0.85295
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57378 | val 0.67194

[I 2026-02-20 05:52:45,008] Trial 207 finished with value: 0.2697445353213925 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006047061630794683, 'weight_decay': 1.343261849058577e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.198983511293215, 'early_stopping_min_delta': 0.009587971783159462}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 020 - train 0.54053 | val 0.73202
  Classification -> best τ=0.580 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2697445353213925
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61511 | val 0.70869
  Epoch 011 - train 0.59426 | val 0.68727
  Classification -> best τ=0.445 (val F1=0.1299)
  Directional -> Accuracy: 0.4211, MCC: -0.1435, F1: 0.5849

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58142 | val 0.71632
  Epoch 011 - train 0.57482 | val 0.71132
  Classification -> best τ=0.495 (val F1=0.1857)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62400 | val 0.79150
  Epoch 012 - train 0.57468 | val 0.85984
  Classification -> best τ=0.550 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62715 | val 0.81593
  Epoch 011 - train 0.62736 | val 0.90225
  Classification -> best τ=0.425 (val F1=0.1156)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59474 | val 0.73372
  Epoch 014 - train 0.72474 | val 0.95220
  Classification -> best τ=0.520 (val F1=0.4414)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58288 | val 0.82583
  Epoch 015 - train 0.54696 | val 0.72622
  Classification -> best τ=0.465 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65933 | val 0.79300
  Epoch 011 - train 0.62256 | val 0.79302
  Classification -> best τ=0.605 (val F1=0.1718)
  Directional -> Accuracy: 0.6029, MCC: 0.0526, F1: 0.1290

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50746 | val 0.89689
  Epoch 011 - train 0.56977 | val 1.15511
  Classification -> best τ=0.340 (val F1=0.1657)
  Directional -> Accuracy: 0.4762, MCC: -0.1750, F1: 0.1538

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58763 | val 0.72083
  Epoch 020 - train 0.50751 | val 0.79752
  Epoch 022 - train 0.52134 | val 1.05069
  Classification -> best τ=0.625 (val F1=0.4197)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56816 | val 0.72546
  Epoch 012 - train 0.57882 | val 0.79363
  Classification -> best τ=0.530 (val F1=0.2307)
  Directional -> Accuracy: 0.5942, MCC: 0.1018, F1: 0.1765

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65117 | val 0.85409
  Epoch 015 - train 0.57060 | val 1.14677
  Classification -> best τ=0.485 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58150 | val 1.15070
  Epoch 011 - train 0.56671 | val 1.49474
  Classification -> best τ=0.415 (val F1=0.1724)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51329 | val 1.19485
  Epoch 011 - train 0.55178 | val 1.19003
  Classification -> best τ=0.340 (val F1=0.2522)
  Directional -> Accuracy: 0.5476, MCC: 0.1972, F1: 0.6415

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59711 | val 0.67918
  Epoch 015 - train 0.56247 | val 0.78832
  Classification -> best τ=0.380 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54196 | val 0.75041
  Epoch 011 - train 0.56246 | val 0.74681
  Classification -> best τ=0.515 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64448 | val 0.74072
  Epoch 013 - train 0.58468 | val 0.82192
  Classification -> best τ=0.500 (val F1=0.3448)
  Directional -> Accuracy: 0.6667, MCC: 0.3404, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62323 | val 1.44798
  Epoch 011 - train 0.59719 | val 1.36897
  Classification -> best τ=0.595 (val F1=0.0827)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62602 | val 0.89319
  Epoch 012 - train 0.63977 | val 0.86441
  Classification -> best τ=0.515 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61867 | val 0.90152
  Epoch 013 - train 0.58697 | val 1.26144
  Classification -> best τ=0.390 (val F1=0.3948)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62227 | val 0.75489
  Epoch 013 - train 0.63285 | val 0.72869
  Classification -> best τ=0.490 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63233 | val 0.69090
  Epoch 020 - train 0.47405 | val 0.88226
  Epoch 023 - train 0.44650 | val 0.84340
  Classification -> best τ=0.490 (val F1=0.3262)
  Directional -> Accuracy: 0.5106, MCC: 0.0168, F1: 0.5660

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60362 | val 0.77795
  Epoch 012 - train 0.60623 | val 0.92381
  Classification -> best τ=0.535 (val F1=0.1960)
  Directional -> Accuracy: 0.5385, MCC: 0.0783, F1: 0.6250

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61278 | val 0.75481
  Epoch 011 - train 0.58082 | val 0.73423
  Classification -> best τ=0.560 (val F1=0.2644)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62093 | val 0.78513
  Epoch 012 - train 0.60365 | val 0.75856
  Classification -> best τ=0.545 (val F1=0.0277)
  Directional -> Accuracy: 0.5077, MCC: -0.0445, F1: 0.1111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56254 | val 0.73939
  Epoch 013 - train 0.52532 | val 1.03843
  Classification -> best τ=0.510 (val F1=0.4907)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56990 | val 1.07871
  Epoch 011 - train 0.56635 | val 1.51985
  Classification -> best τ=0.540 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59754 | val 0.77305
  Epoch 011 - train 0.56917 | val 0.71393
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59418 | val 0.85623
  Epoch 011 - train 0.61329 | val 0.97163
  Classification -> best τ=0.520 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: -0.1704, F1: 0.5634

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56173 | val 0.72120
  Epoch 020 - train 0.48843 | val 1.73101
  Epoch 021 - train 0.50386 | val 1.44736
  Classification -> best τ=0.545 (val F1=0.2957)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58124 | val 0.87539
  Epoch 012 - train 0.63614 | val 0.92660
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0155, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64640 | val 1.66278
  Epoch 020 - train 0.46481 | val 0.98110
  Epoch 023 - train 0.48051 | val 1.76817
  Classification -> best τ=0.440 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5778

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60335 | val 0.82912
  Epoch 014 - train 0.51592 | val 0.94863
  Classification -> best τ=0.475 (val F1=0.3461)
  Directional -> Accuracy: 0.4694, MCC: -0.2402, F1: 0.6389

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60997 | val 0.97144
  Epoch 016 - train 0.53290 | val 0.85779
  Classification -> best τ=0.355 (val F1=0.4032)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57938 | val 0.96778
  Epoch 011 - train 0.61136 | val 1.08010
  Classification -> best τ=0.570 (val F1=0.1334)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61363 | val 0.78938
  Epoch 011 - train 0.60636 | val 0.90239
  Classification -> best τ=0.445 (val F1=0.2972)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54992 | val 0.73827
  Epoch 011 - train 0.49562 | val 0.74216
  Classification -> best τ=0.435 (val F1=0.2409)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59634 | val 0.78252
  Epoch 011 - train 0.59548 | val 0.77190
  Classification -> best τ=0.450 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53220 | val 0.93301
  Epoch 011 - train 0.48235 | val 1.19177
  Classification -> best τ=0.500 (val F1=0.2441)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59033 | val 0.62782
  Epoch 020 - train 0.48001 | val 0.68837
  Epoch 022 - train 0.42954 | val 0.78717
  Classification -> best τ=0.340 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63027 | val 0.82702
  Epoch 012 - train 0.58162 | val 0.99031
  Classification -> best τ=0.450 (val F1=0.2464)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58066 | val 0.69894
  Epoch 012 - train 0.55315 | val 0.77220
  Classification -> best τ=0.520 (val F1=0.3500)
  Directional -> Accuracy: 0.5333, MCC: 0.1493, F1: 0.2222

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60657 | val 0.65272
  Epoch 020 - train 0.50544 | val 0.66572
  Epoch 024 - train 0.48743 | val 0.61752
  Classification -> best τ=0.450 (val F1=0.5230)
  Directional -> Accuracy: 0.6429, MCC: 0.2513, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60005 | val 0.68749
  Epoch 020 - train 0.48922 | val 0.65668
  Epoch 023 - train 0.44122 | val 0.81933
  Classification -> best τ=0.570 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64195 | val 0.80267
  Epoch 011 - train 0.62273 | val 0.76962
  Classification -> best τ=0.620 (val F1=0.1647)
  Directional -> Accuracy: 0.4000, MCC: -0.1992, F1: 0.4211

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56258 | val 1.55736
  Epoch 011 - train 0.56030 | val 2.02579
  Classification -> best τ=0.565 (val F1=0.3104)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60867 | val 0.73842
  Epoch 016 - train 0.54706 | val 0.84025
  Classification -> best τ=0.640 (val F1=0.2064)
  Directional -> Accuracy: 0.5660, MCC: 0.1322, F1: 0.6230

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62164 | val 0.96251
  Epoch 012 - train 0.58845 | val 0.90875
  Classification -> best τ=0.590 (val F1=0.0465)
  Directional -> Accuracy: 0.4545, MCC: -0.1254, F1: 0.5588

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62036 | val 0.75128

[I 2026-02-20 05:53:39,718] Trial 208 finished with value: 0.260171546907839 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.003973856457246266, 'weight_decay': 4.6116506462381015e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.243671073064305, 'early_stopping_min_delta': 0.0092045605166273}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.57640 | val 0.81766
  Classification -> best τ=0.505 (val F1=0.2623)
  Directional -> Accuracy: 0.5500, MCC: 0.1112, F1: 0.2703

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.260171546907839
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63693 | val 0.67700
  Epoch 011 - train 0.63327 | val 0.70853
  Classification -> best τ=0.560 (val F1=0.1430)
  Directional -> Accuracy: 0.5921, MCC: 0.1564, F1: 0.3111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59237 | val 0.68424
  Epoch 016 - train 0.51283 | val 0.69676
  Classification -> best τ=0.440 (val F1=0.4088)
  Directional -> Accuracy: 0.5111, MCC: 0.0551, F1: 0.5000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59897 | val 0.70647
  Epoch 015 - train 0.54949 | val 0.92363
  Classification -> best τ=0.525 (val F1=0.2128)
  Directional -> Accuracy: 0.5652, MCC: 0.1288, F1: 0.5833

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66491 | val 0.81087
  Epoch 015 - train 0.63502 | val 0.79374
  Classification -> best τ=0.545 (val F1=0.2271)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59208 | val 0.81036
  Epoch 014 - train 0.55802 | val 1.03805
  Classification -> best τ=0.550 (val F1=0.4930)
  Directional -> Accuracy: 0.5800, MCC: 0.2417, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59117 | val 0.89191
  Epoch 011 - train 0.58732 | val 0.88392
  Classification -> best τ=0.480 (val F1=0.2593)
  Directional -> Accuracy: 0.5435, MCC: 0.1177, F1: 0.6182

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65696 | val 0.77833
  Epoch 012 - train 0.63792 | val 0.72356
  Classification -> best τ=0.420 (val F1=0.2462)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53302 | val 1.03711
  Epoch 012 - train 0.50652 | val 1.21211
  Classification -> best τ=0.415 (val F1=0.1147)
  Directional -> Accuracy: 0.4524, MCC: -0.2178, F1: 0.1481

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58182 | val 0.82093
  Epoch 016 - train 0.51509 | val 1.08498
  Classification -> best τ=0.565 (val F1=0.2988)
  Directional -> Accuracy: 0.6250, MCC: 0.2492, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60798 | val 0.73406
  Epoch 011 - train 0.59057 | val 1.05763
  Classification -> best τ=0.525 (val F1=0.1607)
  Directional -> Accuracy: 0.5217, MCC: -0.0263, F1: 0.3265

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64491 | val 0.89995
  Epoch 016 - train 0.64680 | val 1.51642
  Classification -> best τ=0.490 (val F1=0.3231)
  Directional -> Accuracy: 0.5510, MCC: 0.0782, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59441 | val 0.91935
  Epoch 012 - train 0.53102 | val 1.31627
  Classification -> best τ=0.445 (val F1=0.0236)
  Directional -> Accuracy: 0.5789, MCC: 0.2092, F1: 0.6923

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55516 | val 1.78559
  Epoch 011 - train 0.62227 | val 1.60348
  Classification -> best τ=0.425 (val F1=0.2172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59966 | val 0.70129
  Epoch 014 - train 0.58291 | val 0.71177
  Classification -> best τ=0.310 (val F1=0.3838)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57160 | val 0.90904
  Epoch 013 - train 0.54897 | val 0.84939
  Classification -> best τ=0.535 (val F1=0.3140)
  Directional -> Accuracy: 0.4510, MCC: -0.0487, F1: 0.5625

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59090 | val 1.02768
  Epoch 012 - train 0.57809 | val 0.89536
  Classification -> best τ=0.530 (val F1=0.3087)
  Directional -> Accuracy: 0.5652, MCC: 0.1100, F1: 0.6809

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59717 | val 1.08256
  Epoch 011 - train 0.60139 | val 1.17243
  Classification -> best τ=0.570 (val F1=0.1291)
  Directional -> Accuracy: 0.5000, MCC: -0.0714, F1: 0.6027

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62673 | val 0.84136
  Epoch 013 - train 0.59564 | val 0.91773
  Classification -> best τ=0.575 (val F1=0.1087)
  Directional -> Accuracy: 0.4133, MCC: -0.0780, F1: 0.2903

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64286 | val 0.74718
  Epoch 012 - train 0.62128 | val 0.96650
  Classification -> best τ=0.570 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65094 | val 0.67741
  Epoch 015 - train 0.59625 | val 0.99722
  Classification -> best τ=0.420 (val F1=0.3471)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57932 | val 0.67557
  Epoch 017 - train 0.46983 | val 1.22986
  Classification -> best τ=0.475 (val F1=0.3251)
  Directional -> Accuracy: 0.4894, MCC: -0.0168, F1: 0.5385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62713 | val 0.77314
  Epoch 011 - train 0.63307 | val 0.82565
  Classification -> best τ=0.580 (val F1=0.2757)
  Directional -> Accuracy: 0.5385, MCC: 0.0959, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60728 | val 0.75421
  Epoch 013 - train 0.59606 | val 0.82539
  Classification -> best τ=0.515 (val F1=0.2981)
  Directional -> Accuracy: 0.4561, MCC: -0.0251, F1: 0.3111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61456 | val 1.01022
  Epoch 012 - train 0.60423 | val 1.13643
  Classification -> best τ=0.445 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68294 | val 0.66089
  Epoch 016 - train 0.64444 | val 0.64080
  Classification -> best τ=0.480 (val F1=0.5048)
  Directional -> Accuracy: 0.5818, MCC: 0.2311, F1: 0.4889

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61055 | val 0.73564
  Epoch 011 - train 0.57942 | val 0.80321
  Classification -> best τ=0.545 (val F1=0.0198)
  Directional -> Accuracy: 0.4000, MCC: -0.1419, F1: 0.4906

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59887 | val 0.70639
  Epoch 011 - train 0.61320 | val 0.68591
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61222 | val 0.76098
  Epoch 014 - train 0.56817 | val 0.79925
  Classification -> best τ=0.340 (val F1=0.2665)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64588 | val 0.73680
  Epoch 017 - train 0.52255 | val 1.42486
  Classification -> best τ=0.505 (val F1=0.4139)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60923 | val 0.91381
  Epoch 020 - train 0.50799 | val 0.81516
  Epoch 021 - train 0.44968 | val 0.84932
  Classification -> best τ=0.740 (val F1=0.3656)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60157 | val 0.81847
  Epoch 015 - train 0.50340 | val 1.07909
  Classification -> best τ=0.445 (val F1=0.3825)
  Directional -> Accuracy: 0.4286, MCC: -0.1083, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54414 | val 0.76677
  Epoch 013 - train 0.48490 | val 0.96570
  Classification -> best τ=0.465 (val F1=0.4100)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60241 | val 0.68819
  Epoch 013 - train 0.57652 | val 0.73848
  Classification -> best τ=0.335 (val F1=0.3593)
  Directional -> Accuracy: 0.5278, MCC: 0.0988, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62748 | val 0.97815
  Epoch 013 - train 0.57354 | val 1.14219
  Classification -> best τ=0.445 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: -0.0145, F1: 0.5769

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64303 | val 0.73699
  Epoch 011 - train 0.62920 | val 0.75459
  Classification -> best τ=0.525 (val F1=0.2665)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55894 | val 0.89575
  Epoch 017 - train 0.58411 | val 1.45100
  Classification -> best τ=0.645 (val F1=0.3260)
  Directional -> Accuracy: 0.6905, MCC: 0.4122, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56379 | val 0.85486
  Epoch 011 - train 0.55525 | val 0.70181
  Classification -> best τ=0.465 (val F1=0.1913)
  Directional -> Accuracy: 0.5536, MCC: 0.0962, F1: 0.4898

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52270 | val 1.00111
  Epoch 011 - train 0.49556 | val 1.06486
  Classification -> best τ=0.500 (val F1=0.2474)
  Directional -> Accuracy: 0.5435, MCC: 0.0891, F1: 0.5882

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59348 | val 0.82200
  Epoch 016 - train 0.50926 | val 0.66431
  Classification -> best τ=0.360 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61153 | val 0.75374
  Epoch 011 - train 0.58870 | val 0.76983
  Classification -> best τ=0.515 (val F1=0.2362)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52617 | val 0.76007
  Epoch 016 - train 0.50661 | val 1.01863
  Classification -> best τ=0.470 (val F1=0.3500)
  Directional -> Accuracy: 0.4889, MCC: -0.0134, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60218 | val 0.59972
  Epoch 019 - train 0.51289 | val 0.65394
  Classification -> best τ=0.455 (val F1=0.5601)
  Directional -> Accuracy: 0.5714, MCC: 0.0807, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56900 | val 0.67087
  Epoch 020 - train 0.45360 | val 0.74529
  Epoch 024 - train 0.39374 | val 0.88747
  Classification -> best τ=0.550 (val F1=0.4176)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61245 | val 0.68893
  Epoch 014 - train 0.53999 | val 0.68505
  Classification -> best τ=0.570 (val F1=0.1357)
  Directional -> Accuracy: 0.4000, MCC: -0.2631, F1: 0.5217

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60237 | val 1.51495
  Epoch 011 - train 0.58964 | val 1.68056
  Classification -> best τ=0.635 (val F1=0.2143)
  Directional -> Accuracy: 0.5714, MCC: 0.2566, F1: 0.6842

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58712 | val 0.96468
  Epoch 012 - train 0.56928 | val 0.77252
  Classification -> best τ=0.670 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62510 | val 0.86243
  Epoch 014 - train 0.60713 | val 0.90217
  Classification -> best τ=0.600 (val F1=0.2121)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65417 | val 0.69057

[I 2026-02-20 05:54:36,677] Trial 209 finished with value: 0.27067780370359645 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006356887278834617, 'weight_decay': 3.8838465260064364e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.282654329503985, 'early_stopping_min_delta': 0.009276963011929127}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.62640 | val 0.86649
  Classification -> best τ=0.415 (val F1=0.1768)
  Directional -> Accuracy: 0.4500, MCC: -0.0953, F1: 0.4923

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27067780370359645
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58665 | val 0.70489
  Epoch 012 - train 0.60202 | val 0.74155
  Classification -> best τ=0.440 (val F1=0.1430)
  Directional -> Accuracy: 0.5921, MCC: 0.1521, F1: 0.3922

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61811 | val 0.67539
  Epoch 012 - train 0.56709 | val 0.67836
  Classification -> best τ=0.395 (val F1=0.2285)
  Directional -> Accuracy: 0.5556, MCC: 0.0055, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60814 | val 0.67892
  Epoch 016 - train 0.51894 | val 0.99308
  Classification -> best τ=0.450 (val F1=0.3285)
  Directional -> Accuracy: 0.5435, MCC: 0.1177, F1: 0.4324

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65381 | val 0.83510
  Epoch 013 - train 0.67564 | val 0.77601
  Classification -> best τ=0.310 (val F1=0.2920)
  Directional -> Accuracy: 0.4865, MCC: -0.0031, F1: 0.4242

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61310 | val 0.65863
  Epoch 017 - train 0.57325 | val 0.98218
  Classification -> best τ=0.445 (val F1=0.4259)
  Directional -> Accuracy: 0.5800, MCC: 0.1574, F1: 0.6038

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63207 | val 0.76263
  Epoch 011 - train 0.56707 | val 0.77217
  Classification -> best τ=0.720 (val F1=0.2739)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63813 | val 0.85625
  Epoch 011 - train 0.66153 | val 1.02495
  Classification -> best τ=0.425 (val F1=0.3042)
  Directional -> Accuracy: 0.5147, MCC: 0.0683, F1: 0.5075

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59034 | val 0.77116
  Epoch 012 - train 0.57166 | val 0.77959
  Classification -> best τ=0.320 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54718 | val 0.68363
  Epoch 015 - train 0.49925 | val 0.83354
  Classification -> best τ=0.505 (val F1=0.4197)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59029 | val 0.77679
  Epoch 011 - train 0.60349 | val 0.82290
  Classification -> best τ=0.530 (val F1=0.0867)
  Directional -> Accuracy: 0.4493, MCC: -0.1099, F1: 0.3871

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62149 | val 0.99850
  Epoch 011 - train 0.61781 | val 0.92072
  Classification -> best τ=0.445 (val F1=0.3241)
  Directional -> Accuracy: 0.5306, MCC: 0.0637, F1: 0.5106

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58793 | val 0.86526
  Epoch 013 - train 0.57605 | val 1.34508
  Classification -> best τ=0.570 (val F1=0.2777)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61258 | val 0.97896
  Epoch 012 - train 0.59625 | val 1.15196
  Classification -> best τ=0.570 (val F1=0.0548)
  Directional -> Accuracy: 0.5238, MCC: 0.0123, F1: 0.3750

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63951 | val 0.60972
  Epoch 019 - train 0.57697 | val 0.62554
  Classification -> best τ=0.250 (val F1=0.4048)
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61407 | val 0.73583
  Epoch 016 - train 0.58593 | val 1.08251
  Classification -> best τ=0.640 (val F1=0.2078)
  Directional -> Accuracy: 0.5882, MCC: 0.1508, F1: 0.3226

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60701 | val 1.34176
  Epoch 013 - train 0.57440 | val 1.71970
  Classification -> best τ=0.755 (val F1=0.3104)
  Directional -> Accuracy: 0.4928, MCC: 0.0433, F1: 0.2857

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66155 | val 1.09083
  Epoch 011 - train 0.64154 | val 1.04820
  Classification -> best τ=0.520 (val F1=0.2429)
  Directional -> Accuracy: 0.5690, MCC: -0.1135, F1: 0.7191

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61003 | val 1.46844
  Epoch 013 - train 0.60085 | val 1.14243
  Classification -> best τ=0.465 (val F1=0.2173)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61676 | val 1.29689
  Epoch 014 - train 0.57628 | val 2.14434
  Classification -> best τ=0.380 (val F1=0.2843)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62930 | val 0.67484
  Epoch 018 - train 0.56036 | val 0.81245
  Classification -> best τ=0.355 (val F1=0.3838)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61101 | val 0.68667
  Epoch 014 - train 0.63861 | val 0.79526
  Classification -> best τ=0.535 (val F1=0.2800)
  Directional -> Accuracy: 0.5319, MCC: 0.0708, F1: 0.5769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64786 | val 0.81389
  Epoch 011 - train 0.66141 | val 0.91614
  Classification -> best τ=0.465 (val F1=0.1650)
  Directional -> Accuracy: 0.4615, MCC: -0.1688, F1: 0.6237

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59781 | val 0.80013
  Epoch 016 - train 0.57741 | val 0.77921
  Classification -> best τ=0.530 (val F1=0.2940)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62936 | val 0.68667
  Epoch 013 - train 0.59395 | val 0.72282
  Classification -> best τ=0.490 (val F1=0.0928)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56563 | val 0.75873
  Epoch 018 - train 0.64188 | val 0.96136
  Classification -> best τ=0.605 (val F1=0.5294)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57824 | val 1.10556
  Epoch 011 - train 0.55065 | val 1.54464
  Classification -> best τ=0.365 (val F1=0.1310)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.4737

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62415 | val 0.72791
  Epoch 011 - train 0.59584 | val 0.76779
  Classification -> best τ=0.640 (val F1=0.1217)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60599 | val 0.83118
  Epoch 012 - train 0.55053 | val 1.03472
  Classification -> best τ=0.295 (val F1=0.2945)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61987 | val 1.42156
  Epoch 013 - train 0.55846 | val 1.55079
  Classification -> best τ=0.495 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64237 | val 0.89022
  Epoch 013 - train 0.54248 | val 1.26100
  Classification -> best τ=0.705 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58490 | val 0.90620
  Epoch 013 - train 0.54446 | val 0.70472
  Classification -> best τ=0.480 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62310 | val 0.84644
  Epoch 012 - train 0.55275 | val 0.96636
  Classification -> best τ=0.435 (val F1=0.2904)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60891 | val 0.83577
  Epoch 016 - train 0.63959 | val 0.82488
  Classification -> best τ=0.380 (val F1=0.3380)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60817 | val 1.18183
  Epoch 013 - train 0.56976 | val 1.62232
  Classification -> best τ=0.310 (val F1=0.3742)
  Directional -> Accuracy: 0.5581, MCC: 0.1154, F1: 0.4571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64861 | val 0.80831
  Epoch 012 - train 0.60680 | val 0.89483
  Classification -> best τ=0.305 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52482 | val 0.92375
  Epoch 012 - train 0.55140 | val 1.11034
  Classification -> best τ=0.515 (val F1=0.1970)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.3784

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65703 | val 0.71981
  Epoch 020 - train 0.50868 | val 0.84377
  Epoch 025 - train 0.43093 | val 0.79568
  Classification -> best τ=0.495 (val F1=0.3360)
  Directional -> Accuracy: 0.5000, MCC: -0.0103, F1: 0.4400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48099 | val 1.34566
  Epoch 014 - train 0.45918 | val 0.93389
  Classification -> best τ=0.500 (val F1=0.2441)
  Directional -> Accuracy: 0.4783, MCC: 0.0706, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58900 | val 0.68933
  Epoch 017 - train 0.51817 | val 0.81676
  Classification -> best τ=0.595 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61075 | val 0.65268
  Epoch 011 - train 0.59884 | val 0.67714
  Classification -> best τ=0.480 (val F1=0.4564)
  Directional -> Accuracy: 0.4730, MCC: -0.0741, F1: 0.6355

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56437 | val 0.82165
  Epoch 012 - train 0.54462 | val 0.92390
  Classification -> best τ=0.375 (val F1=0.3371)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60905 | val 0.61190
  Epoch 020 - train 0.56699 | val 0.69266
  Epoch 030 - train 0.33709 | val 0.46301
  Epoch 040 - train 0.24498 | val 0.72209
  Epoch 045 - train 0.13902 | val 0.82309
  Classification -> best τ=0.505 (val F1=0.7566)
  Directional -> Accuracy: 0.6429, MCC: 0.2501, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60607 | val 0.75328
  Epoch 014 - train 0.56562 | val 0.77931
  Classification -> best τ=0.605 (val F1=0.5689)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59065 | val 0.73822
  Epoch 011 - train 0.60570 | val 0.76103
  Classification -> best τ=0.615 (val F1=0.2132)
  Directional -> Accuracy: 0.3818, MCC: -0.2327, F1: 0.3929

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60198 | val 1.25660
  Epoch 011 - train 0.57320 | val 1.16381
  Classification -> best τ=0.575 (val F1=0.2143)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64370 | val 0.69677
  Epoch 020 - train 0.53555 | val 0.91607
  Epoch 021 - train 0.52110 | val 1.07027
  Classification -> best τ=0.700 (val F1=0.2790)
  Directional -> Accuracy: 0.6038, MCC: 0.2069, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58902 | val 0.97190
  Epoch 014 - train 0.55705 | val 1.00264
  Classification -> best τ=0.635 (val F1=0.0782)
  Directional -> Accuracy: 0.4909, MCC: -0.0687, F1: 0.6216

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59358 | val 0.68738

[I 2026-02-20 05:55:36,377] Trial 210 finished with value: 0.29098623928596284 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009861347406440022, 'weight_decay': 1.9330791211257735e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1868222686256462, 'early_stopping_min_delta': 0.00953920670306816}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.55348 | val 0.68820
  Classification -> best τ=0.415 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0089, F1: 0.1212

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29098623928596284
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62002 | val 0.69044
  Epoch 011 - train 0.60172 | val 0.67575
  Classification -> best τ=0.305 (val F1=0.1328)
  Directional -> Accuracy: 0.4474, MCC: -0.0249, F1: 0.6038

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58157 | val 0.69595
  Epoch 014 - train 0.59781 | val 0.73003
  Classification -> best τ=0.420 (val F1=0.3513)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58286 | val 0.71847
  Epoch 020 - train 0.43628 | val 0.69082
  Epoch 021 - train 0.37268 | val 1.22756
  Classification -> best τ=0.610 (val F1=0.3482)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63645 | val 0.84000
  Epoch 013 - train 0.63421 | val 1.47878
  Classification -> best τ=0.440 (val F1=0.1235)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57226 | val 0.82368
  Epoch 015 - train 0.52926 | val 1.05328
  Classification -> best τ=0.535 (val F1=0.4247)
  Directional -> Accuracy: 0.6400, MCC: 0.3524, F1: 0.5263

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59703 | val 0.79384
  Epoch 013 - train 0.56040 | val 0.75304
  Classification -> best τ=0.520 (val F1=0.1463)
  Directional -> Accuracy: 0.4130, MCC: -0.1860, F1: 0.5424

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68598 | val 0.71928
  Epoch 012 - train 0.68812 | val 0.74188
  Classification -> best τ=0.510 (val F1=0.4308)
  Directional -> Accuracy: 0.5441, MCC: 0.1157, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52490 | val 0.96769
  Epoch 013 - train 0.57187 | val 1.07236
  Classification -> best τ=0.455 (val F1=0.0668)
  Directional -> Accuracy: 0.4524, MCC: -0.1876, F1: 0.2069

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64515 | val 0.72367
  Epoch 012 - train 0.61634 | val 0.70826
  Classification -> best τ=0.450 (val F1=0.2678)
  Directional -> Accuracy: 0.6250, MCC: 0.2308, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60665 | val 0.72029
  Epoch 011 - train 0.60571 | val 0.74946
  Classification -> best τ=0.430 (val F1=0.0867)
  Directional -> Accuracy: 0.3768, MCC: -0.2504, F1: 0.5474

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67496 | val 0.72593
  Epoch 017 - train 0.59558 | val 0.96071
  Classification -> best τ=0.415 (val F1=0.2204)
  Directional -> Accuracy: 0.4898, MCC: 0.0370, F1: 0.5763

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55328 | val 2.00352
  Epoch 012 - train 0.52087 | val 1.43164
  Classification -> best τ=0.610 (val F1=0.1512)
  Directional -> Accuracy: 0.5263, MCC: 0.0561, F1: 0.4906

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56026 | val 1.09696
  Epoch 012 - train 0.51891 | val 1.11626
  Classification -> best τ=0.595 (val F1=0.2522)
  Directional -> Accuracy: 0.5000, MCC: 0.0754, F1: 0.6038

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62984 | val 0.64026
  Epoch 011 - train 0.65528 | val 0.64004
  Classification -> best τ=0.420 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59592 | val 0.71787
  Epoch 011 - train 0.56158 | val 0.70951
  Classification -> best τ=0.530 (val F1=0.3333)
  Directional -> Accuracy: 0.4510, MCC: -0.0858, F1: 0.4615

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61531 | val 0.93185
  Epoch 012 - train 0.57771 | val 1.33052
  Classification -> best τ=0.370 (val F1=0.2341)
  Directional -> Accuracy: 0.5652, MCC: 0.1256, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62745 | val 1.00691
  Epoch 011 - train 0.62388 | val 1.00051
  Classification -> best τ=0.500 (val F1=0.2285)
  Directional -> Accuracy: 0.5172, MCC: 0.0796, F1: 0.5333

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61342 | val 2.24424
  Epoch 012 - train 0.65055 | val 1.99811
  Classification -> best τ=0.525 (val F1=0.1592)
  Directional -> Accuracy: 0.5867, MCC: -0.0278, F1: 0.7350

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62672 | val 0.87728
  Epoch 013 - train 0.59880 | val 1.01498
  Classification -> best τ=0.460 (val F1=0.3421)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66786 | val 0.74184
  Epoch 011 - train 0.67843 | val 0.78425
  Classification -> best τ=0.475 (val F1=0.2271)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61548 | val 0.73220
  Epoch 011 - train 0.60675 | val 0.71199
  Classification -> best τ=0.555 (val F1=0.2359)
  Directional -> Accuracy: 0.5745, MCC: 0.1381, F1: 0.6296

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65642 | val 0.87141
  Epoch 015 - train 0.60916 | val 0.93097
  Classification -> best τ=0.535 (val F1=0.1514)
  Directional -> Accuracy: 0.5077, MCC: 0.0152, F1: 0.5152

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64541 | val 0.84807
  Epoch 012 - train 0.64348 | val 1.14609
  Classification -> best τ=0.635 (val F1=0.3550)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59564 | val 0.74761
  Epoch 011 - train 0.62637 | val 0.73652
  Classification -> best τ=0.385 (val F1=0.1348)
  Directional -> Accuracy: 0.5231, MCC: 0.1024, F1: 0.6353

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58267 | val 0.79323
  Epoch 015 - train 0.51492 | val 0.96258
  Classification -> best τ=0.490 (val F1=0.5644)
  Directional -> Accuracy: 0.4909, MCC: 0.0402, F1: 0.3333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60586 | val 1.41182
  Epoch 012 - train 0.53712 | val 1.67946
  Classification -> best τ=0.490 (val F1=0.1099)
  Directional -> Accuracy: 0.5778, MCC: 0.3149, F1: 0.6545

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61526 | val 0.69582
  Epoch 016 - train 0.59228 | val 0.70634
  Classification -> best τ=0.590 (val F1=0.1353)
  Directional -> Accuracy: 0.5476, MCC: 0.0700, F1: 0.6122

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59152 | val 0.94276
  Epoch 015 - train 0.54278 | val 1.08785
  Classification -> best τ=0.375 (val F1=0.2371)
  Directional -> Accuracy: 0.6071, MCC: 0.1883, F1: 0.6857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64216 | val 0.72881
  Epoch 013 - train 0.63953 | val 0.73264
  Classification -> best τ=0.560 (val F1=0.4063)
  Directional -> Accuracy: 0.4750, MCC: -0.0161, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58450 | val 0.85778
  Epoch 013 - train 0.54836 | val 1.07392
  Classification -> best τ=0.615 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55449 | val 0.75017
  Epoch 020 - train 0.42248 | val 0.66955
  Epoch 022 - train 0.43252 | val 0.72807
  Classification -> best τ=0.385 (val F1=0.2357)
  Directional -> Accuracy: 0.4762, MCC: 0.0214, F1: 0.2667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57381 | val 0.67594
  Epoch 015 - train 0.56725 | val 0.85838
  Classification -> best τ=0.370 (val F1=0.3789)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62802 | val 0.66801
  Epoch 012 - train 0.61509 | val 0.71223
  Classification -> best τ=0.415 (val F1=0.3366)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62332 | val 1.02929
  Epoch 012 - train 0.64048 | val 0.87769
  Classification -> best τ=0.540 (val F1=0.4366)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60931 | val 0.75163
  Epoch 011 - train 0.62612 | val 0.78615
  Classification -> best τ=0.480 (val F1=0.3865)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55465 | val 0.88830
  Epoch 013 - train 0.49626 | val 1.08110
  Classification -> best τ=0.485 (val F1=0.3001)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61429 | val 0.79322
  Epoch 012 - train 0.59495 | val 0.73384
  Classification -> best τ=0.425 (val F1=0.2724)
  Directional -> Accuracy: 0.5000, MCC: -0.0103, F1: 0.4400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52399 | val 1.08717
  Epoch 012 - train 0.49310 | val 1.36897
  Classification -> best τ=0.505 (val F1=0.2441)
  Directional -> Accuracy: 0.4348, MCC: -0.0505, F1: 0.3810

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56628 | val 0.65481
  Epoch 018 - train 0.42348 | val 0.72530
  Classification -> best τ=0.610 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65070 | val 0.70651
  Epoch 013 - train 0.60637 | val 0.69113
  Classification -> best τ=0.560 (val F1=0.3584)
  Directional -> Accuracy: 0.5405, MCC: 0.0792, F1: 0.5143

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56236 | val 0.76077
  Epoch 012 - train 0.54703 | val 0.80109
  Classification -> best τ=0.410 (val F1=0.3500)
  Directional -> Accuracy: 0.5778, MCC: 0.1545, F1: 0.5957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64307 | val 0.73099
  Epoch 015 - train 0.61495 | val 0.68935
  Classification -> best τ=0.565 (val F1=0.6667)
  Directional -> Accuracy: 0.5952, MCC: 0.1487, F1: 0.6792

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61500 | val 0.59041
  Epoch 016 - train 0.56191 | val 0.66385
  Classification -> best τ=0.490 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59971 | val 0.74514
  Epoch 015 - train 0.56270 | val 1.28471
  Classification -> best τ=0.630 (val F1=0.2704)
  Directional -> Accuracy: 0.5455, MCC: 0.2390, F1: 0.3243

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55010 | val 1.68918
  Epoch 011 - train 0.54331 | val 2.33630
  Classification -> best τ=0.680 (val F1=0.2143)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61138 | val 1.36631
  Epoch 011 - train 0.57571 | val 1.62706
  Classification -> best τ=0.400 (val F1=0.2155)
  Directional -> Accuracy: 0.6038, MCC: 0.2082, F1: 0.6441

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57165 | val 1.09560
  Epoch 011 - train 0.55124 | val 1.11987
  Classification -> best τ=0.570 (val F1=0.1166)
  Directional -> Accuracy: 0.4545, MCC: -0.1254, F1: 0.5588

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 05:56:29,504] Trial 211 finished with value: 0.27943374310746366 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008927488362162015, 'weight_decay': 1.1744899338090185e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.163232793631244, 'early_stopping_min_delta': 0.009494753417837164}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 010 - train 0.58621 | val 0.99234
  Epoch 011 - train 0.63021 | val 0.85702
  Classification -> best τ=0.475 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27943374310746366
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60162 | val 0.67152
  Epoch 018 - train 0.55101 | val 1.05723
  Classification -> best τ=0.455 (val F1=0.2919)
  Directional -> Accuracy: 0.6184, MCC: 0.2920, F1: 0.6588

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56263 | val 0.67650
  Epoch 020 - train 0.43760 | val 0.71816
  Epoch 021 - train 0.39758 | val 0.69634
  Classification -> best τ=0.365 (val F1=0.3022)
  Directional -> Accuracy: 0.4889, MCC: 0.0020, F1: 0.4889

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65041 | val 0.79083
  Epoch 013 - train 0.54790 | val 0.80650
  Classification -> best τ=0.555 (val F1=0.2727)
  Directional -> Accuracy: 0.3913, MCC: -0.2496, F1: 0.1250

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64738 | val 1.10637
  Epoch 012 - train 0.64978 | val 0.83139
  Classification -> best τ=0.565 (val F1=0.0088)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59664 | val 0.87901
  Epoch 017 - train 0.55639 | val 0.76484
  Classification -> best τ=0.495 (val F1=0.4753)
  Directional -> Accuracy: 0.5200, MCC: 0.0712, F1: 0.3684

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58733 | val 0.70907
  Epoch 012 - train 0.60235 | val 0.81440
  Classification -> best τ=0.585 (val F1=0.2593)
  Directional -> Accuracy: 0.5652, MCC: 0.1348, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63705 | val 0.86639
  Epoch 012 - train 0.61922 | val 1.20284
  Classification -> best τ=0.505 (val F1=0.1195)
  Directional -> Accuracy: 0.4118, MCC: -0.0378, F1: 0.5349

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57695 | val 0.86362
  Epoch 012 - train 0.50597 | val 0.79545
  Classification -> best τ=0.190 (val F1=0.2453)
  Directional -> Accuracy: 0.4524, MCC: -0.1635, F1: 0.2581

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55673 | val 0.66884
  Epoch 013 - train 0.52392 | val 0.67351
  Classification -> best τ=0.515 (val F1=0.2822)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64248 | val 0.80210
  Epoch 011 - train 0.57600 | val 0.79946
  Classification -> best τ=0.540 (val F1=0.0237)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63404 | val 0.75637
  Epoch 013 - train 0.62082 | val 0.97303
  Classification -> best τ=0.345 (val F1=0.1199)
  Directional -> Accuracy: 0.4286, MCC: -0.1024, F1: 0.5758

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53044 | val 1.10950
  Epoch 011 - train 0.50590 | val 1.31207
  Classification -> best τ=0.500 (val F1=0.0937)
  Directional -> Accuracy: 0.5614, MCC: 0.1950, F1: 0.3243

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56885 | val 1.35256
  Epoch 011 - train 0.53860 | val 1.46130
  Classification -> best τ=0.335 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65032 | val 0.66962
  Epoch 013 - train 0.61721 | val 0.69124
  Classification -> best τ=0.370 (val F1=0.3669)
  Directional -> Accuracy: 0.5833, MCC: 0.2596, F1: 0.6988

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59789 | val 0.69859
  Epoch 011 - train 0.56762 | val 0.80117
  Classification -> best τ=0.540 (val F1=0.3333)
  Directional -> Accuracy: 0.4706, MCC: -0.0497, F1: 0.4706

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60640 | val 0.63612
  Epoch 012 - train 0.55715 | val 0.72082
  Classification -> best τ=0.525 (val F1=0.3035)
  Directional -> Accuracy: 0.5797, MCC: 0.1428, F1: 0.6588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59906 | val 1.57939
  Epoch 013 - train 0.54764 | val 2.30490
  Classification -> best τ=0.640 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63542 | val 0.97042
  Epoch 012 - train 0.58202 | val 0.87913
  Classification -> best τ=0.475 (val F1=0.1834)
  Directional -> Accuracy: 0.6000, MCC: 0.0891, F1: 0.7222

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69743 | val 0.75600
  Epoch 018 - train 0.54980 | val 1.71386
  Classification -> best τ=0.345 (val F1=0.2522)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60393 | val 0.68934
  Epoch 015 - train 0.59275 | val 0.96766
  Classification -> best τ=0.525 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64028 | val 0.70816
  Epoch 011 - train 0.62015 | val 0.70308
  Classification -> best τ=0.505 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66284 | val 0.73441
  Epoch 011 - train 0.62357 | val 1.01670
  Classification -> best τ=0.480 (val F1=0.2673)
  Directional -> Accuracy: 0.4308, MCC: -0.1460, F1: 0.4932

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62509 | val 0.95653
  Epoch 012 - train 0.58336 | val 1.10815
  Classification -> best τ=0.740 (val F1=0.3144)
  Directional -> Accuracy: 0.5263, MCC: 0.1434, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67531 | val 1.06519
  Epoch 011 - train 0.64782 | val 1.00464
  Classification -> best τ=0.480 (val F1=0.1415)
  Directional -> Accuracy: 0.6769, MCC: 0.3517, F1: 0.6557

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67942 | val 0.65445
  Epoch 017 - train 0.57118 | val 0.68787
  Classification -> best τ=0.445 (val F1=0.4524)
  Directional -> Accuracy: 0.6182, MCC: 0.2792, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54813 | val 1.47080
  Epoch 011 - train 0.56713 | val 1.31884
  Classification -> best τ=0.455 (val F1=0.2935)
  Directional -> Accuracy: 0.5778, MCC: 0.3149, F1: 0.6545

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62021 | val 0.71654
  Epoch 013 - train 0.61041 | val 0.69994
  Classification -> best τ=0.610 (val F1=0.1876)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64950 | val 0.74141
  Epoch 011 - train 0.64824 | val 0.74949
  Classification -> best τ=0.445 (val F1=0.1387)
  Directional -> Accuracy: 0.5536, MCC: 0.2311, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57040 | val 0.66779
  Epoch 018 - train 0.44680 | val 1.03521
  Classification -> best τ=0.420 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61168 | val 1.17027
  Epoch 012 - train 0.58788 | val 1.12485
  Classification -> best τ=0.485 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61459 | val 0.92866
  Epoch 011 - train 0.56288 | val 0.84256
  Classification -> best τ=0.535 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53640 | val 1.00566
  Epoch 012 - train 0.50312 | val 1.06870
  Classification -> best τ=0.480 (val F1=0.3718)
  Directional -> Accuracy: 0.5306, MCC: 0.0388, F1: 0.6230

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63502 | val 0.64737
  Epoch 018 - train 0.54089 | val 1.02667
  Classification -> best τ=0.650 (val F1=0.3568)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60441 | val 0.81704
  Epoch 011 - train 0.58217 | val 0.86213
  Classification -> best τ=0.560 (val F1=0.2643)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63720 | val 0.93788
  Epoch 011 - train 0.64207 | val 0.75228
  Classification -> best τ=0.420 (val F1=0.3787)
  Directional -> Accuracy: 0.5606, MCC: 0.0162, F1: 0.6947

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52369 | val 0.89059
  Epoch 014 - train 0.45488 | val 1.36398
  Classification -> best τ=0.360 (val F1=0.3218)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51441 | val 0.91834
  Epoch 012 - train 0.50607 | val 1.12966
  Classification -> best τ=0.465 (val F1=0.2622)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.4828

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60603 | val 0.76154
  Epoch 012 - train 0.52970 | val 0.93883
  Classification -> best τ=0.365 (val F1=0.2118)
  Directional -> Accuracy: 0.5652, MCC: -0.1709, F1: 0.7222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59266 | val 0.65810
  Epoch 020 - train 0.47561 | val 0.67009
  Epoch 028 - train 0.36459 | val 0.74511
  Classification -> best τ=0.285 (val F1=0.4973)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63131 | val 0.69844
  Epoch 018 - train 0.58795 | val 0.80429
  Classification -> best τ=0.350 (val F1=0.3270)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58822 | val 0.77307
  Epoch 013 - train 0.53227 | val 0.80490
  Classification -> best τ=0.490 (val F1=0.3287)
  Directional -> Accuracy: 0.5778, MCC: 0.1678, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58418 | val 0.67599
  Epoch 020 - train 0.46205 | val 0.63368
  Epoch 028 - train 0.29500 | val 0.97902
  Classification -> best τ=0.540 (val F1=0.5784)
  Directional -> Accuracy: 0.5714, MCC: 0.1376, F1: 0.6087

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61200 | val 0.63042
  Epoch 020 - train 0.42882 | val 0.60608
  Epoch 024 - train 0.33379 | val 0.89909
  Classification -> best τ=0.555 (val F1=0.5514)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61851 | val 1.06496
  Epoch 011 - train 0.60366 | val 0.87550
  Classification -> best τ=0.580 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56813 | val 1.48077
  Epoch 011 - train 0.58836 | val 1.85342
  Classification -> best τ=0.445 (val F1=0.3236)
  Directional -> Accuracy: 0.5357, MCC: 0.0930, F1: 0.6061

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62629 | val 0.90251
  Epoch 012 - train 0.60958 | val 0.96888
  Classification -> best τ=0.540 (val F1=0.2317)
  Directional -> Accuracy: 0.5472, MCC: 0.1039, F1: 0.4783

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61586 | val 0.85599
  Epoch 011 - train 0.57601 | val 0.79335
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59387 | val 0.71456

[I 2026-02-20 05:57:25,392] Trial 212 finished with value: 0.2666784768247065 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008308418545631276, 'weight_decay': 1.0416464278310968e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1649636790773712, 'early_stopping_min_delta': 0.009590624662933563}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.57995 | val 0.77043
  Classification -> best τ=0.385 (val F1=0.1825)
  Directional -> Accuracy: 0.5000, MCC: 0.0398, F1: 0.6341

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2666784768247065
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62110 | val 0.67978
  Epoch 012 - train 0.61036 | val 0.72786
  Classification -> best τ=0.425 (val F1=0.2034)
  Directional -> Accuracy: 0.5921, MCC: 0.1649, F1: 0.5079

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54148 | val 0.70784
  Epoch 012 - train 0.53714 | val 0.76383
  Classification -> best τ=0.390 (val F1=0.2829)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57808 | val 0.75616
  Epoch 020 - train 0.55223 | val 1.18483
  Epoch 021 - train 0.56454 | val 1.09180
  Classification -> best τ=0.590 (val F1=0.3482)
  Directional -> Accuracy: 0.4565, MCC: -0.0763, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66283 | val 0.77750
  Epoch 012 - train 0.62606 | val 0.83447
  Classification -> best τ=0.440 (val F1=0.2014)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57855 | val 0.75750
  Epoch 012 - train 0.54807 | val 1.06303
  Classification -> best τ=0.480 (val F1=0.4947)
  Directional -> Accuracy: 0.7600, MCC: 0.5194, F1: 0.7778

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63550 | val 0.75705
  Epoch 011 - train 0.60238 | val 0.83211
  Classification -> best τ=0.450 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64231 | val 0.82309
  Epoch 011 - train 0.63116 | val 0.81312
  Classification -> best τ=0.450 (val F1=0.3209)
  Directional -> Accuracy: 0.5441, MCC: 0.2144, F1: 0.5974

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53398 | val 1.00215
  Epoch 012 - train 0.54450 | val 1.17833
  Classification -> best τ=0.365 (val F1=0.2100)
  Directional -> Accuracy: 0.5476, MCC: -0.0534, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56576 | val 0.83549
  Epoch 014 - train 0.50832 | val 0.97307
  Classification -> best τ=0.530 (val F1=0.3441)
  Directional -> Accuracy: 0.6875, MCC: 0.3580, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60164 | val 0.73810
  Epoch 011 - train 0.59101 | val 0.83130
  Classification -> best τ=0.430 (val F1=0.1858)
  Directional -> Accuracy: 0.3768, MCC: -0.2504, F1: 0.5474

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64661 | val 0.85828
  Epoch 020 - train 0.62147 | val 1.69730
  Epoch 023 - train 0.58404 | val 0.88416
  Classification -> best τ=0.530 (val F1=0.4415)
  Directional -> Accuracy: 0.6122, MCC: 0.2027, F1: 0.4242

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54308 | val 1.06480
  Epoch 012 - train 0.53717 | val 0.98004
  Classification -> best τ=0.605 (val F1=0.1434)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60897 | val 1.57403
  Epoch 012 - train 0.54986 | val 1.88784
  Classification -> best τ=0.380 (val F1=0.1658)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59565 | val 0.79808
  Epoch 015 - train 0.54954 | val 0.83465
  Classification -> best τ=0.445 (val F1=0.3584)
  Directional -> Accuracy: 0.5333, MCC: 0.0707, F1: 0.6000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58941 | val 0.72272
  Epoch 016 - train 0.55132 | val 0.78920
  Classification -> best τ=0.595 (val F1=0.2078)
  Directional -> Accuracy: 0.6275, MCC: 0.2472, F1: 0.4242

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60763 | val 0.77697
  Epoch 016 - train 0.52337 | val 0.93326
  Classification -> best τ=0.675 (val F1=0.2997)
  Directional -> Accuracy: 0.5362, MCC: 0.0964, F1: 0.4839

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62442 | val 1.14842
  Epoch 011 - train 0.59993 | val 1.36547
  Classification -> best τ=0.520 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60321 | val 1.55095
  Epoch 012 - train 0.63885 | val 1.67674
  Classification -> best τ=0.655 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60649 | val 1.25132
  Epoch 014 - train 0.57922 | val 1.86415
  Classification -> best τ=0.395 (val F1=0.3140)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62824 | val 0.69775
  Epoch 019 - train 0.60091 | val 0.72571
  Classification -> best τ=0.295 (val F1=0.3090)
  Directional -> Accuracy: 0.3649, MCC: -0.2530, F1: 0.3188

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62824 | val 0.68772
  Epoch 020 - train 0.57534 | val 0.65797
  Epoch 030 - train 0.50388 | val 0.63293
  Epoch 040 - train 0.35852 | val 0.88455
  Classification -> best τ=0.395 (val F1=0.4104)
  Directional -> Accuracy: 0.4468, MCC: 0.1299, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64681 | val 0.75958
  Epoch 011 - train 0.63405 | val 0.82222
  Classification -> best τ=0.400 (val F1=0.1650)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63215 | val 0.72369
  Epoch 015 - train 0.56220 | val 0.86258
  Classification -> best τ=0.505 (val F1=0.3604)
  Directional -> Accuracy: 0.5088, MCC: 0.0681, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61456 | val 0.78219
  Epoch 011 - train 0.57856 | val 0.90196
  Classification -> best τ=0.460 (val F1=0.0076)
  Directional -> Accuracy: 0.5077, MCC: 0.0020, F1: 0.4074

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57158 | val 0.68284
  Epoch 017 - train 0.50422 | val 1.13356
  Classification -> best τ=0.510 (val F1=0.4399)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53425 | val 0.82188
  Epoch 011 - train 0.52095 | val 0.87744
  Classification -> best τ=0.475 (val F1=0.2935)
  Directional -> Accuracy: 0.4444, MCC: -0.1469, F1: 0.3243

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57860 | val 0.68997
  Epoch 011 - train 0.57959 | val 0.71289
  Classification -> best τ=0.595 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.6316

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62913 | val 0.79114
  Epoch 012 - train 0.58864 | val 0.83331
  Classification -> best τ=0.360 (val F1=0.2892)
  Directional -> Accuracy: 0.5714, MCC: 0.1883, F1: 0.5200

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57488 | val 0.90907
  Epoch 015 - train 0.51133 | val 0.78879
  Classification -> best τ=0.435 (val F1=0.3518)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59347 | val 0.90984
  Epoch 012 - train 0.59311 | val 0.96762
  Classification -> best τ=0.620 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58686 | val 0.88671
  Epoch 017 - train 0.43372 | val 2.03805
  Classification -> best τ=0.615 (val F1=0.3039)
  Directional -> Accuracy: 0.4762, MCC: -0.0123, F1: 0.3889

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59487 | val 0.65636
  Epoch 014 - train 0.54570 | val 0.77705
  Classification -> best τ=0.455 (val F1=0.4467)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62836 | val 0.69018
  Epoch 011 - train 0.60390 | val 0.68902
  Classification -> best τ=0.385 (val F1=0.3346)
  Directional -> Accuracy: 0.5000, MCC: 0.0472, F1: 0.4194

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63808 | val 0.95839
  Epoch 012 - train 0.61473 | val 1.18769
  Classification -> best τ=0.630 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63326 | val 1.02340
  Epoch 011 - train 0.64312 | val 0.89351
  Classification -> best τ=0.400 (val F1=0.3787)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60735 | val 0.75910
  Epoch 012 - train 0.55432 | val 0.85972
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54135 | val 0.80071
  Epoch 012 - train 0.55612 | val 0.87318
  Classification -> best τ=0.505 (val F1=0.1886)
  Directional -> Accuracy: 0.4821, MCC: -0.0384, F1: 0.4528

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56837 | val 1.18542
  Epoch 011 - train 0.53611 | val 1.08442
  Classification -> best τ=0.445 (val F1=0.3749)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57490 | val 0.65492
  Epoch 020 - train 0.41336 | val 0.81401
  Epoch 021 - train 0.38566 | val 0.78641
  Classification -> best τ=0.330 (val F1=0.4973)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61109 | val 0.76118
  Epoch 011 - train 0.57521 | val 0.77932
  Classification -> best τ=0.405 (val F1=0.3823)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55980 | val 0.74489
  Epoch 011 - train 0.52592 | val 0.80413
  Classification -> best τ=0.490 (val F1=0.2767)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58078 | val 0.70792
  Epoch 020 - train 0.46587 | val 0.90167
  Epoch 024 - train 0.49598 | val 0.83781
  Classification -> best τ=0.300 (val F1=0.4588)
  Directional -> Accuracy: 0.6190, MCC: 0.2582, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57894 | val 0.59906
  Epoch 020 - train 0.41188 | val 0.79919
  Classification -> best τ=0.505 (val F1=0.6080)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63555 | val 0.69920
  Epoch 011 - train 0.61852 | val 0.69597
  Classification -> best τ=0.635 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62137 | val 1.53921
  Epoch 011 - train 0.58904 | val 1.46042
  Classification -> best τ=0.560 (val F1=0.2143)
  Directional -> Accuracy: 0.5536, MCC: 0.1279, F1: 0.2424

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62853 | val 0.76420
  Epoch 014 - train 0.55662 | val 0.96962
  Classification -> best τ=0.595 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1729, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58521 | val 0.89322
  Epoch 011 - train 0.59885 | val 0.77742
  Classification -> best τ=0.470 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64824 | val 0.69561

[I 2026-02-20 05:58:21,079] Trial 213 finished with value: 0.2942849625530746 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007129412460668156, 'weight_decay': 1.4832472525674821e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1734314369089742, 'early_stopping_min_delta': 0.009929349670089953}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.58626 | val 0.67520
  Classification -> best τ=0.430 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0062, F1: 0.0645

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2942849625530746
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60736 | val 0.85500
  Epoch 013 - train 0.57031 | val 0.90776
  Classification -> best τ=0.540 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60140 | val 0.69110
  Epoch 015 - train 0.56175 | val 0.67972
  Classification -> best τ=0.395 (val F1=0.2826)
  Directional -> Accuracy: 0.6444, MCC: 0.2619, F1: 0.7037

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63265 | val 0.69926
  Epoch 012 - train 0.58276 | val 0.92908
  Classification -> best τ=0.515 (val F1=0.3693)
  Directional -> Accuracy: 0.5870, MCC: 0.1695, F1: 0.6545

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63037 | val 0.93540
  Epoch 012 - train 0.66750 | val 0.97899
  Classification -> best τ=0.425 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55864 | val 0.80322
  Epoch 013 - train 0.53346 | val 0.97135
  Classification -> best τ=0.510 (val F1=0.4782)
  Directional -> Accuracy: 0.6600, MCC: 0.3320, F1: 0.7213

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59812 | val 0.81385
  Epoch 011 - train 0.59850 | val 0.98563
  Classification -> best τ=0.470 (val F1=0.3069)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64583 | val 0.77887
  Epoch 011 - train 0.62841 | val 1.02700
  Classification -> best τ=0.480 (val F1=0.2140)
  Directional -> Accuracy: 0.5294, MCC: 0.1704, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49812 | val 1.16188
  Epoch 011 - train 0.50465 | val 0.90896
  Classification -> best τ=0.505 (val F1=0.0679)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.5385

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59223 | val 0.74169
  Epoch 012 - train 0.58106 | val 0.78579
  Classification -> best τ=0.545 (val F1=0.2764)
  Directional -> Accuracy: 0.6250, MCC: 0.2492, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59926 | val 0.71442
  Epoch 011 - train 0.58272 | val 0.74484
  Classification -> best τ=0.480 (val F1=0.1304)
  Directional -> Accuracy: 0.4203, MCC: -0.1179, F1: 0.4595

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62075 | val 0.75510
  Epoch 011 - train 0.66890 | val 0.95342
  Classification -> best τ=0.430 (val F1=0.1828)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57399 | val 0.75361
  Epoch 012 - train 0.54980 | val 1.51523
  Classification -> best τ=0.540 (val F1=0.1009)
  Directional -> Accuracy: 0.5263, MCC: 0.0503, F1: 0.6197

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56591 | val 1.74631
  Epoch 011 - train 0.60620 | val 2.12458
  Classification -> best τ=0.495 (val F1=0.2777)
  Directional -> Accuracy: 0.5238, MCC: 0.0478, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58139 | val 0.64925
  Epoch 019 - train 0.55342 | val 0.97994
  Classification -> best τ=0.460 (val F1=0.3558)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55626 | val 1.12831
  Epoch 011 - train 0.53472 | val 0.91385
  Classification -> best τ=0.450 (val F1=0.0211)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58826 | val 0.83528
  Epoch 012 - train 0.56643 | val 1.07066
  Classification -> best τ=0.345 (val F1=0.1823)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62264 | val 1.10839
  Epoch 011 - train 0.60199 | val 1.06730
  Classification -> best τ=0.615 (val F1=0.1913)
  Directional -> Accuracy: 0.3966, MCC: -0.0131, F1: 0.1463

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62574 | val 0.78141
  Epoch 011 - train 0.60129 | val 1.28392
  Classification -> best τ=0.450 (val F1=0.2537)
  Directional -> Accuracy: 0.5733, MCC: 0.0000, F1: 0.7091

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65197 | val 0.68222
  Epoch 013 - train 0.61014 | val 1.22319
  Classification -> best τ=0.410 (val F1=0.3421)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64860 | val 0.70527
  Epoch 015 - train 0.62785 | val 0.69854
  Classification -> best τ=0.410 (val F1=0.3153)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59609 | val 0.70110
  Epoch 019 - train 0.44939 | val 1.26042
  Classification -> best τ=0.365 (val F1=0.3678)
  Directional -> Accuracy: 0.5319, MCC: -0.1702, F1: 0.6857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63517 | val 0.91901
  Epoch 012 - train 0.61480 | val 0.79099
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59004 | val 0.79234
  Epoch 012 - train 0.59491 | val 0.91464
  Classification -> best τ=0.545 (val F1=0.2750)
  Directional -> Accuracy: 0.5439, MCC: 0.0338, F1: 0.6486

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65536 | val 0.94731
  Epoch 012 - train 0.59210 | val 0.76032
  Classification -> best τ=0.480 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.1166, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57037 | val 0.70488
  Epoch 019 - train 0.46098 | val 0.92410
  Classification -> best τ=0.695 (val F1=0.5644)
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54110 | val 1.51671
  Epoch 011 - train 0.55113 | val 1.49335
  Classification -> best τ=0.510 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: -0.2021, F1: 0.2778

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60769 | val 0.70361
  Epoch 011 - train 0.58132 | val 0.71426
  Classification -> best τ=0.525 (val F1=0.1452)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63181 | val 0.69972
  Epoch 011 - train 0.62297 | val 0.69332
  Classification -> best τ=0.530 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62248 | val 0.74761
  Epoch 020 - train 0.45183 | val 0.78969
  Epoch 027 - train 0.36904 | val 1.52285
  Classification -> best τ=0.240 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61880 | val 0.81289
  Epoch 012 - train 0.60781 | val 0.78243
  Classification -> best τ=0.580 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56536 | val 0.98134
  Epoch 014 - train 0.58639 | val 1.23449
  Classification -> best τ=0.630 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55813 | val 0.78612
  Epoch 014 - train 0.53185 | val 0.92752
  Classification -> best τ=0.520 (val F1=0.3718)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60783 | val 0.75927
  Epoch 015 - train 0.57718 | val 0.72901
  Classification -> best τ=0.385 (val F1=0.3815)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61710 | val 1.04675
  Epoch 012 - train 0.60765 | val 1.12189
  Classification -> best τ=0.500 (val F1=0.2465)
  Directional -> Accuracy: 0.4419, MCC: -0.2676, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64684 | val 0.74495
  Epoch 011 - train 0.64319 | val 0.77095
  Classification -> best τ=0.440 (val F1=0.1326)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54253 | val 0.82900
  Epoch 011 - train 0.50568 | val 0.82713
  Classification -> best τ=0.540 (val F1=0.2292)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56367 | val 0.83388
  Epoch 011 - train 0.54411 | val 0.93066
  Classification -> best τ=0.490 (val F1=0.2382)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46799 | val 0.98843
  Epoch 011 - train 0.47704 | val 1.22440
  Classification -> best τ=0.425 (val F1=0.2118)
  Directional -> Accuracy: 0.5652, MCC: 0.0094, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57104 | val 0.71227
  Epoch 020 - train 0.42377 | val 0.63303
  Epoch 029 - train 0.27886 | val 0.75374
  Classification -> best τ=0.325 (val F1=0.5489)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60009 | val 0.74809
  Epoch 012 - train 0.59436 | val 0.87214
  Classification -> best τ=0.445 (val F1=0.4564)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57677 | val 0.72246
  Epoch 011 - train 0.57378 | val 0.75221
  Classification -> best τ=0.525 (val F1=0.4080)
  Directional -> Accuracy: 0.5778, MCC: 0.2222, F1: 0.3871

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58856 | val 0.60229
  Epoch 020 - train 0.54044 | val 1.56026
  Epoch 024 - train 0.51446 | val 2.05450
  Classification -> best τ=0.470 (val F1=0.6667)
  Directional -> Accuracy: 0.6190, MCC: 0.1936, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63740 | val 0.73466
  Epoch 018 - train 0.47475 | val 0.65311
  Classification -> best τ=0.670 (val F1=0.3705)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65441 | val 0.79890
  Epoch 011 - train 0.63205 | val 0.81781
  Classification -> best τ=0.540 (val F1=0.2374)
  Directional -> Accuracy: 0.4909, MCC: 0.1773, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58731 | val 1.16901
  Epoch 011 - train 0.56435 | val 1.46544
  Classification -> best τ=0.690 (val F1=0.2227)
  Directional -> Accuracy: 0.5357, MCC: 0.2296, F1: 0.6750

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61707 | val 0.68599
  Epoch 018 - train 0.57687 | val 0.75378
  Classification -> best τ=0.650 (val F1=0.2719)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60370 | val 0.72694
  Epoch 020 - train 0.52416 | val 0.97162
  Classification -> best τ=0.560 (val F1=0.1997)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61062 | val 0.69464

[I 2026-02-20 05:59:15,989] Trial 214 finished with value: 0.2761656821759754 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.0051902111918584, 'weight_decay': 1.2836767381258164e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1357945748086493, 'early_stopping_min_delta': 0.009774157705622587}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.53308 | val 0.80200
  Classification -> best τ=0.555 (val F1=0.2623)
  Directional -> Accuracy: 0.4500, MCC: -0.2112, F1: 0.0571

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2761656821759754
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62635 | val 0.69464
  Epoch 016 - train 0.63877 | val 0.85349
  Classification -> best τ=0.545 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58414 | val 0.72709
  Epoch 017 - train 0.55254 | val 0.69984
  Classification -> best τ=0.475 (val F1=0.2493)
  Directional -> Accuracy: 0.4222, MCC: -0.0842, F1: 0.2778

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56645 | val 0.72192
  Epoch 013 - train 0.49290 | val 0.99350
  Classification -> best τ=0.485 (val F1=0.3482)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5106

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64117 | val 0.69259
  Epoch 020 - train 0.60164 | val 1.00440
  Classification -> best τ=0.370 (val F1=0.3222)
  Directional -> Accuracy: 0.5135, MCC: 0.0293, F1: 0.5263

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57310 | val 1.02174
  Epoch 011 - train 0.56164 | val 0.86134
  Classification -> best τ=0.430 (val F1=0.4611)
  Directional -> Accuracy: 0.6800, MCC: 0.3870, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61210 | val 0.69349
  Epoch 012 - train 0.57940 | val 0.89542
  Classification -> best τ=0.540 (val F1=0.2208)
  Directional -> Accuracy: 0.5435, MCC: 0.1286, F1: 0.6316

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64280 | val 0.71806
  Epoch 012 - train 0.63054 | val 0.81649
  Classification -> best τ=0.580 (val F1=0.1718)
  Directional -> Accuracy: 0.5441, MCC: 0.0039, F1: 0.3404

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56777 | val 0.66083
  Epoch 020 - train 0.47688 | val 1.71499
  Epoch 021 - train 0.44453 | val 1.51325
  Classification -> best τ=0.240 (val F1=0.2453)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56682 | val 0.63893
  Epoch 018 - train 0.47181 | val 1.03224
  Classification -> best τ=0.515 (val F1=0.3962)
  Directional -> Accuracy: 0.6458, MCC: 0.2714, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66042 | val 0.71946
  Epoch 011 - train 0.63447 | val 0.75871
  Classification -> best τ=0.530 (val F1=0.0224)
  Directional -> Accuracy: 0.4493, MCC: -0.1004, F1: 0.4062

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65006 | val 0.84155
  Epoch 013 - train 0.60837 | val 1.40824
  Classification -> best τ=0.250 (val F1=0.1835)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51539 | val 1.13843
  Epoch 012 - train 0.49878 | val 2.25061
  Classification -> best τ=0.575 (val F1=0.2630)
  Directional -> Accuracy: 0.5263, MCC: 0.0671, F1: 0.4000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61685 | val 1.02941
  Epoch 013 - train 0.61236 | val 0.95774
  Classification -> best τ=0.510 (val F1=0.2636)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66934 | val 0.67697
  Epoch 011 - train 0.66277 | val 0.67242
  Classification -> best τ=0.330 (val F1=0.2568)
  Directional -> Accuracy: 0.5833, MCC: 0.1747, F1: 0.6377

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55745 | val 0.74386
  Epoch 013 - train 0.56578 | val 0.81075
  Classification -> best τ=0.470 (val F1=0.2758)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63004 | val 1.18487
  Epoch 013 - train 0.59194 | val 1.04157
  Classification -> best τ=0.615 (val F1=0.4278)
  Directional -> Accuracy: 0.5362, MCC: 0.0804, F1: 0.5294

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60435 | val 1.66721
  Epoch 011 - train 0.60527 | val 1.81108
  Classification -> best τ=0.550 (val F1=0.2787)
  Directional -> Accuracy: 0.3966, MCC: -0.2132, F1: 0.4615

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66385 | val 0.96868
  Epoch 012 - train 0.63838 | val 1.32788
  Classification -> best τ=0.580 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62205 | val 0.85944
  Epoch 014 - train 0.58694 | val 1.14585
  Classification -> best τ=0.385 (val F1=0.3689)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61159 | val 0.67668
  Epoch 015 - train 0.59895 | val 0.73976
  Classification -> best τ=0.450 (val F1=0.3734)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60434 | val 0.69076
  Epoch 015 - train 0.51778 | val 0.72693
  Classification -> best τ=0.530 (val F1=0.1964)
  Directional -> Accuracy: 0.5106, MCC: -0.1254, F1: 0.6462

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60829 | val 0.82681
  Epoch 014 - train 0.62428 | val 0.93699
  Classification -> best τ=0.495 (val F1=0.2019)
  Directional -> Accuracy: 0.4923, MCC: -0.1231, F1: 0.6598

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64343 | val 0.73139
  Epoch 013 - train 0.61115 | val 0.80831
  Classification -> best τ=0.570 (val F1=0.3421)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66833 | val 0.72585
  Epoch 012 - train 0.63823 | val 0.73477
  Classification -> best τ=0.500 (val F1=0.1393)
  Directional -> Accuracy: 0.5538, MCC: 0.1269, F1: 0.6027

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55432 | val 0.90478
  Epoch 014 - train 0.54402 | val 0.99610
  Classification -> best τ=0.420 (val F1=0.4607)
  Directional -> Accuracy: 0.5636, MCC: 0.1047, F1: 0.6364

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58284 | val 0.81200
  Epoch 012 - train 0.56559 | val 0.94901
  Classification -> best τ=0.565 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60647 | val 0.69941
  Epoch 014 - train 0.52818 | val 0.71244
  Classification -> best τ=0.585 (val F1=0.0142)
  Directional -> Accuracy: 0.5238, MCC: 0.2810, F1: 0.2857

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60810 | val 0.85332
  Epoch 012 - train 0.55290 | val 1.02064
  Classification -> best τ=0.360 (val F1=0.2435)
  Directional -> Accuracy: 0.5357, MCC: 0.2812, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66139 | val 0.73039
  Epoch 020 - train 0.45018 | val 2.19940
  Epoch 021 - train 0.45128 | val 2.68503
  Classification -> best τ=0.395 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56652 | val 1.20915
  Epoch 012 - train 0.57530 | val 1.83769
  Classification -> best τ=0.555 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54849 | val 0.89013
  Epoch 017 - train 0.41975 | val 1.10692
  Classification -> best τ=0.485 (val F1=0.2786)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56244 | val 0.79218
  Epoch 015 - train 0.50458 | val 0.90699
  Classification -> best τ=0.430 (val F1=0.3748)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63742 | val 0.72185
  Epoch 013 - train 0.59041 | val 0.78907
  Classification -> best τ=0.325 (val F1=0.4246)
  Directional -> Accuracy: 0.5833, MCC: 0.2292, F1: 0.5161

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64279 | val 0.89939
  Epoch 012 - train 0.60661 | val 1.04934
  Classification -> best τ=0.410 (val F1=0.3078)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62925 | val 0.88165
  Epoch 014 - train 0.60923 | val 0.91553
  Classification -> best τ=0.590 (val F1=0.2566)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56929 | val 0.79895
  Epoch 013 - train 0.51232 | val 1.91418
  Classification -> best τ=0.410 (val F1=0.1507)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54638 | val 0.79843
  Epoch 013 - train 0.54041 | val 0.93654
  Classification -> best τ=0.480 (val F1=0.1684)
  Directional -> Accuracy: 0.4643, MCC: -0.0667, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50046 | val 1.05162
  Epoch 011 - train 0.48969 | val 0.96587
  Classification -> best τ=0.430 (val F1=0.1195)
  Directional -> Accuracy: 0.5435, MCC: -0.0586, F1: 0.6769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58374 | val 0.67265
  Epoch 018 - train 0.42961 | val 1.24784
  Classification -> best τ=0.530 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61045 | val 0.66096
  Epoch 020 - train 0.58017 | val 0.81866
  Epoch 024 - train 0.50513 | val 0.78276
  Classification -> best τ=0.390 (val F1=0.3548)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61508 | val 0.76183
  Epoch 012 - train 0.56074 | val 0.76335
  Classification -> best τ=0.440 (val F1=0.2874)
  Directional -> Accuracy: 0.5556, MCC: 0.1744, F1: 0.3333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58727 | val 0.66074
  Epoch 017 - train 0.51470 | val 0.67980
  Classification -> best τ=0.515 (val F1=0.4423)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62356 | val 0.70904
  Epoch 011 - train 0.67196 | val 0.64001
  Classification -> best τ=0.530 (val F1=0.5689)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57785 | val 0.70375
  Epoch 011 - train 0.56015 | val 0.73958
  Classification -> best τ=0.550 (val F1=0.2408)
  Directional -> Accuracy: 0.6364, MCC: 0.3435, F1: 0.5652

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53928 | val 1.98894
  Epoch 012 - train 0.54838 | val 2.39754
  Classification -> best τ=0.475 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61430 | val 1.23399
  Epoch 013 - train 0.62881 | val 1.09021
  Classification -> best τ=0.630 (val F1=0.2064)
  Directional -> Accuracy: 0.5094, MCC: 0.0484, F1: 0.2353

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57191 | val 1.42502
  Epoch 011 - train 0.54194 | val 1.32423
  Classification -> best τ=0.575 (val F1=0.0782)
  Directional -> Accuracy: 0.4909, MCC: 0.0125, F1: 0.3333

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61152 | val 0.70676

[I 2026-02-20 06:00:10,757] Trial 215 finished with value: 0.27361623033419863 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00999057632733555, 'weight_decay': 1.9667927032149552e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1733472592606509, 'early_stopping_min_delta': 0.009904568711504113}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.55540 | val 0.72869
  Classification -> best τ=0.505 (val F1=0.3309)
  Directional -> Accuracy: 0.6167, MCC: 0.2311, F1: 0.5818

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27361623033419863
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62447 | val 0.71367
  Epoch 013 - train 0.59946 | val 0.88149
  Classification -> best τ=0.580 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1827, F1: 0.1111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56060 | val 0.69965
  Epoch 014 - train 0.54082 | val 0.68280
  Classification -> best τ=0.455 (val F1=0.1058)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60663 | val 0.85566
  Epoch 012 - train 0.56207 | val 0.95448
  Classification -> best τ=0.585 (val F1=0.3482)
  Directional -> Accuracy: 0.4130, MCC: -0.1774, F1: 0.2286

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65997 | val 0.80135
  Epoch 012 - train 0.67864 | val 0.77533
  Classification -> best τ=0.490 (val F1=0.2030)
  Directional -> Accuracy: 0.5000, MCC: 0.0333, F1: 0.4127

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56019 | val 0.73929
  Epoch 013 - train 0.53809 | val 1.19435
  Classification -> best τ=0.460 (val F1=0.5175)
  Directional -> Accuracy: 0.7800, MCC: 0.5590, F1: 0.7925

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62209 | val 0.82990
  Epoch 011 - train 0.62237 | val 0.86380
  Classification -> best τ=0.390 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61813 | val 0.81490
  Epoch 011 - train 0.61916 | val 1.07180
  Classification -> best τ=0.350 (val F1=0.2101)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56008 | val 1.02063
  Epoch 013 - train 0.51158 | val 1.12705
  Classification -> best τ=0.335 (val F1=0.2453)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.2222

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59809 | val 0.72894
  Epoch 012 - train 0.56482 | val 0.69728
  Classification -> best τ=0.475 (val F1=0.2166)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57601 | val 0.71116
  Epoch 012 - train 0.65244 | val 0.78636
  Classification -> best τ=0.540 (val F1=0.1858)
  Directional -> Accuracy: 0.5217, MCC: -0.0263, F1: 0.3265

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64022 | val 0.65709
  Epoch 020 - train 0.48753 | val 1.50736
  Classification -> best τ=0.450 (val F1=0.3072)
  Directional -> Accuracy: 0.5306, MCC: 0.1168, F1: 0.5965

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52439 | val 1.27565
  Epoch 012 - train 0.51968 | val 1.72427
  Classification -> best τ=0.650 (val F1=0.1181)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57710 | val 1.83187
  Epoch 011 - train 0.58240 | val 1.53723
  Classification -> best τ=0.280 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63937 | val 0.66280
  Epoch 011 - train 0.59335 | val 0.64416
  Classification -> best τ=0.400 (val F1=0.3011)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63373 | val 0.71552
  Epoch 013 - train 0.61008 | val 0.81587
  Classification -> best τ=0.555 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0287, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58407 | val 0.88002
  Epoch 013 - train 0.57709 | val 1.24689
  Classification -> best τ=0.540 (val F1=0.3262)
  Directional -> Accuracy: 0.5652, MCC: 0.1258, F1: 0.5946

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61356 | val 1.26316
  Epoch 011 - train 0.63068 | val 1.34056
  Classification -> best τ=0.530 (val F1=0.2048)
  Directional -> Accuracy: 0.6034, MCC: 0.0131, F1: 0.7416

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63132 | val 0.74986
  Epoch 017 - train 0.58683 | val 0.72397
  Classification -> best τ=0.535 (val F1=0.2082)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65570 | val 0.70325
  Epoch 013 - train 0.62196 | val 0.75038
  Classification -> best τ=0.440 (val F1=0.3357)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64950 | val 0.75350
  Epoch 013 - train 0.60630 | val 0.77547
  Classification -> best τ=0.495 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60785 | val 0.69233
  Epoch 018 - train 0.50696 | val 0.82350
  Classification -> best τ=0.495 (val F1=0.3678)
  Directional -> Accuracy: 0.5957, MCC: -0.0267, F1: 0.7397

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65395 | val 0.82369
  Epoch 011 - train 0.60326 | val 0.89214
  Classification -> best τ=0.525 (val F1=0.0671)
  Directional -> Accuracy: 0.5385, MCC: 0.0959, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60778 | val 0.76604
  Epoch 013 - train 0.56031 | val 0.91029
  Classification -> best τ=0.540 (val F1=0.3329)
  Directional -> Accuracy: 0.5263, MCC: 0.0784, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61814 | val 0.87277
  Epoch 011 - train 0.60969 | val 0.80322
  Classification -> best τ=0.505 (val F1=0.1348)
  Directional -> Accuracy: 0.5538, MCC: 0.1396, F1: 0.6234

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57912 | val 0.73490
  Epoch 017 - train 0.50765 | val 1.02857
  Classification -> best τ=0.420 (val F1=0.4380)
  Directional -> Accuracy: 0.4909, MCC: -0.0410, F1: 0.5625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57891 | val 0.75430
  Epoch 011 - train 0.58076 | val 0.78579
  Classification -> best τ=0.595 (val F1=0.2097)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61872 | val 0.78475
  Epoch 011 - train 0.56997 | val 0.89807
  Classification -> best τ=0.650 (val F1=0.0534)
  Directional -> Accuracy: 0.3810, MCC: -0.2123, F1: 0.3500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62895 | val 0.72532
  Epoch 012 - train 0.60029 | val 0.74841
  Classification -> best τ=0.320 (val F1=0.2892)
  Directional -> Accuracy: 0.5536, MCC: 0.2640, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59522 | val 0.67761
  Epoch 020 - train 0.40246 | val 0.72474
  Classification -> best τ=0.490 (val F1=0.4382)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60306 | val 1.02016
  Epoch 012 - train 0.57762 | val 1.13338
  Classification -> best τ=0.635 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57225 | val 1.40169
  Epoch 016 - train 0.49628 | val 1.65181
  Classification -> best τ=0.515 (val F1=0.2476)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63696 | val 0.74905
  Epoch 012 - train 0.65352 | val 0.73116
  Classification -> best τ=0.410 (val F1=0.3789)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66115 | val 0.70962
  Epoch 016 - train 0.67849 | val 0.92902
  Classification -> best τ=0.405 (val F1=0.4032)
  Directional -> Accuracy: 0.5972, MCC: 0.1696, F1: 0.6667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60148 | val 0.98952
  Epoch 012 - train 0.54384 | val 0.99172
  Classification -> best τ=0.595 (val F1=0.3158)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67496 | val 0.77543
  Epoch 011 - train 0.65042 | val 0.80034
  Classification -> best τ=0.405 (val F1=0.3525)
  Directional -> Accuracy: 0.5758, MCC: 0.0867, F1: 0.6818

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53005 | val 0.89055
  Epoch 012 - train 0.53644 | val 1.11921
  Classification -> best τ=0.415 (val F1=0.2439)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53746 | val 0.84149
  Epoch 012 - train 0.55712 | val 0.90224
  Classification -> best τ=0.395 (val F1=0.1677)
  Directional -> Accuracy: 0.5000, MCC: 0.0157, F1: 0.5333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49265 | val 1.32950
  Epoch 011 - train 0.52575 | val 1.43772
  Classification -> best τ=0.455 (val F1=0.0917)
  Directional -> Accuracy: 0.5217, MCC: 0.0543, F1: 0.5600

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55089 | val 0.65837
  Epoch 016 - train 0.52523 | val 0.70750
  Classification -> best τ=0.555 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62731 | val 0.69205
  Epoch 011 - train 0.59789 | val 0.69062
  Classification -> best τ=0.440 (val F1=0.3040)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56590 | val 0.75805
  Epoch 012 - train 0.50626 | val 0.80051
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55597 | val 0.90443
  Epoch 013 - train 0.57481 | val 0.74824
  Classification -> best τ=0.445 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59659 | val 0.67458
  Epoch 014 - train 0.53032 | val 0.69177
  Classification -> best τ=0.595 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63782 | val 0.76678
  Epoch 011 - train 0.64428 | val 0.80193
  Classification -> best τ=0.465 (val F1=0.2448)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57878 | val 1.53591
  Epoch 011 - train 0.55634 | val 1.80191
  Classification -> best τ=0.525 (val F1=0.2720)
  Directional -> Accuracy: 0.5536, MCC: 0.1011, F1: 0.4444

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61412 | val 0.79853
  Epoch 014 - train 0.59105 | val 2.14071
  Classification -> best τ=0.555 (val F1=0.2133)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59938 | val 0.75974
  Epoch 014 - train 0.57112 | val 0.78541
  Classification -> best τ=0.550 (val F1=0.1062)
  Directional -> Accuracy: 0.4909, MCC: -0.0452, F1: 0.5882

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63328 | val 0.76372

[I 2026-02-20 06:01:03,284] Trial 216 finished with value: 0.2625075446973295 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.0065804486175194896, 'weight_decay': 1.4607150818000154e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.126351872623365, 'early_stopping_min_delta': 0.009589718403204335}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.57086 | val 0.96459
  Classification -> best τ=0.425 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2625075446973295
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59599 | val 0.84430
  Epoch 012 - train 0.61993 | val 0.79182
  Classification -> best τ=0.460 (val F1=0.1772)
  Directional -> Accuracy: 0.5395, MCC: 0.0409, F1: 0.3860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57804 | val 0.67609
  Epoch 020 - train 0.44306 | val 0.67028
  Epoch 022 - train 0.42247 | val 0.73087
  Classification -> best τ=0.310 (val F1=0.2428)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58812 | val 0.74383
  Epoch 016 - train 0.52532 | val 1.12833
  Classification -> best τ=0.530 (val F1=0.3835)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63127 | val 0.89005
  Epoch 012 - train 0.63978 | val 0.86843
  Classification -> best τ=0.425 (val F1=0.1745)
  Directional -> Accuracy: 0.5135, MCC: 0.0433, F1: 0.4857

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58821 | val 0.69307
  Epoch 015 - train 0.53571 | val 0.75799
  Classification -> best τ=0.490 (val F1=0.4048)
  Directional -> Accuracy: 0.5600, MCC: 0.1144, F1: 0.6071

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61514 | val 0.73561
  Epoch 011 - train 0.63771 | val 0.79993
  Classification -> best τ=0.585 (val F1=0.2739)
  Directional -> Accuracy: 0.5870, MCC: 0.1860, F1: 0.3871

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60873 | val 0.89773
  Epoch 011 - train 0.61434 | val 0.82571
  Classification -> best τ=0.505 (val F1=0.1588)
  Directional -> Accuracy: 0.4559, MCC: 0.0415, F1: 0.5432

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56109 | val 0.85413
  Epoch 011 - train 0.56843 | val 0.76455
  Classification -> best τ=0.405 (val F1=0.1418)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56682 | val 0.75121
  Epoch 013 - train 0.55043 | val 0.98608
  Classification -> best τ=0.550 (val F1=0.2784)
  Directional -> Accuracy: 0.6667, MCC: 0.3495, F1: 0.4286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56618 | val 0.81564
  Epoch 011 - train 0.58703 | val 0.85194
  Classification -> best τ=0.495 (val F1=0.1858)
  Directional -> Accuracy: 0.3623, MCC: -0.2412, F1: 0.4054

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62110 | val 0.79414
  Epoch 012 - train 0.59770 | val 0.69005
  Classification -> best τ=0.435 (val F1=0.2543)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57783 | val 0.93397
  Epoch 012 - train 0.54859 | val 1.22502
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58942 | val 1.29931
  Epoch 011 - train 0.56543 | val 1.11267
  Classification -> best τ=0.430 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63732 | val 0.74127
  Epoch 016 - train 0.57570 | val 1.01195
  Classification -> best τ=0.360 (val F1=0.3362)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60162 | val 0.89414
  Epoch 014 - train 0.52173 | val 0.92921
  Classification -> best τ=0.540 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63678 | val 0.80126
  Epoch 014 - train 0.61531 | val 0.93992
  Classification -> best τ=0.595 (val F1=0.3863)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60354 | val 1.01347
  Epoch 011 - train 0.59528 | val 1.26968
  Classification -> best τ=0.705 (val F1=0.2276)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59654 | val 1.81154
  Epoch 013 - train 0.59052 | val 2.02953
  Classification -> best τ=0.430 (val F1=0.1903)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60628 | val 1.03973
  Epoch 014 - train 0.60807 | val 0.78345
  Classification -> best τ=0.295 (val F1=0.3140)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61790 | val 0.80091
  Epoch 012 - train 0.59126 | val 0.87397
  Classification -> best τ=0.460 (val F1=0.3090)
  Directional -> Accuracy: 0.4324, MCC: -0.1633, F1: 0.5116

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60739 | val 0.76725
  Epoch 013 - train 0.59261 | val 0.73283
  Classification -> best τ=0.600 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64293 | val 0.86228
  Epoch 012 - train 0.62818 | val 0.88013
  Classification -> best τ=0.485 (val F1=0.1480)
  Directional -> Accuracy: 0.4308, MCC: -0.1382, F1: 0.3729

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59732 | val 0.79334
  Epoch 011 - train 0.59199 | val 0.78151
  Classification -> best τ=0.520 (val F1=0.3276)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64275 | val 0.86007
  Epoch 012 - train 0.58569 | val 0.84462
  Classification -> best τ=0.460 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58210 | val 0.80028
  Epoch 018 - train 0.50283 | val 0.94625
  Classification -> best τ=0.680 (val F1=0.5009)
  Directional -> Accuracy: 0.4909, MCC: 0.0659, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55887 | val 0.81217
  Epoch 012 - train 0.55751 | val 0.87464
  Classification -> best τ=0.550 (val F1=0.2726)
  Directional -> Accuracy: 0.5333, MCC: -0.0068, F1: 0.3226

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61120 | val 0.70412
  Epoch 011 - train 0.61175 | val 0.73491
  Classification -> best τ=0.555 (val F1=0.1680)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61327 | val 0.77964
  Epoch 011 - train 0.58936 | val 0.82109
  Classification -> best τ=0.480 (val F1=0.2114)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57850 | val 0.69961
  Epoch 016 - train 0.52850 | val 0.98766
  Classification -> best τ=0.535 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61841 | val 0.80021
  Epoch 012 - train 0.61087 | val 0.89761
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64864 | val 0.96048
  Epoch 012 - train 0.56715 | val 0.79728
  Classification -> best τ=0.600 (val F1=0.1846)
  Directional -> Accuracy: 0.4286, MCC: -0.1090, F1: 0.1429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61268 | val 0.80961
  Epoch 015 - train 0.48535 | val 0.99816
  Classification -> best τ=0.450 (val F1=0.2812)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60615 | val 0.69880
  Epoch 015 - train 0.65326 | val 0.64861
  Classification -> best τ=0.335 (val F1=0.3593)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60777 | val 0.96304
  Epoch 011 - train 0.59965 | val 0.98597
  Classification -> best τ=0.490 (val F1=0.3417)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60136 | val 0.77924
  Epoch 011 - train 0.60839 | val 0.76910
  Classification -> best τ=0.390 (val F1=0.2409)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54138 | val 0.69845
  Epoch 011 - train 0.46669 | val 0.71258
  Classification -> best τ=0.495 (val F1=0.2439)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53443 | val 0.78686
  Epoch 012 - train 0.54453 | val 0.87550
  Classification -> best τ=0.355 (val F1=0.2622)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48991 | val 0.98931
  Epoch 011 - train 0.48202 | val 1.18450
  Classification -> best τ=0.545 (val F1=0.2441)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58842 | val 0.62974
  Epoch 019 - train 0.47719 | val 0.70577
  Classification -> best τ=0.245 (val F1=0.3970)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61189 | val 0.75474
  Epoch 014 - train 0.55997 | val 0.95977
  Classification -> best τ=0.520 (val F1=0.2782)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58269 | val 0.85803
  Epoch 012 - train 0.54424 | val 0.90717
  Classification -> best τ=0.535 (val F1=0.2712)
  Directional -> Accuracy: 0.5111, MCC: 0.0069, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60288 | val 0.60158
  Epoch 020 - train 0.52298 | val 0.62384
  Epoch 022 - train 0.53127 | val 0.63440
  Classification -> best τ=0.210 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64829 | val 0.62849
  Epoch 019 - train 0.49968 | val 0.62793
  Classification -> best τ=0.545 (val F1=0.5689)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61775 | val 0.72167
  Epoch 011 - train 0.59698 | val 0.77397
  Classification -> best τ=0.645 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.0585, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57651 | val 1.53018
  Epoch 011 - train 0.55701 | val 1.83874
  Classification -> best τ=0.530 (val F1=0.3294)
  Directional -> Accuracy: 0.5714, MCC: 0.2566, F1: 0.6842

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60917 | val 0.72050
  Epoch 015 - train 0.57893 | val 1.15821
  Classification -> best τ=0.510 (val F1=0.1168)
  Directional -> Accuracy: 0.5472, MCC: 0.0969, F1: 0.6364

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62529 | val 0.82303
  Epoch 014 - train 0.63508 | val 0.77859
  Classification -> best τ=0.435 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 06:01:56,452] Trial 217 finished with value: 0.2648994846146397 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.005552651841240557, 'weight_decay': 1.736685185190757e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2046286421752512, 'early_stopping_min_delta': 0.009431972007782573}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 010 - train 0.58630 | val 0.78233
  Epoch 011 - train 0.57397 | val 0.75455
  Classification -> best τ=0.485 (val F1=0.1489)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2648994846146397
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57136 | val 1.04792
  Epoch 014 - train 0.61584 | val 0.78524
  Classification -> best τ=0.610 (val F1=0.1430)
  Directional -> Accuracy: 0.6184, MCC: 0.2238, F1: 0.3830

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58188 | val 0.68661
  Epoch 013 - train 0.60415 | val 0.67490
  Classification -> best τ=0.435 (val F1=0.3181)
  Directional -> Accuracy: 0.6444, MCC: 0.2545, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61659 | val 0.80215
  Epoch 012 - train 0.55048 | val 0.90410
  Classification -> best τ=0.575 (val F1=0.3171)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65144 | val 0.69320
  Epoch 020 - train 0.59787 | val 0.79597
  Epoch 021 - train 0.59797 | val 0.93142
  Classification -> best τ=0.470 (val F1=0.3506)
  Directional -> Accuracy: 0.4865, MCC: 0.0016, F1: 0.4062

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60237 | val 0.71510
  Epoch 018 - train 0.52607 | val 1.86791
  Classification -> best τ=0.680 (val F1=0.4291)
  Directional -> Accuracy: 0.4800, MCC: -0.0118, F1: 0.1333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65710 | val 0.76649
  Epoch 013 - train 0.60034 | val 0.70288
  Classification -> best τ=0.495 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64450 | val 0.75456
  Epoch 011 - train 0.65123 | val 0.76503
  Classification -> best τ=0.450 (val F1=0.3353)
  Directional -> Accuracy: 0.4559, MCC: 0.0415, F1: 0.5432

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49982 | val 0.66371
  Epoch 011 - train 0.53848 | val 1.03865
  Classification -> best τ=0.365 (val F1=0.1657)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.6207

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55770 | val 0.78770
  Epoch 013 - train 0.52778 | val 1.13605
  Classification -> best τ=0.525 (val F1=0.2764)
  Directional -> Accuracy: 0.5625, MCC: 0.0263, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59480 | val 0.81665
  Epoch 012 - train 0.57468 | val 0.88489
  Classification -> best τ=0.600 (val F1=0.2693)
  Directional -> Accuracy: 0.5652, MCC: 0.0495, F1: 0.3182

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60923 | val 1.02063
  Epoch 015 - train 0.54691 | val 1.37753
  Classification -> best τ=0.445 (val F1=0.1738)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53588 | val 1.62708
  Epoch 018 - train 0.42494 | val 1.84423
  Classification -> best τ=0.335 (val F1=0.2258)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52881 | val 1.15451
  Epoch 011 - train 0.58271 | val 1.41153
  Classification -> best τ=0.535 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61038 | val 0.60464
  Epoch 020 - train 0.63385 | val 0.95024
  Classification -> best τ=0.380 (val F1=0.3196)
  Directional -> Accuracy: 0.5833, MCC: 0.1668, F1: 0.5902

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58486 | val 0.80546
  Epoch 014 - train 0.52076 | val 0.89182
  Classification -> best τ=0.505 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0199, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60164 | val 0.74924
  Epoch 013 - train 0.54495 | val 1.10393
  Classification -> best τ=0.595 (val F1=0.2474)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61150 | val 1.30608
  Epoch 011 - train 0.58927 | val 1.41345
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61745 | val 1.13322
  Epoch 013 - train 0.61103 | val 1.60742
  Classification -> best τ=0.555 (val F1=0.2082)
  Directional -> Accuracy: 0.4800, MCC: 0.2408, F1: 0.2353

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65373 | val 0.94939
  Epoch 015 - train 0.53439 | val 1.69531
  Classification -> best τ=0.350 (val F1=0.2752)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64425 | val 0.71314
  Epoch 013 - train 0.61769 | val 0.83158
  Classification -> best τ=0.475 (val F1=0.3460)
  Directional -> Accuracy: 0.4865, MCC: 0.1844, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59041 | val 0.66310
  Epoch 020 - train 0.51091 | val 0.74703
  Classification -> best τ=0.395 (val F1=0.4078)
  Directional -> Accuracy: 0.5957, MCC: 0.0814, F1: 0.7077

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67227 | val 0.85860
  Epoch 014 - train 0.65757 | val 1.24816
  Classification -> best τ=0.680 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62296 | val 0.72278
  Epoch 012 - train 0.60396 | val 0.76678
  Classification -> best τ=0.575 (val F1=0.2981)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62469 | val 0.86583
  Epoch 013 - train 0.57501 | val 1.05035
  Classification -> best τ=0.670 (val F1=0.1565)
  Directional -> Accuracy: 0.4923, MCC: -0.0251, F1: 0.4211

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56867 | val 0.85742
  Epoch 013 - train 0.60419 | val 0.81863
  Classification -> best τ=0.485 (val F1=0.3751)
  Directional -> Accuracy: 0.5091, MCC: -0.0219, F1: 0.6087

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58518 | val 1.61723
  Epoch 011 - train 0.59665 | val 1.77387
  Classification -> best τ=0.525 (val F1=0.1310)
  Directional -> Accuracy: 0.4222, MCC: -0.2021, F1: 0.2778

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62794 | val 0.71725
  Epoch 013 - train 0.56947 | val 0.68676
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62170 | val 0.74833
  Epoch 014 - train 0.58504 | val 0.81566
  Classification -> best τ=0.510 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62110 | val 0.88484
  Epoch 015 - train 0.55049 | val 1.01821
  Classification -> best τ=0.590 (val F1=0.2957)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64074 | val 0.89486
  Epoch 015 - train 0.59955 | val 0.96707
  Classification -> best τ=0.500 (val F1=0.5210)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62952 | val 0.87061
  Epoch 012 - train 0.54463 | val 0.72928
  Classification -> best τ=0.465 (val F1=0.2066)
  Directional -> Accuracy: 0.5952, MCC: 0.2071, F1: 0.5854

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62460 | val 0.69989
  Epoch 014 - train 0.54128 | val 0.78409
  Classification -> best τ=0.510 (val F1=0.3789)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66139 | val 0.66079
  Epoch 014 - train 0.57101 | val 0.78542
  Classification -> best τ=0.425 (val F1=0.3838)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61799 | val 0.86777
  Epoch 011 - train 0.61042 | val 0.93672
  Classification -> best τ=0.480 (val F1=0.2324)
  Directional -> Accuracy: 0.5581, MCC: 0.2093, F1: 0.6780

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63216 | val 0.83946
  Epoch 011 - train 0.61638 | val 0.72791
  Classification -> best τ=0.335 (val F1=0.3855)
  Directional -> Accuracy: 0.5606, MCC: 0.0718, F1: 0.6506

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58846 | val 0.76490
  Epoch 012 - train 0.55338 | val 0.88742
  Classification -> best τ=0.500 (val F1=0.2665)
  Directional -> Accuracy: 0.7381, MCC: 0.4949, F1: 0.7179

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56236 | val 0.89332
  Epoch 012 - train 0.49778 | val 1.00502
  Classification -> best τ=0.435 (val F1=0.2868)
  Directional -> Accuracy: 0.5357, MCC: 0.0961, F1: 0.5806

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51324 | val 1.16731
  Epoch 011 - train 0.59353 | val 1.24377
  Classification -> best τ=0.540 (val F1=0.0475)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54502 | val 0.65480
  Epoch 016 - train 0.43857 | val 0.71540
  Classification -> best τ=0.380 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60735 | val 0.77563
  Epoch 011 - train 0.58171 | val 0.79090
  Classification -> best τ=0.400 (val F1=0.4293)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56668 | val 0.75142
  Epoch 012 - train 0.55688 | val 0.78396
  Classification -> best τ=0.405 (val F1=0.0125)
  Directional -> Accuracy: 0.6000, MCC: 0.3458, F1: 0.3571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59285 | val 0.61822
  Epoch 020 - train 0.47142 | val 0.66233
  Epoch 026 - train 0.42433 | val 0.60892
  Classification -> best τ=0.215 (val F1=0.5092)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60162 | val 0.67623
  Epoch 020 - train 0.44287 | val 0.78337
  Epoch 025 - train 0.30915 | val 0.97847
  Classification -> best τ=0.680 (val F1=0.4478)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62087 | val 0.68322
  Epoch 015 - train 0.56150 | val 0.86226
  Classification -> best τ=0.615 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56308 | val 1.72376
  Epoch 011 - train 0.57926 | val 1.47418
  Classification -> best τ=0.680 (val F1=0.2143)
  Directional -> Accuracy: 0.5893, MCC: 0.2147, F1: 0.6567

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59258 | val 0.82200
  Epoch 012 - train 0.57719 | val 0.83320
  Classification -> best τ=0.485 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2109, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67413 | val 1.06338
  Epoch 012 - train 0.64967 | val 0.91422
  Classification -> best τ=0.505 (val F1=0.2704)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62447 | val 0.73613

[I 2026-02-20 06:02:52,161] Trial 218 finished with value: 0.26767564542658856 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007120362183560821, 'weight_decay': 1.5747604791491328e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1957218957467872, 'early_stopping_min_delta': 0.009656823958900149}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.62677 | val 0.75159
  Classification -> best τ=0.485 (val F1=0.3680)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26767564542658856
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69120 | val 0.75497
  Epoch 011 - train 0.68195 | val 0.76145
  Classification -> best τ=0.550 (val F1=0.0213)
  Directional -> Accuracy: 0.3947, MCC: -0.2697, F1: 0.2069

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69200 | val 0.70797
  Epoch 011 - train 0.70930 | val 0.71013
  Classification -> best τ=0.505 (val F1=0.0240)
  Directional -> Accuracy: 0.4000, MCC: -0.1273, F1: 0.1290

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70701 | val 0.72210
  Epoch 011 - train 0.70608 | val 0.72614
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69388 | val 0.69420
  Epoch 011 - train 0.69847 | val 0.69890
  Classification -> best τ=0.530 (val F1=0.2065)
  Directional -> Accuracy: 0.5135, MCC: -0.0231, F1: 0.6327

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70269 | val 0.75578
  Epoch 011 - train 0.70949 | val 0.76044
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67770 | val 0.70012
  Epoch 011 - train 0.68230 | val 0.70150
  Classification -> best τ=0.520 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69065 | val 0.68995
  Epoch 011 - train 0.70228 | val 0.68987
  Classification -> best τ=0.505 (val F1=0.0742)
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70599 | val 0.66638
  Epoch 011 - train 0.69951 | val 0.66524
  Classification -> best τ=0.480 (val F1=0.1147)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69147 | val 0.68726
  Epoch 011 - train 0.69466 | val 0.68759
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70782 | val 0.70569
  Epoch 011 - train 0.69083 | val 0.70621
  Classification -> best τ=0.575 (val F1=0.0357)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71467 | val 0.77778
  Epoch 011 - train 0.70785 | val 0.79041
  Classification -> best τ=0.545 (val F1=0.1199)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69032 | val 0.72697
  Epoch 011 - train 0.70239 | val 0.73191
  Classification -> best τ=0.470 (val F1=0.3032)
  Directional -> Accuracy: 0.6491, MCC: 0.3140, F1: 0.6000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66303 | val 0.73392
  Epoch 011 - train 0.66241 | val 0.74415
  Classification -> best τ=0.480 (val F1=0.1189)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69007 | val 0.76881
  Epoch 011 - train 0.70590 | val 0.77592
  Classification -> best τ=0.560 (val F1=0.0316)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70320 | val 0.70158
  Epoch 011 - train 0.71014 | val 0.70488
  Classification -> best τ=0.495 (val F1=0.0529)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68374 | val 0.69994
  Epoch 011 - train 0.67597 | val 0.70452
  Classification -> best τ=0.490 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68686 | val 0.73903
  Epoch 011 - train 0.68951 | val 0.74822
  Classification -> best τ=0.520 (val F1=0.0557)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69013 | val 0.71162
  Epoch 011 - train 0.69344 | val 0.71342
  Classification -> best τ=0.480 (val F1=0.0036)
  Directional -> Accuracy: 0.3733, MCC: -0.1696, F1: 0.0408

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69312 | val 0.68795
  Epoch 011 - train 0.69343 | val 0.68720
  Classification -> best τ=0.480 (val F1=0.1709)
  Directional -> Accuracy: 0.4844, MCC: -0.1672, F1: 0.6292

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69031 | val 0.68162
  Epoch 011 - train 0.69481 | val 0.68270
  Classification -> best τ=0.500 (val F1=0.1673)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69710 | val 0.70167
  Epoch 011 - train 0.70071 | val 0.70355
  Classification -> best τ=0.490 (val F1=0.0853)
  Directional -> Accuracy: 0.4681, MCC: 0.0887, F1: 0.3590

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71440 | val 0.67384
  Epoch 019 - train 0.70503 | val 0.66990
  Classification -> best τ=0.510 (val F1=0.3229)
  Directional -> Accuracy: 0.5385, MCC: 0.1077, F1: 0.3478

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66951 | val 0.66622
  Epoch 016 - train 0.66547 | val 0.67107
  Classification -> best τ=0.635 (val F1=0.3254)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71243 | val 0.73314
  Epoch 011 - train 0.69623 | val 0.72739
  Classification -> best τ=0.575 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70120 | val 0.68402
  Epoch 020 - train 0.68479 | val 0.67341
  Epoch 021 - train 0.69001 | val 0.67272
  Classification -> best τ=0.465 (val F1=0.3105)
  Directional -> Accuracy: 0.5091, MCC: 0.1077, F1: 0.3077

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68449 | val 0.69301
  Epoch 011 - train 0.68937 | val 0.69329
  Classification -> best τ=0.525 (val F1=0.1585)
  Directional -> Accuracy: 0.3778, MCC: -0.2204, F1: 0.3913

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69201 | val 0.69399
  Epoch 011 - train 0.69432 | val 0.69540
  Classification -> best τ=0.530 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: 0.0525, F1: 0.3125

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68895 | val 0.70276
  Epoch 011 - train 0.69402 | val 0.70257
  Classification -> best τ=0.515 (val F1=0.0821)
  Directional -> Accuracy: 0.4464, MCC: -0.3111, F1: 0.6173

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69621 | val 0.69363
  Epoch 011 - train 0.70366 | val 0.69396
  Classification -> best τ=0.490 (val F1=0.3380)
  Directional -> Accuracy: 0.4250, MCC: -0.1234, F1: 0.3429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.73333 | val 0.69765
  Epoch 011 - train 0.74230 | val 0.69773
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69846 | val 0.67808
  Epoch 011 - train 0.69051 | val 0.67945
  Classification -> best τ=0.550 (val F1=0.1286)
  Directional -> Accuracy: 0.3571, MCC: -0.2781, F1: 0.1818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.73914 | val 0.68275
  Epoch 011 - train 0.72514 | val 0.68284
  Classification -> best τ=0.465 (val F1=0.0232)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70100 | val 0.71564
  Epoch 011 - train 0.68968 | val 0.71535
  Classification -> best τ=0.460 (val F1=0.0523)
  Directional -> Accuracy: 0.5833, MCC: 0.1250, F1: 0.7000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68900 | val 0.71941
  Epoch 011 - train 0.67128 | val 0.72576
  Classification -> best τ=0.455 (val F1=0.1607)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69045 | val 0.69523
  Epoch 011 - train 0.68906 | val 0.69583
  Classification -> best τ=0.460 (val F1=0.2292)
  Directional -> Accuracy: 0.4394, MCC: 0.1065, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67450 | val 0.68703
  Epoch 011 - train 0.67582 | val 0.68654
  Classification -> best τ=0.465 (val F1=0.2067)
  Directional -> Accuracy: 0.5952, MCC: 0.2035, F1: 0.5641

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68506 | val 0.70583
  Epoch 011 - train 0.68945 | val 0.70646
  Classification -> best τ=0.500 (val F1=0.0469)
  Directional -> Accuracy: 0.4286, MCC: -0.1487, F1: 0.3846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71727 | val 0.68402
  Epoch 011 - train 0.70164 | val 0.68399
  Classification -> best τ=0.480 (val F1=0.1369)
  Directional -> Accuracy: 0.5435, MCC: -0.0586, F1: 0.6769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69372 | val 0.70136
  Epoch 011 - train 0.69379 | val 0.70150
  Classification -> best τ=0.520 (val F1=0.1267)
  Directional -> Accuracy: 0.4375, MCC: 0.0974, F1: 0.5263

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70174 | val 0.70195
  Epoch 011 - train 0.69142 | val 0.70170
  Classification -> best τ=0.555 (val F1=0.0615)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70794 | val 0.68117
  Epoch 011 - train 0.71585 | val 0.68010
  Classification -> best τ=0.480 (val F1=0.3250)
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69970 | val 0.69351
  Epoch 011 - train 0.68600 | val 0.69282
  Classification -> best τ=0.500 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67009 | val 0.69437
  Epoch 011 - train 0.68069 | val 0.69530
  Classification -> best τ=0.505 (val F1=0.0842)
  Directional -> Accuracy: 0.6250, MCC: 0.2807, F1: 0.5909

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67997 | val 0.69536
  Epoch 011 - train 0.69368 | val 0.69404
  Classification -> best τ=0.485 (val F1=0.1154)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70948 | val 0.69444
  Epoch 011 - train 0.70089 | val 0.69658
  Classification -> best τ=0.490 (val F1=0.0950)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69880 | val 0.67784
  Epoch 011 - train 0.69609 | val 0.67767
  Classification -> best τ=0.520 (val F1=0.1646)
  Directional -> Accuracy: 0.5094, MCC: 0.0054, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.72110 | val 0.79913
  Epoch 011 - train 0.70486 | val 0.81858
  Classification -> best τ=0.520 (val F1=0.1514)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 06:03:39,079] Trial 219 finished with value: 0.13365868506291992 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 9.443431153911243e-06, 'weight_decay': 2.2616217402400733e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1101394444138641, 'early_stopping_min_delta': 0.009956228212104786}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 010 - train 0.72628 | val 0.75568
  Epoch 011 - train 0.71385 | val 0.76597
  Classification -> best τ=0.545 (val F1=0.1624)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13365868506291992
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58896 | val 0.72547
  Epoch 017 - train 0.55485 | val 0.70595
  Classification -> best τ=0.670 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0033, F1: 0.3077

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59707 | val 0.65610
  Epoch 020 - train 0.51973 | val 0.74485
  Epoch 022 - train 0.55539 | val 0.82797
  Classification -> best τ=0.420 (val F1=0.3487)
  Directional -> Accuracy: 0.6444, MCC: 0.2493, F1: 0.7241

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58891 | val 0.87499
  Epoch 014 - train 0.57678 | val 0.79500
  Classification -> best τ=0.455 (val F1=0.3313)
  Directional -> Accuracy: 0.5435, MCC: 0.0767, F1: 0.6182

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63797 | val 0.80584
  Epoch 012 - train 0.60099 | val 1.05215
  Classification -> best τ=0.430 (val F1=0.2246)
  Directional -> Accuracy: 0.4595, MCC: -0.0529, F1: 0.3548

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58994 | val 0.76384
  Epoch 013 - train 0.49643 | val 1.45929
  Classification -> best τ=0.560 (val F1=0.4611)
  Directional -> Accuracy: 0.5600, MCC: 0.2833, F1: 0.2667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52388 | val 0.76861
  Epoch 013 - train 0.51647 | val 0.99978
  Classification -> best τ=0.570 (val F1=0.1537)
  Directional -> Accuracy: 0.4565, MCC: -0.0763, F1: 0.5763

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64412 | val 0.94298
  Epoch 017 - train 0.62839 | val 0.76080
  Classification -> best τ=0.470 (val F1=0.2766)
  Directional -> Accuracy: 0.5000, MCC: 0.1932, F1: 0.5952

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53669 | val 0.73085
  Epoch 012 - train 0.51260 | val 0.89638
  Classification -> best τ=0.345 (val F1=0.1657)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4390

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55776 | val 0.74428
  Epoch 019 - train 0.46552 | val 1.13666
  Classification -> best τ=0.640 (val F1=0.3433)
  Directional -> Accuracy: 0.6667, MCC: 0.3167, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57315 | val 0.90718
  Epoch 011 - train 0.60126 | val 1.04811
  Classification -> best τ=0.515 (val F1=0.0405)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65951 | val 0.66885
  Epoch 017 - train 0.68272 | val 1.15556
  Classification -> best τ=0.360 (val F1=0.3939)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50489 | val 1.64515
  Epoch 012 - train 0.54382 | val 1.90385
  Classification -> best τ=0.530 (val F1=0.2825)
  Directional -> Accuracy: 0.5088, MCC: 0.0110, F1: 0.6000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62582 | val 0.94060
  Epoch 011 - train 0.65093 | val 0.96887
  Classification -> best τ=0.525 (val F1=0.2522)
  Directional -> Accuracy: 0.5952, MCC: 0.3191, F1: 0.6792

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69189 | val 0.69928
  Epoch 017 - train 0.59023 | val 1.13569
  Classification -> best τ=0.420 (val F1=0.3141)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5833

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60391 | val 1.56552
  Epoch 013 - train 0.59661 | val 4.19051
  Classification -> best τ=0.465 (val F1=0.1969)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58716 | val 1.12545
  Epoch 012 - train 0.54296 | val 1.28272
  Classification -> best τ=0.630 (val F1=0.2616)
  Directional -> Accuracy: 0.5362, MCC: 0.0716, F1: 0.5556

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61056 | val 1.75713
  Epoch 011 - train 0.59396 | val 2.17780
  Classification -> best τ=0.545 (val F1=0.2651)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62713 | val 1.38488
  Epoch 013 - train 0.58039 | val 1.87849
  Classification -> best τ=0.500 (val F1=0.1592)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60993 | val 0.75365
  Epoch 012 - train 0.60741 | val 0.92501
  Classification -> best τ=0.455 (val F1=0.2009)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64604 | val 0.69197
  Epoch 016 - train 0.63875 | val 0.70859
  Classification -> best τ=0.430 (val F1=0.2515)
  Directional -> Accuracy: 0.4730, MCC: 0.0942, F1: 0.1333

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60129 | val 0.69414
  Epoch 016 - train 0.53646 | val 0.73986
  Classification -> best τ=0.490 (val F1=0.3678)
  Directional -> Accuracy: 0.5532, MCC: -0.0497, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63601 | val 0.86738
  Epoch 014 - train 0.63430 | val 0.84414
  Classification -> best τ=0.580 (val F1=0.2895)
  Directional -> Accuracy: 0.4769, MCC: -0.0550, F1: 0.1500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61926 | val 0.70197
  Epoch 013 - train 0.54634 | val 0.75579
  Classification -> best τ=0.590 (val F1=0.3382)
  Directional -> Accuracy: 0.5614, MCC: 0.1216, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65239 | val 0.85847
  Epoch 011 - train 0.62785 | val 0.99357
  Classification -> best τ=0.550 (val F1=0.0876)
  Directional -> Accuracy: 0.5385, MCC: 0.0616, F1: 0.3182

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59295 | val 0.63655
  Epoch 020 - train 0.55367 | val 0.65432
  Epoch 023 - train 0.51017 | val 0.72325
  Classification -> best τ=0.550 (val F1=0.5345)
  Directional -> Accuracy: 0.5636, MCC: 0.1330, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59718 | val 0.82390
  Epoch 011 - train 0.54751 | val 0.88682
  Classification -> best τ=0.450 (val F1=0.1310)
  Directional -> Accuracy: 0.4444, MCC: -0.1022, F1: 0.4186

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62370 | val 0.68616
  Epoch 011 - train 0.59913 | val 0.69212
  Classification -> best τ=0.565 (val F1=0.1353)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63108 | val 0.92722
  Epoch 015 - train 0.54944 | val 1.08021
  Classification -> best τ=0.395 (val F1=0.2665)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58586 | val 0.74555
  Epoch 015 - train 0.53373 | val 1.06954
  Classification -> best τ=0.520 (val F1=0.2414)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56912 | val 0.74272
  Epoch 012 - train 0.52538 | val 0.86549
  Classification -> best τ=0.385 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64197 | val 1.09562
  Epoch 011 - train 0.58688 | val 0.98179
  Classification -> best τ=0.510 (val F1=0.2238)
  Directional -> Accuracy: 0.3810, MCC: -0.2248, F1: 0.1875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58787 | val 0.73048
  Epoch 012 - train 0.50812 | val 0.82490
  Classification -> best τ=0.430 (val F1=0.2716)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63631 | val 0.70462
  Epoch 020 - train 0.57332 | val 0.84454
  Epoch 021 - train 0.57580 | val 0.97778
  Classification -> best τ=0.335 (val F1=0.4458)
  Directional -> Accuracy: 0.5139, MCC: 0.0733, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63566 | val 1.00307
  Epoch 012 - train 0.59967 | val 1.08053
  Classification -> best τ=0.490 (val F1=0.4366)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64623 | val 0.79730
  Epoch 012 - train 0.59300 | val 0.74868
  Classification -> best τ=0.460 (val F1=0.3551)
  Directional -> Accuracy: 0.6212, MCC: 0.2086, F1: 0.6914

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60270 | val 0.70419
  Epoch 012 - train 0.57613 | val 0.72578
  Classification -> best τ=0.395 (val F1=0.2067)
  Directional -> Accuracy: 0.5476, MCC: 0.0879, F1: 0.5957

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54102 | val 0.90844
  Epoch 013 - train 0.48729 | val 0.98270
  Classification -> best τ=0.545 (val F1=0.2742)
  Directional -> Accuracy: 0.5714, MCC: 0.1260, F1: 0.4545

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58200 | val 1.01850
  Epoch 012 - train 0.57031 | val 1.23125
  Classification -> best τ=0.450 (val F1=0.3397)
  Directional -> Accuracy: 0.5652, MCC: -0.1709, F1: 0.7222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58545 | val 0.77312
  Epoch 020 - train 0.44466 | val 0.76516
  Epoch 022 - train 0.39003 | val 0.81445
  Classification -> best τ=0.595 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68081 | val 0.68800
  Epoch 020 - train 0.62460 | val 0.69030
  Epoch 021 - train 0.59681 | val 0.73896
  Classification -> best τ=0.290 (val F1=0.3823)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56657 | val 0.80029
  Epoch 012 - train 0.54887 | val 0.76391
  Classification -> best τ=0.505 (val F1=0.2874)
  Directional -> Accuracy: 0.5556, MCC: 0.1129, F1: 0.5455

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60341 | val 0.64773
  Epoch 020 - train 0.40503 | val 0.70602
  Epoch 023 - train 0.42634 | val 0.75048
  Classification -> best τ=0.295 (val F1=0.6667)
  Directional -> Accuracy: 0.6190, MCC: 0.1964, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59601 | val 0.70202
  Epoch 020 - train 0.44981 | val 0.71861
  Epoch 029 - train 0.25262 | val 0.96073
  Classification -> best τ=0.795 (val F1=0.4092)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59998 | val 0.78461
  Epoch 011 - train 0.57148 | val 0.79125
  Classification -> best τ=0.605 (val F1=0.1154)
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60077 | val 1.66334
  Epoch 011 - train 0.57888 | val 1.80968
  Classification -> best τ=0.550 (val F1=0.3246)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64477 | val 1.17811
  Epoch 012 - train 0.63940 | val 1.08903
  Classification -> best τ=0.570 (val F1=0.2131)
  Directional -> Accuracy: 0.4717, MCC: -0.0556, F1: 0.4615

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60691 | val 0.84801
  Epoch 013 - train 0.60395 | val 0.67887
  Classification -> best τ=0.430 (val F1=0.1763)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58421 | val 0.71746

[I 2026-02-20 06:04:37,435] Trial 220 finished with value: 0.2840878974482201 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009941560929711758, 'weight_decay': 1.2847113481780996e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1659031104935322, 'early_stopping_min_delta': 0.00299164471246345}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 015 - train 0.58538 | val 0.73533
  Classification -> best τ=0.420 (val F1=0.1708)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2840878974482201
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59165 | val 0.67882
  Epoch 016 - train 0.53373 | val 0.70093
  Classification -> best τ=0.350 (val F1=0.1635)
  Directional -> Accuracy: 0.5395, MCC: 0.1319, F1: 0.5977

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55395 | val 0.66648
  Epoch 019 - train 0.46582 | val 0.68202
  Classification -> best τ=0.325 (val F1=0.2285)
  Directional -> Accuracy: 0.5556, MCC: 0.0372, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61376 | val 0.76970
  Epoch 013 - train 0.58417 | val 0.83806
  Classification -> best τ=0.385 (val F1=0.3262)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65720 | val 1.30310
  Epoch 012 - train 0.65099 | val 0.71691
  Classification -> best τ=0.405 (val F1=0.1778)
  Directional -> Accuracy: 0.5270, MCC: 0.1771, F1: 0.2857

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56319 | val 0.79153
  Epoch 013 - train 0.51673 | val 1.47126
  Classification -> best τ=0.595 (val F1=0.5079)
  Directional -> Accuracy: 0.5400, MCC: 0.1569, F1: 0.3030

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61721 | val 0.84411
  Epoch 011 - train 0.58827 | val 0.79802
  Classification -> best τ=0.550 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: -0.0349, F1: 0.5200

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64028 | val 0.85408
  Epoch 015 - train 0.60731 | val 1.46921
  Classification -> best τ=0.545 (val F1=0.2536)
  Directional -> Accuracy: 0.5000, MCC: 0.0443, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47675 | val 0.66967
  Epoch 012 - train 0.44909 | val 1.05614
  Classification -> best τ=0.290 (val F1=0.2263)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57253 | val 0.71413
  Epoch 012 - train 0.55611 | val 0.68666
  Classification -> best τ=0.480 (val F1=0.2764)
  Directional -> Accuracy: 0.6458, MCC: 0.2667, F1: 0.4848

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59075 | val 0.83455
  Epoch 011 - train 0.56764 | val 0.78417
  Classification -> best τ=0.520 (val F1=0.2671)
  Directional -> Accuracy: 0.4348, MCC: -0.0302, F1: 0.5517

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62412 | val 0.99187
  Epoch 012 - train 0.55203 | val 1.52184
  Classification -> best τ=0.395 (val F1=0.3492)
  Directional -> Accuracy: 0.5510, MCC: 0.1005, F1: 0.5217

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55365 | val 1.50521
  Epoch 013 - train 0.55459 | val 1.57338
  Classification -> best τ=0.375 (val F1=0.3512)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59889 | val 1.16771
  Epoch 013 - train 0.63332 | val 1.00105
  Classification -> best τ=0.575 (val F1=0.3467)
  Directional -> Accuracy: 0.5000, MCC: 0.0235, F1: 0.5333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61680 | val 0.65197
  Epoch 015 - train 0.59258 | val 0.78091
  Classification -> best τ=0.345 (val F1=0.3601)
  Directional -> Accuracy: 0.5500, MCC: 0.1001, F1: 0.5574

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57613 | val 0.70960
  Epoch 011 - train 0.61873 | val 0.81169
  Classification -> best τ=0.510 (val F1=0.3333)
  Directional -> Accuracy: 0.4118, MCC: -0.2229, F1: 0.5833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60332 | val 1.14371
  Epoch 012 - train 0.59578 | val 1.02309
  Classification -> best τ=0.675 (val F1=0.3679)
  Directional -> Accuracy: 0.5652, MCC: 0.1945, F1: 0.4444

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60582 | val 1.66506
  Epoch 013 - train 0.59889 | val 1.78166
  Classification -> best τ=0.675 (val F1=0.2651)
  Directional -> Accuracy: 0.3276, MCC: -0.2663, F1: 0.0488

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60053 | val 0.83239
  Epoch 012 - train 0.59476 | val 1.39694
  Classification -> best τ=0.470 (val F1=0.1653)
  Directional -> Accuracy: 0.6000, MCC: 0.2069, F1: 0.6341

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59921 | val 1.00537
  Epoch 012 - train 0.58843 | val 1.06727
  Classification -> best τ=0.470 (val F1=0.1931)
  Directional -> Accuracy: 0.5000, MCC: 0.1635, F1: 0.3043

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67348 | val 0.68389
  Epoch 012 - train 0.62655 | val 0.75745
  Classification -> best τ=0.475 (val F1=0.2700)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62290 | val 0.67481
  Epoch 020 - train 0.48176 | val 1.25590
  Classification -> best τ=0.460 (val F1=0.3693)
  Directional -> Accuracy: 0.4043, MCC: -0.0392, F1: 0.2222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64266 | val 0.73081
  Epoch 012 - train 0.62727 | val 0.80984
  Classification -> best τ=0.415 (val F1=0.2529)
  Directional -> Accuracy: 0.6154, MCC: 0.2315, F1: 0.6479

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62363 | val 0.81529
  Epoch 014 - train 0.59125 | val 0.84167
  Classification -> best τ=0.550 (val F1=0.3656)
  Directional -> Accuracy: 0.5263, MCC: 0.1268, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59449 | val 0.75988
  Epoch 012 - train 0.62158 | val 1.09226
  Classification -> best τ=0.495 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0082, F1: 0.0606

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57037 | val 0.87715
  Epoch 016 - train 0.47366 | val 0.84658
  Classification -> best τ=0.655 (val F1=0.4002)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51317 | val 1.40417
  Epoch 011 - train 0.50346 | val 1.67767
  Classification -> best τ=0.450 (val F1=0.1310)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60376 | val 0.70921
  Epoch 015 - train 0.54113 | val 0.74361
  Classification -> best τ=0.595 (val F1=0.3184)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59881 | val 0.81904
  Epoch 015 - train 0.57700 | val 1.20869
  Classification -> best τ=0.400 (val F1=0.2435)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63571 | val 0.78589
  Epoch 011 - train 0.60267 | val 0.81199
  Classification -> best τ=0.505 (val F1=0.2267)
  Directional -> Accuracy: 0.5000, MCC: -0.1340, F1: 0.6552

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56970 | val 1.10348
  Epoch 012 - train 0.60055 | val 0.93261
  Classification -> best τ=0.635 (val F1=0.3501)
  Directional -> Accuracy: 0.5714, MCC: 0.1409, F1: 0.5500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58452 | val 1.03798
  Epoch 012 - train 0.54608 | val 1.86950
  Classification -> best τ=0.525 (val F1=0.1195)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60024 | val 0.75219
  Epoch 012 - train 0.54945 | val 0.77132
  Classification -> best τ=0.445 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62490 | val 0.66963
  Epoch 017 - train 0.50050 | val 0.71217
  Classification -> best τ=0.290 (val F1=0.4032)
  Directional -> Accuracy: 0.5000, MCC: 0.0555, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58966 | val 0.98554
  Epoch 011 - train 0.59724 | val 1.08264
  Classification -> best τ=0.440 (val F1=0.2717)
  Directional -> Accuracy: 0.5814, MCC: 0.1615, F1: 0.5263

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63328 | val 0.76746
  Epoch 011 - train 0.63392 | val 0.79341
  Classification -> best τ=0.405 (val F1=0.1372)
  Directional -> Accuracy: 0.6364, MCC: 0.2556, F1: 0.6842

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58618 | val 0.73442
  Epoch 017 - train 0.51752 | val 1.15865
  Classification -> best τ=0.495 (val F1=0.2658)
  Directional -> Accuracy: 0.5714, MCC: 0.1779, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52916 | val 0.75877
  Epoch 015 - train 0.47360 | val 0.80962
  Classification -> best τ=0.455 (val F1=0.3280)
  Directional -> Accuracy: 0.5357, MCC: 0.0769, F1: 0.5357

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53870 | val 0.96036
  Epoch 011 - train 0.47249 | val 0.85244
  Classification -> best τ=0.500 (val F1=0.1776)
  Directional -> Accuracy: 0.5652, MCC: 0.0505, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57850 | val 0.67258
  Epoch 016 - train 0.47429 | val 0.64812
  Classification -> best τ=0.360 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58661 | val 0.82286
  Epoch 014 - train 0.54672 | val 0.76222
  Classification -> best τ=0.500 (val F1=0.3880)
  Directional -> Accuracy: 0.5270, MCC: 0.0470, F1: 0.3860

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64065 | val 0.74687
  Epoch 015 - train 0.51360 | val 0.83324
  Classification -> best τ=0.565 (val F1=0.2174)
  Directional -> Accuracy: 0.4667, MCC: -0.0644, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62924 | val 0.83857
  Epoch 020 - train 0.47560 | val 0.58588
  Epoch 026 - train 0.48895 | val 0.72272
  Classification -> best τ=0.340 (val F1=0.5092)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61616 | val 0.67277
  Epoch 012 - train 0.56076 | val 0.64531
  Classification -> best τ=0.650 (val F1=0.5689)
  Directional -> Accuracy: 0.5833, MCC: 0.2739, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61648 | val 0.81672
  Epoch 012 - train 0.56797 | val 0.67863
  Classification -> best τ=0.570 (val F1=0.2452)
  Directional -> Accuracy: 0.4909, MCC: 0.0305, F1: 0.3636

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61325 | val 1.56363
  Epoch 011 - train 0.59061 | val 1.86244
  Classification -> best τ=0.615 (val F1=0.3164)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62271 | val 1.00368
  Epoch 012 - train 0.63666 | val 0.79129
  Classification -> best τ=0.680 (val F1=0.2064)
  Directional -> Accuracy: 0.5283, MCC: 0.1943, F1: 0.1379

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66748 | val 0.73731
  Epoch 013 - train 0.66331 | val 0.74172
  Classification -> best τ=0.445 (val F1=0.0214)
  Directional -> Accuracy: 0.4545, MCC: -0.0755, F1: 0.1667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-20 06:05:31,785] Trial 221 finished with value: 0.28173884179766934 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009927824418321346, 'weight_decay': 1.2179010553738988e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1747388648027306, 'early_stopping_min_delta': 0.009051237798100143}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 010 - train 0.58803 | val 0.79358
  Epoch 011 - train 0.58899 | val 0.82706
  Classification -> best τ=0.445 (val F1=0.0673)
  Directional -> Accuracy: 0.5333, MCC: 0.1039, F1: 0.6316

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28173884179766934
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59234 | val 0.67878
  Epoch 012 - train 0.56369 | val 0.78761
  Classification -> best τ=0.310 (val F1=0.1415)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55363 | val 0.68019
  Epoch 020 - train 0.39347 | val 0.73413
  Epoch 026 - train 0.34517 | val 0.70134
  Classification -> best τ=0.485 (val F1=0.5021)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58709 | val 0.68423
  Epoch 012 - train 0.60097 | val 0.76493
  Classification -> best τ=0.530 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63431 | val 0.91772
  Epoch 012 - train 0.64496 | val 0.78190
  Classification -> best τ=0.365 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59194 | val 0.61566
  Epoch 019 - train 0.52847 | val 1.08122
  Classification -> best τ=0.585 (val F1=0.5298)
  Directional -> Accuracy: 0.6800, MCC: 0.4462, F1: 0.5789

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60449 | val 0.71293
  Epoch 013 - train 0.61759 | val 0.80417
  Classification -> best τ=0.480 (val F1=0.3069)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62038 | val 0.98253
  Epoch 013 - train 0.65198 | val 1.44045
  Classification -> best τ=0.570 (val F1=0.1833)
  Directional -> Accuracy: 0.5000, MCC: -0.0062, F1: 0.4333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58657 | val 1.45757
  Epoch 012 - train 0.46944 | val 1.19342
  Classification -> best τ=0.365 (val F1=0.2263)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56124 | val 0.70650
  Epoch 018 - train 0.51762 | val 0.79888
  Classification -> best τ=0.605 (val F1=0.2988)
  Directional -> Accuracy: 0.6042, MCC: 0.1680, F1: 0.3871

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60537 | val 2.01828
  Epoch 012 - train 0.61389 | val 0.83182
  Classification -> best τ=0.405 (val F1=0.2679)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62859 | val 1.12968
  Epoch 013 - train 0.59809 | val 1.07516
  Classification -> best τ=0.320 (val F1=0.3939)
  Directional -> Accuracy: 0.5714, MCC: 0.1237, F1: 0.4878

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63058 | val 1.47271
  Epoch 016 - train 0.46505 | val 1.82217
  Classification -> best τ=0.445 (val F1=0.3122)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57497 | val 1.04171
  Epoch 012 - train 0.53620 | val 1.37022
  Classification -> best τ=0.490 (val F1=0.2172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62074 | val 0.66529
  Epoch 013 - train 0.58097 | val 0.63255
  Classification -> best τ=0.370 (val F1=0.4019)
  Directional -> Accuracy: 0.5667, MCC: 0.1455, F1: 0.6389

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61178 | val 0.94329
  Epoch 011 - train 0.57891 | val 0.84099
  Classification -> best τ=0.470 (val F1=0.0730)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59432 | val 1.17608
  Epoch 013 - train 0.63626 | val 1.12681
  Classification -> best τ=0.645 (val F1=0.2299)
  Directional -> Accuracy: 0.4928, MCC: 0.0176, F1: 0.3860

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62214 | val 1.33174
  Epoch 011 - train 0.62536 | val 1.35636
  Classification -> best τ=0.500 (val F1=0.0086)
  Directional -> Accuracy: 0.6207, MCC: 0.0677, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57422 | val 1.14623
  Epoch 012 - train 0.62049 | val 1.12244
  Classification -> best τ=0.430 (val F1=0.0635)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65789 | val 0.81938
  Epoch 013 - train 0.64423 | val 1.57605
  Classification -> best τ=0.385 (val F1=0.3057)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67095 | val 0.73423
  Epoch 016 - train 0.62301 | val 0.69760
  Classification -> best τ=0.450 (val F1=0.2871)
  Directional -> Accuracy: 0.3919, MCC: -0.2047, F1: 0.3836

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56877 | val 0.73496
  Epoch 020 - train 0.42697 | val 0.91913
  Epoch 023 - train 0.43659 | val 1.40828
  Classification -> best τ=0.335 (val F1=0.3262)
  Directional -> Accuracy: 0.4468, MCC: 0.0497, F1: 0.3158

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64184 | val 1.25931
  Epoch 014 - train 0.59051 | val 1.61020
  Classification -> best τ=0.630 (val F1=0.2766)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62850 | val 0.67272
  Epoch 020 - train 0.57661 | val 0.91826
  Classification -> best τ=0.515 (val F1=0.4027)
  Directional -> Accuracy: 0.5789, MCC: 0.1450, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59469 | val 0.81888
  Epoch 012 - train 0.60577 | val 0.70729
  Classification -> best τ=0.520 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60445 | val 0.72378
  Epoch 016 - train 0.55922 | val 0.72338
  Classification -> best τ=0.565 (val F1=0.5155)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51033 | val 1.62436
  Epoch 011 - train 0.51945 | val 1.83244
  Classification -> best τ=0.430 (val F1=0.1310)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59381 | val 0.73294
  Epoch 011 - train 0.62560 | val 0.69972
  Classification -> best τ=0.615 (val F1=0.1487)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63559 | val 0.70523
  Epoch 016 - train 0.56437 | val 0.92670
  Classification -> best τ=0.310 (val F1=0.2614)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57719 | val 1.13574
  Epoch 012 - train 0.55485 | val 1.83381
  Classification -> best τ=0.555 (val F1=0.5136)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60526 | val 1.32625
  Epoch 012 - train 0.59429 | val 0.96228
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52902 | val 1.16485
  Epoch 017 - train 0.42453 | val 1.19832
  Classification -> best τ=0.655 (val F1=0.1846)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59828 | val 0.87852
  Epoch 015 - train 0.53285 | val 1.33427
  Classification -> best τ=0.455 (val F1=0.3886)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62202 | val 0.76621
  Epoch 018 - train 0.53533 | val 0.93762
  Classification -> best τ=0.385 (val F1=0.3450)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59568 | val 1.23227
  Epoch 011 - train 0.57034 | val 1.18724
  Classification -> best τ=0.455 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63143 | val 0.78309
  Epoch 015 - train 0.65547 | val 0.79690
  Classification -> best τ=0.330 (val F1=0.3551)
  Directional -> Accuracy: 0.5606, MCC: 0.1647, F1: 0.5397

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55233 | val 1.02930
  Epoch 011 - train 0.51023 | val 1.45492
  Classification -> best τ=0.570 (val F1=0.2292)
  Directional -> Accuracy: 0.5476, MCC: 0.1228, F1: 0.4571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56892 | val 0.89385
  Epoch 014 - train 0.50731 | val 1.07095
  Classification -> best τ=0.490 (val F1=0.2868)
  Directional -> Accuracy: 0.4107, MCC: -0.1706, F1: 0.5352

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54293 | val 1.06509
  Epoch 011 - train 0.50647 | val 1.08516
  Classification -> best τ=0.430 (val F1=0.0602)
  Directional -> Accuracy: 0.4783, MCC: 0.0986, F1: 0.3684

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60235 | val 0.83495
  Epoch 020 - train 0.47348 | val 0.81570
  Epoch 022 - train 0.42714 | val 0.78834
  Classification -> best τ=0.535 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60462 | val 0.76197
  Epoch 015 - train 0.61757 | val 0.73208
  Classification -> best τ=0.615 (val F1=0.3622)
  Directional -> Accuracy: 0.4865, MCC: -0.0094, F1: 0.6275

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62135 | val 0.70620
  Epoch 011 - train 0.54935 | val 0.73344
  Classification -> best τ=0.420 (val F1=0.3287)
  Directional -> Accuracy: 0.4667, MCC: -0.0667, F1: 0.2500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61086 | val 0.74818
  Epoch 020 - train 0.49624 | val 0.84960
  Epoch 030 - train 0.34589 | val 0.51667
  Epoch 040 - train 0.14577 | val 0.56973
  Epoch 047 - train 0.13910 | val 0.59664
  Classification -> best τ=0.105 (val F1=0.6124)
  Directional -> Accuracy: 0.5952, MCC: 0.1407, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59644 | val 0.66610
  Epoch 014 - train 0.53735 | val 0.69436
  Classification -> best τ=0.605 (val F1=0.6058)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57728 | val 0.82418
  Epoch 019 - train 0.47667 | val 0.82238
  Classification -> best τ=0.590 (val F1=0.1874)
  Directional -> Accuracy: 0.4182, MCC: -0.3486, F1: 0.5897

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59881 | val 1.79672
  Epoch 012 - train 0.58146 | val 1.98059
  Classification -> best τ=0.590 (val F1=0.3526)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62519 | val 0.86953
  Epoch 017 - train 0.56999 | val 0.97235
  Classification -> best τ=0.380 (val F1=0.2351)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64972 | val 0.93527
  Epoch 014 - train 0.58499 | val 1.02073
  Classification -> best τ=0.410 (val F1=0.2085)
  Directional -> Accuracy: 0.5273, MCC: 0.0350, F1: 0.6176

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59714 | val 0.71937

[I 2026-02-20 06:06:31,622] Trial 222 finished with value: 0.29221190808899017 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008603079845978896, 'weight_decay': 1.1000467910623144e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.159329515518589, 'early_stopping_min_delta': 0.0031100990810784164}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.57076 | val 0.82898
  Classification -> best τ=0.410 (val F1=0.2843)
  Directional -> Accuracy: 0.4667, MCC: -0.0804, F1: 0.3600

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29221190808899017
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66728 | val 0.71583
  Epoch 015 - train 0.58957 | val 0.73774
  Classification -> best τ=0.595 (val F1=0.2036)
  Directional -> Accuracy: 0.6053, MCC: 0.1879, F1: 0.5000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59997 | val 0.69596
  Epoch 014 - train 0.50853 | val 0.79247
  Classification -> best τ=0.475 (val F1=0.3779)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57282 | val 0.79796
  Epoch 015 - train 0.51378 | val 0.83355
  Classification -> best τ=0.490 (val F1=0.3835)
  Directional -> Accuracy: 0.5652, MCC: 0.2416, F1: 0.3333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64063 | val 1.09593
  Epoch 012 - train 0.62884 | val 1.06553
  Classification -> best τ=0.600 (val F1=0.2042)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64157 | val 0.87781
  Epoch 015 - train 0.48436 | val 1.16093
  Classification -> best τ=0.570 (val F1=0.4611)
  Directional -> Accuracy: 0.5000, MCC: 0.0333, F1: 0.2857

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62313 | val 0.76969
  Epoch 011 - train 0.61946 | val 0.73526
  Classification -> best τ=0.685 (val F1=0.2739)
  Directional -> Accuracy: 0.5652, MCC: 0.1234, F1: 0.4444

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64863 | val 0.69820
  Epoch 015 - train 0.61026 | val 0.91094
  Classification -> best τ=0.490 (val F1=0.2536)
  Directional -> Accuracy: 0.5588, MCC: 0.0903, F1: 0.4643

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51784 | val 1.01769
  Epoch 012 - train 0.47168 | val 0.98951
  Classification -> best τ=0.305 (val F1=0.2263)
  Directional -> Accuracy: 0.4762, MCC: -0.1452, F1: 0.2143

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58853 | val 0.70853
  Epoch 012 - train 0.53822 | val 0.77548
  Classification -> best τ=0.505 (val F1=0.3441)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58347 | val 0.93044
  Epoch 015 - train 0.51394 | val 1.20705
  Classification -> best τ=0.360 (val F1=0.0867)
  Directional -> Accuracy: 0.4348, MCC: 0.0376, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57184 | val 0.81863
  Epoch 013 - train 0.61737 | val 0.79704
  Classification -> best τ=0.385 (val F1=0.1965)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55402 | val 1.42863
  Epoch 011 - train 0.52939 | val 1.58687
  Classification -> best τ=0.525 (val F1=0.2428)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58873 | val 1.30188
  Epoch 012 - train 0.52601 | val 1.43209
  Classification -> best τ=0.505 (val F1=0.2933)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61622 | val 0.59007
  Epoch 020 - train 0.53809 | val 0.73184
  Classification -> best τ=0.440 (val F1=0.4193)
  Directional -> Accuracy: 0.5500, MCC: 0.1028, F1: 0.4906

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58668 | val 0.79847
  Epoch 011 - train 0.55154 | val 0.79321
  Classification -> best τ=0.505 (val F1=0.4068)
  Directional -> Accuracy: 0.4706, MCC: 0.0061, F1: 0.5846

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65142 | val 0.78251
  Epoch 012 - train 0.60434 | val 0.85928
  Classification -> best τ=0.470 (val F1=0.2341)
  Directional -> Accuracy: 0.5652, MCC: 0.1256, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58764 | val 1.81737
  Epoch 011 - train 0.56037 | val 2.18199
  Classification -> best τ=0.415 (val F1=0.0499)
  Directional -> Accuracy: 0.5690, MCC: 0.0765, F1: 0.6575

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63906 | val 1.31679
  Epoch 012 - train 0.60597 | val 1.41759
  Classification -> best τ=0.580 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57846 | val 1.06748
  Epoch 011 - train 0.64971 | val 1.32884
  Classification -> best τ=0.585 (val F1=0.1269)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57062 | val 0.73470
  Epoch 018 - train 0.51873 | val 0.77094
  Classification -> best τ=0.605 (val F1=0.3162)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56607 | val 0.90538
  Epoch 020 - train 0.35122 | val 1.09025
  Epoch 022 - train 0.43142 | val 0.94810
  Classification -> best τ=0.425 (val F1=0.3693)
  Directional -> Accuracy: 0.4681, MCC: 0.0887, F1: 0.3590

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68324 | val 1.00149
  Epoch 011 - train 0.64643 | val 0.91139
  Classification -> best τ=0.460 (val F1=0.2673)
  Directional -> Accuracy: 0.5231, MCC: 0.0480, F1: 0.6437

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65599 | val 0.65374
  Epoch 020 - train 0.50315 | val 0.73891
  Classification -> best τ=0.590 (val F1=0.3820)
  Directional -> Accuracy: 0.5439, MCC: 0.1198, F1: 0.5185

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64699 | val 0.80979
  Epoch 013 - train 0.57687 | val 0.74159
  Classification -> best τ=0.485 (val F1=0.0882)
  Directional -> Accuracy: 0.4923, MCC: -0.0917, F1: 0.1081

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58940 | val 0.63652
  Epoch 018 - train 0.50935 | val 0.98990
  Classification -> best τ=0.515 (val F1=0.5635)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57286 | val 0.87356
  Epoch 012 - train 0.49754 | val 1.22567
  Classification -> best τ=0.600 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65170 | val 0.69925
  Epoch 012 - train 0.59345 | val 0.71563
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61200 | val 0.72310
  Epoch 011 - train 0.58932 | val 0.86846
  Classification -> best τ=0.525 (val F1=0.1794)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55023 | val 0.76994
  Epoch 014 - train 0.50448 | val 0.72703
  Classification -> best τ=0.490 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55283 | val 1.39906
  Epoch 012 - train 0.53275 | val 1.79109
  Classification -> best τ=0.565 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61514 | val 1.82907
  Epoch 011 - train 0.60486 | val 1.68575
  Classification -> best τ=0.425 (val F1=0.2042)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56523 | val 0.75510
  Epoch 012 - train 0.54184 | val 0.74061
  Classification -> best τ=0.445 (val F1=0.4278)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63335 | val 0.71519
  Epoch 012 - train 0.60544 | val 0.73813
  Classification -> best τ=0.395 (val F1=0.3815)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64798 | val 1.18364
  Epoch 012 - train 0.59899 | val 1.03835
  Classification -> best τ=0.600 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66976 | val 0.75735
  Epoch 012 - train 0.64815 | val 0.76636
  Classification -> best τ=0.350 (val F1=0.3603)
  Directional -> Accuracy: 0.5909, MCC: 0.1376, F1: 0.6747

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59283 | val 0.75693
  Epoch 013 - train 0.55499 | val 0.87746
  Classification -> best τ=0.415 (val F1=0.2144)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54374 | val 0.86838
  Epoch 011 - train 0.54438 | val 0.92913
  Classification -> best τ=0.465 (val F1=0.2382)
  Directional -> Accuracy: 0.5357, MCC: 0.0961, F1: 0.5806

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49152 | val 1.28613
  Epoch 011 - train 0.41537 | val 1.43061
  Classification -> best τ=0.465 (val F1=0.1074)
  Directional -> Accuracy: 0.5000, MCC: -0.0393, F1: 0.5818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63793 | val 0.91567
  Epoch 011 - train 0.59656 | val 0.91351
  Classification -> best τ=0.425 (val F1=0.3469)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54881 | val 0.87672
  Epoch 012 - train 0.59783 | val 1.06146
  Classification -> best τ=0.495 (val F1=0.2996)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54449 | val 0.79284
  Epoch 015 - train 0.49087 | val 1.14857
  Classification -> best τ=0.460 (val F1=0.3953)
  Directional -> Accuracy: 0.5111, MCC: 0.0391, F1: 0.3529

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69268 | val 0.76603
  Epoch 013 - train 0.56241 | val 0.79546
  Classification -> best τ=0.495 (val F1=0.6124)
  Directional -> Accuracy: 0.5000, MCC: -0.0782, F1: 0.6182

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60571 | val 0.61979
  Epoch 020 - train 0.41512 | val 0.60113
  Epoch 030 - train 0.17260 | val 0.77201
  Epoch 033 - train 0.16439 | val 1.04878
  Classification -> best τ=0.340 (val F1=0.6885)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60377 | val 0.71366
  Epoch 011 - train 0.60231 | val 0.71178
  Classification -> best τ=0.670 (val F1=0.1154)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59319 | val 1.20362
  Epoch 012 - train 0.55758 | val 1.73852
  Classification -> best τ=0.755 (val F1=0.2143)
  Directional -> Accuracy: 0.5179, MCC: 0.0309, F1: 0.4706

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63254 | val 0.94583
  Epoch 018 - train 0.54174 | val 1.10902
  Classification -> best τ=0.840 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67032 | val 0.76715
  Epoch 011 - train 0.64482 | val 0.78825
  Classification -> best τ=0.475 (val F1=0.0602)
  Directional -> Accuracy: 0.5636, MCC: 0.1258, F1: 0.6842

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57187 | val 0.68483

[I 2026-02-20 06:07:27,504] Trial 223 finished with value: 0.2836748375664993 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009977931650320754, 'weight_decay': 1.0648557336621064e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1764150121827242, 'early_stopping_min_delta': 0.009974025584266851}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.56168 | val 0.74429
  Classification -> best τ=0.440 (val F1=0.2354)
  Directional -> Accuracy: 0.4667, MCC: -0.0679, F1: 0.4483

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2836748375664993
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62314 | val 0.75840
  Epoch 015 - train 0.59722 | val 1.08681
  Classification -> best τ=0.570 (val F1=0.2036)
  Directional -> Accuracy: 0.6053, MCC: 0.1978, F1: 0.3182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55832 | val 0.70557
  Epoch 013 - train 0.54903 | val 0.67820
  Classification -> best τ=0.405 (val F1=0.2590)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.6545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59255 | val 0.96013
  Epoch 015 - train 0.56111 | val 1.22735
  Classification -> best τ=0.505 (val F1=0.3171)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64961 | val 0.82541
  Epoch 016 - train 0.60239 | val 0.76113
  Classification -> best τ=0.410 (val F1=0.3162)
  Directional -> Accuracy: 0.4730, MCC: -0.2053, F1: 0.6355

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56333 | val 0.85521
  Epoch 013 - train 0.56808 | val 0.80724
  Classification -> best τ=0.525 (val F1=0.4364)
  Directional -> Accuracy: 0.5400, MCC: 0.1237, F1: 0.3784

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63890 | val 0.78253
  Epoch 014 - train 0.55686 | val 0.72010
  Classification -> best τ=0.490 (val F1=0.1463)
  Directional -> Accuracy: 0.4348, MCC: -0.1461, F1: 0.5806

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62319 | val 0.93504
  Epoch 012 - train 0.60286 | val 0.91929
  Classification -> best τ=0.400 (val F1=0.2937)
  Directional -> Accuracy: 0.4265, MCC: 0.0751, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50664 | val 0.80415
  Epoch 012 - train 0.49755 | val 1.13528
  Classification -> best τ=0.365 (val F1=0.1228)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55935 | val 0.69782
  Epoch 020 - train 0.51410 | val 0.68687
  Epoch 030 - train 0.41197 | val 1.45744
  Epoch 032 - train 0.44783 | val 0.75097
  Classification -> best τ=0.525 (val F1=0.4587)
  Directional -> Accuracy: 0.5417, MCC: 0.2454, F1: 0.6452

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56662 | val 0.69467
  Epoch 012 - train 0.54495 | val 0.79607
  Classification -> best τ=0.490 (val F1=0.1858)
  Directional -> Accuracy: 0.4348, MCC: -0.0667, F1: 0.5063

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69910 | val 0.80185
  Epoch 014 - train 0.58680 | val 0.95260
  Classification -> best τ=0.425 (val F1=0.1199)
  Directional -> Accuracy: 0.5510, MCC: 0.1707, F1: 0.6207

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57792 | val 1.12270
  Epoch 016 - train 0.56615 | val 1.57750
  Classification -> best τ=0.560 (val F1=0.2741)
  Directional -> Accuracy: 0.6316, MCC: 0.2744, F1: 0.5882

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60366 | val 1.15970
  Epoch 012 - train 0.57884 | val 1.39129
  Classification -> best τ=0.470 (val F1=0.1923)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59340 | val 0.62913
  Epoch 020 - train 0.52502 | val 0.65810
  Epoch 022 - train 0.52120 | val 0.63412
  Classification -> best τ=0.365 (val F1=0.3407)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.4727

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58684 | val 1.28830
  Epoch 012 - train 0.52660 | val 0.87599
  Classification -> best τ=0.455 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64466 | val 0.75632
  Epoch 012 - train 0.59824 | val 0.78984
  Classification -> best τ=0.515 (val F1=0.2996)
  Directional -> Accuracy: 0.6087, MCC: 0.2102, F1: 0.6966

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65607 | val 0.89141
  Epoch 011 - train 0.65470 | val 0.90664
  Classification -> best τ=0.550 (val F1=0.1231)
  Directional -> Accuracy: 0.3966, MCC: -0.1806, F1: 0.4262

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61168 | val 1.25438
  Epoch 011 - train 0.61706 | val 1.25539
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62762 | val 1.04303
  Epoch 015 - train 0.64383 | val 1.49297
  Classification -> best τ=0.500 (val F1=0.2315)
  Directional -> Accuracy: 0.4062, MCC: -0.1061, F1: 0.1364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61907 | val 0.70792
  Epoch 015 - train 0.60662 | val 0.77814
  Classification -> best τ=0.465 (val F1=0.3460)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61582 | val 0.68563
  Epoch 020 - train 0.41248 | val 0.71312
  Epoch 022 - train 0.38212 | val 1.05078
  Classification -> best τ=0.390 (val F1=0.3262)
  Directional -> Accuracy: 0.5319, MCC: 0.0504, F1: 0.5926

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62830 | val 1.28986
  Epoch 013 - train 0.60629 | val 1.39596
  Classification -> best τ=0.395 (val F1=0.2529)
  Directional -> Accuracy: 0.4769, MCC: -0.1014, F1: 0.6304

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62718 | val 0.72872
  Epoch 012 - train 0.62551 | val 0.76471
  Classification -> best τ=0.695 (val F1=0.3276)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61460 | val 0.73030
  Epoch 020 - train 0.60445 | val 0.76074
  Epoch 025 - train 0.54650 | val 0.72960
  Classification -> best τ=0.395 (val F1=0.2642)
  Directional -> Accuracy: 0.4615, MCC: -0.0616, F1: 0.5783

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57187 | val 0.70328
  Epoch 016 - train 0.51598 | val 0.83591
  Classification -> best τ=0.530 (val F1=0.5009)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54750 | val 0.87742
  Epoch 014 - train 0.50332 | val 1.39817
  Classification -> best τ=0.540 (val F1=0.3464)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.3077

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62004 | val 0.78168
  Epoch 015 - train 0.58128 | val 0.71880
  Classification -> best τ=0.570 (val F1=0.1105)
  Directional -> Accuracy: 0.4762, MCC: 0.0525, F1: 0.3125

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65840 | val 0.68717
  Epoch 017 - train 0.57074 | val 0.94269
  Classification -> best τ=0.610 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62744 | val 0.69891
  Epoch 014 - train 0.52018 | val 0.70214
  Classification -> best τ=0.505 (val F1=0.1748)
  Directional -> Accuracy: 0.6750, MCC: 0.3472, F1: 0.6977

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57844 | val 1.01846
  Epoch 012 - train 0.56310 | val 0.93241
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57710 | val 0.73735
  Epoch 012 - train 0.53447 | val 1.14767
  Classification -> best τ=0.540 (val F1=0.1804)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63165 | val 0.86974
  Epoch 014 - train 0.52034 | val 0.98916
  Classification -> best τ=0.425 (val F1=0.3069)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60451 | val 0.65766
  Epoch 012 - train 0.59783 | val 0.68045
  Classification -> best τ=0.385 (val F1=0.4460)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63167 | val 0.82613
  Epoch 012 - train 0.59793 | val 0.81859
  Classification -> best τ=0.620 (val F1=0.2780)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67615 | val 0.69479
  Epoch 017 - train 0.66152 | val 0.80572
  Classification -> best τ=0.510 (val F1=0.3510)
  Directional -> Accuracy: 0.4394, MCC: -0.0162, F1: 0.2128

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55404 | val 1.55158
  Epoch 012 - train 0.52216 | val 2.38754
  Classification -> best τ=0.565 (val F1=0.3260)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54112 | val 0.81556
  Epoch 012 - train 0.56094 | val 0.87031
  Classification -> best τ=0.320 (val F1=0.2946)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51392 | val 1.16108
  Epoch 012 - train 0.51625 | val 1.67363
  Classification -> best τ=0.380 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57075 | val 0.69137
  Epoch 020 - train 0.48003 | val 0.91643
  Epoch 021 - train 0.52385 | val 0.93685
  Classification -> best τ=0.410 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61021 | val 0.69080
  Epoch 016 - train 0.59416 | val 0.71446
  Classification -> best τ=0.435 (val F1=0.2765)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54684 | val 0.87894
  Epoch 013 - train 0.50607 | val 1.34996
  Classification -> best τ=0.535 (val F1=0.2668)
  Directional -> Accuracy: 0.5111, MCC: 0.0314, F1: 0.4211

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65417 | val 0.73888
  Epoch 020 - train 0.51290 | val 0.65921
  Epoch 024 - train 0.48251 | val 0.65594
  Classification -> best τ=0.425 (val F1=0.5601)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60687 | val 0.66661
  Epoch 014 - train 0.54748 | val 0.68240
  Classification -> best τ=0.605 (val F1=0.3895)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58234 | val 0.75385
  Epoch 011 - train 0.55845 | val 0.81011
  Classification -> best τ=0.600 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61144 | val 1.25377
  Epoch 011 - train 0.57538 | val 1.21344
  Classification -> best τ=0.585 (val F1=0.3088)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60716 | val 1.20020
  Epoch 012 - train 0.59057 | val 1.50513
  Classification -> best τ=0.500 (val F1=0.2309)
  Directional -> Accuracy: 0.5094, MCC: 0.0113, F1: 0.6061

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62219 | val 0.73722
  Epoch 019 - train 0.53028 | val 0.98582
  Classification -> best τ=0.485 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64060 | val 0.72267

[I 2026-02-20 06:08:26,014] Trial 224 finished with value: 0.2765108970386502 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008640474041532972, 'weight_decay': 1.137296054858469e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2515231705655698, 'early_stopping_min_delta': 0.0021435646426022957}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.58413 | val 0.76564
  Classification -> best τ=0.490 (val F1=0.2623)
  Directional -> Accuracy: 0.6500, MCC: 0.3130, F1: 0.5532

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2765108970386502
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61166 | val 0.79789
  Epoch 020 - train 0.61339 | val 0.88758
  Epoch 022 - train 0.56824 | val 0.74503
  Classification -> best τ=0.410 (val F1=0.3141)
  Directional -> Accuracy: 0.4868, MCC: -0.0349, F1: 0.4348

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61891 | val 0.66971
  Epoch 020 - train 0.54712 | val 0.70558
  Classification -> best τ=0.400 (val F1=0.2314)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65193 | val 0.75775
  Epoch 019 - train 0.48460 | val 1.23280
  Classification -> best τ=0.585 (val F1=0.4252)
  Directional -> Accuracy: 0.3696, MCC: -0.3213, F1: 0.0645

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62845 | val 0.93182
  Epoch 020 - train 0.58908 | val 1.04854
  Epoch 023 - train 0.54453 | val 0.82401
  Classification -> best τ=0.525 (val F1=0.2030)
  Directional -> Accuracy: 0.5405, MCC: 0.0358, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60645 | val 0.73824
  Epoch 013 - train 0.60157 | val 0.95613
  Classification -> best τ=0.565 (val F1=0.4930)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66276 | val 0.81251
  Epoch 013 - train 0.60121 | val 0.83961
  Classification -> best τ=0.490 (val F1=0.2208)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63897 | val 1.02378
  Epoch 014 - train 0.65854 | val 0.97390
  Classification -> best τ=0.550 (val F1=0.2727)
  Directional -> Accuracy: 0.5441, MCC: 0.0039, F1: 0.3404

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51328 | val 0.96952
  Epoch 012 - train 0.52195 | val 1.43988
  Classification -> best τ=0.360 (val F1=0.1147)
  Directional -> Accuracy: 0.4762, MCC: -0.1217, F1: 0.2667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58694 | val 0.79941
  Epoch 012 - train 0.57939 | val 0.86254
  Classification -> best τ=0.470 (val F1=0.3652)
  Directional -> Accuracy: 0.6250, MCC: 0.2185, F1: 0.4706

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63764 | val 0.73561
  Epoch 016 - train 0.57534 | val 1.05293
  Classification -> best τ=0.465 (val F1=0.1858)
  Directional -> Accuracy: 0.4928, MCC: -0.0562, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63376 | val 0.75324
  Epoch 015 - train 0.59974 | val 0.93413
  Classification -> best τ=0.420 (val F1=0.1949)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53134 | val 1.32447
  Epoch 012 - train 0.48954 | val 1.64768
  Classification -> best τ=0.580 (val F1=0.1685)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62028 | val 0.81269
  Epoch 012 - train 0.64916 | val 0.97374
  Classification -> best τ=0.400 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61196 | val 0.70731
  Epoch 017 - train 0.56685 | val 0.76210
  Classification -> best τ=0.440 (val F1=0.4267)
  Directional -> Accuracy: 0.5500, MCC: 0.1014, F1: 0.5091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55815 | val 0.87846
  Epoch 011 - train 0.57292 | val 0.94263
  Classification -> best τ=0.570 (val F1=0.3390)
  Directional -> Accuracy: 0.4118, MCC: -0.1598, F1: 0.4444

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62919 | val 0.81156
  Epoch 020 - train 0.49111 | val 0.97346
  Epoch 023 - train 0.52919 | val 1.27315
  Classification -> best τ=0.880 (val F1=0.3702)
  Directional -> Accuracy: 0.4493, MCC: -0.0867, F1: 0.0500

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58440 | val 1.60672
  Epoch 011 - train 0.56451 | val 1.70124
  Classification -> best τ=0.490 (val F1=0.0980)
  Directional -> Accuracy: 0.4310, MCC: -0.1979, F1: 0.5352

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64325 | val 0.91470
  Epoch 011 - train 0.61047 | val 1.14585
  Classification -> best τ=0.485 (val F1=0.1939)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61154 | val 1.47369
  Epoch 015 - train 0.57092 | val 0.78246
  Classification -> best τ=0.365 (val F1=0.3948)
  Directional -> Accuracy: 0.4531, MCC: 0.0191, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63432 | val 0.66270
  Epoch 020 - train 0.51525 | val 0.85510
  Classification -> best τ=0.385 (val F1=0.3758)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61985 | val 0.67818
  Epoch 020 - train 0.60671 | val 1.11262
  Epoch 025 - train 0.36084 | val 0.95088
  Classification -> best τ=0.485 (val F1=0.3678)
  Directional -> Accuracy: 0.5532, MCC: 0.1043, F1: 0.6038

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63298 | val 1.20788
  Epoch 012 - train 0.61497 | val 1.30425
  Classification -> best τ=0.635 (val F1=0.1512)
  Directional -> Accuracy: 0.5692, MCC: 0.2166, F1: 0.3333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62271 | val 0.73888
  Epoch 016 - train 0.59072 | val 1.02116
  Classification -> best τ=0.585 (val F1=0.3329)
  Directional -> Accuracy: 0.5439, MCC: 0.0906, F1: 0.5667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65964 | val 0.72353
  Epoch 012 - train 0.65604 | val 0.76615
  Classification -> best τ=0.505 (val F1=0.1348)
  Directional -> Accuracy: 0.5077, MCC: 0.0161, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58248 | val 0.78399
  Epoch 016 - train 0.56609 | val 0.90193
  Classification -> best τ=0.480 (val F1=0.4688)
  Directional -> Accuracy: 0.5455, MCC: 0.1257, F1: 0.4898

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56513 | val 1.52025
  Epoch 014 - train 0.50841 | val 1.64703
  Classification -> best τ=0.525 (val F1=0.2035)
  Directional -> Accuracy: 0.6667, MCC: 0.3002, F1: 0.5455

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65472 | val 0.69439
  Epoch 019 - train 0.60349 | val 0.72909
  Classification -> best τ=0.600 (val F1=0.2402)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63506 | val 0.70056
  Epoch 016 - train 0.58478 | val 0.80624
  Classification -> best τ=0.400 (val F1=0.2718)
  Directional -> Accuracy: 0.5357, MCC: 0.2812, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66027 | val 0.70584
  Epoch 016 - train 0.48726 | val 0.73173
  Classification -> best τ=0.425 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61427 | val 0.91880
  Epoch 012 - train 0.60444 | val 0.91692
  Classification -> best τ=0.580 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62867 | val 1.09360
  Epoch 011 - train 0.63854 | val 0.90370
  Classification -> best τ=0.500 (val F1=0.2646)
  Directional -> Accuracy: 0.4524, MCC: -0.0605, F1: 0.3429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60542 | val 0.74609
  Epoch 014 - train 0.51045 | val 1.03694
  Classification -> best τ=0.490 (val F1=0.2812)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62002 | val 0.74826
  Epoch 016 - train 0.59961 | val 0.69079
  Classification -> best τ=0.425 (val F1=0.2765)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59529 | val 0.93411
  Epoch 013 - train 0.49796 | val 1.22882
  Classification -> best τ=0.610 (val F1=0.4275)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60196 | val 0.78038
  Epoch 011 - train 0.60998 | val 0.80317
  Classification -> best τ=0.470 (val F1=0.4073)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48944 | val 1.77427
  Epoch 012 - train 0.47032 | val 3.40866
  Classification -> best τ=0.390 (val F1=0.3218)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54841 | val 0.85451
  Epoch 012 - train 0.57550 | val 0.99500
  Classification -> best τ=0.475 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47203 | val 1.05842
  Epoch 011 - train 0.48442 | val 1.11742
  Classification -> best τ=0.505 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: -0.0475, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59402 | val 0.63902
  Epoch 020 - train 0.43040 | val 0.93699
  Epoch 021 - train 0.37484 | val 1.05491
  Classification -> best τ=0.450 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64407 | val 0.68962
  Epoch 011 - train 0.59582 | val 0.76553
  Classification -> best τ=0.440 (val F1=0.3786)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59197 | val 0.75859
  Epoch 013 - train 0.54252 | val 0.89563
  Classification -> best τ=0.415 (val F1=0.3287)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.6441

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57711 | val 0.64815
  Epoch 016 - train 0.55242 | val 0.70622
  Classification -> best τ=0.570 (val F1=0.6210)
  Directional -> Accuracy: 0.5476, MCC: 0.0313, F1: 0.6545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65905 | val 0.73208
  Epoch 012 - train 0.60700 | val 0.68473
  Classification -> best τ=0.580 (val F1=0.5689)
  Directional -> Accuracy: 0.4583, MCC: -0.0222, F1: 0.4583

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56069 | val 0.73019
  Epoch 011 - train 0.60543 | val 0.77546
  Classification -> best τ=0.625 (val F1=0.1474)
  Directional -> Accuracy: 0.4364, MCC: -0.1144, F1: 0.4151

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50791 | val 2.65609
  Epoch 011 - train 0.57080 | val 1.74545
  Classification -> best τ=0.600 (val F1=0.3585)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60006 | val 1.09718
  Epoch 012 - train 0.59059 | val 1.11726
  Classification -> best τ=0.535 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1138, F1: 0.4286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57772 | val 0.86607
  Epoch 011 - train 0.63759 | val 0.79790
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60640 | val 0.68213
  Epoch 012 - train 0.58500 | val 0.68189

[I 2026-02-20 06:09:24,682] Trial 225 finished with value: 0.2976100906694158 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008780090913196181, 'weight_decay': 1.4366657505111032e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0602379945402964, 'early_stopping_min_delta': 0.0028085176855939566}. Best is trial 180 with value: 0.30107335520239253.

  Classification -> best τ=0.390 (val F1=0.2915)
  Directional -> Accuracy: 0.4833, MCC: -0.0089, F1: 0.6353

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2976100906694158
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58305 | val 0.80884
  Epoch 012 - train 0.58567 | val 0.70216
  Classification -> best τ=0.455 (val F1=0.1206)
  Directional -> Accuracy: 0.5789, MCC: 0.1225, F1: 0.2381

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57617 | val 0.68421
  Epoch 020 - train 0.45495 | val 0.69180
  Epoch 022 - train 0.45322 | val 0.76390
  Classification -> best τ=0.355 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63766 | val 0.70575
  Epoch 015 - train 0.60483 | val 0.84512
  Classification -> best τ=0.510 (val F1=0.3383)
  Directional -> Accuracy: 0.5652, MCC: 0.1241, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62727 | val 0.90617
  Epoch 012 - train 0.64529 | val 0.75078
  Classification -> best τ=0.585 (val F1=0.1776)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60948 | val 0.68806
  Epoch 013 - train 0.59613 | val 0.68578
  Classification -> best τ=0.485 (val F1=0.4787)
  Directional -> Accuracy: 0.7000, MCC: 0.4048, F1: 0.6939

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61833 | val 0.79890
  Epoch 012 - train 0.60902 | val 1.07113
  Classification -> best τ=0.495 (val F1=0.2204)
  Directional -> Accuracy: 0.5435, MCC: 0.0996, F1: 0.1600

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65109 | val 0.72496
  Epoch 016 - train 0.60510 | val 1.35053
  Classification -> best τ=0.525 (val F1=0.1923)
  Directional -> Accuracy: 0.6029, MCC: 0.1455, F1: 0.4490

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53758 | val 0.80490
  Epoch 012 - train 0.50968 | val 1.16088
  Classification -> best τ=0.405 (val F1=0.2075)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.1818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58112 | val 0.71118
  Epoch 012 - train 0.56961 | val 0.69827
  Classification -> best τ=0.445 (val F1=0.2764)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60826 | val 0.76053
  Epoch 011 - train 0.59363 | val 0.84506
  Classification -> best τ=0.545 (val F1=0.1128)
  Directional -> Accuracy: 0.5652, MCC: -0.0115, F1: 0.1176

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60606 | val 2.66481
  Epoch 014 - train 0.58633 | val 2.64256
  Classification -> best τ=0.365 (val F1=0.2883)
  Directional -> Accuracy: 0.5714, MCC: 0.1237, F1: 0.4878

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58738 | val 1.00267
  Epoch 012 - train 0.53756 | val 1.26288
  Classification -> best τ=0.510 (val F1=0.1083)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57078 | val 1.17446
  Epoch 012 - train 0.56075 | val 1.61867
  Classification -> best τ=0.405 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58179 | val 0.76387
  Epoch 013 - train 0.55815 | val 0.71396
  Classification -> best τ=0.435 (val F1=0.3774)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4828

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66070 | val 0.69976
  Epoch 014 - train 0.66501 | val 0.74909
  Classification -> best τ=0.485 (val F1=0.2667)
  Directional -> Accuracy: 0.4902, MCC: 0.1178, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58589 | val 1.24951
  Epoch 013 - train 0.56595 | val 1.45414
  Classification -> best τ=0.345 (val F1=0.2341)
  Directional -> Accuracy: 0.6087, MCC: 0.3006, F1: 0.7327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57983 | val 1.75941
  Epoch 011 - train 0.56226 | val 1.75612
  Classification -> best τ=0.535 (val F1=0.2211)
  Directional -> Accuracy: 0.5172, MCC: -0.0850, F1: 0.6410

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62234 | val 0.98570
  Epoch 012 - train 0.60237 | val 0.99627
  Classification -> best τ=0.580 (val F1=0.0428)
  Directional -> Accuracy: 0.4667, MCC: -0.1111, F1: 0.5556

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64475 | val 0.75163
  Epoch 012 - train 0.70649 | val 0.99946
  Classification -> best τ=0.630 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63134 | val 0.77296
  Epoch 016 - train 0.58727 | val 0.88777
  Classification -> best τ=0.395 (val F1=0.3362)
  Directional -> Accuracy: 0.4730, MCC: 0.1495, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55715 | val 0.90386
  Epoch 016 - train 0.50666 | val 0.93384
  Classification -> best τ=0.530 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64888 | val 0.94885
  Epoch 011 - train 0.61852 | val 1.03848
  Classification -> best τ=0.605 (val F1=0.2378)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60976 | val 0.71215
  Epoch 011 - train 0.59960 | val 0.70472
  Classification -> best τ=0.520 (val F1=0.3144)
  Directional -> Accuracy: 0.4386, MCC: -0.0773, F1: 0.3333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62297 | val 0.80505
  Epoch 012 - train 0.62365 | val 0.96885
  Classification -> best τ=0.515 (val F1=0.1565)
  Directional -> Accuracy: 0.5692, MCC: 0.1561, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62012 | val 0.64660
  Epoch 020 - train 0.49259 | val 0.88953
  Epoch 022 - train 0.42096 | val 0.73477
  Classification -> best τ=0.515 (val F1=0.5048)
  Directional -> Accuracy: 0.5273, MCC: 0.0598, F1: 0.5357

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59159 | val 0.91971
  Epoch 012 - train 0.60158 | val 1.08142
  Classification -> best τ=0.595 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59352 | val 0.72832
  Epoch 011 - train 0.61778 | val 0.72645
  Classification -> best τ=0.610 (val F1=0.1936)
  Directional -> Accuracy: 0.4048, MCC: -0.1407, F1: 0.2857

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61777 | val 0.73164
  Epoch 012 - train 0.62380 | val 0.79296
  Classification -> best τ=0.385 (val F1=0.2315)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62548 | val 0.93722
  Epoch 013 - train 0.54323 | val 1.27299
  Classification -> best τ=0.530 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0754, F1: 0.3333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62343 | val 0.96858
  Epoch 011 - train 0.61119 | val 0.91444
  Classification -> best τ=0.670 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57253 | val 0.82056
  Epoch 011 - train 0.55726 | val 1.10904
  Classification -> best τ=0.365 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55153 | val 0.70422
  Epoch 014 - train 0.46000 | val 0.96339
  Classification -> best τ=0.420 (val F1=0.3461)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58625 | val 0.68470
  Epoch 018 - train 0.53755 | val 1.14993
  Classification -> best τ=0.310 (val F1=0.3593)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64522 | val 0.83818
  Epoch 016 - train 0.61050 | val 0.93443
  Classification -> best τ=0.400 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61853 | val 0.82978
  Epoch 013 - train 0.66624 | val 0.80478
  Classification -> best τ=0.545 (val F1=0.1805)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54352 | val 0.87171
  Epoch 011 - train 0.49549 | val 1.19823
  Classification -> best τ=0.455 (val F1=0.1857)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53983 | val 1.10798
  Epoch 012 - train 0.52402 | val 1.01791
  Classification -> best τ=0.385 (val F1=0.2530)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53248 | val 0.96684
  Epoch 015 - train 0.51036 | val 1.06192
  Classification -> best τ=0.520 (val F1=0.2562)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61767 | val 0.69847
  Epoch 016 - train 0.53932 | val 0.69705
  Classification -> best τ=0.570 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59598 | val 0.82761
  Epoch 016 - train 0.52858 | val 0.93898
  Classification -> best τ=0.400 (val F1=0.2542)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55145 | val 0.78016
  Epoch 012 - train 0.52044 | val 0.85902
  Classification -> best τ=0.390 (val F1=0.2562)
  Directional -> Accuracy: 0.5778, MCC: 0.1545, F1: 0.5957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57321 | val 0.59943
  Epoch 020 - train 0.44306 | val 0.81784
  Epoch 030 - train 0.28611 | val 0.67957
  Epoch 033 - train 0.26297 | val 0.77655
  Classification -> best τ=0.370 (val F1=0.6210)
  Directional -> Accuracy: 0.6667, MCC: 0.3151, F1: 0.7586

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57764 | val 0.64865
  Epoch 020 - train 0.43347 | val 0.65925
  Epoch 030 - train 0.31006 | val 0.56052
  Epoch 036 - train 0.31464 | val 0.69516
  Classification -> best τ=0.445 (val F1=0.4795)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61441 | val 0.71697
  Epoch 013 - train 0.55801 | val 0.72477
  Classification -> best τ=0.585 (val F1=0.0413)
  Directional -> Accuracy: 0.6000, MCC: 0.2820, F1: 0.5000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58298 | val 1.75124
  Epoch 011 - train 0.59075 | val 1.50827
  Classification -> best τ=0.550 (val F1=0.2680)
  Directional -> Accuracy: 0.4821, MCC: -0.0266, F1: 0.5397

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59949 | val 0.75718
  Epoch 012 - train 0.64341 | val 0.75588
  Classification -> best τ=0.450 (val F1=0.1968)
  Directional -> Accuracy: 0.5283, MCC: 0.0863, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61979 | val 0.94057
  Epoch 013 - train 0.57311 | val 1.19826
  Classification -> best τ=0.550 (val F1=0.2625)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62900 | val 0.71240

[I 2026-02-20 06:10:19,950] Trial 226 finished with value: 0.26191941723946255 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007684495369031434, 'weight_decay': 1.0335380532398388e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0951077794264767, 'early_stopping_min_delta': 0.0029037131923030594}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.58392 | val 0.75534
  Classification -> best τ=0.465 (val F1=0.2623)
  Directional -> Accuracy: 0.4833, MCC: -0.1001, F1: 0.1143

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26191941723946255
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62316 | val 0.86266
  Epoch 011 - train 0.57076 | val 1.03976
  Classification -> best τ=0.415 (val F1=0.2200)
  Directional -> Accuracy: 0.4342, MCC: -0.0894, F1: 0.5981

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56631 | val 0.68029
  Epoch 016 - train 0.49086 | val 0.91373
  Classification -> best τ=0.465 (val F1=0.3779)
  Directional -> Accuracy: 0.6444, MCC: 0.2466, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60302 | val 0.67873
  Epoch 012 - train 0.60674 | val 0.74197
  Classification -> best τ=0.480 (val F1=0.3482)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64424 | val 0.73960
  Epoch 012 - train 0.65148 | val 0.77160
  Classification -> best τ=0.610 (val F1=0.1838)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61557 | val 0.65596
  Epoch 015 - train 0.53861 | val 1.20360
  Classification -> best τ=0.510 (val F1=0.4745)
  Directional -> Accuracy: 0.4600, MCC: -0.0699, F1: 0.3415

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60242 | val 0.69397
  Epoch 020 - train 0.52079 | val 0.87939
  Epoch 021 - train 0.51364 | val 0.85800
  Classification -> best τ=0.480 (val F1=0.3222)
  Directional -> Accuracy: 0.6087, MCC: 0.2241, F1: 0.4706

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67361 | val 0.76893
  Epoch 014 - train 0.62126 | val 0.96145
  Classification -> best τ=0.460 (val F1=0.2170)
  Directional -> Accuracy: 0.4412, MCC: -0.0305, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50375 | val 1.25215
  Epoch 012 - train 0.45669 | val 1.02613
  Classification -> best τ=0.455 (val F1=0.2263)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56676 | val 0.76721
  Epoch 020 - train 0.47133 | val 0.79985
  Epoch 025 - train 0.37261 | val 1.20964
  Classification -> best τ=0.720 (val F1=0.4022)
  Directional -> Accuracy: 0.5000, MCC: -0.1264, F1: 0.1429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58822 | val 0.97545
  Epoch 012 - train 0.52366 | val 1.01954
  Classification -> best τ=0.565 (val F1=0.2287)
  Directional -> Accuracy: 0.4348, MCC: -0.0912, F1: 0.4658

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62357 | val 0.93466
  Epoch 014 - train 0.60764 | val 1.24067
  Classification -> best τ=0.370 (val F1=0.2145)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52712 | val 1.02959
  Epoch 012 - train 0.56922 | val 1.07718
  Classification -> best τ=0.670 (val F1=0.1685)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59381 | val 0.99595
  Epoch 015 - train 0.54851 | val 1.47375
  Classification -> best τ=0.495 (val F1=0.3133)
  Directional -> Accuracy: 0.5476, MCC: 0.1513, F1: 0.6122

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59142 | val 0.68049
  Epoch 011 - train 0.59126 | val 0.66975
  Classification -> best τ=0.320 (val F1=0.2891)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57209 | val 0.71926
  Epoch 014 - train 0.56316 | val 0.83768
  Classification -> best τ=0.485 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59290 | val 0.84013
  Epoch 013 - train 0.56380 | val 0.89789
  Classification -> best τ=0.420 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60090 | val 1.23813
  Epoch 012 - train 0.56738 | val 1.35467
  Classification -> best τ=0.625 (val F1=0.1225)
  Directional -> Accuracy: 0.3793, MCC: -0.0470, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63966 | val 1.21345
  Epoch 012 - train 0.58970 | val 1.89306
  Classification -> best τ=0.610 (val F1=0.1002)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.5250

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64082 | val 1.58917
  Epoch 016 - train 0.57156 | val 1.95166
  Classification -> best τ=0.325 (val F1=0.3624)
  Directional -> Accuracy: 0.4531, MCC: -0.0852, F1: 0.4776

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64338 | val 0.69991
  Epoch 016 - train 0.58716 | val 0.79044
  Classification -> best τ=0.430 (val F1=0.3644)
  Directional -> Accuracy: 0.4595, MCC: 0.0249, F1: 0.1304

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56797 | val 1.68419
  Epoch 012 - train 0.59040 | val 1.87685
  Classification -> best τ=0.465 (val F1=0.2800)
  Directional -> Accuracy: 0.5319, MCC: 0.2722, F1: 0.4211

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64761 | val 1.04712
  Epoch 013 - train 0.58433 | val 0.83090
  Classification -> best τ=0.580 (val F1=0.1664)
  Directional -> Accuracy: 0.4308, MCC: -0.1393, F1: 0.3509

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61234 | val 0.75613
  Epoch 013 - train 0.58112 | val 0.82135
  Classification -> best τ=0.415 (val F1=0.3108)
  Directional -> Accuracy: 0.5614, MCC: 0.0639, F1: 0.6753

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67186 | val 0.77816
  Epoch 014 - train 0.58075 | val 0.79868
  Classification -> best τ=0.545 (val F1=0.0568)
  Directional -> Accuracy: 0.4769, MCC: -0.0924, F1: 0.2273

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60826 | val 0.87528
  Epoch 016 - train 0.51038 | val 1.03256
  Classification -> best τ=0.535 (val F1=0.5911)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54968 | val 1.39426
  Epoch 012 - train 0.52627 | val 2.05253
  Classification -> best τ=0.560 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60417 | val 0.78476
  Epoch 013 - train 0.56985 | val 0.74626
  Classification -> best τ=0.610 (val F1=0.2240)
  Directional -> Accuracy: 0.5476, MCC: -0.0534, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60646 | val 0.73865
  Epoch 013 - train 0.61037 | val 0.82157
  Classification -> best τ=0.455 (val F1=0.3116)
  Directional -> Accuracy: 0.5179, MCC: 0.1613, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58214 | val 0.78611
  Epoch 012 - train 0.60784 | val 0.85532
  Classification -> best τ=0.485 (val F1=0.4109)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58085 | val 1.00525
  Epoch 012 - train 0.52832 | val 1.24803
  Classification -> best τ=0.525 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62313 | val 0.85410
  Epoch 012 - train 0.56194 | val 0.77122
  Classification -> best τ=0.545 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58105 | val 0.80596
  Epoch 013 - train 0.53626 | val 0.84862
  Classification -> best τ=0.765 (val F1=0.2969)
  Directional -> Accuracy: 0.4286, MCC: -0.1419, F1: 0.4400

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63477 | val 0.63407
  Epoch 020 - train 0.57114 | val 1.00239
  Classification -> best τ=0.340 (val F1=0.4032)
  Directional -> Accuracy: 0.5278, MCC: 0.0988, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62484 | val 0.91735
  Epoch 012 - train 0.60734 | val 1.09748
  Classification -> best τ=0.460 (val F1=0.2717)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64731 | val 0.71123
  Epoch 014 - train 0.60618 | val 0.85982
  Classification -> best τ=0.595 (val F1=0.1822)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54058 | val 1.04050
  Epoch 011 - train 0.52669 | val 1.82072
  Classification -> best τ=0.665 (val F1=0.2292)
  Directional -> Accuracy: 0.5476, MCC: 0.1342, F1: 0.4242

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55930 | val 0.88873
  Epoch 012 - train 0.53260 | val 0.94063
  Classification -> best τ=0.385 (val F1=0.3217)
  Directional -> Accuracy: 0.4643, MCC: -0.0667, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52440 | val 1.04007
  Epoch 011 - train 0.49089 | val 1.21674
  Classification -> best τ=0.450 (val F1=0.4043)
  Directional -> Accuracy: 0.5435, MCC: -0.0318, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60504 | val 0.67689
  Epoch 019 - train 0.47964 | val 0.74461
  Classification -> best τ=0.475 (val F1=0.3006)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60404 | val 0.73695
  Epoch 016 - train 0.59916 | val 0.68832
  Classification -> best τ=0.580 (val F1=0.4381)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55261 | val 0.72536
  Epoch 013 - train 0.53178 | val 0.83889
  Classification -> best τ=0.540 (val F1=0.3371)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59627 | val 0.84053
  Epoch 015 - train 0.55285 | val 0.83699
  Classification -> best τ=0.520 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59171 | val 0.67253
  Epoch 011 - train 0.57892 | val 0.65089
  Classification -> best τ=0.595 (val F1=0.5689)
  Directional -> Accuracy: 0.5833, MCC: 0.2739, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58520 | val 0.98359
  Epoch 015 - train 0.53790 | val 1.12910
  Classification -> best τ=0.465 (val F1=0.3225)
  Directional -> Accuracy: 0.2909, MCC: -0.4105, F1: 0.2642

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55910 | val 1.66994
  Epoch 011 - train 0.54778 | val 2.04843
  Classification -> best τ=0.525 (val F1=0.0460)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63751 | val 0.83803
  Epoch 015 - train 0.57738 | val 0.86489
  Classification -> best τ=0.445 (val F1=0.1824)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60876 | val 0.96077
  Epoch 013 - train 0.58217 | val 0.89896
  Classification -> best τ=0.495 (val F1=0.2374)
  Directional -> Accuracy: 0.4909, MCC: 0.0251, F1: 0.2632

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60856 | val 0.67997
  Epoch 020 - train 0.52494 | val 0.70003

[I 2026-02-20 06:11:18,429] Trial 227 finished with value: 0.28820100638359347 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00966542967234139, 'weight_decay': 1.447063064556364e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0719037298236347, 'early_stopping_min_delta': 0.0025019026527626706}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 023 - train 0.56560 | val 0.74070
  Classification -> best τ=0.440 (val F1=0.2896)
  Directional -> Accuracy: 0.5833, MCC: 0.2536, F1: 0.6835

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28820100638359347
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58558 | val 0.74981
  Epoch 012 - train 0.56274 | val 0.76921
  Classification -> best τ=0.515 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55387 | val 0.67750
  Epoch 013 - train 0.51920 | val 0.72258
  Classification -> best τ=0.430 (val F1=0.3006)
  Directional -> Accuracy: 0.6000, MCC: 0.2388, F1: 0.5909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58461 | val 0.70488
  Epoch 016 - train 0.54500 | val 1.10642
  Classification -> best τ=0.510 (val F1=0.2559)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64321 | val 0.72029
  Epoch 013 - train 0.61194 | val 0.74871
  Classification -> best τ=0.565 (val F1=0.1808)
  Directional -> Accuracy: 0.5676, MCC: 0.1334, F1: 0.5897

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56120 | val 1.18688
  Epoch 015 - train 0.54852 | val 1.31178
  Classification -> best τ=0.520 (val F1=0.4751)
  Directional -> Accuracy: 0.6800, MCC: 0.3870, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59823 | val 0.76354
  Epoch 011 - train 0.56940 | val 0.76517
  Classification -> best τ=0.495 (val F1=0.2593)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66447 | val 0.69513
  Epoch 012 - train 0.67033 | val 0.76994
  Classification -> best τ=0.535 (val F1=0.2827)
  Directional -> Accuracy: 0.5000, MCC: 0.0443, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56493 | val 0.64757
  Epoch 013 - train 0.48680 | val 0.68749
  Classification -> best τ=0.300 (val F1=0.1650)
  Directional -> Accuracy: 0.5000, MCC: -0.2402, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56445 | val 0.69760
  Epoch 020 - train 0.44937 | val 0.95166
  Epoch 021 - train 0.43212 | val 1.22200
  Classification -> best τ=0.640 (val F1=0.4564)
  Directional -> Accuracy: 0.5833, MCC: 0.1240, F1: 0.4118

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56655 | val 1.09714
  Epoch 013 - train 0.58222 | val 1.26548
  Classification -> best τ=0.600 (val F1=0.1607)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67809 | val 0.69646
  Epoch 016 - train 0.56286 | val 2.56074
  Classification -> best τ=0.345 (val F1=0.2564)
  Directional -> Accuracy: 0.5510, MCC: 0.1407, F1: 0.5926

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54574 | val 1.17301
  Epoch 015 - train 0.55081 | val 1.79485
  Classification -> best τ=0.355 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57530 | val 1.36639
  Epoch 012 - train 0.55827 | val 1.27696
  Classification -> best τ=0.420 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64845 | val 0.61989
  Epoch 017 - train 0.60337 | val 0.65663
  Classification -> best τ=0.405 (val F1=0.3916)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5714

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56360 | val 1.19851
  Epoch 011 - train 0.54051 | val 1.33055
  Classification -> best τ=0.590 (val F1=0.3333)
  Directional -> Accuracy: 0.4510, MCC: -0.0791, F1: 0.4815

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58793 | val 0.72600
  Epoch 013 - train 0.57971 | val 1.16358
  Classification -> best τ=0.450 (val F1=0.5554)
  Directional -> Accuracy: 0.6087, MCC: 0.2144, F1: 0.7033

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58199 | val 1.39088
  Epoch 012 - train 0.56630 | val 1.37043
  Classification -> best τ=0.465 (val F1=0.2485)
  Directional -> Accuracy: 0.5690, MCC: -0.0715, F1: 0.7126

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59739 | val 0.93107
  Epoch 016 - train 0.67458 | val 0.77435
  Classification -> best τ=0.390 (val F1=0.1834)
  Directional -> Accuracy: 0.5600, MCC: 0.0884, F1: 0.6292

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55516 | val 0.74262
  Epoch 014 - train 0.60326 | val 0.89028
  Classification -> best τ=0.375 (val F1=0.3948)
  Directional -> Accuracy: 0.5469, MCC: 0.0384, F1: 0.6420

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59723 | val 0.73983
  Epoch 014 - train 0.56388 | val 0.85911
  Classification -> best τ=0.415 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60566 | val 0.66954
  Epoch 020 - train 0.46353 | val 1.27875
  Epoch 021 - train 0.46782 | val 1.65893
  Classification -> best τ=0.485 (val F1=0.3262)
  Directional -> Accuracy: 0.4681, MCC: 0.2403, F1: 0.2424

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62405 | val 1.01774
  Epoch 012 - train 0.63828 | val 1.33315
  Classification -> best τ=0.680 (val F1=0.1960)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62433 | val 0.78107
  Epoch 015 - train 0.62951 | val 0.90379
  Classification -> best τ=0.650 (val F1=0.3550)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61932 | val 0.85921
  Epoch 011 - train 0.62845 | val 0.81777
  Classification -> best τ=0.560 (val F1=0.1122)
  Directional -> Accuracy: 0.4615, MCC: -0.0664, F1: 0.5205

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61701 | val 0.75796
  Epoch 016 - train 0.51865 | val 0.83740
  Classification -> best τ=0.525 (val F1=0.3227)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52675 | val 1.21288
  Epoch 012 - train 0.52624 | val 1.27266
  Classification -> best τ=0.515 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59466 | val 0.71769
  Epoch 012 - train 0.61011 | val 0.72671
  Classification -> best τ=0.580 (val F1=0.1803)
  Directional -> Accuracy: 0.4762, MCC: -0.0849, F1: 0.5600

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63592 | val 0.74317
  Epoch 011 - train 0.63602 | val 0.78736
  Classification -> best τ=0.390 (val F1=0.2354)
  Directional -> Accuracy: 0.5357, MCC: 0.2812, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62801 | val 0.81694
  Epoch 011 - train 0.61496 | val 1.05164
  Classification -> best τ=0.485 (val F1=0.4719)
  Directional -> Accuracy: 0.5750, MCC: 0.1297, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58238 | val 1.03483
  Epoch 012 - train 0.52517 | val 1.23977
  Classification -> best τ=0.390 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0853, F1: 0.6154

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60985 | val 1.18328
  Epoch 012 - train 0.54605 | val 0.75419
  Classification -> best τ=0.530 (val F1=0.2042)
  Directional -> Accuracy: 0.4524, MCC: -0.1711, F1: 0.5818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55611 | val 0.74209
  Epoch 015 - train 0.47144 | val 1.10676
  Classification -> best τ=0.385 (val F1=0.2918)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62974 | val 0.69224
  Epoch 017 - train 0.57579 | val 0.92001
  Classification -> best τ=0.375 (val F1=0.4246)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59165 | val 1.35947
  Epoch 011 - train 0.57612 | val 1.46571
  Classification -> best τ=0.360 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60699 | val 0.86695
  Epoch 014 - train 0.66533 | val 1.02091
  Classification -> best τ=0.240 (val F1=0.3342)
  Directional -> Accuracy: 0.6061, MCC: 0.2665, F1: 0.5806

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57459 | val 0.79725
  Epoch 014 - train 0.52984 | val 1.12436
  Classification -> best τ=0.485 (val F1=0.2144)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53805 | val 0.95014
  Epoch 012 - train 0.58324 | val 0.89976
  Classification -> best τ=0.405 (val F1=0.2804)
  Directional -> Accuracy: 0.5357, MCC: 0.1040, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57890 | val 1.09882
  Epoch 013 - train 0.52718 | val 1.06115
  Classification -> best τ=0.460 (val F1=0.4335)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61236 | val 0.73054
  Epoch 012 - train 0.57251 | val 0.76584
  Classification -> best τ=0.450 (val F1=0.2943)
  Directional -> Accuracy: 0.3750, MCC: -0.0327, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60442 | val 0.89486
  Epoch 011 - train 0.61818 | val 0.94614
  Classification -> best τ=0.390 (val F1=0.3322)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55524 | val 0.76537
  Epoch 012 - train 0.59222 | val 0.81886
  Classification -> best τ=0.465 (val F1=0.2874)
  Directional -> Accuracy: 0.5333, MCC: 0.0696, F1: 0.5116

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61328 | val 0.64666
  Epoch 020 - train 0.49785 | val 0.62061
  Epoch 030 - train 0.40681 | val 0.64229
  Epoch 038 - train 0.27448 | val 0.62926
  Classification -> best τ=0.255 (val F1=0.7566)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60767 | val 0.66753
  Epoch 020 - train 0.42146 | val 0.58249
  Epoch 030 - train 0.41106 | val 0.64040
  Epoch 035 - train 0.20708 | val 0.69722
  Classification -> best τ=0.435 (val F1=0.6110)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59086 | val 0.70219
  Epoch 015 - train 0.54880 | val 0.76753
  Classification -> best τ=0.565 (val F1=0.1260)
  Directional -> Accuracy: 0.4182, MCC: -0.1415, F1: 0.3333

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52625 | val 1.08099
  Epoch 011 - train 0.56057 | val 1.17282
  Classification -> best τ=0.505 (val F1=0.3088)
  Directional -> Accuracy: 0.5179, MCC: 0.0099, F1: 0.1290

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63683 | val 0.73623
  Epoch 017 - train 0.63075 | val 0.94756
  Classification -> best τ=0.485 (val F1=0.2788)
  Directional -> Accuracy: 0.5472, MCC: 0.2018, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63695 | val 0.71901
  Epoch 011 - train 0.66604 | val 0.70887
  Classification -> best τ=0.340 (val F1=0.0413)
  Directional -> Accuracy: 0.4909, MCC: -0.0687, F1: 0.6216

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58834 | val 0.78238
  Epoch 020 - train 0.56474 | val 0.90021

[I 2026-02-20 06:12:19,641] Trial 228 finished with value: 0.3005725087221459 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009785974715656811, 'weight_decay': 1.4941311383117348e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0055681609935274, 'early_stopping_min_delta': 0.00275586879419709}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 025 - train 0.51213 | val 1.05373
  Classification -> best τ=0.485 (val F1=0.2623)
  Directional -> Accuracy: 0.5333, MCC: 0.0589, F1: 0.3000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.3005725087221459
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59385 | val 0.85922
  Epoch 016 - train 0.56671 | val 0.71615
  Classification -> best τ=0.605 (val F1=0.2510)
  Directional -> Accuracy: 0.6184, MCC: 0.2410, F1: 0.6027

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58610 | val 0.69510
  Epoch 013 - train 0.53724 | val 0.74969
  Classification -> best τ=0.420 (val F1=0.2021)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58773 | val 0.73489
  Epoch 015 - train 0.52837 | val 0.83000
  Classification -> best τ=0.460 (val F1=0.3114)
  Directional -> Accuracy: 0.5217, MCC: 0.0826, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66063 | val 0.74482
  Epoch 014 - train 0.61400 | val 0.82169
  Classification -> best τ=0.485 (val F1=0.1725)
  Directional -> Accuracy: 0.5135, MCC: 0.0076, F1: 0.5814

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56974 | val 0.83728
  Epoch 013 - train 0.52033 | val 1.00861
  Classification -> best τ=0.495 (val F1=0.4414)
  Directional -> Accuracy: 0.6800, MCC: 0.4016, F1: 0.6190

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56737 | val 0.76926
  Epoch 013 - train 0.54874 | val 0.79804
  Classification -> best τ=0.595 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62092 | val 0.77692
  Epoch 012 - train 0.62730 | val 0.94976
  Classification -> best τ=0.460 (val F1=0.2789)
  Directional -> Accuracy: 0.5147, MCC: 0.1280, F1: 0.5600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57572 | val 0.92156
  Epoch 011 - train 0.54379 | val 1.01232
  Classification -> best τ=0.370 (val F1=0.1657)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58776 | val 0.67825
  Epoch 015 - train 0.50851 | val 0.82367
  Classification -> best τ=0.560 (val F1=0.2988)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59734 | val 0.79293
  Epoch 012 - train 0.58366 | val 0.86784
  Classification -> best τ=0.450 (val F1=0.1424)
  Directional -> Accuracy: 0.5217, MCC: 0.0417, F1: 0.4762

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59946 | val 0.74166
  Epoch 014 - train 0.61055 | val 0.84541
  Classification -> best τ=0.375 (val F1=0.2169)
  Directional -> Accuracy: 0.5510, MCC: 0.0714, F1: 0.4211

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56978 | val 1.10627
  Epoch 015 - train 0.47078 | val 2.45069
  Classification -> best τ=0.470 (val F1=0.2162)
  Directional -> Accuracy: 0.5088, MCC: 0.0048, F1: 0.6585

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61723 | val 1.06437
  Epoch 012 - train 0.57900 | val 0.93781
  Classification -> best τ=0.360 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64492 | val 0.62296
  Epoch 019 - train 0.62565 | val 0.63187
  Classification -> best τ=0.375 (val F1=0.3407)
  Directional -> Accuracy: 0.5667, MCC: 0.1383, F1: 0.6176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59994 | val 0.78306
  Epoch 015 - train 0.56371 | val 0.84644
  Classification -> best τ=0.440 (val F1=0.2429)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61013 | val 0.95378
  Epoch 012 - train 0.65155 | val 0.86954
  Classification -> best τ=0.615 (val F1=0.3307)
  Directional -> Accuracy: 0.5072, MCC: 0.0765, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64656 | val 1.00079
  Epoch 011 - train 0.63239 | val 0.98212
  Classification -> best τ=0.525 (val F1=0.2135)
  Directional -> Accuracy: 0.4310, MCC: -0.2994, F1: 0.5823

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62401 | val 1.11016
  Epoch 013 - train 0.59779 | val 1.02219
  Classification -> best τ=0.610 (val F1=0.2082)
  Directional -> Accuracy: 0.5333, MCC: 0.1674, F1: 0.4776

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64423 | val 0.92175
  Epoch 014 - train 0.57706 | val 1.03380
  Classification -> best τ=0.675 (val F1=0.2868)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63495 | val 0.66029
  Epoch 020 - train 0.63126 | val 0.75517
  Classification -> best τ=0.395 (val F1=0.2882)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60963 | val 0.68674
  Epoch 017 - train 0.53340 | val 0.72475
  Classification -> best τ=0.485 (val F1=0.2779)
  Directional -> Accuracy: 0.4468, MCC: 0.0837, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64454 | val 1.03762
  Epoch 013 - train 0.62020 | val 1.14704
  Classification -> best τ=0.465 (val F1=0.1886)
  Directional -> Accuracy: 0.5231, MCC: 0.0442, F1: 0.6173

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56514 | val 0.75250
  Epoch 017 - train 0.52194 | val 0.95993
  Classification -> best τ=0.655 (val F1=0.2644)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65019 | val 0.84370
  Epoch 012 - train 0.64239 | val 0.87199
  Classification -> best τ=0.480 (val F1=0.1348)
  Directional -> Accuracy: 0.5385, MCC: 0.0777, F1: 0.5312

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60721 | val 0.70209
  Epoch 015 - train 0.53576 | val 0.81097
  Classification -> best τ=0.465 (val F1=0.5489)
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57808 | val 0.96637
  Epoch 013 - train 0.51519 | val 0.98028
  Classification -> best τ=0.570 (val F1=0.2241)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61754 | val 0.69571
  Epoch 015 - train 0.55346 | val 0.70583
  Classification -> best τ=0.595 (val F1=0.2161)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62778 | val 0.84991
  Epoch 014 - train 0.57309 | val 0.97007
  Classification -> best τ=0.415 (val F1=0.2892)
  Directional -> Accuracy: 0.5536, MCC: 0.1158, F1: 0.5614

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59763 | val 0.84329
  Epoch 011 - train 0.57978 | val 0.79551
  Classification -> best τ=0.525 (val F1=0.4181)
  Directional -> Accuracy: 0.5500, MCC: 0.0580, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61743 | val 0.78093
  Epoch 012 - train 0.57534 | val 1.29125
  Classification -> best τ=0.580 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1228, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59610 | val 0.74704
  Epoch 012 - train 0.54708 | val 1.41510
  Classification -> best τ=0.490 (val F1=0.1124)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57701 | val 0.84125
  Epoch 013 - train 0.53083 | val 0.94621
  Classification -> best τ=0.405 (val F1=0.4120)
  Directional -> Accuracy: 0.4898, MCC: -0.0118, F1: 0.4681

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61054 | val 0.80776
  Epoch 013 - train 0.60128 | val 0.74480
  Classification -> best τ=0.505 (val F1=0.3861)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61617 | val 1.02280
  Epoch 011 - train 0.55290 | val 1.10749
  Classification -> best τ=0.495 (val F1=0.0473)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66471 | val 0.79469
  Epoch 011 - train 0.63578 | val 0.91926
  Classification -> best τ=0.430 (val F1=0.3254)
  Directional -> Accuracy: 0.5606, MCC: 0.0162, F1: 0.6947

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54708 | val 0.81750
  Epoch 013 - train 0.45216 | val 0.95074
  Classification -> best τ=0.490 (val F1=0.2228)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54408 | val 0.73640
  Epoch 013 - train 0.50351 | val 0.73465
  Classification -> best τ=0.455 (val F1=0.2287)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51940 | val 1.16138
  Epoch 011 - train 0.48851 | val 1.34512
  Classification -> best τ=0.485 (val F1=0.2441)
  Directional -> Accuracy: 0.5870, MCC: 0.0903, F1: 0.6885

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58096 | val 0.70747
  Epoch 016 - train 0.53741 | val 0.71765
  Classification -> best τ=0.520 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61778 | val 0.65943
  Epoch 020 - train 0.53341 | val 0.84099
  Classification -> best τ=0.370 (val F1=0.3075)
  Directional -> Accuracy: 0.4865, MCC: -0.0045, F1: 0.6481

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54800 | val 0.73589
  Epoch 011 - train 0.57062 | val 0.74715
  Classification -> best τ=0.420 (val F1=0.4080)
  Directional -> Accuracy: 0.4889, MCC: -0.0103, F1: 0.2581

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56608 | val 0.61917
  Epoch 019 - train 0.49108 | val 0.76946
  Classification -> best τ=0.620 (val F1=0.6124)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58872 | val 0.55229
  Epoch 020 - train 0.44557 | val 0.81606
  Classification -> best τ=0.580 (val F1=0.5249)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62047 | val 0.72148
  Epoch 012 - train 0.61533 | val 0.77691
  Classification -> best τ=0.585 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54539 | val 2.18021
  Epoch 012 - train 0.53365 | val 2.39539
  Classification -> best τ=0.545 (val F1=0.1974)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62772 | val 1.20958
  Epoch 012 - train 0.59079 | val 1.39867
  Classification -> best τ=0.505 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2139, F1: 0.5714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63105 | val 0.72604
  Epoch 011 - train 0.64930 | val 0.74920
  Classification -> best τ=0.445 (val F1=0.0080)
  Directional -> Accuracy: 0.4545, MCC: -0.2145, F1: 0.6154

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57950 | val 0.76779

[I 2026-02-20 06:13:20,461] Trial 229 finished with value: 0.2734880673138294 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007226210360013555, 'weight_decay': 1.4354347230949668e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0024355504092581, 'early_stopping_min_delta': 0.002943678975312245}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.58848 | val 0.77568
  Classification -> best τ=0.435 (val F1=0.2045)
  Directional -> Accuracy: 0.4167, MCC: -0.1965, F1: 0.2553

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2734880673138294
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55970 | val 0.80540
  Epoch 014 - train 0.56366 | val 0.67012
  Classification -> best τ=0.455 (val F1=0.2412)
  Directional -> Accuracy: 0.5395, MCC: 0.1802, F1: 0.6316

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59462 | val 0.67266
  Epoch 018 - train 0.43418 | val 0.68749
  Classification -> best τ=0.450 (val F1=0.3779)
  Directional -> Accuracy: 0.6444, MCC: 0.2619, F1: 0.7037

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59609 | val 0.74237
  Epoch 017 - train 0.55018 | val 1.06601
  Classification -> best τ=0.695 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65898 | val 0.81198
  Epoch 012 - train 0.63719 | val 0.84663
  Classification -> best τ=0.445 (val F1=0.2056)
  Directional -> Accuracy: 0.5270, MCC: 0.0634, F1: 0.5205

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61343 | val 0.76521
  Epoch 016 - train 0.55890 | val 1.77593
  Classification -> best τ=0.640 (val F1=0.3612)
  Directional -> Accuracy: 0.5000, MCC: 0.1373, F1: 0.0741

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63869 | val 0.81081
  Epoch 013 - train 0.61472 | val 1.11025
  Classification -> best τ=0.585 (val F1=0.1463)
  Directional -> Accuracy: 0.4565, MCC: -0.0784, F1: 0.5098

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63647 | val 0.70333
  Epoch 015 - train 0.58668 | val 1.16932
  Classification -> best τ=0.410 (val F1=0.2519)
  Directional -> Accuracy: 0.5000, MCC: 0.1932, F1: 0.5952

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55698 | val 0.82696
  Epoch 013 - train 0.52669 | val 0.70386
  Classification -> best τ=0.315 (val F1=0.1657)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59055 | val 0.99123
  Epoch 012 - train 0.52600 | val 0.84308
  Classification -> best τ=0.550 (val F1=0.4197)
  Directional -> Accuracy: 0.6042, MCC: 0.2494, F1: 0.6275

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58526 | val 0.75275
  Epoch 011 - train 0.62497 | val 0.84872
  Classification -> best τ=0.455 (val F1=0.0964)
  Directional -> Accuracy: 0.5072, MCC: -0.0112, F1: 0.4138

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64751 | val 0.75545
  Epoch 012 - train 0.59021 | val 0.85661
  Classification -> best τ=0.385 (val F1=0.3543)
  Directional -> Accuracy: 0.5102, MCC: 0.0184, F1: 0.4783

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53356 | val 1.52454
  Epoch 012 - train 0.49494 | val 1.29588
  Classification -> best τ=0.575 (val F1=0.0509)
  Directional -> Accuracy: 0.4912, MCC: -0.0269, F1: 0.5797

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55878 | val 1.44915
  Epoch 012 - train 0.56410 | val 1.54388
  Classification -> best τ=0.505 (val F1=0.1878)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59606 | val 0.64742
  Epoch 013 - train 0.59451 | val 0.72300
  Classification -> best τ=0.385 (val F1=0.3407)
  Directional -> Accuracy: 0.4500, MCC: -0.1809, F1: 0.6118

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58605 | val 0.75621
  Epoch 014 - train 0.62350 | val 0.94384
  Classification -> best τ=0.520 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60677 | val 1.13658
  Epoch 013 - train 0.52592 | val 1.48111
  Classification -> best τ=0.595 (val F1=0.2738)
  Directional -> Accuracy: 0.5072, MCC: 0.0220, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60340 | val 1.07905
  Epoch 011 - train 0.61521 | val 1.21869
  Classification -> best τ=0.420 (val F1=0.0543)
  Directional -> Accuracy: 0.5862, MCC: 0.0195, F1: 0.7143

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59280 | val 1.39380
  Epoch 012 - train 0.60512 | val 1.27334
  Classification -> best τ=0.480 (val F1=0.2253)
  Directional -> Accuracy: 0.5333, MCC: 0.1373, F1: 0.5070

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62136 | val 1.25916
  Epoch 015 - train 0.56013 | val 1.61036
  Classification -> best τ=0.330 (val F1=0.2522)
  Directional -> Accuracy: 0.4531, MCC: 0.0359, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59950 | val 0.78854
  Epoch 013 - train 0.57674 | val 0.81499
  Classification -> best τ=0.440 (val F1=0.3430)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59424 | val 0.67889
  Epoch 020 - train 0.47807 | val 0.71855
  Epoch 028 - train 0.39585 | val 1.20246
  Classification -> best τ=0.610 (val F1=0.4142)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62837 | val 1.13187
  Epoch 011 - train 0.63493 | val 1.22234
  Classification -> best τ=0.425 (val F1=0.1650)
  Directional -> Accuracy: 0.4615, MCC: -0.1688, F1: 0.6237

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60957 | val 0.70669
  Epoch 011 - train 0.60470 | val 0.80359
  Classification -> best τ=0.480 (val F1=0.2583)
  Directional -> Accuracy: 0.4912, MCC: -0.1536, F1: 0.6420

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64421 | val 0.90027
  Epoch 011 - train 0.64271 | val 0.88187
  Classification -> best τ=0.490 (val F1=0.2096)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57529 | val 1.12488
  Epoch 018 - train 0.44751 | val 1.38165
  Classification -> best τ=0.430 (val F1=0.5757)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53369 | val 1.03481
  Epoch 011 - train 0.56620 | val 1.05084
  Classification -> best τ=0.445 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62138 | val 0.70123
  Epoch 012 - train 0.57788 | val 0.73088
  Classification -> best τ=0.560 (val F1=0.0595)
  Directional -> Accuracy: 0.5476, MCC: 0.1260, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61016 | val 0.78707
  Epoch 015 - train 0.57739 | val 0.85750
  Classification -> best τ=0.385 (val F1=0.2945)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63330 | val 0.80243
  Epoch 017 - train 0.52857 | val 1.91830
  Classification -> best τ=0.550 (val F1=0.2957)
  Directional -> Accuracy: 0.6750, MCC: 0.3572, F1: 0.6829

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62671 | val 1.17913
  Epoch 013 - train 0.59066 | val 0.94485
  Classification -> best τ=0.570 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64529 | val 1.11448
  Epoch 011 - train 0.59989 | val 0.83701
  Classification -> best τ=0.630 (val F1=0.1286)
  Directional -> Accuracy: 0.4048, MCC: -0.1940, F1: 0.0741

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62812 | val 0.66903
  Epoch 019 - train 0.49544 | val 0.92050
  Classification -> best τ=0.325 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62337 | val 0.67575
  Epoch 015 - train 0.60916 | val 0.89153
  Classification -> best τ=0.415 (val F1=0.4032)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64940 | val 0.97726
  Epoch 017 - train 0.60794 | val 1.04827
  Classification -> best τ=0.405 (val F1=0.2324)
  Directional -> Accuracy: 0.5814, MCC: 0.1824, F1: 0.6400

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63955 | val 0.77154
  Epoch 011 - train 0.64901 | val 0.80567
  Classification -> best τ=0.610 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60270 | val 1.83041
  Epoch 016 - train 0.44023 | val 1.43590
  Classification -> best τ=0.530 (val F1=0.1586)
  Directional -> Accuracy: 0.5476, MCC: 0.1494, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57700 | val 0.97168
  Epoch 011 - train 0.56575 | val 1.13389
  Classification -> best τ=0.405 (val F1=0.2946)
  Directional -> Accuracy: 0.5357, MCC: 0.1754, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56568 | val 1.18078
  Epoch 013 - train 0.49726 | val 1.15749
  Classification -> best τ=0.570 (val F1=0.3383)
  Directional -> Accuracy: 0.4565, MCC: -0.0700, F1: 0.4898

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54105 | val 0.63635
  Epoch 019 - train 0.35794 | val 0.80086
  Classification -> best τ=0.595 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62098 | val 0.74949
  Epoch 011 - train 0.57589 | val 0.70213
  Classification -> best τ=0.390 (val F1=0.2479)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53676 | val 0.76810
  Epoch 012 - train 0.54882 | val 0.86776
  Classification -> best τ=0.430 (val F1=0.2874)
  Directional -> Accuracy: 0.4667, MCC: -0.0786, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57928 | val 0.63998
  Epoch 020 - train 0.40424 | val 2.08870
  Classification -> best τ=0.350 (val F1=0.4082)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62363 | val 0.70356
  Epoch 016 - train 0.52754 | val 0.69263
  Classification -> best τ=0.605 (val F1=0.6292)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58826 | val 0.73913
  Epoch 016 - train 0.55637 | val 0.73739
  Classification -> best τ=0.510 (val F1=0.0876)
  Directional -> Accuracy: 0.4545, MCC: -0.1077, F1: 0.5161

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60855 | val 1.33814
  Epoch 011 - train 0.61687 | val 1.30787
  Classification -> best τ=0.550 (val F1=0.3104)
  Directional -> Accuracy: 0.5000, MCC: 0.0709, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66611 | val 0.66115
  Epoch 020 - train 0.51820 | val 0.77434
  Classification -> best τ=0.560 (val F1=0.3671)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65399 | val 0.80524
  Epoch 014 - train 0.58255 | val 0.90804
  Classification -> best τ=0.580 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62132 | val 0.67411

[I 2026-02-20 06:14:20,564] Trial 230 finished with value: 0.27406307140308545 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008160186851594023, 'weight_decay': 1.2499945746704334e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1371453564798064, 'early_stopping_min_delta': 0.002592053751374499}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 020 - train 0.55207 | val 1.04465
  Epoch 021 - train 0.52619 | val 0.80136
  Classification -> best τ=0.415 (val F1=0.2789)
  Directional -> Accuracy: 0.5500, MCC: 0.1831, F1: 0.6667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27406307140308545
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64102 | val 0.65891
  Epoch 020 - train 0.53627 | val 0.94976
  Classification -> best τ=0.460 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: 0.0559, F1: 0.4444

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67507 | val 0.68181
  Epoch 020 - train 0.46085 | val 0.69818
  Epoch 029 - train 0.37101 | val 0.79491
  Classification -> best τ=0.465 (val F1=0.2545)
  Directional -> Accuracy: 0.5778, MCC: 0.2769, F1: 0.4865

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62909 | val 0.72502
  Epoch 013 - train 0.56739 | val 1.07781
  Classification -> best τ=0.520 (val F1=0.0019)
  Directional -> Accuracy: 0.4783, MCC: -0.0455, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65412 | val 0.78944
  Epoch 012 - train 0.64305 | val 0.73182
  Classification -> best τ=0.510 (val F1=0.0112)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61003 | val 0.87528
  Epoch 016 - train 0.50234 | val 1.35895
  Classification -> best τ=0.550 (val F1=0.4930)
  Directional -> Accuracy: 0.4800, MCC: -0.0175, F1: 0.2353

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60012 | val 0.99033
  Epoch 011 - train 0.60432 | val 0.99670
  Classification -> best τ=0.510 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62926 | val 0.80308
  Epoch 013 - train 0.61079 | val 1.06570
  Classification -> best τ=0.525 (val F1=0.2361)
  Directional -> Accuracy: 0.5294, MCC: 0.0663, F1: 0.4839

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51930 | val 0.62831
  Epoch 012 - train 0.47965 | val 0.79293
  Classification -> best τ=0.295 (val F1=0.1147)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.3784

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55409 | val 0.78622
  Epoch 012 - train 0.54063 | val 0.74901
  Classification -> best τ=0.470 (val F1=0.3433)
  Directional -> Accuracy: 0.6042, MCC: 0.1782, F1: 0.4865

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57630 | val 0.87984
  Epoch 011 - train 0.57779 | val 0.98546
  Classification -> best τ=0.510 (val F1=0.0263)
  Directional -> Accuracy: 0.4928, MCC: -0.0170, F1: 0.4444

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65150 | val 0.96824
  Epoch 014 - train 0.65372 | val 0.76411
  Classification -> best τ=0.480 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58960 | val 1.21382
  Epoch 015 - train 0.43216 | val 1.91834
  Classification -> best τ=0.460 (val F1=0.2777)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55622 | val 1.41125
  Epoch 011 - train 0.50338 | val 1.83663
  Classification -> best τ=0.490 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64281 | val 0.78420
  Epoch 011 - train 0.59582 | val 0.69643
  Classification -> best τ=0.490 (val F1=0.3387)
  Directional -> Accuracy: 0.5833, MCC: 0.1714, F1: 0.5283

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59194 | val 0.76223
  Epoch 011 - train 0.57913 | val 0.72354
  Classification -> best τ=0.565 (val F1=0.3333)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57837 | val 1.66379
  Epoch 013 - train 0.60297 | val 1.54118
  Classification -> best τ=0.545 (val F1=0.2197)
  Directional -> Accuracy: 0.4928, MCC: -0.0265, F1: 0.5455

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58391 | val 0.98116
  Epoch 014 - train 0.57163 | val 1.46111
  Classification -> best τ=0.660 (val F1=0.1842)
  Directional -> Accuracy: 0.4655, MCC: 0.1387, F1: 0.3111

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61619 | val 1.49631
  Epoch 012 - train 0.62614 | val 1.38071
  Classification -> best τ=0.465 (val F1=0.2216)
  Directional -> Accuracy: 0.5467, MCC: 0.1588, F1: 0.5278

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61619 | val 0.94452
  Epoch 011 - train 0.62453 | val 1.09094
  Classification -> best τ=0.545 (val F1=0.2638)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63182 | val 0.70126
  Epoch 018 - train 0.55670 | val 0.84935
  Classification -> best τ=0.460 (val F1=0.3495)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66312 | val 0.69042
  Epoch 018 - train 0.56687 | val 0.70172
  Classification -> best τ=0.500 (val F1=0.2784)
  Directional -> Accuracy: 0.5532, MCC: -0.0220, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63994 | val 0.93139
  Epoch 011 - train 0.62948 | val 1.03388
  Classification -> best τ=0.510 (val F1=0.2607)
  Directional -> Accuracy: 0.5385, MCC: 0.1436, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63755 | val 0.73025
  Epoch 013 - train 0.63038 | val 0.73611
  Classification -> best τ=0.555 (val F1=0.1418)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57618 | val 1.00997
  Epoch 011 - train 0.62098 | val 0.94815
  Classification -> best τ=0.480 (val F1=0.0412)
  Directional -> Accuracy: 0.4154, MCC: -0.2178, F1: 0.2083

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64355 | val 0.70087
  Epoch 014 - train 0.58904 | val 0.81297
  Classification -> best τ=0.460 (val F1=0.4240)
  Directional -> Accuracy: 0.4909, MCC: 0.0305, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57391 | val 1.42210
  Epoch 011 - train 0.58494 | val 1.69491
  Classification -> best τ=0.555 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63037 | val 0.68811
  Epoch 014 - train 0.60859 | val 0.72162
  Classification -> best τ=0.595 (val F1=0.0280)
  Directional -> Accuracy: 0.4048, MCC: -0.1273, F1: 0.1379

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61467 | val 0.83279
  Epoch 013 - train 0.58263 | val 0.93100
  Classification -> best τ=0.485 (val F1=0.2268)
  Directional -> Accuracy: 0.4643, MCC: 0.0292, F1: 0.1667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58291 | val 1.37587
  Epoch 011 - train 0.55600 | val 1.64292
  Classification -> best τ=0.450 (val F1=0.4114)
  Directional -> Accuracy: 0.5250, MCC: 0.0356, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59251 | val 1.05013
  Epoch 012 - train 0.55845 | val 1.49644
  Classification -> best τ=0.490 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64671 | val 0.90676
  Epoch 013 - train 0.54267 | val 0.72412
  Classification -> best τ=0.550 (val F1=0.1591)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66461 | val 0.69879
  Epoch 014 - train 0.56331 | val 0.87194
  Classification -> best τ=0.595 (val F1=0.5118)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65021 | val 0.71074
  Epoch 016 - train 0.58349 | val 0.99266
  Classification -> best τ=0.335 (val F1=0.3610)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61889 | val 0.92914
  Epoch 012 - train 0.61705 | val 1.07964
  Classification -> best τ=0.545 (val F1=0.3753)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67108 | val 0.76116
  Epoch 015 - train 0.60755 | val 0.84529
  Classification -> best τ=0.415 (val F1=0.3525)
  Directional -> Accuracy: 0.6364, MCC: 0.2556, F1: 0.6842

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59128 | val 0.80791
  Epoch 011 - train 0.58761 | val 1.05737
  Classification -> best τ=0.565 (val F1=0.2409)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53871 | val 0.91794
  Epoch 012 - train 0.54128 | val 1.05990
  Classification -> best τ=0.490 (val F1=0.3322)
  Directional -> Accuracy: 0.5536, MCC: 0.0962, F1: 0.4898

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53336 | val 0.80822
  Epoch 011 - train 0.51149 | val 0.85826
  Classification -> best τ=0.495 (val F1=0.1709)
  Directional -> Accuracy: 0.5435, MCC: -0.0318, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51443 | val 0.71547
  Epoch 013 - train 0.54830 | val 0.76886
  Classification -> best τ=0.425 (val F1=0.3006)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57827 | val 0.71006
  Epoch 016 - train 0.54496 | val 0.66137
  Classification -> best τ=0.415 (val F1=0.3653)
  Directional -> Accuracy: 0.5135, MCC: 0.1622, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60583 | val 0.79250
  Epoch 012 - train 0.55905 | val 0.86377
  Classification -> best τ=0.405 (val F1=0.1976)
  Directional -> Accuracy: 0.4444, MCC: -0.1632, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63585 | val 0.68854
  Epoch 020 - train 0.52418 | val 0.58920
  Epoch 025 - train 0.46868 | val 0.57938
  Classification -> best τ=0.440 (val F1=0.5593)
  Directional -> Accuracy: 0.6429, MCC: 0.2759, F1: 0.7541

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62218 | val 0.70637
  Epoch 018 - train 0.47298 | val 0.62222
  Classification -> best τ=0.565 (val F1=0.6290)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60345 | val 0.83766
  Epoch 015 - train 0.59775 | val 0.90612
  Classification -> best τ=0.540 (val F1=0.3200)
  Directional -> Accuracy: 0.3818, MCC: -0.2792, F1: 0.4848

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62805 | val 1.35449
  Epoch 011 - train 0.62941 | val 1.07551
  Classification -> best τ=0.500 (val F1=0.2444)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64034 | val 1.23128
  Epoch 015 - train 0.56909 | val 1.57530
  Classification -> best τ=0.435 (val F1=0.2668)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64534 | val 0.76565
  Epoch 014 - train 0.60376 | val 0.73542
  Classification -> best τ=0.490 (val F1=0.1757)
  Directional -> Accuracy: 0.4909, MCC: 0.0125, F1: 0.3333

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61340 | val 0.81512

[I 2026-02-20 06:15:20,484] Trial 231 finished with value: 0.26987185485873005 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009925691180872519, 'weight_decay': 1.4997368770515934e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0521147217571187, 'early_stopping_min_delta': 0.0023724565058893285}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 017 - train 0.53017 | val 0.79837
  Classification -> best τ=0.445 (val F1=0.2637)
  Directional -> Accuracy: 0.4833, MCC: -0.0111, F1: 0.6265

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26987185485873005
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57320 | val 0.69992
  Epoch 012 - train 0.59236 | val 0.68433
  Classification -> best τ=0.575 (val F1=0.2036)
  Directional -> Accuracy: 0.5658, MCC: 0.0886, F1: 0.3529

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54617 | val 0.72959
  Epoch 014 - train 0.49920 | val 0.76136
  Classification -> best τ=0.515 (val F1=0.2523)
  Directional -> Accuracy: 0.4889, MCC: 0.0900, F1: 0.3429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64455 | val 0.76108
  Epoch 015 - train 0.60054 | val 0.77853
  Classification -> best τ=0.450 (val F1=0.2759)
  Directional -> Accuracy: 0.5435, MCC: 0.0807, F1: 0.5882

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61911 | val 0.77748
  Epoch 012 - train 0.63627 | val 1.29289
  Classification -> best τ=0.560 (val F1=0.2579)
  Directional -> Accuracy: 0.5000, MCC: -0.0942, F1: 0.6476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59424 | val 0.80950
  Epoch 013 - train 0.58829 | val 0.93003
  Classification -> best τ=0.585 (val F1=0.4602)
  Directional -> Accuracy: 0.5800, MCC: 0.2203, F1: 0.4324

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60583 | val 0.85438
  Epoch 011 - train 0.63851 | val 0.79215
  Classification -> best τ=0.600 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65255 | val 0.67752
  Epoch 020 - train 0.58978 | val 1.37412
  Classification -> best τ=0.300 (val F1=0.3102)
  Directional -> Accuracy: 0.4853, MCC: 0.1391, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50032 | val 0.77552
  Epoch 015 - train 0.48302 | val 1.41179
  Classification -> best τ=0.430 (val F1=0.2168)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58833 | val 0.68256
  Epoch 020 - train 0.42879 | val 1.01979
  Classification -> best τ=0.680 (val F1=0.3433)
  Directional -> Accuracy: 0.6667, MCC: 0.3228, F1: 0.6190

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55979 | val 0.94244
  Epoch 011 - train 0.58880 | val 0.87424
  Classification -> best τ=0.480 (val F1=0.1304)
  Directional -> Accuracy: 0.3913, MCC: -0.2753, F1: 0.2222

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67967 | val 0.70660
  Epoch 014 - train 0.67146 | val 0.90513
  Classification -> best τ=0.425 (val F1=0.3075)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61459 | val 1.19968
  Epoch 012 - train 0.53411 | val 1.67843
  Classification -> best τ=0.580 (val F1=0.0728)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61900 | val 0.84664
  Epoch 012 - train 0.57880 | val 1.03200
  Classification -> best τ=0.510 (val F1=0.2850)
  Directional -> Accuracy: 0.5238, MCC: 0.1062, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63414 | val 0.66982
  Epoch 014 - train 0.57967 | val 0.92521
  Classification -> best τ=0.400 (val F1=0.4019)
  Directional -> Accuracy: 0.5500, MCC: 0.1014, F1: 0.5091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56782 | val 0.81340
  Epoch 013 - train 0.48434 | val 0.96174
  Classification -> best τ=0.565 (val F1=0.2069)
  Directional -> Accuracy: 0.4902, MCC: 0.0659, F1: 0.6061

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61578 | val 0.77924
  Epoch 015 - train 0.55435 | val 0.88600
  Classification -> best τ=0.380 (val F1=0.3448)
  Directional -> Accuracy: 0.6087, MCC: 0.2102, F1: 0.6966

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60493 | val 0.81262
  Epoch 012 - train 0.56648 | val 0.89121
  Classification -> best τ=0.605 (val F1=0.1291)
  Directional -> Accuracy: 0.5172, MCC: 0.3127, F1: 0.3636

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63638 | val 1.07833
  Epoch 012 - train 0.66188 | val 1.03780
  Classification -> best τ=0.575 (val F1=0.1087)
  Directional -> Accuracy: 0.4533, MCC: 0.0419, F1: 0.3051

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60781 | val 1.43547
  Epoch 012 - train 0.63830 | val 1.08706
  Classification -> best τ=0.380 (val F1=0.3140)
  Directional -> Accuracy: 0.5312, MCC: 0.1003, F1: 0.5161

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61109 | val 0.69456
  Epoch 014 - train 0.60384 | val 0.71449
  Classification -> best τ=0.510 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62512 | val 0.68949
  Epoch 011 - train 0.61181 | val 0.71280
  Classification -> best τ=0.585 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63270 | val 0.83451
  Epoch 012 - train 0.61244 | val 0.75058
  Classification -> best τ=0.355 (val F1=0.0566)
  Directional -> Accuracy: 0.5231, MCC: 0.0442, F1: 0.6173

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65503 | val 0.87087
  Epoch 014 - train 0.59996 | val 1.06654
  Classification -> best τ=0.585 (val F1=0.3913)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64370 | val 0.75443
  Epoch 015 - train 0.56697 | val 0.85095
  Classification -> best τ=0.500 (val F1=0.3164)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56686 | val 0.93577
  Epoch 018 - train 0.50644 | val 0.89265
  Classification -> best τ=0.630 (val F1=0.5345)
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56265 | val 0.73478
  Epoch 013 - train 0.51409 | val 1.00616
  Classification -> best τ=0.495 (val F1=0.2035)
  Directional -> Accuracy: 0.5111, MCC: 0.2029, F1: 0.6207

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61013 | val 0.68694
  Epoch 013 - train 0.58606 | val 0.76763
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61924 | val 0.77564
  Epoch 013 - train 0.61235 | val 0.85477
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63176 | val 1.04836
  Epoch 011 - train 0.59150 | val 1.27334
  Classification -> best τ=0.445 (val F1=0.4109)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59102 | val 1.23969
  Epoch 012 - train 0.61780 | val 1.12443
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63162 | val 1.07738
  Epoch 012 - train 0.61464 | val 1.05450
  Classification -> best τ=0.655 (val F1=0.0716)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54787 | val 0.82719
  Epoch 012 - train 0.50593 | val 1.32318
  Classification -> best τ=0.405 (val F1=0.3323)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60562 | val 0.66736
  Epoch 018 - train 0.54714 | val 0.73787
  Classification -> best τ=0.470 (val F1=0.2968)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64115 | val 0.89292
  Epoch 011 - train 0.61302 | val 0.98807
  Classification -> best τ=0.390 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65487 | val 0.86662
  Epoch 013 - train 0.59802 | val 0.91081
  Classification -> best τ=0.460 (val F1=0.2778)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57243 | val 0.82610
  Epoch 011 - train 0.50329 | val 1.30753
  Classification -> best τ=0.480 (val F1=0.2768)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57007 | val 0.90407
  Epoch 012 - train 0.56037 | val 0.72988
  Classification -> best τ=0.390 (val F1=0.2530)
  Directional -> Accuracy: 0.4286, MCC: -0.1281, F1: 0.4839

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58224 | val 0.86495
  Epoch 011 - train 0.54960 | val 0.85152
  Classification -> best τ=0.385 (val F1=0.0460)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60068 | val 0.90738
  Epoch 014 - train 0.55526 | val 0.89426
  Classification -> best τ=0.600 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58721 | val 1.04662
  Epoch 015 - train 0.60204 | val 0.78695
  Classification -> best τ=0.305 (val F1=0.3582)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52822 | val 0.72650
  Epoch 012 - train 0.55501 | val 0.87881
  Classification -> best τ=0.475 (val F1=0.0395)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59048 | val 0.62799
  Epoch 020 - train 0.54031 | val 0.67598
  Epoch 021 - train 0.52087 | val 0.66728
  Classification -> best τ=0.290 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59642 | val 0.66220
  Epoch 014 - train 0.54397 | val 0.78894
  Classification -> best τ=0.415 (val F1=0.5514)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57803 | val 0.86890
  Epoch 011 - train 0.60800 | val 0.75607
  Classification -> best τ=0.565 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60549 | val 1.16826
  Epoch 013 - train 0.52368 | val 1.79416
  Classification -> best τ=0.485 (val F1=0.2385)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65704 | val 0.85482
  Epoch 014 - train 0.61115 | val 1.47733
  Classification -> best τ=0.470 (val F1=0.3033)
  Directional -> Accuracy: 0.5094, MCC: 0.0216, F1: 0.4800

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67891 | val 0.73665
  Epoch 011 - train 0.68692 | val 0.71822
  Classification -> best τ=0.480 (val F1=0.2557)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58965 | val 0.91553

[I 2026-02-20 06:16:17,291] Trial 232 finished with value: 0.26003711678527486 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009928848886629298, 'weight_decay': 1.6280129043927004e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0630197535171344, 'early_stopping_min_delta': 0.0028050587885510322}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 012 - train 0.58602 | val 0.99894
  Classification -> best τ=0.460 (val F1=0.2124)
  Directional -> Accuracy: 0.4667, MCC: -0.1135, F1: 0.2000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26003711678527486
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58678 | val 0.70980
  Epoch 017 - train 0.61126 | val 1.20596
  Classification -> best τ=0.450 (val F1=0.1375)
  Directional -> Accuracy: 0.5132, MCC: 0.1660, F1: 0.6337

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61495 | val 0.66567
  Epoch 020 - train 0.48784 | val 0.67316
  Epoch 023 - train 0.45811 | val 0.81586
  Classification -> best τ=0.460 (val F1=0.5745)
  Directional -> Accuracy: 0.6889, MCC: 0.3547, F1: 0.7407

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56309 | val 0.79235
  Epoch 013 - train 0.58763 | val 0.94974
  Classification -> best τ=0.480 (val F1=0.3308)
  Directional -> Accuracy: 0.5652, MCC: 0.1241, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68670 | val 0.77574
  Epoch 014 - train 0.64344 | val 0.84889
  Classification -> best τ=0.530 (val F1=0.1839)
  Directional -> Accuracy: 0.5000, MCC: 0.0228, F1: 0.4478

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62145 | val 0.86649
  Epoch 015 - train 0.49186 | val 1.16683
  Classification -> best τ=0.605 (val F1=0.4247)
  Directional -> Accuracy: 0.5600, MCC: 0.2009, F1: 0.3529

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61065 | val 0.81261
  Epoch 012 - train 0.56234 | val 0.87955
  Classification -> best τ=0.490 (val F1=0.2204)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64594 | val 0.74023
  Epoch 012 - train 0.69719 | val 0.70508
  Classification -> best τ=0.555 (val F1=0.2727)
  Directional -> Accuracy: 0.5588, MCC: 0.0174, F1: 0.3182

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57368 | val 1.00085
  Epoch 012 - train 0.55574 | val 1.18087
  Classification -> best τ=0.385 (val F1=0.1418)
  Directional -> Accuracy: 0.4762, MCC: -0.1750, F1: 0.1538

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54665 | val 0.66310
  Epoch 020 - train 0.46936 | val 0.82919
  Epoch 025 - train 0.42763 | val 1.23531
  Classification -> best τ=0.525 (val F1=0.3433)
  Directional -> Accuracy: 0.6458, MCC: 0.2768, F1: 0.5854

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58994 | val 0.75978
  Epoch 014 - train 0.52031 | val 1.06255
  Classification -> best τ=0.510 (val F1=0.2986)
  Directional -> Accuracy: 0.4638, MCC: -0.0301, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61972 | val 0.82294
  Epoch 014 - train 0.69513 | val 1.11968
  Classification -> best τ=0.420 (val F1=0.2484)
  Directional -> Accuracy: 0.6122, MCC: 0.2027, F1: 0.4242

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54688 | val 1.48599
  Epoch 015 - train 0.46366 | val 4.00279
  Classification -> best τ=0.400 (val F1=0.1083)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56616 | val 1.15415
  Epoch 013 - train 0.52160 | val 1.00349
  Classification -> best τ=0.445 (val F1=0.2438)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63642 | val 0.77335
  Epoch 013 - train 0.58841 | val 0.77655
  Classification -> best τ=0.360 (val F1=0.3026)
  Directional -> Accuracy: 0.5167, MCC: 0.0385, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60623 | val 0.82471
  Epoch 014 - train 0.55736 | val 1.05484
  Classification -> best τ=0.535 (val F1=0.2078)
  Directional -> Accuracy: 0.5686, MCC: 0.0965, F1: 0.2667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62045 | val 0.91005
  Epoch 012 - train 0.60212 | val 0.84036
  Classification -> best τ=0.550 (val F1=0.4028)
  Directional -> Accuracy: 0.5217, MCC: -0.0357, F1: 0.6733

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62024 | val 1.16134
  Epoch 011 - train 0.61482 | val 1.24414
  Classification -> best τ=0.685 (val F1=0.1291)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62342 | val 0.95199
  Epoch 015 - train 0.57582 | val 1.10277
  Classification -> best τ=0.355 (val F1=0.2216)
  Directional -> Accuracy: 0.5467, MCC: 0.2722, F1: 0.4333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64313 | val 1.03120
  Epoch 014 - train 0.66603 | val 1.37902
  Classification -> best τ=0.390 (val F1=0.3140)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65768 | val 0.70651
  Epoch 014 - train 0.64387 | val 0.73229
  Classification -> best τ=0.460 (val F1=0.3439)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58452 | val 0.71491
  Epoch 019 - train 0.43798 | val 1.10709
  Classification -> best τ=0.395 (val F1=0.3678)
  Directional -> Accuracy: 0.5957, MCC: -0.0267, F1: 0.7397

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62890 | val 1.04494
  Epoch 012 - train 0.66195 | val 0.96369
  Classification -> best τ=0.510 (val F1=0.3216)
  Directional -> Accuracy: 0.4462, MCC: -0.1191, F1: 0.5263

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61651 | val 0.74129
  Epoch 013 - train 0.58956 | val 0.80656
  Classification -> best τ=0.365 (val F1=0.3616)
  Directional -> Accuracy: 0.5789, MCC: 0.1083, F1: 0.7209

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62903 | val 0.74291
  Epoch 012 - train 0.64034 | val 0.96304
  Classification -> best τ=0.380 (val F1=0.1429)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57916 | val 0.62219
  Epoch 020 - train 0.42897 | val 0.90870
  Classification -> best τ=0.455 (val F1=0.4723)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.6154

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58609 | val 0.74152
  Epoch 015 - train 0.39651 | val 1.34616
  Classification -> best τ=0.560 (val F1=0.3006)
  Directional -> Accuracy: 0.5333, MCC: -0.0445, F1: 0.2222

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58603 | val 0.69640
  Epoch 011 - train 0.61180 | val 0.68410
  Classification -> best τ=0.565 (val F1=0.1005)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58428 | val 0.72199
  Epoch 012 - train 0.62133 | val 0.85260
  Classification -> best τ=0.330 (val F1=0.1986)
  Directional -> Accuracy: 0.5357, MCC: 0.0464, F1: 0.6061

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65160 | val 1.31385
  Epoch 012 - train 0.57206 | val 1.37309
  Classification -> best τ=0.505 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59486 | val 1.00846
  Epoch 012 - train 0.57031 | val 0.92433
  Classification -> best τ=0.430 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.6545

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58107 | val 1.86278
  Epoch 012 - train 0.55508 | val 1.31555
  Classification -> best τ=0.525 (val F1=0.1425)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56611 | val 0.71791
  Epoch 016 - train 0.45650 | val 0.96557
  Classification -> best τ=0.335 (val F1=0.3647)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65231 | val 0.68439
  Epoch 020 - train 0.60946 | val 0.68558
  Epoch 022 - train 0.54016 | val 0.76376
  Classification -> best τ=0.500 (val F1=0.4246)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58291 | val 0.88524
  Epoch 011 - train 0.57680 | val 0.87133
  Classification -> best τ=0.585 (val F1=0.2804)
  Directional -> Accuracy: 0.4651, MCC: -0.1084, F1: 0.2069

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66488 | val 0.85936
  Epoch 014 - train 0.61741 | val 1.03376
  Classification -> best τ=0.330 (val F1=0.3603)
  Directional -> Accuracy: 0.4697, MCC: 0.1873, F1: 0.1463

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51913 | val 1.35453
  Epoch 011 - train 0.54567 | val 1.31360
  Classification -> best τ=0.635 (val F1=0.3420)
  Directional -> Accuracy: 0.5476, MCC: 0.1494, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59706 | val 0.71839
  Epoch 012 - train 0.55508 | val 0.71674
  Classification -> best τ=0.450 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0601, F1: 0.6111

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56593 | val 1.09349
  Epoch 012 - train 0.51384 | val 1.21630
  Classification -> best τ=0.420 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56008 | val 0.63776
  Epoch 019 - train 0.44985 | val 0.69106
  Classification -> best τ=0.360 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58252 | val 0.75206
  Epoch 015 - train 0.56472 | val 0.84557
  Classification -> best τ=0.455 (val F1=0.4007)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53607 | val 1.00846
  Epoch 015 - train 0.46712 | val 1.07854
  Classification -> best τ=0.520 (val F1=0.2582)
  Directional -> Accuracy: 0.5556, MCC: 0.1107, F1: 0.5652

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61795 | val 0.86382
  Epoch 017 - train 0.52692 | val 0.61334
  Classification -> best τ=0.225 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66434 | val 0.68167
  Epoch 015 - train 0.62047 | val 0.66057
  Classification -> best τ=0.675 (val F1=0.3638)
  Directional -> Accuracy: 0.5208, MCC: 0.0990, F1: 0.5106

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59230 | val 0.73604
  Epoch 013 - train 0.59021 | val 0.77760
  Classification -> best τ=0.600 (val F1=0.0080)
  Directional -> Accuracy: 0.4909, MCC: -0.2193, F1: 0.6585

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55319 | val 1.05327
  Epoch 011 - train 0.55709 | val 1.13816
  Classification -> best τ=0.530 (val F1=0.2227)
  Directional -> Accuracy: 0.5000, MCC: 0.0405, F1: 0.6316

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59524 | val 1.23447
  Epoch 011 - train 0.59913 | val 2.15150
  Classification -> best τ=0.605 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1005, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61890 | val 1.18909
  Epoch 011 - train 0.58837 | val 1.28228
  Classification -> best τ=0.490 (val F1=0.0924)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63364 | val 0.78542

[I 2026-02-20 06:17:19,249] Trial 233 finished with value: 0.2820663520360208 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009958094850228708, 'weight_decay': 1.0309309658001236e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1071741898190093, 'early_stopping_min_delta': 0.0033742303746420632}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.61124 | val 0.69224
  Classification -> best τ=0.495 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2820663520360208
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60399 | val 0.72879
  Epoch 016 - train 0.55964 | val 0.68973
  Classification -> best τ=0.365 (val F1=0.1328)
  Directional -> Accuracy: 0.4342, MCC: -0.1283, F1: 0.6055

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60391 | val 0.68221
  Epoch 014 - train 0.53334 | val 0.67744
  Classification -> best τ=0.460 (val F1=0.2073)
  Directional -> Accuracy: 0.6444, MCC: 0.2704, F1: 0.7576

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62584 | val 0.72247
  Epoch 014 - train 0.61001 | val 0.78716
  Classification -> best τ=0.475 (val F1=0.2725)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65602 | val 0.79213
  Epoch 012 - train 0.63436 | val 0.73493
  Classification -> best τ=0.430 (val F1=0.1808)
  Directional -> Accuracy: 0.5000, MCC: -0.1895, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59793 | val 0.67395
  Epoch 020 - train 0.55188 | val 0.79174
  Epoch 021 - train 0.43453 | val 0.82444
  Classification -> best τ=0.575 (val F1=0.5155)
  Directional -> Accuracy: 0.4600, MCC: -0.0801, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59719 | val 0.91632
  Epoch 012 - train 0.58854 | val 0.69791
  Classification -> best τ=0.645 (val F1=0.2204)
  Directional -> Accuracy: 0.5652, MCC: 0.1234, F1: 0.4444

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63682 | val 0.90099
  Epoch 011 - train 0.60271 | val 1.11777
  Classification -> best τ=0.520 (val F1=0.1347)
  Directional -> Accuracy: 0.4853, MCC: -0.0301, F1: 0.4262

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55417 | val 0.72740
  Epoch 012 - train 0.49567 | val 0.83443
  Classification -> best τ=0.370 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60197 | val 0.79964
  Epoch 019 - train 0.50432 | val 0.95984
  Classification -> best τ=0.600 (val F1=0.3962)
  Directional -> Accuracy: 0.5625, MCC: 0.0727, F1: 0.3636

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61449 | val 0.71271
  Epoch 012 - train 0.58311 | val 0.81880
  Classification -> best τ=0.405 (val F1=0.1858)
  Directional -> Accuracy: 0.4493, MCC: 0.0544, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66436 | val 0.75912
  Epoch 011 - train 0.64095 | val 0.80798
  Classification -> best τ=0.435 (val F1=0.0825)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55897 | val 1.13663
  Epoch 012 - train 0.52185 | val 1.78142
  Classification -> best τ=0.555 (val F1=0.0465)
  Directional -> Accuracy: 0.3860, MCC: -0.2673, F1: 0.1463

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53425 | val 1.68654
  Epoch 012 - train 0.57782 | val 1.56463
  Classification -> best τ=0.395 (val F1=0.2791)
  Directional -> Accuracy: 0.4762, MCC: -0.0673, F1: 0.3889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62922 | val 0.69778
  Epoch 016 - train 0.57211 | val 0.71159
  Classification -> best τ=0.430 (val F1=0.3833)
  Directional -> Accuracy: 0.6167, MCC: 0.2446, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57205 | val 0.75215
  Epoch 011 - train 0.57255 | val 0.82057
  Classification -> best τ=0.565 (val F1=0.4325)
  Directional -> Accuracy: 0.3922, MCC: -0.1954, F1: 0.5079

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60130 | val 0.97698
  Epoch 014 - train 0.58939 | val 0.79143
  Classification -> best τ=0.695 (val F1=0.2694)
  Directional -> Accuracy: 0.5217, MCC: 0.1839, F1: 0.2326

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60854 | val 0.88999
  Epoch 011 - train 0.59571 | val 0.86411
  Classification -> best τ=0.560 (val F1=0.2540)
  Directional -> Accuracy: 0.3966, MCC: -0.2132, F1: 0.4615

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60973 | val 0.92578
  Epoch 012 - train 0.60492 | val 0.94547
  Classification -> best τ=0.495 (val F1=0.0596)
  Directional -> Accuracy: 0.4933, MCC: 0.0335, F1: 0.4865

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67849 | val 0.68571
  Epoch 015 - train 0.63956 | val 1.07851
  Classification -> best τ=0.305 (val F1=0.2522)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66095 | val 0.66514
  Epoch 020 - train 0.57379 | val 0.64681
  Epoch 028 - train 0.53148 | val 1.46487
  Classification -> best τ=0.675 (val F1=0.4036)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59699 | val 0.68054
  Epoch 020 - train 0.48100 | val 0.97913
  Classification -> best τ=0.455 (val F1=0.4146)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64235 | val 0.89106
  Epoch 011 - train 0.62517 | val 0.85469
  Classification -> best τ=0.595 (val F1=0.2376)
  Directional -> Accuracy: 0.5077, MCC: 0.0533, F1: 0.1579

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64313 | val 0.72439
  Epoch 013 - train 0.61703 | val 0.73619
  Classification -> best τ=0.670 (val F1=0.3550)
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63313 | val 0.80761
  Epoch 012 - train 0.61309 | val 0.70306
  Classification -> best τ=0.430 (val F1=0.1348)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55845 | val 1.11028
  Epoch 014 - train 0.54285 | val 0.79832
  Classification -> best τ=0.505 (val F1=0.4339)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56479 | val 1.38251
  Epoch 011 - train 0.53703 | val 1.81515
  Classification -> best τ=0.430 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60229 | val 0.76481
  Epoch 016 - train 0.53151 | val 0.72338
  Classification -> best τ=0.620 (val F1=0.1353)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63693 | val 0.75428
  Epoch 015 - train 0.60698 | val 1.04572
  Classification -> best τ=0.315 (val F1=0.2066)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62755 | val 0.77809
  Epoch 015 - train 0.49082 | val 0.73977
  Classification -> best τ=0.530 (val F1=0.2618)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61924 | val 0.75591
  Epoch 012 - train 0.54521 | val 0.82003
  Classification -> best τ=0.605 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58846 | val 0.86244
  Epoch 014 - train 0.55593 | val 0.93482
  Classification -> best τ=0.490 (val F1=0.1986)
  Directional -> Accuracy: 0.5238, MCC: 0.0478, F1: 0.5455

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61475 | val 0.74535
  Epoch 013 - train 0.53868 | val 0.83138
  Classification -> best τ=0.670 (val F1=0.2399)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62474 | val 0.71722
  Epoch 018 - train 0.64566 | val 0.77248
  Classification -> best τ=0.330 (val F1=0.3196)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64893 | val 0.75291
  Epoch 018 - train 0.53047 | val 1.01115
  Classification -> best τ=0.460 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: 0.1508, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63447 | val 0.72581
  Epoch 012 - train 0.64245 | val 0.81005
  Classification -> best τ=0.430 (val F1=0.2972)
  Directional -> Accuracy: 0.5606, MCC: 0.2072, F1: 0.4912

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52452 | val 0.71262
  Epoch 012 - train 0.46004 | val 0.84835
  Classification -> best τ=0.510 (val F1=0.3260)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54985 | val 0.79884
  Epoch 012 - train 0.50724 | val 0.80545
  Classification -> best τ=0.435 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.0780, F1: 0.5970

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46085 | val 0.96292
  Epoch 013 - train 0.49294 | val 1.19141
  Classification -> best τ=0.455 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53223 | val 0.76104
  Epoch 012 - train 0.57715 | val 0.70668
  Classification -> best τ=0.460 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62133 | val 0.97998
  Epoch 011 - train 0.62824 | val 0.98721
  Classification -> best τ=0.505 (val F1=0.2782)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59783 | val 0.71007
  Epoch 017 - train 0.47938 | val 0.87717
  Classification -> best τ=0.495 (val F1=0.3500)
  Directional -> Accuracy: 0.5111, MCC: 0.0349, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55546 | val 0.81542
  Epoch 011 - train 0.57504 | val 0.82076
  Classification -> best τ=0.490 (val F1=0.2942)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60270 | val 0.62459
  Epoch 020 - train 0.43140 | val 0.80358
  Epoch 021 - train 0.42470 | val 0.83073
  Classification -> best τ=0.500 (val F1=0.5514)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59484 | val 0.71515
  Epoch 011 - train 0.59949 | val 0.72402
  Classification -> best τ=0.595 (val F1=0.1569)
  Directional -> Accuracy: 0.4545, MCC: -0.0377, F1: 0.2105

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61095 | val 1.63630
  Epoch 012 - train 0.59857 | val 2.04319
  Classification -> best τ=0.485 (val F1=0.2914)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64189 | val 0.92714
  Epoch 012 - train 0.63113 | val 0.88324
  Classification -> best τ=0.505 (val F1=0.2155)
  Directional -> Accuracy: 0.5660, MCC: 0.1343, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62617 | val 0.75408
  Epoch 016 - train 0.60982 | val 0.74664
  Classification -> best τ=0.480 (val F1=0.1943)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60004 | val 1.33879

[I 2026-02-20 06:18:20,929] Trial 234 finished with value: 0.2623501665728176 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007965234658280113, 'weight_decay': 1.2407038256742351e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1066772728310548, 'early_stopping_min_delta': 0.0034630827675147507}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.61886 | val 0.73718
  Classification -> best τ=0.455 (val F1=0.2045)
  Directional -> Accuracy: 0.4500, MCC: -0.1237, F1: 0.2979

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2623501665728176
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59335 | val 0.71093
  Epoch 016 - train 0.63312 | val 0.72136
  Classification -> best τ=0.550 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1835, F1: 0.4231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60095 | val 0.68113
  Epoch 020 - train 0.45505 | val 0.79271
  Epoch 021 - train 0.46783 | val 0.78464
  Classification -> best τ=0.435 (val F1=0.3265)
  Directional -> Accuracy: 0.6444, MCC: 0.2960, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62891 | val 0.92580
  Epoch 013 - train 0.57542 | val 0.90687
  Classification -> best τ=0.530 (val F1=0.3140)
  Directional -> Accuracy: 0.6087, MCC: 0.2137, F1: 0.6400

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65456 | val 0.83219
  Epoch 016 - train 0.62394 | val 0.83042
  Classification -> best τ=0.480 (val F1=0.1105)
  Directional -> Accuracy: 0.4865, MCC: 0.1005, F1: 0.1364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59613 | val 0.76692
  Epoch 011 - train 0.56219 | val 1.12039
  Classification -> best τ=0.495 (val F1=0.3612)
  Directional -> Accuracy: 0.6200, MCC: 0.2442, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64015 | val 0.90809
  Epoch 011 - train 0.62457 | val 0.85014
  Classification -> best τ=0.590 (val F1=0.2739)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.5902

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65978 | val 0.70345
  Epoch 012 - train 0.67409 | val 0.82575
  Classification -> best τ=0.495 (val F1=0.2043)
  Directional -> Accuracy: 0.5882, MCC: 0.1186, F1: 0.4400

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51852 | val 0.71425
  Epoch 015 - train 0.46477 | val 1.25982
  Classification -> best τ=0.310 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59978 | val 0.64133
  Epoch 020 - train 0.49338 | val 0.85438
  Epoch 023 - train 0.43701 | val 1.22844
  Classification -> best τ=0.510 (val F1=0.3962)
  Directional -> Accuracy: 0.5833, MCC: 0.1534, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59119 | val 0.74769
  Epoch 012 - train 0.63705 | val 0.86966
  Classification -> best τ=0.580 (val F1=0.2877)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61399 | val 0.68644
  Epoch 015 - train 0.61921 | val 0.78500
  Classification -> best τ=0.420 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54956 | val 0.88101
  Epoch 012 - train 0.53549 | val 1.34018
  Classification -> best τ=0.585 (val F1=0.0657)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59063 | val 1.26576
  Epoch 012 - train 0.55811 | val 1.49364
  Classification -> best τ=0.445 (val F1=0.2018)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60409 | val 0.79660
  Epoch 013 - train 0.59756 | val 0.79554
  Classification -> best τ=0.365 (val F1=0.3706)
  Directional -> Accuracy: 0.5667, MCC: 0.1667, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60944 | val 0.74325
  Epoch 016 - train 0.66960 | val 0.79119
  Classification -> best τ=0.530 (val F1=0.2078)
  Directional -> Accuracy: 0.4902, MCC: 0.0277, F1: 0.5667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60652 | val 0.90059
  Epoch 013 - train 0.60115 | val 0.85102
  Classification -> best τ=0.485 (val F1=0.2996)
  Directional -> Accuracy: 0.5942, MCC: 0.1744, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63223 | val 0.89076
  Epoch 011 - train 0.61396 | val 0.84556
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62356 | val 1.28612
  Epoch 012 - train 0.63334 | val 1.42624
  Classification -> best τ=0.590 (val F1=0.1164)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63795 | val 0.92754
  Epoch 011 - train 0.67477 | val 1.00036
  Classification -> best τ=0.510 (val F1=0.4444)
  Directional -> Accuracy: 0.5156, MCC: 0.1672, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59942 | val 0.66810
  Epoch 016 - train 0.57598 | val 0.81102
  Classification -> best τ=0.410 (val F1=0.3439)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59901 | val 0.69502
  Epoch 020 - train 0.48830 | val 0.78231
  Epoch 029 - train 0.33122 | val 0.71463
  Classification -> best τ=0.360 (val F1=0.3678)
  Directional -> Accuracy: 0.5319, MCC: 0.1638, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65494 | val 0.90882
  Epoch 013 - train 0.67584 | val 1.51626
  Classification -> best τ=0.535 (val F1=0.2794)
  Directional -> Accuracy: 0.4462, MCC: -0.1301, F1: 0.1818

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62626 | val 0.78033
  Epoch 020 - train 0.58681 | val 0.96796
  Epoch 024 - train 0.54616 | val 0.98704
  Classification -> best τ=0.490 (val F1=0.3015)
  Directional -> Accuracy: 0.5614, MCC: 0.1055, F1: 0.6154

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67052 | val 0.82506
  Epoch 012 - train 0.65771 | val 0.85468
  Classification -> best τ=0.460 (val F1=0.1005)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53000 | val 0.66888
  Epoch 018 - train 0.53358 | val 0.70794
  Classification -> best τ=0.640 (val F1=0.3858)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56028 | val 0.82131
  Epoch 011 - train 0.55054 | val 0.81993
  Classification -> best τ=0.495 (val F1=0.1310)
  Directional -> Accuracy: 0.4889, MCC: -0.0885, F1: 0.3030

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62106 | val 0.77166
  Epoch 012 - train 0.56930 | val 0.77713
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60674 | val 0.80626
  Epoch 013 - train 0.57660 | val 1.09304
  Classification -> best τ=0.460 (val F1=0.2386)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62753 | val 0.69103
  Epoch 018 - train 0.50586 | val 0.87047
  Classification -> best τ=0.435 (val F1=0.4862)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61039 | val 0.89648
  Epoch 012 - train 0.56876 | val 0.91639
  Classification -> best τ=0.565 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53699 | val 1.14024
  Epoch 012 - train 0.60938 | val 0.98869
  Classification -> best τ=0.455 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56379 | val 0.77040
  Epoch 014 - train 0.52155 | val 0.87248
  Classification -> best τ=0.430 (val F1=0.3957)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63778 | val 0.70466
  Epoch 014 - train 0.61853 | val 0.87878
  Classification -> best τ=0.440 (val F1=0.3131)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60579 | val 1.04061
  Epoch 011 - train 0.60060 | val 1.20364
  Classification -> best τ=0.530 (val F1=0.2632)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60265 | val 0.92171
  Epoch 011 - train 0.58554 | val 0.84992
  Classification -> best τ=0.495 (val F1=0.2292)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48038 | val 0.75200
  Epoch 012 - train 0.57533 | val 0.85216
  Classification -> best τ=0.580 (val F1=0.2618)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54091 | val 0.89517
  Epoch 011 - train 0.53797 | val 0.87825
  Classification -> best τ=0.435 (val F1=0.2110)
  Directional -> Accuracy: 0.5357, MCC: 0.0769, F1: 0.5357

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56449 | val 0.97443
  Epoch 012 - train 0.52361 | val 1.13477
  Classification -> best τ=0.550 (val F1=0.3089)
  Directional -> Accuracy: 0.4348, MCC: -0.0094, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51163 | val 0.64986
  Epoch 020 - train 0.41379 | val 0.72338
  Epoch 027 - train 0.34581 | val 0.85724
  Classification -> best τ=0.265 (val F1=0.4469)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61505 | val 0.72599
  Epoch 020 - train 0.51975 | val 0.96280
  Epoch 025 - train 0.44178 | val 1.20691
  Classification -> best τ=0.480 (val F1=0.3584)
  Directional -> Accuracy: 0.4865, MCC: -0.0211, F1: 0.5366

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55386 | val 0.77865
  Epoch 012 - train 0.55822 | val 0.86759
  Classification -> best τ=0.485 (val F1=0.3287)
  Directional -> Accuracy: 0.5556, MCC: 0.1395, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60397 | val 0.62661
  Epoch 020 - train 0.46166 | val 0.95431
  Classification -> best τ=0.270 (val F1=0.4082)
  Directional -> Accuracy: 0.6429, MCC: 0.3203, F1: 0.7619

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62479 | val 0.66981
  Epoch 020 - train 0.41649 | val 0.61347
  Epoch 027 - train 0.26674 | val 0.75083
  Classification -> best τ=0.775 (val F1=0.3705)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61723 | val 0.89663
  Epoch 020 - train 0.51997 | val 1.00995
  Epoch 023 - train 0.53307 | val 1.43458
  Classification -> best τ=0.540 (val F1=0.3298)
  Directional -> Accuracy: 0.4727, MCC: 0.0199, F1: 0.2162

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56818 | val 1.68363
  Epoch 011 - train 0.58053 | val 1.57101
  Classification -> best τ=0.420 (val F1=0.2640)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61757 | val 0.72723
  Epoch 015 - train 0.64706 | val 1.24511
  Classification -> best τ=0.430 (val F1=0.1646)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60452 | val 0.81993
  Epoch 015 - train 0.58176 | val 1.01138
  Classification -> best τ=0.515 (val F1=0.2694)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60965 | val 0.69723

[I 2026-02-20 06:19:24,483] Trial 235 finished with value: 0.2721795761764348 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.0070326085437852955, 'weight_decay': 1.2808931282751468e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.169385897926264, 'early_stopping_min_delta': 0.003110098916625106}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.55997 | val 0.69069
  Classification -> best τ=0.470 (val F1=0.2749)
  Directional -> Accuracy: 0.5000, MCC: -0.0503, F1: 0.1176

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2721795761764348
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61830 | val 0.80572
  Epoch 012 - train 0.68396 | val 0.82501
  Classification -> best τ=0.425 (val F1=0.1637)
  Directional -> Accuracy: 0.4868, MCC: 0.1036, F1: 0.6214

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61922 | val 0.68165
  Epoch 020 - train 0.56018 | val 0.69993
  Epoch 026 - train 0.46216 | val 0.71096
  Classification -> best τ=0.330 (val F1=0.3022)
  Directional -> Accuracy: 0.5778, MCC: 0.1842, F1: 0.5778

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60396 | val 0.74098
  Epoch 017 - train 0.52095 | val 1.11308
  Classification -> best τ=0.440 (val F1=0.3678)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63576 | val 0.89681
  Epoch 012 - train 0.62174 | val 0.83511
  Classification -> best τ=0.535 (val F1=0.2303)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64119 | val 0.63277
  Epoch 019 - train 0.52677 | val 0.78216
  Classification -> best τ=0.585 (val F1=0.4862)
  Directional -> Accuracy: 0.5200, MCC: 0.0385, F1: 0.5385

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66160 | val 0.81429
  Epoch 011 - train 0.61860 | val 0.97412
  Classification -> best τ=0.595 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64944 | val 0.68454
  Epoch 011 - train 0.67907 | val 0.69139
  Classification -> best τ=0.515 (val F1=0.2536)
  Directional -> Accuracy: 0.5735, MCC: 0.0581, F1: 0.3556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51090 | val 1.01261
  Epoch 012 - train 0.48467 | val 0.90144
  Classification -> best τ=0.265 (val F1=0.0668)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.2222

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51785 | val 0.68025
  Epoch 014 - train 0.52382 | val 0.75284
  Classification -> best τ=0.490 (val F1=0.3433)
  Directional -> Accuracy: 0.5417, MCC: -0.0542, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57942 | val 0.98652
  Epoch 012 - train 0.63718 | val 0.76618
  Classification -> best τ=0.560 (val F1=0.1801)
  Directional -> Accuracy: 0.5942, MCC: 0.1324, F1: 0.4167

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66063 | val 0.88900
  Epoch 012 - train 0.58134 | val 1.47325
  Classification -> best τ=0.515 (val F1=0.2484)
  Directional -> Accuracy: 0.5306, MCC: 0.1168, F1: 0.5965

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51927 | val 0.76422
  Epoch 012 - train 0.57960 | val 1.80415
  Classification -> best τ=0.550 (val F1=0.1685)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53844 | val 1.38658
  Epoch 012 - train 0.56788 | val 1.54848
  Classification -> best τ=0.665 (val F1=0.1370)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62048 | val 0.65056
  Epoch 011 - train 0.61882 | val 0.63230
  Classification -> best τ=0.360 (val F1=0.3362)
  Directional -> Accuracy: 0.5167, MCC: 0.0338, F1: 0.5538

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62326 | val 0.71012
  Epoch 013 - train 0.62461 | val 0.76935
  Classification -> best τ=0.450 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59900 | val 0.86201
  Epoch 012 - train 0.62220 | val 0.80589
  Classification -> best τ=0.495 (val F1=0.2185)
  Directional -> Accuracy: 0.4348, MCC: -0.1341, F1: 0.4658

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57865 | val 1.08702
  Epoch 011 - train 0.56910 | val 1.19940
  Classification -> best τ=0.655 (val F1=0.2540)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60722 | val 2.02396
  Epoch 012 - train 0.57127 | val 1.69048
  Classification -> best τ=0.520 (val F1=0.0876)
  Directional -> Accuracy: 0.4000, MCC: -0.0602, F1: 0.1176

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63999 | val 0.79293
  Epoch 017 - train 0.64821 | val 1.48172
  Classification -> best τ=0.565 (val F1=0.3804)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64124 | val 0.66758
  Epoch 018 - train 0.55905 | val 0.70367
  Classification -> best τ=0.400 (val F1=0.3006)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59084 | val 0.66316
  Epoch 020 - train 0.43322 | val 0.83910
  Epoch 021 - train 0.38578 | val 0.98229
  Classification -> best τ=0.540 (val F1=0.4465)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63759 | val 0.81280
  Epoch 013 - train 0.61572 | val 0.89070
  Classification -> best τ=0.495 (val F1=0.2254)
  Directional -> Accuracy: 0.4923, MCC: -0.0341, F1: 0.6207

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62507 | val 0.69939
  Epoch 012 - train 0.61498 | val 0.82442
  Classification -> best τ=0.575 (val F1=0.2981)
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65354 | val 1.04484
  Epoch 011 - train 0.66049 | val 0.75195
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62978 | val 0.62417
  Epoch 020 - train 0.52667 | val 0.66907
  Classification -> best τ=0.540 (val F1=0.4723)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59808 | val 1.20881
  Epoch 011 - train 0.53541 | val 1.27915
  Classification -> best τ=0.440 (val F1=0.1131)
  Directional -> Accuracy: 0.5556, MCC: 0.1308, F1: 0.5455

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60539 | val 0.68073
  Epoch 020 - train 0.51254 | val 0.67442
  Epoch 029 - train 0.44799 | val 0.78399
  Classification -> best τ=0.670 (val F1=0.2810)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.3030

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61277 | val 0.75909
  Epoch 016 - train 0.55612 | val 1.12800
  Classification -> best τ=0.360 (val F1=0.1997)
  Directional -> Accuracy: 0.5893, MCC: 0.1477, F1: 0.6761

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63734 | val 0.71048
  Epoch 012 - train 0.51901 | val 0.87901
  Classification -> best τ=0.525 (val F1=0.3477)
  Directional -> Accuracy: 0.4250, MCC: -0.1372, F1: 0.4103

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60179 | val 1.19835
  Epoch 012 - train 0.57953 | val 1.23318
  Classification -> best τ=0.490 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0754, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59330 | val 0.97081
  Epoch 011 - train 0.52436 | val 0.97423
  Classification -> best τ=0.520 (val F1=0.2646)
  Directional -> Accuracy: 0.4286, MCC: -0.1114, F1: 0.2941

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56471 | val 0.82690
  Epoch 012 - train 0.60643 | val 0.88280
  Classification -> best τ=0.470 (val F1=0.2978)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62771 | val 0.69020
  Epoch 015 - train 0.63945 | val 0.93963
  Classification -> best τ=0.420 (val F1=0.4458)
  Directional -> Accuracy: 0.5139, MCC: 0.0733, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62425 | val 0.82181
  Epoch 012 - train 0.56266 | val 0.93291
  Classification -> best τ=0.540 (val F1=0.3742)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65157 | val 0.84664
  Epoch 013 - train 0.61464 | val 0.85694
  Classification -> best τ=0.505 (val F1=0.2485)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57247 | val 0.68936
  Epoch 016 - train 0.48871 | val 1.16246
  Classification -> best τ=0.375 (val F1=0.2067)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55783 | val 0.76038
  Epoch 014 - train 0.53483 | val 0.87042
  Classification -> best τ=0.375 (val F1=0.2946)
  Directional -> Accuracy: 0.5000, MCC: 0.0214, F1: 0.5484

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52364 | val 0.98592
  Epoch 011 - train 0.50247 | val 1.06021
  Classification -> best τ=0.460 (val F1=0.2118)
  Directional -> Accuracy: 0.5000, MCC: 0.0194, F1: 0.5306

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55420 | val 0.71890
  Epoch 017 - train 0.48529 | val 0.90602
  Classification -> best τ=0.580 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62550 | val 0.79105
  Epoch 011 - train 0.58505 | val 0.75019
  Classification -> best τ=0.500 (val F1=0.3837)
  Directional -> Accuracy: 0.5946, MCC: 0.3057, F1: 0.7000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55315 | val 0.79733
  Epoch 012 - train 0.54132 | val 0.85703
  Classification -> best τ=0.455 (val F1=0.2174)
  Directional -> Accuracy: 0.6000, MCC: 0.2023, F1: 0.6538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57446 | val 0.60555
  Epoch 020 - train 0.52130 | val 0.84311
  Classification -> best τ=0.230 (val F1=0.4588)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65092 | val 0.65719
  Epoch 014 - train 0.62182 | val 0.82484
  Classification -> best τ=0.695 (val F1=0.5689)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57752 | val 0.70188
  Epoch 011 - train 0.59490 | val 0.73874
  Classification -> best τ=0.630 (val F1=0.1647)
  Directional -> Accuracy: 0.3273, MCC: -0.3348, F1: 0.2745

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58046 | val 1.67059
  Epoch 011 - train 0.54794 | val 1.91219
  Classification -> best τ=0.495 (val F1=0.4159)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63856 | val 0.94898
  Epoch 017 - train 0.61429 | val 1.31049
  Classification -> best τ=0.760 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58084 | val 0.93066
  Epoch 011 - train 0.58365 | val 0.93585
  Classification -> best τ=0.550 (val F1=0.0279)
  Directional -> Accuracy: 0.4909, MCC: -0.0014, F1: 0.4167

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63698 | val 0.69829

[I 2026-02-20 06:20:26,750] Trial 236 finished with value: 0.27310612545842233 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008606658998512031, 'weight_decay': 1.0239250320997619e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2939161736079918, 'early_stopping_min_delta': 0.003199692427152945}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 018 - train 0.58284 | val 0.89592
  Classification -> best τ=0.425 (val F1=0.2006)
  Directional -> Accuracy: 0.5667, MCC: 0.1849, F1: 0.6579

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27310612545842233
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62383 | val 0.66289
  Epoch 020 - train 0.53002 | val 0.83349
  Epoch 024 - train 0.52953 | val 1.28117
  Classification -> best τ=0.530 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0822, F1: 0.5205

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57390 | val 0.69453
  Epoch 020 - train 0.46520 | val 0.76861
  Epoch 024 - train 0.47425 | val 0.72577
  Classification -> best τ=0.280 (val F1=0.2285)
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65521 | val 0.75130
  Epoch 015 - train 0.54772 | val 0.85865
  Classification -> best τ=0.415 (val F1=0.4847)
  Directional -> Accuracy: 0.5000, MCC: 0.0547, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67485 | val 0.81050
  Epoch 012 - train 0.64886 | val 0.73990
  Classification -> best τ=0.440 (val F1=0.0693)
  Directional -> Accuracy: 0.4865, MCC: 0.0590, F1: 0.2083

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55027 | val 1.12028
  Epoch 013 - train 0.55313 | val 1.36747
  Classification -> best τ=0.595 (val F1=0.4611)
  Directional -> Accuracy: 0.6200, MCC: 0.3459, F1: 0.4571

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64604 | val 0.74505
  Epoch 011 - train 0.64862 | val 0.70601
  Classification -> best τ=0.560 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64220 | val 0.78106
  Epoch 011 - train 0.63799 | val 0.82850
  Classification -> best τ=0.445 (val F1=0.2727)
  Directional -> Accuracy: 0.5294, MCC: 0.0921, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54255 | val 0.76938
  Epoch 012 - train 0.48874 | val 0.78808
  Classification -> best τ=0.320 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.5385

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55274 | val 0.82877
  Epoch 013 - train 0.52012 | val 1.14979
  Classification -> best τ=0.545 (val F1=0.3616)
  Directional -> Accuracy: 0.6250, MCC: 0.2250, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63592 | val 0.72486
  Epoch 013 - train 0.51848 | val 0.82188
  Classification -> best τ=0.525 (val F1=0.1128)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67343 | val 0.67805
  Epoch 014 - train 0.64574 | val 0.86254
  Classification -> best τ=0.420 (val F1=0.2543)
  Directional -> Accuracy: 0.4694, MCC: -0.0637, F1: 0.4348

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54477 | val 1.54404
  Epoch 012 - train 0.52209 | val 1.78176
  Classification -> best τ=0.525 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60462 | val 1.31424
  Epoch 011 - train 0.58161 | val 1.36736
  Classification -> best τ=0.550 (val F1=0.2522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61806 | val 0.63532
  Epoch 016 - train 0.53614 | val 0.70490
  Classification -> best τ=0.295 (val F1=0.3721)
  Directional -> Accuracy: 0.5500, MCC: 0.1014, F1: 0.5091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64578 | val 0.74094
  Epoch 016 - train 0.57285 | val 2.21232
  Classification -> best τ=0.570 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59222 | val 0.81046
  Epoch 013 - train 0.56657 | val 1.62952
  Classification -> best τ=0.525 (val F1=0.3301)
  Directional -> Accuracy: 0.5507, MCC: 0.1967, F1: 0.3673

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59095 | val 1.31157
  Epoch 014 - train 0.53934 | val 1.67750
  Classification -> best τ=0.680 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61166 | val 2.36414
  Epoch 013 - train 0.59251 | val 1.86823
  Classification -> best τ=0.460 (val F1=0.2479)
  Directional -> Accuracy: 0.5333, MCC: 0.1238, F1: 0.5205

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67400 | val 1.31466
  Epoch 013 - train 0.57985 | val 1.86341
  Classification -> best τ=0.530 (val F1=0.2234)
  Directional -> Accuracy: 0.4688, MCC: 0.1894, F1: 0.1500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63288 | val 0.68286
  Epoch 019 - train 0.61009 | val 0.75061
  Classification -> best τ=0.480 (val F1=0.3164)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62158 | val 0.88430
  Epoch 020 - train 0.48170 | val 1.41388
  Epoch 030 - train 0.31089 | val 0.71705
  Epoch 039 - train 0.36381 | val 1.56675
  Classification -> best τ=0.445 (val F1=0.3693)
  Directional -> Accuracy: 0.5319, MCC: 0.0504, F1: 0.5926

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65713 | val 0.77294
  Epoch 013 - train 0.59838 | val 1.34779
  Classification -> best τ=0.505 (val F1=0.1856)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61365 | val 0.71504
  Epoch 013 - train 0.55687 | val 0.74278
  Classification -> best τ=0.525 (val F1=0.3652)
  Directional -> Accuracy: 0.5614, MCC: 0.1400, F1: 0.5614

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63144 | val 0.75700
  Epoch 015 - train 0.59845 | val 0.71076
  Classification -> best τ=0.425 (val F1=0.0670)
  Directional -> Accuracy: 0.4769, MCC: -0.1601, F1: 0.0556

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59311 | val 0.74594
  Epoch 015 - train 0.59154 | val 0.78900
  Classification -> best τ=0.515 (val F1=0.4914)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54455 | val 0.99439
  Epoch 011 - train 0.55928 | val 0.94701
  Classification -> best τ=0.330 (val F1=0.2935)
  Directional -> Accuracy: 0.4667, MCC: -0.0230, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66833 | val 0.70720
  Epoch 011 - train 0.66930 | val 0.70341
  Classification -> best τ=0.605 (val F1=0.1487)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65145 | val 0.71358
  Epoch 017 - train 0.58230 | val 0.88026
  Classification -> best τ=0.330 (val F1=0.2011)
  Directional -> Accuracy: 0.5714, MCC: 0.0950, F1: 0.7000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58408 | val 0.67952
  Epoch 020 - train 0.39545 | val 1.05919
  Classification -> best τ=0.380 (val F1=0.4109)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63588 | val 0.98274
  Epoch 012 - train 0.55684 | val 1.21132
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58433 | val 1.50112
  Epoch 011 - train 0.54089 | val 1.74962
  Classification -> best τ=0.585 (val F1=0.1846)
  Directional -> Accuracy: 0.4286, MCC: -0.1070, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61688 | val 0.84701
  Epoch 013 - train 0.50341 | val 0.99523
  Classification -> best τ=0.320 (val F1=0.4100)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62245 | val 0.82622
  Epoch 014 - train 0.59996 | val 1.06341
  Classification -> best τ=0.640 (val F1=0.2637)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61404 | val 0.90591
  Epoch 011 - train 0.59736 | val 1.01236
  Classification -> best τ=0.520 (val F1=0.2631)
  Directional -> Accuracy: 0.3256, MCC: -0.3486, F1: 0.3556

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66642 | val 0.73558
  Epoch 012 - train 0.64222 | val 0.82959
  Classification -> best τ=0.350 (val F1=0.2357)
  Directional -> Accuracy: 0.6364, MCC: 0.2315, F1: 0.7209

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55141 | val 0.95638
  Epoch 016 - train 0.47600 | val 0.99767
  Classification -> best τ=0.640 (val F1=0.2618)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57299 | val 0.82993
  Epoch 012 - train 0.56474 | val 0.75888
  Classification -> best τ=0.435 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: -0.1049, F1: 0.4364

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52190 | val 1.21406
  Epoch 012 - train 0.47692 | val 1.25185
  Classification -> best τ=0.330 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54857 | val 0.68540
  Epoch 020 - train 0.43908 | val 0.81388
  Epoch 023 - train 0.38583 | val 0.81433
  Classification -> best τ=0.260 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59773 | val 0.74579
  Epoch 017 - train 0.49443 | val 0.96680
  Classification -> best τ=0.410 (val F1=0.3263)
  Directional -> Accuracy: 0.5000, MCC: 0.0630, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53798 | val 0.80327
  Epoch 013 - train 0.48390 | val 1.14166
  Classification -> best τ=0.445 (val F1=0.2039)
  Directional -> Accuracy: 0.5556, MCC: 0.1129, F1: 0.5455

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60366 | val 0.61471
  Epoch 020 - train 0.54719 | val 0.88048
  Epoch 024 - train 0.49641 | val 1.69130
  Classification -> best τ=0.465 (val F1=0.5230)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62763 | val 0.64033
  Epoch 020 - train 0.45551 | val 0.56458
  Epoch 030 - train 0.22173 | val 1.00549
  Classification -> best τ=0.375 (val F1=0.7775)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59012 | val 0.72954
  Epoch 011 - train 0.59043 | val 0.73459
  Classification -> best τ=0.590 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58741 | val 1.17859
  Epoch 011 - train 0.55016 | val 1.40187
  Classification -> best τ=0.435 (val F1=0.2378)
  Directional -> Accuracy: 0.5357, MCC: 0.0633, F1: 0.4348

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61161 | val 1.01668
  Epoch 012 - train 0.57953 | val 1.20234
  Classification -> best τ=0.450 (val F1=0.2139)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60531 | val 1.12599
  Epoch 011 - train 0.57850 | val 0.97328
  Classification -> best τ=0.460 (val F1=0.0465)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64968 | val 0.86796

[I 2026-02-20 06:21:31,534] Trial 237 finished with value: 0.28092862144463854 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009994546539490707, 'weight_decay': 1.6915644612911372e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1423797667961166, 'early_stopping_min_delta': 0.0027018714469099693}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 014 - train 0.60352 | val 0.81920
  Classification -> best τ=0.490 (val F1=0.2124)
  Directional -> Accuracy: 0.4667, MCC: -0.1710, F1: 0.0588

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28092862144463854
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59129 | val 0.74547
  Epoch 014 - train 0.60792 | val 0.70785
  Classification -> best τ=0.430 (val F1=0.2039)
  Directional -> Accuracy: 0.5395, MCC: 0.1417, F1: 0.6067

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59226 | val 0.67230
  Epoch 020 - train 0.42591 | val 0.66339
  Epoch 027 - train 0.42433 | val 0.67389
  Classification -> best τ=0.530 (val F1=0.3513)
  Directional -> Accuracy: 0.6000, MCC: 0.2060, F1: 0.6250

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62540 | val 0.74649
  Epoch 017 - train 0.50128 | val 1.14261
  Classification -> best τ=0.490 (val F1=0.3285)
  Directional -> Accuracy: 0.5217, MCC: 0.0259, F1: 0.6207

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64447 | val 0.69912
  Epoch 012 - train 0.63319 | val 0.78835
  Classification -> best τ=0.415 (val F1=0.1829)
  Directional -> Accuracy: 0.5000, MCC: 0.0453, F1: 0.3729

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61570 | val 0.67118
  Epoch 014 - train 0.54082 | val 0.88856
  Classification -> best τ=0.555 (val F1=0.4259)
  Directional -> Accuracy: 0.6600, MCC: 0.3309, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59290 | val 0.77483
  Epoch 014 - train 0.53970 | val 1.01075
  Classification -> best τ=0.610 (val F1=0.1684)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64534 | val 0.71648
  Epoch 012 - train 0.64845 | val 0.88794
  Classification -> best τ=0.465 (val F1=0.1907)
  Directional -> Accuracy: 0.5441, MCC: 0.1757, F1: 0.5753

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55420 | val 0.91344
  Epoch 012 - train 0.53754 | val 1.18386
  Classification -> best τ=0.210 (val F1=0.2075)
  Directional -> Accuracy: 0.4762, MCC: -0.1217, F1: 0.2667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59615 | val 0.77723
  Epoch 014 - train 0.50963 | val 0.71392
  Classification -> best τ=0.510 (val F1=0.3431)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60748 | val 0.71613
  Epoch 013 - train 0.58533 | val 0.99400
  Classification -> best τ=0.520 (val F1=0.0299)
  Directional -> Accuracy: 0.5362, MCC: 0.0392, F1: 0.4286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64077 | val 0.88633
  Epoch 013 - train 0.57044 | val 2.39994
  Classification -> best τ=0.425 (val F1=0.1422)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61410 | val 0.74082
  Epoch 016 - train 0.50005 | val 1.50260
  Classification -> best τ=0.615 (val F1=0.2083)
  Directional -> Accuracy: 0.4737, MCC: -0.0675, F1: 0.1176

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55582 | val 1.66657
  Epoch 012 - train 0.54310 | val 1.32797
  Classification -> best τ=0.550 (val F1=0.2176)
  Directional -> Accuracy: 0.5000, MCC: -0.2032, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64018 | val 0.64354
  Epoch 020 - train 0.65793 | val 1.28605
  Epoch 021 - train 0.60520 | val 1.11282
  Classification -> best τ=0.460 (val F1=0.4139)
  Directional -> Accuracy: 0.5167, MCC: 0.0335, F1: 0.5397

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59714 | val 0.71621
  Epoch 014 - train 0.59726 | val 0.73965
  Classification -> best τ=0.500 (val F1=0.2078)
  Directional -> Accuracy: 0.4902, MCC: -0.0216, F1: 0.4583

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59399 | val 0.78385
  Epoch 011 - train 0.58543 | val 1.13129
  Classification -> best τ=0.520 (val F1=0.3570)
  Directional -> Accuracy: 0.5507, MCC: 0.0913, F1: 0.5974

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59756 | val 0.91000
  Epoch 013 - train 0.62240 | val 0.93614
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58110 | val 0.96049
  Epoch 013 - train 0.66626 | val 0.88893
  Classification -> best τ=0.485 (val F1=0.2621)
  Directional -> Accuracy: 0.6000, MCC: 0.1315, F1: 0.6939

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65657 | val 1.03692
  Epoch 013 - train 0.60557 | val 1.17692
  Classification -> best τ=0.460 (val F1=0.3385)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67248 | val 0.68377
  Epoch 011 - train 0.67648 | val 0.67667
  Classification -> best τ=0.545 (val F1=0.3206)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60161 | val 0.74011
  Epoch 019 - train 0.54312 | val 0.86951
  Classification -> best τ=0.455 (val F1=0.3678)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62008 | val 1.01897
  Epoch 011 - train 0.61421 | val 0.88957
  Classification -> best τ=0.660 (val F1=0.0772)
  Directional -> Accuracy: 0.5077, MCC: 0.1231, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67420 | val 0.67684
  Epoch 012 - train 0.64271 | val 0.74662
  Classification -> best τ=0.550 (val F1=0.4008)
  Directional -> Accuracy: 0.5088, MCC: 0.0286, F1: 0.5172

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56939 | val 0.93334
  Epoch 016 - train 0.54424 | val 0.90909
  Classification -> best τ=0.570 (val F1=0.1393)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67280 | val 0.67704
  Epoch 015 - train 0.62352 | val 0.73165
  Classification -> best τ=0.495 (val F1=0.4582)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54150 | val 0.77444
  Epoch 014 - train 0.50066 | val 1.19196
  Classification -> best τ=0.580 (val F1=0.2726)
  Directional -> Accuracy: 0.6444, MCC: 0.2493, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65368 | val 0.69381
  Epoch 011 - train 0.62394 | val 0.69523
  Classification -> best τ=0.550 (val F1=0.0829)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.6780

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68478 | val 0.75135
  Epoch 019 - train 0.64356 | val 0.98369
  Classification -> best τ=0.445 (val F1=0.2999)
  Directional -> Accuracy: 0.5714, MCC: 0.2952, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63737 | val 0.81985
  Epoch 016 - train 0.53151 | val 1.12067
  Classification -> best τ=0.575 (val F1=0.3477)
  Directional -> Accuracy: 0.4750, MCC: -0.0453, F1: 0.4878

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62733 | val 1.11013
  Epoch 012 - train 0.55282 | val 1.26247
  Classification -> best τ=0.670 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64188 | val 0.71767
  Epoch 020 - train 0.52378 | val 2.03181
  Epoch 026 - train 0.35069 | val 1.08950
  Classification -> best τ=0.320 (val F1=0.3385)
  Directional -> Accuracy: 0.4286, MCC: -0.1276, F1: 0.4000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61298 | val 0.73570
  Epoch 017 - train 0.53112 | val 1.08052
  Classification -> best τ=0.620 (val F1=0.3574)
  Directional -> Accuracy: 0.5102, MCC: 0.0835, F1: 0.2941

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61625 | val 0.66279
  Epoch 013 - train 0.62535 | val 0.76100
  Classification -> best τ=0.470 (val F1=0.3801)
  Directional -> Accuracy: 0.5278, MCC: -0.0157, F1: 0.6531

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62000 | val 0.78767
  Epoch 012 - train 0.55444 | val 0.94850
  Classification -> best τ=0.505 (val F1=0.0593)
  Directional -> Accuracy: 0.6279, MCC: 0.2611, F1: 0.5556

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62683 | val 0.82539
  Epoch 013 - train 0.61589 | val 1.09031
  Classification -> best τ=0.275 (val F1=0.3603)
  Directional -> Accuracy: 0.5152, MCC: 0.1126, F1: 0.4286

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51235 | val 2.12969
  Epoch 011 - train 0.47026 | val 2.47321
  Classification -> best τ=0.610 (val F1=0.2439)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55452 | val 0.79360
  Epoch 011 - train 0.53464 | val 0.80728
  Classification -> best τ=0.390 (val F1=0.2804)
  Directional -> Accuracy: 0.5536, MCC: 0.1222, F1: 0.5763

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50711 | val 1.12098
  Epoch 013 - train 0.47154 | val 1.40505
  Classification -> best τ=0.380 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59930 | val 0.74396
  Epoch 012 - train 0.56981 | val 0.65954
  Classification -> best τ=0.470 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61696 | val 0.67007
  Epoch 017 - train 0.56114 | val 0.69549
  Classification -> best τ=0.490 (val F1=0.3031)
  Directional -> Accuracy: 0.5000, MCC: 0.0267, F1: 0.6263

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53615 | val 0.80664
  Epoch 014 - train 0.50194 | val 1.05263
  Classification -> best τ=0.515 (val F1=0.3190)
  Directional -> Accuracy: 0.5111, MCC: 0.0445, F1: 0.3125

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59777 | val 0.71997
  Epoch 011 - train 0.59654 | val 0.73168
  Classification -> best τ=0.470 (val F1=0.2408)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71307 | val 0.85804
  Epoch 019 - train 0.61759 | val 0.81397
  Classification -> best τ=0.560 (val F1=0.5131)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61841 | val 0.67671
  Epoch 020 - train 0.52678 | val 0.74777
  Epoch 022 - train 0.49690 | val 0.82866
  Classification -> best τ=0.745 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58201 | val 2.15060
  Epoch 011 - train 0.53975 | val 1.78153
  Classification -> best τ=0.500 (val F1=0.2720)
  Directional -> Accuracy: 0.5179, MCC: 0.0167, F1: 0.2703

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63198 | val 0.84547
  Epoch 012 - train 0.61139 | val 0.91104
  Classification -> best τ=0.600 (val F1=0.1668)
  Directional -> Accuracy: 0.5472, MCC: 0.0977, F1: 0.5200

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61471 | val 0.82725
  Epoch 013 - train 0.60189 | val 0.92332
  Classification -> best τ=0.515 (val F1=0.2408)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61942 | val 0.68072

[I 2026-02-20 06:22:34,453] Trial 238 finished with value: 0.270890107373263 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00995224031425249, 'weight_decay': 1.626707031349624e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1056063898065722, 'early_stopping_min_delta': 0.0024028157730337524}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 018 - train 0.50388 | val 0.71938
  Classification -> best τ=0.565 (val F1=0.3448)
  Directional -> Accuracy: 0.4500, MCC: -0.1641, F1: 0.1538

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.270890107373263
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60076 | val 0.84406
  Epoch 012 - train 0.56160 | val 0.72346
  Classification -> best τ=0.425 (val F1=0.2034)
  Directional -> Accuracy: 0.4605, MCC: -0.0251, F1: 0.5591

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57723 | val 0.69427
  Epoch 012 - train 0.54735 | val 0.81448
  Classification -> best τ=0.420 (val F1=0.1722)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61355 | val 0.80193
  Epoch 011 - train 0.56673 | val 0.78626
  Classification -> best τ=0.615 (val F1=0.3882)
  Directional -> Accuracy: 0.5870, MCC: 0.2845, F1: 0.3871

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64563 | val 0.80324
  Epoch 012 - train 0.61577 | val 1.10053
  Classification -> best τ=0.495 (val F1=0.1849)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56890 | val 0.87502
  Epoch 016 - train 0.51124 | val 0.73622
  Classification -> best τ=0.575 (val F1=0.4602)
  Directional -> Accuracy: 0.5000, MCC: 0.1373, F1: 0.0741

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57206 | val 0.89337
  Epoch 011 - train 0.58281 | val 0.84940
  Classification -> best τ=0.620 (val F1=0.2739)
  Directional -> Accuracy: 0.5870, MCC: 0.1860, F1: 0.3871

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66266 | val 0.74527
  Epoch 015 - train 0.62960 | val 1.01002
  Classification -> best τ=0.510 (val F1=0.3110)
  Directional -> Accuracy: 0.5147, MCC: 0.1115, F1: 0.5479

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53988 | val 0.63961
  Epoch 012 - train 0.52203 | val 0.66141
  Classification -> best τ=0.335 (val F1=0.1657)
  Directional -> Accuracy: 0.4762, MCC: -0.1217, F1: 0.2667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58913 | val 0.76233
  Epoch 012 - train 0.56596 | val 0.79446
  Classification -> best τ=0.560 (val F1=0.3433)
  Directional -> Accuracy: 0.5833, MCC: 0.1116, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60649 | val 0.75381
  Epoch 011 - train 0.56246 | val 0.81272
  Classification -> best τ=0.440 (val F1=0.1304)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62072 | val 1.08816
  Epoch 015 - train 0.57369 | val 0.80867
  Classification -> best τ=0.395 (val F1=0.2672)
  Directional -> Accuracy: 0.5714, MCC: 0.1044, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55695 | val 1.60956
  Epoch 011 - train 0.55396 | val 1.57704
  Classification -> best τ=0.450 (val F1=0.2258)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56570 | val 1.58213
  Epoch 011 - train 0.59077 | val 1.36247
  Classification -> best τ=0.530 (val F1=0.1658)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59531 | val 0.63906
  Epoch 011 - train 0.57740 | val 0.66115
  Classification -> best τ=0.445 (val F1=0.3320)
  Directional -> Accuracy: 0.5167, MCC: 0.0335, F1: 0.4912

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60628 | val 0.83572
  Epoch 015 - train 0.54512 | val 0.87424
  Classification -> best τ=0.570 (val F1=0.2078)
  Directional -> Accuracy: 0.5882, MCC: 0.1583, F1: 0.2759

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61319 | val 0.71487
  Epoch 013 - train 0.59285 | val 0.85099
  Classification -> best τ=0.600 (val F1=0.3813)
  Directional -> Accuracy: 0.5072, MCC: 0.0596, F1: 0.3704

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59888 | val 0.92444
  Epoch 011 - train 0.58234 | val 0.94461
  Classification -> best τ=0.615 (val F1=0.2186)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61386 | val 1.36116
  Epoch 012 - train 0.57625 | val 2.05881
  Classification -> best τ=0.590 (val F1=0.1925)
  Directional -> Accuracy: 0.5200, MCC: 0.1299, F1: 0.4706

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60317 | val 0.94887
  Epoch 011 - train 0.60378 | val 1.38354
  Classification -> best τ=0.420 (val F1=0.2522)
  Directional -> Accuracy: 0.5469, MCC: 0.1825, F1: 0.4727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63405 | val 0.68404
  Epoch 019 - train 0.57275 | val 0.89378
  Classification -> best τ=0.475 (val F1=0.3460)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60642 | val 0.83815
  Epoch 017 - train 0.44815 | val 1.26519
  Classification -> best τ=0.415 (val F1=0.2800)
  Directional -> Accuracy: 0.5745, MCC: 0.1798, F1: 0.6000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65311 | val 0.85817
  Epoch 011 - train 0.64535 | val 0.82120
  Classification -> best τ=0.520 (val F1=0.1482)
  Directional -> Accuracy: 0.5077, MCC: 0.0384, F1: 0.2381

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62818 | val 0.76958
  Epoch 012 - train 0.60834 | val 0.91137
  Classification -> best τ=0.575 (val F1=0.3294)
  Directional -> Accuracy: 0.4912, MCC: 0.0154, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62233 | val 0.73652
  Epoch 014 - train 0.61765 | val 0.69858
  Classification -> best τ=0.430 (val F1=0.2056)
  Directional -> Accuracy: 0.4923, MCC: -0.0220, F1: 0.4407

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57747 | val 0.94211
  Epoch 013 - train 0.53891 | val 1.13699
  Classification -> best τ=0.450 (val F1=0.4051)
  Directional -> Accuracy: 0.4909, MCC: -0.1295, F1: 0.6410

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57417 | val 0.86741
  Epoch 013 - train 0.52530 | val 1.40040
  Classification -> best τ=0.570 (val F1=0.1932)
  Directional -> Accuracy: 0.5556, MCC: 0.0225, F1: 0.2857

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60314 | val 0.72475
  Epoch 011 - train 0.62041 | val 0.77291
  Classification -> best τ=0.565 (val F1=0.1487)
  Directional -> Accuracy: 0.5476, MCC: -0.0534, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63752 | val 0.84867
  Epoch 012 - train 0.62316 | val 1.13439
  Classification -> best τ=0.410 (val F1=0.1997)
  Directional -> Accuracy: 0.5536, MCC: 0.2311, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63717 | val 1.24970
  Epoch 016 - train 0.54781 | val 1.57530
  Classification -> best τ=0.455 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59853 | val 0.93373
  Epoch 020 - train 0.46068 | val 0.84029
  Epoch 025 - train 0.39674 | val 0.68613
  Classification -> best τ=0.710 (val F1=0.5210)
  Directional -> Accuracy: 0.5476, MCC: 0.1064, F1: 0.5778

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56740 | val 1.50173
  Epoch 011 - train 0.59278 | val 1.39471
  Classification -> best τ=0.365 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56902 | val 0.86585
  Epoch 013 - train 0.48368 | val 0.88638
  Classification -> best τ=0.330 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63399 | val 0.79805
  Epoch 016 - train 0.56925 | val 1.60012
  Classification -> best τ=0.470 (val F1=0.3583)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61589 | val 0.90491
  Epoch 012 - train 0.54465 | val 1.10233
  Classification -> best τ=0.365 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64611 | val 0.83893
  Epoch 012 - train 0.62355 | val 0.93287
  Classification -> best τ=0.515 (val F1=0.4073)
  Directional -> Accuracy: 0.6212, MCC: 0.2086, F1: 0.6914

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56204 | val 0.73907
  Epoch 017 - train 0.41238 | val 0.75431
  Classification -> best τ=0.475 (val F1=0.2193)
  Directional -> Accuracy: 0.5952, MCC: 0.1866, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57811 | val 0.76364
  Epoch 014 - train 0.52158 | val 0.81977
  Classification -> best τ=0.440 (val F1=0.2327)
  Directional -> Accuracy: 0.5179, MCC: 0.0283, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57966 | val 0.94574
  Epoch 013 - train 0.48223 | val 0.97998
  Classification -> best τ=0.460 (val F1=0.3105)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60091 | val 0.60928
  Epoch 020 - train 0.48932 | val 0.79366
  Classification -> best τ=0.320 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58332 | val 0.65349
  Epoch 016 - train 0.57694 | val 0.75941
  Classification -> best τ=0.505 (val F1=0.4801)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56007 | val 0.85254
  Epoch 012 - train 0.52933 | val 0.78943
  Classification -> best τ=0.415 (val F1=0.1890)
  Directional -> Accuracy: 0.5111, MCC: 0.1474, F1: 0.0833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61489 | val 0.63491
  Epoch 018 - train 0.49293 | val 1.03471
  Classification -> best τ=0.585 (val F1=0.6667)
  Directional -> Accuracy: 0.6190, MCC: 0.2123, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65864 | val 0.72779
  Epoch 012 - train 0.63184 | val 0.69279
  Classification -> best τ=0.540 (val F1=0.4795)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61060 | val 0.68936
  Epoch 011 - train 0.58801 | val 0.68379
  Classification -> best τ=0.640 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59928 | val 1.41526
  Epoch 011 - train 0.56202 | val 1.76039
  Classification -> best τ=0.380 (val F1=0.2939)
  Directional -> Accuracy: 0.4821, MCC: -0.0266, F1: 0.5397

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63288 | val 1.21889
  Epoch 011 - train 0.61619 | val 0.90424
  Classification -> best τ=0.500 (val F1=0.1409)
  Directional -> Accuracy: 0.5849, MCC: 0.1691, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61435 | val 0.84521
  Epoch 014 - train 0.57016 | val 0.81288
  Classification -> best τ=0.415 (val F1=0.1129)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66283 | val 0.69243

[I 2026-02-20 06:23:33,168] Trial 239 finished with value: 0.2815354202055291 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00843243972199701, 'weight_decay': 1.8289906981182127e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1429038035785337, 'early_stopping_min_delta': 0.0026996685303139045}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.64647 | val 0.71450
  Classification -> best τ=0.445 (val F1=0.2000)
  Directional -> Accuracy: 0.4167, MCC: -0.1649, F1: 0.4262

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2815354202055291
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62331 | val 0.80303
  Epoch 016 - train 0.54691 | val 0.96636
  Classification -> best τ=0.625 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0059, F1: 0.2222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56129 | val 0.69189
  Epoch 015 - train 0.51090 | val 0.69922
  Classification -> best τ=0.455 (val F1=0.3126)
  Directional -> Accuracy: 0.5111, MCC: 0.0885, F1: 0.4500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60628 | val 0.69589
  Epoch 020 - train 0.48390 | val 1.16597
  Epoch 021 - train 0.49687 | val 1.45409
  Classification -> best τ=0.545 (val F1=0.3285)
  Directional -> Accuracy: 0.5435, MCC: 0.0767, F1: 0.6182

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64507 | val 0.81464
  Epoch 014 - train 0.63305 | val 0.76470
  Classification -> best τ=0.495 (val F1=0.2327)
  Directional -> Accuracy: 0.5405, MCC: 0.0427, F1: 0.6531

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58875 | val 0.81754
  Epoch 015 - train 0.46801 | val 1.10581
  Classification -> best τ=0.540 (val F1=0.3751)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57941 | val 1.08588
  Epoch 013 - train 0.56585 | val 1.72041
  Classification -> best τ=0.535 (val F1=0.1463)
  Directional -> Accuracy: 0.5435, MCC: 0.0754, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65090 | val 0.84752
  Epoch 013 - train 0.61641 | val 0.92687
  Classification -> best τ=0.550 (val F1=0.2823)
  Directional -> Accuracy: 0.4265, MCC: -0.0925, F1: 0.4507

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52194 | val 0.94801
  Epoch 012 - train 0.54203 | val 0.90088
  Classification -> best τ=0.415 (val F1=0.0668)
  Directional -> Accuracy: 0.4286, MCC: -0.2041, F1: 0.2500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56907 | val 0.90984
  Epoch 012 - train 0.54851 | val 0.81154
  Classification -> best τ=0.375 (val F1=0.3376)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60611 | val 0.80882
  Epoch 016 - train 0.49500 | val 0.80892
  Classification -> best τ=0.540 (val F1=0.3208)
  Directional -> Accuracy: 0.5072, MCC: -0.0310, F1: 0.3704

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64505 | val 1.41264
  Epoch 015 - train 0.59592 | val 1.09508
  Classification -> best τ=0.440 (val F1=0.2593)
  Directional -> Accuracy: 0.5510, MCC: 0.2513, F1: 0.6562

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53137 | val 0.97178
  Epoch 014 - train 0.50649 | val 1.72119
  Classification -> best τ=0.530 (val F1=0.2487)
  Directional -> Accuracy: 0.5614, MCC: 0.1420, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54780 | val 1.13450
  Epoch 012 - train 0.51660 | val 1.24656
  Classification -> best τ=0.380 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62285 | val 0.65685
  Epoch 017 - train 0.49759 | val 1.06819
  Classification -> best τ=0.400 (val F1=0.3774)
  Directional -> Accuracy: 0.4833, MCC: -0.0385, F1: 0.5867

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60168 | val 0.87760
  Epoch 016 - train 0.49944 | val 0.98792
  Classification -> best τ=0.395 (val F1=0.2381)
  Directional -> Accuracy: 0.6078, MCC: 0.2571, F1: 0.6429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59773 | val 0.81340
  Epoch 016 - train 0.55316 | val 1.30064
  Classification -> best τ=0.630 (val F1=0.3386)
  Directional -> Accuracy: 0.5072, MCC: 0.0093, F1: 0.5405

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61612 | val 0.97120
  Epoch 011 - train 0.62432 | val 1.10484
  Classification -> best τ=0.560 (val F1=0.1629)
  Directional -> Accuracy: 0.5517, MCC: -0.1066, F1: 0.6977

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57965 | val 1.85974
  Epoch 012 - train 0.56765 | val 1.28920
  Classification -> best τ=0.570 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59536 | val 0.93301
  Epoch 014 - train 0.61957 | val 1.34021
  Classification -> best τ=0.525 (val F1=0.2326)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67822 | val 0.70865
  Epoch 018 - train 0.69107 | val 0.68164
  Classification -> best τ=0.635 (val F1=0.2701)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61715 | val 1.04325
  Epoch 017 - train 0.54509 | val 1.52378
  Classification -> best τ=0.555 (val F1=0.3020)
  Directional -> Accuracy: 0.4468, MCC: 0.2057, F1: 0.1875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60982 | val 1.05045
  Epoch 011 - train 0.62234 | val 0.97690
  Classification -> best τ=0.635 (val F1=0.2376)
  Directional -> Accuracy: 0.4462, MCC: -0.2234, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63094 | val 0.79418
  Epoch 015 - train 0.62031 | val 0.72602
  Classification -> best τ=0.795 (val F1=0.3550)
  Directional -> Accuracy: 0.4561, MCC: 0.0500, F1: 0.1143

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65059 | val 1.00814
  Epoch 011 - train 0.67389 | val 0.86529
  Classification -> best τ=0.525 (val F1=0.1348)
  Directional -> Accuracy: 0.5231, MCC: 0.0286, F1: 0.3673

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56325 | val 0.70791
  Epoch 015 - train 0.53734 | val 1.07693
  Classification -> best τ=0.635 (val F1=0.4947)
  Directional -> Accuracy: 0.4727, MCC: 0.0199, F1: 0.2162

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55875 | val 0.97340
  Epoch 011 - train 0.57791 | val 0.93218
  Classification -> best τ=0.460 (val F1=0.0155)
  Directional -> Accuracy: 0.4222, MCC: -0.0618, F1: 0.5517

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61741 | val 0.74765
  Epoch 016 - train 0.53339 | val 0.81789
  Classification -> best τ=0.655 (val F1=0.0913)
  Directional -> Accuracy: 0.5952, MCC: 0.1795, F1: 0.6383

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66423 | val 0.81665
  Epoch 011 - train 0.64892 | val 0.81025
  Classification -> best τ=0.440 (val F1=0.1341)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59805 | val 0.71479
  Epoch 019 - train 0.51166 | val 0.91396
  Classification -> best τ=0.405 (val F1=0.4139)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60917 | val 0.95168
  Epoch 012 - train 0.60781 | val 1.34552
  Classification -> best τ=0.480 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0754, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57606 | val 1.22531
  Epoch 012 - train 0.56813 | val 1.37060
  Classification -> best τ=0.580 (val F1=0.1425)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59946 | val 0.76558
  Epoch 013 - train 0.54470 | val 0.87023
  Classification -> best τ=0.630 (val F1=0.3465)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64183 | val 0.69509
  Epoch 013 - train 0.60745 | val 0.81377
  Classification -> best τ=0.385 (val F1=0.4032)
  Directional -> Accuracy: 0.5000, MCC: 0.0555, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61580 | val 0.70683
  Epoch 012 - train 0.63090 | val 0.77527
  Classification -> best τ=0.380 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62555 | val 0.79549
  Epoch 016 - train 0.61798 | val 0.81481
  Classification -> best τ=0.420 (val F1=0.2576)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52092 | val 1.09734
  Epoch 011 - train 0.48026 | val 1.14297
  Classification -> best τ=0.455 (val F1=0.2439)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49381 | val 0.84217
  Epoch 011 - train 0.53027 | val 0.79333
  Classification -> best τ=0.430 (val F1=0.2026)
  Directional -> Accuracy: 0.5893, MCC: 0.2034, F1: 0.6230

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54147 | val 1.27798
  Epoch 011 - train 0.54598 | val 1.55317
  Classification -> best τ=0.495 (val F1=0.1362)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5490

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58606 | val 0.67978
  Epoch 018 - train 0.44365 | val 1.01056
  Classification -> best τ=0.570 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62459 | val 0.71227
  Epoch 013 - train 0.58589 | val 0.67223
  Classification -> best τ=0.520 (val F1=0.3597)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56915 | val 0.77684
  Epoch 012 - train 0.52535 | val 0.89510
  Classification -> best τ=0.500 (val F1=0.3500)
  Directional -> Accuracy: 0.5333, MCC: 0.0764, F1: 0.4615

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60346 | val 0.67939
  Epoch 020 - train 0.47786 | val 0.87479
  Epoch 026 - train 0.40524 | val 0.93170
  Classification -> best τ=0.295 (val F1=0.4588)
  Directional -> Accuracy: 0.6190, MCC: 0.2107, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56952 | val 0.61042
  Epoch 020 - train 0.41378 | val 0.78109
  Epoch 022 - train 0.39987 | val 0.59448
  Classification -> best τ=0.505 (val F1=0.7162)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58107 | val 0.71098
  Epoch 011 - train 0.59627 | val 0.79289
  Classification -> best τ=0.625 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57460 | val 1.49952
  Epoch 011 - train 0.57267 | val 1.79251
  Classification -> best τ=0.500 (val F1=0.3104)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65627 | val 0.92262
  Epoch 011 - train 0.64502 | val 0.85382
  Classification -> best τ=0.545 (val F1=0.2133)
  Directional -> Accuracy: 0.5660, MCC: 0.1423, F1: 0.6567

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62701 | val 0.96799
  Epoch 011 - train 0.62640 | val 0.96853
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60247 | val 0.74806

[I 2026-02-20 06:24:33,051] Trial 240 finished with value: 0.2698962274840944 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007708287266275366, 'weight_decay': 1.0137229686061485e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1650034954744366, 'early_stopping_min_delta': 0.001726505815561513}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 017 - train 0.55933 | val 0.91640
  Classification -> best τ=0.415 (val F1=0.2915)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2698962274840944
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61034 | val 0.69107
  Epoch 018 - train 0.56813 | val 0.77501
  Classification -> best τ=0.380 (val F1=0.1435)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60728 | val 0.69176
  Epoch 017 - train 0.58225 | val 0.68320
  Classification -> best τ=0.530 (val F1=0.2073)
  Directional -> Accuracy: 0.6889, MCC: 0.3485, F1: 0.7586

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59480 | val 0.69922
  Epoch 019 - train 0.50428 | val 1.06126
  Classification -> best τ=0.555 (val F1=0.3678)
  Directional -> Accuracy: 0.5435, MCC: 0.2529, F1: 0.2222

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61844 | val 0.70807
  Epoch 020 - train 0.54772 | val 0.94110
  Epoch 022 - train 0.54969 | val 0.72024
  Classification -> best τ=0.510 (val F1=0.2011)
  Directional -> Accuracy: 0.5270, MCC: -0.1079, F1: 0.6903

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56431 | val 0.74898
  Epoch 015 - train 0.50611 | val 1.04770
  Classification -> best τ=0.540 (val F1=0.4851)
  Directional -> Accuracy: 0.5400, MCC: 0.1375, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60685 | val 0.70039
  Epoch 013 - train 0.61994 | val 0.72224
  Classification -> best τ=0.510 (val F1=0.0890)
  Directional -> Accuracy: 0.4565, MCC: -0.1945, F1: 0.0741

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67273 | val 0.74229
  Epoch 012 - train 0.64776 | val 0.94903
  Classification -> best τ=0.415 (val F1=0.3353)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57752 | val 0.93454
  Epoch 012 - train 0.51924 | val 1.41037
  Classification -> best τ=0.420 (val F1=0.1147)
  Directional -> Accuracy: 0.3810, MCC: -0.2123, F1: 0.4091

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56476 | val 0.79491
  Epoch 015 - train 0.55017 | val 0.76651
  Classification -> best τ=0.515 (val F1=0.3433)
  Directional -> Accuracy: 0.6458, MCC: 0.2673, F1: 0.5405

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59726 | val 0.72321
  Epoch 013 - train 0.58216 | val 0.71699
  Classification -> best τ=0.450 (val F1=0.2364)
  Directional -> Accuracy: 0.4928, MCC: -0.0170, F1: 0.4444

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65860 | val 0.68700
  Epoch 013 - train 0.69011 | val 1.05710
  Classification -> best τ=0.435 (val F1=0.3075)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57415 | val 0.78260
  Epoch 012 - train 0.53858 | val 1.43308
  Classification -> best τ=0.490 (val F1=0.1002)
  Directional -> Accuracy: 0.4211, MCC: -0.2330, F1: 0.5714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60024 | val 1.19681
  Epoch 011 - train 0.59108 | val 1.12881
  Classification -> best τ=0.400 (val F1=0.2522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60045 | val 0.62201
  Epoch 020 - train 0.54592 | val 0.63066
  Epoch 021 - train 0.52088 | val 0.63604
  Classification -> best τ=0.440 (val F1=0.3387)
  Directional -> Accuracy: 0.5333, MCC: 0.0707, F1: 0.4400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56588 | val 0.76535
  Epoch 016 - train 0.60348 | val 0.79623
  Classification -> best τ=0.585 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0487, F1: 0.3030

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60447 | val 0.73282
  Epoch 013 - train 0.61163 | val 0.85256
  Classification -> best τ=0.480 (val F1=0.3050)
  Directional -> Accuracy: 0.5507, MCC: 0.0987, F1: 0.5753

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62497 | val 1.54786
  Epoch 011 - train 0.61795 | val 1.74369
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59944 | val 1.60729
  Epoch 011 - train 0.59924 | val 1.97978
  Classification -> best τ=0.520 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61631 | val 0.98897
  Epoch 011 - train 0.63716 | val 0.75192
  Classification -> best τ=0.440 (val F1=0.1578)
  Directional -> Accuracy: 0.5156, MCC: 0.1672, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61750 | val 0.71344
  Epoch 015 - train 0.58375 | val 0.75230
  Classification -> best τ=0.380 (val F1=0.3525)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58396 | val 0.67798
  Epoch 020 - train 0.47821 | val 0.91284
  Classification -> best τ=0.420 (val F1=0.4078)
  Directional -> Accuracy: 0.5106, MCC: -0.0247, F1: 0.5965

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65132 | val 1.16618
  Epoch 011 - train 0.64264 | val 1.11803
  Classification -> best τ=0.545 (val F1=0.2376)
  Directional -> Accuracy: 0.4615, MCC: -0.0777, F1: 0.4776

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65571 | val 0.68269
  Epoch 020 - train 0.61114 | val 0.87818
  Epoch 022 - train 0.60830 | val 0.89621
  Classification -> best τ=0.855 (val F1=0.3550)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65233 | val 0.85527
  Epoch 012 - train 0.62406 | val 0.75714
  Classification -> best τ=0.520 (val F1=0.1985)
  Directional -> Accuracy: 0.5077, MCC: -0.0336, F1: 0.1579

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55380 | val 0.64920
  Epoch 017 - train 0.45641 | val 0.94413
  Classification -> best τ=0.510 (val F1=0.3851)
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52863 | val 1.08593
  Epoch 011 - train 0.50445 | val 1.25770
  Classification -> best τ=0.525 (val F1=0.4328)
  Directional -> Accuracy: 0.5111, MCC: 0.2029, F1: 0.6207

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60297 | val 0.72556
  Epoch 011 - train 0.58587 | val 0.75105
  Classification -> best τ=0.600 (val F1=0.1578)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62866 | val 0.74675
  Epoch 015 - train 0.59558 | val 0.93796
  Classification -> best τ=0.350 (val F1=0.2892)
  Directional -> Accuracy: 0.5000, MCC: 0.0460, F1: 0.4167

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56576 | val 2.05846
  Epoch 013 - train 0.67959 | val 1.78418
  Classification -> best τ=0.465 (val F1=0.2414)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61626 | val 1.11816
  Epoch 012 - train 0.58856 | val 1.24192
  Classification -> best τ=0.570 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55761 | val 1.02855
  Epoch 015 - train 0.48187 | val 2.22010
  Classification -> best τ=0.365 (val F1=0.2357)
  Directional -> Accuracy: 0.5952, MCC: 0.2071, F1: 0.5854

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51312 | val 0.70234
  Epoch 016 - train 0.41702 | val 0.91333
  Classification -> best τ=0.315 (val F1=0.3957)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60632 | val 0.67119
  Epoch 014 - train 0.58603 | val 0.76532
  Classification -> best τ=0.420 (val F1=0.4243)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62480 | val 0.84702
  Epoch 011 - train 0.65118 | val 0.83566
  Classification -> best τ=0.495 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: 0.0051, F1: 0.0870

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64838 | val 0.74269
  Epoch 012 - train 0.65807 | val 0.92487
  Classification -> best τ=0.300 (val F1=0.3525)
  Directional -> Accuracy: 0.6667, MCC: 0.3013, F1: 0.7500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48951 | val 1.89441
  Epoch 011 - train 0.47198 | val 1.96382
  Classification -> best τ=0.430 (val F1=0.2439)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55075 | val 0.70913
  Epoch 016 - train 0.43613 | val 1.00042
  Classification -> best τ=0.540 (val F1=0.2742)
  Directional -> Accuracy: 0.5536, MCC: 0.0962, F1: 0.4898

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50417 | val 0.92518
  Epoch 011 - train 0.50323 | val 0.93263
  Classification -> best τ=0.475 (val F1=0.0894)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59215 | val 0.80335
  Epoch 011 - train 0.58267 | val 0.83964
  Classification -> best τ=0.555 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63849 | val 0.70953
  Epoch 013 - train 0.65860 | val 0.76177
  Classification -> best τ=0.500 (val F1=0.3031)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54776 | val 0.83578
  Epoch 012 - train 0.46631 | val 0.84582
  Classification -> best τ=0.395 (val F1=0.3873)
  Directional -> Accuracy: 0.5111, MCC: 0.0069, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65888 | val 0.61837
  Epoch 020 - train 0.54646 | val 0.55081
  Epoch 030 - train 0.33578 | val 1.13990
  Classification -> best τ=0.240 (val F1=0.6124)
  Directional -> Accuracy: 0.6190, MCC: 0.2582, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55608 | val 0.75094
  Epoch 013 - train 0.53821 | val 0.69275
  Classification -> best τ=0.630 (val F1=0.5689)
  Directional -> Accuracy: 0.5417, MCC: 0.0436, F1: 0.4211

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62469 | val 0.69447
  Epoch 014 - train 0.59779 | val 0.68656
  Classification -> best τ=0.575 (val F1=0.2132)
  Directional -> Accuracy: 0.4909, MCC: 0.1773, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57839 | val 1.56995
  Epoch 012 - train 0.57170 | val 1.47728
  Classification -> best τ=0.655 (val F1=0.2690)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60506 | val 0.95276
  Epoch 012 - train 0.63372 | val 1.14828
  Classification -> best τ=0.565 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1299, F1: 0.3684

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65737 | val 0.87075
  Epoch 011 - train 0.62821 | val 1.00965
  Classification -> best τ=0.380 (val F1=0.1757)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64982 | val 0.76734

[I 2026-02-20 06:25:37,608] Trial 241 finished with value: 0.2792233968381546 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008434628526315909, 'weight_decay': 1.9698438907787263e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1331178322004416, 'early_stopping_min_delta': 0.002717713117264412}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 018 - train 0.59502 | val 0.69916
  Classification -> best τ=0.495 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2792233968381546
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59335 | val 0.91056
  Epoch 016 - train 0.55947 | val 0.95921
  Classification -> best τ=0.545 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0903, F1: 0.4848

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57716 | val 0.68426
  Epoch 012 - train 0.53395 | val 0.68438
  Classification -> best τ=0.395 (val F1=0.1857)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56047 | val 0.74389
  Epoch 011 - train 0.55255 | val 0.94337
  Classification -> best τ=0.545 (val F1=0.2398)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69798 | val 0.81691
  Epoch 016 - train 0.66456 | val 0.69588
  Classification -> best τ=0.465 (val F1=0.1716)
  Directional -> Accuracy: 0.5676, MCC: 0.1194, F1: 0.6279

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61752 | val 0.68685
  Epoch 017 - train 0.59522 | val 0.90493
  Classification -> best τ=0.460 (val F1=0.4753)
  Directional -> Accuracy: 0.5600, MCC: 0.1442, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56283 | val 0.73620
  Epoch 019 - train 0.48842 | val 0.84824
  Classification -> best τ=0.595 (val F1=0.2739)
  Directional -> Accuracy: 0.6087, MCC: 0.2145, F1: 0.5263

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64514 | val 0.74832
  Epoch 015 - train 0.64155 | val 0.98120
  Classification -> best τ=0.510 (val F1=0.2067)
  Directional -> Accuracy: 0.4118, MCC: -0.0378, F1: 0.5349

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52464 | val 0.87936
  Epoch 012 - train 0.49915 | val 1.36184
  Classification -> best τ=0.375 (val F1=0.2810)
  Directional -> Accuracy: 0.4762, MCC: -0.1217, F1: 0.2667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60144 | val 0.77531
  Epoch 015 - train 0.51800 | val 1.05769
  Classification -> best τ=0.605 (val F1=0.2764)
  Directional -> Accuracy: 0.6875, MCC: 0.3637, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56930 | val 0.85537
  Epoch 015 - train 0.52197 | val 1.01409
  Classification -> best τ=0.460 (val F1=0.1424)
  Directional -> Accuracy: 0.3768, MCC: -0.1919, F1: 0.4819

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59524 | val 0.93448
  Epoch 016 - train 0.53055 | val 1.54432
  Classification -> best τ=0.390 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55170 | val 1.15592
  Epoch 012 - train 0.54533 | val 1.19846
  Classification -> best τ=0.550 (val F1=0.2536)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59539 | val 0.70564
  Epoch 011 - train 0.58456 | val 0.74063
  Classification -> best τ=0.465 (val F1=0.1878)
  Directional -> Accuracy: 0.4762, MCC: 0.0663, F1: 0.6207

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64103 | val 0.62988
  Epoch 011 - train 0.61468 | val 0.63847
  Classification -> best τ=0.340 (val F1=0.3669)
  Directional -> Accuracy: 0.5667, MCC: 0.1576, F1: 0.6579

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58404 | val 0.73326
  Epoch 014 - train 0.51919 | val 1.06007
  Classification -> best τ=0.505 (val F1=0.1344)
  Directional -> Accuracy: 0.4510, MCC: -0.0487, F1: 0.5625

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61373 | val 0.72619
  Epoch 013 - train 0.62423 | val 0.93651
  Classification -> best τ=0.460 (val F1=0.3589)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60281 | val 1.44726
  Epoch 011 - train 0.59191 | val 1.56091
  Classification -> best τ=0.630 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61855 | val 1.32661
  Epoch 015 - train 0.57766 | val 1.36136
  Classification -> best τ=0.590 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67566 | val 0.82090
  Epoch 016 - train 0.64188 | val 0.78544
  Classification -> best τ=0.245 (val F1=0.3421)
  Directional -> Accuracy: 0.5312, MCC: 0.1396, F1: 0.4643

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60835 | val 0.78793
  Epoch 011 - train 0.60658 | val 0.95001
  Classification -> best τ=0.495 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59234 | val 0.68152
  Epoch 020 - train 0.47558 | val 1.15532
  Epoch 021 - train 0.49311 | val 0.83901
  Classification -> best τ=0.395 (val F1=0.3693)
  Directional -> Accuracy: 0.4468, MCC: -0.0240, F1: 0.4091

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64065 | val 0.93171
  Epoch 011 - train 0.63489 | val 0.97228
  Classification -> best τ=0.675 (val F1=0.1925)
  Directional -> Accuracy: 0.4308, MCC: -0.1660, F1: 0.1778

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59807 | val 0.74165
  Epoch 015 - train 0.55934 | val 0.83141
  Classification -> best τ=0.470 (val F1=0.2896)
  Directional -> Accuracy: 0.5263, MCC: 0.0255, F1: 0.5970

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61215 | val 0.91089
  Epoch 012 - train 0.59432 | val 1.14178
  Classification -> best τ=0.540 (val F1=0.1415)
  Directional -> Accuracy: 0.5077, MCC: -0.0336, F1: 0.1579

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58243 | val 0.75156
  Epoch 018 - train 0.51556 | val 0.85779
  Classification -> best τ=0.480 (val F1=0.4973)
  Directional -> Accuracy: 0.4545, MCC: -0.0319, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53702 | val 1.13766
  Epoch 012 - train 0.50418 | val 1.88150
  Classification -> best τ=0.585 (val F1=0.3039)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59658 | val 0.69292
  Epoch 011 - train 0.59206 | val 0.71339
  Classification -> best τ=0.550 (val F1=0.0807)
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58074 | val 0.99596
  Epoch 013 - train 0.60056 | val 0.88069
  Classification -> best τ=0.595 (val F1=0.2478)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61499 | val 0.77446
  Epoch 017 - train 0.49754 | val 1.70751
  Classification -> best τ=0.560 (val F1=0.4114)
  Directional -> Accuracy: 0.5000, MCC: -0.0439, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64814 | val 0.82907
  Epoch 015 - train 0.58062 | val 0.85429
  Classification -> best τ=0.615 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54944 | val 0.69813
  Epoch 020 - train 0.52855 | val 1.54778
  Classification -> best τ=0.385 (val F1=0.2357)
  Directional -> Accuracy: 0.4524, MCC: -0.0677, F1: 0.3784

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57449 | val 0.66236
  Epoch 014 - train 0.54297 | val 0.79201
  Classification -> best τ=0.335 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59936 | val 0.76207
  Epoch 014 - train 0.55824 | val 1.35960
  Classification -> best τ=0.360 (val F1=0.3007)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58318 | val 1.27345
  Epoch 012 - train 0.52843 | val 1.55979
  Classification -> best τ=0.465 (val F1=0.2057)
  Directional -> Accuracy: 0.4884, MCC: -0.0452, F1: 0.2667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63255 | val 0.76740
  Epoch 014 - train 0.55816 | val 0.91284
  Classification -> best τ=0.300 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.1084, F1: 0.6585

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56582 | val 1.02643
  Epoch 011 - train 0.60254 | val 1.05133
  Classification -> best τ=0.545 (val F1=0.2292)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53775 | val 0.99494
  Epoch 011 - train 0.56798 | val 1.10360
  Classification -> best τ=0.385 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0555, F1: 0.5574

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64466 | val 0.76132
  Epoch 017 - train 0.55513 | val 0.85528
  Classification -> best τ=0.495 (val F1=0.2268)
  Directional -> Accuracy: 0.4565, MCC: 0.0917, F1: 0.2857

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56565 | val 0.76006
  Epoch 015 - train 0.51023 | val 0.93321
  Classification -> best τ=0.540 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64402 | val 0.67591
  Epoch 018 - train 0.60179 | val 0.84347
  Classification -> best τ=0.190 (val F1=0.2766)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54172 | val 0.75831
  Epoch 012 - train 0.50702 | val 0.82903
  Classification -> best τ=0.390 (val F1=0.3873)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61613 | val 0.72574
  Epoch 016 - train 0.49475 | val 0.81445
  Classification -> best τ=0.375 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60600 | val 0.71892
  Epoch 012 - train 0.52622 | val 0.64351
  Classification -> best τ=0.605 (val F1=0.6058)
  Directional -> Accuracy: 0.3750, MCC: -0.0976, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59924 | val 0.68809
  Epoch 011 - train 0.60777 | val 0.73794
  Classification -> best τ=0.500 (val F1=0.2228)
  Directional -> Accuracy: 0.4545, MCC: -0.2390, F1: 0.6154

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58590 | val 1.46708
  Epoch 011 - train 0.57766 | val 1.51050
  Classification -> best τ=0.505 (val F1=0.3585)
  Directional -> Accuracy: 0.4821, MCC: -0.0206, F1: 0.5797

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60001 | val 0.78177
  Epoch 016 - train 0.57085 | val 0.73553
  Classification -> best τ=0.595 (val F1=0.2105)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67218 | val 0.75267
  Epoch 011 - train 0.63702 | val 0.80708
  Classification -> best τ=0.430 (val F1=0.1053)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59766 | val 0.82460
  Epoch 012 - train 0.56796 | val 0.97199

[I 2026-02-20 06:26:38,020] Trial 242 finished with value: 0.2775488255619223 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008535792329742786, 'weight_decay': 1.8222692100315222e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1019477552628043, 'early_stopping_min_delta': 0.002780561855495055}. Best is trial 180 with value: 0.30107335520239253.

  Classification -> best τ=0.480 (val F1=0.1489)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2775488255619223
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57875 | val 0.73621
  Epoch 014 - train 0.58863 | val 0.68499
  Classification -> best τ=0.540 (val F1=0.1430)
  Directional -> Accuracy: 0.6053, MCC: 0.1938, F1: 0.5312

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62141 | val 0.67235
  Epoch 019 - train 0.49877 | val 0.68642
  Classification -> best τ=0.455 (val F1=0.2545)
  Directional -> Accuracy: 0.4444, MCC: -0.0763, F1: 0.4186

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58467 | val 0.77503
  Epoch 014 - train 0.51595 | val 0.76056
  Classification -> best τ=0.545 (val F1=0.3114)
  Directional -> Accuracy: 0.5870, MCC: 0.2143, F1: 0.4865

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65909 | val 0.91450
  Epoch 012 - train 0.62926 | val 1.21045
  Classification -> best τ=0.470 (val F1=0.1725)
  Directional -> Accuracy: 0.4595, MCC: -0.0495, F1: 0.3333

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56136 | val 0.90271
  Epoch 013 - train 0.58453 | val 1.03982
  Classification -> best τ=0.520 (val F1=0.4782)
  Directional -> Accuracy: 0.5800, MCC: 0.1662, F1: 0.6769

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59417 | val 0.71359
  Epoch 013 - train 0.54153 | val 0.71148
  Classification -> best τ=0.490 (val F1=0.1113)
  Directional -> Accuracy: 0.4130, MCC: -0.2002, F1: 0.5574

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62681 | val 0.74573
  Epoch 015 - train 0.60825 | val 0.79423
  Classification -> best τ=0.515 (val F1=0.3010)
  Directional -> Accuracy: 0.5000, MCC: 0.1034, F1: 0.5526

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50868 | val 0.74539
  Epoch 012 - train 0.50788 | val 0.88231
  Classification -> best τ=0.430 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57801 | val 0.98279
  Epoch 012 - train 0.55492 | val 0.91844
  Classification -> best τ=0.540 (val F1=0.2233)
  Directional -> Accuracy: 0.6250, MCC: 0.2208, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58995 | val 0.81733
  Epoch 014 - train 0.54846 | val 0.84139
  Classification -> best τ=0.520 (val F1=0.2364)
  Directional -> Accuracy: 0.4058, MCC: -0.1153, F1: 0.5176

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61828 | val 1.08274
  Epoch 012 - train 0.64162 | val 1.72955
  Classification -> best τ=0.440 (val F1=0.5319)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55788 | val 0.75906
  Epoch 014 - train 0.55083 | val 1.55080
  Classification -> best τ=0.525 (val F1=0.1512)
  Directional -> Accuracy: 0.4561, MCC: -0.1806, F1: 0.6173

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57269 | val 1.18278
  Epoch 012 - train 0.56345 | val 1.31013
  Classification -> best τ=0.470 (val F1=0.3070)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60052 | val 0.89436
  Epoch 011 - train 0.59870 | val 1.25604
  Classification -> best τ=0.345 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1558, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57516 | val 0.82220
  Epoch 013 - train 0.54402 | val 0.93569
  Classification -> best τ=0.545 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60474 | val 0.87377
  Epoch 013 - train 0.56566 | val 1.20197
  Classification -> best τ=0.355 (val F1=0.2795)
  Directional -> Accuracy: 0.6377, MCC: 0.3302, F1: 0.7423

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60866 | val 1.19557
  Epoch 012 - train 0.56569 | val 1.57299
  Classification -> best τ=0.565 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60937 | val 1.16018
  Epoch 014 - train 0.57263 | val 1.35545
  Classification -> best τ=0.330 (val F1=0.2166)
  Directional -> Accuracy: 0.6000, MCC: 0.1400, F1: 0.6875

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65576 | val 0.77676
  Epoch 013 - train 0.61045 | val 1.00787
  Classification -> best τ=0.415 (val F1=0.3140)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65393 | val 0.75919
  Epoch 016 - train 0.57183 | val 1.09013
  Classification -> best τ=0.465 (val F1=0.4039)
  Directional -> Accuracy: 0.4865, MCC: 0.1844, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61907 | val 0.72041
  Epoch 018 - train 0.48832 | val 0.86161
  Classification -> best τ=0.530 (val F1=0.3262)
  Directional -> Accuracy: 0.5106, MCC: 0.0373, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70601 | val 0.86846
  Epoch 015 - train 0.58968 | val 0.80936
  Classification -> best τ=0.405 (val F1=0.0566)
  Directional -> Accuracy: 0.5077, MCC: 0.0081, F1: 0.6190

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60186 | val 0.79720
  Epoch 011 - train 0.57687 | val 0.73581
  Classification -> best τ=0.480 (val F1=0.2644)
  Directional -> Accuracy: 0.5614, MCC: 0.0340, F1: 0.7059

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62019 | val 0.86865
  Epoch 011 - train 0.62020 | val 0.92045
  Classification -> best τ=0.525 (val F1=0.0171)
  Directional -> Accuracy: 0.4462, MCC: -0.0991, F1: 0.5610

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58868 | val 0.90821
  Epoch 013 - train 0.55295 | val 0.71975
  Classification -> best τ=0.555 (val F1=0.3786)
  Directional -> Accuracy: 0.6000, MCC: 0.2820, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59757 | val 1.14843
  Epoch 011 - train 0.57682 | val 1.27908
  Classification -> best τ=0.515 (val F1=0.1310)
  Directional -> Accuracy: 0.4889, MCC: 0.0020, F1: 0.4889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61922 | val 0.69380
  Epoch 015 - train 0.61981 | val 0.69582
  Classification -> best τ=0.615 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64484 | val 0.92908
  Epoch 011 - train 0.60161 | val 0.89522
  Classification -> best τ=0.460 (val F1=0.2011)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59963 | val 0.83176
  Epoch 013 - train 0.56786 | val 0.78796
  Classification -> best τ=0.565 (val F1=0.2957)
  Directional -> Accuracy: 0.4000, MCC: -0.2010, F1: 0.4286

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70686 | val 1.39939
  Epoch 015 - train 0.66930 | val 0.92520
  Classification -> best τ=0.695 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55226 | val 0.96340
  Epoch 012 - train 0.53273 | val 1.12811
  Classification -> best τ=0.470 (val F1=0.0806)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51800 | val 0.84995
  Epoch 015 - train 0.42437 | val 1.20210
  Classification -> best τ=0.730 (val F1=0.2969)
  Directional -> Accuracy: 0.5102, MCC: -0.1358, F1: 0.6757

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65346 | val 0.68806
  Epoch 017 - train 0.58825 | val 0.91203
  Classification -> best τ=0.390 (val F1=0.4243)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58224 | val 1.09393
  Epoch 011 - train 0.56636 | val 1.11650
  Classification -> best τ=0.530 (val F1=0.2631)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61782 | val 1.02985
  Epoch 013 - train 0.61806 | val 0.86599
  Classification -> best τ=0.370 (val F1=0.3855)
  Directional -> Accuracy: 0.5909, MCC: 0.1253, F1: 0.6897

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50214 | val 0.85096
  Epoch 013 - train 0.45401 | val 1.11010
  Classification -> best τ=0.565 (val F1=0.3260)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56717 | val 0.91721
  Epoch 012 - train 0.54771 | val 0.91510
  Classification -> best τ=0.345 (val F1=0.2450)
  Directional -> Accuracy: 0.4464, MCC: -0.0925, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48645 | val 1.04113
  Epoch 011 - train 0.49240 | val 0.90960
  Classification -> best τ=0.550 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59123 | val 0.65634
  Epoch 020 - train 0.52703 | val 0.63659
  Epoch 021 - train 0.49037 | val 0.63609
  Classification -> best τ=0.310 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57815 | val 0.88988
  Epoch 013 - train 0.55044 | val 0.97392
  Classification -> best τ=0.360 (val F1=0.3533)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58971 | val 0.74186
  Epoch 013 - train 0.52330 | val 0.84940
  Classification -> best τ=0.435 (val F1=0.1942)
  Directional -> Accuracy: 0.5333, MCC: 0.1493, F1: 0.2222

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58759 | val 0.69741
  Epoch 020 - train 0.49203 | val 0.82098
  Epoch 027 - train 0.36517 | val 0.68658
  Classification -> best τ=0.365 (val F1=0.5601)
  Directional -> Accuracy: 0.5952, MCC: 0.1407, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62165 | val 0.76990
  Epoch 015 - train 0.55612 | val 0.60531
  Classification -> best τ=0.595 (val F1=0.6290)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57913 | val 0.69850
  Epoch 011 - train 0.59740 | val 0.69854
  Classification -> best τ=0.645 (val F1=0.1474)
  Directional -> Accuracy: 0.4000, MCC: -0.1796, F1: 0.2979

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58649 | val 1.39994
  Epoch 012 - train 0.54301 | val 1.94315
  Classification -> best τ=0.550 (val F1=0.2075)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63184 | val 0.72225
  Epoch 012 - train 0.58481 | val 0.72740
  Classification -> best τ=0.510 (val F1=0.1801)
  Directional -> Accuracy: 0.6038, MCC: 0.2080, F1: 0.6038

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57235 | val 0.97417
  Epoch 015 - train 0.53623 | val 0.76514
  Classification -> best τ=0.565 (val F1=0.1357)
  Directional -> Accuracy: 0.4364, MCC: -0.1605, F1: 0.5373

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65052 | val 0.78651

[I 2026-02-20 06:27:35,372] Trial 243 finished with value: 0.2696951633177118 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007205417997012509, 'weight_decay': 1.2624165226894107e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1408128877507888, 'early_stopping_min_delta': 0.0031120470364732608}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.59208 | val 0.89777
  Classification -> best τ=0.455 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2696951633177118
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61202 | val 0.74982
  Epoch 016 - train 0.55012 | val 0.90915
  Classification -> best τ=0.605 (val F1=0.2036)
  Directional -> Accuracy: 0.6053, MCC: 0.1910, F1: 0.3478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59855 | val 0.66907
  Epoch 020 - train 0.45617 | val 0.76771
  Classification -> best τ=0.390 (val F1=0.3989)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57383 | val 0.67959
  Epoch 020 - train 0.42149 | val 1.02593
  Classification -> best τ=0.475 (val F1=0.3894)
  Directional -> Accuracy: 0.6087, MCC: 0.2179, F1: 0.6786

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62008 | val 0.71002
  Epoch 015 - train 0.59418 | val 1.05411
  Classification -> best τ=0.610 (val F1=0.2241)
  Directional -> Accuracy: 0.4865, MCC: 0.1005, F1: 0.1364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57679 | val 0.89999
  Epoch 015 - train 0.57453 | val 0.81368
  Classification -> best τ=0.500 (val F1=0.4556)
  Directional -> Accuracy: 0.5200, MCC: 0.0642, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68950 | val 0.71916
  Epoch 011 - train 0.66055 | val 0.71941
  Classification -> best τ=0.580 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61527 | val 0.99589
  Epoch 014 - train 0.60722 | val 1.43819
  Classification -> best τ=0.525 (val F1=0.1640)
  Directional -> Accuracy: 0.5000, MCC: 0.0443, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53125 | val 0.77833
  Epoch 012 - train 0.56864 | val 0.85689
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57353 | val 0.88489
  Epoch 012 - train 0.53407 | val 0.88372
  Classification -> best τ=0.400 (val F1=0.2443)
  Directional -> Accuracy: 0.4375, MCC: -0.0263, F1: 0.5970

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57623 | val 0.80122
  Epoch 013 - train 0.60551 | val 1.04760
  Classification -> best τ=0.500 (val F1=0.1424)
  Directional -> Accuracy: 0.5072, MCC: -0.0112, F1: 0.4138

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64629 | val 1.08665
  Epoch 013 - train 0.62567 | val 0.91288
  Classification -> best τ=0.375 (val F1=0.1428)
  Directional -> Accuracy: 0.4694, MCC: 0.0594, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55138 | val 1.02025
  Epoch 012 - train 0.57725 | val 1.39900
  Classification -> best τ=0.575 (val F1=0.2157)
  Directional -> Accuracy: 0.4211, MCC: -0.2607, F1: 0.5823

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58838 | val 1.11400
  Epoch 011 - train 0.58808 | val 1.18418
  Classification -> best τ=0.470 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61839 | val 0.84722
  Epoch 013 - train 0.61103 | val 0.68171
  Classification -> best τ=0.335 (val F1=0.3026)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.6364

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56522 | val 0.88508
  Epoch 011 - train 0.53558 | val 1.08012
  Classification -> best τ=0.485 (val F1=0.0333)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61918 | val 1.59086
  Epoch 013 - train 0.51383 | val 1.66716
  Classification -> best τ=0.710 (val F1=0.3492)
  Directional -> Accuracy: 0.5072, MCC: 0.0765, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62374 | val 1.04538
  Epoch 011 - train 0.58855 | val 1.28545
  Classification -> best τ=0.440 (val F1=0.0103)
  Directional -> Accuracy: 0.5862, MCC: -0.0322, F1: 0.7273

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61569 | val 1.27571
  Epoch 012 - train 0.61201 | val 1.48746
  Classification -> best τ=0.465 (val F1=0.1348)
  Directional -> Accuracy: 0.5333, MCC: 0.0653, F1: 0.5783

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60792 | val 1.23016
  Epoch 012 - train 0.62360 | val 1.51818
  Classification -> best τ=0.425 (val F1=0.2843)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63956 | val 0.69395
  Epoch 016 - train 0.64390 | val 0.83146
  Classification -> best τ=0.495 (val F1=0.2588)
  Directional -> Accuracy: 0.3919, MCC: -0.2094, F1: 0.4000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61864 | val 0.74891
  Epoch 012 - train 0.58425 | val 0.73843
  Classification -> best τ=0.475 (val F1=0.3678)
  Directional -> Accuracy: 0.5319, MCC: 0.2722, F1: 0.4211

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64598 | val 0.87298
  Epoch 012 - train 0.62943 | val 1.29196
  Classification -> best τ=0.695 (val F1=0.2183)
  Directional -> Accuracy: 0.5231, MCC: 0.0879, F1: 0.2439

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64725 | val 0.67124
  Epoch 016 - train 0.65936 | val 0.82701
  Classification -> best τ=0.585 (val F1=0.2981)
  Directional -> Accuracy: 0.5614, MCC: 0.0773, F1: 0.6575

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66364 | val 0.73490
  Epoch 014 - train 0.61021 | val 0.72887
  Classification -> best τ=0.435 (val F1=0.1478)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55719 | val 0.73032
  Epoch 015 - train 0.56967 | val 1.01054
  Classification -> best τ=0.560 (val F1=0.5684)
  Directional -> Accuracy: 0.5091, MCC: 0.0199, F1: 0.5263

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52900 | val 1.98391
  Epoch 011 - train 0.50872 | val 1.64362
  Classification -> best τ=0.480 (val F1=0.0155)
  Directional -> Accuracy: 0.4889, MCC: 0.1591, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60855 | val 0.71675
  Epoch 012 - train 0.56448 | val 0.77456
  Classification -> best τ=0.540 (val F1=0.0574)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67382 | val 0.66455
  Epoch 020 - train 0.62337 | val 0.73873
  Classification -> best τ=0.415 (val F1=0.2386)
  Directional -> Accuracy: 0.5357, MCC: 0.2812, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64595 | val 0.68818
  Epoch 020 - train 0.47772 | val 0.80676
  Epoch 021 - train 0.44832 | val 1.04657
  Classification -> best τ=0.515 (val F1=0.4382)
  Directional -> Accuracy: 0.5500, MCC: 0.0580, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64596 | val 0.71936
  Epoch 018 - train 0.59599 | val 0.98479
  Classification -> best τ=0.625 (val F1=0.4110)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54563 | val 0.69379
  Epoch 014 - train 0.47822 | val 0.68921
  Classification -> best τ=0.545 (val F1=0.3158)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56112 | val 0.81070
  Epoch 013 - train 0.50299 | val 1.22784
  Classification -> best τ=0.400 (val F1=0.3647)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63395 | val 0.68265
  Epoch 017 - train 0.66468 | val 0.65827
  Classification -> best τ=0.165 (val F1=0.2888)
  Directional -> Accuracy: 0.5278, MCC: -0.0674, F1: 0.6792

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64800 | val 0.75719
  Epoch 012 - train 0.60916 | val 0.96066
  Classification -> best τ=0.480 (val F1=0.2057)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61221 | val 0.83550
  Epoch 013 - train 0.61779 | val 0.77135
  Classification -> best τ=0.595 (val F1=0.2228)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56890 | val 0.75595
  Epoch 013 - train 0.52901 | val 0.95716
  Classification -> best τ=0.450 (val F1=0.3218)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55383 | val 0.86160
  Epoch 011 - train 0.54176 | val 0.95537
  Classification -> best τ=0.395 (val F1=0.3145)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55852 | val 1.19845
  Epoch 011 - train 0.53778 | val 1.20381
  Classification -> best τ=0.450 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58322 | val 0.65362
  Epoch 020 - train 0.43571 | val 0.69147
  Epoch 022 - train 0.42176 | val 0.73541
  Classification -> best τ=0.365 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56986 | val 0.76345
  Epoch 011 - train 0.53443 | val 0.86884
  Classification -> best τ=0.465 (val F1=0.3426)
  Directional -> Accuracy: 0.4595, MCC: -0.0965, F1: 0.6078

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56454 | val 0.76313
  Epoch 015 - train 0.47646 | val 1.01503
  Classification -> best τ=0.480 (val F1=0.3287)
  Directional -> Accuracy: 0.5556, MCC: 0.1129, F1: 0.5455

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58178 | val 0.69673
  Epoch 020 - train 0.51179 | val 0.64172
  Epoch 030 - train 0.32623 | val 0.60920
  Epoch 038 - train 0.33331 | val 0.76162
  Classification -> best τ=0.530 (val F1=0.6667)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56461 | val 0.69514
  Epoch 011 - train 0.55858 | val 0.64999
  Classification -> best τ=0.580 (val F1=0.4682)
  Directional -> Accuracy: 0.5417, MCC: 0.0648, F1: 0.4500

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58743 | val 0.72721
  Epoch 011 - train 0.57474 | val 0.71894
  Classification -> best τ=0.680 (val F1=0.1757)
  Directional -> Accuracy: 0.5091, MCC: 0.1617, F1: 0.2286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57507 | val 1.10685
  Epoch 016 - train 0.59647 | val 0.99355
  Classification -> best τ=0.775 (val F1=0.2649)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62950 | val 0.87951
  Epoch 016 - train 0.55691 | val 1.75306
  Classification -> best τ=0.710 (val F1=0.2064)
  Directional -> Accuracy: 0.5283, MCC: 0.0662, F1: 0.4444

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61738 | val 0.86531
  Epoch 011 - train 0.59111 | val 1.00357
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62731 | val 0.80910
  Epoch 011 - train 0.66665 | val 0.73456
  Classification -> best τ=0.475 (val F1=0.1489)
  Directional -> Accuracy: 0.4167, MCC: -0.1823, F1: 0.3137

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26328841503963324

[I 2026-02-20 06:28:38,555] Trial 244 finished with value: 0.26328841503963324 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009718742875149077, 'weight_decay': 1.6816150087694373e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.1925195789700065, 'early_stopping_min_delta': 0.002362835739087115}. Best is trial 180 with value: 0.30107335520239253.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60786 | val 0.67645
  Epoch 020 - train 0.53855 | val 0.72343
  Epoch 030 - train 0.42427 | val 0.76274
  Epoch 031 - train 0.40318 | val 0.78237
  Classification -> best τ=0.530 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: 0.0917, F1: 0.5934

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59879 | val 0.69039
  Epoch 020 - train 0.46691 | val 0.82971
  Epoch 024 - train 0.37865 | val 0.75349
  Classification -> best τ=0.470 (val F1=0.3006)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60069 | val 0.91478
  Epoch 020 - train 0.45598 | val 1.50589
  Epoch 024 - train 0.39420 | val 1.92803
  Classification -> best τ=0.570 (val F1=0.3114)
  Directional -> Accuracy: 0.5652, MCC: 0.1241, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63286 | val 0.78943
  Epoch 020 - train 0.49559 | val 1.94932
  Epoch 022 - train 0.50032 | val 1.69248
  Classification -> best τ=0.470 (val F1=0.1441)
  Directional -> Accuracy: 0.5541, MCC: 0.1042, F1: 0.5823

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59822 | val 0.96444
  Epoch 020 - train 0.46792 | val 1.66726
  Epoch 026 - train 0.33202 | val 1.53848
  Classification -> best τ=0.575 (val F1=0.4493)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61474 | val 0.76718
  Epoch 020 - train 0.51292 | val 1.49245
  Epoch 021 - train 0.52202 | val 1.64887
  Classification -> best τ=0.535 (val F1=0.3222)
  Directional -> Accuracy: 0.5000, MCC: 0.0766, F1: 0.6462

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64791 | val 0.81917
  Epoch 020 - train 0.51075 | val 2.05692
  Epoch 022 - train 0.49882 | val 2.14286
  Classification -> best τ=0.525 (val F1=0.2827)
  Directional -> Accuracy: 0.5147, MCC: 0.0819, F1: 0.5217

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52869 | val 0.79456
  Epoch 020 - train 0.42315 | val 1.27738
  Epoch 022 - train 0.38935 | val 1.43406
  Classification -> best τ=0.360 (val F1=0.2453)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58612 | val 0.79719
  Epoch 020 - train 0.44054 | val 0.98955
  Epoch 021 - train 0.47146 | val 0.90235
  Classification -> best τ=0.510 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.2322, F1: 0.6296

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58002 | val 0.69786
  Epoch 020 - train 0.41633 | val 1.21042
  Epoch 022 - train 0.40900 | val 1.81453
  Classification -> best τ=0.540 (val F1=0.1668)
  Directional -> Accuracy: 0.5072, MCC: -0.0310, F1: 0.3704

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63551 | val 0.87141
  Epoch 020 - train 0.50720 | val 1.85472
  Epoch 024 - train 0.47133 | val 2.13659
  Classification -> best τ=0.410 (val F1=0.4415)
  Directional -> Accuracy: 0.4694, MCC: 0.0594, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55234 | val 1.29554
  Epoch 020 - train 0.32084 | val 2.43666
  Epoch 025 - train 0.26301 | val 3.40292
  Classification -> best τ=0.525 (val F1=0.2157)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57186 | val 1.53689
  Epoch 020 - train 0.43173 | val 2.25468
  Epoch 021 - train 0.42279 | val 2.26226
  Classification -> best τ=0.380 (val F1=0.2522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61284 | val 0.74611
  Epoch 020 - train 0.46220 | val 0.93083
  Epoch 021 - train 0.44390 | val 0.96318
  Classification -> best τ=0.450 (val F1=0.3281)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5161

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57350 | val 0.80475
  Epoch 020 - train 0.46363 | val 1.01839
  Epoch 023 - train 0.43038 | val 1.23390
  Classification -> best τ=0.480 (val F1=0.2078)
  Directional -> Accuracy: 0.5686, MCC: 0.0965, F1: 0.2667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63713 | val 0.70187
  Epoch 020 - train 0.53308 | val 1.00199
  Epoch 024 - train 0.45478 | val 0.97359
  Classification -> best τ=0.530 (val F1=0.4213)
  Directional -> Accuracy: 0.5072, MCC: 0.0411, F1: 0.4333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61746 | val 0.79478
  Epoch 020 - train 0.48789 | val 1.09996
  Epoch 021 - train 0.47542 | val 1.11013
  Classification -> best τ=0.485 (val F1=0.2135)
  Directional -> Accuracy: 0.5517, MCC: -0.1066, F1: 0.6977

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64794 | val 1.04195
  Epoch 020 - train 0.51896 | val 1.57195
  Epoch 022 - train 0.50611 | val 1.76326
  Classification -> best τ=0.575 (val F1=0.1031)
  Directional -> Accuracy: 0.4133, MCC: -0.0876, F1: 0.3125

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68713 | val 1.00048
  Epoch 020 - train 0.45854 | val 1.42550
  Epoch 022 - train 0.49721 | val 1.18666
  Classification -> best τ=0.375 (val F1=0.2843)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63536 | val 0.73660
  Epoch 020 - train 0.51042 | val 0.84739
  Epoch 022 - train 0.47726 | val 0.95374
  Classification -> best τ=0.630 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58557 | val 0.68944
  Epoch 020 - train 0.44041 | val 0.77784
  Epoch 030 - train 0.23285 | val 0.86043
  Epoch 035 - train 0.16166 | val 0.84133
  Classification -> best τ=0.460 (val F1=0.3458)
  Directional -> Accuracy: 0.4468, MCC: 0.1299, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61404 | val 1.11775
  Epoch 020 - train 0.53611 | val 1.44543
  Epoch 021 - train 0.52659 | val 1.14826
  Classification -> best τ=0.500 (val F1=0.1650)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63143 | val 0.76059
  Epoch 020 - train 0.52559 | val 0.93056
  Epoch 023 - train 0.49247 | val 1.00669
  Classification -> best τ=0.635 (val F1=0.3276)
  Directional -> Accuracy: 0.4561, MCC: -0.0051, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60590 | val 1.10550
  Epoch 020 - train 0.50152 | val 1.05290
  Epoch 022 - train 0.45447 | val 1.28729
  Classification -> best τ=0.590 (val F1=0.2451)
  Directional -> Accuracy: 0.4462, MCC: -0.1694, F1: 0.1818

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58615 | val 0.71466
  Epoch 020 - train 0.47021 | val 0.95632
  Epoch 027 - train 0.36341 | val 1.04725
  Classification -> best τ=0.455 (val F1=0.4524)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55667 | val 0.92664
  Epoch 020 - train 0.42537 | val 1.99554
  Epoch 021 - train 0.41136 | val 2.10303
  Classification -> best τ=0.560 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.0636, F1: 0.4118

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63742 | val 0.71508
  Epoch 020 - train 0.49297 | val 0.70051
  Epoch 027 - train 0.44268 | val 0.85534
  Classification -> best τ=0.560 (val F1=0.1487)
  Directional -> Accuracy: 0.5476, MCC: 0.1105, F1: 0.5581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63883 | val 0.73578
  Epoch 020 - train 0.56854 | val 0.84439
  Epoch 023 - train 0.53130 | val 0.90333
  Classification -> best τ=0.360 (val F1=0.2804)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63819 | val 0.86291
  Epoch 020 - train 0.43773 | val 1.87214
  Epoch 022 - train 0.42240 | val 2.04019
  Classification -> best τ=0.515 (val F1=0.4114)
  Directional -> Accuracy: 0.5250, MCC: 0.0661, F1: 0.5128

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63310 | val 0.97371
  Epoch 020 - train 0.47145 | val 0.77956
  Epoch 021 - train 0.47510 | val 0.77907
  Classification -> best τ=0.575 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.1489, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63062 | val 0.95297
  Epoch 020 - train 0.43852 | val 1.38299
  Epoch 022 - train 0.45944 | val 1.42011
  Classification -> best τ=0.435 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56929 | val 0.68088
  Epoch 020 - train 0.31983 | val 1.42924
  Epoch 025 - train 0.27889 | val 1.77725
  Classification -> best τ=0.410 (val F1=0.3232)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66563 | val 0.64356
  Epoch 020 - train 0.63243 | val 0.70973
  Epoch 030 - train 0.52078 | val 1.05390
  Classification -> best τ=0.320 (val F1=0.3366)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62061 | val 0.79911
  Epoch 020 - train 0.52606 | val 0.78414
  Epoch 021 - train 0.52723 | val 0.99716
  Classification -> best τ=0.510 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62249 | val 0.81378
  Epoch 020 - train 0.48922 | val 1.11930
  Epoch 023 - train 0.47037 | val 1.34243
  Classification -> best τ=0.340 (val F1=0.3342)
  Directional -> Accuracy: 0.5758, MCC: 0.1236, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55722 | val 1.02776
  Epoch 020 - train 0.43276 | val 1.44978
  Epoch 021 - train 0.41947 | val 1.74688
  Classification -> best τ=0.425 (val F1=0.2067)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55360 | val 0.77781
  Epoch 020 - train 0.38650 | val 1.06565
  Epoch 022 - train 0.35103 | val 1.14074
  Classification -> best τ=0.425 (val F1=0.2110)
  Directional -> Accuracy: 0.4464, MCC: -0.0891, F1: 0.5079

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59396 | val 1.40049
  Epoch 020 - train 0.35295 | val 2.20596
  Epoch 021 - train 0.33157 | val 2.31661
  Classification -> best τ=0.390 (val F1=0.1195)
  Directional -> Accuracy: 0.5435, MCC: -0.0318, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58964 | val 0.68178
  Epoch 020 - train 0.39680 | val 0.74347
  Epoch 030 - train 0.23692 | val 0.83735
  Epoch 033 - train 0.17172 | val 0.84102
  Classification -> best τ=0.330 (val F1=0.4644)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59019 | val 0.81046
  Epoch 020 - train 0.45465 | val 1.20793
  Epoch 023 - train 0.40586 | val 1.35332
  Classification -> best τ=0.385 (val F1=0.2706)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57655 | val 0.71581
  Epoch 020 - train 0.41476 | val 0.86857
  Epoch 023 - train 0.37845 | val 0.92431
  Classification -> best τ=0.490 (val F1=0.3500)
  Directional -> Accuracy: 0.6000, MCC: 0.2257, F1: 0.6897

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59956 | val 0.61640
  Epoch 020 - train 0.49123 | val 0.67037
  Epoch 030 - train 0.35467 | val 0.53831
  Epoch 040 - train 0.26231 | val 0.59465
  Epoch 050 - train 0.10358 | val 1.51408
  Classification -> best τ=0.755 (val F1=0.6651)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53820 | val 0.68863
  Epoch 020 - train 0.38652 | val 0.85549
  Epoch 025 - train 0.35126 | val 0.92779
  Classification -> best τ=0.455 (val F1=0.4682)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61313 | val 0.71539
  Epoch 020 - train 0.47670 | val 0.72433
  Epoch 021 - train 0.45525 | val 0.75800
  Classification -> best τ=0.585 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55661 | val 1.26603
  Epoch 020 - train 0.47488 | val 2.34637
  Epoch 021 - train 0.46092 | val 2.52738
  Classification -> best τ=0.565 (val F1=0.2669)
  Directional -> Accuracy: 0.5357, MCC: 0.1486, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66226 | val 0.72608
  Epoch 020 - train 0.49566 | val 0.93625
  Epoch 024 - train 0.46584 | val 1.07878
  Classification -> best τ=0.600 (val F1=0.2482)
  Directional -> Accuracy: 0.5472, MCC: 0.1004, F1: 0.6471

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61749 | val 0.74886
  Epoch 020 - train 0.50699 | val 0.88265
  Epoch 024 - train 0.45018 | val 0.94630
  Classification -> best τ=0.505 (val F1=0.1569)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57365 | val 0.67985
  Epoch 020 - train 0.49581 | val 0.75613

[I 2026-02-20 06:30:16,543] Trial 245 finished with value: 0.2872360795178413 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.007096369480274513, 'weight_decay': 1.4257723454112204e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.0260602686046592, 'early_stopping_min_delta': 0.002614280541461077}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 023 - train 0.46961 | val 0.82568
  Classification -> best τ=0.460 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2872360795178413
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57633 | val 0.74260
  Epoch 015 - train 0.60769 | val 0.90184
  Classification -> best τ=0.430 (val F1=0.2036)
  Directional -> Accuracy: 0.5921, MCC: 0.1521, F1: 0.3922

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58318 | val 0.67566
  Epoch 014 - train 0.57020 | val 0.67961
  Classification -> best τ=0.440 (val F1=0.3126)
  Directional -> Accuracy: 0.6667, MCC: 0.3877, F1: 0.6512

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61068 | val 0.66686
  Epoch 020 - train 0.53201 | val 0.87545
  Epoch 023 - train 0.46015 | val 0.84700
  Classification -> best τ=0.555 (val F1=0.4178)
  Directional -> Accuracy: 0.6957, MCC: 0.4008, F1: 0.6818

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63907 | val 0.86593
  Epoch 013 - train 0.60938 | val 1.24030
  Classification -> best τ=0.540 (val F1=0.0279)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59508 | val 0.72634
  Epoch 017 - train 0.55494 | val 0.74726
  Classification -> best τ=0.560 (val F1=0.4787)
  Directional -> Accuracy: 0.5600, MCC: 0.1650, F1: 0.4211

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57872 | val 0.99093
  Epoch 012 - train 0.56712 | val 0.75771
  Classification -> best τ=0.590 (val F1=0.2739)
  Directional -> Accuracy: 0.6087, MCC: 0.2197, F1: 0.6087

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65462 | val 0.70844
  Epoch 017 - train 0.61232 | val 1.08706
  Classification -> best τ=0.545 (val F1=0.2361)
  Directional -> Accuracy: 0.5147, MCC: 0.1463, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56299 | val 0.98113
  Epoch 013 - train 0.56183 | val 1.46871
  Classification -> best τ=0.385 (val F1=0.0668)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57063 | val 0.83587
  Epoch 012 - train 0.54639 | val 1.15058
  Classification -> best τ=0.495 (val F1=0.2764)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58858 | val 0.81223
  Epoch 013 - train 0.53639 | val 1.03695
  Classification -> best τ=0.425 (val F1=0.1424)
  Directional -> Accuracy: 0.4058, MCC: -0.1264, F1: 0.4938

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62578 | val 0.68075
  Epoch 011 - train 0.63062 | val 0.79716
  Classification -> best τ=0.450 (val F1=0.1965)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57490 | val 1.36781
  Epoch 012 - train 0.51820 | val 1.73740
  Classification -> best τ=0.525 (val F1=0.2741)
  Directional -> Accuracy: 0.6842, MCC: 0.3704, F1: 0.7097

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56914 | val 1.22593
  Epoch 012 - train 0.53626 | val 1.22919
  Classification -> best τ=0.600 (val F1=0.2850)
  Directional -> Accuracy: 0.3571, MCC: -0.2781, F1: 0.4706

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61785 | val 0.85914
  Epoch 011 - train 0.60691 | val 0.98871
  Classification -> best τ=0.435 (val F1=0.3387)
  Directional -> Accuracy: 0.5167, MCC: 0.0335, F1: 0.4912

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61070 | val 0.71547
  Epoch 016 - train 0.57128 | val 1.25828
  Classification -> best τ=0.445 (val F1=0.2245)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61518 | val 0.74988
  Epoch 014 - train 0.54762 | val 0.88941
  Classification -> best τ=0.430 (val F1=0.4156)
  Directional -> Accuracy: 0.5507, MCC: 0.1028, F1: 0.5634

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59345 | val 1.25366
  Epoch 011 - train 0.58013 | val 1.41365
  Classification -> best τ=0.515 (val F1=0.1878)
  Directional -> Accuracy: 0.5690, MCC: -0.1135, F1: 0.7191

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58980 | val 1.20659
  Epoch 012 - train 0.65287 | val 1.39038
  Classification -> best τ=0.560 (val F1=0.2321)
  Directional -> Accuracy: 0.4133, MCC: -0.0780, F1: 0.2903

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61851 | val 1.22259
  Epoch 013 - train 0.68554 | val 0.73372
  Classification -> best τ=0.460 (val F1=0.3421)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61227 | val 0.70968
  Epoch 013 - train 0.64099 | val 0.82222
  Classification -> best τ=0.475 (val F1=0.2597)
  Directional -> Accuracy: 0.4730, MCC: 0.0942, F1: 0.1333

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60386 | val 0.67743
  Epoch 020 - train 0.46892 | val 1.00967
  Classification -> best τ=0.475 (val F1=0.3020)
  Directional -> Accuracy: 0.5745, MCC: 0.2030, F1: 0.5833

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61637 | val 0.91059
  Epoch 011 - train 0.61984 | val 0.93403
  Classification -> best τ=0.575 (val F1=0.0329)
  Directional -> Accuracy: 0.5231, MCC: 0.1014, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59618 | val 0.80223
  Epoch 012 - train 0.55364 | val 0.81384
  Classification -> best τ=0.720 (val F1=0.3550)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64209 | val 0.74439
  Epoch 020 - train 0.59187 | val 0.72618
  Epoch 021 - train 0.63070 | val 0.70655
  Classification -> best τ=0.415 (val F1=0.2420)
  Directional -> Accuracy: 0.5385, MCC: 0.0836, F1: 0.1176

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59635 | val 0.82600
  Epoch 018 - train 0.44774 | val 0.78341
  Classification -> best τ=0.680 (val F1=0.4674)
  Directional -> Accuracy: 0.4909, MCC: 0.0141, F1: 0.4167

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58104 | val 0.82250
  Epoch 011 - train 0.57263 | val 1.00366
  Classification -> best τ=0.515 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: -0.0732, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61306 | val 0.79092
  Epoch 011 - train 0.63608 | val 0.83768
  Classification -> best τ=0.625 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.3784

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61706 | val 0.70343
  Epoch 014 - train 0.59299 | val 0.91954
  Classification -> best τ=0.455 (val F1=0.2755)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56908 | val 0.68908
  Epoch 012 - train 0.55476 | val 0.73381
  Classification -> best τ=0.590 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0439, F1: 0.4118

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62948 | val 0.77490
  Epoch 012 - train 0.57227 | val 0.89650
  Classification -> best τ=0.590 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61311 | val 0.79247
  Epoch 015 - train 0.52341 | val 1.47399
  Classification -> best τ=0.415 (val F1=0.2042)
  Directional -> Accuracy: 0.4286, MCC: -0.1083, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61015 | val 0.73370
  Epoch 014 - train 0.51562 | val 0.85530
  Classification -> best τ=0.420 (val F1=0.3461)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63972 | val 0.68169
  Epoch 016 - train 0.56373 | val 0.77454
  Classification -> best τ=0.430 (val F1=0.3076)
  Directional -> Accuracy: 0.5417, MCC: 0.1332, F1: 0.4762

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66566 | val 0.88571
  Epoch 011 - train 0.63633 | val 1.11533
  Classification -> best τ=0.460 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66017 | val 0.81945
  Epoch 011 - train 0.64654 | val 0.81903
  Classification -> best τ=0.360 (val F1=0.3603)
  Directional -> Accuracy: 0.5909, MCC: 0.1145, F1: 0.7033

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52524 | val 0.88237
  Epoch 011 - train 0.48859 | val 0.85704
  Classification -> best τ=0.480 (val F1=0.2439)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55482 | val 0.78393
  Epoch 011 - train 0.53698 | val 0.83484
  Classification -> best τ=0.505 (val F1=0.1235)
  Directional -> Accuracy: 0.5357, MCC: 0.0292, F1: 0.2353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50945 | val 0.98842
  Epoch 011 - train 0.48403 | val 1.08110
  Classification -> best τ=0.445 (val F1=0.3397)
  Directional -> Accuracy: 0.6304, MCC: 0.1859, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58459 | val 0.67100
  Epoch 012 - train 0.55320 | val 0.67246
  Classification -> best τ=0.475 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58255 | val 0.78776
  Epoch 011 - train 0.57442 | val 0.79796
  Classification -> best τ=0.370 (val F1=0.2706)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56622 | val 0.75141
  Epoch 016 - train 0.51716 | val 0.86655
  Classification -> best τ=0.510 (val F1=0.3371)
  Directional -> Accuracy: 0.4667, MCC: -0.0672, F1: 0.4783

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57248 | val 0.59976
  Epoch 020 - train 0.50037 | val 0.64507
  Classification -> best τ=0.445 (val F1=0.5092)
  Directional -> Accuracy: 0.6429, MCC: 0.2513, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58210 | val 0.63083
  Epoch 020 - train 0.44338 | val 0.72738
  Epoch 030 - train 0.34892 | val 0.96685
  Epoch 032 - train 0.30981 | val 0.97158
  Classification -> best τ=0.275 (val F1=0.4682)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57325 | val 0.73083
  Epoch 011 - train 0.54721 | val 0.72061
  Classification -> best τ=0.510 (val F1=0.2291)
  Directional -> Accuracy: 0.4909, MCC: -0.1617, F1: 0.6500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62074 | val 1.36311
  Epoch 011 - train 0.61426 | val 1.33816
  Classification -> best τ=0.550 (val F1=0.2793)
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.1379

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60251 | val 0.83773
  Epoch 012 - train 0.62748 | val 0.99056
  Classification -> best τ=0.590 (val F1=0.2064)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62403 | val 1.16994
  Epoch 011 - train 0.60008 | val 1.01531
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59500 | val 0.84248

[I 2026-02-20 06:31:16,164] Trial 246 finished with value: 0.2734683973485778 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.00709964338937828, 'weight_decay': 1.0136899772174219e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0210967796452552, 'early_stopping_min_delta': 0.0034070053020339307}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 013 - train 0.56663 | val 0.78764
  Classification -> best τ=0.410 (val F1=0.2311)
  Directional -> Accuracy: 0.5000, MCC: -0.0034, F1: 0.4643

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2734683973485778
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59015 | val 1.06886
  Epoch 020 - train 0.52764 | val 0.83304
  Epoch 023 - train 0.49697 | val 1.17623
  Classification -> best τ=0.460 (val F1=0.1430)
  Directional -> Accuracy: 0.5921, MCC: 0.1522, F1: 0.3673

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59380 | val 0.68080
  Epoch 020 - train 0.47904 | val 0.68310
  Epoch 023 - train 0.40521 | val 0.69264
  Classification -> best τ=0.445 (val F1=0.4088)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59325 | val 0.72530
  Epoch 020 - train 0.47916 | val 1.09775
  Epoch 022 - train 0.47007 | val 1.21093
  Classification -> best τ=0.450 (val F1=0.2800)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64594 | val 0.84473
  Epoch 020 - train 0.59494 | val 1.21267
  Epoch 024 - train 0.50826 | val 1.14014
  Classification -> best τ=0.320 (val F1=0.1808)
  Directional -> Accuracy: 0.5270, MCC: 0.0542, F1: 0.5455

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57904 | val 0.77837
  Epoch 020 - train 0.34410 | val 0.94213
  Epoch 021 - train 0.33453 | val 1.08456
  Classification -> best τ=0.465 (val F1=0.3945)
  Directional -> Accuracy: 0.7400, MCC: 0.4804, F1: 0.7451

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58981 | val 0.69819
  Epoch 020 - train 0.42941 | val 0.85398
  Epoch 021 - train 0.42285 | val 0.76581
  Classification -> best τ=0.625 (val F1=0.2739)
  Directional -> Accuracy: 0.5652, MCC: 0.2416, F1: 0.6774

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62954 | val 0.86241
  Epoch 020 - train 0.53632 | val 1.57274
  Epoch 021 - train 0.52115 | val 1.46509
  Classification -> best τ=0.435 (val F1=0.2772)
  Directional -> Accuracy: 0.4412, MCC: 0.0509, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56037 | val 0.93180
  Epoch 020 - train 0.41242 | val 1.38052
  Epoch 024 - train 0.37330 | val 1.70663
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62754 | val 0.85030
  Epoch 020 - train 0.48861 | val 1.32292
  Epoch 023 - train 0.42977 | val 1.53710
  Classification -> best τ=0.535 (val F1=0.3959)
  Directional -> Accuracy: 0.6667, MCC: 0.3130, F1: 0.5294

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64847 | val 0.74123
  Epoch 020 - train 0.55910 | val 0.72845
  Epoch 026 - train 0.50059 | val 0.76745
  Classification -> best τ=0.490 (val F1=0.1609)
  Directional -> Accuracy: 0.4348, MCC: -0.1163, F1: 0.4179

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62902 | val 0.86282
  Epoch 020 - train 0.49255 | val 1.06937
  Epoch 023 - train 0.47070 | val 1.19470
  Classification -> best τ=0.410 (val F1=0.2478)
  Directional -> Accuracy: 0.6531, MCC: 0.3136, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61275 | val 1.06613
  Epoch 020 - train 0.40933 | val 2.53853
  Epoch 025 - train 0.33936 | val 2.98266
  Classification -> best τ=0.480 (val F1=0.3027)
  Directional -> Accuracy: 0.5789, MCC: 0.1672, F1: 0.6571

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55646 | val 1.58341
  Epoch 020 - train 0.42740 | val 2.38950
  Epoch 022 - train 0.43188 | val 2.81592
  Classification -> best τ=0.405 (val F1=0.2172)
  Directional -> Accuracy: 0.5000, MCC: 0.2032, F1: 0.6441

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63974 | val 0.70312
  Epoch 020 - train 0.52355 | val 0.81852
  Epoch 025 - train 0.46185 | val 1.02629
  Classification -> best τ=0.385 (val F1=0.3477)
  Directional -> Accuracy: 0.5333, MCC: 0.0673, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55687 | val 0.73838
  Epoch 020 - train 0.50427 | val 0.74529
  Epoch 022 - train 0.44657 | val 0.76712
  Classification -> best τ=0.490 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61366 | val 0.83382
  Epoch 020 - train 0.44638 | val 1.16982
  Epoch 023 - train 0.42437 | val 1.46284
  Classification -> best τ=0.545 (val F1=0.3159)
  Directional -> Accuracy: 0.4783, MCC: -0.0123, F1: 0.3571

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61432 | val 0.99344
  Epoch 020 - train 0.50806 | val 1.42483
  Epoch 021 - train 0.50644 | val 1.37169
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60378 | val 1.62154
  Epoch 020 - train 0.48654 | val 2.33200
  Epoch 022 - train 0.46878 | val 2.55240
  Classification -> best τ=0.490 (val F1=0.1243)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65948 | val 0.69808
  Epoch 020 - train 0.58592 | val 1.43928
  Epoch 023 - train 0.55373 | val 1.62862
  Classification -> best τ=0.410 (val F1=0.2843)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59533 | val 0.80670
  Epoch 020 - train 0.45514 | val 1.14894
  Epoch 022 - train 0.43552 | val 1.26639
  Classification -> best τ=0.555 (val F1=0.3460)
  Directional -> Accuracy: 0.4189, MCC: -0.1858, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58757 | val 0.69119
  Epoch 020 - train 0.48460 | val 0.65832
  Epoch 030 - train 0.20709 | val 0.74255
  Epoch 036 - train 0.16170 | val 0.68464
  Classification -> best τ=0.370 (val F1=0.4286)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67331 | val 0.83920
  Epoch 020 - train 0.53893 | val 0.95540
  Epoch 021 - train 0.53105 | val 1.28374
  Classification -> best τ=0.510 (val F1=0.2037)
  Directional -> Accuracy: 0.5231, MCC: 0.0507, F1: 0.6517

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63814 | val 0.67615
  Epoch 020 - train 0.55131 | val 0.84071
  Epoch 023 - train 0.51685 | val 0.91416
  Classification -> best τ=0.520 (val F1=0.2940)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66474 | val 0.96555
  Epoch 020 - train 0.47070 | val 0.84918
  Epoch 022 - train 0.44870 | val 0.92427
  Classification -> best τ=0.505 (val F1=0.1874)
  Directional -> Accuracy: 0.5538, MCC: 0.1866, F1: 0.1212

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62163 | val 0.72670
  Epoch 020 - train 0.51073 | val 0.73738
  Epoch 026 - train 0.37948 | val 0.95062
  Classification -> best τ=0.365 (val F1=0.4307)
  Directional -> Accuracy: 0.5091, MCC: -0.0852, F1: 0.6582

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57609 | val 0.68618
  Epoch 020 - train 0.39871 | val 1.27485
  Epoch 030 - train 0.20864 | val 1.45079
  Classification -> best τ=0.435 (val F1=0.3669)
  Directional -> Accuracy: 0.5111, MCC: 0.2670, F1: 0.6333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59074 | val 0.75357
  Epoch 020 - train 0.48442 | val 0.76343
  Epoch 021 - train 0.46915 | val 0.79973
  Classification -> best τ=0.575 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.3784

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64239 | val 0.72922
  Epoch 020 - train 0.47129 | val 1.10411
  Epoch 022 - train 0.44824 | val 1.07821
  Classification -> best τ=0.355 (val F1=0.2637)
  Directional -> Accuracy: 0.5536, MCC: 0.2311, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63349 | val 0.71760
  Epoch 020 - train 0.47838 | val 1.00792
  Epoch 030 - train 0.27452 | val 1.66168
  Epoch 033 - train 0.22821 | val 1.69415
  Classification -> best τ=0.455 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61541 | val 0.72714
  Epoch 020 - train 0.47599 | val 0.77042
  Epoch 022 - train 0.44053 | val 0.69721
  Classification -> best τ=0.630 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0561, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57888 | val 1.12383
  Epoch 020 - train 0.39942 | val 1.68513
  Epoch 027 - train 0.23257 | val 1.64995
  Classification -> best τ=0.740 (val F1=0.3067)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60650 | val 0.69553
  Epoch 020 - train 0.40991 | val 1.09593
  Epoch 023 - train 0.33809 | val 1.29488
  Classification -> best τ=0.520 (val F1=0.3069)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60519 | val 0.67912
  Epoch 020 - train 0.51315 | val 0.95981
  Epoch 026 - train 0.41248 | val 1.62117
  Classification -> best τ=0.390 (val F1=0.3838)
  Directional -> Accuracy: 0.5278, MCC: 0.0988, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62287 | val 1.00700
  Epoch 020 - train 0.41594 | val 1.95292
  Epoch 025 - train 0.27745 | val 2.24136
  Classification -> best τ=0.560 (val F1=0.2892)
  Directional -> Accuracy: 0.6744, MCC: 0.3485, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66238 | val 0.95009
  Epoch 020 - train 0.52526 | val 1.07838
  Epoch 021 - train 0.53232 | val 1.11382
  Classification -> best τ=0.445 (val F1=0.3254)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57303 | val 1.09096
  Epoch 020 - train 0.38869 | val 1.92477
  Epoch 021 - train 0.39192 | val 2.06219
  Classification -> best τ=0.505 (val F1=0.2439)
  Directional -> Accuracy: 0.6905, MCC: 0.4122, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58179 | val 0.79740
  Epoch 020 - train 0.39178 | val 1.55627
  Epoch 021 - train 0.37692 | val 1.25219
  Classification -> best τ=0.455 (val F1=0.3322)
  Directional -> Accuracy: 0.5893, MCC: 0.1706, F1: 0.3784

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54889 | val 1.21271
  Epoch 020 - train 0.36172 | val 1.70979
  Epoch 021 - train 0.36165 | val 1.86394
  Classification -> best τ=0.465 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58382 | val 0.69462
  Epoch 020 - train 0.44403 | val 0.82049
  Epoch 026 - train 0.31667 | val 0.85706
  Classification -> best τ=0.465 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61854 | val 0.71722
  Epoch 020 - train 0.42425 | val 0.87939
  Epoch 024 - train 0.37757 | val 0.93731
  Classification -> best τ=0.500 (val F1=0.3332)
  Directional -> Accuracy: 0.4730, MCC: -0.0741, F1: 0.6355

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56878 | val 0.78350
  Epoch 020 - train 0.47275 | val 0.91789
  Epoch 022 - train 0.42592 | val 0.99188
  Classification -> best τ=0.475 (val F1=0.2174)
  Directional -> Accuracy: 0.5778, MCC: 0.1935, F1: 0.6885

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56525 | val 0.64321
  Epoch 020 - train 0.52315 | val 0.62518
  Epoch 030 - train 0.35398 | val 0.55050
  Epoch 040 - train 0.13759 | val 0.76560
  Epoch 048 - train 0.06393 | val 0.83612
  Classification -> best τ=0.285 (val F1=0.6124)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61060 | val 0.78077
  Epoch 020 - train 0.50770 | val 0.65501
  Epoch 024 - train 0.45583 | val 0.71264
  Classification -> best τ=0.645 (val F1=0.3410)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61045 | val 0.72154
  Epoch 020 - train 0.48850 | val 0.72679
  Epoch 021 - train 0.45483 | val 0.73012
  Classification -> best τ=0.520 (val F1=0.2292)
  Directional -> Accuracy: 0.4182, MCC: -0.2500, F1: 0.5556

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59474 | val 1.57900
  Epoch 020 - train 0.43199 | val 1.98927
  Epoch 022 - train 0.40597 | val 2.11257
  Classification -> best τ=0.450 (val F1=0.2386)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62014 | val 0.94368
  Epoch 020 - train 0.51847 | val 1.39837
  Epoch 023 - train 0.49643 | val 1.90201
  Classification -> best τ=0.560 (val F1=0.2482)
  Directional -> Accuracy: 0.5849, MCC: 0.1825, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66062 | val 0.88148
  Epoch 020 - train 0.58509 | val 1.24923
  Epoch 023 - train 0.55098 | val 1.17590
  Classification -> best τ=0.540 (val F1=0.0711)

[I 2026-02-20 06:32:51,760] Trial 247 finished with value: 0.2800217628481155 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006644804808925435, 'weight_decay': 1.3807289926617632e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.0698122364556517, 'early_stopping_min_delta': 0.0029960050497782557}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 034 - train 0.30798 | val 1.23240
  Classification -> best τ=0.510 (val F1=0.3108)
  Directional -> Accuracy: 0.4833, MCC: -0.0272, F1: 0.5231

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2800217628481155
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62196 | val 0.68960
  Epoch 020 - train 0.51501 | val 1.01766
  Epoch 021 - train 0.53422 | val 0.80726
  Classification -> best τ=0.405 (val F1=0.0220)
  Directional -> Accuracy: 0.5000, MCC: -0.0862, F1: 0.2083

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60393 | val 0.67680
  Epoch 020 - train 0.44379 | val 0.78189
  Epoch 030 - train 0.34344 | val 0.90873
  Classification -> best τ=0.475 (val F1=0.2073)
  Directional -> Accuracy: 0.4667, MCC: -0.0782, F1: 0.5200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56866 | val 0.74397
  Epoch 020 - train 0.44477 | val 1.19395
  Epoch 022 - train 0.40112 | val 1.47266
  Classification -> best τ=0.525 (val F1=0.2311)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65689 | val 0.99020
  Epoch 020 - train 0.55949 | val 1.17135
  Epoch 026 - train 0.47107 | val 1.34164
  Classification -> best τ=0.465 (val F1=0.1483)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59696 | val 0.85202
  Epoch 020 - train 0.39819 | val 1.10995
  Epoch 026 - train 0.30359 | val 1.92641
  Classification -> best τ=0.525 (val F1=0.4083)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56382 | val 0.72125
  Epoch 020 - train 0.52426 | val 0.77937
  Epoch 023 - train 0.44587 | val 0.79755
  Classification -> best τ=0.570 (val F1=0.1463)
  Directional -> Accuracy: 0.5435, MCC: 0.1557, F1: 0.0870

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64220 | val 0.75179
  Epoch 020 - train 0.55369 | val 0.94447
  Epoch 022 - train 0.52936 | val 0.93359
  Classification -> best τ=0.425 (val F1=0.2220)
  Directional -> Accuracy: 0.4706, MCC: 0.0693, F1: 0.5500

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53862 | val 0.89335
  Epoch 020 - train 0.43169 | val 1.19541
  Epoch 027 - train 0.32484 | val 1.94895
  Classification -> best τ=0.400 (val F1=0.1147)
  Directional -> Accuracy: 0.4048, MCC: -0.1925, F1: 0.3590

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54964 | val 0.76785
  Epoch 020 - train 0.41562 | val 1.07393
  Epoch 027 - train 0.30314 | val 1.45388
  Classification -> best τ=0.660 (val F1=0.3433)
  Directional -> Accuracy: 0.5625, MCC: 0.0727, F1: 0.3636

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54756 | val 0.85617
  Epoch 020 - train 0.41186 | val 1.31477
  Epoch 023 - train 0.39680 | val 1.59514
  Classification -> best τ=0.465 (val F1=0.2693)
  Directional -> Accuracy: 0.5362, MCC: 0.0853, F1: 0.5152

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61801 | val 1.23044
  Epoch 020 - train 0.49745 | val 1.98802
  Epoch 022 - train 0.46859 | val 2.20848
  Classification -> best τ=0.475 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57697 | val 1.25659
  Epoch 020 - train 0.39170 | val 4.51304
  Epoch 022 - train 0.38625 | val 4.81818
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59806 | val 1.03924
  Epoch 020 - train 0.49403 | val 1.73910
  Epoch 022 - train 0.47934 | val 1.91595
  Classification -> best τ=0.600 (val F1=0.2942)
  Directional -> Accuracy: 0.5714, MCC: 0.1114, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61194 | val 0.69662
  Epoch 020 - train 0.51955 | val 1.00274
  Epoch 029 - train 0.38151 | val 1.21625
  Classification -> best τ=0.405 (val F1=0.3407)
  Directional -> Accuracy: 0.5333, MCC: 0.0680, F1: 0.5758

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56254 | val 0.75505
  Epoch 020 - train 0.54016 | val 0.83473
  Epoch 025 - train 0.44695 | val 0.81539
  Classification -> best τ=0.440 (val F1=0.1925)
  Directional -> Accuracy: 0.4902, MCC: 0.0506, F1: 0.5938

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62345 | val 0.79614
  Epoch 020 - train 0.50391 | val 1.21402
  Epoch 023 - train 0.45872 | val 2.01716
  Classification -> best τ=0.510 (val F1=0.3849)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63576 | val 0.96364
  Epoch 020 - train 0.50910 | val 1.66971
  Epoch 021 - train 0.52284 | val 1.85127
  Classification -> best τ=0.385 (val F1=0.0046)
  Directional -> Accuracy: 0.5690, MCC: -0.0156, F1: 0.6988

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62409 | val 0.93704
  Epoch 020 - train 0.54283 | val 1.32296
  Epoch 022 - train 0.49881 | val 1.75355
  Classification -> best τ=0.545 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63731 | val 0.78171
  Epoch 020 - train 0.48365 | val 1.97337
  Epoch 024 - train 0.41675 | val 2.95691
  Classification -> best τ=0.385 (val F1=0.3267)
  Directional -> Accuracy: 0.4531, MCC: 0.0577, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64594 | val 0.65124
  Epoch 020 - train 0.55768 | val 0.71848
  Epoch 030 - train 0.44585 | val 1.08925
  Classification -> best τ=0.385 (val F1=0.3045)
  Directional -> Accuracy: 0.4054, MCC: -0.1574, F1: 0.1852

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62881 | val 0.68306
  Epoch 020 - train 0.49785 | val 0.96069
  Epoch 030 - train 0.19864 | val 0.96588
  Epoch 032 - train 0.16484 | val 0.92040
  Classification -> best τ=0.535 (val F1=0.3138)
  Directional -> Accuracy: 0.5745, MCC: 0.2287, F1: 0.5652

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64923 | val 1.09315
  Epoch 020 - train 0.57142 | val 0.91173
  Epoch 021 - train 0.55815 | val 0.98892
  Classification -> best τ=0.460 (val F1=0.0346)
  Directional -> Accuracy: 0.5231, MCC: 0.0767, F1: 0.6737

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62355 | val 0.75851
  Epoch 020 - train 0.51220 | val 1.11366
  Epoch 030 - train 0.36180 | val 1.67432
  Epoch 032 - train 0.32115 | val 1.89207
  Classification -> best τ=0.620 (val F1=0.3276)
  Directional -> Accuracy: 0.5789, MCC: 0.1809, F1: 0.5714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61567 | val 0.86592
  Epoch 020 - train 0.52529 | val 0.72066
  Epoch 028 - train 0.37376 | val 0.80220
  Classification -> best τ=0.520 (val F1=0.1701)
  Directional -> Accuracy: 0.5538, MCC: 0.1327, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62986 | val 0.67994
  Epoch 020 - train 0.56648 | val 0.68182
  Epoch 026 - train 0.48433 | val 0.87740
  Classification -> best τ=0.540 (val F1=0.3563)
  Directional -> Accuracy: 0.5455, MCC: 0.0930, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55132 | val 0.89481
  Epoch 020 - train 0.33600 | val 1.11811
  Epoch 022 - train 0.30058 | val 1.28198
  Classification -> best τ=0.640 (val F1=0.2097)
  Directional -> Accuracy: 0.5111, MCC: 0.0710, F1: 0.5417

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61805 | val 0.74479
  Epoch 020 - train 0.51399 | val 0.81252
  Epoch 021 - train 0.51573 | val 0.83152
  Classification -> best τ=0.600 (val F1=0.2240)
  Directional -> Accuracy: 0.4286, MCC: -0.1514, F1: 0.4783

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61777 | val 0.71948
  Epoch 020 - train 0.44543 | val 1.26248
  Epoch 023 - train 0.40116 | val 1.62536
  Classification -> best τ=0.430 (val F1=0.2841)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62942 | val 0.71679
  Epoch 020 - train 0.45381 | val 0.99801
  Epoch 030 - train 0.24726 | val 1.14255
  Epoch 031 - train 0.27842 | val 1.20770
  Classification -> best τ=0.330 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66284 | val 1.04678
  Epoch 020 - train 0.51099 | val 0.73217
  Epoch 022 - train 0.48289 | val 0.85144
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60747 | val 1.07487
  Epoch 020 - train 0.43573 | val 1.45152
  Epoch 028 - train 0.30935 | val 1.73991
  Classification -> best τ=0.500 (val F1=0.2646)
  Directional -> Accuracy: 0.6190, MCC: 0.2392, F1: 0.6364

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56195 | val 0.79386
  Epoch 020 - train 0.32546 | val 1.17475
  Epoch 023 - train 0.31573 | val 1.23097
  Classification -> best τ=0.375 (val F1=0.3433)
  Directional -> Accuracy: 0.5306, MCC: 0.0183, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63834 | val 0.64622
  Epoch 020 - train 0.51867 | val 0.71282
  Epoch 028 - train 0.39610 | val 1.17837
  Classification -> best τ=0.445 (val F1=0.3380)
  Directional -> Accuracy: 0.5556, MCC: 0.1936, F1: 0.4483

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61519 | val 0.78273
  Epoch 020 - train 0.49060 | val 1.16225
  Epoch 025 - train 0.38889 | val 1.43707
  Classification -> best τ=0.480 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.6441

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62371 | val 0.81060
  Epoch 020 - train 0.52199 | val 0.89332
  Epoch 023 - train 0.51051 | val 0.96805
  Classification -> best τ=0.620 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57148 | val 0.71134
  Epoch 020 - train 0.44383 | val 0.68749
  Epoch 022 - train 0.41445 | val 0.70329
  Classification -> best τ=0.415 (val F1=0.3001)
  Directional -> Accuracy: 0.7619, MCC: 0.5227, F1: 0.7727

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57452 | val 0.81329
  Epoch 020 - train 0.40718 | val 1.23371
  Epoch 021 - train 0.38323 | val 1.40187
  Classification -> best τ=0.530 (val F1=0.1794)
  Directional -> Accuracy: 0.5179, MCC: 0.0283, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52371 | val 1.02157
  Epoch 020 - train 0.31039 | val 1.55051
  Epoch 024 - train 0.30569 | val 2.12237
  Classification -> best τ=0.545 (val F1=0.2254)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53362 | val 0.64460
  Epoch 020 - train 0.41122 | val 0.66855
  Epoch 030 - train 0.24664 | val 0.86454
  Epoch 034 - train 0.22157 | val 0.99563
  Classification -> best τ=0.340 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62130 | val 0.69425
  Epoch 020 - train 0.46769 | val 0.78658
  Epoch 026 - train 0.44353 | val 1.18338
  Classification -> best τ=0.590 (val F1=0.2518)
  Directional -> Accuracy: 0.5541, MCC: 0.1651, F1: 0.6598

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60211 | val 0.80314
  Epoch 020 - train 0.41493 | val 1.03890
  Epoch 022 - train 0.42889 | val 1.08857
  Classification -> best τ=0.430 (val F1=0.3500)
  Directional -> Accuracy: 0.6222, MCC: 0.2466, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55653 | val 0.61925
  Epoch 020 - train 0.48811 | val 0.80654
  Epoch 030 - train 0.32894 | val 1.19467
  Epoch 033 - train 0.27338 | val 1.32607
  Classification -> best τ=0.630 (val F1=0.5784)
  Directional -> Accuracy: 0.6190, MCC: 0.2041, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61538 | val 0.59652
  Epoch 020 - train 0.50897 | val 0.69761
  Epoch 025 - train 0.43869 | val 0.71949
  Classification -> best τ=0.560 (val F1=0.5514)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57813 | val 0.67176
  Epoch 020 - train 0.45043 | val 0.76779
  Epoch 021 - train 0.47159 | val 0.89614
  Classification -> best τ=0.565 (val F1=0.2527)
  Directional -> Accuracy: 0.4909, MCC: -0.0336, F1: 0.5484

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55455 | val 1.73929
  Epoch 020 - train 0.37911 | val 3.04139
  Epoch 023 - train 0.31662 | val 3.16783
  Classification -> best τ=0.635 (val F1=0.2917)
  Directional -> Accuracy: 0.5000, MCC: -0.0065, F1: 0.4400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61153 | val 0.84385
  Epoch 020 - train 0.47608 | val 0.92367
  Epoch 023 - train 0.46477 | val 1.21870
  Classification -> best τ=0.595 (val F1=0.0750)
  Directional -> Accuracy: 0.4528, MCC: -0.0926, F1: 0.3830

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62329 | val 0.79503
  Epoch 020 - train 0.49410 | val 0.85349
  Epoch 021 - train 0.48450 | val 0.92009
  Classification -> best τ=0.050 (val F1=0.0000)

[I 2026-02-20 06:34:30,240] Trial 248 finished with value: 0.2591379041707229 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.008349787260200825, 'weight_decay': 2.0919012271419227e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.923829179215454, 'early_stopping_min_delta': 0.0025440814671529293}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 025 - train 0.43066 | val 1.00007
  Classification -> best τ=0.370 (val F1=0.3525)
  Directional -> Accuracy: 0.4833, MCC: -0.0062, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2591379041707229
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60712 | val 0.67441
  Epoch 012 - train 0.61370 | val 0.68114
  Classification -> best τ=0.485 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57547 | val 0.67809
  Epoch 020 - train 0.45203 | val 0.68597
  Epoch 022 - train 0.47662 | val 0.70722
  Classification -> best τ=0.475 (val F1=0.3006)
  Directional -> Accuracy: 0.5778, MCC: 0.1408, F1: 0.6275

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56975 | val 0.73403
  Epoch 011 - train 0.59034 | val 0.88611
  Classification -> best τ=0.535 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65308 | val 0.84165
  Epoch 012 - train 0.63692 | val 0.79052
  Classification -> best τ=0.400 (val F1=0.1548)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57768 | val 0.85625
  Epoch 014 - train 0.54797 | val 0.98664
  Classification -> best τ=0.460 (val F1=0.4745)
  Directional -> Accuracy: 0.6200, MCC: 0.3170, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56014 | val 0.84230
  Epoch 012 - train 0.57466 | val 0.79108
  Classification -> best τ=0.540 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60687 | val 1.05039
  Epoch 011 - train 0.65997 | val 0.89372
  Classification -> best τ=0.480 (val F1=0.2810)
  Directional -> Accuracy: 0.4412, MCC: 0.0771, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55486 | val 0.80734
  Epoch 012 - train 0.52245 | val 0.90762
  Classification -> best τ=0.385 (val F1=0.0765)
  Directional -> Accuracy: 0.3810, MCC: -0.2831, F1: 0.2353

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61166 | val 0.81241
  Epoch 013 - train 0.55787 | val 0.73554
  Classification -> best τ=0.410 (val F1=0.1402)
  Directional -> Accuracy: 0.4583, MCC: 0.0258, F1: 0.5938

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57184 | val 0.77881
  Epoch 011 - train 0.54151 | val 0.87644
  Classification -> best τ=0.500 (val F1=0.1858)
  Directional -> Accuracy: 0.4058, MCC: -0.1064, F1: 0.5684

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62188 | val 0.79722
  Epoch 014 - train 0.63467 | val 1.17772
  Classification -> best τ=0.450 (val F1=0.2593)
  Directional -> Accuracy: 0.4898, MCC: 0.1193, F1: 0.6269

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57064 | val 1.33053
  Epoch 011 - train 0.50584 | val 1.80449
  Classification -> best τ=0.495 (val F1=0.1304)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61066 | val 1.28023
  Epoch 011 - train 0.58088 | val 1.57951
  Classification -> best τ=0.415 (val F1=0.3172)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58091 | val 0.62649
  Epoch 018 - train 0.51758 | val 0.65750
  Classification -> best τ=0.410 (val F1=0.3558)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61063 | val 0.80979
  Epoch 011 - train 0.56544 | val 0.87438
  Classification -> best τ=0.480 (val F1=0.2571)
  Directional -> Accuracy: 0.4314, MCC: -0.1225, F1: 0.4528

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62616 | val 0.86616
  Epoch 012 - train 0.56764 | val 0.95106
  Classification -> best τ=0.595 (val F1=0.3063)
  Directional -> Accuracy: 0.5797, MCC: 0.1997, F1: 0.5085

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60044 | val 0.79347
  Epoch 011 - train 0.58941 | val 0.79954
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62615 | val 0.92931
  Epoch 012 - train 0.57004 | val 0.99710
  Classification -> best τ=0.490 (val F1=0.1627)
  Directional -> Accuracy: 0.5733, MCC: 0.0399, F1: 0.6923

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64173 | val 0.90265
  Epoch 015 - train 0.57540 | val 1.48182
  Classification -> best τ=0.580 (val F1=0.2932)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60329 | val 0.66060
  Epoch 020 - train 0.55476 | val 0.72206
  Epoch 027 - train 0.54272 | val 0.75599
  Classification -> best τ=0.455 (val F1=0.3439)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58423 | val 0.76721
  Epoch 020 - train 0.41312 | val 0.62183
  Epoch 030 - train 0.24482 | val 0.90443
  Classification -> best τ=0.350 (val F1=0.4286)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66130 | val 0.79567
  Epoch 013 - train 0.62075 | val 0.81912
  Classification -> best τ=0.495 (val F1=0.1204)
  Directional -> Accuracy: 0.4462, MCC: -0.1191, F1: 0.5263

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63401 | val 0.81010
  Epoch 011 - train 0.60165 | val 0.78262
  Classification -> best τ=0.580 (val F1=0.3550)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66614 | val 0.87069
  Epoch 014 - train 0.66801 | val 0.70235
  Classification -> best τ=0.500 (val F1=0.0406)
  Directional -> Accuracy: 0.5077, MCC: -0.0445, F1: 0.1111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57174 | val 0.65995
  Epoch 012 - train 0.53032 | val 0.86400
  Classification -> best τ=0.550 (val F1=0.5009)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63597 | val 1.15637
  Epoch 012 - train 0.55613 | val 0.78950
  Classification -> best τ=0.570 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62833 | val 0.69173
  Epoch 011 - train 0.61770 | val 0.69202
  Classification -> best τ=0.605 (val F1=0.0589)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62676 | val 0.72667
  Epoch 014 - train 0.63469 | val 0.84295
  Classification -> best τ=0.375 (val F1=0.2892)
  Directional -> Accuracy: 0.5714, MCC: 0.2187, F1: 0.4783

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57982 | val 0.70916
  Epoch 015 - train 0.50260 | val 0.87252
  Classification -> best τ=0.480 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60234 | val 1.01578
  Epoch 016 - train 0.48884 | val 0.77700
  Classification -> best τ=0.640 (val F1=0.4067)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58327 | val 1.15309
  Epoch 013 - train 0.52585 | val 0.91296
  Classification -> best τ=0.460 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58442 | val 0.91945
  Epoch 012 - train 0.55536 | val 1.05251
  Classification -> best τ=0.515 (val F1=0.2034)
  Directional -> Accuracy: 0.4694, MCC: -0.1293, F1: 0.6061

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58179 | val 0.66052
  Epoch 014 - train 0.61097 | val 0.71293
  Classification -> best τ=0.345 (val F1=0.3366)
  Directional -> Accuracy: 0.5417, MCC: 0.1155, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60890 | val 0.97411
  Epoch 011 - train 0.60881 | val 1.34403
  Classification -> best τ=0.550 (val F1=0.1702)
  Directional -> Accuracy: 0.5581, MCC: 0.1140, F1: 0.5128

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66216 | val 0.75013
  Epoch 013 - train 0.69819 | val 0.75726
  Classification -> best τ=0.350 (val F1=0.3603)
  Directional -> Accuracy: 0.6212, MCC: 0.1990, F1: 0.7059

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57043 | val 1.15440
  Epoch 011 - train 0.53980 | val 1.00822
  Classification -> best τ=0.515 (val F1=0.3001)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58549 | val 0.81731
  Epoch 011 - train 0.56233 | val 0.83010
  Classification -> best τ=0.465 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0340, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46028 | val 1.51341
  Epoch 014 - train 0.44392 | val 1.76377
  Classification -> best τ=0.635 (val F1=0.2254)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53334 | val 0.63288
  Epoch 020 - train 0.46367 | val 0.63868
  Epoch 024 - train 0.42063 | val 0.74815
  Classification -> best τ=0.330 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64401 | val 0.66824
  Epoch 011 - train 0.64384 | val 0.72388
  Classification -> best τ=0.440 (val F1=0.4520)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53413 | val 0.75084
  Epoch 011 - train 0.55927 | val 0.74466
  Classification -> best τ=0.490 (val F1=0.3371)
  Directional -> Accuracy: 0.5778, MCC: 0.1540, F1: 0.6122

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57648 | val 0.58313
  Epoch 020 - train 0.50496 | val 0.71636
  Classification -> best τ=0.210 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54531 | val 0.64511
  Epoch 017 - train 0.48332 | val 0.68099
  Classification -> best τ=0.575 (val F1=0.3705)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59328 | val 0.71573
  Epoch 011 - train 0.62076 | val 0.70524
  Classification -> best τ=0.530 (val F1=0.2212)
  Directional -> Accuracy: 0.4909, MCC: -0.1617, F1: 0.6500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58611 | val 1.65601
  Epoch 011 - train 0.56684 | val 1.64296
  Classification -> best τ=0.575 (val F1=0.2837)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61665 | val 0.91212
  Epoch 012 - train 0.57001 | val 0.73141
  Classification -> best τ=0.560 (val F1=0.1126)
  Directional -> Accuracy: 0.5660, MCC: 0.1310, F1: 0.6102

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61823 | val 1.01074
  Epoch 012 - train 0.59945 | val 1.01434
  Classification -> best τ=0.490 (val F1=0.0644)
  Directional -> Accuracy: 0.4727, MCC: -0.0289, F1: 0.2927

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61943 | val 1.04953

[I 2026-02-20 06:35:29,946] Trial 249 finished with value: 0.25973245280347496 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.006162145577519279, 'weight_decay': 1.1667513125301168e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9856992608463133, 'early_stopping_min_delta': 0.0029542434737479515}. Best is trial 180 with value: 0.30107335520239253.

  Epoch 016 - train 0.53072 | val 0.72352
  Classification -> best τ=0.520 (val F1=0.2623)
  Directional -> Accuracy: 0.4667, MCC: -0.1437, F1: 0.1111

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25973245280347496
Saved Optuna results to results/benchmarking/classification/optuna_tuning_base_1H.csv